### ISSUE TITLE
Once I opend clipisht anywhere I click on waybar is cliphist input. OLD(Dolphine has no theme and swww not working)

### ISSUE THREAD

**Issue by haShinui** [prasanthrangan/hyprdots#10]
Hello
So 1 day dolphine just didnt have a theme anymore and I am pretty sure I can control dolphine theme over kvantum, whatever I do it does not work. I continue to try to get it to work but maybe you have an idea how exactly
![image](https://github.com/prasanthrangan/hyprdots/assets/67230963/4c6e6bde-0eff-48fc-9a8c-3de49554721e)
.
Edit: So some environment variables were disabled, but still the theme of dolphin is better then before, but still not the same. 
![image](https://github.com/prasanthrangan/hyprdots/assets/67230963/d1ebe792-ca20-47cc-9360-9a85b8528251)

**Comment by prasanthrangan** [comment]
Hi,

Few things you could check,
1. the main hyprland config has `~/.config/hypr/hyprland.conf` has `env = QT_QPA_PLATFORMTHEME,qt5ct `
2. the qt5ct config `~/.config/qt5ct/qt5ct.conf` has correct color scheme for your theme `color_scheme_path=~/.config/qt5ct/colors/Catppuccin-Mocha.conf`
3. the kvantum config directory should have these files (with correct file names) -
![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/5e5618cd-3abb-41cf-8aa3-2db59abd1c37)

once its there please try reapplying the theme from kvantum manager

**Comment by haShinui** [comment]
So the dolphine works now.
But I changed/ updated the swww wallpaper thing. I just copied the files and astructure and removed the old files. But now that I did I cant change the wallpaper, I am stuck with the default and when I try to change it the bottom half flickers with the new wallpaper for a second and then it returns to the hyprland. The color change is also a bit messed, because my firefox is in autmatic, but doesnt matter if I switch to light or dark theme with waybar, it is stuck in light theme and also the firfox colors are wierd.
I tried screen recording with obs, but after switching wallpaper and then switching color the system has a crash for about 2s and then brings me back to sddm login.
Also I think the system theme is light theme right now, because when I open the dolphin from firefoxm it is light theme but when I open dolphin from linux, so command it is dark theme. 
I dont know whats going on and I doubled checked if everything is right, I also redid the symlinks between files

**Comment by prasanthrangan** [comment]
for the wallpaper, whats the error while running `~/.config/swww/swwwallpaper.sh` from terminal?
also for theme/color change, please try running `~/.config/hypr/scripts/themeswitch.sh` and let me know if there are any errors.

The obs crash is most likely due to the `~/.config/hypr/hyprland.conf` file has monitor set to auto which will cause the themechange script to crash hyprland while recording and brings you back to sddm. So please set your monitor in the `hyprland.conf` file.

The `~/.config/hypr/scripts/resetxdgportal.sh` is just to ensure no other xdg portals are running, so please ignore the 
`killall xdg-desktop-portal-hyprland killall xdg-desktop-portal-gnome: no process found killall xdg-desktop-portal-kde: no process found killall xdg-desktop-portal-lxqt: no process found killall xdg-desktop-portal-wlr: no process found` error messages

**Comment by haShinui** [comment]
Hello so I fixed the swww, it was not you config but some kind of cache problem I found out by reading this [problem](https://bbs.archlinux.org/viewtopic.php?pid=2095946#p2095946).
But now I have another problem, that is rofi in general, its mainly styling issue that propraly occur because of the diffrent screen resolutions we have. But one really annoying one I am trying to fix is that when I click on cliphist in the right tray bar and it opens, once I close it with escape, anywhere where I click on the waybar area, it is a cliphist input, even middleclick. I am trying to fix it but maybe you have an Idea.

**Comment by haShinui** [comment]
Ok so I found out thanks to your know Issue at the bottom which i forgot that this I should use right instead of left click. I didnt try it yet but apparently I t can be fixed if you time it out for some second, like 10ms and then launch it, didnt try it yet but on it.

**Comment by haShinui** [comment]
Ok so adding `sleep 0.1 &&` to the right,middle and left click fixed it for me and and I will make a pull request so that user have the option to add this to their .conf of waybar. The delay is minimal and you can play around with the value, for me 0.1 was the lowest I could go, at 0.05 I just after the second time I clicked on the waybar it went back normally

**Comment by haShinui** [comment]
> ~/.config/swww/swwwallpaper.sh

Ok so I set the monitor a while a go and it still happnes, but its okay. Also swww is working, till the cache is full, and it fills really fast. I have 15000 lines and I just used waybar for 1 hour since last wipe. Also what applies the overall dark theme, when I run gtk settings its in light theme but theme is set to mocha. Do you have any idea where I can set all gtk to dark, I am trying but didnt find the way.

**Comment by prasanthrangan** [comment]
> Ok so adding `sleep 0.1 &&` to the right,middle and left click fixed it for me and and I will make a pull request so that user have the option to add this to their .conf of waybar. The delay is minimal and you can play around with the value, for me 0.1 was the lowest I could go, at 0.05 I just after the second time I clicked on the waybar it went back normally
> 
> Edit: I submitted a small pull request to give users the option to fix that problem if they have it. I will keep this open because I still have some rofi issue I am trying to fix. And I still get this I the termianl whenevere I click on cliphist `error in "decode": decoding: extracting id: input not prefixed with id `

Thank you! Let me try adding sleep to waybar cliphist and then merge your request.
Ya please ignore the `error in "decode": decoding: extracting id: input not prefixed with id` as its happens when you don't select any item from rofi menu list for `cliphist decode` to copy it.

**Comment by prasanthrangan** [comment]
> Ok so I set the monitor a while a go and it still happnes, but its okay. Also swww is working, till the cache is full, and it fills really fast. I have 15000 lines and I just used waybar for 1 hour since last wipe. Also what applies the overall dark theme, when I run gtk settings its in light theme but theme is set to mocha. Do you have any idea where I can set all gtk to dark, I am trying but didnt find the way.

You can apply theme to all gtk app using gtk settings (nwg-look) or from terminal using `gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-Mocha'`
you might also need to comment out the `exec = gsettings set org.gnome.desktop.interface gtk-theme` line from the hyprland config `~/.config/hypr/themes/theme.conf` so that the theme you have set does not change when you reload hyprland

**Comment by haShinui** [comment]
> > Ok so I set the monitor a while a go and it still happnes, but its okay. Also swww is working, till the cache is full, and it fills really fast. I have 15000 lines and I just used waybar for 1 hour since last wipe. Also what applies the overall dark theme, when I run gtk settings its in light theme but theme is set to mocha. Do you have any idea where I can set all gtk to dark, I am trying but didnt find the way.
> 
> You can apply theme to all gtk app using gtk settings (nwg-look) or from terminal using `gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-Mocha'` you might also need to comment out the `exec = gsettings set org.gnome.desktop.interface gtk-theme` line from the hyprland config `~/.config/hypr/themes/theme.conf` so that the theme you have set does not change when you reload hyprland

Hello so gtk was a bit messed u becuase mocha was a light theme and frappe was dark for some reason. But now it works.

**Comment by haShinui** [comment]
So I made a video on my phone of the wallpaper crash, I dont think you can help me much but still just to show and also that crash with obs just happens when I switch wallpapers, if I dont switch nothing happens. Also after the crash happens, I can open obs but cant select from which monitor to screen capture, so in short obs not working till I reboot. But as I said this issue doesnt affect me right now, maybe later when I wanna do a post on unixporn.

So the only important problem I have now is rofi, the one with the applauncher was here since I downloaded hyprland with your script about a month ago, but just didnt have time looking into it becuase was ricing. And I checked that all scripts are up do date that I use for rofi. As you can see it in the obs screen capture I made it works, besides the middle click color theme switching.
I know I can fix it myself and I am on it right now, its probably has mostly to do with scaling, the only thing I am unsure is the middle click color switching.

https://github.com/prasanthrangan/hyprdots/assets/67230963/42151351-1f93-4c99-b998-402a13b72781

Also quick question, all my gtk based application come with rounding now since I updated, like firfox (shown in snippet and also obs), do you know how to turn it off, I will look into it but maybe you have an idea.
![image](https://github.com/prasanthrangan/hyprdots/assets/67230963/a9f9726e-4968-4ba3-b553-bd80e2800e44)

**Comment by prasanthrangan** [comment]
> So the only important problem I have now is rofi, the one with the app-launcher was here since I downloaded hyprland with your script about a month ago, but just didnt have time looking into it because was ricing. And I checked that all scripts are up do date that I use for rofi. As you can see it in the obs screen capture I made it works, besides the middle click color theme switching.
> I know I can fix it myself and I am on it right now, its probably has mostly to do with scaling, the only thing I am unsure is the middle click color switching.

The issue is with rofi scaling, looks like your monitor resolution is lower than 1080p, so you'll have to adjust the rofi configs for your resolution.
For theme select (middle click) please adjust the icon size (line 89) in  `~/.config/rofi/themeselect.rasi` as per your resolution -

https://github.com/prasanthrangan/hyprdots/assets/106020512/e53bc491-0a32-424e-a499-6e02c42c9132

In theme select `echo -en "$thm\x00icon\x1f$ThumbDir/${thm}.png\n" ` is just to show an image as element icon in rofi from `~/.config/swww/Themes-Ctl`. here the icon/thumbnails can be refreshed by running  `./themeselect.sh T`


> Also quick question, all my gtk based application come with rounding now since I updated, like firfox (shown in snippet and also obs), do you know how to turn it off, I will look into it but maybe you have an idea.

The corners might be the issue with the gtk theme itself,  please try with a different theme.

**Comment by haShinui** [comment]
> > So the only important problem I have now is rofi, the one with the app-launcher was here since I downloaded hyprland with your script about a month ago, but just didnt have time looking into it because was ricing. And I checked that all scripts are up do date that I use for rofi. As you can see it in the obs screen capture I made it works, besides the middle click color theme switching.
> > I know I can fix it myself and I am on it right now, its probably has mostly to do with scaling, the only thing I am unsure is the middle click color switching.
> 
> The issue is with rofi scaling, looks like your monitor resolution is lower than 1080p, so you'll have to adjust the rofi configs for your resolution. For theme select (middle click) please adjust the icon size (line 89) in `~/.config/rofi/themeselect.rasi` as per your resolution -
> rofi_720p.mp4
> 
> In theme select `echo -en "$thm\x00icon\x1f$ThumbDir/${thm}.png\n" ` is just to show an image as element icon in rofi from `~/.config/swww/Themes-Ctl`. here the icon/thumbnails can be refreshed by running `./themeselect.sh T`
> 
> > Also quick question, all my gtk based application come with rounding now since I updated, like firefox (shown in snippet and also obs), do you know how to turn it off, I will look into it but maybe you have an idea.
> 
> The corners might be the issue with the gtk theme itself, please try with a different theme.

So understand this line `$thm\x00icon\x1f$ThumbDir/${thm}.png\n` better now. Because of chatgpt, but I have the problem that my monitor is a 3:2, because I am on laptop and its a framework laptop, would rather have 16:9 but yea. And what happens with 3:2 is that I dont have that much width.
So what I tried to do is to display the theme name on the top of the icon, but the problem is that  `$thm\n\x00icon\x1f$ThumbDir/${thm}.png\n` does not work because \n is the separator between the different groups so the icon and theme name get separated, is there any way my idea of name top and icon under it is possible, gonna keep trying.
Also when I did `  `$thm\n....` the list would go a new "page"  as you can see in the vid. Maybe I can use that, where I have 2 per page and I go right to see the rest, but I dont now how set that it shows the full theme name or how to set 2 elements per page. 
I would rather have the first solution with name on top, because it looks better in my opinion and I think I can figure out the second solution.

https://github.com/prasanthrangan/hyprdots/assets/67230963/0fcf6a49-b4ce-493c-8e87-f83c8cb47ff2

**Comment by haShinui** [comment]
> > So the only important problem I have now is rofi, the one with the app-launcher was here since I downloaded hyprland with your script about a month ago, but just didnt have time looking into it because was ricing. And I checked that all scripts are up do date that I use for rofi. As you can see it in the obs screen capture I made it works, besides the middle click color theme switching.
> > I know I can fix it myself and I am on it right now, its probably has mostly to do with scaling, the only thing I am unsure is the middle click color switching.
> 
> The issue is with rofi scaling, looks like your monitor resolution is lower than 1080p, so you'll have to adjust the rofi configs for your resolution. For theme select (middle click) please adjust the icon size (line 89) in `~/.config/rofi/themeselect.rasi` as per your resolution -
> rofi_720p.mp4
> 
> In theme select `echo -en "$thm\x00icon\x1f$ThumbDir/${thm}.png\n" ` is just to show an image as element icon in rofi from `~/.config/swww/Themes-Ctl`. here the icon/thumbnails can be refreshed by running `./themeselect.sh T`
> 
> > Also quick question, all my gtk based application come with rounding now since I updated, like firefox (shown in snippet and also obs), do you know how to turn it off, I will look into it but maybe you have an idea.
> 
> The corners might be the issue with the gtk theme itself, please try with a different theme.

So understand this line `$thm\x00icon\x1f$ThumbDir/${thm}.png\n` better now. Because of chatgpt, but I have the problem that my monitor is a 3:2, because I am on laptop and its a framework laptop, would rather have 16:9 but yea. And what happens with 3:2 is that I dont have that much width.
So what I tried to do is to display the theme name on the top of the icon, but the problem is that  `$thm\n\x00icon\x1f$ThumbDir/${thm}.png\n` does not work because \n is the separator between the different groups so the icon and theme name get separated, is there any way my idea of name top and icon under it is possible, gonna keep trying.
Also when I did `  `$thm\n....` the list would go a new "page"  as you can see in the vid. Maybe I can use that, where I have 2 per page and I go right to see the rest, but I dont now how set that it shows the full theme name or how to set 2 elements per page. 
I would rather have the first solution with name on top, because it looks better in my opinion and I think I can figure out the second solution.


https://github.com/prasanthrangan/hyprdots/assets/67230963/c0f44eed-5d04-4079-b41b-5a6c47bedfff

**Comment by prasanthrangan** [comment]
> is there any way my idea of name top and icon under it is possible

to change icon and name orientation, change the `element orientation` (line 56) to vertical.


> how set that it shows the full theme name or how to set 2 elements per page.
> I would rather have the first solution with name on top

you can adjust the number of column from `listview columns` (line 36) but not sure if its possible to set the name on top.
