### ISSUE TITLE
issue with gkt opacity

### ISSUE THREAD

**Issue by user12xxxxxx** [prasanthrangan/hyprdots#1008]
![240303_12h01m38s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111512589/dacb5f03-4ea3-4dda-aa19-78f21bad2a45)
![240302_20h36m59s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111512589/296541bd-3b02-4fe2-a53c-f56bedee107e)
so i applied the transparency but for some reason it only works for daughter window.
i also set it to float which also doesn't work

**Comment by kRHYME7** [comment]
How did you set up your windowsrule?

**Comment by user12xxxxxx** [comment]
> How did you set up your windowsrule?

![240303_14h40m16s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111512589/e6650f7a-aff3-415a-8ed4-1acc09e9938e)
![240303_14h39m56s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111512589/308ce87a-2212-4968-9a92-98dc06323bf4)

**Comment by user12xxxxxx** [comment]
i downloaded skride from aur (yay) and emote from flahub (id com.tomjwatson.Emote

**Comment by kRHYME7** [comment]
class for emote is ``` emote ```. Use ``` hyprctl clients ``` to know the class etc... 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/b8317715-1c08-4eed-a6c4-d85b87a1afaf)



![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/b4f3e5c4-be0d-4d4e-a397-e9660c37d689)




BTW we have some built in emoji here.  run  ``` Hyprdots show emoji ```

**Comment by user12xxxxxx** [comment]
that helped thanks (sorry for troubling should have read the documentation)
