### ISSUE TITLE
[Feature Request]: Add the community themes

### ISSUE THREAD

**Issue by enzzodani** [prasanthrangan/hyprdots#1014]
### Description
I've seen many interesting themes that still couldn't be applied by themepatching.sh, like an incredible one for MacOS and Windows 11. Therefore, it might be interesting to add them in the next update.

### Proposed Solution

Instead of having many branches across different repositories, it might be better for them to be merged and included in the next update of Hyprdots. Alternatively, themes that can't be used with themepatching.sh could be made usable.

### Additional Information

Repository that has MacOS and Windows 11 without themepatching: [https://github.com/T-Crypt/hyprdots/tree/MacOS-/-Windows](https://github.com/T-Crypt/hyprdots/tree/MacOS-/-Windows)

**Comment by kRHYME7** [comment]
It can't be patched because the theme lacks a qt6 configuration. You can raise the issue to the maintainer of the theme.

 Prasangth  decided not to include other themes as we have 10 default themes. And Themepatcher can patch extra themes.

IMO having those Themes makes this repository very heavy. You can also make a pull request to include the MacOS and Windows 11 in hyprdots-mods repo.


I am currently using Tcrypt's theme BTW. I am maintaining this locally. I can push a fork so someone can patch it.

**Comment by enzzodani** [comment]
Got it, I really wanted those themes lol, I support the idea of putting them in hyprdots-mods, anyway, I would love to have those themes lol. Do I just fork your repository?

**Comment by kRHYME7** [comment]
> those themes lol. Do I just fork your repository?

For now, this is in my local. I'll send you the link if I manage to put these together. You can use this until Tcrypt can update his themes soon.  I'll provide you the link soon. (Turtle net ). Just Ping me if I forget.

**Comment by kRHYME7** [comment]
@enzzodani  https://github.com/kRHYME7/Hyprdots-gallery

```
Hyprdots theme patch 'MacOS' 'https://github.com/kRHYME7/Hyprdots-gallery' 'davidbwaters.macos-modern-theme~MacOS Modern Dark - Xcode Modern'
```

```
Hyprdots theme patch 'Windows-11' 'https://github.com/kRHYME7/Hyprdots-gallery' 'extensioncreator.windows-11-color-theme~Windows 11 Dark'
```

**Comment by enzzodani** [comment]
Thanks man, you're freaking amazing

**Comment by rishav12s** [comment]
@kRHYME7 did you make the rain dark one ?

**Comment by kRHYME7** [comment]
Nope. Here's the discussion with the author

https://github.com/prasanthrangan/hyprdots/discussions/892
