### ISSUE TITLE
[Problem]: Mouse lag & Low fps Hyprland

### ISSUE THREAD

**Issue by maykel535** [prasanthrangan/hyprdots#1020]
I try the change variables of  acceleration, sensitivity but I feel lag, sometimes low fps and no precision ... but not resolved it.

**Comment by jenil1122** [comment]
Same Happens with me After new hyprland update.
i think its because i use Bluetooth mouse and Bluetooth headset together
the problems gets temporarily solved once i disconnect either one of the device

**Comment by maykel535** [comment]
It happens to me with the touchpad

**Comment by kRHYME7** [comment]
Can you provide output for this ``` Hyprdots systeminfo ```

**Comment by kRHYME7** [comment]
Can you try to install the hyprland-git for testing. 0.35 is a bit outdated and vaxry mentions about the latest commits might solve these issues.

**Comment by jenil1122** [comment]
Hyprland git version has more issues than Hyprland for me . I will Update my system  today and check if new Hyprland release is available..(Hyprland should be more stable than git version shouldn't it?)

**Comment by kRHYME7** [comment]
> Hyprland git version has more issues than Hyprland for me . I will Update my system today and check if new Hyprland release is available..(Hyprland should be more stable than git version shouldn't it?)

We are on arch though. Also, also git version might not be stable sometimes, but you can get the fix faster than waiting for the package manager to update. (BTW, arch repo for hyprland is outdated. 0.36.0 was released already, maybe week ago)

**Comment by maykel535** [comment]
No, hyprland not cause this issue.

I probe install arch from vanilla + hyprland by default and I try install garuda hyrpland, mouse works well. With this, I will move mouse smooth, precision very well...

It has to be anything of config of https://github.com/prasanthrangan/hyprdots

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/blob/cd168495ce5181d3b9a048dfdeaa079f3010e1f2/Configs/.config/hypr/hyprland.conf#L67C1-L91C2 

These are the lines that are config related, can you try to comment it out?

**Comment by maykel535** [comment]
Also, if disable hypr effects with Super + Alt + G , the mouse is most smootly

**Comment by kRHYME7** [comment]
Nice!  Please   try to add your configurations in the ./userprefs.conf to override it. (In case you want to  fetch from this repo)

example: 

```
input:touchpad:force_no_accel = 0
```


Then maybe you can try these persistent commands. (The game mode is a temporary   option)
 
``` Hyprdots power save  [--options] ``
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/9a4be429-c6d7-491e-8707-32a17c302fbc)

**Comment by maykel535** [comment]
The config in userprefs.conf may be these:

input {force_no_accel = 0}

with this one I get an error:

input:touchpad:force_no_accel = 0

Thx

**Comment by maykel535** [comment]
Yes, it works with that config. Thanks

**Comment by maykel535** [comment]
For anyone ... I disabled the blur on the themes, it was causing low fps in general (include move mouse)

Now, the effects is very smooth! And it goes more fluid

**Comment by rubiin** [comment]
I think this can be closed
