### ISSUE TITLE
[Bug]: options in the context menu are not displayed correctly

### ISSUE THREAD

**Issue by DiegoSof2** [prasanthrangan/hyprdots#1029]
##description

After the last system update, the context menu has the problem of not displaying options within options

### Expected behavior

it should open correctly display the options
### Current Behavior
  the options appear empty as shown in the screenshot, if I go through all the context menus the problem disappears and returns to work for a specified period of time

### Screenshots

![20240306_223005.jpg](https://github.com/prasanthrangan/hyprdots/assets/105827698/1cdbefbc-bca8-45a6-ace2-1a9b125d3606)

![20240306_224801.jpg](https://github.com/prasanthrangan/hyprdots/assets/105827698/82ae3d85-a07b-43ff-b283-8a57443b7f88)

#

for example.,

- Linux distribution: arch Linux 6.7.8- arch 1-1
- Hyprland version: v0. 35.0
  - laptop with ryzen 7 and amd gpu
- Other information: 1920x 1080 resolution

###Additional Information
  in my last
update was requested to exchange 3 packages

-baloon5
-kuserfeedback
-libblockdev-utils

**Comment by kRHYME7** [comment]
What happened if you revert the package? (dolphin right ?)

**Comment by DiegoSof2** [comment]
> ~What happened if you revert the package? (dolphin right ?)~ I see it's arch.

Yes, it's dolphin, the package that I believe is causing the problem to occur is baloo but I can't revert it because the baloo 5 that was previously installed does not exist in the archlinux repository

**Comment by kRHYME7** [comment]
@DiegoSof2  Okii Let's see what we can do about it. Major DE is releases might hurt our setup.
We are in a middle of transition, it would be rough.

**Comment by DiegoSof2** [comment]
> @DiegoSof2 Okii Let's see what we can do about it. Major DE is releases might hurt our setup. We are in a middle of transition, it would be rough.

I think I'll try another file manager, dolphin hasn't really pleased me, do you know of any others that work well in hyprland?

**Comment by kRHYME7** [comment]
Thunar is great

**Comment by DiegoSof2** [comment]
> Thunar is great

I really liked the thunar, the only problem is that it is not transparent like the dolphin

**Comment by RookiexCookie** [comment]
you can add the transparency effect for thunar in the windows rule tho

**Comment by kRHYME7** [comment]
> I really liked the thunar, the only problem is that it is not transparent like the dolphin

😁 My first loved File manager when I first try linux. 

Add this line 
```
windowrulev2 = opacity 0.80 0.80,class:^(thunar)$
```
in your ./userprefs.conf


![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/961d6619-3be6-4290-bfce-76c679beac2e)

**Comment by DiegoSof2** [comment]
> windowrulev2 = opacity 0.80 0.80,class:^(thunar)$

Thank you very much, it was perfect

**Comment by abenezerw** [comment]
@DiegoSof2 would you mind closing this if it worked for you.
