### ISSUE TITLE
[Bug]: doplhin not themed

### ISSUE THREAD

**Issue by itsmenewbie03** [prasanthrangan/hyprdots#1030]
### Description

After the latest system update, for some reasons dolphin is now on _"hurt your eyes"_ mode (light mode).

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/89230263/5b7bc339-20ae-40f5-972a-febf49f4da4d)

**Comment by kRHYME7** [comment]
What happens if you disable wallbash ?

**Comment by jasonKoogler** [comment]
having same issue here.  wallbash disabled produces same effect.

**Comment by kRHYME7** [comment]
I see, got this issue after updating today.

**Comment by hoodust** [comment]
Same. Wasn't able to use downgrade either, I think because of the silly user feedback addition?
```
warning: cannot resolve "kuserfeedback5", a dependency of "dolphin"
```

**Comment by RandomLegend** [comment]
Garuda-Hyprland user here - I've got the same problem.

Issue is, i'd like to not update my dotfiles from here as i've heavily customized it to my liking and i don't want to overwrite stuff

**Comment by kRHYME7** [comment]
Hmmm I think this is a qt or KDE thing because it happened after an update.  Let's Just wait for a while when things are settled.

**Comment by kRHYME7** [comment]
I am now testing the wallbash-v3 of Hyprdots, and I also got these issues. I'll try to ping Tittu regarding this.

**Comment by Xeo23** [comment]
> yup can confirm it's the issue with my setup too, few of the things aren't getting customized as usual
> 
> password picker:- ![image](https://private-user-images.githubusercontent.com/94917588/310839170-611b6993-900c-43fc-8e0a-ed783dceeab0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTE0MzEsIm5iZiI6MTcwOTgxMTEzMSwicGF0aCI6Ii85NDkxNzU4OC8zMTA4MzkxNzAtNjExYjY5OTMtOTAwYy00M2ZjLThlMGEtZWQ3ODNkY2VlYWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDExMzIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYTgxZDdkMzM2YWMzMDZmZWFlZGVjNjRiNDI5Nzg1YmM5NjNlYmRhM2U4Zjc1NDBhYmZjZmQwYjM2NmI2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r_MRwp7P66ty-FcDQG4zeYr9v_3dnFWgwHTSEUk_u34)
> 
> few apps like KDE connect ![image](https://private-user-images.githubusercontent.com/94917588/310839365-50be78e4-6a7a-4bf0-b923-737eb22e134d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTE0MzEsIm5iZiI6MTcwOTgxMTEzMSwicGF0aCI6Ii85NDkxNzU4OC8zMTA4MzkzNjUtNTBiZTc4ZTQtNmE3YS00YmYwLWI5MjMtNzM3ZWIyMmUxMzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDExMzIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNzE5YWQ3NDBkOTkzZjUwMjliZjYwODNkODQ4NzkxMzc1YTRhZWU4NzBlMWM4ODBjY2UxYjFmNmJiZWQ1NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vL7FMuFEq-IOb7kQjIw9-FniWpBed9xT5-Ze9Qor-BY)
> 
> seems like an upstream issue..

Yeah having the same issue with password prompt and kde connect.

**Comment by Gravyon** [comment]
Same here. I was able to go back before the upgrade using timeshift. I'll wait for a fix in the meantime.

**Comment by Bryan-Campuzano** [comment]
i have the same issue and partially fixed, in the hyprland.conf uncomment this line "env = QT_STYLE_OVERRIDE,kvantum
" and return the colors and bars BUT, don't see the icons, i don't khow what happen, now this is looks like 
![imagen](https://github.com/prasanthrangan/hyprdots/assets/105027477/5a1f76eb-3bdf-4671-a34e-e23367d5078c)

**Comment by hoodust** [comment]
> i have the same issue and partially fixed, in the hyprland.conf uncomment this line "env = QT_STYLE_OVERRIDE,kvantum " and return the colors and bars BUT, don't see the icons, i don't khow what happen, now this is looks like

Thanks! I did this for now but I actually have icons, just the crummy ones?? Still preferable to that default theme.

![image](https://github.com/prasanthrangan/hyprdots/assets/69404732/575ec791-ddfb-4063-8d09-960f78c9f372)

**Comment by Bryan-Campuzano** [comment]
> > i have the same issue and partially fixed, in the hyprland.conf uncomment this line "env = QT_STYLE_OVERRIDE,kvantum " and return the colors and bars BUT, don't see the icons, i don't khow what happen, now this is looks like
> 
> Thanks! I did this for now but I actually have icons, just the crummy ones?? Still preferable to that default theme.
> 
> ![image](https://private-user-images.githubusercontent.com/69404732/311008811-575ec791-ddfb-4063-8d09-960f78c9f372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDIxMzQsIm5iZiI6MTcwOTg0MTgzNCwicGF0aCI6Ii82OTQwNDczMi8zMTEwMDg4MTEtNTc1ZWM3OTEtZGRmYi00MDYzLThkMDktOTYwZjc4YzlmMzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIwMDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NjRhNzExYTVlZDNlODc5ZjBiN2QwOWM4YWRmYWUyZjhmZmM0ZmFhNjk1MjQxZjQyMmJmZDdiNGY3ODk1MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9t_SlUSpAH4BABQoeGghC1oJ5c2l-6u5iow8gw5gkAE)

you lucky one gg, i still have the icon problem, T-T

**Comment by hoodust** [comment]
Got the fix for this from hyprland's own Vaxry on their discord server. To quote:

- install kvantum
- install qt6ct-git (git has some patches)
- remove one line from your qt6ct.conf I forgot which but it has @Invalid() and is not stylesheets or ignored_applications
- QT_QPA_PLATFORMTHEME=qt6ct (env var in hprland.conf)
- restart

I already had kvantum, and I had no qt6ct.conf or even its directory, so I just copied everything from ~/.config/qt5ct/ and renamed the new folder and .conf file qt6ct and it worked like a charm. I did not have any other @Invalid() lines so didn't end up needing to edit the conf.

(Also don't forget to comment out `env = QT_STYLE_OVERRIDE,kvantum` if you tried the workaround above).

**Comment by hoodust** [comment]
Oh and this method breaks icon switching with themes because of the new .conf file, lol. But you can just edit `~/.config/hypr/scripts/themeswitch.sh` and add the second (qt6ct) section below:

```
# qt5ct
sed -i "/^color_scheme_path=/c\color_scheme_path=$ConfDir/qt5ct/colors/${ThemeSet}.conf" $ConfDir/qt5ct/qt5ct.conf
IconSet=`awk -F "'" '$0 ~ /gsettings set org.gnome.desktop.interface icon-theme/{print $2}' $ConfDir/hypr/themes/${ThemeSet}.conf`
sed -i "/^icon_theme=/c\icon_theme=${IconSet}" $ConfDir/qt5ct/qt5ct.conf

# qt6ct
sed -i "/^color_scheme_path=/c\color_scheme_path=$ConfDir/qt6ct/colors/${ThemeSet}.conf" $ConfDir/qt6ct/qt6ct.conf
IconSet=`awk -F "'" '$0 ~ /gsettings set org.gnome.desktop.interface icon-theme/{print $2}' $ConfDir/hypr/themes/${ThemeSet}.conf`
sed -i "/^icon_theme=/c\icon_theme=${IconSet}" $ConfDir/qt6ct/qt6ct.conf
```

**Comment by hoodust** [comment]
Two issues I've noticed with this new dolphin that I can't find "fixes" for:

- Copy/move progress windows launch in a tileable window (with blank space around it) instead of a floating window. I think these used to fall under `windowrulev2 = float,class:^(qt5ct)$` in `windowrules.conf` but making a qt6ct version doesn't work. You can add `windowrulev2 = float,class:^(org.kde.dolphin)$` to fix it, but of course your dolphin will float (heh) every time you launch it also (i.e. the main window too).
- Large file transfers seem to hang the main dolphin window.

Hoping they fix things upstream, because I can't figure out how to downgrade :D

**Comment by kRHYME7** [comment]
I dont have much issues on my dolphin except that the "open with is blank"

**Comment by hoodust** [comment]
> I don't have many issues on my dolphin, except that the "open with" is blank.
> 
> The copy/move seems okay on my end.

How weird, on mine the "open with" menu looks and works perfectly.

**Comment by Enigma1309** [comment]
for me dolphin isn't having any issues whatsoever it maybe because i've kde-plasma installed in my system, the only issue i have is with the password picker, and a few other apps not getting themed properly.

**Comment by kRHYME7** [comment]
One more thing,  is you kde polkit fine? 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a100c65e-e9d8-4765-8fff-329b9f07fbfe)

**Comment by Enigma1309** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/312bb1b9-c934-474e-9177-65ac692b15c5)
what does that output mean?

**Comment by Bryan-Campuzano** [comment]
> Oh and this method breaks icon switching with themes because of the new .conf file, lol. But you can just edit `~/.config/hypr/scripts/themeswitch.sh` and add the second (qt6ct) section below:
> 
> ```
> # qt5ct
> sed -i "/^color_scheme_path=/c\color_scheme_path=$ConfDir/qt5ct/colors/${ThemeSet}.conf" $ConfDir/qt5ct/qt5ct.conf
> IconSet=`awk -F "'" '$0 ~ /gsettings set org.gnome.desktop.interface icon-theme/{print $2}' $ConfDir/hypr/themes/${ThemeSet}.conf`
> sed -i "/^icon_theme=/c\icon_theme=${IconSet}" $ConfDir/qt5ct/qt5ct.conf
> 
> # qt6ct
> sed -i "/^color_scheme_path=/c\color_scheme_path=$ConfDir/qt6ct/colors/${ThemeSet}.conf" $ConfDir/qt6ct/qt6ct.conf
> IconSet=`awk -F "'" '$0 ~ /gsettings set org.gnome.desktop.interface icon-theme/{print $2}' $ConfDir/hypr/themes/${ThemeSet}.conf`
> sed -i "/^icon_theme=/c\icon_theme=${IconSet}" $ConfDir/qt6ct/qt6ct.conf
> ```

tnk u so much, before this all dolphin works fine.

**Comment by boudywho** [comment]
> I don't have many issues on my dolphin, except that the "open with" is blank.
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/311611059-0dc82265-bfaa-4b76-a7dc-9610fab3c574.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDEzMDAsIm5iZiI6MTcxMDQwMTAwMCwicGF0aCI6Ii81MzQxNzQ0My8zMTE2MTEwNTktMGRjODIyNjUtYmZhYS00Yjc2LWE3ZGMtOTYxMGZhYjNjNTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA3MjMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MWNmNjc0Mzg2MmMwMGQxNDg0YmRjOGZkMWRmN2NkOWQ5YzgwNjlkZDExMWM0ZWI4MGFiZmI1ODYyZGMwZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zFvvCTnqYXY3FbeiclVUZ6CmAdRIaTrWbq6kQmnxQ2M)
> 
> The copy/move seems okay on my end.

@kRHYME7 you need to install these `kservice5 kdbusaddons5 kfilemetadata5 kconfig5 kcoreaddons5 kcrash5 kguiaddons5 ki18n5 kitemviews5 kwidgetsaddons5 kwindowsystem5kservice5`, I had the same issue, now it's working fine

**Comment by nicolkrit999** [comment]
I have the same problem in my desktop pc but not in my laptop. And I make sure they are exactly the same, meaning updating at the same time, same applications, same themese etc. If someone know what configurations could have caused this (automatically without me knowing, for example in an update) I can send you one from the desktop and one from the laptop so you can compare

**Comment by mahaveergurjar** [comment]
How to fix the polkit-kde theme break 
@kRHYME7 
![240320_22h28m40s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/627ab12c-d7c0-4c11-90a8-99b209396a70)

**Comment by kRHYME7** [comment]
@itsmenewbie03  Does the latest commit fix the issue?



@mahaveergurjar  Dunno really, I'm waiting for someone to provide a fix 😅

**Comment by mahaveergurjar** [comment]
Ok 😅

**Comment by DeividReinkeSchiitz** [comment]
Dolphin seems to use qt6ct now. The best approach is to reinstall the script ./hyprdots/Scripts/install.sh.
If you are not seeing any folder, just install qt6ct.

**Comment by kreutzi** [comment]
if you install kvantum-qt6-git and changes qt6 settings style to kvantum it fixes dolphin

**Comment by AzanAdnan23** [comment]
> if you install kvantum-qt6-git and change qt6 settings style to kvantum it fixes dolphin

how to do that?

**Comment by nicolkrit999** [comment]
> > if you install kvantum-qt6-git and change qt6 settings style to kvantum it fixes dolphin
> 
> 
> 
> how to do that?

This is not enough. 

If you look at the current hyprland.conf you can find something like QT_OVERRIDE you need to change that and also replace the current kvantum you have with the qt6

If you use yay you can do yay -S kvantum-qt6-git

It will prompt for a conflict and just tell yes 

The easiest way is to git pull the repo and run again./install.sh and then do hyprdots cache rebuild 

Beware this will change your hyprland.conf so if you made changes there copy them somewhere. There is also a directory when old the file is moved while rebuilding but I don't remember which one

**Comment by mahaveergurjar** [comment]
I try not work on  polkit-kde

**Comment by BentleyOph** [comment]
SO what fix works?Tried all these and it seems i broke my polkit and now i need a fix for that too

**Comment by kRHYME7** [comment]
>  broke my polkit 

Well no fix for polkit for now

**Comment by kellianb** [comment]
> SO what fix works?Tried all these and it seems i broke my polkit and now i need a fix for that too

I just pulled the latest version of hyprdots and reran the install script.

**Comment by itsmenewbie03** [comment]
I ran 
```shell
git clone --depth 1 https://github.com/prasanthrangan/hyprdots ~/Hyprdots
./install.sh
```
but dolphin seems to be **sick** again xD
![image](https://github.com/prasanthrangan/hyprdots/assets/89230263/28a9fe30-0120-4c0b-9571-a078d1a4d10d)

**Comment by hoodust** [comment]
Yay, qt6ct-git workaround no longer needed! I didn't need to re-pull hyprdots, just switch back to qt6ct. Guessing this was due to the upstream fix we've been waiting for. Also fixes file transfer progress windows opening non-floating for me.

**Comment by Enigma1309** [comment]
pol-kit still doesn't seem to theme well
