### ISSUE TITLE
[Question] How to remove blur behind waybar? 

### ISSUE THREAD

**Issue by WorldTeacher** [prasanthrangan/hyprdots#1040]
I recently found this repo and am planning to use it as my baseline for hyprland. I have already created a waybar setup I want to use, but don't like the blur added below the waybar.
I replaced the waybar folder with mine and restarted waybar, but noticed the blur beneath the bar. 
 Is there a way to remove it?

**Comment by WorldTeacher** [comment]
![IMG_20240309_082721.jpg](https://github.com/prasanthrangan/hyprdots/assets/41587052/acf63386-d2d0-461a-8cfd-f903d81621b2)

Image as example

**Comment by kRHYME7** [comment]
https://wiki.hyprland.org/Configuring/Window-Rules/#rules

```
# layerrule = unset, waybar
```
