### ISSUE TITLE
[Bug]: cant mount partition

### ISSUE THREAD

**Issue by user12xxxxxx** [prasanthrangan/hyprdots#1050]
![240310_12h24m41s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111512589/164767c4-6196-464a-a17f-caf0992fa335)

i cannot mount other partition of my disk

- Linux Distro: [ EndeavourOS]
- Linux Version
  Linux hp14 6.7.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000 x86_64 GNU/Linux   

- Hyprland Version
  Hyprland, built from branch main at commit f8a081b56d09ec325ac485a0f055e541146486d3 dirty (layout: warp the cursor when focusing windows (4982)).
Date: Tue Mar 5 23:26:06 2024
Tag: v0.36.0-53-gf8a081b5

- Installation Environment: [On The Main Hardware]

**Comment by kRHYME7** [comment]
Can you mount it on the terminal ?

**Comment by user12xxxxxx** [comment]
`/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1` 
running it in terminal gives nothing
should i remove kde-polkit? (sorry if its a silly question)

**Comment by user12xxxxxx** [comment]
> `/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1` running it in terminal gives nothing should i remove kde-polkit? (sorry if its a silly question)

_
![Uploading 240310_13h00m11s_screenshot.png…]()
_

**Comment by kRHYME7** [comment]
Normally, it gives nothing because it should run in the background ( a service /  daemon). That is why It is run on as auto start

**Comment by user12xxxxxx** [comment]
so i added the line `exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1`
![240310_13h44m43s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111512589/de923c13-d6a7-4fef-ada3-cbf6bb1cb229)
restarted, but still no luck
![240310_13h44m54s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111512589/e647242a-4c78-4de4-8bde-fa6c7af4d6d8)

**Comment by user12xxxxxx** [comment]
yes i can mount my partition through terminal
`polkit.service - Authorization Manager
     Loaded: loaded (/usr/lib/systemd/system/polkit.service; static)
     Active: active (running) since Sun 2024-03-10 13:56:41 IST; 1h 37min ago
       Docs: man:polkit(8)
   Main PID: 798 (polkitd)
      Tasks: 4 (limit: 8686)
     Memory: 5.9M (peak: 7.8M)
        CPU: 2.261s
     CGroup: /system.slice/polkit.service
             └─798 /usr/lib/polkit-1/polkitd --no-debug

polkit.service - Authorization Manager
     Loaded: loaded (/usr/lib/systemd/system/polkit.service; static)
     Active: active (running) since Sun 2024-03-10 13:56:41 IST; 1h 37min ago
       Docs: man:polkit(8)
   Main PID: 798 (polkitd)
      Tasks: 4 (limit: 8686)
     Memory: 5.9M (peak: 7.8M)
        CPU: 2.261s
     CGroup: /system.slice/polkit.service
             └─798 /usr/lib/polkit-1/polkitd --no-debug

Mar 10 15:21:59 hp14 polkitd[798]: Registered Authentication Agent for unix-process:9188:513374 (system bus name :1.78 [flatpak remote-ls --updates], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_IN)
Mar 10 15:21:59 hp14 polkitd[798]: Unregistered Authentication Agent for unix-process:9188:513374 (system bus name :1.78, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_IN)
Mar 10 15:23:10 hp14 polkitd[798]: Registered Authentication Agent for unix-process:12802:520477 (system bus name :1.86 [flatpak remote-ls --updates], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_IN)
Mar 10 15:23:19 hp14 polkitd[798]: Unregistered Authentication Agent for unix-process:12802:520477 (system bus name :1.86, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_IN)
Mar 10 15:24:18 hp14 polkitd[798]: Registered Authentication Agent for unix-process:15242:527256 (system bus name :1.87 [flatpak --user override --env=GTK_THEME=Cyberpunk-Edge], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_IN)
Mar 10 15:24:18 hp14 polkitd[798]: Unregistered Authentication Agent for unix-process:15242:527256 (system bus name :1.87, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_IN)
Mar 10 15:24:18 hp14 polkitd[798]: Registered Authentication Agent for unix-process:15267:527265 (system bus name :1.88 [flatpak --user override --env=ICON_THEME=Tela-circle-yellow], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_IN)
Mar 10 15:24:18 hp14 polkitd[798]: Unregistered Authentication Agent for unix-process:15267:527265 (system bus name :1.88, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_IN)
Mar 10 15:24:21 hp14 polkitd[798]: Registered Authentication Agent for unix-process:16857:527572 (system bus name :1.92 [flatpak remote-ls --updates], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_IN)
Mar 10 15:24:23 hp14 polkitd[798]: Unregistered Authentication Agent for unix-process:16857:527572 (system bus name :1.92, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_IN)
`

**Comment by kRHYME7** [comment]
what happens if you run ``` pkexec ``` on terminal? 

In my case I will get a dialog like this 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a08a3c53-385c-47da-9c53-5427e85df7d5)

**Comment by user12xxxxxx** [comment]
I was applying the fixes for #1030 and when i rebooted it was fixed
thanks for bearing with me

**Comment by BentleyOph** [comment]
> I was applying the fixes for #1030 and when i rebooted it was fixed thanks for bearing with me

Which fix worked for you?

**Comment by BentleyOph** [comment]
> so i added the line `exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1` ![240310_13h44m43s_screenshot](https://private-user-images.githubusercontent.com/111512589/311494776-de923c13-d6a7-4fef-ada3-cbf6bb1cb229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjA0OTksIm5iZiI6MTcxMjgyMDE5OSwicGF0aCI6Ii8xMTE1MTI1ODkvMzExNDk0Nzc2LWRlOTIzYzEzLWQ2YTctNGZlZi1hZGEzLWNiZjZiYjFjYjIyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwNzIzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmQwZDI0YTUyZmU1NmU5N2I0ZDNhODUwYzg5ZjQ4OTA3MWQ3OTZiNWRlYmIxYjM2YjY1YzllYWE3Y2Q3OTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VvK20jJR5xbsgEIW2UEsNjaA7fu7suZcN1GpvbKF2Rc) restarted, but still no luck ![240310_13h44m54s_screenshot](https://private-user-images.githubusercontent.com/111512589/311494812-e647242a-4c78-4de4-8bde-fa6c7af4d6d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjA0OTksIm5iZiI6MTcxMjgyMDE5OSwicGF0aCI6Ii8xMTE1MTI1ODkvMzExNDk0ODEyLWU2NDcyNDJhLTRjNzgtNGRlNC04YmRlLWZhNmM3YWY0ZDZkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwNzIzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjdkMDQ3YjZkZmEzNTljMzc2NzRmNjQxNGQyNDY3MjMyODljZWFmOTU2YzNlZjU0Mzc5NjRhMWRlNzgxNzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.krwUZ0xB6ICgL-OMKIUAUWhPVJzodlSSyHw0yhdK0Cs)
Just a question ....what's that file navigator in first screenshot?
