### ISSUE TITLE
[Bug]: Wallbash color bug in themes.conf ;  https://github.com/prasanthrangan/hyprdots/discussions/1051

### ISSUE THREAD

**Issue by H1manshu-Soni** [prasanthrangan/hyprdots#1052]
### Description

Pulled the latest changes and installed using the script install.sh and now wallbash refuses to work.

### Steps to Reproduce

1. install latest changes
2. enable wallbash
3. experience errors

### Expected Behavior

nice colors?

### Actual Behavior

bug and red bars from hyprland because of error.

### Screenshots

![240310_13h17m41s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/84933847/986f1812-0172-47a5-9cb0-61305267cef0)

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/discussions/1051

please run ``` Hyprdots cache rebuild ```

**Comment by kRHYME7** [comment]
Most changes do not need to rebuild the cache. This one needs to.
