### ISSUE TITLE
READ Me 🤚 [ BREAKING CHANGES ]  Hyprdots update 

### ISSUE THREAD

**Issue by kRHYME7** [prasanthrangan/hyprdots#1053]
# For those who want to pull the latest commit: 

> This is not a full fledge DE so transitioning from updates is rough and needs users ability to handle there own files without mindlessly re/moving it. I advice  A full fresh install of configs. 😉

###  1. Please back up all your configurations!  

> [!Caution]
>  Backup your configurations so you can manually restore some configs back

``` Hyprdots backup all ``` 

### 2.  Pull the updates from the repository
```
git pull 
 ``` 

>  [!Important]
> I adviced to fully pull the changes 
> Please Handle some merge errors yourself it's easy 
>  For those having a fork you know what you are doing, so you can merge and restore it through your fork. 

NOTE: A fresh installation is better 

### 2.  Restore the configuration

> [!Important]
> Please be aware that the -r restore flag is to restore configuration from the github repo to your $HOME. It is not use to preserve/retain your dots. 

Note: you can modify the files to not be overwritten using  by editing the ```   ./restore_cfg.lst ``` 

>if the 1st field of the list is " Y " the config will be overwritten 
>  if the 2nd field  of the list is "N" this means the file wont be backed up

The default list is okay, and you have the backup already from step 1. 

```
./install.sh -r 
```

or 

Interactive command : 
```
Hyprdots restore defaults 
```

### 3. Be sure to rebuild the wallpapers

> [!Caution]
> Before doing this be sure to have atleast 6Gb of free storage (wallpapers are not included ) as the caching process will take a significant amount of Storage data!  ( Do not worry it is freed once the installation is done )

```
Hyprdots cache rebuild
```

or 

```
./create_cache.sh -f                      # force create thumbnails (delete old cache)
```

# Must Do

> [!Caution]
> +Please remove older ``` ~/.config/hypr/scripts ``` and ``` ~/.config/hypr/wallbash ``` 
as both are moved to ``` ~/.config/hyprdots ```.
> + Be sure the $ScrPath variable is adjusted into ``` ~/.config/hyprdots/scripts ``` inside your ./keybindings.conf

**Comment by se7en-x230** [comment]
alias hypup="Hyprdots backup all ; Hyprdots update ; Hyprdots restore config"
 
 should take care of everything correct?

**Comment by kRHYME7** [comment]
Hey, don't do that the scripts are moved to ``` ./.config/hyprdots/scripts ```

## Do not forget to back up 

``` Hyprdots back up all ```



### So you must have to modify your configuration list. 

Here is my preferred ``` ~/.config/hyprdots-ctl/manage_cfg.lst ``` ( modify this first) 


```
S|${HOME}/.config|dunst|dunst
S|${HOME}/.config|fish|fish
S|${HOME}/.config/hypr|animations.conf|hyprland
S|${HOME}/.config/hypr|hyprland.conf|hyprland
S|${HOME}/.config/hypr|windowrules.conf|hyprland
S|${HOME}/.config/hypr|themes|hyprland
S|${HOME}/.config/hypr|monitors.conf|hyprland
S|${HOME}/.config/hyprdots|scripts|hyprland
S|${HOME}/.config/hyprdots|wallbash|hyprland
S|${HOME}/.config|kitty|kitty
S|${HOME}/.config|Kvantum|kvantum
S|${HOME}/.config|lsd|lsd
S|${HOME}/.config|MangoHud|mangohud
S|${HOME}/.config|neofetch|neofetch
S|${HOME}/.config|qt5ct|qt5ct
S|${HOME}/.config|qt6ct|qt6ct
S|${HOME}/.config|rofi|rofi
S|${HOME}/.config|swaylock|swaylock-effects
S|${HOME}/.config|swww|swww
S|${HOME}/.config/waybar|modules|waybar
S|${HOME}/.config/waybar|style.css|waybar
S|${HOME}/.config/waybar|config.jsonc|waybar
S|${HOME}/.config/waybar|themes|waybar
S|${HOME}/.config|wlogout|wlogout
S|${HOME}/.config|xsettingsd|nwg-look
S|${HOME}/.config|nwg-look|nwg-look
S|${HOME}/.config|gtk-3.0|nwg-look
S|${HOME}/.icons|default|nwg-look
S|${HOME}|.gtkrc-2.0|nwg-look
S|${HOME}/.config|kdeglobals|dolphin
S|${HOME}/.local/share|dolphin|dolphin
S|${HOME}/.local/share/kxmlgui5|dolphin|dolphin

P|${HOME}/.config|dolphinrc|dolphin
P|${HOME}/.config/waybar|config.ctl|waybar
P|${HOME}/.config/hyprdots|theme.ctl|hyprland
P|${HOME}/.config/hypr|userprefs.conf|hyprland
P|${HOME}/.config/hypr|keybindings.conf|hyprland
P|${HOME}/.config/hypr|nvidia.conf|hyprland nvidia-utils
P|${HOME}|.zshrc|zsh oh-my-zsh-git zsh-theme-powerlevel10k pokemon-colorscripts-git
P|${HOME}|.p10k.zsh|zsh oh-my-zsh-git zsh-theme-powerlevel10k pokemon-colorscripts-git
P|${HOME}/.config/Code/User|settings.json|visual-studio-code-bin

```


If you want to use this 
```
alias hypup="Hyprdots backup all ; Hyprdots update ; Hyprdots restore config"
```

instead of ``` Hyprdots restore config ``` use ``` Hyprdots updgrade ``` 


> [!Note]
> Do not forget to run ``` Hyprdots cache rebuild ```.  We needed to rebuild the cache for wallpaper.

**Comment by Enigma1309** [comment]
I've updated the dot's (did a clean install actually) but my systray icons aren't visible after changing the theme, or even relaunching waybar,

running blueman-try shows this 

![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/e6e49118-f04b-4293-be56-05cff8b49359)

and the cpu usage skyrockets

![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/e98a46f5-4a0e-4020-8ea7-e0277e4bfdc9)

**Comment by kRHYME7** [comment]
> I've updated the dot's (did a clean install actually) but my systray icons aren't visible after changing the theme, or even relaunching waybar,

>running blueman-try shows this

Strange, is it just bluemand-tray ?

**Comment by Enigma1309** [comment]
nah every icon is not visible, it can be recreated by just triggering, wallbash script on/off 
recording:-

https://github.com/prasanthrangan/hyprdots/assets/94917588/3277229a-315f-4127-a01c-a67b80ea3a27

blueman tray cpu usage can be seen in the recording i guess
here is a screenshot
![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/105c44d1-7278-4331-8c52-d060cdf2932e)

**Comment by Enigma1309** [comment]
i see it's an upstream issue got a recent issue about this on blueman repo https://github.com/blueman-project/blueman/issues/2282

**Comment by Enigma1309** [comment]
what i did was to remove my all cache (run `pc` in terminal it's an alias). and reinstalled blueman.
thought the problem is fixed mostly but still sometimes waybar don't launch or takes a lot of time to launch at startup.

**Comment by kRHYME7** [comment]
Someone interested in something like this? Might be useful for some announcements. 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/238de708-41ac-4582-aef1-b9372e91887e)

**Comment by Enigma1309** [comment]
Yup would be an great enhancement

**Comment by yaikohi** [comment]
What is the `Hyprdots` executable? I don't seem to have it (or am I misunderstanding something). Where can I find it?

I am geting the classic
> "zsh: command not found: Hyprdots"

**Comment by kRHYME7** [comment]
https://aur.archlinux.org/packages/hyprdots-ctl

**Comment by som-num** [comment]
I followed all the instructions but it doesn't output the wallpaper I also rebuild it
![image](https://github.com/prasanthrangan/hyprdots/assets/78010819/2d6408ab-3b95-488a-84a1-e5866aecd466)

**Comment by kRHYME7** [comment]
Ow  it's the swww version.

Try to run ``` swww init ``` on the terminal

**Comment by som-num** [comment]
> Ow it's the swww version.
> 
> Try to run `swww init` on the terminal

it worked now thanks!

**Comment by Enigma1309** [comment]
> Ow it's the swww version.
> 
> Try to run `swww init` on the terminal

yes for some reasons version 9.x.x is not in the aur yet and titty have pushed the changes to the repo, mabe a rollback would do...
