### ISSUE TITLE
Issue with logging in

### ISSUE THREAD

**Issue by 0xSnoxzy** [prasanthrangan/hyprdots#106]
Hello, i noticed even after installing several times, whenever i try to login with my username and password to the system it keeps bringing me back to the login screen. i installed it on a clean arch install and can't figure out what is the problem.

**Comment by DiegoSof2** [comment]
something similar happened to me try to go back from the login screen to the terminal, and send the install command again, just install command without the rest

**Comment by prasanthrangan** [comment]
Hi, this might be an nivida thing, can you please try login from TTY and check the error message.

**Comment by Mezo-hx** [comment]
I got the same issue, and for me, the tty is blank, other then for the flickering underscore symbol at the top left

**Comment by 0xSnoxzy** [comment]
> Hi, this might be an nivida thing, can you please try login from TTY and check the error message.

Could the problem be that I installed it on a VM?

**Comment by Mezo-hx** [comment]
I installed it on bare metal, so I doubt installing on a VM is an issue.

**Comment by T-Crypt** [comment]
What graphics card do you have? This is a generic graphics error when installing hyprland. 

Usually due to what nvidia pkg was installed during the script.

**Comment by Mezo-hx** [comment]
For me, I got a GT 1030

**Comment by T-Crypt** [comment]
@Mezo-hx 

When the script calls for the nvidia driver selection on line #97 

You should be selecting the nvidia-dkms/nvidia-utils, if the script detects an integrated GPU it will also give the driver options for it so it is possibly you installed without the nvidia support.

You can try setting nomodeset in grub and installing nvidia-dkms manually and restarting the your machine.

**Comment by Mezo-hx** [comment]
> @Mezo-hx
> 
> When the script calls for the nvidia driver selection on line #97
> 
> You should be selecting the nvidia-dkms/nvidia-utils, if the script detects an integrated GPU it will also give the driver options for it so it is possibly you installed without the nvidia support.
> 
> You can try setting nomodeset in grub and installing nvidia-dkms manually and restarting the your machine.

I still get the same issue... For me, I'm using systemd currently

**Comment by T-Crypt** [comment]
@Mezo-hx  

Sounds similar to an issue I had on 1 install. I do know that after first install, sometimes the your account username isn't populated. Are you able to get to the hyprland login screen or is it all black / no option to login at all? 

I had to put in my user account that I created into the username field or else it just loops.

**Comment by T-Crypt** [comment]
enter the user account name that you setup when you ran "archinstall" above the password field. By default, i've seen it just say "user" and you need to input your username.

**Comment by Mezo-hx** [comment]
> enter the user account name that you setup when you ran "archinstall" above the password field. By default, i've seen it just say "user" and you need to input your username.

I did that and I entered the password, and when I login, it sends me to some console for like 2 seconds, and then sends me back to the login screen

**Comment by T-Crypt** [comment]
Open TTY and go back to the hyprdots and run the ./install.sh by itself. 

If you try that and it finishes and you get same result, just try running the script as "sudo ./install.sh" as I've seen permissions fail on /etc/grub before and then log back in as user and run the ./install script again.

**Comment by 0xSnoxzy** [comment]
> Open TTY and go back to the hyprdots and run the ./install.sh by itself. 
> 
> If you try that and it finishes and you get same result, just try running the script as "sudo ./install.sh" as I've seen permissions fail on /etc/grub before and then log back in as user and run the ./install script again. 

I will try it in a moment.

**Comment by 0xSnoxzy** [comment]
> Open TTY and go back to the hyprdots and run the ./install.sh by itself. 
> 
> If you try that and it finishes and you get same result, just try running the script as "sudo ./install.sh" as I've seen permissions fail on /etc/grub before and then log back in as user and run the ./install script again. 

It doesnt let me run the install with sudo since it has to run makepkg with sudo too :(

**Comment by T-Crypt** [comment]
@0xSnoxzy just navigate to the hyprdots directory, and su root and then just type ./install.sh

Script is not meant to run as root, but it won't hurt when your system is unable to login already. 

Once its done, su 'user' and run the ./install.sh

**Comment by 0xSnoxzy** [comment]
> @0xSnoxzy just navigate to the hyprdots directory, and su root and then just type ./install.sh
> 
> Script is not meant to run as root, but it won't hurt when your system is unable to login already.
> 
> Once its done, su 'user' and run the ./install.sh

still have the same problem.
![Screenshot 2023-08-25 202541](https://github.com/prasanthrangan/hyprdots/assets/104795368/6f1771b9-adc6-45a9-9b4c-9b4a91b90ab4)

**Comment by T-Crypt** [comment]
@0xSnoxzy 

Give me a minute, I'm going to try to re-create this issue on my Dell laptop with a Nvidia 1060

**Comment by 0xSnoxzy** [comment]
And now it also gives me this other error:

![error](https://github.com/prasanthrangan/hyprdots/assets/104795368/9f25ff60-0ae6-4421-8ead-e23fc5e3ae24)

**Comment by Mezo-hx** [comment]
Well, since I made a slight mistake, had to reinstall arch linux... And now, I'm greeted by errors
![20230825_150228](https://github.com/prasanthrangan/hyprdots/assets/47868851/f6c13869-ccd7-48fa-bc9b-ea5d588c8318)
![20230825_150224](https://github.com/prasanthrangan/hyprdots/assets/47868851/dc17da4e-91c0-4064-b229-e7dcc630604f)

**Comment by 0xSnoxzy** [comment]
> @0xSnoxzy 
> 
> Give me a minute, I'm going to try to re-create this issue on my Dell laptop with a Nvidia 1060

Note that im trying to do all that on a VM, I don't think It Is a problem with the graphics card since it automatically skips the drivers installation in the script.

**Comment by T-Crypt** [comment]
@0xSnoxzy 

From my understanding and Hyprland documentation, I believe if you are setting up in a VM this is a little more difficult to get working properly. 

You may need to look at the Hyprland VM wiki
https://wiki.hyprland.org/Getting-Started/Master-Tutorial/

**Comment by T-Crypt** [comment]
@Mezo-hx 

Did you install with Grub or systemd?

**Comment by 0xSnoxzy** [comment]
> @Mezo-hx 
> 
> Did you install with Grub or systemd? 
> 
> 

GRUB!

**Comment by T-Crypt** [comment]
@0xSnoxzy 

I've only gotten this to work with systemd, grub is a whole other ball game I didn't feel like playing.

If you give me a day or two, ill throw arch in my proxmox server and see if I can get it working. From my past experiences, I gave up quickly, and just ran endeavour OS on VM rather than base Arch

**Comment by 0xSnoxzy** [comment]
> @0xSnoxzy 
> 
> I've only gotten this to work with systemd, grub is a whole other ball game I didn't feel like playing.
> 
> If you give me a day or two, ill throw arch in my proxmox server and see if I can get it working. From my past experiences, I gave up quickly, and just ran endeavour OS on VM rather than base Arch

Tomorrow I will try to run It with sysyemd thank you a lot for helping!!!!!

**Comment by Mezo-hx** [comment]
> @Mezo-hx
> 
> Did you install with Grub or systemd?

Systemd

**Comment by T-Crypt** [comment]
@Mezo-hx  

Are you install baremetal or is this a VM as well?

**Comment by prasanthrangan** [comment]
> Well, since I made a slight mistake, had to reinstall arch linux... And now, I'm greeted by errors

is it not even booting till TTY? with both grub and systemd ?

**Comment by CQuarkH** [comment]
i had the same issue, but i was in vbox so i turned on the 3D Acceleration and it works.

**Comment by kRHYME7** [comment]
Hello, Any updates regarding this ?

**Comment by kRHYME7** [comment]
Halu! Many changes have gone since then. Please reopen another issue. Also, the Op's GPU supports the latest NVIDIA driver. It should work fine with hyprland upon installation. (sudo problems)
