### ISSUE TITLE
[Bug]: Rofi-lbonn-wayland-git error

### ISSUE THREAD

**Issue by Wazes1** [prasanthrangan/hyprdots#1073]
## Bug Report
When trying to install hyprdots from install.sh , scripts fails to install rofi-lbonn-wayland-git

e.g.,

- Linux Distro: EndeavourOS

When trying to install rofi-lbonn-wayland-git i see this after 'The Meson build system' line :

Source dir: /home/wazes/.cache/yay/rofi-lbonn-wayland-git/src/rofi-lbonn-wayland-git
Build dir: /home/wazes/.cache/yay/rofi-lbonn-wayland-git/src/build
Build type: native build
Project name: rofi
Project version: 1.7.5+wayland3-dev
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230801")
C linker for the host machine: cc ld.bfd 2.42.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wparentheses: YES 
Compiler for C supports arguments -Winline: YES 
Compiler for C supports arguments -Wunreachable-code: YES 
Compiler for C supports arguments -Werror=missing-prototypes: YES 
Compiler for C supports arguments -Wno-overlength-strings: YES 
Compiler for C supports arguments -Wno-inline: YES 
Found pkg-config: YES (/usr/bin/pkg-config) 2.1.0
Run-time dependency glib-2.0 found: YES 2.78.4
Run-time dependency gmodule-2.0 found: YES 2.78.4
Run-time dependency cairo found: YES 1.18.0
Library m found: YES
Run-time dependency gio-unix-2.0 found: YES 2.78.4
Run-time dependency pango found: YES 1.52.1
Run-time dependency pangocairo found: YES 1.52.1
Run-time dependency xkbcommon found: YES 1.6.0
Run-time dependency gdk-pixbuf-2.0 found: YES 2.42.10

Executing subproject libgwater 

libgwater| Project name: libgwater
libgwater| Project version: undefined
libgwater| C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230801")
libgwater| C linker for the host machine: cc ld.bfd 2.42.0
libgwater| Dependency glib-2.0 found: YES 2.78.4 (cached)
libgwater| Run-time dependency gobject-2.0 found: YES 2.78.4
libgwater| Run-time dependency gio-2.0 found: YES 2.78.4
libgwater| Dependency gio-unix-2.0 found: YES 2.78.4 (cached)
libgwater| Has header "errno.h" : YES
libgwater| Has header "sys/types.h" : YES
libgwater| Has header "sys/socket.h" : YES
libgwater| Run-time dependency wayland-client found: YES 1.22.0
libgwater| Run-time dependency wayland-server found: YES 1.22.0
libgwater| Run-time dependency xcb found: YES 1.16.1
libgwater| Run-time dependency libmpdclient found: YES 2.22
libgwater| Dependency glib-2.0 found: YES 2.78.4 (cached)
libgwater| Run-time dependency libnl-3.0 found: YES 3.9.0
libgwater| Has header "linux/netlink.h" : YES
libgwater| Has header "sys/poll.h" : YES
libgwater| Run-time dependency alsa found: YES 1.2.11
libgwater| Build targets in project: 6
libgwater| Subproject libgwater finished.

Dependency xcb found: YES 1.16.1 (cached)
Run-time dependency xcb-aux found: YES 0.4.1
Run-time dependency xcb-xkb found: YES 1.16.1
Run-time dependency xkbcommon-x11 found: YES 1.6.0
Run-time dependency xcb-ewmh found: YES 0.4.2
Run-time dependency xcb-icccm found: YES 0.4.2
Run-time dependency xcb-randr found: YES 1.16.1
Run-time dependency xcb-cursor found: YES 0.1.5
Run-time dependency xcb-xinerama found: YES 1.16.1
Run-time dependency cairo-xcb found: YES 1.18.0
Run-time dependency libstartup-notification-1.0 found: YES 0.12
Run-time dependency wayland-protocols found: YES 1.33
Dependency wayland-client found: YES 1.22.0 (cached)
Run-time dependency wayland-cursor found: YES 1.22.0
Run-time dependency check found: YES 0.15.2
Configuring config.h using configuration

Executing subproject libnkutils 

libnkutils| Project name: libnkutils
libnkutils| Project version: 1.0.0
libnkutils| C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230801")
libnkutils| C linker for the host machine: cc ld.bfd 2.42.0
libnkutils| Dependency glib-2.0 found: YES 2.78.4 (cached)
libnkutils| Dependency gio-2.0 found: YES 2.78.4 (cached)
libnkutils| Dependency gobject-2.0 found: YES 2.78.4 (cached)
libnkutils| Program git found: YES (/usr/bin/git)
libnkutils| Dependency glib-2.0 found: YES 2.78.4 (cached)
libnkutils| Dependency xkbcommon found: YES 1.6.0 (cached)
libnkutils| Run-time dependency xkeyboard-config found: YES 2.41
libnkutils| Build targets in project: 20
libnkutils| Subproject libnkutils finished.

Program flex found: YES (/usr/bin/flex)
Program bison found: YES (/usr/bin/bison)
Program wayland-scanner found: YES (/usr/bin/wayland-scanner)
Dependency gio-2.0 found: YES 2.78.4 (cached)
Program /usr/bin/glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Program go-md2man found: NO
Configuring rofi.doxy using configuration
Program doxygen found: NO
Program cppcheck found: NO
Program ohcount found: NO
Build targets in project: 49

rofi 1.7.5+wayland3-dev

  Subprojects
    libgwater         : YES
    libnkutils        : YES

  User defined options
    auto_features     : enabled
    buildtype         : plain
    libexecdir        : lib
    prefix            : /usr
    sbindir           : bin
    wrap_mode         : nodownload
    python.bytecompile: 1
    b_pie             : true
    check             : enabled
    wayland           : enabled

Found ninja-1.11.1 at /usr/bin/ninja
INFO: autodetecting backend as ninja                                                                                                                                                                                 
INFO: calculating backend command to run: /usr/bin/ninja -C /home/wazes/.cache/yay/rofi-lbonn-wayland-git/src/build
ninja: Entering directory `/home/wazes/.cache/yay/rofi-lbonn-wayland-git/src/build'
[29/150] Compiling C object subprojects/libgwater/xcb/liblibgwater-xcb.a.p/libgwater-xcb.c.o
../rofi-lbonn-wayland-git/subprojects/libgwater/xcb/libgwater-xcb.c: '_g_water_xcb_source_dispatch' işlevinde:
../rofi-lbonn-wayland-git/subprojects/libgwater/xcb/libgwater-xcb.c:97:36: UYARI: ISO C işlev göstericisinin nesne göstericisine dönüştürülmesini yasaklar [-Wpedantic]
   97 |     ret = ((GWaterXcbEventCallback)(void *)callback)(event, user_data);
      |                                    ^
../rofi-lbonn-wayland-git/subprojects/libgwater/xcb/libgwater-xcb.c:97:12: UYARI: ISO C nesne göstericisinin işlev göstericisine dönüştürülmesini yasaklar [-Wpedantic]
   97 |     ret = ((GWaterXcbEventCallback)(void *)callback)(event, user_data);
      |            ^
../rofi-lbonn-wayland-git/subprojects/libgwater/xcb/libgwater-xcb.c: 'g_water_xcb_source_new_for_connection' işlevinde:
../rofi-lbonn-wayland-git/subprojects/libgwater/xcb/libgwater-xcb.c:160:48: UYARI: ISO C işlev göstericisinin nesne göstericisine dönüştürülmesini yasaklar [-Wpedantic]
  160 |     g_source_set_callback(source, (GSourceFunc)(void *)callback, user_data, destroy_func);
      |                                                ^
../rofi-lbonn-wayland-git/subprojects/libgwater/xcb/libgwater-xcb.c:160:35: UYARI: ISO C nesne göstericisinin işlev göstericisine dönüştürülmesini yasaklar [-Wpedantic]
  160 |     g_source_set_callback(source, (GSourceFunc)(void *)callback, user_data, destroy_func);
      |                                   ^
[101/150] Compiling C object rofi.p/source_modes_dmenu.c.o
../rofi-lbonn-wayland-git/source/modes/dmenu.c: 'read_input_thread' işlevinde:
../rofi-lbonn-wayland-git/source/modes/dmenu.c:312:19: UYARI: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  312 |                   write(pd->pipefd2[1], "r", 1);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../rofi-lbonn-wayland-git/source/modes/dmenu.c:329:13: UYARI: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  329 |             write(pd->pipefd2[1], "r", 1);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../rofi-lbonn-wayland-git/source/modes/dmenu.c:345:9: UYARI: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  345 |         write(pd->pipefd2[1], "r", 1);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../rofi-lbonn-wayland-git/source/modes/dmenu.c:351:3: UYARI: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  351 |   write(pd->pipefd2[1], "q", 1);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../rofi-lbonn-wayland-git/source/modes/dmenu.c: 'dmenu_finish' işlevinde:
../rofi-lbonn-wayland-git/source/modes/dmenu.c:743:5: UYARI: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  743 |     write(pd->pipefd[1], "q", 1);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[106/150] Compiling C object rofi.p/source_modes_recursivebrowser.c.o
../rofi-lbonn-wayland-git/source/modes/recursivebrowser.c: 'recursive_browser_input_thread' işlevinde:
../rofi-lbonn-wayland-git/source/modes/recursivebrowser.c:266:3: UYARI: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  266 |   write(pd->pipefd2[1], "r", 1);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../rofi-lbonn-wayland-git/source/modes/recursivebrowser.c:267:3: UYARI: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  267 |   write(pd->pipefd2[1], "q", 1);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../rofi-lbonn-wayland-git/source/modes/recursivebrowser.c: 'scan_dir' işlevinde:
../rofi-lbonn-wayland-git/source/modes/recursivebrowser.c:222:11: UYARI: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  222 |           write(pd->pipefd2[1], "r", 1);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../rofi-lbonn-wayland-git/source/modes/recursivebrowser.c:250:11: UYARI: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  250 |           write(pd->pipefd2[1], "r", 1);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[150/150] Linking target rofi
==> check() işlemine başlanıyor...
ninja: Entering directory `/home/wazes/.cache/yay/rofi-lbonn-wayland-git/src/build'
[1/1] Generating subprojects/libnkutils/core/nkutils-git-version.h with a custom command
 1/19 libnkutils:enum / libnkutils enum module tests                           OK              0.03s   13 subtests passed
 2/19 libnkutils:format-string / libnkutils format-string module tests         OK              0.03s   94 subtests passed
 3/19 libnkutils:colour / libnkutils colour module tests                       OK              0.03s   17 subtests passed
 4/19 libnkutils:xdg-de / libnkutils xdg-de module tests                       OK              0.02s   19 subtests passed
 5/19 libnkutils:gtk-settings / libnkutils gtk-settings module tests           OK              0.02s   4 subtests passed
 6/19 libnkutils:xdg-theme / libnkutils xdg-theme module tests                 OK              0.02s   8 subtests passed
 7/19 rofi / history test                                                      OK              0.02s
 8/19 rofi / widget test                                                       OK              0.01s
 9/19 rofi / box test                                                          OK              0.01s
10/19 rofi / helper_pidfile test                                               OK              0.03s
11/19 rofi / scrollbar test                                                    OK              0.03s
12/19 rofi / helper test                                                       OK              0.02s
13/19 rofi / helper_expand test                                                OK              0.02s
14/19 rofi / helper_config_cmdline_parser test                                 OK              0.02s
15/19 rofi / mode test                                                         OK              0.01s
16/19 rofi / textbox test                                                      OK              0.03s
17/19 rofi / helper_tokenize test                                              OK              0.02s
18/19 libnkutils:bindings / libnkutils bindings module tests                   OK              0.07s   16 subtests passed
19/19 rofi / theme_parser test                                                 FAIL            0.07s   exit status 1
>>> MALLOC_PERTURB_=12 ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 /home/wazes/.cache/yay/rofi-lbonn-wayland-git/src/build/theme_parser.test

Ok:                 18  
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /home/wazes/.cache/yay/rofi-lbonn-wayland-git/src/build/meson-logs/testlog.txt
==> HATA: check() içinde bir hata oluştu.
    Çıkılıyor...
 -> yapılırken hata: rofi-lbonn-wayland-git-exit status 4
 -> İstenen paketler yüklenemedi. Manüel müdahale gerekli:
rofi-lbonn-wayland-git - exit status 4

**Comment by Enigma1309** [comment]
this is a rofi-lbonn-wayland-git related issue and has nothing to do with this repo or hyprdots, report it to upstream
