### ISSUE TITLE
[Help]: hyprpicker-git - exit status 4. Required manual installation

### ISSUE THREAD

**Issue by Gugedo** [prasanthrangan/hyprdots#1075]
I dont know what to do, can someone help me?

**Comment by ysimard94** [comment]
I've replaced hyprpicker-git for hyprpicker in custom_hypr.lst and it worked fine.

**Comment by Brazlucas** [comment]
> I've replaced hyprpicker-git for hyprpicker in custom_hypr.lst and it worked fine.

Thank you, it's working here!!

**Comment by Gugedo** [comment]
> I've replaced hyprpicker-git for hyprpicker in custom_hypr.lst and it worked fine.

thanks man u saved me a lot of time!
P.S. For the newbies to do that u have to open the custom_hypr.lst file inside the Scripts folder with an editor, for exemple vi(type "vi custom_hypr.lst" when u are inside Scripts folder)->change hyprpicker-git in hyprpicker(if u use vi press "i" to enter the insert mode, then pres "esc" to exit insert mode and digit ":wq" to save and come back to terminal)->now start the installer "./install.sh"

**Comment by kRHYME7** [comment]
Let me pin this post. 


> [!Note]
> From hyprpicker AUR 
> The Makefile has been removed as it is no longer used. Functionality has been transfered to CMake.

**Comment by Anomyous99** [comment]
Bro how exactly should I replace hyprpicker and with what
Pls I'm a newbie I want to know

**Comment by Gugedo** [comment]
> Bro how exactly should I replace hyprpicker and with what Pls I'm a newbie I want to know

u can follow what i wrote 2 comments above, that is the way. If you have problem recomment and i answer u

**Comment by Anomyous99** [comment]
Bro I did that i enter in the scripts and found hyprpicker-git too
But I don't get what should I do next after that should I comment it or replace it ,if replace it then how??

**Comment by Anomyous99** [comment]
An ya I also got this error 
![Uploading 1710345921833346660733937871114.jpg…]()

**Comment by Gugedo** [comment]
> Bro I did that i enter in the scripts and found hyprpicker-git too But I don't get what should I do next after that should I comment it or replace it ,if replace it then how??

1) u have to enable insert mode pressing "i" key, now u can modify the file.
2) change hyprpicker-git with hyprpicker, dont modify other things.
3)press "esc" to exit insert mode
4)at the bottom, under the file, u shoulds see a blank line there type ":wq" that saves the changes and quit the editor
5) retry the installation with ./install.sh

**Comment by Anomyous99** [comment]
Bro I did it with vs code 🙂
Did I did it wrong?!!? I'm getting a bit concerned now 🙂

**Comment by Javatrix** [comment]
> Bro I did it with vs code 🙂 Did I did it wrong?!!? I'm getting a bit concerned now 🙂

No its fine, just if you edited it properly it should work.

**Comment by Anomyous99** [comment]
Ohh I think I get it i should delete the -git from hyprpicker-git
And it should look like something "hyprpicker"

**Comment by Javatrix** [comment]
> Ohh I think I get it i should delete the -git from hyprpicker-git And it should look like something "hyprpicker"

thats right

**Comment by Anomyous99** [comment]
Ok that's a lot of help bro 
Thank a lot 🥹😊

**Comment by Gugedo** [comment]
> Ohh I think I get it i should delete the -git from hyprpicker-git And it should look like something "hyprpicker"

yes thats the point, all the things that i said were for _vi editor_ but u can do with every editor.

**Comment by Anomyous99** [comment]
I'm so happy
Thanks a lot to you and everyone in the thread

**Comment by Anomyous99** [comment]
See  you guys soon in future 😊

**Comment by Phunguy65** [comment]
I have same issue after replace hyprpicker-git with hyprpicker

**Comment by Anomyous99** [comment]
At first open the session on KDE
The open the scripts folder of hyprdots and find custom_hypr.lst then find hyprpicker -git and remove the "-git" from hyprpicker-git
That's it 
Save 
And run the ./install.sh again
It will work
