### ISSUE TITLE
[Bug]: Notifications not displaying correctly

### ISSUE THREAD

**Issue by Nic-Vladimir** [prasanthrangan/hyprdots#1080]
### Description

Notifications don't display properly. They appear too dark and are missing elements. Especially noticeable in the Spotify ones.

### Steps to Reproduce

1. Install or update to the latest  hyprdots-git version
2. Perform any action that triggers a notification pop-up (change spotify song, change volume or brightness etc.)

### Expected Behavior

It is expected that the notifications are clear, readable and correctly display their supposed elements.

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/116428311/306d9cc6-47a7-4bfb-9d26-c675a03c2a5f)

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux Mother 6.7.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0
- Installation Environment: On The Main Hardware
- Other info: Display Resolution: 1920x1080@60

**Comment by nicolkrit999** [comment]
Why are yo ahead of the main branch? Anyway try to reinstall the dunst notification applet. If that does not work you can use the repo under ~/.config you find the dunst folder, check that you have all the necessary icons

- vol.svg
- arch.svg
- critical.svg
- hyprdots.png
- hyprdots.svg
- keyboard.svg
and that in the parent folder you have the same configuration as the repo in dunst.conf

**Comment by kRHYME7** [comment]
Hmmm did you rebuild your cache? 


If no, 

``` Hyprdots cached rebuild ``` 

Please read this thread first #1053

**Comment by lewisblackburn** [comment]
Running `Hyprdots reload` fixed this issue for me!

**Comment by lewisblackburn** [comment]
This issue seems to be when changing the theme, the notifications don't change theme along with it and therefore break.

**Comment by t101804** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/113588203/74214c97-a9de-4ea6-8b8f-73010d2961b2)


when i reload this error show me. and the waybar closed immediatly

**Comment by kRHYME7** [comment]
Did you properly Follow this #1053

**Comment by t101804** [comment]
> Did you properly Follow this #1053
> 
>     * remove the older script directory.

![image](https://github.com/prasanthrangan/hyprdots/assets/113588203/38396092-e4fa-476e-8c6e-429d9066666c)


waybar still cant and Error: Failed to source globalcontrol.sh

**Comment by kRHYME7** [comment]
yay -Sy hyprdots-ctl-git 

Try to update first

**Comment by t101804** [comment]
> yay -Sy hyprdots-ctl-git

![image](https://github.com/prasanthrangan/hyprdots/assets/113588203/0e42ad25-a4a9-41a7-9c08-fe9a2e4e33d7)

**Comment by kRHYME7** [comment]
do you have this file? 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/3832c1f8-5c57-4c9c-a2c4-86ef3750371b)



How was your notification ?

**Comment by abenezerw** [comment]
Could you close as solved if you no longer have this issue. Thank you @Nic-Vladimir
