### ISSUE TITLE
[Bug]: Notification not displaying properly

### ISSUE THREAD

**Issue by Vivarium69420** [prasanthrangan/hyprdots#1083]
### Description
Any notification show up in the middle of the screen with only text no icon or anything

### Steps to Reproduce

Pull from the latest update. And just system update for all apps

[What actually happened?]

### Screenshots
![image](https://github.com/prasanthrangan/hyprdots/assets/124338880/ac48cfff-24ee-48a6-b8af-409a57427b29)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux archlinux 6.6.21-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 06 Mar 2024 16:59:55 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)
- Installation Environment: On main

**Comment by kRHYME7** [comment]
out is the output if you run ``` dunst ```

**Comment by Vivarium69420** [comment]
Thank you ._. 
That was dumb of me, somehow `mako` ran first instead of `dunst`
