### ISSUE TITLE
context menu with border

### ISSUE THREAD

**Issue by iEscapedVim** [prasanthrangan/hyprdots#1085]
## Bug Report

Context menu on chrome has the blurry border which's annoying, I tried switching chrome's theme to GTK/QT but no difference. 

### Steps to Reproduce

1. Install Chrome
2. Right Click Anywhere

### Expected Behavior

The context menu shouldn't have that big border around it. 

### Actual Behavior

The context menu doesn't have that big border around it.

### Screenshots

![240315_10h44m59s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/32537564/7013f65a-c659-4178-919b-dfa7deb1f5ff)

### Environment

- Linux Distro: CachyOS (Arch Based)
- Linux Version: Linux Bimo 6.8.0-2-cachyos
- Hyprland Version: 
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
- Installation Environment: HP Elitebook 840 G3
- CPU : Intel i5-6300U (4) @ 3.000GHz 
- GPU : Intel HD 520

**Comment by kRHYME7** [comment]
Try to run your chrome with wayland flag?

**Comment by iEscapedVim** [comment]
yup that worked
![image](https://github.com/prasanthrangan/hyprdots/assets/32537564/b4809ae3-9bdc-4beb-bbf7-b7ad01fd366c)
