### ISSUE TITLE
[Sddm]: i wasn't able to select the option from the install script 

### ISSUE THREAD

**Issue by Coderx11** [prasanthrangan/hyprdots#1092]
### themeing 

[So can you please make a script regarding setting themes of sddm , i had similar issue with grub theme so it would be great if I could get a script or steps to select or to apply manually the themes of grub or sddm , for grub I replaced some text files and it worked but I have no idea or time to search for fixing sddm theme 😞]

**Comment by Coderx11** [comment]
@kRHYME7 sir 😥

**Comment by kRHYME7** [comment]
What do you want to do on the themes? Changing themes? candy to corners and vice versa?

**Comment by Coderx11** [comment]
Yea change themes as I missed my chance to select it and it won't work again after I rerun the script

**Comment by kRHYME7** [comment]
@Coderx11  Added ``` Hyprdots sddm theme ``` to select theme

**Comment by Coderx11** [comment]
Thanks sir

**Comment by Luiz0047** [comment]
@kRHYME7 I also want to change corners to candy, how can i do that ? Is Hyprdtos sddm theme another script ?

**Comment by kRHYME7** [comment]
@Luiz0047 yes it's the cli for hyprdots and it's probably installed on your system. 

https://github.com/kRHYME7/Hyprdots-ctl

But Hyprdots are moving to Hyde soon. Something might change. https://discord.gg/FjkBSNGm Here's our discord channel.
