### ISSUE TITLE
[Bug]: Graphite-Mono text tends to be black

### ISSUE THREAD

**Issue by Cruleo** [prasanthrangan/hyprdots#1093]
### Description

When the QT6CT selected theme is Kvantum > Custom Palette > Color scheme: Graphite Mono, it leads to some text being black (see picture below). 

![image](https://github.com/prasanthrangan/hyprdots/assets/25243300/72313ccc-605f-4153-9952-1b2fd90d6af1)

If the Palette in QT6CT is set to Default, then text is behaving as expected.

Additionally, the sidebar on Dolphin color of text and selected colour seems to be overlapping (shown below). If I double click the entry on the sidebar, then text shows as expected.
![image](https://github.com/prasanthrangan/hyprdots/assets/25243300/7bb668e7-1355-44b1-8510-2be43b1f3a95)

Both of the listed issues do not occur with Graphite-Rimless-dark from [here](https://github.com/vinceliuice/Graphite-kde-theme).

### Steps to Reproduce

1. Use Graphite-Mono theme
2. Open Dolphin
3. Click on "Places" sidebar
4. Open Qt6Ct or Kvantum Manager
5. See some text being dark (especially hover tooltips)

### Expected Behavior

Dolphin sidebar text should be readable. Tooltips having black text should follow the text colour of normal text.

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: Arch Linux
- Linux Version, output of `uname -a`: 6.8.0
- Hyprland Version, output of `hyprctl version`: ```Hyprland, built from branch main at commit 164e92f8e376536fff89dac41cde654293e64522 dirty (internal: minor fixups for fading out xwayland windows).
Date: Thu Mar 14 19:25:28 2024
Tag: v0.36.0-108-g164e92f8```
- Installation Environment: Main hardware (NVIDIA GPU)

Any help appreciated. Thanks in advance!

**Comment by Xeo23** [comment]
Also facing same issue + mostly gtk themes have white topbar when the app is in focus.
![image](https://github.com/prasanthrangan/hyprdots/assets/65211497/01d60c00-aca8-4f3e-9514-1e9b83e27298)

**Comment by prasanthrangan** [comment]
> Both of the listed issues do not occur with Graphite-Rimless-dark from [here](https://github.com/vinceliuice/Graphite-kde-theme).

hmm.. let me check `qt5ct` colors, but i'm unable to find it in this repo - it only has kvantum configs.

**Comment by Cruleo** [comment]
I do use Kvantum with qt5ct/qt6ct and therefore believe it should be within Kvantum config.

**Comment by celikj** [comment]
when i select a text in browser it is also unreadable.

**Comment by abenezerw** [comment]
This was solved on theme update @Cruleo would you mind closing this out
