### ISSUE TITLE
[Bug]: keybinding window doesn't open in waybar

### ISSUE THREAD

**Issue by Ramy-Ashraf** [prasanthrangan/hyprdots#1095]
### Description

I know it's a small bug but when I click on keybindings button in waybar nothing happen.

### Steps to Reproduce

1. Click on keybindings button in waybar.

### Expected Behavior

Open keybindings description window

### Actual Behavior

Nothing happen

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/85342902/cd6ba863-96fb-4575-96b4-52d59b1ebdad)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: ArchLinux.
- Linux Version, output of `uname -a`: Linux archlinux 6.7.9-arch1-1
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0
- Installation Environment: On The Main Hardware.
- Other info: Display Resolution (1920x1080)

**Comment by kRHYME7** [comment]
What happens if you run ``` Hyprdots show binds ``` on the terminal? 

Can you provide the output for 

``` cat ~/.config/waybar/modules/keybindhint.jsonc ```


It still works on my end

**Comment by Ramy-Ashraf** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/85342902/ca10a3a6-0215-452d-a8d1-7551dcf5d943)
this happens

**Comment by Ramy-Ashraf** [comment]
I think rofi has a problem.
![image](https://github.com/prasanthrangan/hyprdots/assets/85342902/e6a4711f-24e6-44a2-9cf3-17b0331f8eee)

**Comment by ljijljijljijl** [comment]
I have sort of the same issue. At least i noticed it the same way, through keybind hint.
Tried pulling latest commits and restoring configs, didn't fix the issue.
Rofi works fine.

![240316_22h30m03s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/63408677/502702d9-323f-49cf-8a52-d6a4ac6ba96b)

**Comment by kRHYME7** [comment]
Hmmm it's the Hyprdots-ctl error. 


What is the output for 

```
Hyprdots version
ls ~/.config/hyprdots/scripts/globalcontrol.sh
```

Try to update ``` yay -Sy hyprdots-ctl ```


#1053 <<< Read this 
#1070 <<<< Also see this

**Comment by Ramy-Ashraf** [comment]
this is the output first time running it.
![image](https://github.com/prasanthrangan/hyprdots/assets/85342902/54fd5172-8d9f-40e2-a63c-d7be2e81444f)
this is the second time.
![image](https://github.com/prasanthrangan/hyprdots/assets/85342902/520d3ecb-639c-41e8-8741-0ebfeffc65c6)

**Comment by Ramy-Ashraf** [comment]
> yay -Sy hyprdots-ctl

updating it made it work fine and every thing now works good including keybindings window

**Comment by MostlyKIGuess** [comment]
@Ramy-Ashraf  I have the same issue, win + tab does open the windows switcher but clicking on another windows doesn't switch anything or do anything
