### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by Wazes1** [prasanthrangan/hyprdots#1096]
when tried to install via install.sh script i get this error and could not find what to do :

100% 15:0=0s Catppuccin-Mocha /home/wazes/.config/swww/Catppuccin-Mocha/switch_swirl.jpg                                                                                                      
Creating thumbnails for Catppuccin-Latte [15]
100% 15:0=0s Catppuccin-Latte /home/wazes/.config/swww/Catppuccin-Latte/waifu_jasmin.jpg                                                                                                      
Creating thumbnails for Decay-Green [6]
100% 6:0=0s Decay-Green /home/wazes/.config/swww/Decay-Green/relaxed_mario.png                                                                                                                
Creating thumbnails for Rose-Pine [12]
83% 10:2=0s Rose-Pine /home/wazes/.config/swww/Rose-Pine/waifu_pink.png                                                                                                                       convert: no decode delegate for this image format `GIF' @ error/constitute.c/ReadImage/746.
convert: no images defined `/home/wazes/.cache/hyprdots/Rose-Pine/nimbus.gif' @ error/convert.c/ConvertImageCommand/3362.
convert: no decode delegate for this image format `GIF' @ error/constitute.c/ReadImage/746.
convert: no images defined `/home/wazes/.cache/hyprdots/Rose-Pine/nimbus.gif.rofi' @ error/convert.c/ConvertImageCommand/3362.
convert: no decode delegate for this image format `GIF' @ error/constitute.c/ReadImage/746.
convert: no images defined `/home/wazes/.cache/hyprdots/Rose-Pine/nimbus.gif.blur' @ error/convert.c/ConvertImageCommand/3362.
100% 12:0=0s Rose-Pine /home/wazes/.config/swww/Rose-Pine/waifu_pink.png

**Comment by kRHYME7** [comment]
What happens if you rerun the installation?

**Comment by Wazes1** [comment]
> What happens if you rerun the installation?

Same thing, i see this error again

**Comment by kRHYME7** [comment]
can you provide output for this ?

**Comment by Wazes1** [comment]
installed giflib but still convert -list format | grep GIF output is blank and can't install

**Comment by prasanthrangan** [comment]
does it work for other images?? is it only the gifs causing this??

can you check if you all these libraries installed `ldd $(which convert)` -

```
❯ ldd $(which convert)
	linux-vdso.so.1 (0x00007ffe85bb8000)
	libMagickCore-7.Q16HDRI.so.10 => /usr/lib/libMagickCore-7.Q16HDRI.so.10 (0x0000797ebba00000)
	libMagickWand-7.Q16HDRI.so.10 => /usr/lib/libMagickWand-7.Q16HDRI.so.10 (0x0000797ebb8b6000)
	libc.so.6 => /usr/lib/libc.so.6 (0x0000797ebb6d4000)
	liblcms2.so.2 => /usr/lib/liblcms2.so.2 (0x0000797ebbd9a000)
	libraqm.so.0 => /usr/lib/libraqm.so.0 (0x0000797ebbd92000)
	liblqr-1.so.0 => /usr/lib/liblqr-1.so.0 (0x0000797ebbd82000)
	libfftw3.so.3 => /usr/lib/libfftw3.so.3 (0x0000797ebb400000)
	libxml2.so.2 => /usr/lib/libxml2.so.2 (0x0000797ebb296000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x0000797ebbd30000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x0000797ebb1c8000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x0000797ebbd1b000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x0000797ebb085000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x0000797ebb6c1000)
	libz.so.1 => /usr/lib/libz.so.1 (0x0000797ebb6a7000)
	libltdl.so.7 => /usr/lib/libltdl.so.7 (0x0000797ebb69b000)
	libm.so.6 => /usr/lib/libm.so.6 (0x0000797ebaf99000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x0000797ebb64a000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x0000797ebaf74000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x0000797ebbe2a000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x0000797ebae66000)
	libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x0000797ebae46000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x0000797ebacfa000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x0000797ebacc7000)
	libicuuc.so.74 => /usr/lib/libicuuc.so.74 (0x0000797ebaa00000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x0000797ebac9e000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x0000797ebac64000)
	libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x0000797ebb63b000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x0000797ebac39000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x0000797ebac16000)
	libpcre2-8.so.0 => /usr/lib/libpcre2-8.so.0 (0x0000797eba962000)
	libicudata.so.74 => /usr/lib/libicudata.so.74 (0x0000797eb8c00000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0000797eb8800000)
	libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x0000797eb8bdd000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x0000797ebb636000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x0000797ebb62e000)
```

**Comment by Wazes1** [comment]
Yes i have all of these packages 

ldd $(which convert)
	linux-vdso.so.1 (0x00007ffc84539000)
	libMagickCore-7.Q16HDRI.so.10 => /usr/lib/libMagickCore-7.Q16HDRI.so.10 (0x000078618fa00000)
	libMagickWand-7.Q16HDRI.so.10 => /usr/lib/libMagickWand-7.Q16HDRI.so.10 (0x000078618f8b6000)
	libc.so.6 => /usr/lib/libc.so.6 (0x000078618f6d4000)
	liblcms2.so.2 => /usr/lib/liblcms2.so.2 (0x000078618fd8d000)
	libraqm.so.0 => /usr/lib/libraqm.so.0 (0x000078618fd85000)
	liblqr-1.so.0 => /usr/lib/liblqr-1.so.0 (0x000078618fd75000)
	libfftw3.so.3 => /usr/lib/libfftw3.so.3 (0x000078618f400000)
	libxml2.so.2 => /usr/lib/libxml2.so.2 (0x000078618f296000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x000078618fd23000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x000078618f1c8000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x000078618f6bf000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x000078618f085000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x000078618f6ac000)
	libz.so.1 => /usr/lib/libz.so.1 (0x000078618f692000)
	libltdl.so.7 => /usr/lib/libltdl.so.7 (0x000078618fd15000)
	libm.so.6 => /usr/lib/libm.so.6 (0x000078618ef99000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x000078618f641000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x000078618ef74000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x000078618fe18000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x000078618ee66000)
	libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x000078618ee46000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x000078618ecfa000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x000078618ecc7000)
	libicuuc.so.74 => /usr/lib/libicuuc.so.74 (0x000078618ea00000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x000078618ec9e000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x000078618ec64000)
	libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x000078618f632000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x000078618ec39000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x000078618ec16000)
	libpcre2-8.so.0 => /usr/lib/libpcre2-8.so.0 (0x000078618e962000)
	libicudata.so.74 => /usr/lib/libicudata.so.74 (0x000078618cc00000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x000078618c800000)
	libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x000078618cbdd000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x000078618ec11000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x000078618cbd5000)

**Comment by prasanthrangan** [comment]
hmmm I'm unable to replicate this issue, based on the log shared only the gif file seem to cause this..... so can you please remove these `.gif` files and rerun `create_cache.sh -f`

```
find ~/.config/swww/ -name "*.gif"
~/.config/swww/Rose-Pine/nimbus.gif
~/.config/swww/Tokyo-Night/street.gif
~/.config/swww/Tokyo-Night/gas_station.gif
```

**Comment by Wazes1** [comment]
I removed git files and it worked but now script freezes after this :

[cache] creating thumbnails for Catppuccin-Mocha [15]
100% 15:0=0s Catppuccin-Mocha /home/wazes/.config/swww/Catppuccin-Mocha/switch_s
[cache] creating thumbnails for Catppuccin-Latte [15]
100% 15:0=0s Catppuccin-Latte /home/wazes/.config/swww/Catppuccin-Latte/waifu_ja
[cache] creating thumbnails for Decay-Green [6]
100% 6:0=0s Decay-Green /home/wazes/.config/swww/Decay-Green/relaxed_mario.png  
[cache] creating thumbnails for Rose-Pine [11]
100% 11:0=0s Rose-Pine /home/wazes/.config/swww/Rose-Pine/waifu_pink.png        
[wazes@arch Scripts]$
