### ISSUE TITLE
[Bug]: Randomly locked workspaces 

### ISSUE THREAD

**Issue by blankRiot96** [prasanthrangan/hyprdots#1102]
### Description

So I installed everything as per the installation guide here on arch. Everything is perfect, but for some reason my workspaces keep randomly getting locked. I'm unable to `Super + 1` into the first workspace for example, but the apps there get highlighted. I also tried toggling on/off the "special workspace mode" using `Super + S` but that didnt seem to solve it either.

Here's an example where I'm unable to go to workspace `3` where I have my firefox open, which also gets highlighted and the mouse seems to go there, but my view is stuck on the current workspace instead.

https://github.com/prasanthrangan/hyprdots/assets/77634274/362b42b8-8a19-48be-a27a-8c38d142b50c

As you can see the firefox logo on the waybar seems to get highlighted but im unable to see it.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux archlinux 6.7.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Linux archlinux 6.7.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000 x86_64 GNU/Linux
- Installation Environment: Main hardware, lenovo
- Other info: 1920x1080 Display resolution

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by kRHYME7** [comment]
``` hyprctl clients ``` To see where Firefox go. Also, waybar is buggy (that window feature), don't rely on it too much. 

I usually use workspace module as windows module tends to be unreliable. 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/e121ae2f-5a31-458a-9e54-5285bab367e8)

**Comment by blankRiot96** [comment]
@kRHYME7 Thanks for your reply.
This is what `hyprctl clients` seems to say about firefox when I keep it in the 3rd workspace:
```
Window 5a4bc2cee0a0 -> [Bug]: Randomly locked workspaces · Issue #1102 · prasanthrangan/hyprdots — Mozilla Firefox:
	mapped: 1
	hidden: 0
	at: 10,41
	size: 1260,669
	workspace: 3 (3)
	floating: 0
	monitor: 0
	class: firefox
	title: [Bug]: Randomly locked workspaces · Issue #1102 · prasanthrangan/hyprdots — Mozilla Firefox
	initialClass: firefox
	initialTitle: Mozilla Firefox
	pid: 20635
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 2
```

Also, what did you mean by the workspace module? Is that one of the waybar modes with `Super + Alt + up/down`

**Comment by kRHYME7** [comment]
> Is that one of the waybar modes with Super + Alt + up/down 

This 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/759fa8c2-ab22-4319-836a-31c7cd4e5fb2)
And yes, those modes are some presets for waybar, so try to use the one with workspace numbers first so you can debug accurately. 

+  what changes have you done on your ./userprefs.conf ? 
+ Do you have multi monitor?

**Comment by mahaveergurjar** [comment]
> `hyprctl clients` To see where Firefox go. Also, waybar is buggy (that window feature), don't rely on it too much.
> 
> I usually use workspace module as windows module tends to be unreliable. ![image](https://private-user-images.githubusercontent.com/53417443/313446843-e121ae2f-5a31-458a-9e54-5285bab367e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzMxMTIsIm5iZiI6MTcxMDY3MjgxMiwicGF0aCI6Ii81MzQxNzQ0My8zMTM0NDY4NDMtZTEyMWFlMmYtNWEzMS00NThhLTllNTQtNTI4NWJhYjM2N2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEwNTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzOWU0YjQ5NTExN2M1YmQ3NWE0MmQ5Yjc0OWZiNDE4MjhlZTA0YTE2ZTUxM2FjMzgyMDE0ZjMzY2U1MzA5M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2uA8JeqIc1MchcKlvr5zsDxacjH5jqCOlQG1rGrlL2w)

can you send this module that you are customise

**Comment by blankRiot96** [comment]
@kRHYME7 So I tried the workspace module rather than the windows mode, but as you can see the `1` workspace is still locked regardless of what I do
As I said the workspace which is locked seems to be randomly changing, but it may be worth noting that usually on starting the computer the 1st workspace is usually locked instead

> what changes have you done on your ./userprefs.conf?

None

> Do you have multi monitor?

No, just an acer monitor connected to my laptop

Here is the video of my using the workspace module instead, and **1 is locked and not being switched to**

https://github.com/prasanthrangan/hyprdots/assets/77634274/2e6f8d7a-9ec9-445b-a2fe-a9ca6469c619

**Comment by blankRiot96** [comment]
@kRHYME7  Yes, so after further research on this issue I have figured out that yes it is indeed due to the workspace being binded to a different monitor: https://wiki.hyprland.org/Configuring/Workspace-Rules/#rules

However, I cannot find a `monitor:` instance in my `.config/hypr/`, so I'm not sure where and how this was binded.

**Comment by blankRiot96** [comment]
Okay, so I've solved this by disabling the laptop monitor! Thank you for the hints and support

**Comment by UcraNerd** [comment]
> Okay, so I've solved this by disabling the laptop monitor! Thank you for the hints and support

what did you do?
