### ISSUE TITLE
[Bug]: Rofi Window Switcher isn't working

### ISSUE THREAD

**Issue by MostlyKIGuess** [prasanthrangan/hyprdots#1106]
## Bug Report
- So doing win + tab to open the Rofi windows switcher , it does open the tab but when I click on other applications it basically does nothing.

### Steps to Reproduce

1. Run windows switcher by either writing 
```
rofi -show window
```
or just win + tab.
2. Click on any window
3. and so it does nothing

### Expected Behavior

It should switch to that workspace when I click on that application.

### Actual Behavior

Nothing happens :(

### Environment

- Linux Distro: [ArchLinux]
- Linux Version, output of `uname -a`: Linux archlinux 6.7.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch main at commit cb258c82f4fa3276ad9b2e2dfc1243e8ee683b2c  (assets: update tetrahedra by honkadaloonga).
Date: Sat Feb 10 22:53:27 2024
Tag: v0.35.0-12-gcb258c82

flags: (if any)

- Installation Environment: Main Hardware

**Comment by kRHYME7** [comment]
@MostlyKIGuess I reopened the Older thread
