### ISSUE TITLE
Hyprland.conf doesnt change system

### ISSUE THREAD

**Issue by pedestrianzone** [prasanthrangan/hyprdots#1107]
## Description

Everything works flawlessly, BUT I cannot make any changes to the config. Changes in `~/hyprdots/Configs/.config/hypr/hyprland.conf` do not apply to the system.

For example I changed the keyboard layout to `de`, yet it remains `us`. I also tried mapping the terminal to another keybind, however it remains the same. Help is appreciated, surely I've missed something, I'm new here.

### Expected Behavior

Changes in the hyprland.conf and other .conf files change the system accordingly.

### Actual Behavior

The system remains the same, regardless of any changes in the hyprland config files.

**Comment by kRHYME7** [comment]
Change your configurations inside ``` ~/.config/hypr/ ```

**Comment by pedestrianzone** [comment]
Well, as expected, I missed the obvious, this solves my issue. Thank you for the insanely quick support!

**Comment by RookiexCookie** [comment]
Hey , if this is solved please closed the issue
