### ISSUE TITLE
[Bug]: Theme shortcut not updating itself

### ISSUE THREAD

**Issue by MostlyKIGuess** [prasanthrangan/hyprdots#1109]
### Description
- After updating to the latest version and patching the extra themes , when I try to select those using win + shift + T , the new themes don't show up but when I type "Hyprdots theme select" in the terminal it works perfectly fine and shows me the themes,

### Steps to Reproduce

- Try updating it and it will occur I guess, or just updating the theme patcher.

### Expected Behavior

- On pressing Win + shift + T it should update on the themeswitcher window as well.   

### Actual Behavior

- It works from the terminal command so it's not a themepatcher problem, but rather a script that involves in patching the current theme to aliases.

### Screenshots

- Pressing Win + shift + T :
![image](https://github.com/prasanthrangan/hyprdots/assets/135974627/a8b5bf63-04c8-4691-8f9f-2b4ca08e9034)
- Writing Hyprdots theme select :
![image](https://github.com/prasanthrangan/hyprdots/assets/135974627/c9940b02-6fac-4134-922b-8abbc08cdf49)

**Comment by kRHYME7** [comment]
Did you remove ~/.config/hypr/scripts? #1051

**Comment by MostlyKIGuess** [comment]
- No it's there as well as my wallbash is working , I did rebuild the cache as well.
- It was not working before but rebuilding the cache fixed it.

**Comment by kRHYME7** [comment]
> No it's there as well as my wallbash is working  

If it is there remove it please 
new directory is at ``` ~/.config/hyprdots/scripts? ``` same goes to wallbash

**Comment by MostlyKIGuess** [comment]
- Works after replacing the files from hyperdots folder to hypr. Thanks a lot!
