### ISSUE TITLE
[Help]: Replacing default applications & tiling issues 

### ISSUE THREAD

**Issue by jlengelbrecht** [prasanthrangan/hyprdots#1110]
I primarily use Librewolf and Warp as my default browser and terminal. 
I was not able to find anything in the docs on how I can go about changing out the current defaults (kitty & brave) 

While poking around the web I found mention of editing ~/.config/hypr/hyprstart & mimeapps.list
https://forum.garudalinux.org/t/change-default-internet-browser/33948/4

However when i attempt to do so there is no ~/.config/hypr/hyperstart and the mimeapps.list does not contain anything regarding browser settings that I can see either. 

How can I go about replacing both with the desired default apps? 

Additionally, Warp Terminal does not seem to snap tile like most other apps do.
When opened it always opens in the center of the screen as a floating app. 

How can I go about fixing this?

**Comment by se7en-x230** [comment]
I would also be in favor to be able to have an easy way to overwrite the defaults without editing the main hyprland.config file.

**Comment by mahaveergurjar** [comment]
For Browser use this command 

```shell
xdg-settings set default-web-browser firefox.desktop
``` 

For default application for a file type, you can just right click on a file of that type, select properties and change it there. This will apply the settings according to the xdg standards and from this point this will be the default application for that file type for the whole system.
 
![240319_00h18m49s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/10ffe278-c846-4224-8dac-57b2a13b8b7d)
![240319_00h19m27s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/0326cfdc-bbeb-4316-ae48-34a1059dfa51)
![240319_00h20m23s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/ebb93b5b-ede1-46bf-a93c-51a62a3640bb)

**Comment by jlengelbrecht** [comment]
> ```shell
> xdg-settings set default-web-browser firefox.desktop
> ```

Running this returns the following: 
```
❯ xdg-settings set default-web-browser librewolf.desktop
xdg-settings: $BROWSER is set and can't be changed with xdg-settings
```

On the site I linked above  it talks about needing to modify  `~/.config/hypr/hyprstart & mimeapps.list` but one of these doesn't exist and the one that does `mimeapps.list` does not mention anything pertaining to the browser. 

I guess my question is how can I replace brave in the hyprland config created by the installer bash script?. 
I have no clue where its setup and poking around has just lead to more confusion.

**Comment by mahaveergurjar** [comment]
```
mimeapps.list 
``` 
are available in 
```shell
~/.config/mimeapps.list
``` 

![240319_08h22m59s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/6197990e-7e64-4a38-b88d-601f6db6cb69)
![240319_08h23m34s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/f83b3baa-55b8-40ca-8e06-a99931747237)

And install this application for GUI version to change the default apps

**Comment by RWayne93** [comment]
@jlengelbrecht are you able to get warp terminal to switch colors when you change your theme if so whats your config setup like?

**Comment by mahaveergurjar** [comment]
I am not use warp terminal but you can conf warp terminal on the bases of theme base or wallpaper base go to hyde and check the Wallbash conf of are you able to get warp terminal to switch colors when you change your theme if so whats your config setup like? terminal that you can see and take Idea how the walpaper base the work

**Comment by RWayne93** [comment]
not sure where i would add it. been looking around the project structure here on github and its still unclear to me. but thanks ill keep looking around.

**Comment by rubiin** [comment]
some applications can be changed via mimelist while some can be done via `hyper.conf` .

**Comment by kRHYME7** [comment]
Can you please elaborate more on what you meant of being default?

> [!NOTE]
> You can't find anything helpful in ~/.config/hypr/*. Hyde only set the default  keybinding `  ~/.config/hypr/keybindings.conf `. There is no such thing as hyprstart here. However if you want to know what command are executed upon opening Hyprlad, here 
https://github.com/prasanthrangan/hyprdots/blob/37da06d3867671134186581453a7da00ea520a4b/Configs/.config/hypr/hyprland.conf#L27C1-L41C1

 **default keybinds?** 
https://github.com/prasanthrangan/hyprdots/blob/37da06d3867671134186581453a7da00ea520a4b/Configs/.config/hypr/keybindings.conf#L12C1-L15C19

**Default popups/ executions ?**
Modify mime list  or do it with a GUI. :

*example:*  Browsers ask you to be set as default.
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/e454f549-7e39-4ecd-b76f-19266ce110e6)


Using dolphin:
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/6ef7f462-024f-419a-acae-e43c4b12b1e9)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/679b96a8-8307-41ba-baf2-7e7a6de68494)

These are GUI based suggestions, and they are capable fof setting the mimelist for you

 
I also did not read the wiki but here's some link. 

https://wiki.archlinux.org/title/XDG_MIME_Applications
https://wiki.archlinux.org/title/default_applications

Mime list

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a1678aa4-69ad-4778-b226-04d3b4f908fc)

**Comment by kRHYME7** [comment]
BTW about warp. How did you install it? 
flatpak ? or from pacman ?

**Comment by RWayne93** [comment]
@kRHYME7 paru. which i guess would be pacman.

**Comment by kRHYME7** [comment]
@RWayne93  I can't find warp terminal in AUR what is the package name you installed?

**Comment by RWayne93** [comment]
@kRHYME7 it use to be a different package on the AUR but then it disappeared so I actually just pulled the .pkg.tar.zst from warp.dev and then after that I'm able to update it through paru and the package on my machine is listed as warpdotdev/warp-terminal

You can find it with paru or pacman-Ss warp-terminal

**Comment by rubiin** [comment]
I think can be closed. Also for questions discussions are better compared to issue :)

**Comment by kRHYME7** [comment]
Lemme put this here too

warp terminal wallbash template
https://github.com/HyDE-Project/terminals-hyde/tree/main/warp
