### ISSUE TITLE
[Bug]: Cannot mount Appimage, please check your FUSE setup.

### ISSUE THREAD

**Issue by DhilipanCodes** [prasanthrangan/hyprdots#1113]
### Description
When trying to run a appimage, it always seems to produce the error to check your FUSE setup

### Steps to Reproduce

1. Install Hyprdots
2. Install fuse2 and fuse3
3. Run the appimage

### Expected Behavior

Appimage should have opened and work properly (seemed to work fine in previous hyprdot setups.

### Actual Behavior

Error: Cannot mount Appimage, please check your FUSE setup.

### Screenshots
https://imgur.com/a/bycOolb

### Environment
Fresh Hyprdots install on archlinux.

e.g.,

- Linux Distro: Arch linux
- Linux Version, Linux root 6.8.1-1, x86_64 GNU/Linux
- Hyprland Version, v0.35.0
- Installation Environment: Laptop with i5-8250U
- Other info: Display Resolution - 1900x1200

### Additional Information

Self explanatory, I tried it on my older hyprdots setup and It worked fine. Also, when trying to install the lib32 of fuse2 (using paru), A error (C compiler cannot create executables) pops up.

**Comment by Enigma1309** [comment]
Right click on the app and click properties, then in permissions tab allow executable
![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/e75623ab-5aaa-46e2-a3a3-24c5dd345299)


or try to launch it via terminal by `./whateverapp.appimage`

**Comment by DhilipanCodes** [comment]
tried it, still same issue

**Comment by kRHYME7** [comment]
@DhilipanCodes  What appimage are you trying to run. I'll try to test on my end.

**Comment by NawreCode** [comment]
@kRHYME7 you can try with `devpod` (installed without issue using `yay`), I've encountered the exact same issue with that app on a fresh install I've done yesterday.

**Comment by kRHYME7** [comment]
> @kRHYME7 you can try with devpod (installed without issue using yay), I've encountered the exact same issue with that app on a fresh install I've done yesterday.

If you read the PKGBUILD ``` depends=('fuse2') ``` .  So devpod needs fuse2. After installing ``` fuse2 ``` it should run.

**Comment by kRHYME7** [comment]
@DhilipanCodes  can you show the full terminal output?

**Comment by DhilipanCodes** [comment]
Sorry for late replies. For @kRHYME7 questions, any appimage does not work and as far as I'm aware the terminal only displays that error. When ran, a notification appears which can be found in the screenshots. When ran using the terminal, only that error appears.

**Comment by kRHYME7** [comment]
okie

I can't replicate it 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a0456c04-fe26-4fa2-8812-12897daffdc6)

How did you run your appimage? a full terminal output will be appreciated.

**Comment by NawreCode** [comment]
Ok, I did try to download the AppImage directly and indeed, that one is working.

But the AUR package isn't. However I tried on a X11 DE (i3wm) on another computer and it's not working either. Sooooo... looks like it has nothing to do with Hyperdot, my bad 😓

**Comment by kRHYME7** [comment]
> But the AUR package isn't. 

I think the PKGBUILD is broken, you can directly report it as flag out of date or not working so the maintainer can take actions. 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/59fcbb9d-ee87-4b2f-a0ea-5d1539269786)

**Comment by DhilipanCodes** [comment]
> > But the AUR package isn't.
> 
> I think the PKGBUILD is broken, you can directly report it as flag out of date or not working so the maintainer can take actions.
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/316808020-59fcbb9d-ee87-4b2f-a0ea-5d1539269786.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDEyNzYsIm5iZiI6MTcxMTk0MDk3NiwicGF0aCI6Ii81MzQxNzQ0My8zMTY4MDgwMjAtNTlmY2JiOWQtZWU4Ny00YjJmLWEwZWEtNWQxNTM5MjY5Nzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAzMDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NWM4MTA0MzNhZDQxODJiYzlhMjI4NjE4MDQ3ZjNhZGY4YTc3ZGZkY2U1ZjEzYThiZTdiYTg4OWM1MTQxZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IHJNFLP8-D4tmi7Tt7YdEyjox5sKKB0WQwFwSxcfZks)

No, all appimages don't work until I extract and run it.

**Comment by DhilipanCodes** [comment]
> okie
> 
> I can't replicate it
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/316792554-a0456c04-fe26-4fa2-8812-12897daffdc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDEyNzYsIm5iZiI6MTcxMTk0MDk3NiwicGF0aCI6Ii81MzQxNzQ0My8zMTY3OTI1NTQtYTA0NTZjMDQtZmUyNi00ZmEyLTg4MTItMTI4OTdkYWZmZGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAzMDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3N2RjM2MyNDkwMDI1NzEyODU3Y2FmOWJjYmZlNThhZGZhM2M1YmMwOWYwOGVhZjVlMWMxODM1NTI2MzA5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UUd-D27XxUV9F-vKq7y9USBDMX3cplXS-6ejYZCBojU)
> 
> How did you run your appimage? a full terminal output will be appreciated.

Oh, suddenly fixed now??? I didn't even do anything to modify it expect upgrading my packages. I guess fixed?

**Comment by DhilipanCodes** [comment]
Now fixed
