### ISSUE TITLE
[Bug]:  clipboard not deleting

### ISSUE THREAD

**Issue by its-19818942118** [prasanthrangan/hyprdots#1116]
### Description

so its been around 3 days. but i recently noticed that i am unable to delete clipboard entire history. not even a single line. i checked the documentaion on github page. but that just doesnt have anythig to do with clipboard. i have some highly secret passwords that i want to delete. but it just clutters up. i checked the shell script but that doesnt lead to anywhere. pls help me or in future make it so that clipboard history is saved in a txt file.

### Steps to Reproduce

1. [First Step]

>  copy something

2. [Second Step]

> open up clipboard

3. [Third Step]

> delete unwanted stuff

### Expected Behavior

well like on rofi launcher i assumed using _**`Shift + Delete`**_ removes it from history.

### Actual Behavior

it did not thing. i tried everysingle possible option but it just doesnt do it 

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment
- Linux Distro: [ **`EndeavourOS`** ]
- Linux Version, output of `Linux *Hostname:Aurora* 6.7.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000 x86_64 GNU/Linux`:
- Hyprland Version, output of `Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0`:
- Installation Environment: [`Bare Metal`]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by kRHYME7** [comment]
It's not how it works

Are you using this command?  ``` ~/.config/hyprdots/scripts/cliphist.sh d ``` 

adding ``` d ``` as flag well launch rofi on delete mode 

Alternative:

``` Hyprdots show pastebin c ``` 

on the last part of the list you can Select ``` Delete ``` option then delete mode will lauch. 

> [!Note]
> To mark a selection use ``` shift + enter ``` 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/787e0147-4ea7-4730-b730-d8adff59cde8)

**Comment by mahaveergurjar** [comment]
You can also used the waybar module click on waybar clipboard module with three fingers  clear  clipboard history option are show and click with two finger then show delete in clipboard 
![240319_21h55m38s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/3a29b6cd-b371-4dcf-9787-833f0a20feb4)
![240319_21h55m38s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/b2745199-40a3-451a-806a-acdf12fffbdf)

some thing you can do by Hyprdots-ctl using this command
```shell
Hyprdots show pastebin w
``` 
![240319_21h56m30s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/69af67c9-07fb-4c42-a2e1-e1c8da02fbd9)

**Comment by its-19818942118** [comment]
how to do it i am stupid.
this is `~/.config/hypr/keybindings.conf`
`bind = $mainMod, V, exec, pkill -x rofi || $scrPath/cliphist.sh c  # open Pasteboard in screen center`

and no it doesnt work with `super + v` then `shift + enter` i need to use the terminal to do it.
pls tell me a fix cuz going to the terminal to delete all the time can be kinda annoying

**Comment by its-19818942118** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/87006850/4940d7fa-f9ca-4d17-95a5-ceba774c3ee3)
`super + v` outputs this. then shift enter dont work. and its on search mode so `d` dont work

**Comment by kRHYME7** [comment]
> bind = $mainMod, V, exec, pkill -x rofi || $scrPath/cliphist.sh c  # open Pasteboard in screen center

Change above into 


```  bind = $mainMod, V, exec, Hyprdots show pastebin c  # open Pasteboard in screen center ```

This is the repo for the Hyprdots CLI  commands

https://github.com/kRHYME7/Hyprdots-ctl

**Comment by its-19818942118** [comment]
ok but wont it hinder pasting ability?

**Comment by its-19818942118** [comment]
> > bind = $mainMod, V, exec, pkill -x rofi || $scrPath/cliphist.sh c  # open Pasteboard in screen center
> 
> Change above into
> 
> ` bind = $mainMod, V, exec, Hyprdots show pastebin c # open Pasteboard in screen center`
> 
> This is the repo for the Hyprdots CLI commands
> 
> https://github.com/kRHYME7/Hyprdots-ctl

thanks i will give it a try

**Comment by its-19818942118** [comment]
> That's not how this work.
> 
> Are you using this command? `~/.config/hyprdots/scripts/cliphist.sh d`
> 
> adding `d` as flag well launch rofi cliphist on delete mode
> 
> Alternative:
> 
> `Hyprdots show pastebin c`
> 
> on the last part of the list you can Select `Delete` option then delete mode will lauch.
> 
> Note
> 
> To mark a selection use `shift + enter`
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/314028388-787e0147-4ea7-4730-b730-d8adff59cde8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjAyNjQsIm5iZiI6MTcxMDkxOTk2NCwicGF0aCI6Ii81MzQxNzQ0My8zMTQwMjgzODgtNzg3ZTAxNDctNGVhNy00NzMwLWI3MzAtZDhhZGZmNTljZGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA3MzI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YTQ2YjRlNWMyYTRlMTZjNjFmYjEyMzEwNTQ4NmE5NjJiNTg5YjU2OGYyMjE5YjcwMDlkZmNiZjQzNjFlMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NKj9NDJLe-Rn8q3pPClMDB0cz4BfWGdKYLypMe8zxOQ)

yeah update... it didnt work cuz i thought it did but it was still there

**Comment by its-19818942118** [comment]
also where are the clipboard history saved to?

**Comment by kRHYME7** [comment]
Press enter to confirm

https://github.com/prasanthrangan/hyprdots/assets/53417443/fcf42a87-a44f-4dcf-b1bf-415257e1fcd2

**Comment by its-19818942118** [comment]
oh it worked thanks so much and sorry for the trouble. by the a feat request in the future make keybindings choosing option interactive. and the keyboard shortcuts instead of clicking. it will be help full. and on first install. nofication to show the keybindings :) i have a bunch of feature requests. but i dont know how to implement it
