### ISSUE TITLE
[Bug]: Stuck at booting

### ISSUE THREAD

**Issue by t101804** [prasanthrangan/hyprdots#1117]
### Description

Cant boot into the linux

### Steps to Reproduce

1. Install vmware

### Expected Behavior

entering linux

### Actual Behavior

Stuck

### Screenshots

[![IMG-20240319-WA0293.jpg](https://github.com/prasanthrangan/hyprdots/assets/113588203/02f15e03-3bd6-4858-9630-5c151eb19c08)

![IMG_20240319_193027.jpg](https://github.com/prasanthrangan/hyprdots/assets/113588203/455f1691-4d79-4302-855c-3e019a011e5f)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: Arch linux
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`: latest
- Installation Environment: Main hardware
- Other info: Nvidia rtx 3060 , Monitor 1920 144hz

### Additional Information

I cant get into the arch linux or opening Hyprland after installing vmware. also when i want to update ( when i stuck i can get into tty by pressing ctrl alt f2 )

**Comment by t101804** [comment]
> how did you configure your system and vmware  ?
> 

also before downloading vmware , i downgrading my nvidia-dkms and nvidia utils and other nvidia to 525 to fix the stuttering issue on electron apps

**Comment by kRHYME7** [comment]
> ( when i stuck i can get into tty by pressing ctrl alt f2 )

+Can you still access tty?
see if your nvidia is correctly loaded. 

if not,
+ Can you chroot?  >>> Live usb then >>> arch-chroot >>> Try to see if nvidia is loaded , or just try to update your system.

Ask help here to revive your system: 
https://archlinux.org
https://www.reddit.com/r/archlinux/

**Comment by t101804** [comment]
> > ( when i stuck i can get into tty by pressing ctrl alt f2 )
> 
> +Can you still access tty? see if your nvidia is correctly loaded.
> 
> if not,
> 
>     * Can you chroot?  >>> Live usb then >>> arch-chroot >>> Try to see if nvidia is loaded , or just try to update your system.
> 
> 
> Sadly this Repo is for dot files only and eyecandy, this seemed unrelated. Ask help here to revive your system: https://archlinux.org https://www.reddit.com/r/archlinux/

nvm its solved already by reinstalling nvidia-dkms . seems its problem when i downgrading nvidia-dkms and nvdia-utils to version 535. but how i downgrade then?

![image](https://github.com/prasanthrangan/hyprdots/assets/113588203/282660f6-aca8-43db-9d08-41049e6180e0)

**Comment by kRHYME7** [comment]
Have you tested 550?

**Comment by CYCLOP5** [comment]
550 works fine for me no stutters at all
