### ISSUE TITLE
[Bug]: After updating this line showed up.

### ISSUE THREAD

**Issue by nvn152** [prasanthrangan/hyprdots#1123]
![240319_22h45m45s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/133593113/2c10068d-553b-4a79-a6e7-3f8366b59567)

### Description

[Provide a clear and concise description of the bug.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by kRHYME7** [comment]
Already fixed 828c1324c502dbc4f1ca72a90cb0fb2a6d39bca0

**Comment by Skerse** [comment]
Hyprland just updated in the main repo today, which introduced a dependency to hyprlang, please update to this commit:  https://github.com/prasanthrangan/hyprdots/commit/828c1324c502dbc4f1ca72a90cb0fb2a6d39bca0 to  fix.
