### ISSUE TITLE
[PLEASE]: Adjust hyprland.conf for Hyprland  > 0.36.

### ISSUE THREAD

**Issue by rubairakib** [prasanthrangan/hyprdots#1126]
![240320_10h26m10s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/149327362/0b903527-c6ac-4026-a1fa-232fb77ed311)
### Description

Error massage on the screen.

### Steps to Reproduce

1. Click on package update button on the waybar
2. Asked to exclude some packages, forgot to progress any further for some reason
3. When turning on the machine next time got the error massage showed on the ss

### Expected Behavior

Get rid of the error

### Screenshots

Added.

e.g.,

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux archlinux 6.6.22-1-lts #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 06:20:33 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)

- Installation Environment: On The Main Hardware

### Additional Information

The ss says it all

**Comment by kRHYME7** [comment]
Fix your config or pull latest Hyprdots commit

https://github.com/prasanthrangan/hyprdots/pull/930

**Comment by slowayy** [comment]
or do this 
cd ~/Hyprdots/Scripts
git pull
./install.sh -r

but all the configs do you changed before gon be changed to default of repo

**Comment by its-19818942118** [comment]
all right i dont understand so pls help me

**Comment by its-19818942118** [comment]
i dont have git.conf on the dir so i cant pull i need to manually do it

**Comment by its-19818942118** [comment]
> Thanks for the notice, as you can see fix are now merged.
> 
> Fix your hyprland.conf or pull latest Hyprdots commit
> 
> Also, it is advisable to read the error
> 
> #930
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/314383285-85e4acbb-cf9a-4f59-965e-8cac4f731121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDE5ODQsIm5iZiI6MTcxMTAwMTY4NCwicGF0aCI6Ii81MzQxNzQ0My8zMTQzODMyODUtODVlNGFjYmItY2Y5YS00ZjU5LTk2NWUtOGNhYzRmNzMxMTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA2MTQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NDJmMmJiMmM3NmJjMGY0ZWI5ZWRkMTA5OTcyM2JhMTg4N2ZiYjFiYmFjYzhjYWQ1OGE2ZWExODBlZmVjMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YK1uINgu6aSEjkZhDLH1iOHX7LOwg684mq_6C7ATALE)
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/314383405-49b7618e-b5d2-47fb-8a57-cb3277b628fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDE5ODQsIm5iZiI6MTcxMTAwMTY4NCwicGF0aCI6Ii81MzQxNzQ0My8zMTQzODM0MDUtNDliNzYxOGUtYjVkMi00N2ZiLThhNTctY2IzMjc3YjYyOGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA2MTQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMTZlNTBmZDU5NTEzMGNhMGY1MmUyYjg2NTQ3ZTgwYTg5ZmYwODhhNmIxMjJmOWY3ZmIyYTE2ZGNlMGFjNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CFszuimsZSZkWVn4s8BM1Ome-dA2e33RYbw1jAS1uYQ)

i dont understand device thing pls explain

**Comment by kRHYME7** [comment]
> i dont understand device thing pls explain....

Just remove that, you don't need that configuration either. 

> i dont have git.conf on the dir so i cant pull i need to manually do it

Try to run ``` Hyprdots update ``` 

what does it says?

**Comment by blackpysc** [comment]
i got 3 line problem
line 1 , line 5 and line 83 

just comment the line 83 and uncomment line 1-5 and comment it again 
solved
if im only comment the line 83 the line 1 and 5 still says error ,
so i just make it uncomment first and comment again

**Comment by its-19818942118** [comment]
> > i dont understand device thing pls explain....
> 
> Just remove that, you don't need that configuration either.
> 
> > i dont have git.conf on the dir so i cant pull i need to manually do it
> 
> Try to run `Hyprdots update`
> 
> what does it says?
```
CloneDirectory: /home/izumi/hyprdots
Git URL: git@github.com:prasanthrangan/hyprdots.git
Git Branch: main



remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 121 (delta 70), reused 80 (delta 63), pack-reused 18
Receiving objects: 100% (121/121), 45.18 KiB | 114.00 KiB/s, done.
Resolving deltas: 100% (71/71), completed with 36 local objects.
From github.com:prasanthrangan/hyprdots
   876c918..26f8e96  main       -> origin/main
Updating 876c918..26f8e96
Fast-forward
 Configs/.config/hypr/hyprland.conf                  |  20 +++--
 Configs/.config/hypr/userprefs.t2                   |   1 +
 Configs/.config/hypr/windowrules.conf               |   3 +-
 Configs/.config/hyprdots/scripts/gamelauncher.sh    |  82 +++++++++++++-------
 Configs/.config/hyprdots/scripts/gpuinfo.sh         |   2 +-
 Configs/.config/hyprdots/scripts/keybinds_hint.sh   |   6 +-
 Configs/.config/hyprdots/scripts/swwwallbash.sh     |   1 +
 Configs/.config/hyprdots/scripts/themeswitch.sh     |   2 +-
 Configs/.config/hyprdots/scripts/volumecontrol.sh   |   7 +-
 Configs/.config/hyprdots/scripts/wallbashdiscord.sh |  25 ++++---
 Configs/.config/hyprdots/scripts/wbarstylegen.sh    |   2 +-
 Configs/.config/hyprdots/wallbash/discord.dcol      | 235 +++++++++++++++++-----------------------------------------
 Configs/.config/libinput-gestures.conf              |  19 +++++
 Configs/.config/rofi/keybinds_hint.rasi             |  99 -------------------------
 Configs/.config/waybar/config.jsonc                 |   3 +-
 Configs/.config/waybar/modules/keybindhint.jsonc    |   2 +-
 Configs/.config/waybar/modules/power.jsonc          |   1 +
 Configs/.config/waybar/style.css                    |   2 +-
 Configs/.zshrc                                      |  23 ++++--
 README.md                                           |   2 +-
 Scripts/.extra/custom_flat.lst                      |   8 +-
 Scripts/.extra/drivext_mnt.sh                       |  34 +++++++++
 Scripts/.extra/install_fpk.sh                       |  18 ++---
 Scripts/.extra/mnt_drives.lst                       |   2 -
 Scripts/.extra/mnt_drives.sh                        |  71 ------------------
 Scripts/{.extra => .old}/install_hyp.sh             |   0
 Scripts/create_cache.sh                             |  18 +++--
 Scripts/custom_apps.lst                             |   6 +-
 Scripts/custom_hypr.lst                             |   3 +-
 Scripts/global_fn.sh                                |  63 +++++++---------
 Scripts/install.sh                                  | 107 +++++++++++++++-----------
 Scripts/install_aur.sh                              |  30 ++++----
 Scripts/install_pkg.sh                              |  80 +++++++-------------
 Scripts/install_pre.sh                              |  13 ++--
 Scripts/install_pst.sh                              |  25 ++++---
 Scripts/restore_cfg.lst                             |   1 +
 Scripts/restore_cfg.sh                              |  32 ++++----
 Scripts/restore_fnt.sh                              |  17 +++--
 Scripts/restore_lnk.sh                              |  17 +++--
 Scripts/restore_shl.sh                              |  31 ++++----
 Scripts/themepatcher.sh                             |  60 +++++++++------
 Source/arcs/Firefox_UserConfig.tar.gz               | Bin 3608 -> 3807 bytes
 42 files changed, 505 insertions(+), 668 deletions(-)
 mode change 100755 => 100644 Configs/.config/hyprdots/scripts/gamelauncher.sh
 create mode 100644 Configs/.config/libinput-gestures.conf
 delete mode 100644 Configs/.config/rofi/keybinds_hint.rasi
 create mode 100755 Scripts/.extra/drivext_mnt.sh
 delete mode 100644 Scripts/.extra/mnt_drives.lst
 delete mode 100755 Scripts/.extra/mnt_drives.sh
 rename Scripts/{.extra => .old}/install_hyp.sh (100%)
```

**Comment by kRHYME7** [comment]
@its-19818942118  do you have changes in your own configurations? 

if not you can run ``` Hyprdots restore defaults ```

It will ask you what to preserve, to sync and to overwrite. 

BTW before proceeding what errors do have?

**Comment by jenil1122** [comment]
do u still have the error?
share the output for ``` cat ~/.config/hypr/hyprland.conf     ```
