### ISSUE TITLE
[Bug]: Rofi doesn't toggle off when pressed keybinds (super + A)

### ISSUE THREAD

**Issue by Ace-c** [prasanthrangan/hyprdots#1131]
# Description

It is mention in keybindings.config is that, Rofi is toggled on/off if you repeat the key presses which is " super + A ". But it is not working anymore, The problem arrived when I'm tweaking style config. but I don't think so style.css is anything do with it.

Wlogout working fine
Clipboard have same issue
rofilaunch and rofiselect have same issue

**Comment by kRHYME7** [comment]
What will happen if you press ESC? 


Let,s try to test first. 

Run this command then right after open any rofi window
```
sleep 3 && pkill rofi
```
let's see if rofi exits

**Comment by Ace-c** [comment]
> What will happen if you press ESC?
> 
> Let,s try to test first.
> 
> Run this command then right after open any rofi window
> 
> ```
> sleep 3 && pkill rofi
> ```
> 
> let's see if rofi exits

It's working now using esc but still have the issue with super + A, Anyway thanks for quick reply

**Comment by kRHYME7** [comment]
I remember this issue, try to update your rofi. This is an issue where when rofi layer is present you cannot use your hyprland shortcut. 

This is the latest rofi version I got.
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/f25eb71b-8eb5-45a5-85b2-fd14369307e6)

**Comment by Ace-c** [comment]
> I remember this issue, try to update your rofi. This is an issue where when rofi layer is present you cannot use your hyprland shortcut.
> 
> This is the latest rofi version I got. ![image](https://private-user-images.githubusercontent.com/53417443/314605704-f25eb71b-8eb5-45a5-85b2-fd14369307e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTY0MDYsIm5iZiI6MTcxMDk1NjEwNiwicGF0aCI6Ii81MzQxNzQ0My8zMTQ2MDU3MDQtZjI1ZWI3MWItOGViNS00NWE1LTg1YjItZmQxNDM2OTMwN2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDE3MzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3OWZiNGM5ODI0MGFlNGI4NjRmYjFhYzQ4MWJlZGJmZDQxYTgzYjNjODhmMjFjZThjM2Q0ZTEzZDdkNTMwMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dioIVrsqvknr195-o56Y3mONPtJRoSUf6vjjP531-mE)

Ohh so that's the issue, got it
