### ISSUE TITLE
[Bug]: UI Notification BUG

### ISSUE THREAD

**Issue by t101804** [prasanthrangan/hyprdots#1135]
### Description

[Provide a clear and concise description of the bug.]

### Steps to Reproduce

1. Get notification
2. Black notification

### Expected Behavior

Normal notification

### Actual Behavior
Blank/Black notification

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/113588203/7235730e-d1f8-4716-82b9-088be9ffbf91)
Sound notification ( the bug )
![image](https://github.com/prasanthrangan/hyprdots/assets/113588203/2aacc228-ef24-423d-8d45-96b27fca56f6)

### Environment

- Linux Distro: Arch

**Comment by kRHYME7** [comment]
Hi, this is a dupe https://github.com/prasanthrangan/hyprdots/issues/1080
