### ISSUE TITLE
[Bug]: Waybar crash by clicking on taskbar app icon

### ISSUE THREAD

**Issue by ALEX5402** [prasanthrangan/hyprdots#1136]
### Description
-  Waybar crashes when i click into the app icon on the waybar 3 to 4 times
- here is the taskbar [config](https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/waybar/modules/taskbar.jsonc) for waybar
- waybar version  v0.10.0
- ik its a bug of waybar so i also made a [issue](https://github.com/Alexays/Waybar/issues/3053) on waybar repo

### Steps to Reproduce

1. run waybar from anywhere you like 
2. just click on the taskbar app icon which one is running 
3. and suddenly waybar crashes after click 2 or 3 times on any app icon

### Expected Behavior
- its need to be focus to the clicked application

### Actual Behavior
- it crashes the waybar

### Here is a video how it happens

https://github.com/prasanthrangan/hyprdots/assets/76860596/958ffae0-54ad-4754-ba1e-47cbabb0999a

### Environment

- EndeavourOS Linux x86_64
- 6.8.1-zen1-1-zen 
- Installation Environment On my Main Hardware 
- AMD Ryzen 5 5500GT with Radeon Graphics (12) @ 4.457GHz
- Resolution : 1920x1080 
- here is my all installed packages 
[packages.txt](https://0x0.st/Xrvz.txt)

### Additional Information
- here is the [logs](https://pastebin.com/raw/XipySYgZ)

**Comment by ffoebel** [comment]
Alexays/Waybar#2032

**Comment by ALEX5402** [comment]
> [Alexays/Waybar#2032](https://github.com/Alexays/Waybar/issues/2032) The described workaround works for me, I’ll keep it until the next release.

ok

**Comment by Andrjs** [comment]
> > [Alexays/Waybar#2032](https://github.com/Alexays/Waybar/issues/2032) The described workaround works for me, I’ll keep it until the next release.
> 
> in which part of the hyprland.conf do i have to add this `no_cursor_warps = true` it gives errors at input or misc for example.

general {
    no_cursor_warps = true
}

**Comment by Abdullah-Faik** [comment]
> > > [Alexays/Waybar#2032](https://github.com/Alexays/Waybar/issues/2032) The described workaround works for me, I’ll keep it until the next release.
> > 
> > 
> > in which part of the hyprland.conf do i have to add this `no_cursor_warps = true` it gives errors at input or misc for example.
> 
> general { no_cursor_warps = true }

it works thanks
