### ISSUE TITLE
[Bug]: multiple instances of waybar

### ISSUE THREAD

**Issue by rohansharma-developer** [prasanthrangan/hyprdots#1137]
Whenever I try to change the theme, it starts a new way bar instance with the changed theme, but the old waybar instance is still present. And this goes on forever….

**Comment by kRHYME7** [comment]
What is the output for ``` ~/.config/hyprdots/scripts/themeswitch.sh -n ```

**Comment by rohansharma-developer** [comment]
> ~/.config/hyprdots/scripts/themeswitch.sh -n

Selected theme: Rose-Pine
ok
Installing extensions...
Installing extension 'mvllow.rose-pine'...
Extension 'mvllow.rose-pine' v2.9.0 was successfully installed.
[skip] /home/bionic/.config/spicetify/Themes/Sleek
[skip] /home/bionic/.config/cava
/home/bionic/.config/hyprdots/scripts/wallbashkitty.sh: line 15: killall: command not found
/home/bionic/.config/hyprdots/scripts/wallbashdunst.sh: line 14: killall: command not found
/home/bionic/.config/hyprdots/scripts/wbarstylegen.sh: line 131: killall: command not found
eDP-1: 1366x768, scale: 1, currently displaying: image: /home/bionic/.config/swww/Decay-Green/moments_before_desk.png
HDMI-A-1: 1360x768, scale: 1, currently displaying: color: 000000

**Comment by rohansharma-developer** [comment]
seems like the `killall` command is not found....

**Comment by rohansharma-developer** [comment]
The error is fixed, i just installed the "psmisc" package from pacman. Worked magically! Thanks for the help!
