### ISSUE TITLE
access denied to get to hyprland.conf

### ISSUE THREAD

**Issue by gwen-real** [prasanthrangan/hyprdots#1138]
so im trying to fix fractional scaling so that vscode doesnt look so crusty - i go into 

`.config/hypr/hyprland.conf` and am greeted woth 
`zsh: permission denied: .config/hypr/hyprland.conf` 

how fix

**Comment by kRHYME7** [comment]
go ? like edit? can you show a screenshot?

**Comment by gwen-real** [comment]
> go ? like edit? can you show a screenshot?

sure 
![240321_16h48m11s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/164343304/28ea5ab6-5952-4d54-b749-409a525d974f)

**Comment by gwen-real** [comment]
oh hey that worked!! thanks so much
