### ISSUE TITLE
[Feature Request]: Keybind cheatsheet

### ISSUE THREAD

**Issue by marc-hg** [prasanthrangan/hyprdots#1139]
### Description

Users can see a popup cheetsheet with the preset keybindings 

### Use Case

I click on an icon from waybar or do a keybind combination (like holding super button) and a popup shows up with a cheatsheet of the keybindings

### Alternatives

First version could just be the default keybindings instead of dynamic per user

**Comment by kRHYME7** [comment]
Please explore it's already implemented.
