### ISSUE TITLE
[Feature Request]: Spotify installed by default and Spicetify themes linked to OS themes

### ISSUE THREAD

**Issue by marc-hg** [prasanthrangan/hyprdots#1140]
### Description

Spotify installed by default and Spicetify themes linked to OS themes. When switching to a different OS theme, spicetify should change to its matching one.

### Use Case

When switching to a different OS theme, spicetify should change to its matching one.

### Proposed Solution

Could use these themes https://github.com/spicetify/spicetify-themes

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/69079b6b-0d95-48d0-9443-e43abc13576b)


Like this?

**Comment by marc-hg** [comment]
Yeah, and then the theme changes if you switch to a different OS theme (similar to how it does with kitty/firefox/dolphin/etc)

**Comment by kRHYME7** [comment]
It already follows the wallapaper and already implemented.  turn on the feature by  toggling wallbash. 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/b9accf56-7491-4478-b8c8-f7e53e3e899a)

**Comment by kRHYME7** [comment]
PLEASE use the discussion panel if you have queries. 
![Uploading image.png…]()

**Comment by Skerse** [comment]
Spotify shouldn't be installed by default, it's pretty easy to install yourself and is already in `Scripts/custom_apps.lst`.

**Comment by kRHYME7** [comment]
@marc-hg  spotify and spicetify are already available as custom app. 

You just need to follow the installation process.
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/11dc3ab0-1d05-4adf-b7c6-35c60aaf6f4c)

**Comment by kRHYME7** [comment]
Closing this as this feature is implemented already
