### ISSUE TITLE
[Bug]: Unable to Open Links in Browser via Flatpak: Hindering App Functionality

### ISSUE THREAD

**Issue by Itz-Abhishek-Tiwari** [prasanthrangan/hyprdots#1144]
### Description
#I am unable to open links through a Flatpak in the browser. As a result, many apps are currently unusable. For instance, I can't log in to my Figma unofficial wrapper because it requires me to log in through the browser. Can you help me fix this issue?

### Steps to Reproduce

1. Download Figma from Flathub and install it.
2. Attempt to log in to my account through Google login.
3. Observe that nothing happens as the browser fails to open.

### Expected Behavior

I expected the browser to open when attempting to log in to my account through Google login in Figma, allowing me to complete the authentication process.

### Actual Behavior

No action occurs when attempting to log in to my account through Google login in Figma. The browser fails to open, preventing me from completing the authentication process.

### Screenshots
![image](https://github.com/prasanthrangan/hyprdots/assets/69257109/3995df76-8250-4dfd-a8e2-5a536eb35b05)

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`:
  ``` Linux archlinux 6.8.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000 x86_64 GNU/Linux ```

- Hyprland Version, output of `hyprctl version`: 
`Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1
 `
- Installation Environment: On The Main Hardware

**Comment by Enigma1309** [comment]
i can't reproduce the error
please try this :-`xdg-settings set default-web-browser firefox.desktop`
to set firefox as default browser (you can choose other if you prefer that)  and then try to launch the login page

**Comment by Itz-Abhishek-Tiwari** [comment]
Nothing happened. I had previously set Firefox as the default browser, and this is happening with all Flatpak apps. In this scenario, they are unable to open links in the browser.

**Comment by Enigma1309** [comment]
do you have following packages installed?
```
libportal
libportal-gtk3
libportal-gtk4
xdg-desktop-portal-gtk
xdg-desktop-portal-hyprland
```

**Comment by prasanthrangan** [comment]
please try running `~/.config/hyprdots/scripts/polkitkdeauth.sh`, its missing execute permission...

**Comment by Itz-Abhishek-Tiwari** [comment]
> ~/.config/hyprdots/scripts/polkitkdeauth.sh

I don't have any file named 'polkitkdeauth.sh' in the scripts folder

**Comment by Itz-Abhishek-Tiwari** [comment]
> libportal
> libportal-gtk3
> libportal-gtk4
> xdg-desktop-portal-gtk
> xdg-desktop-portal-hyprland

Yes this are install

```❯ pacman -Q libportal
  pacman -Q libportal-gtk3
  pacman -Q libportal-gtk4
  pacman -Q xdg-desktop-portal-gtk
  pacman -Q xdg-desktop-portal-hyprland

libportal 0.7.1-2
libportal-gtk3 0.7.1-2
libportal-gtk4 0.7.1-2
xdg-desktop-portal-gtk 1.15.1-1
xdg-desktop-portal-hyprland 1.3.1-6
```

**Comment by prasanthrangan** [comment]
> I don't have any file named 'polkitkdeauth.sh' in the scripts folder

ah my bad, its from a latest commit... and its not related to your issue.
I'm unable to open links just fine... can you try to run the flatpak app from terminal and share the output.

**Comment by akashgagda** [comment]
Also flatpak discords unable to open link in default browser

**Comment by Itz-Abhishek-Tiwari** [comment]
> please try running `~/.config/hyprdots/scripts/polkitkdeauth.sh`, its missing execute permission...

The issue has been fixed. I copied the file from GitHub and executed it.

In the future, if anyone faces the same issue as me, just copy the file from the above location in the repository, paste it in the same location, give it execution permission, and run it. It will fix the issue. Thank you, Prasanthrangan, for helping me.

**Comment by prasanthrangan** [comment]
cool, glad its fixed!

**Comment by Itz-Abhishek-Tiwari** [comment]
> > I don't have any file named 'polkitkdeauth.sh' in the scripts folder
> 
> ah my bad, its from a latest commit... and its not related to your issue. I'm able to open links just fine... can you try to run the flatpak app from terminal and share the output.

![image](https://github.com/prasanthrangan/hyprdots/assets/69257109/5a957d8a-ae0a-4507-8592-9ea398ac96a3)
