### ISSUE TITLE
[Bug]: buttons on waybar got bigger and everything seems zoomed in after tried to pull the latest commit

### ISSUE THREAD

**Issue by rubairakib** [prasanthrangan/hyprdots#1146]
## Bug Report
buttons on waybar got bigger and everything seems zoomed in after tried to pull the latest commit
### Steps to Reproduce

1. followed the steps mentioned 
2. and tried bunch of stuffs i cant recall

### Expected Behavior

the way it was before 

### Actual Behavior

all the buttons on waybar got bigger, texts in vs code looks glitchy

### Screenshots
![240321_17h44m27s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/149327362/5819a076-f685-4f7e-8bb4-b837e8becbc5)
![240321_17h45m04s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/149327362/4784a9f3-0d9e-4d19-b241-44727cd59a31)

### Environment

e.g.,
- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux archlinux 6.6.22-1-lts #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 06:20:33 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445 (props: bump ver 0.37.1).
- Installation Environment: On The Main Hardware

**Comment by kRHYME7** [comment]
How about editing the waybar size? run, ``` Hyprdots waybar control ``` then it should pop up on vscode.

about vscode run it in wayland 

try experimenting this flags ``` code --ozone-platform-hint=wayland --disable-gpu ```.

Remember to exit all running VS Code instance as flags won't take effect if there is an already running instance

**Comment by rubairakib** [comment]
> How about editing the waybar size? run, `Hyprdots waybar control` then it should pop up on vscode.
> 
> about vscode run it in wayland
> 
> try experimenting this flags `code --ozone-platform-hint=wayland --disable-gpu`.
> 
> Remember to exit all running VS Code instance as flags won't take effect if there is an already running instance

can you please explain the flag thing and how would i do it. I may sound dumb but im just new to all of these.

**Comment by kRHYME7** [comment]
ok

One by one, run the command in the terminal,  be  sure to exit all running vscode sessions.

``` code --ozone-platform-hint=wayland ``` 

If vs code appears invisible
``` code --ozone-platform-hint=wayland --disable-gpu ```

**Comment by rubairakib** [comment]
i think vs code is fixed after i run that flag but the zoomed in issue is still there

**Comment by kRHYME7** [comment]
only way bar is zoomed? run this, ``` Hyprdots waybar control ``` then find the row with 1 as the 1st field. modify the 2nd field to suit the sizes you want 


https://github.com/prasanthrangan/hyprdots/assets/53417443/d1f5f855-07a0-4f2a-a940-454dc80bc472

**Comment by rubairakib** [comment]
> only way bar is zoomed? run this, `Hyprdots waybar control` then find the row with 1 as the 1st field. modify the 2nd field to suit the sizes you want
> 2024-03-22.21-38-20.mp4

everything is zoomed including this webpage in firefox. Even everything seems broken i.e the touchpad scroll working in natural mode, kitty looks different.
Is there any other way to fresh reinstall or something like that as fixing all these seems too overwhelmed to me?

**Comment by kRHYME7** [comment]
Yup try to run ``` Hyprdots-install ``` it is just a wrapper of the installation script.

**Comment by rubairakib** [comment]
Haven't changed anything. I was just trying to pull the commit and that leads to this situation. Except for kitty, i have installed Oh My Zsh, then when i removed it my previous kitty config was gone.

**Comment by kRHYME7** [comment]
Ow Hyprdots-install will be enough

but update first ``` yay -Sy hyprdots-ctl-git ```

**Comment by mrspedd** [comment]
I am not sure but possibly your monitor scaling settings need to be changed from auto. 
Have a look in ~/.config/hypr/hyprland.conf

Under monitor section:

monitor = ,preferred, auto, 1

**Comment by rubairakib** [comment]
> I am not sure but possibly your monitor scaling settings need to be changed from auto. Have a look in ~/.config/hypr/hyprland.conf
> 
> Under monitor section:
> 
> ```
> monitor = ,preferred, auto, 1
> ```
it was "monitor = ,preferred, auto, auto," now its fixed after editing. 
I have switched to Gnome as i couldn't fix it anyway. Thanks mate!

**Comment by rubairakib** [comment]
got one more issue. My touchpad is still working naturally any idea to fix that one?

**Comment by mrspedd** [comment]
> got one more issue. My touchpad is still working naturally any idea to fix that one?

Hmm, Ive got no clue for that one. My laptop worked fine after pulling changes. Is it the same issue as #1159?

**Comment by RizkiIqbal02** [comment]
> > I am not sure but possibly your monitor scaling settings need to be changed from auto. Have a look in ~/.config/hypr/hyprland.conf
> > Under monitor section:
> > ```
> > monitor = ,preferred, auto, 1
> > ```
> 
> it was "monitor = ,preferred, auto, auto," now its fixed after editing. I have switched to Gnome as i couldn't fix it anyway. Thanks mate!

thanks, you save my day

**Comment by kRHYME7** [comment]
If you meant this natural scroll for touchpad
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c6f96e27-8a82-4da5-82bc-18dd1257f22b)
