### ISSUE TITLE
Swww build error: how to skip?

### ISSUE THREAD

**Issue by Mattescantcode** [prasanthrangan/hyprdots#1150]
There is some kind of bug going on with the aur version of swww, where an error occurs in build()

I set up a clean arch install to make sure it is reproducible,
the install.sh always ends in a status 4 exit code due to this issue.
So i tried to build swww from source from [https://github.com/LGFae/swww](https://github.com/LGFae/swww ) with cargo,
but it the script installs it regardless.
I tried removing it from install_pkg.lst, which didnt help
How do i remove swww from install.sh so i can install it manually?
Or is there another way to fix this anyone can think of?

ps:
might be a slightly dumb question, sry

**Comment by kRHYME7** [comment]
>  might be a slightly dumb question, sry

No probs 

it's a dupe #1145. I'll be closing this one
