### ISSUE TITLE
[Bug]: Wallpaper is not changing 

### ISSUE THREAD

**Issue by Itz-Abhishek-Tiwari** [prasanthrangan/hyprdots#1157]
### Description

I'm trying to change my wallpaper, but it's not working. I attempted to reinstall 'swww' but encountered an error. Instead, I installed 'swww-git', which was available, but nothing happened. To simplify, when I updated 'hyprdots', I encountered an issue where my wallpaper didn't appear; instead, I got a black screen as shown in the first screenshot. After some searching, I discovered that the problem was related to 'swww'. Someone in another thread suggested installing 'swww-git', which I did. This did change my wallpaper, but it appeared differently, as shown in the second screenshot. However, now I'm unable to set another wallpaper.

### Steps to Reproduce

1. Update hyprdots.
2. Notice the wallpaper has disappeared, and a black screen is shown (refer to the screenshot).
3. Install 'swww-git' to address the wallpaper issue.
4. Despite installing 'swww-git', the wallpaper remains unchanged, and attempts to change it are unsuccessful.

### Expected Behavior

I expected that when I changed my wallpaper, it would update accordingly. 

### Actual Behavior

When attempting to change the wallpaper, it did not change.

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/69257109/41fc7c94-ae3a-4e64-a519-c44e9ba579b3)

![image](https://github.com/prasanthrangan/hyprdots/assets/69257109/79d0c833-8b39-4fa1-9eae-52730fb8c509)

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: ` Linux archlinux 6.8.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000 x86_64 GNU/Linux `
- Hyprland Version, output of `hyprctl version`:` Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1
 `
- Installation Environment: On The Main Hardware

**Comment by Mattescantcode** [comment]
same issue here, https://github.com/prasanthrangan/hyprdots/issues/1142 is the reason, the solution mentioned there didnt work for me yet though

**Comment by Itz-Abhishek-Tiwari** [comment]
This is the output of the ` yay -Sy swww `

```
❯ yay -Sy swww
[sudo] password for abhishek: 
:: Synchronizing package databases...
 core is up to date
 extra                           8.3 MiB   925 KiB/s 00:09 [-------------------------------] 100%
 multilib is up to date
AUR Explicit (1): swww-0.8.2-2
:: PKGBUILD up to date, skipping download: swww
  1 swww                             (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
:: Deleting (1/1): /home/abhishek/.cache/yay/swww
HEAD is now at f597165 upgpkg: 0.8.2-2: Refactor PKGBUILD
warning: could not open directory 'pkg/': Permission denied
Removing pkg/
Removing src/
Removing swww-0.8.2.tar.gz
  1 swww                             (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
 -> swww: No changes -- skipping

:: Proceed with install? [Y/n] y
==> Making package: swww 0.8.2-2 (Sat 23 Mar 2024 03:54:38 PM IST)
==> Retrieving sources...
  -> Downloading swww-0.8.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 73488  100 73488    0     0  56848      0  0:00:01  0:00:01 --:--:-- 1010k
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    swww-0.8.2.tar.gz ... Passed
:: (1/1) Parsing SRCINFO: swww
==> Making package: swww 0.8.2-2 (Sat 23 Mar 2024 03:54:41 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found swww-0.8.2.tar.gz
==> Validating source files with sha256sums...
    swww-0.8.2.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting swww-0.8.2.tar.gz with bsdtar
==> Starting prepare()...
==> Sources are ready.
==> Making package: swww 0.8.2-2 (Sat 23 Mar 2024 03:54:46 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
   Compiling proc-macro2 v1.0.76
   Compiling cfg-if v1.0.0
   Compiling unicode-ident v1.0.12
   Compiling autocfg v1.1.0
   Compiling libc v0.2.152
   Compiling bitflags v2.4.1
   Compiling bitflags v1.3.2
   Compiling crossbeam-utils v0.8.19
   Compiling smallvec v1.12.0
   Compiling pkg-config v0.3.28
   Compiling log v0.4.20
   Compiling libloading v0.8.1
   Compiling rayon-core v1.12.0
   Compiling simd-adler32 v0.3.7
   Compiling dlib v0.5.2
   Compiling syn v1.0.109
   Compiling rustix v0.38.30
   Compiling version_check v0.9.4
   Compiling memchr v2.7.1
   Compiling downcast-rs v1.2.0
   Compiling scoped-tls v1.0.1
   Compiling utf8parse v0.2.1
   Compiling libm v0.2.8
   Compiling anstyle-parse v0.2.3
   Compiling anstyle-query v1.0.2
   Compiling memoffset v0.7.1
   Compiling num-traits v0.2.17
   Compiling lock_api v0.4.11
   Compiling crc32fast v1.3.2
   Compiling heck v0.4.1
   Compiling quote v1.0.35
   Compiling colorchoice v1.0.0
   Compiling ahash v0.7.7
   Compiling crossbeam-epoch v0.9.18
   Compiling quick-xml v0.30.0
   Compiling anstyle v1.0.4
   Compiling syn v2.0.48
   Compiling jobserver v0.1.27
   Compiling crossbeam-deque v0.8.5
   Compiling adler v1.0.2
   Compiling linux-raw-sys v0.4.12
   Compiling cc v1.0.83
   Compiling wayland-sys v0.31.1
   Compiling miniz_oxide v0.7.1
   Compiling anstream v0.6.7
   Compiling once_cell v1.19.0
   Compiling either v1.9.0
   Compiling thiserror v1.0.56
   Compiling strsim v0.10.0
    Building [========>                 ] 62/173: thiserror(build.rs), cc, num-traits(build).   Compiling getrandom v0.2.12
   Compiling nix v0.26.4
   Compiling wayland-scanner v0.31.0
   Compiling scopeguard v1.2.0
   Compiling clap_lex v0.6.0
   Compiling clap_builder v4.4.16
   Compiling rayon v1.8.0
   Compiling rkyv v0.7.43
   Compiling flate2 v1.0.28
   Compiling hashbrown v0.12.3
   Compiling spin v0.9.8
   Compiling seahash v4.1.0
   Compiling weezl v0.1.7
   Compiling time-core v0.1.2
   Compiling powerfmt v0.2.0
   Compiling time-macros v0.2.16
   Compiling deranged v0.3.11
   Compiling wayland-backend v0.3.2
   Compiling lzzzz v1.0.4
   Compiling terminal_size v0.3.0
   Compiling flume v0.11.0
   Compiling rand_core v0.6.4
   Compiling zune-inflate v0.2.54
   Compiling fdeflate v0.3.3
   Compiling lazy_static v1.4.0
   Compiling xcursor v0.3.5
   Compiling jpeg-decoder v0.3.1
   Compiling wayland-client v0.31.1
   Compiling num_threads v0.1.6
   Compiling lebe v0.5.2
   Compiling half v2.2.1
   Compiling cursor-icon v1.1.0
   Compiling bytemuck v1.14.0
   Compiling ppv-lite86 v0.2.17
    Building [===============>         ] 113/173: clap_builder, jpeg-decoder, wayland-backen   Compiling itoa v1.0.10
   Compiling bit_field v0.10.2
   Compiling color_quant v1.1.0
   Compiling smithay-client-toolkit v0.18.0
   Compiling rand_chacha v0.3.1
   Compiling exr v1.71.0
   Compiling gif v0.12.0
   Compiling time v0.3.31
   Compiling wayland-protocols v0.31.0
   Compiling wayland-cursor v0.31.0
   Compiling qoi v0.4.1
   Compiling wayland-csd-frame v0.3.0
   Compiling tiff v0.9.1
   Compiling clap_derive v4.4.7
   Compiling thiserror-impl v1.0.56
   Compiling png v0.17.11
   Compiling memmap2 v0.9.3
   Compiling ptr_meta_derive v0.1.4
   Compiling rkyv_derive v0.7.43
   Compiling mint v0.5.9
   Compiling ptr_meta v0.1.4
   Compiling byteorder v1.5.0
   Compiling xkeysym v0.2.0
   Compiling termcolor v1.1.3
   Compiling image v0.24.8
   Compiling keyframe v1.1.1
   Compiling simplelog v0.12.1
   Compiling rand v0.8.5
   Compiling nix v0.27.1
   Compiling sd-notify v0.4.1
   Compiling spin_sleep v1.2.0
   Compiling wayland-protocols-wlr v0.2.0
   Compiling fast_image_resize v2.7.3
   Compiling clap v4.4.16
   Compiling clap_complete v4.4.6
   Compiling swww v0.8.2 (/home/abhishek/.cache/yay/swww/src/swww-0.8.2)
warning: swww@0.8.2: generated shell completion file: "completions/swww.bash"
warning: swww@0.8.2: generated shell completion file: "completions/_swww"
warning: swww@0.8.2: generated shell completion file: "completions/swww.fish"
warning: swww@0.8.2: generated shell completion file: "completions/swww.elv"
   Compiling utils v0.8.2 (/home/abhishek/.cache/yay/swww/src/swww-0.8.2/utils)
   Compiling swww-daemon v0.8.2 (/home/abhishek/.cache/yay/swww/src/swww-0.8.2/daemon)
error: non-binding let on a synchronization lock
   --> daemon/src/wallpaper.rs:146:21
    |
146 |         let (inner, _) = self.lock();
    |                     ^ this lock is not assigned to a binding and is immediately dropped
    |
    = help: consider immediately dropping the value using `drop(..)` after the `let` statement
    = note: `#[deny(let_underscore_lock)]` on by default
help: consider binding to an unused variable to avoid immediately dropping the value
    |
146 |         let (inner, _unused) = self.lock();
    |                     ~~~~~~~

error: could not compile `swww-daemon` (bin "swww-daemon") due to 1 previous error
warning: build failed, waiting for other jobs to finish...
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: swww-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
swww - exit status 4

~ took 1m55s 
❯ 

```

**Comment by Enigma1309** [comment]
revert [this](https://github.com/prasanthrangan/hyprdots/commit/ec4b65c9eb1ea12203d6f715ec167fa88b087f6d) commit and see if the problem fixes

basically change 
    `swww-daemon --format xrgb` to `swww init` 
in line 145 of `~/.config/hyprdots/scripts/swwwallpaper.sh`

**Comment by Itz-Abhishek-Tiwari** [comment]
> revert [this](https://github.com/prasanthrangan/hyprdots/commit/ec4b65c9eb1ea12203d6f715ec167fa88b087f6d) commit and see if the problem fixes
> 
> basically change `swww-daemon --format xrgb` to `swww init` in line 145 of `~/.config/hyprdots/scripts/swwwallpaper.sh`

Yes, it works. Thanks, man. But I have one question: Is swww-git unstable or unsafe for daily use?

**Comment by Itz-Abhishek-Tiwari** [comment]
now i got this 
![Uploading image.png…]()

**Comment by Itz-Abhishek-Tiwari** [comment]
Now i got this 
![image](https://github.com/prasanthrangan/hyprdots/assets/69257109/3e2b7bd4-9df5-43c3-908b-6a09d02e93ae)

**Comment by kRHYME7** [comment]
Hi it is fixed rn. 

https://github.com/prasanthrangan/hyprdots/pull/1155

please fetch the latest changes

**Comment by hdm9527** [comment]
Comment check in the $HOME/.config/hyprdots/scripts/swwwallpaper.sh file. This check seems to be useless.
![image](https://github.com/prasanthrangan/hyprdots/assets/39702328/4ab86e9e-7645-470c-a562-f4f6371edb48)

**Comment by kRHYME7** [comment]
Useless?

**Comment by Itz-Abhishek-Tiwari** [comment]
> Hi it is fixed rn.
> 
> #1155
> 
> please fetch the latest changes

i fetch the latest one but noting change

**Comment by kRHYME7** [comment]
Run this first
``` grep "swww-daemon" ~/.config/hyprdots/scripts/swwwallpaper.sh ``` 
should output this
```
swww-daemon --format xrgb
```

I suggest to do a reboot

**Comment by Itz-Abhishek-Tiwari** [comment]
> Run this first `grep "swww-daemon" ~/.config/hyprdots/scripts/swwwallpaper.sh` should output this
> 
> ```
> swww-daemon --format xrgb
> ```
> 
> I suggest to do a reboot

now wallpaper is not changing 

![image](https://github.com/prasanthrangan/hyprdots/assets/69257109/40ce3fe6-7d50-4cf4-84d0-d91a5e2e8329)

**Comment by kRHYME7** [comment]
**Run this first
``` ~/.config/hyprdots/scripts/swwwallpaper.sh -n ``` 
if it outputs ``` An instance of the script is already running... ``` 

then  please remove the lock file. 

I'll add a PR to auto detect older lock file to avoid this confusion. 

This is how to remove the lockfile
```
rm /tmp/hyrpdots$(id -u)swwwallpaper.lock
```
This is a safety check, and slightly convenient  to avoid accidents like purging the whole theme.ctl file for spamming the wallpaper next function.

**Comment by Itz-Abhishek-Tiwari** [comment]
> **Run this first `~/.config/hyprdots/scripts/swwwallpaper.sh -n` if it outputs `An instance of the script is already running...`
> 
> then please remove the lock file.
> 
> I'll add a PR to auto detect older lock file to avoid this confusion.
> 
> This is how to remove the lockfile
> 
> ```
> rm /tmp/hyrpdots$(id -u)swwwallpaper.lock
> ```
> 
> This is a safety check, and slightly convenient to avoid accidents like purging the whole theme.ctl file for spamming the wallpaper next function.

yeah now it fix

**Comment by hdm9527** [comment]
> Useless?



> Useless?
> 
> > This check seems to be useless.
> 
> Ow this part, it avoids user spamming wallpaper next so that the thumbnails won't be messed up.



> Useless?
> 
> > This check seems to be useless.
> 
> Ow this part, it avoids user spamming wallpaper next so that the thumbnails won't be messed up.

Thanks, I got it.

**Comment by hdm9527** [comment]
It was fixed. #1163
