### ISSUE TITLE
[Bug]: Color of apps does not update according to wallpaper 

### ISSUE THREAD

**Issue by Itz-Abhishek-Tiwari** [prasanthrangan/hyprdots#1162]
### Description

Now, the theme of applications such as Waybar, Dolphin, Kitty, and any other app does not change in accordance with the wallpaper I am using. Instead, it changes based on themes, rather than the wallpaper.

### Steps to Reproduce

1. Change wallpaper.
2. See that app color does not change according to wallpaper.

### Expected Behavior

The expected behavior would be for the theme of apps to change dynamically based on the wallpaper being used, rather than solely changing according to predefined themes.

### Actual Behavior

When I attempt to change the theme of apps, it updates to the selected theme successfully. However, it does not automatically adjust according to the wallpaper I am using. Instead, it remains unchanged regardless of the wallpaper.

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/69257109/69c72ddf-3a4d-48e3-8630-7905fd8fa000)

![image](https://github.com/prasanthrangan/hyprdots/assets/69257109/ca0a3ff7-96ce-48c5-8ccc-26998268357b)

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: `  Linux archlinux 6.8.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000 x86_64 GNU/Linux ` 
- Hyprland Version, output of `hyprctl version`:` Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1
 `
- Installation Environment: On The Main Hardware

### Additional Information

[I acknowledge that I've been submitting too many bug reports in the past few days, and I apologize for that. I'm new to Hyprland and, in general, new to coding.]

**Comment by hdm9527** [comment]
It was fixed. #1163

**Comment by kRHYME7** [comment]
is your wallbash enabled already? if yes then @hdm9527  already fixed the issue

**Comment by Itz-Abhishek-Tiwari** [comment]
> It was fixed. #1163

yeah it fixed
