### ISSUE TITLE
[Bug]: Some applications like vscode and brave look blurry 

### ISSUE THREAD

**Issue by yashGoyal40** [prasanthrangan/hyprdots#1168]
### Description

-> some of my apps like VSCode ,brave and docker-desktop are blurry 
-> meanwhile applications like Firefox ,blender and OBS are running just fine
-> This might be an graphic acceleration issue or font issue or a theme issue
-> I am not able to fix this  please help me fixing this because despite nvim and everything i use VSCode a lot

### Screenshots

![240324_14h05m05s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/82037873/9fec93b0-b65b-49ac-a645-c31de4e6090a)
![240324_14h08m05s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/82037873/fe06bc0a-759c-4b03-b277-9c0c4452736b)

### Environment

-Processor: AMD Ryzen 5 5500u with Radeon graphics  (integrated gpu)
- GPU in Neofetch - AMD ATI 03:00.0 Lucienne 
- Linux Distro: ArchLinux
- Linux Version: Linux archlinux 6.8.1-arch1-1 
- Hyprland Version: v0.37.1
- Installation Environment: bare metal
- Screen resolution: 1920x1080

**Comment by kRHYME7** [comment]
Please utilize the search filter. The fixes for this are all over the place. I'll try to add this on the wiki. but for the mean time please please use the Issue tracker 🥲

**Comment by Itz-Abhishek-Tiwari** [comment]
> ## Bug Report
> ### Description
> -> some of my apps like VSCode ,brave and docker-desktop are blurry -> meanwhile applications like Firefox ,blender and OBS are running just fine -> This might be an graphic acceleration issue or font issue or a theme issue -> I am not able to fix this please help me fixing this because despite nvim and everything i use VSCode a lot
> 
> ### Screenshots
> ![240324_14h05m05s_screenshot](https://private-user-images.githubusercontent.com/82037873/316296136-9fec93b0-b65b-49ac-a645-c31de4e6090a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNzI2MzksIm5iZiI6MTcxMTI3MjMzOSwicGF0aCI6Ii84MjAzNzg3My8zMTYyOTYxMzYtOWZlYzkzYjAtYjY1Yi00OWFjLWE2NDUtYzMxZGU0ZTYwOTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA5MjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ODI0NDZiMTQ5ZDE0NjlkMWIyY2MxYTRlNWJjYjYzYWRmNmJkNzAyYjhhODUyNzFmZWQ2MGViMmNiMGNkNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o8Dk9B3GTaiRZV21glk6nhLoKCMZTFYOH-_XWEQg4OU) ![240324_14h08m05s_screenshot](https://private-user-images.githubusercontent.com/82037873/316296145-fe06bc0a-759c-4b03-b277-9c0c4452736b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNzI2MzksIm5iZiI6MTcxMTI3MjMzOSwicGF0aCI6Ii84MjAzNzg3My8zMTYyOTYxNDUtZmUwNmJjMGEtNzU5Yy00YjAzLWIyNzctOWMwYzQ0NTI3MzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA5MjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NGY4NWFkZDU2ZDdiOTkxOGQxOTNmYzg2ZDU0OTk4ZTk4ODQwYTMzMmIzOTMzY2MxZTQ4OGJiZjhmZGZjMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DVDyXnw785yTS4DjA-_je0FUdcHqJKWq-CJo4CcRpr4)
> 
> ### Environment
> -Processor: AMD Ryzen 5 5500u with Radeon graphics (integrated gpu)
> 
> * GPU in Neofetch - AMD ATI 03:00.0 Lucienne
> * Linux Distro: ArchLinux
> * Linux Version: Linux archlinux 6.8.1-arch1-1
> * Hyprland Version: v0.37.1
> * Installation Environment: bare metal
> * Screen resolution: 1920x1080


add this : ` xwayland {
  force_zero_scaling = true
} `  

in ` ~/.config/hypr/userprefs.conf `

**Comment by yashGoyal40** [comment]
![240324_15h10m40s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/82037873/cdc7a64c-7b81-4b19-bc40-5fe7ccd93379)


> > ## Bug Report
> > ### Description
> > -> some of my apps like VSCode ,brave and docker-desktop are blurry -> meanwhile applications like Firefox ,blender and OBS are running just fine -> This might be an graphic acceleration issue or font issue or a theme issue -> I am not able to fix this please help me fixing this because despite nvim and everything i use VSCode a lot
> > ### Screenshots
> > ![240324_14h05m05s_screenshot](https://private-user-images.githubusercontent.com/82037873/316296136-9fec93b0-b65b-49ac-a645-c31de4e6090a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNzI2MzksIm5iZiI6MTcxMTI3MjMzOSwicGF0aCI6Ii84MjAzNzg3My8zMTYyOTYxMzYtOWZlYzkzYjAtYjY1Yi00OWFjLWE2NDUtYzMxZGU0ZTYwOTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA5MjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ODI0NDZiMTQ5ZDE0NjlkMWIyY2MxYTRlNWJjYjYzYWRmNmJkNzAyYjhhODUyNzFmZWQ2MGViMmNiMGNkNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o8Dk9B3GTaiRZV21glk6nhLoKCMZTFYOH-_XWEQg4OU) ![240324_14h08m05s_screenshot](https://private-user-images.githubusercontent.com/82037873/316296145-fe06bc0a-759c-4b03-b277-9c0c4452736b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNzI2MzksIm5iZiI6MTcxMTI3MjMzOSwicGF0aCI6Ii84MjAzNzg3My8zMTYyOTYxNDUtZmUwNmJjMGEtNzU5Yy00YjAzLWIyNzctOWMwYzQ0NTI3MzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA5MjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NGY4NWFkZDU2ZDdiOTkxOGQxOTNmYzg2ZDU0OTk4ZTk4ODQwYTMzMmIzOTMzY2MxZTQ4OGJiZjhmZGZjMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DVDyXnw785yTS4DjA-_je0FUdcHqJKWq-CJo4CcRpr4)
> > ### Environment
> > -Processor: AMD Ryzen 5 5500u with Radeon graphics (integrated gpu)
> > 
> > * GPU in Neofetch - AMD ATI 03:00.0 Lucienne
> > * Linux Distro: ArchLinux
> > * Linux Version: Linux archlinux 6.8.1-arch1-1
> > * Hyprland Version: v0.37.1
> > * Installation Environment: bare metal
> > * Screen resolution: 1920x1080
> 
> add this : `xwayland { force_zero_scaling = true }`
> 
> in `~/.config/hypr/userprefs.conf`

![240324_15h10m40s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/82037873/81557d59-6905-4432-9bd7-6a7cebd31fc7)

**Comment by yashGoyal40** [comment]
worked thank's mate

**Comment by Aryan214G** [comment]
Thank you!
