### ISSUE TITLE
[Bug]: The brightness cannot be adjusted

### ISSUE THREAD

**Issue by hui3215** [prasanthrangan/hyprdots#1172]
### Description

The brightness cannot be adjusted
The screen is dark
### Steps to Reproduce

```shell
➜  ~ brightnessctl set +5%
Updated device 'acpi_video0':
Device 'acpi_video0' of class 'backlight':
	Current brightness: 100 (100%)
	Max brightness: 100
```

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by kRHYME7** [comment]
provide ``` Hyprdots systeminfo ```

**Comment by hui3215** [comment]
> provide output for `Hyprdots systeminfo`

```shell
➜  ~ Hyprdots systeminfo
**Hyprdots-ctl Version:**
Version: v0.5.0-17-g432e1a0
Last commit: 432e1a0 Sat Mar 23 18:56:05 2024 +0800
Commit message: 'fix rofi pos'

**Repository:**
CloneDirectory: /home/hui/Hyprdots
Git URL: https://github.com/prasanthrangan/hyprdots
Git Branch: main

**GPU:** 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] [10de:1f91] (rev a1)

**CPU:** 

**OS:** 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

**Hyprland System Information:** (Not always available)
Hyprland, built from branch main at commit 86dc46ffea2fa72abe1228c1fad1b42d1507e45d dirty (animationmgr: use realpos and size for border damage).
Date: Sun Mar 24 11:09:46 2024
Tag: v0.37.1-55-g86dc46ff

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] [10de:1f91] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

➜  ~ 
```

**Comment by kRHYME7** [comment]
Hmm try to run this first ``` ~/.config/hyprdots/scripts/brightnesscontrol.sh i ```

**Comment by hui3215** [comment]
> 嗯，先尝试运行这个`~/.config/hyprdots/scripts/brightnesscontrol.sh i`
> 
> 我认为这是无用的，但先试试吧。
> 
> 您的驱动程序版本为 NVIDIA ？`yay -Qs nvidia`
> 
> 还有一件事，您使用的是笔记本电脑显示器还是外接显示器？

I'm using a laptop, the graphics card is NVIDIA, and the brightness has been the dimest after the update
