### ISSUE TITLE
[Bug]: No audio with Nvidia gpu

### ISSUE THREAD

**Issue by dieBakterie** [prasanthrangan/hyprdots#1174]
### Description

I've No audio No Matter what Output/Source Kombination i try

### Steps to Reproduce

1. Minimal Arch
2. Hyprdots install
3. No audio

### Expected Behavior

To have audio output

### Actual Behavior

No audio No Matter what Port/Output

### Environment

- Linux Distro: Arch Linux x86_64
- Linux Version: 6.8.1-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC
- Hyprland Version: Hyprland, build from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445 (props: bump ver v0.37.1) Tag: v0.37.1
- Installation Environment: Main Hardware
- Monitors: 1920x1080@60 & @144

### Additional Information

- lspci | grep VGA: NVIDIA Corporation Tu106 [GeForce RTX 2070 Rev. A] (rev a1)

**Comment by Itz-Abhishek-Tiwari** [comment]
> ## Bug Report
> ### Description
> I've No audio No Matter what Output/Source Kombination i try
> 
> ### Steps to Reproduce
> 1. Minimal Arch
> 2. Hyprdots install
> 3. No audio
> 
> ### Expected Behavior
> To have audio output
> 
> ### Actual Behavior
> No audio No Matter what Port/Output
> 
> ### Environment
> * Linux Distro: Arch Linux x86_64
> * Linux Version: 6.8.1-zen1-1-zen [Symlinks #1](https://github.com/prasanthrangan/hyprdots/issues/1) ZEN SMP PREEMPT_DYNAMIC
> * Hyprland Version: Hyprland, build from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445 (props: bump ver v0.37.1) Tag: v0.37.1
> * Installation Environment: Main Hardware
> * Monitors: 1920x1080@60 & @144
> 
> ### Additional Information
> * lspci | grep VGA: NVIDIA Corporation Tu106 [GeForce RTX 2070 Rev. A] (rev a1)

did you install pipewire ?? and NVIDIA driver in arch install script ???

**Comment by dieBakterie** [comment]
Sorry for the late reply and yes i did

**Comment by Itz-Abhishek-Tiwari** [comment]
check if pipewire is install ` pipewire --version `
and for NVIDIA : ` pacman -Qs nvidia `

**Comment by dieBakterie** [comment]
Both are installed. Should i Install `nvidia-utils` too?

**Comment by dieBakterie** [comment]
Hell yeah it works was just borked ig. If this comes Back after installing hyprdots i'll reopen this.
