### ISSUE TITLE
Hyprpicker-git

### ISSUE THREAD

**Issue by dieBakterie** [prasanthrangan/hyprdots#1184]
Just that you know `hyprpicker-git` with paru atleast isn't complieable

**Comment by kRHYME7** [comment]
It's just the same for both yay and paru.  Check the aur page of hyprpicker-git. 

Tip. yay needs to have ``` --devel ``` flag if you want to make it sure to fetch the latest commits from git

**Comment by dieBakterie** [comment]
i'm using paru so i don't need this right?

**Comment by kRHYME7** [comment]
For now just use the stable one. Hyprdots moved to using the stable one.

#### Sidenote 

One of the reasons I use chaotic AUR is to avoid broken packages. In my case I can still install  hyprpicker-git .

On chaotic: 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/6f37440d-0341-4be5-9a5e-9cbe40455833)


PS. Not promoting chaotic here, but it should be beneficial as long as you're aware of what you're doing.  (I can fresh Hyprdots for around 15 mins).

**Comment by dieBakterie** [comment]
Fresh Install in 15 min or what do you meant by this?

**Comment by kRHYME7** [comment]
> Fresh Install in 15 min or what do you meant by this?

I mean, I don't compile some packages while "Installing" this repo. So example if I do a fresh arch install then run ``` Hyprdots-install ``` it would take only about 15 minutes and I have Hyprdots running.  (Given my hardware is an Ultrabook that limits 1.8 Ghz )

**Comment by dieBakterie** [comment]
Yeah i guess i'll do that now
