### ISSUE TITLE
[Bug]: Wallbash break the waybar and logout menu 

### ISSUE THREAD

**Issue by mahaveergurjar** [prasanthrangan/hyprdots#1187]
### Description
After update the Hyprdots on latest commits of @prasanthrangan on wallbash v4 waybar and logout menu UI
 breaks

### Steps to Reproduce
Enable wallbash 

### Expected Behavior
After enable wallbash waybar and logout menu also change the color according to bas on wallpaper color

### Actual Behavior

The waybar not working when wallbash enable and logout menu UI also breaks

#### Without wallbash 
![240326_08h06m03s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/c78974a9-61ba-45e1-994b-175e854536a0)
![240326_08h08m29s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/6adc3c1f-14f1-48b3-8253-1bd2c8c9cd42)

#### With wallbash
![240326_08h05m46s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/1196cbff-8e19-4793-b9a8-a08cbd0a43f6)
![240326_07h48m23s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/6df0c626-fdf8-4431-93e9-a9586cac23f7)

### Environment

❯ Hyprdots systeminfo
**Hyprdots-ctl Version:**
Version: v0.5.0-17-g432e1a0
Last commit: 432e1a0 Sat Mar 23 18:56:05 2024 +0800
Commit message: 'fix rofi pos'

**Repository:**
CloneDirectory: /home/mahaveer/Hyprdots
Git URL: https://github.com/prasanthrangan/hyprdots
Git Branch: main

**GPU:** 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-UP3 GT2 [UHD Graphics] [8086:4628] (rev 0c)

**CPU:** 
12th Gen Intel(R) Core(TM) i5-1235U

**OS:** 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

**Hyprland System Information:** (Not always available)
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)

System Information:
System name: Linux
Node name: archlinux
Release: 6.8.1-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000

GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-UP3 GT2 [UHD Graphics] [8086:4628] (rev 0c) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

**Comment by kRHYME7** [comment]
Now thats the good way to provide info! 

Have you tried running this ? ``` ~/.config/hyprdots/scripts/swwwallpaper.sh -n ```  Also do not forget to ``` Hyprdots cache rebuid ```

**Comment by mahaveergurjar** [comment]
Yes  ```Hyprdots cache rebuid ``` 

 I reinstall fresh the Hyprdots but The waybar break after this command  ```~/.config/hyprdots/scripts/swwwallpaper.sh -n ``` 
or change on waybar position  

After change the wallpaper 
the waybar wall-Dcol.css file empty 
```
@define-color bar-bg ;
@define-color main-bg ;
@define-color main-fg ;
@define-color wb-act-bg ;
@define-color wb-act-fg ;
@define-color wb-hvr-bg ;
@define-color wb-hvr-fg ;

``` 
I put manually these color in waybar wall-Dcol.css file
This file
[https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/waybar/themes/Wall-Dcol.css](url) 

```
@define-color bar-bg rgba(0, 0, 0, 0);
@define-color main-bg #1B1B29;
@define-color main-fg #9F9FD6;
@define-color wb-act-bg #974C4E;
@define-color wb-act-fg #00001A;
@define-color wb-hvr-bg #1F293D;
@define-color wb-hvr-fg #9FC6D6;
``` 
After adding change the wallpaper and give same problem wallbash color are not fetch

I think the problem are in file```~/ .config/hyprdots/wallbash/waybar.dcol``` 

```
$HOME/.config/waybar/themes/Wall-Dcol.css|${ScrDir}/wbarconfgen.sh
@define-color bar-bg <wallbash_pry1_rgba(0)>;
@define-color main-bg <wallbash_pry1_rgba(0.8)>;
@define-color main-fg <wallbash_1xa8_rgba(0.8)>;
@define-color wb-act-bg <wallbash_pry4_rgba(0.4)>;
@define-color wb-act-fg <wallbash_1xa1_rgba(0.8)>;
@define-color wb-hvr-bg <wallbash_2xa3_rgba(0.4)>;
@define-color wb-hvr-fg <wallbash_3xa8_rgba(0.8)>;

``` 

Old waybar wallbash waybar.dcol work properly and also logout menu work properly 
```
$HOME/.config/waybar/themes/Wall-Dcol.css|${ScrDir}/wbarconfgen.sh
@define-color bar-bg rgba(0, 0, 0, 0);
@define-color main-bg #<wallbash_pry1>;
@define-color main-fg #<wallbash_1xa8>;
@define-color wb-act-bg #<wallbash_pry4>;
@define-color wb-act-fg #<wallbash_1xa1>;
@define-color wb-hvr-bg #<wallbash_2xa3>;
@define-color wb-hvr-fg #<wallbash_3xa8>;
``` 
but not work in new waybar.dcol wallbash color that are more accurate but I don't know why these are not fetch the color in wall-Dcol.css @kRHYME7 please help me how to fix this issue

**Comment by kRHYME7** [comment]
That means some colors aren't cache


run this ``` cat ~/.cache/hyprdots/Catppuccin-Mocha/aesthetic_deer.png.dcol ``` 
```
dcol_pry1="0B1834"
dcol_pry1_rgba="rgba(11,24,52,\1)"
dcol_txt1="FFFFFF"
dcol_txt1_rgba="rgba(255,255,255,\1)"
dcol_1xa1="293652"
dcol_1xa1_rgba="rgba(41,54,82,\1)"
dcol_1xa2="3A496B"
dcol_1xa2_rgba="rgba(58,73,107,\1)"
dcol_1xa3="4B5B7D"
dcol_1xa3_rgba="rgba(75,91,125,\1)"
dcol_1xa4="57698F"
dcol_1xa4_rgba="rgba(87,105,143,\1)"
dcol_1xa5="6579A3"
dcol_1xa5_rgba="rgba(101,121,163,\1)"
dcol_1xa6="7A91C2"
dcol_1xa6_rgba="rgba(122,145,194,\1)"
dcol_1xa7="9AB2E6"
dcol_1xa7_rgba="rgba(154,178,230,\1)"
dcol_1xa8="AAC0F0"
dcol_1xa8_rgba="rgba(170,192,240,\1)"
dcol_1xa9="CCDCFF"
dcol_1xa9_rgba="rgba(204,220,255,\1)"
dcol_pry2="212748"
dcol_pry2_rgba="rgba(33,39,72,\1)"
dcol_txt2="FFFFFF"
dcol_txt2_rgba="rgba(255,255,255,\1)"
dcol_2xa1="292F52"
dcol_2xa1_rgba="rgba(41,47,82,\1)"
dcol_2xa2="3A416B"
dcol_2xa2_rgba="rgba(58,65,107,\1)"
dcol_2xa3="4B537D"
dcol_2xa3_rgba="rgba(75,83,125,\1)"
dcol_2xa4="57608F"
dcol_2xa4_rgba="rgba(87,96,143,\1)"
dcol_2xa5="656FA3"
dcol_2xa5_rgba="rgba(101,111,163,\1)"
dcol_2xa6="7A85C2"
dcol_2xa6_rgba="rgba(122,133,194,\1)"
dcol_2xa7="9AA5E6"
dcol_2xa7_rgba="rgba(154,165,230,\1)"
dcol_2xa8="AAB5F0"
dcol_2xa8_rgba="rgba(170,181,240,\1)"
dcol_2xa9="CCD4FF"
dcol_2xa9_rgba="rgba(204,212,255,\1)"
dcol_pry3="413054"
dcol_pry3_rgba="rgba(65,48,84,\1)"
dcol_txt3="FFFFFF"
dcol_txt3_rgba="rgba(255,255,255,\1)"
dcol_3xa1="3C2952"
dcol_3xa1_rgba="rgba(60,41,82,\1)"
dcol_3xa2="513A6B"
dcol_3xa2_rgba="rgba(81,58,107,\1)"
dcol_3xa3="634B7D"
dcol_3xa3_rgba="rgba(99,75,125,\1)"
dcol_3xa4="71578F"
dcol_3xa4_rgba="rgba(113,87,143,\1)"
dcol_3xa5="8265A3"
dcol_3xa5_rgba="rgba(130,101,163,\1)"
dcol_3xa6="9C7AC2"
dcol_3xa6_rgba="rgba(156,122,194,\1)"
dcol_3xa7="BE9AE6"
dcol_3xa7_rgba="rgba(190,154,230,\1)"
dcol_3xa8="CBAAF0"
dcol_3xa8_rgba="rgba(203,170,240,\1)"
dcol_3xa9="E4CCFF"
dcol_3xa9_rgba="rgba(228,204,255,\1)"
dcol_pry4="B33D60"
dcol_pry4_rgba="rgba(179,61,96,\1)"
dcol_txt4="FEFEFE"
dcol_txt4_rgba="rgba(254,254,254,\1)"
dcol_4xa1="522935"
dcol_4xa1_rgba="rgba(82,41,53,\1)"
dcol_4xa2="6B3A48"
dcol_4xa2_rgba="rgba(107,58,72,\1)"
dcol_4xa3="7D4B5A"
dcol_4xa3_rgba="rgba(125,75,90,\1)"
dcol_4xa4="8F5768"
dcol_4xa4_rgba="rgba(143,87,104,\1)"
dcol_4xa5="A36578"
dcol_4xa5_rgba="rgba(163,101,120,\1)"
dcol_4xa6="C27A8F"
dcol_4xa6_rgba="rgba(194,122,143,\1)"
dcol_4xa7="E69AB0"
dcol_4xa7_rgba="rgba(230,154,176,\1)"
dcol_4xa8="F0AABF"
dcol_4xa8_rgba="rgba(240,170,191,\1)"
dcol_4xa9="FFCCDB"
dcol_4xa9_rgba="rgba(255,204,219,\1)"

```


That's 88 lines check yours.

**Comment by mahaveergurjar** [comment]
I find what the problem in this waybar wallbash need to change the Wall-Dcol.css file color hexa to rgba 
```
@define-color bar-bg rgba(0, 0, 0, 0);
@define-color main-bg #1B1B29;
@define-color main-fg #9F9FD6;
@define-color wb-act-bg #974C4E;
@define-color wb-act-fg #00001A;
@define-color wb-hvr-bg #1F293D;
@define-color wb-hvr-fg #9FC6D6;
``` 
New wallbash color in rgba
```
@define-color bar-bg rgba(0, 0, 0, 0);
@define-color main-bg rgba(27, 27, 41, 1);
@define-color main-fg rgba(159, 159, 214, 1);
@define-color wb-act-bg rgba(151, 76, 78, 1);
@define-color wb-act-fg rgba(0, 0, 26, 1);
@define-color wb-hvr-bg rgba(31, 41, 61, 1);
@define-color wb-hvr-fg rgba(159, 198, 214, 1);

``` 
I test this will be work

**Comment by mahaveergurjar** [comment]
> That means some colors aren't cache
> 
> run this `cat ~/.cache/hyprdots/Catppuccin-Mocha/aesthetic_deer.png.dcol`
> 
> ```
> dcol_pry1="0B1834"
> dcol_pry1_rgba="rgba(11,24,52,\1)"
> dcol_txt1="FFFFFF"
> dcol_txt1_rgba="rgba(255,255,255,\1)"
> dcol_1xa1="293652"
> dcol_1xa1_rgba="rgba(41,54,82,\1)"
> dcol_1xa2="3A496B"
> dcol_1xa2_rgba="rgba(58,73,107,\1)"
> dcol_1xa3="4B5B7D"
> dcol_1xa3_rgba="rgba(75,91,125,\1)"
> dcol_1xa4="57698F"
> dcol_1xa4_rgba="rgba(87,105,143,\1)"
> dcol_1xa5="6579A3"
> dcol_1xa5_rgba="rgba(101,121,163,\1)"
> dcol_1xa6="7A91C2"
> dcol_1xa6_rgba="rgba(122,145,194,\1)"
> dcol_1xa7="9AB2E6"
> dcol_1xa7_rgba="rgba(154,178,230,\1)"
> dcol_1xa8="AAC0F0"
> dcol_1xa8_rgba="rgba(170,192,240,\1)"
> dcol_1xa9="CCDCFF"
> dcol_1xa9_rgba="rgba(204,220,255,\1)"
> dcol_pry2="212748"
> dcol_pry2_rgba="rgba(33,39,72,\1)"
> dcol_txt2="FFFFFF"
> dcol_txt2_rgba="rgba(255,255,255,\1)"
> dcol_2xa1="292F52"
> dcol_2xa1_rgba="rgba(41,47,82,\1)"
> dcol_2xa2="3A416B"
> dcol_2xa2_rgba="rgba(58,65,107,\1)"
> dcol_2xa3="4B537D"
> dcol_2xa3_rgba="rgba(75,83,125,\1)"
> dcol_2xa4="57608F"
> dcol_2xa4_rgba="rgba(87,96,143,\1)"
> dcol_2xa5="656FA3"
> dcol_2xa5_rgba="rgba(101,111,163,\1)"
> dcol_2xa6="7A85C2"
> dcol_2xa6_rgba="rgba(122,133,194,\1)"
> dcol_2xa7="9AA5E6"
> dcol_2xa7_rgba="rgba(154,165,230,\1)"
> dcol_2xa8="AAB5F0"
> dcol_2xa8_rgba="rgba(170,181,240,\1)"
> dcol_2xa9="CCD4FF"
> dcol_2xa9_rgba="rgba(204,212,255,\1)"
> dcol_pry3="413054"
> dcol_pry3_rgba="rgba(65,48,84,\1)"
> dcol_txt3="FFFFFF"
> dcol_txt3_rgba="rgba(255,255,255,\1)"
> dcol_3xa1="3C2952"
> dcol_3xa1_rgba="rgba(60,41,82,\1)"
> dcol_3xa2="513A6B"
> dcol_3xa2_rgba="rgba(81,58,107,\1)"
> dcol_3xa3="634B7D"
> dcol_3xa3_rgba="rgba(99,75,125,\1)"
> dcol_3xa4="71578F"
> dcol_3xa4_rgba="rgba(113,87,143,\1)"
> dcol_3xa5="8265A3"
> dcol_3xa5_rgba="rgba(130,101,163,\1)"
> dcol_3xa6="9C7AC2"
> dcol_3xa6_rgba="rgba(156,122,194,\1)"
> dcol_3xa7="BE9AE6"
> dcol_3xa7_rgba="rgba(190,154,230,\1)"
> dcol_3xa8="CBAAF0"
> dcol_3xa8_rgba="rgba(203,170,240,\1)"
> dcol_3xa9="E4CCFF"
> dcol_3xa9_rgba="rgba(228,204,255,\1)"
> dcol_pry4="B33D60"
> dcol_pry4_rgba="rgba(179,61,96,\1)"
> dcol_txt4="FEFEFE"
> dcol_txt4_rgba="rgba(254,254,254,\1)"
> dcol_4xa1="522935"
> dcol_4xa1_rgba="rgba(82,41,53,\1)"
> dcol_4xa2="6B3A48"
> dcol_4xa2_rgba="rgba(107,58,72,\1)"
> dcol_4xa3="7D4B5A"
> dcol_4xa3_rgba="rgba(125,75,90,\1)"
> dcol_4xa4="8F5768"
> dcol_4xa4_rgba="rgba(143,87,104,\1)"
> dcol_4xa5="A36578"
> dcol_4xa5_rgba="rgba(163,101,120,\1)"
> dcol_4xa6="C27A8F"
> dcol_4xa6_rgba="rgba(194,122,143,\1)"
> dcol_4xa7="E69AB0"
> dcol_4xa7_rgba="rgba(230,154,176,\1)"
> dcol_4xa8="F0AABF"
> dcol_4xa8_rgba="rgba(240,170,191,\1)"
> dcol_4xa9="FFCCDB"
> dcol_4xa9_rgba="rgba(255,204,219,\1)"
> ```
> 
> That's 88 lines check yours.

Ok wait I will check

**Comment by mahaveergurjar** [comment]
```shell
❯ cat ~/.cache/hyprdots/Catppuccin-Mocha/aesthetic_deer.png.dcol


dcol_pry1="0B1834"
dcol_pry1_rgba="rgba(11,24,52,\1)"
dcol_txt1="FFFFFF"
dcol_txt1_rgba="rgba(255,255,255,\1)"
dcol_1xa1="293652"
dcol_1xa1_rgba="rgba(41,54,82,\1)"
dcol_1xa2="3A496B"
dcol_1xa2_rgba="rgba(58,73,107,\1)"
dcol_1xa3="4B5B7D"
dcol_1xa3_rgba="rgba(75,91,125,\1)"
dcol_1xa4="57698F"
dcol_1xa4_rgba="rgba(87,105,143,\1)"
dcol_1xa5="6579A3"
dcol_1xa5_rgba="rgba(101,121,163,\1)"
dcol_1xa6="7A91C2"
dcol_1xa6_rgba="rgba(122,145,194,\1)"
dcol_1xa7="9AB2E6"
dcol_1xa7_rgba="rgba(154,178,230,\1)"
dcol_1xa8="AAC0F0"
dcol_1xa8_rgba="rgba(170,192,240,\1)"
dcol_1xa9="CCDCFF"
dcol_1xa9_rgba="rgba(204,220,255,\1)"
dcol_pry2="212748"
dcol_pry2_rgba="rgba(33,39,72,\1)"
dcol_txt2="FFFFFF"
dcol_txt2_rgba="rgba(255,255,255,\1)"
dcol_2xa1="292F52"
dcol_2xa1_rgba="rgba(41,47,82,\1)"
dcol_2xa2="3A416B"
dcol_2xa2_rgba="rgba(58,65,107,\1)"
dcol_2xa3="4B537D"
dcol_2xa3_rgba="rgba(75,83,125,\1)"
dcol_2xa4="57608F"
dcol_2xa4_rgba="rgba(87,96,143,\1)"
dcol_2xa5="656FA3"
dcol_2xa5_rgba="rgba(101,111,163,\1)"
dcol_2xa6="7A85C2"
dcol_2xa6_rgba="rgba(122,133,194,\1)"
dcol_2xa7="9AA5E6"
dcol_2xa7_rgba="rgba(154,165,230,\1)"
dcol_2xa8="AAB5F0"
dcol_2xa8_rgba="rgba(170,181,240,\1)"
dcol_2xa9="CCD4FF"
dcol_2xa9_rgba="rgba(204,212,255,\1)"
dcol_pry3="413054"
dcol_pry3_rgba="rgba(65,48,84,\1)"
dcol_txt3="FFFFFF"
dcol_txt3_rgba="rgba(255,255,255,\1)"
dcol_3xa1="3C2952"
dcol_3xa1_rgba="rgba(60,41,82,\1)"
dcol_3xa2="513A6B"
dcol_3xa2_rgba="rgba(81,58,107,\1)"
dcol_3xa3="634B7D"
dcol_3xa3_rgba="rgba(99,75,125,\1)"
dcol_3xa4="71578F"
dcol_3xa4_rgba="rgba(113,87,143,\1)"
dcol_3xa5="8265A3"
dcol_3xa5_rgba="rgba(130,101,163,\1)"
dcol_3xa6="9C7AC2"
dcol_3xa6_rgba="rgba(156,122,194,\1)"
dcol_3xa7="BE9AE6"
dcol_3xa7_rgba="rgba(190,154,230,\1)"
dcol_3xa8="CBAAF0"
dcol_3xa8_rgba="rgba(203,170,240,\1)"
dcol_3xa9="E4CCFF"
dcol_3xa9_rgba="rgba(228,204,255,\1)"
dcol_pry4="B33D60"
dcol_pry4_rgba="rgba(179,61,96,\1)"
dcol_txt4="FEFEFE"
dcol_txt4_rgba="rgba(254,254,254,\1)"
dcol_4xa1="522935"
dcol_4xa1_rgba="rgba(82,41,53,\1)"
dcol_4xa2="6B3A48"
dcol_4xa2_rgba="rgba(107,58,72,\1)"
dcol_4xa3="7D4B5A"
dcol_4xa3_rgba="rgba(125,75,90,\1)"
dcol_4xa4="8F5768"
dcol_4xa4_rgba="rgba(143,87,104,\1)"
dcol_4xa5="A36578"
dcol_4xa5_rgba="rgba(163,101,120,\1)"
dcol_4xa6="C27A8F"
dcol_4xa6_rgba="rgba(194,122,143,\1)"
dcol_4xa7="E69AB0"
dcol_4xa7_rgba="rgba(230,154,176,\1)"
dcol_4xa8="F0AABF"
dcol_4xa8_rgba="rgba(240,170,191,\1)"
dcol_4xa9="FFCCDB"
dcol_4xa9_rgba="rgba(255,204,219,\1)"

```

**Comment by mahaveergurjar** [comment]
@kRHYME7 can you send me the files of your system waybar theme.css and wall-Dcol.css with and without wallbash

**Comment by kRHYME7** [comment]
Here

https://github.com/kRHYME7/Hyprdesk

I recently save it

**Comment by mahaveergurjar** [comment]
The files you used are correct in Hyperdesk used rgba format for color in wall-Dcol.css 
[https://github.com/kRHYME7/Hyprdesk/blob/Hyprdesk/Configs/.config/waybar/themes/Wall-Dcol.css](url)

BUt in @Tittu Hyprdots the file used hexa color due to this problem the wall-Dcol.css not fetch the color
[https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/waybar/themes/Wall-Dcol.css](url)
@prasanthrangan update the file wall-Dcol.css in waybar theme hexa color to rgba color format

**Comment by kRHYME7** [comment]
Try to regenerate it 

```  timeout 10 ~/.config/hyprdots/scripts/testrunner.sh ```

Try to execute this this might help in reloading the configurations

**Comment by mahaveergurjar** [comment]
Ok

**Comment by mahaveergurjar** [comment]
Thanks now working

**Comment by psilvaricardo** [comment]
@kRHYME7 @mahaveergurjar sorry as I am late on the discussion, I recently updated and reinstalled and my system is messed up. I do not see the waybar and some themes and/or wallpapers does not load.

do you have an specific fix ?

**Comment by kRHYME7** [comment]
See the pinned issues.

**Comment by FahriAl-Hafiz** [comment]
i follow everything but seems doesnt really work ,and when im run 

cat ~/.cache/hyprdots/Catppuccin-Mocha/aesthetic_deer.png.dcol
this is the output , kind of different 
dcol_pry1="0B1834"
dcol_txt1="FFFFFF"
dcol_1xa1="293652"
dcol_1xa2="3A496B"
dcol_1xa3="4B5B7D"
dcol_1xa4="57698F"
dcol_1xa5="6579A3"
dcol_1xa6="7A91C2"
dcol_1xa7="9AB2E6"
dcol_1xa8="AAC0F0"
dcol_1xa9="CCDCFF"
dcol_pry2="212748"
dcol_txt2="FFFFFF"
dcol_2xa1="292F52"
dcol_2xa2="3A416B"
dcol_2xa3="4B537D"
dcol_2xa4="57608F"
dcol_2xa5="656FA3"
dcol_2xa6="7A85C2"
dcol_2xa7="9AA5E6"
dcol_2xa8="AAB5F0"
dcol_2xa9="CCD4FF"
dcol_pry3="413054"
dcol_txt3="FFFFFF"
dcol_3xa1="3C2952"
dcol_3xa2="513A6B"
dcol_3xa3="634B7D"
dcol_3xa4="71578F"
dcol_3xa5="8265A3"
dcol_3xa6="9C7AC2"
dcol_3xa7="BE9AE6"
dcol_3xa8="CBAAF0"
dcol_3xa9="E4CCFF"
dcol_pry4="B33D60"
dcol_txt4="FEFEFE"
dcol_4xa1="522935"
dcol_4xa2="6B3A48"
dcol_4xa3="7D4B5A"
dcol_4xa4="8F5768"
dcol_4xa5="A36578"
dcol_4xa6="C27A8F"
dcol_4xa7="E69AB0"
dcol_4xa8="F0AABF"
dcol_4xa9="FFCCDB"
❯

**Comment by kRHYME7** [comment]
@FahriAl-Hafiz  did you pull the latest commits?  then run ``` ./install.sh -r ``` ? 

After that run ``` ./create_cache.sh -f ``` to regenerate the cache (your cache are outdated)

**Comment by FahriAl-Hafiz** [comment]
> @FahriAl-Hafiz did you pull the latest commits? then run `./install.sh -r` ?
> 
> After that run `./create_cache.sh -f` to regenerate the cache (your cache are outdated)

Thanks ,it worked.

**Comment by FahriAl-Hafiz** [comment]
@kRHYME7 sorry but i wanna ask , is it necessary to do
git pull
./install.sh -r
./create_cache.sh -f
everytime we got update ?

**Comment by kRHYME7** [comment]
@FahriAl-Hafiz  This depends on what kind of changes made. Example this one 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/3ade609f-b3c1-45ff-a12c-48980a522393)
