### ISSUE TITLE
Making theming easier for basic modifications

### ISSUE THREAD

**Issue by SpaceLarry14** [prasanthrangan/hyprdots#1189]
### Description

The documentation describing file structures for theme building is great, but it would be helpful to be able to understand what scripts are making changes to relevant css files (in the waybar folder for example) in order for custom css is to be made and not overriden during a theme selection

### Current Documentation

https://github.com/prasanthrangan/hyprdots/wiki/Theming

### Proposed Documentation

During a theme switch, any changes made to style.css is overriden by a process in the theme switching script, some documentation on how this occurs and what files are changed would allow much more freedom in waybar theming.

Take font size as an example, changing font size and minimum height is not achievable with the current set of documentation. Nor is more detail colour theming using basic css calls laid out in waybar/themes/theme.css. Being locked into the default colour scheme by the same override function described above.

**Comment by kRHYME7** [comment]
@SpaceLarry14  The documentation will be change soon. The Theme switching will be implemented differently.


 #### For waybar

``` ~/.config/waybar/modules/style.css ```  this is the file that the user should  modify
```~/.config/waybar/style.css ``` will always be overwritten by the script as this .css file is script  generated 

#### about the wayabr size

Take this for example

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/381c326c-b6fd-4f25-a6e3-2c62127847a6)

imagine the array to be in columns separated by '|'

+ 1st  - active/inactive status
+ 2nd - waybar scale size
+ 3rd - left module group
+ 4th - mid module group
+ 5th - right module group

We can divide each module group in to sections

example for mid module group 

| (mod1) (mod2) |

**Comment by Skerse** [comment]
Theming is now much better with the introduction of HyDE, All theme related files are now in one directory, making it completely dynamic! Making a new theme should be pretty simple, you can even just make minor modifications to an existing theme pretty easily.
