### ISSUE TITLE
[Error]: error during installation of some packages

### ISSUE THREAD

**Issue by lolrida** [prasanthrangan/hyprdots#1202]
### Description

it doesn't let me install these last packages which apparently are necessary.

### Screenshots

![Screenshot_20240326_234656](https://github.com/prasanthrangan/hyprdots/assets/97251836/135c0fcc-08c9-4b10-87bf-f5742f8362f4)

### Environment

ArchLinux

**Comment by kRHYME7** [comment]
try to run this first

``` yay -Sy hyprdots-ctl-git ``` what is the output?

**Comment by abenezerw** [comment]
Could you close as solved if you no longer have this issue. Thank you 
@lolrida
