### ISSUE TITLE
Waybar (config.json) breaks 

### ISSUE THREAD

**Issue by spdjky** [prasanthrangan/hyprdots#1203]
### Description

Waybar crashes randomly when i try to do stuff like switching dock mode, wallpaper, toggling wallbash.
This happens only when i use key binds to switch i believe. I tried to find the issue and when restarting waybar it reports the 'rotation' param is empty. I have to regen the config using wbarconfgen.sh to fix it.

I've tried moving to swww-git, waybar-git, rebuilding cache, restoring with install.sh. Nothing works.

I'm ready to provide more info if needed.

### Steps to Reproduce

1. Switch dock | wallpaper using key binds
2. waybar crashes 
3. cannot launch waybar manually

### Expected Behavior

Works normally

### Actual Behavior

Waybar Crashes

Im on Arch Linux on the latest versions of all packages. I just updated everything.

**Comment by kRHYME7** [comment]
Output when executing ``` ~/.config/hyprdots/scripts/swwwallpaper.sh -n ``` ?

**Comment by spdjky** [comment]
> Output when executing `~/.config/hyprdots/scripts/swwwallpaper.sh -n` ?

❯ ~/.config/hyprdots/scripts/swwwallpaper.sh -n
[skip] /home/barath/.config/cava
[skip] /home/barath/.config/spicetify/Themes/Sleek
waybar: no process found
eDP-1: 1280x720, scale: 2, currently displaying: image: /home/barath/.config/swww/Gruvbox-Retro/lady.png



also when i try to run waybar again:

❯ waybar

(waybar:3661): Gtk-WARNING **: 22:19:30.590: Theme parsing error: gtk.css:6691:68: Invalid name of pseudo-class
[2024-03-27 22:19:30.614] [info] Using configuration file /home/barath/.config/waybar/config.jsonc
[2024-03-27 22:19:30.615] [error] Error parsing JSON: * Line 26, Column 19
  Syntax error: value, object or array expected.

**Comment by kRHYME7** [comment]
```  timeout 10 ~/.config/hyprdots/scripts/testrunner.sh  ``` 

You can simulate all the functions. Try it 

> [!Important]
> You should probably rebuild your cache if you recently pulled ``` Hyprdots cache rebuild ```  Will takes some time.

**Comment by spdjky** [comment]
I've rebuilt my cache multiple times already.

> timeout 10 ~/.config/hyprdots/scripts/testrunner.sh

This works and returns my waybar. But as soon as I toggle wallbash off and on again it crashes. Even when I try to change my wallpaper/theme it takes around 5 - 7 sec then wallpaper/theme changes but waybar crashes.

Please note this only happens when I use keybinds (**super + alt + right** | **super + alt + up** | **super + shift + d**)
or 
when I use the theme/wallpaper switch menu
This is my waybar [config.jsonc](https://pastebin.com/1Es45zRf) after it crashes 

The buttons on the dock to switch works fine.
and
Hyprdots cli works fine 
```
Hyprdots wallbash toggle
Hyprdots theme select
Hyprdots wallpaper select
```

All of these are fine

I suspect the issue is with scaling as it reports 720p when my display is 1080p.
And the UI is broken on the select menus. I can fix those my self.

**Comment by spdjky** [comment]
```
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1541, in _shutdown
    def _shutdown():
    
  File "/home/barath/.config/waybar/modules/mediaplayer.py", line 22, in signal_handler
    sys.exit(0)
SystemExit: 0
[1]    244764 terminated  waybar -l trace
```


I tried launching waybar with -l error and got this. It outputs this only sometimes.
I'm not sure if it's helpful.

**Comment by kRHYME7** [comment]
The script directory should be adjusted . It was moved to .~/.config/hyprdots/scripts . So please remove the older folder.

**Comment by spdjky** [comment]
Thank you for your help.

I fixed it by deleting the `~/.config/hypr/scripts/` folder.

I changed the N to Y to overwrite the keybindings.conf in `~/Hyprdots/scripts/restore_cfg.lst`
This was the issue I feel. The monitors.conf and keybindings.conf never got overwritten and just skipped no matter how many times I reinstalled.

then ran `./restore_cfg.sh`
`./install.sh -r` should work fine I believe
