### ISSUE TITLE
[Bug]: Stuttering issue still have on nvidia 550.67-1 in hyprdots configuration

### ISSUE THREAD

**Issue by t101804** [prasanthrangan/hyprdots#1206]
### Description

Stuttering in vscode and other application

### Steps to Reproduce

use vscode/discord/other apps

### Expected Behavior

Normal usage like using v530?

### Actual Behavior

Stuttering

### Screenshots

https://github.com/prasanthrangan/hyprdots/assets/113588203/fae62113-9c5d-4618-bd6f-4343cc8d99ff

### Environment

- Linux Distro: Arch LInux
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by t101804** [comment]
also my spotify stutering

**Comment by Nidhogblo** [comment]
It may help to export the variables in your hyprland config: 

```  
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
```

For more info use : https://wiki.hyprland.org/Nvidia/                   
https://bbs.archlinux.org/viewtopic.php?id=291970

**Comment by Nidhogblo** [comment]
i forgot , make sure yo have qt5-wayland, qt5ct , libva and libva-nvidia-driver-git (AUR) , and reboot

**Comment by t101804** [comment]
> i forgot , make sure you have qt5-wayland, qt5ct , libva and libva-nvidia-driver-git (AUR) , and reboot

![image](https://github.com/prasanthrangan/hyprdots/assets/113588203/2da1e93b-1c21-416c-a324-b0bac8aa7eb5)


already configured but the same issue stil happen to me. alredy install also

**Comment by t101804** [comment]
> `env = LIBVA_DRIVER_NAME,nvidia env = XDG_SESSION_TYPE,wayland env = GBM_BACKEND,nvidia-drm env = __GLX_VENDOR_LIBRARY_NAME,nvidia env = WLR_NO_HARDWARE_CURSORS,1`

in the docs said its flickering u need to use 535:)

installing the 535xx versions of the drivers, as later (545, 550) can cause flickering with XWayland

    these are available for arch via [the AUR here](https://aur.archlinux.org/packages?O=0&K=535xx)

**Comment by NotAF0e** [comment]
This happens due to incompatibility between Wayland and electron.

You can fix this by going to  `/usr/share/applications/` then find the app you want to modify open its desktop entry. To the end of the Exec command add `--enable-features=UseOzonePlatform --ozone-platform=wayland`

**Comment by t101804** [comment]
> This happens due to incompatibility between Wayland and electron.
> 
> You can fix this by going to  `/usr/share/applications/` then find the app you want to modify,  open its desktop entry. To the end of the Exec command add `--enable-features=UseOzonePlatform --ozone-platform=wayland`

is there any alternative? usually i use 535 its working fine. do u have other alternative?

**Comment by NotAF0e** [comment]
@t101804 No sorry, I only know of that fix as it fixed my issues. I never used 535, just the most up to date driver

**Comment by abenezerw** [comment]
Could you close as solved if you no longer have this issue. Thank you 
@t101804
