### ISSUE TITLE
[Bug]: Sudo GUI prompt is not themed; Kde Policy Kit not following color scheme  

### ISSUE THREAD

**Issue by NotAF0e** [prasanthrangan/hyprdots#1217]
![240330_11h17m38s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/75176016/a541160c-5b45-438b-ba7a-d02b18bf8354)
As you can see above this sudo prompt is not themed. I am not sure if you can control this part of the UI but it does slightly detract from an otherwise beautiful rice.

**Comment by Xeo23** [comment]
same issue

**Comment by Skerse** [comment]
I'm thinking it might be a good idea to change our polkit agent, due to the theming issue. Also [polkit-kde-agent](https://archlinux.org/packages/extra/x86_64/polkit-kde-agent/) has a lot more dependencies compared to something simple like [polkit-gnome](https://archlinux.org/packages/extra/x86_64/polkit-gnome/).

A list of polkit options are listed here in section 1.1: https://wiki.archlinux.org/title/Polkit. If anyone has any recommendations feel free to say!

**Comment by dieBakterie** [comment]
[QT-Theming root applications](https://wiki.archlinux.org/title/Qt#Theme_not_applied_to_root_applications)

**Comment by dieBakterie** [comment]
[QT-Theming root applications](https://wiki.archlinux.org/title/Qt#Theme_not_applied_to_root_applications)
[GTK-Theming root applications](https://wiki.archlinux.org/title/GTK#Theme_not_applied_to_root_applications)
This has information regarding an Uniform Look for GTK- and QT-Apps/root applications.

**Comment by dieBakterie** [comment]
I'm personally fine with [polkit-gnome](https://archlinux.org/packages/extra/x86_64/polkit-gnome/) for Hyde.

**Comment by dieBakterie** [comment]
Are there any plans about changing to gnome polkit or another one?

**Comment by kRHYME7** [comment]
yes

**Comment by rubiin** [comment]
I am having similar issue with dunst

**Comment by Skerse** [comment]
> I am having similar issue with dunst

That's actually our issue, we don't have our own dunst notification style at the moment. Hopefully we have one soon!

**Comment by prasanthrangan** [comment]
> Are there any plans about changing to gnome polkit or another one?

has any one tried using `gnome-polkit` ? i just wanna know if it has similar issues like the kde polkit...


> > I am having similar issue with dunst
> 
> That's actually our issue, we don't have our own dunst notification style at the moment. Hopefully we have one soon!

There is no rofi layout available for notification action, I'll try making a new layout!
I wanna make one for screenshot too.. but will do that later :)

**Comment by Skerse** [comment]
> has any one tried using gnome-polkit ? i just wanna know if it has similar issues like the kde polkit...

Someone tried in the discord and reported it working perfectly.

**Comment by kRHYME7** [comment]
The gnome polkit follows the current gtk theme.  (been switching both polkits 😅 )

**Comment by prasanthrangan** [comment]
nice... then we can go ahead and replace kde with gnome

**Comment by prasanthrangan** [comment]
> I am having similar issue with dunst, heres what it looks like

I've added a rofi menu for notification actions in 843b7a3 -

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/1c3bb9fa-5469-42a0-9b15-0fa0b9cdc83a)
