### ISSUE TITLE
[Bug]: Kitty and alacritty crashes

### ISSUE THREAD

**Issue by Sveen** [prasanthrangan/hyprdots#1218]
### Description

After using kitty or alacritty it suddenly stops responding and refuses to close when i use the key binding 
### Steps to Reproduce

1. Update the system with sudo pacman -Syyu 
2. Use kitty until it crashes

# Actual Behavior
Cant type in any command or close the terminal

#Screenshots
![image](https://github.com/prasanthrangan/hyprdots/assets/140259096/4d222b9a-d0ec-432d-9274-7338d4eec86f)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: ArchLinu
-  Linux archlinux 6.8.2-arch2-1
- Hyprland Version, Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)

- Installation Environment: , On The Main Hardware,

**Comment by Nidhogblo** [comment]
* I'm looking for information but I didn't find anything similar.
* can you check Resource Usage // just to rule that out

by any chance have you felt your hyprland slow ?, I see that this is a common problem in hyprland.

if it's not one of those, tell me so I can look for where else the error might be.

**Comment by Sveen** [comment]
yes i felt that hyprland has been slow especially when i change the theme

**Comment by Nidhogblo** [comment]
i think is more problem of your drivers or wayland ,that a alacritty/kitty problem , Do you have nvidia or a especial gpu?

**Comment by kRHYME7** [comment]
Do you need a reboot to fix this ? or only happens in the terminal?

**Comment by Sveen** [comment]
Yes i need a reboot to fix it, but when the terminal crashes it sometimes affect the use of other apps and stops the laptop from functioning properly

**Comment by kRHYME7** [comment]
> Yes i need a reboot to fix it, but when the terminal crashes it sometimes affect the use of other apps and stops the laptop from functioning properly

I experienced this issues too, there is a possibility that your secondary drive where you install your Linux is failing or loose. 

I always experience this issue when
* My NVMe drive had loose screw
* I've used an old HDD 
* Installed Hyprland in a Thumb Drive. 

Usually occurs if drive is overwhelmed. Please check yours.

**Comment by Sveen** [comment]
I am dual booting it in primary drive and the problem did not start until i did an update and i don't think my HDD is that old.
Do you know of anything that could be the problem

**Comment by kRHYME7** [comment]
The second OS you dual boot works?

**Comment by Sveen** [comment]
yes it does and it's windows am dual booting with

**Comment by its-19818942118** [comment]
Actually same problem happens on my end too which is annoying so I open another terminal instance and kill kitty

**Comment by kRHYME7** [comment]
@Sveen  Hello do you still have these issues?

**Comment by abenezerw** [comment]
If you no longer have this problem, can you close out this issue. @Sveen

**Comment by kRHYME7** [comment]
Closing this as stale. 


For someone who might stumble with the Alacritty keyword here for HyDE here you go! https://github.com/HyDE-Project/terminals-hyde/tree/main/alacritty
