### ISSUE TITLE
[Bug]: swaylock-effects and swaylock-effects are in conflict

### ISSUE THREAD

**Issue by geeflaxx** [prasanthrangan/hyprdots#1219]
### Description

In the end of the installation it ask me to remove swaylock-effects because it is in conflict with swaylock-effects-git

### Steps to Reproduce

1. ./install.sh
### Expected Behavior
clean installation :dagger: 

### Actual Behavior

::swaylock-effects-git-r470.. and swaylock-effects-1.7.0... are in conflict (swaylock). Remove swaylock-effects? [y/N]

### Screenshots
![PXL_20240330_154932507 MP](https://github.com/prasanthrangan/hyprdots/assets/21129138/8841fddd-c65e-482d-b22f-2acb3fda93f0)

### Environment

e.g.,

- Linux Distro: Arch Linux
- Linux Version, output of `uname -a`: 6.8.2-arch2-1
- Hyprland Version, output of `hyprctl version`: HYPERLAND_INSTANCE_SIGNATURE not set!
- Installation Environment: Laptop
- Other info:FullHD

**Comment by kRHYME7** [comment]
how about pressing ``` y ``` when asked? 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/79de9acd-79e3-4feb-9183-b5476aa3ad58)

**Comment by Itz-Abhishek-Tiwari** [comment]
> ## Bug Report
> ### Description
> In the end of the installation it ask me to remove swaylock-effects because it is in conflict with swaylock-effects-git
> 
> ### Steps to Reproduce
> 1. ./install.sh
> 
> ### Expected Behavior
> clean installation 🗡️
> 
> ### Actual Behavior
> ::swaylock-effects-git-r470.. and swaylock-effects-1.7.0... are in conflict (swaylock). Remove swaylock-effects? [y/N]
> 
> ### Screenshots
> ![PXL_20240330_154932507 MP](https://private-user-images.githubusercontent.com/21129138/318203161-8841fddd-c65e-482d-b22f-2acb3fda93f0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MTM4MzAsIm5iZiI6MTcxMTgxMzUzMCwicGF0aCI6Ii8yMTEyOTEzOC8zMTgyMDMxNjEtODg0MWZkZGQtYzY1ZS00ODJkLWIyMmYtMmFjYjNmZGE5M2YwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE1NDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2Mzc3MjQ4OWRhYzYwMmQ2Y2Y2OGZmZmY3M2YzMGQxYmU1MTI0YTkxMTFlODM3MTM0ODlmMTI4M2Q0ZDg0NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tfi3T0p1Yh7tPfDlYNgPlZ-OEkB9iOe5nUiGAHxW6lo)
> 
> ### Environment
> e.g.,
> 
> * Linux Distro: Arch Linux
> * Linux Version, output of `uname -a`: 6.8.2-arch2-1
> * Hyprland Version, output of `hyprctl version`: HYPERLAND_INSTANCE_SIGNATURE not set!
> * Installation Environment: Laptop
> * Other info:FullHD
> 
> ### Additional Information

just press y
