### ISSUE TITLE
Error when installing hyprland-nvidia-git

### ISSUE THREAD

**Issue by wiscaksono** [prasanthrangan/hyprdots#122]
am doing a clean installation with my arch linux.
but in the middle of installation, i get an error when installing `hyprland-nvidia-git`, it need to install `wlroots` but the [site](https://gitlab.freedesktop.org/wlroots/wlroots/) it self is down, is there any alternative way to install it?

**Comment by AllStars101-sudo** [comment]
Yeah same issue here. Guess we'll just have to wait until it's back up?

**Comment by prasanthrangan** [comment]
> but in the middle of installation, i get an error when installing `hyprland-nvidia-git`, it need to install `wlroots` but the [site](https://gitlab.freedesktop.org/wlroots/wlroots/) it self is down, is there any alternative way to install it?

The only alternate i can think of is, using the hyprland package from official arch repo instead of git version.
So you could try updating line 20 in `custom_hypr.lst` to form `hyprland-git` to `hyprland` and then run the install script.

**Comment by wiscaksono** [comment]
i fix it by adding another repository mirror for my pacman, am using [`chaotic-aur`](https://aur.chaotic.cx/) and then install the `hyprland-nvidia-git` then reinstall the hyprdots
