### ISSUE TITLE
[Error]: Globbing error

### ISSUE THREAD

**Issue by s0me1newithhand7s** [prasanthrangan/hyprdots#1227]
### Description:
after creating and applying my Hyprland config with **only**  `sources` i've got `globbing error`

### System:
![image](https://github.com/prasanthrangan/hyprdots/assets/117505144/77de5b52-bdbc-4b88-ae2e-0ab238d741ca)

### How to reproduce:
1. NixOS in VM
2. My NixOS config
3. My Hyprland config

### Expected
Hyprland reads `source` and use configs

### Actual Behavior
errors on screenshots

### Screenshots (if applicable)
![image](https://github.com/prasanthrangan/hyprdots/assets/117505144/44b3df4b-1860-4af2-8c08-7ce76f9bc950)
![image](https://github.com/prasanthrangan/hyprdots/assets/117505144/955e8ef1-5981-49d2-8eb0-29e5aa066521)

### Steps before
1. tried to replace `~` with `/home/hand7s` 
2. tried to rename `hyprland.d` with `config`
3. tried generation with Hypland only
4. tried another VM with Hyprland only

### Additional Information
my host is Windows 11 with: 
![image](https://github.com/prasanthrangan/hyprdots/assets/117505144/412c70af-e476-418d-ae39-7f888aa95ca6)

my VM host is Oracle VM VirtualBox:
![image](https://github.com/prasanthrangan/hyprdots/assets/117505144/d98c76df-044e-4592-a678-ce18689beb32)

**Comment by Skerse** [comment]
I don't really understand NixOS, and these dotfiles aren't really designed for distros other than Arch so i don't think i can help you. If you want you can look at this discussion: https://github.com/prasanthrangan/hyprdots/discussions/166 to see you find anything helpful?

**Comment by s0me1newithhand7s** [comment]
there is no NixOS-specific options in my dots, as i've tested it with OpenSUSE, Fedora, Arch and Void. i don't think this is distro-specific error, as there was #687 with same "globbing" error. 
for now i'll make mono-config.

**Comment by kRHYME7** [comment]
Contents for ``` cat ~/.config/hypr/hyprland.conf ``` ? 

Also, can you check what lines are sourced?

**Comment by kRHYME7** [comment]
Sorry I'm ~a bit~ very confused, can you elaborate more why this repo "Hyprdots" related to " My NixOS config
My Hyprland config" ?

**Comment by s0me1newithhand7s** [comment]
~~idk how and why this happened~~

**Comment by kRHYME7** [comment]
If you ask why you got globing errors. It means that the file you tried to source do not exist.
