### ISSUE TITLE
How to remove the Brave browser installed through install.sh

### ISSUE THREAD

**Issue by hui3215** [prasanthrangan/hyprdots#1229]
How to remove the Brave browser installed through install.sh

**Comment by Skerse** [comment]
I'm confused, brave browser isn't installed with our script? Only firefox is in `Scripts/custom_hypr.lst`. Though to answer your question on how to remove it, just do `sudo pacman -S brave` (or maybe `brave-bin` / `brave-git` depending on your install method).

**Comment by kRHYME7** [comment]
flatpak uninstall <the app id of brave>

**Comment by Itz-Abhishek-Tiwari** [comment]
> How to remove the Brave browser installed through install.sh


` flatpak uninstall  com.brave.Browser  `

**Comment by hui3215** [comment]
> > How to remove the Brave browser installed through install.sh
> 
> `flatpak uninstall com.brave.Browser `

ok ,thank you
