### ISSUE TITLE
[Bug]: Package update button is not acurate/does not update (minor)

### ISSUE THREAD

**Issue by NotAF0e** [prasanthrangan/hyprdots#1233]
When manually updating packages the package update button never syncs. Also when clicking the button and quickly updating packages it also does not sync to show that there are no packages to update.

This could be fixed by checking if packages need to updated in the background occasionally and when commands such as yay are run which update the whole system.

Very minor but a bug never the less.

**Comment by Enigma1309** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/07ec2a67-017e-4848-ab36-356db5b42b94)
That is due to the update interval of waybar module.
By default it's one day, you may change it to something low,  
it's there in `~/.config/waybar/modules/updates.jsonc`

**Comment by NotAF0e** [comment]
Thank you! Should this be closed or?

**Comment by Enigma1309** [comment]
if it's fixed for you then you can :)

**Comment by NotAF0e** [comment]
👍

**Comment by NotAF0e** [comment]
Yeah the issue is sadly not fixed.
Bellow is my `updates.jsonc`:
```
"custom/updates": {
    "exec": "${ScrDir}/systemupdate.sh",
    "return-type": "json",
    "format": "󰮯 {}",
    "rotate": ${r_deg},
    "on-click": "${ScrDir}/systemupdate.sh up",
    "interval": 30, // once every 30 seconds
    "tooltip": true,
},

```
But the button never properly syncs.

**Comment by Enigma1309** [comment]
make sure you are also updating the flatpak apps as they aren't updated by yay or pacman, try `flatpak update`
![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/df42dfd9-c1ac-4f04-aa44-73a02e1da5b8)

**Comment by NotAF0e** [comment]
I don't have any flatpaks

**Comment by Enigma1309** [comment]
how off the number is from actual value? , cause i've tried it and it works

**Comment by NotAF0e** [comment]
Say there are 10 updates. I click the button and update. But the button still says that there are 10 updates until I click it again and then it says zero.

**Comment by kRHYME7** [comment]
That's expected. I'll try to push the fixes only in the dev branch. hyde

**Comment by NotAF0e** [comment]
Ok cool!

**Comment by Enigma1309** [comment]
> That's expected. I'll try to push the fixes only in the dev branch. hyde

can you explain me how and why?? cause it's working fine at my end

here's my updates.jsonc config
```   
 "custom/updates": {
        "exec": "${ScrDir}/systemupdate.sh",
        "return-type": "json",
        "format": "󰮯 {}",
        "rotate": ${r_deg},
        "on-click": "${ScrDir}/systemupdate.sh up",
        // "interval": 86400, // once every day
        "interval": 45, // once every 45 seconds
        "tooltip": true,
    },
```

**Comment by kRHYME7** [comment]
>         "interval": 45, // once every 45 seconds

😮 This should perfectly work, but I can't imagine my system will query every 45 seconds, for me that's bad for laptops. 
The query is intensive too {checkupdates, aurhelper and flatpak} 




> can you explain me how and why??

Sometimes it works, sometimes not. 


![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a49b8fdf-a317-4cf3-af4e-94825964dade)

example, I recently updated my system but still got the above values unless we tell waybar to run the script to query again. ( querying it on short interval is too bad) or reloading waybar is too hackish

Fortunately we can tell way bar to load a certain module .
```
    "custom/updates": {
        "exec": "systemupdate.sh",
        "return-type": "json",
        "format": "󰮯 {}",
        "rotate": ${r_deg},
        "on-click": "systemupdate.sh up",
        "interval": 86400, // once every day
        "tooltip": true,
	    "signal": 20,
    },
```



Then inside the systemupdate script you can add 

``` trap  'pkill -RTMIN+20 waybar' EXIT ```

Which tells waybar to reload the Module which has SIG 20

**Comment by kRHYME7** [comment]
>         "interval": 45, // once every 45 seconds

😮 This should perfectly work, but I can't imagine my system will query every 45 seconds, for me that's bad for laptops. 
The query is intensive too {checkupdates, aurhelper and flatpak} 




> can you explain me how and why??




![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a49b8fdf-a317-4cf3-af4e-94825964dade)

example, I recently updated my system but still got the above values unless we tell waybar to run the script to query again. ( querying it on short interval is too bad) or reloading waybar is too hackish

Fortunately we can tell way bar to load a certain module .
```
    "custom/updates": {
        "exec": "systemupdate.sh",
        "return-type": "json",
        "format": "󰮯 {}",
        "rotate": ${r_deg},
        "on-click": "systemupdate.sh up",
        "interval": 86400, // once every day
        "tooltip": true,
	    "signal": 20,
    },
```



Then inside the systemupdate.sh up script we can add 

``` trap  'pkill -RTMIN+20 waybar' EXIT ```
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c077aa1b-a8d0-4742-bfff-5e6103199032)


Which tells waybar to reload the Module which has signal 20 when the  scripts exit
