### ISSUE TITLE
[Bug]: No sound on headphone jack(s) from Application, internal speakers are working

### ISSUE THREAD

**Issue by win5923** [prasanthrangan/hyprdots#1236]
### Description

When adjusting the volume using the headphone jack, there is sound, but there is no sound when adjusting through the application. Bluetooth has been tested and is functioning normally, as are the internal speakers.

```
$ pacman -Qqs pipewire | pacman -Q linux -
linux 6.8.2.arch2-1
gst-plugin-pipewire 1:1.0.4-4
libpipewire 1:1.0.4-4
libwireplumber 0.5.1-1
pipewire 1:1.0.4-4
pipewire-alsa 1:1.0.4-4
pipewire-audio 1:1.0.4-4
pipewire-jack 1:1.0.4-4
pipewire-pulse 1:1.0.4-4
wireplumber 0.5.1-1
```

```
$ systemctl --user list-unit-files pipewire\*
UNIT FILE                        STATE    PRESE
T 
pipewire-pulse.service           enabled  enabled
pipewire-session-manager.service alias    -      

pipewire.service                 disabled 
enabled
pipewire-pulse.socket            enabled  enabled
pipewire.socket                  enabled  enabled

5 unit files listed.
```

```
$ pactl list sinks
Sink #53
	State: SUSPENDED
	Name: alsa_output.pci-0000_00_1f.3.analog-stereo
	Description: Built-in Audio Analog Stereo
	Driver: PipeWire
	Sample Specification: s32le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 4294967295
	Mute: no
	Volume: front-left: 59311 /  91% / -2.60 dB,   front-right: 59311 /  91% / -2.60 dB
	       balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor Source: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY 
	Properties:
		alsa.card = "0"
		alsa.card_name = "HDA Intel PCH"
		alsa.class = "generic"
		alsa.device = "0"
		alsa.driver_name = "snd_hda_intel"
		alsa.id = "ALC256 Analog"
		alsa.long_card_name = "HDA Intel PCH at 0x6022188000 irq 212"
		alsa.name = "ALC256 Analog"
		alsa.resolution_bits = "16"
		alsa.subclass = "generic-mix"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		api.alsa.card.longname = "HDA Intel PCH at 0x6022188000 irq 212"
		api.alsa.card.name = "HDA Intel PCH"
		api.alsa.path = "front:0"
		api.alsa.pcm.card = "0"
		api.alsa.pcm.stream = "playback"
		audio.channels = "2"
		audio.position = "FL,FR"
		card.profile.device = "7"
		device.api = "alsa"
		device.class = "sound"
		device.id = "49"
		device.profile.description = "Analog Stereo"
		device.profile.name = "analog-stereo"
		device.routes = "2"
		factory.name = "api.alsa.pcm.sink"
		media.class = "Audio/Sink"
		device.description = "Built-in Audio"
		node.name = "alsa_output.pci-0000_00_1f.3.analog-stereo"
		node.nick = "ALC256 Analog"
		node.pause-on-idle = "false"
		object.path = "alsa:pcm:0:front:0:playback"
		priority.driver = "1009"
		priority.session = "1009"
		factory.id = "18"
		clock.quantum-limit = "8192"
		client.id = "45"
		node.driver = "true"
		factory.mode = "merge"
		audio.adapt.follower = ""
		library.name = "audioconvert/libspa-audioconvert"
		object.id = "53"
		object.serial = "53"
		api.acp.auto-port = "false"
		api.alsa.card = "0"
		api.alsa.use-acp = "true"
		api.dbus.ReserveDevice1 = "Audio0"
		api.dbus.ReserveDevice1.Priority = "-20"
		device.bus = "pci"
		device.bus_path = "pci-0000:00:1f.3"
		device.enum.api = "udev"
		device.form_factor = "internal"
		device.icon_name = "audio-card-analog-pci"
		device.name = "alsa_card.pci-0000_00_1f.3"
		device.nick = "HDA Intel PCH"
		device.plugged.usec = "5772197"
		device.product.id = "0x51c8"
		device.product.name = "Alder Lake PCH-P High Definition Audio Controller"
		device.subsystem = "sound"
		sysfs.path = "/devices/pci0000:00/0000:00:1f.3/sound/card0"
		device.vendor.id = "0x8086"
		device.vendor.name = "Intel Corporation"
		device.string = "0"
	Ports:
		analog-output-speaker: Speakers (type: Speaker, priority: 10000, availability group: Legacy 2, availability unknown)
		analog-output-headphones: Headphones (type: Headphones, priority: 9900, availability group: Legacy 3, not available)
	Active Port: analog-output-headphones
	Formats:
		pcm
```

```
wpctl status
PipeWire 'pipewire-0' [1.0.4, blocka@archlinux, cookie:2308705921]
 └─ Clients:
        31. WirePlumber                         [1.0.4, blocka@archlinux, pid:789]
        32. pipewire                            [1.0.4, blocka@archlinux, pid:790]
        45. WirePlumber [export]                [1.0.4, blocka@archlinux, pid:789]
        56. xdg-desktop-portal-hyprland         [1.0.4, blocka@archlinux, pid:1474]
        57. waybar                              [1.0.4, blocka@archlinux, pid:894]
        58. waybar                              [1.0.4, blocka@archlinux, pid:894]
        59. Blueman                             [1.0.4, blocka@archlinux, pid:896]
        60. Brave input                         [1.0.4, blocka@archlinux, pid:192]
        67. wpctl                               [1.0.4, blocka@archlinux, pid:59123]

Audio
 ├─ Devices:
 │      49. Built-in Audio                      [alsa]
 │  
 ├─ Sinks:
 │      53. Built-in Audio Analog Stereo        [vol: 0.91]
 │  
 ├─ Sources:
 │  *   54. Built-in Audio Analog Stereo        [vol: 1.00]
 │  
 ├─ Filters:
 │  
 └─ Streams:

Video
 ├─ Devices:
 │  
 ├─ Sinks:
 │  
 ├─ Sources:
 │  
 ├─ Filters:
 │  
 └─ Streams:

Settings
 └─ Default Configured Devices:
❯ wpctl status
PipeWire 'pipewire-0' [1.0.4, blocka@archlinux, cookie:2308705921]
 └─ Clients:
        31. WirePlumber                         [1.0.4, blocka@archlinux, pid:789]
        32. pipewire                            [1.0.4, blocka@archlinux, pid:790]
        45. WirePlumber [export]                [1.0.4, blocka@archlinux, pid:789]
        56. xdg-desktop-portal-hyprland         [1.0.4, blocka@archlinux, pid:1474]
        57. waybar                              [1.0.4, blocka@archlinux, pid:894]
        58. waybar                              [1.0.4, blocka@archlinux, pid:894]
        59. Blueman                             [1.0.4, blocka@archlinux, pid:896]
        60. Brave input                         [1.0.4, blocka@archlinux, pid:192]
        67. wpctl                               [1.0.4, blocka@archlinux, pid:59520]

Audio
 ├─ Devices:
 │      49. Built-in Audio                      [alsa]
 │  
 ├─ Sinks:
 │      53. Built-in Audio Analog Stereo        [vol: 0.91]
 │  
 ├─ Sources:
 │  *   54. Built-in Audio Analog Stereo        [vol: 1.00]
 │  
 ├─ Filters:
 │  
 └─ Streams:

Video
 ├─ Devices:
 │  
 ├─ Sinks:
 │  
 ├─ Sources:
 │  
 ├─ Filters:
 │  
 └─ Streams:

Settings
 └─ Default Configured Devices:
```

[Provide a clear and concise description of the bug.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/56353753/abcdc631-5798-434f-b4cb-1d9ac6ab3498)
![image](https://github.com/prasanthrangan/hyprdots/assets/56353753/d9c02af4-2a61-475c-974e-62cad311677d)
![image](https://github.com/prasanthrangan/hyprdots/assets/56353753/17a426c6-2720-4bd7-a90b-bdfe15bf59f6)
![image](https://github.com/prasanthrangan/hyprdots/assets/56353753/ce53141e-d304-41dc-948a-aec46dac201e)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`:
```
Linux archlinux 6.6.23-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 27 Mar 2024 07:47:20 +0000 x86_64 GNU/Linux
```
- Hyprland Version, output of `hyprctl version`:
```
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)
```
- Installation Environment: On The Main Hardware
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by Enigma1309** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/1c0ce6a0-f3a2-4d6a-8eaf-f3fe529a1c55)
these packages are also needed for pipewire to work correctly, i also had the somewhat same issue back then i got it working by installing these 

```
alsa-card-profiles
alsa-firmware
alsa-lib
alsa-plugins
alsa-topology-conf
alsa-ucm-conf
alsa-utils
lib32-alsa-lib
lib32-alsa-plugins
pipewire-alsa
```

**Comment by win5923** [comment]
> ![image](https://private-user-images.githubusercontent.com/94917588/318742852-1c0ce6a0-f3a2-4d6a-8eaf-f3fe529a1c55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTU3ODIsIm5iZiI6MTcxMjA1NTQ4MiwicGF0aCI6Ii85NDkxNzU4OC8zMTg3NDI4NTItMWMwY2U2YTAtZjNhMi00ZDZhLThlYWYtZjNmZTUyOWExYzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDEwNTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMDJiNjUyMmE1NzRjZDY4NWI4NjFjNmNiYTIwZTVjYzVmNTMxZjMxYmFjZGZiNWFjZjdkYmNjYzk3NzYyZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zVAEO7SplU3qelicvF1NF0ZdhQMDen9Mg4NyUDWrcnU) these packages are also needed for pipewire to work correctly, i also had the somewhat same issue back then i got it working by installing these
> 
> ```
> alsa-card-profiles
> alsa-firmware
> alsa-lib
> alsa-plugins
> alsa-topology-conf
> alsa-ucm-conf
> alsa-utils
> lib32-alsa-lib
> lib32-alsa-plugins
> pipewire-alsa
> ```

I've installed all packages and reboot but still no sound on my headphone. 
Not sure what the reason is....

**Comment by Enigma1309** [comment]
try running alsamixer

**Comment by win5923** [comment]
> try running alsamixer

![image](https://github.com/prasanthrangan/hyprdots/assets/56353753/c1f8d748-c585-452a-8e5d-096723cd23ca)

**Comment by Enigma1309** [comment]
have you tried checking any other browser/ source of audio?

also try checking the pipewire section of archwiki

**Comment by win5923** [comment]
> have you tried checking any other browser/ source of audio?
> 
> also try checking the pipewire section of archwiki

Yes, I tried firefox,but still got same issue.

**Comment by win5923** [comment]
Alsamixer:

![image](https://github.com/prasanthrangan/hyprdots/assets/56353753/c09d2743-5a5e-40cc-9c60-83843be1cc06)

**Comment by Enigma1309** [comment]
ohh i was scratching my head but... it's good if it worked :+1:  

but did the jack problem got solved?

**Comment by win5923** [comment]
> ohh i was scratching my head but... it's good if it worked 👍
> 
> but did the jack problem got solved?

not yet. 😢

**Comment by win5923** [comment]
I tried the way one from ZeroAnarchy, The problem got sloved!
I created a file, and shutdown the system and turn on.
```
$cat /etc/modprobe.d/alsa.conf
options snd-hda-intel model=headset-mode
```
Ref: https://forum.manjaro.org/t/sound-from-speakers-no-sound-from-3-5mm-jack-audio/5343/20

**Comment by capGoblin** [comment]
If anyone encountered the same problem and the above solution by @win5923 didn't work for you (didn't work for me)


Try this, especially if the output device is labeled as "dummy output":

- create the file: /etc/modprobe.d/audio-fix.conf

- and paste these two lines into it:
`blacklist snd-sof-pci`
`options snd-intel-dspcfg dsp_driver=1`

Answer by [anti4r](https://unix.stackexchange.com/users/246879/anti4r) here: https://unix.stackexchange.com/questions/633019/arch-linux-doesnt-recognize-sound-driver-dummy-output

**Comment by b01programmer** [comment]
in ubuntu 24.04 i just uninstalled via `sudo apt autoremove pipewire` and unmuted headphone in `alsamixer`
it worked for me.

**Comment by Sahil0912** [comment]
@capGoblin I have tried both the methods but still no sound is coming.
The headphones are getting detected as well the sound levels are also changing as I do but no sound is coming.
In the pavucontrol too the headphones are detected and the sound can be seen  but no sound coming out
