### ISSUE TITLE
Glitched Wallpaper

### ISSUE THREAD

**Issue by iEscapedVim** [prasanthrangan/hyprdots#1237]
## Bug Report
The wallpapers look like this 
![image](https://github.com/prasanthrangan/hyprdots/assets/32537564/9a50a458-e9fd-460b-8377-3a6bfe308aa6)

### Description

The screen is fine opening any application 
![image](https://github.com/prasanthrangan/hyprdots/assets/32537564/5936b748-c962-4575-aa42-2df842dd71e7)

### Steps to Reproduce

Not that I can think of any but maybe after .xz update, idk not sure, I restarted my laptop like after three days.

### Expected Behavior

Have normal looking screen

### Actual Behavior

Glitched Wallpaper

### Environment

- Linux Distro: ArchLinux
- Linux Version: Linux Bimo 6.8.2-zen2-1-zen # 1 ZEN SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:20 +0000 x86_64 GNU/Linux
- Hyprland Version: Hyprland, built from branch HEAD at commit 3875679755014997776e091ff8903acfb311dd2f  (props: bump ver to 0.38.0).

### Installation Environment: 
- HP Elitebook 840 G3
- CPU: Intel i5-6300U
- GPU: Intel HD 520

**Comment by RookiexCookie** [comment]
hey check this out
#1204

**Comment by iEscapedVim** [comment]
> hey check this out #1204

give this output not sure

```
❯ swww-daemon --format xrgb
Error: "couldn't bind socket: Address already in use (os error 98)"
```
```
❯ sudo swww-daemon --format xrgb
[sudo] password for zero: 
thread 'main' panicked at daemon/src/main.rs:129:45:
failed to connect to the wayland server: NoCompositor
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
04:09:26 [INFO] (main) Removed socket at "/tmp/swww/swww.socket"
```

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/issues/1204

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c0e241e4-fb7d-4466-99b4-aae67a991959)

whichever is convenient, you can also install ``` swww-git ````  both have the same effect. Needs a reboot / relogin to take effect

Also this is a dupe so please comment any queries on the pinned thread so we can make it better
