### ISSUE TITLE
[Bug]: Can't increase Rofi's drun etc icon's size

### ISSUE THREAD

**Issue by PWDSerialgamer07** [prasanthrangan/hyprdots#1241]
### Description

I'm trying to increase the size of the respective icons of display-drun, display-run, display-filebrowser and display-window, and nothing I tried worked.

### Steps to Reproduce

1. Edit Rofi styles config
2. Under "element-icon", increase "size"
3. Update rofi appearance by switching to another them and back

### Expected Behavior

Icons become bigger

### Actual Behavior

Nothing happens

### Screenshots
Default size (48px):
![image](https://github.com/prasanthrangan/hyprdots/assets/118306463/7bd68283-2c20-4ef3-afb8-2c45a8e7ca6b)
Custom size(150px):
![image](https://github.com/prasanthrangan/hyprdots/assets/118306463/9aa78947-d41d-4e95-aad5-4db5f0ed339d)

### Environment

Distro: EndeavourOS
Linux Version: Linux F****** 6.8.2-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000 x86_64 GNU/Linux
Hyprland Version: v0.38.0
Env: main hardware
Resolution: 2240x1400
e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

Attempted after fresh update

**Comment by kRHYME7** [comment]
It is overwritten by the script.
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/9f77b91b-789b-4560-a663-b9c1f1686dd8)

Would it be nice to add an option to override this ? something like 

``` examplerofiscript -w  90px -h 80px --glyph -100 ```

**Comment by PWDSerialgamer07** [comment]
yeah it would be nice, because if someone has the same problem as me, Ie the icons being too small and not centered it would be kinda hard to fix.

**Comment by kRHYME7** [comment]
should be fix on the upcoming release

**Comment by abenezerw** [comment]
If this problem was resolved could you close this issue. @PWDSerialgamer07
