### ISSUE TITLE
cannot change cursor size 

### ISSUE THREAD

**Issue by jenil1122** [prasanthrangan/hyprdots#1243]
cursor size was perfect when i was Hyprland using at auto resolution 
Ii changed the resolution of my hyprland.conf for Gaming :
From : 
```
monitor = eDP-1,highres,auto,1
```
To :
```
monitor = eDP-1,800x450,auto,1
```
I tried a lot to change my cursor from terminal and nwg-look gui but it didnt work
i tried the following : 
```
gsettings set org.gnome.desktop.interface cursor-size 10
```
```
hyprctl setcursor 10
```
**Nothing Worked**

**Comment by jenil1122** [comment]
with nwg-look i was able to increase size but couldn't go below 6 .
at current resolution the size of cursor is big & i want it  at atleast 2-3

**Comment by rubiin** [comment]
+1 i cannot change the curso size as well

**Comment by kRHYME7** [comment]
`
exec = hyprctl setcursor Bibata-Modern-Ice 50
exec = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec = gsettings set org.gnome.desktop.interface cursor-size 50
`

add this to your userprefs.conf

 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a041021c-aca6-40ba-b22a-f097b1ab7f45)


Note: you might find it that the cursors are inconsistent. I don't have solutions for that.

**Comment by kRHYME7** [comment]
upstream
