### ISSUE TITLE
pixel arts in terminal

### ISSUE THREAD

**Issue by MadSkillZzZz** [prasanthrangan/hyprdots#1244]
i'm not sure it is a right place for asking something like this, but how do i change or even disable pixel arts in terminal and how can i change this thing at the start of a line(idk what it's name, so i marked it with red circle)?
![240405_02h09m24s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/143466033/4d3434cc-9253-4143-b986-8fa9be395fc3)

**Comment by Nidhogblo** [comment]
What you mark with the circle is the promt, and of course it can be modified. 
For more info : (the project ohmyzsh is the most famous project and  easy)
https://ohmyz.sh/
https://dev.to/cassidoo/customizing-my-zsh-prompt-3417

**Comment by MadSkillZzZz** [comment]
what about the picture? It just appears everytime i open terminal?

**Comment by Nidhogblo** [comment]
and of course the pixelated pokemon art can be deactivated(although I wouldn't know why you would do that :D )
to do this:
open the .zshrc go to last code line and comment this line : 
![image](https://github.com/prasanthrangan/hyprdots/assets/90667852/86985e03-7496-481b-bdbc-f7696a396e11)

**Comment by Nidhogblo** [comment]
if I did not make myself clear, ask me :D

**Comment by MadSkillZzZz** [comment]
yeah, it helped. Pretty clear, thank you :)

**Comment by Nidhogblo** [comment]
Men,i search more of the packages on hyprdots about the shell ,
![image](https://github.com/prasanthrangan/hyprdots/assets/90667852/8b66bd0a-9e06-4a6d-8132-769cf9291a4d)
you can search here how much you can modify or of course, if you want to modify more things or install more things
