### ISSUE TITLE
[Feature Request]: Add a confirmation whether you want to style certain apps

### ISSUE THREAD

**Issue by rubiin** [prasanthrangan/hyprdots#1247]
### Description

Thanks for the configuration. Can we have a section that prompts user whether a user want to change certain apps. For example in my case, I have my own kitty and vscode config and dont want the configuration from the repo.

### Use Case

Use your own config

### Proposed Solution

Would like an option that would prompt user before applying the config and theming 

### Alternatives

[Are there any alternative solutions or workarounds that you've considered? If so, describe them here.]

### Additional Information

[Add any other information about the feature request here. For example, you might include links to similar features in other projects, or screenshots or diagrams to help explain your idea.]

**Comment by kRHYME7** [comment]
Hello this does not happen interactively but if you explore the files there is a file called ./restore_cfg.lst  find the line that you want to be user pref. You can either omit the line
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/6fc2d673-f9fa-44e1-a810-e62f5dc09b37)

Future plans
Soon the Hyprdots repo will be called 'HyDE' and on this branch  we are trying to work on different implementation. Together with that is the CLI for Hyde. (Hyde-cli) 

Here's a snippet where you can control what dots you want to populate on your system 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/66c5df33-8e0c-48bb-a39d-7152b06e81be)

**Comment by rubiin** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/8222059/45e7a793-0702-4365-90ad-c2502b4ea14d)
Also the rofi launcher seems big on my laptop


this is what i am using for scaling

```lua

xwayland {
    force_zero_scaling = true
    }

monitor=,highres,auto,1.3333

```
