### ISSUE TITLE
[Feature Request]: Add blue light filter

### ISSUE THREAD

**Issue by rubiin** [prasanthrangan/hyprdots#1248]
### Description
Coming from kde , I do miss the night light feature.  Is it possible to add 

### Use Case

[Describe how this feature would be useful to you or to other users of the project.]

### Proposed Solution
 Use something like redshift

### Alternatives

[Are there any alternative solutions or workarounds that you've considered? If so, describe them here.]

### Additional Information

[Add any other information about the feature request here. For example, you might include links to similar features in other projects, or screenshots or diagrams to help explain your idea.]

**Comment by Enigma1309** [comment]
use hyprshade
- install it via 
`yay -S hyprshade`

- add this line to you userprefs.conf 
```exec=hyprshade auto```

- make `hyprshade.toml` in `~/.config/hypr/`
and put the following code in it
```
[[shades]]
name = "blue-light-filter"
start_time = 18:00:00
end_time = 07:00:00
```

you can customize it even more [see](https://github.com/loqusion/hyprshade?tab=readme-ov-file#scheduling)

- enable hyprshade
`hyprshade install`
`systemctl --user enable --now hyprshade.timer`
---

here's my custom config (in hyprshade.toml)
``` 
[[shades]]
name = "vibrance"
default = true

[[shades]]
name = "blue-light-filter"
start_time = 18:00:00
end_time = 07:00:00
```

and custom key-bind in `userprefs.toml` (in case i have to turn it off manually)
![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/98ba68c1-27cd-4ab8-bfb9-120d81f794eb)

--- 

in case something don't work refer to the the [hyprshade repo](https://github.com/loqusion/hyprshade)

**Comment by celikj** [comment]
mouse cursor doesnt change with this

**Comment by Enigma1309** [comment]
yeah it uses hyprland screenshader feature as an bluelight switcher which currently does not support mouse shading.


i think it won't matter unless you're using a very huge mouse font, in that case look for alternatives like #1616 (i haven't tested them so i'm not fully sure if it works or not)
