### ISSUE TITLE
[Bug]: Keybindings hint does not activate on click

### ISSUE THREAD

**Issue by Radrahil** [prasanthrangan/hyprdots#1251]
The keybindings hint in the waybar does NOT activate on click despite it working if you execute the script manually.
```
    "custom/keybindhint": {
        "format": " ",
        "rotate": 0,
        "on-click": "~/.config/hyprdots/scripts/keybinds_hint.sh"
    },
```
The rest work as expected

**Comment by kRHYME7** [comment]
Hey, I think you're running on the dev branch ?  

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/91107906-cb59-4200-aa77-6c3ccab717df)

**Comment by Radrahil** [comment]
It would seem so. However, changing it to the one in your image has no change. Furthermore, only keybinds is affected for some reason. How do I fix this?

**Comment by kRHYME7** [comment]
after changing this, you should probably reload waybar by changing waybar layout so the configs will refresh.

**Comment by Radrahil** [comment]
changing it to  ```"on-click": "~/.local/share/bin/keybinds_hint.sh"``` did the trick, thanks
