### ISSUE TITLE
Sidebar for notification history and quick toggles.

### ISSUE THREAD

**Issue by Xeo23** [prasanthrangan/hyprdots#1252]
### Description

A sidebar containing all notifications history and quick toggles like wifi, bluetooth, dnd, audio, night light, etc. and also a todo list.

### Use Case

A sidebar would be very helpful for many. I use KDE connect all the time and It's a hassle to execute `dunstctl history-pop` every time to see notification history. And a to-do list would also be nice to have.

### Proposed Solution

https://github.com/end-4/dots-hyprland 
I have seen an implementation here, but not sure how it is done.  I think it's AGS.

**Comment by Skerse** [comment]
The only known notification daemons that have a graphical history are [swaync](https://github.com/ErikReider/SwayNotificationCenter) and [ags](https://github.com/Aylur/ags) (however ags isn't primarily a notification daemon and you do kind of have to manually set that up). The only way i see it being maybe possible is with [dunst](https://github.com/dunst-project/dunst) is `dunstctl history` and using [rofi](https://github.com/lbonn/rofi).

I think we have thoughts on adding swaync as an install option (which is so much easier to configure and can include some of the quick toggle you mentioned), so perhaps in the future that will become a thing!

**Comment by Enigma1309** [comment]
being discussed in #709 and #1023, meanwhile you can use swaync since a lot of dependency on dunst has been removed from repo

**Comment by kRHYME7** [comment]
@Xeo23  We can  further this discussion at https://github.com/prasanthrangan/hyprdots/issues/1023
