### ISSUE TITLE
[Bug]: Google-Chrome and Brave does'nt change theme but firefox does 

### ISSUE THREAD

**Issue by aryan-212** [prasanthrangan/hyprdots#1255]
If I have a chome tab or brave opened and I change the theme, the current instance does'nt change the theme. But firefox changes it themes live. I have selected GTK as thier theme in all the browsers.

**Comment by Enigma1309** [comment]
Choose Gtk or QT theme in brave settings.

![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/a25ca27f-a1c2-4c4f-bc81-7abaf4a77ef3)

also you have to reopen the browser for theme to be updated.

also chrome comes default by qt setting (i guess) the steps should be similar on both.
