### ISSUE TITLE
[Bug]: 2 errors after installation

### ISSUE THREAD

**Issue by Yakumo-Yukari** [prasanthrangan/hyprdots#1256]
![240406_19h16m04s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/12076232/7db8dbcd-8f62-4ca7-8a69-38a6de42355a)

 After logging out and logging back in, the wallpaper would fail to load. Of course, some programs, such as rofi, could not be launched via shortcut keys.

**Comment by aryan-212** [comment]
running `swww init` might fix the wallpaper

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/issues/1204

Actually the issue is pinned.
