### ISSUE TITLE
[Bug]: Clipboard history can't be wiped

### ISSUE THREAD

**Issue by Radrahil** [prasanthrangan/hyprdots#1259]
I'm not sure what hyprdots uses for its clipboard, but cliphist wipe doesn't persist between reboots, and middle click + yes on clipboard also doesn't work. What do I do to completely  clear clipboard?

**Comment by Radrahil** [comment]
removing ~/.cache/cliphist/db does the trick, but cliphist wipe doesn't work

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/0101416d-51b4-4181-9f72-f55f37daa5fa)

This did not work?

**Comment by Radrahil** [comment]
That is correct, it did not. Try rebooting. As a "hack" solution I'm simply removing the db file.

**Comment by Skerse** [comment]
Can we get terminal logs to see if any errors explain what's wrong?

Hyprdots: `~/.config/hyprdots/scripts/cliphist.sh w`
Hyde: `~/.local/share/bin/cliphist.sh w`

**Comment by Skerse** [comment]
Any update on this? As far as I know, no one else has this issue.. if you have a response/update feel free to reopen the issue but i'm going to close this for now.
