### ISSUE TITLE
[Bug]: SDDM theme unmasks user password

### ISSUE THREAD

**Issue by RBMLWizard** [prasanthrangan/hyprdots#1263]
### Description
The SDDM theme in the install script unmasks the password while the user is typing, posing a security risk. Attempts to fix this by modifying the SDDM configuration file in /etc have been unsuccessful. 

### Steps to Reproduce
1. Fresh install Arch.
2. Install the script.
3. Reboot.

### Expected Behavior
The password should be masked/asterik while typing.

### Actual Behavior
The password is visible as you type.

### Environment
- Operating System: Arch Linux

**Comment by Luiz0047** [comment]
Its happening to me as well

**Comment by Pallaxis** [comment]
There's a setting in /usr/share/sddm/themes/(theme-you-picked)/theme.conf called ForceHideCompletePassword, mine was in Candy and I just set that to true to fix

**Comment by Luiz0047** [comment]
> There's a setting in /usr/share/sddm/themes/(theme-you-picked)/theme.conf called ForceHideCompletePassword, mine was in Candy and I just set that to true to fix

This worked for me, thanks

**Comment by abenezerw** [comment]
Can you mark this as resolved please. @RBMLWizard

**Comment by kRHYME7** [comment]
We accept PRs in fixing this. I guess users in general would prefer this option.

**Comment by abenezerw** [comment]
> We accept PRs in fixing this. I guess users in general would prefer this option.

I have one right after the hyprlock one. It’s already made. You can check the sddm in my repo. Basically we just theme one as the default for Hyde. Then we can achieve singularity over the theming and rules the 9 kingdoms.
