### ISSUE TITLE
[Feature Request]: Waybar icon size keeps changing every reboot

### ISSUE THREAD

**Issue by RBMLWizard** [prasanthrangan/hyprdots#1264]
### Description

The size of the Waybar and icon sizes revert across reboots and also when switching between themes.

### Use Case

This feature would ensure a consistent user experience by maintaining the size of Waybar and icons across reboots and theme changes, enhancing usability and aesthetics.

### Proposed Solution

One alternative could be implementing a feature that allows users to manually set the size of Waybar and icons using UI in Waybar itself, providing more control over their appearance.

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/fee2078c-dad2-4d0c-8d8e-7c247b1a10ce)

Do not modify this auto generated files
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/0ade1d0a-fcde-4e70-9aa1-2c42f7212d5a)

**Comment by abenezerw** [comment]
Can you also mark this as resolved please. @RBMLWizard
