### ISSUE TITLE
[Bug]: Ethernet not working

### ISSUE THREAD

**Issue by rohansharma-developer** [prasanthrangan/hyprdots#1265]
I installed hyprdots on a fresh installation of arch linux.

when i try to connect my computer to the router via ethernet, the internet status in the waybar changes to connecting, and it just never connects to the router. Therefore, no internet :(

**Comment by kRHYME7** [comment]
Archinstall?

**Comment by rohansharma-developer** [comment]
Just resolved the issue! My pc was connected to the router in the router’s second LAN port. I just switched it to the first one and it randomly started working. I guess it was a router issue.
