### ISSUE TITLE
[Feature Request]: Kitty saying which process block

### ISSUE THREAD

**Issue by noahfraiture** [prasanthrangan/hyprdots#1267]
### Description

Hello, I often have  some bug in my terminal where a background process doesn't want use close the terminal and it's pretty normal and common. I think it would be good if the terminal, when asking us if we want to close can tell us what process block. 
I got the "idea" when I saw that the default behavior in EndeavourOS does that.
However I have no idea what do that, even if the close confirmation is from kitty or something else.

Does someone know if it's something possible with kitty ?

An alternative could be to change the terminal emulator but I don't think it's worth the effort

**Comment by Nidhogblo** [comment]
Men , i think this could be help you,you can copy and paste on your bashrc/zshrc/(or what ever you use) : 
```
# Get the PID of the process using the terminal's lock file
pid=$(fuser ~/.config/kitty/running_lock)

if [ -n "$pid" ]; then
    # Get information about the process blocking the terminal
    process_info=$(ps -p $pid -o comm=)
    echo "The terminal is being used by the process: $process_info"
else
    echo "The terminal is not being blocked by any process."
fi
```

**Comment by noahfraiture** [comment]
It does nothing except saying
`Specified filename /home/noah/.config/kitty/running_lock does not exist.
The terminal is not being blocked by any process.` at the opening of the terminal

**Comment by kRHYME7** [comment]
>  I got the "idea" when I saw that the default behavior in EndeavourOS does that.

What terminal on endeavorOS does this? Any material could help.

**Comment by Nidhogblo** [comment]
my apologies ,I didn't make myself clear,this code It wasn't meant to be taken so literally, it was more of an example,but I looked for a solution and put a request directly into kitty's code.
the request has been answered and a solution has been found.
check this :
https://github.com/kovidgoyal/kitty/issues/7331
https://github.com/kovidgoyal/kitty/commit/1c8fd0ccc4134c2c40ad946f300a3be2dfdf922b

**Comment by Nidhogblo** [comment]
> It does nothing except saying `Specified filename /home/noah/.config/kitty/running_lock does not exist. The terminal is not being blocked by any process.` at the opening of the terminal

my apologies ,I didn't make myself clear,this code It wasn't meant to be taken so literally, it was more of an example,but I looked for a solution and put a request directly into kitty's code.
the request has been answered and a solution has been found.
check this :
https://github.com/kovidgoyal/kitty/issues/7331
https://github.com/kovidgoyal/kitty/commit/1c8fd0ccc4134c2c40ad946f300a3be2dfdf922b

**Comment by noahfraiture** [comment]
Wow, that's great, I guess we simply need to wait for the release in package manager. Thank you ! 
I'm going to close now and open it again if there's a problem later with it
