### ISSUE TITLE
[Bug]: Dolphin ricing is unavailable after update

### ISSUE THREAD

**Issue by YourManz** [prasanthrangan/hyprdots#1268]
### Description
Dolphin file manager reverts back to default styling after `sudo pacman -Syu`

### Steps to Reproduce

No sure what causes this bug, I updated using the above command on 2024-03-08. While I am not sure that is the cause of the issue, that is the first thing that comes to mind.  

### Expected Behavior
Dolphin file editor should look riced and switch looks depending on the theme.

### Actual Behavior
Dolphin has a default look with no icons or styling beyond the hyprland window styling.
### Screenshots
![240408_17h53m36s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/49378706/d311cc9e-36c7-4657-b70b-3db001e01d7f)

### Environment

e.g.,

- Linux Distro: ArchLinux
- Linux Version: Linux archlinux 6.8.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 00:14:23 +0000 x86_64 GNU/Linux
- 
- Hyprland Version:Hyprland, built from branch main at commit 289d4241bea72ebd891e037996ec4ffd356aadc8 dirty (groupbar: scale groupbar text according to monitor scale (4640)).
Date: Thu Feb 8 14:29:10 2024
Tag: v0.35.0-9-g289d4241

- Installation Environment: Hardware

### Additional Information
Honestly not sure if this is just me or my machine, will probably just cp the .config/dolphin file and overwrite the existing one.

**Comment by Bryan-Campuzano** [comment]
try to see the #1030 issue and follow the instructions there, i've the same problem a month ago so look it up.

**Comment by zenghost1** [comment]
Is it fixed yet? I have tried some solutions from the mentioned thread. But had no luck so far.

**Comment by itsmenewbie03** [comment]
> > SO what fix works?Tried all these and it seems i broke my polkit and now i need a fix for that too
> 
> I just pulled the latest version of hyprdots and reran the install script.



> Is it fixed yet? I have tried some solutions from the mentioned thread. But had no luck so far.
> 
> Edit: After spending "more than I should have" hours, I took the easy way out and did a fresh install. It is fixed for me now

how did you do the fresh install? tried it but dolphin is still not fixed
