### ISSUE TITLE
is there any waybar user custom config?

### ISSUE THREAD

**Issue by MadSkillZzZz** [prasanthrangan/hyprdots#1269]
how can i change waybar config? It looks like it changes every time i update it's state/reboot. I wanna make changes persist

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/e3de49b9-2d44-4b99-8ff1-b5b9fbceeb88)

1. Active waybar if it's 1 rest should be 0
2. waybar scaling
3. position
4. left hand side modules
5. center modules
6. right hand side module


Toggle waybar layout using keybind  to update the autogenerated config

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/671b3b14-6cb2-4442-96a4-49c2fd3464f1)
