### ISSUE TITLE
Pixelated applications

### ISSUE THREAD

**Issue by JafetGA** [prasanthrangan/hyprdots#1273]
## Bug Report

Some programs are not at the resolution of my screen and look pixelated.
![240409_13h52m00s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/124212097/143dd55c-5ef6-498e-aa10-72d57a18e189)

**Comment by kRHYME7** [comment]
add Wayland flag?

**Comment by Itz-Abhishek-Tiwari** [comment]
> ## Bug Report
> Some programs are not at the resolution of my screen and look pixelated. ![240409_13h52m00s_screenshot](https://private-user-images.githubusercontent.com/124212097/320984214-143dd55c-5ef6-498e-aa10-72d57a18e189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzI5OTAsIm5iZiI6MTcxMjgzMjY5MCwicGF0aCI6Ii8xMjQyMTIwOTcvMzIwOTg0MjE0LTE0M2RkNTVjLTVlZjYtNDk4ZS1hYTEwLTcyZDU3YTE4ZTE4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxMDUxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODE2ZDkzOGU5MmQ2YzI2MTc2ZDcyY2E0NmQ4ODhiMjRjYzZlYzRlZThjNzlhNjcyNjE2MDEyNmZkZTIzOWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jbFYNx9eOBE7h7_iwfpZOea_ij0-EEmwp9hC5Tli_fY)

Add this in 
```

xwayland {
  force_zero_scaling = true
}


``` 

in the ` ~/.config/hypr/userprefs.config `  i will fixed .
