### ISSUE TITLE
[Bug]: Unable to take screenshot with keybind

### ISSUE THREAD

**Issue by Chasewhip8** [prasanthrangan/hyprdots#1281]
### Description

The screenshot script works fine when executed directly but when bound to the default bind it randomly stopped working. Pointing the output to a file results in nothing so it fails silently. 

### Steps to Reproduce

1. Bind key with
bind = $mainMod, P, exec, $scrPath/screenshot.sh s
2. Try it.

### Expected Behavior

The script executes.

### Actual Behavior

Nothing.

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux 6.8.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 00:14:23 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).

### Additional Information

The other bind
bind = ,print, exec, $scrPath/screenshot.sh p

seems to work, changing the p to an s makes it fail.

**Comment by Skerse** [comment]
> The screenshot script works fine when executed directly

Just to be clear, it works when you run `./screenshot.sh s` in the terminal but not with the keybind? If you didn't add the letter at the end when running it directly, please do and then provide terminal logs. It works completely fine for me, so i don't know what's happening for you..

Also, just so i know, are you running Hyprdots or HyDE?

**Comment by Chasewhip8** [comment]
It just started working again out of nowhere. Running Hyprdots.
