### ISSUE TITLE
[Bug]: Can't able to build cache 

### ISSUE THREAD

**Issue by Itz-Abhishek-Tiwari** [prasanthrangan/hyprdots#1284]
### Description

I am trying to build cache but getting errors

### Steps to Reproduce

1. update hyprdots
2. reboot system
3. exectue ` Hyprdots cache rebuild `

### Expected Behavior

build cache automatically 

### Actual Behavior

get error ` /usr/bin/Hyprdots: line 193: ./create_cache.sh: No such file or directory `

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/69257109/90e6be50-6709-4b95-a84f-6d6f687dde11)

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: ` Linux archlinux 6.8.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 00:14:23 +0000 x86_64 GNU/Linux `
- Hyprland Version, output of `hyprctl version`:``` Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
Date: Sat Apr 6 14:24:13 2024
Tag: v0.38.1  ```
- Installation Environment: On The Main Hardware

### Additional Information
This update is one of the smoothest update thanks

**Comment by kRHYME7** [comment]
This is deprecated   please install ``` yay -Sy hyde-cli-git ``` 

then follow the instructions. I suggest a fresh install of the Hyde repo. As Hyprdots will be deprected  

https://github.com/kRHYME7/Hyde-cli
