### ISSUE TITLE
[Breaking Changes!]: Read Me before posting an issue!

### ISSUE THREAD

**Issue by kRHYME7** [prasanthrangan/hyprdots#1285]
So we got a rough transition now. Hyprdots is deprecated, and we are doing a transition to 'hyde' 

So what change? Everything! Therefore, we encourage you to do a fresh install of this repo.

If you are planning to use the CLI in the future,  Please follow instructions here at the repo https://github.com/kRHYME7/Hyde-cli

or follow this repos README.  
```
cd ~/Hyprdots/Scripts
git pull
./install.sh
```

**Changes are discussed in this Merge request.**
https://github.com/prasanthrangan/hyprdots/pull/1282

_* this will be a developing post, depending on anything you would want to know._

Our brand new **discord** 💬
https://github.com/prasanthrangan/hyprdots/discussions/1235

**Comment by shripadk** [comment]
Want to start off by saying that I love Hyprdots. Most pleasant experience I have had on any Linux system till date. Thank you for making this!

My issue really boils down to there being no "stable releases" of Hyprdots (and whatever incarnation it might take in the future). Is there any way to version and mark these changes as stable/unstable? Reason being that I got Hyprdots installed on my girl's machine and she ended up with no wallpaper. Themes are broken too. Can't switch to any theme (Theme selection shows no theme at all). Checking Hyde output I get:

```bash
~> Hyde                                                                                     1 04/13/2024 09:40:45 AM
fixig link :: /mnt/work/.config/hyde/themes/Nordic Blue/wall.set
ERROR: No image found in /mnt/work/.config/hyde/themes/Nordic Blue
ERROR: No image found in any source
```

I initially thought it might be an issue with her system. Then I checked Hyprdots repo and saw that there was an issue related to wallpapers not loading. So decided to upgrade my Hyprdots (through `Hyprdots-Install`) on my working system and sure enough the entire setup is broken at this point. I am guessing reverting to my previous state would be to just checkout the latest stable commit that was working for me and `install.sh` from there?

It would be great if you could pin stable versions so we don't end up inadvertently installing WIP master branch code.

**Comment by kRHYME7** [comment]
Yes, this transition will cater those issues. https://github.com/prasanthrangan/hyprdots/releases/tag/v0.1.0

On the CLI side it is useless in the past to have releases if the hyprdots repo don't have any release cycles. Will definitely pushed a stable Hyde-cli in the future if this Hyde repository got it's first version.

**Comment by prasanthrangan** [comment]
Hey, thanks for the support!

There has been a significant change in almost everything, please refer [1282](https://github.com/prasanthrangan/hyprdots/pull/1282) for details.

So please clear these dirs from your `$HOME`  -
```
$HOME/.config/hyprdots
$HOME/.config/swww
$HOME/.cache/hyprdots
```

And clone or pull in the latest commit and rerun the install -
```
git clone --depth 1 https://github.com/prasanthrangan/hyprdots ~/Hyprdots
cd ~/Hyprdots/Scripts
./install.sh
```

Then reboot your system...

**Comment by shripadk** [comment]
@kRHYME7 Gotcha! Thanks for the clarification on this!

@prasanthrangan Thanks for the steps. I did try this. It seems like the themes are not being copied to `~/.config/hyde`. The install logs end with:

```nushell

[themepatcher] Patching themes...
100% 12:0=0s Nordic Blue https://github.com/prasanthrangan/hyde-themes/tree/Nordic-Blue --skipcaching false
```

Checking `~/.config/hyde`:

```nushell
~/Hyprdots/Scripts> ls ~/.config/hyde/                                                     12 04/13/2024 10:59:26 AM
╭───┬────────────────────────────────────────────┬──────┬─────────┬──────────────╮
│ # │                    name                    │ type │  size   │   modified   │
├───┼────────────────────────────────────────────┼──────┼─────────┼──────────────┤
│ 0 │ /home/shripadkrishna/.config/hyde/wallbash │ dir  │ 4.0 KiB │ a minute ago │
╰───┴────────────────────────────────────────────┴──────┴─────────┴──────────────╯
```

As you can see above, the themes are not being copied over to `~/.config/hyde`. Seems to be an issue with `themepatcher.sh`. I'll investigate further and get back to you on this.

**Comment by prasanthrangan** [comment]
the output for themepatcher will be suppressed by the main install.

So try running this, and check for errors -
```
./themepatcher.sh "Catppuccin Mocha" "https://github.com/prasanthrangan/hyde-themes/tree/Catppuccin-Mocha"
```

Its most likely failing due to git clone...
So checking in `$HOME/.cache/hyde/themepatcher` directory if it has cloned any themes.

**Comment by shripadk** [comment]
I get the following error:

```nushell
~/Hyprdots/Scripts> ./themepatcher.sh "Catppuccin Mocha" "https://github.com/prasanthrangan/hyde-themes/tree/Catppuccin-Mocha"
[ERROR]/mnt/work/.config/hyde/wallbash/Wall-Dcol do not exist!
```

**Comment by dieBakterie** [comment]
Yeah /Home/.. exists but not /mnt/.../.config/...

**Comment by shripadk** [comment]
Okay it seems to be an issue with it detecting `$HOME` as my mounted work related partition `/mnt/work` which also has a `.config` folder. I have no idea why it is picking that folder.

```nushell
~/Hyprdots/Scripts> ./themepatcher.sh "Catppuccin Mocha" "https://github.com/prasanthrangan/hyde-themes/tree/Catppuccin-Mocha"
[ERROR]/mnt/work/.config/hyde/wallbash/Wall-Dcol do not exist!

~/Hyprdots/Scripts> ls ~/.config/hyde/wallbash/                                             1 04/13/2024 11:45:32 AM
╭───┬──────────────────────────────────────────────────────┬──────┬─────────┬─────────────╮
│ # │                         name                         │ type │  size   │  modified   │
├───┼──────────────────────────────────────────────────────┼──────┼─────────┼─────────────┤
│ 0 │ /home/shripadkrishna/.config/hyde/wallbash/Wall-Dcol │ dir  │ 4.0 KiB │ an hour ago │
│ 1 │ /home/shripadkrishna/.config/hyde/wallbash/Wall-Ways │ dir  │ 4.0 KiB │ an hour ago │
╰───┴──────────────────────────────────────────────────────┴──────┴─────────┴─────────────╯

~/Hyprdots/Scripts> ls ~/.config/hyde/wallbash/Wall-Dcol/                                     04/13/2024 11:46:17 AM
╭──────┬─────────────────────────────────────────────────────────────────────┬─────────┬───────────┬───────────────╮
│    # │                                name                                 │  type   │   size    │   modified    │
├──────┼─────────────────────────────────────────────────────────────────────┼─────────┼───────────┼───────────────┤
│    0 │ /home/shripadkrishna/.config/hyde/wallbash/Wall-Dcol/hypr.dcol      │ file    │     549 B │ an hour ago   │
│    1 │ /home/shripadkrishna/.config/hyde/wallbash/Wall-Dcol/kitty.dcol     │ file    │   1,009 B │ an hour ago   │
│    2 │ /home/shripadkrishna/.config/hyde/wallbash/Wall-Dcol/kvantum        │ dir     │   4.0 KiB │ an hour ago   │
│    3 │ /home/shripadkrishna/.config/hyde/wallbash/Wall-Dcol/rofi.dcol      │ file    │     300 B │ an hour ago   │
│    4 │ /home/shripadkrishna/.config/hyde/wallbash/Wall-Dcol/waybar.dcol    │ file    │     402 B │ an hour ago   │
╰──────┴─────────────────────────────────────────────────────────────────────┴─────────┴───────────┴───────────────╯
```

**Comment by prasanthrangan** [comment]
> Okay it seems to be an issue with it detecting `$HOME` as my mounted work related partition `/mnt/work` which also has a `.config` folder. I have no idea why it is picking that folder.

it follows the XDG specs for configs, so please check if `XDG_CONFIG_HOME` is messed up

**Comment by Evre-nos** [comment]
> > Okay it seems to be an issue with it detecting `$HOME` as my mounted work related partition `/mnt/work` which also has a `.config` folder. I have no idea why it is picking that folder.
> 
> it follows the XDG specs for configs, so please check if `XDG_CONFIG_HOME` is messed up
I saw an update in this repo yesterday, so I updated it with the provided commands in the readme. After that, my Hyprland was broken. Rofi is not launching, wallpaper is not showing, Wayber not responding. It's like it is hanged.

So, I again installed Arch without any desktop environment. And then cloned this repo, but nothing happened, still the issue persisted. Then, I installed Arch again with KDE, but it did not solve the problem. I installed Arch with Hyprland several times, but nothing changed.

**Comment by shripadk** [comment]
@prasanthrangan Yes `XDG_CONFIG_HOME` points to:

```nushell
~/Hyprdots/Scripts> echo $env.XDG_CONFIG_HOME                                                 04/13/2024 11:56:45 AM
/mnt/work/.config
```

So it is giving preference to `XDG_CONFIG_HOME` over `HOME`.

**Comment by prasanthrangan** [comment]
> So, I again installed Arch without any desktop environment. And then cloned this repo, but nothing happened, still the issue persisted. Then, I installed Arch again with KDE, but it did not solve the problem. I installed Arch with Hyprland several times, but nothing changed.

Hey @Evre-nos , did the install script complete without errors?
if it did, please check these dirs and confirm if they are in place -

```
$HOME/.config/hyde
$HOME/.cache/hyde
$HOME/.local/share/bin
```

**Comment by rubiin** [comment]
By fresh install do you mean system install or just running the install.sh . I did run install.sh and seems to be working

**Comment by prasanthrangan** [comment]
> @prasanthrangan Yes `XDG_CONFIG_HOME` points to:
> 
> ```nushell
> ~/Hyprdots/Scripts> echo $env.XDG_CONFIG_HOME                                                 04/13/2024 11:56:45 AM
> /mnt/work/.config
> ```
> 
> So it is giving preference to `XDG_CONFIG_HOME` over `HOME`.

thats strange..... anyways just update the `global_fn.sh` in Scripts directory and set `confDir` as below -
```
confDir="$HOME/.config"
```
then rerun `install.sh`

**Comment by Evre-nos** [comment]
> By fresh install do you mean system install or just running the install.sh . I did run install.sh and seems to be working


Completely fresh arch install

**Comment by Evre-nos** [comment]
> > So, I again installed Arch without any desktop environment. And then cloned this repo, but nothing happened, still the issue persisted. Then, I installed Arch again with KDE, but it did not solve the problem. I installed Arch with Hyprland several times, but nothing changed.
> 
> Hey @Evre-nos , did the install script complete without errors? if it did, please check these dirs and confirm if they are in place -
> 
> ```
> $HOME/.config/hyde
> $HOME/.cache/hyde
> $HOME/.local/share/bin
> ```



The ./install.sh script ended with : 


[themepatcher] Patching themes...
100% 12:0=0s Nordic Blue https://github.com/prasanthrangan/hyde-themes/tree/Nordic-Blue --skipcaching false

And, those directories exist.

**Comment by shripadk** [comment]
I set `XDG_CONFIG_HOME` in my nushell config file. The reason I do so is because I work primarily from `/mnt/work` and I want all my work related cache files to be stored in that partition (also need for Nix which I use as my package manager).

```nushell
~/Hyprdots/Scripts> rg "XDG_CONFIG_HOME" ~/.config/nushell/                                   04/13/2024 11:59:07 AM
/home/shripadkrishna/.config/nushell/config.nu
843:$env.XDG_CONFIG_HOME = "/mnt/work/.config"
```

Changed L10 in `global_fn.sh` file to:

```diff
confDir="$HOME/.config"
```

Then ran `themepatcher.sh` again and it worked!

But Hyde still complains about not finding the theme because it is searching for it in `XDG_CONFIG_HOME`.

```nushell
~/Hyprdots/Scripts> ./themepatcher.sh "Catppuccin Mocha" "https://github.com/prasanthrangan/hyde-themes/tree/Catppuccin-Mocha"
/home/shripadkrishna/Hyprdots/Scripts
/home/shripadkrishna/.config
Directory /home/shripadkrishna/.cache/hyde/themepatcher/Catppuccin-Mocha-prasanthrangan does not exist. Cloning repository into new directory.
Patching --// Catppuccin Mocha //-- from /home/shripadkrishna/.cache/hyde/themepatcher/Catppuccin-Mocha-prasanthrangan

[OK] .config/hyde/themes/Catppuccin Mocha/rofi.theme
[OK] .config/hyde/themes/Catppuccin Mocha/kvantum/kvconfig.theme
[OK] .config/hyde/themes/Catppuccin Mocha/kvantum/kvantum.theme
[OK] .config/hyde/themes/Catppuccin Mocha/waybar.theme
[OK] .config/hyde/themes/Catppuccin Mocha/hypr.theme
[OK] .config/hyde/themes/Catppuccin Mocha/kitty.theme

[OK] wallpapers :: [count] 15 (.gif+.jpg+.jpeg+.png)
[OK] hypr.theme :: [gtk] Catppuccin-Mocha
[OK] ../*.tar.* :: [gtk] Catppuccin-Mocha
[OK] hypr.theme :: [icon] Tela-circle-dracula
[OK] ../*.tar.* :: [icon] Tela-circle-dracula
[!!] hypr.theme :: [cursor] Not Found

[skip] "/home/shripadkrishna/.themes/Catppuccin-Mocha" already exists
[skip] "/home/shripadkrishna/.icons/Tela-circle-dracula" already exists

[exec] restore_cfg.sh "/home/shripadkrishna/.cache/hyde/themepatcher/Catppuccin-Mocha-prasanthrangan/restore_cfg.lst" "/home/shripadkrishna/.cache/hyde/themepatcher/Catppuccin-Mocha-prasanthrangan/Configs" "Catppuccin Mocha"

fixig link :: /mnt/work/.config/hyde/themes/Nordic Blue/wall.set
ERROR: No image found in /mnt/work/.config/hyde/themes/Nordic Blue
ERROR: No image found in any source
```

```nushell
~/Hyprdots/Scripts> ./themepatcher.sh "Nordic Blue" "https://github.com/prasanthrangan/hyde-themes/tree/Nordic-Blue"
/home/shripadkrishna/Hyprdots/Scripts
/home/shripadkrishna/.config
Directory /home/shripadkrishna/.cache/hyde/themepatcher/Nordic-Blue-prasanthrangan already exists. Using existing directory.
Patching --// Nordic Blue //-- from /home/shripadkrishna/.cache/hyde/themepatcher/Nordic-Blue-prasanthrangan

[OK] .config/hyde/themes/Nordic Blue/rofi.theme
[OK] .config/hyde/themes/Nordic Blue/kvantum/kvconfig.theme
[OK] .config/hyde/themes/Nordic Blue/kvantum/kvantum.theme
[OK] .config/hyde/themes/Nordic Blue/waybar.theme
[OK] .config/hyde/themes/Nordic Blue/hypr.theme
[OK] .config/hyde/themes/Nordic Blue/kitty.theme

[OK] wallpapers :: [count] 7 (.gif+.jpg+.jpeg+.png)
[OK] hypr.theme :: [gtk] Nordic-Blue
[OK] ../*.tar.* :: [gtk] Nordic-Blue
[OK] hypr.theme :: [icon] Nordzy
[OK] ../*.tar.* :: [icon] Nordzy
[!!] hypr.theme :: [cursor] Not Found

[extracting] /home/shripadkrishna/.cache/hyde/themepatcher/Nordic-Blue-prasanthrangan/Source/Gtk_NordicBlue.tar.gz --> /home/shripadkrishna/.themes
[extracting] /home/shripadkrishna/.cache/hyde/themepatcher/Nordic-Blue-prasanthrangan/Source/Icon_NordicBlue.tar.gz --> /home/shripadkrishna/.icons

[exec] restore_cfg.sh "/home/shripadkrishna/.cache/hyde/themepatcher/Nordic-Blue-prasanthrangan/restore_cfg.lst" "/home/shripadkrishna/.cache/hyde/themepatcher/Nordic-Blue-prasanthrangan/Configs" "Nordic Blue"

fixig link :: /mnt/work/.config/hyde/themes/Nordic Blue/wall.set
ERROR: No image found in /mnt/work/.config/hyde/themes/Nordic Blue
ERROR: No image found in any source
```

**Comment by prasanthrangan** [comment]
> But Hyde still complains about not finding the theme because it is searching for it in `XDG_CONFIG_HOME`.

yup, that's for caching... please update `confDir` (line 6) in `~/.local/share/bin/globalcontrol.sh` as well to -
```
export confDir="$HOME/.config"
```

**Comment by shripadk** [comment]
@prasanthrangan Yep! You are right. It was cached in `~/.local/share/bin/globalcontrol.sh`. Made the necessary changes and it did not throw an error after that. However, I feel the installation is still not complete because it had failed silently on the `Patching themes...` step (not sure what steps come after that).

Can you tell me which file is being invoked that is writing to `~/.local/share/bin/globalcontrol.sh`?  The reason being that when I run `./install.sh` again, it overrides my changes to `~/.local/share/bin/globalcontrol.sh`. The `./install.sh` ends with:

```nushell
100% 12:0=33s Nordic Blue https://github.com/prasanthrangan/hyde-themes/tree/Nordic-Blue --skipcaching false

[cache] generating cache files...
fixig link :: /mnt/work/.config/hyde/themes/Nordic Blue/wall.set
ERROR: No image found in /mnt/work/.config/hyde/themes/Nordic Blue
ERROR: No image found in any source
```

**Comment by shripadk** [comment]
I think the problem probably has to do with mixing `$HOME` and `$XDG_CONFIG_HOME` in various steps within various scripts. So it is creating few folders/files in `$HOME` and rest in `$XDG_CONFIG_HOME`. I feel if we could set everything to be stored in/executed from either `$XDG_CONFIG_HOME` or `$HOME` it would probably work without issues. I also feel most devs will probably have `$XDG_CONFIG_HOME` pointing to `$HOME` so wouldn't experience this issue. My case is pretty specific (since I am using Nix <sup>[1]</sup>) and probably why its breaking down. Though if the intent is to move everything to `$XDG_CONFIG_HOME` it would be great too.

1: https://github.com/NixOS/nixpkgs/issues/224525

**Comment by prasanthrangan** [comment]
For now, in your clone directory `~/Hyprdots`, replace the `confDir` in these 2 scripts as below -

1. `~/Hyprdots/Configs/.local/share/bin/globalcontrol.sh`
```
export confDir="$HOME/.config"
export XDG_CONFIG_HOME="$HOME/.config"
```

2. `~/Hyprdots/Scripts/global_fn.sh`
```
confDir="$HOME/.config"
```

then rerun ./install.sh.

**Comment by shripadk** [comment]
@prasanthrangan Yep! That worked! Thank you so much!

**Comment by prasanthrangan** [comment]
> [themepatcher] Patching themes... 100% 12:0=0s Nordic Blue https://github.com/prasanthrangan/hyde-themes/tree/Nordic-Blue --skipcaching false
> 
> And, those directories exist.

Hey @Evre-nos ,  try running themepatcher as below, and check for errors -
```
./themepatcher.sh "Catppuccin Mocha" "https://github.com/prasanthrangan/hyde-themes/tree/Catppuccin-Mocha"
```

Please share its output.

**Comment by Evre-nos** [comment]
![IMG_20240413_202420](https://github.com/prasanthrangan/hyprdots/assets/138004078/0a48d491-984e-4ef1-befd-bd099ff10bf4)
@prasanthrangan after running your command, this shows up.

**Comment by prasanthrangan** [comment]
>  @prasanthrangan after running your command, this shows up.

Hey @Evre-nos , its trying to scan your `~/.config/hyde/themes` directory to generate cache...
and it seems like the `Edge Runner` theme installation did not complete from its previous run.
can you list the themes from `~/.config/hyde/themes` ? if they exist, please clear them and rerun the themepatcher.

**Comment by its-19818942118** [comment]
@kRHYME7 just a suggestion but break down all the hypr.confs cuz it's too cluttered. Or I can implement it but my laptop screen is dead so I can't unfortunately do it. But breaking it down is really use full as it won't override any existing configs and user configs can be made more easier:)

**Comment by its-19818942118** [comment]
> Hey, thanks for the support!
> 
> There has been a significant change in almost everything, please refer [1282](https://github.com/prasanthrangan/hyprdots/pull/1282) for details.
> 
> So please clear these dirs from your `$HOME` as these are deprecated -
> ```
> $HOME/.config/hyprdots
> $HOME/.config/swww
> $HOME/.cache/hyprdots
> ```
> 
> And clone or pull in the latest commit and rerun the install -
> ```
> git clone --depth 1 https://github.com/prasanthrangan/hyprdots ~/Hyprdots
> cd ~/Hyprdots/Scripts
> ./install.sh
> ```
> 
> Then reboot your system...

Hey just a suggestion um when using fresh Linux install it keeps asking for ssh via GitHub. Is there no other options other than got clone cuz setting up ssh on fresh Linux with only tty is hard. I am a noob but whatever I tried none of them worked on git clone

**Comment by Evre-nos** [comment]
> > @prasanthrangan after running your command, this shows up.
> 
> Hey @Evre-nos , its trying to scan your `~/.config/hyde/themes` directory to generate cache... and it seems like the `Edge Runner` theme installation did not complete from its previous run. can you list the themes from `~/.config/hyde/themes` ? if they exist, please clear them and rerun the themepatcher.



Found a fix! First time running ./install.sh got stuck at the Nordic Blue theme part. So, I cleared out the themes folder with "rm -rf ~/.config/hyde/themes/*". Tried again, no luck. But after a PC reboot, gave it one more shot and voila! Full installation worked. Big thanks to @prasanthrangan for the assist!

**Comment by tryprncp** [comment]
> > Hey, thanks for the support!
> > There has been a significant change in almost everything, please refer [1282](https://github.com/prasanthrangan/hyprdots/pull/1282) for details.
> > So please clear these dirs from your `$HOME` as these are deprecated -
> > ```
> > $HOME/.config/hyprdots
> > $HOME/.config/swww
> > $HOME/.cache/hyprdots
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And clone or pull in the latest commit and rerun the install -
> > ```
> > git clone --depth 1 https://github.com/prasanthrangan/hyprdots ~/Hyprdots
> > cd ~/Hyprdots/Scripts
> > ./install.sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then reboot your system...
> 
> Hey just a suggestion um when using fresh Linux install it keeps asking for ssh via GitHub. Is there no other options other than got clone cuz setting up ssh on fresh Linux with only tty is hard. I am a noob but whatever I tried none of them worked on git clone

maybe this command will help.
curl -L -o hyprdots.zip https://github.com/prasanthrangan/hyprdots/archive/main.zip
