### ISSUE TITLE
[Help]: Error with theme switching after updating dotfiles

### ISSUE THREAD

**Issue by vox625** [prasanthrangan/hyprdots#1288]
![240412_19h43m02s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/112044661/620cab96-2acb-4892-8c26-0a03b2e32da4)

**Comment by kRHYME7** [comment]
output for this ```  ls ~/.config/hyde/themes ``` ?

**Comment by vox625** [comment]
> output for this ` ls ~/.config/hyde/themes` ?

![Uploading 240412_21h21m56s_screenshot.png…]()

**Comment by vox625** [comment]
> output for this ` ls ~/.config/hyde/themes` ?

![240412_21h21m56s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/112044661/7b57db0e-0812-468a-92a4-f5624a1322fa)

**Comment by kRHYME7** [comment]
Try this command

``` themeswitch.sh -s "" ``` 

or ```   themeswitch.sh -n ```


How did you update  Hyde ?

**Comment by vox625** [comment]
> Try this command
> 
> `themeswitch.sh -s ""`
> 
> or ` themeswitch.sh -n`
> 
> How did you update Hyde ?

I can do it with this commands, but can't do it whit shortcuts, and if I switch wallpapers, not from the current theme, but from the previous.
I just ran the commands:
cd ~/Hyprdots/Scripts
git pull
./install.sh -r
to update my config.

**Comment by vox625** [comment]
The Kvantum window pops up evert time I switch between theme and wallpaper.
![240412_22h20m37s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/112044661/b74f7e50-c8d7-421c-90cd-36cbd9a79818)

**Comment by kRHYME7** [comment]
> I can do it with this commands, but can't do it whit shortcuts, and if I switch wallpapers, not from the current theme, but from the previous.

Please remove first the old script directories ``` ~/.config/hyprdots/scripts ``` should not exist. 


 scripts are now inside ``` ~/.local/share/bin/ ```  check where your keybinds are pointing to

**Comment by vox625** [comment]
> > I can do it with this commands, but can't do it whit shortcuts, and if I switch wallpapers, not from the current theme, but from the previous.
> 
> Please remove first the old script directories `~/.config/hyprdots/scripts` should not exist.
> 
> scripts are now inside `~/.local/share/bin/` check where your keybinds are pointing to

OK.
Problem solved.
Thank you.
