### ISSUE TITLE
[Bug]: Light theme in gamelauncher.sh after hyde-update

### ISSUE THREAD

**Issue by Enigma1309** [prasanthrangan/hyprdots#1291]
### Description
Game launcher don't respects the user defined color-scheme after the update
### Steps to Reproduce

1. Launch the gamelauncher.sh

### Expected Behavior

It should respect the user theme 

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/e81377eb-af2b-4d7e-aaa9-1096e1b767d2)

**Comment by prasanthrangan** [comment]
Hey, my bad... should be fixed in 317d2aa.
Please try with latest configs

**Comment by Enigma1309** [comment]
Thanks it's fixed now
