### ISSUE TITLE
[Bug]: Semi working

### ISSUE THREAD

**Issue by dieBakterie** [prasanthrangan/hyprdots#1292]
### Description

[Provide a clear and concise description of the bug.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots

![240412_21h19m28s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/50206827/c4bfed82-efcb-483c-9b00-83504a801365)

### Environment

**Hyde-cli Version:**
Version: v0.5.0-118-gf88030c
Last commit: f88030c Fri Apr 12 22:41:35 2024 +0800
Commit message: 'Maybe it fixes the no meta dat err'

**Hyde Repository:**
CloneDirectory: /home/bakterie/.cache/hyde/Hyde-Clone
Git URL: https://github.com/prasanthrangan/hyprdots
Git Branch: main
Hyde version: 317d2aa
Modified:  Sat Apr 13 00:07:26 2024 +0530
Commit message: fix rofi gamelauncher theme #1291

**GPU:** 
2b:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2070 Rev. A] [10de:1f07] (rev a1)

**CPU:** 

**OS:** 
- NAME="Arch Linux"
- PRETTY_NAME="Arch Linux"
- ID=arch
- BUILD_ID=rolling
- ANSI_COLOR="38;2;23;147;209"
- HOME_URL="https://archlinux.org/"
- DOCUMENTATION_URL="https://wiki.archlinux.org/"
- SUPPORT_URL="https://bbs.archlinux.org/"
- BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
- PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
- LOGO=archlinux-logo

**Hyprland System Information:** (Not always available)
- Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
- Date: Sat Apr 6 14:24:13 2024
- Tag: v0.38.1

flags: (if any)

System Information:
- System name: Linux
- Node name: archlinux
- Release: 6.8.5-zen1-1-zen
- Version: #1 ZEN SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 01:47:18 +0000
- Installation Environment: [On The Main Hardware]
- Other info: [1920x1080@60,1920x1080@144]

GPU information: 
- 2b:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2070 Rev. A] [10de:1f07] (rev a1) (prog-if 00 [VGA controller])

- os-release: NAME="Arch Linux"
- PRETTY_NAME="Arch Linux"
- ID=arch
- BUILD_ID=rolling
- ANSI_COLOR="38;2;23;147;209"
- HOME_URL="https://archlinux.org/"
- DOCUMENTATION_URL="https://wiki.archlinux.org/"
- SUPPORT_URL="https://bbs.archlinux.org/"
- BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
- PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
- LOGO=archlinux-logo

### Additional Information

Already had issues through installation with Hyde-install

**Comment by dieBakterie** [comment]
![grafik](https://github.com/prasanthrangan/hyprdots/assets/50206827/0608f50f-8e42-4fd8-b6f1-43a873dedeaa)
That's not intended like this.

**Comment by dieBakterie** [comment]
![grafik](https://github.com/prasanthrangan/hyprdots/assets/50206827/ddd11800-b00d-422c-a43f-a0ef7af35f28)
So is this intended i need to trigger wallbash 2 times fast in a row to get it like this

**Comment by kRHYME7** [comment]
> So is this intended i need to trigger wallbash 2 times fast in a row to get it like this 

yes? 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/44fa09f3-659f-46d0-ba5f-f721df1277e7)

**Comment by dieBakterie** [comment]
So that code-oas opens with the Flags as Files is intended too?

**Comment by kRHYME7** [comment]
> So that code-oss opens with the Flags as Files is intended too?

dunno about this though let me check first

**Comment by dieBakterie** [comment]
![grafik](https://github.com/prasanthrangan/hyprdots/assets/50206827/4057c410-ea68-4484-befc-305e0a099fd2)

I've sometimes no icons but don't know why/how to reproduce. And is there a reason for the bluetooth/network icon not following wallbash?

**Comment by dieBakterie** [comment]
Are there any plans to make the waybar safe it's state?

**Comment by kRHYME7** [comment]
> I've sometimes no icons but don't know why/how to reproduce. And is there a reason for the bluetooth/network icon not following wallbash?

waybar icons are tray icons from their respective packages. Unless we can generate a wallbash gtk then it is posible. 

some gtk themes seemed to have not icon in the specific icon pack

**Comment by dieBakterie** [comment]
![grafik](https://github.com/prasanthrangan/hyprdots/assets/50206827/7dc64e47-c803-420f-90cf-5d75bc01c239)
Appears when trying to open downloaded file in folder

**Comment by dieBakterie** [comment]
i've ```env = XDG_PICTURES_DIR,$HOME/Bilder/``` in _userprefs.conf_

**Comment by dieBakterie** [comment]
> > I've sometimes no icons but don't know why/how to reproduce. And is there a reason for the bluetooth/network icon not following wallbash?
> 
> waybar icons are tray icons from their respective packages. Unless we can generate a wallbash gtk then it is posible.
> 
> some gtk themes seemed to have not icon in the specific icon pack
> 
> And sometime it's just waybar being waybar(ops buggy)
> 
> happens when disabling and enabling waybar

**Comment by kRHYME7** [comment]
Better to do a separated post for this, please the Original Post will be address soon

**Comment by prasanthrangan** [comment]
> o that code-oss opens with the Flags as Files is intended too?

no it is not intended... please modify `/usr/bin/code-oss` by removing the quotes from ${codeflags[@]} like this -
```
ELECTRON_RUN_AS_NODE=1 exec /usr/lib/${name}/electron /usr/lib/code/out/cli.js "${electronflags[@]}" /usr/lib/code/code.js ${codeflags[@]} "$@"
```

**Comment by dieBakterie** [comment]
![grafik](https://github.com/prasanthrangan/hyprdots/assets/50206827/166a8e4e-714a-4b51-8c60-b9890337b11b)
Why isn't the screenshot.sh respecting my XDG_PICTURES_DIR?

**Comment by dieBakterie** [comment]
> > o that code-oss opens with the Flags as Files is intended too?
> 
> no it is not intended... please modify `/usr/bin/code-oss` by removing the quotes from `${codeflags[@]}` in the last line like this -
> 
> ```
> ELECTRON_RUN_AS_NODE=1 exec /usr/lib/${name}/electron /usr/lib/code/out/cli.js "${electronflags[@]}" /usr/lib/code/code.js ${codeflags[@]} "$@"
> ```

Fixed it thanks.
