### ISSUE TITLE
[Bug]: how to change sddm wallpaper to follow hyde themes, not hyprdots?

### ISSUE THREAD

**Issue by Ramy-Ashraf** [prasanthrangan/hyprdots#1297]
### Description

SDDM wallpaper is stuck on the wallpaper I used before updating.

### Steps to Reproduce

1. update form repo
2. then SDDM wallpaper doesn't change

### Expected Behavior

SDDM wallpaper change by changing the wallpaper

### Actual Behavior

Nothing change

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/85342902/0f871e51-beee-45f9-817a-b9329faf5179)

### Environment

- Linux Distro: ArchLinux
- Installation Environment: On The Main Hardware

**Comment by Itz-Abhishek-Tiwari** [comment]
> ## Bug Report
> ### Description
> SDDM wallpaper is stuck on the wallpaper I used before updating.
> 
> ### Steps to Reproduce
> 1. update form repo
> 2. then SDDM wallpaper doesn't change
> 
> ### Expected Behavior
> SDDM wallpaper change by changing the wallpaper
> 
> ### Actual Behavior
> Nothing change
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/85342902/322190179-0f871e51-beee-45f9-817a-b9329faf5179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTk1NzEsIm5iZiI6MTcxMzQxOTI3MSwicGF0aCI6Ii84NTM0MjkwMi8zMjIxOTAxNzktMGY4NzFlNTEtYmVlZS00NWY5LTgxN2EtYjkzMjlmYWY1MTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA1NDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMmRiMGUxYmIzZWE5NjU1NGMxYzNjMWY3NWIxZjEyMWU2ZThlNGUyM2Q4ZTQzOWQzMmEyZDNlODdmNmEyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l3Ba7bVP3cdIz7b1Agy-_1eqAmcgiDSHHuEGsRJk02w)
> 
> ### Environment
> * Linux Distro: ArchLinux
> * Installation Environment: On The Main Hardware

I think there is not such feature right now
