### ISSUE TITLE
[Feat Req ] rofi layout to show dunst actions  ~[Bug]: dunst window doesn't follow the theme~

### ISSUE THREAD

**Issue by Ramy-Ashraf** [prasanthrangan/hyprdots#1298]
### Description

dunst window doesn't follow the theme, but the notification itself does.

### Steps to Reproduce

1. Click on notification to open the window

### Expected Behavior

expected dunst window to follow the theme

### Actual Behavior

dunst window doesn't follow the theme

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/85342902/6c73c9a7-8f06-42df-af80-a9bf2abdeb89)

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`:  Linux archlinux 6.8.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 01:47:33 +0000 x86_64 GNU/Linux
- Installation Environment: On The Main Hardware

**Comment by dieBakterie** [comment]
I wish i had notifications man

**Comment by simplemachine-zz** [comment]
> I wish i had notifications man

Install libnotify

**Comment by dieBakterie** [comment]
> > I wish i had notifications man
> 
> Install libnotify

The dunst notifications doesn't Work for me

**Comment by simplemachine-zz** [comment]
> > > I wish i had notifications man
> > 
> > 
> > Install libnotify
> 
> The dunst notifications doesn't Work for me

Mine didn't work before either, but after using the **notify-send foo** command in terminal, it recommended me to install **libnotify** and it started working again. I'm on Fresh Arch Linux Install and installed that dots last night.

**Comment by dieBakterie** [comment]
Jeah Same

**Comment by prasanthrangan** [comment]
this is not a bug, currently there is no rofi layout to show dunst actions.

**Comment by Skerse** [comment]
This is now added/fixed! https://github.com/prasanthrangan/hyprdots/commit/843b7a37f1eab21df76ee9f91534567112c4f85b
