### ISSUE TITLE
[Feature Request]: Wallbash Select Menu similar to Rofi Style Select

### ISSUE THREAD

**Issue by saulback** [prasanthrangan/hyprdots#1301]
### Description

Change MOD + Shift + D to open a Rofi style menu to select between Disabled, Auto, Dark, Light.

### Use Case

Currently the MOD + Shift + D cycles between the 4 options. Each time, wallbash is reset and takes a few seconds and causes windows to move around until all settings are applied. Most of the time, the user knows which option they want. Making them cycle through all to get to the one they want is a bit annoying.

Having a rofi style select similar to wallpaper/theme/rofi style select menu would make changing wallbash settings simpler.

### Proposed Solution

Simple menu with the four possible options.

### Alternatives

Not considered

### Additional Information

See wallpaper/theme/rofi selector for examples.

**Comment by prasanthrangan** [comment]
I thought of this, but honestly didn't think the users will change modes frequently...
If you guys like a rofi menu for this, then I'll definitely implement it!

**Comment by saulback** [comment]
I don't see users changing it frequently either, but when you do want to change it, cycling through is kind of annoying. I do have something that I've been using. It is just missing icons/images. I was thinking light bulbs for icons, but I'm not really sure. If you want me to I can make a branch with these changes and go through the PR process myself. But I'm really not sure where to put icons, where to get the icons, which icons to  use, etc.

```
#!/usr/bin/env sh


#// set variables

scrDir="$(dirname "$(realpath "$0")")"
source "${scrDir}/globalcontrol.sh"
rofiConf="${confDir}/rofi/selector.rasi"
rofiStyleDir="${confDir}/rofi/styles"
rofiAssetDir="${confDir}/rofi/assets"


#// set rofi scaling

[[ "${rofiScale}" =~ ^[0-9]+$ ]] || rofiScale=10
r_scale="configuration {font: \"JetBrainsMono Nerd Font ${rofiScale}\";}"


#// scale for monitor

x_monres=$(hyprctl -j monitors | jq '.[] | select(.focused==true) | .width')
y_monres=$(hyprctl -j monitors | jq '.[] | select(.focused==true) | .height')
aspect_r=$((x_monres * 10 / y_monres ))


#// generate config

elem_border=$(( hypr_border * 5 ))
icon_border=$(( elem_border - 5 ))
i_size=$(( aspect_r - 4 ))
r_override="listview{columns:4;} element{orientation:vertical;border-radius:${elem_border}px;} element-icon{border-radius:${icon_border}px;size:${i_size}em;} element-text{padding:1em;}"

#// set currentSelection

case "${enableWallDcol}" in 
    0) currentSelection="disabled"
        ;;
    1) currentSelection="auto"
        ;;
    2) currentSelection="dark"
        ;;
    3) currentSelection="light"
        ;;
esac

#// launch rofi menu

newSelection=$(echo -en "auto\ndark\nlight\ndisabled\n" | while read styleNum
do
    # echo -en "${styleNum}\x00icon\x1f${rofiAssetDir}/style_${styleNum}.png\n"
    echo -en "${styleNum}\n"
done | rofi -dmenu -theme-str "${r_override}" -config "${rofiConf}" -select "${currentSelection}")

echo ${newSelection}

if [ -z "${newSelection}" ] ; then
    exit
fi
# if [ "$newSelection" = "$currentSelection" ]
# then 
#     echo 'no change, do nothing'
#     exit
# fi


#// switch WallDcol variable

case "${newSelection}" in
    "auto")  set_conf "enableWallDcol" "1"
        notif="wallbash auto"
        ;;
    "dark")  set_conf "enableWallDcol" "2"
        notif="wallbash dark mode"
        ;;
    "light")  set_conf "enableWallDcol" "3"
        notif="wallbash light mode"
        ;;
    "disabled")  set_conf "enableWallDcol" "0"
        notif="wallbash disabled"
        ;;
esac


#// reset the colors

export reload_flag=1
"${scrDir}/swwwallpaper.sh" -s "$(readlink "${hydeThemeDir}/wall.set")"
notify-send -a "t1" -i "~/.config/dunst/icons/hyprdots.png" "${notif}"


```

**Comment by prasanthrangan** [comment]
thanks this is done in b078123, I created a new rofi layout for this

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/3ba21eaf-d492-468f-9570-9d8cf416669b)

**Comment by dieBakterie** [comment]
For me it doesn't even Work. It's the Same behaviour as before

**Comment by prasanthrangan** [comment]
> If i = 0, then it would setMode = -1, which I don't think is a valid.

yup, `line 57` should adjust that...

**Comment by prasanthrangan** [comment]
> For me it doesn't even Work. It's the Same behaviour as before

to open menu.. use `wallbashtoggle.sh -m`

**Comment by dieBakterie** [comment]
Ok

**Comment by dieBakterie** [comment]
You are using hyprdots?!

**Comment by saulback** [comment]
ummm.. yes? This is the hyprdots github, right? I just followed the installation instructions on the readme.md. What did I do wrong?

**Comment by kRHYME7** [comment]
The new script directory

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c011437b-2c43-495b-99e8-ba09d44d644f)

**Comment by prasanthrangan** [comment]
> but when I do a `install.sh -r`, the new wallbashtoggle.sh (and probably other files) don't get copied to the ~.config/hyprdots/scripts directory. Is there a different way I should be updating? I'm ok overwriting any customization I've done. Is it safe to just do a `install.sh` to overwrite everything?

please clear your `~.config/hyprdots` as its deprecated... `install.sh -r` should now copy the scripts to `~/.local/share/bin`... also your existing `${HOME}/.config/hypr/keybindings.conf` will be always preserved, so it wont be overwritten.

**Comment by saulback** [comment]
Any reason you don't want to default the wallbashtoogle to go to the menu? Or at least change keybindings.conf to use the new -m option? It seems a shame that users aren't really going to be able to use the new menu unless they know to go to their keybindings and add the -m themselves. If you add it to the keybindings.sh, at least new users will get the new menu.

**Comment by prasanthrangan** [comment]
> Any reason you don't want to default the wallbashtoogle to go to the menu? Or at least change keybindings.conf to use the new -m option? It seems a shame that users aren't really going to be able to use the new menu unless they know to go to their keybindings and add the -m themselves. If you add it to the keybindings.sh, at least new users will get the new menu.

Yes, I've updated keybindings to open menu by default, but did not commit it yet.. I was just thinking about using a different key instead of `Super` + `D`.
So I'll push it soon.
