### ISSUE TITLE
[Feature Request]: MOD + ? Open keybinds_hint.sh?

### ISSUE THREAD

**Issue by saulback** [prasanthrangan/hyprdots#1302]
### Description

MOD + ? default binding to open the keybinding hint window.

### Use Case

As a brand new user of hyprdots, my gut instinct to understand options was to hit MOD + ? to hopefully see what keybindings are available. I'm not sure why I thought that keybinding would work. Maybe I've seen that specific keybinding done elsewhere. After looking around I did find the keyboard icon on the waybar. 

### Proposed Solution

[If you have a specific solution in mind, describe it here. If not, you can skip this section.]
MOD + ? runs the `keybinds_hint.sh`

### Alternatives

None considered

### Additional Information

I completely understand if you don't want to do this one. It is just something I thought of when I first started using hyprdots and thought that if I tried MOD + ?, others may have tried it as well.

**Comment by dieBakterie** [comment]
Yeah and Keybind for this would be nice

**Comment by kRHYME7** [comment]
have you tried it?

**Comment by dieBakterie** [comment]
not working on my end with german layout ```xkbcli interactive-wayland
seat0: keycode [ AE11 ] keysyms [ ssharp                      ] unicode [ ß ] layout [ German (0) ] level [ 0 ] mods [ ] leds [ ] ``` that's the key for my keyboard `bind = $mainMod, ß, exec, keybinds_hint.sh -h 80% -w 50%  -d  # Show keybind hints` doen't works too

**Comment by dieBakterie** [comment]
propably `bind = $mainMod, h, exec, keybinds_hint.sh -h 80% -w 50%  -d  # Show keybind hints` h for hint?

**Comment by saulback** [comment]
That one with the '?' doesn't work. I've been using this:

`bind = $mainMod SHIFT, code:61, exec, $scrPath/keybinds_hint.sh # Show keybind hints`

Unfortunately in the hint window, it doesn't recognize how to deal with the code:61. It shows this:
![image](https://github.com/prasanthrangan/hyprdots/assets/17965720/2b49585d-6d49-4b43-9ef8-eb2c57709303)

So maybe MOD + H might be better, but the whole idea for this was to make it more discoverable for new users. I'm not sure if MOD + H would be helpful for new users.

**Comment by kRHYME7** [comment]
Yeah should work with keycode number. 

Can you try ``` question ``` ?

**Comment by dieBakterie** [comment]
Just an Idea

**Comment by dieBakterie** [comment]
> Yeah should work with keycode number. 
> 
> Can you try ``` question ``` ?  
>  

Doesn't Work

**Comment by dieBakterie** [comment]
Oh and any Idea why https://github.com/prasanthrangan/hyprdots/issues/1186#issuecomment-2053693198  doesn't works anymore suddenly?

**Comment by Enigma1309** [comment]
i've been using `mod+alt+k` for keybinding hints

**Comment by kRHYME7** [comment]
I don't  actually care about what are the defaults. 

But yey we can convert keycodes now 

example: keycode:61 is ? 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/17ca8901-7dfb-4f65-9b65-4f67d910e4c4)

**Comment by saulback** [comment]
I think I've steered you guys wrong here.

After digging in a bit more on this, it turns out code:61 is for `/` not for `?`. / and ? are on the same key on my keyboard. I was thinking that in the keybinding the SHIFT would modify the next key. But it looks like hyprland swallows/ignores the SHIFT when used in a keybinding? So in reality I was doing a `MOD + SHIFT + /` instead of the `?`. 

I did try `bind = $mainMod SHIFT, /, exec, $scrPath/keybinds_hint.sh # Show keybind hints`, but that didn't work. So that would still need the ability to convert the keycode, but it would actually have to show the `/` instead of the `?`, mostly in case of keyboard layouts when they are not the same key.

I really thought this was a straightforward simple request. I didn't think it would get blown up into this mess. I'd be ok just closing this ticket, or maybe using MOD + h instead of `?`. I really like the idea of using the question mark, but this is ridiculous.

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/8b3f7ba0-e10d-4fc9-ac8c-68e69db4f48d)

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/df066038-b664-4831-bed9-79d897b8ec08)


No problem with that, you just made the script better after you raised this issue.

**Comment by kRHYME7** [comment]
Also added an option to map the keycode manually ( ke codes are actually tied to some keyboard layout so would be better to map it manually https://www.toptal.com/developers/keycode/table )

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/86b05c5f-be4f-4acc-a29e-48b99ffcc503)


#1303

**Comment by kRHYME7** [comment]
For now it is set to ` SUPER + slash `

**Comment by its-19818942118** [comment]
> For now it is set to `SUPER + slash`

@kRHYME7 set it to mod / yes also for upper level keys adding shift suffices. for misc keys like this.
