### ISSUE TITLE
[Bug]: error: failed to commit transaction (conflicting files) swww-git

### ISSUE THREAD

**Issue by Pranav-Saraswat** [prasanthrangan/hyprdots#1306]
### Description

While Updating the hyprdots script I'm facing this issue

error: failed to commit transaction (conflicting files)
swww-git-debug: /usr/lib/debug/usr/bin/swww-daemon.debug exists in filesystem (owned by swww-debug)
swww-git-debug: /usr/lib/debug/usr/bin/swww.debug exists in filesystem (owned by swww-debug)
Errors occurred, no packages were upgraded.
 -> error installing: [/home/pranav/.cache/yay/swww-git/swww-git-0.4.0.r366.ga27aeff-1-x86_64.pkg.tar.zst /home/pranav/.cache/yay/swww-git/swww-git-debug-0.4.0.r366.ga27aeff-1-x86_64.pkg.tar.zst] - exit status 1

**Comment by twist250** [comment]
I faced this issue, and  I deleted those files with `rm -rf`

**Comment by kRHYME7** [comment]
I think you need to to yay -R those -debug packages first.

**Comment by twist250** [comment]
using yay -R didn't help me, those files stayed, in the end I deleted them manually

**Comment by Pranav-Saraswat** [comment]
@twist250 hello can you write a full commands to fix this

**Comment by twist250** [comment]
@Pranav-Saraswat `rm -rf /usr/lib/debug/usr/bin/swww-daemon.debug /usr/lib/debug/usr/bin/swww.debug`

**Comment by Pranav-Saraswat** [comment]
@twist250 thanks it works now I'm closing this issue
