### ISSUE TITLE
[Custom]: Is it possible to add the ability to display the time on the right side?

### ISSUE THREAD

**Issue by Klee-Klee** [prasanthrangan/hyprdots#1308]
![240414_15h00m36s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/105958444/362e1f72-e899-4942-b0ec-eb1679e2c234)
![240414_15h28m48s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/105958444/28ead305-d3cd-4c5e-b300-10ddbf02b0c1)

Modified config.jsonc in .config/waybar to display the time on the right side.

But every time I switch themes or upgrade hyprdots the modified code gets reset, is there a better way?

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/bbafa06e-be66-4788-946c-3d6999aadd39)


see ``` ~/.config/waybar/config.ctl ``` file and modify the positions of the modules

**Comment by Klee-Klee** [comment]
> ![image](https://private-user-images.githubusercontent.com/53417443/322255605-bbafa06e-be66-4788-946c-3d6999aadd39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjgxMjMsIm5iZiI6MTcxMzE2NzgyMywicGF0aCI6Ii81MzQxNzQ0My8zMjIyNTU2MDUtYmJhZmEwNmUtYmU2Ni00Nzg4LTk0NmMtM2Q2OTk5YWFkZDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA3NTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMmE2ZjdkNmNkNTcyYzBkZGU1ZTI0MjUyZDU1NjQ4OTBlYjBjN2EzZjEyN2RhNGViZWU1ZGNhZjlmYTJhMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZKpbdEfH01Ytql_FIqXktwoO5CUeIEgZ1L1lu9fs0KY)
> 
> see `~/.config/waybar/config.ctl` file and modify the positions of the modules

 thanks
