### ISSUE TITLE
[Bug]: VSC Theme Not Syncing

### ISSUE THREAD

**Issue by MostlyKIGuess** [prasanthrangan/hyprdots#1310]
## Bug Report
- Some of the apps theme not syncing 
### Description

- So I had ML4W Dots on my newly installed arch and I ran their uninstall script, I had issues on installing hyprdots at first but then I just removed some apps and it worked , but the problem I face now is that the colors and theme are not synced on those apps, for example visual studio code.

### Steps to Reproduce

1. Install Ml4w and uninstall it.
2. Install hyprdots
3. Check your theme on apps

### Expected Behavior

It should sync on every app like before , I used to run this on my old arch installation.
### Actual Behavior

It didn't sync

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/135974627/d95fbd2d-fe07-4cfe-a151-dde7019e5662)

### Environment

- Linux Distro:ArchLinux
- Linux Version: Linux mostlyk 6.8.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 01:47:33 +0000 x86_64 GNU/Linux
- Hyprland Version: Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1).
Date: Sat Apr 6 14:24:13 2024
Tag: v0.38.1

flags: (if any)

- Installation Environment: Main Hardware

**Comment by kRHYME7** [comment]
> example visual studio code.

This feature is not supported anymore as the owner is planning to remove vscode and its extension dependencies. Would you still prefer to have that function? 

In the future releases/commits we will have dynamic colors for code with wallbash. 

BTW the HyDE repo is now using the code-oss, not the vsc version

**Comment by MostlyKIGuess** [comment]
Yeah it was a very good feature, I will try with HyDE repo, thanks for that :)

**Comment by prasanthrangan** [comment]
I've plan to integrate vscode theme/wallbash colors using our own extension. I'll get to this soon.

**Comment by MostlyKIGuess** [comment]
> I've plan to integrate vscode theme/wallbash colors using our own extension. I'll get to this soon.

I would love to help on this, I can work on adding more themes if you need off work , I can try to do it :)

**Comment by DiegoSof2** [comment]
> > example visual studio code.
> 
> This feature is not supported anymore as the owner is planning to remove vscode and its extension dependencies. Would you still prefer to have that function?
> 
> In the future releases/commits we will have dynamic colors for code with wallbash.
> 
> BTW the HyDE repo is now using the code-oss, not the vsc version

code-oss doesn't support syncing with github?

**Comment by kRHYME7** [comment]
` code-marketplace `

I installed this so I can get the vscode functionality and extensions.
