### ISSUE TITLE
[Bug Report]: Dunst notifications fix

### ISSUE THREAD

**Issue by dieBakterie** [prasanthrangan/hyprdots#1313]
### Description

Adding libnotify to dependencies as without it notifications doesn't work.

### Use Case

Working notifications Out of the Box.

### Proposed Solution

Installing libnotify through `install.sh`

### Alternatives

Add an Info that you propably need to install libnotify for dunst notifications to work properly.

### Additional Information

Arch Linux(minimal w/pipewire) , Zen Kernel-6.8

**Comment by prasanthrangan** [comment]
wait what...?!? I thought `libnotify` should be installed as a dependency for dunst.

**Comment by dieBakterie** [comment]
No it doesn't and it was a fresh Install through Hyde-install ig?
