### ISSUE TITLE
[Bug]: 2 files created whenever code oss is opened

### ISSUE THREAD

**Issue by NotAF0e** [prasanthrangan/hyprdots#1315]
These files are `--ozone-platform-hint=wayland` and `--disable-gpu`. I assume this is happening as these are 2 launch arguments but they do not do what is intended and instead create 2 files.

**Comment by prasanthrangan** [comment]
this is known issue, please refer https://github.com/prasanthrangan/hyprdots/issues/1292#issuecomment-2052979781

you'll need to fix `/usr/bin/code-oss` by removing the quotes from `${codeflags[@]}` in the last line.

**Comment by NotAF0e** [comment]
Thanks, that did the job!

**Comment by AtnProjects** [comment]
thank you so much

**Comment by Ramy-Ashraf** [comment]
> this is known issue, please refer [#1292 (comment)](https://github.com/prasanthrangan/hyprdots/issues/1292#issuecomment-2052979781)
> 
> you'll need to fix `/usr/bin/code-oss` by removing the quotes from `${codeflags[@]}` in the last line.
> 
> ```
> ELECTRON_RUN_AS_NODE=1 exec /usr/lib/${name}/electron /usr/lib/code/out/cli.js "${electronflags[@]}" /usr/lib/code/code.js ${codeflags[@]} "$@"
> ```

![image](https://github.com/prasanthrangan/hyprdots/assets/85342902/6220345e-246f-471a-a688-69ce3f9bc9dc)

I did that but these 2 files still appear ..... this happened after last code-oss update

**Comment by vampirepapi** [comment]
> this is known issue, please refer [#1292 (comment)](https://github.com/prasanthrangan/hyprdots/issues/1292#issuecomment-2052979781)
> 
> you'll need to fix `/usr/bin/code-oss` by removing the quotes from `${codeflags[@]}` in the last line.
> 
> ```
> ELECTRON_RUN_AS_NODE=1 exec /usr/lib/${name}/electron /usr/lib/code/out/cli.js "${electronflags[@]}" /usr/lib/code/code.js ${codeflags[@]} "$@"
> ```

TYSM bro

**Comment by NotAF0e** [comment]
Whenever I do Hyde update this comes back

**Comment by kRHYME7** [comment]
Re you sure only Hyde update,?

This is handled by pacman. So whenever there's an update the fixes you made will change because /usr/bin/code is handled by the package from the package manager

**Comment by kRHYME7** [comment]
BTW to report the bug it's from the arch Official package Manager.


Here's the problematic file ig.
https://gitlab.archlinux.org/archlinux/packaging/packages/code/-/blob/main/code.sh

**Comment by NotAF0e** [comment]
Ok thanks!

**Comment by unknowncat-meow** [comment]
if you have issue similar to this. this might help https://github.com/prasanthrangan/hyprdots/issues/1685
