### ISSUE TITLE
[Bug]: The Brightness indicator and Volume Indicator are not visible

### ISSUE THREAD

**Issue by KitsuneKode** [prasanthrangan/hyprdots#1316]
### Description
The functionality is intact and works properly i.e, the brightness and volume are changing but the notification that used to be shown in the right upper corner of the desktop indicating the brightness/volume is not shown/rendered.

The indicator in the waybar is working perfectly tho.

**Comment by kRHYME7** [comment]
@KitsuneKode  Please confirm if you got this package ``` yay -Qs libnotify ```

**Comment by KitsuneKode** [comment]
> @KitsuneKode Please confirm if you got this package `yay -Qs libnotify`

````yay -Qs libnotify
local/libnotify 0.8.3-1
    Library for sending desktop notifications`````

**Comment by kRHYME7** [comment]
sometimes that daemon just die or may conflict to other notification daemon. will close this as complete
