### ISSUE TITLE
Get rid of config.ctl in waybar directory

### ISSUE THREAD

**Issue by ChrolloRifat** [prasanthrangan/hyprdots#1318]
Is it possible to get rid of the reliance on the config.ctl file in the waybar directory which is used to generate the wbarconfgen.sh? The config.ctl unnecessarily complicates the both the script and the editing of the waybar. It is too hard to understand or make any changes to the waybar because of this file.

**Comment by Skerse** [comment]
> The config.ctl unnecessarily complicates the both the script and the editing of the waybar

I would say it makes it a lot easier to understand.. it makes it nice to easily change things in a small and more readable format and have a script generate it.

> Is it possible to get rid of the reliance on the config.ctl file in the waybar directory
Though, sure, you can remove it yourself like a personal fork but i don't believe we'll be removing it on our end.

Everything related to that is: 
- `Configs/.config/waybar/config.ctl`
- `Configs/.config/waybar/modules/wbar.jsonc`
- `Configs/.local/share/bin/wbarconfgen.sh`
- `Configs/.local/share/bin/wbarstylegen.sh`

**Comment by ChrolloRifat** [comment]
I don't know how to exactly read this file. Is there any guide or documentation that would help me understand the file better?!

**Comment by dieBakterie** [comment]
Should we add how to use this File in the Wiki?

**Comment by Skerse** [comment]
Is there any guide or documentation that would help me understand the file better?!

No.. but i just finished working making the readme up-to-date, i'll be working on making significant improvements to the wiki now. Though, i'll just copy a response i made to someone on the discord before: 

> Each field is split by a "|"
> 
> Field 1: Whether or not the configs should be overwritten
> Field 2: Whether or not the configs should be backed up
> Field 3: Base config file/directory path location
> Field 4: Relative path to where the file/directory path location is to the base path
> Field 5: The packages that need to be installed for the script to even work correctly

**Comment by dieBakterie** [comment]
That's what i meant

**Comment by kRHYME7** [comment]
@Skerse  If you can salvage the old wiki, I think the instructions are there. Slightly busy these days, so I can't help that much.

**Comment by ChrolloRifat** [comment]
> Should we add how to use this File in the Wiki?
yes please.
