### ISSUE TITLE
[Feature Request]: How to  Uninstall hyprdots?

### ISSUE THREAD

**Issue by leemeng0x61** [prasanthrangan/hyprdots#1319]
### how to uninstall hyprdots?

I don't wanna use it.

**Comment by MostlyKIGuess** [comment]
@kRHYME7 

```
#!/bin/bash


read -p "Are you sure you want to uninstall? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
# files
    rm -f "${HOME}/.zshrc"
    rm -f "${HOME}/.p10k.zsh"
    rm -f "${HOME}/.config/Code/Usersettings.json"
    rm -f "${HOME}/.config/Code - OSS/Usersettings.json"
    rm -f "${HOME}/.config/code-flags.conf"
    rm -f "${HOME}/.config/spotify-flags.conf"
    rm -f "${HOME}/.config/dunst/dunst"
    rm -f "${HOME}/.config/fish/fish"
    rm -f "${HOME}/.config/hydewall/bash/hyprland"
    rm -f "${HOME}/.config/hypranimations.conf"
    rm -f "${HOME}/.config/hyprhyprland.conf"
    rm -f "${HOME}/.config/hyprwindowrules.conf"
    rm -f "${HOME}/.config/hyprthemeshyprland"
    rm -f "${HOME}/.config/hyprkeybindings.conf"
    rm -f "${HOME}/.config/hyprmonitors.conf"
    rm -f "${HOME}/.config/hypruserprefs.conf"
    rm -f "${HOME}/.config/hyprnvidia.conf"
    rm -f "${HOME}/.local/share/bin/hyprland"
    rm -f "${HOME}/.config/kitty/kitty"
    rm -f "${HOME}/.config/Kvantum/kvantum"
    rm -f "${HOME}/.config/lsd/lsd"
    rm -f "${HOME}/.config/MangoHud/mangohud"
    rm -f "${HOME}/.config/neofetch/neofetch"
    rm -f "${HOME}/.config/qt5ct/qt5ct"
    rm -f "${HOME}/.config/qt6ct/qt6ct"
    rm -f "${HOME}/.config/rofi/rofi"
    rm -f "${HOME}/.config/swaylock/swaylock-effects"
    rm -f "${HOME}/.config/waybar/modules/waybar"
    rm -f "${HOME}/.config/waybar/config.jsonc"
    rm -f "${HOME}/.config/waybar/style.css"
    rm -f "${HOME}/.config/waybar/theme.css"
    rm -f "${HOME}/.config/waybar/config.ctl"
    rm -f "${HOME}/.config/wlogout/wlogout"
    rm -f "${HOME}/.config/xsettingsd/nwg-look"
    rm -f "${HOME}/.config/nwg-look/nwg-look"
    rm -f "${HOME}/.config/gtk-3.0/nwg-look"
    rm -f "${HOME}/.icons/default/nwg-look"
    rm -f "${HOME}/.gtkrc-2.0/nwg-look"
    rm -f "${HOME}/.config/dolphinrc"
    rm -f "${HOME}/.config/kdeglobals"
    rm -f "${HOME}/.local/share/dolphin/dolphin"
    rm -f "${HOME}/.local/share/kxmlgui5/dolphin/dolphin"
    rm -f "${HOME}/.local/share/kio/servicemenus/hydewallpaper.desktop"
    rm -f "${HOME}/.config/libinput-gestures.conf"

    # direcotries
    rm -rf "${HOME}/.config/Code"
    rm -rf "${HOME}/.config/Code - OSS"
    rm -rf "${HOME}/.config/dunst"
    rm -rf "${HOME}/.config/fish"
    rm -rf "${HOME}/.config/hydewall"
    rm -rf "${HOME}/.config/hyprland"
    rm -rf "${HOME}/.config/kitty"
    rm -rf "${HOME}/.config/Kvantum"
    rm -rf "${HOME}/.config/lsd"
    rm -rf "${HOME}/.config/MangoHud"
    rm -rf "${HOME}/.config/neofetch"
    rm -rf "${HOME}/.config/qt5ct"
    rm -rf "${HOME}/.config/qt6ct"
    rm -rf "${HOME}/.config/rofi"
    rm -rf "${HOME}/.config/swaylock"
    rm -rf "${HOME}/.config/waybar"
    rm -rf "${HOME}/.config/wlogout"
    rm -rf "${HOME}/.config/xsettingsd"
    rm -rf "${HOME}/.config/nwg-look"
    rm -rf "${HOME}/.config/gtk-3.0"
    rm -rf "${HOME}/.icons/default"
    rm -rf "${HOME}/.config/dolphin"
    rm -rf "${HOME}/.local/share/dolphin"

echo "Uninstallation completed."

else 
    echo "Uninstallation aborted."
fi
```
- Should I add this as a uninstall script? or maybe add options for each app to user?

**Comment by kRHYME7** [comment]
This is actually bad and better off doing a fresh install of any apps. New Packages will just overwrite the configs. So What's better is to delete apps that are inside the custom_hypr.lst that the users don't use.

**Comment by prasanthrangan** [comment]
I'll create a script to remove the config files, but it wont be able to remove the installed packages... so you have to manually uninstall the packages that you don't need.
You'll also have to manually remove and restore customized icons/themes/fonts/cursors/sddm/pacman/bootloader etc...

**Comment by prasanthrangan** [comment]
This is done in a170b50

Please follow these steps to uninstall everything...

### Step 1 : exec uninstall
```
cd ~/Hyprdots/Scripts
git pull
./uninstall                                  # type in "DONT HYDE" when it prompts
```

### Step 2 : remove these manually

Remove HyDE related backups/icons/fonts/themes manually from these paths
```
$HOME/.config/cfg_backups                    # remove all previous backups
$HOME/.local/share/fonts                     # remove fonts from here
$HOME/.icons                                 # remove icons from here
$HOME/.themes                                # remove themes from here
```

Revert back bootloader/pacman/sddm settings manually from these backups
```
/boot/loader/entries/*.conf.t2.bkp           # restore systemd-boot from this backup
/etc/default/grub.t2.bkp                     # restore grub from this backup
/boot/grub/grub.t2.bkp                       # restore grub from this backup
/usr/share/grub/themes                       # remove grub themes from here
/etc/pacman.conf.t2.bkp                      # restore pacman from this backup
/etc/sddm.conf.d/kde_settings.t2.bkp         # restore sddm from this backup
/usr/share/sddm/themes                       # remove sddm themes from here
```

### Step 3 : uninstall packages
Uninstall the packages manually that are no longer required based on these list
[custom_hypr.lst](https://github.com/prasanthrangan/hyprdots/blob/main/Scripts/custom_hypr.lst)
[custom_apps.lst](https://github.com/prasanthrangan/hyprdots/blob/main/Scripts/custom_apps.lst)

**Comment by raphael-as** [comment]
> This is done in [a170b50](https://github.com/prasanthrangan/hyprdots/commit/a170b50a9fb9c1d8528d277398106c99ea30eda0)
> 
> Please follow these steps to uninstall everything...
> ### Step 1 : exec uninstall
> 
> ```
> cd ~/Hyprdots/Scripts
> git pull
> ./uninstall                                  # type in "DONT HYDE" when it prompts
> ```
> 
> ### Step 2 : remove these manually
> 
> Remove HyDE related backups/icons/fonts/themes manually from these paths
> 
> ```
> $HOME/.config/cfg_backups                    # remove all previous backups
> $HOME/.local/share/fonts                     # remove fonts from here
> $HOME/.icons                                 # remove icons/cursors from here
> $HOME/.themes                                # remove themes from here
> ```
> 
> Revert back bootloader/pacman/sddm settings manually from these backups
> 
> ```
> /boot/loader/entries/*.conf.t2.bkp           # restore systemd-boot from this backup
> /etc/default/grub.t2.bkp                     # restore grub from this backup
> /boot/grub/grub.t2.bkp                       # restore grub from this backup
> /usr/share/grub/themes                       # remove grub themes from here
> /etc/pacman.conf.t2.bkp                      # restore pacman from this backup
> /etc/sddm.conf.d/kde_settings.t2.bkp         # restore sddm from this backup
> /usr/share/sddm/themes                       # remove sddm themes from here
> ```
> 
> ### Step 3 : uninstall packages
> 
> Uninstall the packages manually that are no longer required based on these list [custom_hypr.lst](https://github.com/prasanthrangan/hyprdots/blob/main/Scripts/custom_hypr.lst) [custom_apps.lst](https://github.com/prasanthrangan/hyprdots/blob/main/Scripts/custom_apps.lst)
> 
> If you have the old hyprdots strcture, then remove it as below
> 
> ```
> rm -rf "$HOME/.config/hyprdots"
> rm -rf "$HOME/.config/swww"
> rm -rf "$HOME/.cache/hyprdots"
> ```

hello ! i try to do that but it say that bash: ./uninstall: No such file or directory

**Comment by kRHYME7** [comment]
@raphael-as  Navigate to where you clone the repository. 

find the file "uninstall.sh" 

then run it. 

```
cd ~/HyDE/Scripts/
./uninstall.sh
```

https://github.com/prasanthrangan/hyprdots/blob/a170b50a9fb9c1d8528d277398106c99ea30eda0/Scripts/uninstall.sh
or copy this file name it uninstall.sh then run it like ` bash ./uninstall.sh `

**Comment by raphael-as** [comment]
> @raphael-as Navigate to where you clone the repository.
> 
> find the file "uninstall.sh"
> 
> then run it.
> 
> ```
> cd ~/HyDE/Scripts/
> ./uninstall.sh
> ```
> 
> https://github.com/prasanthrangan/hyprdots/blob/a170b50a9fb9c1d8528d277398106c99ea30eda0/Scripts/uninstall.sh or copy this file name it uninstall.sh then run it like `bash ./uninstall.sh`

ok its work but after this, my terminal is white even in dark mode and VScode the navbar is white too how can i fix that pls

**Comment by WGrav01** [comment]
When I run uninstall.sh I get the following error:

```bash <(curl -s https://raw.githubusercontent.com/prasanthrangan/hyprdots/main/Scripts/uninstall.sh) 

-------------------------------------------------
        .
       / \                 _  _      ___  ___ 
      /^  \      _____    | || |_  _|   \| __|
     /  _  \    |_____|   | __ | || | |) | _| 
    /  | | ~\             |_||_|\_, |___/|___|
   /.-'   '-.\                  |__/          

-------------------------------------------------


.: WARNING :: This will remove all config files related to HyDE :.

please type "DONT HYDE" to continue...
DONT HYDE

         _         _       _ _ 
 _ _ ___|_|___ ___| |_ ___| | |
| | |   | |   |_ -|  _| .'| | |
|___|_|_|_|_|_|___|_| |__,|_|_|


/proc/self/fd/11: line 39: /proc/143623/fd/global_fn.sh: No such file or directory
Error: unable to source global_fn.sh...```
