### ISSUE TITLE
waybar size changes depending on whether an application is on or not

### ISSUE THREAD

**Issue by icoderarely** [prasanthrangan/hyprdots#1320]
So suppose I have no application running or they are in some other workspace, so I will have something like this
![image](https://github.com/prasanthrangan/hyprdots/assets/166960965/b9b833d7-7ebf-474c-ae17-8b4b154bdd53)

And if I open any application the size increases a bit
![image](https://github.com/prasanthrangan/hyprdots/assets/166960965/003f1ec9-5940-487f-a853-7780498bde7f)

`I am not sure if you're able to make out the difference in size, because it is very less but it does show up to me.`
Again if I close this application or move it to another workspace 2 and I stay on workspace 1, I will be seeing the default size.

What could be the potential issue here? And what do I do to fix this?

**Comment by kRHYME7** [comment]
are you pertaining to the gaps?  or the entire waybar layer becomes bigger ?

**Comment by Skerse** [comment]
> are you pertaining to the gaps? or the entire waybar layer becomes bigger ?

Looking at the image side by side, the whole layer becomes bigger. I have no idea why, i know that the specific waybar layout they're using *should* have a set pixel width.. unless they messed with the waybar layout themselves.

**Comment by kRHYME7** [comment]
Yow can anyone try this https://github.com/Alexays/Waybar/issues/3334#issuecomment-2151753984 https://github.com/Alexays/Waybar/issues/3334

**Comment by abenezerw** [comment]
i think this was fixed upstream. can you please close the issue if its solved. @icoderarely
