### ISSUE TITLE
[Bug]: Code - OSS Launch Arguments Error

### ISSUE THREAD

**Issue by SizzinSeal** [prasanthrangan/hyprdots#1322]
## Bug Report
Code - OSS does not parse launch arguments properly

### Description

Code - OSS does not parse launch arguments properly. It thinks some arguments are files that need to be created

### Steps to Reproduce

1. Launch Code - OSS
2. Observe 2 files opened with names that appear to be launch flags

### Expected Behavior

Code - OSS does not try to create files on launch

### Actual Behavior

Code - OSS launches and tries to create files with names resembling launch flags

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/111480281/a4941cfa-4194-4d8a-954e-0ee63d5461e1)

### Environment
- Linux Distro: CachyOS (Arch based)
- Linux Version: 6.8.6-2-cachyos
- Code - OSS version: 1.88.1

### Additional Information

Code - OSS seems to be functioning as intended. Why are those flags necessary in the first place?

**Comment by AtnProjects** [comment]
![imagen](https://github.com/prasanthrangan/hyprdots/assets/72979783/113d4639-0719-4319-8a8b-bc7fdf702738)

**Comment by kRHYME7** [comment]
Dupe https://github.com/prasanthrangan/hyprdots/issues/1315

We can use the search filter BTW

**Comment by SizzinSeal** [comment]
The solution in #1315 did not fix it

**Comment by SizzinSeal** [comment]
Also it outputs a warning when launched from the terminal: `Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.`

**Comment by SizzinSeal** [comment]
I printed the command that was executed, this is what it after all variables have been substituted with their values:
```
 exec /usr/lib/electron28/electron /usr/lib/code/out/cli.js /usr/lib/code/code.js --ozone-platform-hint=wayland --disable-gpu
 ```

**Comment by SizzinSeal** [comment]
Oh wait nevermind, I fixed it. I forgot that vscode will preserve unsaved files if you close it, so I thought it still wasn't working. The fix worked. This issue can stay closed
