### ISSUE TITLE
[Bug]: rofi text display breaks when scaling is larger than 1

### ISSUE THREAD

**Issue by SizzinSeal** [prasanthrangan/hyprdots#1323]
### Description

CSS breaks when hyprland scaling is set to a value larger than 1, e.g `monitor = eDP-1,1920x1080@300,0x0,1.25`

### Steps to Reproduce

1. Set monitor scaling in hyprland.conf to a value larger than 1, e.g 1.25
2. Open theme select and rofi wall select
3. Observe cut-off text

### Expected Behavior

Images scale to allow enough room for text

### Actual Behavior

Images cut off text

### Screenshots

__**Scaling 1**__
![image](https://github.com/prasanthrangan/hyprdots/assets/111480281/9f902043-01f7-4bc5-9a7e-c4e8ef6b5b42)
![image](https://github.com/prasanthrangan/hyprdots/assets/111480281/50099b33-2d6b-4284-b8ee-7abb249c2c19)

__**Scaling 1.25**__
![image](https://github.com/prasanthrangan/hyprdots/assets/111480281/8a8ed9ef-9f81-4038-a8f3-844a609a5e92)
![image](https://github.com/prasanthrangan/hyprdots/assets/111480281/b7725903-a8fa-41b2-8820-7a016e3dd0b6)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

- __**Hyprland monitor config:**__ `monitor = eDP-1,1920x1080@300,0x0,1.25`
- __**Hyprland Version:**__ `v0.39.0`
- __**Rofi Version:**__` 1.7.5+wayland3-3-g47ae31eb`
__**Rofi Monitor layout:**__
```
Monitor layout:
              ID: 50
            name: eDP-1
           scale: 2
        position: 0,0
            size: 1920,1080
            size: 340mm,190mm  dpi: 72,72
```

### Additional Information
 - Observation - rofi scale is set to 2. Does rofi not support fractional scaling?
 - This seems to affect all rofi displays. I did not attach all of them for clarity, but I'm happy to add them upon request.

**Comment by kRHYME7** [comment]
Try to scale it first though.

inside ``` ~/.config/hyde/hyde.conf ```

add line

``` rofiScale=8  ```  Try to tweak this value

also dunno about the keybind, See the README the keybindings are there.

**Comment by SizzinSeal** [comment]
Will do. But it should probably be automatic

**Comment by SizzinSeal** [comment]
Yes that worked. Should I convert this to an frq or leave it as a bug?

**Comment by kRHYME7** [comment]
leave it as a bug for now. I got a way to dynamically scale it a bit want to try?

**Comment by SizzinSeal** [comment]
sure

**Comment by kRHYME7** [comment]
https://gist.github.com/kRHYME7/bc97c3bf99d931d5af11df56a6e1f668

To test please remove the changes on the rofiScale first

**Comment by itsmenewbie03** [comment]
Tweaking the value affects the other rofi components? (idk how it's called)
![image](https://github.com/prasanthrangan/hyprdots/assets/89230263/b632de5b-3ca9-4601-8aa4-732e26d6eeea)
still the theme selector looks odd
![image](https://github.com/prasanthrangan/hyprdots/assets/89230263/01ca72f5-94a3-421b-92de-3afb27c7069a)

**Comment by prasanthrangan** [comment]
Yup, the monitor scale is not considered yet, I'll update the logic to reduce the columns if it does not fit your screen...

**Comment by prasanthrangan** [comment]
Hi, this is fixed... so when you reduce `rofiScale` value in `~/.config/hyde/hyde.conf` it will increase the columns to fill... and if you increase the `rofiScale` value, then number of cols will be reduce to fit the elements.
