### ISSUE TITLE
[Bug]: Notification bug

### ISSUE THREAD

**Issue by Chiro145** [prasanthrangan/hyprdots#1326]
**It may be duplicated, but the existing solutions not work for me**
### Actual Behavior

The sound **notification bar** has a problem, it no longer shows the sound level but instead shows **"t2"**
The notification box **looks sharp**, and doesn't look like the **latest update**

### Screenshots
![image](https://github.com/prasanthrangan/hyprdots/assets/87656808/462c9c29-155f-42bc-b133-7a1b4b914efb)

- Linux Distro: Arch
- Hyprland Version: v0.35.0
- Installation Environment: On The Main Hardware
- Other info: [e.g., Display Resolution, Resolution, etc] = Monitor 1: 1366x768, Monitor 2: 1920x1080

**Comment by kRHYME7** [comment]
updated to the latest commit?

**Comment by kRHYME7** [comment]
Can You run this? ``` Hyde version ``` ?

This actually looks like an older commit

**Comment by kRHYME7** [comment]
Please follow this. we got a lot of changes
https://github.com/prasanthrangan/hyprdots/issues/1285

**Comment by Skerse** [comment]
@Chiro145 in the screenshot you ran `yay -S Hyde`, it's `hyde-cli-git`.

**Comment by rubiin** [comment]
No problems on mine so far
![image](https://github.com/prasanthrangan/hyprdots/assets/8222059/60c2eb62-87b9-4a18-b9a5-1d926ecee51e)
