### ISSUE TITLE
[Wallpaper fit not working]: wallpapers not taking all the space available

### ISSUE THREAD

**Issue by asuka-405** [prasanthrangan/hyprdots#1335]
### Description

![image](https://github.com/prasanthrangan/hyprdots/assets/97630173/9fa0f875-dd1b-4691-9d0e-ddb35e3d8883)

Since yesterday, all wallpapers looks like this.
I tried to reinstall hyprdots, even reinstalled the entire os but still its like this.

### Steps to Reproduce

Bug appears as soon as hyprland with hyprdots start.
It's like this in my system without even messing with any config.

### Expected Behavior

Wallpaper should fit itself to the screen width

### Actual Behavior

Wallpaper is stretches smaller than actual screen width leaving blackspace in all 4 directions.

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/97630173/9fa0f875-dd1b-4691-9d0e-ddb35e3d8883)

![image](https://github.com/prasanthrangan/hyprdots/assets/97630173/46af78a5-d813-48a5-b01f-2d3508669b8c)

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: 6.8.6-arch1-1
- Hyprland Version, output of `hyprctl version`:
                   Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
                   Date: Tue Apr 16 16:01:03 2024
                   Tag: v0.39.1, commits: 4460
- Installation Environment: On The Main Hardware
- Other info: 1920x1080@60Hz

**Comment by kRHYME7** [comment]
Hello thanks for rising this issue. This is actually an upstream bug and a duplicate. Please read the thread below.  (And utilize the search filter)

https://github.com/prasanthrangan/hyprdots/issues/1317
