### ISSUE TITLE
[Bug]: Clock format resets after themeswitch.sh

### ISSUE THREAD

**Issue by TimSchimansky** [prasanthrangan/hyprdots#1338]
### Description

I personally hate the AM/PM time format, as I am very used to the 24hour format. When i set that up in ...../waybar/config.jsonc as `"format": "{:%H:%M}",` and then restarting waybar it initially works great, but after toggling the themeswitch.sh once (via the shortcut in the waybar) it just reverts back the changes. I do not see why it does this tho...

### Steps to Reproduce

1. Change clock format
2. Toggle themeswitch
3. clock broken again

**Comment by kRHYME7** [comment]
Do not change that there. 

Change the value in this file
```
~/.config/waybar/modules/clock.jsonc
```

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/6c163009-ab74-40f8-8024-f8d12a51464e)


But I would suggest making a separate module and do your changes there,
Example I added the ./roman_clock.jsonc
then added the entry to ~/.config/waybar/config.ctl ``` 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/9ac3117d-8aef-4478-b3bf-9d47fa0df084)


I added a separate module so that if you pull changes even the clock json is overwritten your own clock module can be retirve easily

**Comment by TimSchimansky** [comment]
oooh I am really sorry then. I only used sway before, where there was just a single waybar config and i wasnt aware of the external clock config. Yeah then this is solved. Thanks for your quick reply! :)

**Comment by kRHYME7** [comment]
No probs! 👍 It is just a way to reproduce the waybar configs with different layouts hence this control file.
