### ISSUE TITLE
[Bug]: After update can't change keyboard layout (language)

### ISSUE THREAD

**Issue by Artavazdpet** [prasanthrangan/hyprdots#1339]
### Description

After not updating for a while (for 8 months or so, lmao), when i updated i can't change my keyboard language anymore, iirc i did it with localectl so i was sure that it should work, but well, it doesn't.

### Expected Behavior

To change language on win+space.

### Actual Behavior

Nothing, it just types the space.

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/90024173/4b46f0c6-ed90-490e-9fc8-cee9b64d3e8f)

- Linux Distro: ArchLinux
- Linux Version: 6.8.7-arch1-1 
- Hyprland Version: v0.39.1
- Installation Environment: Main

**Comment by Enigma1309** [comment]
```
input {
    kb_layout = ru     # replace ru with your preferred layout 
 }
```
add this to your `~/.config/hypr/userprefs.conf`

**Comment by Artavazdpet** [comment]
> ```
> input {
>     kb_layout = ru     # replace ru with your preferred layout 
>  }
> ```
> 
> add this to your `~/.config/hypr/userprefs.conf`

No i don't want to permanently change the keyboard language, i want to have the ability to change them with win + space (and i'm a little bit lazy to create script for that).
As i said before it was working with localectl, but after adding hyprdots new version something conflicts with it and doesn't allow for localectl to change the language (And no, it's not "Input" part of the ~/.config/hypr/hyprland.conf)

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/893bac7a-7c73-4f49-991f-90854aa95236)

 This?

**Comment by Artavazdpet** [comment]
> This?

Aaaaah, never knew you can do that
Now it works, thanks

![image](https://github.com/prasanthrangan/hyprdots/assets/90024173/a989fae8-c0f0-4c97-87ed-3d2384fed16e)

**Comment by abusen333** [comment]
## How to Add Arabic Keyboard Layout and Toggle Using Super + Space in Hyprland

This guide will help you set up a dual keyboard layout (English and Arabic) and configure the toggle using the Super (Windows) key + Space in Hyprland on Linux. This method has been tested and works as expected.

### Step 1: Modify the Configuration File

Navigate to the Hyprland configuration file located at:
/home/a/.config/hypr/hyprland.confg

Update the input block as follows:


```
input {
    kb_layout = us,ara  # Specifies US and Arabic keyboard layouts
    kb_variant = ,       # No specific variants are used
    kb_options = grp:win_space_toggle  # Sets Super + Space as the toggle
    follow_mouse = 1

    touchpad {
        natural_scroll = no  # Disables natural scrolling
    }

    sensitivity = 0
    force_no_accel = 1
}
```

### Step 2: Reload Hyprland
To apply the changes, reload the Hyprland configuration. Open your terminal and execute the following command:
`systemctl restart hyprland`

### Note

_This configuration enables you to toggle between English and Arabic keyboard layouts using the Super key (Windows key) + Space. This feature is especially useful for bilingual users who need to switch between these two languages frequently._
