### ISSUE TITLE
Issue with Install script

### ISSUE THREAD

**Issue by lnagler1** [prasanthrangan/hyprdots#134]
After some time the install does not continue and is stuck. After making package nwg-look.

==> Making package: nwg-look 0.2.4-1 (Mi 30 Aug 2023 15:41:45)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading github.com/gotk3/gotk3 v0.6.2
go: downloading golang.org/x/sys v0.6.0
github.com/gotk3/gotk3/gtk

After the last line the install does not continue.

**Comment by SivertGullbergHansen** [comment]
> Hello Inagler1,
> 
> Did you find a solution to the problem? My installation is also hanging on `github.co/gotk3/gotk3/gtk`

To give an actual answer to this question: it just takes time... I didn't keep track of mine but perhaps 10-15 minutes.
