### ISSUE TITLE
[Feature Request]: Add dracula

### ISSUE THREAD

**Issue by rubiin** [prasanthrangan/hyprdots#1340]
### Description

Dracula themes seems to be a good fit for default themes. 
Theres even hyprcursor [guillaumeboehm/hyprcursor_dracula_kde](https://github.com/guillaumeboehm/hyprcursor_dracula_kde)

[Provide a clear and concise description of the feature you'd like to see added.]

### Use Case

[Describe how this feature would be useful to you or to other users of the project.]

### Proposed Solution

[If you have a specific solution in mind, describe it here. If not, you can skip this section.]

### Alternatives

[Are there any alternative solutions or workarounds that you've considered? If so, describe them here.]

### Additional Information

[Add any other information about the feature request here. For example, you might include links to similar features in other projects, or screenshots or diagrams to help explain your idea.]

**Comment by RAprogramm** [comment]
[Dracula](https://github.com/RAprogramm/Dracula) will be added to [HyDe Gallery](https://github.com/kRHYME7/hyde-gallery) soon

**Comment by RAprogramm** [comment]
Dracula was added!

**Comment by rubiin** [comment]
I think there is some problems on icons , getting this question mark
![image](https://github.com/prasanthrangan/hyprdots/assets/8222059/16e180df-3de4-4eb6-a868-03e00787f322)

**Comment by RAprogramm** [comment]
> I think there is some problems on icons , getting this question mark
> ![image](https://github.com/prasanthrangan/hyprdots/assets/8222059/16e180df-3de4-4eb6-a868-03e00787f322)
> 

Open issue in my repo, please, I have same

**Comment by rubiin** [comment]
sure thing. I guess i will close this one here
