### ISSUE TITLE
[Bug]: Logoutlaunch.sh doesnt do anything anymore

### ISSUE THREAD

**Issue by dbt0815** [prasanthrangan/hyprdots#1342]
### Description
mainmod + backspace doesnt start the logout out launch.
running it by clicking the .sh file doesnt do anything either.

EndavourOS, Hyprland (latest),

**Comment by kRHYME7** [comment]
output when you execute ``` logoutlaunch.sh ```

**Comment by dbt0815** [comment]
"/home/drum/.local/share/bin//logoutlaunch.sh: line 57: /home/drum/.cache/hyde/wall.dcol: No such file or directory"

**Comment by kRHYME7** [comment]
I suggest reloading or rebuilding cache.

Hyde cache reload

or


Hyde  cache rebuild

**Comment by dbt0815** [comment]
the command hyde doesnt to anything for me.

**Comment by Skerse** [comment]
> the command hyde doesnt to anything for me.

Make sure it's a capital letter if you didn't do so.. `Hyde`

If it's not installed, make sure by doing `yay -S hyde-cli-git` or `paru -S hyde-cli-git`

**Comment by dbt0815** [comment]
this did the trick.
thank you very much.

**Comment by Skerse** [comment]
Nice, you're welcome.
