### ISSUE TITLE
[Bug]: install.sh terminates after [themepatcher] Patching themes...

### ISSUE THREAD

**Issue by tryprncp** [prasanthrangan/hyprdots#1344]
### Description

The installation script terminates after: 
[themepatcher] Patching themes...
100% 12:0=5m40s Nordic Blue https://github.com/prasanthrangan/hyde-themes/tree/Nordic-Blue --skipcaching false 

It didn't even proceed to line: 
echo -e "\n\033[0;32m[cache]\033[0m generating cache files..."

I didn't have this issue before (when it was hyprdots) prior to HyDE
Also, i have to keep trying running install.sh because git clone keeps terminating when cloning aur packages like oh-my-zsh-git and zsh-theme-powerlevel10k. So packages are not installed in their order, maybe this script is sensitive to that?
I hope anyone notices this :>

### Steps to Reproduce

1. [First Step] run ./install.sh
2. [Second Step]
3. [and so on...]

### Expected Behavior

It should complete the installation without any errors.

### Actual Behavior

It didn't finish the installation script and terminate after themepactcher

### Screenshots

![240420_14h04m18s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/91647110/7662bb2a-3b71-4bf6-aa8c-b17a25699f73)

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux archnemesis 6.8.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460
- Installation Environment: On The Main Hardware
- Other info: 1920x1080@60

### Additional Information
 CPU : 12th Gen Intel i5-1235U (12) @ 4.400GHz
 GPU : Intel Alder Lake-UP3 GT2 [Iris Xe Graphics] 
​ GPU Driver : Hewlett-Packard Company Device [103c:8a20] 
﬙ Memory : 3327MiB / 31773MiB 

Also, dolphin isn't themed
![240420_13h49m32s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/91647110/eecd2dac-d5fd-4e0f-a720-0807befa93b2)

**Comment by kRHYME7** [comment]
for themes can you run ``` Hyde theme patch ``` ? and select some themes?

**Comment by Igor-Imej** [comment]
Got the same issue for quite some time on multiple devices. Hyde-install didnt work. Hyde theme patch didnt work. Same result both cases:

❯ Hyde theme patch
[themepatcher] Patching the following themes...
Synth Wave
[ENTER] continue [ANY]  Exit:
100% 1:0=1s Synth Wave https://github.com/prasanthrangan/hyde-themes/tree/Synth-Wave --skipcaching false

**Comment by kRHYME7** [comment]
@Igor-Imej  can you try this? 

`./themepatcher.sh  "One Dark" "https://github.com/RAprogramm/OneDark/tree/One-Dark-hyde" `

**Comment by Igor-Imej** [comment]
It worked for me. 

Saw new wallpapers (like yellow truck) in update screenshots, but not in my update. Bug?

**Comment by kRHYME7** [comment]
Wallpapers now belong to themes. about the yellow truck dunno which theme hosts that, but definitely not a bug. This repo doesn't  have any themes. Themes are hosted in a different repo.

**Comment by kRHYME7** [comment]
`Hyde theme patch ` doesn't work?

Try selecting another theme using this.

**Comment by Igor-Imej** [comment]
❯ Hyde theme patch
[themepatcher] Patching the following themes...
Rosé Pine
[ENTER] continue [ANY]  Exit:
100% 1:0=1s Rosé Pine https://github.com/prasanthrangan/hyde-themes/tree/Rose-Pine --skipcaching false                       

[cache] generating cache files...
100% 124:0=0s 7cd12a23084b0ad1e02b9053f9322afbd35cfb10 /home/igord/.config/hyde/themes/Tokyo Night/wallpapers/tokyo_pink.png 



❯ Hyde theme patch
[themepatcher] Patching the following themes...
Frosted Glass
[ENTER] continue [ANY]  Exit:
100% 1:0=1s Frosted Glass https://github.com/prasanthrangan/hyde-themes/tree/Frosted-Glass --skipcaching false               

[cache] generating cache files...
100% 124:0=0s 7cd12a23084b0ad1e02b9053f9322afbd35cfb10 /home/igord/.config/hyde/themes/Tokyo Night/wallpapers/tokyo_pink.png 


Not working.

**Comment by kRHYME7** [comment]
I think it works. can you check your theme list?

`ls ~/.config/hyde/themes/`

**Comment by Igor-Imej** [comment]
 'Catppuccin Latte'
 'Catppuccin Mocha'
 'Decay Green'
 'Edge Runner'
 'Frosted Glass'
 'Graphite Mono'
 'Gruvbox Retro'
 'Material Sakura'
 'Nordic Blue'
 'One Dark'
 'Rosé Pine'
 'Synth Wave'
 'Tokyo Night'

Just wiped my laptop and reinstalled Arch and Hyprdots everything works fine.  However script still seems to crash on my PC after patching theme.  Ill leave it to the original poser to provide more information about the bug since it seems that his Dolphin theme is also bugged so it might be a different issue since mine is working just fine.

**Comment by rubiin** [comment]
I dont know if this is a bug or not on hyde cli but when selecting multiple themes to patch , only one is being patched
![image](https://github.com/prasanthrangan/hyprdots/assets/8222059/34327a5e-bdaa-442b-8534-b778b9334ef0)

**Comment by kRHYME7** [comment]
How do you know that it only patch 1 theme? 

what is the output for ` ls ~/.config/hyde/themes/ `

**Comment by rubiin** [comment]
Oh I was just using the terminal output . It was just showing progress for one

**Comment by kRHYME7** [comment]
> Oh I was just using the terminal output . It was just showing progress for one

The progress bar will show the themes 1 at a time


https://github.com/prasanthrangan/hyprdots/assets/53417443/b4b1af76-0e5a-4827-b2fd-9a16381ad7aa

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/d74587f2-9f93-4106-bc67-533d419f753e)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/3b84fdb3-981f-449b-8f2a-4ebe5fcd9bc0)

**Comment by kRHYME7** [comment]
Sure https://github.com/kRHYME7/Hyde-cli/blob/511472f9a989813a4b440ec21e1550c238b39b20/Scripts/Manage-Themes#L132C1-L144C7
