### ISSUE TITLE
Spicetify theme is different

### ISSUE THREAD

**Issue by drnikos** [prasanthrangan/hyprdots#1346]
I did a fresh install 2 days ago, and when I used the spotify wallbash script, the theme is different than expected:  the progress bar  is always shown with an circle in the end and the pause-play button is like the one in stock spotify. How can I revert to the previous style?
![240420_16h55m28s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/153459342/6988c76e-c0ac-4fa4-8539-672f4bd27737)

**Comment by sandibi13** [comment]
This is hyprdots custom theme applied by wallbash.

Remove the theme and scheme from your spicetify config to get the default looks back.
