### ISSUE TITLE
[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by XUnkownX** [prasanthrangan/hyprdots#1351]
Hello! I'm having a bit of an issue with Hyprdots. I installed it, but when I restart the computer, it doesn't come installed. I'm not sure if it's the config file. I just started using Hyprland recently, so I'm still learning the ropes!

Here's what I did to install it:

1. I installed Hyprland with Archinstall.

2. I installed some necessary packages (unzip, curl, wget).

3. I downloaded it as a ZIP file and extracted the folder. 

4 - I went into the Scripts folder and started the `install.sh` bash file (without root, `./install.sh`).

After the installation was finished, I turned the computer off and on.

I would be so grateful if you could help me and forgive me if I have any problems with my English. It's not my native language, and I'm translating it through a free online service, not to get it right. 🙏😇

I hope you're having a great day! I just wanted to let you know that I translated this with DeepL.com (free version).

**Comment by dieBakterie** [comment]
Some Error Messages or what isn't working would be helpful.,

**Comment by XUnkownX** [comment]
```
[xshadow@archlinux ~]$ cat /tmp/hypr/$(ls -t /tmp/hypr/ | head -n 2 | tail -n 1)/hyprland.log
[LOG] Instance Signature: fe7b748eb668136dd0558b7c8279bfcd7ab4d759_1713650695
[LOG] Hyprland PID: 481
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: archlinux
[LOG] Release: 6.8.7-arch1-1
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000


[LOG] GPU information:
00:02.0 VGA compatible controller [0300]: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display [8086:0f31] (rev 0e) (prog-if 00 [VGA controller])


[LOG] os-release:
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG] 
Current splash: "Hyper".replace("e", "")


[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] [hookSystem] New hook event registered: configReloaded
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 74.84µs. Estimated average calc time: 0.12µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 54.89µs. Estimated average calc time: 0.13µs.
[LOG] Using config: /home/xshadow/.config/hypr/hyprland.conf
[LOG] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
```

**Comment by dieBakterie** [comment]
Okay what's your Problem cause Hyprland doesn't Report any Errors

**Comment by dieBakterie** [comment]
Do you've a Login screen or are you using the terminal like you did for the log.

**Comment by XUnkownX** [comment]
My problem is that after installing Hyprdots nothing changes, no watbar, no icons. According to what I saw on the internet, after the installation I restart the computer and everything is supposed to be installed ? 

I am using sddm.

**Comment by XUnkownX** [comment]
![Uploading IMG_20240421_014345.jpg…]()

**Comment by XUnkownX** [comment]
![IMG_20240421_014345](https://github.com/prasanthrangan/hyprdots/assets/163411894/87b8b01d-a782-4b5d-905c-54463b9280da)

**Comment by dieBakterie** [comment]
What's the Output for `ls ~/.config/hypr/` ?

**Comment by dieBakterie** [comment]
So sddm is the same as before the installation?

**Comment by dieBakterie** [comment]
You Had No Errors while Installation? Entered your Password when prompted? Easiest would be to do `git pull` and then `./install.sh -r`

**Comment by XUnkownX** [comment]
Yes same as before Sddm installation

```
[xshadow@archlinux ~]$ ls ~/.config/hypr/
hyprland.conf
```

**Comment by dieBakterie** [comment]
Seems the Script does nothing cause there is only the `hyprland.conf` file. Can't say why just try to Reinstall ig

**Comment by dieBakterie** [comment]
I meant the dots `./install.sh`

**Comment by XUnkownX** [comment]
Thank you, my problem was solved with the command you gave. Thank you for your help 
`./install.sh -r`

**Comment by XUnkownX** [comment]
Thank you.
