### ISSUE TITLE
Fastfetch japanese

### ISSUE THREAD

**Issue by se7en-x230** [prasanthrangan/hyprdots#1354]
36m    コンピューター
I changed that to 
            "format": "\u001b[33mEat  , Sleep  , Linux "

![image](https://github.com/prasanthrangan/hyprdots/assets/69777713/707f726a-1a1d-44e1-a1df-5e307c49e820)

**Comment by Skerse** [comment]
Why did you make an issue for this, then mark it as a bug..? This is mostly for issues and feature requests. This does not belong here, at most this is something maybe for our discord. I'm going to close this.

**Comment by se7en-x230** [comment]
A language that can't be read by most might be an issue but whatever move it wherever you see fit

**Comment by kRHYME7** [comment]
You can do a PR to get it reviewed. Or at discussion's panel.
