### ISSUE TITLE
[Bug]: Blur is not applied on spotify after adding spotify controls to the waybar.

### ISSUE THREAD

**Issue by Tisteos** [prasanthrangan/hyprdots#1355]
### Description

The blur doesn't work after the second time you enter the spotify, and for some reason the spotify is called the name of the song that's playing.

### Steps to Reproduce

1. Open spotify (blur works).
2. Close the spotify so that it moves to the tray.
3. Open spotify and blur are gone.

### Expected Behavior

Semi-transparent spotify window.

### Actual Behavior

[What actually happened?]

![image](https://github.com/prasanthrangan/hyprdots/assets/111273978/1a7b7411-6216-4024-8634-23b428c13349)

### Environment

- archlinux 6.8.7-arch1-1
- Hyprland Version: 0.39.1
- Installation Environment: On The Main Hardware

### Additional Information

This issue appeared after adding spotify controls to the waybar.

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/4abbb320-7a9b-4715-817b-85ecb19be6db)


checkout hyprctl clients for that. You got Spotify subscription? 

You can add this ``` windowrulev2 = opacity 0.80 0.80,initialTitle:^(Spotify)(.*)$ ```

**Comment by Tisteos** [comment]
> ![image](https://private-user-images.githubusercontent.com/53417443/324225560-4abbb320-7a9b-4715-817b-85ecb19be6db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzgxNTQsIm5iZiI6MTcxMzY3Nzg1NCwicGF0aCI6Ii81MzQxNzQ0My8zMjQyMjU1NjAtNGFiYmIzMjAtN2E5Yi00NzE1LTgxN2ItODVlY2IxOWJlNmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA1MzczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZGYxNTdlNDMyNTYyM2U2ZTU1MmI4MjFkZDA4ODU2NmZlZDI2NTkwMTkyM2Q3NDMzOTdiMTI3YjgyMTgxMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RVh4PFoI0xUMH3JHjopUOVQDRSGupoiKEIvFgBRds-A)
> 
> checkout hyprctl clients for that. You got Spotify subscription?
> 
> You can add this `windowrulev2 = opacity 0.80 0.80,initialTitle:^(Spotify)(.*)$`

![image](https://github.com/prasanthrangan/hyprdots/assets/111273978/646735ed-e3d8-4d3f-95ed-e9209110fff0)

**Comment by Tisteos** [comment]
Sometimes it shows up normally, sometimes it doesn't.

**Comment by Tisteos** [comment]
I think I've figured out how it comes about. If you open spotify, then if you don't turn on the music, everything is fine, but if you turn on the music, minimize the spotify to the tray and open it again, while the music was on, the blur disappears.

**Comment by Tisteos** [comment]
If you do not turn on the music, it still shows "Spotify free".

![image](https://github.com/prasanthrangan/hyprdots/assets/111273978/0051f7d6-3b21-4319-8241-cd50d4e6be1d)

![image](https://github.com/prasanthrangan/hyprdots/assets/111273978/948e6f2d-1e8a-47e0-9242-adb2f17b6ef5)

**Comment by kRHYME7** [comment]
I see, happens to me too. Would you like to make all apps blur by default?  then just override it if you want specific app to be not blurred? 

``` windowrulev2 = opacity 0.80 0.80,class:^(.*)$ ``` add this then.

**Comment by Tisteos** [comment]
okay

**Comment by kRHYME7** [comment]
Add this to your ./userprefs.conf so that   it won't be overwritten across updates.

**Comment by kRHYME7** [comment]
Running it on xwayland looks ugly looks jaggy on some. 

But here's a way to set it for xwayland 

For spotify run by spicetify-cli (everytime you change wallpaper spicetify launches spotify for you)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/4e800408-7118-4235-ad2c-f1795d5047d5)

For spotify launch using the app launcher

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/f5bc6e0a-0aba-4d20-bb23-7cd04e98d572)


Change ` wayland ` to ` x11 `

Will close this as this is an upstream bug either report this to spicetify-cli please. Thanks
