### ISSUE TITLE
[Bug]: Swaylock can not switch keyboard layout

### ISSUE THREAD

**Issue by zeerayne** [prasanthrangan/hyprdots#1356]
### Description

Swaylock use current keyboard layout and does not have an ability to switch keyboard layout, and password can not be entered correctly if screen was locked using non-us keyboard layout

### Steps to Reproduce

1. Setup two or more keyboards layout in `~/.config/hypr/userprefs.conf`, i.e.
```jsonc
input {
    kb_layout = us,ru
}
```
2. Switch to `non-us` layout (`$mainMod+K`)
3. Lock screen with swaylock (`$mainMod+L`)
4. Screen can not be unlocked, due keyboard layout can not be switched to `us` for input password correctly

### Expected Behavior

When screen is locked with swaylock, switching keyboard layout should be available or swaylock should force switch layout to `us`

### Actual Behavior

When screen is locked with swaylock, keyboard layout last switched to is used and can not be changed

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: 6.8.7-arch1-1
- Hyprland Version, output of `hyprctl version`: 0.39.1
- Installation Environment: On The Main Hardware
- Swaylock-effects version: r470.496059a-1

**Comment by kRHYME7** [comment]
Can you check swaylock docs regarding this? https://man.archlinux.org/man/swaylock.1 

On your ` ./keybindings.conf ` make ` bind ` in ` bindl ` so that you can switch kb layout while lock   
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/1b7eba67-54a8-40d1-971c-fff8e1253a47)
