### ISSUE TITLE
[Bug]: Code OSS keeps opening unwanted files

### ISSUE THREAD

**Issue by betacoder7** [prasanthrangan/hyprdots#1357]
## Bug Report
Code OSS keep opening unwanted unsaved files
### Description
I have installed this config in qemu vm and I have noticed that code oss is keep opening files named 
    1. --ozone-platform-hint=wayland
    2. --disable-gpu

I keep closing those files but it keeps happening I have not made any changes to application desktop entry.

### Expected Behavior

It should open my previously opened workspace or If I open new window it should have any files or folders opened.

### Actual Behavior

It is keep opening given files names and those files are also unsaved. so I am pretty sure there is some issues with its desktop entry file but I haven't even added those flags for code oss.

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/155577876/53deb3c3-910f-4600-9948-5416837bd3d0)

### Environment

- Linux Distro: ArchLinux
- Linux Version: Linux-lts 6.6.27-1-lts
- Hyprland Version: built from branch v0.38.1-b
- Installation Environment: On A Virtual Machine
- Other info: it is set to auto

### Additional Information

Please inform me if I need to give any other relevant information.

**Comment by kevaldonga** [comment]
same issue here.

**Comment by Igor-Imej** [comment]
https://github.com/prasanthrangan/hyprdots/issues/1315

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/f0660c73-314c-49b0-a97a-7903ee5247dd)

#1315 

https://www.google.com/search?client=firefox-b-d&q=how+to+use+gihub+search+filter
