### ISSUE TITLE
Each time code-oss is opened, 2 new files are created[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by Yakumo-Yukari** [prasanthrangan/hyprdots#1361]
![240421_10h41m40s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/12076232/9b0cbfdd-bf54-4e56-bd08-1e4e6d44713c)
Used to use vscode without any problems, using the new version of hyprdots after a new installation of code-oss In the terminal use `code .` command in the terminal, two windows will open and code-oss will automatically create two new files.

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/issues/1315
