### ISSUE TITLE
Wayvnc doesn't work

### ISSUE THREAD

**Issue by Sitolam** [prasanthrangan/hyprdots#137]
I'm getting this error when I try to run wayvnc `Segmentation fault (core dumped)`

**Comment by prasanthrangan** [comment]
does it work in wayland? could be issue with `wayvnc` or `hyprland` itself.`

**Comment by hqrakiri** [comment]
> does it work in wayland? could be issue with `wayvnc` or `hyprland` itself.`

It's definitely an issue with the config.

**Comment by prasanthrangan** [comment]
hmm, if its working with default auto generated conf, then you could try disabling/enabling the env variables and sourced files.

**Comment by kRHYME7** [comment]
Hello,👋 still got issues regarding this ?

**Comment by Sitolam** [comment]
> Hello,👋 still got issues regarding this ? 

Nope, forgot to close you need to apply a patch to fix the issue
