### ISSUE TITLE
[Bug]: Code Color Theme Not Syncing

### ISSUE THREAD

**Issue by Liu-WeiHu** [prasanthrangan/hyprdots#1370]
## Bug Report
Switching themes code Color theme does not respond
### Description

Manually installed the `[Code_Wallbash.vsix](https://github.com/prasanthrangan/hyprdots/blob/main/Source/arcs/Code_Wallbash.vsix)` extension and installed the latest hyprdots library. When switching themes or switching wallbash I see that the configuration file under `/home/liu/.vscode-oss/extensions/undefined_publisher.wallbash-0.0.1/themes/wallbash-color-theme.json` has changed. But Code does not refresh the theme. Manually close Code and reopen Code to get the appropriate theme. It seems that the script is missing the step of restarting Code.

### Steps to Reproduce

1. ./install.sh
2. Manually installing the [Code_Wallbash.vsix](https://github.com/prasanthrangan/hyprdots/blob/main/Source/arcs/Code_Wallbash.vsix) extension for Code
3. Switch topics or wallbash
4. Code has not changed.

### Expected Behavior

When switching themes or wallbash, the Code theme will change.

### Actual Behavior

Code theme has not changed

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux Arch 6.8.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1)
- Installation Environment: Main Hardware

**Comment by Liu-WeiHu** [comment]
> --extensionDevelopmentPath=$HOME/.vscode-oss/extensions/undefined_publisher.wallbash-0.0.1

Thank you. He works.

**Comment by abenezerw** [comment]
> > --extensionDevelopmentPath=$HOME/.vscode-oss/extensions/undefined_publisher.wallbash-0.0.1
> 
> Thank you. He works.

Could you close this if solved. @Liu-WeiHu

**Comment by kRHYME7** [comment]
If anyone here knows how to make an extension or understand how vscode theme extension works feel free to PR.
