### ISSUE TITLE
Problems with the taskbar

### ISSUE THREAD

**Issue by normalnonerealno** [prasanthrangan/hyprdots#1372]
### Description

Firstly, when you turn on game mode/change the theme/hide the panel, the icons of open applications disappear.
Secondly, in some cases, when you try to open the application through the same icons, the panel closes and we return to point 1 :)

### Steps to Reproduce

 1. Turn on game mode/change the theme/hide the panel

 2. Click to randomly application on the doc

### Screenshots

![240423_03h23m49s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/73527191/3169723c-e9b4-437f-a834-5ff8a9107edd)

https://github.com/prasanthrangan/hyprdots/assets/73527191/30ca41cf-2d09-451d-8df4-f5bbce6c2587

https://github.com/prasanthrangan/hyprdots/assets/73527191/d35aeee8-3e67-4318-9e05-e6c1c37326c7

e.g.,

- Linux Distro: ArchLinux
- Linux Version, Linux archlinux 6.8.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 01:47:33 +0000 x86_64 GNU/Linux
- Hyprland Version, Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

- Installation Environment on The Main Hardware,

in the files I only changed the keyboard layout + updated the system to the latest version just in case. By the way, besides this error, the system is amazing, thanks to the author :)
ready to answer any questions

**Comment by kRHYME7** [comment]
can you try waybar without any configuration? plus only the module? The bar is too buggy.

**Comment by kRHYME7** [comment]
Yeah, got this issues too. I guess this is a waybar issue https://github.com/Alexays/Waybar

**Comment by normalnonerealno** [comment]
> Yeah, got this issues too. I guess this is a waybar issue https://github.com/Alexays/Waybar

did you solve this problem? I didn’t find this problem in the Weybar git, and most of it doesn’t have answers there

**Comment by kRHYME7** [comment]
It mostly happened when I use multi monitor. 

https://github.com/Alexays/Waybar/issues/2954
https://github.com/Alexays/Waybar/issues/2777
https://github.com/Alexays/Waybar/issues/2802

**Comment by abenezerw** [comment]
i feel like i also get this issue sometimes, but not as of late. could you reconfirm if this was solved upstream and close this as solved if so. @normalnonerealno

**Comment by normalnonerealno** [comment]
> i feel like i also get this issue sometimes, but not as of late. could you reconfirm if this was solved upstream and close this as solved if so. @normalnonerealno
tbh, i really forgot about it. It just solved when i update system by itself, thx to the autor
