### ISSUE TITLE
[Feature Request]: preserve and restore hypr.theme

### ISSUE THREAD

**Issue by tryprncp** [prasanthrangan/hyprdots#1376]
### Description

I have a relatively small display so the default theme isnt suitable for me so i always modify hypr.theme file of each hyde theme to suit what i like such as gaps_in, gaps_out, blur etc. it would be very nice if it is preserved and not overridden after an update

**Comment by kRHYME7** [comment]
how about overwriting it in your userprefs.conf? I got a small monitor too.

**Comment by prasanthrangan** [comment]
yup, you can already userprefs.conf...as it wont overwritten

**Comment by tryprncp** [comment]
@kRHYME7 @prasanthrangan can  you guys show me how to do that plss. it would be very helpful

**Comment by kRHYME7** [comment]
@tryprncp

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/14e4aa83-cfdf-481e-9aaa-faf64174af8e)


https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

Will close this for now.
