### ISSUE TITLE
[Bug]: Spotify Crashes and Restarts When Changing Theme or Wallpaper

### ISSUE THREAD

**Issue by sandibi13** [prasanthrangan/hyprdots#1380]
### Description

When attempting to change the theme or wallpaper, Spotify consistently crashes and restarts. Additionally, after this occurrence, the Spotify logo disappears from the waybar. This issue severely disrupts the user experience and makes it challenging to customize the desktop environment without encountering interruptions in Spotify's functionality.

### Steps to Reproduce

1. Launch Spotify
2. While Spotify is running change the theme or walpaper

### Expected Behavior

Expected Spotify to remain operational and stable when changing the theme or wallpaper on the Linux distribution. Specifically, I anticipated that the application would not crash or restart during these customization processes. Additionally, I expected the Spotify logo to persistently appear in the waybar, indicating normal functionality and integration with the desktop environment.

### Actual Behavior

Upon attempting to change the theme or wallpaper on the Linux distribution, Spotify crashes and restarts intermittently. Additionally, following this occurrence, the Spotify logo disappears from the waybar, indicating a disruption in the application's stability and integration with the desktop environment.

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/104856187/ab30381e-48cf-4259-a197-520074f1833c)

### Environment

- Linux Distro: ArchLinux
- Linux Version: 6.8.7-arch1-1
- Hyprland Version: v0.39.1
- Installation Environment: On The Main Hardware
- Other info: 1920x1080 @ 60Hz

### Additional Information

Encountered this problem after utilizing specificity to style and customize Spotify's appearance. It appears that the issue may be related to these customizations, as the crashes and restarts only occur when attempting to change the theme or wallpaper on the Linux distribution.

**Comment by kRHYME7** [comment]
It's not crashes but spicetify-CLI will restart Spotify  spawning it to your current workspace

For now your can disable this behavior by not having the colors dynamic on the go 

Remove this lines for now 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/6cfe739a-3c89-4e99-8217-cbb0e9664f5a)
