### ISSUE TITLE
[Bug]: install script stops after gpu detected

### ISSUE THREAD

**Issue by dayv21** [prasanthrangan/hyprdots#1389]
## running the install script on a minimal install of arch linux stops after my gpu is detected (amd)

No error message just finishes the script

**Comment by Skerse** [comment]
There was already a recent issue made about this.. : https://github.com/prasanthrangan/hyprdots/issues/1378

Also the latest commit fixed this: https://github.com/prasanthrangan/hyprdots/commit/2416433ab14215bf8f41d7269048afbda2b38346

**Comment by dayv21** [comment]
> This should be fixed. Please ` git pull ` then run the installation

Ty <3 I didn't see the issue sorry
