### ISSUE TITLE
kitty-0.28.1-1-x86_64.pkg.tar.zst failed to download

### ISSUE THREAD

**Issue by DIMFLIX-OFFICIAL** [prasanthrangan/hyprdots#139]
![изображение](https://github.com/prasanthrangan/hyprdots/assets/112165977/77992b08-e255-4ca7-aafc-3e708e0757d6)

**Comment by DIMFLIX-OFFICIAL** [comment]
How to do it? I am new to linux

**Comment by DIMFLIX-OFFICIAL** [comment]
How to do it? I am new to linux

**Comment by T-Crypt** [comment]
You need to update your mirrors config. 

/etc/pacman.d/mirrorlist

And uncomment mirrors you would like to use. Then update your packages or trying downloading again 

sudo pacman -Syyu (forces package list refresh) 

https://wiki.archlinux.org/title/mirrors

**Comment by prasanthrangan** [comment]
Updating the mirrors should fix this issue, closing this as this is old... please reopen is required!
