### ISSUE TITLE
[Bug]: Waybar and kitty Theme Not Syncing 

### ISSUE THREAD

**Issue by Asthestarsfalll** [prasanthrangan/hyprdots#1394]
After switching wallpapers, waybar theme remains unchanged. Need to mannualy reload waybar. But switching theme works well. kitty always keeps unchanged

**Comment by Asthestarsfalll** [comment]
> output for this ? `Hyde version`

```
       ░▒▒▒▒▒▒▒░░░
     ░░▒▒▒▒▒▒░░░░▓▓          ____________
    ░░▒▒▒▒▒░░░░░▓▓        //____________/
   ░░░▒▒▒░░░░░░▓▓     _   _ _     _ ______
   ░░░▒▒▒░░░░░▓▓▓▓▓▓ | | | | |   | |  ___/
    ░░░▒▒░░░░▓▓   ▓▓ | |_| | |__/ /| |_____
     ░░░▒▒░░▓▓   ▓▓   \__  |_____/ |______/
       ░░▒▒▓▓   ▓▓  //____/
 ═════════════════
║Hyde-cli version ║
 ═════════════════
============================================================================================================================
Version: v0.5.0-166-g498860d
Last commit: 498860d Wed Apr 24 18:13:24 2024 +0800
Commit message: 'source /usr/share/hyde-cli/Hyde.zsh'
============================================================================================================================
```

**Comment by kRHYME7** [comment]
Ops are you using the latest commits? 
https://github.com/prasanthrangan/hyprdots/issues/1285

**Comment by kRHYME7** [comment]
We can ignore the error it is unrelated. 

Please provide any outputs when you run ` themeselect.sh ` then choose other theme.

**Comment by Asthestarsfalll** [comment]
> We can ignore the error it is unrelated.
> 
> Please provide any outputs when you run `themeselect.sh` then choose other theme.

```

(process:2833): Rofi-WARNING **: 21:59:13.444: ABI version of plugin: 'emoji.so' does not match: 00000006 expecting: 00000007
:: applying theme :: "Tokyo Night"
:: applying wall :: "/home/czh/.config/hyde/themes/Tokyo Night/wallpapers/cat_lofi_cafe.jpg"
:: deploying Tokyo Night colors :: dark wallpaper detected
```

**Comment by kRHYME7** [comment]
Be sure to tun on wallbash ? ` wallbashtoggle.sh ` 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/fc01cfa4-35e3-46c6-b6d7-5bdebb6588c7)

**Comment by Asthestarsfalll** [comment]
> Be sure to tun on wallbash ? ` wallbashtoggle.sh ` 
> 
> 
> 
> ![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/fc01cfa4-35e3-46c6-b6d7-5bdebb6588c7)
> 
> 

yes I switch to dark

**Comment by kRHYME7** [comment]
Still kitty not working?

To investigate further, please try to see if this file changes after you change wallpapers. 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/73e3c185-837c-49d0-89cb-8b258880b054)

**Comment by Asthestarsfalll** [comment]
I know what happens to kitty. In previous version, the theme.conf was placed in the /themes/theme.conf. So I need to modify the inlude in config.

But waybar remains unchanged when switching wallpapers.  The theme.css changs but kitty does't reload the config. I think it's becuase the style.css don't change.  So this may be a bug?

**Comment by kRHYME7** [comment]
> But waybar remains unchanged when switching wallpapers. The theme.css changs but waybar does't reload the config. I think it's becuase the style.css don't change. So this may be a bug?

style.css won't change because the colors are sourced from theme.css 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/22fab05f-4f93-4374-8100-5df3d604d98f)

Also if you're on the latest commit please check if this line is available. This auto reloads the waybar colors.
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/6e5512fc-e5da-44e9-b335-84b36e011b78)


BTW I don't think you need to modify kitty configuration. How did you update your configs?

**Comment by kRHYME7** [comment]
I see,  unfortunately, I couldn't help you much as of this moment, as I can't trace what's happening in your fork.  But try to start debugging this scripts `  wbarconfgen.sh wbarstylegen.sh `. 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/0792c3c6-20ad-4010-b900-12c9b56dbd75)

I would greatly suggest trying to clean up your fork and add some of your personal changes bit by bit.  

Didn't get these errors as I'm just following the latest commits using the CLI.

**Comment by Asthestarsfalll** [comment]
Thank you for your helps!
