### ISSUE TITLE
[Feature Request]: Cursor theming support for flatpak apps

### ISSUE THREAD

**Issue by zeerayne** [prasanthrangan/hyprdots#1395]
### Description

Some flatpak apps (i.e. Spotify, Obsidian) do not follow cursor theme without additional settings. Looks like adding these settings will improve user experience. Wanted to provide screenshots, but cursor is not a part of screenshot :)

### Use Case

For more smooth experience it is a good idea for all flatpak apps have same cursor as set up in system theme

### Proposed Solution

Looks like this is sufficient
```sh
flatpak --user override --filesystem=$HOME/.icons/:ro
```

But also this override can be added if someone decides to use system-installed cursors
```sh
flatpak --user override --filesystem=/usr/share/icons/:ro
```

### Alternatives

I didn't find any alternative solutions.

**Comment by kRHYME7** [comment]
Will be glad to have a PR.

**Comment by zeerayne** [comment]
I will double check on fresh install

**Comment by zeerayne** [comment]
Have checked, and yes - all is working fine
