### ISSUE TITLE
Spicetify does not work correctly and Spotify starts flashing when cursor move across the window

### ISSUE THREAD

**Issue by mikami520** [prasanthrangan/hyprdots#1396]
### Description

```Spicetify``` was applied but the marketplace does not show on the ```Spotify```. Also, when the cursor focus and move across ```Spotify``` window, it started to flick and twinkling.

### Steps to Reproduce

1. Open Terminal
2. Type ```spicetify apply```
3. Open ```Spotify```

### Expected Behavior

```Marketplace``` or extensions widgets are shown

### Actual Behavior

Nothing shows there except ```Home``` and ```Search```

### Screenshots

![240425_15h08m54s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/70731556/964af855-2080-4d81-9536-a9ee03cbc7ce)

### Environment
Linux Distro: ```ArchLinux``` 
Linux Version: ```6.8.7-arch1-1```
Hyprland Version: ```Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759 (props: bump version to 0.39.1)```
Installation Environment: ```On The Main Hardware```
Display Resolution: ```Monitor 1: 3840x2160@144; Monitor 2: 2560x1440@75```

**Comment by kRHYME7** [comment]
Why should the marketplace be expected? marketplace  is not needed to have the Themes working.

You can follow this to have marketplace,

https://github.com/spicetify/spicetify-marketplace/wiki/Installation

**Comment by mikami520** [comment]
> Why should the marketplace be expected? marketplace is not needed to have the Themes working.
> 
> You can follow this to have marketplace,
> 
> https://github.com/spicetify/spicetify-marketplace/wiki/Installation

Thanks for your help. Now, after I install some extensions to the spicetify, the icon for spotify become disappeared at the waybar. Do you know how to solve this issue?

![240425_21h24m31s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/70731556/1c6c6126-1d40-42ae-9256-7acd7ac1b03a)

**Comment by kRHYME7** [comment]
@mikami520  
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/2073eb72-b6ed-4574-badd-1542fbe16329)

Notice that the class and initial class value becomes blank. This seemed to be spotify or the spicetify client not showing the spotify  class. https://www.reddit.com/r/hyprland/comments/18sm93h/how_does_waybars_taskbar_find_application_iconi/

The actual behavior that's happening is 
1. When you launch spotify using desktop icon (launcher),   the spotify from /usr/bin/spotify is launch. (which now shows the icons correctly) 
2. When you switch themes/wallpaper/mode `spicetify-cli` handles the relaunching for you which leaves the class/initialclass blank. 
3.  Now the class is blank and waybar now does't know what to show as the class is blank.   

Will close this for now as Hyde cannot fix it but spicetify can.
