### ISSUE TITLE
[Bug]: Vscode params opening custom files

### ISSUE THREAD

**Issue by Felipellira** [prasanthrangan/hyprdots#1397]
### Description

the parameters supplied to vscode open new empty files instead of being used as launch parameters

### Steps to Reproduce

1. Fresh Hyde install
2. Open code

### Expected Behavior

The parameters --ozone-platform-hint=wayland and --disable-gpu should be used as launch parameters

### Actual Behavior

It displays two empty files on code, one called --ozone-platform-hint=wayland and other called  --disable-gpu

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/86257253/bf619502-7561-4996-b573-c5dd476c9507)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: Arch Linux
- Linux Version, output of `uname -a`: `Linux archlinux 6.8.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 x86_64 GNU/Linux`
- Hyprland Version, output of `hyprctl version`: `
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460`
- Installation Environment: Main Hardware

**Comment by kRHYME7** [comment]
Wow! thanks for the notice. It's actually a pinned issue. https://github.com/prasanthrangan/hyprdots/issues/1315
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/62cd84c0-0e60-4bdb-8bd9-1bf816621cae)
