### ISSUE TITLE
[Bug]: system kind of broke after updating HyDe

### ISSUE THREAD

**Issue by Lol-Lap** [prasanthrangan/hyprdots#1398]
### Description
There is something wrong with the theme.conf file and Rofi and the theme is syncing.

### Steps to Reproduce

1. update HyDe
2. change the theme or don't it will brake after a bit

### Expected Behavior

The system functions normally after the update.

### Actual Behavior

rofi theme is missing, and theme.conf is corrupted

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/120711779/31500e4c-78fa-4c23-93a6-aec4442c5695)
![image](https://github.com/prasanthrangan/hyprdots/assets/120711779/0f354d85-0ec3-4313-bcdb-28521f3d3ab5)
![image](https://github.com/prasanthrangan/hyprdots/assets/120711779/d6aa06a3-536e-4439-aff1-53386d265586)

### Environment

- Linux Distro: ArchLinux
- Linux Version: Linux archlinux 6.8.7-arch1-1
- Hyprland Version: Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)

- Installation Environment: Main Hardware
- Other info: Monitor eDP-1 (ID 0):
	1920x1080@59.99900 at 0x0
	description: BOE 0x0810
	make: BOE
	model: 0x0810
	serial: 
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 28 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 1920x1080@60.00Hz 1920x1080@48.00Hz 1680x1050@60.00Hz 1280x1024@60.00Hz 1440x900@60.00Hz 1280x800@60.00Hz 1280x720@60.00Hz 1024x768@60.00Hz 800x600@60.00Hz 640x480@60.00Hz

**Comment by kRHYME7** [comment]
Already read this ? https://github.com/prasanthrangan/hyprdots/issues/1285 

Check this out https://github.com/prasanthrangan/hyprdots/pull/1282

To narrow down the problem, please run ` Hyde cache rebuild ` might solve the color issues. 

To fix the themes install is again ` Hyde theme patch ` 

The scripts are moved so you may need to remove the old scripts directory
`
 ~/.config/hyprdots/
~/.config/hypr/scripts
~/.config/hypr/wallbash
`
 
 Will suggest to do a fresh install of Hyde by ` ./install.sh `

**Comment by Lol-Lap** [comment]
> Already read this ? #1285
> 
> Check this out #1282
> 
> To narrow down the problem, please run `Hyde cache rebuild` might solve the color issues.
> 
> To fix the themes install is again `Hyde theme patch`
> 
> The scripts are moved so you may need to remove the old scripts directory `~/.config/hyprdots/ ~/.config/hypr/scripts ~/.config/hypr/wallbash`
> 
> Will suggest to do a fresh install of Hyde by `./install.sh`

Thanks that fixes it.
