### ISSUE TITLE
Can't start KDE related apps.

### ISSUE THREAD

**Issue by tellmeY18** [prasanthrangan/hyprdots#14]
I'm unable to launch any kde related apps currently. I could open it when I had run the script and configured it initially. The desktop my secondary PC, has no issues running them. But I'm receiving 

**_dolphin: error while loading shared libraries: libKF5CoreAddons.so.5: cannot open shared object file: No such file or directory_**

While trying to launch Dolphin and 

**_kf.windowsystem: Cannot use KWindowSystem without a QGuiApplication
[1]    42673 segmentation fault (core dumped)  lanshare_**

this error for opening other QT apps. 

**_konsole: error while loading shared libraries: libKF5CoreAddons.so.5: cannot open shared object file: No such file or directory_**

**_kdeconnect-app: error while loading shared libraries: libKF5CoreAddons.so.5: cannot open shared object file: No such file or directory_**

**Comment by prasanthrangan** [comment]
Hi,

Did it stop working after system update? I've not faced this error so is there any steps to replicate this?
The error message looks like some missing dependency, so can you please try reinstalling the kcoreaddons package --> https://archlinux.org/packages/extra/x86_64/kcoreaddons/

**Comment by prasanthrangan** [comment]
no updates
