### ISSUE TITLE
[Bug]: Streched out text in Network dialog

### ISSUE THREAD

**Issue by kevaldonga** [prasanthrangan/hyprdots#1404]
## Bug Report
I having this is issue where text is streched out in network dialog.
here is the screenshot of it
This type of text is also shown at start up in sddm.

### Screenshots
![image](https://github.com/prasanthrangan/hyprdots/assets/100512807/4d280e20-10d1-4937-8cd7-564c0b77d7c7)

### Environment
- Linux Distro: ArchLinux
- Linux Version: Linux archlinux 6.8.7-arch1-2
- Hyprland Version : Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
- Installation Environment: On The Main Hardware

### Additional Information

I have intel card (don't know if that's relevant)

**Comment by dieBakterie** [comment]
That's the trays fault not HyDE. It's an upstream problem.

**Comment by kevaldonga** [comment]
have you ever faced this ?

**Comment by dieBakterie** [comment]
Yeah for the Bluetooth one two sadly i don't know what i did wring to get it stretched

**Comment by kevaldonga** [comment]
mine was already like this. is there a active thread on this issue that I can follow ?

**Comment by dieBakterie** [comment]
There is no "fix" for it, as far as i know.

**Comment by kRHYME7** [comment]
@kevaldonga https://github.com/prasanthrangan/hyprdots/issues/236 Here's the duplicate for this issue. Best way to fix it is to find another solution than nm-applet.
