### ISSUE TITLE
Solution, "open with" problem, with Dolphin.

### ISSUE THREAD

**Issue by MiniMarmotaVorazYT** [prasanthrangan/hyprdots#1406]
If someone has the problem with "open with" on Dolphin.
First: sudo pacman -S  archlinux-xdg-menu
and XDG_MENU_PREFIX=arch- kbuildsycoca6

Sorry, I dont speak English very well. But in this reddit is expleined:
https://www.reddit.com/r/kde/comments/1bd313p/dolphin_not_recognizing_file_associations/

**Comment by ashu-otaku** [comment]
thank you, so much, it helped me a lot

**Comment by simplemachine-zz** [comment]
I did this solution but it didn't work for me but I renamed a file called arch-applications.menu to applications.menu and it's working now. It is located in the /etc/xdg/menus directory.

**Comment by rubiin** [comment]
this works:

First try running this command
kbuildsycoca6 --noincremental

If it does print this output -> "applications.menu" not found in QList("~/.config/menus", "/etc/xdg/menus"), you will need to get this file.
To get the applications.menu file, install this package
sudo pacman -Sy archlinux-xdg-menu

Then run this command to generate the file
sudo update-desktop-database

As the file name differs you need to change the file name
cd /etc/xdg/menus

ls

expected output -> "arch-applications.menu"
sudo mv arch-applications.menu applications.menu

Then run again this command and it should work fine
kbuildsycoca6 --noincremental


Tested on my machine as well

**Comment by rubiin** [comment]
> For me with this method after a while, dolphin still has the "open with" problem.
> 
> I found a solution that work for me in this reddit post: [reddit.com/r/kde/comments/1bd313p/comment/l1jinyf/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button](https://www.reddit.com/r/kde/comments/1bd313p/comment/l1jinyf/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
> 
> kbuildsycoca6 --noincremental
> 
> If it does print this output -> "applications.menu" not found in QList("~/.config/menus", "/etc/xdg/menus"), you will need to get this file
> 
> sudo pacman -Sy archlinux-xdg-menu sudo update-desktop-database cd /etc/xdg/menus ls expected output -> "arch-applications.menu" sudo mv arch-applications.menu applications.menu

This works, tested on my machine as well

**Comment by kRHYME7** [comment]
Comment 1 works but don't persist across reboots

To persist any changes


NOTE!  This file: `  /etc/xdg/menus/arch-applications.menu ` should exist first
copy it to this directory
` cp /etc/xdg/menus/*applications.menu ~/.config/menus/applications.menu `

if this file does not exist, install ` sudo pacman -S archlinux-xdg-menu `
then run ` kbuildsycoca6 ` 


this will give you errors like this 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a5f19c30-9434-4b94-9b2c-244363894423)

now just do this ` 
 cp /etc/xdg/menus/*applications.menu ~/.config/menus/applications.menu 
 `

**Comment by rubiin** [comment]
This can be closed i guess

**Comment by kRHYME7** [comment]
Will pin this for a month I guess

**Comment by ashu-otaku** [comment]
> Comment 1 works but don't persist across reboots
> 
> To persist any changes
> 
> NOTE! This file: ` /etc/xdg/menus/arch-applications.menu` should exist first copy it to this directory `cp /etc/xdg/menus/*applications.menu ~/.config/menus/applications.menu`
> 
> if this file does not exist, install `sudo pacman -S archlinux-xdg-menu` then run `kbuildsycoca6`
> 
> this will give you errors like this ![image](https://private-user-images.githubusercontent.com/53417443/326664063-a5f19c30-9434-4b94-9b2c-244363894423.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODU3MTAsIm5iZiI6MTcxNDQ4NTQxMCwicGF0aCI6Ii81MzQxNzQ0My8zMjY2NjQwNjMtYTVmMTljMzAtOTQzNC00Yjk0LTliMmMtMjQ0MzYzODk0NDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDEzNTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZWIxZTE4NjM0MjdhNzU3YTE5NDdhNTMwNTRhOTUyZDBhNDJmNzQ5YTM2NzU0YTY3MzA5NDJhODQ1ZWZjOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7WHURsFy0_Z_7jGId7gEJfaP06rBCFqGQn2jSHvYoRg)
> 
> now just do this ` cp /etc/xdg/menus/*applications.menu ~/.config/menus/applications.menu `

I just create a symlink for that with this command:
sudo ln -sf arch-applications.menu applications.menu

**Comment by kRHYME7** [comment]
Hello, I tried to remove ` archlinux-xdg-menu` just to see what really are the essential packages needed in fixing this.

Then just tried to fetch the ` application.menu ` file from kde repo.

` 
curl -L https://raw.githubusercontent.com/KDE/plasma-workspace/master/menu/desktop/plasma-applications.menu -o $HOME/.config/menus/applications.menu
 `

This works on my system. Can anyone here confirm

**Comment by allen7731** [comment]
I found this in the Arch Linux forum [](https://bbs.archlinux.org/viewtopic.php?pid=2167945#p2167945) https://bbs.archlinux.org/viewtopic.php?pid=2167945#p2167945
![Pasted image](https://github.com/prasanthrangan/hyprdots/assets/129892225/67233f25-8947-488a-b35d-c928c0b537ca)

**Comment by simplemachine-zz** [comment]
> Hello, I tried to remove ` archlinux-xdg-menu` just to see what really are the essential packages needed in fixing this.
> 
> Then just tried to fetch the `application.menu` file from kde repo.
> 
> ` curl -L https://raw.githubusercontent.com/KDE/plasma-workspace/master/menu/desktop/plasma-applications.menu -o $HOME/.config/menus/applications.menu`
> 
> This works on my system. Can anyone here confirm

Yes. It works.

1- `mkdir $HOME/.config/menus/`

2- `curl -L https://raw.githubusercontent.com/KDE/plasma-workspace/master/menu/desktop/plasma-applications.menu -o $HOME/.config/menus/applications.menu`

3 - `kbuildsycoca6`

Clean solution!

**Comment by prasanthrangan** [comment]
Hey guys, I've uninstalled `archlinux-xdg-menu` and `kservice5`, just having the applications.menu config file resolves it.

**Comment by Xecty** [comment]
Just to add to the conversation, I added this to my userprefs.conf and it worked without having to install anything or downgrade any packages.

env = XDG_MENU_PREFIX,arch-

**Comment by BrayanLope5** [comment]
Can confirm, just using the following steps worked for me with a kde installation and a hyprland installation in the same system.

1- `mkdir $HOME/.config/menus/`
2- `curl -L https://raw.githubusercontent.com/KDE/plasma-workspace/master/menu/desktop/plasma-applications.menu -o $HOME/.config/menus/applications.menu`

To make it easier on myself, after downloading, I added the file to my dot files so that it's automatically synced. This is not related to the problem, just thought I mentioned it.

**Comment by kirkserverhl** [comment]
i similarly  put a bash script in my hyprland.conf file  so that when I change machines or break my configuration its in the dotfiles, cheers

**Comment by nate-moo** [comment]
> Comment 1 works but don't persist across reboots
> 
> To persist any changes
> 
> NOTE! This file: ` /etc/xdg/menus/arch-applications.menu` should exist first copy it to this directory `cp /etc/xdg/menus/*applications.menu ~/.config/menus/applications.menu`
> 
> if this file does not exist, install `sudo pacman -S archlinux-xdg-menu` then run `kbuildsycoca6`
> 
> this will give you errors like this ![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a5f19c30-9434-4b94-9b2c-244363894423)
> 
> now just do this (User Level)` ln -fs /etc/xdg/menus/*applications.menu ~/.config/menus/applications.menu `
> 
> Edit: use symlinks

You are a godsend, I finally after at least 2 hours of fighting, digging, and trying everything, this symlink was the one that finally actually worked.

Thank you much, Nate

**Comment by rnavxn** [comment]
Does these solutions persist. Or I have add this ```kbuildsycoca6``` to exec-onec?

**Comment by kRHYME7** [comment]
You only need the file in your `.config`
