### ISSUE TITLE
[Bug]: Discord wall bash colors make certain elements invisible

### ISSUE THREAD

**Issue by NoahPsight** [prasanthrangan/hyprdots#1407]
https://github.com/prasanthrangan/hyprdots/assets/120606151/e44be284-3b73-4083-bd45-deb5893f352a

Video demonstrating

**Comment by prasanthrangan** [comment]
please try copying this [discord.txt](https://github.com/prasanthrangan/hyprdots/files/15149886/discord.txt) to `~.config/hyde/wallbash/Wall-Ways/discord.dcol`

**Comment by kRHYME7** [comment]
@prasanthrangan  This looks way better on my end  😁 Thanks

**Comment by prasanthrangan** [comment]
> @prasanthrangan This looks way better on my end 😁 Thanks

cool, I'll commit this!
