### ISSUE TITLE
[Bug]: Unable to set default applications for image, video, text... files

### ISSUE THREAD

**Issue by YassirEH** [prasanthrangan/hyprdots#1419]
### Description

I already installed and used Hyprdots on EndeavourOS, but I wanted to wipe my SSD and install it again, I installed EndeavourOS with no DE, cloned https://github.com/prasanthrangan/hyprdots, and ran the install script, everything seems to work except when i try to open files (whether it's .png .jpg .mp4 .txt, anything) it asks which application should i run the file with, i tried to set the default apps but nothing works it keeps asking for the default app each time i try to open a file, but i don't have a problem browsing and opening folders with Dolphin it works as expected, tried setting the default apps with [selectdefaultapplication-git ](https://aur.archlinux.org/packages/selectdefaultapplication-git) my mimeapps.list is in screenshots as well as a video example.

 
### Steps to Reproduce

1. Install Hyprdots on a clean EndeavourOS 

### Expected Behavior

Open the files using the default app

### Actual Behavior

Choosing the default apps every time

### Screenshots

![240430_21h03m13s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/141313218/4943551f-bd37-450b-a482-aa22e2d8e9ad)

https://github.com/prasanthrangan/hyprdots/assets/141313218/cbcc3964-48eb-4b16-8475-e11db964c774

### Environment

- Linux Distro: EndeavourOS
- Linux Version, output of `uname -a`: Linux Yassirs-EnOS 6.8.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 28 Apr 2024 15:59:47 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460
- Installation Environment: On The Main Hardware

Thank you.

edit: added video example.

**Comment by kRHYME7** [comment]
See pinned issue.

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/issues/1406
