### ISSUE TITLE
This script breaks theming for KDE Plasma.

### ISSUE THREAD

**Issue by Abdulsarhan** [prasanthrangan/hyprdots#1420]
I don't use Hyprland full-time. 
I mostly use KDE plasma. 
After installing this script, all of my GTK apps now have the Catpuccin theme. 
The problem is that I can't use Plasma's Global theme changer to change the theme back in my GTK apps. 
I even tried changing the theme that I use in the GTK config files but it still doesn't work. 

EDIT: To be clear, I don't mind the fact that I may have to change my theme back when I go back to KDE Plasma after using Hyprland. My issue is that it's literally impossible to change it back.

**Comment by kRHYME7** [comment]
Can you change your gtk related themes using `gsetting` ?

**Comment by kRHYME7** [comment]
Can you change your gtk related themes using `gsettings` ?

**Comment by Skerse** [comment]
Did you read this before you installed HyDE?

> While installing HyDE alongside another [DE](https://wiki.archlinux.org/title/Desktop_environment)/[WM](https://wiki.archlinux.org/title/Window_manager) should work, due to it being a heavily customized setup, it **will** conflict with your [GTK](https://wiki.archlinux.org/title/GTK)/[Qt](https://wiki.archlinux.org/title/Qt) theming, [Shell](https://wiki.archlinux.org/title/Command-line_shell), [SDDM](https://wiki.archlinux.org/title/SDDM), [GRUB](https://wiki.archlinux.org/title/GRUB), etc. and is at your own risk.

This is mostly meant to be used by itself, and I think there is no way we can fix that on our end.

**Comment by Abdulsarhan** [comment]
Okay, I managed to fix it for everything. For some reason, plasma doesn't change the 

> Can you change your gtk related themes using `gsettings` ?
> 
> for each theme the script invokes some `gsettings` command ![image](https://private-user-images.githubusercontent.com/53417443/327056876-e11b1991-f043-42c1-955f-59d3e2e85b9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NDQ5MjUsIm5iZiI6MTcxNDU0NDYyNSwicGF0aCI6Ii81MzQxNzQ0My8zMjcwNTY4NzYtZTExYjE5OTEtZjA0My00MmMxLTk1NWYtNTlkM2UyZTg1YjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDA2MjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZGZlYzIyMTY1YWFkYTZjNmE4ZDUxNjM5YjlhNjExMTQyNDM3MzE2Yzk4M2VkYTA3MDIwZmNkNzc5NTUxYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ly6MaiHB3ZwP0y3LhbYpI_97gcRn85AgB9K27nFX2h4)
> 
> Now I did not dig deeper, but there are files related to gtk, try to remove these then try to to change themes on kde using the global theme changer. (It would be helpful if we would know how kde handles gtk) ![image](https://private-user-images.githubusercontent.com/53417443/327057251-1d9cb6fa-aa07-4437-873e-37c9a2125139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NDQ5MjUsIm5iZiI6MTcxNDU0NDYyNSwicGF0aCI6Ii81MzQxNzQ0My8zMjcwNTcyNTEtMWQ5Y2I2ZmEtYWEwNy00NDM3LTg3M2UtMzdjOWEyMTI1MTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDA2MjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NzY0NTZiYWI4Y2QzOTAwNTRiOWQ3NDZmNDRiODMxOTBlN2ZkZGRhNGUxNzljNzMxODM0OTYyYTY0MjZkN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OKWb_CkrjICk3GNoEL9VP6W6D2YHEDIwJziO1zrH7vM)

Thank you, [kRHYME7](https://github.com/kRHYME7).

I ran the following commands and fixed it: 
gsettings set org.gnome.desktop.interface icon-theme 'Breeze-Dark'
gsettings set org.gnome.desktop.interface gtk-theme 'Breeze-Dark'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

**Comment by Abdulsarhan** [comment]
Also, I will be reporting this to KDE because a theme changer should change the theme.
