### ISSUE TITLE
[Bug]: GTK Flatpak apps are not themed

### ISSUE THREAD

**Issue by GeoBoi254** [prasanthrangan/hyprdots#1421]
### Description

GTK apps on Flatpak aren't theme are transparent for some reason.

### Steps to Reproduce

1. Open an app like Flatseal

### Expected Behavior

App should respect the theme selected.

### Actual Behavior

They do not have any theme and are transparent

### Screenshots
![240501_18h06m51s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111936622/49ce19bd-8ce6-4b70-8126-195dfe082d71)

**Comment by kRHYME7** [comment]
can you try to change the theme?

**Comment by GeoBoi254** [comment]
I've tried to change themes but they don't seem to work.

**Comment by GeoBoi254** [comment]
I found the issue, it only applies the wallbash theme. 
![240501_20h19m06s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111936622/2dc4f094-aefa-45f2-a6f4-c0b0b48c786e)

**Comment by kRHYME7** [comment]
what wallbash mode is this ? 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/aeb4a80f-b1fe-4b61-b5e0-4ac0ef995131)

Can you also try to provide outputs from ` themeselect.sh ` ?

**Comment by kRHYME7** [comment]
To fix theme related issues run ` Hyde theme patch ` then try to select a theme this way it will renew the files for you

**Comment by GeoBoi254** [comment]
Here are screenshots with and without wallbash applied.
![240501_23h53m08s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111936622/cfca1cb2-0455-4ad6-a17a-a77e2fc0cb01)
![240501_23h52m49s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111936622/66612120-beb6-4ffc-98ac-7d8542ff97ba)

**Comment by Luiz0047** [comment]
I'm facing this issue as well
