### ISSUE TITLE
[Bug]: Volume resets when refreshing browser window

### ISSUE THREAD

**Issue by ConquereRofEternaLNight** [prasanthrangan/hyprdots#1423]
### Description

everytime I increase the volume to max(upto 153) and refresh the browser window it automatically goes back to 100 and volume decreases

### Expected Behavior

It should stay lock to the specific volume setting

### Actual Behavior

resets to 100

**Comment by abenezerw** [comment]
> ## Bug Report
> ### Description
> 
> everytime I increase the volume to max(upto 153) and refresh the browser window it automatically goes back to 100 and volume decreases
> ### Expected Behavior
> 
> It should stay lock to the specific volume setting
> ### Actual Behavior
> 
> resets to 100

what browser are you using and do you still have this issue

**Comment by kRHYME7** [comment]
We don't have any daemon/service that is running and can cause this issue. Try to check your browser.
