### ISSUE TITLE
[Custom]: Window opacity doesn't change for apps such as postman, zoom

### ISSUE THREAD

**Issue by KitsuneKode** [prasanthrangan/hyprdots#1424]
For certain apps like libreoffice, postman, zoom, mongobd-compass,opencomic, the windowrule opacity isn't applied

I  actually tried 
`windowrulev2 = opacity 0.80 0.80,class:^(postman-bin)$`
`windowrulev2 = opacity 0.80 0.80,class:^(libreoffice)$`
`windowrulev2 = opacity 0.80 0.80,class:^(us.zoom.Zoom)$`
`windowrulev2 = opacity 0.80 0.80,class:^(mongodb-compass)$`

 But those apps weren't affected by that! I tried to change the opacity values but no changes, 
 Btw I use the flatpak version of zoom as the aur version is broken! 
 
 And I was curious about one more thing: **Does the windowrules.conf file get updated after a fresh installation of applications or do I have to manually add them?**  

![image](https://github.com/prasanthrangan/hyprdots/assets/135751082/1b592d26-0cac-40b4-a392-f37369049d7f)

**Comment by Skerse** [comment]
Are you getting the class name right? Run `hyprctl clients` when the window is open and look at 'initialclass'.

Also i've occasionally had issues with class name not working, title name would also work..

Make sure you put these in `userprefs.conf`. That file will remain the same when updating/restoring HyDE.

**Comment by KitsuneKode** [comment]
> Are you getting the class name right? Run `hyprctl clients` when the window is open and look at 'initialclass'.
> 
> Also i've occasionally had issues with class name not working, title name would also work..
> 
> Make sure you put these in `userprefs.conf`. That file will remain the same when updating/restoring HyDE.


Thanks man, I was getting the class names wrong! @Skerse  bro do u know why are some apps automatically starts on window focus full screen and dont tile as usual hyprland windows does!

**Comment by Skerse** [comment]
> > windowrule=tile,class:^(_class name_)$
> 
> nope didn't work, I tried various kind of rules no difference!
> 
> , I added the flag postman --ozone-platform-hint=wayland then it worked normally, 

Strange, but i guess if forcing wayland fixes it then nice.

> If i wanna add the flag to the app when I wanna start from desktop application menu, where should i add the flag!

I guess you *could* edit the desktop file which likely is in `/usr/share/applications` but before you do that, see if you can make a `*name*-flags.conf` file like we do with `code-flags.conf` for vscode and place that flag in there, usually that's pretty common with chromium/electron based applications from what i see.

**Comment by KitsuneKode** [comment]
> > > windowrule=tile,class:^(_class name_)$
> > 
> > 
> > nope didn't work, I tried various kind of rules no difference!
> > , I added the flag postman --ozone-platform-hint=wayland then it worked normally,
> 
> Strange, but i guess if forcing wayland fixes it then nice.
> 
> > If i wanna add the flag to the app when I wanna start from desktop application menu, where should i add the flag!
> 
> I guess you _could_ edit the desktop file which likely is in `/usr/share/applications` but before you do that, see if you can make a `*name*-flags.conf` file like we do with `code-flags.conf` for vscode and place that flag in there, usually that's pretty common with chromium/electron based applications from what i see.


I was also hoping for that `-flags.conf` file but i guess postman doesnot have that! 

I actually search for all postman configs and found a file in `~/.config/Postman/window` there there was 4 json obj where maximize was set to true by default, changing the last obj maximize value to false fixed mine!

**Comment by KitsuneKode** [comment]
Closing the issue as the major problems are solved! If any other related problem comes up, i will reopen this!
