### ISSUE TITLE
[Enhancement]: Systemupdate error

### ISSUE THREAD

**Issue by dieBakterie** [prasanthrangan/hyprdots#1426]
### Description

`systemupdate.sh` doesn't work correctly when no flatpaks installed and therefore flatpak isn't enabled at all.

### Steps to Reproduce

1. Have no flatpaks installed and flatpak not activated.
2. Use the script, Waybar module or terminal, doesn't matter.
3. Script fails at line 5, 'cause no flatpaks are installed.

### Expected Behavior

Script Updates the packages and installed them.

### Actual Behavior

Script fails after Updating without installing them.

### Environment

Main System, Kernel 6.8.8(zen)

### Proposed Solution

Import the pkg_installed function from `globalfunction.sh` and import it in Line 12 and add in now Line 13 in the cmd for Updating flatpaks.

**Comment by kRHYME7** [comment]
@dieBakterie  change line 12. 

```
export -f pkg_installed
fpk_exup="pkg_installed flatpak && flatpak update || exit 1"

```

Please confirm if this works

**Comment by dieBakterie** [comment]
Thanks i'll try this later.

**Comment by Skerse** [comment]
I'm confused. i just installed flatpak, installed no flatpak packages, then received no error at all?

![image](https://github.com/prasanthrangan/hyprdots/assets/139541046/7640395e-692f-4f4b-89a1-0c010f52271a)

**Comment by dieBakterie** [comment]
Yeah if you don't activate flatpak and Install No you don't get any error. For me it says `error command flatpak doesn't exist`

**Comment by dieBakterie** [comment]
> @dieBakterie change line 12.
> 
> ```
> export -f pkg_installed
> fpk_exup="pkg_installed flatpak && flatpak update"
> ```
> 
> Please confirm if this works
> 
> edit : Remove the exit 1 it is for testing.

`#!/usr/bin/env bash

# Check release
if [ ! -f /etc/arch-release ] ; then
    exit 0
fi

# source variables
scrDir=$(dirname "$(realpath "$0")")
source "$scrDir/globalcontrol.sh"
get_aurhlpr
export -f pkg_installed
fpk_exup="pkg_installed flatpak && flatpak update"

# Trigger upgrade
if [ "$1" == "up" ] ; then
    trap 'pkill -RTMIN+20 waybar' EXIT
    command="
    fastfetch
    $0 upgrade
    ${aurhlpr} -Syu
    $fpk_exup
    read -n 1 -p 'Press any key to continue...'
    "
    kitty --title systemupdate sh -c "${command}"
fi

# Check for AUR updates
aur=$(${aurhlpr} -Qua | wc -l)
ofc=$( (while pgrep -x checkupdates > /dev/null ; do sleep 1; done) ; checkupdates | wc -l)

# Check for flatpak updates
if pkg_installed flatpak ; then
    fpk=$(flatpak remote-ls --updates | wc -l)
    fpk_disp="\n󰏓 Flatpak $fpk"
else
    fpk=0
    fpk_disp=""
fi

# Calculate total available updates
upd=$(( ofc + aur + fpk ))

[ "${1}" == upgrade ] && printf "[Official] %-10s\n[AUR]      %-10s\n[Flatpak]  %-10s\n" "$ofc" "$aur" "$fpk" && exit

# Show tooltip
if [ $upd -eq 0 ] ; then
    upd="" #Remove Icon completely
    # upd="󰮯"   #If zero Display Icon only
    echo "{\"text\":\"$upd\", \"tooltip\":\" Packages are up to date\"}"
else
    echo "{\"text\":\"󰮯 $upd\", \"tooltip\":\"󱓽 Official $ofc\n󱓾 AUR $aur$fpk_disp\"}"
fi
` There is no `exit 1` in here

**Comment by kRHYME7** [comment]
> ```
> export -f pkg_installed
> fpk_exup="pkg_installed flatpak && flatpak update"
> 
> ```

**Comment by Skerse** [comment]
> > ```
> > export -f pkg_installed
> > fpk_exup="pkg_installed flatpak && flatpak update"
> > ```
> 
> This check on Line 12 is pretty much it ig?

Yeah, but it's not working apparently.

**Comment by dieBakterie** [comment]
For me it works

**Comment by rubiin** [comment]
can be closed then as it seems solved

**Comment by kRHYME7** [comment]
The script is fixed now?

**Comment by dieBakterie** [comment]
Yeah would be nice, one script less i changed and need to update in my fork manually.

**Comment by dieBakterie** [comment]
Yeah would be nice If you add those fixes upstream.
