### ISSUE TITLE
[Bug]: Wallbash not working for GTK 3 and 4 apps 

### ISSUE THREAD

**Issue by Enigma1309** [prasanthrangan/hyprdots#1430]
Recent commits reegarding gtk theming f67cddf4200dd91ab5daf9d723823cd2b129c967 are not working on the machine...

- continuation of https://github.com/prasanthrangan/hyprdots/commit/f67cddf4200dd91ab5daf9d723823cd2b129c967#commitcomment-141442790

- the apps are having a slightly pink tinted color text (even if i choose any wallpaper) and there's no spacing between context menu items
![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/60e84901-5a52-4564-ae78-7e6393ea3e11)

- some gtk variables are wrong and applications throws up a bunch of theming error at launch..
![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/9e927500-f940-4a14-a869-e160e04d704b)

- i've reinstalled the dots but the problem persists

**Comment by prasanthrangan** [comment]
Oh, this was already fixed in `acb343d`, could you try with the latest commit (if you have not tried already).

To investigate further, try to watch this file while changing the wallpaper -
```
watch -n 0.1 "head ~/.themes/Wallbash-Gtk/gtk-3.0/gtk.css"
```
and let me know if the variables are updated as expected.

**Comment by Enigma1309** [comment]
> watch -n 0.1 "head ~/.themes/Wallbash-Gtk/gtk-3.0/gtk.css"

i don't see the file updating :(

i'm going the destructive way 😈

i've nuked the themedir but no luck :( 

---

I've tried running the wallbashtoggle.sh in terminal but recieved no error...(but got stuck at vscode installing extension ..)

but it did flashed log for a split second and cleared them, so i tried screen recording and found this

![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/fca9f01a-567f-45a4-9abb-e5ffc4f534d6)

after a bit more inspection i checked the directory permission, it was given to the another user (i have a multi user pc), more specifically the first root user i created (they have incremental id  afaik)

the themes directory was under my permission but,
![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/ac73cf37-b3e8-4905-9cf4-6b83f9d72165)

the specific files were not under mine permission...
idk if it's the script bug but whatsoever...

so i ran `sudo chown -R user:user ~/.themes` ( replace user with your username in case anyone encountered the same issue)

nevertheless the issue got solved...

Thank you
