### ISSUE TITLE
[Bug]: After installing hyprdots, the wallpaper does not appear on the desktop

### ISSUE THREAD

**Issue by Erubarm** [prasanthrangan/hyprdots#1431]
### Description

[After installing hyprdots, the wallpaper does not appear on the desktop]

### Steps to Reproduce

1. Installed Arch Linux minimal
2. Launched the hyprland installation
3. After installation, logged in
4. No wallpaper

### Expected Behavior

[I was expecting working wallpapers]

### Actual Behavior

[Gray screen]

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/95746081/07fea3e7-9cb0-4e29-850c-57ae156b7b0d)
![image](https://github.com/prasanthrangan/hyprdots/assets/95746081/1fa27527-f686-4948-9e4a-49a108bbfb15)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [Arch Linux minimal]
- Linux Version, output of `uname -a`: Linux archlinux 6.8.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 28 Apr 2024 15:59:47 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460
- Installation Environment: [On The Main Hardware]

### Description

Hello, I'm new to Hyperland and facing this problem. I hope for your understanding and help in solving this problem. If you need more detailed information, tell me and I will provide it.

**Comment by nicolkrit999** [comment]
I seem to have a similar problem but only if I change the wallpaper. If I change it then logout or reboot then the new one appear. Did you try to turn off the pc completely or to change the wallpaper with another and do a logout?

**Comment by nicolkrit999** [comment]
> Hi, please try changing the wallpaper from terminal -
> 
> ```
> swwwallselect.sh
> ```
> 
> it should give you an output or some errors
> 
> ```
>  swwwallselect.sh
> :: applying wall :: "/home/tittu/.config/hyde/themes/Catppuccin Mocha/wallpapers/hanged_man_tree.jpg"
> :: deploying wallbash colors :: dark wallpaper detected
> ```

Thanks for the amazing dots and constant support from both you and your maintainers. 


In my machine I deleted some files under **~/.config/sww** most notably.

They contained the preview and the link of a .gif that i put in tokyo-night but did not work. Even tough I had a different wallpaper the link was to that gif.

I do not know if this would break something under that I am not seeing, but for now it seems I can change themes and wallpapers very fast and without requiring reboot or login. 

- wall.blur
- wall.dcol
- wall.rofi
- wall.set
- wall.thmb

**Comment by prasanthrangan** [comment]
Thanks, for your support! appreciate it :)

> In my machine I deleted some files under **~/.config/sww** most notably.

oh noo.. thats from the older version... please remove these dirs if it exists - 
```
~/.config/sww
~/.config/hyprdots
~/.cache/hyprdots
```
its now in `~/.config/hyde` and the new cache dir is `~/.cache/hyde`

**Comment by nicolkrit999** [comment]
> Thanks, for your support! appreciate it :)
> 
> > In my machine I deleted some files under **~/.config/sww** most notably.
> 
> oh noo.. thats from the older version... please remove these dirs if it exists -
> 
> ```
> ~/.config/sww
> ~/.config/hyprdots
> ~/.cache/hyprdots
> ```
> 
> its now in `~/.config/hyde` and the new cache dir is `~/.cache/hyde`

Is there something else do i need to delete? Everything seems to work but you never know what's happening inside

in cache I have 

- hyde
- hyprdots-ctl
- p10k-krit
- swww


in config I have
- gtk-3.0
- gtk-4.0
- hyde
- hypr
- hyprdots-ctl
- Kvantum
- menus
- nwg-look
- qt5ct
- qt6ct
- swaylock
- wlogout

**Comment by prasanthrangan** [comment]
> Is there something else do i need to delete? Everything seems to work but you never know what's happening inside

you are good to go... everything (including walls) is now in `~/.config/hyde` and all the scripts should be in `~/.local/share/bin` as long as these 2 dirs are preserved, it should work!

**Comment by Carecovisk** [comment]
I am having a similar problem; every time I start my computer, the wallpaper does not appear and only comes back when I change it. But when I shut down the PC and log in again, the wallpaper does not appear.

**Comment by kRHYME7** [comment]
try https://github.com/prasanthrangan/hyprdots/issues/1599#issuecomment-2171583745

**Comment by Carecovisk** [comment]
> try [#1599 (comment)](https://github.com/prasanthrangan/hyprdots/issues/1599#issuecomment-2171583745)

thanks, it worked

**Comment by kRHYME7** [comment]
Closing this as the post is 2 months ago. So much was changed.
