### ISSUE TITLE
[Bug]: Kitty in Synth wave theme does not show history outline

### ISSUE THREAD

**Issue by Luiz0047** [prasanthrangan/hyprdots#1432]
### Description

Kitty in Synth wave theme does not show history outline

### Steps to Reproduce

1. Open kitty
2. Try to type anything you have typed before
3. See that there is no history outline

### Expected Behavior

History outline being displayed

### Actual Behavior

No history outline at all

### Screenshots

First two pics are from synth wave and the third is from nordic, to show that it is working

![image](https://github.com/prasanthrangan/hyprdots/assets/123905188/a7153657-d7b4-43b2-9844-82961403e2dd)
![image](https://github.com/prasanthrangan/hyprdots/assets/123905188/a1fdd279-3dcf-4f5d-844d-4b3a8478201e)
![image](https://github.com/prasanthrangan/hyprdots/assets/123905188/4ecf0abf-418f-4337-af09-1c605e42bffe)

### Environment

- Linux Distro:  EndeavourOS
- Kernel : 6.6.29-1-lts
- Hyprland Version: hyprland 0.39.1-5
- Installation Environment: On The Main Hardware
- Other info: 1920x1080 @75hz

**Comment by prasanthrangan** [comment]
ohh.. good catch, i never noticed it! I'll fix this.

**Comment by abenezerw** [comment]
@Luiz0047 was this fixed for you?
