### ISSUE TITLE
Wallbash integration in Firefox webpages

### ISSUE THREAD

**Issue by kevaldonga** [prasanthrangan/hyprdots#1433]
We should have wallbash extension on firefox like we have in code-oss.

### Description
right now when I change the theme color scheme in firefox changes but the website scheme is not integrated.
It would be great if that would be integrated as well.

we don't need complete color scheme implementation like vscode ( as It would be pretty much impossible ), but it should at least detect if the theme is dark or light and change the website scheme according to that.

**Comment by prasanthrangan** [comment]
Hi, firefox already does this by default. Please check firefox settings (`general` > `appearance` > `automatic`)

Dark:
![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/98222d5e-9be3-43ae-9711-603dbe576126)
Light:
![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/47e26b32-59e1-4f15-a57f-8c47e3c6790d)

**Comment by Skerse** [comment]
> firefox already does this by default as it follows system gtk theme.

That wasn't what he was asking, but yeah firefox itself does and websites can change light and dark mode based on it too, but they were saying this: 

> the theme color scheme in firefox changes but the website scheme is not integrated

Which, i have to say, is pretty much impossible. Websites do not follow a standard, change often, and the best we could do is integrate each individual website we want which even that i'm not sure is possible to work with the system.

**Comment by prasanthrangan** [comment]
> Which, i have to say, is pretty much impossible. Websites do not follow a standard, change often, and the best we could do is integrate each individual website we want which even that i'm not sure is possible to work with the system.

yup, exactly... but there is a [stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) plugin that could inject css to websites...
I think the best we could do is sync the colors to firefox start page.

**Comment by Tisteos** [comment]
By the way, what is the firefox theme?

**Comment by kevaldonga** [comment]
I have set appearance to automatic. using no external theme.

**Comment by kevaldonga** [comment]
There is no way to implement custom color schemes to webpages, but we can at least have customized homepage for each theme.

**Comment by RookiexCookie** [comment]
That we can do with browsersync and wallbash 
mine is like this im using bento homepage
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/7a7d109c-b625-4a03-9137-b22893a5e1fb)
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/4d6dfe0b-bee1-476f-8b74-54319d5344c1)

**Comment by kevaldonga** [comment]
How can I do that ? I can't figure it out

**Comment by kevaldonga** [comment]
closing this issue is as syncing color scheme with browser webpages is not possible.

**Comment by shin01221** [comment]
i know this is close but i figured out a solution to this and it's using zen browser and i general settings you fill find
manage colors choose always and it's working really great for me this option is in firefox too but when i enable it, it force light theme and i can't force back dark theme i don't know why it behave like this + in youtube u will need a plugin called theater mode for youtube this plugin will force youtube to open all vids in theater mode and that solve some color issue in zen browser for youtube .
i still need to test out other websites but as for now it's working really great
