### ISSUE TITLE
[Bug]: No standard programs to choose from

### ISSUE THREAD

**Issue by LunasShade** [prasanthrangan/hyprdots#1434]
### Description

For example, if you want to open a text file, a window appears asking how you want to open the file, but unfortunately there is no program to select. **This phenomenon can occur after a fresh installation.**

### Steps to Reproduce

1. Follow the installation instructions
3. Login for the first time
4. Start Dolphin and try to open an file

### Expected Behavior

A selection of programs is displayed from which you can choose

### Actual Behavior

An empty window with no programs to choose from.

### Screenshots

![Screenshot](https://github.com/prasanthrangan/hyprdots/assets/55425467/5386db49-83da-418f-a5fe-f85f03367770)

### Environment

- Linux Distro: ArchLinux
- Linux Version: Linux archlinux 6.8.9-1-cachyos-eevdf #1 SMP PREEMPT_DYNAMIC Fri, 03 May 2024 07:40:33 +0000 x86_64 GNU/Linux
- Hyprland Version: v0.39.1
- Installation Environment: On The Main Hardware

**Comment by kevaldonga** [comment]
It is related to https://github.com/prasanthrangan/hyprdots/issues/1406
