### ISSUE TITLE
[Bug]: Dolphin "open with" blank

### ISSUE THREAD

**Issue by nicolkrit999** [prasanthrangan/hyprdots#1435]
### Description
As seen in the image it does not display any application that I can use. If I remember the name correctly, such as "firefox" and press enter then it opens it with the correct one. I tought it was a good idea to remove the folder (cloned with git clone) in **~/Hyprdots**, which was the destination folder given a few weeks/months ago. And then cloned into **~/HyDE** as suggested in the installation script as of today.
I tried to run `Hyprdots cache rebuild` but I have the following error

![carbon](https://github.com/prasanthrangan/hyprdots/assets/117823281/56df9f71-2004-4262-a79a-6e33f0482920)

I assume I need to tell the command to use the new ~/HyDE/Scripts folder, but I do not know where and how.

Additionally, if I go to **~/HyDE/Scripts** and run `./global_fn.sh` powercolor tells me a green arrow, meaning something went all good, but at the end of the day it didn't to anything

### Steps to reproduce
1. Delete recursively the content of hyprdots as well as the root directory itself inside **~/Hyprdots**
2. `cd /Scripts && ./install.sh ` (also `./install.sh -r` does not solve the problem)
3. `Hyprdots cache rebuild`

### Expected Behavior
The menu to display me the possible applications

### Actual Behavior
![WhatsApp Image 2024-05-03 at 5 35 53 PM](https://github.com/prasanthrangan/hyprdots/assets/117823281/2eb1a6f7-9207-4e7b-9380-f1762c0b6403)

### Environment
- OS : Arch Linux x86_64
- Kernel : 6.8.7-arch1-2
- Linux archlinux 6.8.7-arch1-2 #1 SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:31 +0000 x86_64 GNU/Linux
- Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460
- Main Hardware (all amd)
- 3160x1440, 160 Hz, landscape (right side)
- 1440x2560, 180 Hz, portrait (left side)

**Comment by prasanthrangan** [comment]
Hi, this is duplicate... please refer https://github.com/prasanthrangan/hyprdots/issues/1406

**Comment by kRHYME7** [comment]
Two problems here.

1.Dolphin:  The fix is pinned, check it out
2. Hyprdots-ctl is outdated  and renamed it to this ` yay -Sy hyde-cli-git ` 

After installing `Hyde cache rebuild ` rebuilds cache.
or ` swwwallcache -f `


Also please see the pinned issue about what changes we got.
