### ISSUE TITLE
custom wallpapers

### ISSUE THREAD

**Issue by totkyle** [prasanthrangan/hyprdots#1436]
i need a a way to change my wallpaper to a custom one in hyprdots in a simple way, i saw a closed issue about this but i couldn't really get anything out of it because it told to run some .sh file but that file didnt exist in my HyDE scripts thing.

**Comment by prasanthrangan** [comment]
Hi @totkyle , 

You could add your custom wallpaper directory path in `~/.config/hyde/hyde.conf` as below -

```
wallAddCustomPath=("/path/to/wall/dir")
```

for example i've set mine as -
```
wallAddCustomPath=("$HOME/Pictures/mushrooms" "$HOME/Pictures/treescapes" "$HOME/Pictures/ultrawides")
```

https://github.com/prasanthrangan/hyprdots/blob/2f65f8edae07772340e1d440f48e255091455629/Configs/.config/hyde/hyde.conf#L34-L36

**Comment by its-19818942118** [comment]
Um don't you think it's a bit of overkill. To manually define each one.

**Comment by kRHYME7** [comment]
each one of?

**Comment by kRHYME7** [comment]
@totkyle this is resolved now. https://github.com/prasanthrangan/hyprdots/issues/1436#issuecomment-2093480153
