### ISSUE TITLE
Artifact on the border. Termial slow to launch. 

### ISSUE THREAD

**Issue by NoahFraiture** [prasanthrangan/hyprdots#144]
Hello,
Today, I installed your dots, and it's beautiful.

# Artifact Issue:
However, I'm currently facing an issue. Firstly, there's an artifact on the side of the screen that disappears after a few minutes (though I haven't noticed exactly when). This artifact tends to appear when I move my mouse to the border of the screen. It's reminiscent of the artifacts that can occur when you move your mouse over a glitchy window on Windows. Despite this, there's nothing visible in the screenshot. Could this be related to Wayland?

Here's the screenshot:

![230901_00h15m05s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/94681915/916f11de-3019-4b91-ad30-24428f002859)
![artifact](https://github.com/prasanthrangan/hyprdots/assets/94681915/bbcefe34-21ec-41d2-9086-a073a2d96760)

I'm using an Nvidia RTX and an Intel Iris. Neofetch indicates that the Intel GPU is active, but I'm unsure if this is due to the RTX being inactive or if it's not functioning correctly. I attempted to install optimus-manager, but it resulted in my computer failing to start.

# Terminal Slowness:
On another note, there's an issue with terminal speed. If I haven't opened a new terminal for a few seconds, it takes an additional few seconds for the Kitty terminal to launch. Exiting the terminal is also often sluggish. Is there a potential solution to address this performance problem?
Edit : I search in the zshrc file, the hyprland.conf file where the terminal is launch and in kitty.conf but I didn't find any clue of this slowness

Bonus - Neofetch Refresh Rate:
Additionally, I noticed that Neofetch doesn't appear to detect my monitor's refresh rate, even when using the relevant option.

Once again, excellent work!

**Comment by T-Crypt** [comment]
Have you tried modifying your monitors.conf to adjust your resolution and refresh rate and scaling?

**Comment by NoahFraiture** [comment]
Yes, I made me understand some blur trouble with electron app and scaling, but I didn't realized it was related to the artifacts problem.
But set the scale to 1 would be very annoying since I should set font and size of the whole system and every app to be readable. Do you have idea to resolve this problem with scaling on ?

**Comment by T-Crypt** [comment]
I haven't seen the artifact issue before, I was just curious if you had modified your settings for your monitor! 

ill look into this

**Comment by prasanthrangan** [comment]
> I'm using an Nvidia RTX and an Intel Iris. Neofetch indicates that the Intel GPU is active, but I'm unsure if this is due to the RTX being inactive or if it's not functioning correctly. I attempted to install optimus-manager, but it resulted in my computer failing to start.

Can you try disabling the nvidia [variables](https://wiki.hyprland.org/Nvidia/)?
Also, is vrr enabled? if so, disable it.

> On another note, there's an issue with terminal speed. If I haven't opened a new terminal for a few seconds, it takes an additional few seconds for the Kitty terminal to launch. Exiting the terminal is also often sluggish. Is there a potential solution to address this performance problem? Edit : I search in the zshrc file, the hyprland.conf file where the terminal is launch and in kitty.conf but I didn't find any clue of this slowness
> 
> Bonus - Neofetch Refresh Rate: Additionally, I noticed that Neofetch doesn't appear to detect my monitor's refresh rate, even when using the relevant option.

This too seems like gpu related.

**Comment by NoahFraiture** [comment]
I disabled NVIDIA variables, and now the glitch doesn't respond to my mouse; it remains static, but it's still there. VRR was already 0. The terminal speed hasn't been affected

**Comment by prasanthrangan** [comment]
Your hybrid graphics seems to be causing this, so identify your nvidia card and set it as primary like this in hyprland.conf -
```
env = WLR_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0
```
please refer this wiki - https://wiki.hyprland.org/Configuring/Multi-GPU/

**Comment by NoahFraiture** [comment]
After some tests I have result : if I try to start with my nvidia first, I can't log in my computer, after enter the password, quick black screen and back to the login page. But it works well if I put my intel iris first. Which is kind of weird because like I said I can run sf6 without much trouble and I don't think an intel iris could do that.
I also had some trouble with nvidia variable but I after search the line "env = GBM_BACKEND,nvidia-drm" make me freeze after the login

Beside that there's still the artifact but static, it's more like a line of pixels of the wrong color, since I went from scale 1.5 to scale 1.3. I of course can get these glitch back with scale 1.5 and more, the bigger the scale, the bigger the glitches. (To avoid blur problem with xwayland software I simply disabe scaling for all of them and one by one I set their scale in the bin file)
The terminal is still very slow to start and close which is kind of annoying. The artifacts are now more details

**Comment by prasanthrangan** [comment]
> I also had some trouble with nvidia variable but I after search the line "env = GBM_BACKEND,nvidia-drm" make me freeze after the login

is the other nvidia variables enabled? and also is `nvidia_drm.modeset=1` set in grub?


> Beside that there's still the artifact but static, it's more like a line of pixels of the wrong color, since I went from scale 1.5 to scale 1.3. I of course can get these glitch back with scale 1.5 and more, the bigger the scale, the bigger the glitches. (To avoid blur problem with xwayland software I simply disabe scaling for all of them and one by one I set their scale in the bin file)
> The terminal is still very slow to start and close which is kind of annoying. The artifacts are now more details.

Does everything work when scaling is set to 1?

> Edit : From kitty documentation slowness come from power issue from the gpu, but if it doesn't work, shouldn't the intel be always active ? So no slow down
> I have rtx 4060 laptop so ada lovelace architecture, the arch wiki doesn't speak of it. Would it too recent ? I can't choose between nvidia-dkms or nvidia-open-dkms since it's not maxwell or turing architecture, I keept the original drivers of these dots


I just checked the nvidia official drivers, they do have `GeForce RTX 4060 Laptop GPU` listed so the `535.104.05` driver (i'm using the same) is supposed to work. If you have any other optimus drivers installed, try uninstalling it.

```
Version: | 535.104.05
Release Date: | 2023.8.22
Operating System: | Linux 64-bit
```

**Comment by NoahFraiture** [comment]
> 
> is the other nvidia variables enabled? and also is `nvidia_drm.modeset=1` set in grub?

Yes they are, and I'm not exactly sure but there's this line `GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet splash nvidia_drm.modeset=1"` in /etc/default/grub

> Does everything work when scaling is set to 1?

There's not the artifact but that's it. Terminal is slow but I made more test.
I was wrong but also right. Sorry for the confusion. The gpu works, its usage and memory rise when I open a game. But it seems to not work at all with hyprland. 
Like we saw earlier, I can't use it when I log in hyprland with the priority chain. With a scale of 1, I don't have the artifact and the terminal seem to start a bit faster, but still not very good. I guess it's my best shot for the moment. Do you have any advice for scaling apps ? Some are very small and --force-device-scaling can give weird results.

I maybe should wait for update with hyprland, the dev is very active. I will also try clean hyprland without any dots. From memory I think I had no slowness problem with terminal when I install arch with hyprland without anything else but I guess I should do more test, and also with other distro to see if there's a hardware problem.

**Comment by prasanthrangan** [comment]
> With a scale of 1, I don't have the artifact and the terminal seem to start a bit faster, but still not very good. I guess it's my best shot for the moment. Do you have any advice for scaling apps ? Some are very small and --force-device-scaling can give weird results.

Its the same for me, when i use fractional scaling, it looks blurry. Not sure if there is any workaround it.




> I maybe should wait for update with hyprland, the dev is very active. I will also try clean hyprland without any dots. From memory I think I had no slowness problem with terminal when I install arch with hyprland without anything else but I guess I should do more test, and also with other distro to see if there's a hardware problem.

Good idea, try hyprland with default config... and check if its using nvidia as primary.

**Comment by NoahFraiture** [comment]
I'm back. I had some trouble testing the OS, but I have some news.

I tested this configuration: https://github.com/JaKooLit/Hyprland-v3 on endeavourOS, and it works pretty well. There are the same artifacts with scaling, but the terminal opens at a normal speed which is the real deal.

I tried closing all major packages like rofi, waybar, and the rest, but that didn't change anything. And to my knowledge, there's nothing in the hyprland config file that's causing the problem with my terminal.

I tried using another terminal or another shell, but that didn't help either.

However, I noticed that I have the same issue with the file explorer, which is bound to the terminal: if I open a terminal (slow), I can open other terminals or the file explorer (fast). However, this problem doesn't occur with Thunar. My guess is that the problem is related to the blur and transparency. (Webcord, which has the same transparency, is also slow, but that could be because it's Discord.) Thunar which has no blur works well

Do you know what is responsible for rendering the transparency? That could help me. I don't understand. It could really be the drivers, since it works perfectly on another Hyprland OS. I can provide a list of the different packages with the other configuration.

**Comment by prasanthrangan** [comment]
Hi, could you try adjusting the blur values in this [config](https://github.com/prasanthrangan/hyprdots/blob/3d6cad4a71c2abb4b2bac1f551d17a3eb98a6d03/Configs/.config/hypr/themes/Catppuccin-Mocha.conf#L34C5-L34C10).
Also the transparency set in `~/.config/hypr/windowrules.conf`

**Comment by NoahFraiture** [comment]
Sadly, nothing help in these. Isn't there a package possibly missing ?

**Comment by prasanthrangan** [comment]
> if I try to start with my nvidia first, I can't log in my computer, after enter the password, quick black screen and back to the login page.

I think the slowness is mainly mainly due to this, your nvidia card is not being used!
If you get black screen while using nvidia as primary means that nvidia_drm is not enabled before sddm, so refer [this](https://wiki.archlinux.org/title/NVIDIA#Early_loading) and try early loading.

**Comment by NoahFraiture** [comment]
Nope sadly that doesn't help. I'm surrending and I'll use another wm or config, I have found things (much less pretty) but it'll fit for now. If someone find what cause this issue in the future, I'll gladly come back to this config

**Comment by prasanthrangan** [comment]
hahaa no worries, have fun!
please let me know if you manage to figure out what setting caused it...

**Comment by Muhammad-Abubakr** [comment]
Okay, I would like to give my input on this issue. I was facing the exact same issue and I was tinkering around the monitor and nvidia settings. So, I am not really sure what actually helped me but I think that using this setting `monitor = eDP-1, highrr, auto, 1.25, bitdepth, 10` for my monitor actually fixed the issue while previously it was `monitor = eDP-1, 1920x1080@120, 0x0, 1.25`. Can you try it and update please.

**Comment by NoahFraiture** [comment]
It actually seems to help, but I'm not sure I have this problem anymore even without that. I think it leaves without a word. Probably an update solve the issue.
Anyway thank you all
