### ISSUE TITLE
[Bug]: `Failed Installing Extensions` from VSCode when selecting themes

### ISSUE THREAD

**Issue by Oskar-Idland** [prasanthrangan/hyprdots#1440]
### Description
When doing `Hyde theme select`, I select a theme in the rofi menu. This successfully changes for waybar, the wallpaper and tile borders. It does not change the terminal (kitty + fish) theme, and does not change the vscode theme. It stays at Catpuccin Mocha.  The theming is also just applied to the default vscode profile. I have added the user folders as well for further development at the bottom. 

I have multiple version of vscode like the insider version and OSS version, along with the regular. The OSS  version is the only one to create a `jq`, error. After excluding it from the script I still got the other `Failed Installing Extensions:`Below I have added a video of what happens when changing theme, and the error message produced.  

I added print statements `wallbashcode.sh` to see what is happening. I print which vscode version is being worked on, and when the loop is done. This confirmed the script hangs after it should be done. My edited script:
```sh
for i in "${!codeConf[@]}" ; do
	echo "=================="
	echo ${codeConf[i]}
	echo ${codeVsix[i]}
	echo "=================="
    [ -f "${codeConf[i]}/User/settings.json" ] || continue
    extTheme="$(jq -r '.["workbench.colorTheme"]' "${codeConf[i]}/User/settings.json")"


    if [ ! -f "${codeVsix[i]}/${tgtFile}" ] ; then
        [ -f "${cacheDir}/landing/Code_Wallbash.vsix" ] || curl -L -o "${cacheDir}/landing/Code_Wallbash.vsix" https://github.com/prasanthrangan/hyprdots/raw/main/Source/arcs/Code_Wallbash.vsix
        code --install-extension "${cacheDir}/landing/Code_Wallbash.vsix"
    fi

    if [ "${extTheme}" != "wallbash" ] ; then
        jq '.["workbench.colorTheme"] = "wallbash"' "${codeConf[i]}/User/settings.json" > "${tmpFile}" && mv "${tmpFile}" "${codeConf[i]}/User/settings.json"
    fi
    
    cp "${cacheDir}/landing/wallbashcode.json" "${codeVsix[i]}/${tgtFile}"
done
echo "Loop Done"
```

This was a lot so here comes a small summary.
#### Summary
1. The terminal theme does not switch no matter what, and the scripts hangs after execution, no matter what.  The system theme does switch for the wallpaper and waybar
2. Having the newest version of vscode is necessary to download the extensions, but there is is another jq parsing error popping up no matter what.
3. The OSS version of vscode is the only one generating the first jq error. This must be fixed, or just removed as an option from the script entirely. The rest of the errors come from the extension installation
4. There are 3 errors, from both `jq` and the theme installation command caused by the  `cp: cannot create regular file '/home/oskar/.vscode-oss/extensions/undefined_publisher.wallbash-0.0.1/themes/wallbash-color-theme.json': No such file or directory`

### Steps to Reproduce

1. `Hyde theme select`
2. Choose any theme

### Video and Errors

[Video](https://github.com/prasanthrangan/hyprdots/assets/69601310/8770cf66-0fc2-49fd-8dbc-361ed2134584) Showing the full error, using the older version of vscode, including the OSS version.

Output with vscode version 1.89
```sh
==================
/home/oskar/.config/Code
/home/oskar/.vscode
==================
==================
/home/oskar/.config/Code - Insiders
/home/oskar/.vscode-insiders
==================
Installing extensions...
Extension 'Code_Wallbash.vsix' was successfully installed.
==================
/home/oskar/.config/Code - OSS
/home/oskar/.vscode-oss
==================
Installing extensions...
Extension 'Code_Wallbash.vsix' was successfully installed.
Loop Done
jq: parse error: Invalid numeric literal at line 300, column 12
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
jq: parse error: Invalid numeric literal at line 300, column 12
cp: cannot create regular file '/home/oskar/.vscode-insiders/extensions/undefined_publisher.wallbash-0.0.1/themes/wallbash-color-theme.json': No such file or directory
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
cp: cannot create regular file '/home/oskar/.vscode-oss/extensions/undefined_publisher.wallbash-0.0.1/themes/wallbash-color-theme.json': No such file or directory
```

Output when only doing the standard version of vscode. After the loop is done, it just hangs, without terminating the script. 
```sh
❯ ==================
/home/oskar/.config/Code
/home/oskar/.vscode
==================
Only doing standard vscode
Loop Done
```

Output with vscode older than 1.86 as shown in video
```sh
  ~/.local/share   19:07 
❯ Hyde theme select

(process:1667288): Rofi-WARNING **: 19:07:32.894: ABI version of plugin: 'librofi_vscode_mode.so' does not match: 00000006 expecting: 00000007
:: applying theme :: "Mac OS"
:: applying wall :: "/home/oskar/.config/hyde/themes/Mac OS/wallpapers/10-10.jpg"
 

  ~/.local/share   19:07 took 3s 
❯ ==================
/home/oskar/.config/Code
/home/oskar/.vscode
==================
==================
/home/oskar/.config/Code - Insiders
/home/oskar/.vscode-insiders
==================
Installing extensions...
==================
/home/oskar/.config/Code - OSS
/home/oskar/.vscode-oss
==================
Installing extensions...
Loop Done
jq: parse error: Invalid numeric literal at line 300, column 12
(node:1668785) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Error: Unable to install extension 'undefined_publisher.wallbash' as it is not compatible with VS Code '1.85.2'.
    at X.install (/home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:48:63942)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async v.g (/home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:28:299)
    at async /home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:27:16429
    at async Promise.all (index 0)
    at async v.installExtensions (/home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:27:16358)
    at async /home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:50:6587
    at async Object.ge [as main] (/home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:50:10259)
    at async v (/home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:31:22737)
Failed Installing Extensions: file:///home/oskar/.cache/hyde/landing/Code_Wallbash.vsix
jq: parse error: Invalid numeric literal at line 300, column 12
cp: cannot create regular file '/home/oskar/.vscode-insiders/extensions/undefined_publisher.wallbash-0.0.1/themes/wallbash-color-theme.json': No such file or directory
(node:1668833) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Error: Unable to install extension 'undefined_publisher.wallbash' as it is not compatible with VS Code '1.85.2'.
    at X.install (/home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:48:63942)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async v.g (/home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:28:299)
    at async /home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:27:16429
    at async Promise.all (index 0)
    at async v.installExtensions (/home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:27:16358)
    at async /home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:50:6587
    at async Object.ge [as main] (/home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:50:10259)
    at async v (/home/oskar/VSCode_Old/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:31:22737)
Failed Installing Extensions: file:///home/oskar/.cache/hyde/landing/Code_Wallbash.vsix
cp: cannot create regular file '/home/oskar/.vscode-oss/extensions/undefined_publisher.wallbash-0.0.1/themes/wallbash-color-theme.json': No such file or directory
```

### System Info

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: 6.8.8-arch1-1 
- Hyprland Version, output of `hyprctl version`: v0.39.1
- VSCode version: 1.89
- Hyde version: v0.1.0.r52.abd5ede

### VSCode profile files location
For further development, I have added where VSCode stores the extra information for their profiles. Each profile is given a random set of character names in the format `-<10 random letters and numbers>`. The symlinks are my own, for ease of use with git. 
![image](https://github.com/prasanthrangan/hyprdots/assets/69601310/fabf9f2b-2648-43d7-abcb-b2e449cff576)

**Comment by kRHYME7** [comment]
Hi can you test it using just the raw script.

just run ` themeselect.sh `

**Comment by Oskar-Idland** [comment]
Exactly the same output

**Comment by Oskar-Idland** [comment]
I also added the output with both old and new version of vscode

**Comment by mahaveergurjar** [comment]
manually install the Wallbash extension and then try 
I think wallbash extension is not install in your system

**Comment by Oskar-Idland** [comment]
What is the name? 
![image](https://github.com/prasanthrangan/hyprdots/assets/69601310/4c42099b-f812-462a-a8f5-c8185f9d1b45)

**Comment by mahaveergurjar** [comment]
this is not in vscode extension marketplace

**Comment by mahaveergurjar** [comment]
got to repo and then got Source/arcs the starting one file is wallbash extension

**Comment by Oskar-Idland** [comment]
I do not quite get what you mean. What exact file and what should I do with it?

**Comment by mahaveergurjar** [comment]
download this extension and install in vscode
![image](https://github.com/prasanthrangan/hyprdots/assets/57872034/97717ffa-ea88-4ee0-92f0-bf915df3f9cd)

**Comment by mahaveergurjar** [comment]
after download open vscode go to extension click on three dot and you see the option to install the extension 
![240505_00h36m17s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/bf18accc-497d-411b-b801-317b5139f843)

**Comment by Oskar-Idland** [comment]
# Update after installing vsix-file
When selecting theme, the terminal theme does not change and I must reload manually to get vscode to change theme, so that almost works as it should. The weird part now is that sometimes, swaylock is activated after using `themeselect.sh`????

**Comment by kRHYME7** [comment]
Happens everytime?

**Comment by Oskar-Idland** [comment]
It does not happen every time, and I really do not see pattern. We can close the issue, as I found out my kitty config sourced the old theme file. I might add some stuff to the wiki about integrating custom config files. I wan't to keep my fish aliases and kitty config etc, but still have themes. This would make everything even more modular.

**Comment by kRHYME7** [comment]
All points are expected.

**Comment by Oskar-Idland** [comment]
A super simple hotfix, is to just terminate the loop after the first iteration, as that is the default vscode, until this works for all editions:
```sh
for i in "${!codeConf[@]}" ; do
    if [ $i = 1 ]; then
    	break
    fi

```
Or just not looping at all, and simply just doing the standard version only.

**Comment by kRHYME7** [comment]
what is the output whe you run ` find ~/.config/Code* -mindepth 1 -maxdepth 1 -type d -name "Code*" | sort ` ?

**Comment by Oskar-Idland** [comment]
```
/home/oskar/.config/Code/Code Cache
/home/oskar/.config/Code - Insiders/Code Cache
/home/oskar/.config/Code - OSS/Code Cache
```
All my versions of vscode. The regular one is at the top

**Comment by kRHYME7** [comment]
How aboout this ? 

` find "$HOME" -mindepth 1 -maxdepth 1 -type d -name ".vscode*" | sort ` ?

**Comment by Oskar-Idland** [comment]
```shell
/home/oskar/.vscode
/home/oskar/.vscode-insiders
``` 
I forgot to mention, I deleted the OSS version of vscode, just had not removed the folder. Both config folders are gone now

**Comment by Oskar-Idland** [comment]
> `"${codeVsix[i]}/${tgtFile}"` this will only try cp to tgtFile

So if only `tgtFile` is defined, then of course, you will get the final path of `/extensions/undefined_publisher.wallbash-0.0.1/themes/wallbash-color-theme.json`, as the first path is missing

**Comment by kRHYME7** [comment]
`[ -d "${codeVsix[i]}" ] && cp "${cacheDir}/landing/wallbashcode.json" "${codeVsix[i]}/${tgtFile}"  `

how about we add checks for line 29.

> `cp: cannot create regular file '/extensions/undefined_publisher.wallbash-0.0.1/themes/wallbash-color-theme.json': No such file or directory  `

this error should not occur now

**Comment by kRHYME7** [comment]
If you're fine making a PR, it would be awesome!

**Comment by Oskar-Idland** [comment]
Will do! You have enough on your plate:)

**Comment by Oskar-Idland** [comment]
Tested some more and found that SOMETIMES the scripts just hangs for no reason, with the `jq` error from earlier. I tried to echo some text in the loop as well, and sometimes it is not visible, and sometimes it is. I think way more is happening in the background, which makes no sense, as it just this simple script...

**Comment by Oskar-Idland** [comment]
This is the result of me just spamming the script. At the last attempt, it hangs....
https://github.com/prasanthrangan/hyprdots/assets/69601310/f019cc26-41b3-43da-8730-2f6e6a16b1a9

**Comment by kRHYME7** [comment]
let's arrow it down first 

`   bash -x ~/.local/share/bin/wallbashcode.sh `
This should give us Idea which part it hangs.
