### ISSUE TITLE
[Bug/Question]: Brave-Sync Issue?

### ISSUE THREAD

**Issue by LunasShade** [prasanthrangan/hyprdots#1441]
## Bug Report

Does something have to be changed in the system for it to work or is something configured incorrectly for me?

### Description

Somehow I have to log in to Brave-Sync after every restart. But I only have this problem here. It works in Cachy and Nobara but not here, what is wrong or am I missing?

### Steps to Reproduce

1. Open Brave-Settings
2. Login to an existance sync-chain
3. Restart computer
4. Open Brave-Sync-Settings
5. No longer logged in

### Expected Behavior

That I am not automatically logged out.

### Actual Behavior

I get logged out every time for a reason I don't understand.

### Additonal Informations

I use the same Repository to download the browser as with the other distros before

### Environment

- Linux Distro: ArchLinux
- Linux Version: Linux archlinux 6.8.9-1-cachyos-eevdf #1 SMP PREEMPT_DYNAMIC Fri, 03 May 2024 07:40:33 +0000 x86_64 GNU/Linux
- Hyprland Version: v0.39.1
- Installation Environment: On The Main Hardware

**Comment by rubiin** [comment]
I honestly havent used brave for a while . Unlike chrome or vivaldi which are also based on chromium, getting sync on brave is little tricky https://support.brave.com/hc/en-us/articles/360021218111-How-do-I-set-up-Sync , maybe simething here that will help you

**Comment by kRHYME7** [comment]
> Does something have to be changed in the system for it to work or is something configured incorrectly for me?

Maybe some password storing issues. 

Brave did not ask you to setup a password? 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/951b1eb0-a4d6-49a1-bc3f-dddd0288013a)

**Comment by zeerayne** [comment]
I faced likely similar issue with skype - it forgets credentials after every restart. I have find out that skype is strictly using `gnome-keyring` for storing secrets, and if there is no gnome-keyring, it simply does not store anything. Maybe brave have similar problem

**Comment by LunasShade** [comment]
> > Does something have to be changed in the system for it to work or is something configured incorrectly for me?
> 
> Maybe some password storing issues.
> 
> Brave did not ask you to setup a password? ![image](https://private-user-images.githubusercontent.com/53417443/328029568-951b1eb0-a4d6-49a1-bc3f-dddd0288013a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MzI5ODUsIm5iZiI6MTcxNDkzMjY4NSwicGF0aCI6Ii81MzQxNzQ0My8zMjgwMjk1NjgtOTUxYjFlYjAtYTRkNi00OWExLWJjM2YtZGRkZDAyODgwMTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDE4MTEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZGQ2N2Y1MjVlZDI3ZDM4ZTZhZmE5MDY0YzNlMzc3MjdjOTkxOWNlNGNlMTBmOTI3NDNlM2Y4MGVlOTMyODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qE9sjC1nzzbhRbGBBr2OAsdOAHB0fQjFkDdn1NSFGUE)
> 
> Edit:
> 
> Might be relevant
> 
> #395

Something like that came at the beginning I just took nothing as a passoword, is that a problem?

**Comment by kRHYME7** [comment]
you probably should at least just choose the ` classic ` option. It's not a fancy way to store passwords but it should at least save your profiles .

Try to remove the brave directory inside ~/. config then uninstall brave( not necessary ).  reboot  then install and open brave again. 


After setting it up, probably it will always ask for password, Please follow the comment of @ prasanthrangan in my mentioned comment earlier.

**Comment by LunasShade** [comment]
When using the command `brave --password-store=basic`. this error occurs:


```
[21857:21880:0506/173224.574217:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[21857:21880:0506/173224.574256:ERROR:select_file_dialog_linux_portal.cc(286)] Failed to read portal version property
[21857:21857:0506/173224.576369:ERROR:chrome_browser_cloud_management_controller.cc(161)] Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
[21857:21857:0506/173224.587191:ERROR:brave_sync_prefs.cc(141)] Decrypt sync seed failure
src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000
```

**Comment by kRHYME7** [comment]
Errors like brave won't show up? or warning?

**Comment by LunasShade** [comment]
More of a warning Brave opens anyway

**Comment by LunasShade** [comment]
Now it works as it should, thanks ^^

**Comment by kRHYME7** [comment]
> [!TIP]
>  Add this file so that brave will use it and no need to modify the .desktop or the binds (Useful if an app is electron )

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/cdf97dba-ea29-43e0-84db-ad4b149ce922)
