### ISSUE TITLE
[Bug]: Random system crashes (is there a tool to figure out what's wrong)

### ISSUE THREAD

**Issue by LunasShade** [prasanthrangan/hyprdots#1442]
### Description

I have no idea what the problem is, but from time to time at different intervals, be it 5 minutes or several hours, everything suddenly hangs and I have to restart. Is there a tool to find out what the issue is?

It doesn't matter what I do, whether it's just listening to music or doing things in the browser. Except when a game is open in Steam, there are no hang-ups for hours.

### Expected Behavior

Arch running normally without random hang-ups

### Actual Behavior

Arch with hang-ups :(

### Environment

Linux Distro: ArchLinux
Linux Version: Linux archlinux 6.8.9-1-cachyos-eevdf https://github.com/prasanthrangan/hyprdots/issues/1 SMP PREEMPT_DYNAMIC Fri, 03 May 2024 07:40:33 +0000 x86_64 GNU/Linux
Hyprland Version: v0.39.1
Installation Environment: On The Main Hardware

**Comment by Enigma1309** [comment]
i had the exact same issue a while back (an years ago i guess...),
for me it was lagging when listening to music on spotify and then the system randomly freezes and i have to hard power reset the pc  ..
it wasn't hyprdots but yeah, i fixed it by reinstalling arch.. that's the only way i found out the problem to be fixed without getting your head into...

**Comment by LunasShade** [comment]
Unfortunately, I have already tried this without success.

**Comment by kRHYME7** [comment]
` Hyde power save --[options] `

Try to select all maybe Hyprland consumes your system resources. Do you have Swap memory?

**Comment by LunasShade** [comment]
Yes, swap is activated by default

**Comment by kRHYME7** [comment]
> Yes, swap is activated by default

vanilla arch don't have "defaults" so how can we confirm 😅

If it "hangs " can you change to another tty session? if no probably hardaware or kernel panic, try to use the LTS one in case or fallback.

If you are able to change to another TTY then certainly a Hyprland issue. You can check out the logs on that hyprland session.

Logs are available at `  /tmp/hypr/[INSTANCE SIGNATURE]/hyprland.log` 

for the latest hyprland release new dir is located at  
` $XDG_RUNTIME_DIR/hypr/[INSTANCE SIGNATURE]/hyprland.log `

**Comment by kRHYME7** [comment]
I meant you're asking for a tool 

These are the posible .log files you need. 
`  $XDG_RUNTIME_DIR/hypr/[INSTANCE SIGNATURE]/hyprland.log `
`  /tmp/hypr/[INSTANCE SIGNATURE]/hyprland.log ` 

But this is only accessible if you did not restart/reboot.

 > If it "hangs " can you change to another tty session? if no probably hardaware or kernel panic, try to use the LTS one in case or fallback.
 
 If it freezes can you change to another TTY session? ` ctrl + alt + f3 ` something.  If no, it's probably a kernel issue or hardware.

**Comment by LunasShade** [comment]
^^
