### ISSUE TITLE
Sakura material missing

### ISSUE THREAD

**Issue by NoahFraiture** [prasanthrangan/hyprdots#145]
Hello, I'm stupid and I updated "rose pine" in vscode, I search among installation file and google but I didn't manage to find where material sakura was installed, where could I search ?

**Comment by T-Crypt** [comment]
Can you explain a little more? (You're not stupid) 

Did you modify the theme "Rose Pine"? -- material sakura is installed during the install script.

**Comment by prasanthrangan** [comment]
Ahh... Apologies, my bad, I knew an update will break it!

Please re-extract  `~/Hyprdots/Source/arcs/Code_Extensions.tar.gz`  back to `~/.vscode`, to restore the older extension version.

**Comment by NoahFraiture** [comment]
> Can you explain a little more? (You're not stupid)
> 
> Did you modify the theme "Rose Pine"? -- material sakura is installed during the install script.

In vscode the extension Pine-Rose that contains the Material Sakurai had an update, I didn't think twice and proceed to the update, that removed the sakura theme since it's not a native theme from the extension


> Ahh... Apologies, my bad, I knew an update will break it!
> 
> Please re-extract `~/Hyprdots/Source/arcs/Code_Extensions.tar.gz` back to `~/.vscode`, to restore the older extension version.

Thank you ! I worked perfectly
