### ISSUE TITLE
Aligning neovim color scheme with kitty

### ISSUE THREAD

**Issue by kevaldonga** [prasanthrangan/hyprdots#1456]
How can I set neovim color scheme same as kitty or wallbash but I don't know how get colors from wallbash.
I have noticed that kitty has base 16 colors is there any plugin that can set all those colors in nvim. I need some tips here.

**Comment by kRHYME7** [comment]
@kevaldonga  Hello do we need a single file to add colors on neovim ? 

Normally, Neovim can follow the terminal colors unless you manually set it. I'm not using neovim, but I can help you to make a wallbash template for that. 

* It's easier if neovim parse the colors from a single file that can be overwritten.

**Comment by kevaldonga** [comment]
I have set tokyo night theme so it may be overidding colors. also some of the colors are picked up by neovim like background but other stuff like lualine is not adapting it. 
I can't pinpoint where the issue is but I can provide my config file for you to have a look.
[init.lua](https://github.com/prasanthrangan/hyprdots/files/15248265/init.txt)

**Comment by kevaldonga** [comment]
> * It's easier if neovim parse the colors from a single file that can be overwritten.
there is theme.conf file that has all 16 colors in kitty folder which changes the colors when theme is changed.
now there is 2 ways to approach this
    1. I need to create listener in neovim that listen to that file changes
    2. or we can listen to wallbash directly
this way we can change the theme of neovim and load new base 16 colors but I don't know how to do that.

**Comment by kevaldonga** [comment]
It is fixed. for anyone wondering I started using https://github.com/RAprogramm/NEVIRAIDE.git as it is integrated with all themes Hyde comes with. may not have support for custom themes.

**Comment by kRHYME7** [comment]
Wow! Is NEVIRAIDE ready now? Waiting for an  official installer for this. 😮

**Comment by kevaldonga** [comment]
It just lacks installer but you can work around that. other than that it decent.

**Comment by kRHYME7** [comment]
I see! Thanks!
