### ISSUE TITLE
[Feature Request]: Theme doesn't apply on notification 

### ISSUE THREAD

**Issue by tryprncp** [prasanthrangan/hyprdots#1458]
### Description
Hello, Im just curious if this is supposed to be themed? if it is, maybe it's a bug?

Any guides would be helpful

[Add any other information about the feature request here. For example, you might include links to similar features in other projects, or screenshots or diagrams to help explain your idea.]
![240508_16h33m45s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/91647110/2a18c645-da76-4bd2-817e-b4b9b8c3e629)

![image](https://github.com/prasanthrangan/hyprdots/assets/91647110/18b44e81-5420-41ec-801a-5cedf498e901)

**Comment by kRHYME7** [comment]
It's a warning so this is the default color for warnings

**Comment by tryprncp** [comment]
> Nice Wallpaper BTW! Can you share some of those?

Thanks @kRHYME7 . It's from my custom themes, it would be nice if someone can rice it HAHAHA. I yoink it from @prasanthrangan  hyde-themes/Catppuccin-Mocha. may he forgive me 😅

https://github.com/tryprncp/Themes/tree/AI-Arts

**Comment by kRHYME7** [comment]
Wow!  

>  may he forgive me 😅

Nah he would be glad, 
In case you want to share your theme to the world and be available if you run ` Hyde theme patch ` 

visit this and add your theme
https://github.com/kRHYME7/hyde-gallery/blob/hyde-gallery/hyde-themes.db
https://github.com/kRHYME7/hyde-gallery

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/322421cc-44b5-4164-ad18-c81beeddaadd)
