### ISSUE TITLE
[Bug] the Java symbol constantly appears in the Fish termina

### ISSUE THREAD

**Issue by AtnProjects** [prasanthrangan/hyprdots#1462]
### Description

After installing JDK 22.0.1, the Java symbol constantly appears in the Fish terminal in EndeavourOS, persisting indefinitely.

### Steps to Reproduce

1. Install JDK 22.0.1 on EndeavourOS.
2. Open a Fish terminal.
3. Observe that the Java symbol appears continuously in the terminal prompt.

### Expected Behavior

The Java symbol should not persist indefinitely in the Fish terminal after installing JDK 22.0.1.

### Actual Behavior

After installing JDK 22.0.1, the Java symbol continuously appears in the Fish terminal and does not disappear, even when no Java-related commands are being executed.

### Environment

- Operating System: EndeavourOS
- Terminal: Fish
- JDK Version: 22.0.1

### Additional Information

This issue persists indefinitely, regardless of the user's actions or commands executed in the Fish terminal. It would be beneficial to find a solution to prevent the continuous appearance of the Java symbol after installing JDK 22.0.1.

![image](https://github.com/prasanthrangan/hyprdots/assets/72979783/42cdb50d-2103-4f03-a845-c7ee8fecf1e4)

**Comment by kRHYME7** [comment]
which folder are you in ?

**Comment by kRHYME7** [comment]
Hi, check this out 

https://github.com/starship/starship, 

This repo do not have any configuration of starship prompt so check out the upstream starship if you want to configure yours.

**Comment by AtnProjects** [comment]
sorry, it was the directory processed to close the issue
