### ISSUE TITLE
[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by goheakan** [prasanthrangan/hyprdots#1470]
### Description

I just made an update of the my git folder of hyprdots with :
`git pull`
And after I made an update with :
`install.sh -r`
The thing is there is no restore the config of my waybar. Without that everything is ok and restored.

### MAYBE ?
I checked this file `hyprdots/Scripts/restore_cfg.lst` and maybe there is an adjustment to do on the line 23 and need to delete **_modules_** because the config files are on the waybar main folder I think :
`Y|Y|${HOME}/.config/waybar|modules config.jsonc style.css theme.css|waybar`

### Environment
 
 OS : Arch Linux x86_64 
 Kernel : 6.8.9-arch1-2
 Installation On The Main Hardware
 Resolution : 1920x1080 
 DE : Hyprland v0.40.0
 Terminal : kitty

**Comment by kRHYME7** [comment]
` restore ` means   **Restore from the upstream repo**   not the other way around. 

> do not touch this line
>  Y|Y|${HOME}/.config/waybar|modules config.jsonc style.css theme.css|waybar 

Instead you can modify ` Y|Y|${HOME}/.config/waybar|config.ctl|waybar `  that part 
make the flags ` N|Y|....` 

or if you want to handle the updates interactively ` Hyde restore Config ` 

The repo 
https://github.com/kRHYME7/Hyde-cli
Adaption/installation if you did not use the CLI to install Hyde 
https://github.com/kRHYME7/Hyde-cli?tab=readme-ov-file#installation-instructions-for-hyde-with-hyde-install
it shoud be easy as ` Hyde-install --link --dir ~/HyDE ` ~/HyDE is the path to where you clone the repo. 

Dots management:
https://github.com/kRHYME7/Hyde-cli/wiki/Dots-Management

A  demo of ` Hyde restore Config `
https://www.youtube.com/watch?v=l3CiiSTpJ78

**Comment by goheakan** [comment]
Ok I never edited any files of the repo, I wrote a script bash to copy some personnal config files and that's it.
I didn't know there is a Hyde-Cli now ! Nice and well done !
Ok this really simple. Thanks a lot !

**Comment by kRHYME7** [comment]
Added something recently 

` Hyde check Config ` 

should check any diff on some mismatched files.
