### ISSUE TITLE
Post-install HyDE does not load login screen after installing on EndeavourOS

### ISSUE THREAD

**Issue by horugane** [prasanthrangan/hyprdots#1471]
I installed EndeavourOS after deleting Arch Linux because of the root partition issue hassle and installed HyDE using the README.txt instructions. The installation initially aborted altogether because of one package unable to install, then I use Hyde-install from HyDE-cli to install Hyprland. 

The issue is whenever I reboot my PC, it will go into no desktop environment (initial choice during EndeavourOS installation) and not display any login screen by Hyprland. Only if I type Hyde-install again and press a few enter clicks, then it would show the login screen again. I did check that there's a red line that mentions mandatory requirement for SDDM authorization or something.

**Comment by kRHYME7** [comment]
` systemctl enable sddm  ` 

to reinstall the display manager theme

`Hyde sddm theme `

**Comment by horugane** [comment]
Thanks, I'll try it and let you know later

**Comment by horugane** [comment]
It worked, thank you so much! =D

**Comment by kevaldonga** [comment]
Cose the issue if problem is fixed
