### ISSUE TITLE
[Bug]: Rofi;  Deformaties in application and gamelauncher rofi.

### ISSUE THREAD

**Issue by Xeo23** [prasanthrangan/hyprdots#1473]
### Description

The items in app menu and gamelauncher automatically gets glitched and gets normal when closing and reopening.

### Expected Behavior

These meus should show normally like this.

![image](https://github.com/prasanthrangan/hyprdots/assets/65211497/5f224010-9303-48bb-a189-a85d33207595)

![image](https://github.com/prasanthrangan/hyprdots/assets/65211497/d679c602-ea78-456b-8038-1e9ebc2452cb)

### Actual Behavior

These deformaties happens randomly.

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/65211497/fa1d8b72-e83e-42a0-a551-8fa6b3fe728d)

![image](https://github.com/prasanthrangan/hyprdots/assets/65211497/602b3dc3-7f20-415d-9446-f58b7b1ce31b)

- Linux Distro: [ArchLinux]
- Linux Version, output of `uname -a`: 6.8.9
- Hyprland Version, output of `hyprctl version`: 0.39.1
- Installation Environment: [On The Main Hardware]
- Other info: [1920x1080]

**Comment by Enigma1309** [comment]
not related to dots, related to recent commits on upstream
try posting issue [here](https://github.com/lbonn/rofi)

**Comment by kRHYME7** [comment]
@Enigma1309  https://github.com/lbonn/rofi/commit/b04bedca44b34e276a75785bec2c42a83d7a79b7

I'm a lil bit confused if it's upstream as the latest commit is 5 days ago, and it's minor fix

**Comment by rubiin** [comment]
i had the similar issue

**Comment by Enigma1309** [comment]
I'm not too sure about this but it started happening just after the recent update (4 days ago), which makes it highly suspect-able..

also can anyone compile and test the version without this commit..

**Comment by kRHYME7** [comment]
Same problem 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/13b7fffa-da48-4934-afb0-f8e9f3e61bf4)

I'm using a version of rofi that is committed around 3 weeks ago

**Comment by Xeo23** [comment]
so its seems its not related to the recent commits

**Comment by rubiin** [comment]
> I'm not too sure about this but it started happening just after the recent update (4 days ago), which makes it highly suspect-able..
> 
> also can anyone compile and test the version without this commit..

mine started around 2-3 days. Maybe mark this issue as upstream

**Comment by rubiin** [comment]
@kRHYME7 can this closed?

**Comment by kRHYME7** [comment]
why?

**Comment by rubiin** [comment]
> why?

my bad . I thought your last commit was on this :D lol

**Comment by Enigma1309** [comment]
can be closed now as it is fixed in 02d42a9f14361226b041384a55d093f1131afd09
