### ISSUE TITLE
Cant switch apps using waybar or rofi after update

### ISSUE THREAD

**Issue by drnikos** [prasanthrangan/hyprdots#1474]
After I updated the system, I can no longer switch apps using the waybar taskbar or rofi menu so my only option is to use SUPER+scroll. Any ideas on how to fix that?

https://github.com/prasanthrangan/hyprdots/assets/153459342/7886d968-9fd6-4982-8f1a-d71b8e08533b

**Comment by kRHYME7** [comment]
Try reboot?

**Comment by drnikos** [comment]
I managed to fix this by replacing hyprland with hyprland-git, but I had to remove the "general:no_cursor_warps=1" from the userprefs.conf file and replace it with "cursor:no_warps= true".
