### ISSUE TITLE
[Bug]: waybar styling and config is not working 

### ISSUE THREAD

**Issue by shivamsinghcse** [prasanthrangan/hyprdots#1476]
![image](https://github.com/prasanthrangan/hyprdots/assets/121515299/d69f1257-ef86-4729-95d4-bd8acd917271)

**Comment by kRHYME7** [comment]
Do you have changes inside ?

**Comment by shivamsinghcse** [comment]
i have install this on top of garuda hyprland

**Comment by kRHYME7** [comment]
>  what theme is this ?

Catpuccin Latte?

**Comment by shivamsinghcse** [comment]
i have already tried it

**Comment by shivamsinghcse** [comment]
rose pine 
![image](https://github.com/prasanthrangan/hyprdots/assets/121515299/707d0314-4e95-4d7b-baf1-f646680db719)
mocha 
![image](https://github.com/prasanthrangan/hyprdots/assets/121515299/d328013e-c3e7-488a-97b8-5e123df62589)

**Comment by kRHYME7** [comment]
all waybar layouts looks like that ?

**Comment by shivamsinghcse** [comment]
> all waybar layouts looks like that ? 
> 

Yes

**Comment by kRHYME7** [comment]
Strange, 

how did you install the dots, using ./install.sh ?

I recently push a utility to find mismatched dot files 

command is ` Hyde check Config ` 

It should work something like this

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/1a15a3f8-2c72-4edf-9133-97c0f03478c9)
 

The CLI comes preinstalled together with the dots, but by default the clone directory is  `  ~/.cache/hyde/Hyde-Clone ` 
In case you install it using ./install.sh   Hyde-cli do not know the Cloned directory's path. 
you can run `Hyde-install --link --dir ~/HyDE  ` where ~HyDE is the path to the clone directory. 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/40977f33-012b-4f87-ac9a-46e87e7aa3d6)



the repo https://github.com/kRHYME7/Hyde-cli

**Comment by rubiin** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/8222059/8e47ab1f-be10-4216-94e4-718b4420bc81)
I did this install on Endeavor-kde but didnt encounter any issue.  Did you by any chance modified anything?

**Comment by shivamsinghcse** [comment]
> Strange, can you send more screenshot of the different waybar layouts? When I say, layout I'm talking about these: ![image](https://private-user-images.githubusercontent.com/53417443/329760755-408f0d6d-6245-41d4-9dca-209014a7f409.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjEyNTYsIm5iZiI6MTcxNTQyMDk1NiwicGF0aCI6Ii81MzQxNzQ0My8zMjk3NjA3NTUtNDA4ZjBkNmQtNjI0NS00MWQ0LTlkY2EtMjA5MDE0YTdmNDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA5NDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzN2NhNDQ5YzZjZTUwMDc2ODljNzk2NzlhYzUyOTA4NTdjMGJhZWVkMjFkOGM0MTZiNjk4MGJkMjM3ZjRkZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KYCLXmfpCSM66d74f4s6rDC0ucc14XCsLnI_F2h_0t0) ![image](https://private-user-images.githubusercontent.com/53417443/329760775-2a55fc63-b0cd-404b-89ef-b1c494aa1beb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjEyNTYsIm5iZiI6MTcxNTQyMDk1NiwicGF0aCI6Ii81MzQxNzQ0My8zMjk3NjA3NzUtMmE1NWZjNjMtYjBjZC00MDRiLTg5ZWYtYjFjNDk0YWExYmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA5NDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNTZjOTM1MzQwMTM2ZmFlMzQxMGJlODVhYzZjN2NmODBiNDg3OWQ5ZTUzZDUxOGU5MmYwOWU4ZjU1ZTQ5OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.033p_6FgUvj_eCfnqrjJUr7Hm7aVsMpkDGUJ8mw5l6I) ![image](https://private-user-images.githubusercontent.com/53417443/329760790-434314fc-9910-4238-a34b-f2e730cbab51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjEyNTYsIm5iZiI6MTcxNTQyMDk1NiwicGF0aCI6Ii81MzQxNzQ0My8zMjk3NjA3OTAtNDM0MzE0ZmMtOTkxMC00MjM4LWEzNGItZjJlNzMwY2JhYjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA5NDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYjhmZWRmYjU3ODE4YmMwN2ZlZWQ3ZGE3M2RlY2M4ODE2NmQwZjIwZWIzMDhmMTU3NGEwNTBjYTUzNjM4YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OZM_fBA31jiF2LhoIWLfZ6-IwgLNawL7r5F5SFmrjKc)
> 
> keybind to toggle waybar ![image](https://private-user-images.githubusercontent.com/53417443/329761038-e0a3ea4d-9bdf-48b8-91df-7c33622d1ca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjEyNTYsIm5iZiI6MTcxNTQyMDk1NiwicGF0aCI6Ii81MzQxNzQ0My8zMjk3NjEwMzgtZTBhM2VhNGQtOWJkZi00OGI4LTkxZGYtN2MzMzYyMmQxY2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA5NDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNzQxZGM0YzI4NWQ1ZmMwNmI0MmU0YmQ3ZmYxMDkxYzM3ODk5MTBmYzllMTc4NzM5MTFhYWEyMGUzY2VmNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ej0zOdsigX-IDsCdeeamnCymbpDbk-TDseYxCDpoEk)
> 
> Moreover; How did you install the dots, using ./install.sh ?
> 
> I recently push a utility to find mismatched dot files
> 
> command is `Hyde check Config`
> 
> It should work something like this
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/329760352-1a15a3f8-2c72-4edf-9133-97c0f03478c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjEyNTYsIm5iZiI6MTcxNTQyMDk1NiwicGF0aCI6Ii81MzQxNzQ0My8zMjk3NjAzNTItMWExNWEzZjgtMmM3Mi00ZWRmLTkxMzMtOTdjMGYwMzQ3OGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA5NDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YzNiMTJlZDMyYjIwOWE5OWY4OGM5MGEyNTZmMmRiZjc1ODBiOTRhMjAwZDgzMzRjMzNiZmFkZGE5NWI2YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QhgV_3mTZ8z9fk5yDslZKnla2MHsQjD0t4F1OSBJKnc)
> 
> The CLI comes preinstalled together with the dots, but by default the clone directory is ` ~/.cache/hyde/Hyde-Clone` In case you install it using ./install.sh Hyde-cli do not know the Cloned directory's path. you can run `Hyde-install --link --dir ~/HyDE ` where ~HyDE is the path to the clone directory.
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/329760632-40977f33-012b-4f87-ac9a-46e87e7aa3d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjEyNTYsIm5iZiI6MTcxNTQyMDk1NiwicGF0aCI6Ii81MzQxNzQ0My8zMjk3NjA2MzItNDA5NzdmMzMtMDEyYi00Zjg3LWFjOWEtNDZlODdlN2FhM2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA5NDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZjMwMGI2NWM2NmE0YWQxMGJlNTA4ZGE2ZjBjZmVmYjE2ZWU2YmQ1NDJiN2YyMWI0NTg4ZjRiOWQxMWY4ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3JG4HDFRaD9en58PKbPmvRBAJODmb0iVYMEFG4lY5OA)
> 
> the repo https://github.com/kRHYME7/Hyde-cli

![image](https://github.com/prasanthrangan/hyprdots/assets/121515299/1c11296a-fddb-4ae6-8851-b4e1f3b32595)

**Comment by shivamsinghcse** [comment]
> ![image](https://private-user-images.githubusercontent.com/8222059/329763281-8e47ab1f-be10-4216-94e4-718b4420bc81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjE3NzEsIm5iZiI6MTcxNTQyMTQ3MSwicGF0aCI6Ii84MjIyMDU5LzMyOTc2MzI4MS04ZTQ3YWIxZi1iZTEwLTQyMTYtOTRlNC03MThiNDQyMGJjODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDk1NzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjkyNDYwODU5NjMwOTNhYTNmMTM3ZTI1Y2YxOGNlMTc0YjllMWVjNTkyNTMxOGE1YzJhYmI2YTE0OTMzN2QwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7NqdrF5JwbVExzUlHcMUp0t4PQB8H_fYzw5fjrJugyE) I did this install on Endeavor-kde but didnt encounter any issue. Did you by any chance modified anything?

i have used it in garuda kde it work fine in that except some other issue(like keyring issue) currently i am using garuda hyprland which comes with pre-build waybar config but i think installing that script will overwrite the config

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/020d547f-fc93-4aca-95ae-6ec970a004a7)

Please diff these 2 files. I assumed you got some minor spacing error here or something

**Comment by shivamsinghcse** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/121515299/1bcf577e-8f9e-4c8e-a332-3013cc6f4063)

**Comment by shivamsinghcse** [comment]
0|28|bottom|( cpu memory custom/cpuinfo custom/gpuinfo ) ( idle_inhibitor clock )|( hyprland/workspaces hyprland/window )|( backlight network pulseaudio pulseaudio#microphone custom/updates custom/keybindhint ) ( tray battery ) ( custom/wallchange custom/theme custom/wbar custom/cliphist custom/power )
0|28|top|( cpu memory custom/cpuinfo custom/gpuinfo ) ( idle_inhibitor clock )|( hyprland/workspaces hyprland/window )|( backlight network pulseaudio pulseaudio#microphone custom/updates custom/keybindhint ) ( tray battery ) ( custom/wallchange custom/theme custom/wbar custom/cliphist custom/power )
0|28|bottom|( cpu memory custom/cpuinfo custom/gpuinfo ) ( idle_inhibitor clock ) ( hyprland/workspaces )|( hyprland/window )|( backlight network pulseaudio pulseaudio#microphone custom/updates custom/keybindhint ) ( tray battery ) ( custom/wallchange custom/theme custom/wbar custom/cliphist custom/power )
0|28|top|( cpu memory custom/cpuinfo ) ( idle_inhibitor clock ) ( hyprland/workspaces )|( hyprland/window )|( backlight network pulseaudio pulseaudio#microphone custom/updates custom/keybindhint ) ( tray battery ) ( custom/wallchange custom/theme custom/wbar custom/cliphist custom/power )
0||bottom|( hyprland/workspaces hyprland/window )|( idle_inhibitor clock )|( cpu memory custom/cpuinfo custom/gpuinfo ) ( backlight network pulseaudio pulseaudio#microphone custom/updates custom/keybindhint ) ( tray battery ) ( custom/wallchange custom/theme custom/wbar custom/cliphist custom/power )
0||top|( hyprland/workspaces hyprland/window )|( idle_inhibitor clock )|( cpu memory custom/cpuinfo custom/gpuinfo ) ( backlight network pulseaudio pulseaudio#microphone custom/updates custom/keybindhint ) ( tray battery ) ( custom/wallchange custom/theme custom/wbar custom/cliphist custom/power )
1|31|bottom|( custom/power custom/cliphist custom/wbar custom/theme custom/wallchange ) ( wlr/taskbar custom/spotify ) |( idle_inhibitor clock )|( tray battery ) ( backlight network pulseaudio pulseaudio#microphone custom/notifications custom/keybindhint )
0|31|left|( custom/power custom/cliphist custom/wbar custom/theme custom/wallchange ) ( wlr/taskbar custom/spotify ) |( idle_inhibitor clock )|( tray battery ) ( backlight network pulseaudio pulseaudio#microphone custom/keybindhint )
0|31|top|( custom/power custom/cliphist custom/wbar custom/theme custom/wallchange ) ( wlr/taskbar custom/spotify ) |( idle_inhibitor clock )|( tray battery ) ( backlight network pulseaudio pulseaudio#microphone custom/keybindhint )
0|31|right|( custom/power custom/cliphist custom/wbar custom/theme custom/wallchange ) ( wlr/taskbar custom/spotify ) |( idle_inhibitor clock )|( tray battery ) ( backlight network pulseaudio pulseaudio#microphone custom/keybindhint )
0|32|bottom||( custom/power ) ( tray battery ) ( wlr/taskbar idle_inhibitor clock ) ( custom/cliphist ) ( custom/wbar ) ( custom/wallchange ) ( custom/theme )|
0|32|left||( custom/power ) ( tray battery ) ( wlr/taskbar idle_inhibitor clock ) ( custom/cliphist ) ( custom/wbar ) ( custom/wallchange ) ( custom/theme )|
0|32|top||( custom/power ) ( tray battery ) ( wlr/taskbar idle_inhibitor clock ) ( custom/cliphist ) ( custom/wbar ) ( custom/wallchange ) ( custom/theme )|
0|32|right||( custom/power ) ( tray battery ) ( wlr/taskbar idle_inhibitor clock ) ( custom/cliphist ) ( custom/wbar ) ( custom/wallchange ) ( custom/theme )|
0|31|bottom|( cpu memory custom/cpuinfo custom/gpuinfo ) ( idle_inhibitor clock ) ( hyprland/workspaces )|( wlr/taskbar )|( backlight network pulseaudio pulseaudio#microphone custom/updates custom/keybindhint ) ( tray battery ) ( custom/wallchange custom/theme custom/wbar custom/cliphist custom/power )
0|31|top|( cpu memory custom/cpuinfo custom/gpuinfo ) ( idle_inhibitor clock ) ( hyprland/workspaces )|( wlr/taskbar )|( backlight network pulseaudio pulseaudio#microphone custom/updates custom/keybindhint ) ( tray battery ) ( custom/wallchange custom/theme custom/wbar custom/cliphist custom/power )
0|29|bottom|( wlr/taskbar mpris )|( idle_inhibitor clock )|( backlight network pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/theme custom/wbar custom/cliphist custom/power )
0|29|left|( wlr/taskbar mpris )|( idle_inhibitor clock )|( backlight network pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/theme custom/wbar custom/cliphist custom/power )
0|29|top|( wlr/taskbar mpris )|( idle_inhibitor clock )|( backlight network pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/theme custom/wbar custom/cliphist custom/power )
0|29|right|( wlr/taskbar mpris )|( idle_inhibitor clock )|( backlight network pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/theme custom/wbar custom/cliphist custom/power )
0|28|bottom|( custom/power custom/cliphist custom/wbar custom/theme custom/wallchange ) ( idle_inhibitor clock custom/spotify )|( wlr/taskbar )|( tray ) ( backlight network pulseaudio pulseaudio#microphone )
0|28|left|( custom/power custom/cliphist custom/wbar custom/theme custom/wallchange ) ( idle_inhibitor clock custom/spotify )|( wlr/taskbar )|( tray ) ( backlight network pulseaudio pulseaudio#microphone )
0|28|top|( custom/power custom/cliphist custom/wbar custom/theme custom/wallchange ) ( idle_inhibitor clock custom/spotify )|( wlr/taskbar )|( tray ) ( backlight network pulseaudio pulseaudio#microphone )
0|28|right|( custom/power custom/cliphist custom/wbar custom/theme custom/wallchange ) ( idle_inhibitor clock custom/spotify )|( wlr/taskbar )|( tray ) ( backlight network pulseaudio pulseaudio#microphone )

**Comment by kRHYME7** [comment]
Lemme fire up a garuda kde and test

**Comment by shivamsinghcse** [comment]
> So strange the config.ctl looks find
> 
> Let me fire up a garuda kde and test (🐢 ... 🌐)

i am using garuda hyprland  https://iso.builds.garudalinux.org/iso/latest/community/hyprland/latest.iso?r2=1

**Comment by kRHYME7** [comment]
LOL the garuda waybar is overriding everything! 


You can actually see the correct Hyde waybar theme if you run it with flags 
` waybar --config ~/.config/waybar/config.jsonc --style ~/.config/waybar/style.css `
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/0443ac92-14fb-445f-b718-a45be272321c)

So this one will give as the default user executions
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/f875dc93-9719-4ec8-b69d-36651cbab84d)

If you understand the situation, we might need to add patches for Hyde to override Garuda's waybar or modify their waybar spin . 

Or HyDE will adjust and handle it in user level. This seemed a neat solution. 
 Edit the ` ~/.local/share/bin/wbarconfgen.sh ` then change the waybar line to this 
```
waybar --config ~/.config/waybar/config.jsonc --style ~/.config/waybar/style.css
``

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/897a179d-80e1-448f-9d29-280af9510bbc)

If you want you can do a PR for this in this repo.

**Comment by rubiin** [comment]
This is what I was afraid when I tried hyprdots, config overide by my existing system.I was gonna do a fresh endeavour hyperland install but thought I would encounter something like this so Instead used Kde version.

**Comment by kRHYME7** [comment]
Do the endeavor have Hyprland spin.
I tried the minimal EOS  in VM to test my Commits but no issues on configs.IMO it's better than Garadu.😁 But garuda is pretty fast I guess when using the foot terminal also everything is set up and ready. That's how shallow I experience both though.

**Comment by rubiin** [comment]
> Do the endeavor have Hyprland spin. I tried the minimal EOS in VM to test my Commits but no issues on configs.IMO it's better than Garadu.😁 But garuda is pretty fast I guess when using the foot terminal also everything is set up and ready. That's how shallow I experience both though.

I think there is a community spin available. I used to use plain arch but since I own multiple devices , setting each was a pain and endeavor was closest to vanilla arch . I could get arch running under 5 mins. I tried garuda but was distracted with the vibrant color schemes :D

**Comment by shivamsinghcse** [comment]
I fixed the issue Thank you very much...
