### ISSUE TITLE
[Bug]: Error during installation 

### ISSUE THREAD

**Issue by nvn152** [prasanthrangan/hyprdots#1477]
### Description

A failure occurred in build()
Aborting 

And then it reboots into minimal hyprland installation without hyprdots.

### Steps to Reproduce

1. Mininal arch install 
2. Clone the repo
3. Execute the install script 

### Expected Behavior

Successful installation of hyprdots

### Actual Behavior

Exit status 4

### Screenshots
![PXL_20240511_105502003](https://github.com/prasanthrangan/hyprdots/assets/133593113/5800d784-5d35-4a44-9eec-e337d11dcbed)

**Comment by kRHYME7** [comment]
that package is broken upstream  

try to install using this command ` Hyde-install ` 

if the above command is not available ` yay -Sy hyde-cli-git `

**Comment by nvn152** [comment]
> that powerlevel10k package is broken upstream
> 
> try to install using this command `Hyde-install`
> 
> if the above command is not available `yay -Sy hyde-cli-git`

cat: /run/users/custom-app-list: No such file or directory 

![PXL_20240511_115233080](https://github.com/prasanthrangan/hyprdots/assets/133593113/1d255de8-6018-4f04-be54-bf34853f1646)

**Comment by kRHYME7** [comment]
@nvn152  Thanks! I already fix it upstream please  update the package

**Comment by nvn152** [comment]
Thanks now it worked

**Comment by nvn152** [comment]
Now different error popped in post install.

![PXL_20240511_122727693](https://github.com/prasanthrangan/hyprdots/assets/133593113/915557a6-2e10-489d-8e02-919e180358df)

**Comment by kRHYME7** [comment]
You tried rerunning ` Hyde-install `?

**Comment by rubiin** [comment]
@nvn152 can you show output of `ls -ah`

**Comment by nvn152** [comment]
Here's what's happening, running Hyde-install and completing its setup, it prompts for a reboot. Following the reboot, sddm and the hyprland session run smoothly. However, upon subsequent reboots, the system redirects to the tty instead of launching the graphical interface.

![PXL_20240511_131801448 MP](https://github.com/prasanthrangan/hyprdots/assets/133593113/e8453a6d-d304-4690-b637-19628ca3fa8f)

**Comment by kRHYME7** [comment]
Looks good this is `Hyde-install` fault as it is only using some scripts from Hyde repo. 

Will get back to you after i port things 

For now, to fix the display manager   ` systemctl enable sddm ` run this command. This is due to the command stopping mid-execution.

**Comment by nvn152** [comment]
SDDM is functioning correctly now. However, upon running Hyde shell select and choosing the Zsh shell, an error occurs.

![PXL_20240511_181331993](https://github.com/prasanthrangan/hyprdots/assets/133593113/7632feb2-0a7a-4acf-9089-f135a89323cd)

**Comment by kRHYME7** [comment]
Yup, Please the CLI as I already added a patch for that error.

**Comment by rubiin** [comment]
> Here's what's happening, running Hyde-install and completing its setup, it prompts for a reboot. Following the reboot, sddm and the hyprland session run smoothly. However, upon subsequent reboots, the system redirects to the tty instead of launching the graphical interface.
> 
> ![PXL_20240511_131801448 MP](https://private-user-images.githubusercontent.com/133593113/329764235-e8453a6d-d304-4690-b637-19628ca3fa8f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzQyNzgsIm5iZiI6MTcxNTQzMzk3OCwicGF0aCI6Ii8xMzM1OTMxMTMvMzI5NzY0MjM1LWU4NDUzYTZkLWQzMDQtNDY5MC1iNjM3LTE5NjI4Y2EzZmE4Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxMzI2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmZiYmM4OTZkYzZkYzg4ZDJmZjc1NjU5ZTBkYWUyMjA2NmIyOThmMzY1NzdiMDgwMjlmMWU1YTUwYzZlYTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DWZ2IGe06Lo5mPKTFst27mS7sX8y1GKbpWSr-cINKE4)

thats odd there is no .zshrc . If cli doesnt get this fixed ,Maybe you could try to install manually  for the ohmyzsh part.

**Comment by nvn152** [comment]
Yeah, installed oh-my-zsh manually, configured some plugins, and moved some files here and there to get it working.
