### ISSUE TITLE
[Bug]: Rofi and Waybar won't switch workspace  for hyprland v0.40.0 

### ISSUE THREAD

**Issue by aho-emi** [prasanthrangan/hyprdots#1480]
### Description
I cant switch windows from waybar also it appears to get cropped when placed vertically most of the icons gets burried beyond the screen

### Media
https://github.com/prasanthrangan/hyprdots/assets/136156874/af982238-b686-4eaf-9475-c994c02256d1

### Environment

- Linux Distro: ArchLinux,
- Linux Version, output of `uname -a`: linux archlinux x86_64 6.8.9-arch1-2 
- Hyprland Version, output of `hyprctl version`: 0.40.0
- Installation Environment: main hardware
- Other info: resolution 1920x1080

**Comment by aho-emi** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/136156874/6bf4f31a-5f45-4002-b2ee-673523eb1ba0)

**Comment by kRHYME7** [comment]
Change the size `Hyde waybar size 28` will change the size of the current waybar layout.

**Comment by aho-emi** [comment]
> Change the size `Hyde waybar size 28` will change the size of the current waybar layout.


https://github.com/prasanthrangan/hyprdots/assets/136156874/137d905e-a9ad-4509-98dd-0d4abfed3359

**Comment by kRHYME7** [comment]
> also what about the window switching btw

Upstream, check some close discussion, somewhat probably got it fixed.

**Comment by rubiin** [comment]
@kRHYME7 is there a way to set the size of all waybar styles to certain number. Like on my device the nice number is 40. But config.ctl for waybar has default to 28 and everytime I switch to another waybar layout , I have to do it manually

**Comment by kRHYME7** [comment]
"Hyde waybar size $anynumber "

**Comment by aho-emi** [comment]
> > also what about the window switching btw
> 
> Upstream, check some close discussion, someone probably got it fixed.

okay i searched the discussion but didnt find any results.. maybe i can reinstall waybar?

**Comment by kRHYME7** [comment]
it won't solve it.  Let's just wait for an upstream fix.

**Comment by kRHYME7** [comment]
@aho-emi if you're fine installing the ` hyprland-git ` it should fix the issue or wait fot the 0.41. version of hyprland.
