### ISSUE TITLE
[Bug]: flatpak theme issues

### ISSUE THREAD

**Issue by Itz-Abhishek-Tiwari** [prasanthrangan/hyprdots#1481]
### Description

i have just install the fresh arch Linux with HyDE at the time of installing i didn't select the flatpak app installation and now theme is not working 

### Steps to Reproduce

1. Do a fresh install of hyde
2. do not select the flatpak option
3. now don't get the theme

### Expected Behavior

theme should be apply as other apps

### Actual Behavior

default theme by gnome is showing instead of actual theme

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/69257109/57eb07dc-14c6-4b9c-a85d-42205c2d526b)

### Environment:

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`:``` Linux archlinux 6.6.30-2-lts #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:45:29 +0000 x86_64 GNU/Linux ```
- Hyprland Version, output of `hyprctl version`:
``` 
 Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606
```
- Installation Environment: The Main Hardware

**Comment by kRHYME7** [comment]
Lol, labeled as bug, but you skipped the flatpak setup. 

```
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        gtkTheme=$(gsettings get org.gnome.desktop.interface gtk-theme | sed "s/'//g")
        gtkIcon=$(gsettings get org.gnome.desktop.interface icon-theme | sed "s/'//g")

        flatpak --user override --filesystem=~/.themes
        flatpak --user override --filesystem=~/.icons

        flatpak --user override --env=GTK_THEME=${gtkTheme}
        flatpak --user override --env=ICON_THEME=${gtkIcon}
```
 or ` Hyde inject flatpak ` but please update the cli first ` yay -Sy hyde-cli-git `

**Comment by Itz-Abhishek-Tiwari** [comment]
ohh really sorry i thought it was asking for me for installing the flatpak apps not to setup flatpak themeing

**Comment by kRHYME7** [comment]
> ohh really sorry i thought it was asking for me for installing the flatpak apps not to setup flatpak themeing

Actually it installs flatpak plus those apps, so you're right. I already added the inject flatpak function in the CLI  for situations like this.

**Comment by Itz-Abhishek-Tiwari** [comment]
> > ohh really sorry i thought it was asking for me for installing the flatpak apps not to setup flatpak themeing
> 
> Actually it installs flatpak plus those apps, so you're right. I already added the inject flatpak function in the CLI for situations like this.

one more thing i cant able too scroll to the bottom in the Hyde man cli

**Comment by kRHYME7** [comment]
Use arrow keys or swipe or scroll your mouse ? this is a typcial ` less ` command being executed so users can search for keywords

**Comment by kRHYME7** [comment]
if you want to spit it to the terminal `  Hyde man | cat - `

**Comment by Itz-Abhishek-Tiwari** [comment]
> if you want to spit it to the terminal ` Hyde man | cat -`

okay
