### ISSUE TITLE
Text on login screen

### ISSUE THREAD

**Issue by TheTreeTops** [prasanthrangan/hyprdots#1482]
How do I remove the text above the time on the login screen?
![IMG_2998](https://github.com/prasanthrangan/hyprdots/assets/158498287/cd185bf9-f439-4afe-babd-c76f87767ced)

**Comment by mahaveergurjar** [comment]
nsfw sddm #1130

**Comment by rubiin** [comment]
https://github.com/prasanthrangan/hyprdots/discussions/1130#discussioncomment-8861174
Please see this 
This can be closed
