### ISSUE TITLE
[Bug]: with the install script i get error making: zsh-theme-powerlevel10k-exit status 4

### ISSUE THREAD

**Issue by szx-2020** [prasanthrangan/hyprdots#1483]
## Bug Report

i used this : pacman -Sy git
git clone --depth 1 https://github.com/prasanthrangan/hyprdots ~/HyDE
cd ~/HyDE/Scripts
./[install.sh](http://install.sh/) .
-
i used it once but it didn't work so i did a fresh boot and it's the same 
every thing is working good with the install until it reaches installing zsh-theme-powerlevel110k. 
-
src/tag_db.cc:133:43: error: ignoring return value of ‘std::unique_lock<_Mutex>::unique_lock(mutex_type&) [with _Mutex = std::mutex; mutex_type = std::mutex]’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  133 |   if ((std::unique_lock<std::mutex>(mutex_), id2name_dirty_)) {
      |                                           ^
In file included from /usr/include/c++/14.1.1/condition_variable:43,
                 from src/tag_db.h:27,
                 from src/tag_db.cc:18:
/usr/include/c++/14.1.1/bits/unique_lock.h:70:16: note: declared here
   70 |       explicit unique_lock(mutex_type& __m)
      |                ^~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:32: obj/tag_db.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: zsh-theme-powerlevel10k-exit status 4
loading packages...
resolving dependencies...
looking for conflicting packages...

Package (2)    New Version  Net Change

wlogout        1.2.2-0        0.12 MiB
wlogout-debug  1.2.2-0        0.08 MiB

Total Installed Size:  0.20 MiB

:: Proceed with installation? [Y/n] y
(2/2) checking keys in keyring                                [----------------------------------] 100%
(2/2) checking package integrity                              [----------------------------------] 100%
(2/2) loading package files                                   [----------------------------------] 100%
(2/2) checking for file conflicts                             [----------------------------------] 100%
(2/2) checking available disk space                           [----------------------------------] 100%
:: Processing package changes...
(1/2) installing wlogout                                      [----------------------------------] 100%
(2/2) installing wlogout-debug                                [----------------------------------] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
checking dependencies...
:: hyprland optionally requires cmake: to build and install plugins using hyprpm
:: hyprland optionally requires meson: to build and install plugins using hyprpm

Package (8)  Old Version  Net Change

cppdap       1.58.0-1      -1.62 MiB
libuv        1.48.0-2      -0.58 MiB
ninja        1.12.0-2      -0.37 MiB
python-tqdm  4.66.4-1      -0.60 MiB
rhash        1.4.4-1       -0.32 MiB
cmake        3.29.3-1     -73.16 MiB
meson        1.4.0-5      -12.42 MiB
scdoc        1.11.3-1      -0.03 MiB

Total Removed Size:  89.10 MiB

:: Do you want to remove these packages? [Y/n] 
:: Processing package changes...
(1/8) removing cmake                                          [----------------------------------] 100%
(2/8) removing rhash                                          [----------------------------------] 100%
(3/8) removing libuv                                          [----------------------------------] 100%
(4/8) removing cppdap                                         [----------------------------------] 100%
(5/8) removing scdoc                                          [----------------------------------] 100%
(6/8) removing meson                                          [----------------------------------] 100%
(7/8) removing python-tqdm                                    [----------------------------------] 100%
(8/8) removing ninja                                          [----------------------------------] 100%
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Updating the MIME type database...
(3/4) Updating icon theme caches...
(4/4) Updating the desktop file MIME type cache...
 -> Failed to install the following packages. Manual intervention is required:
zsh-theme-powerlevel10k - exit status 4

**Comment by connorjjantzi** [comment]
I also had the same issue so I referenced the powerlevel10k github page and it specifically said not to use the ```zsh-theme-powerlevel10k``` package and instead use the ```zsh-theme-powerlevel10k-git``` package. Manually installing that package and restarting the install script worked for me. Not sure if there is a reason why they don't use the -git package but I think it should be changed. Reference: [powerlevel10k GitHub](https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#arch-linux)

**Comment by szx-2020** [comment]
> I also had the same issue so I referenced the powerlevel10k github page and it specifically said not to use the `zsh-theme-powerlevel10k` package and instead use the `zsh-theme-powerlevel10k-git` package. Manually installing that package and restarting the install script worked for me. Not sure if there is a reason why they don't use the -git package but I think it should be changed. Reference: [powerlevel10k GitHub](https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#arch-linux)

thx i downloaded it, but the default theme didn't change idk why (i rebooted)

**Comment by kRHYME7** [comment]
Hey your package manager did not automatically switch it for you?

like if the stable is not installed it will be  changed to -git?

does installing the -git fix the installation?  If yes  I will do a quick fix.

**Comment by szx-2020** [comment]
> Hey your package manager did not automatically switch it for you?
> 
> like if the stable is not installed it will be changed to -git?
> 
> does installing the -git fix the installation? If yes I will do a quick fix.

the package manager did not automatically switch to it

no it didn't install -git i did it manually 

the installation is fine but the only issue is zsh-theme, plus it didn't change the full theme and i don't know how to do it my self so i'm just sitting here with a lot of useless files. 
the theme is applied to rofi and the google text box that shows when you get in full screen and the thing that shows when you turn on the pc: 
- arch linux
- arch linux extra settings
- etc

**Comment by connorjjantzi** [comment]
I used yay and I got the same issue that was shown here.  It just aborts the install script and shows the following: 
```
-> Failed to install the following packages. Manual intervention is required: 
zsh-theme-powerlevel10k - exit status 4
```
Installing the -git package manually fixed the issue for me and is the recommended package on the official powerlevel10k GitHub.

As to the other problems described here I'm not sure, but changing the package to the -git version should at least stop the install script from failing.

Perhaps @szx-2020 could provide some screenshots or more detailed information on what wasn't actually applied.

**Comment by szx-2020** [comment]
> I used yay and I got the same issue that was shown here. It just aborts the install script and shows the following:
> 
> ```
> -> Failed to install the following packages. Manual intervention is required: 
> zsh-theme-powerlevel10k - exit status 4
> ```
> 
> Installing the -git package manually fixed the issue for me and is the recommended package on the official powerlevel10k GitHub.
> 
> As to the other problems described here I'm not sure, but changing the package to the -git version should at least stop the install script from failing.
> 
> Perhaps @szx-2020 could provide some screenshots or more detailed information on what wasn't actually applied.

the only issue is zsh theme the rest is my problem, i don't know how to apply the files and configurations

**Comment by kRHYME7** [comment]
@szx-2020 

 ` Hyde shell select ` then choose a shell it will try to install missing files for the shell prompt.

But if you did not use the CLI upon installation, use ` Hyde-install --link --dir  ~/HyDE `  where the ~/HyDE  is the path to the clone directory

**Comment by szx-2020** [comment]
> @szx-2020
> 
> `Hyde shell select` then choose a shell it will try to install missing files for the shell prompt.
> 
> But if you did not use the CLI upon installation, use `Hyde-install --link --dir ~/HyDE` where the ~/HyDE is the path to the clone directory

damn it worked ! you are a legend 🙃 thank you
