### ISSUE TITLE
question about the script

### ISSUE THREAD

**Issue by ferkaua** [prasanthrangan/hyprdots#1485]
I'm now venturing into this side of hyprland and I'm very interested in this script, I have a question, does it also work well with AMD video cards or just NVIDIA?

**Comment by kRHYME7** [comment]
It works better with nonnvidia actually. The nvidia script part just handles modesetting for nvidia to render Hyprland upon boot.

The Script does not handle anything special for Non-nvidia though.

If you're installing this on Endeavor OS or Garuda Hyprland it should work out of the box.

For Vanilla arch, well, it's the user's responsibility to install special drivers for their hardware if they need to.But I'm confident that it would still render Hyprland by default.

**Comment by rubiin** [comment]
> I'm now venturing into this side of hyprland and I'm very interested in this script, I have a question, does it also work well with AMD video cards or just NVIDIA?

I am using it on amd video card and the chip as well . No problems so far

**Comment by Skerse** [comment]
When you ask questions in the future, can you ask them in discussions? This place is mostly only for issues or enhancements.

Looks like your question was answered, and you have everything going well, so i'll close this as complete.
