### ISSUE TITLE
[Issue]: Rofi application launcher 

### ISSUE THREAD

**Issue by Chiro145** [prasanthrangan/hyprdots#1486]
## Bug Report 

**Rofi issue
After updating Hyde and Hyprland I had this problem.
Rofi sometimes has this bug.**

### Steps to Reproduce

[Super + A]

### Actual Behavior

Looks like the rofi app launcher alignment has gone wrong

### Screenshots

**Before:**
![image](https://github.com/prasanthrangan/hyprdots/assets/87656808/358d4cd0-f39b-490c-b06e-3296ad85cf85)
**After:**
![image](https://github.com/prasanthrangan/hyprdots/assets/87656808/4b09de84-acc8-448e-bfa0-915610f27ad9)

e.g.,

- Linux Distro: [ArchLinux]
- Hyprland Version, output of `hyprctl version`: v0.40.0-32-ge4e84064
- Installation Environment: [On The Main Hardware]

**Comment by kRHYME7** [comment]
Thanks for the fast notice! Unfortunately someone is much faster to report this. https://github.com/prasanthrangan/hyprdots/issues/1473

dupe, please utilize the search filter next time
