### ISSUE TITLE
webcord file picker issue

### ISSUE THREAD

**Issue by kevaldonga** [prasanthrangan/hyprdots#1488]
I having this weird padding around webcord file picker
![image](https://github.com/prasanthrangan/hyprdots/assets/100512807/1839799e-8ac6-43ca-8974-6b219055e1cf)

It is only happening in webcord.

**Comment by kRHYME7** [comment]
probably running on xwayland? 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/f349018b-34bd-41cc-a1ba-b013fa1aa475)

**Comment by kRHYME7** [comment]
https://github.com/flathub/io.github.spacingbat3.webcord

**Comment by kRHYME7** [comment]
Fixed use flatseal to force wayland.  do not know why it's not respecting it if I run in the terminal but this works. 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/03e7ab4d-4318-4ff3-8d61-c1a6057d2316)

Preview

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/0684a17e-e7cd-45b2-b675-66238b2a2497)

**Comment by kevaldonga** [comment]
It is solved now
