### ISSUE TITLE
[Bug]: Wallpaper doesn't fit the screen when changing monitor scale

### ISSUE THREAD

**Issue by KevinNitroG** [prasanthrangan/hyprdots#1489]
### Description

The wallpaper doesn't fit the screen when changing scale of the monitor in `hyprland.conf`

### Steps to Reproduce

1. Change scale in `monitor` in `hyprland.conf`
	![image](https://github.com/prasanthrangan/hyprdots/assets/86353526/3f017e40-6d71-41ed-adca-216907258089)

### Expected Behavior

The wallpaper should fit the screen.

### Actual Behavior

The wallpaper was minimised.

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/86353526/7e6d7ff6-e463-4849-9493-f1131cb19a90)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: ArchLinux
- Linux Version, output of `6.8.9-arch1-2`:
- Hyprland Version, output of `0.40.0`:
- Installation Environment: On The Main Hardware
- Display Resolution: 1920x1080@60

**Comment by kRHYME7** [comment]
you already updated `swwww `?

**Comment by KevinNitroG** [comment]
> you already updated `swwww `?
> 
> #1317

Thank you. I will close this issue and follow the #1317 one.
