### ISSUE TITLE
[Feature Request]: Implementation of Nix flake or configuration

### ISSUE THREAD

**Issue by D3vil0p3r** [prasanthrangan/hyprdots#1495]
### Description

It would be wonderful to have this Hyprland configuration in NixOS. Could you please create a `.nix` file for it or a flake?

### Use Case

The use case is to allow NixOS users to use your Hyprland configuration.

**Comment by kRHYME7** [comment]
Hi @D3vil0p3r  it would be a long discussion to achieve this.  Yes we can but it might not be usable on nix out of the box.  

 I hope someone can make a nix fork of Hyde. 
Here's a related discussion regarding this. Please contribute your insights there. 
https://github.com/prasanthrangan/hyprdots/discussions/166
