### ISSUE TITLE
Adding Arabic as an input language option to the keyboard?

### ISSUE THREAD

**Issue by ZiadMostafaGit** [prasanthrangan/hyprdots#1498]
## Question

Is there a simple method to add Arabic as an input language to the keyboard without having to deal with complicated configurations?

**Comment by Artavazdpet** [comment]
https://github.com/prasanthrangan/hyprdots/issues/1339#issuecomment-2068669775

You can do something like this

**Comment by kRHYME7** [comment]
How complicated is complicated by the way ? 

^^^^
https://github.com/prasanthrangan/hyprdots/issues/1339#issuecomment-2068669775

**Comment by Skerse** [comment]
Please use [discussions](https://github.com/prasanthrangan/hyprdots/discussions) for questions in the future please.

**Comment by abusen333** [comment]
## How to Add Arabic Keyboard Layout and Toggle Using Super + Space in Hyprland

This guide will help you set up a dual keyboard layout (English and Arabic) and configure the toggle using the Super (Windows) key + Space in Hyprland on Linux. This method has been tested and works as expected.

### Step 1: Modify the Configuration File

Navigate to the Hyprland configuration file located at:
/home/a/.config/hypr/hyprland.confg

Update the input block as follows:


```
input {
    kb_layout = us,ara  # Specifies US and Arabic keyboard layouts
    kb_variant = ,       # No specific variants are used
    kb_options = grp:win_space_toggle  # Sets Super + Space as the toggle
    follow_mouse = 1

    touchpad {
        natural_scroll = no  # Disables natural scrolling
    }

    sensitivity = 0
    force_no_accel = 1
}
```

### Step 2: Reload Hyprland
To apply the changes, reload the Hyprland configuration. Open your terminal and execute the following command:
`systemctl restart hyprland`

### Note

_This configuration enables you to toggle between English and Arabic keyboard layouts using the Super key (Windows key) + Space. This feature is especially useful for bilingual users who need to switch between these two languages frequently._

**Comment by mrmostafaxd** [comment]
> kb_options = grp:win_space_toggle  # Sets Super + Space as the toggle

Instead of using kb_options to set the binding, you can use/modifiy the [existing binding](https://github.com/prasanthrangan/hyprdots/blob/bb0c6a95b1e044c54c02341752617738080074cf/Configs/.config/hypr/keybindings.conf#L77), which enables the toggling between the keyboard layouts in addition to sending a notification using `notify-send`.

**Comment by haytham-med** [comment]
You can set an arabic variant if you want arabic letters:

` kb_variant = ,qwerty_digits`
