### ISSUE TITLE
Unload Font or graphics

### ISSUE THREAD

**Issue by RedSnoww12** [prasanthrangan/hyprdots#15]
is it normal for it to be like this?
![image](https://github.com/prasanthrangan/hyprdots/assets/70609663/ced22afd-0616-40b9-bed8-3fc8c93071f8)

**Comment by prasanthrangan** [comment]
Hi,

This does not look right... The padding for wlogout is set as 
`wlogout -b 2 -c 0 -r 0 -L 930 -R 930 -T 300 -B 300 --protocol layer-shell`
in hyprland.conf and waybar config.jsonc

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/b4d94184-78f9-4b5a-9535-f6f2cc4f4b28)

Here please try adjusting the left `-L 930`, right  `-R 930`, top `-T 300` and bottom `-B 300` padding values to fit your screen resolution -

![230614_20h16m56s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/106020512/c74f631f-6f88-4584-bd47-6e61c38ab1ab)

**Comment by RedSnoww12** [comment]
It seems to be good 
![image](https://github.com/prasanthrangan/hyprdots/assets/70609663/3e6cab6f-a485-40c5-a2ed-165e6a8c54fa)
I have a nvidia rtx ect... 
Can I look in a log file and share it to see what's wrong?

**Comment by prasanthrangan** [comment]
> It seems to be good ![image](https://user-images.githubusercontent.com/70609663/246390864-3e6cab6f-a485-40c5-a2ed-165e6a8c54fa.png) I have a nvidia rtx ect... Can I look in a log file and share it to see what's wrong?

Hi, there is nothing wrong with your nvidia card, its just the padding used for `wlogout`.
so please adjust it for your resolution, try with lower value like `-L 500 -R 500` as shown here -

https://github.com/prasanthrangan/hyprdots/assets/106020512/d7f129dd-06bc-46c3-ae3b-e5896bc9d066

**Comment by RedSnoww12** [comment]
Ok it's better with this conf:
![image](https://github.com/prasanthrangan/hyprdots/assets/70609663/ba42d2b0-0c6a-49b6-99db-3277c03a60b2)
![image](https://github.com/prasanthrangan/hyprdots/assets/70609663/50837615-ad9c-4fac-8d69-efdcb2120884)
How can I see if some thing else is bad configured or not load ?

**Comment by prasanthrangan** [comment]
the screen resolution may affect these config files as well -
```
~/.config/hypr/themes/*.conf # mainly for font size
~/.config/rofi/*.rasi # for rofi menu size
~/.config/waybar/* # for bar height and font
```
So you can try adjusting these.
