### ISSUE TITLE
wallpaper

### ISSUE THREAD

**Issue by Aman49362** [prasanthrangan/hyprdots#150]
I am new to linux commuity and i installed your project it is very well made but i am confused about changing my wallpaper to an custom one
![image](https://github.com/prasanthrangan/hyprdots/assets/83559417/7c750cd5-540a-4498-8d17-0c41848bac51)
And it will be helpful if you can guide we with the theme selector issue

**Comment by prasanthrangan** [comment]
Hi, Thank you!

In `~/.config/hypr/scripts/themeselect.sh` can you please try changing this line -

```
r_override="element{border-radius:${elem_border}px;} element-icon{border-radius:${icon_border}px;size:${x_monres}px;}"
```
to this -
```
r_override="element{border-radius:${elem_border}px;} element-icon{border-radius:${icon_border}px;}"
```

and then try theme select again.

**Comment by Aman49362** [comment]
> Hi, Thank you!
> 
> In `~/.config/hypr/scripts/themeselect.sh` can you please try changing this line -
> 
> ```
> r_override="element{border-radius:${elem_border}px;} element-icon{border-radius:${icon_border}px;size:${x_monres}px;}"
> ```
> 
> to this -
> 
> ```
> r_override="element{border-radius:${elem_border}px;} element-icon{border-radius:${icon_border}px;}"
> ```
> 
> and then try theme select again

it is the same

**Comment by prasanthrangan** [comment]
hmm ok, whats your screen resolution?

can you also adjust the icon size in `~/.config/rofi/themeselect.rasi` -
```
element-icon {
    size:                        33%;
```
try decreasing this size to fit your screen res.

**Comment by Aman49362** [comment]
my screen res is 1366x768 and it still doesnt work

**Comment by prasanthrangan** [comment]
Hi, could you please try these steps -

1) remove this line in ~/.config/hypr/scripts/themeselect.sh -
```
r_override="element{border-radius:${elem_border}px;} element-icon{border-radius:${icon_border}px;size:${x_monres}px;}"
```

2) decrease icon size in ~/.config/rofi/themeselect.rasi -
```
element-icon {
    size:                        33%;
```

3) check output of theme list as below -
```
cat $HOME/.config/swww/wall.ctl
```

4) run it from terminal and check if gives any error -
```
cd ~/.config/hypr/scripts
./themeselect.sh
```

**Comment by Aman49362** [comment]
It gave this error
![image](https://github.com/prasanthrangan/hyprdots/assets/83559417/c3dacdb6-5365-46a3-a16f-209f4f441dff)

**Comment by mahaveergurjar** [comment]
you can add your custom wallpaper in the wallpaper theme directory  to which theme you are using Add your wallpaper in those theme folder

open Dolphin press ctrl+h or show a hidden directories & files
path: .config/swww/
Then open  the theme  directory which theme you are using and then add your wallpaper to this directory

**Comment by mahaveergurjar** [comment]
> Syntax error I think you added more brackets or missing Bracket

**Comment by kRHYME7** [comment]
Feel free to reopen this if necessary.
