### ISSUE TITLE
[Bug]: Rofi, Theme selector and wallpaper selector not launching

### ISSUE THREAD

**Issue by zenghost1** [prasanthrangan/hyprdots#1500]
## Bug Report
I can't launch Rofi for some reason after I did a package upgrade after a long time and now. During the upgrade it was showing syntax error in conf files, I just waited for it to upgrade. But now, it is just unresponsvie. I have tried rofi -show drun in the terminal as well but seems to get no response. Also, my theme selector and wallpaper selector are not showing up as well. 

### Description
I assumed that my script is broken. So, I did a fresh install with Hyde. Last time I updated was just after the breaking transition and it wasn't officially named Hyde. Now, to my knowledge the scripts are fine. I tried launching rofi through terminal and it still doesn't work.

### Expected Behavior

ROFI launches on SUPER + A
Theme selector shows up on SUPER + SHIFT + W
Wallpaper selector shows up on SUPER + SHIFT + T

### Actual Behavior

All are unresponsive

- Linux Distro: ArchLinux
- Linux archlinux 6.8.9-arch1-2 #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000 x86_64 GNU/Linux
- Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606
- Installation Environment: Lenovo ideapad gaming laptop

**Comment by zenghost1** [comment]
PS: first time opening issue, please let me know if I accidentally did something wrong.

**Comment by zenghost1** [comment]
PS: first time opening issue, please let me know if I accidentally did something wrong.

**Comment by kRHYME7** [comment]
reboot

**Comment by kevaldonga** [comment]
$HOME/.local/share/bin rofi and sww shell files are in this directory. for 3 commands not working you has 3 shell files in this directory.
- wallpaper select - swwwallselect.sh
- rofi seach - rofilaunch.sh
- theme select - themeselect.sh

can you run above shell files and show the output.

also theme select menu has keybing super + shift + T

**Comment by kRHYME7** [comment]
The Cli got this Utility to check what the files diff. Might as well find this usefull 

` Hyde check Config `
checkout what you might have missed 


if it gives errors 

` Hyde-intstall --link --dir  ~/HyDE ` ~/HyDE is your clone directory.

**Comment by zenghost1** [comment]
> $HOME/.local/share/bin rofi and sww shell files are in this directory. for 3 commands not working you has 3 shell files in this directory.
> 
>     * wallpaper select - swwwallselect.sh
> 
>     * rofi seach - rofilaunch.sh
> 
>     * theme select - themeselect.sh
> 
> 
> can you run above shell files and show the output.
> 
> also theme select menu has key bindigg super + shift + T

Apparently it gives nothing as output.....
![image](https://github.com/prasanthrangan/hyprdots/assets/89266411/1306725a-dc41-4f9f-8843-4fd303f1e6b2)
Yes I meant super+shift+t accidentally switched them..

**Comment by zenghost1** [comment]
> The Cli got this Utility to check what the files diff. Might as well find this usefull
> 
> `Hyde check Config` ![image](https://private-user-images.githubusercontent.com/53417443/330375868-de674bdd-7b6f-4d92-91c2-ebe3180d5904.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODA0NjEsIm5iZiI6MTcxNTY4MDE2MSwicGF0aCI6Ii81MzQxNzQ0My8zMzAzNzU4NjgtZGU2NzRiZGQtN2I2Zi00ZDkyLTkxYzItZWJlMzE4MGQ1OTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA5NDkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5N2Y1YTk2NTY5NTMyMTU3NTNlZGM5YjdjMzE5YzljZjk3ZjA4ZmRjN2NlNDkxOGU2NjBhMWZkYTQzMDRkODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bastwLknbEJtd2zdz8_bRNRKVF1eTAHsOPubvAC_Yqc) checkout what you might have missed. Also remove now the old Hyprdots folder
> 
> if it gives errors
> 
> `Hyde-intstall --link --dir ~/HyDE` ~/HyDE is your clone directory.

Ok this one might help!! I got a lot of mismatch for rofi styles...

```console
❯ Hyde check Config
[preserved] /home/ghost/.config/Code - OSS/User/settings.json
[preserved] /home/ghost/.config/Code/User/settings.json
[wallbash] /home/ghost/.config/Kvantum/wallbash/wallbash.kvconfig
[wallbash] /home/ghost/.config/Kvantum/wallbash/wallbash.svg
[missing] Directory: /home/ghost/.config/MangoHud
[mismatch] /home/ghost/.config/dolphinrc != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/dolphinrc
[dynamic] /home/ghost/.config/dunst/dunstrc
[wallbash] /home/ghost/.config/dunst/icons/hyprdots.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/muted-mic.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/muted-speaker.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/unmuted-mic.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/unmuted-speaker.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-0.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-10.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-100.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-15.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-20.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-25.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-30.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-35.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-40.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-45.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-5.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-50.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-55.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-60.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-65.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-70.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-75.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-80.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-85.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-90.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-95.svg
[wallbash] /home/ghost/.config/dunst/wallbash.conf
[missing] Directory: /home/ghost/.config/fish
[mismatch] /home/ghost/.config/gtk-3.0/settings.ini != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/gtk-3.0/settings.ini
[mismatch] /home/ghost/.config/hyde/hyde.conf != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/hyde/hyde.conf
[mismatch] /home/ghost/.config/hypr/hyprland.conf != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/hypr/hyprland.conf
[mismatch] /home/ghost/.config/hypr/keybindings.conf != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/hypr/keybindings.conf
[mismatch] /home/ghost/.config/hypr/monitors.conf != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/hypr/monitors.conf
[missing] File: /home/ghost/.config/hypr/monitors.t2
[preserved] /home/ghost/.config/hypr/nvidia.conf
[dynamic] /home/ghost/.config/hypr/themes/theme.conf
[mismatch] /home/ghost/.config/hypr/userprefs.conf != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/hypr/userprefs.conf
[missing] File: /home/ghost/.config/hypr/userprefs.t2
[mismatch] /home/ghost/.config/kitty/kitty.conf != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/kitty/kitty.conf
[wallbash] /home/ghost/.config/kitty/theme.conf
[missing] File: /home/ghost/.config/libinput-gestures.conf
[missing] Directory: /home/ghost/.config/lsd
[missing] Directory: /home/ghost/.config/lsd
[missing] Directory: /home/ghost/.config/lsd
[wallbash] /home/ghost/.config/qt5ct/colors.conf
[mismatch] /home/ghost/.config/qt5ct/qt5ct.conf != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/qt5ct/qt5ct.conf
[dynamic] /home/ghost/.config/qt6ct/colors.conf
[mismatch] /home/ghost/.config/qt6ct/qt6ct.conf != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/qt6ct/qt6ct.conf
[missing] File: /home/ghost/.config/rofi/assets/notification.png
[missing] File: /home/ghost/.config/rofi/assets/style_10.png
[missing] File: /home/ghost/.config/rofi/assets/style_11.png
[missing] File: /home/ghost/.config/rofi/assets/style_12.png
[missing] File: /home/ghost/.config/rofi/assets/wallbash_mode.png
[mismatch] /home/ghost/.config/rofi/clipboard.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/clipboard.rasi
[missing] File: /home/ghost/.config/rofi/notification.rasi
[mismatch] /home/ghost/.config/rofi/quickapps.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/quickapps.rasi
[missing] File: /home/ghost/.config/rofi/selector.rasi
[mismatch] /home/ghost/.config/rofi/steam/gamelauncher_1.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/steam/gamelauncher_1.rasi
[mismatch] /home/ghost/.config/rofi/steam/gamelauncher_2.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/steam/gamelauncher_2.rasi
[mismatch] /home/ghost/.config/rofi/steam/gamelauncher_3.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/steam/gamelauncher_3.rasi
[mismatch] /home/ghost/.config/rofi/steam/gamelauncher_4.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/steam/gamelauncher_4.rasi
[mismatch] /home/ghost/.config/rofi/steam/gamelauncher_5.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/steam/gamelauncher_5.rasi
[mismatch] /home/ghost/.config/rofi/styles/style_1.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/styles/style_1.rasi
[missing] File: /home/ghost/.config/rofi/styles/style_10.rasi
[missing] File: /home/ghost/.config/rofi/styles/style_11.rasi
[missing] File: /home/ghost/.config/rofi/styles/style_12.rasi
[mismatch] /home/ghost/.config/rofi/styles/style_2.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/styles/style_2.rasi
[mismatch] /home/ghost/.config/rofi/styles/style_3.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/styles/style_3.rasi
[mismatch] /home/ghost/.config/rofi/styles/style_4.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/styles/style_4.rasi
[mismatch] /home/ghost/.config/rofi/styles/style_5.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/styles/style_5.rasi
[mismatch] /home/ghost/.config/rofi/styles/style_6.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/styles/style_6.rasi
[mismatch] /home/ghost/.config/rofi/styles/style_7.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/styles/style_7.rasi
[mismatch] /home/ghost/.config/rofi/styles/style_8.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/styles/style_8.rasi
[mismatch] /home/ghost/.config/rofi/styles/style_9.rasi != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.config/rofi/styles/style_9.rasi
[wallbash] /home/ghost/.config/rofi/theme.rasi
[missing] File: /home/ghost/.config/rofi/wallbash.rasi
[preserved] /home/ghost/.config/waybar/config.ctl
[dynamic] /home/ghost/.config/waybar/config.jsonc
[wallbash] /home/ghost/.config/waybar/theme.css
[dynamic] /home/ghost/.local/share/dolphin/dolphinstaterc
[mismatch] /home/ghost/.p10k.zsh != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.p10k.zsh
[mismatch] /home/ghost/.zshrc != /home/ghost/.cache/hyde/Hyde-Clone/Configs/.zshrc
=======================================================================================
```

**Comment by kevaldonga** [comment]
> `Hyde-intstall --link --dir ~/HyDE` ~/HyDE is your clone directory.
do this

**Comment by kRHYME7** [comment]
` Hyde update ` to git pull from upstream 
` Hyde restore Config `  to deploy the Configs to you local. 

Please choose Sync if you want to not want to overwrite the entire folder.  ` Overwrite ` if it's fine. 
Preserve files that needs to be Preserved like .zshrc etc 
 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/2780db2e-4136-4a32-9fe5-119dad4748d1)

**Comment by zenghost1** [comment]
> you are supposed to run those sh files, and run this `Hyde check Config` check if you have different files than the repo

Wait!! I did run them or am I missing something? I am questioning myself too much now.

> Your configs are broken in so many levels.
> 
> `Hyde update` to git pull from upstream `Hyde restore Config` to deploy the Configs to you local.
> 
> Please choose Sync if you don't want to overwrite the entire folder. `Overwrite` if it's fine. Preserve files that needs to be Preserved like .zshrc etc
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/330379890-2780db2e-4136-4a32-9fe5-119dad4748d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODE1MDIsIm5iZiI6MTcxNTY4MTIwMiwicGF0aCI6Ii81MzQxNzQ0My8zMzAzNzk4OTAtMjc4MGRiMmUtNDEzNi00YTMyLTlmZTUtMTE5ZGFkNDc0OGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEwMDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNTMwMDBjMTZmZmFiZjFiM2MyYzQwMDg3Y2VjODdiNzRjYTdkMjVjZmZkMjA4NDQzZTk2OGYwZWM3NWNkNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iHjhcZA6xVrjBU4TyW1Qwy3hCOlg5wvdUyY0o-jWtuw)

Okay I did this, although the mismatch are gone now. The rofi still doesn't launch. 😭 
NEW LOGS for Hyde check Config:
```console
❯ Hyde check Config
[mismatch] /home/ghost/.config/Code - OSS/User/settings.json != /home/ghost/HyDE/Configs/.config/Code - OSS/User/settings.json
[mismatch] /home/ghost/.config/Code/User/settings.json != /home/ghost/HyDE/Configs/.config/Code/User/settings.json
[wallbash] /home/ghost/.config/Kvantum/wallbash/wallbash.kvconfig
[wallbash] /home/ghost/.config/Kvantum/wallbash/wallbash.svg
[missing] Directory: /home/ghost/.config/MangoHud
[dynamic] /home/ghost/.config/dunst/dunstrc
[wallbash] /home/ghost/.config/dunst/icons/hyprdots.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/muted-mic.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/muted-speaker.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/unmuted-mic.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/unmuted-speaker.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-0.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-10.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-100.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-15.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-20.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-25.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-30.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-35.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-40.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-45.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-5.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-50.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-55.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-60.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-65.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-70.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-75.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-80.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-85.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-90.svg
[wallbash] /home/ghost/.config/dunst/icons/vol/vol-95.svg
[wallbash] /home/ghost/.config/dunst/wallbash.conf
[missing] Directory: /home/ghost/.config/fish
[mismatch] /home/ghost/.config/gtk-3.0/settings.ini != /home/ghost/HyDE/Configs/.config/gtk-3.0/settings.ini
[mismatch] /home/ghost/.config/hyde/hyde.conf != /home/ghost/HyDE/Configs/.config/hyde/hyde.conf
[mismatch] /home/ghost/.config/hypr/hyprland.conf != /home/ghost/HyDE/Configs/.config/hypr/hyprland.conf
[missing] File: /home/ghost/.config/hypr/monitors.t2
[dynamic] /home/ghost/.config/hypr/themes/theme.conf
[missing] File: /home/ghost/.config/hypr/userprefs.t2
[wallbash] /home/ghost/.config/kitty/theme.conf
[missing] File: /home/ghost/.config/libinput-gestures.conf
[missing] Directory: /home/ghost/.config/lsd
[missing] Directory: /home/ghost/.config/lsd
[missing] Directory: /home/ghost/.config/lsd
[wallbash] /home/ghost/.config/qt5ct/colors.conf
[mismatch] /home/ghost/.config/qt5ct/qt5ct.conf != /home/ghost/HyDE/Configs/.config/qt5ct/qt5ct.conf
[dynamic] /home/ghost/.config/qt6ct/colors.conf
[mismatch] /home/ghost/.config/qt6ct/qt6ct.conf != /home/ghost/HyDE/Configs/.config/qt6ct/qt6ct.conf
[wallbash] /home/ghost/.config/rofi/theme.rasi
[dynamic] /home/ghost/.config/waybar/config.jsonc
[wallbash] /home/ghost/.config/waybar/theme.css
========================================================================================================================================================================
```

**Comment by kRHYME7** [comment]
please exec this ` themeselect.sh `

**Comment by kRHYME7** [comment]
The script should work even the file is missing. So this one is not the issue. 

I htink you got no issues with the script but with rofi ??

>   I have tried rofi -show drun in the terminal as well but seems to get no response


can you confirm  if executing ` rofi ` provides the rofi layer ? 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/6489f16b-f6f2-4030-8ea7-a94c84c845ee)
 
if it won't respond try to to reinstall rofi 

` yay -Sy rofi-lbonn-wayland-git `

**Comment by zenghost1** [comment]
Thanks!! kRhyme, you are right. It was issue with Rofi. 
![image](https://github.com/prasanthrangan/hyprdots/assets/89266411/23a4b95b-36b9-4270-9576-ebc0df46dd4a)
It works now!!! Also fixed a lot of other issues as well thanks to you.
Also I want to thank you for making this repo such a beautiful place. I didn't knew so many new themes were added as well. And the new Hyde install interface is just "ART". Can't stress enough. I was on the older Hyprdots for a long time. Now, I will regularly pull the updates. My appreciation for this repo keeps on increasing.

Anyways for context.. 
###Soluction:

Rofi might get corrupted during installation due to multiple conflicts it didn't commit, I guess.

```console
Hyde check Config
Hyde update
Hyde restore Config (can also do complete Hyde-install)
```
The package won't upgrade and conflict due to files already being written in .config. So, can force overwrite it.
```console
sudo pacman -Sy rofi-lbonn-wayland-git --overwrite '*' 
```
