### ISSUE TITLE
[Feature Request]: Neovim wallbash theming

### ISSUE THREAD

**Issue by sanchitsahni07** [prasanthrangan/hyprdots#1505]
Nvim theme matching with tty 

https://github.com/ayamir/nvimdots

consider these dots file if you can modify these according to the hypydots will be helpfull

**Comment by rubiin** [comment]
Also can you change the title of the issue

**Comment by dieBakterie** [comment]
I thought we use @RAprogramm 's nvraid for this?

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/issues/1225

Ohh will close this in favor of the above discussion.
