### ISSUE TITLE
[Bug]: Rofi notification actions do not appear

### ISSUE THREAD

**Issue by ffrancesco94** [prasanthrangan/hyprdots#1508]
### Description

When a notification appears (of any kind, like Telegram or Thunderbird), clicking on it does not trigger any rofi window.

[Provide a clear and concise description of the bug.]

### Steps to Reproduce

1. Receive a notification
2. Click on in with any mouse button
3. Nothing happens

### Expected Behavior

A rofi window with actions appears.

### Actual Behavior

Nothing happens.

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: Arch
- Linux Version, output of `uname -a`: 6.8.9-arch1-2
- Hyprland Version, output of `hyprctl version`: v.0.40.0a, commits 4606
- Installation Environment: Lenovo laptop

**Comment by kRHYME7** [comment]
can you simulate this ? 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/5017823f-7dd0-45d5-8ea4-4a2c42d3d4b3)


` notify-send "https://google.com"  ` 

please tell if this do not spawn a rofi menu. 


If it spawed with this condition above then it is safe to assume that the apps e.g telegram you're using do not provide much info in the dbus interface .

**Comment by ffrancesco94** [comment]
Yes, that does work. Then it's app things, I'll try to bring it up with them. Thank you, we can close this then!

**Comment by kRHYME7** [comment]
Some apps do not provide links.

I'm using Whatsapp and it spawned a window where I can write a reply. But some messaging apps do not do this.
