### ISSUE TITLE
[Bug]: Code no longer uses these flags as shown on screenshot

### ISSUE THREAD

**Issue by rubiin** [prasanthrangan/hyprdots#1509]
### Description

[Provide a clear and concise description of the bug.]

As shown , whenever you open code , those flags are treated as files

![image](https://github.com/prasanthrangan/hyprdots/assets/8222059/2828252b-b204-4d9e-91c4-38f84d3c57d5)

The fix would be to remove the flags on $editor on hypr conf

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

Update code to latest

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/issues/1315

see pinned 🤣

**Comment by rubiin** [comment]
closing in favor of that
