### ISSUE TITLE
super+tab doesnot works for different workspace

### ISSUE THREAD

**Issue by KitsuneKode** [prasanthrangan/hyprdots#1512]
The different windows could not be accessed from the super+tab for different workspaces! I remember it to work if I am not wrong! 

Previously the waybar also allowed me to access the different windows opened by clicking on it! Now it also does not work! 
It is annoying to go through all the workspace to find the right workspace to find the window! And also go back to your previous workspace! 

Is it a bug or am I the only one facing the issue?

**Comment by kRHYME7** [comment]
update to ` hyprland-git ` for now
