### ISSUE TITLE
[Issue]: Nvidia gpu utilization 0% 

### ISSUE THREAD

**Issue by KitsuneKode** [prasanthrangan/hyprdots#1513]
I have ` GPU 1: AMD Lucienne @ 0.40 GHz [Integrated]
             GPU 2: NVIDIA GeForce MX450 [Discrete] `
             
             
 Now the utilization of nvidia gpu is always 0% regardless of the task I am performing! How can i enable the ability of the gpu to switch when nvidia is required!  The Cpu and the amd gpu is being utilised only. 

![image](https://github.com/prasanthrangan/hyprdots/assets/135751082/8b0c8dbf-d8f9-4bbd-a12f-4be083d5838a)

**Comment by kRHYME7** [comment]
Can you provide some output of ` nvidia-smi ` ?

**Comment by Ramy-Ashraf** [comment]
> Can you provide some output of `nvidia-smi` ? Also can you confirm that this worked, but now it is not working?
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/331563084-8d7dabb0-09c3-4293-8efb-555d1f4b2078.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTk0NDgsIm5iZiI6MTcxNTk1OTE0OCwicGF0aCI6Ii81MzQxNzQ0My8zMzE1NjMwODQtOGQ3ZGFiYjAtMDljMy00MjkzLThlZmItNTU1ZDFmNGIyMDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE1MTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYjI2NTY3YTE5MDdiMTA5ZmU3YWM5MDFkNzdjYTI3ZmM3MWJkMDU1ZDUwYmZkMzYyOGI3NWI4MjZhN2Y0ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fG-VHdPbjhaTFSyI6fbJNO5WqOlUn-G3ezgzNSZrJBI)
> 
> And it's worth noting that not all Nvidia GPUs / drivers support GPU utilization monitoring. I know mine doesn’t. So see nvidia-smi command )
> 
> You can contact NVIDIA for that if you really like to have that feature I guess.

sorry side question, when I tried it I found that my gpu is off. is this normal?

![image](https://github.com/prasanthrangan/hyprdots/assets/85342902/1ee4f686-09e4-4641-acbc-aa2fa4e248a9)

**Comment by kRHYME7** [comment]
@Ramy-Ashraf 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/5925ea60-4128-4086-bc8f-53f78e1ea1f5)

Better to understand first what are the meaning of those values

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/435b9175-ddd2-46f2-92ba-4b1c3292e296)

Note that my GPU is entry level ` mx250 ` for laptop and  this setting on my end is always on, this specific gpu cannot dynamically idle, so it sucks out all my battery and it really sucks ! 


https://medium.com/analytics-vidhya/explained-output-of-nvidia-smi-utility-fc4fbee3b124

**Comment by KitsuneKode** [comment]
> Can you provide some output of `nvidia-smi` ? Also can you confirm that this worked, but now it is not working?
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/331563084-8d7dabb0-09c3-4293-8efb-555d1f4b2078.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NjE4NDMsIm5iZiI6MTcxNTk2MTU0MywicGF0aCI6Ii81MzQxNzQ0My8zMzE1NjMwODQtOGQ3ZGFiYjAtMDljMy00MjkzLThlZmItNTU1ZDFmNGIyMDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE1NTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczODdkZjFkMTU0N2ZkOTkzNDg1ZjA3YjJiYjRjOTRkNWY3NDYzN2E4ZmQ2ZDA0YTdjMTNjZTI1Y2M3YThmNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gT3OB9jUMFgTJV6OhMzQKTWhInhdNWkDUhrmm3P1p3c)
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/331655163-446e50ab-4515-4d75-a9e9-cf26e02403d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NjE4NDMsIm5iZiI6MTcxNTk2MTU0MywicGF0aCI6Ii81MzQxNzQ0My8zMzE2NTUxNjMtNDQ2ZTUwYWItNDUxNS00ZDc1LWE5ZTktY2YyNmUwMjQwM2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE1NTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYWNmOTNjYzE2MmEyODRiMTFmMWQ4Y2M4NGRkYTU4Mjc3MjIzMzYyY2M3MWU5YWM3MDJmOGZiZDFhMDMyMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vLj05xt0ghFe0tSFV9ik-dZx0qR8dAJcT2PmaNOAfJA)
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/331654992-dbcc9ba8-9204-4dd4-9c29-0e143afb72ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NjE4NDMsIm5iZiI6MTcxNTk2MTU0MywicGF0aCI6Ii81MzQxNzQ0My8zMzE2NTQ5OTItZGJjYzliYTgtOTIwNC00ZGQ0LTljMjktMGUxNDNhZmI3MmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE1NTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MzEyMTA3ZjQzYmU1NzVhODlhZTA0ZjRlMjIwYjExNzEwYTgxZjRmZDA3YjEyZDNlMjU1OGUwMTY3MzQ0NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3M2W36XgBA6lAf6fJdIhmj-hIBekUT26yBLeWrbQIp8)
> 
> And it's worth noting that not all Nvidia GPUs / drivers support GPU utilization monitoring. I know mine doesn’t. So see nvidia-smi command )
> 
> Base on experience, it's not worth it if we always use nvidia GPU on our laptops. (if your unit is a laptop)
> 
> You can contact NVIDIA for that if you really like to have that feature I guess.



This is the screenshot @kRHYME7 
so does it mean utilization monitoring is not supported here either?

![image](https://github.com/prasanthrangan/hyprdots/assets/135751082/a2268572-e60b-4d27-80b3-9ac40f36f34a)

**Comment by KitsuneKode** [comment]
I am curious about something. Just to be sure, Websites like metacrafters.io used to work properly in my windows and like google-chrome used to utilise the nvidia gpu and everything rendered properly. But here firefox renders the website properly without lag but google-chrome renders it very laggy manner where navigating is also impossible and on checking in nvtop the gpu is not utilized at all, Only the Cpu works!  As given in my first picture you can see that.


How to make sure google-chrome not only works on cpu but also utilizes the gpu when needed like firefox

**Comment by KitsuneKode** [comment]
@kRHYME7 

For ` nvidia-smi --query-gpu=utilization.gpu, --format=csv` 
results:  `utilization.gpu [%]
0 %
`


And chrome is running on wayland!

I wasn't comparing linux and windows tho(just used a reference that it used to work) 

Yea, seems like chrome has an issue with like just utilizing the cpu and not using the gpu! Not sure tho why!

**Comment by kRHYME7** [comment]
how about checking if hardware acceleration is enabled

**Comment by KitsuneKode** [comment]
Installing optimus-manager fixed it! 

@kRHYME7 I am facing another issue after the installation of optimus-manager! I don't remember tweaking anything else,

Whenever I reboot/fresh start my device, the login screen that used to come doesnot render anymore! Its just a black screen and upon giving your password with muscle memory the screen starts. And I tried loging out, then the login screen renders! 

Is it something that happens?

**Comment by kRHYME7** [comment]
checkout your sddm service. 

Learn the basics of systemctl, so you can use the commands below 

```
  systemctl status sddm.service 
 systemctl enable sddm.service 
 systemctl restart sddm.service 
```

 Also, the ` optimus-manager `  got a section on the arch wiki read it for some fixes that you might have missed. 
 Configuring optimus-manager is simple but sometimes it's annoying.  

Will close this as this is fit to discussions panel or other threads e.g reddit/archlinux.
