### ISSUE TITLE
Cursor Theme

### ISSUE THREAD

**Issue by IgorD-lab** [prasanthrangan/hyprdots#1517]
### Discussed in https://github.com/prasanthrangan/hyprdots/discussions/1399

<div type='discussions-op-text'>

<sup>Originally posted by **IgorD-lab** April 26, 2024</sup>
Some themes provide a custom cursor theme, but it seems applications aren't applying it consistently. Some programs show the themed cursor, while others default to the standard cursor. Additionally, the cursor theme seems to flicker between the two within the same application.

Is there a way to force all applications to use only themed cursor?

https://github.com/prasanthrangan/hyprdots/assets/74680803/e51ea86b-44fb-49f5-b920-a1a965a89218

</div>

**Comment by kRHYME7** [comment]
For now, I suggest setting a consistent cursor in ` userprefs.conf ` 

```
exec = hyprctl setcursor Bibata-Modern-Ice 20
exec = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec = gsettings set org.gnome.desktop.interface cursor-size 20
```

**Comment by kRHYME7** [comment]
@IgorD-lab  Hello! I recently added a command to  patch the XCURSOR to be hyprland cursor compatible.

This is for gruvbox
` Hyde --dev convert_cursor ~/.icons/Gruvbox-Retro/ ` 


Note that  some errors needs to be handled manually. 
Example gruvbox will have extra file that ` hyprcursorutil ` cannot convert, leading to errors. Deleting that file will make the convertion & patching succeed.
in my case I saw this error specifically for gruvbox theme 

` ~/.icons/Gruvbox-Retro/cursors/thumbnail.png `  so just delete this, and you're good to rerun the above command.

**Comment by IgorD-lab** [comment]
![240520_11h54m35s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/74680803/13d94273-c1ce-4153-bea9-d0c95f48c80e)
![240520_11h57m06s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/74680803/83201915-6763-4d03-bd7d-9bffce0f7b0b)

I removed the thumbnail.png file from ~/.icons/Gruvbox-Retro/cursors/ and ran the command Hyde --dev convert_cursor ~/.icons/Gruvbox-Retro/ to convert the cursors. However, the cursor appearance remains unchanged. I'm presented with prompts based on the images mentioned earlier, but regardless of which option I choose, the cursor still looks the same. This leads me to believe there might be something wrong with my approach, or it's possible the hyprcursorutil utility isn't working as expected. Is there a chance I'm missing a step in the process?

**Comment by IgorD-lab** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/74680803/9a8cc941-fe38-4378-a955-c08e865d7fe1)

"Small" problem. Cursor got got a bit bigger. As far as I can see big cursor appears where white cursor would appear earlier.

**Comment by kRHYME7** [comment]
> Note that this will not totally remove the XCURSOR (gtk theming needs this old tech) so you'll still see the cursor would look blurred(hence the ugly flickering ) on top of gtk aps for example waybar.

Plus the scaling too.  The hyprcursor had an ability to fractional scale, whilst XCURSOR don't.


I wrote something on the CLI . You can use this to override the cursor size. This will set the XCURSOR and the HYPRCURSOR as a single command 

` Hyde cursor size  20 `  just modify the size 

 

Note that the hyprcursor conversion will follow the largest possible size of the XCURSOR.  ( will tell you this in advance, incase )

**Comment by IgorD-lab** [comment]
Tried it out and it works pretty well, thanks for help.

**Comment by kRHYME7** [comment]
Add it to your userprefs.conf to persist
