### ISSUE TITLE
keybinds shortcuts app or idk isnt showing any shortcuts

### ISSUE THREAD

**Issue by hdgetban** [prasanthrangan/hyprdots#1518]
i did a update in arch aka cachyos and i restarted it and when i click the keyboard icon on waybar this shows how to fix it?
![240517_22h29m34s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/156936988/54de835c-e465-4f67-bc78-e2226e049dd0)

**Comment by kRHYME7** [comment]
please run `keybindshint.sh `, any error?

**Comment by dieBakterie** [comment]
I've the same problem but when i try it with optargs added for example  `keybind_hints.sh -w 38% -h 80%` just throws out the help message

**Comment by kRHYME7** [comment]
@dieBakterie

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/67d6027d-61e9-461a-b321-dfadc8b44696)

**Comment by dieBakterie** [comment]
Ig then it's skerse's refactor that broke this functionality for me

**Comment by dieBakterie** [comment]
it works but not per keybind only in terminal

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/7de5c749-40e0-4653-bbc5-4a011e92ff52)

Do hyprland even know this file path?

**Comment by dieBakterie** [comment]
Yes and it only isn't showing though the keybind, in terminal and waybar module it works.

**Comment by kRHYME7** [comment]
How about doing some basics like ` $HOME/.config/hypr/silos.conf `?  It's not magic yk, to tell hyprland which path is which.

**Comment by dieBakterie** [comment]
Sorry bro it's fixed now, all it needs was **$HOME**

**Comment by hdgetban** [comment]
i fixed it because i added kitty -o "linux_display_server=wayland" so i removed it and it fixed but still it will launch kitty slow without it

**Comment by kRHYME7** [comment]
@hdgetban  I see. can you provide the output  for.' Hyde systeminfo `

**Comment by hdgetban** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/156936988/881a8a18-6d65-4a0f-8f76-7d291321f60b)

**Comment by hdgetban** [comment]
wrong one 
![image](https://github.com/prasanthrangan/hyprdots/assets/156936988/fb44056b-3f62-48ac-9c03-59be2cc34ff3)

**Comment by hdgetban** [comment]
let me run Hyde-install and see if it works

**Comment by hdgetban** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/156936988/89b3ce56-d430-4993-bd47-c7db31643249)

**Comment by kRHYME7** [comment]
Is catchy Os lightweight will try to investigate in a VM.

**Comment by hdgetban** [comment]
I mean yeah is lightweight I used someone hyprland dotfiles and it wasn't that laggy  and slow but when I used this dotfiles is kinda slow and laggy when I open some stuff

**Comment by hdgetban** [comment]
And I have mx350 and 8gb of ram and hdd and i5-1135G7

**Comment by kRHYME7** [comment]
Try to `Hyde power save --[options] `   then  try to disable some of them specially the borderangle animation

**Comment by hdgetban** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/156936988/bf6cc819-ee92-4723-9e63-22a2b14438ad)
done now what

**Comment by kRHYME7** [comment]
test if you still have some lagging issue. The borderangle animation peaks to 20% of memory usage even idle. Maybe it causes some bottleneck

**Comment by hdgetban** [comment]
Is still lagging and slow when opening steam and rofi and kitty and other apps opens slow

**Comment by hdgetban** [comment]
I FIXED IT so the problem is zsh making my system slow so I switched to fish and it's faster

**Comment by kRHYME7** [comment]
Nice!
