### ISSUE TITLE
[Feature Request]: keybind hints enhancements

### ISSUE THREAD

**Issue by dieBakterie** [prasanthrangan/hyprdots#1519]
### Description

Would be nice if `keybinds_hint.sh`  spacer follows the specified width and an space between the super glyph and everything would be nice too and that it scales with the given height too. As seen in the screenshot there is enough space for two or even three more keybinds to be shown.

### Use Case

It's an cosmertic detail that kinda annoys myself and it reduces the need of scrolling too.

### Proposed Solution

Use the given -w/-h values and scale accordingly.

### Additional Information

![240518_02h09m03s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/50206827/e4e4b132-b221-45a0-ab0c-c178e6e0b2c2)

**Comment by kRHYME7** [comment]
I hope you're aware of how rofi operates. It will never be a full-fledge GUI toolkit. 

* For now, if you're using custom width/height you should also indicate the custom number of lines. (Maybe it is posible to do it dynamically soon, also I assume it's still okay to manually declare the number of lines you are already declaring the width/height)

Here's the PR
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/98e2ee0b-1ecb-4f14-89fd-7496d20fc59d)

*fixed the spacing 
https://github.com/prasanthrangan/hyprdots/pull/1520

**Comment by dieBakterie** [comment]
Yeah sure that's no problem for me and thanks for the fast fix mate.

**Comment by kRHYME7** [comment]
Please approve the PR so I can merge it.

**Comment by dieBakterie** [comment]
As far as i know i can't Approve the PR, 'cause i haven't write access on this repo.
