### ISSUE TITLE
setup projector in hyprland

### ISSUE THREAD

**Issue by tryprncp** [prasanthrangan/hyprdots#1523]
hey guys i really need some help.
I have a school presentation tomorrow, im presenting a pptx using libreoffice-impress. how do i setup the projector as a secondary display or maybe a mirror display? should i put this in my hyprland.conf? 
monitor = eDP-1, 1920x1080@60, 0x0, 1, bitdepth, 10
monitor = HDMI-A-1, 1920x1080@60, 0x0, 1

any help would be nice :>
sorry if not related.

**Comment by kRHYME7** [comment]
install nwg-displays so you can have a gui.

**Comment by tryprncp** [comment]
@kRHYME7 it only show the waybar and cursor. i really dont know how to troubleshoot this

**Comment by kRHYME7** [comment]
WdYM? shown on the projector?

**Comment by tryprncp** [comment]
yeah, but i got it to work eventually. thanks
