### ISSUE TITLE
[Bug]: Brightness doesn't change on AMOLED display in hp laptop.

### ISSUE THREAD

**Issue by S44WN** [prasanthrangan/hyprdots#1526]
### Description

I have tried xrandr and other AUR brightness but none seems to work.
the laptop has nvidia gpu and intel cpu

**Comment by kRHYME7** [comment]
@S44WN  Try this first ` brightnessctl set 50% `

**Comment by jenil1122** [comment]
Temp solution :
```

echo 1000 | sudo tee /sys/class/backlight/intel_backlight/brightness

use Tab for auto completion and replace 1000 with preferred brightness level 
```

**Comment by abenezerw** [comment]
can you mark that as answer and close this issue please. @jenil1122
