### ISSUE TITLE
[Bug]: cant add keyboard layout spanish

### ISSUE THREAD

**Issue by Alejandrovsdev** [prasanthrangan/hyprdots#1529]
### Description

i cant add es keyboard.

### Expected Behavior

es keyboard option

how can i add es layout to super + k

**Comment by kRHYME7** [comment]
Checkout the wiki first 
https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#switchable-keyboard-layouts

Here's the part you're interested in
https://github.com/prasanthrangan/hyprdots/blob/29b199ab210772055685642e6b57cdd3cb78929b/Configs/.config/hypr/hyprland.conf#L65C1-L67C21

Please post questions on discussion panel

**Comment by kRHYME7** [comment]
Here's some answered questions https://github.com/prasanthrangan/hyprdots/issues/1339#issuecomment-2068669775
