### ISSUE TITLE
monitor issue ; Overlapping  sddm greeters on multiscreen setup ;

### ISSUE THREAD

**Issue by Newer1107** [prasanthrangan/hyprdots#153]
I have two monitors and the notifications and the volume bar shows at the second one.
How do I default it to the primary monitor?

**Comment by Newer1107** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/116626403/b5df4acf-dc7a-4049-ae8a-18d3b267470c)
this one

**Comment by prasanthrangan** [comment]
Hi, try changing this [line](https://github.com/prasanthrangan/hyprdots/blob/88695e44c4c63b6c04aef9b08e089a35ad772460/Configs/.config/dunst/dunstrc#L7C16-L7C16) in dunst config `monitor = 1`

**Comment by Newer1107** [comment]
> Hi, try changing this [line](https://github.com/prasanthrangan/hyprdots/blob/88695e44c4c63b6c04aef9b08e089a35ad772460/Configs/.config/dunst/dunstrc#L7C16-L7C16) in dunst config `monitor = 1`

thanks that fixed it, I have another issue in which some part of my second monitor is like mirror of the first monitor
![image](https://github.com/prasanthrangan/hyprdots/assets/116626403/707b6467-3e73-43c2-92a5-bbc2d9eedd51)
![image](https://github.com/prasanthrangan/hyprdots/assets/116626403/77cc883a-7d37-4463-852f-c1ddee2a7aa1)

**Comment by Newer1107** [comment]
only happens during login

**Comment by psilvaricardo** [comment]
@Newer1107 
`hyprctl monitors` will give you the configuration of your setup.

I adjusted my configuration based on Hyprland Wiki [here](https://wiki.hyprland.org/Configuring/Monitors/)

```
❯ hyprctl monitors
Monitor HDMI-A-1 (ID 0):
	1920x1080@60.000000 at 0x0
	description: Acer Technologies Acer CB271H T5EAA0034204 (HDMI-A-1)
	make: Acer Technologies
	model: Acer CB271H
	serial: T5EAA0034204
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 42 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0

Monitor DP-4 (ID 1):
	2560x1440@59.951000 at 1920x0
	description: Acer Technologies K272HUL T6AAA0048522 (DP-4)
	make: Acer Technologies
	model: K272HUL
	serial: T6AAA0048522
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 42 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
```

my ~/.config/hypr/hyprland.conf looks like this where HDMI-A-1 is on the left and DP-4 on the right:
 
```
monitor = HDMI-A-1,highres,auto,1
monitor = DP-4,highres,auto,1
```

**Comment by kRHYME7** [comment]
https://wiki.archlinux.org/title/SDDM#Overlapping_greeters_on_multiscreen_setup
