### ISSUE TITLE
[Bug]: system tray icons not showing

### ISSUE THREAD

**Issue by azmarifdev** [prasanthrangan/hyprdots#1533]
### Description

At first, the system tray icons can be seen in the wayber, but after hiding the wayber with Crtl + Esc, if you unhide it, the icons of the apps that were in the system tray are not shown. but, when I reboot or logout and login, the system tray icons showing.

### Steps to Reproduce

1. Hide wayber with Ctrl + Esc.
2. Again unhide wayber with Ctrl + Esc.
3. Then, system tray icons not showing.

### Expected Behavior
I hope system tray icons will show even if wayber is toggled.

### Actual Behavior

https://github.com/prasanthrangan/hyprdots/assets/81615122/d5044208-a2c1-4e05-ae92-4787f24c717d

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux ArchHyprland 6.9.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000 x86_64 GNU/Linux

- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

- Installation Environment: On The Main Hardware.
- Other info: Display Resolution - 1366x768

**Comment by kRHYME7** [comment]
restarting  did not fix it?

**Comment by azmarifdev** [comment]
> restarting did not fix it?


when I restart or logout and login, the system tray icons showing.
