### ISSUE TITLE
[Bug]: My laptop works on nvidia rtx 3050 which is connected to external monitor when ever i sleep or suspend  my laptop my eDP will boot but my external display doesn't starts

### ISSUE THREAD

**Issue by shivamsinghcse** [prasanthrangan/hyprdots#1536]
shivam-nitroan51558 :: ~ » lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Alder Lake-P GT1 [UHD Graphics] (rev 0c)
01:00.0 VGA compatible controller: NVIDIA Corporation GA107M [GeForce RTX 3050 Mobile] (rev a1)

shivam-nitroan51558 :: ~ » hyprctl monitors
Monitor eDP-1 (ID 0):
	1920x1080@144.00000 at 0x0
	description: BOE 0x0B02
	make: BOE
	model: 0x0B02
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 0 0 32
	scale: 1.33
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 1920x1080@144.00Hz 1920x1080@60.00Hz

Monitor HDMI-A-1 (ID 1):
	1920x1080@74.97300 at -1920x0
	description: Samsung Electric Company S24C31x H9DW503076
	make: Samsung Electric Company
	model: S24C31x
	serial: H9DW503076
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 0 0 32
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 1920x1080@60.00Hz 1920x1080@74.97Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1680x1050@59.95Hz 1600x900@60.00Hz 1280x1024@60.02Hz 1440x900@59.89Hz 1280x800@59.81Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@70.07Hz 1024x768@60.00Hz 800x600@72.19Hz 800x600@60.32Hz 800x600@56.25Hz 720x576@50.00Hz 720x480@59.94Hz 640x480@72.81Hz 640x480@59.94Hz

**Comment by kRHYME7** [comment]
If you unplug then plug ?

**Comment by shivamsinghcse** [comment]
> If you unplug then plug ?

nothing happens i have to restart to laptop

**Comment by kRHYME7** [comment]
Can hyprctl monitors detect the missing monitor? or it wouldn't detect anymore

**Comment by shivamsinghcse** [comment]
It can detect

**Comment by shivamsinghcse** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/121515299/05776c8d-caf5-4acc-a991-2f4e2a13c772)

**Comment by kRHYME7** [comment]
Can you provide the output here during that behavior m

**Comment by kRHYME7** [comment]
Cool, can you install nag-display and map your other monitor to a certain position?

as you can see your ext monitor is map at a negative value. Try it first.

**Comment by shivamsinghcse** [comment]
Actually I have manually done that from hypr.conf

**Comment by shivamsinghcse** [comment]
okey i have change this also 
![image](https://github.com/prasanthrangan/hyprdots/assets/121515299/6885f180-0e5e-4e23-b0d3-0e109c5e1e92)
with the help of wdisplays

**Comment by kRHYME7** [comment]
Is the ext monitor still not fixed?

**Comment by shivamsinghcse** [comment]
No

**Comment by kRHYME7** [comment]
Ok, try to check the wiki https://wiki.hyprland.org/Nvidia/ . If still no fix please open the issue on their github.

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/1998cef8-03e2-43a5-87b3-3d75248acc5e)

**Comment by shivamsinghcse** [comment]
okay
