### ISSUE TITLE
Waybar not showing wlr/workspaces numbers with module activated

### ISSUE THREAD

**Issue by Ew4n1011** [prasanthrangan/hyprdots#154]
Using this waybar config:
```
1||top|( wlr/workspaces hyprland/window )|( clock )|( cpu memory ) ( network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
```

I'm on an 1080p laptop so maybe that has something to do with it? Idk

**Comment by Ew4n1011** [comment]
I also get this error when running waybar from the terminal, don't know if its related or not:
`[error] Item '': No icon name or pixmap given.`

**Comment by Ew4n1011** [comment]
Ok going through the waybar wiki for Hyprland modules and it seems wlr/workspaces has been renamed to hyprland/workspaces.

Tried that config and it worked instantly, maybe a config change is needed in order to update this.

**Comment by prasanthrangan** [comment]
> Ok going through the waybar wiki for Hyprland modules and it seems `wlr/workspaces` has been renamed to `hyprland/workspaces`.

Oh thank you, did this change with the latest update?? I'll update my system and fix this!!
