### ISSUE TITLE
[Feature Request]: NixOS Distribution

### ISSUE THREAD

**Issue by ArikRahman** [prasanthrangan/hyprdots#1544]
### Description

[Provide a clear and concise description of the feature you'd like to see added.]
I was rocking hyprdots for a long time on archcraft until I managed to break the package manager. This made me ragehop onto a distro that kept backups and wouldn't allow for this sort of issue, landing me on NixOS. 

### Use Case

[Describe how this feature would be useful to you or to other users of the project.]
I think having a similar setup on NixOS would make these dotfiles future-proof against dependency breakage.

### Proposed Solution

[If you have a specific solution in mind, describe it here. If not, you can skip this section.]
I am currently working on an implemenration and configuration.nix that allows for hyprland setup. Since this all happened recently, I've only managed to boot into bare hyprland from a gnome session.

### Alternatives

[Are there any alternative solutions or workarounds that you've considered? If so, describe them here.]
N/A

### Additional Information

[Add any other information about the feature request here. For example, you might include links to similar features in other projects, or screenshots or diagrams to help explain your idea.]

**Comment by rubiin** [comment]
This can be doable. But I guess its difficult to manage in this repo . Would be good to do on a separate repo similar to how hyperdots-debian is there.

**Comment by kRHYME7** [comment]
Please see the attempts in the discussions panel and continue the discussions there. I will try to link it later. Will close this now as we need a larger discussion platform to talk about these things.

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/discussions/166
