### ISSUE TITLE
[Bug]: I stopped flatpak and my system got nuked

### ISSUE THREAD

**Issue by HawliKerim** [prasanthrangan/hyprdots#1548]
### Description

Just run the script

### Expected Behavior

I just expected it to install the packages

### Actual Behavior

Flatpak installed 16 kb/s and it showed 2 hrs for just 1mb download
And obviously i canceled the download but my system got nuked

### Environment

Dell g15 5530 laptop 
tenda router

arch
### Additional Information
I dont think flatpak has a place in this beatiful script

**Comment by kRHYME7** [comment]
you can skip flatpak

**Comment by abenezerw** [comment]
i would also avoid flatpaks, if this issue was solved can you please close this out. @HawliKerim
