### ISSUE TITLE
Discord scale bug?

### ISSUE THREAD

**Issue by sosiska-killer-of** [prasanthrangan/hyprdots#155]
Everything in discord is pixelated .
![image](https://github.com/prasanthrangan/hyprdots/assets/105828681/7831d4cb-9d93-4806-bc09-faf668c3731d)
 its not just discord

**Comment by prasanthrangan** [comment]
Hi, have you set your correct resolution in `hyprand.conf` or `monitors.conf` ? its pixelated as its not running at native resolution. also, please set the scaling to 1.

**Comment by sosiska-killer-of** [comment]
Monitors.conf is empty and I set the resolution restarted but it’s still the same, I also can’t find where to set resizing to 1

**Comment by Lol-Lap** [comment]
> Monitors.conf is empty and I set the resolution restarted but it’s still the same, I also can’t find where to set resizing to 1

Just press SUPER + E to open dolphin file explorer then go to the home directory, then your user file then there press CTRL + H to view the hidden files then go to .Config file then hypr file there you should see all the conf files, open the hyprland.conf then edit the monitor value to your resolution.

**Comment by Lol-Lap** [comment]
> Monitors.conf is empty and I set the resolution restarted but it’s still the same, I also can’t find where to set resizing to 1

 Can you please share your hyprctl and monitor value that you have set?

**Comment by Lol-Lap** [comment]
> Monitors.conf is empty and I set the resolution restarted but it’s still the same, I also can’t find where to set resizing to 1

Can you please share your hyprctl and the monitor value that you have set?

**Comment by katsuja** [comment]
> Monitors.conf is empty and I set the resolution restarted but it’s still the same, I also can’t find where to set resizing to 1


# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# See https://wiki.hyprland.org/Configuring/Monitors/

#monitor = ,preferred,auto,1
monitor = eDP-1, 2256x1504@59.999001, 0x0, 1      <---------the last number (1) sets the scaling

**Comment by kRHYME7** [comment]
@sosiska-killer-of  Hi, have you found some fix on this ?
