### ISSUE TITLE
[Bug]: Monitor disconnects and there is no fix except reinstalling Arch

### ISSUE THREAD

**Issue by Sens120ms** [prasanthrangan/hyprdots#1550]
### After Installing the HyprDots config, as soon as I restart the PC everything goes blank and monitor disconnects showing no signal, no method ever fixes this except a fresh reinstall, this is a behavior that only occurs after installing my Nvidia GPU drivers in any linux distro, but behaviour differs as distros like Ubuntu and Mint show lost Signal while other distros such as Fedora and ARch load without any GPU drivers.

unfortunately this HyprDots installs Nvidia drivers which my GPU seems to hate, I typically use Noveau drivers for this reason as they work great except gaming.

I have looked throught the scripts and configs but because I'm pretty bad with this stuff I could not find anything relating to not permitting the installation of graphics card related drivers and software as I install the the HyprDots conf.

**Steps to Reproduce**

1. Install the HyprDots config (Which includes Nvidia Drivers)
2. Restart PC
3. After GRUB section, monitor loses signal as GPU driver loads in with the OS

### Expected Behavior

Expected to load in without any driver since this is typical Arch behavior after loading in Nvidia proprietary drivers, where I could uninstall the drivers from the Terminal

### Actual Behavior

Rather than booting in without drivers like typical Arch Nvidia Driver Install, it decides to boot in the way Ubuntu and Mint does causing an irreversible damage of OS leading to Monitor losing signal, which ultimately leaves one choice: Reinstalling Arch 

- Linux Distro: Arch Linux
- Linux Version, output of 'uname -a': 6.9.2
- Hyprland Version, output of `hyprctl version`: Not Applicable (Unable to get to OS after HyprLand )
- Installation Environment: Main Hardware, (basically Natively Run OS)

**Comment by Sens120ms** [comment]
I am aware nobody can do anything about Nvidia drivers corrupting the install, but would it be possible to provide an install for this HyprDots WITHOUT Nvidia drivers installation?

**Comment by kRHYME7** [comment]
Yup ` Hyde-install`  note that it is designed to always ask you what to choose. 


(will be improved soon)

**Comment by Sens120ms** [comment]
> Yup ` Hyde-install` note that it is designed to always ask you what to choose.

Sorry for being annoying, but because I do not want to reinstall Arch for the 3rd time today, could I make sure doing this will ensure I get to choose whether to install Nvidia drivers or not?

**Comment by Sens120ms** [comment]
Issue Resolved.

Solution:
- I went into the folder named Scripts where you have the Install.sh file and etc
- I selected show hidden files, there should be a folder named .nvidia or smth, go inside the folder
- Enter every driver installation file in text editing mode and empty every single bit of text inside
- Install and reboot
- in GRUB menu press 'e' after selecting your Arch install to enter editing mode
- You should find a line where near the end of the line there is something about nvidia_drm.nomodeset=1, cant remember word for word
- Final Step, change the nvidia text to nouveau

Enjoy!
