### ISSUE TITLE
[Feature Request]: Theme all bar icons

### ISSUE THREAD

**Issue by NotAF0e** [prasanthrangan/hyprdots#1552]
Theme the currently open background apps as well as network, bluetooth and udiskie buttons on the bar. Currently these icons are white while other icons such as power are themed.

**Comment by kRHYME7** [comment]
They are different, and are called System tray Icons.

**Comment by kRHYME7** [comment]
Here's a relevant link. 
https://github.com/prasanthrangan/hyprdots/issues/1537

Only solution for this is creating a wallbash template for each   .svg files and try to cater all thousands++ ish icon. Tha's  tooooo much work.  If you can find a relevant ref. on "how to dynamically change svg icons' colors  using the command line." , then everything might be easy.  

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/6b1750c4-47f8-406e-9440-60f0144b931a)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/f84aab33-dc75-405e-9a86-c1fea95e6abe)

Maybe it is possible, but for now this is too much. You can disable this tray icons by removing `tray ` in the ~/.config/waybar/config.ctl ` but note that some apps won't start. 

Or find GTK icons that fit the whole style. 

I will close this for now as unplanned. But I hope this can be done in the future.
