### ISSUE TITLE
How do I update?

### ISSUE THREAD

**Issue by Newer1107** [prasanthrangan/hyprdots#156]
I've been thoroughly enjoying using Hyprland as my window manager, and I've noticed that you've made some exciting changes and added new features to the project recently. I'm eager to get my hands on these latest improvements, but I'm not quite sure how to update my current installation to access them.

Could you kindly provide me with instructions on how to update to the latest version? I want to make sure I'm benefiting from all the great work you've been putting into the project.

If there are any specific commands or steps I need to follow, or if you have any recommendations for a seamless update process, I'd greatly appreciate your guidance.

**Comment by prasanthrangan** [comment]
Thank you!

Just pull the latest changes and run the install script as below -

```
cd ~/Hyprdots/Scripts
git pull
./install.sh -r
```
It will backup your existing config files and copy the updated ones!

**Comment by Newer1107** [comment]
I made some changes to my current configs but I'm not sure what stuff I edited, is there something I can do about this?

**Comment by prasanthrangan** [comment]
Hmm... if you know which files you changed you can restore it back... you can also try comparing the .config directories to figure it out
```
diff -bur $HOME/Hyprdots/Configs/.config $HOME/.config
```

**Comment by Newer1107** [comment]
I'm not sure..
http://ix.io/4FrM

**Comment by Newer1107** [comment]
none of these commands are working.
I don't see the new theme either.
I ran ./install.sh -r
![swappy-20230905_214355](https://github.com/prasanthrangan/hyprdots/assets/116626403/d308c1d4-9890-4d17-b21d-6b72d4ab6c44)
![swappy-20230905_214432](https://github.com/prasanthrangan/hyprdots/assets/116626403/3205ad5f-11f0-44a6-8fd3-26414d384e7e)
![swappy-20230905_214442](https://github.com/prasanthrangan/hyprdots/assets/116626403/a77dae3a-6da8-4e2e-bb1a-cff8bcca0992)

**Comment by Newer1107** [comment]
it installed.
how do I fix this?
![image](https://github.com/prasanthrangan/hyprdots/assets/116626403/19c1a3f5-78fb-4232-b72c-0ed95e718cd8)
there's something written which isnt even readable.

**Comment by Newer1107** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/116626403/aaccea53-d61a-4b2f-9bae-2701f32b41fa)
here is it, I've tried removing the blur function completely but it doesn't work it regenerates itself when theme is changed

**Comment by Newer1107** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/116626403/90091b9a-5b43-4ada-b153-8dba2bdecb99)
here is the file

**Comment by stove-jeebs** [comment]
try to remove the line xray = false from the file. Xray should default to false anyway

**Comment by prasanthrangan** [comment]
ahh.. you are using older version of hyprland, that's causing it, the blur variable declarations have changed in the latest version!

**Comment by Newer1107** [comment]
![230906_09h26m46s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/116626403/c0f0a554-0925-4848-a321-3e9666ee3d93)
getting this error when trying to update

**Comment by prasanthrangan** [comment]
ohh.. its the waybar issue again :(
can you try updating just the hyprland package...

**Comment by Newer1107** [comment]
Yes I did the exact same thing, just updated the hyprland package. but now the workspace number on the waybar broke like it doesn't show the workspace number anymore. I'll upload the screenshot when I get home

**Comment by prasanthrangan** [comment]
hahaa, that's also expected :)
its fixed in 2443fc7 ... so please pull the latest update and reinstall the latest waybar config

**Comment by Newer1107** [comment]
Hi, it worked but when I tried to apply my config for the network speed monitor it broke again (the workspace numbers)
here is the diff of both and I'm unsure about how to fix it.
ix.io/4FvO

**Comment by Newer1107** [comment]
nvm I fixed it
![image](https://github.com/prasanthrangan/hyprdots/assets/116626403/8406ae6f-946d-43a6-96c8-d47c35dd264b)
how do I move the clock? it doesn't seem to be perfectly at the centre

**Comment by prasanthrangan** [comment]
hmm... maybe you have additional `(` or `)` set in config.ctl file?

**Comment by Newer1107** [comment]
You're right, it's fixed now.
