### ISSUE TITLE
Screen share is to laggy and low fps (1-2 fps approx)

### ISSUE THREAD

**Issue by piush-terminalwitchcraft** [prasanthrangan/hyprdots#1560]
### Description

See title

### Steps to Reproduce

1. Go to meet.google.com
2. share your screen
3. view from another device

### Expected Behavior
Smooth screen share atleast

### Actual Behavior

Laggy screen share

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

-  ArchLinux
- Linux terminalwitchcraft 6.9.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sun, 26 May 2024 01:30:09 +0000 x86_64 GNU/Linux
-  Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

- On The Main Hardware
- 4k

**Comment by vampirepapi** [comment]
any updates on this?

**Comment by kRHYME7** [comment]
try to run ` resetxdgportal.sh ` everytime the screensharing is broken.  Also make sure that the app is running in wayland. 

Try to read this too https://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/

**Comment by abenezerw** [comment]
Can you close this issue, #1848 has a work-around, but still an upstream issue for now. @piush-terminalwitchcraft
