### ISSUE TITLE
Add rofi launch calculator

### ISSUE THREAD

**Issue by savaobay** [prasanthrangan/hyprdots#1566]
### Description

Can you add https://github.com/svenstaro/rofi-calc

### Use Case

Makes calculations easy based on rofi without having to install additional applications

### Proposed Solution
Launch rofi calculator with theme using keybinding Command+Shift+C

**Comment by savaobay** [comment]
yes it works but i don't know how to make it follow the theme :V 
![240607_00h19m01s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/38123103/f96389c6-c3dc-4e3b-8676-92bf4fdf5ede)

**Comment by Sitolam** [comment]
Would like to see this themed too 😃

**Comment by se7en-x230** [comment]
I just use my old dmenu script with rofi

![image](https://github.com/prasanthrangan/hyprdots/assets/69777713/ec3ada13-0dbd-4d68-b6bc-9d1c555b4a23)

**Comment by kRHYME7** [comment]
I see so this way we will only need qalc, right?

**Comment by se7en-x230** [comment]
yes the lib 
1 extra/libqalculate 5.2.0-1 [0 B 15.49 MiB] [Installed]
I forgot if you need the gui version to run updates on currency to be able to convert. I might have found a cli command to do that but I forgot

**Comment by kRHYME7** [comment]
That's perfect! I only got the Flatpak qt one. Didn't know the lib exposes an executable. Can I get inspiration from your script? Will add a ` Hyde show calc ` option if anyone would like to use it.

**Comment by se7en-x230** [comment]
Welcome

**Comment by kRHYME7** [comment]
>  to always run a quick update

hmm can we make it run  every 24 hours by default?  or every after reboot/relogin.  I takes much time for me to always fetch.

**Comment by se7en-x230** [comment]
Sounds like a plan

**Comment by kRHYME7** [comment]
` Hyde show calc ` 


At launch :
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/cd634cd4-eab5-4d9c-b2c3-1a32ac428882)

After some calcualtions: 
* last result becomes the entry message
* the  message will be added to pasteboard
* also being notified too
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c13e77dc-b8ff-4525-a65e-aa39b4b63c94)


![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/f0b49a1d-8308-4919-b97b-4037a2266643)
 

regarding the currency rate,  updated it every launch  in  background,  and  works like a charm.

**Comment by se7en-x230** [comment]
Very nice.

But dunst is a bit unreadable in Mocha

![240630_09h21m32s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/69777713/7c71c9bd-5ae0-4851-8fe9-d1139640626b)

**Comment by kRHYME7** [comment]
Reverted it back to default for now. Soon if we had a single executable for wallbash.  We might as well generate the color scheme on the go. 

(we can cater for both light and dark modes, but this might be start of having a bloated icon pack stored in the repo)

**Comment by se7en-x230** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/69777713/3f10aeda-2ccf-46b2-84ff-58baa794bd53)

**Comment by Sitolam** [comment]
> That's perfect! I only got the Flatpak qt one. Didn't know the lib exposes an executable. Can I get inspiration from your script? Will add a `Hyde show calc` option if anyone would like to use it.

I can use the `Hyde show calc` option. But I was wondering how to implement this little program in my setup. So when I want to set a keybind for that, do I need to use `Hyde show calc` or is it better to use something else (like the actual shell script and if so where can I find that).

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/f1974aec-1a21-4bd3-9a96-bd57c9dc2d53)

edit your keybinds at ` ~/.config/hypr/keybindings.conf `

**Comment by Sitolam** [comment]
> ![image](https://private-user-images.githubusercontent.com/53417443/344468981-f1974aec-1a21-4bd3-9a96-bd57c9dc2d53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NjEyMzIsIm5iZiI6MTcxOTc2MDkzMiwicGF0aCI6Ii81MzQxNzQ0My8zNDQ0Njg5ODEtZjE5NzRhZWMtMWEyMS00YmQzLTlhOTYtYmQ1N2M5ZGMyZDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE1MjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NDc5NjU2NDY5YzQ5ZGI4YjQ4MWU1ZjBmOTkzOTRiMzllZWIwYzJiY2Y1ODYyNzE2NmVhOTc0MzY2MWEyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H2qvXB7n8OSEO0lH993Ajih7YSc5gviaACyHQ791gjs)
> 
> edit your keybinds at `~/.config/hypr/keybindings.conf`

Why do you use `bindd` and not just `bind`. If I try your configuration I get this error:
![image](https://github.com/prasanthrangan/hyprdots/assets/79202140/3bc4c31e-fa97-46cd-9d51-67cd3619bc62)

**Comment by kRHYME7** [comment]
> Why do you use bindd and not just bind.

Upon the latest update we can now have explicit description for keybinds hence adding 'd'  flag. 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/01631f39-1030-41b7-8513-ba99cf836f19)
