### ISSUE TITLE
[Bug]: Fastfetch is failing to display PNG files

### ISSUE THREAD

**Issue by AtnProjects** [prasanthrangan/hyprdots#1569]
### Description

Fastfetch is failing to display PNG files correctly from the directory ~/.config/fastfetch/pngs/. Instead of displaying the image, it shows "�PNG", indicating recognition of the file format but improper rendering.

### Steps to Reproduce

1. Ensure that fastfetch is installed and configured correctly.
2. Place PNG files in the directory ~/.config/fastfetch/pngs/.
3. Run fastfetch.

### Screenshots
![imagen](https://github.com/prasanthrangan/hyprdots/assets/72979783/42be9caf-7eb1-4a3b-9abc-41ef4c6e361a)

- Linux Distro: ArchLinux
- Linux Version:Linux archlinux 6.9.3-arch1-186_64 GNU/Linux

- Hyprland Version: 0.40.0
- Installation Environment: Real  hadware

**Comment by AtnProjects** [comment]
The solution was to install imagemagick yay -S imagemagick

**Comment by kRHYME7** [comment]
It's not installed when you installed HyDE?
