### ISSUE TITLE
keyboard dificultie

### ISSUE THREAD

**Issue by Gedankenn** [prasanthrangan/hyprdots#157]
Hello, sorry for the trouble, i managed to get my keyboard working for my native language PT-BR using the config us and intl
```input {
    kb_layout = us
    kb_variant = intl
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    force_no_accel = 1
}

```
but now, i cant make the Ç, now when i press the keys it does this instead: Ć

someone know how to solve it?
thanks

**Comment by jhenrique04** [comment]
Hello, jut change "us" to "br" and leave the other variable as it was, worked like a charm for me

**Comment by Gedankenn** [comment]
the problem is my kerboard is US. it doest have the key for that C. :(

**Comment by Gedankenn** [comment]
i also tryed to put the locale language to pt-br. i dont know, after some updates my ć is now broken. someday they may fix.

**Comment by DeividReinkeSchiitz** [comment]
In my case i just added in the input category the abnt2 keyboard
`  

     input {
      kb_layout = br
      kb_variant = abnt2
      kb_model = abnt2
      kb_options =
      kb_rules =
      follow_mouse = 1  
      touchpad {
          natural_scroll = no
      }
  
      sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
      force_no_accel = 1
    }

`

**Comment by prasanthrangan** [comment]
This seems to be resolved, please reopen if required!
