### ISSUE TITLE
[Bug]: cursor size

### ISSUE THREAD

**Issue by D3dde** [prasanthrangan/hyprdots#1570]
## Bug Report

Cursor size change depending on the application

### Description

I'd like to start by making it clear that I'm new to Linux. On some applications such as Godot and VLC the cursor becomes much larger than normal, I think it is related to the PPI of the monitor (108.79) but I'm not sure at all.

### Expected Behavior

that the cursor is the same size in all applications.

### Screenshots

https://github.com/prasanthrangan/hyprdots/assets/160339765/27aabba0-50ae-4304-9bcf-130c2c57922f

### Environment

- Linux Distro: ArchLinux
- Linux Version: 6.9.3-arch1-1
- Hyprland Version: v0.40.0
- Installation Environment: Main hardware (dual boot with windows)
- Other info: 2 monitors (both 2560x1440)

### Additional Information

I've tried to tweak a few things in hyprland.conf but nothing changed

I took a look at #1517  but I don't understand if it's the same problem

**Comment by kRHYME7** [comment]
> I took a look at https://github.com/prasanthrangan/hyprdots/issues/1517 but I don't understand if it's the same problem

@D3dde Yeah it is 

Here some relevant links 

https://github.com/prasanthrangan/hyprdots/issues/834
https://github.com/prasanthrangan/hyprdots/issues/1517


> I'd like to start by making it clear that I'm new to Linux. 

A Linux Windows manager thing


>  I think it is related to the PPI of the monitor (108.79) but I'm not sure at all. 

not at all, it just that we are using Linux and a Window Manager so we do not have a centralized way of rendering the cursor (Applications tries to render their own cursor). I think this will be solved in the next [Hyprland  ](https://wiki.hyprland.org/)update.


> On some applications such as Godot and VLC the cursor becomes much larger than norma

Try to check if your app is running under wayland too, maybe it is running over  [x11 / xwayland ](https://www.reddit.com/r/linuxquestions/comments/17ptob7/can_you_explain_xwayland_to_me_using_small_words/)'.
run ` hyprctl clients `  to know which apps are running over ` xwayland = 1 `. '1' means  it is running in xwayland which looks blurry. 


You can google this issues online and binge read this Linux drama. HAHA.
