### ISSUE TITLE
[Bug]: Screen flickering effect when mouse hover over any application

### ISSUE THREAD

**Issue by psilvaricardo** [prasanthrangan/hyprdots#1573]
### Description
Screen flickering effect when mouse hover over any application

### Steps to Reproduce

1. Mouseover / mouse hover any application ( web browser for this example )
2. [Second Step] The application starts flickering quite randomly.

Any help you can give me to fix this annoying issue will be very welcome.

https://github.com/prasanthrangan/hyprdots/assets/125488497/ad4c8472-5925-4d68-a344-da7e8fc84a35

### Environment

uname -a
Linux arch 6.9.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 x86_64 GNU/Linux

### Additional InformatioN

hyprctl version
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

 OS : Arch Linux x86_64 
​​ ​  Kernel : 6.9.3-arch1-1 
​​ ​  Packages : 1522 (pacman), 29 (flatpak) 
​​ ​  Resolution : 2560x1440 
​​ ​  DE : Hyprland 
​​ ​  Terminal : kitty

**Comment by kRHYME7** [comment]
Nvidia?


or try to install `hyprland-git ` see if it still persist. reboot required.

**Comment by psilvaricardo** [comment]
@kRHYME7 sorry for the delay my workload has been crazy lately.

Yes I do have NVidia:  GPU : NVIDIA GeForce RTX 3060 Lite Hash Rate 
                                               ​​ ​  GPU Driver : NVIDIA 550.78 

I believe, by the time of writting, hyprland-git might be broken, I will try later.

![image](https://github.com/prasanthrangan/hyprdots/assets/125488497/18996c7b-2512-4365-8360-7a9c1446f2d0)

**Comment by kRHYME7** [comment]
have you tried downgrading GPU?

**Comment by psilvaricardo** [comment]
@kRHYME7 sorry for the delay.

I haven't tried, how do you downgrade GPU driver? currently I have: 

![image](https://github.com/prasanthrangan/hyprdots/assets/125488497/1814a6c7-d269-49f7-bc52-fa8756293034)

**Comment by dieBakterie** [comment]
It was an easy fix for me with just one environment variable `ELECTRON_OZONE_PLATFORM_HINT=auto` for electron 28+ apps applicable, i'm using this one `ELECTRON_OZONE_PLATFORM_HINT=wayland` and no issues so far. And the `--disable-gpu` flag "fix " is using vaapi that makes electron apps able to use the gpu so no need to disable it, but some work needed to be done, but then you won't need any electron flags(nvidia proprietary nvidia-dkms needed tho) but can't guarantee it to work flawless tho, could be broken again by new release. Follow instructions as on [Hyprland Nvidia wiki](https://wiki.hyprland.org/Nvidia/) and [VAAPI](https://github.com/elFarto/nvidia-vaapi-driver) described. Hope this helps you.

**Comment by psilvaricardo** [comment]
@dieBakterie thanks for your advice, I have not been able to update because there is some issues when updating to the latest version of hyprland-git, I will try again later

![image](https://github.com/prasanthrangan/hyprdots/assets/125488497/38516916-f595-4dee-b031-19582ab09a38)

**Comment by psilvaricardo** [comment]
@dieBakterie @kRHYME7 I got it fixed, thanks for your time and help.

1. Removed hyprland-git and libdisplay-info
2. I did a full system update.
3. Installed latest libdisplay-info and hyprutils-git.
4. Reinstalled hyprland-git
