### ISSUE TITLE
Font missing(?)

### ISSUE THREAD

**Issue by Newer1107** [prasanthrangan/hyprdots#1575]
am I missing a font?
![image](https://github.com/prasanthrangan/hyprdots/assets/116626403/8c35ff92-43c2-42fe-8364-c170b6236ea6)

**Comment by kRHYME7** [comment]
you got this package? 

` ttf-jetbrains-mono-nerd `

**Comment by Newer1107** [comment]
> you got this package?
> 
> `ttf-jetbrains-mono-nerd`

![image](https://github.com/prasanthrangan/hyprdots/assets/116626403/d93020c5-1d68-44ae-8491-2a32a3176e56)
installed it, still the same.

**Comment by kRHYME7** [comment]
@Newer1107  This is only happening when on the bluetooth applet right? 

Can you confirm which pack fixes it?
https://github.com/blueman-project/blueman/blob/main/Dependencies.md#dependencies
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/eb9f27b7-51ca-4272-8a85-f240b4f40ee8)

**Comment by jenil1122** [comment]
I also did notice font issues on chromium browser for certain type of text such as youtube auto play captions .. i used apple fonts while installing hyde

**Comment by abenezerw** [comment]
![image](https://github.com/user-attachments/assets/0e7c1b2d-f085-4d5c-b261-8cde8d4ce9d1)
its the double slashes "//" works fine on my system
it should be "papirus" because that's the only one out of the options in your screenshot that i have in icons. @kRHYME7

**Comment by kRHYME7** [comment]
Use the Bluetooth applet for tooltip as they supported the tooltip preview now

**Comment by abenezerw** [comment]
That one just shows name and nothing else for me.
