### ISSUE TITLE
[Bug]: Size of floating window is larger than screen.

### ISSUE THREAD

**Issue by ashraddhansh** [prasanthrangan/hyprdots#1576]
Window size goes bigger than screen in floating mode and I need to manually resize it each time. Also it didn't remember the previous window size. It happens in all apps. The hyprland scaling is 1.2

**Comment by kRHYME7** [comment]
Hi, as different users have their own preferences, please add each of the unscaled window their own 'windowrule'. Add it inside ` ~/.config/hypr/userprefs.conf `

Here's the wiki  on how to do it  https://wiki.hyprland.org/Configuring/Window-Rules/. 

You can post the issue upstream, https://github.com/hyprwm/Hyprland. This repo only host configurations, this is not the compositor/window manager itself. 

I got this issue too, on x2 scaling.  I just manually added windowrule to fix them.
