### ISSUE TITLE
rofi and new hyprland (v0.41.0)

### ISSUE THREAD

**Issue by Senshi111** [prasanthrangan/hyprdots#1578]
i updated hyprland like a 5 min ago and now there is some kind of issues with rofi. i noticed this problem while using hyprland-git so for that reason i installed only hyprland 15 days ago

rofi menu is now behaves like a classic window

![viber_image_2024-06-11_18-42-41-147](https://github.com/prasanthrangan/hyprdots/assets/40372242/86338bed-4098-43d3-ac89-e4b6a149d92e)

**Comment by kRHYME7** [comment]
Is it the 0.41.0 release ?

**Comment by Senshi111** [comment]
yes

**Comment by kaixenberg** [comment]
I see ur using hyprdots config like me. For me, waybar suddenly stopped showing open window icons after updating hyprland to latest git

**Comment by Evre-nos** [comment]
> I see ur using hyprdots config like me. For me, waybar suddenly stopped showing open window icons after updating hyprland to latest git

Same here

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/263cb076-d012-4a04-9c7c-d3adf27c7193)

Will also add this for context. 

I don't have @Senshi111's issue about rofi.

**Comment by mrhyperbit** [comment]
@Senshi111 install rofi-wayland instead of rofi, it will fix this.

**Comment by vampirepapi** [comment]
> I see ur using hyprdots config like me. For me, waybar suddenly stopped showing open window icons after updating hyprland to latest git

same, anyone found fix for this??

**Comment by kRHYME7** [comment]
@vampirepapi  @Evre-nos 
Here's the same specific issue. Please share your inputs on this thread 
https://github.com/prasanthrangan/hyprdots/issues/1579

**Comment by Senshi111** [comment]
> Hey @Senshi111, try swapping out rofi for rofi-wayland, it should resolve the issue.

that worked for me

**Comment by vampirepapi** [comment]
> > Hey @Senshi111, try swapping out rofi for rofi-wayland, it should resolve the issue.
> 
> that worked for me

could you please explain what steps did you exactly took to fix the issue? TIA

**Comment by Senshi111** [comment]
> > > Hey @Senshi111, try swapping out rofi for rofi-wayland, it should resolve the issue.
> > 
> > 
> > that worked for me
> 
> could you please explain what steps did you exactly took to fix the issue? TIA

just installed rofi-wayland, i had regular rofi installed

**Comment by vampirepapi** [comment]
> > > > Hey @Senshi111, try swapping out rofi for rofi-wayland, it should resolve the issue.
> > > 
> > > 
> > > that worked for me
> > 
> > 
> > could you please explain what steps did you exactly took to fix the issue? TIA
> 
> just installed rofi-wayland, i had regular rofi installed

know icons are visible for ya? in waybar?

**Comment by Senshi111** [comment]
> > > > > Hey @Senshi111, try swapping out rofi for rofi-wayland, it should resolve the issue.
> > > > 
> > > > 
> > > > that worked for me
> > > 
> > > 
> > > could you please explain what steps did you exactly took to fix the issue? TIA
> > 
> > 
> > just installed rofi-wayland, i had regular rofi installed
> 
> know icons are visible for ya? in waybar?

i have icon on waybar but im using regular waybar not git one

![240612_18h30m09s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/40372242/8e63e29d-16b2-4a78-8663-31c6cc74b8c4)

**Comment by kRHYME7** [comment]
Will close this as completed. The whole waybar issue should be discussed here. https://github.com/prasanthrangan/hyprdots/issues/1579
