### ISSUE TITLE
[Bug]: Waybar No Icons and Date Tooltip not Centered;Hyprland v0.41.0 

### ISSUE THREAD

**Issue by itsmenewbie03** [prasanthrangan/hyprdots#1579]
### Description
Before when you have apps running their icons appear on the top right part (based on my preferred waybay config) now they are missing. Also as I remember the Calendar tooltip is centered and now it's not. This happened after I updated to the latest linux firmware.

### Screenshots
* Firefox icon not showing in the icon area
![image](https://github.com/prasanthrangan/hyprdots/assets/89230263/1600af33-eea5-4f56-a5f6-7b52946c6e5a)
* Uncentered Calendar Tooltip
![image](https://github.com/prasanthrangan/hyprdots/assets/89230263/7065b350-4844-4fcc-ab35-c99d1aa642f2)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: EndeavourOS
- Linux Version: `Linux dadsgift 6.9.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 x86_64 GNU/Linux`
- Hyprland Version:
```bash
Hyprland, built from branch  at commit ea2501d4556f84d3de86a4ae2f4b22a474555b9f  (props: bump version to 0.41.0).
Date: Mon Jun 10 14:23:06 2024
Tag: v0.41.0, commits: 4794
flags: (if any)
```
- Installation Environment: On The Main Hardware

**Comment by itsmenewbie03** [comment]
@kRHYME7  where can I track the bug?

**Comment by kRHYME7** [comment]
Please try to see the waybar repository first.

**Comment by itsmenewbie03** [comment]
> Please try to see the waybar repository first.
> 
> https://www.reddit.com/r/hyprland/comments/1dcpklz/wlrtaskbar_module_broken/
> 
> I do not know if someone open up this issue yet. Here's the waybar repo https://github.com/Alexays/Waybar

been searching in the issues on the waybar repo but found nothing similar

**Comment by kRHYME7** [comment]
If most required wlroots backend is rewritten by the Hyprland dev it should make sense that the wlr/taskbar and the  IPC that handles it won't work. So we need to patch waybar to communicate to hyprland again. Feel free to open an issue in waybar and let's see what the dev says about it.

**Comment by vampirepapi** [comment]
> If most required wlroots backend is rewritten by the Hyprland dev it should make sense that the wlr/taskbar and the IPC that handles it won't work. So we need to patch waybar to communicate to hyprland again. Feel free to open an issue in waybar and let's see what the dev says about it.

yeah, i have opened a bug issue in waybar, let's see what they say.

**Comment by kRHYME7** [comment]
Might be better to narrow down the issue into just the ` wlr/taskbar ` failing. As the tooltip might be a different issue. 
https://github.com/prasanthrangan/hyprdots/issues/1560

**Comment by kRHYME7** [comment]
Yow got it fixed upstream of hyprland. 


Note that the fix is on the hyprland-git package. 
 [Hyprland source changes frequently, it is recommended to use the -git version of the dependent hyprwm libraries.](https://aur.archlinux.org/packages/hyprland-git)

Install this 
` yay -Sy hyprutils-git hyprcursor-git hyprlang-git    hyprwayland-scanner-git  ` 
then ` yay -Sy aur/hyprland-git `  (the aur/ flag tells yay to use the aur mirror instead of chaotic-aur) 


![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/9f262f9e-078e-4305-97a8-b5a04526c53d)

**Comment by itsmenewbie03** [comment]
Can confirm this works
> Install this `yay -Sy hyprutils-git hyprcursor-git hyprlang-git hyprwayland-scanner-git ` then `yay -Sy aur/hyprland-git` (the aur/ flag tells yay to use the aur mirror instead of chaotic-aur)

![image](https://github.com/prasanthrangan/hyprdots/assets/89230263/d853f698-45db-4197-8509-5a00d691180c)

**Comment by itsmenewbie03** [comment]
As the issue with the tooltip not being centered is not related with the taskbar icons I close this now.

**Comment by itsmenewbie03** [comment]
@kRHYME7 if the latest patch comes out, do i need to uninstall what I installed fro the workaround?
