### ISSUE TITLE
[Bug]:  vs code  terminal prompt icons not rendering

### ISSUE THREAD

**Issue by devsjuans** [prasanthrangan/hyprdots#1580]
### Description

the prompt icons in vscode are broken, but only in vscode in Kitty are they fine.

### Screenshots

![240612_01h30m39s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/172473042/2fa14870-66cd-4f0c-ad7a-a5e9bc2aab0e)

**Comment by vampirepapi** [comment]
anyone found the fix for this?

**Comment by kRHYME7** [comment]
Add the nerdfont mono to vscode to show the Icons in vscode

**Comment by devsjuans** [comment]
thank you @kRHYME7 
![image](https://github.com/prasanthrangan/hyprdots/assets/172473042/e41d9eae-306a-45c5-8970-f79180858ead)

**Comment by vampirepapi** [comment]
> thank you @kRHYME7 ![image](https://private-user-images.githubusercontent.com/172473042/339188900-e41d9eae-306a-45c5-8970-f79180858ead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDgwMjAsIm5iZiI6MTcxODI0NzcyMCwicGF0aCI6Ii8xNzI0NzMwNDIvMzM5MTg4OTAwLWU0MWQ5ZWFlLTMwNmEtNDVjNS04OTcwLWY3OTE4MDg1OGVhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMzAyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmI2OTc2MTc3ZGE0ZGExZTg1YTgyNGE4Y2NmZmU1NmIwNmZlOTAwYmE0NzU0ZTQ1MGE4ZWE2OGVmYmY1NDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fdqVoHLWZOgZXRoMc0kDkHzOZZQeEtnkGY1dAJwxqCo)

could you please show your settings font family, what you exactly added. TIA

**Comment by vampirepapi** [comment]
> > thank you @kRHYME7 ![image](https://private-user-images.githubusercontent.com/172473042/339188900-e41d9eae-306a-45c5-8970-f79180858ead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDgwMjAsIm5iZiI6MTcxODI0NzcyMCwicGF0aCI6Ii8xNzI0NzMwNDIvMzM5MTg4OTAwLWU0MWQ5ZWFlLTMwNmEtNDVjNS04OTcwLWY3OTE4MDg1OGVhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMzAyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmI2OTc2MTc3ZGE0ZGExZTg1YTgyNGE4Y2NmZmU1NmIwNmZlOTAwYmE0NzU0ZTQ1MGE4ZWE2OGVmYmY1NDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fdqVoHLWZOgZXRoMc0kDkHzOZZQeEtnkGY1dAJwxqCo)
> 
> could you please show your settings font family, what you exactly added. TIA

NVM this helped - 

If the icons are not displaying correctly, ensure that the font name in the settings matches the name exactly as it is installed on your system.
You can use the command fc-list | grep Nerd on Linux to verify the exact name of the installed Nerd Font.

and add the font in Editor:Font Family
![image](https://github.com/prasanthrangan/hyprdots/assets/39551118/5846fd2a-d541-4824-8875-cbe9512ce45c)
