### ISSUE TITLE
[Feature Request]: Rofi audio selector

### ISSUE THREAD

**Issue by ffrancesco94** [prasanthrangan/hyprdots#1583]
### Description

Right now, to change audio source/sink, we right-click on the waybar icon which opens pavucontrol (by the way, there's a bug: pavucontrol is open by default on the first workspace of the main screen, regardless of which workspace is active when the icon is touched). Might be worthwile to make a rofi interface for that that can be called with a keybinding.

### Use Case

Makes it easier (and keyboard-only) to change audio source/sink. At first I didn't even realise that pavucontrol was open.

### Proposed Solution

Have a rofi audio selector, so that changing source/sink can be done on the fly without actually opening a new window

### Alternatives

A good starting point would be to at least open pavucontrol on the active workspace.

### Additional Information

Something along those lines is implemented [here](https://github.com/kellya/rofi-sound).

**Comment by kRHYME7** [comment]
> (by the way, there's a bug: pavucontrol is open by default on the first workspace of the main screen, regardless of which workspace is active when the icon is touched) 

This one is upstream bug will wait for Hyprland to iron this out. 

And Yeah the feature request is useful would be cool if we can find an implementation like this. Will try to see what we can do.

**Comment by kRHYME7** [comment]
Should work like this 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c630bf96-8a23-4cb1-80d7-6aa0dd47e834)

**Comment by kRHYME7** [comment]
checkout https://github.com/prasanthrangan/hyprdots/pull/1588

**Comment by ffrancesco94** [comment]
So from what I understood the selector should appear when right clicking the icon? Doesn't appear for me...

**Comment by kRHYME7** [comment]
Are you sure you fetched the PR? 

what is the output when you run ` volumecontrol.sh -s "" `  ?

**Comment by ffrancesco94** [comment]
`volumecontrol.sh -s ""` opens the right rofi menu, it's just the right-clicking that doesn't work.

**Comment by kRHYME7** [comment]
So the script works. 


Can I see this file? 
` ~/.config/waybar/modules/pulseaudio.jsonc ` 


![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/187f9974-33c7-4565-a2e6-c2c34cd38f32)

**Comment by ffrancesco94** [comment]
Found the issue. I had just logged out and in, but it took a whole reboot for it to actually apply. Thank you, it works!
