### ISSUE TITLE
[Bug]: Battery icon doesn't automatically change

### ISSUE THREAD

**Issue by babylittlepony** [prasanthrangan/hyprdots#1585]
Description

When i plugged battery, the icon still same, it doesn't automatically change to  plugged icon

Expected Behavior

icon changed automatically to what it should be

Actual Behavior

icon doesn't change automatically, must clicked
Screenshots

![not-charged](https://github.com/prasanthrangan/hyprdots/assets/105470161/7b727f92-b45f-44a5-aa47-581fd1565865)

must clicked it to change
![charged](https://github.com/prasanthrangan/hyprdots/assets/105470161/2f97131a-d5ed-4af1-a6ad-13c42d2f4431)

Environment

    Linux Distro: Arch Linux
    Linux Version: Linux archlinux 6.9.3-arch1-1
    Hyprland Version, output of hyprctl version: Hyprland, (props: bump version to 0.40.0).
    Installation Environment: Main Hardware
    Other info: -

**Comment by kRHYME7** [comment]
did you wait for 5 seconds?

**Comment by babylittlepony** [comment]
i didnt know it, thanks
