### ISSUE TITLE
Pack file too large in the Git repository, affecting clone speed.

### ISSUE THREAD

**Issue by shimingsir** [prasanthrangan/hyprdots#1586]
**Description:**  
When cloning the hyprdots repository, I noticed that the .git/objects/pack/ directory takes up nearly 900MB of space, which makes the cloning process very slow.
```zsh
$ du -sh hyprdots
1.1G    hyprdots
$ du -sh hyprdots/.git/objects/pack/
897M    hyprdots/.git/objects/pack/
```

**Environment Information:**  
- Operating System: Arch Linux  
- Git Version: 2.45.2

**Expected Result:**   
It would be great if the Git repository size could be optimized and the pack file size reduced, as this would improve cloning speed and enhance the user experience.
 
Thank you!

My native language is not English, so there might be spelling or grammatical errors. Please bear with me.
):

**Comment by shimingsir** [comment]
Please bear with me. I am a beginner, and my submission might not be perfect. Thank you for your understanding.

**Comment by kRHYME7** [comment]
how did you clone 'HyDE'? 

It's essentially lightweight as there are no wallpapers stored on this repo.

**Comment by shimingsir** [comment]
Sorry for the delay.
The command I used was:
 `git clone https://mirror.ghproxy.com/https://github.com/prasanthrangan/hyprdots.git`.
 I did use a mirror site to clone 'HyDE' due to restrictions caused by the Great Firewall (GFW).

Thank you very much for your suggestion. After following it, the issue has been resolved. I appreciate your patience.

**Comment by kRHYME7** [comment]
No problem. It is actaully stated in the README. 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/beb38af7-4082-4b71-aa45-a4eda6185b08)
