### ISSUE TITLE
[Bug]: SWWW - Black BG - no wallpaper

### ISSUE THREAD

**Issue by FroggieStick** [prasanthrangan/hyprdots#1599]
### Description
SWWW - Black background no wallpaper
```

`~/.config/hyde/themes/Gruvbox Retro ❯ Hyde wallpaper select

09:42:09 PM:: applying wall :: "/home/username/.config/hyde/themes/Gruvbox Retro/wallpapers/raven1.jpg"

~/.config/hyde/themes/Gruvbox Retro ❯ [skip] "/home/username/.config/cava/Wall-Dcol" 
09:42:21 PM[skip] "/home/username/.config/spicetify/Themes/Sleek/color.ini"`

```

I have tried to rebuild/Reload Hyde. deleted swww cache folder and files.
sometimes i can use the super + alt + arrow keys to switch wallpapers and it will eventually show up randomly.

Only one picture is set to this theme. No other images in this setup.

clearly a swww issue but not sure how to resolve it.

When i try to select the wallpaper from CLI it runs extra things like /spicetify/ which isnt even a directory on my machine and the cli gets hung.

**Comment by kRHYME7** [comment]
what happens when you run ` swww restore `

**Comment by FroggieStick** [comment]
Nothing happens with `swww restore`

If found if I 
```
swww kill
swww init
```

it comes back. But when I reboot it goes back to black screen. Have to kill and init everytime but it comes back after.

**Comment by kRHYME7** [comment]
init is deprecated. 

can you run this ` swwwallpaper.sh ` on 2 different terminals, what happen?  run  same command but 2 instances.

**Comment by Shanu-Kumawat** [comment]
facing similar issue with swww, no wallpaper sometime just a black screen, changing wallpaper works once or twice then get stuck, changing theme changes colors and other properties but wallpaper gets stuck and doesnt change

**Comment by BentleyOph** [comment]
Error: "couldn't bind socket: Address already in use (os error 98)"

**Comment by FroggieStick** [comment]
@kRHYME7 
I ran `swwwallpaper.sh` in two separate terminals and had no results. It says it applied the wallpaper but nothing happens.

If i call `swww-daemon `directly since init is deprecated it works. Until i reboot again. Still have to kill swww then call it directly.

**Comment by kRHYME7** [comment]
Let's try to narrow down those  issues 
using this version of swww?
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c264e52e-4f90-4f21-a073-0dbce41d575e)


You can modify  ` ~/.local/share/bin/swwwallpaper.sh  `  and add this line after lline 100 
` swww query && swww restore ` 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/9f18fc37-47a0-49cf-9aae-8389f9ccdb7a)


Try to reboot what happen? 

take note I'm using ` hyprland-git `

**Comment by FroggieStick** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/167017319/f86cf5fd-eb3b-4a77-9e91-9542d5f0a3d8)

After making the edit it seems to have worked. Ive rebooted a couple times now and it always comes back up. Thank you!

can you explain why though? or is this just a bandaid solution.

**Comment by kRHYME7** [comment]
Cool!  Just swww's  breaking change about a week ago.  I did of not make a PR as I cannot merge my own.  I'm actually waiting for someone to do it . Can you do a PR with that changes please? Will merge it immediately

**Comment by FroggieStick** [comment]
@kRHYME7 
Sorry, never done a pull request before lol. I guess i did it right. Let me know if not.

**Comment by kRHYME7** [comment]
Will close this for now

**Comment by BentleyOph** [comment]
Added the lines and im still getting the issue

**Comment by kRHYME7** [comment]
rebooted?

**Comment by BentleyOph** [comment]
Added the lines and im still getting the issue 

> rebooted?

yeah ...still getting that issue ...could it be my swww version ?

**Comment by kRHYME7** [comment]
Hey try this 

`  killall swww-daemon  ` 


then open 2 separate terminals

run ` swww-daemon` 
on the other term run ` swww restore `  

Please describe the behaviour.

**Comment by BentleyOph** [comment]
> Hey try this
> 
> ` killall swww-daemon `
> 
> then open 2 separate terminals
> 
> run ` swww-daemon` on the other term run `swww restore`
> 
> Please describe the behavior.
> 
> Also can you please share the output of this ?
> 
> ` grep "swww restore" ~/.local/share/bin/swwwallpaper.sh`
Fix was updating swww
