### ISSUE TITLE
My Wallpapers are not loading into the Themeselect or Wallselect

### ISSUE THREAD

**Issue by lnagler1** [prasanthrangan/hyprdots#160]
![image](https://github.com/prasanthrangan/hyprdots/assets/92120753/f0540fa1-7654-42fc-a14d-324efc2c3ca0)

**Comment by prasanthrangan** [comment]
Its just missing the cache... can you please run this -

```
cd ~/Hyprdots/Scripts
./create_cache.sh
```

**Comment by lnagler1** [comment]
./create_cache.sh solved my problem
