### ISSUE TITLE
[Help]: Waybar config resets each time I switch a theme

### ISSUE THREAD

**Issue by Hexanchus29** [prasanthrangan/hyprdots#1601]
Each time I switch a theme, my custom waybar config is overwritten with the default theme's config (including: waybar modules, waybar's style.css file)

Any way that I can replace the default theme's waybar config with mine ? (using Tokyo Night theme)

sorry if this is a dumb question im new to WM's

**Comment by Enigma1309** [comment]
edit config.ctl instead of editing css files

**Comment by Hexanchus29** [comment]
I dont really understand it at all ;d

cant find anywhere where its explained

**Comment by dieBakterie** [comment]
Ok it's separates by `|` and the First is 0(disabled) and 1 stands for enabled so the bar that's been used. Then the second segment is for the soze of the bar or it's height, Text and Icon size. The Next 3 segments are for left, middle and right modules. And those you can group additionally or Split in Segments. If you want the idle Indikator and the clock/calendar in the Same segment just do `( idle_xxx clock )` and with ` ` the Next `( custom/wbar windows hyprland/workspaces)` then these two Segments are on the left for example.

**Comment by Hexanchus29** [comment]
thanks so much that fixed the layout, however the icons for the modules still get changed to the default ones and the style.css file gets  reverted to default aswell

**Comment by kRHYME7** [comment]
@Hexanchus29  Edit the file inside the ./modules directory


![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/e32ff0c8-bfdf-4a31-a2ba-95cd00fed3a3)

**Comment by Hexanchus29** [comment]
Ohhh im dumb lol. thanks a lot. using the workspace module in config.ctl however doesnt show persistent workspaces and only shows ones that have a window open in them, can i fix this in the workspaces.jsonc file ?

**Comment by Hexanchus29** [comment]
Nevermind, fixed it ! alright,  i think thats all, thank you for your help

**Comment by gadour21** [comment]
> Nevermind, fixed it ! alright, i think thats all, thank you for your help

how plss
