### ISSUE TITLE
Installation Issue on Arch Linux

### ISSUE THREAD

**Issue by JSTNFPS** [prasanthrangan/hyprdots#1605]
When attempting to install hyprdots, everything else works fine except the installation of oh-my-zsh. I get the following error.

==> Making package: oh-my-zsh-git r6192.be4a95297-1 (Sun 16 Jun 2024 06:47:36 PM EDT)
==> Retrieving sources...
  -> Updating oh-my-zsh-git git repo...
  -> Found 0001-zshrc.patch
==> Validating source files with sha256sums...
    oh-my-zsh-git ... Skipped
    0001-zshrc.patch ... Passed
==> Making package: oh-my-zsh-git r6192.be4a95297-1 (Sun 16 Jun 2024 06:47:38 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating oh-my-zsh-git git repo...
  -> Found 0001-zshrc.patch
==> Validating source files with sha256sums...
    oh-my-zsh-git ... Skipped
    0001-zshrc.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of oh-my-zsh-git git repo...
Cloning into 'oh-my-zsh-git'...
done.
==> Starting prepare()...
patching file zshrc
Hunk #1 FAILED at 1.
Hunk #2 succeeded at 72 with fuzz 2 (offset 16 lines).
Hunk #3 succeeded at 101 (offset 20 lines).
1 out of 3 hunks FAILED -- saving rejects to file zshrc.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'oh-my-zsh-git-r6192.be4a95297-1': 
error: packages failed to build: oh-my-zsh-git-r6192.be4a95297-1

**Comment by simplemachine-zz** [comment]
I solved this by downloading the commit (0c9b42a) prior to this update that caused the problem and replacing the content in the src folder inside the oh-my-zsh-git which is inside the yay folder in .cache and open a terminal in the oh-my-zsh-git folder and use makepkg -si.

**Comment by so-uvik** [comment]
> I solved this by downloading the commit `(0c9b42a)` prior to this update that caused the problem and replacing the content in the `src` folder inside the `oh-my-zsh-git` which is inside the `yay` folder in `.cache` and open a terminal in the `oh-my-zsh-git` folder and use `makepkg -si`

Excuse me if i am wrong but i don't see any `src` folder in the downloaded commit `(0c9b42a)`.
![image](https://github.com/prasanthrangan/hyprdots/assets/102872077/bfbf3f38-7105-4bf0-92ce-a64186b21087)
On the left is the `~/.cache/yay/oh-my-zsh-git` folder and on the right the specific commit `(0c9b42a)`, downloaded from ohmyzsh

**Comment by simplemachine-zz** [comment]
Remove the content inside src from the left and extract the content from the commit inside the src folder.

**Comment by simplemachine-zz** [comment]
Thats the commit:
[0c9b42a](https://github.com/ohmyzsh/ohmyzsh/tree/0c9b42a863778d67aee22bbd43f296110fe1f047)

Copy all of this:
![240617_12h09m04s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/5226334/26273b99-d22c-447c-9b5c-3d02aca7611f)

Here:
![240617_12h07m54s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/5226334/32245244-d0d4-4064-b0e2-c34dc5ed981e)

Open Terminal here:
![240617_12h13m18s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/5226334/55cdc095-2dd0-4024-895a-0d3271ca9147)

Use `makepkg -si` to install

**Comment by so-uvik** [comment]
I am still facing the same error again. Are you using the up to date, `oh-my-zsh-git r6192.be4a95297-1` version of oh-my-zsh or some old version? I've tried copy but still the error won't go away.

**Comment by so-uvik** [comment]
I am still encountering the same issue even after copying the files over from the specific ohmyzsh commit.
Let me tell you, what i did.
Downloaded `(0c9b42a)` from ohmyzsh repo
Went to `~/.cache/yay/oh-my-zsh-git/src` wiped the two files that were present, and pasted the contents of the downloaded commits inside it.
Changed directory back, and ran `makepkg -si`
Got the same error. Are you using the latest oh-my-zsh-git version i.e. `oh-my-zsh-git r6192.be4a95297-1`? Or any older version?

**Comment by kRHYME7** [comment]
For anyone who just want to build it successfully.

the error is due to the  latest patch.  
So please navigate to the PKGBUILD 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/e16e4150-82f7-4f2a-b5d5-2962e2d6fabb)

Find that line then just comment it for now. 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/d0a86aff-c64d-47de-b1da-6367cb7a5e7c)

If the package updates soon, and the issue is fixed, you'll get the update too.

This workaround should not break it, as we are only removing the patch. (Ig the patch is not critical for functionality)

**Comment by JSTNFPS** [comment]
I just tried to comment that line out, when I run the install script again it still fails giving me the same error. After I get the same error I go back to the PKGBUILD file and the file got reverted back to default, thus removing my comment.

**Comment by JSTNFPS** [comment]
> I am still encountering the same issue even after copying the files over from the specific ohmyzsh commit. Let me tell you, what i did. Downloaded `(0c9b42a)` from ohmyzsh repo Went to `~/.cache/yay/oh-my-zsh-git/src` wiped the two files that were present, and pasted the contents of the downloaded commits inside it. Changed directory back, and ran `makepkg -si` Got the same error. Are you using the latest oh-my-zsh-git version i.e. `oh-my-zsh-git r6192.be4a95297-1`? Or any older version?



> I solved this by downloading the commit `(0c9b42a)` prior to this update that caused the problem and replacing the content in the `src` folder inside the `oh-my-zsh-git` which is inside the `yay` folder in `.cache` and opening a terminal in the `oh-my-zsh-git` folder and using `makepkg -si`

How would I be able to install that specific commit? Im using minimal arch and I'm quite new to linux as well so im still learning my way around things.

**Comment by kRHYME7** [comment]
Ops I forgot to continue, 

after editing the file install, build  oh-my-zsh first 
in archlinux:

`  makepkg -sfi `  inside the PKGBUILD directory. 

now oh-my-zsh should be installed . 

Run the installer, then it should skip the oh-my-zsh as it is already installed

**Comment by JSTNFPS** [comment]
Noted, I'll give that a try and come back with updates, your help is very much appreciated! :D

**Comment by JSTNFPS** [comment]
> Ops I forgot to continue,
> 
> after editing the file , build oh-my-zsh first in archlinux:
> 
> ` makepkg -sfi` inside the PKGBUILD directory.
> 
> now oh-my-zsh should be installed .
> 
> Run the installer, then it should skip the oh-my-zsh as it is already installed

This worked perfectly! thank you very much
