### ISSUE TITLE
[Bug]: updating system could not satisfy dependencies

### ISSUE THREAD

**Issue by vampirepapi** [prasanthrangan/hyprdots#1613]
### Description

Updating system results in error: failed to prepare transaction (could not satisfy dependencies)

### Steps to Reproduce

1. sudo pacman -Syu

### Expected Behavior

should update the pkgs!

### Actual Behavior

❯ sudo pacman -Syu
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing libdisplay-info (0.2.0-1) breaks dependency 'libdisplay-info.so=1-64' required by hyprland-git

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/39551118/1f961bb2-cd41-4b1d-b098-3a364fef0c6a)

TIA

**Comment by kRHYME7** [comment]
try to remove  ` gamescope ` first. if you won't use it or wait for it to be fixed on its own. 

![Uploading image.png…]()
https://github.com/ValveSoftware/gamescope/issues/1390
https://bbs.archlinux.org/viewtopic.php?id=297004

**Comment by vampirepapi** [comment]
@kRHYME7 
I see a [fix](https://gitlab.archlinux.org/archlinux/packaging/packages/gamescope/-/issues/3) is being prepared. If I don't try to fix it myself, will it get fixed automatically? Will I be able to get the fix when I update the system?

**Comment by kRHYME7** [comment]
Yeah maybe. 

The only problem here is ` libdisplay-info ` can't be updated because of gamescope conflicting the update. So either delete gamescope if you don't use it (install if it's already fixed). Or wait for the package manager to resolve it.

**Comment by vampirepapi** [comment]
I removed GameScope and was able to **update the system**. However, I'm not sure what happened; there was an issue with the SDDM loop. Creating the symlink below helped resolve it:
bash
sudo ln -s /usr/lib/libdisplay-info.so /usr/lib/libdisplay-info.so.1

**Comment by kRHYME7** [comment]
>  sudo ln -s /usr/lib/libdisplay-info.so /usr/lib/libdisplay-info.so.1

This one is probably a bad Idea. (don't forget to revert this back to normal)

updating ` yay -Sy libdisplay-info ` should fix it

**Comment by vampirepapi** [comment]
> > sudo ln -s /usr/lib/libdisplay-info.so /usr/lib/libdisplay-info.so.1
> 
> This one is probably a bad Idea. (don't forget to revert this back to normal)
> 
> updating `yay -Sy libdisplay-info` should fix it

Okay buddy, I will try this once I get home.
