### ISSUE TITLE
[Bug]: Keyboard keys don't work after lid close - open

### ISSUE THREAD

**Issue by WantDead** [prasanthrangan/hyprdots#1614]
### Description

Keyboard keys don't work after lid close - open
except super + "0-9" and possibly some others
For me this did not pose any problem, because I could simply switch between workspaces and everything worked, but now I wanted to add swaylock activation after closing and opening the laptop lid
And in this situation this becomes a problem, since the keyboard does not respond to any press
And all I have to do is manually restart the laptop

### Steps to Reproduce

1. Add swaylock for lid close-open
2. Close-Open lid
3. Keys don't work

### Screenshots

-

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]
- Arch
- 6.9.5-arch1-1
- Hyprland 0.41.1
- Main Hardware

**Comment by vampirepapi** [comment]
This was happening to me too. I removed the swaylock config, and now it's working fine.

**Comment by kRHYME7** [comment]
Try https://github.com/hyprwm/hyprlock

**Comment by Andrjs** [comment]
Try to add these lines in the misc section of  hyprland.conf file:

misc {

    mouse_move_enables_dpms=true
    key_press_enables_dpms=true
}

**Comment by WantDead** [comment]
@Andrjs no, didn't work :(

**Comment by WantDead** [comment]
@kRHYME7 @vampirepapi ok i test it, thx
