### ISSUE TITLE
how to add your wallpaper to an active theme

### ISSUE THREAD

**Issue by Gecoste** [prasanthrangan/hyprdots#1617]
I had problems adding my wallpaper to the selected theme, when adding it to the themesdir/wallpapers folder, I did not achieve the result

**Comment by kRHYME7** [comment]
what results? can you share some screenshots? The images needs to be cached so you might need to run `Hyde reload ` to atleast reload the missing cached files. (thumbnails etc)

**Comment by vampirepapi** [comment]
> I had problems adding my wallpaper to the selected theme, when adding it to the themesdir/wallpapers folder, I did not achieve the result

![image](https://github.com/prasanthrangan/hyprdots/assets/39551118/de5682f4-c419-4c0b-8c0f-e3daa67e7257)

Hey, download the wallpaper and from Dolphin APP, move  to the path where your wallpaper is located. Right-click on the image, and you will get the 'Add to Wallpaper' option.

**Comment by vinayydv3695** [comment]
Never know you can do that   but i prefer terminal  so 
cp -r /home/zura/ps/anime.png   /home/zura/.config/hyde/themes/'Rosé Pine'/wallpapers
