### ISSUE TITLE
[Bug]: Master:New_is_Master does not exist.

### ISSUE THREAD

**Issue by FroggieStick** [prasanthrangan/hyprdots#1621]
## Bug Report
Getting an error <Master:new_is_master> does not exist after updating this morning.

### Description
Error: "Config error in file ~/.config/hypr/hyprland.conf at line 104: config option <master:new_is_master> does not exist.

### Steps to Reproduce
Latest Updates.

### Environment
Arch

### Additional Information
~~If i comment out the line in the .conf file my bar top bar disappears all together.~~
Rebooted and bar came back.

**Comment by dieBakterie** [comment]
Upstream changes needs to be adjustet in this repo too. It's deprecated that's why it's not working.

**Comment by dieBakterie** [comment]
I've Not this problem and i comment the master section in full Out.

**Comment by FroggieStick** [comment]
> I've Not this problem and i comment the master section in full Out.

I rebooted and the bar came back thankfully.

**Comment by dieBakterie** [comment]
https://github.com/prasanthrangan/hyprdots/pull/1620 Here IS the fix should pull Updates or fix IT yourself it's `new_status = master` now.

**Comment by dieBakterie** [comment]
> > I've Not this problem and i comment the master section in full Out.
> 
> I rebooted and the bar came back thankfully.

Propably just restarting the bar with `strg+alt+w` solved this too.

**Comment by FroggieStick** [comment]
Thank you!
