### ISSUE TITLE
DIsplay Refresh Rate / FPS Issue

### ISSUE THREAD

**Issue by Kitsunejasutin** [prasanthrangan/hyprdots#163]
I freshly installed your dots and it's the one of the simplest setup out there with brightness and volume support. Configs looks simple and easy to learn specially it's my first time with this kind of setup.

Initially I am having issues with the Refresh Rate of my second monitor which supports 144hz. Which I fixed later on (maybe), Currenly I am getting 35-50 fps on both of my external monitor and laptop monitor specially when windows are open. I have GTX 1050 as gpu. I am pasting some info below that might help. I am thinking that I might be missing some display drivers but I can't figure it out where to start installing stuff. Thank you in advance!

![image](https://github.com/prasanthrangan/hyprdots/assets/73803767/6be47216-ced4-45ac-a847-9fba3b8d56e4)
![image](https://github.com/prasanthrangan/hyprdots/assets/73803767/daba0930-945d-4896-a664-9b8371f072ec)
![image](https://github.com/prasanthrangan/hyprdots/assets/73803767/e4c5370a-559d-4ff8-b9e9-4bcac3f7c37d)

**Comment by prasanthrangan** [comment]
Hi, thank you so much! glad it works for you :)

> Initially I am having issues with the Refresh Rate of my second monitor which supports 144hz. Which I fixed later on (maybe), Currenly I am getting 35-50 fps on both of my external monitor and laptop monitor specially when windows are open. I have GTX 1050 as gpu. I am pasting some info below that might help. I am thinking that I might be missing some display drivers but I can't figure it out where to start installing stuff. Thank you in advance!

Your `monitors.conf` looks good, I don't see anything wrong in here...
Do you mean you 35-50 fps in games or is it the hyprland animations laggy?

nvidia driver should already be installed, please check with `nvidia-smi` command.
as you are using laptop with hybrid graphics, you might have to set nvidia as primary, please follow the instructions [here](https://wiki.hyprland.org/Configuring/Multi-GPU/) to do that.

**Comment by Kitsunejasutin** [comment]
Hyprland animation feels laggy. Will look into that wiki, I didn't see that Multi GPU one when I was doing the monitors

**Comment by quiet69** [comment]
it was quite laggy on my pc too... so i ran this
`lspci -k | grep -A 2 -E "(VGA|3D)"`
and it showed nouveau drivers. i then installed nvidia-dkms and reboot fixed it

**Comment by Kitsunejasutin** [comment]
> it was quite laggy on my pc too... so i ran this `lspci -k | grep -A 2 -E "(VGA|3D)"` and it showed nouveau drivers. i then installed nvidia-dkms and reboot fixed it

I have a screenshot above showing the result of the same command, it shows kernel driver in use is already nvidia so maybe just me. If I unplugged the external monitor, my main laptop monitor is now working fine. Added `env = WLR_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0` and vice versa, still having those slow animations

**Comment by prasanthrangan** [comment]
please do check if the `nvidia-dkms` package is installed and  `nvidia_drm.modeset=1` set in grub?

**Comment by Kitsunejasutin** [comment]
> please do check if the `nvidia-dkms` package is installed and `nvidia_drm.modeset=1` set in grub?

It's all set
![image](https://github.com/prasanthrangan/hyprdots/assets/73803767/cbc7845a-4115-4425-a026-f2c05c34f35e)
![image](https://github.com/prasanthrangan/hyprdots/assets/73803767/192f7a13-cc40-4778-851c-b918c60c303d)

**Comment by Kitsunejasutin** [comment]
This is my main laptop screen when windows opened on second monitor
![image](https://github.com/prasanthrangan/hyprdots/assets/73803767/95fee2cf-b44d-4aff-9ff0-83f2d7b7cf40)
This is without
![image](https://github.com/prasanthrangan/hyprdots/assets/73803767/ff734797-e65d-4653-a707-d5414c57ba0b)

The same issue with my external monitor
![image](https://github.com/prasanthrangan/hyprdots/assets/73803767/3e30cb5f-3105-436b-9842-89ba5b54e3ad)

**Comment by prasanthrangan** [comment]
hmm, strange behavior... does it work when both monitors are set to 60hz? and what about setting it to auto, does hyprland detect the correct refresh rate?

**Comment by Kitsunejasutin** [comment]
> hmm, strange behavior... does it work when both monitors are set to 60hz? and what about setting it to auto, does hyprland detect the correct refresh rate?

Setting them both preferred makes them both 60hz

**Comment by Kitsunejasutin** [comment]
> Hi, thank you so much! glad it works for you :)
> 
> > Initially I am having issues with the Refresh Rate of my second monitor which supports 144hz. Which I fixed later on (maybe), Currenly I am getting 35-50 fps on both of my external monitor and laptop monitor specially when windows are open. I have GTX 1050 as gpu. I am pasting some info below that might help. I am thinking that I might be missing some display drivers but I can't figure it out where to start installing stuff. Thank you in advance!
> 
> Your `monitors.conf` looks good, I don't see anything wrong in here... Do you mean you 35-50 fps in games or is it the hyprland animations laggy?
> 
> nvidia driver should already be installed, please check with `nvidia-smi` command. as you are using laptop with hybrid graphics, you might have to set nvidia as primary, please follow the instructions [here](https://wiki.hyprland.org/Configuring/Multi-GPU/) to do that.

Does this spit anything? Thou it shows that hyprland is on gpu's processes but 1MB usage
![image](https://github.com/prasanthrangan/hyprdots/assets/73803767/38e77743-33a6-4758-9e74-0774ebfd1ca2)

**Comment by Kitsunejasutin** [comment]
I found out that if I'll be disabling my laptop monitor it will use the gpu and actually use more memory usage. I guess I am stuck with this setup since my HDMI is connected to the gpu itself. I'll stick to this for now I guess

**Comment by prasanthrangan** [comment]
you could try raising this with hyprland team
