### ISSUE TITLE
[Bug]: Zsh auto-suggestion not working

### ISSUE THREAD

**Issue by Sitolam** [prasanthrangan/hyprdots#1631]
### Description

The auto-suggestion of zsh doesn't appear. 

### Expected Behavior

Seeing a suggestion.

### Actual Behavior

Just white text without any suggestions.

### Screenshots
![image](https://github.com/prasanthrangan/hyprdots/assets/79202140/172f4ba7-31fe-4cfb-95ed-1fe1da3cafd7)

### Additional Information

First it worked but then after I think running `./install.sh -r` it didn't work anymore.

**Comment by kRHYME7** [comment]
you should rerun the Script to reinstall the zsh plugins.

**Comment by Sitolam** [comment]
> you should rerun the Script to reinstall the zsh plugins.

After running `./install.sh` it was solved thank you.
