### ISSUE TITLE
[Feature Request]: Add Hyprspace plugin

### ISSUE THREAD

**Issue by Sitolam** [prasanthrangan/hyprdots#1633]
### Description

Add the Hyprspace plugin to the configuration. https://github.com/KZDKM/Hyprspace

https://github.com/prasanthrangan/hyprdots/assets/79202140/85015521-5f35-402d-a38d-91ce84391246 

(demo video from https://github.com/KZDKM/Hyprspace)

### Use Case

It adds a cool workspace overview.

### Additional Information

If it isn't suited for the repository could someone explain how I could implement it in my own fork of the project?

**Comment by Sitolam** [comment]
Don't use https://github.com/KZDKM/Hyprspace it doesn't work on the new version of Hyprland use https://github.com/ReshetnikovPavel/Hyprspace.

**Comment by kRHYME7** [comment]
Yeah that's why adding them as default causes more problems. I think plugins are too user specific for now.   The best way to implement a plugin is maybe request the main Hyprland to add it as a feature instead.

**Comment by Sitolam** [comment]
> Yeah that's why adding them as default causes more problems. I think plugins are too user specific for now. The best way to implement a plugin is maybe request the main Hyprland to add it as a feature instead.

I completely understand I got it working in my system so it's fine. I appreciate the quick replies 😎
