### ISSUE TITLE
[Bug]: Invisible cursor in GIMP

### ISSUE THREAD

**Issue by Rastafaustian** [prasanthrangan/hyprdots#1634]
### Description

When using GIMP (both flatpak and native) the cursor is invisible when mousing over most UI elements except for text boxes and window resizers (the tool cursors show up fine when editing the image itself). After noticing this, I did a fresh reinstall of vanilla Hyprland to test, and the problem only reemerged when I reinstalled HyDE. This is definitely an issue with something to do with  HyDE, not Hyprland. I've tried searching, but I can't find anything helpful regarding this issue. My apologies if I've overlooked an existing fix.

Edit: Just noticed the same issue when using reflector-simple

Edit 2: Spontaneously and for no apparent reason I now have a cursor in GIMP, but it's one from a theme I'm not using. As far as I know I haven't changed or installed anything that would have this effect. It's possible that I've done something to cause this, but I really don't think so.

**Comment by Phaethonix** [comment]
This happens to me too in GIMP, scrcpy, and Ren'Py games like Being a DIK. My workaround right now is that when I change the wallpaper or theme, the cursor will show up for a few minutes, but if I don't move my mouse for too long, it disappears again. Really annoying lmao

**Comment by kRHYME7** [comment]
enable no hardware cursor.

**Comment by Phaethonix** [comment]
> enable no hardware cursor.

![Image](https://github.com/user-attachments/assets/ac3d33a2-b606-450f-ac07-238c4e7d3a4b)

Like this right?

**Comment by kRHYME7** [comment]
yup

**Comment by Phaethonix** [comment]
Didn't change anything, I'm afraid. Granted, I kinda dumb maybe I missed something lol 🤣

**Comment by kRHYME7** [comment]
>  I'm afraid. Granted, I kinda dumb 


Can't help you with that...


But if you feel like trying add 
```
cursor {
no_hardware_cursors = true
}
```

in ` ~/.config/hypr/userprefs.conf `

**Comment by Phaethonix** [comment]
Ahh, I see. That’s why I said I’m kinda dumb, lol. I meant that adding them to the `userprefs.conf` or `hyprland.conf` didn’t change anything, if that’s what you meant. Sorry, English is not my first language.

**Comment by kRHYME7** [comment]
` hyprctl getoption cursor:no_hardware_cursors -j ` 

output of this?

**Comment by Phaethonix** [comment]
![Image](https://github.com/user-attachments/assets/c6a4e611-1105-44e9-98b9-dce6ef0a303f)

**Comment by kRHYME7** [comment]
your configs are properly set, sadly this is more of xwayland issues you got. We can't do anything at this point.

**Comment by Phaethonix** [comment]
Nah man, never mind. Thanks for being patient. And yeah, I guess as much, but like I said, it's more of an inconvenience than anything.
