### ISSUE TITLE
Need help about MTP

### ISSUE THREAD

**Issue by laleeroy** [prasanthrangan/hyprdots#1639]
Can you help me where to find the path of the MTP devices?
Copying manually in dolphin file manager is working, but I want to copy with script and I needed the path for mtp devices

**Comment by kRHYME7** [comment]
Repo's not a bash 101. Better to open a discussion. Or the Discord channel. 


But probably external devices can be in /dev/ or inside ` $XDG_RUNTIME_DIR/<UID> ` you can ls on those path.

**Comment by laleeroy** [comment]
Thank you!
