### ISSUE TITLE
[Bug]: stuck on the shutting down

### ISSUE THREAD

**Issue by vampirepapi** [prasanthrangan/hyprdots#1642]
### Description

Today, when rebooting, I got stuck on the "shutting down" page and had to forcefully shut down my device by holding down the power button. This allowed me to reboot it successfully.

### Steps to Reproduce

1. Suspend the system
2. Power on
3. Shutdown

### Expected Behavior

Should shutdown the system

### Actual Behavior

Hangs on shutdown screen, capslock led blinks continously.

### Screenshots
![PXL_20240701_103034170](https://github.com/prasanthrangan/hyprdots/assets/39551118/90d16ee0-4f69-471f-bd01-a6322f743081)

**Comment by vampirepapi** [comment]
@kRHYME7 do you anything about this buddy?

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/bba236fc-7b21-4f82-b27c-c1ab72621b72)


There should something here  colored in red.  Can you take a photo of it?

**Comment by vampirepapi** [comment]
> ![image](https://private-user-images.githubusercontent.com/53417443/344879196-bba236fc-7b21-4f82-b27c-c1ab72621b72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDA1MzgsIm5iZiI6MTcxOTkwMDIzOCwicGF0aCI6Ii81MzQxNzQ0My8zNDQ4NzkxOTYtYmJhMjM2ZmMtN2IyMS00ZjgyLWIyN2MtYzFhYjcyNjIxYjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA2MDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMWQ3MTBmYzAxN2FhYWVjODkyYjEyOGE1NjA2OWY4OTdhZjcwZGFjYWI3Y2E1NmZhYmE1ZTNkZjRmMmM1MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kdSUHu8r5VLwK-5i6MAoCEBnxIw88UUaWoI42YzdLkw)
> 
> There should something here colored in red. Can you take a photo of it?

nothing after that, it remains stuck there without any further progress.

**Comment by Vakkaria** [comment]
it might be kernel panic. Usually it happens on start/shutdown/updating and have blinking caps lock. If your GPU is nvidia try to change nvidia-dkms to nvidia-open-dkms

**Comment by vampirepapi** [comment]
> it might be kernel panic. Usually it happens on start/shutdown/updating and have blinking caps lock. If your GPU is nvidia try to change nvidia-dkms to nvidia-open-dkms

yes this is what exactly happening, okay will try.
Thanks

**Comment by abenezerw** [comment]
> > it might be kernel panic. Usually it happens on start/shutdown/updating and have blinking caps lock. If your GPU is nvidia try to change nvidia-dkms to nvidia-open-dkms
> 
> yes this is what exactly happening, okay will try. Thanks

Would you mind closing as solved if you no longer have this issue @vampirepapi
