### ISSUE TITLE
[Feature Request]: Is there any plans of using ags 

### ISSUE THREAD

**Issue by chrollorifat** [prasanthrangan/hyprdots#1645]

**Comment by NotAF0e** [comment]
This would be wonderful +1

**Comment by kRHYME7** [comment]
Hey how about sharing a working ags config then will do it in wallbash. How bout that?

**Comment by chrollorifat** [comment]
> Hey how about sharing a working ags config then will do it in wallbash. How bout that?

Here, you can check out this repo: https://github.com/Jas-SinghFSU/HyprPanel

**Comment by kRHYME7** [comment]
Cool. But this would become a breaking change in the repo. 

1. How about  I will fork the above repo and try  maintaining it.

Then we can have `Hyde-panel` which at first becomes an installer and should populate Hyprpanel to `~/.config/hydepanel` 

This should work as a separate package and configuration without  touching ./ags folder. 

I'm not sure If I can pull it off but the main goal of forking it is to make sure certain files will be placed correctly.

2. You guys can disregard 1.
 The best approach for me is to just help you make a wallbash template for this. I think this one is easy. Then the panels should be DIY. This way we have lesser issues and obligations on this repo.

**Comment by Sitolam** [comment]
> Cool. But this would become a breaking change in the repo.
> 
>     1. How about  I will fork the above repo and try  maintaining it.
> 
> 
> Then we can have `Hyde-panel` which at first becomes an installer and should populate Hyprpanel to `~/.config/hydepanel`
> 
> This should work as a separate package and configuration without touching ./ags folder.
> 
> I'm not sure If I can pull it off but the main goal of forking it is to make sure certain files will be placed correctly.
> 
>     2. You guys can disregard 1.
>        The best approach for me is to just help you make a wallbash template for this. I think this one is easy. Then the panels should be DIY. This way we have lesser issues and obligations on this repo.

I like option 1 😃

**Comment by kRHYME7** [comment]
Hyprpanel Lags when I toggle something 😭

**Comment by dotaxis** [comment]
>        The best approach for me is to just help you make a wallbash template for this. I think this one is easy. Then the panels should be DIY. This way we have lesser issues and obligations on this repo.

I would greatly appreciate this if you still have any interest :)

**Comment by kRHYME7** [comment]
For option 2 

We need to know where the Hyprpanel gets it's colors. Is it hardcoded? follows GTK? can we declare it in a single file?.

**Comment by dotaxis** [comment]
There is a themes folder in the repo filled with JSON files that contain the colours for each theme.

I don't actually use AGS yet so I'm not sure if that's actually what you're asking.

**Comment by kRHYME7** [comment]
This? 



https://github.com/Jas-SinghFSU/HyprPanel/blob/master/scss/style/colors.scss

**Comment by Jas-SinghFSU** [comment]
HyprPanel dev here, will provide more info tomorrow. Also, what toggle are causing you to lag?

**Comment by kRHYME7** [comment]
> HyprPanel dev here, will provide more info tomorrow.  

Wow! Hi, it will be easy to integrate Hyprpanel if there is an existing pywal template (Which I think there is ).  The script use to generate colors only need the target file and we can make a template for the target file. I guess ags can update CSS dynmically right? 


>  Also, what toggle are causing you to lag?

All the buttons here makes the cursors laggy. But I guess this can be fix later on
![image](https://github.com/user-attachments/assets/2d4a72a5-e7ff-4eee-80a9-c102ea60adcc)
Edit: popups like notification also tends to lag. 

Some disclaimer, I'm no owner of this repo therefore I can't guarantee and confident to merge more features on this repo. What I can do though is adding some patches so we can at least integrate something to his repo without changing it fundamentally. 

We can dedicate a wiki or some sort of howto page ( to extend this repo's functionality)  for ` Hyprpanel ` and also other external rices .

**Comment by kRHYME7** [comment]
So the lag is due to missing dependencies ` matugen-bin gpu-screen-recorder libgtop python-gpustat`  I do not know though which one fixes it.

**Comment by sitolam** [comment]
How can I test this?

**Comment by kRHYME7** [comment]
@Jas-SinghFSU  Will definitely open an issue soon. But theming hyprpanel is so easy. 

Using ` ags -r "useTheme('${cacheDir}/landing/hyprpanel_wallbash.json')" `

![image](https://github.com/user-attachments/assets/7bf84e2f-8ecd-4ae3-b5bb-daf701170056)
![image](https://github.com/user-attachments/assets/fc29aa69-67aa-4eae-8cf8-99417123570a)
![image](https://github.com/user-attachments/assets/face9d40-569c-4762-a1f0-75179d76d6c2)
![image](https://github.com/user-attachments/assets/6cd33028-65bd-4f9f-8648-818048555611)
![image](https://github.com/user-attachments/assets/2d7a6597-3b8e-4c5f-b7c2-503674d1df1b)

**Comment by Jas-SinghFSU** [comment]
WTF, that's so sick!

**Comment by kRHYME7** [comment]
> WTF, that's so sick! 

It's because of your implementation making it easy to integrate. 

BTW is there a way to store hyprpanel configs from a different directory without linking it? 

example 
` ags -c ~/.config/HyprPanel/config.js  ` (This works ) but importing in the GUI reverts it back to  ~/.config/ags

**Comment by Jas-SinghFSU** [comment]
I haven't looked in to #.2 at yet. Most of theming I've done so far has been manual.

As for #.1 you're saying that importing a config in the gui restarts the bar without the config directory?

**Comment by kRHYME7** [comment]
1. Yes It forgets about the initial -c path I gave.


2. I've tried to finish the tutorial for ags and that time I did not do theming at all, it follows the gtk by default.

**Comment by Jas-SinghFSU** [comment]
I'll have to look at default gtk theme some other time but I can provide a way to specify a restart config in the useTheme method if that would help

**Comment by kRHYME7** [comment]
>  useTheme method if that would help 

Thank you! Also, Will definitely open an issue in your repo.

**Comment by kRHYME7** [comment]
Hello to everyone following this thread!

* While I would love to integrate this with the HyDE project's defaults, unfortunately, I can't for several reasons:
  1. I'm not the owner of the repository.
  2. AGS is an additional challenge, especially since we're just a dotfiles repository, and some newcomers mistakenly think we're a full desktop environment (DE). What?!
  3. That said, HyprPanel is great—it's solid, customizable, and overall a fantastic tool.
  4.  ... more 

* Implementing another version of AGS would be an extra burden on us, and it could also slow down development by fragmenting the existing AGS project.

* HyprPanel has excellent documentation, is actively maintained, and I’m excited about its future success. 

* I also managed to create a wallbash template for HyprPanel, which feels like a big win!

And yes, I’ve kicked off a HyDE project organization, inspired by Catppuccin’s repo, where they aim to "Catppuccinize" everything (haha)!

Check out the project here:  
[https://github.com/HyDE-Project/HyprPanel](https://github.com/HyDE-Project/HyprPanel)

**Comment by kRHYME7** [comment]
![image](https://github.com/user-attachments/assets/f503db2a-536c-4ffe-869a-9c24957e6cbf)
![image](https://github.com/user-attachments/assets/a72c9e2e-e2e8-41c1-a87e-08a005bea974)
![image](https://github.com/user-attachments/assets/6d4cd6e1-1715-4fa3-a1e2-8853db6ca06d)

**Comment by chrollorifat** [comment]
let's go catppuccin all the way...when's the new update be rolling in?
