### ISSUE TITLE
[Bug]: GTK can't open Gparted

### ISSUE THREAD

**Issue by wa4lo7k** [prasanthrangan/hyprdots#1648]
Bug Report
Summary:
When trying to launch gparted, I receive the following error: Authorization required, but no authorization protocol specified and Gtk-WARNING **: cannot open display: :1.

Steps to Reproduce:

Open terminal.
Run the command **gparted**.
Expected Results:
_gparted should open without any authorization or display errors._

Actual Results:
The following error messages are displayed:

**sql
Copy code
Authorization required, but no authorization protocol specified
(gpartedbin:5005): Gtk-WARNING **: cannot open display: :1234:** 
System Information:

OS: Arch Linux x86_64
Kernel: 6.9.6-arch1-1
Uptime: 43 secs
Packages: 1106 (pacman), 18 (Flatpak)
Resolution: 1366x768
DE: Hyprland
Terminal: kitty
CPU: Intel i7-7500U @ 2.70GHz
GPU: Intel HD Graphics 620
Memory: 716MiB / 7890MiB
Additional Information:

The issue occurs when using the Hyprland desktop environment.
I have attached a screenshot for reference.
Screenshot:
![240703_00h11m04s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/145761859/0949312c-d18f-49bc-a105-c96a43583419)

Potential Fixes:

Verify if the authorization protocol is correctly set.
Ensure that the display environment variable is correctly configured.

**Comment by kRHYME7** [comment]
run ` sudo -E gparted ` 

This means run gparted with your hyprland and user environment.
