### ISSUE TITLE
keyboard backlight control on laptop

### ISSUE THREAD

**Issue by quiet69** [prasanthrangan/hyprdots#165]
hey, i am trying to add a keyboard backlight script to keybinds
```
binde = , XF86KbdBrightnessDown, exec, ~/.config/hypr/scripts/asus_kbd_light.sh down
binde = , XF86KbdBrightnessUp, exec, ~/.config/hypr/scripts/asus_kbd_light.sh up
```
added the script as txt. can you tell me if this is failing because of sudo priviledge?
i will update this if i manage to figure it out. i think adding the user to leds group might work.
Also sorry for silly questions. i have returned to linux after almost a year
[asus_kbd_light.txt](https://github.com/prasanthrangan/hyprdots/files/12530124/asus_kbd_light.txt)

**Comment by prasanthrangan** [comment]
Hi, there is a script already available -
https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/scripts/brightnesscontrol.sh

could you please try if it works for you?

**Comment by quiet69** [comment]
hi if i am understanding correctly, this script has the display brightness (and its working!). The script i attached is for laptop keyboard backlight

**Comment by quiet69** [comment]
on asus keyboards, installing asusctl and adding these lines to keybind works splendid!
```
binde = , XF86KbdBrightnessDown, exec, asusctl -p
binde = , XF86KbdBrightnessUp, exec, asusctl -n
```

**Comment by quiet69** [comment]
on asus keyboards, installing asusctl and adding these lines to keybind works splendid!
```
binde = , XF86KbdBrightnessDown, exec, asusctl -p
binde = , XF86KbdBrightnessUp, exec, asusctl -n
```
