### ISSUE TITLE
[Bug]: keybind for quickapps.sh doesn't launch applications

### ISSUE THREAD

**Issue by Sitolam** [prasanthrangan/hyprdots#1663]
### Description

When I try to add a keybind for quickapps it doesn't launch the applications when hitting enter. It shows the selection but doesn't launch any application.
I added it like this in `userprefs.conf`: 
`bind = $mainMod, backslash, exec, $scrPath/quickapps.sh anki element-desktop signal`

### Expected Behavior

I expected that the application that I selected and hit enter on would launch.

### Actual Behavior

It just closes the menu but doesn't do anything.

### Environment

- Linux Distro: Archlinux
- Linux Version, output of `uname -a`: `Linux archbox 6.9.7-zen1-1-zen`
- Hyprland Version, output of `hyprctl version`: `v0.41.2`
- Installation Environment: On the main hardware

### Additional Information

Using `quickapps.sh` from the terminal works. But that is not a keybind.

**Comment by kRHYME7** [comment]
Coz I will fix it?

**Comment by Sitolam** [comment]
> Coz I will fix it?

Ow, that's nice. Didn't understand 😀

**Comment by Sitolam** [comment]
@kRHYME7 Any progress?

**Comment by kRHYME7** [comment]
Yup! It is already available in my local. But Unfortunately I accidentally corrupted my boot(Btrfs noob) also bit busy this week.

**Comment by Sitolam** [comment]
> Yup! It is already available in my local. But Unfortunately I accidentally corrupted my boot(Btrfs noob) also bit busy this week.
> 

No problem I appreciate the work

**Comment by kRHYME7** [comment]
@Sitolam  

Can you try to use this bind instead? 


bind = CTRL, backslash, exec,pkill -x rofi || hyprctl dispatch exec "$scrPath/quickapps.sh $quickapps" # Launch Quickapps: $quickapps

**Comment by Sitolam** [comment]
> @Sitolam
> 
> Can you try to use this bind instead?
> 
> bind = CTRL, backslash, exec,pkill -x rofi || hyprctl dispatch exec "$scrPath/quickapps.sh $quickapps" # Launch Quickapps: $quickapps

It works!! Thank you
