### ISSUE TITLE
Waybar error after install and reboot

### ISSUE THREAD

**Issue by Danidro20** [prasanthrangan/hyprdots#1668]
When the installation is finished, I reboot and when I log in to my user it loads everything, but there is no waybar. It's a bit weird because if I have the terminal open or some app and I try to bring up the waybar using `ctrl` + `alt` + `w`, the app window goes down as if to bring up the waybar but the window comes back up.
If after the installation, I enter without restarting, if there is waybar, but if I turn off the pc or restart it, when I turn it on, there is no waybar.
And if I try to launch the logout menu using `Super` + `Backspace`, it comes up for a second and goes away.
Please help, I love this rice T_T
Arch Linux.

**Comment by kRHYME7** [comment]
try to run waybar in the Terminal.

Do some stuff. see if it crashes.

**Comment by Danidro20** [comment]
This is the output when I run waybar
![image](https://github.com/prasanthrangan/hyprdots/assets/70298813/abe9a381-e493-44a3-9b58-0b685b579e16)

**Comment by kRHYME7** [comment]
Hmm is this a fresh install of arch? Or installed something before installing HyDE?

**Comment by Danidro20** [comment]
I use archinstall with the minimal type, grub and only change the key map. 
It's weird because the first time I installed it, everything went fine. T_T

**Comment by kRHYME7** [comment]
try using different waybar layout

**Comment by Danidro20** [comment]
I changed the theme and the position and it still doesn't appear.
I will install it on another disk to see if the error persists.

**Comment by Danidro20** [comment]
The error was not fixed.

**Comment by kRHYME7** [comment]
Try to use ` waybar-git `

**Comment by Danidro20** [comment]
I tried with other configurations and it worked, it's like it was a configuration bug

**Comment by kRHYME7** [comment]
Hey any progress on this? which layout inthe config.ctl excibits the bug?

**Comment by Danidro20** [comment]
I'm trying to fix the bug (This is my first time using a WM)

**Comment by GideonCoDer1993** [comment]
im getting the same error. running a fresh install of arch linux with base hyprland installed.

**Comment by kRHYME7** [comment]
Try to run "Hyde reload"

**Comment by GideonCoDer1993** [comment]
is that a package i can install? i have no clue what hyde is.

**Comment by kRHYME7** [comment]
It should already be installed when you run ./install.sh

**Comment by Danidro20** [comment]
Does your PC have dual GPU?

**Comment by DiegoSof2** [comment]
![image](https://github.com/user-attachments/assets/0f2098e9-5b07-444d-89f0-7d705f652b2f)
I also have this problem

**Comment by abenezerw** [comment]
This was fixed in a recent merge. #1869 @Danidro20 @DiegoSof2 
Can you please close this issue if this is fixed.
