### ISSUE TITLE
[Bug]: Code oss opens with two files: ozone-platform-hind=wayland and --disable-gpu

### ISSUE THREAD

**Issue by Jamsjz** [prasanthrangan/hyprdots#1669]
## Bug Report
Code oss opens with two files: ozone-platform-hind=wayland and --disable-gpu
### Description
these are not arguments but files that are opened.

When I didnot intall these dotfiles code oss was working fine, but when I installed it Code oss opens with two files: ozone-platform-hind=wayland and --disable-gpu
yes files not options or arguments to code-oss
### Steps to Reproduce
1. open code-oss after installing hyprdots

### Expected Behavior
Should open with no files opened. 
Should not open platform-hind=wayland and --disable-gpu files

### Actual Behavior

Code oss opens with two files: ozone-platform-hind=wayland and --disable-gpu

### Screenshots

![240707_10h51m28s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/138278527/85c847a5-89e2-4b6d-b46c-353637dbd6ad)

### Environment
                                              コンピューター
                                          ┌──────────────────────────────────────────┐
                                             OS : Arch Linux x86_64
                                             Kernel : Linux 6.9.7-arch1-1
                                             Packages : 2091 (pacman), 26 (flatpak)
                                             Display : 1024x1280 @ 60Hz [External]
                                             Display : 1920x1080 @ 144Hz [Built-in]
                                             WM : Hyprland (Wayland)
                                             Terminal : kitty 0.35.1
                                          └──────────────────────────────────────────┘

                                             : j@jj
                                          ┌──────────────────────────────────────────┐
                                             CPU : 12th Gen Intel(R) Core(TM) i5-12450H
                                             GPU : UHD Graphics
                                             GPU : GeForce GTX 1650 Mobile / Max-Q
                                             GPU Driver : i915
                                             GPU Driver : nvidia 555.58.02
                                            ﬙ Memory : 4.25 GiB / 7.43 GiB (57%)
                                          └──────────────────────────────────────────┘

                                            ● ● ● ● ● ● ● ●

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/issues/1315

Pinned
