### ISSUE TITLE
[Bug]: Dolphin freezes on fresh install

### ISSUE THREAD

**Issue by isimsizolan** [prasanthrangan/hyprdots#1671]
### Description

Installed archlinux with archinstall, zero configuration, did not installed additional packages. After initial login, install script ran.

### Steps to Reproduce

1. Arch linux mininal installition
2. Using hyprdots install script
3. super+e and dolphin freezes

### Additional Information
Amd 5800u lenovo laptop

**Comment by kRHYME7** [comment]
can you run ` dolphin` in the terminal and see for errors

**Comment by tinytempmouse** [comment]
dolphin returns: [1] 4516 segmentation fault (core dumped) dolphin, on my system. If its any help in the diagnosis cmake-gui returns the same as well.

**Comment by kRHYME7** [comment]
report to dolphin
