### ISSUE TITLE
[Bug]: Constant %7 cpu consuption after fresh install

### ISSUE THREAD

**Issue by isimsizolan** [prasanthrangan/hyprdots#1672]
### Description

hyprland consumes %7 cpu on idle after fresh installition

### Steps to Reproduce

1. Install archlinux minimal
2. Run install script (hyprdots
3. htop to see consuptions

### Additional Information

amd 5800u lenovo laptop

**Comment by kRHYME7** [comment]
if it's the Hyprland please report it to there repo. 

https://github.com/hyprwm/Hyprland

You can Either turn off your animations (Specially borderangle animation)

https://wiki.hyprland.org/Configuring/Animations/
