### ISSUE TITLE
[Bug]: Pavucontrol dark mode issue

### ISSUE THREAD

**Issue by Sitolam** [prasanthrangan/hyprdots#1677]
### Description

Pavucontrol is in light mode but my wallbash is standing on dark mode. I'm using the light theme "Catpuccin Latte" though. It switches to dark mode when I'm using a dark theme like "Catpuccin Mocha", but shouldn't it also be in dark mode in "Catpuccin Latte" when wallbash is set to dark mode? All other application are in dark mode for example the bluetooth menu when using the dark mode in wallbash.

### Expected Behavior

I expected it to be in dark mode.

### Actual Behavior

It is in light mode.

### Screenshots
> These screenshot are taken with the same theme "Catpuccin Latte" and with wallbash set to dark mode.

Pavucontrol
![image](https://github.com/user-attachments/assets/5d2ac99a-3877-4cf4-83de-f0ca4a2b2d11)
Wallbash
![image](https://github.com/user-attachments/assets/9bf602fe-93d2-45a3-a3b3-ce535057b8a0)
Bluetooth menu
![image](https://github.com/user-attachments/assets/9efebd29-985c-4dfd-a5a6-4aa05175c182)

### Environment

- Linux Distro: Archlinux
- Linux Version, output of `uname -a`: `Linux archbox 6.9.9-zen1-1-zen`
- Hyprland Version, output of `hyprctl version`: `v0.41.2`
- Installation Environment: On the main hardware

**Comment by Enigma1309** [comment]
do you have flatpak version of app?
if yes see this https://github.com/prasanthrangan/hyprdots/issues/1481#issuecomment-2105748109

**Comment by Sitolam** [comment]
> do you have flatpak version of app? if yes see this [#1481 (comment)](https://github.com/prasanthrangan/hyprdots/issues/1481#issuecomment-2105748109)

It's not a flatpak it is just installed automatically from the project.

**Comment by Enigma1309** [comment]
wallbash mode is meant for script to choose the specified color from wallpaper and generate the colors for the same it has nothing to do with the light or dark theme of system

afaik this pull request is meant to fix that
https://github.com/prasanthrangan/hyprdots/pull/1691

**Comment by mahaveergurjar** [comment]
Yeah this issue I think due to prefer-light but  show dark in theme mode bluethoot and wifi in  "Catpuccin Latte" this theme behave
![240721_14h50m13s_screenshot](https://github.com/user-attachments/assets/3a2d1b3e-3d9c-4b16-a905-872698a89350)
![240721_14h51m16s_screenshot](https://github.com/user-attachments/assets/5dad6759-ff3e-4728-b3b7-665c17a40d30)

**Comment by mahaveergurjar** [comment]
Pavucontrol not goes in dark mode because its not work with wallbash its only chnage with theme @Sitolam

**Comment by kRHYME7** [comment]
> Pavucontrol not goes in dark mode because its not work with wallbash its only change with theme @Sitolam


lol now that I realized it. Yeah above is expected. And should be fixe with this PR https://github.com/prasanthrangan/hyprdots/pull/1691 

But take note that Latte is meant for Light mode so it should look awkward on some dark wallpapers.
Using dark wallpapers makes some apps handles by wallbash turns dark mode. 
To fix this the https://github.com/prasanthrangan/hyprdots/pull/1691 PR will read the color-scheme that is set and use that to decide weather to be in dark or light mode.

**Comment by kRHYME7** [comment]
Merged. Also this is not really a bug in the script. This is expected.

**Comment by Sitolam** [comment]
I merged the pull request but it's still not working, but I guess that I should just use a dark theme. I liked the wallpapers from "Catpuccin Latte" though 😥
