### ISSUE TITLE
Help : Sddm after install does not include any theme.

### ISSUE THREAD

**Issue by thyeun** [prasanthrangan/hyprdots#1679]
As per title, after follow the step by step ```./install.sh``` 

My current sddm still is the original one, and i check with the folder there are no sddm-candy-theme inside.

May i know how can i manually include all the ```sddm theme``` ?

**Comment by kRHYME7** [comment]
Can you please run ` Hyde sddm theme ` command

**Comment by thyeun** [comment]
i fix it myself, i re-run the ```./install.sh```, everything are fine now, previously because of the gruvbox theme not finish up downloading, that why make the ```./install.sh``` script never continue till the end. That why the```sddm theme``` are not install.
