### ISSUE TITLE
[Bug]: Cursor sometimes defaults to main when a different variant should be used

### ISSUE THREAD

**Issue by NotAF0e** [prasanthrangan/hyprdots#1680]
The problem is that this feels quite random so I have no clue how to reproduce it. Lets say im editing a text document in obsidian for example, when changing between workspaces and just using the system sometimes the cursor defaults to the main pointy one when instead it should be using the text field cursor or the grab cursor. Not really a major issue but its just quite annoying sometimes

**Comment by NotAF0e** [comment]
Perhaps an upstream hyprcursor issue?

**Comment by kRHYME7** [comment]
yeah please open it upstream

**Comment by NotAF0e** [comment]
ok! I will follow up with if this is perhaps a hyde issue or not

**Comment by NotAF0e** [comment]
https://github.com/hyprwm/hyprcursor/issues/53

**Comment by kRHYME7** [comment]
That's recognized as a Hyprland issue. See Hyprland's GitHub

**Comment by iamtheabdi** [comment]
Try with the latest commit
