### ISSUE TITLE
[Feature Request]: Switch nvidia-dkms to nvidia-open-dkms

### ISSUE THREAD

**Issue by Vakkaria** [prasanthrangan/hyprdots#1682]
## Feature Request

Hi! Many users are facing kernel panic because of nvidia drivers. This only happens if u are using nvidia-dkms drivers. So it would be good if your installer has nvidia-open-dkms instead of nvidia-dkms.

**Comment by Vakkaria** [comment]
For my laptop with GEFORCE 3050M GPU, nvidia-dkms causes kernel panic. I just can't use arch because it may stuck in any moment (usually in start/shutdown/updating). However, there are details in [arch wiki](https://wiki.archlinux.org/title/NVIDIA).

**Comment by simplemachine-zz** [comment]
I Dont have Kernel Panic and i use nvidia-dkms.

**Comment by Vakkaria** [comment]
> I Dont have Kernel Panic and i use nvidia-dkms.

Are you arch user? And what's your GPU?

**Comment by simplemachine-zz** [comment]
> > I Dont have Kernel Panic and i use nvidia-dkms.
> 
> Are you arch user? And what's your GPU? In my case, i have arch kernel and 3050M with Intel Graphics

Arch Linux. Nvidia GTX 970

**Comment by dieBakterie** [comment]
I would not recommend to Switch to nvidia-open-dkms as of this Part in the Hyprland Wiki ![Screenshot_2024-07-23-11-35-56-509_org.mozilla.firefox-edit.jpg](https://github.com/user-attachments/assets/59cda8b1-0fd3-40d8-8ec2-201fd0650b9a)

**Comment by vampirepapi** [comment]
yes kernel panicking happening in my pc too.

> > I Dont have Kernel Panic and i use nvidia-dkms.
> 
> Are you arch user? And what's your GPU? In my case, i have arch kernel and 3050M with Intel Graphics

**Comment by SyedArbaazHussain** [comment]
A selection is better than complete change like how we select themes for sddm during installation because the nvidia-dkms is a very good choice for newer GPUs.

**Comment by dieBakterie** [comment]
Yeah that's what i meant by this to let the user select what nvidia driver to use and not hardcode/force a speciific one on them.

**Comment by kRHYME7** [comment]
Let's move this to Discussion to resolve this topic better. I don't think the open-dkms driver is for the majority. Let's use this as a reference for devices that don't work on proprietary nvidia driver.
