### ISSUE TITLE
[Custom]: tiling and floating window

### ISSUE THREAD

**Issue by TruonggDann** [prasanthrangan/hyprdots#1683]
Hi guys
Can i disable tiling window manager ?
I want to use floating window manager like window.
It sounds silly because my english is not good.
Yours dotfiles is very cool.Thank you guys

**Comment by kRHYME7** [comment]
Hi I think you're lost. Hyprland is a dynamic tiling window manager. So making everything float won't make sense at all.In theory we can make everything float. But It would cause a lot of issues as Hyprland is designed for tiling only
