### ISSUE TITLE
Code oss 3 files are created

### ISSUE THREAD

**Issue by unknowncat-meow** [prasanthrangan/hyprdots#1685]
![image](https://github.com/user-attachments/assets/3a14af5b-bb61-4058-b7b8-b595313cbd2c)
I have followed the previous solution and this error still there any idea ?

**Comment by unknowncat-meow** [comment]
I have also removed quotes from `${electronflags[@]}` in t his line `ELECTRON_RUN_AS_NODE=1 exec /usr/lib/${name}/electron /usr/lib/code/out/cli.js "${electronflags[@]}" /usr/lib/code/code.js ${codeflags[@]} "$@"`.
It fixed the issue
does this change anything ?

**Comment by kRHYME7** [comment]
Are you sure the issue persisted? Or maybe Code still remembers the last openned file

**Comment by Kanu3690** [comment]
at first when I closed those files and opened folder in vscode. it opened 2 instances of code one with opened folder and one with those unsaved files.

**Comment by unknowncat-meow** [comment]
at first when I closed those files and opened folder in vscode. it opened 2 instances of code one with opened folder and one with those unsaved files. after about 3rd launch the instance where I had folder open got closed and only instance with those unsaved files remained.

**Comment by kRHYME7** [comment]
Can you share here the file you edited from here 

https://github.com/prasanthrangan/hyprdots/issues/1685#issuecomment-2238052928

**Comment by unknowncat-meow** [comment]
> Can you share here the file you edited from here
> 
> [#1685 (comment)](https://github.com/prasanthrangan/hyprdots/issues/1685#issuecomment-2238052928)
> 
> And let's continue this to the pinned post

sure I have done this to fix the issue

> I have also removed quotes from `${electronflags[@]}` in t his line `ELECTRON_RUN_AS_NODE=1 exec /usr/lib/${name}/electron /usr/lib/code/out/cli.js "${electronflags[@]}" /usr/lib/code/code.js ${codeflags[@]} "$@"`. It fixed the issue does this change anything ?

**Comment by kRHYME7** [comment]
Take note the your package manager will overwrite that file during updates 

In my case I added a copy of the edited/fixed ./code  file to ` /usr/local/bin  `  This way package manager won't overwrite it.

**Comment by nickheyer** [comment]
> Take note the your package manager will overwrite that file during updates
> 
> In my case I added a copy of the edited/fixed ./code file to `/usr/local/bin ` This way package manager won't overwrite it.

Yeah, this didnt fix the issue for me. Package manager doesn't care about /usr/local/bin, it still reverts to the `"${codeflags[0]}"` after an update. I've now needed to reset the code-oss bin in /usr/bin like 30 times.
