### ISSUE TITLE
[Help]: Stuck on minimal install

### ISSUE THREAD

**Issue by TacShot** [prasanthrangan/hyprdots#1686]
Need advice / help

After running the script on my laptop (Asus TUF F15) and rebooting the system I'm still stuck on the minimal install cli on Arch

### Steps to Reproduce (if applicable)

1. Do a minimal install of arch with archinstall script
2. Insert and run following commands
3. pacman -Sy git
git clone --depth 1 https://github.com/prasanthrangan/hyprdots ~/HyDE
cd ~/HyDE/Scripts
./install.sh
4. Proceed with the usual steps
5. Reboot

### Expected Behavior

Was hoping to see the sddm greeter 

### Actual Behavior

I was in the CLI asked for login and password and still nothing happens 

### Screenshots (if applicable)

[If applicable, add screenshots to help explain your problem.]

![17214053714905648300734504442219](https://github.com/user-attachments/assets/fa1c2d29-ac52-4eb6-bd05-5668c3c67e35)

**Comment by Enigma1309** [comment]
to enable login manager `sudo systemctl enable sddm.service --force` 
also you should run `Hyprland` instead 'hyprland`

**Comment by abenezerw** [comment]
Was this solved for you @TacShot

**Comment by TacShot** [comment]
Oh hey guys sorry for the late reply this was at the time when I was just starting out using ArchLinux and Hyprland. So turns out some of the packages were missing back then including SDDM for some reason anyways 6 months later I'm more than a bit familiar with Arch and my system works flawlessly thanks a lot for the help @abenezerw @Enigma1309 appreciate your help.
