### ISSUE TITLE
[HELP]Issues with CPU Temperature Display and Time Configuration in Waybar

### ISSUE THREAD

**Issue by AntonOrtiz** [prasanthrangan/hyprdots#1687]
Hello,

I am experiencing issues with my Waybar configuration. Here are the details:

CPU Temperature: Waybar does not display the CPU temperature even though I have the module configured. There are no visible errors in the logs.
Time Configuration: Waybar displays the time in UTC format instead of local time. I have tried changing the clock configuration in the config file, but Waybar does not accept the changes. Here is the current clock configuration:

![image](https://github.com/user-attachments/assets/3391f20d-84b8-4164-a408-def02a743903)

**Comment by Enigma1309** [comment]
for the cpu issue `yay -S lm-sensors`

for time issue see this :- https://wiki.archlinux.org/title/Installation_guide#Time

also try setting up ntp

**Comment by AntonOrtiz** [comment]
> for the cpu issue `yay -S lm-sensors`
> 
> for time issue see this :- https://wiki.archlinux.org/title/Installation_guide#Time
> 
> also try setting up ntp

I have changed the time settings and the system shows the correct one. Could it be a failure in the Waybar module?

**Comment by Enigma1309** [comment]
Can you try [this](https://www.reddit.com/r/archlinux/comments/14oe4sb/issue_with_setting_system_time_and_hardware_time/) solution

Also send the command output here

**Comment by AntonOrtiz** [comment]
I was able to solve it by adding the following line to the configuration file.
Now I'm working on getting the temperature sensors to work.


![imagen](https://github.com/user-attachments/assets/17be43aa-6799-4940-bdbc-10e013276f32)

**Comment by abenezerw** [comment]
If this issue has been solved for you, could you close this out as solved. Thank you @AntonOrtiz
