### ISSUE TITLE
Replace hard coded path to dynamic path

### ISSUE THREAD

**Issue by notnetworky** [prasanthrangan/hyprdots#169]
In Configs/.config/swww I think you might need to change wall.blur wall.rofi and wall.set from the /home/tittu/ to ~/ or $HOME. Not sure if thats important but just thought I should make an issue of it.

**Comment by prasanthrangan** [comment]
Hi, I think even if ~/ or $HOME is used to create the symlinks, it gets hardcoded... So this is handled during installation by the [script](https://github.com/prasanthrangan/hyprdots/blob/main/Scripts/restore_lnk.sh).
