### ISSUE TITLE
[Bug]: Blueman freezes before start

### ISSUE THREAD

**Issue by WantDead** [prasanthrangan/hyprdots#1696]
### Description

When I try to start bluetooth I get an error
![240722_04h27m09s_screenshot](https://github.com/user-attachments/assets/fcdfea5c-4454-4b8f-94b4-ef13735dbcaf)

after a couple of minutes (sometimes 5 minutes) the service starts and everything is fine

I tried using tips from this thread
and yes, the command attached there worked
https://github.com/blueman-project/blueman/issues/2378
but I don’t think this is a “complete” solution

### Steps to Reproduce

1. run blueman

### Expected Behavior

-

### Actual Behavior

-

### Screenshots

-

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: Arch
- Linux Version, output of `uname -a`: 6.9.10
- Hyprland Version, output of `hyprctl version`: 0.41.2
- Installation Environment: main

### Additional Information

and one more note
I recently reinstalled arch with hyprdots and BEFORE using Hyde-cli, blueman worked correctly
But as soon as I installed Hyde-cli, the problem returned, since a rather voluminous script is executed there repeatedly, it’s difficult for me to say what exactly is causing the problem

But maybe someone has already encountered this and knows the solution?

**Comment by kRHYME7** [comment]
How does the `Hyde-cli` package affect it?

**Comment by WantDead** [comment]
i think main problem in blueman-tray
because bluethooth works correctly without it
and problem starts when i try to start bluetooth via tray

I’ll post back a little later if I solve this problem, in case it’s useful to someone
