### ISSUE TITLE
How to fix screen blank after entering password 

### ISSUE THREAD

**Issue by wernayasa** [prasanthrangan/hyprdots#17]
I've installed this script 7 times, every installation was successful except when I logged in.
Screen blank and sometime freeze.
The solution is easy, delete hyprlan-git and replace it with hyprland.
If your screen froze hit <kbd>super key + del</kbd>.
Next hit <kbd>ctrl+alt+F3</kbd>.
Enter username and password.
On tty3 console type: <code>yay hyprland</code>.
Hit enter chose option non git, I think it's <b>extra/hyprland</b>.
Good luck.

**Comment by wz790** [comment]
I do it but the same thing bad luck 🤣💔

**Comment by zlgxzswjy** [comment]
Yes, replacing hyprland-git with hyprland in custom_hypr.lst works fine. However, the normal user can log in normally, but the root user still has a black screen after logging in
