### ISSUE TITLE
strange workspace position ; waybar

### ISSUE THREAD

**Issue by edanbigw** [prasanthrangan/hyprdots#170]
![image](https://github.com/prasanthrangan/hyprdots/assets/87627576/fcf4feed-4380-4fda-9a2d-09c81230a0ed)
I found strange 10th workspace position on waybar

**Comment by prasanthrangan** [comment]
hmm... i'm unable to replicate it, any config change that caused it?

**Comment by kRHYME7** [comment]
Please reopen if this issue persists.
