### ISSUE TITLE
Emoji Picker

### ISSUE THREAD

**Issue by Jchael12** [prasanthrangan/hyprdots#1701]
I am having a hard time to see and test if this has an emoji picker using keyboard. If there please guide me. Thank you for this wonderful config. :)

**Comment by Somnius** [comment]
i've tried [rofi-emoji](https://github.com/Mange/rofi-emoji) but in some apps (e.g. telegram-desktop-bin) it inserted a "0" alongside the emoji (!?) (_[my post on garudalinux forum](https://forum.garudalinux.org/t/hyprland-wofi-emoji-inserts-0-on-telegram-desktop/33934)_) so i went thru and installed "[emote](https://github.com/tom-james-watson/Emote)" easy to bind onto a key.. for example on @prasanthrangan dotfiles you can visit your home folder and `.config/hypr/` inside you'll find the `keybindings.conf` file there you can add e.g. `bind = $mainMod, 52, exec, emote` as 52 is the key for `.` (dot). Dont forget to install `emote` first, using pacman or yay idk

**Comment by kRHYME7** [comment]
run `Hyde show emoji `

**Comment by Jchael12** [comment]
Thank you very much for the help, Im new to linux specifically in hyprland. :)

**Comment by Jchael12** [comment]
> run `Hyde show emoji `

btw how to bind the a keyboard shortcut for this ?

**Comment by kRHYME7** [comment]
Here you go https://wiki.hyprland.org/Configuring/Binds/

**Comment by Jchael12** [comment]
> Here you go https://wiki.hyprland.org/Configuring/Binds/
> 
> Also checkout our discord.


Thank you very much for the help !
