### ISSUE TITLE
[Bug]: hang while trying to install over lightdm

### ISSUE THREAD

**Issue by Somnius** [prasanthrangan/hyprdots#1704]
Tried endeavourOS that had i3wm installed with lightdm as login, and the `install.sh` script stopped
Had to re-install endeavourOS without a desktop and run the installation script in order to complete the sddm part.

Suggestion: Why not identify current dm and ask to replace it with sddm and then ask for candy or corners ?

**Comment by kRHYME7** [comment]
Hey! you needed to remove sddm to the list to be installed

this file
https://github.com/prasanthrangan/hyprdots/blob/ee2654cedca8aadef10f97b562c8313fc8cc99df/Scripts/custom_hypr.lst#L20
and this
https://github.com/prasanthrangan/hyprdots/blob/ee2654cedca8aadef10f97b562c8313fc8cc99df/Scripts/system_ctl.lst#L3

**Comment by kRHYME7** [comment]
I will close this as you need to manually do the things I mention above, specially if the installation is not a minimal arch. 

 We will be glad to accept a Pull Request instead. Wil help you merge it 
 
 
 > Suggestion: Why not identify current dm and ask to replace it with sddm and then ask for candy or corners ? 
 
I am planning to add this part on Hyde CLI  instead. I won't touch anything related to the ` install.sh ` as the owner is AFK.
