### ISSUE TITLE
[Bug]: waybar apps side suddenly Disappears

### ISSUE THREAD

**Issue by aziz-204** [prasanthrangan/hyprdots#1706]
- Linux Distro: ArchLinux
- Linux Version, Linux archbtw 6.10.0-zen1-2-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 22 Jul 2024 17:45:00 +0000 x86_64 GNU/Linux
- Hyprland Version: v0.41.2
- Installation Environment: On The Main Hardware
- Other info: [e.g., Display Resolution, Resolution, etc]

**Comment by aziz-204** [comment]
![240726_00h40m25s_screenshot](https://github.com/user-attachments/assets/7bd5525b-70ee-4950-ab70-1aeb21774371)

**Comment by Enigma1309** [comment]
known issue, happens when we switch theme/wallpaper,etc and/or change waybar position.
https://github.com/prasanthrangan/hyprdots/issues/1053#issuecomment-1987244900

after endless discord conversations and digging, we still don't know the fix yet

**Comment by kRHYME7** [comment]
ask waybar maybe?.

**Comment by aziz-204** [comment]
yah i fixed it this guide with https://github.com/Alexays/Waybar/issues/3468#issuecomment-2262074645
