### ISSUE TITLE
Game window becomes black after wakeup

### ISSUE THREAD

**Issue by QSkill** [prasanthrangan/hyprdots#1709]
### Description

Whenever I launch a game and then closed the lid of my laptop (which runs systemctl suspend) and then wake my laptop up and input my password the game window becomes black, this happens with Steam and non-Steam games, in proton and in native games.

### Steps to Reproduce

1. Launch game 
2. Suspend laptop
3. Wake up and log in

### Expected Behavior

Game window acts normally

### Actual Behavior

Game window becomes black

### Screen recording

https://github.com/user-attachments/assets/60c87a4b-7784-4a36-a504-e948dfdaa03f

### Environment

- Linux Distro: [ArchLinux]
- Linux Version: Linux 6.10.1-arch1-1
- Hyprland Version: 0.41.2
- Installation Environment: On The Main Hardware
- Other info: I use Hyprlock

**Comment by Enigma1309** [comment]
it depends on game, sometime wine games does it, it has nothing to do with these dotfiles.

**Comment by QSkill** [comment]
> this happens with Steam and non-Steam games, in proton and in native games.

Also this isn't new, it has been bothering me for a while now, but I just didn't find an answer so I reported it here.

btw I now use nvidia-open-dkms but it was also happening with nvidia-dkms.

I have a feeling this might be caused by Hyprland or Wayland so I reported it here.

**Comment by kRHYME7** [comment]
> my laptop (which runs systemctl suspend)

Try to disable that and use `hyprctl dpms off ` instead

**Comment by QSkill** [comment]
I use that to turn off my screen but I want to suspend to RAM to save battery, is the problem always going to happen when suspending to RAM?

**Comment by kRHYME7** [comment]
BTW Can you try report it ni Hyprland  repo
` https://github.com/hyprwm/Hyprland ` 


This issue might not be under the scope of this dotfiles. Please reopen if you guys find out that the dotfiles lack something/ causes the issue. Thank you
