### ISSUE TITLE
Minor ui issues

### ISSUE THREAD

**Issue by UcraNerd** [prasanthrangan/hyprdots#171]
Custom scripts for changing theme and wallaper, rofi, clipboard manager, clock info don't work; keyboard layout changed.

**Comment by prasanthrangan** [comment]
Hi, can you please try running the scripts from terminal to check the errors and share logs or screenshots?

**Comment by UcraNerd** [comment]
![20230907_073133.jpg](https://github.com/prasanthrangan/hyprdots/assets/102480084/75644c02-7506-463d-8041-42cfc5431b0e)

**Comment by UcraNerd** [comment]
Maybe i forgot to run locale-gen. (Now work everything, however i still have ui issues; i think its because of the differencies between our screen aspects)

**Comment by UcraNerd** [comment]
UPDATE: I changed the monitor settings in the hyprland main setting to my screen resolution with scale 1 (.config > hyprl > hyprland.conf with `monitor=eDP-1, 1920x1080@60, 0x0,` .
Then the custom scripts, firefox and the super+backspace are fine now. The logout button in the waybar still have some ui issues and the main font is very small. For the waybar i increased the second value between the |n| in the waybar .config > config.ctl file to like 40/45. Hope will help you someway.

**Comment by UcraNerd** [comment]
No for the waybar logout button i mean the ui when i clock it not the item itself...

**Comment by prasanthrangan** [comment]
oh noo, I thought its fixed... will look into it!
what about layout 1, does it scale correctly to your screen ?

**Comment by UcraNerd** [comment]
> oh noo, I thought its fixed... will look into it!
> what about layout 1, does it scale correctly to your screen ?

If you mean the super+backspace, it's fine

**Comment by prasanthrangan** [comment]
> If you mean the super+backspace, it's fine; and what's the new games launcher, is it still work in progress?

ok cool, I'll update layout2 (the waybar one)...

ya the game launcher is just a rofi menu for your installed steam games, it works but might take time (~20sec) to scan games (if you have many) on first launch.

there is no keyboard shortcut set, so you can try running it as below -
```
.config/hypr/scripts/gamelauncher.sh n # where n is layout [1-4]
```

**Comment by prasanthrangan** [comment]
I've removed the padding and adjusted layout for wlogout, please try the latest fix!

**Comment by UcraNerd** [comment]
> I've removed the padding and adjusted layout for wlogout, please try the latest fix!

![image](https://github.com/prasanthrangan/hyprdots/assets/102480084/cb8a77e5-e87c-4467-8d3c-634c192235eb)

For the icon size no problem, i can fix it; still have ui issues

**Comment by prasanthrangan** [comment]
hmm.. it is the x res padding that's messing it up, let me check!
