### ISSUE TITLE
[Custom]: Short description of the issue

### ISSUE THREAD

**Issue by Kristallik355** [prasanthrangan/hyprdots#1711]
![240729_10h30m28s_screenshot](https://github.com/user-attachments/assets/7f8d9175-5650-44f9-ace6-b059ef454c5e)

**Comment by unknowncat-meow** [comment]
`Hyde theme patch` try this

**Comment by kRHYME7** [comment]
@Kristallik355  theme name is not correct  . 

Theme name is "Rosé Pine" not "Rose-Pine"

use ` Hyde theme patch ` instead
