### ISSUE TITLE
[Bug]:Hyde installing issue. Git clone error

### ISSUE THREAD

**Issue by Rafid337** [prasanthrangan/hyprdots#1712]
### Description

I was installing Hyde using script. When cloning git get many error.

### Steps to Reproduce

1. I pasted the Hyde script. It started cloneing git
2. Get many errors
3. Installation cancelled for errors

### Expected Behavior

I was expecting, I will just paste the Hyde script and it will install it.

### Actual Behavior

It started and ended when git cloning with many errors

### Screenshots

Forgot to take screenshots . If you want I will try another time and send this

### Environment

I did some like
git config --global http.postBuffer 524288000
git config --global pack.windowMemory 100m
git config --global pack.packSizeLimit 100m
git config --global pack.deltaCacheSize 100m
git config --global pack.threads 4
https://stackoverflow.com/questions/59282476/error-rpc-failed-curl-92-http-2-stream-0-was-not-closed-cleanly-protocol-error

e.g.,

- Linux Distro: ArchLinux
- Linux Version: 6.10 kernel`:
- Hyprland Version, Not installed installation error
- Installation Environment:Main Hardware
- Other info: 1366×720 display resolution 

### Additional Information

Error messages 
First time
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 1443 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
bash: cd: /home/rafid/HyDE/Scripts: No such file or directory
bash: ./install.sh: No such file or directory
Second time
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
With the same errors above

note:Git clone started at speed 720 kbps than it down at 12kbps. other git clone work fine. their speed is 900kbps.

**Comment by kRHYME7** [comment]
try to download the zip.

**Comment by Zer0metal** [comment]
> try to download the zip.

What to do after that? I'm a newbie. Facing the same issue as well. I did downloaded the zip but the question remains what to do next

**Comment by abenezerw** [comment]
> > try to download the zip.
> 
> What to do after that? I'm a newbie. Facing the same issue as well. I did downloaded the zip but the question remains what to do next

Extract it, cd into the scripts and run install.sh to run the install.
