### ISSUE TITLE
[Bug]: Most of the keybindings aren't working

### ISSUE THREAD

**Issue by progb4atys** [prasanthrangan/hyprdots#1713]
Many keybindings, apart from the application shortcut and session actions, are not functioning as expected. For instance, pressing Super + A fails to open the application menu, among other issues. I attempted to modify the keybindings, but the changes did not resolve the problem.

**Comment by kRHYME7** [comment]
Terminal output if you run this `  rofilaunch.sh ` .

**Comment by kRHYME7** [comment]
please provide output for  ` Hyde version` 

also is this from fresh minimal install of arch ? looks like a broken install of Hyde.

**Comment by progb4atys** [comment]
the issue was solved by `Hyde-install`

thanks for the assistance
