### ISSUE TITLE
[Bug]: freeze desktop when suspend 

### ISSUE THREAD

**Issue by ahmed-2bodre3** [prasanthrangan/hyprdots#1717]
### Description
 When make suspend on my laptop it's get black windows and not working 
[Provide a clear and concise description of the bug.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by iamtheabdi** [comment]
You've given too little information on the issue but I'm guessing it has something to do with your mkinitcpio config rather than HyDE.

Read this thoroughly:
https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate

**Comment by kRHYME7** [comment]
will close this as pointed out by @iamtheabdi . Reopen if necessary. Also if you need someone to chat/for help we got a  discord mini community that might help you.
