### ISSUE TITLE
Suggestion: Add styling to grouped tabs/windows

### ISSUE THREAD

**Issue by stove-jeebs** [prasanthrangan/hyprdots#172]
The Current grouped windows have no styling applied to them:

unlocked:
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/10083501-9ce1-4eef-84fc-36dd5a300772)

locked (a little difficult to see but it is slightly redder):
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/f14d7d88-6ceb-4898-82da-26305bc3c9ea)

**Comment by prasanthrangan** [comment]
Oh thanks, I'm not sure if it can be configured, but I'll look into this!

**Comment by stove-jeebs** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/7a9d03df-e3ce-4ad9-a36f-79fa8a618b95)

They can be found in:
https://wiki.hyprland.org/Configuring/Variables/

**Comment by prasanthrangan** [comment]
Thanks, I'll add it to the hypr theme files when i'm back home!

**Comment by prasanthrangan** [comment]
fixed in 79807bd
