### ISSUE TITLE
[Feature Request]: Short description of the feature

### ISSUE THREAD

**Issue by liamwibo** [prasanthrangan/hyprdots#1721]
## Feature Request

Browser media control via the waybar like spotify

### Description

Hi i was using HyDE and noticed it had a currently playing feature in the waybar for spotify and i like it very much but i mainly use youtube on firefox for listening to music. Is it possible to make this work with a browser?

### Use Case

Controling browser medie via the waybar

### Proposed Solution

I have seen this work with the KDE integration extension but i don't know how to implement this.

**Comment by dieBakterie** [comment]
This should already Work with your browser/YouTube just need to use the mpris module instead of the Spotify one.
