### ISSUE TITLE
low volume compared to windows

### ISSUE THREAD

**Issue by celikj** [prasanthrangan/hyprdots#1723]
sorry i know it is not related to hyprdots but the community here seems to know a lot about linux stuff

my max volume on hyprdots is much lower than it is on windows what can I do about it?

**Comment by kRHYME7** [comment]
We got a discord server. check it out. 

In discord we can have a thread on this topic.
If you don't use discord please open this topic in the Discussion Panel instead of the issue. Thank you. have a great day!
