### ISSUE TITLE
How can I ignore kitty padding for a specific terminal app like neovim? 

### ISSUE THREAD

**Issue by Mahathirrr** [prasanthrangan/hyprdots#1726]
I just want to ignore them for neovim only. Is there any modifications I can do in my kitty config. 
![240803_20h13m37s_screenshot](https://github.com/user-attachments/assets/ae7ec4ec-1a9b-41bd-b35c-bc5e9f59e0ab)

**Comment by kRHYME7** [comment]
![image](https://github.com/user-attachments/assets/c089b677-9899-4158-953f-e3b5475936c6)
Hi! GitHub had a filter feature to search some relevant issues. 
Dups 😎

https://github.com/prasanthrangan/hyprdots/issues/1505
https://github.com/prasanthrangan/hyprdots/issues/1456
https://github.com/prasanthrangan/hyprdots/issues/735
https://github.com/prasanthrangan/hyprdots/issues/881
https://github.com/prasanthrangan/hyprdots/issues/785

Here's a breakdown of how you might solve it. (Read first the above issues if those suggestions won't work for you check out below )
 
* IIRC think you can use some functionality of kitty to dynamically change its layout (google might help)
* Now you can run a command to remove kitty's padding dynamically
* Make a script out of it and launch nvim after removing kitty's padding 
* Now If you're using nvim I hope you're comfortable to configure it. I think nvim is capable of launching a custom command before you exit it. 
* Use the above functionality and run a script to re store kitty's padding.

**Comment by kRHYME7** [comment]
BTW We got[ a Discord server](https://discord.com/invite/qWehcFJxPa) specially for queries like this. If you avoid using discord please use the discussions panel
![image](https://github.com/user-attachments/assets/abd135bb-40c5-4a88-bf77-655417de479a)
