### ISSUE TITLE
Monitor Output

### ISSUE THREAD

**Issue by Jchael12** [prasanthrangan/hyprdots#1728]
So I disabled my laptop monitor to use the external monitor as my primary, I disabled it because it extends the display even if i fold my laptop, I don't want that. I want  it to not be extended. is there a way with that ? , Thank you for your help :)

**Comment by kRHYME7** [comment]
Hi @Jchael12! We got[ a Discord server](https://discord.com/invite/qWehcFJxPa) specially for queries like this. If you avoid using discord please use the discussions panel 
![image](https://github.com/user-attachments/assets/acfa2e2a-38a4-45c8-b415-a23385c9b14c)

I'm  the only active collaborator for now, so It would be helpful to segregate those queries.

**Comment by kRHYME7** [comment]
But check this out 
Here you can use this bind to fire up some command when you close your monitor. 

https://wiki.hyprland.org/Configuring/Binds/#switches

Now we need to have a command to disable the monitor 
![image](https://github.com/user-attachments/assets/2b2f9596-1639-4890-8a6d-da69b220f7c8)
I thin we need a custom script to dynamically "disable" monitor. 
The dispatcher dpms off  behaves different. Will be back on this thread if I can figure out something

**Comment by Jchael12** [comment]
Got it, I apologize for not using the discussion for this type of question. Thank you :)

**Comment by kRHYME7** [comment]
@Jchael12  Lol I think the very first link provides the answer ! 

Check that bind. Switches are different for each device, so check yours first
![image](https://github.com/user-attachments/assets/fd649297-f0f0-4275-a6fb-00aa738faa3b)
