### ISSUE TITLE
dbus-update-activation-environment needed

### ISSUE THREAD

**Issue by DozNaka** [prasanthrangan/hyprdots#173]
Starting the authentication dialogue agent is not enough. Applications like Dolphin when trying to authenticate to an SFTP server, will fail because the authentication gui will not show up.

Adding ``exec-once = dbus-update-activation-environment --systemd --all`` to the hyprland config will fix this issue.

**Comment by prasanthrangan** [comment]
Hi, thank you... I'll add it to the hyprland config

**Comment by prasanthrangan** [comment]
fixed in 79807bd
