### ISSUE TITLE
Disable blur in waybar

### ISSUE THREAD

**Issue by ILYFKA** [prasanthrangan/hyprdots#1730]
Hello. How to disable blur in waybar? And one more small question. How to make the alt time format always applied after changing the theme. Thank you very much!

**Comment by kRHYME7** [comment]
Use the discussions panel
![image](https://github.com/user-attachments/assets/a869ab81-4b6c-4728-8894-1f16d10b08f2)

Or 
You can chat in our discord Server. 

Thank you for understanding. At the moment I'm the only collaborator that is active on this repo, so I encourage asking queries in the Discord server or in discussions panel where things like this best fitted.
