### ISSUE TITLE
There used to be a notifications icon in waybar bottom right but after an update it disappeared.

### ISSUE THREAD

**Issue by midosaid28** [prasanthrangan/hyprdots#1734]
i just need a way to bring it back is all

**Comment by kRHYME7** [comment]
You should add it yourself.

https://github.com/prasanthrangan/hyprdots/blob/main/Configs%2F.config%2Fwaybar%2Fconfig.ctl

add `custom/notifications `

**Comment by midosaid28** [comment]
Oh thank you!
If I'm not disturbing u, may i ask to which config file ?

**Comment by midosaid28** [comment]
Oh thank you!
If I'm not disturbing u, may i ask to which config file ?

**Comment by thyeun** [comment]
@midosaid28 you should go ```~/.local/share/bin``` and look for ```notification.py``` and choose ```Properties ---> Permissions``` and check ```Is executable``` 

I faced that also after the latest update.

**Comment by midosaid28** [comment]
> @midosaid28 you should go ```~/.local/share/bin``` and look for ```notification.py``` and right click ```Properties ---> Permissions``` and check ```Is executable``` 
> 
> I faced that also after the latest update.

From the bottom of my heart, Thank you ♡
