### ISSUE TITLE
grub and login to the desktop do not take effect

### ISSUE THREAD

**Issue by jiangdengke** [prasanthrangan/hyprdots#1736]
Today I installed this new script, and then zhon had an error, and at the end there was the following output, and then I quickly checked whether it took effect, and found that the grub interface and the sddm page did not take effect
![微信图片_20240807132652](https://github.com/user-attachments/assets/e048a9da-dbe7-476d-aecf-f3310ba16cdc)

**Comment by jiangdengke** [comment]
By the way, I saw that the demo video of this project supports stacking, but it seems that hyprand does not support stacking. Maybe I haven't found it. If you know, I hope you can tell me. Thank you.

**Comment by kRHYME7** [comment]
Hi the install.sh got a bug that stops the installation at that point. You can use `Hyde-install` instead and instead of installing all the themes just pick a single theme. then the installation will continue. Note that you can just install the themes later.

**Comment by jiangdengke** [comment]
> Did you find the solution to the problem?你找到问题的解决办法了吗？

Sorry, I haven't found it yet

**Comment by jiangdengke** [comment]
> Hi the install.sh got a bug that stops the installation at that point. You can use `Hyde-install` instead and instead of installing all the themes just pick a single theme. then the installation will continue. Note that you can just install the themes later.您好，install.sh 有一个错误，会在安装过程中停止安装。你可以使用 `Hyde-install` 代替，这样就不用安装所有主题，只需选择一个主题即可。注意，你可以稍后再安装主题。

Okay thank you
