### ISSUE TITLE
[Bug]: Mouse stuttering when changing window focus, frame drops.

### ISSUE THREAD

**Issue by mokeWe** [prasanthrangan/hyprdots#1739]
### Description

On a fresh install of Arch, Hyprland, and these dotfiles, I'm having a small issue: whenever I move my cursor between windows everything stutters for a few frames. CPU usage spikes to ~40% if quickly changing between two or more windows.

Additionally, the framerate of the system seemingly cannot maintain a consistent 144 Hz, and slows down significantly every few seconds, only to spring back a little later.

Disabling hypr effects fixes the inconsistent framerate (at the cost of the beautiful animations :[), but not the mouse stuttering.

Any help at all would be appreciated, thanks in advance :]

### Steps to Reproduce

1. Install Arch on an Intel + NVIDIA system
2. Switch focus between two windows.

### Expected Behavior

A buttery smooth experience :]

### Actual Behavior

Stuttering, frame drops.

### Environment

- Linux Distro: Arch Linux
- Linux Version: Linux arch 6.10.3-arch1-2
- Hyprland Version: Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5 (v0.41.2)
- Installation Environment: Baremetal
- Other info: Two monitors, one 1920x1080@144hz, one 1280x1024@75hz

### Additional Information

Unplugging the secondary monitor and restarting the machine does not resolve the issue. #1020 seems to be a similar issue, but none of the fixes suggested there resolved the issue. #800 also seemed promising, but no luck there either.

Here's the output of `hyprctl systeminfo`:

```
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)


System Information:
System name: Linux
Node name: arch
Release: 6.10.3-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 06 Aug 2024 07:21:19 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2070 Rev. A] [10de:1f07] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

```

**Comment by kRHYME7** [comment]
please open it up in the Hyprland GitHub repo😭

**Comment by ledror** [comment]
https://wiki.hyprland.org/Nvidia/#how-to-get-hyprland-to-possibly-work-on-nvidia
Scroll down to "Environment variables"
I noticed after a fresh install that it used the deprecated "WLR_NO_HARDWARE_CURSORS".
use "cursor:no_hardware_cursors = true" and it should be fixed (at least it did for me)

**Comment by kRHYME7** [comment]
@ledror  Can you push a MR, so I can merge it. Hyprland 0.4.2 is released, so we also need to change this ENV var to aquamarine

**Comment by mokeWe** [comment]
That resolved the issue! I'll go ahead and close the issue, and thank you guys again :]
