### ISSUE TITLE
[Bug]: Kvantum theme causes crash

### ISSUE THREAD

**Issue by tinytempmouse** [prasanthrangan/hyprdots#1742]
### Description

Kvantum theme causes [1] 4516 segmentation fault (core dumped) crash stopping all qt6/5 apps from launching eg cmake-gui

### Steps to Reproduce

1. Fresh install of arch
2. Install Hyprdots
3. Open a qt app

### Expected Behavior

Opened app launches

### Actual Behavior

Crash: [1] 4516 segmentation fault (core dumped)

### Screenshots

![IMG_20240810_181843_236](https://github.com/user-attachments/assets/cf1879ca-8814-4e66-9518-fb5076167a15)

### Environment

- Linux Distro: ArchLinux
- Linux Version: 6.6.42-1
- Hyprland Version: v0.41.2
- Installation Environment: On The Main Hardware

### Additional Information

Disabling Kvantum theme in qt6 config file ends the issue but now there is no theme

**Comment by kRHYME7** [comment]
all themes excibit this behavior?

**Comment by tinytempmouse** [comment]
Unfortunately yes

**Comment by kRHYME7** [comment]
can you try to add another user then try to run dolphins in that environment? I can't replicate the issue unfortunately

**Comment by tinytempmouse** [comment]
I've tried that, dolphin or cmake-gui or anything qt based does not launch. The only thing that fixes it is disabling Kvantum in the qt config file.

**Comment by abenezerw** [comment]
Was this solved for you? @tinytempmouse

**Comment by tinytempmouse** [comment]
Besides the sad solution of not using kvantum then no 😞

**Comment by kRHYME7** [comment]
Does kvantum manager still launch?
