### ISSUE TITLE
Everything related to wallpapers doesn't work. How do I fix this?

### ISSUE THREAD

**Issue by H-doctmon** [prasanthrangan/hyprdots#1743]
After installing using the script, it was perfectly working. and then the wallpapers vanished and the keybinds for the wallpapers also stopped working, What might be the issue causing this?
 
 OS EndeavourOS

**Comment by kRHYME7** [comment]
reboot?

**Comment by Bryan-Campuzano** [comment]
> reboot?

i've the same issue, already reboot and nothing appears, i can't change the wallpaper and the theme selector doesn't work also.

**Comment by kRHYME7** [comment]
can you run`Hyde reload ` in the Terminal

**Comment by Bryan-Campuzano** [comment]
![imagen](https://github.com/user-attachments/assets/85d51a73-459b-4fe9-9b42-71fe61bc3de7)
yea, but don't works. and the theme selector looks like this, the wallpaper selector not apears

**Comment by kRHYME7** [comment]
I meant, output for `Hyde Reload`

**Comment by Bryan-Campuzano** [comment]
the` Hyde Reload` command don't works:

![imagen](https://github.com/user-attachments/assets/62e34a7d-06e0-45e3-be1b-b9ac9dba268f)

and this command runs but doesn't work 

![imagen](https://github.com/user-attachments/assets/41c348a5-dacd-409c-b577-f2668e261ef2)

**Comment by kRHYME7** [comment]
Hmm, I don't think you finished the installation successfully

**Comment by Stan-breaks** [comment]
I had the same issue but fixed when I reinstalled hyde

**Comment by Bryan-Campuzano** [comment]
> I had the same issue but fixed when I reinstalled hyde

how do you reinstall this? i try to `pacman/yay -R hyde` and doesn`s works, can you help me?

**Comment by kRHYME7** [comment]
run ./install.sh again.

**Comment by Stan-breaks** [comment]
back up your dot files cos it will rewrite everything

**Comment by Bryan-Campuzano** [comment]
> back up your dot files cos it will rewrite everything

i'm new with this linux custom rices, do you recommend timeshift? or just copy and paste de files on another site and reinstall?
 all help will be accepted

**Comment by kRHYME7** [comment]
The files in this custom configuration are mostly inside $HOME, therefore it might not be covered with timeshift. 

you can try this command instead to preserve certain files/ directory. just add them to `preserve ` 

`  Hyde control Config `
This command is use to make a restore configuration. so just read over the instructions in there.
![image](https://github.com/user-attachments/assets/3b4231a6-c6bf-4c5f-89d8-2afda5b1693a)
![image](https://github.com/user-attachments/assets/dd96f2af-5b01-454d-8c9c-a662fecc2f4b)
click ` Preserve/Ppopulate ` > check the list > then Confirm
If the Configuration is ready, you can run 
` Hyde restore Config ` 
Which should look the same  but it would execute the restoration process if yuou confirm
![image](https://github.com/user-attachments/assets/80abfcbe-b281-4c4e-93d0-b686a5d6bf51)

**Comment by Bryan-Campuzano** [comment]
> The files in this custom configuration are mostly inside $HOME, therefore it might not be covered with timeshift.
> 
> you can try this command instead to preserve certain files/ directory. just add them to `preserve `
> 
> ` Hyde control Config` This command is use to make a restore configuration. so just read over the instructions in there. ![image](https://private-user-images.githubusercontent.com/53417443/361272179-3b4231a6-c6bf-4c5f-89d8-2afda5b1693a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTAzODEsIm5iZiI6MTcyNDgxMDA4MSwicGF0aCI6Ii81MzQxNzQ0My8zNjEyNzIxNzktM2I0MjMxYTYtYzZiZi00YzVmLTg5ZDgtMmFmZGE1YjE2OTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAxNTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MDllMTJkOWRlOWQ0MjMwNDVhNDZlN2IwYjNhNWM2MmRhNDc5NjY0ODA5ZGJhYzA3YWEzMTQ0ZTYwNTgzNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.akzfzxMDoG_KzpcOkaMUlYbOpifP3vu8070zDB7UCRE) ![image](https://private-user-images.githubusercontent.com/53417443/361272262-dd96f2af-5b01-454d-8c9c-a662fecc2f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTAzODEsIm5iZiI6MTcyNDgxMDA4MSwicGF0aCI6Ii81MzQxNzQ0My8zNjEyNzIyNjItZGQ5NmYyYWYtNWIwMS00NTRkLThjOWMtYTY2MmZlY2MyZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAxNTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZjYyNDVjNWMwNjcwZTdmMmYwMjgyYjc3MmRmYTkzNDE3ZjBhMGY5ODEzODcxMGUxY2RjNzhkMzJhNzI5NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LUWMfCwwlNVWEvZCfquC3H9QBIWPqYnqDI5Eb9MDvqs) click `Preserve/Ppopulate` > check the list > then Confirm If the Configuration is ready, you can run `Hyde restore Config` Which should look the same but it would execute the restoration process if yuou confirm ![image](https://private-user-images.githubusercontent.com/53417443/361272390-80abfcbe-b281-4c4e-93d0-b686a5d6bf51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTAzODEsIm5iZiI6MTcyNDgxMDA4MSwicGF0aCI6Ii81MzQxNzQ0My8zNjEyNzIzOTAtODBhYmZjYmUtYjI4MS00YzRlLTkzZDAtYjY4NmE1ZDZiZjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAxNTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MzJmN2I0YjQzMTg3OTAzOGViMTRiZjllNDg3NzQ2NGM0MDFlNjE5MTMzNmE2MDRmNzY3YTNjMDg1MTVkYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6Q1x4jGsFJhRInj-xkMz8kPu5zs-AIob3zX-lzg6po)

tkns man, i fix the issue with the install.sh, gratefully don't erase mi firefox and wallpapers but, dont update the wallpapers library, they still in the folder but i can't select them, how can i change that? maibe some of the config files have the routes? oh and the `hyde` comand still no work jaja

**Comment by kRHYME7** [comment]
as in ` Hyde ` with capital letter?

**Comment by Bryan-Campuzano** [comment]
> as in `Hyde` with capital letter?

`Hyde` and `hyde` doesn't work, but ey, all works fine, i only need add my personal wallpapers and i don`t know to selec them

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/discussions/1783#discussioncomment-10493958

**Comment by abenezerw** [comment]
Could you please close the issue if this has been solved for you. 
@Bryan-Campuzano
