### ISSUE TITLE
[Bug]: Messed up my Hyprland configs; how to reinstall hyprdots from scratch or rebuild it from scratch?

### ISSUE THREAD

**Issue by vampirepapi** [prasanthrangan/hyprdots#1744]
### Description

I just updated my system, and now the Hyprland session is not starting. The login manager keeps reappearing. On TTY, it says:
**Hyprland: error while loading shared libraries: libhyprutils.so.0: cannot open shared object file: No such file or directory**

### Steps to Reproduce

1. Run `sudo pacman -Syu`
2. Restart the system
3. SDDM keeps reappearing

### Expected Behavior

The Hyprland session should start.

### Additional Information

I followed this issue: https://github.com/hyprwm/Hyprland/issues/7185. Creating a symlink fixed it, but now after restarting, the wallpaper and Waybar aren't working. I think I messed something up. Could anyone tell me how I can reinstall Hyprland from scratch while keeping my keybindings and configs, please?

Thanks.

**Comment by vampirepapi** [comment]
@kRHYME7 bro could you help me with this?

**Comment by kRHYME7** [comment]
just remove all hyprland related packages and install it again.


`yay -Rns hyprland hyprlang hyprutils hyprcursor `

**Comment by vampirepapi** [comment]
> just remove all hyprland related packages and install it again.
> 
> `yay -Rns hyprland hyprlang hyprutils hyprcursor `
> 
> then change `-Rns ` to ` -Syu` to install them again

bro what if i have installed hyprland-git and hyprland both?
Sometime because of some pkg dependency i'm not able to uninstall them! :(

**Comment by kRHYME7** [comment]
That would become a nightmare if you can't manage them. You can remove them then reinstall again together with the stable version. I would suggest not to use -git package in arch if you did not understand yet how the PKGBUILD works, you might get an unstable system in there.

**Comment by kRHYME7** [comment]
BTW just run `Hyde-install` it should reinstall HyDE and keybindings are preserved by default so it shouldn't be overwritten

**Comment by vampirepapi** [comment]
> That would become a nightmare if you can't manage them. You can remove them then reinstall again together with the stable version. I would suggest not to use -git package in arch if you did not understand yet how the PKGBUILD works, you might get an unstable system in there.
> 
> Also don't mix dependencies with -git and stable ones. You'll be in dependency hell if some core packages are dropped.

so should i remove git pkgs and stable pkgs as well and reinstall again the stable pkg?
