### ISSUE TITLE
How change kb layout 

### ISSUE THREAD

**Issue by nellle** [prasanthrangan/hyprdots#1745]
while I was studying the settings, I noticed that my layout was not changing, in the settings it was: ru, en 
I decided to check if ru was working and erased en from the config and only after saving realized that all the bindings were tied to the English layout. Is there any way to undo this? I can't even log in to the system.

**Comment by kRHYME7** [comment]
> Is there any way to undo this? I can't even log in to the system. 

+ Login to a different TTY ( `  ctrl + alt + F5 ` ) login in there. 
+ Modify the file that you changed
+ relogin


 *** Questions like these should not be placed in the Issue panel; instead, they belong in the Discussions panel. Alternatively, you could join our Discord server, where someone might assist you in a conversational manner. I will close this issue for now.

**Comment by nellle** [comment]
thank you very much, I already thought that I would have to reinstall the system, you saved me. I'm sorry that I posted it in the wrong place, I was in a panic, I tried to install different Linux distributions for 3 days
