### ISSUE TITLE
[Feature Request]: Different themes for the login screen

### ISSUE THREAD

**Issue by Stan-breaks** [prasanthrangan/hyprdots#1750]
### Different themes for the login screen
I am requesting for different themes for the sddm login screen that can switch with the color scheme selected

### Use Case
To increase consistency of themes all across the machine, and the default although fine it is a bit dull  

### Proposed Solution
Include installation of  different sddm login themes that can be found in the AUR then copy the default login script you guys cooked on to the themes. 

### Alternatives
Make our own themes using the wallpapers with have for different color schemes

### Additional Information
The themes are pretty light weight , I experimented with a few

**Comment by kRHYME7** [comment]
Hi ` Hyde sddm set $Theme ` is now available. I think this is enough capability to switch sddm theme downloaded from the aur.

You just need to find the theme directory at ./.config/hyde/themes/theme-name/hypr.theme.

edit the `hypr.theme` file and add an exec = command

`exec = Hyde sddm set Theme-Name`
