### ISSUE TITLE
My RGB backlit light blinks for a second and turned off after using your hyprdots

### ISSUE THREAD

**Issue by piyushyadav0191** [prasanthrangan/hyprdots#1752]
Previous I had to evoke my backlit light with this command

`sudo sh -c 'echo 1 > /sys/class/leds/input12::scrolllock/brightness'`

but now its not working.

To reproduce
1. Opens the terminal and types the above command
2. then RGB light lit for a second and then turned off
3. I tried again but it blinks for a second only

**Comment by kRHYME7** [comment]
???
