### ISSUE TITLE
[Bug]: Waybar doesn't show up after startup

### ISSUE THREAD

**Issue by Stan-breaks** [prasanthrangan/hyprdots#1758]
### Description
After rebooting my system, the waybar (Wayland status bar) didn't appear on startup as expected.

### Steps to Reproduce
1. Boot the system
2. Login to a session
3. Observe that waybar is not present

### Expected Behavior
The waybar should appear automatically after logging into a session.

### Actual Behavior
The waybar does not appear at all after login.

### Environment
- Linux Distro:  ArchLinux, 
- Linux Version :Linux ArchLinux 6.10.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:30 +0000 x86_64 GNU/Linux
- Hyprland Version:
```bash
   Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
   Date: Wed Aug 7 19:17:10 2024
  Tag: v0.42.0, commits: 5069
```
- Waybar Version: Waybar v0.10.4
- Installation Environment:  On The Main Hardware

### Additional Information
This is happening after a full system update

**Comment by kRHYME7** [comment]
try running waybar in the Terminal

**Comment by sitolam** [comment]
Sometimes I have this too. Then I need to do 'CTRL + ALT + W' to let it show up. I don't know why it happens.

**Comment by Stan-breaks** [comment]
> try running waybar in the Terminal

it shows up when I run it in the terminal but wen I restart it doesn't show up automatically


> Sometimes I have this too. Then I need to do 'CTRL + ALT + W' to let it show up. I don't know why it happens.

thank you ,I will be doing this.I am not that well versed with arch, could it be a problem with a startup script?

**Comment by kRHYME7** [comment]
@Stan-breaks  Yow i too observed this behavior after the aquamarine updates. I am using the latest hyrpland commits right now and works fine.  I am pretty sure this issue is fixed upstream.

**Comment by Stan-breaks** [comment]
@kRHYME7 Thank you
