### ISSUE TITLE
[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by cupenk** [prasanthrangan/hyprdots#1759]
vscode not syncing with theme
![image](https://github.com/user-attachments/assets/2f66bc3c-c9b1-499d-8eb2-aaf5472b43f4)

**Comment by kRHYME7** [comment]
do you have an old installation of any Code? like code-oss or vscodium?

**Comment by kRHYME7** [comment]
also you must reload that windows

**Comment by Stan-breaks** [comment]
I had the same issue but fixed when I reinstalled hyde
