### ISSUE TITLE
[Bug]: Volume module not working after update

### ISSUE THREAD

**Issue by SpaceLarry14** [prasanthrangan/hyprdots#1764]
### Description

Following a full system update, the Pulse Audio volume module does not open, either from the Waybar or from Rofi

### Expected Behavior

Pulse audio should run

### Actual Behavior

Nothing happens

### Screenshots

![240820_09h18m14s_screenshot](https://github.com/user-attachments/assets/05037b3c-328c-4027-92ab-49b2b7b89700)

### Environment

- Linux Distro: CachyOS
- Linux Version: Linux CachyOS 6.10.5-2-cachyos
- Hyprland Version: v0.42.0-18-g3b4aabe0

### Additional Information

Attempted doing a full HyDE upgrade, as well as manually uninstalling pipewire and reinstalling Pulse Audio. Either the module will disappear completely or it will do the same as before

**Comment by kRHYME7** [comment]
run ` pavucontrol  ` ?

**Comment by SpaceLarry14** [comment]
It was already running according to btop. I've given up and blasted my install. You can close this

**Comment by kRHYME7** [comment]
So far I can't replicate this so will consider this for now as system/environment specific issue
