### ISSUE TITLE
[Custom]: Some GTK apps are not  themed

### ISSUE THREAD

**Issue by Melk0rr** [prasanthrangan/hyprdots#1765]
### Description

First of all, thank you a lot for the project. I always dreamt of a piece of software that would synchronize my wallpaper colors across all my applications to achieve complete theming. 

I am not certain that the issue is related to hyde.
My problem is : some of my GTK apps are not following wallbash theme.
I think those application were correctly themed days / weeks ago. I will look into some logs.

### Steps to Reproduce (if applicable)

Not applicable

### Expected Behavior

All GTK apps follow the theme. 
Most of the apps follow the theme properly:
- Firefox
- BlueZ
- Timeshift
- Polkit
- etc

### Actual Behavior

Some apps do not follow the theme
So for exemple:
- Mission Center
- Resources
- Baobab
- Winetricks

#### GTK theme and color scheme:
![GTK theme and color scheme are correctly set](https://github.com/user-attachments/assets/bdbdd348-a7cc-48e3-9815-bae00bd40ddf)

#### Exemple of apps not applying the theme (baobab / resources) :
![Baobab and Resources: KO](https://github.com/user-attachments/assets/521631db-25e1-4ab2-8270-675dc05cc289)
![winetricks](https://github.com/user-attachments/assets/1408fb19-dca3-4772-8d4c-8a8f1288de39)

#### Exemple of app applying the theme
![Timeshift: OK](https://github.com/user-attachments/assets/60c9ad6d-652e-418f-a7ca-991d90643271)

#### Nwg-look:
![nwg-look](https://github.com/user-attachments/assets/ddd5bdbb-8b81-4fda-bcfe-c63c329b47df)

### Proposed Solution (if applicable)
- Do you guys have any lead ?

### Additional Information
- I use Wallbash
- I do not use any flatpak application. Only official repos and AUR
- GTK theme and color scheme are correctly set
- nwg-look shows no error and follow the theme
- Running baobab or resources from terminal do not show any particular error

**Comment by kRHYME7** [comment]
Hi! Thank you for the elaborate bug report, are you using the wallbash in automode ?  I can't replicate your issue but can you check if your configs are the same with the upstream wallbash gtk template? 


mission center (aur)
![image](https://github.com/user-attachments/assets/d4aca391-6daa-4798-bf5d-2ec488eb8b4a)
misson center flatpak 
![image](https://github.com/user-attachments/assets/4c9faf05-1018-4391-b553-fbaf4064f588)

![image](https://github.com/user-attachments/assets/fa6b00b2-de64-41f5-988d-33f69bbc2cd1)

**Comment by kRHYME7** [comment]
Can you try to change themes and restart the instance of those applications?

**Comment by Melk0rr** [comment]
Hello !
Thanks for you response. I just found out where the issue comes from:
![screenshot_20240821_16h23m10s](https://github.com/user-attachments/assets/246f5d98-b46f-49cc-90dd-3aedbac937e1)

- So the symlink **gtk-4.0** in _~/.config_ points to _~/.themes/<Current theme>_. It does not point to ~/.themes/Wallbash-Gtk.
- When I delete it and create it manually to point to **Wallbash-Gtk**, all the apps follow the theme:
![screenshot_20240821_16h40m15s](https://github.com/user-attachments/assets/8ac90a77-5120-4be3-8eab-96b3dcbe5bcc)


- It is generated by themeswitch.sh:
![screenshot_20240821_16h27m43s](https://github.com/user-attachments/assets/85f776ca-5e48-474c-8330-d1dbe490d402)
- So am I missing something here ? When wallbash is toggled is it not supposed to change the theme pointed by the symlink ? I installed everything manually (btw)

Again thank you for the help !

**Comment by Melk0rr** [comment]
Thing is: 

- In themeswitch.sh, gtk theme is retreived here. From this file **${hydeThemeDir}/hypr.theme**:
![screenshot_20240821_17h04m01s](https://github.com/user-attachments/assets/80551698-5f11-4c8d-9cf9-5d94c80dc3e7)

-  **gtkTheme** value can't be "Wallbash-Gtk" since it uses hyde themes located in **hydeThemeDir.**
- So there:
![screenshot_20240821_17h06m37s](https://github.com/user-attachments/assets/f3b105af-640b-4006-9fc6-50381f8a366f)
The symlink will never point to Wallbash-Gtk right ?

**Comment by kRHYME7** [comment]
If you are using wallbash auto,dark,light Modes it will point to the wallbash template directory and of course will  use Wallbash-Gtk as we can see when you query it using gsettings.

So to put it simply, When wallbash is on then It should use the Wallbash-Gtk.

**Comment by Melk0rr** [comment]
I just don't see where it is supposed to override in the code.
And since I use wallbash with dark mode. I don't get why this symlink does not point to Wallbash-Gtk.

**Comment by kRHYME7** [comment]
hypr.theme are populated to ./hypr/theme/theme.conf

so we can say that the exec = gsettings... command is executed effectively setting the gtk theme

Now when wallbash mode is enabled./hypr/wallbash/Wall-Dcol/hypr.dcol will populate to ./hypr/theme/theme.conf  which in turn overrides the gtk-theme to Wallbash-Gtk 
https://github.com/prasanthrangan/hyprdots/blob/main/Configs%2F.config%2Fhyde%2Fwallbash%2FWall-Dcol%2Fhypr.dcol

![Screenshot_2024-08-21-23-36-52-640_com.github.android-edit.jpg](https://github.com/user-attachments/assets/81eacb06-c06e-4964-ba0f-7cb9776b7302)

**Comment by kRHYME7** [comment]
> But apparently, some apps look at the files directly in ~/. config/gtk-4.0 rather than the theme in gsettings 

It's strange to me why the themeswitch.sh skips or exits before linking ./gtk-4.0 in your end. There must be something lacking in your install.

**Comment by Melk0rr** [comment]
> It's strange to me why the themeswitch.sh skips or exits before linking ./gtk-4.0 in your end. There must be something lacking in your install.

- It does not skips or exits before the linking. But always links to the gtk theme corresponding to selected hyde theme rather than Wallbash-Gtk if wallbash is enabled
- For exemple, If I select the theme _Catppuccin Mocha_, then it will link to the **gtk-4.0** in **~/.themes/Catppuccin-Mocha/gtk-4.0**. Instead of linkink to Wallbash-Gtk if wallbash is enabled

**Comment by kRHYME7** [comment]
I see, in most cases, gsettings command will override for every gtk apps. So I can say that the ` exec =  ...` part which is in colors.conf (ONLY during wallbash mode)  is executed, making the current gtk theme  "Wallbash-Gtk".  Which is pretty much sufficient, given that this is use for months now.  
I do not know what is happening during gsettings command execution, but I'm sure whatever the `gsettings` command executed, it is respected (sometimes) by the whole display SESSION . One can try testing it ` gsettings set org.gnome.desktop.interface gtk-theme Theme-name ` and it is dynamic. But I guess not all applications respects this and instead tries to use whatever is in ./gtk-*.0 ?  

Given that you're the only one reported this (as I can remember) shows that there might be lacking on the install, as to why gsettings command did not affect some apps. 

Let's try to reference this issue for now for the time being and see if we should really force the symlink.

**Comment by Melk0rr** [comment]
> Let's try to reference this issue for now for the time being and see if we should really force the symlink.
- Yep, I specifically added instructions in themeswitch on my end to handle wallbash for this symlink. So it is working.

> Given that you're the only one reported this (as I can remember) shows that there might be lacking on the install, as to why gsettings command did not affect some apps.
- Yeah, I agree. Because I installed everything manually, there might be some things handled during the installation process that avoids this. I will dig a little bit into this

Thank you again !
