### ISSUE TITLE
[Bug]: Windows are moving for no reason in graphite mono theme.

### ISSUE THREAD

**Issue by CaioSimioni** [prasanthrangan/hyprdots#1768]
### Description
Windows are moving for no reason in graphite mono theme.

### Steps to Reproduce
https://youtu.be/fO2nRseDffM?si=wZ9LhBYqOx2b3xCl

### Environment
Arch Linux x86_64 v6.10.5-arch1-1
Hyprland v0.42.0
AMD Ryzen 5 600
GeForce RTX 3060
16 GiB RAM

### Additional Information
I thought it was relevant to open this issue because I didn't find anything talking about it.
aur/prismlauncher 8.4-2

**Comment by kRHYME7** [comment]
Can you check if it's running under Wayland or Xwayland?

run ` hyprctl clients `

**Comment by CaioSimioni** [comment]
```
hyprctl clients

Window 5fad9ebd3c80 -> [Bug]: Windows are moving for no reason in graphite mono theme. · Issue #1768 · prasanthrangan/hyprdots — Mozilla Firefox:
	mapped: 1
	hidden: 0
	at: 17,17
	size: 1886,1014
	workspace: 3 (3)
	floating: 0
	pseudo: 0
	monitor: 0
	class: firefox
	title: [Bug]: Windows are moving for no reason in graphite mono theme. · Issue #1768 · prasanthrangan/hyprdots — Mozilla Firefox
	initialClass: firefox
	initialTitle: Mozilla Firefox
	pid: 24779
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags: 
	swallowing: 0
	focusHistoryID: 1

Window 5fada76c96e0 -> hyprctl clients:
	mapped: 1
	hidden: 0
	at: 17,17
	size: 1886,1014
	workspace: 5 (5)
	floating: 0
	pseudo: 0
	monitor: 0
	class: kitty
	title: hyprctl clients
	initialClass: kitty
	initialTitle: kitty
	pid: 33306
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags: 
	swallowing: 0
	focusHistoryID: 0

Window 5fada70d87a0 -> Prism Launcher 8.4:
	mapped: 1
	hidden: 0
	at: 17,17
	size: 1886,1014
	workspace: 2 (2)
	floating: 0
	pseudo: 0
	monitor: 0
	class: org.prismlauncher.PrismLauncher
	title: Prism Launcher 8.4
	initialClass: org.prismlauncher.PrismLauncher
	initialTitle: Prism Launcher 8.4
	pid: 34970
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags: 
	swallowing: 0
	focusHistoryID: 3
```

**Comment by CaioSimioni** [comment]
note: Prismlauncher is not the only application in this state, dolphin itself is shaking the window only in graphite mono theme

**Comment by kRHYME7** [comment]
Can you enable your wallbash ?  to **auto, dark or light** instead of theme

![image](https://github.com/user-attachments/assets/c0734256-8322-451e-aed1-44b051a5ec78)

I will check if this is due to a qt theme bug.

**Comment by kRHYME7** [comment]
Hi this is a bug from the graphite qt theme

Please move this issue on this repo https://github.com/prasanthrangan/hyde-themes/tree/Graphite-Mono

**Comment by kRHYME7** [comment]
and this are the problematic files 

https://github.com/prasanthrangan/hyde-themes/tree/Graphite-Mono/Configs/.config/hyde/themes/Graphite%20Mono/kvantum
