### ISSUE TITLE
[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by devsjuans** [prasanthrangan/hyprdots#1769]
---

### Description

Applications like Eclipse and DBeaver are not functioning properly, specifically their visual components fail, making them very difficult to read. Although it is not apparent in screenshots, when positioning the cursor over certain areas, nearby elements blend into the background, making them indistinguishable.

### Steps to Reproduce

1. Open Eclipse or DBeaver.
2. Try navigating through the UI or accessing menus.
3. Observe the visual issues, especially when moving the cursor over different areas.

### Expected Behavior

The applications should display correctly with clear and readable text and UI components, without any blending issues.

### Actual Behavior

The visual elements of the applications, such as text and menus, are either not rendered correctly or are difficult to read. Additionally, hovering over certain areas causes nearby elements to blend into the background.

### Screenshots

![240821_13h16m29s_screenshot](https://github.com/user-attachments/assets/78c87f4d-7dc2-40cb-9330-7897310ca46a)

### Video

[Video demonstrating the issue](https://vimeo.com/1001312775?share=copy)

### Environment

- Linux Distro: Arch Linux
- Linux Version: Linux 6.10.6-arch1-1 (output of `uname -a`)
- Hyprland Version: [Provide output of `hyprctl version`]
- Installation Environment: Main Hardware
- Display: 1920x1080 @ 144 Hz (External) and 1024x768 
- WM: Hyprland (Wayland)
- GPU: GeForce RTX 2060 Rev. A
- GPU Driver: NVIDIA (proprietary) 555.58.02

---

**Comment by kRHYME7** [comment]
Are you using a different DE before populating HyDE configs?

**Comment by devsjuans** [comment]
> Are you using a different DE before populating HyDE configs?

 No, during the Archinstall process, I used the minimal profile along with the additional packages like git, nano, vim, and unzip. After the base installation was completed, I directly downloaded HyDE and ran the installation script(./install.sh custom_apps.lst).

**Comment by kRHYME7** [comment]
are ` DBeaver ` and ` Eclipse ` all QT apps?

**Comment by devsjuans** [comment]
No, DBeaver and Eclipse are not QT applications. Both DBeaver and Eclipse are built using SWT (Standard Widget Toolkit), which is a different framework from QT. DBeaver runs on the Eclipse RCP (Rich Client Platform), which also uses SWT for its user interface. So, neither of these apps use QT for their UI.

> are `DBeaver` and `Eclipse` all QT apps?

**Comment by kRHYME7** [comment]
I see, what I can tell from glance are those applications "sometimes" follow the GTK colors but only some parts of it. Can you check if it's possible to not use the system theme, so these apps will have their own colors?  This will lead to the apps having their own color scheme apart from the Whole System, but this means it is more usable. IMO, this is better. 

Or another approach is to search for any methods on theming those apps aside from GTK theming. (gtk theming on this one I think is not fully utilized as some parts example the "workspace" is always white like what we see on browsers too )



![image](https://github.com/user-attachments/assets/5eb09f06-2b7d-4452-9927-c28f3931465c)

**Comment by kRHYME7** [comment]
for dbeaver I followed this 
https://dbeaver.com/docs/dbeaver/User-Interface-Themes/ 
The results is this It actually can follow the Whole GTK thing now by enabling ` High Contrast ` 
![Uploading image.png…]()

**Comment by devsjuans** [comment]
> ### dbeaver
> I followed this https://dbeaver.com/docs/dbeaver/User-Interface-Themes/ The results is this It actually can follow the Whole GTK thing now by enabling `High Contrast` or Classic ![image](https://private-user-images.githubusercontent.com/53417443/360224273-b26bfeb6-bc5e-4a7c-938f-840f788fe5c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTM0NTMsIm5iZiI6MTcyNDI5MzE1MywicGF0aCI6Ii81MzQxNzQ0My8zNjAyMjQyNzMtYjI2YmZlYjYtYmM1ZS00YTdjLTkzOGYtODQwZjc4OGZlNWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAyMTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNDBmMWU3ZmRjMzc2OTljMGQyNmVjZjAxY2Y1MGI3ZGRjMjZiNDA4MGJhZDZlMTNjYWYzYTVlM2Q2ZTE1YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7FaCo6zbGjlSgGZME371RcE19e30Jz0_v1jdlhGnr8o)

Thank you so much for resolving the issue with DBeaver! I’ll check out the Eclipse problem next. I’ll look into that later. Thanks again for your assistance

**Comment by kRHYME7** [comment]
If both have the same framework both should be themed the same
