### ISSUE TITLE
[Bug]: Code_Wallbash.vsix extension not installed

### ISSUE THREAD

**Issue by olisancor** [prasanthrangan/hyprdots#1772]
### Description

I performed a clean install of HyDE, but when opening code, I noticed that the Code_Wallbash.vsix extension was not installed. And the problem is that when installing it manually by downloading the .vsix and running it with code --install-extension Code_Wallbash.vsix, the extension does not automatically detect the themes, so it does not change color.

**Comment by kRHYME7** [comment]
you need to reload the vscode window. this is expected as of now.
