### ISSUE TITLE
Waybar Font size change to default 

### ISSUE THREAD

**Issue by Ram3zani** [prasanthrangan/hyprdots#1775]
Hi
I clone your repo and install on fresh arch. Everything is good. Because my scaling is  125% waybar default font size is not good for me. I search for how change font size waybar. I change font size in Style.css file in waybar config folder. Waybar font size is good now. But i have problem when i change theme or switch between dock or panel waybar Font size change to default font size. How can i fix this?

**Comment by kRHYME7** [comment]
![image](https://github.com/user-attachments/assets/7d28a597-22d4-46c5-9c5d-b566a53c3965)

waybar configurations layout are written on the file from ./waybar/config.ctl.  
![image](https://github.com/user-attachments/assets/46ebecaa-892d-4445-af05-d95be42be649)

` size | position | ( left modules ) | ( center modules ) | ( right modules )
