### ISSUE TITLE
Cpu usage 

### ISSUE THREAD

**Issue by Ram3zani** [prasanthrangan/hyprdots#1776]
Hello 
my laptop cpu is intel 10 Gen. Fresh arch and your repo. Everything is fine. But one core my cpu always 80% usage. My battery draining and laptop is hot. Dolphin file manager is laggy when right click menu.

**Comment by kRHYME7** [comment]
try to use another theme. 
disable animations 

Check this command. 
![image](https://github.com/user-attachments/assets/0c1f2d97-bd66-496b-94a2-426089af58b5)

you might also need to checkout the hyrpland wiki page
 https://wiki.hyprland.org/
 https://wiki.hyprland.org/Getting-Started/Master-Tutorial/
