### ISSUE TITLE
[fixed ] [Bug]: Dolphin: Icons theme doesnt change with themes

### ISSUE THREAD

**Issue by TheyCallMeSecond** [prasanthrangan/hyprdots#1778]
icons doesnt change with changing theme since today...for example graphite mono's icon is tela circle grey but it is not
i restored the configs but didnt fix
![image](https://github.com/user-attachments/assets/9cae8c72-a6b9-4e82-a383-0521cc425961)

**Comment by kRHYME7** [comment]
what is in the screenshots? looks normal to me.
 can you run `Hyde reload ` and see what errors you might catch.

**Comment by TheyCallMeSecond** [comment]
the icon pack you see in the screenshot is not Tela Circle gray
i got no error

**Comment by nvn-bisht** [comment]
I got the same problem since I updated dolphin

**Comment by kRHYME7** [comment]
Coming from an update and experiencing the same. Hope someone can link any issue related to dolphin. Is this a regression or we should set something.

**Comment by abenezerw** [comment]
> Coming from an update and experiencing the same. Hope someone can link any issue related to dolphin. Is this a regression or we should set something.

![image](https://github.com/user-attachments/assets/a00e85de-c2fa-4887-bc5c-017255a5c37f)
same

**Comment by thyeun** [comment]
Same here, only dolphin wont update the icon, when there is a icon theme change.

**Comment by TheyCallMeSecond** [comment]
changing file manager is not an option for me :))

**Comment by kRHYME7** [comment]
Cool, you can wait for an update from arch repo. Or try to use the dev version of dolphin (might cause dependency hell)

**Comment by kRHYME7** [comment]
If you used dolphin excessively, you can try nemo. Thunar is so simple 

![image](https://github.com/user-attachments/assets/b632545f-b289-4d5d-8abe-72dfbf77123a)
(by defaut)

**Comment by thyeun** [comment]
This is a ```cache``` issue, if you all know where to clear the ```cache```, it will be solve. I cant find out the ```cache``` file. hahahaha

All ```cache``` that i know, i been deleted.

**Comment by kRHYME7** [comment]
@thyeun  I can't seem to fix it even though I cleared my ~/.cache

**Comment by thyeun** [comment]
@kRHYME7 not in that folder, it should be at /var. But some how this update of dolphin, not put it under /var

**Comment by dyba404** [comment]
## Temporary Solution
1. **Installing the tool `downgrade`**  
   `downgrade`  is a utility that facilitates the installation of older versions of packages.

   Install  `downgrade` using `yay`:
   ```bash
   > yay -S downgrade
   > sudo downgrade dolphin

## Preventing Dolphin Automatic Updates
  ```bash
     > sudo nano /etc/pacman.conf
       IgnorePkg=dolphin

**Comment by gomma91** [comment]
I had the same problem, solved by downgrade dolphin whit: 
`sudo pacman -U file:///var/cache/pacman/pkg/old_version_dolphin`

**Comment by rubiin** [comment]
You can also edit the kdeglobals 
See here for a fix with latest version

![image](https://github.com/user-attachments/assets/274fdf99-acef-49f7-9cc2-9616cdf7758e)

![image](https://github.com/user-attachments/assets/29306822-29ef-4bab-834e-9fb42202f51e)

**Comment by rubiin** [comment]
Can be closed I guess

**Comment by thyeun** [comment]
This one still consider temporary solution, due to that if you change to another icons theme, you have to manually edit the ```kdeglobals``` again.

**Comment by kRHYME7** [comment]
I figured something out. If this is an intended feature of dolphin, I will add the Icon part of ./kdeglobals  ship with the dotfiles. 


How dolphin gets its icons
| version                | qt5 | qt6 | kdeglobals |
| ---------------------- | --- | --- | ---------- |
| dolphin 24.02.2-2 <br> | x   | /   | x          |
| dolphin 24.08.0-1      | x   | x   | /          |

**Comment by kRHYME7** [comment]
Please try this patch 

https://github.com/prasanthrangan/hyprdots/pull/1806

**Comment by thyeun** [comment]
@kRHYME7 the new update work on yours?

**Comment by kRHYME7** [comment]
> @kRHYME7 the new update work on yours?

Yes and I think ` dolphin 24.08.0-1 ` uses kdeglobals. This might change if dolphin supports Qt6 again. 

The older version of dolphin is not supporting kdeglobals only qt6

**Comment by rubiin** [comment]
> dotfiles.

I think so too. You might wanna confirm here https://discuss.kde.org

**Comment by thyeun** [comment]
@rubiin @kRHYME7 thanks for finding out the solution 🫡🫡🫡

**Comment by thyeun** [comment]
KDE is a big joke to me, they been changed dolphin from ```kdeglobals``` to ```qt6```, than now they change back from ```qt6``` to ```kdeglobals```.

This is the reason i'm never using KDE.

**Comment by ArctynFox** [comment]
@kRHYME7 Even after making the changes in the update you linked, Dolphin still looks like this for me, where there are borders in the UI and the main view isn't themed:

![image](https://github.com/user-attachments/assets/6f7fd15a-a593-4339-81ec-8af965309b78)

**Comment by thyeun** [comment]
@ArctynFox Two things to confirm with you.

1. Are you been changed the original look of dolphin from this dotfile to the image that you attached?
2. Can you share out your ```~/.config/dolphinrc``` ?

Original dolphin should look like this.
![240905_23h02m28s_screenshot](https://github.com/user-attachments/assets/0a3dd3e3-e91e-4f97-9285-68ba4fd492ae)

**Comment by rubiin** [comment]
![image](https://github.com/user-attachments/assets/d99ed21c-6d41-444b-9508-2a09d1eb7f9d)

Working fine. I am using catpuccin as well. Also make sure to change theme. Like change from one theme to another

**Comment by rubiin** [comment]
ktorrent uses qt6 while dolphin uses kdeglobals :D

**Comment by ArctynFox** [comment]
@thyeun The only thing I've changed about Dolphin myself is the options on the toolbar.

I haven't modified dolphinrc myself either, but here it is:

```
MenuBar=Disabled

[$Version]
update_info=dolphin_detailsmodesettings.upd:rename-leading-padding

[General]
ShowSelectionToggle=false
ShowStatusBar=false
Version=202
ViewPropsTimestamp=2023,4,26,16,58,48.324

[IconsMode]
MaximumTextLines=1
PreviewSize=112

[InformationPanel]
dateFormat=ShortFormat

[KFileDialog Settings]
Places Icons Auto-resize=false
Places Icons Static Size=16

[KPropertiesDialog]
2560x1080 screen: Window-Maximized=true

[MainWindow]
MenuBar=Disabled
ToolBarsMovable=Disabled

[MainWindow][Toolbar mainToolBar]
IconSize=16
ToolButtonStyle=IconOnly

[PlacesPanel]
IconSize=16

[PreviewSettings]
Plugins=appimagethumbnail,audiothumbnail,comicbookthumbnail,cursorthumbnail,djvuthumbnail,ebookthumbnail,exrthumbnail,imagethumbnail,jpegthumbnail,kraorathumbnail,windowsexethumbnail,windowsimagethumbnail,opendocumentthumbnail,svgthumbnail,ffmpegthumbs

[Toolbar mainToolBar]
IconSize=16
ToolButtonStyle=IconOnly
```

**Comment by thyeun** [comment]
@ArctynFox 

1. For the icons change with theme change, check this file ```~/.local/share/bin/themeswitch.sh```. And go to line ```86```, see this line exist or not ```sed -i "/^Theme=/c\Theme=${gtkIcon}" "${confDir}/kdeglobals"```.

if the line not exist, you can add it manually than logout/login and try to change the theme and see the icon change according to theme change or not.

**Comment by ArctynFox** [comment]
@thyeun I've already made this change; the icons are theming properly, but the window is not.

Trying on a different user now as kHRYME suggested.

**Comment by ArctynFox** [comment]
@kRHYME7 
> you can reinstall HyDe on a new user to confirm . This is a hustle, but I can't really provide any solution to this.

I've done as you asked, but on the new user, dolphin is completely unthemed other than icons:
![240905_10h42m07s_screenshot](https://github.com/user-attachments/assets/841d6cfe-78f3-4e0e-8a72-fe8f1c5591ea)
![240905_10h42m52s_screenshot](https://github.com/user-attachments/assets/9c070b31-c8bc-47d8-8b47-ae11814a21b1)

**Comment by ArctynFox** [comment]
@thyeun I tried as you recommended here but it's produced no change. It still looks as it did above.

**Comment by thyeun** [comment]
@ArctynFox Change one time theme, and see any different?

**Comment by ArctynFox** [comment]
I did change themes a few times, but it didn't resolve.

**Comment by thyeun** [comment]
@ArctynFox can you share your ```kdeglobals```?

**Comment by ArctynFox** [comment]
@thyeun
>@ArctynFox can you share your kdeglobals?

```
[General]
TerminalApplication=kitty

[Icons]
Theme=Tela-circle-dracula
```

**Comment by curtainp** [comment]
encounter the same problem with same kdeglobals config and latest version dolphin. btw, it's also a fresh installation from minimal archinstall.
kdeglobals config:
```
[General]
TerminalApplication=kitty

[Icons]
Theme=Adwaita
```


dolphin version: local/dolphin 24.08.0-1
![image](https://github.com/user-attachments/assets/d02a62ec-9862-428e-970b-3332946fb60e)

**Comment by kRHYME7** [comment]
Hi everyone, 

Can you check if this env vars can potentially resolve the issue of dolphin?
![image](https://github.com/user-attachments/assets/2c5b5ed1-fb14-44d5-9124-7e0730e613c5)



 I'm somehow confused why this issue is not consistent. The only thing I needed (my end) is to change the
```
[Icons]
Theme=Some=Theme
```
But some users needed this to change the background, etc in kdeglobals. Anyone here knows the proper Docs for this?

usig dolphin 24.08.1-1

**Comment by thyeun** [comment]
Make change on ```kdeglobals``` is the only way to get back the icon theme for version ```24.08.1-1```

**Comment by kRHYME7** [comment]
how about the backgorund and other stuff. Some got issues but I don't.

**Comment by ArctynFox** [comment]
None of them resolved the background issue, and the final one leaves the entire application unthemed save for icons:
![image](https://github.com/user-attachments/assets/eda76840-7c7a-495a-8414-d071c77c02da)

**Comment by kRHYME7** [comment]
@ArctynFox  

So this background of yours is just from kdeglobals?

```
 [Colors:View]
BackgroundNormal=#xxxxxx 
```

**Comment by thyeun** [comment]
i dont think that background is related to dolphin, it is wallbash and you have to set your dolphin into transparent

**Comment by thyeun** [comment]
show your qt6/qt5 setting and kvantum setting with screenshot pls.

**Comment by ArctynFox** [comment]
> So this background of yours is just from kdeglobals?

Yes, it just displays the color listed in kdeglobals, which for me is #464646


> dolphinrc

Only difference I can see is that I have MenuBar=Disabled at the top. Removing it doesn't seem to change anything.
```
MenuBar=Disabled

[$Version]
update_info=dolphin_detailsmodesettings.upd:rename-leading-padding

[General]
ShowSelectionToggle=false
ShowStatusBar=false
Version=202
ViewPropsTimestamp=2023,4,26,16,58,48.324

[IconsMode]
MaximumTextLines=1
PreviewSize=112

[InformationPanel]
dateFormat=ShortFormat

[KFileDialog Settings]
Places Icons Auto-resize=false
Places Icons Static Size=16

[KPropertiesDialog]
2560x1080 screen: Window-Maximized=true

[MainWindow]
MenuBar=Disabled
ToolBarsMovable=Disabled

[MainWindow][Toolbar mainToolBar]
IconSize=16
ToolButtonStyle=IconOnly

[PlacesPanel]
IconSize=16

[PreviewSettings]
Plugins=appimagethumbnail,audiothumbnail,comicbookthumbnail,cursorthumbnail,djvuthumbnail,ebookthumbnail,exrthumbnail,imagethumbnail,jpegthumbnail,kraorathumbnail,windowsexethumbnail,windowsimagethumbnail,opendocumentthumbnail,svgthumbnail,ffmpegthumbs

[Toolbar mainToolBar]
IconSize=16
ToolButtonStyle=IconOnly
```


> qt6 setting

![image](https://github.com/user-attachments/assets/f9f5e174-5a42-4a73-a41a-657b2f146c84)
![image](https://github.com/user-attachments/assets/a29c18c4-6626-4064-abb5-85295755717d)

**Comment by thyeun** [comment]
As you can see here, the background you see, actually is a transparent of dolphin, it is not a background for dolphin.
![241010_10h01m26s_screenshot](https://github.com/user-attachments/assets/8fc33080-d8d0-487c-9613-fdf01361bb99)

**Comment by ArctynFox** [comment]
@thyeun I don't know what you're asking me to do, the only difference between it working and not working is the version of Dolphin I am using. If I downgrade to 24.05.2-1 it works as expected:
![image](https://github.com/user-attachments/assets/e3d9cd01-e7ff-401f-918e-ea27789d11b2)

**Comment by kRHYME7** [comment]
I removed the wallpaper. I'm just confused of why it is not consistent across other devices.  


![image](https://github.com/user-attachments/assets/d107380f-7e00-43f9-a3f3-57f5329c38c6)

**Comment by ArctynFox** [comment]
Ah, right, I forgot to show kvantum as well:
![image](https://github.com/user-attachments/assets/5070645f-1184-4fab-9a90-a7d2999b1058)

**Comment by kRHYME7** [comment]
Same as wallbash right ?
![image](https://github.com/user-attachments/assets/e9569360-c134-4802-9bb3-1345a596ba43)


Here's the thing we can auto generate the kdeglobals but issues are we are touching other kde stuff just to fix dolphin

**Comment by thyeun** [comment]
the version i'm using is 24.08.1-1 and im not encounter any issue. and with fresh installation, at for another two laptop with the change kdeglobals with version 24.08.1-1, i still no facing any issue.

**Comment by kRHYME7** [comment]
> at for another two laptop with the change kdeglobals with version 24.08.1-1, i still no facing any issue.

@thyeun  

I could assume some of the ones with issues has some unknown envs  and a fresh installation can potentially fix it?

**Comment by thyeun** [comment]
My Kvantum setting as below 

![241010_10h14m10s_screenshot](https://github.com/user-attachments/assets/44cd0d20-0eb2-4ec6-9af3-96c11e157588)
![241010_10h14m46s_screenshot](https://github.com/user-attachments/assets/26b9dfb3-5ec7-468a-827d-bc0f029bb12c)
![241010_10h15m32s_screenshot](https://github.com/user-attachments/assets/379e0b53-136a-4749-9a38-64d0d7f4172c)

**Comment by ArctynFox** [comment]
As I said earlier though, I tried a fresh install on a laptop and experienced the same issue:
![image](https://github.com/user-attachments/assets/13dbd881-b63c-422f-a316-e50f7e09e553)

**Comment by kRHYME7** [comment]
Sorry for not being clear but the issue I'm trying to diagnose is the background where dolphin tries to use the one in the kdeglobals

**Comment by kRHYME7** [comment]
> As I said earlier though, I tried a fresh install on a laptop and experienced the same issue:

Damn dolphin, too confusing.

**Comment by kRHYME7** [comment]
@ArctynFox  Is your wallbash on auto?

**Comment by ArctynFox** [comment]
As in, does it change automatically if I switch theme or wallpaper? Yes

**Comment by kRHYME7** [comment]
this 
![image](https://github.com/user-attachments/assets/b5a20b0a-2e82-4ff8-853a-f7f987f0edd7)



@thyeun  @ArctynFox  let's continue it here https://github.com/prasanthrangan/hyprdots/issues/1843

**Comment by thyeun** [comment]
@kRHYME7 As @ArctynFox mentioned early, the old version work out of the box. Since like new version some how still having some cache issue.

**Comment by kRHYME7** [comment]
So we should just wait for more info from dolphin kde right?

**Comment by thyeun** [comment]
Explain further, during fresh installation, the dolphin version is old version, and once it been install, it will cache in the setting, and if the cache setting are not clear out after the new version been install, when qt env change to kdeglobals.

old version is using qt env
new version is using kdeglobals
