### ISSUE TITLE
[Bug]: Dolphin 24.08.0 Partially Unthemed

### ISSUE THREAD

**Issue by ArctynFox** [prasanthrangan/hyprdots#1780]
### Description

This might actually be an issue in dolphin itself, but when I upgraded to dolphin 24.08.0 today, UI borders appeared in dolphin and the main file view is back to using the theme defined by KDE's system settings. According to my environment variables and qt6 and kvantum settings, it still should be using the same theme and works fine if I downgrade back to 24.05.2. See the screenshots below. Nothing else about my setup is different, it goes between working and not working simply by upgrading and downgrading only dolphin.

### Screenshots

Before dolphin update:
![after update](https://github.com/user-attachments/assets/d1b47ab3-3f59-426e-9343-a807a4f8679b)

After dolphin update:
![after update](https://github.com/user-attachments/assets/c28cb61f-fe87-46a6-b1b8-cb201f60f210)

### Additional Information

I have KDE Plasma installed as well as Hyprland, so it may be an issue solely present on machines with both installed. Until now, this has caused no similar issues.

**Comment by kRHYME7** [comment]
dup https://github.com/prasanthrangan/hyprdots/issues/1778
