### ISSUE TITLE
[Bug]: Dolphin background color changed to white

### ISSUE THREAD

**Issue by FatPootis03** [prasanthrangan/hyprdots#1784]
Dolphin's background color turned white and stays like this on every theme.
Edit: I forgot to add that i tried updating, and it didn't help.

![image](https://github.com/user-attachments/assets/09e142fd-a693-47dd-b473-3c79b74ee3ae)

### Expected Behavior

The background matched the theme

### Environment

-Linux Distro: RebornOs Arch
-Version:6.10.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000 x86_64 GNU/Linux
-Hyprland version:Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069
-Main hardware
-Display resolution: 2880 x 1800
-Scale: 2

**Comment by kRHYME7** [comment]
dup
