### ISSUE TITLE
Wallpaper is black

### ISSUE THREAD

**Issue by Ethanol48** [prasanthrangan/hyprdots#1788]
After I installed it, worked fine, everything was correct, but after an update to my system the wallpaper stopped working.

I investigated the code and try to run from the command line the script responsible for the wallpaper and works.

I tried to change settings inside the hyprland conf to see if it's being loaded, and it does, it seems that hyprland is not running the `exec-once` statement for the wallpaper, does anyone have or had this problem?

**Comment by kRHYME7** [comment]
running this ` swwwallpaper.sh ` after boot  shows the wallpaper? 


what is the output for this 

` grep "restore" ~/.local/share/bin/swwwallpaper.sh ` ?

**Comment by Ethanol48** [comment]
Yes, if I run the script manually shows the wallpaper.

**Comment by kRHYME7** [comment]
2nd question?.

**Comment by Ethanol48** [comment]
Yesterday I tried to re-install HyDe and now works as it should.

**Comment by Ethanol48** [comment]
> running this ` swwwallpaper.sh ` after boot  shows the wallpaper? 
> 
> 
> 
> 
> 
> what is the output for this 
> 
> 
> 
> ` grep "restore" ~/.local/share/bin/swwwallpaper.sh ` ? 

Hi, yes it worked at the moment, but I think that I'm now unable to give you the output of that command as maybe could not be relevant.

After some time yesterday I reinstalled HyDe and the problem disappeared.

Do you still want it?

**Comment by kRHYME7** [comment]
> Hi, yes it worked at the moment, but I think that I'm now unable to give you the output of that command as maybe could not be relevant. 

After some swww updates about  a month or two I added this  
` swww query && swww restore ` to that swwwallpaper.sh to fix this issue. So updating your scripts should fix it.
