### ISSUE TITLE
How to achieve a similar README markdown

### ISSUE THREAD

**Issue by Ew4n1011** [prasanthrangan/hyprdots#179]
Hi, sorry if this clutters the issues page, but I was trying to replicate the Warning section of the README in markdown, but I can't seem to find how you applied the colors and icons. Most places say its impossible to do, but obviously it isn't since you have. I managed to color the text using:
```
<blockquote style=color:orange><strong>Warning</strong>
```
Yet I still can't find out how to colour the sidebar, nor how to add the icon.

Thanks in advance

**Comment by prasanthrangan** [comment]
Hi, just do this -
```
> **Warning**
>
> This is a warning!
```

And it will look like this -
> **Warning**
>
> This is a warning!

**Comment by Ew4n1011** [comment]
Yes that worked, thanks!
