### ISSUE TITLE
[Bug]: 1K External Display Turns Off After Logging into Hyperland

### ISSUE THREAD

**Issue by sharjeelmazhar** [prasanthrangan/hyprdots#1790]
### Description

After logging into Hyperland, my 1K external monitor (connected via DP-1) turns off, even though it works perfectly on the login screen. The cursor can move to where the monitor should be, but the display remains off.

### Steps to Reproduce

1. Boot the system and reach the login screen (SDDM or similar).
2. Observe that all three monitors are active:
   - Laptop Display: eDP-1
   - 2K Display: HDMI-A-1 (main display, on the left side)
   - 1K Display: DP-1 (on the right side)
3. Log into Hyperland.
4. The 1K external monitor (DP-1) turns off, while the other monitors remain active.

### Expected Behavior

The 1K external monitor (DP-1) should remain active and display content after logging into Hyperland, just as it does at the login screen.

### Actual Behavior

The 1K external monitor (DP-1) turns off upon logging in, despite being correctly configured in the Hyperland config file. The cursor can still move to the monitor’s position, but the display itself is off.

### Screenshots

![image](https://github.com/user-attachments/assets/fc810c52-3e80-4f9a-b295-a048333cd5c6)

**Monitor Layout:**

- **1 (eDP-1):** Laptop Display
- **2 (HDMI-A-1):** 2K Display (current screenshot monitor)
- **3 (DP-1):** 1K Monitor (having the issue)

**Issue Explanation:**

At the login screen, all three displays (Laptop, 2K, and 1K) are detected and functioning properly. I can move my cursor across all screens, indicating that the hardware setup is correct.

However, after logging into Hyperland, the 1K monitor (DP-1) turns off, even though it is configured in the Hyperland configuration file. The cursor can still move to the area where the 1K monitor should be, but the display remains off.

Initially, I tested the auto-detection by commenting out all custom monitor lines, but the 1K monitor still did not work after login. I then commented out the auto-detect line and manually set the configurations for `HDMI-A-1` and `DP-1`, but the issue persisted.

This suggests that the problem is not related to a conflict between auto-detect and manual configurations, but rather an issue with how Hyperland is handling the 1K monitor after login.

### Environment

- **Linux Distro:** [Arch Linux]
- **Linux Version:** [Linux arch 6.10.6-arch1-1]
- **Hyprland Version:** [Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069]
- **Installation Environment:** On The Main Hardware
- **Display Configuration:** 
  - **Monitor 1:** HDMI-A-1, 2560x1440@60, main display, left side
  - **Monitor 2:** DP-1, 1920x1080@60, right side
  - **Laptop Display (eDP-1):** Disabled in Hyperland config

### Additional Information

- Configuration lines used in `~/.config/hypr/hyprland.conf`:

```plaintext
monitor = HDMI-A-1,2560x1440@60,0x0,1
monitor = DP-1,1920x1080@60,2560x0,1

**Comment by kRHYME7** [comment]
An Upstream issue please post this immediately in the Hyprland repository. We won't be much of help here.

**Comment by kRHYME7** [comment]
The dev there will fix it immediately as long as you provide a sufficient logs

**Comment by sharjeelmazhar** [comment]
should i create the same issue on the hyprland official github relo?

**Comment by kRHYME7** [comment]
yes

**Comment by kRHYME7** [comment]
Wait. Can you try to install ` yay -Sy hyprland-git ` ? I think this one is already fix upstream

**Comment by sharjeelmazhar** [comment]
let me try and will let you know, will is cause any issue with my working setup of hyprland with hyprdots?

**Comment by kRHYME7** [comment]
> let me try and will let you know, will is cause any issue with my working setup of hyprland with hyprdots?

Not much, You'll just be using the latest commits. Not good if you're looking for stability.

**Comment by sharjeelmazhar** [comment]
i am not able to install it, it say that there are some conflicts with the files and packages related to hyprland (not git version) so i am not able to install hyprland-git it throws an error. should i reinstall the system with hyprland-git? how would i be able to do it because by default i guess hyprdots install script installs hyprland not hyprland-git and one more thing, on the login screen i see japanese/chinese text idk for sure, how can i make it to english?

**Comment by kRHYME7** [comment]
It's fine I'm daily driving Hyprland-git right now to foresee any changes for this repo. Just be sure to remember what files are overwritten when you type Y. If you're not confident doing it. Then the best you can do is wait for the v0.43.0 update of hyprland and hope it fixes the monitor issue 



for the sddm one let's tackle it later as issue panel In GitHub does not have a reply option.

**Comment by sharjeelmazhar** [comment]
if i install arch on external ssd and try to test out the hyprland-git, what changes do i need to make in the hyprdots? will it ask me on setting up what should i use? like when we clone this repo and run the install.sh file to setup HyDE.

**Comment by kRHYME7** [comment]
> if i install arch on external ssd and try to test out the hyprland-git, what changes do i need to make in the hyprdots? will it ask me on setting up what should i use? like when we clone this repo and run the install.sh file to setup HyDE.


Nope. It's quite hard to answer all upstream issues of the -git package, so we are using the official release.

**Comment by sharjeelmazhar** [comment]
If you could just find a few minutes if your valuable time to provide me an online resource or a few instructions of setting up hyprland-git and hyprdots then I'll be greatly thankful to you!

**Comment by kRHYME7** [comment]
hmmm you don't need to setup anything on your install now. Please don't be confused with this. 

hyprland < the versioned release
hyprland-git <  the latest commits and soon will be the released version

Difference are the issues of the versioned release might be fixed on the latest commits. 

Changing version is simply downloading a package


` yay -Sy hyprland-git ` and you're good to go .  


![image](https://github.com/user-attachments/assets/ab25c6e9-5942-43fe-9c81-d0e9a62ce681)

**Comment by kRHYME7** [comment]
If your issues are fixed on this version, then rest assured it will be fixed on the next versioned release. So you either wait for that release or use -git for the mean time, then switch back to versioned if they release it .

**Comment by sharjeelmazhar** [comment]
when i try to install: paru -S hyprland-git and it throws an error stating that a few dependencies are needed by hyprland and cant ununistall

![image](https://github.com/user-attachments/assets/7417ed10-0cc8-44fa-97b9-a3185c4cb00b)

**Comment by kRHYME7** [comment]
Then ` yay -Rns hyprland ` then ` yay -Sy hyprland-git ` 

Try learning your package manager as this would be helpful in the future.

**Comment by sharjeelmazhar** [comment]
yes, i actually did watch a yt tut on pacman, thanks for advice!

**Comment by sharjeelmazhar** [comment]
Thank you man!!! i just really cant thank you enough, i ran your commands but it was not removing hyprland because of a conflict and i asked chatgpt and it helped me and now my issue is resolved, i install hyprland-git and that 2nd monitor has started working!!! ALL THANKS TO YOU MAN!

**Comment by kRHYME7** [comment]
If the 2nd monitor is essential use hyprland-git for now. If hyprland v0.4.3 is released you can install hyprland again. as -git is expected to change

**Comment by sharjeelmazhar** [comment]
Will do! Thank you for your time and support. Much appreciated.

**Comment by sharjeelmazhar** [comment]
and also did you mean: 0.43.0? because the latest version of github is 0.42.0. just wanted to double check.
