### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by rares9301** [prasanthrangan/hyprdots#180]
Where is the folder that contains the images displayed in the kitty terminal? i d like to change them. Also inside neofetch i d like to get the Arch image back 😀

**Comment by prasanthrangan** [comment]
Hi, are you referring to pokemon sprites? you can change it by removing file [this](https://github.com/prasanthrangan/hyprdots/blob/79807bdfdfb26f94d342ed7b5312754ceccee961/Configs/.zshrc#L126) line in .zshrc file!

for neofetch, comment out [this](https://github.com/prasanthrangan/hyprdots/blob/79807bdfdfb26f94d342ed7b5312754ceccee961/Configs/.config/neofetch/config.conf#L721C1-L721C1) line to get back the default Arch logo

**Comment by rares9301** [comment]
Thank you for your input. What if instead of removing, i want to just change the images to my custom ones?

**Comment by rares9301** [comment]
> Hi, are you referring to pokemon sprites? you can change it by removing file [this](https://github.com/prasanthrangan/hyprdots/blob/79807bdfdfb26f94d342ed7b5312754ceccee961/Configs/.zshrc#L126) line in .zshrc file!
> 
> for neofetch, comment out [this](https://github.com/prasanthrangan/hyprdots/blob/79807bdfdfb26f94d342ed7b5312754ceccee961/Configs/.config/neofetch/config.conf#L721C1-L721C1) line to get back the default Arch logo

Thank you for the information. Solved
