### ISSUE TITLE
# [Bug]: SDDM Not Starting Automatically, No Customization Applied After Hyprdots Installation

### ISSUE THREAD

**Issue by sharjeelmazhar** [prasanthrangan/hyprdots#1801]
### Description

After installing Hyprdots on a fresh, minimal installation of Arch Linux, several issues have been encountered:

- **SDDM does not start automatically upon reboot**. Instead, the system boots into TTY.
- **When SDDM is manually started** using `systemctl`, it loads the default, uncustomized SDDM theme, lacking any of the configurations or customizations provided by Hyprdots.
- **Default shell is not set to Zsh** as it should be according to the Hyprdots install script.

### Steps to Reproduce

1. Perform a minimal installation of Arch Linux using the Arch install script.
2. Clone the Hyprdots repository and run the install script.
3. Reboot the system.
4. The system boots into TTY instead of starting SDDM.
5. Log in via TTY and manually start Hyperland by typing `Hyperland`.
6. Notice that the default shell is not Zsh.
7. Manually start SDDM using `systemctl enable sddm` and `systemctl start sddm`.
8. Observe that SDDM uses the default theme without any customizations.

### Issues Observed

- **SDDM does not start automatically** after installation and reboot.
- **No customizations** from Hyprdots are applied to SDDM; it loads with the default look.
- **Zsh is not set as the default shell** after logging into Hyperland from TTY.

### Expected Behavior

- SDDM should start automatically with the customized theme applied by Hyprdots.
- The default shell should be set to Zsh after installation, as configured by the Hyprdots script.

### Actual Behavior

- The system boots into TTY instead of starting SDDM.
- When SDDM is manually started, it loads with the default, uncustomized theme.
- The default shell is not set to Zsh, requiring manual configuration.

### Environment

- **Linux Distro**: Arch Linux
- **Linux Version**: Linux arch 6.10.7-arch-1
- **Hyprland Version**: built from branch at commit 9a09eac... 5a9259, Tag: 0.42.0, commit 5069
- **Installation Environment**: On the Main Hardware
- **Other Info**: Using Intel CPU, all packages are up-to-date.

### Additional Information

These issues were not present in a previous installation using the same script on the same hardware 3 or 4 days ago. Everything, including SDDM and Zsh, was automatically configured and customized as expected.

**Comment by kRHYME7** [comment]
can you please re run the installer?
 but with -s flag.

./install.sh -s

**Comment by kRHYME7** [comment]
@sharjeelmazhar  https://github.com/prasanthrangan/hyprdots/wiki/Installation#execution

**Comment by sharjeelmazhar** [comment]
I'm reinstalling the whole OS and I'll surely follow wiki this time and will let you know if the issue still persists! Until then, I think we should keep this issue open as I had the same issue twice or thrice today, so maybe there is a bug, maybe not! Who knows, I'll give it a last try.

**Comment by sharjeelmazhar** [comment]
I'm reinstalling the whole OS and I'll surely follow wiki this time and will let you know if the issue still persists! Until then, I think we should keep this issue open as I had the same issue twice or thrice today, so maybe there is a bug, maybe not! Who knows, I'll give it a last try.

**Comment by kRHYME7** [comment]
This is actually an expected issue. You can try to install this using `Hyde-install`  and only choose 1 or 2 themes. The issue is during installation the script tries to install 12 themes from a different repo simultaneously and makes the script Stop after the last theme. 
The owner has not yet been active for months now to fix this issue, and I'm not planning to touch his installation Script. So I maintained the CLI.

**Comment by kRHYME7** [comment]
Or if you want to follow the above wiki. I suggest you edit the `themepatcher.lst ` and comment out some theme repo and leave at least 1 or 2 themes.

You can Install more themes later using the `Hyde theme patch ` command later.

**Comment by sharjeelmazhar** [comment]
Let me try it! Will let you know!

**Comment by sharjeelmazhar** [comment]
Could you please suggest to me the way by which it should get it all working and at the same time I have all of the themes.

**Comment by kRHYME7** [comment]
If you still did not reinstall the whole OS yet, Run ` Hyde-install` 

You can have all the themes later on, just don't select all the themes during the installation.

**Comment by kRHYME7** [comment]
Then installation of themes will simply be ` Hyde theme patch ` then select themes. 
![image](https://github.com/user-attachments/assets/5753d812-45b5-4ad7-b7a8-784791f0fb93)

**Comment by sharjeelmazhar** [comment]
I have reinstalled the OS, minimal arch Linux using arch install script 😂 what should I do next to set it up, should I use HyDE install or what?

**Comment by kRHYME7** [comment]
```
curl -sL https://raw.githubusercontent.com/kRHYME7/Hyde-cli/master/install.sh | bash
```



then run `Hyde-install` after

**Comment by thyeun** [comment]
This is not a bug, it happen because your download theme been not finish it all, and it cause by two issues, first it is because your download speed and second it is because the download theme site been very slow and the re-try been reach out and once the retry been reach out, it will jump/skip to next theme, if the next theme still having the same issue, it will continue till all without finish up the download theme, but the installation still will continue until the content of the installation script finish up (meaning here, you finish up the installation but the theme or the retry download been skip), That why you have the default sddm theme.

For your solution, you can manually install sddm and sddm theme, than it will solve your issue.

**Comment by sharjeelmazhar** [comment]
I do have somewhat slow/unstable connection of 10 Mbps as you know here in Pakistan we don't have that good Internet service. Is there any way that I can manually download all those fonts and big files and place them in their respective directories so that when I run ./install.sh it doesn't have to go and download and cause problems?

**Comment by sharjeelmazhar** [comment]
The script doesn't work well with 10 Mbps connection, so I had to connect my mobile via USB tethering and it worked just fine. Everything was setup and working properly. 

[IMP] DO THIS IF YOU HAVE A SLOW INTERNET LIKE MINE!!!

You might wanna run the script a few times if you face any issues with the setup, try executing it `./install.sh`several times until it doesn't download or do anything and just runs and exits quickly. And also if you zsh is not changed automatically then run this command in the terminal to change it `chsh -s /use/bin/zsh`


This issue is resolved, you can close this.
