### ISSUE TITLE
4k 1.5 scaling in apps ; Fractional Scaling 

### ISSUE THREAD

**Issue by mpoweredo** [prasanthrangan/hyprdots#181]
Hi there!

First of all i wanna emphesize that im newbie to linux, hyprland etc.
My problem is that i have 4k monitor and when i was using macos or windows i used to have scaling 1.5 which gives me real view of 2560x1440. In the hyprland.conf I also set scaling to 1.5 and it works great with the system things like terminal, waybar etc but for example discord, vscode or chromium are not scaled properly and the resolution of these apps is 4k. I've done some research and find that I should propably set GDK_SCALE so Ive done this but the problem is that i cannot use non integer values like 1.5 scale that I want. Is there any way to achive that my apps would be scaled properly in 1.5 scale that I want?

thanks for reading this :D please be forgiving for not knowing a lot of about this, I just wanna learn some new stuff :D

**Comment by prasanthrangan** [comment]
Hi, GDK_SCALE only applies to xwayland applications (legacy apps that only runs on xorg), and fractional scaling does not work for those apps.
So please set `env = GDK_SCALE,2` and let the native wayland applications use 1.5 scaling.

**Comment by stove-jeebs** [comment]
maybe try increase your scaling by changing `monitor = eDP-1, <resolution>@<refresh-rate>,0x0,1.5`

**Comment by stove-jeebs** [comment]
did you change your scaling at `monitor = eDP-1, <resolution>@<refresh-rate>,0x0,1.5`? Discord seems to be properly scaled on my device

**Comment by kRHYME7** [comment]
@mpoweredo If you're still using hyprdots now, here's how to do it, but this sometime makes some apps blurry

```
xwayland:force_zero_scaling = false
```


This will just try to scale it explained above
```
env = GDK_SCALE,2
```

+ Some apps are just not design for fractional scaling, therefore making every app of this kind blurry (x11  apps)

+ Some apps also have their own scaling implementation, so maybe check each package documentation.

+ Apps that can scale on a Wayland compositor should not give you scaling problems. 


Please reopen this if needed .
