### ISSUE TITLE
[Bug]: Issues with icon themes applying with dolphin.

### ISSUE THREAD

**Issue by poseidonai555** [prasanthrangan/hyprdots#1811]
### Description

Issues with icon themes applying with dolphin.

### Expected Behavior

Icon themes from theming applications (qt6ct, qt5ct, nwg-look) would apply to dolphin. 

### Actual Behavior

Icon themes selected had no impact on dolphin.

### Screenshots

![240906_19h39m55s_screenshot](https://github.com/user-attachments/assets/b6fbff72-5544-4f1a-9f34-454502527c4f)

How dolphin looks with current wallbash kvantum theme and tela-circle-purple icon themes applied.

### Environment

- Linux Distro: Arch Linux
- Linux Version: 6.10.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 04 Sep 2024 15:16:37 +0000 x86_64 GNU/Linux
- Hyprland Version: Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069
- Installation Environment: Bare metal

### Additional Information

I have qt6ct, qt5ct, kvantum manager and nwg-look installed, all of which are working well for themeing across the system, it just seems that I am unable to apply the tela-circle-purple or any other icon theme to dolphin.

**Comment by kRHYME7** [comment]
#1778 ?

**Comment by kRHYME7** [comment]
Likely dolphin is trying to get the theme from kdeglobals
