### ISSUE TITLE
The screen Shot quality is very poor, i want to increase screenshot quality what shall i do

### ISSUE THREAD

**Issue by slyjain** [prasanthrangan/hyprdots#1812]
### Description

[Provide a clear and concise description of the bug.]

### Steps to Reproduce
![image](https://github.com/user-attachments/assets/f74cad8a-602c-4cb7-99a2-640a8a3f4cb1)
![screenshot_2024-09-07_11-55-37](https://github.com/user-attachments/assets/a6721ca7-7d24-4aa0-9cd9-30437bd8d9f1)
![screenshot_2024-09-07_12-02-16](https://github.com/user-attachments/assets/a6c30694-a8c6-498e-9d91-5789bacaa8d9)

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by kRHYME7** [comment]
Here's the repo for grim.
https://github.com/emersion/grim
I guess there is no option to improve its quality. 

you can try to use flameshot 

https://github.com/flameshot-org/flameshot
