### ISSUE TITLE
Custom resolution

### ISSUE THREAD

**Issue by nizarfadlan** [prasanthrangan/hyprdots#182]
Before using these dots I had set a custom resolution size of 1600x900@60 but I tried on `hyprland.conf` after using these dots suddenly blank screen and returned to the lock screen and could not log in.
![230909_12h27m42s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/40895148/7b6c9127-af69-4d22-82f5-7fa1594400c8)
![image](https://github.com/prasanthrangan/hyprdots/assets/40895148/a62b6461-e468-4811-a16b-5ec320f66b57)

**Comment by prasanthrangan** [comment]
Hi, does your monitor support `1600x900@60` ? based on xrandar it looks like your monitor only supports upto `1366x768`

**Comment by nizarfadlan** [comment]
> Hi, does your monitor support `1600x900@60` ? based on xrandar it looks like your monitor only supports upto `1366x768`

I don't understand if what I'm doing is strange or not because previously I used this https://github.com/SolDoesTech/HyprV4 can customize resolutions above the high resolution of the laptop screen

**Comment by stove-jeebs** [comment]
@nizarfadlan try `monitor = eDP-1, 1366x768@59.80, 0x0 , 1`?
