### ISSUE TITLE
[Bug]: Waybar Displays Time in UTC Instead of Local Time After Upgrade

### ISSUE THREAD

**Issue by amedeo** [prasanthrangan/hyprdots#1829]
### Description

After a recent upgrade, the Waybar clock widget displays the time in UTC rather than the local time set in the system. This issue persists even though the system time is correctly configured to the local time zone.

### Expected Behavior

The time displayed by Waybar should reflect the local time zone configured in the system settings.

### Actual Behavior

Waybar displays the time in UTC, ignoring the local time configuration set on the system.

### Screenshots

![image](https://github.com/user-attachments/assets/d0cc027f-c151-434a-81a2-e89f9050510a)

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux x570 6.10.9-arch1-1
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

- Installation Environment: On The Main Hardware

### Additional Information

- No changes were made to the Waybar configuration prior to the update.
- A temporary workaround has been to adjust the time format manually in Waybar’s configuration, though this is not ideal.

**Comment by kRHYME7** [comment]
downgrade tzdata


Check the issue panel. GitHub does have a search feature.
