### ISSUE TITLE
[Bug]: After reboot it doesn't go past Sddm, it just changes the theme

### ISSUE THREAD

**Issue by XSebastian-GimenezX** [prasanthrangan/hyprdots#1830]
I did a minimal installation of arch and ran the install.sh script and everything worked perfectly until I restarted the PC and from then on it wouldn't let me log in.

**Comment by XSebastian-GimenezX** [comment]
Information that could possibly help would be that I have an Nvidia GT 710 graphics card and an AMD Ryzen 5 2600 processor and something that could possibly be the reason for the error is that it told me to uninstall some Nvidia drivers because otherwise it wouldn't continue due to an incompatibility error. If you need anything else, let me know and please help me because I have to finish a university project and I love this configuration too much to abandon it.

**Comment by kRHYME7** [comment]
please navigate to a different TTY by ` ctrl alt f5 ` then login. 
After that run ` Hyprland ` inside  there. You can take a photo of the output, or you can redirect it to a file and send it here

**Comment by XSebastian-GimenezX** [comment]
![IMG_20240912_002308](https://github.com/user-attachments/assets/2d3a71b3-fca2-4070-b2a5-228e12c66cf6)

Here is the photo you asked me for

**Comment by kRHYME7** [comment]
![Screenshot_2024-09-12-13-40-49-423_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/e3556aa2-b0ea-46f9-b62b-dd1be9eb4312)

File a bug to the hyprland repository providing that file.
 You can also send it here let's check what we can do.

You can also `yay -Syu hyprland-git ` then reboot see if the latest commits already fix this

**Comment by abenezerw** [comment]
Was this solved for you @XSebastian-GimenezX
