### ISSUE TITLE
[Bug]: Can't get past GRUB when rebooting after fresh install

### ISSUE THREAD

**Issue by Lqnk4** [prasanthrangan/hyprdots#1846]
### Description

I'm using an nvidia rtx 3050 ti, after installing from both an arch install minimal profile as well as a manual install, the first time launching Hyprland after the setup script works great. I did a reboot immediately after entering hyprland and when I get back to grub and try to boot into arch I suddenly don't get any hdmi display output and can't get to the tty. I also tried fallback initramfs, booting arch with no display mode by putting a 3 after the Linux line in the default grub kernel parameters, and setting vga=887 to force the display resolution GRUB gives to the kernel to change.
### Steps to Reproduce

1. Do archinstall with a minimal profile
2. Go through the install script, login, and enter hyprland
3. Reboot the system
4. Try to boot arch after reaching GRUB
### Expected Behavior
Grub boots into sddm properly
### Actual Behavior
I no longer get any hdmi display output (notified by my monitor) and can't reach a try.
### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

.g.,

- Linux Distro: Arch Linux
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`: tried on both latest hyprland and hyprland-git packages 
- Installation Environment: Main hardware, RTX 3050 Ti, Intel i3 7th gen with integrated graphics attempted as enabled and disabled in the BIOS
- Other info:Monitor Display Resolution is 1080p

### Additional Information

After chrooting into the system it seems like hyprland didn't leave a log file from the first time it launched properly

**Comment by kRHYME7** [comment]
Check the old issues about this. 
Can you check you kernel parameters , do you have this set 
![image](https://github.com/user-attachments/assets/be1bd79a-1b62-4504-9931-a50853a044dd)

**Comment by Lqnk4** [comment]
Yes, though I have it as "nvidia-drm.modeset=1" in my /etc/default/grub 
I tried both as well as "nvidia_drm.modeset=1" but the dash is what works on my other machine so I left it as that

Also after further testing after trying to set up x11 or any other non-tty based display manger I end up with the same black screen so It doesn't seem like a hyprland/installer script issue, more an nvidia driver issue

**Comment by heretic1321** [comment]
Was this resolved ? I am getting the same issue with my rtx 4070.

**Comment by kRHYME7** [comment]
Try opening the issue in the Hyprland repo.
