### ISSUE TITLE
Feature Request : Variety + swww + pywall

### ISSUE THREAD

**Issue by KAGEYAM4** [prasanthrangan/hyprdots#185]
I am new to ricing, basically just using your configs right now. 

What do you think about later adding varity ( change wallpaper automatically from online sources ) + pywall ( get prominent color from wallpaper ) into this setup.

**Comment by prasanthrangan** [comment]
Hi, swww is already in use.
I've not tried variety and pywall, but will have a look!

**Comment by kRHYME7** [comment]
Hello, @KAGEYAM4  we have wallbash now for pywall and the swww. About Variety, I think that's possible.

>  change wallpaper automatically from online sources ) 

We can definitely make a dynamic changing of wallpapers, Ill try to write it in [this](https://github.com/kRHYME7/Hyprdots-ctl) repo. 

However not all $user might want to connect to internet for there wallpapers. So I think the win-win  implementation should be  user have any option(e.g. variaty) to feed a directory where the wallpapers are hosted. Now if new wallpapers will be available the the dynamic changing of wallpaper will fetch images on that folder.  
What do you think? 

I really love this feature I have a  while back I'm using windows but it slows my system.

**Comment by KAGEYAM4** [comment]
> However not all $user might want to connect to internet for there wallpapers. So I think the win-win implementation should be user have any option(e.g. variaty) to feed a directory where the wallpapers are hosted. Now if new wallpapers will be available the the dynamic changing of wallpaper will fetch images on that folder. What do you think?

Yuup, true. 

How is bashwall implemented, can it not just change the color based on active wallpaper? I was thinking - no need to have another script, variety will donwload and apply wallpapers. Bashwall will change color.

**Comment by kRHYME7** [comment]
the wallbash is written by @prasanthrangan  to  make all this related apps  follow the wallpaper color palette. 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/2a3b1ac5-5a72-4b3d-a27d-17f6e474ba4f)

BTW I don't know how to to change wallpaper using variety. I have read some of its backend scripts and it all points  out to  sway WM command line. Have you tried using variety to change wallpaper?

**Comment by kRHYME7** [comment]
@KAGEYAM4   This feature looks cool!  I am currently using it now. Would you like to test it ?

**Comment by KAGEYAM4** [comment]
@kRHYME7  yes its swaybg, but the current set-wallpaper script has a bug, this fixes it https://github.com/varietywalls/variety/commit/0d2e7f0075e707f51ea2038a755b60373ae83093

>  This feature looks cool! I am currently using it now. Would you like to test it
Sorry, currently i am not doing any ricing. As you can see, the only thing i am running now is variety
![image](https://github.com/prasanthrangan/hyprdots/assets/75798544/04d6b8ce-6250-4771-b718-a0b56577759d)


i looked at `/scripts/swwwallbash.sh` which is called by `scripts/swwwallpaper.sh`, more can be explained by [prasanthrangan], 
and also variesy calls `set-wallpaper.sh` with its first argument the name of wallpaper/or path not sure, you can just edit that to call swwwallpaper.sh

**Comment by KAGEYAM4** [comment]
also do you of anyother projects beside pywal as it was last updated 6 years ago.
https://github.com/dylanaraps/pywal/issues/670
https://github.com/eylles/pywal16

**Comment by kRHYME7** [comment]
@KAGEYAM4  Thanks! this app is very intuitive so I got used to it. Here's a discussion of its functionality https://github.com/prasanthrangan/hyprdots/discussions/876 . I am looking forward to resolving this feature request so we can close it.

**Comment by kRHYME7** [comment]
@KAGEYAM4 I'll be closing this for now as the variety is another set of suite and this is optional for the users. But the integration of variety is now possible and working.  https://github.com/prasanthrangan/hyprdots/discussions/876

**Comment by eylles** [comment]
maybe not relevant anymore but just pushed the latest release of pywal16 and it is now available at pypi https://pypi.org/project/pywal16/
