### ISSUE TITLE
The blur effect 

### ISSUE THREAD

**Issue by Hareekshith** [prasanthrangan/hyprdots#1855]
This effect is not seen in my device at the places of theme switcher and power menu, is it because I have missed a module?

**Comment by kRHYME7** [comment]
Screenshots please.

**Comment by Hareekshith** [comment]
![240917_17h43m34s_screenshot](https://github.com/user-attachments/assets/febbe14b-766d-4662-8770-3ab7bbe023a1)

**Comment by kRHYME7** [comment]
That's expected. That one you launch is not  the same as the other launcher. this is wlogout.

That one you send has blur because that "layer" is rendered in full screen with a transparent background. The other launcher which is "rofi" is not rendered in Fullscreen.

**Comment by Hareekshith** [comment]
Which menu should I use here to get the expected blur in the menu?

**Comment by kRHYME7** [comment]
> Which menu should I use here to get the expected blur in the menu?

Blurs are dictated by the themes. Try to check various themes and see any difference

this is the themeselector are you expecting to have blurred in here? 
![image](https://github.com/user-attachments/assets/8da47247-2685-4c0d-9a7f-f6a1e237d61f)

**Comment by Hareekshith** [comment]
Bruhh, I want blur as it is showcased in the youtube
![image](https://github.com/user-attachments/assets/11bfca11-5082-42bd-a7b9-e1cea3e9e9d4)
But what I am getting is for the same theme:
![image](https://github.com/user-attachments/assets/26e6eac9-d917-493d-bb2f-6e45d44c6d4f)
What package have I not downloaded?

**Comment by kRHYME7** [comment]
You only need Hyprland for the blur.

Try to enable wallbash mode instead of theme mode

**Comment by kRHYME7** [comment]
What you're saying is you don't have blur at your end? Like for the windows and layers?

**Comment by Hareekshith** [comment]
Great, enabling wallbash mode worked!!
![image](https://github.com/user-attachments/assets/1cdbb2e0-e381-4e47-a848-67b4665d6488)

**Comment by kRHYME7** [comment]
> Blurs are dictated by the themes. 

So here's a thing . 

wallbash auto,dark,light are  just an autogenerated themes so you can just think of it as a theme alone.

**Comment by m-cnan** [comment]
> You only need Hyprland for the blur.
> 
> Try to enable wallbash mode instead of theme mode

hi in what are you saying to change?

**Comment by Hareekshith** [comment]
> > You only need Hyprland for the blur.
> > Try to enable wallbash mode instead of theme mode
> 
> hi in what are you saying to change?

Press the shortcut SUPER+SHIFT+R, keep auto as the theme, now you will have the blur setup!
