### ISSUE TITLE
[Feature Request]: Short description of the feature

### ISSUE THREAD

**Issue by Hareekshith** [prasanthrangan/hyprdots#1861]
### Description
Add the Cava, in the waybar module u already have

### Use Case

People will have an aesthetic view of the cava from the waybar instead of loading from the CLI

**Comment by rubiin** [comment]
until supported here, you can use this https://github.com/JaKooLit/Hyprland-Dots/blob/2b715deacefc61247ca15ed8527730c0537407f1/config/waybar/ModulesCustom#L109C1-L112C3

**Comment by rubiin** [comment]
![image](https://github.com/user-attachments/assets/84ac331e-cd3a-4c13-8174-7ad2c5961d56)

**Comment by rubiin** [comment]
I have a pr , lets wait till merge

**Comment by Hareekshith** [comment]
Man, how do I go about applying it? I am new to arch hyprland

**Comment by rubiin** [comment]
> Man, how do I go about applying it? I am new to arch hyprland

you could just add custom/cava component to whichever waybar style you are using.
I added a waybar style at the end of the waybar styles list as an example

**Comment by kRHYME7** [comment]
@rubiin  Can you also change 1 into 0 it will case wbarconfgen to have errors

**Comment by Hareekshith** [comment]
Can you just send me an ss of your config.ctl file? with the waybar style text?
