### ISSUE TITLE
[Bug]: My SSDM just stop showing...

### ISSUE THREAD

**Issue by ind4skylivey** [prasanthrangan/hyprdots#1866]
**After the last update last night, now when i see the typical Point i can't see the fantastic SSD that this repo give. what could happen, or what should i do to fix it ?**

**Comment by kRHYME7** [comment]
it reverts to default? 

run ` Hyde sddm set `  and select a theme 

![image](https://github.com/user-attachments/assets/e41280e2-dae4-44f9-94b4-fc7e2ab9fe9b)

**Comment by AzanAdnan23** [comment]
Help
![image](https://github.com/user-attachments/assets/27ef0388-7e78-4767-b20c-595760bc1924)

**Comment by kRHYME7** [comment]
Try to read the errors.
 There's   [note]  try to run the recommended command. also check if that directory even exist.

You can also try to run `Hyde sddm install` first

**Comment by Anshul-007** [comment]
You can close this issue
