### ISSUE TITLE
Waybar updates module doesn't update

### ISSUE THREAD

**Issue by Newer1107** [prasanthrangan/hyprdots#187]
I changed this config file:
![image](https://github.com/prasanthrangan/hyprdots/assets/116626403/4cf369c9-4c82-48d4-927e-27728fd71d91)
I made it to check updates every hour instead of every day like it was before, however it doesn't update anymore. It just stays on zero until I click it. Here's a video for context:

https://github.com/prasanthrangan/hyprdots/assets/116626403/a15d7857-c7d3-46b6-9727-09a9e779a6a4

**Comment by prasanthrangan** [comment]
hmmm, i'll have a look...
