### ISSUE TITLE
[Bug]: Dolphin theme lost 

### ISSUE THREAD

**Issue by BentleyOph** [prasanthrangan/hyprdots#1870]
So after a full system upgrade it seems i have lost my dolphin theme ,saw a recent issue with Dolphin too here .Is the issue upstream for this too 
![image](https://github.com/user-attachments/assets/737defbf-fb81-4b78-a79a-5fb97a4ef7d9)

**Comment by kRHYME7** [comment]
Please show your ~/.config/kdeglobals

**Comment by BentleyOph** [comment]
> Please show your ~/.config/kdeglobals

![image](https://github.com/user-attachments/assets/f28462f6-627e-4c6b-bdaf-6b6f46885fc5)

**Comment by kRHYME7** [comment]
![image](https://github.com/user-attachments/assets/79bd97e6-989d-487b-92a6-e303ebbe791b)

Add 

```
[Icons]
Theme= add something random here
```


then change a theme to toggle it.

**Comment by rodrygo-c-garcia** [comment]
there is a problem with the latest updates with Dolphin, the workaround is to use an older version:
```
yay -S downgrade
sudo downgrade dolphin       #choose version `24.05.2` or a different version than the current version
```

**Comment by kRHYME7** [comment]
status?

**Comment by kRHYME7** [comment]
Hi everyone, 

Can you check if this env vars can potentially resolve the issue of dolphin?
![image](https://github.com/user-attachments/assets/2c5b5ed1-fb14-44d5-9124-7e0730e613c5)

**Comment by BentleyOph** [comment]
> status?

Went with downgrading and that worked
