### ISSUE TITLE
[Bug]: GUI Volume Control Not Launching

### ISSUE THREAD

**Issue by oven8** [prasanthrangan/hyprdots#1878]
### Description

After updating to the latest pipewire-alsa and pipewire-pulse (version 1.24), hyprland (version 0.43.0) the volume control GUI is not opening anymore. I also have easyeffects installed, which is also not opening. I can however control volume from keyboard bindings.

### Steps to Reproduce

Not sure yet.

### Expected Behavior

I expect the GUI to launch from the app drawer on clicking.

### Actual Behavior

Volume control GUI is not launch. In fact nothing is happening.

### Screenshots

Not applicable here.

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: 6.10.10-arch1-1
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196
- Installation Environment: On The Main Hardware
- Other info: Laptop variant is ROG Zephyrus G14 (2021)

**Comment by kRHYME7** [comment]
Got this issue too. can you share what is the output of pulseaudio command the one that pops up the GUI

**Comment by kRHYME7** [comment]
Try to downgrade one of them and see which fixes it.

**Comment by oven8** [comment]
> Got this issue too. can you share what is the output of pulseaudio command the one that pops up the GUI

I don't think there was any pulseaudio command (for terminal) that would open the GUI. The easyeffects command gives the following:

`fish: Job 1, 'easyeffects' terminated by signal SIGSEGV (Address boundary error)`

Another thing is when I run easyeffects in the background things seem to work although the GUI still doesn't open up. I used the command `easyeffects --gapplication-service`.

> Try to downgrade one of them and see which fixes it.

I tried downgrading to version 1.23 (both) but the problem still seems to persist. At this point I'm not even sure if its a pipewire issue or something else (might as well be related to the new hyprland update).

**Comment by sitolam** [comment]
I have this issue since today too.

**Comment by chaitanya-p23** [comment]
I attempted to launch Waybar from the terminal, but encountered this error when trying to open the GUI by clicking the audio or speaker icon.

`Failed to register: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Remote peer disconnected`

**Comment by kRHYME7** [comment]
My bad it's the `pavucontrol` command.

**Comment by kRHYME7** [comment]
You all are on the official 0.43.0 release?

**Comment by kRHYME7** [comment]
Already fixed upstream. I don't know, though, what fixed it.

**Comment by born2ngopi** [comment]
hi @kRHYME7 , i have some issue when launch `pavucontrol`

``` bash
$ pavucontrol
Failed to register: Timeout was reached
```
hyprctl version
``` bash
$ hyprctl version
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2


flags: (if any)
```

do you have any idea?

**Comment by kRHYME7** [comment]
You already updated your system? Can you try to clean build pavucontrol?
