### ISSUE TITLE
Suspend option by default

### ISSUE THREAD

**Issue by DeividReinkeSchiitz** [prasanthrangan/hyprdots#188]
I think a option to suspend by default should exist, by default if possible.
`exec-once = swayidle -w timeout 600 'hyprctl dispatch dpms off' timeout 900 'systemctl suspend' resume 'hyprctl dispatch dpms on' # turn off monitor after 10 mins and suspend after 15mins
`

**Comment by Gedankenn** [comment]
pleaseeeee, nooooo. i have a vm, if it suspend my entire vm is shutdown hehehehe.,

**Comment by prasanthrangan** [comment]
> I think a option to suspend by default should exist, by default if possible.

I had this enabled by default before, but some users were facing issues with swayidle not waking up the system again... so I've removed it

**Comment by DeividReinkeSchiitz** [comment]
Ok, no problem. Thanks for reply
