### ISSUE TITLE
[Feature Request]: Switch to a maintained zsh prompt

### ISSUE THREAD

**Issue by fesowowako** [prasanthrangan/hyprdots#1880]
### Description

I reckon it would be wiser to opt for a more actively maintained prompt for zsh, such as Oh My Posh or Starship. Powerlevel10k is no longer maintained, and it's likely to develop bugs soon without any fixes in sight. In my view, switching to a more reliable option like Oh My Posh or Starship is the way to go. However, I believe Oh My Posh has the upper hand, as it offers a transient prompt feature that Starship lacks on zsh. If the maintainer of these dotfiles is in agreement, I can easily submit a pull request that mirrors the aesthetic of the current Powerlevel10k across whichever prompt the maintainer prefers.

**Comment by kRHYME7** [comment]
try a PR. And let's move the discussion in there.
