### ISSUE TITLE
[Bug]: Frozen "Wrong" screen on waking up after sleep/suspend

### ISSUE THREAD

**Issue by way2me** [prasanthrangan/hyprdots#1884]
### Description

I have noticed it twice that when I wake up system from sleep state, it lands me on a screen with encircled "Wrong" message. Remember, I have not yet entered any password. It does not happen always but yes after 3-4 suspension, I am noticing it reccuring.

I don't know how to recover from it, except doing a restart and that cause loss of unsaved work.

Can you please help me with any workaround until it is not fixed?

### Steps to Reproduce

1. It happens randomly right after after system wakes up. I am using multiple screens.

### Expected Behavior

It should land me on lock screen.

### Actual Behavior

It is frozen screen with "wrong" message

### Screenshots

![IMG_20240924_164631973](https://github.com/user-attachments/assets/c88bacfd-39d0-4f73-bde9-9fadd2cab83a)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]: Arch
- Linux Version, output of `uname -a`: 
> Linux mysystem 6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`:
> Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
> Host
- Other info: [e.g., Display Resolution, Resolution, etc] 
> Dual monitors with QHD and FHD resp.

**Comment by way2me** [comment]
@kRHYME7 Isn't it a bug because swaylock was installed by default and it is demoed in the README too?

**Comment by kRHYME7** [comment]
Yup yup, Still we can't do anything about their bug. Sure will be moving to hyprlock soon.

What idle daemon are you using BTW? the swayidle one?

**Comment by way2me** [comment]
> Yup yup, Still we can't do anything about their bug. Sure will be moving to hyprlock soon.
> 
> What idle daemon are you using BTW? the swayidle one?

I don't know, it is all default. I couldn't find swayidle running or any "idle" in the ps log
