### ISSUE TITLE
[Bug]: Volume control cannot overamplify

### ISSUE THREAD

**Issue by ffrancesco94** [prasanthrangan/hyprdots#1893]
### Description

I have kind of weak speakers on my laptop and I usually need to set the volume above 100% (overamplify) through pavucontrol. I would like to be able to do it through the keybind, but when I use it, the volume is capped at 100%. Moreover, if I leave it above 100%, whether I try to increase it or decrease it, it goes back to 100%. Must be this number hardcoded somewhere

### Steps to Reproduce

1. Try to increase volume
2. Observe it not increasing above 100%
3. If done it through pavucontrol, it goes back to 100% no matter what I press.

### Expected Behavior

Volume bar can cycle below and above 100%.

### Actual Behavior

The bar is capped at 100%.

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: Arch
- Linux Version, output of `uname -a`: 6.11
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: Bare metal
- Other info: [e.g., Display Resolution, Resolution, etc]

**Comment by kRHYME7** [comment]
Try to set your max volume using pavucontrol  which is already installed on your device
