### ISSUE TITLE
[Custom]: Issue with F10, F11, and F12 Key Mapping in Hyprland for Neovim Debugging

### ISSUE THREAD

**Issue by sharjeelmazhar** [prasanthrangan/hyprdots#1899]
I am using Hyperland on Arch Linux as my desktop environment, with Wayland as the display server. My configuration is set up using hyprdots, which relies on hyprland in the backend.

I have configured Neovim for Python development, and I am experiencing issues with using the function keys for debugging. While the F5 key works perfectly fine for starting the debugging session, the other keys—F10, F11, and F12—do not work. After some trial and error, I discovered that pressing Caps Lock along with these function keys (e.g., Caps Lock + F10) allows them to work correctly.

However, this workaround is inconvenient. Having to use Caps Lock interferes with my keybindings in Neovim, and if Caps Lock is accidentally left on, it disrupts my workflow. I do not need the function keys to be mapped to system controls like volume or mute, so I am open to remapping these functions.

Expected Behavior:
I want to use F10, F11, and F12 directly for debugging in Neovim without needing to use the Caps Lock key.

Steps to Reproduce:

Set up hyprland with the hyprdots configuration.
Set up Neovim for Python development.
Attempt to use F10, F11, and F12 in Neovim for debugging.
Current Workaround:
Press Caps Lock + F10, F11, or F12 to use the debugging shortcuts in Neovim.

Proposed Solution:

Is there a way to remap F10, F11, and F12 in hyprland so they are directly available for use in Neovim without requiring the Caps Lock key?
Can the volume control, mute, or other functionalities currently mapped to these keys be moved to Caps Lock + Function key combinations instead?
Any help or guidance on how to modify the key mappings in hyprland or the hyprdots configuration would be greatly appreciated.

Thank you!

**Comment by kRHYME7** [comment]
1. yes
2. yes 

Change it here
![image](https://github.com/user-attachments/assets/fc151b9c-091d-491a-9336-b679887a7ac4)


As for rebinding, check this and the faq section
https://wiki.hyprland.org/Configuring/Binds/
