### ISSUE TITLE
Border from waybar tooltip

### ISSUE THREAD

**Issue by DeividReinkeSchiitz** [prasanthrangan/hyprdots#190]
The text hitting the border is really annoying, its not a big change but small change make a lot of difference in the system:
![image](https://github.com/prasanthrangan/hyprdots/assets/55961826/f8c930c6-ec9f-4602-bb1f-69602bb9bc55)

 After setting a static border radius in i set it to 8px, but 5px is also great: 
![image](https://github.com/prasanthrangan/hyprdots/assets/55961826/fe919f2b-b564-40a3-8cd9-6ffac05f97dc)
![image](https://github.com/prasanthrangan/hyprdots/assets/55961826/f66d7eb7-3ec6-45fe-88da-806d5e1a2d0b)

**Comment by prasanthrangan** [comment]
hmmm, don't remember the variable, but I think I used the same variable as module border radius.
so let me check and fix it!

**Comment by Balssh** [comment]
To add to this, when hovering over an element from waybar there is a rectangle around the rounded corners of the tooltip (seen this in Tokyo-Night theme). Can't SS it apparently, but if needed I can make a photo with my phone.

**Comment by DeividReinkeSchiitz** [comment]
Exactly @prasanthrangan. By the way, thanks for the project, its getting really great!

**Comment by DeividReinkeSchiitz** [comment]
@Balssh, I think i know what are you talking about, not also in Tokyo-Night, but in Sakura too. 
![image](https://github.com/prasanthrangan/hyprdots/assets/55961826/8f663a2d-f2ce-4539-bf1c-fa0c1a588665)
![image](https://github.com/prasanthrangan/hyprdots/assets/55961826/b1c9f646-7e81-43ce-8f77-0e1b9c6f4afb)

**Comment by prasanthrangan** [comment]
> The text hitting the border is really annoying, its not a big change but small change make a lot of difference in the system:

This should be fixed now!

**Comment by TheyCallMeSecond** [comment]
its back on Tokyo-Night, Material-Sakura and Gruvbox

**Comment by TurtleMeds** [comment]
Is there any more updates on this?

**Comment by kRHYME7** [comment]
Have this on gruvbox, https://github.com/prasanthrangan/hyprdots/discussions/1001

**Comment by kRHYME7** [comment]
Hi, as we are moving the themes now to a different repo I will be closing this. 

If this is a specific theme issue, please navigate your way to that specific theme. 
Here's the list of themes available that is Hyde compatible. 
https://github.com/kRHYME7/hyde-gallery
https://github.com/prasanthrangan/hyde-themes
