### ISSUE TITLE
[Bug]: Multi GPU issue + DKMS issue

### ISSUE THREAD

**Issue by mmrmagno** [prasanthrangan/hyprdots#1901]
### Description

After an nvidia dkms update when I try to login I get stuck in a black screen. If I change the monitor resolutions to ``` Preferred,auto,auto ``` it works I'm able to login but the resolution gets put to 1280x1040 @ 60 Hz (My monitor is a 2560x1600 @ 240 Hz) I tried downgrading the dkms to no success (the same issues persisted). when I try changing the resolutions to 2560x1600 @ 60 I'm able to login but everything is super glitchy  and unusable. 

I've gotten to some state where it shows each gpu on as a "different" monitor:

```
❯ hyprctl monitors
Monitor Unknown-1 (ID 0):
	1280x1024@60.00000 at 0x0
	description: 
	make: 
	model: 
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 32 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: A XRGB8888 H XRGB8888
	availableModes: 1280x1024@60.00Hz 

Monitor eDP-1 (ID 1):
	2560x1600@60.00200 at 1280x0
	description: BOE NE160QDM-NZ5
	make: BOE
	model: NE160QDM-NZ5
	serial: 
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 31 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: A XRGB8888 H XRGB8888
	availableModes: 2560x1600@60.00Hz 2560x1600@240.00Hz 
```

and it considers the lower res one as primary, If I some how manage to change that to the second monitor which can go to 2560x1600@240Hz it would fix my issue I guess?

### Steps to Reproduce

1. update dkms
2. login
3. blackscreen

### Expected Behavior

To be able to login and use Hyprland without any issues on the right resolution and frequency.

### Actual Behavior

Only able to use it on the wrong resolution and frequency

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: ```bash Linux bready 6.11.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 30 Sep 2024 23:49:50 +0000 x86_64 GNU/Linux ```
- Hyprland Version, output of `hyprctl version`: ```bash Linux bready 6.11.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 30 Sep 2024 23:49:50 +0000 x86_64 GNU/Linux ```
- Installation Environment: Asus ROG Strix G16 
```
                                           OS : Arch Linux x86_64
                                           Kernel : Linux 6.11.1-arch1-1
                                           Packages : 1057 (pacman), 7 (flatp)
                                           Display : 2560x1600 @ 60 Hz in 16″]
                                           Display : 1280x1024 @ 60 Hz in 17″
                                           WM : Hyprland (Wayland)
                                           Terminal : kitty 0.36.4

                                           CPU : 13th Gen Intel(R) Core(TM) iX
                                           GPU : GeForce RTX 4060 Max-Q / Mobe
                                           GPU : Raptor Lake-S UHD Graphics
                                           GPU Driver : nvidia (proprietary) 3
                                           GPU Driver : i915
                                           Memory : 3.09 GiB / 30.97 GiB (10%)
                                           OS Age  : 0 days
                                           Uptime  : 21 mins
```

**Comment by kRHYME7** [comment]
please report on the upstream hyprland repo. I advice to try the latest hyprland-git first

**Comment by mmrmagno** [comment]
Thx will do!
