### ISSUE TITLE
[Bug]: Dolphin has a weird white background color and no matter what theme i use it refuses to change

### ISSUE THREAD

**Issue by midosaid28** [prasanthrangan/hyprdots#1908]
![241006_18h25m31s_screenshot.png](https://github.com/user-attachments/assets/f3f900e2-517f-478a-a4cc-3972fc10f309)

Any help would be appreciated

**Comment by kRHYME7** [comment]
` cat ~/.config/kdeglobals ` ???

**Comment by midosaid28** [comment]
> ` cat ~/.config/kdeglobals ` ??? 
> 
> Do you happen to have kde installed? 

Output of cat:

[General]
TerminalApplication=kitty

[Icons]
Theme=Tela-circle-dracula

I do have KDE installed

**Comment by kRHYME7** [comment]
This is dup https://github.com/prasanthrangan/hyprdots/issues/1843

Please follow this thread. We don't have fixes yet

**Comment by midosaid28** [comment]
> ` cat ~/.config/kdeglobals ` ??? 
> 
> Do you happen to have kde installed? 

Solved: i just added
```
[Colors:View]
BackgroundNormal=#20212d
```
To ~/.config/kdeglobals
And it's normal now
![241006_18h46m36s_screenshot.png](https://github.com/user-attachments/assets/4c98ed31-eaa7-4c48-90bc-e3bc0b9cfcb2)

**Comment by midosaid28** [comment]
> This is dup https://github.com/prasanthrangan/hyprdots/issues/1843
> 
> Please follow this thread. We don't have fixes yet

Maybe we can add an echo command to the kdeglobals file in the install script of the specific theme color y'all use.
It seems to be working for me for now.

**Comment by kRHYME7** [comment]
Thanks for confirming this. Some versions of  (we do not know dolphin/Qt/kde/  ) are messy. Will wait for it to be stable and maybe have a proper way to theme it again. 

If someone can find any docs that pointed how to theme kdeglobals then we will try to do it.

**Comment by TheXro** [comment]
> > `cat ~/.config/kdeglobals` ???
> > Do you happen to have kde installed?
> 
> Solved: i just added
> 
> ```
> [Colors:View]
> BackgroundNormal=#20212d
> ```
> 
> To ~/.config/kdeglobals And it's normal now ![241006_18h46m36s_screenshot.png](https://private-user-images.githubusercontent.com/42911325/373960126-4c98ed31-eaa7-4c48-90bc-e3bc0b9cfcb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NTI3MDYsIm5iZiI6MTczMjQ1MjQwNiwicGF0aCI6Ii80MjkxMTMyNS8zNzM5NjAxMjYtNGM5OGVkMzEtZWFhNy00YzQ4LTkwYmMtZTNiYzBiOWNmY2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDEyNDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZTA0MzM0OGYxYzYzODFjN2E2NzM5ZjM0Yjg2OWRkNmMxM2E1YTA1NmJiYjQyMTA3MDdiMWVjMGJlMWJmNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UBnDSzpo5vxg18GWtcZQQxP9GnVyvgfnudZvyY54990)

Instead of using a color just use transparent and it will work on every theme.
 ```
[Colors:View]
BackgroundNormal=#00000000
```

**Comment by kRHYME7** [comment]
or any character.

as long as it's not blank


ColorScheme=*
