### ISSUE TITLE
how to set wallpaper only for 2nd monitor

### ISSUE THREAD

**Issue by machucyst** [prasanthrangan/hyprdots#1909]
just like the title states.

im aware of wallAddCustomPath= in hyde.conf that lets me add the wallpapers i want but can i do that for specific monitors only?

**Comment by kRHYME7** [comment]
Using ` swww img ` command to set  

![image](https://github.com/user-attachments/assets/7733b7ce-6f94-4273-af44-f76fe184b369)


We are using ` swwww ` here, so use its command line to handle wallpapers
