### ISSUE TITLE
[Bug]: Cannot paste text from Google Chrome to VSCode

### ISSUE THREAD

**Issue by sharjeelmazhar** [prasanthrangan/hyprdots#1914]
### Description

I am experiencing an issue where I cannot paste text copied from Google Chrome into VSCode on Arch Linux with Hyprland. The pasting functionality works fine between other applications (e.g., Zed Editor, Firefox, Terminal), but specifically fails with text copied from Google Chrome to VSCode. The only workaround I found is using the clipboard manager (triggered by Win/Mod + V) to manually select and then paste the text using Ctrl + V, which is not required with any other applications.

### Steps to Reproduce

1. Copy any text from Google Chrome.
2. Attempt to paste directly into VSCode using Ctrl + V.
3. Observe that the paste operation does not work.
4. Press Win/Mod + V to open the clipboard manager and select the recently copied text.
5. Press Enter, then use Ctrl + V to paste into VSCode, which then works.

### Expected Behavior

I expected to paste text directly from Google Chrome into VSCode using the standard Ctrl + V shortcut without additional steps.

### Actual Behavior

Text copied from Google Chrome cannot be pasted directly into VSCode using Ctrl + V. It requires an additional step involving the clipboard manager to manually select the text for pasting.

### Environment

- Linux Distro: Arch Linux
- Linux Version, output of `uname -a`: Linux arch 6.6.54-1-lts
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch  at commit 0c7a7e2d569eeed9d6025f3eef4ea0690d90845d  (version: bump to 0.44.0).
Date: Sun Oct 6 11:04:13 2024
Tag: v0.44.0, commits: 5299
built against aquamarine 0.4.1
- Installation Environment: On the main hardware

### Additional Information

This issue only appears when copying from Google Chrome; other applications do not exhibit this problem. It affects workflow efficiency significantly, especially when working with code and web content simultaneously. No recent changes were made to the system or VSCode that might have caused this issue.

**Comment by kRHYME7** [comment]
yeah

**Comment by sharjeelmazhar** [comment]
> yeah

what the fix?

**Comment by kRHYME7** [comment]
> what the fix?

This issue on VS Code occurred months ago. I never experience this back then as I'm using vscodium. 
Fast-forward, I experienced this after a couple of updates from vscoidum. I don't know the fix, either. 

It is wise to ask for help to the repos responsible for this . 

https://github.com/sentriz/cliphist   - Stores the text/image
https://github.com/bugaevc/wl-clipboard - Service that storesthe copied files to cliphist
https://code.visualstudio.com/ - This too
https://github.com/hyprwm/Hyprland - Just in case


As you and I observed, it gets copied to the clipboard but when you try to paste it suddenly it won't paste

**Comment by kRHYME7** [comment]
>  but specifically fails with text copied from Google Chrome to VSCode. T

Happens ALL the time?

**Comment by kRHYME7** [comment]
to query if google chrome is on Xwayland, 


run ` hyprctl clients ` 
![image](https://github.com/user-attachments/assets/b7e0cf53-6661-4352-8c44-492c53a71cad)


This says that I am not running google-chrome as Xwayland which fixes the above issue.

**Comment by Naimul007A** [comment]
> > but specifically fails with text copied from Google Chrome to VSCode. T
> 
> Happens ALL the time?
> 
> If yes, then be sure to run Google Chrome as Wayland.
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/375366349-3006d80a-72d7-4391-9638-80eaf1505137.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDEyNDMsIm5iZiI6MTczMTQwMDk0MywicGF0aCI6Ii81MzQxNzQ0My8zNzUzNjYzNDktMzAwNmQ4MGEtNzJkNy00MzkxLTk2MzgtODBlYWYxNTA1MTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA4NDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3OThkMjRjMGQ1YTZmOGY3YjlkMjk4YjdjYjM2ZTk2ZGRhZjcyZWNhYzNmMTQ4YmUwYWM0MDUxZTEwOTU5MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z5tEOBgBDZtn7oBkafP7reg8XJtiXNaBX9wPRbRYOLg)
> 
> By default, chrome is launch as xwayland thus giving you this error
> 
> Another method that works for arch is this https://wiki.archlinux.org/title/Chromium#Making_flags_persistent

It's work for me.But i face another problem when i select wayland ,My 
fcitx5  not working this time .What should i do  ?

**Comment by kRHYME7** [comment]
Search online, there are alternatives or ways to use that input method in Wayland

**Comment by kRHYME7** [comment]
https://github.com/hyprwm/Hyprland/discussions/421
