### ISSUE TITLE
不能叫出终端模拟器

### ISSUE THREAD

**Issue by wanqiu2004** [prasanthrangan/hyprdots#1916]
### Description

[Provide a clear and concise description of the bug.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by wanqiu2004** [comment]
我的终端模拟器是Kitty

**Comment by wanqiu2004** [comment]
super+a 直接点击图标也没用

**Comment by wanqiu2004** [comment]
我使用终端模拟器的foot可以正常打开

**Comment by abenezerw** [comment]
你有安装了Kitty吗？ 然后方便看一下你的这个文件 /.config/hypr/keybindings.conf

**Comment by abenezerw** [comment]
> 你有安装了Kitty吗？ 然后方便看一下你的这个文件 /.config/hypr/keybindings.conf

@wanqiu2004

**Comment by kRHYME7** [comment]
BTW if it's a VM check if kitty can actually launch in there. I guess kitty needs 3d acceleration

**Comment by thyeun** [comment]
@wanqiu2004  

1. 如果你使用這個repos ```super + t``` 才能喚出kitty。
