### ISSUE TITLE
Wanna skip NVIDIA Driver part

### ISSUE THREAD

**Issue by Shaakey** [prasanthrangan/hyprdots#1917]
Hello, I have a GT 730 (outdated GPU) and I wanna ask, is there some way to just skip the Nvidia driver gpu part entirely? thanks!

**Comment by kRHYME7** [comment]
Yes, use ` Hyde-install` it will ask you to skip nvidia flag. 

https://github.com/HyDE-Project/Hyde-cli


Or if you understand bash script head to the ./Scripst dir, then go to the `/globalcontrol.sh ` find the nvidia part in there and make them return a 1 value to always reject nvidia checks
