### ISSUE TITLE
[Bug]: Frame drops when moving the mouse.

### ISSUE THREAD

**Issue by CaioSimioni** [prasanthrangan/hyprdots#1919]
### Description
Frame drops when moving the mouse.

When the mouse is still, nothing happens, but when I move the mouse, the frames drop, but after 2 seconds the frames return to normal.

Using the system, I noticed that when I'm using OBS-Studio, the problem doesn't happen, nor when I'm playing CS2. But when I play Path of Exile without OBS turned on, it's impossible to play due to the frame drops.

I believe it's something related to the GPU or some video driver, but I don't have the knowledge to solve the problem.

The problem started recently, a week ago, when I updated my arch linux. :(

### Environment

System:
  Kernel: 6.11.3-arch1-1 arch: x86_64 bits: 64
  Desktop: Hyprland v: 0.44.1 Distro: Arch Linux
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: PRIME B550M-A v: Rev X.0x
CPU:
  Info: 6-core model: AMD Ryzen 5 5600 bits: 64 type: MT MCP cache: L2: 3 MiB
Graphics:
  Device-1: NVIDIA GA106 [GeForce RTX 3060 Lite Hash Rate] driver: nvidia
    v: 560.35.03
  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 24.1.2
    compositor: Hyprland v: 0.44.1 driver: X: loaded: nvidia
    unloaded: modesetting gpu: nvidia,nvidia-nvswitch
    resolution: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: nvidia,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 560.35.03
    renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2

### Note

[Normal View](https://youtu.be/LugRjJADvdE)
[OBS View](https://youtu.be/KvoFahzF9_w)

I am totally free to try to solve this problem, please help me.

**Comment by kRHYME7** [comment]
Hi @CaioSimioni  Please open this up to Hyprland repo we can't help you here.

You can also try to Install the latest commits of hyprland `hyprland-git` and check if it is already fixed upstream.

**Comment by CaioSimioni** [comment]
Thanks for the suggestion. I found the problem in an issue in the hyprland repository that fixed the issue.

https://github.com/hyprwm/Hyprland/issues/8036

**Comment by CaioSimioni** [comment]
> Hi @CaioSimioni Please open this up to Hyprland repo we can't help you here.
> 
> You can also try to Install the latest commits of hyprland `hyprland-git` and check if it is already fixed upstream.
> 
> `yay -Sy hyprland-git ` the reboot

It was not necessary to install the hyprland-git version.

I just add the following code in ~/.config/hypr/hyprland.conf file next to the inputs

```
cursor {
   no_hardware_cursors = true
}
```
