### ISSUE TITLE
[Bug]: when using alacritty, waybar icon is missing

### ISSUE THREAD

**Issue by ZongBen** [prasanthrangan/hyprdots#1925]
## Icon missing

When using Kitty, there is a kitty taskbar icon, 
but when I default my terminal to Alacritty, there is no icon. 
Is there a configuration I can set, or does it simply not work?

![圖片](https://github.com/user-attachments/assets/0dcd999a-32c4-4308-901a-ab290a27bbb3)

**Comment by kRHYME7** [comment]
Try this ` gtk-update-icon-cache -f -t ~/.icons/ `

Or these commands 
 ![image](https://github.com/user-attachments/assets/2923c337-e05c-4cef-ba6a-28c75f1fed09)
1. Get the current Icon Theme
2. run `gtk-update-icon-cache -f -t /path/to/icons `

**Comment by ZongBen** [comment]
thx for helping
