### ISSUE TITLE
[Bug]: vscode doesn't scale properly 

### ISSUE THREAD

**Issue by Zardexd** [prasanthrangan/hyprdots#1926]
### Description 
Doesn't scale properly on second monitor. It scales the window, not the image of it, so the empty areas are responding to clicks etc. 
![image](https://github.com/user-attachments/assets/a9f75c10-2844-497a-8eef-32cd665f8fa2)

### Steps to Reproduce
Go to hyprland.conf, scale down the monitor. 

### Expected Behavior
Scaling like any other window.
### Actual Behavior
Doesn't scale the image.

### Environment
![image](https://github.com/user-attachments/assets/fba36652-82a7-408c-84e1-7aecb0ed5978)

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,
- `Linux archlinux 6.11.3-lqx1-1-lqx #1 ZEN SMP PREEMPT Thu, 10 Oct 2024 14:22:48 +0000 x86_64 GNU/Linux`
- ```Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
  Date: Wed Oct 9 12:54:39 2024
  Tag: v0.44.1, commits: 5309 , built against aquamarine 0.4.2```
- `Installation Environment: Laptop`

_In hyprdots.conf_

```
xwayland {
    force_zero_scaling = true
} 
```
False or True , doesn't affect the outcome. 

Might be affected by #1315 , will fix and check soon.

**Comment by kRHYME7** [comment]
Send screenshot of vscode after you run this `  code --ozone-platform=wayland --ozone-platform-hint=auto `  **Note** you should kill other vscode instances. 

Also check if your vscode is actually running over "xwayland". ` hyprctl clients `  vscode should return false under xwayand

![image](https://github.com/user-attachments/assets/0631e8dd-ec29-48cf-8dc4-5b1f821550d6)

**Comment by Zardexd** [comment]
Yea, that was the first thing i wanted to test, just a bit in a hurry, i'll check in like 5-10min

**Comment by Zardexd** [comment]
> Send screenshot of vscode after you run this ` code --ozone-platform=wayland --ozone-platform-hint=auto` **Note** you should kill other vscode instances.
> 
> Also check if your vscode is actually running over "xwayland". `hyprctl clients` vscode should return false under xwayand
![image](https://github.com/user-attachments/assets/511a1b6f-ef08-45f3-b842-5a3c9969c3b0)
![image](https://github.com/user-attachments/assets/edd2ad51-9e49-41d2-901e-43178eeaf904)

Might be something with the way i configured displays, it's totally normal when i move it to my second display.

**Comment by kRHYME7** [comment]
I think It's the monitor. Try to reboot first then check. 

 Check if it's a monitor issue or the specific application.

**Comment by Zardexd** [comment]
> I think It's the monitor. Try to reboot first then check.
No just vscode. Also being blurry only when re-scaled, so for sure not monitor.

**Comment by kRHYME7** [comment]
Try to install hyprland-git and confirm if the issue is not being fixed yet.

**Comment by Zardexd** [comment]
> yow still an issue? 
> 

I would need to check again, haven't taken a look since I last updated.

**Comment by Zardexd** [comment]
Sorry for the delay, i totally forgot. Yes, i cant reproduce the bug anymore. The little blurriness that appears when i scale things down are still there, but i think it has nothing to do with that, and should be just a fractional scaling issue.
