### ISSUE TITLE
[Bug]: Vs code not working properly

### ISSUE THREAD

**Issue by tushar-agarwal7** [prasanthrangan/hyprdots#1928]
### Description

I installed vscode by paru -S visual-studio-code-bin but when i try to paste some code in vscode it is not working

### Expected Behavior

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by kRHYME7** [comment]
yeah, have you tried searching for similar issues first?
