### ISSUE TITLE
[Bug]: Partial Screenshot utility has grimblast utility components shown in it

### ISSUE THREAD

**Issue by YuanziX** [prasanthrangan/hyprdots#1929]
### Description

When I take a partial screenshot using the keybind (Meta + P) or (Meta + Ctrl + P), the ui of the screenshot utility shows in the resultant screenshot.

### Steps to Reproduce

1. Initiate partial screenshot using keybind (Meta + P or Meta + Ctrl + P)
2. Make selection

### Expected Behavior

Clear screenshot with only the selected area being shown in it.

### Actual Behavior

Screenshot utility (and cursor, sometimes) shows in the captured image.

### Screenshots

Screenshot of bug / actual behavior (the black line and then translucent white color at bottom)
![image](https://github.com/user-attachments/assets/0f831b50-0a88-40c8-a948-4c360b3f8dfa)
![image](https://github.com/user-attachments/assets/7c59be43-329e-463f-9e33-c6e3b2698d72)
![image](https://github.com/user-attachments/assets/88356d0d-85c2-4914-97df-47935547854f)

Full display screenshot for reference
![image](https://github.com/user-attachments/assets/862b1dc2-2e13-4f20-b8e9-21e726578af4)

### Environment
- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux kit 6.11.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 10 Oct 2024 20:11:06 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland 0.44.0 built from branch main at commit 01c2ff34ddcb5995409c33c2b549e93b98b56d6b  (layout: simplify the conditions to autogroup (8120)).
Date: Tue Oct 15 00:01:17 2024
Tag: v0.44.0-44-g01c2ff34, commits: 5343
built against aquamarine 0.4.3
flags set:
debug
- Installation Environment: On The Main Hardware

**Comment by YuanziX** [comment]
welp, this is not there after reflashing my system. can't reproduce either so closing.

**Comment by YuanziX** [comment]
Got the issue again, and found a fix for it this time. Removing animations from selection fixes this issue. so the layerrule ```layerrule = noanim, selection``` works.

Before:
![image](https://github.com/user-attachments/assets/86429f00-e051-46f5-8663-82e73fdcf871)
After:
![image](https://github.com/user-attachments/assets/5a5fa8bf-fcb8-4201-b332-bc1e89cbe269)

**Comment by kRHYME7** [comment]
This is a grimblast issue. But we can add the fixes on our script, though it might be redundant.

**Comment by YuanziX** [comment]
> This is a grimblast issue. But we can add the fixes on our script, though it might be redundant.

does hyprshot wrap around grimblast? because i had this issue in that also.

**Comment by kRHYME7** [comment]
the layer "selection" is from `slurp` .  which is used for almost anything to get geometry., used by grimblast and hyprshot.  (The transparent layer you see when doing a screenshot ) 

I don't have this issues. 

But if disabling the animation for the layer "selection", feel free to open a PR I will merge it. We don't really need any animation for this tool.
