### ISSUE TITLE
[Bug]: Cant install the last AUR packages, failed to get

### ISSUE THREAD

**Issue by gltchii** [prasanthrangan/hyprdots#1930]
## Bug Report

When running the install.sh command, at the very end, a few packages fail to install

### Steps to Reproduce

1. Use arch+sddm+hyprland+ml4w+virtualbox
2. Clone the repo
3. Run the install.sh command

### Expected Behavior

the install script works without failing on these packages

### Actual Behavior

Error: Failed to install the following packages. Manual intervention is required:
hyde-cli-git - exit status 10
zsh-theme-powerlevel10k-git - exit status 10
pokemon-colorscripts-git - exit status 10
oh-my-zsh-git - exit status 10
grimblast-git - exit status 10
swaylock-effects-git - exit status 10

### Screenshots

![Screenshot 2024-10-16 120934](https://github.com/user-attachments/assets/5749dc37-6642-479b-9d0d-f9a15c4c757e)

### Environment

The issue also occurs when doing this via yay and pacman manually, without the install script.

e.g.,

- Linux Distro: Arch Linux (base)
- Linux Version: Linux archlinux 6.11.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 10 Oct 2024 20:11:06 +0000 x86_64 GNU/Linux
- Hyprland Version: Hyprland, built from branch at commit 4520b30d498daca8079365bdb909a8dea38e8d55 (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2
- Installation Environment: On a VM, but the VM hasn't caused any other issues before.
- Other info: 1920x1080, 60 HZ

### Additional Information

No changes were made, no strange behavior before the error.

**Comment by tryprncp** [comment]
those are AUR packages and not core packages. they're a bit hard to install if you have unstable internet connection

**Comment by gltchii** [comment]
my internet is pretty good so Im not sure how that would affect it

**Comment by kRHYME7** [comment]
can you try to install the `hyde-cli-git` first and send SS of the errors.

**Comment by Hello-world150** [comment]
You can trust this key`F9F9FA97A403F63E` locally like this`pacman-key --lsign-key F9F9FA97A403F63E`,it will be useful

**Comment by Hello-world150** [comment]
You can trust this key`F9F9FA97A403F63E` locally like this`pacman-key --lsign-key F9F9FA97A403F63E`,it will be useful

**Comment by gltchii** [comment]
thanks that fixed it

**Comment by gltchii** [comment]
that fixed it thanks

**Comment by gltchii** [comment]
++: turns out arch doesnt like signing that key, my fix was installing the non latest git commit version via AUR. Strange tbh

**Comment by kRHYME7** [comment]
` yay -Sy archlinux-keyring`
