### ISSUE TITLE
Question what fonts are being used for the waybar icons?

### ISSUE THREAD

**Issue by ShadowReaper420** [prasanthrangan/hyprdots#1936]
I couldn't find them listed anywhere.

**Comment by ShinniUwU** [comment]
Based on my observations in the [Waybar style configuration](https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/waybar/style.css) from the repository, it seems that **JetBrains Mono Nerd Font** might be a suitable choice for the font configuration. However, I recommend waiting for someone with more in-depth knowledge of the repo to provide confirmation. In the meantime, it could be worthwhile to experiment with **JetBrains Mono Nerd Font** to see if it meets your needs.

**Comment by kRHYME7** [comment]
JetBrainsMono Nerd Font
![image](https://github.com/user-attachments/assets/58cecc9a-99a2-47e9-aab7-99205d5b1af5)

You can modify it in the modules then regen the waybar configuration by running `wbarconfgen.sh ` 
Take note that ` ~/.config/waybar/style.css ` is auto generated so edit things in modules

![image](https://github.com/user-attachments/assets/45840bb8-3974-45ef-b139-2ce9b2a657bb)
