### ISSUE TITLE
[Bug]: VS code does not remember recently opened projects

### ISSUE THREAD

**Issue by YuanziX** [prasanthrangan/hyprdots#1937]
### Description
The 'open recent'  tab in vscode does not remember the last opened projects

### Expected Behavior
recently opened folders show up in the list to be selected by the user

### Actual Behavior
empty list found

### Additional Information
I seem to have found the "fix" to this issue as well, the issue is caused by the ```--extensionDevelopmentPath=$HOME/.vscode-oss/extensions/undefined_publisher.wallbash-0.0.1``` flag passed to vscode using code-flags config file. After the removal to this flag the bug was gone. and it worked as normal.

**Comment by YuanziX** [comment]
Also found this issue caused by the flag, if you have the flag then you can't open multiple instances of code without using the new window shortcut from inside code itself.

For ex, if I have set the keybind to launch code to ```Ctrl + C``` then if i press it multiple times nothing happens (it only opens once)

without the flag it opens multiple times as it does normally.

**Comment by Andrjs** [comment]
This fix works for me.
Thanks a lot.

**Comment by kRHYME7** [comment]
Can you guys do a Pr regarding this

**Comment by YuanziX** [comment]
#1938  created the pull request, please review and merge.
