### ISSUE TITLE
[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by AeonShai** [prasanthrangan/hyprdots#1940]
### Description

Hyprland, Tigerlake high usage. 

### Screenshots

![image](https://github.com/user-attachments/assets/505ca860-b86a-4b46-8e3f-755bc89b1e15)
![image](https://github.com/user-attachments/assets/0f883b8c-8666-4202-90a0-748ecb175c9f)

### Environment
- Linux Distro: Arch Linux
- Linux Version: Linux archlinux 6.11.5-arch1-1
- Hyprland Version:Hyprland 0.44.0
- Installation Environment: Main Hardwarre
- Other info: 
![image](https://github.com/user-attachments/assets/f2714887-c010-42e5-b8d7-c2d198f960d5)

### Additional Information

I have Discrete Graphics Mode on my laptop, but I don't know how to activate it in arch. I can activate it with the MSI app, which is only available in W11. 
I did a clean install because I had this problem before, but it still didn't solve my problem. I honestly have no idea why this is happening.
[hyprland.log](https://github.com/user-attachments/files/17527635/hyprland.log)

**Comment by AeonShai** [comment]
![image](https://github.com/user-attachments/assets/dfffa75e-d169-4eb9-bb8a-fe2d9e472d5b)
![image](https://github.com/user-attachments/assets/a7ad65cb-a819-44d1-ba3e-0f702d3f5563)
+I'm using dual boot, the other is W11. I'll switch to W11 and upload the hardware status.

**Comment by kRHYME7** [comment]
report this to the hyrpland repository

**Comment by AeonShai** [comment]
oops. sorry my bad.

**Comment by kRHYME7** [comment]
@AeonShai  Try this command though `Hyde power save on `

It disables The expensive stuff of hyprland.


But take note that there's a report about memory leak on nvidia leading to Hyprland consuming that amount of Ram
