### ISSUE TITLE
Bug: Cursor issue when looking around in game

### ISSUE THREAD

**Issue by CerasCTK** [prasanthrangan/hyprdots#195]
Can't use the mouse to look around in some games like: Minecraft, CS-GO,...

**Comment by T-Crypt** [comment]
@CerasCTK -- Have you used Super + Alt + G  to disable the hyprland effects for gaming? 

References: https://github.com/hyprwm/Hyprland/issues/2376

**Comment by CerasCTK** [comment]
I've tried using it but it doesn't work. I also tried switching to hyprland-nvidia or hyprland but seem it still doesn't work.

**Comment by CerasCTK** [comment]
I tried gamescope with Minecraft and I can't get into the game, this is the output when I use `gamescope minecraft-launcher` command.

[Minecraft gamescope output](https://hastebin.com/share/okusofigag.yaml)

**Comment by prasanthrangan** [comment]
strange that `xkbcomp` seems to cause it, i dont have csgo installed, but when i get time I'll install and try it!

**Comment by CerasCTK** [comment]
> strange that `xkbcomp` seems to cause it, i dont have csgo installed, but when i get time I'll install and try it!

So do you have a solution yet? You can try with [Minecraft online version](https://classic.minecraft.net/)

**Comment by prasanthrangan** [comment]
Hey, i tried CSGO and its working perfectly fine for me...

**Comment by CerasCTK** [comment]
> Hey, i tried CSGO and its working perfectly fine for me...

Can you show me all the packages you have installed?

**Comment by prasanthrangan** [comment]
Sure, here you go...

[pacman_list.txt](https://github.com/prasanthrangan/hyprdots/files/12708652/pacman_list.txt)

**Comment by kRHYME7** [comment]
It would be good to open a newer issue as lot have changes since posting this. Thank 🥂
