### ISSUE TITLE
Install.sh now terminates at zshrc step

### ISSUE THREAD

**Issue by iiTzSeb** [prasanthrangan/hyprdots#1952]
The packagebuild for zshrc is currently broken, so now the .install.sh is broken. May want to enable some kind of bypass that will just move on to the next step/package in the list if a prior package is unavailable/broken as selecting "[N]one"still seems to force you into parsing the broken package(s) then bombs out immediately after.

**Comment by iiTzSeb** [comment]
`patching file zshrc
Hunk #1 FAILED at 2.
1 out of 3 hunks FAILED -- saving rejects to file zshrc.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: oh-my-zsh-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
oh-my-zsh-git - exit status 4
[seb@arch Scripts]$ `

**Comment by akanyanu** [comment]
Same error

**Comment by iiTzSeb** [comment]
Joined the HyDE Discord and found the solution from Shabba:

Clone:

`git clone https://aur.archlinux.org/oh-my-zsh-git.git`

Change dir
`cd oh-my-zsh-git`

Edit pkgbuild
`nano PKGBUILD`


Under prepare() comment out the line `patch -p1 < "${srcdir}/0001-zshrc.patch"`

Save and exit
build with `makepkg -sfi`
