### ISSUE TITLE
Install.sh now terminates at zshrc step

### ISSUE THREAD

**Issue by akanyanu** [prasanthrangan/hyprdots#1953]
[Bug]: Short description of the issuepatching file zshrc Hunk #1 FAILED at 2. 1 out of 3 hunks FAILED -- saving rejects to file zshrc.rej ==> ERROR: A failure occurred in prepare(). Aborting... -> error making: oh-my-zsh-git-exit status 4 -> Failed to install the following packages. Manual intervention is required: oh-my-zsh-git - exit status 4 [seb@arch Scripts]$

**Comment by iiTzSeb** [comment]
Clone
`git clone https://aur.archlinux.org/oh-my-zsh-git.git`

Change dir
`cd oh-my-zsh-git`

Edit pkgbuild
`nano PKGBUILD`

Under prepare() comment out the line `patch -p1 < "${srcdir}/0001-zshrc.patch"`

Save and exit
`build with makepkg -sfi`

**Comment by shockpulse05** [comment]
After i do just like you said and i reboot there's no interface can you help me?

**Comment by ngocthien115** [comment]
> After i do just like you said and i reboot there's no interface can you help me?

@shockpulse05 you sure you not have error on progress, i had the same problem as you, installing, got an error, installed the package separately, and ran the `install.sh` command again, and boom, it's working

Or you can reinstall from scratch, including arch

I just installed it successfully 5 minutes ago after 2 days, follow vid from Ksk Royal

**Comment by kRHYME7** [comment]
Maybe sddm is not set yet? try `Hyde-install` or `Hyde sddm install`

**Comment by a-ww2-er** [comment]
> Clone
> `git clone https://aur.archlinux.org/oh-my-zsh-git.git`
> 
> Change dir
> `cd oh-my-zsh-git`
> 
> Edit pkgbuild
> `nano PKGBUILD`
> 
> Under prepare() comment out the line `patch -p1 < "${srcdir}/0001-zshrc.patch"`
> 
> Save and exit
> `build with makepkg -sfi`
> 
> Then continue the install script under ~/HyDE/Scripts/

Is the path you clone it into important? Because even after doing this.. It doesn't work.

**Comment by ngocthien115** [comment]
> > Clone
> > `git clone https://aur.archlinux.org/oh-my-zsh-git.git`
> > Change dir
> > `cd oh-my-zsh-git`
> > Edit pkgbuild
> > `nano PKGBUILD`
> > Under prepare() comment out the line `patch -p1 < "${srcdir}/0001-zshrc.patch"`
> > Save and exit
> > `build with makepkg -sfi`
> > Then continue the install script under ~/HyDE/Scripts/
> 
> Is the path you clone it into important? Because even after doing this.. It doesn't work.

for the problem i had, it showed error when installing oh-my-zsh-git, so i installed it manually and then ran install.sh command again

**Comment by kRHYME7** [comment]
Try https://github.com/Hyde-project/hyde
