### ISSUE TITLE
[Bug]: VScode lost transluscent effect 

### ISSUE THREAD

**Issue by BentleyOph** [prasanthrangan/hyprdots#1957]
![image](https://github.com/user-attachments/assets/1e99eab3-dd2b-454c-8e32-079685eb855c)
So after the update to version 1.95 visual-studio-code-bin I no longer have the transluscent effect that it had initially?

**Comment by kRHYME7** [comment]
Already fix it here https://github.com/prasanthrangan/hyprdots/commit/823d53ca642aa4da9b797c178c445e3e7cbc10bb try to check commits or update your dotfiles

**Comment by BentleyOph** [comment]
@kRHYME7 Yeah...checked commits same day and fixed ...what is the best way to update dotfiles btw ?

**Comment by kRHYME7** [comment]
For now using the cli (lol) 

Basically `Hyde update` then `Hyde restore Config ` then it will list the files that will be preserved sync and be overwritten. You should set it 1 by 1 your self.

Another best way is to maintain a fork.
