### ISSUE TITLE
[Bug]: oh-my-zsh-git - exit status 4

### ISSUE THREAD

**Issue by rotkis** [prasanthrangan/hyprdots#1959]
### Description

error making: oh-my-zsh-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
oh-my-zsh-git - exit status 4

### Steps to Reproduce

1. install the script
2. run the script
3. error on install oh-my-zsh-git 

### Expected Behavior

oh-my-zsh-git install

### Actual Behavior

oh-my-zsh-git not install

### Environment

I try reinstaling arch linux to run and doesn't work

e.g.,

- Linux Distro: arch linux
- Linux Version, output of `uname -a`: 6.11.5
- Hyprland Version, output of `hyprctl version`: 0.44.1
- Installation Environment: main hardware 
- Other info: CPU: Intel i5-7200U (4) @ 3.100GHz GPU: Intel HD Graphics 620 Host: Inspiron 5567 

### Additional Information

I don't know what I do to run this

**Comment by kRHYME7** [comment]
![image](https://github.com/user-attachments/assets/0a8ee7f2-b23c-453c-8301-07ab33b66da2)

There's a reason why the `search` bar is longer than the `new issue` button
