### ISSUE TITLE
[Bug]: Bluetooth Headphones not detected as output device 

### ISSUE THREAD

**Issue by Hareekshith** [prasanthrangan/hyprdots#1963]
### Description

I connected by Headphones (Boat Rockerz 425) to arch, it got paired. The sound whichever is playing is only coming from the laptop's speaker and not from the Headphones. It almost seems like the Headphones isn't detected as a audio output device. 

### Expected Behavior

I expected that after pairing with the system, the audio output will automatically change to that of Headphones. 

### Actual Behavior

The Headphones got paired, but is not detected as an output or input device. 

Requesting a resolution to the issue

**Comment by kRHYME7** [comment]
Try to right click the Speaker symbol. It should pop up a menu. Can you see your Device?

**Comment by Hareekshith** [comment]
![image](https://github.com/user-attachments/assets/47ecfbf9-7a56-4ffd-a9be-390b580a35cc)
This is the screen I am getting, the unplugged Headphones was the previous device I was using.

**Comment by kRHYME7** [comment]
Headphone was still (unplugged) even plugging in?

**Comment by Hareekshith** [comment]
No, I am connecting the headphones via bluetooth. That was the previous Headphone I was using, through aux cableI used to connect it. 
![image](https://github.com/user-attachments/assets/d409fbf6-0c22-49ae-a5ca-2b037a959395)

**Comment by kRHYME7** [comment]
I see, Can you check if it is successfully connected to Bluetooth? click the Bluetooth tray Icon  and check if the headphone is connected

**Comment by Hareekshith** [comment]
![image](https://github.com/user-attachments/assets/95fa5116-7620-43ac-99ab-411739ad9c0e)
It is connected right?

**Comment by Hareekshith** [comment]
Hello, u there?

**Comment by kRHYME7** [comment]
yup it should work. I do sometimes get some bugs on pipewire(handles your audio connection and stuff) though. And it fixes after a reboot.

Also Bluetooth devices should have a separate dropdown menu below the default speakers in the volume control GUI.

**Comment by kRHYME7** [comment]
> ![image](https://github.com/user-attachments/assets/0e8498a7-09f7-43ef-a90b-f589fdffeb64)
> This is the screen I am getting, the unplugged Headphones was the previous device I was using.



In this image pipewire should display another output given that it is connected via Bluetooth

**Comment by Hareekshith** [comment]
> yup it should work. I do sometimes get some bugs on pipewire(handles your audio connection and stuff) though. And it fixes after a reboot.
> 
> Also Bluetooth devices should have a separate dropdown menu below the default speakers in the volume control GUI.
> 
> 
> 

Now that is the problem, I properly paired my device, but the audio ain't getting played

**Comment by Hareekshith** [comment]
> > ![image](https://github.com/user-attachments/assets/0e8498a7-09f7-43ef-a90b-f589fdffeb64)
> > This is the screen I am getting, the unplugged Headphones was the previous device I was using.
> 
> 
> 
> In this image pipewire should display another output given that it is connected via Bluetooth 

Here, the Headphones was already connected

**Comment by kRHYME7** [comment]
It's unplugged. Can you check if the headphone needs drivers?

**Comment by kRHYME7** [comment]
Maybe the wiki can help you. This is sort of Linux issues now.

https://wiki.archlinux.org/title/Bluetooth_headset

**Comment by Hareekshith** [comment]
![Uploading image.png…]()
I tried that and getting this error

**Comment by Hareekshith** [comment]
sudo pacman -S pipewire pipewire-pulse pipewire-alsa pipewire-jack wireplumber
sudo pacman -S pipewire-media-session pipewire-pulse pipewire-alsa pipewire-jack

systemctl --user enable --now pipewire pipewire-pulse wireplumber

This works

**Comment by Hareekshith** [comment]
Thank you for assisting me
