### ISSUE TITLE
[Bug]: VSCode - only one instance opens

### ISSUE THREAD

**Issue by seemsindie** [prasanthrangan/hyprdots#1964]
### Description

When i open code from the terminal like `code .` in a specific folder and then do that in another folder i get only one instace of VSCode and not the new folder but the initial one.

### Steps to Reproduce

1. Open two different folders in terminal
2. Run `code .`  in both terminals

### Expected Behavior

I would expect two see two VSCode instances for each folder I opened

### Actual Behavior

I get only one instance

### Screenshots

Check out this video https://youtu.be/AAYS-RduIsY?si=nNRQLqisNgCteMXE

Also recents are not working
![image](https://github.com/user-attachments/assets/2dad1915-070b-4981-984f-48d3e4493591)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: Arch Minimal Installation
- Linux Version, output of `uname -a`: Linux tardis 6.11.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 22 Oct 2024 18:31:38 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1)
- Installation Environment: On the metal
- Other info: 

### Additional Information

Also recents are not working, and pasting stuff in apps is just not working, I have to Win + V and select what i just copied to even paste it...

**Comment by kRHYME7** [comment]
search bar

**Comment by seemsindie** [comment]
Resolved by applying this fix https://github.com/prasanthrangan/hyprdots/pull/1938
