### ISSUE TITLE
[Bug]: Can't login after installing this

### ISSUE THREAD

**Issue by Comitz134** [prasanthrangan/hyprdots#1966]
## Bug Report

After installing I can't login
### Description

After installing tried to login and "Login failed"

### Expected Behavior

Login normally

### Actual Behavior

Can't login: login failed

### Environment

- Linux Distro:ArchLinux
- Installation Environment: On The Main Hardware

**Comment by kRHYME7** [comment]
using hyprland-git?

**Comment by kRHYME7** [comment]
try loging in on a different TTY.  then run ` Hyprland ` 

If somehow you don't know what is TTY, try to search online or at least some parts in the arch wiki

**Comment by tinytempmouse** [comment]
When you boot into arch and sddm loads (the lock screen) find the Session button and switch from Session: Hyprland (systems session) to Session: Hyprland

**Comment by kRHYME7** [comment]
we don't have kwin does ,sddm ship kwin by default?

**Comment by kRHYME7** [comment]
> After installing tried to login and "Login failed

But for this error it looks like an unfinished installation?
