### ISSUE TITLE
[Bug]: When switching themes, there is an error in the hypr theme configuration file

### ISSUE THREAD

**Issue by vgoer** [prasanthrangan/hyprdots#1967]
### Steps to Reproduce

1. Update hyprland
2. Switch the theme style

### Screenshots

![241107_10h16m41s_screenshot](https://github.com/user-attachments/assets/0c379375-379b-4b06-9fcd-7039166a0b82)

### Environment

OS : Archcraft x86_64
Host : KuangshiG16 Series GM6AR0Q Standard
Kernel : 6.11.6-zen1-1-zen
Uptime : 23 mins
Packages : 2414 (pacman), 34 (flatpak)
Shell : zsh 5.9
Resolution : 2560x1600
DE : Hyprland
Terminal : kitty

**Comment by kRHYME7** [comment]
What theme?

**Comment by kRHYME7** [comment]
Using hyprland-git?

**Comment by vgoer** [comment]
> What theme?

anyone theme

**Comment by vgoer** [comment]
yes hyprland-git

**Comment by kRHYME7** [comment]
revert it if you can't manage it on your own. 

continue, if you want to solve it in your own. 

# remove the errors first

- Before we continue remove all the errors first. To do that follow the change on this commit.
https://github.com/prasanthrangan/hyprdots/pull/1969

**Note:** we just remove the warning and did not solve the  issue yet

# Make the shadow decoration work again 

- What happend is in the latest hyprland commit they move the shadow variable into a sub category. 
- So users using the latest build of hyprland  or hyprland > v0.45.0 should adjust all the theme files MANUALLY

Hyprland now had the shadow variable.  https://wiki.hyprland.org/Configuring/Variables/#shadow
![image](https://github.com/user-attachments/assets/0a7bd034-e4e0-4111-981a-fb83a947646b)

Now let's choose a theme to fix. 

```bash
 ~/.config/hyde/themes/Catppuccin\ Mocha/hypr.theme
```

You can see in this theme `drop_shadow` is unknown. So remove that line and make a new configruation for shadow
### OLD 
![image](https://github.com/user-attachments/assets/9233d204-15d0-40c0-bef2-b94fe1c0a47d)
### NEW
![image](https://github.com/user-attachments/assets/7fba4c67-f115-40b5-849b-2d777b0b0eab)



Now do that to all the ` hypr.theme ` files
Or report the issue to the theme owner listed in here ` https://github.com/HyDE-Project/hyde-gallery`

**Comment by kRHYME7** [comment]
Added a discussions here for anyone watching this repo. #1970

**Comment by vgoer** [comment]
i got it . thakns
