### ISSUE TITLE
[Bug]: Dolphin white font everywhere

### ISSUE THREAD

**Issue by Kamil-Bagienski** [prasanthrangan/hyprdots#1977]
## Bug Report

Dolphin white font everywhere

### Description

After installing the update for Dolphin, I can't change the font even when switching to a theme other than the gray or white-gray one. Changing the theme doesn't affect the fonts, only the background of active files/folders. Now, even downgrading Dolphin hasn't helped.

### Steps to Reproduce

1. Install update to hyprland and dolphin
2. Launch dolphin
3. White font everywhere

### Expected Behavior

Font should change with the theme change.

### Actual Behavior

The font color of inactive files/folders remains white regardless of the theme, and due to opacity, it looks gray.

### Screenshots

![image](https://github.com/user-attachments/assets/f69426ee-ba87-42e7-a65a-57b8648aa608)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`:Linux Szufilak 6.11.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:41 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
- Installation Environment: On The Main Hardware

### Additional Information

I tried changing the fonts in QT6, Kvantum, etc., but nothing changes. I don't even have any idea what to change anymore.

**Comment by kRHYME7** [comment]
Us too! We don't know yet how to properly theme dolphin. Also I can't even replicate these issues, Mine works perfectly fine.

**Comment by s0m3th1ng-r4nd0m** [comment]
every Dolphin update breaks something for me but i can fix it by copy pasting kdeglobals and dolphinrc from my local HyDE clone but there was an update today or yesterday idr that makes the folders color blue when they are selected. I can't seem to fix it by reinstalling HyDE either.

**Comment by Kamil-Bagienski** [comment]
> Us too! We don't know yet how to properly theme dolphin. Also I can't even replicate these issues, Mine works perfectly fine.

Damn, I tried everything in the config files to change the font color, but nothing happened. So now I'm using Nemo instead waiting for Dolphin  documentation.

Thanks for answers anyway :1st_place_medal:

**Comment by Kamil-Bagienski** [comment]
> every Dolphin update breaks something for me but i can fix it by copy pasting kdeglobals and dolphinrc from my local HyDE clone but there was an update yesterday or today idr that makes the folders color blue when they are selected. I can't seem to fix it by reinstalling HyDE either.

@s0m3th1ng-r4nd0m  Oh, I have the same problem too. I was so focused on the font that I overlooked highlight color.

**Comment by kRHYME7** [comment]
Can you open your qt6ct and see if it exhibits the same issue like dolphin?

**Comment by Andrjs** [comment]
In my case qt6ct looks fine with no issue.

**Comment by kRHYME7** [comment]
@Andrjs You also got the dolphin bug?

Can you also send a qt5ct screenshot beside the qt6ct?

**Comment by kRHYME7** [comment]
example my main(a laptop), Looks fine and I don't have issues for dolphin 
![image-2.png](https://github.com/user-attachments/assets/8fdfc110-07ce-4a83-a63f-f09513d18e13)

Then I borrowed someone else's Pc and have this issue . In this PC dolphin had some issues with the font color the same as the qt6ct
![image-1.png](https://github.com/user-attachments/assets/8e04d37a-ffee-4f96-81c0-d9ba66199eaf)

**Comment by Andrjs** [comment]
Yes, I also got the dolphin bug.

![241111_01h04m04s_screenshot](https://github.com/user-attachments/assets/59950e2c-13e4-4785-894f-e1d214bd984c)

On the left qt5ct and on the right qt6ct.

**Comment by kRHYME7** [comment]
Your qt6ct looks fine . can you share your dolphin screenshot too?

**Comment by Kamil-Bagienski** [comment]
Left qt5, right qt6
![image](https://github.com/user-attachments/assets/91531a75-4cfe-44f4-afde-56a03c091577)

**Comment by kRHYME7** [comment]
This is too confusing.  Lol 

@Kamil-Bagienski  your qt6ct looks fine but the dolphin was still broken. Now it's too confusing lol.

Can you remove the dolphin stater in `~/.local/dolphin/` both the dolphin stuff

**Comment by Kamil-Bagienski** [comment]
@kRHYME7  xD
![image](https://github.com/user-attachments/assets/75397a39-dfd5-4347-af6f-4d62e6b9732b)

**Comment by kRHYME7** [comment]
sadly the same issue. Might be better to use another file manager for now. I recommend some gtk base if it's fine for you like nemo.

**Comment by rishav12s** [comment]
maybe downgrading dolphin is a solution ?

someone said that selected folders showing a blue color on them no matter the theme

i fixed it by downgrading 3-4 versions back

maybe it could help solve this as a temporary solution

**Comment by kRHYME7** [comment]
Icon not syncing is solved in this commit. Soit won't make sense if they're still using the old version to fix icons.  

https://github.com/prasanthrangan/hyprdots/commit/7ed7b8963165c650b63cf0ca2cded35ffa5f8b93

also I guess we should modify dolphinrc instead of changing kdeglobals to narrow down the scope of change. Or maybe have both.

Do we still get the background color always white/black/unthmed issue in dolphin?

**Comment by kRHYME7** [comment]
> The font color of inactive files/folders remains white regardless of the theme, and due to opacity, it looks gray.

@Kamil-Bagienski  I somehow missed this part. Is there any way for you to turn off the opacity for dolphin and see what is the actual color for that problematic element.

**Comment by rishav12s** [comment]
its not icon theme problem icons change according to theme

in recent update when a folder is selected there is a bluish glow on the folder icon 

this shouldnt happen

**Comment by Andrjs** [comment]
> > The font color of inactive files/folders remains white regardless of the theme, and due to opacity, it looks gray.
> 
> @Kamil-Bagienski I somehow missed this part. Is there any way for you to turn off the opacity for dolphin and see what is the actual color for that problematic element.


The only theme that seems works fine is Material Sakura:

![241111_09h20m56s_screenshot](https://github.com/user-attachments/assets/1e22b48e-5b31-4f2a-b598-e842203753e5)

Here with Rose Pine theme:

![241111_09h20m18s_screenshot](https://github.com/user-attachments/assets/7a4db170-29f9-4e47-8a39-1d73b7910dc8)

Note that the dot file and folder look almost fine.

**Comment by rishav12s** [comment]
> > > The font color of inactive files/folders remains white regardless of the theme, and due to opacity, it looks gray.
> > 
> > 
> > @Kamil-Bagienski I somehow missed this part. Is there any way for you to turn off the opacity for dolphin and see what is the actual color for that problematic element.
> 
> The only theme that seems works fine is Material Sakura:
> 
> ![241111_09h20m56s_screenshot](https://private-user-images.githubusercontent.com/24222253/384843867-1e22b48e-5b31-4f2a-b598-e842203753e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTYyMzksIm5iZiI6MTczMTMxNTkzOSwicGF0aCI6Ii8yNDIyMjI1My8zODQ4NDM4NjctMWUyMmI0OGUtNWIzMS00ZjJhLWI1OTgtZTg0MjIwMzc1M2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA5MDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YTNlOGM2OWNlNjY5ZTJlODJjMzhlZTBlMjEwZTI2ODg4ZTM4NzM4MmFhNTY2ZTQ0MjZkNjFlYmZjMWVkYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.05ID5KlhuGIBncXATxgM6-LAf68lXi7oMqQtr_YWlZw)
> 
> Here with Rose Pine theme:
> 
> ![241111_09h20m18s_screenshot](https://private-user-images.githubusercontent.com/24222253/384844044-7a4db170-29f9-4e47-8a39-1d73b7910dc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTYyMzksIm5iZiI6MTczMTMxNTkzOSwicGF0aCI6Ii8yNDIyMjI1My8zODQ4NDQwNDQtN2E0ZGIxNzAtMjlmOS00ZTQ3LThhMzktMWQ3M2I3OTEwZGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA5MDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYmY4YjdlNWI3YzU1NmJkZWZkNjZmN2JkOTBiNzRhOTZmZDZiNTk3OTgwMmIxNTQ5ODhlZTFmZjA4NTk0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eo3H8BXQ-9oUJyuNJWnLirr_8-b32bIExStFDJiBdfc)
> 
> Note that the dot file and folder look almost fine.

could you try downgrading dolphin 4 versions back and give the ss 

maybe others who are facing the font problem can also try it

could be a temporary fix ig one of the dependencies didnt get updated in arch repo

**Comment by kRHYME7** [comment]
Yow please confirm if 

```
gsettings set org.gnome.desktop.interface color-scheme prefer-light
```
and
```
gsettings set org.gnome.desktop.interface color-scheme prefer-dark 

```



Changes that font. In my QT dynamically follows the colorsheme from gsettings. This might be the solution for this.

**Comment by rishav12s** [comment]
@kRHYME7 yea its working fine except of the bluish glow not facing any font related issues 

so setting prefer light in dark theme will fix it or remove that line completely ?

**Comment by kRHYME7** [comment]
> bluish glow 

Maybe a feature lol. all themes?

**Comment by rishav12s** [comment]
> > bluish glow
> 
> Maybe a feature lol. all themes?

on some themes its more visible where the accent color isnt supposed to be blue lol

**Comment by kRHYME7** [comment]
I replicated the blue highlights on a new user! But after removing all the state/dolphin share/dolphin then populate the dots then restart it seemed to fix it lol. 

And also a couple of theme changes.

**Comment by Kamil-Bagienski** [comment]
> I replicated the blue highlights on a new user! But after removing all the state/dolphin share/dolphin then populate the dots then restart it seemed to fix it lol.
> 
> And also a couple of theme changes.

@kRHYME7 I deleted Dolphin's state/dolphin and share/dolphin, reinstalled the dotfiles, reboot, but the same font bug persists. Then, I removed Dolphin completely, along with any related files, reinstalled the dotfiles, reboot, but still encountered the same font bug. Maybe my PC is cursed. 

The only thing that reinstalling Dolphin and the dotfiles helped with was the flickering in Dolphin, which started appearing after the update.

**Comment by tsssu** [comment]
Hello, im also facing the same issue with the dolphin theme, but only for dark theme since white theme works fine.

**Comment by bwafi** [comment]
there is a way to fix the issue?

**Comment by Andrjs** [comment]
I've found a solution in a reddit post that work for me.

Add these lines to ~/.config/dolphinrc 
```
[UiSettings] 
ColorScheme=Theme Name
```

In Catppuccin theme I still have some issues with highlight of right menu, but with the others themes everything is work just fine.

Here the post:
https://www.reddit.com/r/hyprland/comments/1gobj8c/dolphin_file_manager_font_colors/

**Comment by rishav12s** [comment]
> I've found a solution in a reddit post that work for me.
> 
> Add these lines to ~/.config/dolphinrc
> 
> ```
> [UiSettings] 
> ColorScheme=Theme Name
> ```
> 
> In Catppuccin theme I still have some issues with highlight of right menu, but with the others themes everything is work just fine.
> 
> Here the post: https://www.reddit.com/r/hyprland/comments/1gobj8c/dolphin_file_manager_font_colors/

what should theme name be ?
kvantum name ?

**Comment by Malvin555** [comment]
> I've found a solution in a reddit post that work for me.
> 
> Add these lines to ~/.config/dolphinrc
> 
> ```
> [UiSettings] 
> ColorScheme=Theme Name
> ```
> 
> In Catppuccin theme I still have some issues with highlight of right menu, but with the others themes everything is work just fine.
> 
> Here the post: https://www.reddit.com/r/hyprland/comments/1gobj8c/dolphin_file_manager_font_colors/

Thats work :]

**Comment by kRHYME7** [comment]
Hello anyone vouching that this works.

What is the indicator for the Theme Name?

is it from the ~/.themes?  or something around kavantum?

**Comment by Kamil-Bagienski** [comment]
@Andrjs THANK YOU!
> Hello anyone vouching that this works.
> 
> What is the indicator for the Theme Name?
> 
> is it from the ~/.themes? or something around kavantum?
@kRHYME7  Working with theme names from dotfiles :)

**Comment by kRHYME7** [comment]
Can you help me with the syntax??


can you try using this?

 `wallbash ` 
`kvantum` 
`qt5ct`
`qt6ct`

for the theme how should it be formatted?

Catppuccin-Mocha? How to derive the Theme name? from the GTK theme?

**Comment by TheyCallMeSecond** [comment]
> Can you help me with the syntax??
> 
> can you try using this?
> 
> `wallbash ` `kvantum` `qt5ct` `qt6ct`
> 
> for the theme how should it be formatted?
> 
> Catppuccin-Mocha? How to derive the Theme name? from the GTK theme?
> 
> Edit:
> 
> lol. Setting it like this fixes the bluish highlights
> 
> ```
> [UiSettings]
> ColorScheme=*
> ```
> 
> Putting anything except blank fixes it.
> 
> This is the only bug I got so needed someone to check if the above solution fixes those issues eg. Background and the Font color

Fixed
![image](https://github.com/user-attachments/assets/7a77b746-5d10-4312-b2f0-b695bf13ec6b)

**Comment by s0m3th1ng-r4nd0m** [comment]
> Can you help me with the syntax??
> 
> 
> can you try using this?
> 
>  `wallbash ` 
> `kvantum` 
> `qt5ct`
> `qt6ct`
> 
> for the theme how should it be formatted?
> 
> Catppuccin-Mocha? How to derive the Theme name? from the GTK theme?
> 
> 
> Edit:
> 
> lol. Setting it like this fixes the bluish highlights 
> 
> 
> ```
> [UiSettings]
> ColorScheme=*
> 
> ```
> 
> 
> Putting anything except blank fixes it.
> 
> This is the only bug I got so needed someone to check if the above solution fixes those issues eg. Background and the Font color


It works! ![241114_19h11m51s_screenshot.png](https://github.com/user-attachments/assets/d31c438a-2610-4613-91cf-7a652c8d8a15)

**Comment by bwafi** [comment]
> Can you help me with the syntax??
> 
> can you try using this?
> 
> `wallbash ` `kvantum` `qt5ct` `qt6ct`
> 
> for the theme how should it be formatted?
> 
> Catppuccin-Mocha? How to derive the Theme name? from the GTK theme?
> 
> Edit:
> 
> lol. Setting it like this fixes the bluish highlights
> 
> ```
> [UiSettings]
> ColorScheme=*
> ```
> 
> Putting anything except blank fixes it.
> 
> This is the only bug I got so needed someone to check if the above solution fixes those issues eg. Background and the Font color


It works!

**Comment by kRHYME7** [comment]
Let's see each other again some dolphin updates

**Comment by s0m3th1ng-r4nd0m** [comment]
> Let's see each other again after some dolphin updates

create an issue to post dolphin bugs in and then pin it 😂
