### ISSUE TITLE
[Bug]: No CPU and GPU temperatures in Waybar after reinstalling HyDE

### ISSUE THREAD

**Issue by s0m3th1ng-r4nd0m** [prasanthrangan/hyprdots#1979]
### Description

I did ./install.sh -r to update my dotfiles today and after that i can't see the CPU and GPU temperatures in my Waybar.

### Steps to Reproduce

1. git pull in HyDE directory
2. ./install.sh -r
3. see that CPU and GPU temperatures don't show in Waybar anymore.

### Expected Behavior

To be able to see CPU and GPU temperatures beside CPU and ram usage.

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

i didn't mess with anything else except for that i added ~/.cargo/bin to path in my hyprland.conf which shouldn't mess with my Waybar config.

e.g.,

- Linux Distro: Arch Linux
- Linux Version: 6.11.6.arch1-1
- Hyprland Version: 0.44.1
- Installation Environment: Laptop (not VM)
- Other info: 1366x768

### Additional Information

none

**Comment by kRHYME7** [comment]
output of `gpuinfo.sh`

**Comment by s0m3th1ng-r4nd0m** [comment]
command not found. same output when running it in ~/.local/share/bin too

**Comment by s0m3th1ng-r4nd0m** [comment]
![241110_16h30m16s_screenshot.png](https://github.com/user-attachments/assets/99c835d1-3fe6-4d87-ab1f-0ef514d8aa8b)

**Comment by s0m3th1ng-r4nd0m** [comment]
> no command found when run in home directory but running in ~/.local/share/bin gives this output.

there's no ~/.local/share/bin in the output of ```echo $PATH```

**Comment by kRHYME7** [comment]
> there's no ~/.local/share/bin in the output of echo $PATH


did you modify your path in env? 

like added another directory to PATH? 

This is wrong
```hyprlang
env = PATH,$PATH:/new/path/ 
```

use this instead 
```hyprlang
env = PATH,$PATH:$scrPath:/new/path
```

**Comment by s0m3th1ng-r4nd0m** [comment]
> did you modify your path in env? 
> 
> like added another directory to PATH? 
> 
yup. that's what i did.

> This is wrong
> ```hyprlang
> env = PATH,$PATH:/new/path/ 
> ```
oh, i see. so i was just resetting it to ~/.cargo/bin instead of appending ~/.cargo/bin to $PATH


> use this instead 
> ```hyprlang
> env = PATH,$PATH:$scrPath:/new/path
> ```
well that fixes it. thanks! i thought i could append $PATH by adding another environment variable.
