### ISSUE TITLE
How to disable hyde themes, and set it to my normal config?

### ISSUE THREAD

**Issue by BarniF10** [prasanthrangan/hyprdots#1980]
Hi!
I have an Issue, that i accidentally set my hyde theme to catppuccin, and i dont know how to disable it. I want to use my normal .config/hypr config as my config.

**Comment by kRHYME7** [comment]
This is a configuration file repo so probably your old configuration is overwritten.  

Your old configs should be in ` ~/.config/cfg_backups/ ` 

> I want to use my normal .config/hypr config as my config. 

what do you mean by normal?
