### ISSUE TITLE
Exa doesn't get installed

### ISSUE THREAD

**Issue by kronikpillow** [prasanthrangan/hyprdots#199]
for some reason exa doesn't get installed when you select paru ... not sure if it's the same with yay, it did install before the latest commit

**Comment by T-Crypt** [comment]
You may need to re-run the install script. Its located in the custom_hypr.lst and installed during the script. 

https://github.com/T-Crypt/hyprdots/blob/main/Scripts/custom_hypr.lst -- Line 50 

called in

   #----------------------#
    # prepare package list #
    #----------------------#
    shift $((OPTIND -1))
    cust_pkg=$1
    cp custom_hypr.lst install_pkg.lst

    if [ -f "$cust_pkg" ] && [ ! -z "$cust_pkg" ] ; then
        cat $cust_pkg >> install_pkg.lst
    fi

**Comment by kronikpillow** [comment]
In the last 3-4 days, iv reinstalled your dotfiles several times on a fresh install while i was creating a OpenSUSE btrfs style layout,  exa doeant get installed, for some reason it says package not found ...

Also when using the -d option it installs the packages but not the dotfiles, all with paru as a option ... Havent tried yay since the latest commit, but it worked fine with yay before the latest commit ...

I noticed that you removed the default pkg list and that its installing from the custom list now, maybe something in the install script is broken cuz of it ...

**Comment by T-Crypt** [comment]
https://github.com/prasanthrangan/hyprdots/commit/5fe39c0fe17a5834f81c7bb7b41a622b06be0c82

the only update I see is about 3 weeks ago. No major updates to the install script in the last few days....

May need to look into this a little more.

**Comment by prasanthrangan** [comment]
> [88695e4](https://github.com/prasanthrangan/hyprdots/commit/88695e44c4c63b6c04aef9b08e089a35ad772460)
> 
> looks like this could be the commit, -d was modified here.

hmmm... this was just to skip a package from list if its commented out.

from the latest commit from exa repo from last week, looks like its not maintained anymore 

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/f81b0d61-3457-431d-b73d-b20e63537a97)

**Comment by kronikpillow** [comment]
Wow, i didnt know that, still doesnt explain why the installer skips that package, since its still in the Arch repos

**Comment by kronikpillow** [comment]
![IMG_20230913_085415.jpg](https://github.com/prasanthrangan/hyprdots/assets/48420193/2dd7a29c-22a3-41f0-9790-dcdd1e461faf)

Right now doing a fresh run ...

**Comment by prasanthrangan** [comment]
yup, makes sense.. just try replacing `exa` with `eza` in `custom_hypr.lst`, and then rerun install.

**Comment by kronikpillow** [comment]
Even when i ls it says exa unknown command, but ... When i type pacman -Sy exa, it gets installed andbworks ... Weird ??

**Comment by prasanthrangan** [comment]
hmm, the script checks if its available in repo before installing, so try if `pacman -Sy exa`  works.
this `pacman -Sy exa` might be redirecting it to `eza` package. but I'll check later and fix this.

**Comment by kronikpillow** [comment]
I dont think its redirecting to eza because the aliases in the .zshrc wouldnt work regardless of the package redirection, but yes, we should probably switch to eza ..


Off topic:
Love your rice and your work to be honest, best one i found so far for Hyprland, but i very much dislike the arrow-keys workflow, i preffer a vim-like experience, im thinking of maintaining a vim keybinding oriented fork, and possibly with a master layout cuz im very much used to dwm and the LukeSmith keybinding scheme ...


Can i ask about the Catppucin themes? What accent colors variant did you use? When i install the Catppucin theme from AUR it actually comes with many accent color variants ...

I was also wondering how you solved the Cattpuccin ncurses colors miss-march (like when using htop or alsamixer, using the one from the official repo actually makes part of it unreadable)

**Comment by kronikpillow** [comment]
Confirming that sudo pacman -Sy exa actually redirects to eza

**Comment by prasanthrangan** [comment]
> I dont think its redirecting to eza because the aliases in the .zshrc wouldnt work regardless of the package redirection, but yes, we should probably switch to eza ..

nope, it does work... as exa is linked to eza now  -

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/d3696e53-81a6-4170-ba03-15c0405c6b99)

But i'll fix the package list and .zshrc anyways to keep it clean and consistent.

> Love your rice and your work to be honest, best one i found so far for Hyprland, but i very much dislike the arrow-keys workflow, i preffer a vim-like experience, im thinking of maintaining a vim keybinding oriented fork, and possibly with a master layout cuz im very much used to dwm and the LukeSmith keybinding scheme ...

Thank you so much! ya sure, please feel free to fork this and change the keybindings that works for you!

> Can i ask about the Catppucin themes? What accent colors variant did you use? When i install the Catppucin theme from AUR it actually comes with many accent color variants ...
> 
> I was also wondering how you solved the Cattpuccin ncurses colors miss-march (like when using htop or alsamixer, using the one from the official repo actually makes part of it unreadable)

I don't use any aur packages for theming, i think i had the old version from their git, but you can find the gtk theme files in [here](https://github.com/prasanthrangan/hyprdots/blob/main/Source/arcs/Gtk_CatppuccinMocha.tar.gz).
I'm also not sure about Cattpuccin ncurses colors miss-march, any steps to replicate?
