### ISSUE TITLE
[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by marko-onechance** [prasanthrangan/hyprdots#1995]
How to change this... It was happen after the install last updates. I don't have any fonts for name of folders...
![image](https://github.com/user-attachments/assets/213dfc44-9f1d-410a-bc0c-f2315ff84b14)

**Comment by marko-onechance** [comment]
please help me, how can i solve it??)

**Comment by marko-onechance** [comment]
![image](https://github.com/user-attachments/assets/b458fd69-25b9-47e6-ac3b-e65e8f181f64)

**Comment by kRHYME7** [comment]
Duplicate. See the Dolphin issue.


I recommend using Nemo file manager for now.
