### ISSUE TITLE
[Bug]: Unable to install several themes

### ISSUE THREAD

**Issue by Tizz-Tumbler** [prasanthrangan/hyprdots#1997]
### Description

Trying to install Monterey and pixel dream, 

### Steps to Reproduce

1. Hyde theme import
2. when choosing multiple themes, I get no errors. But theme is still not installed (3rd image)
3. when choosing one theme, I get a few errors/warnings, and nada

### Expected Behavior

installed drakula theme with no issue, using this same method

### Screenshots

![image](https://github.com/user-attachments/assets/0c4fe486-9512-4496-b036-ccc0c3ece4bc)
![image](https://github.com/user-attachments/assets/dd371a88-3b6b-49db-b34b-4ba731d77321)
![image](https://github.com/user-attachments/assets/82990726-f809-4e64-a4e4-ebb54188488b)

### Environment

- Linux Distro: Arch
-  Linux Version: Linux tizz 6.6.60-1-lts #1 SMP PREEMPT_DYNAMIC Fri, 08 Nov 2024 16:03:02 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland 0.45.0 built from branch  at commit  dirty ().
- Installation Environment: main hardware

### Additional Information

Tried to hunt for document-font and monospace-font to see if that was causing the issue, 
I couldn't find them so no dice, but I have a feeling its not the fonts that are causing this

**Comment by kRHYME7** [comment]
update your cli `yay -S hyde-cli-git`.

If not working report to the broken theme.

**Comment by Tizz-Tumbler** [comment]
> update your cli `yay -S hyde-cli-git`.
> 
> If not working report to the broken theme.

this worked! thx
