### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by FatngatirBilek** [prasanthrangan/hyprdots#2]
After running install.sh it say queue... And the error package not found

**Comment by prasanthrangan** [comment]
Its just checking if package is available in official or aur repos... should not be a problem, so please ignore those error messages.
I'll look into hiding those errors!

**Comment by FatngatirBilek** [comment]
Yeah. keep it up bro <3

**Comment by prasanthrangan** [comment]
this is fixed now... enjoy!
