### ISSUE TITLE
[Bug]: Multiple processes of Cava

### ISSUE THREAD

**Issue by s0m3th1ng-r4nd0m** [prasanthrangan/hyprdots#2000]
### Description

When switching from a waybar style that uses Cava to one that doesn't and then back again to one that does, it doesn't kill the previous Cava process and creates a new one again which results in multiple useless Cava processes running in background.

### Steps to Reproduce

1. switch Waybar style to one that uses Cava
2. change it again to one that doesn't use Cava
3. switch it again to the Waybar style that uses Cava
4. See that there are multiple instances of Cava running in the background

### Expected Behavior

It should kill the Cava process when it is no longer needed like when switching to a Waybar style that doesn't have Cava module.

or

It should check if a Cava process is already running and use that process instead of making a new one again.

### Actual Behavior

There's multiple useless processes of Cava running in the background each using around 9-10 MBs of RAM.

### Screenshots

![241115_14h24m22s_screenshot.png](https://github.com/user-attachments/assets/3d46930a-13e6-4a62-b1d8-9d95e532ac99)

### Environment

- Linux Distro: Arch Linux
- Linux Version: 6.11.7.arch1-1
- Hyprland Version: 0.45.0-1
- Installation Environment: Laptop (not vm)

**Comment by keth-real** [comment]
@kRHYME7  Gotta push it here #1988

**Comment by kRHYME7** [comment]
@s0m3th1ng-r4nd0m  Fixed on #1988
