### ISSUE TITLE
[Bug]: Waybar audio visualizer glitches 

### ISSUE THREAD

**Issue by theactualmariluski** [prasanthrangan/hyprdots#2002]
### Description

When I try to play anything, the bar's visualizer glitches, and puts weird unicode characters

### Steps to Reproduce

1. Put some video, song, or anything that has sound
2. See the bar

### Expected Behavior

So it displays a nice audio visualizer

### Actual Behavior

Start glitching with weird unicode characters changing instantly 

### Screenshots

![https://ibb.co/wBSjpt2](only bar)
![https://ibb.co/k09wtfB](full screen + cava)

### Environment

Changed the theme and wallpaper to firewatch.jpg and the theme to Catppuccin Mocha

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

Audios only tested from YouTube and Spotify

**Comment by kRHYME7** [comment]
show screen shot

**Comment by kRHYME7** [comment]
Can you check which is broken. need to restart waybar to see changes `wayabar_caba.sh --reset `


https://github.com/prasanthrangan/hyprdots/blob/main/Configs%2F.config%2Fhyde%2Fhyde.conf#L98-L110



Please also confirm if this is specific for the theme only or all the themes exhibit this issues.

**Comment by theactualmariluski** [comment]
All themes have this issue, I don't really know what i did, but it now works fine
