### ISSUE TITLE
[Bug]: config option <decoration_shadow> does not exist

### ISSUE THREAD

**Issue by MINAX2U** [prasanthrangan/hyprdots#2004]
### Description
error after updating 

### Steps to Reproduce

1. yay
2. sudo pacman -Syu
3. reboot

### Expected Behavior

[What did you expect to happen?]
work normal
### Actual Behavior

[What actually happened?]

it says Config error in theme.conf at line 24: config option <decoration:drop_shadow> does not exist

### Screenshots

![241116_13h53m50s_screenshot](https://github.com/user-attachments/assets/28847fac-dc2f-4b06-8f3a-44fea5b9dae5)

### Environment
Linux Distro: ArchLinux

**Comment by kRHYME7** [comment]
Follow the commits, Read issues, Search for issues, find duplicate. 
update your configs, update your themes, read hyprland wiki, join discord
