### ISSUE TITLE
Drop shadow Error Every time I Change theme

### ISSUE THREAD

**Issue by neepanb009** [prasanthrangan/hyprdots#2010]
After the new hyperland version has been released i am having issues with the drop shadow, every time i change the theme it shows a drop shadow error, regardless that i delete the drop shadow text from theme.conf file. every time. How can it be solved

**Comment by som-num** [comment]
same error 
![image](https://github.com/user-attachments/assets/03344556-bfe9-401d-ba85-c7cd82965bd0)

**Comment by kRHYME7** [comment]
![image](https://github.com/user-attachments/assets/f42f966d-2bc7-4b0e-bcb5-ccfa78114ea3)

Look filter/searh bar is longer than the New issue button.  

Here's the explaination
https://github.com/prasanthrangan/hyprdots/issues/1967#issuecomment-2461763000
