### ISSUE TITLE
[Bug]: Waybar is not responsible

### ISSUE THREAD

**Issue by Wertyqin99331** [prasanthrangan/hyprdots#2026]
### Description

After changing waybar layout. some waybar modules become not working, some still work (sound, network), other stucks (theme changer, wallpaper changer)

### Steps to Reproduce

1. Change waybar layout
2. Click on waybar modules (clipboard hist, change theme and etc)
3. Nothing happens

### Expected Behavior

I expect, it works as usual

### Actual Behavior

It stucks and nothing happenned

e.g.,

Arch linux, not VM

### Additional Information

After changing themes by keymap, sometimes it dissapears

**Comment by boulder-roller** [comment]
works on my machine

**Comment by kRHYME7** [comment]
Typical waybar stuff (hangs out of nowhere). It might be a problematic system tray. 

Please relaunch the waybar if it crashes using the bind. checkout the keybindings table for the bind to toggle waybar.

I'll be closing this as this is an outside scope of the configuration. Report further issues like this on upstream waybar repository

**Comment by Wertyqin99331** [comment]
solved, waybar doesn't have $PATH to these scripts (strange)
