### ISSUE TITLE
[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by paulemacedo** [prasanthrangan/hyprdots#2033]
### Description
I can't fill the vertical monitor wallpaper os set different wallpaper for each monitor
when setting a vertical wallpaper it cuts anyways

### Steps to Reproduce

on boot

### Expected Behavior

either fill wallpaper so i cant see the black bars
or set an vertical walppaper 

### Actual Behavior

[What actually happened?]

### Screenshots
![image](https://github.com/user-attachments/assets/4c52cd23-4527-4db2-8c2b-e6c7d6620144)
![image](https://github.com/user-attachments/assets/2742e93e-196f-43f7-b903-71889a3d0fc2)

### Environment
monitor = DP-2, 1920x1080@144, 1080x250, 1
monitor = HDMI-A-1, 1920x1080@75, 0x0, 1, transform, 1

e.g.,

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux archlinux 6.12.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland 0.45.2 built from branch  at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: Tue Nov 19 21:47:18 2024
Tag: v0.45.2, commits: 5451
built against aquamarine 0.5.0

flags set:
debug

- Installation Environment: On The Main Hardware
- Other info: both monitors 1920x1080

**Comment by kRHYME7** [comment]
Use swww-git for now.

`yay -S swww-git ` they don't seem to care to update it yet.
