### ISSUE TITLE
[Bug]: Dolphin window size glitching

### ISSUE THREAD

**Issue by TacShot** [prasanthrangan/hyprdots#2037]
Bug Report:
Dolphin window size glitching out 

 Description:
When I open the Dolphin file manager, the window size keeps glitching out when hovering over a folder.

https://github.com/user-attachments/assets/a5468585-9b3c-45fd-a587-61ec4d92e37b

https://github.com/user-attachments/assets/7708feca-2df4-47a1-bd02-298bb17f526c

Steps to Reproduce

1. Open dolphin
2. Move cursor in the "Places" panel or the Tabs
3. Witness the magic!

Expected Behavior:

Hoping windows stay in their place.

 Actual Behavior:

Dolphin window thinks that it is a combination of Flash and Ant-Man cuz it keeps resizing like Ant-Man at the speeds of Barry Allen.

But if I float the window, then it does the same shit to other open windows in the workspace. Well to be specific it happens to the first window opened in the workspace.

 Environment:

- Linux Distro:  ArchLinux,
- Linux Version: 
 Linux hypros 6.12.3-arch11 #1 SMP PREEMPT_DYNAMIC Fri, 06 Dec 2024 11:15:43 +0000 x86_64 GNU/Linux

- Hyprland Version, output of `hyprctl version`:
 
 Hyprland 0.45.2 built from branch  at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: Tue Nov 19 21:47:18 2024
Tag: v0.45.2, commits: 5451
built against aquamarine 0.5.0

- Installation Environment: On The Main Hardware (Asus TUF F15 2020, i5-10300H, GTX  1660TI)
- Other info: Resolution 1920x1080@144

P.S.

You might have to download the video to play. My bad.

**Comment by kRHYME7** [comment]
This bug happened a month ago. Are you using the latest version of dolphin?

**Comment by Anshul-007** [comment]
I think this might be a wayland issue.

`dolphin --platform xcb` seems to work, and the problem seems to be the tooltip which is glitching for wayland

**Comment by TacShot** [comment]
Adding `--platform xcb` to the keybindings config file and .desktop in /usr/share/applications worked like a charm.

**Comment by azmarifdev** [comment]
> Adding `--platform xcb` to the keybindings config file and .desktop in /usr/share/applications worked like a charm.

Brother, how to add this line?
i go to `sudo nano /usr/share/applications/org.kde.dolphin.desktop`

then...

`[Desktop Entry]
Name=Dolphin
Name[ar]=دولفين
Name[ast]=Dolphin
Name[az]=Dolphin
Name[be]=Dolphin
Name[bg]=Dolphin
Name[ca]=Dolphin
Name[ca@valencia]=Dolphin
Name[cs]=Dolphin
Name[da]=Dolphin
Name[de]=Dolphin
Name[el]=Dolphin
Name[en_GB]=Dolphin
Name[eo]=Dolfin
Name[es]=Dolphin`

I get this. then where should I use this line `dolphin --platform xcb` ?
or What else do I need to do?

**Comment by Anshul-007** [comment]
Exec = dolphin `--platform xcb` %u

**Comment by TacShot** [comment]
> > Adding `--platform xcb` to the keybindings config file and .desktop in /usr/share/applications worked like a charm.
> 
> Brother, how to add this line? i go to `sudo nano /usr/share/applications/org.kde.dolphin.desktop`
> 
> then...
> 
> [Desktop Entry] Name=Dolphin Name[ar]=دولفين Name[ast]=Dolphin Name[az]=Dolphin Name[be]=Dolphin Name[bg]=Dolphin Name[ca]=Dolphin Name[ca@valencia]=Dolphin Name[cs]=Dolphin Name[da]=Dolphin Name[de]=Dolphin Name[el]=Dolphin Name[en_GB]=Dolphin Name[eo]=Dolfin Name[es]=Dolphin Exec=dolphin %u Icon=org.kde.dolphin Type=Application X-DocPath=dolphin/index.html Categories=Qt;KDE;System;FileTools;FileManager; GenericName=File Manager GenericName[ar]=مدير ملفّات GenericName[ast]=Xestor de ficheros GenericName[az]=Fayl meneceri GenericName[be]=Кіраўнік файлаў GenericName[bg]=Файлов мениджър GenericName[ca]=Gestor de fitxers GenericName[ca@valencia]=Gestor de fitxers GenericName[cs]=Správce souborů GenericName[da]=Filhåndtering GenericName[de]=Dateiverwaltung GenericName[el]=Διαχειριστής αρχείων GenericName[en_GB]=File Manager GenericName[eo]=Dosiermastrumilo GenericName[es]=Gestor de archivos GenericName[et]=Failihaldur GenericName[eu]=Fitxategi-kudeatzailea GenericName[fi]=Tiedostonhallinta GenericName[fr]=Gestionnaire de fichiers GenericName[gl]=Xestor de ficheiros GenericName[he]=מנהל קבצים GenericName[hi]=फ़ाइल प्रबंधक GenericName[hu]=Fájlkezelő GenericName[ia]=Gerente de file GenericName[id]=Pengelola File GenericName[zh_TW]=檔案管理員 MimeType=inode/directory; InitialPreference=10 X-DBUS-ServiceName=org.kde.dolphin X-KDE-Shortcuts=Meta+E StartupWMClass=dolphin
> 
> I get this. then where should I use this line `dolphin --platform xcb` ? or What else do I need to do?
> 
> [Anshul-007](https://github.com/Anshul-007) [TacShot](https://github.com/TacShot) [kRHYME7](https://github.com/kRHYME7) Help me bro.

---------------------------------------------------------------------------------------------------------------------------
In the line Exec=dolphin %u add --platform xcb just before %u

**Comment by kRHYME7** [comment]
Cause running it in xwayland is not a solution

**Comment by Anshul-007** [comment]
> Why don't we add this by default. I have faced same issue multiple time.

Also there might be noticable missing feature like dragging n dropping a file/folder

**Comment by TacShot** [comment]
there are times when i drag and drop files from a zip file using ark and after extraction i can't use my mouse in dolphin until i kill both processes

**Comment by Meshwa428** [comment]
I also had the same issue.
And adding --platform xcb solved it, but the mouse cursor size is too small when it is inside the dolphin's window. Is there any work around to set mouse size in xcb?

**Comment by kRHYME7** [comment]
>Is there any work around to set mouse size in xcb?

Wayland is the solution for X haha it's a loop.

But try to export  XCURSOR_SIZE=12

or something, note it won't scale.
