### ISSUE TITLE
[Bug]: Dunst v1.12.0 height does not apply properly

### ISSUE THREAD

**Issue by bwafi** [prasanthrangan/hyprdots#2039]
### Description

Dunst height after update Dunst to v1.12.0

### Steps to Reproduce

1. Trigger a notification with brightness or volume.
2. Observe that the notification height is incorrect.

### Expected Behavior

The notification height should be consistent with the configuration but appears incorrect.

### Actual Behavior

The notification height does not match the configured value and appears taller than expected.

### Screenshots

- **Dunst v1.12.0**

![241209_23h34m09s_screenshot](https://github.com/user-attachments/assets/d5520266-914c-431c-872d-fd7bf0783919)

- **Dunst v1.11.0**

![241209_23h54m42s_screenshot](https://github.com/user-attachments/assets/89723f04-d7ea-46da-94a7-628fb5b441bf)

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux arch-linux 6.12.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 06 Dec 2024 11:15:43 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`:
Hyprland 0.45.2 built from branch  at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: Tue Nov 19 21:47:18 2024
Tag: v0.45.2, commits: 5451
built against aquamarine 0.5.0
- Installation Environment: On The Main Hardware
- Other info: 1920x1080

### Additional Information

In Dunst version 1.12.0, the height configuration behaves differently than in previous versions. Using ```height = 300``` no longer works as expected, and instead, the setting must be written as ```height = (0, 300)``` to achieve the desired notification height.

**Comment by itsmenewbie03** [comment]
Thank you for the fix
