### ISSUE TITLE
A command to change swww wallpaper transition.

### ISSUE THREAD

**Issue by Jamaljacobs123** [prasanthrangan/hyprdots#2040]
I want it to be easy to change the wallpaper transition but I have no idea how to

**Comment by T-Crypt** [comment]
You need to modify the ~/.local/share/bin/swwwallpaper.sh 

```
while getopts "nps:" option ; do
    case $option in
    n ) # set next wallpaper
        xtrans="grow"
        Wall_Change n
        ;;

```

```
#// set defaults

[ -z "${xtrans}" ] && xtrans="grow"
[ -z "${wallFramerate}" ] && wallFramerate=60
[ -z "${wallTransDuration}" ] && wallTransDuration=0.4
```

Changing the xtrans to your preferred transition 

review swww repo to get the available transitions. 

https://github.com/LGFae/swww
