### ISSUE TITLE
[Bug]: Persian Characters Render as Nerd Font Icons in Applications

### ISSUE THREAD

**Issue by neox1de** [prasanthrangan/hyprdots#2048]
### Description

Persian text (characters) in some GTK-based applications is not rendered correctly. Instead of showing proper Persian glyphs, the characters appear as **Nerd Font icons** or unrelated symbols. This issue disrupts the readability and appearance of Persian text, particularly in applications like kitty and Element (Matrix client).

### Steps to Reproduce

1. Install prasanthrangan hyprdots using the install scripts
2. Open any GTK-based application (e.g., Element, kitty).
3. Type or view Persian text such as: `سلام چطوری`.
4. Notice that some characters, like `چ`, are incorrectly displayed using Nerd Fonts.

### Expected Behavior

Persian characters should render properly and be displayed as intended without showing unrelated glyphs or symbols.
 
### Actual Behavior

Persian characters are not rendered correctly. They are replaced by glyphs from an unrelated Nerd Font, breaking the text rendering.

### Screenshots

![241211_11h03m48s_screenshot](https://github.com/user-attachments/assets/c5fddd11-6090-4b30-ab4a-22351f855b5e)
---
![241211_11h03m27s_screenshot](https://github.com/user-attachments/assets/86474789-91d8-45c1-bc61-30013da974e9)
---
![241211_11h09m38s_screenshot](https://github.com/user-attachments/assets/e09dcb4d-0277-4461-bcca-f50853761843)

### Environment

- **Linux Distro**: Arch Linux
- **Linux Version**: Output of `uname -a`:
  ```Linux flameX 6.12.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 06 Dec 2024 11:15:43 +0000 x86_64 GNU/Linux```

- **Hyprland Version**: Output of `hyprctl version`:
```
Hyprland 0.45.2 built from branch  at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: Tue Nov 19 21:47:18 2024
Tag: v0.45.2, commits: 5451
built against aquamarine 0.5.0
```

flags set:
debug

- **Installation Environment**: On the main hardware.
- **Display Resolution**: 1920x1080.

**Comment by YuanziX** [comment]
do you have any persian fonts installed?

**Comment by neox1de** [comment]
> do you have any persian fonts installed?

yes, i have vazirmatn font installed on my system

**Comment by T-Crypt** [comment]
@neox1de did you change the font in ~/.config/gtk-3.0/settings.ini? 

![image](https://github.com/user-attachments/assets/51a9b7f1-3a3f-43dc-9fe1-599bec58d76a)

**Comment by neox1de** [comment]
i actually have. however, some characters still gets rendered as a nerd font

**Comment by neox1de** [comment]
@T-Crypt just an update, editing the kitty config file, fixed the problem in kitty, however i still have the problem in gtk. it doesn't change at all, even after a reboot.

**Comment by T-Crypt** [comment]
Open GTK-Settings via Super + A and modify the font settings and apply as it will overwrite the gtkrc2.0 file. 

Something is still overwriting your font preference for GTK applications

**Comment by T-Crypt** [comment]
@neox1de Did that help?

**Comment by neox1de** [comment]
> @neox1de Did that help?

i had to change both fonts in gtk and it worked!
thanks for your help.
