### ISSUE TITLE
[Bug]: Laptop monitor backlight on even with monitor disabled

### ISSUE THREAD

**Issue by NvnStar** [prasanthrangan/hyprdots#2060]
### Description

I have my laptop  plugged into a external monitor, and a monitor config for disabling laptop one `monitor=eDP-1,disable` . After logging in to DM, the backlight of my laptop still turns on. This happens after I updated hyprdots recently.

### Expected Behavior

Laptop light should be turn off completely, and the waybar module for backlight should not appear

### Actual Behavior

Laptop monitor still on (black dim screen), the backlight module for waybar is displaying the percentage of my laptop monitor config the last time I used it

### Environment

e.g.,

- Linux Distro: ArchLinux 6.12.4-zen1-1-zen
- Hyprland 0.45.2
- Installation Environment: On The Main Hardware,
- Other info: Using i915 driver

**Comment by NvnStar** [comment]
Oh and seems like the backlight module now capped at 1% making this less convenient to turn the laptop screen off

**Comment by kRHYME7** [comment]
how about turning off dpms?

**Comment by NvnStar** [comment]
> how about turning off dpms?

dpms off for eDP-1 is not working. 
dpms off for both monitors, external one turns off normally, laptop monitor off for a slight second but go back to dim light immediately

**Comment by NvnStar** [comment]
Tested with settings a bit, it's more like a hyprland issue so I will close this for now.
