### ISSUE TITLE
[Bug]: Material Sakura - Menus have the same font color as the background, making it unreadable

### ISSUE THREAD

**Issue by SSebigo** [prasanthrangan/hyprdots#2061]
### Description

Just like the description says when I open any menu in the file manager (File, Edit, View, etc...) or the right click menu in the Material Sakura theme (or any theme for that matter), the text of the menu is the same color as the background so it's unreadable.

### Steps to Reproduce

- Select any Hyprdots theme
- Open the file manager
- Try right-clicking anywhere

### Expected Behavior

For the Material Sakura theme, I expected a light theme for the menus background and a black text, or at least different colors for the text and the background

### Actual Behavior

The menus have a black background with a black text

### Screenshots

![241216_22h12m21s_screenshot](https://github.com/user-attachments/assets/c00e1204-c54e-48f3-9e67-6b5221559e92)
![241216_22h12m31s_screenshot](https://github.com/user-attachments/assets/eb9c10a0-b1ba-44ec-a667-f3c1b20d24cc)

### Environment

- ArchLinux
- Linux Version, output of `uname -a`: Linux archlinux 6.6.65-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 11 Dec 2024 15:35:54 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland 0.45.2 built from branch at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: Tue Nov 19 21:47:18 2024
Tag: v0.45.2, commits: 5451
built against aquamarine 0.5.0
- Installation Environment: On The Main Hardware
- CPU: Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
- GPU: NVIDIA Corporation GP104 [GeForce GTX 1080]
- Other info: Monitor - 2560x1440@144

**Comment by kRHYME7** [comment]
ark? kde app?

**Comment by SSebigo** [comment]
@kRHYME7 KDE, I'm using Dolphin for the file manager.

**Comment by SSebigo** [comment]
#2058 worked for me, closing this issue.

**Comment by kRHYME7** [comment]
Wow great! I hope this is the end of KDE theming problems.
