### ISSUE TITLE
[Bug]: does not have hyprland-qtutils installed

### ISSUE THREAD

**Issue by azmarifdev** [prasanthrangan/hyprdots#2067]
## Bug Report
your system does not have hyprland-qtutils installed. this is a runtime dependaency for some dialogs. consider installing it.

### Description
When I log in to my Hyprland session, I get a warning. this warning is "your system does not have hyprland-qtutils installed. this is a runtime dependaency for some dialogs. consider installing it."

### Steps to Reproduce

1. Log in to my Hyprland session.
2. I get a warning.

### Screenshots

![241221_00h22m30s_screenshot](https://github.com/user-attachments/assets/c16d827f-7f82-4afe-8344-bde1e41306c3)

### Environment

- Linux Distro: ArchLinux

- Linux Version, output of `uname -a`: Linux ArchHyprland 6.6.65-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 11 Dec 2024 15:35:54 +0000 x86_64 GNU/Linux

- Hyprland Version, output of `hyprctl version`: Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.2.6
 hyprcursor 0.1.10
 hyprgraphics 0.1.1

- Installation Environment: On The Main Hardware
- Other info: Single Display - 1366*768

**Comment by kRHYME7** [comment]
> your system does not have hyprland-qtutils installed. this is a runtime dependaency for some dialogs. consider installing it.


Are you by chance using hyprland-git ? 

If not, report this issue to the arch package repo. 
https://archlinux.org/packages/extra/x86_64/hyprland/


I don't know if this will fix this, but try to install. ` yay -S hyprland-qtutils`  <- But looks like this package do not exist yet so I think you're on  hyprland-git  ? 

Looks to me this is a packager issue
