### ISSUE TITLE
Jetbrains products are displayed large on the main display

### ISSUE THREAD

**Issue by jiangdengke** [prasanthrangan/hyprdots#2074]
I use two monitors, and when I open a JetBrains product (e.g. idea, pycharm), it shows a large display on the main display, and it shows normally when I drag it to the secondary display. However, other software displays normally regardless of which screen it is on。
Here are two pictures
![图片](https://github.com/user-attachments/assets/c82aedd2-ece8-474d-aba2-b1699af0a580)
![图片](https://github.com/user-attachments/assets/7a668402-5372-4817-9356-ac379b7c5a47)

**Comment by kRHYME7** [comment]
yeah , Jetbrains runs now on Wayland?

**Comment by jiangdengke** [comment]
> yeah , Jetbrains runs now on Wayland?是的，Jetbrains 现在能在 Wayland 上运行了吗？ I'm sure not yet. https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/
> 
> Please see the difference between wayland and x11 stuff you'll get your answers.请参阅 wayland 和 x11 之间的区别，你会得到答案。
> 
> you can add this though if you want to scale it不过，如果您想缩放，也可以添加这个功能
> 
> ```
> xwayland {
>     force_zero_scaling = false
> }
> ```
> 
> would look jagged but yeah that's the progress of linux for now.但这就是目前 Linux 的进步。

Oh, it worked, thank you very much
