### ISSUE TITLE
Unable to login to hyperland , Need Help!

### ISSUE THREAD

**Issue by neepan** [prasanthrangan/hyprdots#2079]
My laptop suddenly got shutdown due to low battery, and after that I am unable to login to my hyperland. Every time I try to login , it's getting black and opening the login screen again and again . https://github.com/user-attachments/assets/cffa4e26-1143-4e4a-9551-66e12cccdd19

**Comment by AbrarAbe** [comment]
have you tried launching hypland from tty ?
