### ISSUE TITLE
[Bug]: Conflicting packages at installation

### ISSUE THREAD

**Issue by opixelum** [prasanthrangan/hyprdots#2081]
### Description

During the installation, there are packages conflicting. See the following logs:

```console
looking for conflicting packages...
:: hyprgraphics-0.1.1-3 and hyprgraphics-git-0.1.1.r2.g0f9b8ca6-1 are in conflict. Remove hyprgraphics-git? [y/N] y
:: hyprutils-0.3.0-1 and hyprutils-git-0.2.6.r4.ge6cf45cd-1 are in conflict. Remove hyprutils-git? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: removing hyprutils-git breaks dependency 'hyprutils-git' required by hypridle-git
:: removing hyprutils-git breaks dependency 'hyprutils-git' required by hyprlang-git
:: removing hyprutils-git breaks dependency 'hyprutils-git' required by hyprlock-git
:: removing hyprgraphics-git breaks dependency 'hyprgraphics-git' required by hyprlock-git
:: removing hyprutils-git breaks dependency 'hyprutils-git' required by illogical-impulse-widgets
:: removing hyprutils-git breaks dependency 'hyprutils-git' required by xdg-desktop-portal-hyprland-git
```

If I type `N` at the first message:

```console
looking for conflicting packages...
:: hyprgraphics-0.1.1-3 and hyprgraphics-git-0.1.1.r2.g0f9b8ca6-1 are in conflict. Remove hyprgraphics-git? [y/N] N
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: hyprgraphics-0.1.1-3 and hyprgraphics-git-0.1.1.r2.g0f9b8ca6-1 are in conflict
```

If I type `N` at the second message:

```console
looking for conflicting packages...
:: hyprgraphics-0.1.1-3 and hyprgraphics-git-0.1.1.r2.g0f9b8ca6-1 are in conflict. Remove hyprgraphics-git? [y/N] y
:: hyprutils-0.3.0-1 and hyprutils-git-0.2.6.r4.ge6cf45cd-1 are in conflict. Remove hyprutils-git? [y/N] N
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: hyprutils-0.3.0-1 and hyprutils-git-0.2.6.r4.ge6cf45cd-1 are in conflict
```

**Comment by Sstmtz** [comment]
This happens when I install hyprland-meta-git, you need to manually uninstall hyprutils and the packages that depend on it first. Oddly enough, if you install hyprland-qutils (which also depends on hyprutils) but don't uninstall it, uninstalling hyprutils doesn't give a dependency error. But when you install hyprutils-git, it says "hyprutils-0.3.0-1 and hyprutils-git-0.2.6.r4.ge6cf45cd-1 conflict". So I ended up uninstalling hyprland-qutils and then reinstalling hyprland-meta-git when the error no longer happened:)

**Comment by kRHYME7** [comment]
report to your packager.

**Comment by aminoo10** [comment]
> This happens when I install hyprland-meta-git, you need to manually uninstall hyprutils and the packages that depend on it first. Oddly enough, if you install hyprland-qutils (which also depends on hyprutils) but don't uninstall it, uninstalling hyprutils doesn't give a dependency error. But when you install hyprutils-git, it says "hyprutils-0.3.0-1 and hyprutils-git-0.2.6.r4.ge6cf45cd-1 conflict". So I ended up uninstalling hyprland-qutils and then reinstalling hyprland-meta-git when the error no longer happened:)

installing hyprland-meta-git fixed this issue for me and now I can pacman -Syu normally again :). Thank you.

**Comment by nocthub** [comment]
am using ml4w dotfiles hyprland , and i get this error when i try to update my packages : 

:: hyprutils-0.8.0-1 and hyprutils-git-0.7.1.r0.g674ea57-1 are in conflict. Remove hyprutils-git? [y/N]   
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: hyprutils-0.8.0-1 and hyprutils-git-0.7.1.r0.g674ea57-1 are in conflict

i Don't want to loose my configs from ML4w

**Comment by kRHYME7** [comment]
package manager won't touch $HOME files
