### ISSUE TITLE
Can't toggle themes, duplicated themeselect

### ISSUE THREAD

**Issue by Vivarium69420** [prasanthrangan/hyprdots#210]
![230914_22h38m08s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/124338880/dec470bd-71d3-4c99-9365-daf227fb72d3)
![230914_22h49m49s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/124338880/e329b990-abea-4348-884e-573cb0c43aa5)
For some reason, I can't change into Catppucin-latte, and tokyo-night theme.
It's unclickable.

**Comment by T-Crypt** [comment]
@Vivarium69420 

Can you run the restore_cfg.sh script located below and try again:

LOCATION: Hyprdots/Scripts/restore_cfg.sh 
Should be located where you cloned the repository for these dots.

**Comment by prasanthrangan** [comment]
Oh, can you please try running `themeselect.sh` from terminal, and check the error

**Comment by Vivarium69420** [comment]
I fix the problem with replacing all the dotfiles, it seem to work now. Still don't know what I did to cause the problem.

**Comment by prasanthrangan** [comment]
great, thank you! I'll close this :)
