### ISSUE TITLE
couple issues

### ISSUE THREAD

**Issue by stove-jeebs** [prasanthrangan/hyprdots#214]
1. the current screenshot prints all monitors instead of the currently active one
![230915_19h32m12s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/67490238/54823aa8-d465-4880-a2f5-30903b4dd1a2)

2. the temperature icon can not be displayed with the currently installed fonts
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/c89bbf52-4a5b-4caa-8e81-08853a2f4a3d)

3. something I personally find really frustrating about screenshot snip is that it currently doesn't "snapshot"/freeze the screen in place. For example, I wouldn't be able to snip a tooltip because the moment I press the screenshot key bind it unhovers the tooltip

**Comment by T-Crypt** [comment]
@stove-jeebs 

1. Your using Super + Alt + P to take the screenshot which would make sense to grab the connected current monitors -- I'm sure there is a way to specify the current keyboard active monitor to get this dialed in. but you could also just use Super + P to snip the current screen or the screen you want. ( I can look into this today ) -- @prasanthrangan is on different time zone so I try to respond during his inactive hours or resolve issues for these dots while he is inactive.

2. Tittu is working on the font pack for the GPU temperature as the user who merged this installed the font pack locally on their machine . (most likely add the font pack or change the gpu icon to the current font installed)

3. This is the same behavior for Windows Snip tool -- You must hover your mouse over the tooltip that you want and use "Super + P" while the mouse is still hovering other wise, yes it does freeze the workspace. The function of the snip is to grab the current environment as it stands.

**Comment by prasanthrangan** [comment]
> 1. Your using Super + Alt + P to take the screenshot which would make sense to grab the connected current monitors -- I'm sure there is a way to specify the current keyboard active monitor to get this dialed in. but you could also just use Super + P to snip the current screen or the screen you want. ( I can look into this today ) -- @prasanthrangan is on different time zone so I try to respond during his inactive hours or resolve issues for these dots while he is inactive.

cool thanks! you could handle that in `screenshot.sh`

> * Tittu is working on the font pack for the GPU temperature as the user who merged this installed the font pack locally on their machine . (most likely add the font pack or change the gpu icon to the current font installed)

This should be fixed now in a554ba3, i've already changed the temp glyph!

> 3\. This is the same behavior for Windows Snip tool -- You must hover your mouse over the tooltip that you want and use "Super + P" while the mouse is still hovering other wise, yes it does freeze the workspace. The function of the snip is to grab the current environment as it stands.

Not sure if there is a way to freeze it, but if there is it can be added as an option in `screenshot.sh`
