### ISSUE TITLE
Waybar doesn't open after I switch the waybar mode.

### ISSUE THREAD

**Issue by IgLocoXD** [prasanthrangan/hyprdots#220]
Everytime I switch the Waybar mode (with keybinding or with the Switch icon), Waybar doesn't open anymore, saying;
`[2023-09-16 07:26:45.117] [info] Using configuration file /home/vivinosmol/.config/waybar/config.jsonc
[2023-09-16 07:26:45.117] [info] Using CSS file /home/vivinosmol/.config/waybar/style.css
[2023-09-16 07:26:45.118] [error] style.css:19:19Expected a number`
The only way to fix it is restoring the old config.

**Comment by prasanthrangan** [comment]
Hi, this was recently updated to a new variable --

```
tooltip {
    background: @main-bg;
    color: @main-fg;
    border-radius: ${t_radius}px;
    border-width: 0px;
}
```
So please use the latest version of `wbarconfgen.sh` and `wbarstylegen.sh` in `~/.config/hypr/scripts/`

**Comment by IgLocoXD** [comment]
> Hi, this was recently updated to a new variable --
> 
> ```
> tooltip {
>     background: @main-bg;
>     color: @main-fg;
>     border-radius: ${t_radius}px;
>     border-width: 0px;
> }
> ```
> 
> So please use the latest version of `wbarconfgen.sh` and `wbarstylegen.sh` in `~/.config/hypr/scripts/`

Alright! I'm going to test it and see if it works now, if it works I will close the Issue

**Comment by IgLocoXD** [comment]
Yeah! It worked, although I have another issue I would like to fix tbh....
But I will make another one for that
