### ISSUE TITLE
keyboard layout changing bind

### ISSUE THREAD

**Issue by wemmmm** [prasanthrangan/hyprdots#221]
bind for changing keyboard layout not work
![image](https://github.com/prasanthrangan/hyprdots/assets/145137550/4971e9fb-5994-4a47-ae4e-5817a9ca1fdc)

**Comment by prasanthrangan** [comment]
hmm, is this the correct `hyprland.conf` file in `.config/hypr/` ?

**Comment by wemmmm** [comment]
in the home path i have only:
![image](https://github.com/prasanthrangan/hyprdots/assets/145137550/77914a9b-97e3-4334-ae29-810fe2acc836)

**Comment by Lol-Lap** [comment]
> in the home path i have only: ![image](https://user-images.githubusercontent.com/145137550/268490454-77914a9b-97e3-4334-ae29-810fe2acc836.png)

in the home path on dolphin press CTRL + H to show hidden files the go to .config/hypr/

**Comment by Lol-Lap** [comment]
> in the home path i have only: ![image](https://user-images.githubusercontent.com/145137550/268490454-77914a9b-97e3-4334-ae29-810fe2acc836.png)

In the home path in dolphin press CTRL + H to show hidden files then go to .config/hypr/

**Comment by wemmmm** [comment]
Working
