### ISSUE TITLE
switch menubar key has changed and how to open game launcher?

### ISSUE THREAD

**Issue by nx-smul** [prasanthrangan/hyprdots#222]
![image](https://github.com/prasanthrangan/hyprdots/assets/68707319/01d3bc8a-4886-4d6c-ba84-00dcfa64194f)
this has changed and how to open game launcher? :D
also kindly fix this for 1080p screen 
![image](https://github.com/prasanthrangan/hyprdots/assets/68707319/6e716590-9469-4774-8ea5-7ca427b4335b)

**Comment by stove-jeebs** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/77e84cba-abd3-481a-bf86-763342f548c8)

right/middle click to switch menubar and left click to open quickapps

**Comment by nx-smul** [comment]
go it

**Comment by prasanthrangan** [comment]
> right/middle click to switch menubar and left click to open quickapps
> but yeah... I agree this is kind of confusing since the tooltip still displays "switch menubar"

Think I'll re-arrange it, `left/right click` to change waybarmode and `middle click` for quick launch

**Comment by prasanthrangan** [comment]
> this has changed and how to open game launcher? :D

You'll need steam game installed, and then run this -
```
./gamelauncher.sh <n> # where n is style [1-4] 
```

**Comment by nx-smul** [comment]
> > right/middle click to switch menubar and left click to open quickapps
> > but yeah... I agree this is kind of confusing since the tooltip still displays "switch menubar"
> 
> Think I'll re-arrange it, `left/right click` to change waybarmode and `middle click` for quick launch

Maybe change the echo message will be enough. And can you found a way to add more apps to quick launch? That will be handy.

**Comment by nx-smul** [comment]
> > this has changed and how to open game launcher? :D
> 
> You'll need steam game installed, and then run this -
> 
> ```
> ./gamelauncher.sh <n> # where n is style [1-4] 
> ```

I found another way using rofi games plugins. And it works with your themes 😀

**Comment by prasanthrangan** [comment]
> Maybe change the echo message will be enough. And can you found a way to add more apps to quick launch? That will be handy.

this is done, you can set your own apps as below in `~/.config/waybar/modules/wbar.jsonc`  -

```
"on-click-middle": "sleep 0.1 && ~/.config/hypr/scripts/quickapps.sh kitty firefox spotify code dolphin",
```

> I found another way using rofi games plugins. And it works with your themes 😀

awesome, glad it works!

**Comment by nx-smul** [comment]
al rit am closing this thanks.
