### ISSUE TITLE
Certain themes (or even all) Make the apps being less brighter.

### ISSUE THREAD

**Issue by IgLocoXD** [prasanthrangan/hyprdots#224]
When I'm using Hyprdots without having the app in fullscreen, I can sometimes see the app itself have a blur effect, that, although its nice, it can make sometimes all the apps that are not in fullscreen have their brightness lowed down, this happens mostly in themes with darker colors.

Using Mesa drivers and a Radeon 6660.

**Comment by stove-jeebs** [comment]
you can change the opacity of windows in ~/.config/hypr/windowrules.conf

**Comment by IgLocoXD** [comment]
> ~/.config/hypr/windowrules.conf

huh, it worked, now the other (and last thing) im trying to do, its neofetch using the gif folder instead of the png one, but it never load anything

**Comment by stove-jeebs** [comment]
I'm not sure this is possible tbh. Does neofetch support animating gifs?

**Comment by prasanthrangan** [comment]
I don't think its possible in neofetch, but you can directly show the gifs in kitty with `icat` -
```
kitten icat --align left $(find $HOME/.config/neofetch/gifs/ -name "*.gif"
```
