### ISSUE TITLE
gpuinfo not working

### ISSUE THREAD

**Issue by chcknsld** [prasanthrangan/hyprdots#225]
![230917_09h49m46s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/61536915/36761ab7-34e0-4ba3-8068-96672e531f2b)

![230917_09h57m52s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/61536915/a35fcee5-c07b-4596-b501-23dcbf0963f6)

Is there supposed to be a package I have to install first in order for this to work?

**Comment by prasanthrangan** [comment]
hmm no, as you have amd gpu, the nvidia packages are not expected to be installed, so the script should be detecting it... This is a bug...

**Comment by katsuja** [comment]
> AMD-Pro drivers

It doesn't work for me either. I also tried with AMD-Pro drivers with the same result.

**Comment by T-Crypt** [comment]
I can fix this tomorrow morning. — looks like the AMD gpu_info is probably grabbing from the wrong location.

I don’t have a AMD GPU to verify but I can do a script refresh tomorrow.


Trevin Tindall

Service Desk Engineer II

O: 800-659-3705

***@***.***

www.xceptional.com<http://www.xceptional.com/>


Embrace the Xceptional Experience

10089 Willow Creek Road, Suite 100

San Diego, CA 92131



1079 S Hover Street, Suite 200

Longmont, CO 80501




________________________________

**Comment by T-Crypt** [comment]
I can fix this tomorrow morning. — looks like the AMD gpu_info is probably grabbing from the wrong location. 

I don’t have a AMD GPU to verify but I can do a script refresh tomorrow.

**Comment by T-Crypt** [comment]
Sorry -- Family emergency yesterday.. Working on this now

**Comment by chcknsld** [comment]
> Sorry -- Family emergency yesterday.. Working on this now

Hey it's okay, man. Take your time. I hope everything turns out alright for you and your family.

**Comment by prasanthrangan** [comment]
> Sorry -- Family emergency yesterday.. Working on this now

Relax brother, take care of yourself and family...

**Comment by T-Crypt** [comment]
I'm almost done! This was more work than I thought lol -- but im about to submit my PR

**Comment by katsuja** [comment]
> I'm almost done! This was more work than I thought lol -- but im about to submit my PR
> 
> **DONE



I just updated to your commit and get this result:
![230919_21h58m21s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/c183d9d7-5691-4f5a-a1f0-e496befb3809)

**Comment by T-Crypt** [comment]
Do you have an AMD integrated?

**Comment by katsuja** [comment]
> Do you have an AMD integrated?
> 
> Running into a lot of road blocks on the ability to get a grepable output for the AMD integrated -- may be the same for the intel gpu -- haven't tested yet

Yes I have an integrated AMD on an laptop serface 4 AMD

❯ lspci -v | grep -A 12 "VGA controller"
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev e3) (prog-if 00 [VGA controller])
	Subsystem: Microsoft Corporation Renoir
	Flags: bus master, fast devsel, latency 0, IRQ 47
	Memory at 2b0000000 (64-bit, prefetchable) [size=256M]
	Memory at 2c0000000 (64-bit, prefetchable) [size=2M]
	I/O ports at 1000 [size=256]
	Memory at f1300000 (32-bit, non-prefetchable) [size=512K]
	Capabilities: <access denied>
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu

03:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Renoir Radeon High Definition Audio Controller
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Renoir Radeon High Definition Audio Controller

**Comment by T-Crypt** [comment]
https://github.com/Umio-Yasuno/amdgpu_top

im working on integrating this package into the script as its the only greppable format cli tool for amd gpu's that i've found

amdgpu_top -J >>> puts in json format. Need a little time to dial it in!!

**Comment by chcknsld** [comment]
Here's the result on my end

![230920_09h54m28s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/61536915/96a1d1d6-425a-480f-8c34-6d3ec3dcb91e)

**Comment by katsuja** [comment]
> Do you have an AMD integrated?
> 
> Running into a lot of road blocks on the ability to get a grepable output for the AMD integrated -- may be the same for the intel gpu -- haven't tested yet

I also get the same result on the desktop with discrete AMD GPU:
![230920_13h54m09s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/3ccc2fec-3975-4b03-8606-19ea971e4c91)
If you want I can act as a guinea pig with the desktop.
Maybe I'll sell the laptop today :)

**Comment by T-Crypt** [comment]
Can you go to my repo and clone and run the install script so I don't have to open a PR until it is ready?

I have updated the script to use amdgpu_top and formatted the output similar to the nvidia-smi output.

REPO: https://github.com/T-Crypt/hyprdots

**Comment by T-Crypt** [comment]
for first use make sure to run ./gpuinfo.sh and it will install the needed packages.

**Comment by katsuja** [comment]
> for first use make sure to run ./gpuinfo.sh and it will install the needed packages.

I get this:
![230920_18h53m14s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/a4bd6ef9-9edf-428a-9153-746d08e2cc5e)

**Comment by T-Crypt** [comment]
Do you get an ouput with running  `amdgpu_top -d`

**Comment by katsuja** [comment]
![230920_19h46m45s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/2958ab99-0eff-4aa6-bc22-b2a04b1009b4)
![230920_19h46m55s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/b7f19f91-e78e-49fa-8395-184fb78d1fe1)

**Comment by T-Crypt** [comment]
Okay try now from my commit - 9 minutes ago.

**Comment by katsuja** [comment]
![230920_23h02m03s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/74f707bf-368d-4a73-a999-f0a3a83214b4)

**Comment by T-Crypt** [comment]
Yeah I need to refine the script today / tomorrow to get this working. I've got mostly there -- When I actually echo the $gpu_info_amd -- it seems to produce the output for the script but for some reason messes up the whole waybar gpu module as I believe the output is not formatted correctly in "json" like the gpuinfo.jsonc has it formatted. 

I apologize for the issues guys, working hard on getting this to work for AMD gpu's and integrated as well -- seems nvidia was straight forward were as AMD wants me to jump through hoops for the needed stats.

**Comment by prasanthrangan** [comment]
Thank you bro, I think amd should be straight forward without the amd_top, you could try [these](https://wiki.archlinux.org/title/AMDGPU#Manually) files. Please lemme know if you need anything from me

**Comment by prasanthrangan** [comment]
cool, there is also this [nvtop](https://github.com/Syllo/nvtop)... I've not tried this, but you can check it out if you find it useful... it shows gpu info for all nvidia/intel/amd cards.

There is also python libraries available from gpu vendors that can be used in a python script to fetch the gpu info.. i might mess around with it later when i get some time!

**Comment by T-Crypt** [comment]
I updated the script 

https://github.com/T-Crypt/hyprdots/blob/main/Configs/.config/hypr/scripts/gpuinfo.sh

my next option is like you said python libraries:

1. https://pypi.org/project/amdgpu-stats/
2. https://pypi.org/project/pyamdgpuinfo/

**Comment by T-Crypt** [comment]
I've got it working with Python!! 

Now I just need to modify the original script to call for this in:

amd_info=$(python3 ~/.config/hypr/scripts/amdgpu.py)

![230921_11h44m06s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/132922589/8b59c731-cc5a-46e7-8e76-8ba8c7b6535c)

**Comment by T-Crypt** [comment]
can one of you try with your AMD gpu to the updated commits.

**Comment by katsuja** [comment]
No icon in waybar after reboot. What you see is the CPU temperature (screenshot).
Now the shell shows signs of life :)
When I launch the script from the terminal it always reinstalls python-pyamdgpuinfo then prints the output (screenshot)

![230921_22h46m31s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/e09618ab-d698-4f7d-bdb5-f83e5f1f1a78)
![230921_22h46m52s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/cecebdd7-ac71-4a4b-9725-4699bbc76422)

**Comment by T-Crypt** [comment]
Okay I removed the install function and placed python-pyamdgpuinfo in custom_hypr.lst so it doesn't try to reinstall over and over.

**Comment by katsuja** [comment]
Works!
Thank you :)
![230922_14h00m17s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/e793f661-315a-4fea-8324-268c6cc7bd18)

**Comment by T-Crypt** [comment]
Ill fix the MHz / GHz format today so that is resolved!! 

Finally got this working -- Makes me happy!

**Comment by katsuja** [comment]
If it's not a problem, I would like to point out that there are problems with Intel GPUs too:
![230922_16h28m54s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/d960e85d-4d81-4e2f-be66-0256cb10b709)
![230922_16h29m26s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/a0d773dd-b695-4396-ba06-4186a5665ecc)

**Comment by T-Crypt** [comment]
Yeah -- that's the next hurdle for today's resolve!! 

Ill work on this now, it may require python as well to integrate the results.

**Comment by katsuja** [comment]
ok! I am available in case of testing.

**Comment by T-Crypt** [comment]
> I noticed it now that there are both Mhz and Ghz units :)

I updated this in the pull request -- just need to update to the latest commit :)

**Comment by T-Crypt** [comment]
Can you do me a favor and use this command and paste your output? I dont have an intel device to test on with arch or linux --- Just WSL :( my main is a nvidia and AMD apu 

run this in terminal

`sensors`

**Comment by katsuja** [comment]
I noticed that it doesn't reveal the intel gpu temp. I did not notice that. I installed arch linux on this laptop yesterday
To you.
Anyway, here's the output:
![230922_16h51m28s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/898baf1d-98fe-4b58-a4b7-1cf2ef9d2820)

**Comment by katsuja** [comment]
Now I have to go out.
Later :)

**Comment by T-Crypt** [comment]
I need someone to run this with a intel integrated GPU

`yes | sudo sensors-detect`

**Comment by katsuja** [comment]
I ran "yes | sudo sensors-detect" but it doesn't reveal the igpu temp.
I'll look around to see if I can find a solution for this damn sensor. :)
![230922_17h57m58s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/c3e1fa2e-eac8-4078-94d6-3434d550eb78)

**Comment by T-Crypt** [comment]
I think its because its handled with a ACPI sensor.. 

this one is a little more complicated

**Comment by katsuja** [comment]
CPU and GPU temperatures are the same thing, they both live on the same piece of silicon. (quote https://bbs.archlinux.org/viewtopic.php?id=223852)
Is flawless

**Comment by T-Crypt** [comment]
> CPU and GPU temperatures are the same thing, they both live on the same piece of silicon. (quote https://bbs.archlinux.org/viewtopic.php?id=223852)
Is flawless


I think it is fair to say that for Intel igpu's the coretemp of the CPU package ID 0: will most likely be 5°C higher or lower than the igpu sensor temp. Of course, only to a degree as the proximity would necessarily even things out, but still they can heat up differently. 

For now you can at least monitor the whole package temp with this updated script in my test branch! You want to download this script and run this on your intel machine to see what result you get?

https://github.com/T-Crypt/hyprdots/blob/test/Configs/.config/hypr/scripts/gpuinfo.sh

**Comment by katsuja** [comment]
ok I'll try now

**Comment by katsuja** [comment]
![230922_18h54m47s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/5f0950f7-0896-4604-a6ec-9959a86e31ed)

**Comment by T-Crypt** [comment]
Can you make sure this returns results first? Looks like my conditional statements weren't set properly!

lspci -v | grep -A 12 "VGA controller"

**Comment by katsuja** [comment]
![230922_19h06m16s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/5340bfe1-1d41-4cad-a14b-51aadd172c09)

**Comment by T-Crypt** [comment]
Try with this one now that its updated -- sorry, I really need to get one of my intel laptops setup with linux but I haven't had the time!

https://github.com/T-Crypt/hyprdots/blob/test/Configs/.config/hypr/scripts/gpuinfo.sh

**Comment by T-Crypt** [comment]
Make sure your using the script from my test branch and not the main!!

**Comment by katsuja** [comment]
> Make sure your using the script from my test branch and not the main!!

Yes, certainly.
Now I try

**Comment by katsuja** [comment]
![230922_19h44m21s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/ca169005-c618-4099-b07d-2f74f7fc0704)
![230922_19h45m10s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/ee1b55d7-a1e8-46a5-aff7-5f45434f974a)

**Comment by katsuja** [comment]
The notification says amd but I'm on the laptop with only the integrated igpu.

**Comment by katsuja** [comment]
![230922_19h49m52s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/c1d7a2e6-363d-4be3-8124-116d665ddc8e)

**Comment by T-Crypt** [comment]
Hmm.. This is odd -- I think one of my conditional statements is causing it to think its an AMD GPU. 

let me refine this so we can at least get a temperature reading for intel cpus/gpus.

**Comment by T-Crypt** [comment]
Can you try with the updated script that prioritizes Intel first then falls back to AMD? 

https://github.com/T-Crypt/hyprdots/blob/test/Configs/.config/hypr/scripts/gpuinfo.sh

**Comment by katsuja** [comment]
same thing
![230922_22h49m17s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/c7fc9f5d-63b0-42b3-a305-20a35ad09f80)

**Comment by T-Crypt** [comment]
@katsuja 

can you try my updated script? Sorry for the delay, Im usually busy on the weekends!

https://github.com/T-Crypt/hyprdots/blob/test/Configs/.config/hypr/scripts/gpuinfo.sh

**Comment by T-Crypt** [comment]
@katsuja 

Can you test with this updated script? Sorry Im usually busy on the weeks so sorry for the delay!

https://github.com/T-Crypt/hyprdots/blob/test/Configs/.config/hypr/scripts/gpuinfo.sh

**Comment by katsuja** [comment]
> @katsuja
> 
> Can you test with this updated script? Sorry Im usually busy on the weeks so sorry for the delay!
> 
> https://github.com/T-Crypt/hyprdots/blob/test/Configs/.config/hypr/scripts/gpuinfo.sh



Imagine no problem. We all have a life :). Then you do all the work, I just have to try :)
It does not work. :(
![230925_17h45m23s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/56fca752-075b-443a-8b7c-6c5b80fdf470)
![230925_17h45m30s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/badbe7e8-cb8c-44c0-b580-e559ea6fb35a)

**Comment by T-Crypt** [comment]
Okay can you download again and try?

https://github.com/T-Crypt/hyprdots/blame/test/Configs/.config/hypr/scripts/gpuinfo.sh

I added:

```
else
  # Check for Intel GPU
  intel_gpu=$(lspci -nn | grep -i "VGA compatible controller" | grep -i "Intel Corporation" | awk -F' ' '{print $1}')
  if [ -n "$intel_gpu" ]; then
    primary_gpu="Intel GPU"

**Comment by katsuja** [comment]
Like before. Icon in the waybar without indications and script same thing.
![230925_18h23m11s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/5a9ce910-c652-4fee-b391-a46416d31781)

**Comment by T-Crypt** [comment]
Is it returning anything from this command?

`lspci -nn | grep -E "VGA|3D controller" | grep -i "AMD"`

**Comment by T-Crypt** [comment]
Its stating AMD gpu so I feel like something is being pulled from the `check_amd_gpu` function.

**Comment by T-Crypt** [comment]
Do you have a device in 

`/sys/class/drm/` -- Labeled card0?

**Comment by katsuja** [comment]
This is the result on desktop with dedicated GPU:

![230925_18h34m47s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/f7970f1c-7597-4d27-b1f2-a5d8e6e6cf4e)
![230925_18h36m45s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/f3135be1-fb5f-4453-b011-a0c915ce80ff)

Then I'll give you the one with Intel integrated.

**Comment by katsuja** [comment]
This is the result on laptops with integrated Intel GPU.
Icon has but no info
![230925_18h40m03s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/00acc0f3-e532-41e0-821a-b67ec00e92c1)

**Comment by T-Crypt** [comment]
I'm really not sure if its possible to get the GPU temperature for the intel HD graphics... I think its just going to have to stay supporting AMD and Nvidia only for now until I can figure this out without relying on your system to provide details I need. 

>1. It is worth mentioning that the processor graphics is integrated (built-in) in the processor itself. In other words, the integrated graphics is on the same die as the CPU cores, and other components found on the processor die.

> 2. There are thermal sensors within a CPU, one in each CPU core, but there is no thermal sensor for the Intel® Processor Graphics.

Reference: https://community.intel.com/t5/Graphics/Hello-how-can-i-monitor-HD-620-GPU-temperature/td-p/662714

**Comment by T-Crypt** [comment]
Can you just verify the module populates in the waybar when using the previous script from last week on your AMD system?

https://github.com/T-Crypt/hyprdots/blob/main/Configs/.config/hypr/scripts/gpuinfo.sh

**Comment by katsuja** [comment]
I figured he might have problems with a laptop that can't even read the gpu temperature.
Of course yes.
![230925_19h00m11s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/1e49ba72-eb90-4277-9f4b-63b2f2e96f7c)
It's going great!

**Comment by T-Crypt** [comment]
Feel free to try this updated script on the intel system -- I just don't have a lot of faith in Intel iGPU's anymore... SMH 

https://github.com/T-Crypt/hyprdots/blob/test/Configs/.config/hypr/scripts/gpuinfo.sh

I added below (check for AMD temperature reading -- if temperature is present then AMD is primary)

```
  if [ -n "$temperature" ]; then
    primary_gpu="AMD GPU"

**Comment by katsuja** [comment]
> Feel free to try this updated script on the intel system -- I just don't have a lot of faith in Intel iGPU's anymore... SMH
> 
> https://github.com/T-Crypt/hyprdots/blob/test/Configs/.config/hypr/scripts/gpuinfo.sh
> 
> I added below (check for AMD temperature reading -- if temperature is present then AMD is primary)
> 
> ```
>   if [ -n "$temperature" ]; then
>     primary_gpu="AMD GPU"
> ```

I think there are some improvements. The icon appears with the heading intel.
Here are the screenshots.
![230925_21h51m04s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/59b30a7e-1fcd-41dd-aa45-e4c0e292cb7c)
![230925_21h51m16s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/4a3732cc-cf79-4415-8c9e-f7c94b9a6cd3)

**Comment by T-Crypt** [comment]
updated the intel get temperature function!

https://github.com/T-Crypt/hyprdots/blob/test/Configs/.config/hypr/scripts/gpuinfo.sh

**Comment by katsuja** [comment]
works! Good job :)
![230925_23h38m50s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/f47108ef-8131-4524-9045-06498c4fb18c)
![230925_23h40m17s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/2d3f2c66-063c-4e31-a3e5-b05d1fec10d6)

**Comment by T-Crypt** [comment]
Very nice! let me just remove that .0 on there!

**Comment by T-Crypt** [comment]
Done -- Updated the PR -- Its ready to merge!! 

We can also close this out now @chcknsld

**Comment by chcknsld** [comment]
Hey, man. Thanks for all the hard work that you did but here's what I got from my end using the latest commit. I already installed python-pyamdgpuinfo.

![230926_08h03m46s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/61536915/7fff64b9-96bf-4fdb-aba1-285c46a8f346)

I got some results with amdgpu.py tho..

![230926_08h04m36s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/61536915/f997eece-25c5-45c9-a045-c43c3d5ad709)

**Comment by T-Crypt** [comment]
@chcknsld -- This is odd, seemed to be working on @katsuja's system with a dedicated GPU.

Let me see what else I can do to troubleshoot this.

**Comment by T-Crypt** [comment]
@chcknsld can you use my debugging script to get an output? and paste that here? 

https://github.com/T-Crypt/hyprdots/blob/test/Configs/.config/hypr/scripts/gpuinfo.sh

**Comment by chcknsld** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/61536915/046f7e88-609f-49e0-b6c3-6b7ea358c9b6)

**Comment by T-Crypt** [comment]
Looks like its not running the script at all.

can you run:

python3 ~/.config/hypr/scripts/amdgpu.py

**Comment by T-Crypt** [comment]
Also make sure the script is executable!

`chmod +x ~/.config/hypr/scripts/amdgpu.py` (not sure how you updated your dots, by default all the scripts are executable but if you downloaded it and replaced the file then it needs to be executable!)

**Comment by chcknsld** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/61536915/b7d6453e-e1b4-4bc6-a043-b81da3c21ab1)

I haven't pulled the whole dots repository yet. I only downloaded the files involved (gpuinfo.sh, amdgpu.py) from yours then set the necessary perms to make them executable.

**Comment by T-Crypt** [comment]
can you run this whole line as this is what is called in the script? Looks like yours for some reason in the script is reporting empty.. 

`python3 ~/.config/hypr/scripts/amdgpu.py`

you can just copy and paste that whole line. Make sure that is running, Ill add another debug statement this morning for testing after this!

**Comment by chcknsld** [comment]
Like this?

![image](https://github.com/prasanthrangan/hyprdots/assets/61536915/4232a4e2-d719-4da4-948a-101feea1ba65)

**Comment by katsuja** [comment]
> @chcknsld -- This is odd, seemed to be working on @katsuja's system with a dedicated GPU.
> 
> Let me see what else I can do to troubleshoot this.

I confirm that it works with AMD dedicated GPU (RX580) and also works on Intel integrated GPU (Noteook Lenovo T450)

**Comment by T-Crypt** [comment]
Yeah it also is working when he runs the script manually -- So something in the script is causing it to not run the execute_amd_script function!

Im busy today with work -- but i will grab this and work on debug statement when i can!!

**Comment by chcknsld** [comment]
@katsuja 
I also have the same AMD GPU. I wonder if there's something wrong with my configs. Although I did not install or change any GPU related stuff except the ones mention here (python-pyamdgpuinfo). I did set a kernel command line parameter (**amdgpu.ppfeaturemask=0xffffffff**) to use [amdgpu-clocks](https://github.com/sibradzic/amdgpu-clocks) but I don't think it's really related. 

@T-Crypt 
Alright, man. Just hmu. I'll do my best to respond ASAP because we're on a different timezone and I'm busy with work too.

**Comment by katsuja** [comment]
> @katsuja I also have the same AMD GPU. I wonder if there's something wrong with my configs. Although I did not install or change any GPU related stuff except the ones mention here (python-pyamdgpuinfo). I did set a kernel command line parameter (**amdgpu.ppfeaturemask=0xffffffff**) to use [amdgpu-clocks](https://github.com/sibradzic/amdgpu-clocks) but I don't think it's really related.
> 
> @T-Crypt Alright, man. Just hmu. I'll do my best to respond ASAP because we're on a different timezone and I'm busy with work too.

The only thing I installed is opencl-amd to have output to the clinfo command that was required in the old script:
![230928_15h50m07s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/da74721d-e339-4615-b65d-04e77e67222c)

![230928_15h55m37s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/6b44db61-ed08-4fbf-b34b-b81786bd40da)
![230928_15h50m07s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/02aa1784-267d-42bf-b4de-7750180233a4)

I don't use grub but the uki method and I don't use any arguments regarding the amd gpu:

![230928_15h52m46s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/19fee6b5-8243-4414-8604-361e8aab2005)

I don't use grub but the uki method and I don't use any arguments regarding the amd gpu:

**Comment by chcknsld** [comment]
Just installed opencl-amd..

![image](https://github.com/prasanthrangan/hyprdots/assets/61536915/b176e598-1dc7-4916-9b72-5f25edaa8b4b)

..still got nothing.

![image](https://github.com/prasanthrangan/hyprdots/assets/61536915/045e4881-25e0-41e2-8ea4-5dabf6254666)

What drivers are you using?

**Comment by katsuja** [comment]
> Just installed opencl-amd..
> 
> ![image](https://user-images.githubusercontent.com/61536915/271324930-b176e598-1dc7-4916-9b72-5f25edaa8b4b.png)
> 
> ..still got nothing.
> 
> ![image](https://user-images.githubusercontent.com/61536915/271325725-045e4881-25e0-41e2-8ea4-5dabf6254666.png)
> 
> What drivers are you using?

I use open drivers and active HOOKS array in /etc/mkinitcpio.conf MODULES=(amdgpu)

**Comment by katsuja** [comment]
![230928_20h10m40s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/ad487960-512f-41bc-9b40-9b6c8825aab4)

**Comment by katsuja** [comment]
> Just installed opencl-amd..
> 
> ![image](https://user-images.githubusercontent.com/61536915/271324930-b176e598-1dc7-4916-9b72-5f25edaa8b4b.png)
> 
> ..still got nothing.
> 
> ![image](https://user-images.githubusercontent.com/61536915/271325725-045e4881-25e0-41e2-8ea4-5dabf6254666.png)
> 
> What drivers are you using?

Driver open

**Comment by T-Crypt** [comment]
@chcknsld Yeah I think jq is missing here -- `sudo pacman -S jq`

**Comment by chcknsld** [comment]
Got some positive results now after installing jq!

![image](https://github.com/prasanthrangan/hyprdots/assets/61536915/f27e6d00-8521-491d-bf68-96e2c23974f1)

But now it's not showing up on waybar..

![image](https://github.com/prasanthrangan/hyprdots/assets/61536915/c888515a-06f2-4a53-ab7c-4c8ac84420a5)

This is on the newest waybar commit though. I just updated my system yesterday.  Or is it because this is a debugging script that I am using right now?

**Comment by T-Crypt** [comment]
It’s probably due to the debugging section that is echoing the temperature.

Let me remove that and give you the updated script or you can grab the script from my main branch on my page.


Trevin Tindall

Service Desk Engineer II

O: 800-659-3705

***@***.***

www.xceptional.com<http://www.xceptional.com/>


Embrace the Xceptional Experience

10089 Willow Creek Road, Suite 100

San Diego, CA 92131



1079 S Hover Street, Suite 200

Longmont, CO 80501




________________________________

**Comment by T-Crypt** [comment]
Can you update your gpuinfo.sh to this script in my main repo?

https://github.com/T-Crypt/hyprdots/blob/main/Configs/.config/hypr/scripts/gpuinfo.sh

**Comment by chcknsld** [comment]
It's working now! Thank you so much! So that was the only thing that's missing. Just the "jq" package. lol

![230930_08h42m01s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/61536915/2fd6d3a0-8610-4588-85dc-942482d7eafc)

**Comment by T-Crypt** [comment]
Merged into the main branch now!! We can close this issue ❤️

**Comment by chcknsld** [comment]
Closing this now. Thank you, guys. Especially @prasanthrangan and @T-Crypt! Y'all are doing an excellent job with this repo!

**Comment by kRHYME7** [comment]
Hello, got a unified solution that is fundamentally based on @T-Crypt's script. This one is discussed in #643 . 
This uses flags to query all 3 GPUs, if can't detect it will use sensors as a generic query. 
If 2 GPUs are detected you can toggle it to use the other.
The priority GPU will be queried therefore it won't always query for other GPUs. 
I hope someone can test it Here. Thank you!

This should prevent some parsing errors if a value is not present.

**Comment by T-Crypt** [comment]
@kRHYME7 -- Ill test this out in a second, I have a Nvidia and AMD gpu systemt to test on
