### ISSUE TITLE
Dolphin places issue

### ISSUE THREAD

**Issue by mahaveergurjar** [prasanthrangan/hyprdots#228]
![230917_15h34m43s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/aa337533-c88d-4813-8403-46877949b7e4)

Places don`t show completely 

like this 
![230917_15h35m37s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/149e137e-090b-4713-b2bc-0f2c5f70bd92)

I expand more when reopen automatically sets the default setting I can't change this panel
and also please tell me how to place this panel on the left side

**Comment by prasanthrangan** [comment]
you can unlock the plane and adjust the height and width of these plane.
you can drag it to the left as well.

**Comment by mahaveergurjar** [comment]
Okay
