### ISSUE TITLE
Screen Capture Not Saving

### ISSUE THREAD

**Issue by i5hi** [prasanthrangan/hyprdots#229]
Hi! Firstly a big thank you for sharing your config. Been using it for a little over a week now and its been great. 

When using the `Super + P` keybinding to capture a part of the screen, the `Save Surface` button does not save and gives no feedback.

**Comment by stove-jeebs** [comment]
The screenshots should be saved at ~/Pictures by default.

**Comment by katsuja** [comment]
I solved it like this:
![230918_02h18m21s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/cbe1f366-e279-4797-b3c1-8bc7f70fcd86)

**Comment by i5hi** [comment]
Thanks for all the responses! And the reminder that most of my answers are in the config files xD

It doesn't default to Pictures for me. Will investigate the config and find where its currently being saved.

**Comment by i5hi** [comment]
okay it works -_- goes into ~/Pictures.

**Comment by prasanthrangan** [comment]
> Hi! Firstly a big thank you for sharing your config. Been using it for a little over a week now and its been great.
> 
> When using the `Super + P` keybinding to capture a part of the screen, the `Save Surface` button does not save and gives no feedback.

Thank you so much!

Ive added notification for `Save Surface`  when you exit swappy
