### ISSUE TITLE
HiDPI

### ISSUE THREAD

**Issue by amedeo** [prasanthrangan/hyprdots#23]
Over the past few days, I have been experimenting with the configuration files in order to achieve a specific goal: using a 4k resolution with a **scale of 1** that is easily readable.

When using one of the current beautiful themes in a 4k resolution, unfortunately the experience is not pleasant to the eyes. To address this, I started by cloning the Mocha theme and creating a version specifically designed for 4k displays called Mocha-4k. Following the theming guide, I have successfully made adjustments in various areas such as the top menu, kitty, rofi, kvantum, and more.

![output](https://github.com/prasanthrangan/hyprdots/assets/8573/66e064ca-9cf7-4b88-a67a-5bc78bfb875d)

However, considering the repetitive nature of this process and my desire to not be limited to just one theme for 4k, I am seeking a more generic approach to configure this fantastic Hyprland setup for HiDPI displays. 

What could be a suitable approach? Should I use a procedure involving multiple `sed` instructions to switch back and forth with  HiDPI? Do you have any suggestions? Is it worth pursuing this route?

**Comment by prasanthrangan** [comment]
Hi, thank you for your continuous inputs and suggestions.

I'm using a 1080p (2560x1080) display, so I've no idea how the themes look in 4k or higher resolutions.
So if you could help me out with the changed you made to Mocha-4k theme, maybe we can either,
1. improve the themeswitch script to detect screen resolution and dynamically adjust the config files.
2. develop a 4k theme template and script to clone and convert any existing theme like Mocha to Mocha-4k

Please lemme know your thoughts.

**Comment by amedeo** [comment]
Sure! Here is an incomplete list of files from the sample 4k theme I was working on before you made the main refactoring on the waybar. Please note that this should not be considered a final product by any means.

[draft_4k_theme.tar.gz](https://github.com/prasanthrangan/hyprdots/files/11890774/draft_4k_theme.tar.gz)

It primarily involved adjusting font sizes, element dimensions, positions, and other factors to enhance the visual experience. 

Your first suggestion sounds fantastic. I noticed that Hyprland tends to scale at 1.5 when set to "auto" for HiDPI resolutions, so I adopted that ratio for my configuration file conversion. 

The reason for having a separate 4k theme instead of scaling everything to 1.5 is because not all applications scale well. Additionally, it helps preserve valuable screen space, which is crucial for apps like Blender and others.

Thank you once again for your ongoing support and assistance with this amazing project.

**Comment by prasanthrangan** [comment]
Cool thanks for sharing the 4k config file.
I'll compare them and try to improve the themeswitch script to adapt screen resolution.
This would take some time and your help to test it in different resolution!

**Comment by prasanthrangan** [comment]
Hi @amedeo ,
I've made few changes to rofi (launcher, clipboard, themeselect)  to use the font size set in the main hypr theme config.
Also for waybar the font size is adapted from the hypr theme in use, while height/icon size adapts to monitor res when its not hardcoded in the control file `~/.config/waybar/config.ctl`
So when you get a chance to test it in 4k, let me know if it scales properly.

**Comment by amedeo** [comment]
Hi @prasanthrangan,

Thanks for all your effort with this enhancement. 

I hope I understood how to "scale" the interface correctly.
I tried doubling all the fonts and cursor dimensions in the Mocha hypr theme to highlight the differences, and below is what I got switching theme from the waybar.

The font size of the waybar was increased and more readable, even if the scaling, I believe, was not complete, as you may see below:

![tl](https://github.com/prasanthrangan/hyprdots/assets/8573/c2b238c6-64b8-4ce0-8d4d-71f122db9ab2)


![tr](https://github.com/prasanthrangan/hyprdots/assets/8573/082d4af1-fd19-4fda-98a5-5104781387e2)


The clipboard changed the font size, but I have noticed no difference with the launcher or theme selector.

![themesel](https://github.com/prasanthrangan/hyprdots/assets/8573/5473a19a-8491-4389-99cc-24416d3ac39d)

![launcher](https://github.com/prasanthrangan/hyprdots/assets/8573/461eada9-3f80-434a-a9c9-2ab519638d1d)



Please let me know if I should investigate something different or operate differently.

**Comment by prasanthrangan** [comment]
Hey, thanks for testing it out!

for waybar, does it look correct when its scaled to 2 like this?

![230702_12h51m07s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/106020512/b6775553-639b-4559-9983-8ea833010441)

For the rofi configs, i think the hardcoded px values we have to use pertages, to maintain correct shape in different res.

**Comment by amedeo** [comment]
Hello! 
I have reset the configuration files to their default settings and attempted scaling factors 1 and 2. As you can observe, the scaling appears balanced in all aspects. 

![topr](https://github.com/prasanthrangan/hyprdots/assets/8573/1543db6d-9f40-4ce7-bf62-bdc5dff05e2e)


Additionally, I made another attempt to modify the font size in the main hypr style to analyze how your script was addressing the scaling aspect. By comparing the scaled versions of the Mocha and Latte, the only noticeable difference was the font size, which was correctly inherited by the main style. However, all other attributes, such as paddings, margins, borders, etc., remained unchanged. This lack of adjustment resulted in an imbalanced scaling, as my previous screenshot shows. 

If you compare the files I shared in the draft 4k theme, you will notice all the values I modified to achieve a consistent scaling effect. I hope this information is helpful. 

Thank you once again for your dedication to this matter.

**Comment by prasanthrangan** [comment]
> Additionally, I made another attempt to modify the font size in the main hypr style to analyze how your script was addressing the scaling aspect. By comparing the scaled versions of the Mocha and Latte, the only noticeable difference was the font size, which was correctly inherited by the main style. However, all other attributes, such as paddings, margins, borders, etc., remained unchanged. This lack of adjustment resulted in an imbalanced scaling, as my previous screenshot shows.

Hi, the adjustments are done on bar height (from control file or screen res), here is the calculation part -

```shell
# calculate values based on height and generate theme style

export b_radius=$(( b_height*70/100 ))   # block rad 90% of height
export e_margin=$(( b_height*30/100 ))   # block margin 30% of height
export e_paddin=$(( b_height*10/100 ))   # block padding 10% of height
export g_margin=$(( b_height*14/100 ))   # module margin 14% of height
export g_paddin=$(( b_height*15/100 ))   # module padding 15% of height
export w_radius=$(( b_height*30/100 ))   # workspace rad 30% of height
export w_margin=$(( b_height*10/100 ))   # workspace margin 10% of height
export w_paddin=$(( b_height*10/100 ))   # workspace padding 10% of height
export w_padact=$(( b_height*40/100 ))   # workspace active padding 40% of height

if [ $e_paddin -le 2 ] ; then
    export e_paddin=0
fi
envsubst < $in_file > $out_file
```
I'm trying to adjust all the values here based on a certain % of bar height.

**Comment by amedeo** [comment]
Hello there! Great news! The waybar has been successfully scaled to perfection. 

I apologize for any previous configuration issues I might have had. I have restored the config files and doubled the font size in the main hypr theme to achieve this result. This is how the waybar now appears. 

![swappy-20230702_163843](https://github.com/prasanthrangan/hyprdots/assets/8573/f7a8924a-07d8-44d0-b7e4-9193202afe87)

Below is the image showcasing the current state of Latte with the original font size. 

![swappy-20230702_164722](https://github.com/prasanthrangan/hyprdots/assets/8573/1144287f-7444-4d9d-8a65-2d5aac1b5922)


Unfortunately, I cannot discern any differences with the launcher or theme selector, and it seems that the tray icons cannot be resized. Thank you for your support!

**Comment by prasanthrangan** [comment]
Hey, 
That waybar looks great now! But not sure why the tray icon is not scaling... 
I'm able to scale the tray cons by either changing height or hardcoding the `icon-size` and `spacing` values in `~/.config/waybar/modules/tray.jsonc`, same can you please try the same.

https://github.com/prasanthrangan/hyprdots/assets/106020512/65d4fafa-9bf3-498e-9bfe-7c65fbe2a974

when using `$i_size` variable, its calculated a s below in `~/.config/waybar/wbarconfgen.sh`, but I don't even remember how i came up with this logic :(
```
export i_size=$(( ((w_height + 2)) * 5 / 10 ))
if [ $i_size -lt 12 ] ; then
    export i_size="12"
fi
```
so you can try adjusting this calculation as well...

> Unfortunately, I cannot discern any differences with the launcher or theme selector, and it seems that the tray icons cannot be resized. Thank you for your support!

Yup, I've not changed the config files for rofi, just implemented the font overrides...

**Comment by amedeo** [comment]
Hi @prasanthrangan ,

I am playing with the latest revision, and it works great, even with icon size. 

I would suggest changing the ratio when height is not set:

```
if [ -z $w_height ] ; then
    y_monres=`cat /sys/class/drm/*/modes | head -1 | cut -d 'x' -f 2`
    export w_height=$(( y_monres * 2 / 100 ))
fi
```
The 3% was producing a too-high and not-balanced bar:

![swappy-20230702_221956](https://github.com/prasanthrangan/hyprdots/assets/8573/e6263017-464c-4bfe-b83e-0ce7bd76969a)
 
Thanks!

**Comment by amedeo** [comment]
Hi @prasanthrangan ,

The dynamic generation you are implementing is brilliant. Instead of generating everything starting from a specific theme's font size, what if we utilize an environment variable defined in the hyprland.conf file? Something like 

`HYPRDOTS_SCALE=1.5 `

This approach would eliminate the need to modify the font size in every theme and make the scaling factor accessible to all the scripts.

Thanks

**Comment by prasanthrangan** [comment]
Hey @amedeo, that's an awesome idea!
You are right, creating an environment variable `HYPRDOTS_SCALE=1.5` would make things easy and accessible to all the scripts, and eliminates the need to read the theme symlink files each time.

**Comment by prasanthrangan** [comment]
Hi,
I gave this a try, but seems like environment variables like this only gets refreshed when the hyprland session is launched... So trying to figure out how to update it dynamically.
