### ISSUE TITLE
Swap memory

### ISSUE THREAD

**Issue by Aman49362** [prasanthrangan/hyprdots#232]
Can you help me increase the swap memory here i am new to linux so i dont know how can i 
![image](https://github.com/prasanthrangan/hyprdots/assets/83559417/83cadda5-1b60-4c99-98f6-700ac106f863)

**Comment by prasanthrangan** [comment]
Hi, if you installed arch with `archinstall`, i think it creates swap partition based on your system ram capacity.
please refer [this](https://wiki.archlinux.org/title/swap)
