### ISSUE TITLE
Japanese font is very poor.

### ISSUE THREAD

**Issue by UleyeyeUwma** [prasanthrangan/hyprdots#233]
The japanese font looks very cool, but it lacks a lot of characters and can lead to some programs being unreadable.

I'm not sure if it's possible to use that font just for some programs like the terminal while using something more reasonable like noto cjk for everything else. If not it'd be amazing to know which font it is to either remove it or creating a preference override as I currently have no clue.

[example of missing characters](https://imgur.com/a/7Gh0Bgp)

**Comment by prasanthrangan** [comment]
Hi, ya the the Japanese font pack i have is an old one and don't think its a complete pack. so please let me know, if you know any free complete font pack.

**Comment by stove-jeebs** [comment]
https://archlinux.org/packages/extra/any/noto-fonts-cjk/

will this do?

**Comment by UleyeyeUwma** [comment]
Hello, yes, noto cjk is a font that is complete. The way I noticed about the missing characters was when I opened Krita and used the animation JP template, the layers were unreadable, some being completely blank and others only having a few characters, then to test for it further I just used Firefox and saw some Japanese text on Twitter.

**Comment by prasanthrangan** [comment]
Thanks for testing it! i'll add noto-fonts-cjk as well!

**Comment by UleyeyeUwma** [comment]
I have to add that even if you install noto-fonts-cjk the problem font still takes priority, which is why I came here for, since I do not know what font is the problematic one to remove or make it take less priority.

**Comment by prasanthrangan** [comment]
> I have to add that even if you install noto-fonts-cjk the problem font still takes priority, which is why I came here for, since I do not know what font is the problematic one to remove or make it take less priority.

its this font Japanese font, you can try removing it manually and rebuild cache -
https://github.com/prasanthrangan/hyprdots/blob/7e9b4ab52fb4e210a6b67aaac85fa9bea8a86abf/Scripts/restore_fnt.lst#L6

I've replaced this with `noto-sans-cjk`

**Comment by prasanthrangan** [comment]
> have plans to add spicetify?

yup, i do... I'd tried it before but it slows down the theme change
