### ISSUE TITLE
Missing script

### ISSUE THREAD

**Issue by katsuja** [prasanthrangan/hyprdots#234]
The testrunner.sh file is missing in the ~/.config/hypr/scripts/ folder referencing line 14 of the userprefs.conf  in ~/.config/hypr/.

**Comment by prasanthrangan** [comment]
Hi, it was intentional...
It was just for me to test every configs/themes/wallpapers, so I'm not sure if it will be of any use to others?!?

**Comment by katsuja** [comment]
> Hi, it was intentional... the `userpref.conf` wont be copied by default, and you can set it to your preference! The testrunner.sh was just for me to test every configs/themes/wallpapers, so I'm not sure if it will be of any use to others?!?



Hi, it was intentional... the userpref.conf wont be copied by default, and you can set it to your preference!
The testrunner.sh was just for me to test every configs/themes/wallpapers, so I'm not sure if it will be of any use to others?!?

**Comment by katsuja** [comment]
> no worries, i've committed it anyways, and disabled it by default... so hopefully no one runs it :)



ha ha I just ran it :) . it's crazy cool!
