### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by katsuja** [prasanthrangan/hyprdots#238]
It will certainly be wrong to write what I'm about to write here but I really don't know where to do it and I apologize in advance.
Unfortunately some governments in recent times are putting the world of open source at risk, and I wanted to thank all of you developers who every day for years have dedicated yourselves with passion and dedication to sharing your immense creativity and knowledge with all of us.
Thank you very much!
This configuration is truly complete, beautiful and fun and constantly improving.
Sorry for my translated English

**Comment by prasanthrangan** [comment]
Thank you so much for your continuous support and kind words!! Means a lot!
