### ISSUE TITLE
in terminal can't use ls command

### ISSUE THREAD

**Issue by ghost** [prasanthrangan/hyprdots#239]
Wheneven i tried to use ls command, i will always have 
![image](https://github.com/prasanthrangan/hyprdots/assets/137838426/07921866-bcc0-4a0c-b575-12dbca807034)

I'm very confused i've checked all .zsh file i can see and didn't found single clue

**Comment by katsuja** [comment]
> .zsh

Updated to the latest commit without any problems.
Try with the original .zsh of the rise and then add your customizations if necessary.
![230918_20h02m11s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/853ea0be-9fe9-4b1b-b558-de4429649bdc)

**Comment by prasanthrangan** [comment]
can you try `\ls` instead, might be issue with eza, so you can try uninstalling it as well...

**Comment by stove-jeebs** [comment]
What do you get from `which eza`?

**Comment by kRHYME7** [comment]
Closing this now as we have been ghosted.
