### ISSUE TITLE
cant install what should i do

### ISSUE THREAD

**Issue by Ooknag** [prasanthrangan/hyprdots#243]
-> error installing: [/home/fooknag/.cache/yay/hyprland-nvidia-git/hyprland-nvidia-git-0.29.1.r92.gd8d0cd75-1-any.pkg.tar.zst /home/fooknag/.cache/yay/wlogout/wlogout-1.1.1-3-x86_64.pkg.tar.zst /home/fooknag/.cache/yay/visual-studio-code-bin/visual-studio-code-bin-1.82.2-1-x86_64.pkg.tar.zst /home/fooknag/.cache/yay/rofi-lbonn-wayland-git/rofi-lbonn-wayland-git-1.7.5.wayland2.r146.gbb856341-1-x86_64.pkg.tar.zst /home/fooknag/.cache/yay/oh-my-zsh-git/oh-my-zsh-git-r6979.cdd7dab5d-1-any.pkg.tar.zst /home/fooknag/.cache/yay/swww/swww-0.8.1-0-x86_64.pkg.tar.zst /home/fooknag/.cache/yay/zsh-syntax-highlighting-git/zsh-syntax-highlighting-git-0.8.0.alpha1.pre.redrawhook.r75.g143b25e-1-any.pkg.tar.zst /home/fooknag/.cache/yay/zsh-theme-powerlevel10k-git/zsh-theme-powerlevel10k-git-r4197.873c4ff0-1-x86_64.pkg.tar.zst /home/fooknag/.cache/yay/zsh-autosuggestions-git/zsh-autosuggestions-git-0.7.0.r12.gc3d4e57-1-any.pkg.tar.zst /home/fooknag/.cache/yay/pokemon-colorscripts-git/pokemon-colorscripts-git-r112.0483c85-1-any.pkg.tar.zst /home/fooknag/.cache/yay/swaylock-effects-git/swaylock-effects-git-r420.7c5681c-1-x86_64.pkg.tar.zst /home/fooknag/.cache/yay/nwg-look/nwg-look-0.2.4-1-x86_64.pkg.tar.zst] - exit status 1

**Comment by jpx40** [comment]
hey , what distro are u using?

**Comment by Ooknag** [comment]
Endeavour os

**Comment by Clutchnp** [comment]
I think you This is because you ran the script as root as al the packages with yay were failed , I think the solution would be to run install_pkg.sh without root

**Comment by prasanthrangan** [comment]
> Endeavour os

Hi, are you able to install anything with yay ?
can you try installing one manually, like this for example -
```
yay -S  hyprland-nvidia-git
```

**Comment by Ooknag** [comment]
yeah i try and i can install the hyprland-nvidia-git

**Comment by Ooknag** [comment]
also i run install_pkg.sh without root still the same error :(

**Comment by prasanthrangan** [comment]
hi, can you try installing the package manually using `yay`?
this does not seem to be an issue with install script...

**Comment by devCKVargas** [comment]
> also i run install_pkg.sh without root still the same error :(

Have you tried `paru`?

I used `yay-git` on Endeavour and It went smooth.

**Comment by kRHYME7** [comment]
@Ooknag  Feel free to reopen this issue.
