### ISSUE TITLE
Default Wallpaper On Resolution Change

### ISSUE THREAD

**Issue by TZProgrammer** [prasanthrangan/hyprdots#254]
Hello there,

First of all, amazing rice, thank you for providing us with this amazing config.

I have noticed a small bug on my setup. When I change the resolution in hyprland.conf, the wallpaper changes to one of the default hyprland wallpapers. This is undone upon using the function to change wallpapers ($mainMod + ALT + Arrowkey for me).

I was wondering if you have any idea why this is happening. I would also say this is low priority since it is easily undone, but maybe someone else is experiencing this as well. 

I am using Arch, if that is in any way relevant.

**Comment by TZProgrammer** [comment]
One more detail that might be relevant. Upon rebooting the system, before the real wallpaper shows up, the default hyperland one is present (and the swww one opens from that). I do not know if that is the intended behaviour of the config, or if this is related to this issue

**Comment by T-Crypt** [comment]
You can disable the hyprland logo with

in ~/.config/hypr/hyprland.conf

misc {
  disable_hyprland_logo = true
}

**Comment by TZProgrammer** [comment]
That fixed it. Thank you!

**Comment by prasanthrangan** [comment]
> I have noticed a small bug on my setup. When I change the resolution in hyprland.conf, the wallpaper changes to one of the default hyprland wallpapers. This is undone upon using the function to change wallpapers ($mainMod + ALT + Arrowkey for me).

hmm this is strange, the swww daemon might be getting killed when you change resolution, next time if this happens please check if the daemon is running with this `swww query`
