### ISSUE TITLE
Waybar issues

### ISSUE THREAD

**Issue by Sitolam** [prasanthrangan/hyprdots#256]
Only 4 of the waybar templates work.

**Comment by T-Crypt** [comment]
Are you using Super + Alt + Up Arrow to switch?

**Comment by Sitolam** [comment]
> Are you using Super + Alt + Up Arrow to switch?

yes

**Comment by Sitolam** [comment]
Don't I have a package or something because I noticed that I needed  `yay` for the systemupdate.sh package but I only had `paru` installed. I installed yay but that still didn't fix the issue of having only 4 waybar templates

**Comment by T-Crypt** [comment]
Can you run 

`/.config/hypr/scripts/wbarconfgen.sh n` and see if the 2 missing styles are generated?

**Comment by prasanthrangan** [comment]
Hi, it might be one of the module that's causing it or the version of script.

so could you run `.config/hypr/scripts/wbarconfgen.sh n` from terminal and check for errors, also please share these files for one of the failed templates -
```
~/.config/waybar/style.css
~/.config/waybar/config.jsonc
~/.config/waybar/config.ctl
```

**Comment by prasanthrangan** [comment]
> Don't I have a package or something because I noticed that I needed `yay` for the systemupdate.sh package but I only had `paru` installed. I installed yay but that still didn't fix the issue of having only 4 waybar templates

yup, i'll update the systemupdate.sh

**Comment by Sitolam** [comment]
> Hi, it might be one of the module that's causing it or the version of script.
> 
> so could you run `.config/hypr/scripts/wbarconfgen.sh n` from terminal and check for errors, also please share these files for one of the failed templates -
> 
> ```
> ~/.config/waybar/style.css
> ~/.config/waybar/config.jsonc
> ~/.config/waybar/config.ctl
> ```

I ran `.config/hypr/scripts/wbarconfgen.sh n` but I didn't get any errors. Here are the asked files for the first failed template: [Archive.zip](https://github.com/prasanthrangan/hyprdots/files/12705895/Archive.zip)

**Comment by prasanthrangan** [comment]
Hi, thanks for sharing... i just copied the configs to my system and it works fine for me --

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/4602cb8e-9515-4a28-888e-01f9cb93a605)

can you please try removing the modules from `config.ctl` one by one and rerun waybar to figure out which one is causing waybar to fail
```
1|31|bottom|( cpu memory custom/gpuinfo ) ( idle_inhibitor clock ) ( hyprland/workspaces )|( wlr/taskbar )|( network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
```

**Comment by Sitolam** [comment]
> Hi, thanks for sharing... i just copied the configs to my system and it works fine for me --
> 
> ![image](https://user-images.githubusercontent.com/106020512/270095646-4602cb8e-9515-4a28-888e-01f9cb93a605.png)
> 
> can you please try removing the modules from `config.ctl` one by one and rerun waybar to figure out which one is causing waybar to fail
> 
> ```
> 1|31|bottom|( cpu memory custom/gpuinfo ) ( idle_inhibitor clock ) ( hyprland/workspaces )|( wlr/taskbar )|( network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
> ```

By removing  `( cpu memory custom/gpuinfo )`  from the first failing template, the first failing template worked..

**Comment by prasanthrangan** [comment]
ah oki, so its `custom/gpuinfo` thats causing it... @T-Crypt is working on it, so for now please remove it from your config.ctl

**Comment by Sitolam** [comment]
> ah oki, so its `custom/gpuinfo` thats causing it... @T-Crypt is working on it, so for now please remove it from your config.ctl

Ok, thx
