### ISSUE TITLE
nvidia-dkms issue after fresh install

### ISSUE THREAD

**Issue by edanbigw** [prasanthrangan/hyprdots#257]
btw I have this dgpu on my system : NV167 (TU117) | GeForce GTX 1650, but after fresh install of this beautiful dotfiles, "nvidia-dkms" doesn't run properly. I've tried install and reboot with zen-kernel, still got same result, and when I tried install "nvidia" latest package (booted on default kernel) it's work flawlesly~ but I got package conflict due to nvidia and nvidia-dkms, should I delete nvidia-dkms or you guys have any other solution?  Thank in advice

this screenshot after fresh install : 
![230923_12h31m59s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/87627576/5e820343-a65b-423c-b905-557c7375ab8c)

**Comment by prasanthrangan** [comment]
Hi, thank you so much! was there any errors during installation for nvidia dkms modules?

> but I got package conflict due to nvidia and nvidia-dkms, should I delete nvidia-dkms or you guys have any other solution? Thank in advice

Yes, this conflict is expected, as `nvidia` works for your gpu please uninstall the `nvidia-dkms`, pacman will do this automatically when you install nvidia package

**Comment by edanbigw** [comment]
> Hi, thank you so much! was there any errors during installation for nvidia dkms modules?
> 
> > but I got package conflict due to nvidia and nvidia-dkms, should I delete nvidia-dkms or you guys have any other solution? Thank in advice
> 
> Yes, this conflict is expected, as `nvidia` works for your gpu please uninstall the `nvidia-dkms`, pacman will do this automatically when you install nvidia package

aaaa I see, no errors with the installation, but gpuinfo on waybar showing like that (on my screenshot)

**Comment by edanbigw** [comment]
> Hi, thank you so much! was there any errors during installation for nvidia dkms modules?
> 
> > but I got package conflict due to nvidia and nvidia-dkms, should I delete nvidia-dkms or you guys have any other solution? Thank in advice
> 
> Yes, this conflict is expected, as `nvidia` works for your gpu please uninstall the `nvidia-dkms`, pacman will do this automatically when you install nvidia package

aaa I see, no errors with the installation sir, thanks
