### ISSUE TITLE
Disable waybar background (like Material-Sakura theme).

### ISSUE THREAD

**Issue by SchnuBby2205** [prasanthrangan/hyprdots#258]
Hi,

i want to disable the background / backdrop for waybar on another theme else then "Material-Sakura". 

![grafik](https://github.com/prasanthrangan/hyprdots/assets/80288097/bef3913e-c8d8-41a8-968e-887bd02fd559)

I have searched for hours now, but can't find the place where to do it. Can you please enlighten me!

Thanks so much in advance!

**Comment by TheyCallMeSecond** [comment]
go to /.config/hypr/themes and comment the blurls = waybar line for each theme you want

**Comment by TheyCallMeSecond** [comment]
[![waybar](https://i.imgur.com/nZi1Rzq.png?raw=true "waybar")](https://i.imgur.com/nZi1Rzq.png?raw=true "waybar")

**Comment by SchnuBby2205** [comment]
Oh my god! It was THAT simple!? ....

I did comment this line ... maybe i haven't reloaded everything correct. So i thought i wouldn't work!

Thanks so much for the fast Help! You guys are great and your project is great. Keep up the awesome work. Thanks again :)!

**Comment by TheyCallMeSecond** [comment]
your welcome bro
im just a user of this beautiful project 
tnx to @prasanthrangan

**Comment by prasanthrangan** [comment]
Thank you so much guys! sounds like this is good to close!
