### ISSUE TITLE
dunst

### ISSUE THREAD

**Issue by TheyCallMeSecond** [prasanthrangan/hyprdots#259]
do you have a plan for theming dunst?

**Comment by stove-jeebs** [comment]
dunst is the notification daemon
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/22d265e1-6147-4799-bd70-d26bdde8dc45)

I think it looks good as is.

or perhaps you mean the rofi menu that pops up when you left-click dunst
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/8fa401cf-893c-44ed-a4f1-29beca6ea55b)

**Comment by TheyCallMeSecond** [comment]
no i mean dunst...notifications has dracula theme in all themes

**Comment by TheyCallMeSecond** [comment]
![230924_00h02m38s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/73380906/bf4dbbc3-81eb-4fc9-a18b-edd906fcbb9f)

**Comment by prasanthrangan** [comment]
> do you have a plan for theming dunst?

yes, I've plan to generate dunst config based on theme so that the colors are in sync.


> I think it looks good as is.
> 
> or perhaps you mean the rofi menu that pops up when you left-click dunst

yup, the current config only match the Catppucchin-Mocha theme, but not others.
hmm, i think i'll have to create separate rofi menu for dunst...
