### ISSUE TITLE
 there is a problem with Decay-Green

### ISSUE THREAD

**Issue by 220320bs** [prasanthrangan/hyprdots#26]
Well, I think there is a problem with Decay-Green

I used the old config file without the error, I used the new one and it became like this, then I rm -rf ~/.config/waybar and reinstalled it, but it still did

![image](https://github.com/prasanthrangan/hyprdots/assets/113283361/153fcbca-95db-4047-a861-6eb9a758b18e)

**Comment by prasanthrangan** [comment]
Hi, do you mean the color or the box shape? I updated the Decay-Green theme to have square edges and changed up the waybar color a bit...

So just update the rounded corner set in hyprland theme file `~/.config/hypr/themes/Decay-Green.conf` and the waybar should go back to pill shape!

https://github.com/prasanthrangan/hyprdots/assets/106020512/ebf0780e-e59f-4070-a348-7a5f72e9e142

Regarding the colors, if you want the old one, just revert back the `~/.config/waybar/themes/Decay-Green.css`

**Comment by 220320bs** [comment]
@prasanthrangan OK I know  I thought there had been a problem
