### ISSUE TITLE
Steam Valve

### ISSUE THREAD

**Issue by aloisiomarques** [prasanthrangan/hyprdots#260]
Hello friends, I have a problem when someone invites me to play the CSGO game and I click on the play button, Steam closes out of nowhere and doesn't open the game. Would this be a hyprland problem or a theme problem?

**Comment by prasanthrangan** [comment]
Hi, CSGO just works fine for me...
can you launch steam from terminal and check for errors??
also, do you have mangohud installed or its variables enabled?

**Comment by aloisiomarques** [comment]
The problem only occurs if you receive an invitation from Steam friends to play the game. When we accept via chat, the game and Steam close completely. It's worth mentioning that the game works very well, but when I receive an invitation to play, everything closes.

I'm not using mangohud or gamemod.

**Comment by prasanthrangan** [comment]
ohh, so the game works when you launch it from library and but crash when joining via chat...
not sure, but might be due to missing dependency?!?
can you please launch stream from terminal and join the game via chat, so we could see the log that way.

**Comment by aloisiomarques** [comment]
"steam.sh[63012]: Running Steam on arch rolling 64-bit
steam.sh[63012]: STEAM_RUNTIME is enabled automatically
setup.sh[63089]: Steam runtime environment up-to-date!
steam.sh[63012]: Steam client's requirements are satisfied
[2023-09-25 18:39:53] Startup - updater built Sep 11 2023 20:48:54
[2023-09-25 18:39:53] Startup - Steam Client launched with: '/home/me/.local/share/Steam/ubuntu12_32/steam'
[2023-09-25 18:39:53] Loading cached metrics from disk (/home/me/.local/share/Steam/package/steam_client_metrics.bin)
[2023-09-25 18:39:53] Using the following download hosts for Public, Realm steamglobal
[2023-09-25 18:39:53] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-09-25 18:39:53] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-09-25 18:39:53] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'

Steam logging initialized: directory: /home/me/.local/share/Steam/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf00b4db0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf00b3500
steamwebhelper.sh[63149]: Runtime for steamwebhelper: defaulting to /home/me/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[63149]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 147 milliseconds to initialize
/home/me/.gtkrc-2.0:4: Unable to find include file: "~/.gtkrc-2.0.mine"
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 63331
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
Fossilize INFO: Autogroup scheduling is not enabled on this kernel. Will rely entirely on nice().
BRefreshApplicationsInLibrary 1: 93ms
BuildCompleteAppOverviewChange: 623 apps
RegisterForAppOverview 1: 27ms
RegisterForAppOverview 2: 28ms
[2023-09-25 18:41:54] Background update loop checking for update. . .
[2023-09-25 18:41:54] Verificando se há atualizações...
[2023-09-25 18:41:54] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=3614291466
[2023-09-25 18:41:54] Manifest download: send request
[2023-09-25 18:41:54] Manifest download: waiting for download to finish
[2023-09-25 18:41:55] Manifest download: finished
[2023-09-25 18:41:55] Download skipped: /steam_client_ubuntu12?t=3614291466 version 1694466342, installed version 1694466342, existing pending version 0
[2023-09-25 18:41:55] Nothing to do
Fossilize INFO: Autogroup scheduling is not enabled on this kernel. Will rely entirely on nice().
/bin/sh\0-c\0/home/me/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=730 -- /home/me/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/csgo.sh' -steam +connect_lobby 109775243215961426 -vulkan -novid +fps_max 999 -freq 144 -refresh 144 -tickrate 128 -nojoy\0
chdir "/media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive"
ERROR: ld.so: object '/home/me/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/me/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/me/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/me/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 85307 != 85306, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/me/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/me/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
SDL video target is 'x11'
 failed to dlopen /media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/engine_client.so error=/media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/engine_client.so: wrong ELF class: ELFCLASS32
 failed to dlopen /media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/filesystem_stdio_client.so error=/media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/filesystem_stdio_client.so: wrong ELF class: ELFCLASS32
 failed to dlopen /media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/inputsystem_client.so error=/media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/inputsystem_client.so: wrong ELF class: ELFCLASS32
 failed to dlopen /media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/vphysics_client.so error=/media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/vphysics_client.so: wrong ELF class: ELFCLASS32
 failed to dlopen /media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/materialsystem_client.so error=/media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/materialsystem_client.so: wrong ELF class: ELFCLASS32
 failed to dlopen /media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/datacache_client.so error=/media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/datacache_client.so: wrong ELF class: ELFCLASS32
 failed to dlopen /media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/studiorender_client.so error=/media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/studiorender_client.so: wrong ELF class: ELFCLASS32
 failed to dlopen /media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/soundemittersystem_client.so error=/media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/soundemittersystem_client.so: wrong ELF class: ELFCLASS32
 failed to dlopen /media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/vscript_client.so error=/media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/vscript_client.so: wrong ELF class: ELFCLASS32
 failed to dlopen /media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/vguimatsurface_client.so error=/media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/vguimatsurface_client.so: wrong ELF class: ELFCLASS32
 failed to dlopen /media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/vgui2_client.so error=/media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/vgui2_client.so: wrong ELF class: ELFCLASS32
 failed to dlopen /media/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/localize_client.so error=/me
dia/jogos/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/bin/localize_client.so: wrong ELF class: ELFCLASS32
info:  Game: csgo_linux64
info:  DXVK: v1.9.1-100-g336868d
info:  Built-in extension providers:
info:    SDL2 WSI
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_xlib_surface
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce GTX 1070:
info:    Driver: 535.113.1
info:    Vulkan: 1.3.242
info:    Memory Heap[0]: 
info:      Size: 8192 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 23996 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
Created D3D9Ex device successfully
WARNING: unable to link grab_window and grab_window because one or more is a ConCommand.
Using breakpad minidump system 730/13879.1573.JC
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/me/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 730
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
09/25 18:50:27 Init: Installing breakpad exception handler for appid(730)/version(13879.1573.JC)/tid(85331)
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Initialized low level socket/threading support.
Got ISteamNetworkingSockets user interfaces from standalone lib
Pending ping measurement until network config is obtained.
SDR RelayNetworkStatus:  avail=Attempting  config=Attempting  anyrelay=Waiting   (Attempt #1 to fetch config from https://api.steampowered.com/ISteamApps/GetSDRConfig/v1?appid=730)
USRLOCAL path using Steam profile data folder:
/home/me/.local/share/Steam/userdata/91914899/730/local
RESZ SUPPORTED!
INTZ SUPPORTED!
RESZ SUPPORTED!
INTZ SUPPORTED!
XIO:  fatal IO error 2 (No such file or directory) on X server ":1"                                                          
      after 7643 requests (7643 known processed) with 40 events remaining."
===============================================================================================
this error appears at the end when accepted. thank you for the support

**Comment by T-Crypt** [comment]
Can you add " ``` " to the beginning of that long bolded text so it is easier to read??

```
should look like this

``` 

![Screenshot 2023-09-25 172310](https://github.com/prasanthrangan/hyprdots/assets/132922589/03f2866c-404b-4036-95eb-baca640acdcd)

**Comment by aloisiomarques** [comment]
ok

**Comment by opticblu** [comment]
> ohh, so the game works when you launch it from library and but crash when joining via chat... not sure, but might be due to missing dependency?!? can you please launch stream from terminal and join the game via chat, so we could see the log that way.

This might be related to SDDM of all things

Does the script configure SDDM to use Wayland is it just default settings with the theme?

SDDM will actually spawn xorg on another display (display :0 probably) and then Wayland/hyprland will be at display :1 

Steam might be trying to spawn the game on the wrong $DISPLAY

Other than that, if user is using a shell with weird variable handling (fish for instance) it might be mishandling environment variables

Long and short of it, make sure :1 is what you really want the game to launch on

**Comment by aloisiomarques** [comment]
> > ohh, so the game works when you launch it from library and but crash when joining via chat... not sure, but might be due to missing dependency?!? can you please launch stream from terminal and join the game via chat, so we could see the log that way.
> 
> This might be related to SDDM of all things
> 
> Does the script configure SDDM to use Wayland is it just default settings with the theme?
> is the theme config
> SDDM will actually spawn xorg on another display (display :0 probably) and then Wayland/hyprland will be at display :1
> here it is on the display :1, but I don't know how to see what the Steam output is
> Steam might be trying to spawn the game on the wrong $DISPLAY
> How do I check steam output?
> Other than that, if user is using a shell with weird variable handling (fish for instance) it might be mishandling environment variables
> I use the theme
> Long and short of it, make sure :1 is what you really want the game to launch on
How do I check this?

**Comment by aloisiomarques** [comment]
I tested with sddm and gdm and the same problem occurs. In Gnome and Plasma I don't have this problem.

**Comment by prasanthrangan** [comment]
> I tested with sddm and gdm and the same problem occurs. In Gnome and Plasma I don't have this problem.

Is it native or proton version? could you try running steam with `gamescope`? gnome and plasma have its own xdg desktop portal... maybe try installing the kde or gtk version.

> Long and short of it, make sure :1 is what you really want the game to launch on

I think it can be set as env variable `GTK_USE_PORTAL=1` in `hyprland.conf`, but not sure about this...

**Comment by aloisiomarques** [comment]
thx guys, problem solved. cs2 does not have this problem.

**Comment by prasanthrangan** [comment]
oh cool, the legends at valve have fixed it :)
and cs2 looks amazing, I'll have to try it out later...
