### ISSUE TITLE
Firefox Delay when launching 

### ISSUE THREAD

**Issue by Clutchnp** [prasanthrangan/hyprdots#261]
Firefox has delay of about 10 sec before launching.
Note: This only happens for the first window and not for the ones opened after that 
Checked:
There are no other De's or wms other than hyprland(and hence no other portals)
This install was done on a fresh minimal install of Arch
Note:When I first booted into the system there was this error "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running." but now on running nvidia-smi things show up as normal
There are no major points other than sometimes when run from terminal  this error shows -
``` [GFX1-]: Wayland protocol error: warning: queue 7f9490f8b5e0 destroyed while proxies still attached:

[GFX1-]: Wayland protocol error:   zwp_linux_dmabuf_feedback_v1@52 still attached

[GFX1-]: Wayland protocol error:   zwp_linux_dmabuf_feedback_v1@31 still attached

[GFX1-]: Wayland protocol error:   zwp_linux_dmabuf_v1@47 still attached 
```

couldn't debug further, any assistance will be appreciated

**Comment by prasanthrangan** [comment]
Hi, I get the same error but i don't have any delays launching firefox...
can you check with autogenerated default hyprland.conf file instead of my config, to see if its my config that's causing it?
maybe its one of those nvidia variable??

```
❯ firefox
[GFX1-]: Wayland protocol error: warning: queue 7f7e163d3e50 destroyed while proxies still attached:

[GFX1-]: Wayland protocol error:   zwp_linux_dmabuf_feedback_v1@62 still attached

[GFX1-]: Wayland protocol error:   zwp_linux_dmabuf_feedback_v1@31 still attached

[GFX1-]: Wayland protocol error:   zwp_linux_dmabuf_v1@47 still attached
```

**Comment by Clutchnp** [comment]
Well this is weird , I tried using the default hyprland config as you suggested and delay was still there, but for some reason when i went back to the old one again, the issue was fixed?
What could have been causing the issue i wonder, anyhow i am closing the issue,Thanks for your work and effort.
