### ISSUE TITLE
Request for Assistance with Monitor Configuration Issue

### ISSUE THREAD

**Issue by imsherl** [prasanthrangan/hyprdots#263]
##### Hello,

I hope this message finds you well. I am currently facing an issue with my dual-monitor setup on my Linux system, and I am seeking assistance to resolve it. Here's a detailed description of the problem and the troubleshooting steps I have taken so far:

# Problem Description:
I recently connected a second monitor to my system, and by default, the settings configure the main monitor on the left and the second monitor on the right. However, I prefer to have my main monitor on the right. The issue is that when I move my mouse to the right, it does not switch to the main monitor as expected. Instead, it switches when I move the mouse to the left, which is quite confusing.

# Troubleshooting Steps:
To address this problem, I attempted several solutions using the xrandr command, but unfortunately, none of them worked. Here are the commands I tried:

### Attempted to set the second monitor as the primary/main monitor:
`xrandr --output eDP-1 --primary --output HDMI-A-1`

### Tried moving the main monitor to the right using the xrandr command:
`xrandr --output eDP-1 --auto --output HDMI-A-1 --auto --right-of eDP-1`

I also attempted to use the GNOME desktop manager (gdm) to address this issue, but it failed to launch.

I would greatly appreciate your assistance in resolving this monitor configuration problem. If you have any insights or suggestions on how to make my main monitor function correctly when moving the mouse to the right, please let me know.

Thank you for your time and assistance.

Sincerely,
Imsherl

**Comment by Lol-Lap** [comment]
> ##### Hello,
> 
> I hope this message finds you well. I am currently facing an issue with my dual-monitor setup on my Linux system, and I am seeking assistance to resolve it. Here's a detailed description of the problem and the troubleshooting steps I have taken so far:
> # Problem Description:
> 
> I recently connected a second monitor to my system, and by default, the settings configure the main monitor on the left and the second monitor on the right. However, I prefer to have my main monitor on the right. The issue is that when I move my mouse to the right, it does not switch to the main monitor as expected. Instead, it switches when I move the mouse to the left, which is quite confusing.
> # Troubleshooting Steps:
> 
> To address this problem, I attempted several solutions using the xrandr command, but unfortunately, none of them worked. Here are the commands I tried:
> ### Attempted to set the second monitor as the primary/main monitor:
> 
> `xrandr --output eDP-1 --primary --output HDMI-A-1`
> ### Tried moving the main monitor to the right using the xrandr command:
> 
> `xrandr --output eDP-1 --auto --output HDMI-A-1 --auto --right-of eDP-1`
> 
> I also attempted to use the GNOME desktop manager (gdm) to address this issue, but it failed to launch.
> 
> I would greatly appreciate your assistance in resolving this monitor configuration problem. If you have any insights or suggestions on how to make my main monitor function correctly when moving the mouse to the right, please let me know.
> 
> Thank you for your time and assistance.
> 
> Sincerely, Imsherl

Can you please share the monitor configuration from `hyprland.conf` from.config/hypr/

**Comment by prasanthrangan** [comment]
Hi, `xrandar` wont work in wayland.

For hyprland you'll have to configure it as below
1. identify your monitor port, resolution and refreshrate with `hyprctl monitors`.
2. set monitor config in `~/.config/hypr/hyprland.conf` or `~/.config/hypr/monitor.conf` , for example -

```
monitor=DP-1, 1920x1080, 0x0, 1
monitor=DP-2, 1920x1080, 1920x0, 1
```
this shows monitor at `DP-1` with `1920x1080` res is set as primary (left), while monitor at `DP-2` is set to the right.
for more details please refer [this](https://wiki.hyprland.org/Configuring/Monitors/).

**Comment by imsherl** [comment]
##### Hello again,

I have adjusted the configuration file in accordance with your recommendations, and the issue has been successfully resolved. I would like to extend my sincere gratitude to both of you for your invaluable assistance and efforts. 

Wishing you both a pleasant day ahead!
