### ISSUE TITLE
Game launcher resolution issue

### ISSUE THREAD

**Issue by Ew4n1011** [prasanthrangan/hyprdots#264]
Hi, when I open the game launcher (Set with a keybind) it crops it like what used to happen to the wallpaper selector. Maybe its because I'm on a 1920x1080 monitor?

![image](https://github.com/prasanthrangan/hyprdots/assets/96702632/ae58c64a-a043-4718-9611-2c9d055de5a2)

**Comment by Ew4n1011** [comment]
Also a side note, is it possible to include non steam games to show as well? (Games that have been added to steam but use another launcher (like heroic))

**Comment by T-Crypt** [comment]
> Also a side note, is it possible to include non steam games to show as well? (Games that have been added to steam but use another launcher (like heroic))

I believe they need to be present in the steam library folder in order to show up.. Are they located in a different folder since they are set for another launcher? (folder location below)

```
# set steam library
SteamLib="$HOME/.local/share/Steam/config/libraryfolders.vdf"

**Comment by Ew4n1011** [comment]
Ah I see, yeah they're stored in ~/Games, which now makes sense why steam doesn't detect them (the game files at least)

**Comment by Ew4n1011** [comment]
Yeah just checked, they're not there. Would it be possible to parse through another directory?

**Comment by prasanthrangan** [comment]
Hi, it only scans for Steam directories, i have no idea how the metadata files looks like for others launchers.
The rofi scaling is fixed for this, and didnt get a change to make it dynamic yet... anyways I'll be reworking on this launcher later...

**Comment by Ew4n1011** [comment]
Ok, thanks for replying! I'll have a look into the metadata of other launchers to see if it's possible to add to the script, and make a PR if I find a way how

**Comment by celikj** [comment]
having the same issue
the fifth style is too big it dont even fit in my screen

**Comment by kRHYME7** [comment]
Here's mine
![image](https://github.com/user-attachments/assets/dc253949-66b6-4069-aaf7-ae1955695acb)

That's expected you can manually rescale this image with your monitor size 

![image](https://github.com/user-attachments/assets/7432a4ce-c7a0-46a0-9aa2-f1369e4a6b9e)
