### ISSUE TITLE
waybar showing NVIDIA card ... I don't have one?

### ISSUE THREAD

**Issue by kronikpillow** [prasanthrangan/hyprdots#267]
after running ./install.sh -r to apply new configs etc, waybar is showing NVIDIA in my statusbar, and some errot that it can't communicate with it ... I don't have a NVIDIA Card, i have a Radeon R9 380... strange ... 

I do have a integrated nvidia card that is disabled thou, and not used

**Comment by T-Crypt** [comment]
It is throwing that error because nvidia-smi error. 

if you run `nvidia-smi` in the terminal it will produce the same result as the waybar error. 

The pull request that is pending should resolve this issue and report for the R9 380!

**Comment by T-Crypt** [comment]
@kronikpillow -- Are you able to close this issue?

**Comment by kronikpillow** [comment]
Yes issue can be closed, iv moved away temporarily from Hyprland even thou i love it, as iv encountered issues related to my work, particularly to explain, I work in Marketing, and when I was writing a LinkedIn Article, and tried to attach a image to the article, the image doesnt get attached/uploaded, while on xorg it does, this was unfortunately reason enough for me to move away, as i work in Social Media Marketing, and doing such things is a day to day thing almost ...

I dunno werther this was a issue related to wayland, hyprland, the dolphin file picker, or i dunno, i just got disappointed with being unable to do work trough Hyprland so i switched back to Plasma, until Hyprland and Wayland mature more
