### ISSUE TITLE
Android Studio Emulator Error

### ISSUE THREAD

**Issue by imsherl** [prasanthrangan/hyprdots#268]
# Issue Description:
Hello, I hope you're having a good day.

I installed Android Studio using AUR (yay) on Arch Linux. It launches correctly and allows me to create projects. However, whenever I try to run the code with the "Run" button and the Android Studio Emulator, I encounter the following error. I have tried the two methods mentioned below, but I am still getting the error shown in the screenshot:

![image](https://github.com/prasanthrangan/hyprdots/assets/142403502/14bd104a-f334-460f-b83e-c5b35e61f8ef)

# Troubleshooting Steps Taken:

I attempted to resolve the issue by individually downloading and installing the following packages, but I still encountered the same error:

[android-sdk-cmdline-tools-latest](https://aur.archlinux.org/packages/android-sdk-cmdline-tools-latest)
[android-sdk-build-tools](https://aur.archlinux.org/packages/android-sdk-build-tools)
[android-sdk-platform-tools](https://aur.archlinux.org/packages/android-sdk-platform-tools)
[android-platform](https://aur.archlinux.org/packages/android-platform)
[android-emulator](https://aur.archlinux.org/packages/android-emulator)

___

I navigated to the /opt/android-sdk directory and used the command ./emulator/emulator -list-avds to list the installed virtual devices.

![image](https://github.com/prasanthrangan/hyprdots/assets/142403502/71921ab2-7fe0-419d-8461-96e5bb67da76)

I attempted to run the installed device in the terminal and received the following error message. While I don't fully understand it, there may be some clues related to the issue in the error output.
![image](https://github.com/prasanthrangan/hyprdots/assets/142403502/5676b46b-b4a3-4a81-aefb-fa934839a90b)

Please assist me in resolving this issue, your help is greatly appreciated.

Sincerely,
Imsherl

**Comment by prasanthrangan** [comment]
Hi,

I've not used Android Studio Emulator, but isn't avd supposed to be created in home path `~/.android/avd`??

based on the error, maybe you can try setting the env variable `ANDROID_SDK_ROOT` path in `hyprland.conf` or is there an option in the studio for this??

Also you can give the Android Studio flatpak version a try!

**Comment by jaypatel208** [comment]
@imsherl does your android studio issued resolved?? all thinks working fine??

I installed studio but having issue to launching an emulator

**Comment by sidoelz123** [comment]
Hi, you can use command
QT_QPA_PLATFORM=xcb emulator -avd Pixel_3a_API_30

**Comment by TowhidMolla-Dev** [comment]
Uncomment this 2 line will do the job

env = QT_QPA_PLATFORM,wayland
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

**Comment by kRHYME7** [comment]
Please reopen if necessary.
