### ISSUE TITLE
what ascii art generator was used in the hyprland config file

### ISSUE THREAD

**Issue by noornee** [prasanthrangan/hyprdots#269]
Hii @prasanthrangan  i was wondering what ascii art you used for the hyprland config. i tried searching for something that generates an art like that and i discovered `figlet` but i couldnt find any of the font that looked similar to what you used.

https://github.com/prasanthrangan/hyprdots/commit/49b41713e820915ca1de667bfc831a3cdf1ae1e8
![ascii_goes_brr](https://github.com/prasanthrangan/hyprdots/assets/71889751/982f1ced-f208-4519-9bdb-3b11f4411ef1)

Great dots btw!

**Comment by prasanthrangan** [comment]
Hi, Thank you so much!
Here you go -- https://fsymbols.com/generators/

**Comment by noornee** [comment]
> Hi, Thank you so much! Here you go -- https://fsymbols.com/generators/

you're welcome!
Thankss for the link to generator too. ^^
