### ISSUE TITLE
Screen Sharing Issues 

### ISSUE THREAD

**Issue by Clutchnp** [prasanthrangan/hyprdots#271]
1.  Screen sharing worked just after the running the script, but after a reboot,screen sharing didn't work (checked as have reinstalled multiple times so i can confirm that rebooting is part of the problem.(Webcord's screen sharing just keeps loading and on firefox nothing happens)
2.
Pipewire seems to behaving a bit weird   
![image](https://github.com/prasanthrangan/hyprdots/assets/105556048/f5f009ba-6503-4ab8-97e6-72158bf6d91b)
3. 
 xdg-portal-hyprland seems to be inactive(dead) 
 ![image](https://github.com/prasanthrangan/hyprdots/assets/105556048/58ca0f63-06ad-4fdf-a4e1-4fcec8d26206)

4. No other portal is installed
5. Tried:  Restarting pipewire , activating the portal
Any help would be appreciated:)

**Comment by prasanthrangan** [comment]
Hi, I think i've seen this before... it might be `~/.config/hypr/scripts/resetxdgportal.sh` that runs at startup.

**Comment by Clutchnp** [comment]
I aldready tried removing it and rebooting which indeed helped start up the hyprland portal but still the error persists though looking through the hyprwm repo's issues tab. I think this is not a local problem rather a bug in new version hyprland portal 
![image](https://github.com/prasanthrangan/hyprdots/assets/105556048/3af4b138-183b-4401-8acf-d027644b03a0) anyway this is the log after trying to screen share

**Comment by prasanthrangan** [comment]
> 1. Screen sharing worked just after the running the script, but after a reboot,screen sharing didn't work (checked as have reinstalled multiple times so i can confirm that rebooting is part of the problem.(Webcord's screen sharing just keeps loading and on firefox nothing happens)

i updated my system and my screen sharing stopped working as well... obs shows black screen and discoed in firefox did nothing..

found this in hyprwm repo's issues, it solved it for me by adding bitdepth in monitor config -
```
monitor = DP-1, 2560x1080@144, 0x0, 1, bitdepth, 10
```

now both firefox discord and obs screenshare works, but for reason the framerate seems messed up (not as smooth as before)

**Comment by Clutchnp** [comment]
> > 1. Screen sharing worked just after the running the script, but after a reboot,screen sharing didn't work (checked as have reinstalled multiple times so i can confirm that rebooting is part of the problem.(Webcord's screen sharing just keeps loading and on firefox nothing happens)
> 
> i updated my system and my screen sharing stopped working as well... obs shows black screen and discord in firefox did nothing..
> 
> found this in hyprwm repo's issues, it solved it for me by adding bitdepth in monitor config -
> 
> ```
> monitor = DP-1, 2560x1080@144, 0x0, 1, bitdepth, 10
> ```
> 
> now both firefox discord and obs screenshare works, but for reason the framerate seems messed up (not as smooth as before)

For me the error still persists even after adding bitdepth , I will see what I can do ,since this is not because of the script i am closing this issue. Thanks.:)

**Comment by wiscaksono** [comment]
> > 1. Screen sharing worked just after the running the script, but after a reboot,screen sharing didn't work (checked as have reinstalled multiple times so i can confirm that rebooting is part of the problem.(Webcord's screen sharing just keeps loading and on firefox nothing happens)
> 
> i updated my system and my screen sharing stopped working as well... obs shows black screen and discord in firefox did nothing..
> 
> found this in hyprwm repo's issues, it solved it for me by adding bitdepth in monitor config -
> 
> ```
> monitor = DP-1, 2560x1080@144, 0x0, 1, bitdepth, 10
> ```
> 
> now both firefox discord and obs screenshare works, but for reason the framerate seems messed up (not as smooth as before)

this is working for me, thank you!
