### ISSUE TITLE
Waybar clock

### ISSUE THREAD

**Issue by Thinnish5** [prasanthrangan/hyprdots#272]
clock in waybar not displaying
![230929_11h14m09s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/86500829/b2dade2e-448e-4620-b08a-2174c62e0734)

**Comment by prasanthrangan** [comment]
oh, any error when you launch waybar from terminal?
could you please share these generated files 
```
~/.config/waybar/style.css
~/.config/waybar/config.jsonc
~/.config/waybar/config.ctl
```

**Comment by T-Crypt** [comment]
Need to set the timezone on your linux machine. Looks like you installed arch without setting the timezone. 

You can use `timedatectl list-timezones` to get a list of the available zones and then set using the line below.

`sudo timedatectl set-timezone <your_time_zone>`
