### ISSUE TITLE
Pixelated Windows (On NVIDIA DRIVERS)

### ISSUE THREAD

**Issue by cosmic-helios** [prasanthrangan/hyprdots#274]
I use Arch with your Dots on a Portable SSD, i usually use it on an Intel-Based GPU. I had to switch to a NVIDIA-Based GPU.

- Now, i get this issue of pixelated windows for Brave, Spotify and other apps.
- I tried running the script to install the necessary driver for Nvidia, that didn't really work out well.
- I also changed the monitor config, that didn't work either.
**ANY SOLUTIONS?**

![230929_22h41m36s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/136916325/dea936f2-b2f4-4fbd-818b-acd3692af673)
![230929_22h43m28s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/136916325/d11da6a3-d43b-485a-ba19-618403b39f0b)
![230929_22h45m20s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/136916325/0b8d1964-8d96-436e-8f9d-d8a3c1c54aef)

**Comment by cosmic-helios** [comment]
Also the system windows work just fine.

**Comment by Thinnish5** [comment]
try to change the ~/.config/hypr/hyprland.conf and comment the monitor setting u have and change to this one monitor=,highres,auto,1 it will focus on resolution. Like this
![230929_18h57m09s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/86500829/a5f74f45-da36-4909-bcdf-042c6dbf0353)

**Comment by cosmic-helios** [comment]
**The-Savior**

I was on the fence of switching to NixOS.

There's only 1 problem now, the display now a little too small

Any Changes?

**Comment by cosmic-helios** [comment]
So, I tried to change the highres part to 1980x1080. It blanked out my monitor.

**Comment by Thinnish5** [comment]
Keep in highres and change the 1 to higher numbers until u have the perfect scale

**Comment by cosmic-helios** [comment]
Thanks @Thinnish5

**Comment by zer0cha0s** [comment]
Can you run `hyprctl monitors` in the terminal and post the output. 
I've read there can be issues with the Nimbus font at lower resolutions.

**Comment by cosmic-helios** [comment]
I can't do it as of now, cuz I messed up the  whole monitor, it's blacked out.

**Comment by zer0cha0s** [comment]
Try pressing `CTRL+ALT+F3` to switch to a different tty, hopefully it will give you a terminal prompt so you can go an undo the changes that blanked the monitor.

**Comment by Thinnish5** [comment]
> So, I tried to change the highres part to 1980x1080. It blanked out my monitor.

That probably happened becouse you forgot to set refresh rate 1980x1080@60 was the right command, when you can try to boot in termial mode and change it back to highres and change the vaule of 1 to 1,25

**Comment by cosmic-helios** [comment]
> Try pressing `CTRL+ALT+F3` to switch to a different tty, hopefully it will give you a terminal prompt so you can go an undo the changes that blanked the monitor.

I reseted the whole thing, Thanks for the advice though.
