### ISSUE TITLE
Unanime the hyprland startup

### ISSUE THREAD

**Issue by V1rtualTurtle** [prasanthrangan/hyprdots#275]
Hi! I am enjoying customising your dotfiles to my liking but I am not aware how to stop displaying the anime girls after SDDM on startup... I'd like to eliminate that possibility and only show the hyprland logo with no anime next to it. Many thanks, V1rtualTurtle.

**Comment by T-Crypt** [comment]
Need to add this to Misc in hyprland.conf

```
misc {
  disable_hyprland_logo = true
}

**Comment by V1rtualTurtle** [comment]
I am not trying to get rid of the hyprland logo, but the waifu next to the logo, because there are three possibilities, a normal plain hyprland logo, and 2 with waifus, is there any chance you can tell me how to just get the plain one

**Comment by V1rtualTurtle** [comment]
never mind I found the solution... I just RTFM'd... if anyone wants to know you have to write:

disable_hypr_chan = true

**Comment by YasirRWebDesigner** [comment]
`disable_hypr_chan = true ` has been removed in v 0.31.0  use `force_default_wallpaper - 0`

otherwise you will get this error 


![image](https://github.com/prasanthrangan/hyprdots/assets/32537564/af872b05-2afc-467d-a5e4-a2eb0cf73dde)
