### ISSUE TITLE
Blurry and pixelated in vscode and virtualbox

### ISSUE THREAD

**Issue by T3l3sc0p3** [prasanthrangan/hyprdots#278]
Hi, recently I discovered that vscode and virtualbox have blurry fonts. Even though I tried using other fonts, it still didn't work
I tried searching and found quite a few people with the same situation as me
Personally, I think this problem lies in the resolution configuration, but I still cannot address it
I'm currently using 1920x1080, hope this helps

**Comment by prasanthrangan** [comment]
Hi, can you try disabling the scaling and check if its better?

```
env = GDK_SCALE,1

xwayland {
force_zero_scaling = true
}
```

**Comment by T3l3sc0p3** [comment]
I have tried that way. It's true that it's no longer blurred, but now the font is too small. I can increase the font size in vscode, however I can't do it in virtualbox

**Comment by opticblu** [comment]
> I have tried that way. It's true that it's no longer blurred, but now the font is too small. I can increase the font size in vscode, however I can't do it in virtualbox

run it like this

$ QT_QPA_PLATFORM=xcb virtualbox

**Comment by T3l3sc0p3** [comment]
I have found a way to force vscode scaling to 1.5 without blurry text. All I need to do is run [`code --force-device-scale-factor=1.5`](https://wiki.archlinux.org/title/Visual_Studio_Code#Blurry_text_under_Wayland)

However, I'm still unable to run virtualbox in the same way, how unpleasant :confused:

Maybe I will try another virtual machine...
