### ISSUE TITLE
File sddmwall.sh

### ISSUE THREAD

**Issue by katsuja** [prasanthrangan/hyprdots#279]
After the pull I noticed this new script for sddm, I think for the background image, but I didn't see it declared in any config file.
Do I have to do something special?
Thank you
![230930_13h29m06s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/e2bd85b8-af27-411e-9b95-c50a4236d369)

**Comment by katsuja** [comment]
However, it's nice as you use it, it updates the sddm wallpaper based on the theme set on hypr.
But just as I have to throw it every time.
Should I put it as an executable in hyprland.conf?

**Comment by prasanthrangan** [comment]
Hi, just set the background as below in `/usr/share/sddm/themes/corners/theme.conf`
```
Background="/home/<user>/.config/swww/wall.set"
```
the script is not required for this.

**Comment by katsuja** [comment]
> Hi, just set the background as below in `/usr/share/sddm/themes/corners/theme.conf`
> 
> ```
> Background="/home/<user>/.config/swww/wall.set"
> ```
> 
> the script is not required for this.

Ok.
Thx.
