### ISSUE TITLE
desktop problem

### ISSUE THREAD

**Issue by liweiyang2023** [prasanthrangan/hyprdots#280]
Desktop display decoration: multisample_ Edges no such field, how can I fix this problem

**Comment by liweiyang2023** [comment]
Another question: What shortcut key to open Terminal? I am a noob，i really dont know

**Comment by prasanthrangan** [comment]
> Desktop display decoration: multisample_ Edges no such field, how can I fix this problem

Hi, comment out this line from `~/.config/hypr/themes/*.conf`

https://github.com/prasanthrangan/hyprdots/blob/14a41e6fc2d1aa59116a71c404c94dc8df3842cc/Configs/.config/hypr/themes/Catppuccin-Mocha.conf#L35

> Another question: What shortcut key to open Terminal? I am a noob，i really dont know

its `Super` + `T`

**Comment by liweiyang2023** [comment]
> > 桌面显示装饰：multisample_ Edges 没有此字段，如何解决此问题
> 
> 你好，注释掉这行`~/.config/hypr/themes/*.conf`
> 
> https://github.com/prasanthrangan/hyprdots/blob/14a41e6fc2d1aa59116a71c404c94dc8df3842cc/Configs/.config/hypr/themes/Catppuccin-Mocha.conf#L35
> 
> > 还有一个问题：打开终端的快捷键是什么？我是菜鸟，我真的不知道
> 
> 它的`Super`（Windows键）+`T`

thanks for your answer!!,I've already done this, does this feature make a difference？and I finally opened the terminal

**Comment by prasanthrangan** [comment]
> thanks for your answer!!,I've already done this, does this feature make a difference？and I finally opened the terminal

No it was just for antialiasing rounded corners, and it seems to be removed from latest version of hyprland.
Anyways I've fixed it in abb9914
