### ISSUE TITLE
hyprland config error

### ISSUE THREAD

**Issue by Newer1107** [prasanthrangan/hyprdots#281]
I just upgraded my system so I thought about running the restore command to update hyprland files, I git pull and reran the script and I'm getting this error:
![image](https://github.com/prasanthrangan/hyprdots/assets/116626403/6d72b1f1-06a4-4159-91b2-428090503a01)
there's also the error above which came in the red.
TIA!

**Comment by prasanthrangan** [comment]
Hi, multisample_edges seems to be removed from latest version of hyprland.
so i've fixed it in abb9914743c262d88e4b0faff3624ccd76c35deb

**Comment by Newer1107** [comment]
> Hi, multisample_edges seems to be removed from latest version of hyprland. so i've fixed it in [abb9914](https://github.com/prasanthrangan/hyprdots/commit/abb9914743c262d88e4b0faff3624ccd76c35deb)

I cant update I get this error:
![image](https://github.com/prasanthrangan/hyprdots/assets/116626403/56a52d4b-bcc9-45e3-9dfa-bdef8a948314)
honestly, the new thing you added isnt my thing (the new update in terminal) I think you should go back to the old one.

**Comment by Newer1107** [comment]
Hi,

I just wanted to follow up on this issue. I'm still experiencing the problem described in my original post and I'm unable to proceed with the upgrade. I understand that you may be busy, but if you could spare a moment to provide some guidance or insight into this issue, I would greatly appreciate it.

Thank you for your help!

**Comment by TheyCallMeSecond** [comment]
".config/hypr/themes/theme.conf" is a symlink...is it linked to the right path?
--> /home/YOUR-USERNAME/.config/hypr/themes/Catppuccin-Mocha.conf

**Comment by prasanthrangan** [comment]
Hi, based on the error the file `.p10k.zsh` doses not exist in your clone dir... so please clone it again.

**Comment by KareemZohdy** [comment]
> delete the Dots folder in your home directory and git clone again the repo and restore from fresh Dots folder

I have the same problem and i tried your answer and i didn't work, do you have any other way to solve this?

**Comment by TheyCallMeSecond** [comment]
> > delete the Dots folder in your home directory and git clone again the repo and restore from fresh Dots folder
> 
> I have the same problem and i tried your answer and it didn't work, do you have any other way to solve this? ![231012_17h10m27s_screenshot](https://user-images.githubusercontent.com/113604542/274578922-e9890824-2fa7-4d53-8f7a-feccd7f000d4.png)

no its not the same error...update your hyprland-git (hyprland-nvidia-git) package...

**Comment by T-Crypt** [comment]
Yep need to install hyprland-nvidia-git manually (update packages dont update it for some reason)

yay -S hyprland-nvidia-git if you're on nvidia 

then 

reboot

**Comment by TheyCallMeSecond** [comment]
yep system update doesn't show any update for hyprland-git (hyprland-nvidia-git)

**Comment by KareemZohdy** [comment]
> > > delete the Dots folder in your home directory and git clone again the repo and restore from fresh Dots folder
> > 
> > 
> > I have the same problem and i tried your answer and it didn't work, do you have any other way to solve this? ![231012_17h10m27s_screenshot](https://user-images.githubusercontent.com/113604542/274578922-e9890824-2fa7-4d53-8f7a-feccd7f000d4.png)
> 
> no its not the same error...update your hyprland-git (hyprland-nvidia-git) package and reboot your machine...

Thanks, i did what you told me and i can't see the error now.

![231014_21h44m50s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/113604542/3a48c0fb-1b17-4690-80e4-eb71f8729ef2)

**Comment by prasanthrangan** [comment]
this is already fixed!
