### ISSUE TITLE
Emoji are not show font issue

### ISSUE THREAD

**Issue by mahaveergurjar** [prasanthrangan/hyprdots#282]
Emojis are not showing  how to fix this problem
![231001_18h22m30s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/5982261f-4584-4096-a45d-054f00435dc3)
![231001_18h20m46s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/4372f2ab-3c6a-4341-97b7-ca763f544c90)

**Comment by T-Crypt** [comment]
You are most likely missing the font pack for those emojis.

**Comment by mahaveergurjar** [comment]
ok

**Comment by T-Crypt** [comment]
> ok

Did you find the font package for these emjoi's?

**Comment by mahaveergurjar** [comment]
No

**Comment by T-Crypt** [comment]
Try install `noto-font-emjoi`

and then fc-fache -fv 

then reboot

REF: https://archlinux.org/packages/extra/any/noto-fonts-emoji/

**Comment by mahaveergurjar** [comment]
Thanks, emojis are showing

**Comment by Brazlucas** [comment]
> Try installing `noto-font-emjoi`
> 
> and then run `fc-fache -fv` in terminal
> 
> then reboot
> 
> REF: https://archlinux.org/packages/extra/any/noto-fonts-emoji/

thank you, it's working now!
