### ISSUE TITLE
I have no waybar

### ISSUE THREAD

**Issue by Sitolam** [prasanthrangan/hyprdots#283]
My waybar elements disappeared the only thing that is left is the blur. 
![image](https://github.com/prasanthrangan/hyprdots/assets/79202140/a74f8b66-eb82-440b-8cf6-44b7fd5ccfa4)

**Comment by Sitolam** [comment]
This is the output if I run waybar from the terminal.
```bash
[2023-10-01 18:06:02.071] [info] Using configuration file /home/sitolam/.config/waybar/config.jsonc
[2023-10-01 18:06:02.071] [info] Using CSS file /home/sitolam/.config/waybar/style.css
[2023-10-01 18:06:02.084] [warning] module : Unknown module: 
[2023-10-01 18:06:02.084] [warning] module : Unknown module: 
[2023-10-01 18:06:02.084] [warning] module : Unknown module: 

(waybar:2447): GLib-GObject-CRITICAL **: 18:06:02.094: ../glib/gobject/gsignal.c:2088: type 'GtkWindow' is already overridden for signal id '73'

(waybar:2447): GLib-GObject-CRITICAL **: 18:06:02.094: ../glib/gobject/gsignal.c:2088: type 'GtkWindow' is already overridden for signal id '72'
[2023-10-01 18:06:02.094] [warning] module : Unknown module: 
[2023-10-01 18:06:02.094] [warning] module : Unknown module: 
[2023-10-01 18:06:02.094] [warning] module : Unknown module: 
[2023-10-01 18:06:02.103] [info] Bar configured (width: 1920, height: 21) for output: DP-1
[2023-10-01 18:06:02.103] [info] Bar configured (width: 1080, height: 21) for output: eDP-1
```

**Comment by whenryweb** [comment]
Take a look at the contents of config.jsonc

**Comment by T-Crypt** [comment]
@Sitolam 

Looks like its saying unknown module as one of the modules you have is not configured correctly.

Can you run 

`~/.config/hypr/scripts/wbarconfgen.sh` and/or SUPER + ALT + Up Arrow / Down Arrow

**Comment by Sitolam** [comment]
> @Sitolam
> 
> Looks like its saying unknown module as one of the modules you have is not configured correctly.
> 
> Can you run
> 
> `~/.config/hypr/scripts/wbarconfgen.sh` and/or SUPER + ALT + Up Arrow / Down Arrow

I tried that but that didn't work. I'm not sure but I think the issue started when I pressed the keybind too many times.

**Comment by T-Crypt** [comment]
If not that, try restoring your configs.

`/home/Hyprdots/Scripts/restore_cfg.sh`

**Comment by Sitolam** [comment]
> `/home/Hyprdots/Scripts/restore_cfg.sh`

I tried that but that didn't work, maybe that doesn't work because I ran ./install.sh -r twice.

**Comment by T-Crypt** [comment]
Can you copy your config.json file here for the waybar?

**Comment by Sitolam** [comment]
```bash
//   --// waybar config generated by wbarconfgen.sh //--   //

{
// sourced from header module //

    "layer": "top",
    "position": "",
    "mod": "dock",
    "height": 21,
    "exclusive": true,
    "passthrough": false,
    "gtk-layer-shell": true,


// positions generated based on config.ctl //

	"modules-left": ["custom/padd","","custom/padd"],
	"modules-center": ["custom/padd","","custom/padd"],
	"modules-right": ["custom/padd","","custom/padd"],


// sourced from modules based on config.ctl //


// modules for padding //

    "custom/l_end": {
        "format": " ",
        "interval" : "once",
        "tooltip": false
    },

    "custom/r_end": {
        "format": " ",
        "interval" : "once",
        "tooltip": false
    },

    "custom/sl_end": {
        "format": " ",
        "interval" : "once",
        "tooltip": false
    },

    "custom/sr_end": {
        "format": " ",
        "interval" : "once",
        "tooltip": false
    },

    "custom/rl_end": {
        "format": " ",
        "interval" : "once",
        "tooltip": false
    },

    "custom/rr_end": {
        "format": " ",
        "interval" : "once",
        "tooltip": false
    },

    "custom/padd": {
        "format": "  ",
        "interval" : "once",
        "tooltip": false
    }

}

```

**Comment by Sitolam** [comment]
My modules are present I think see the image. 
![image](https://github.com/prasanthrangan/hyprdots/assets/79202140/bd42d5d3-7fb9-4aa6-81a8-e887922af903)

This is the content of my ```~/.config/waybar/config.ctl``` file:
```bash
0|28|bottom|( cpu memory custom/gpuinfo ) ( idle_inhibitor clock )|( hyprland/workspaces hyprland/window )|( network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
0||top|( hyprland/workspaces hyprland/window )|( idle_inhibitor clock )|( cpu memory custom/gpuinfo ) ( network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
0|31|bottom|( custom/power custom/cliphist custom/wbar custom/mode custom/wallchange ) ( wlr/taskbar custom/spotify ) |( idle_inhibitor clock )|( tray battery ) ( network bluetooth pulseaudio pulseaudio#microphone )
0|32|top||( custom/power ) ( tray battery ) ( wlr/taskbar idle_inhibitor clock ) ( custom/cliphist ) ( custom/wbar ) ( custom/wallchange ) ( custom/mode )|
0|31|bottom|( cpu memory custom/gpuinfo ) ( idle_inhibitor clock ) ( hyprland/workspaces )|( wlr/taskbar )|( network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
0|29|top|( wlr/taskbar mpris )|( idle_inhibitor clock )|( network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
0|28|bottom|( custom/power custom/cliphist custom/wbar custom/mode custom/wallchange ) ( idle_inhibitor clock custom/spotify )|( wlr/taskbar )|( tray ) ( network bluetooth pulseaudio pulseaudio#microphone )

```

**Comment by T-Crypt** [comment]
And you have ran the `wbarconfgen.sh` and the `wbarstylegen.sh`? 

I know its going to be related to the wbarconfgen.sh as its not importing the modules into your config.json.

Can you try `~/.config/hypr/scripts/wbarconfgen.sh n` with n being the next waybar style.

**Comment by prasanthrangan** [comment]
> This is the content of my `~/.config/waybar/config.ctl` file:
> 
> ```shell
> 0|28|bottom|( cpu memory custom/gpuinfo ) ( idle_inhibitor clock )|( hyprland/workspaces hyprland/window )|( network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
> 0||top|( hyprland/workspaces hyprland/window )|( idle_inhibitor clock )|( cpu memory custom/gpuinfo ) ( network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
> 0|31|bottom|( custom/power custom/cliphist custom/wbar custom/mode custom/wallchange ) ( wlr/taskbar custom/spotify ) |( idle_inhibitor clock )|( tray battery ) ( network bluetooth pulseaudio pulseaudio#microphone )
> 0|32|top||( custom/power ) ( tray battery ) ( wlr/taskbar idle_inhibitor clock ) ( custom/cliphist ) ( custom/wbar ) ( custom/wallchange ) ( custom/mode )|
> 0|31|bottom|( cpu memory custom/gpuinfo ) ( idle_inhibitor clock ) ( hyprland/workspaces )|( wlr/taskbar )|( network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
> 0|29|top|( wlr/taskbar mpris )|( idle_inhibitor clock )|( network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
> 0|28|bottom|( custom/power custom/cliphist custom/wbar custom/mode custom/wallchange ) ( idle_inhibitor clock custom/spotify
> ```

in the control file, please set one of the line to `1` as every line seems to be set as `0`

**Comment by Sitolam** [comment]
That fixed the issue thank you all for helping me out
