### ISSUE TITLE
Cisco packettracer is not run in hyprland 

### ISSUE THREAD

**Issue by mahaveergurjar** [prasanthrangan/hyprdots#294]
![Uploading 231004_19h42m38s_screenshot.png…]()

**Comment by T-Crypt** [comment]
@mahaveergurjar This isn't an issue with repository so I would suggest to close this issue.

But I can provide you resources on getting this resolved. 

References:

 1. https://wiki.archlinux.org/title/PacketTracer -- Section: Troubleshooting
 2. https://www.reddit.com/r/hyprland/comments/16dm3sv/packettracer_float_goes_wrong/

**Comment by mahaveergurjar** [comment]
Ok
