### ISSUE TITLE
Rofi not working

### ISSUE THREAD

**Issue by Miguerfi** [prasanthrangan/hyprdots#297]
![image](https://github.com/prasanthrangan/hyprdots/assets/91486755/13d5f2bc-1f02-4912-923a-446effb9fb1d)

**Comment by katsuja** [comment]
Try running the create_cache.sh script to recreate the cache. You can find the script in the git you cloned.

**Comment by T-Crypt** [comment]
@Miguerfi 

you could just run the install.sh script again to make sure your Rofi config gets added.

This is an error if the rofi configs are incomplete or missing. 

`Hyprdots/Scripts/install.sh`

**Comment by prasanthrangan** [comment]
can you please share the `~/.config/hypr/themes/Catppuccin-Mocha.conf` file.
Is it working for other themes?

**Comment by Miguerfi** [comment]
the error was occuring because on theme change, if i set manually works fine.
