### ISSUE TITLE
[ENHANCEMENT] Updater script

### ISSUE THREAD

**Issue by MopigamesYT** [prasanthrangan/hyprdots#298]
It would be greatly appreciated if we could have an updater script that has the capability to update the dots WITHOUT MAKING ANY CHANGES TO THE ALREADY MODIFIED DOTS. For instance, if my monitor configuration is set to:
`monitor=eDP-1,preferred,0x0,1
monitor=HDMI-A-1,1920x1080@60,1920x0,1
workspace=eDP-1,1`
or for example my keyboard and keybind settings, i dont want them deleted. would it be possible to do something like this?

**Comment by T-Crypt** [comment]
Just pull the latest changes and run the install script as below -
```
cd ~/Hyprdots/Scripts
git pull
./install.sh -r
```
It will backup your existing config files and copy the updated ones!

I run the install.sh script all the time, it has never messed with my monitors.conf file.

**Comment by prasanthrangan** [comment]
> It would be greatly appreciated if we could have an updater script that has the capability to update the dots WITHOUT MAKING ANY CHANGES TO THE ALREADY MODIFIED DOTS. For instance, if my monitor configuration is set to:
> `monitor=eDP-1,preferred,0x0,1 monitor=HDMI-A-1,1920x1080@60,1920x0,1 workspace=eDP-1,1`
> or for example my keyboard and keybind settings, i dont want them deleted. would it be possible to do something like this?

Hi, the update script already does preserve  these files -

```
~/.config/hypr/monitors.conf
~/.config/hypr/userprefs.conf
```
So please use these files to configure hyprland to your preference.

**Comment by heysl** [comment]
> So if I place my keybinds in userprefs.conf & monitor setup w/wrkspaces in monitors.conf it will source those first, correct?

If I'm not wrong, userprefs.conf and monitors.conf are being sourced **after** the other conf-files, so your preferences overwrite the hyprdots defaults.
However, in my experience keybindings do not get overwritten! (Or maybe I'm doing it wrong)
If you have a custom keybinding that has the same hotkey-combination as some hyprdot-keybinding, **both** execute.
So conflicting keybindings have to be commented out in the hyprdot-configs (and again after every rebuild I presume)

**Comment by prasanthrangan** [comment]
> However, in my experience keybindings do not get overwritten! (Or maybe I'm doing it wrong)

yup, this is expected behavior... you'll have to use different keys for for your specific usecase... 
or if you need to change the default keys, you can copy your `keybindings.conf` from the backup directory if you run install script.

The monitors configured in `monitors.conf` will be override the `auto` set in `hyprland.conf`.

**Comment by prasanthrangan** [comment]
closing this as this feature already exists!
