### ISSUE TITLE
vs code theme

### ISSUE THREAD

**Issue by TheyCallMeSecond** [prasanthrangan/hyprdots#299]
i think there is a small bug in vs code theming...
In the file "themeswitch.sh" we have "$ThemeSet" controlled by "$ThemeCtl" and "$ThemeCtl" gets the theme name from the file "/swww/wall.ctl" (which has the themes name ) and it "sed" to $ConfDir/Code/User/settings.json file for theming vs code, right?
the problem is here...
some theme's name in "wall.ctl" file doesnt match with vs code theme name...for example Tokyo-Night...the theme name in "wall.ctl" file is "Tokyo-Night" but this theme name in vs code is "Tokyo Night"
so when we switch theme to tokyo night the vs code theme doesnt change

![01](https://github.com/prasanthrangan/hyprdots/assets/73380906/4787efc5-c671-4802-94ba-4d6302257390)

![02](https://github.com/prasanthrangan/hyprdots/assets/73380906/15022c78-1081-4eba-a2e3-821c81b7151b)

i found these too :
**Rose-Pine --> Rose Pine**
**Catppuccin-Mocha --> Catppuccin Mocha**
**Catppuccin-Latte --> Catppuccin Latte**

**Comment by TheyCallMeSecond** [comment]
When we reopen vs code, the theme changes but its not the right theme (Tokyo Night in this example)

the theme after switching:
![231006_03h11m35s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/73380906/b6354abb-2adf-4142-8592-a3ebdd42a087)

the theme after reopening:
![231006_03h12m23s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/73380906/ace9c87a-d5cf-4646-96a5-e1b8e8344df2)

the right Tokyo Night theme:
![231006_03h13m50s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/73380906/7b046be4-5499-4606-ba76-dd31e05d37fd)

**Comment by T-Crypt** [comment]
Ill work on fixing this today.

**Comment by prasanthrangan** [comment]
Hi, looks like you have updated the theme extensions...
This will reset the changes i'd made to the vscode theme extensions!

So you either change/apply the themes manually or remove the updated extensions and restore the old version from [here](https://github.com/prasanthrangan/hyprdots/blob/main/Source/arcs/Code_Extensions.tar.gz)

**Comment by TheyCallMeSecond** [comment]
yes your right tnx

**Comment by prasanthrangan** [comment]
I'll try to separate the vscode theme from the theme extensions.. so that it remains static!

**Comment by T-Crypt** [comment]
@prasanthrangan 

Name: Material Theme Kit
Id: ms-vscode.Theme-MaterialKit
Description: Material themes for VS Code. Based on the TextMate themes.
Version: 0.1.4
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.Theme-MaterialKit

Lets add this to the extensions for Material-Sakura 

edit package.json for Material Night theme to Material-Sakura

**Comment by TheyCallMeSecond** [comment]
nice! added to my config

**Comment by T-Crypt** [comment]
@TheyCallMeSecond - I updated the code extensions in my latest pull request as well.

**Comment by kRHYME7** [comment]
Hello👋 This issue might be already been resolved as we already implemented a different way to handle vscode extensions. I'll close this as resolved.
