### ISSUE TITLE
Switch Mode and wallpaper didn't work

### ISSUE THREAD

**Issue by FatngatirBilek** [prasanthrangan/hyprdots#3]
After changing the resolution on hyprland.conf suddenly the wallpaper becomes the default hyperland and when I press the switch mode button everything gets messed up. is my way of changing the resolution wrong?

**Comment by FatngatirBilek** [comment]
if i reset the monitor settings to prefered,auto,auto then everything works.

**Comment by prasanthrangan** [comment]
i've updated the hyprland.conf file... so it lo longer a symlink now! can you try using the latest configs

**Comment by FatngatirBilek** [comment]
i change my resolution to 1920x1080 manually and it won't work. the wallpaper change to default hyprland

**Comment by FatngatirBilek** [comment]
Demonstration:


https://user-images.githubusercontent.com/81058978/234440491-a815c236-0c22-4355-98e4-d68279cf37f0.mp4

**Comment by prasanthrangan** [comment]
looks like setting resolution by wlr-randar is crashing the swww daemon.
please try using hyprland.conf to set your correct monitor resolution.
also can you try running the script manually and see if gives error message -
```
cd ~/.config/swww/
./swwwallpaper.sh
swww query
swww init
```

**Comment by FatngatirBilek** [comment]
I set my res on my hyprland.conf:
![image](https://user-images.githubusercontent.com/81058978/234450223-d1d2f7ba-0d83-4b8a-8a33-c68ec30d3a45.png)

I run script manually:
![image](https://user-images.githubusercontent.com/81058978/234450077-91fe190a-42c7-4788-af17-7e6c19dae2e2.png)

**Comment by prasanthrangan** [comment]
looks like its unable to recover from previous run crash...
can you delete the cache directory `~/.cache/swww/`

![image](https://user-images.githubusercontent.com/106020512/234470327-31840649-7bef-4cc3-b813-d774120b0453.png)

and then run these -
```
swww kill
cd ~/.config/swww/
./swwwallpaper.sh
```

**Comment by FatngatirBilek** [comment]
Yes, it worked now thanks <3

**Comment by FatngatirBilek** [comment]
yes, it worked now thanks <3
