### ISSUE TITLE
Gruvbox Dolphin problem

### ISSUE THREAD

**Issue by kraddoc** [prasanthrangan/hyprdots#300]
Is seems there is a bug in a new Gruvbox theme, as a result instead of an icon Dolphin renders "Show Hidden Files" button as text.

Normal behavior: 
![image](https://github.com/prasanthrangan/hyprdots/assets/69300400/385b65aa-926c-43ba-8511-7be0bf4d906a)

Bugged behavior:
![image](https://github.com/prasanthrangan/hyprdots/assets/69300400/494ed331-1afc-4a83-8b8b-62deb8a09011)

**Comment by T-Crypt** [comment]
Let me find the icon and Ill repackage the Icon_Gruvbox.tar.gz and update the repo.

**Comment by prasanthrangan** [comment]
This is fixed in 1933d18

**Comment by T-Crypt** [comment]
@prasanthrangan 

Did you fix the hidden file issue?

Some reason the icons are present in "Actions" and all there for the gnumeric-row and gnumeric-column.

**Comment by prasanthrangan** [comment]
> Did you fix the hidden file issue?

yup, fixed it -

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/18ca02b8-4b2f-4e2b-be24-90a2039ea803)
