### ISSUE TITLE
[laptop] Request brightnes icon

### ISSUE THREAD

**Issue by nx-smul** [prasanthrangan/hyprdots#302]
hi kindly  make a brigthness control icon on waybar thanks

**Comment by katsuja** [comment]
Then do this:
touch backlight.jsonc ~/.config/waybar/modules
Then open it with your editor and paste this content:
❯ ls /sys/class/backlight/
intel_backlight -> ../../devices/pci0000:00/0000:00:02.0/drm/card1/card1-eDP-1/intel_backlight
For amd amdgpu_bl0

![231008_14h46m47s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/cb3d0d18-410e-453e-bdec-817ab0f57603)

"backlight": {
     "device": "intel_backlight", <-----for intel
     "format": "{percent}% {icon}",
     "format-icons": ["", ""]
},

Open the config.ctl file and add "backlight" in:
nano ~/.config/waybar/config.ctl

![231008_14h26m58s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/b030b9ee-01b2-469d-bba8-19032486a761)

Open the file ~/.config/waybar/style.css and add "#backlight" in:
#backlight,
![231008_14h28m47s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/53b730be-6917-4753-a966-55b175347f67)



Exit and re-enter Hyprland

**Comment by nx-smul** [comment]
one slight problen this will reset everytime when I'll resotre updated config. so if he implements this this will be better

**Comment by kRHYME7** [comment]
maybe we could PR?

**Comment by katsuja** [comment]
> maybe we could PR?

What does this mean? I'm not very familiar with abbreviations (PR). I'm embarrassed 😅

**Comment by T-Crypt** [comment]
PR = Pull Request. 

Fork repo into your repositories 

Make changes > Contribute

**Comment by T-Crypt** [comment]
Fixed in #320  -- Can close this now

**Comment by nx-smul** [comment]
Topic closed
