### ISSUE TITLE
No notification about changing the keyboard layout.

### ISSUE THREAD

**Issue by NerdzzyDev** [prasanthrangan/hyprdots#306]
I wrote this script for myself, but I think it might be useful to someone.
![image](https://github.com/prasanthrangan/hyprdots/assets/55660001/124e9df5-2da7-4c5f-abbd-073be1079ee9)

```
#!/bin/bash

# Change the current keyboard layout
hyprctl switchxkblayout at-translated-set-2-keyboard next

# Run the hyprctl command and store the output in the variable devices_output
devices_output=$(hyprctl devices)

# Extract active keyboard layouts
active_layouts=$(echo "$devices_output" | grep "active keymap" | awk '{print $NF}')

# Select the first unique value from the active layouts
unique_layout=$(echo "$active_layouts" | tr ' ' '\n' | sort -u | head -n1)
echo $unique_layout

# Customize these paths with your own icon files
ru_icon="/path/to/your/ruflag.svg"
us_icon="/path/to/your/usflag.svg"

# Customize the layout you want to check (e.g., replace "Russian" with your layout name)
#run below command to get current keyboard layout name
# hyprctl devices | grep "active keymap" | awk '{print $NF}'
custom_layout="YourLayoutName" #(e.g "Russian")

# Notification
if [ "$unique_layout" == $custom_layout]; then
    notify-send -u low -t 2000 --icon="$ru_icon" 'Keyboard layout' 'Current layout is: RU'
else
    notify-send -u low -t 2000 -- icon="$us_icon" 'Keyboard layout' 'Current layout is: US'
fi
```
#run below command to get current keyboard layout name
`hyprctl devices | grep "active keymap" | awk '{print $NF}'`

 Then add it in userprefs.cong (~/.config/hypr/userprefs.conf)

```
# Castum shortcuts
#I use super + space to change keyboard layout
bind = $mainMod, Space, exec, ~/.config/hypr/scripts/SCRIPTNAME.sh # change keyboard Layout #change script name!

#input
input {
    kb_layout = us, ru #indicate the languages you will use
    kb_variant =
    kb_model =
    kb_options = 
    kb_rules =
    follow_mouse = 1
}
```

**Comment by prasanthrangan** [comment]
Hi, Thank you so much!

The issue with my system is that `hyprctl devices | grep "active keymap"` does not fetch my correct keyboard.
So let me try and integrate this.

**Comment by prasanthrangan** [comment]
> This at least provides the keyboard input device.

hmm ya, let me try this when I get to my PC.

**Comment by NerdzzyDev** [comment]
> hyprctl devices | grep "keyboard"

This does not output the layout name to make a notification with the current layout

**Comment by NerdzzyDev** [comment]
> Hi, Thank you so much!
> 
> The issue with my system is that `hyprctl devices | grep "active keymap"` does not fetch my correct keyboard. So let me try and integrate this.

Thank you very much for this project. I really really like him, let me know if I can help with his development in any way. Regarding the layout, maybe it’s worth making a separate script? He could ask the user what layouts he would like to add. After which I downloaded the necessary flag icons. And if necessary, switched them cyclically. My script version supports more than 2 layouts. If necessary, I can make a script like this

**Comment by T-Crypt** [comment]
> > hyprctl devices | grep "keyboard"
> 
> 
> 
> This does not output the layout name to make a notification with the current layout

It's not to get the layout, this needs to be modified as the section 

'hyprctl switchxkblayout at-translated-set-2-keyboard next' 

Does not change the keyboard layout as you need the current device/keyboard to change the layout. Translated-set-2-keyboard is not a device. 

It needs 

'Hyprctl switchxblayout [device] next'

So this needs to be modified to 

'''
hyprctl switchxblayout $keyboard next

keyboard=$(hyprctl devices | grep "keyboard" | awk '{print $2}')
echo $keyboard
'''

**Comment by NerdzzyDev** [comment]
> > > hyprctl devices | grep "keyboard"
> > 
> > 
> > This does not output the layout name to make a notification with the current layout
> 
> It's not to get the layout, this needs to be modified as the section
> 
> `hyprctl switchxkblayout at-translated-set-2-keyboard next`
> 
> does not change the keyboard layout as you need the current device/keyboard to change the layout. Translated-set-2-keyboard is not a device.
> 
> It needs `hyprctl devices` to get the current keyboard/device.
> 
> `Hyprctl switchxblayout [device] next`
> 
> So this needs to be modified to something like this
> 
> ```
> keyboard=$(hyprctl devices | grep "keyboard" | awk '{print $2}')
> echo $keyboard
> 
> hyprctl switchxblayout $keyboard next
> ```


Thanks for your answer! But isn't at-translated-set-2-keyboard a generic name?
Please check the output of hyprctl devices (assuming you have 2 keyboard layouts installed)

Is the name different?

output for me:
```
hyprctl devices | awk '/Keyboards:/,/^$/' | sed '/^$/d'
```

```
Keyboards:
	Keyboard at 55eb6e44c2f0:
		video-bus
			rules: r "", m "", l "us, ru", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 55eb6e444270:
		power-button
			rules: r "", m "", l "us, ru", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 55eb6e7f2c50:
		huawei-wmi-hotkeys
			rules: r "", m "", l "us, ru", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 55eb6e819d20:
		at-translated-set-2-keyboard
			rules: r "", m "", l "us, ru", v "", o ""
			active keymap: English (US)
			main: yes
```
And only at-translated-set-2-keyboard is responsible for changing the layout.

It seems to me that I don't know how to solve this problem.

I might suggest using

```
hyprctl devices | awk -F '\n' 'BEGIN {RS=""} /main: yes/ {print $18}'

at-translated-set-2-keyboard
```
But it seems to me that this is a less universal option.

**Comment by T-Crypt** [comment]
I dont think its that generic.. 

My output of `hyprctl devices`

```
 hyprctl devices
mice:
	Mouse at 55611ab50500:
		asus-keyboard-1
			default speed: 0.00000
	Mouse at 55611ab568a0:
		asue120a:00-04f3:319b-mouse
			default speed: 0.00000
	Mouse at 55611a6f4d00:
		asue120a:00-04f3:319b-touchpad
			default speed: 0.00000


Keyboards:
	Keyboard at 55611a7bae60:
		asus-wireless-radio-control
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 55611a7ce970:
		video-bus
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 55611a960800:
		power-button
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 55611ac092c0:
		sleep-button
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 55611ac46440:
		asus-keyboard
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 55611ac809b0:
		asus-wmi-hotkeys
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: yes


Tablets:


Touch:


Switches:
	Switch Device at 55611ab68240:
		Lid Switch
```

**Comment by NerdzzyDev** [comment]
> I dont think its that generic..
> 
> My output of `hyprctl devices`
> 
> ```
>  hyprctl devices
> mice:
> 	Mouse at 55611ab50500:
> 		asus-keyboard-1
> 			default speed: 0.00000
> 	Mouse at 55611ab568a0:
> 		asue120a:00-04f3:319b-mouse
> 			default speed: 0.00000
> 	Mouse at 55611a6f4d00:
> 		asue120a:00-04f3:319b-touchpad
> 			default speed: 0.00000
> 
> 
> Keyboards:
> 	Keyboard at 55611a7bae60:
> 		asus-wireless-radio-control
> 			rules: r "", m "", l "us", v "", o ""
> 			active keymap: English (US)
> 			main: no
> 	Keyboard at 55611a7ce970:
> 		video-bus
> 			rules: r "", m "", l "us", v "", o ""
> 			active keymap: English (US)
> 			main: no
> 	Keyboard at 55611a960800:
> 		power-button
> 			rules: r "", m "", l "us", v "", o ""
> 			active keymap: English (US)
> 			main: no
> 	Keyboard at 55611ac092c0:
> 		sleep-button
> 			rules: r "", m "", l "us", v "", o ""
> 			active keymap: English (US)
> 			main: no
> 	Keyboard at 55611ac46440:
> 		asus-keyboard
> 			rules: r "", m "", l "us", v "", o ""
> 			active keymap: English (US)
> 			main: no
> 	Keyboard at 55611ac809b0:
> 		asus-wmi-hotkeys
> 			rules: r "", m "", l "us", v "", o ""
> 			active keymap: English (US)
> 			main: yes
> 
> 
> Tablets:
> 
> 
> Touch:
> 
> 
> Switches:
> 	Switch Device at 55611ab68240:
> 		Lid Switch
> ```

Oh, sorry. I think you're right, but I can't imagine how this can be implemented. I don't really like the option I suggested,
If I understand correctly, then there may be a different number of devices (for example, bluetooth connected keyboards)
Then, we need to grab main: yes and print the name - this would be a more universal option, but my skills are not enough to do this.
I thought "at-translated-set-2-keyboard" was a universal option because something was said about it on the wiki
[switchxkblayout](https://wiki.hyprland.org/Configuring/Using-hyprctl/#switchxkblayout)

P.S.
Sorry for my English, I understand that it may be difficult to read and understand me. But this is not my native language, now I’m just learning it.

**Comment by T-Crypt** [comment]
@NerdzzyDev dude no worries on the English -- no judgement between us Open Source guru's! Coding / Development is an accepting community!! 

Yeah @prasanthrangan and I were looking into this a while ago and it seems to be more difficult to implement off first glances to get this going as it can be quite different for each users devices. 

(honestly hoping that Hypr Development develops an easier solution than the hyprctl switchxblayout as its very user specific on the device) 

I'll look into this a little more as this is like the 3rd or 4th request for this option -- Tittu has it in the TODO as well (enhancement)

**Comment by kRHYME7** [comment]
Hello Do we only need to parse the current keyboard?
Is the current keyboard the one with ``` main: yes ''' ?

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/1253af54-9b31-4c4b-a44d-086d388f47de)

**Comment by T-Crypt** [comment]
> Hello Do we only need to parse the current keyboard? Is the current keyboard the one with ``` main: yes ''' ?
> 
> ![image](https://user-images.githubusercontent.com/53417443/274374734-1253af54-9b31-4c4b-a44d-086d388f47de.png)

Check my output of the hyprctl devices above -- It seems my main keyboard is `asus-keyboard` but "main: yes" is on my asus-wmi-hotkeys so this might not be consistent

**Comment by T-Crypt** [comment]
Okay I did it! 

Python is my bestfriend :) 

```
#!/usr/bin/python3
import json
import subprocess
import sys
 
def get_keyboards():
    output = subprocess.check_output(["hyprctl","devices","-j"]).decode("utf-8")
    if output:
        devices=json.loads(output)
    return devices["keyboards"]
 
def change_layout():
    active_keymap=False
    for keyboard in get_keyboards():
        if active_keymap and active_keymap != keyboard["active_keymap"]:
            print ("The keyboard %s has the layout %s which differs from %s, equalizing"%(keyboard["name"],keyboard["active_keymap"],active_keymap))
            return False #Not every keyboard is at the same layout currently
        active_keymap=keyboard["active_keymap"]
        command = ["hyprctl","switchxkblayout",keyboard["name"],"next"]
        result = subprocess.run(command,stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if result.returncode == 0:
            print("Switched the layout for %s.\n%s" % (keyboard["name"],result.stdout))
        else:
            sys.stderr.write("Error while switching the layout for %s.\n%s\n" % (keyboard["name"],result.stderr))
            got_error = True
    return True #All layouts had been cycled successfully
 
got_error = False
while not change_layout():
    pass
if got_error:
    sys.stderr.write("Some errors were found during the process...\n")
    sys.exit(1)
```

**Comment by T-Crypt** [comment]
Check #314  

checkout with github cli and test please 

cd into $HOME/Hyprdots and run 

`gh pr checkout 314`

**Comment by T-Crypt** [comment]
Ill work on the notification next.

**Comment by kRHYME7** [comment]
Hello I have a proposal to make in handling common hyprland events can we utilized the https://github.com/hyprwm/contrib/#shellevents 
I think having a centralized event handling  is better



![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/b1b635f0-f21c-493f-a7e0-6172e502595f)

**Comment by T-Crypt** [comment]
I made it integrated with the python script itself as the shellevents have to be built manually and cannot be added to the custom_apps.lst to install.

The script is updated and added to the PR.

**Comment by kRHYME7** [comment]
Thank you! The shellevents project is only a 1 file script so maybe we could integrate it, but much more than this should be on separate discussion.  Just for future reference to declutter the project, as of now, it is not concerning. Cheers

**Comment by T-Crypt** [comment]
@NerdzzyDev -- We can close this out now!
