### ISSUE TITLE
Delayed Rendering

### ISSUE THREAD

**Issue by jenil1122** [prasanthrangan/hyprdots#308]
Rofi image rendering takes time it uses to work great before 
rofi launches normally but it takes around 30 miliseconds to render image of Background..
![231010_20h39m02s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/78353041/7e7e2f59-84ec-4398-87e6-e849abec23a2)

**Comment by jenil1122** [comment]
i tried and still same issue
maybe we can preload image files to support old devices

**Comment by prasanthrangan** [comment]
> i tried and still same issue
> maybe we can preload image files to support old devices

I think rofi already does it... Let me look into it.
You can also try adjusting the cache image quality in `swwwallpaper.sh` if that helps -

https://github.com/prasanthrangan/hyprdots/blob/2adb9aeb6f86e2089a4d7eba67ad75eb2bc9a935/Configs/.config/hypr/scripts/swwwallpaper.sh#L17

https://github.com/prasanthrangan/hyprdots/blob/2adb9aeb6f86e2089a4d7eba67ad75eb2bc9a935/Configs/.config/hypr/scripts/swwwallpaper.sh#L22

https://github.com/prasanthrangan/hyprdots/blob/2adb9aeb6f86e2089a4d7eba67ad75eb2bc9a935/Configs/.config/hypr/scripts/swwwallpaper.sh#L26

**Comment by NerdzzyDev** [comment]
> I think rofi already does it... Let me look into it.
> You can also try adjusting the cache image quality in `swwwallpaper.sh` if that helps -

I cleared the rofi cache and applied these settings, but the problem remained

**Comment by kRHYME7** [comment]
hello is your rofi still **rofi-lbonn-wayland**?
I had the same issue a few weeks ago, The reason is I installed Another version of Rofi.


Please Ignore this if it doesn't  help.

**Comment by kRHYME7** [comment]
Ow, I think I also got this issue, 


at launch

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/0736cb4e-839a-4d7d-b46b-d987d5498866)

loads very less than a second but noticeable  and slow enough that I can printscreen

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/bdd1feb2-267a-4ac5-ae54-2ea750fbe43f)


So far this is not a problem for me, also the icons loaded on mine.

**Comment by prasanthrangan** [comment]
this commit e29e544 only removes the white background before the blurred image is loaded.
