### ISSUE TITLE
Function for turning bluetooth on and off using a keyboard shortcut

### ISSUE THREAD

**Issue by NerdzzyDev** [prasanthrangan/hyprdots#309]
Function for turning bluetooth on and off using a keyboard shortcut

```
#!/bin/bash

# Function to enable Bluetooth
enable_bluetooth() {
    bluetoothctl power on
    notify-send -i "/path/to/your/bluetooth-on-icon.svg" "Bluetooth ON"
}

# Function to disable Bluetooth
disable_bluetooth() {
    bluetoothctl power off
    notify-send -i "/path/to/your/bluetooth-off-icon.svg" "Bluetooth off"
}

toggle_bluetooth() {
    # Prompt for a password using zenity
    password=$(zenity --password --title "Authenticate with sudo")

    # Check the password
    if echo "$password" | sudo -Sv; then
        # Check the current Bluetooth status
        bluetooth_status=$(bluetoothctl show | grep "Powered: yes")

        if [ -n "$bluetooth_status" ]; then
            # Bluetooth is enabled, so disable it
            disable_bluetooth
        else
            # Bluetooth is disabled, so enable it
            enable_bluetooth
        fi
    else
        echo "Failed to authenticate with sudo."
    fi
}

# Call the function to perform the actions
toggle_bluetooth
```

Remember to replace "/path/to/your/bluetooth-on-icon.svg" and "/path/to/your/bluetooth-off-icon.svg" with the actual file paths for your Bluetooth icons.

Don't forget to add the keyboard shortcut to userprefs.conf
```
bind = $mainMod, B, exec, ~/.config/hypr/scripts/scriptname.sh # toggle bluetooth
```

**Comment by stove-jeebs** [comment]
I value your efforts, but I believe such features should be tailored to individual preferences. Not every function requires a shortcut, especially if it's not frequently used by the average user or isn't a core feature.

**Comment by NerdzzyDev** [comment]
> Hi, I value your efforts, but I believe such features should be tailored to individual preferences. Not every function requires a shortcut, especially if it's not frequently used by the average user or isn't a core feature to Hyprland.

sorry, but thanks, I think you're right.  I really like this project, can I somehow help the development of the project?

**Comment by stove-jeebs** [comment]
You can highlight potential problems by creating issues and participate in relevant discussions. If you have suggestions or concerns, feel free to submit pull requests with any proposed changes to the repository, ensuring you provide valid reasoning for each. Additionally, you can check out the GitHub [Projects > Hyprdots](https://github.com/users/prasanthrangan/projects/1/views/1) section to see features that are either planned or under development.
