### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by candied-apple** [prasanthrangan/hyprdots#311]
![231011_04h10m19s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/50497574/bb43935c-2357-4e85-b2b0-92fb0c32503e)

I dont know why im getting this 
this is a fresh install im using dual boot with windows.

**Comment by dev-Gois** [comment]
i having the same error

**Comment by kRHYME7** [comment]
hello For those having this issue, I'll PR ASAP within today if @prasanthrangan  may be busy. 

Reasons:
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/97ebd533-b56f-496a-bfea-be44e20b6940)

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/e4dede7f-0f34-4b3d-8f2b-a91a8cc921b6)

Please edit your config  while waiting for the update.



Here is  a quick fix for you 


~.config/hypr/themes/colors.conf
```
general {
    col.active_border = rgba(0D1935ff) rgba(553054ff) 45deg
    col.inactive_border = rgba(242749cc) rgba(6F3A65cc) 45deg

}

group {
    col.border_active = rgba(0D1935ff) rgba(553054ff) 45deg
    col.border_active = rgba(242749cc) rgba(6F3A65cc) 45deg
    col.border_locked_active = rgba(0D1935ff) rgba(553054ff) 45deg
   col.border_locked_inactive = rgba(242749cc) rgba(6F3A65cc) 45deg
}
```
~/.config/hypr/themes/theme.conf
```
exec = kvantummanager --set Catppuccin-Mocha
exec = gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-dracula'
exec = gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-Mocha'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'


general {
    gaps_in = 1
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.inactive_border = rgba(b4befecc) rgba(6c7086cc) 45deg
    layout = dwindle
    resize_on_border = true
}

group { 
        col.border_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.border_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
    col.border_locked_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.border_locked_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
}

decoration {
    rounding = 10
    drop_shadow = false

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

blurls = waybar
```

**Comment by nickdritan** [comment]
Changed the hypr/themes/theme.conf according to the new documentation and I think it works now:
```
general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.inactive_border = rgba(b4befecc) rgba(6c7086cc) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.border_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
    col.border_locked_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.border_locked_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
}
```

**Comment by MysticalPvE** [comment]
Same config error here, any fix so I can continue using hyprdots?

**Comment by candied-apple** [comment]
Someone told me :

Changed the hypr/themes/theme.conf according to the new documentation and I think it works now:

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.inactive_border = rgba(b4befecc) rgba(6c7086cc) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.border_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
    col.border_locked_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.border_locked_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
}


And it worked for me too

**Comment by kRHYME7** [comment]
Hello please check Pull Request [#312 ](https://github.com/prasanthrangan/hyprdots/pull/312)

**Comment by Balssh** [comment]
I just updated the config and it gives me the error about relating col.border_locked_inactive. I suspect this has to do with the fact I have hyprland-nvidia-git and not hyprland-git. Any others having this?

**Comment by Gedankenn** [comment]
same here, to solve the problem i comented the lines where the error was due. expecting a proper solution.

i have hyprland-git and tryed the hyprland with the same error. didnt try the hyprland-nvidia-git.

**Comment by kRHYME7** [comment]
> I just updated the config and it gives me the error about relating col.border_locked_inactive. I suspect this has to do with the fact I have hyprland-nvidia-git and not hyprland-git. Any others having this?


Hello for this issue, as of the moment can you please use the repo prior to commit #312?
While waiting for hyprland-nvidia dev to update changes.

**Comment by kRHYME7** [comment]
> same here, to solve the problem i comented the lines where the error was due. expecting a proper solution.
> 
> i have hyprland-git and tryed the hyprland with the same error. didnt try the hyprland-nvidia-git.

Good day! @Gedankenn 

Can we see the config that you commented out? 
Also please use the latest commit if you're using hyprland-git. Thanks

**Comment by T-Crypt** [comment]
@Balssh 

I had to update hyprland-nvidia-git manually. 

Try 

Yay -S hyprland-nvidia-git 

Then reboot 

For some reason, it didn't come as a package update running "yay" or the updates module on waybar.

**Comment by katsuja** [comment]
With the latest one I get this error:
![231012_16h41m51s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/b91fffca-497c-4099-a939-8b01feb859bc)
I have an amd rx580 card

**Comment by katsuja** [comment]
Forget it! Fixed by switching from hyprland version to hyprland-git version

**Comment by Balssh** [comment]
> > I just updated the config and it gives me the error about relating col.border_locked_inactive. I suspect this has to do with the fact I have hyprland-nvidia-git and not hyprland-git. Any others having this?
> 
> @Balssh Hello for this issue, as of the moment can you please use the repo prior to commit #312? While waiting for hyprland-nvidia dev to update changes.

One question, I have hyprland-nvidia-git, but checking AUR I see that hyprland-nvidia has a newer update date. Do you happen to know which are the differences?
