### ISSUE TITLE
ISSUE 101

### ISSUE THREAD

**Issue by nx-smul** [prasanthrangan/hyprdots#316]
![image](https://github.com/prasanthrangan/hyprdots/assets/68707319/74859487-3479-40b9-acf5-f210fc3d0552)
WHAT'S THE ISSUE WITH THIS THING

**Comment by kRHYME7** [comment]
Hello Are you using hyprland-nvidia?

**Comment by nickdritan** [comment]
This is because of a hyprland update, but I think that the latest commit fixes that issue

**Comment by nx-smul** [comment]
> Hello Are you using hyprland-nvidia?

no

**Comment by nx-smul** [comment]
not fixed in mine 

> This is because of a hyprland update, but I think that the latest commit fixes that issue

not fixed in mine st. also wlogout showing full screen crop

**Comment by nx-smul** [comment]
another weird isse wlogout menu launching full screen 
![image](https://github.com/prasanthrangan/hyprdots/assets/68707319/42f663b2-8a6a-4236-b061-d2dc547bfb12)

**Comment by GeorgeAndreiBals** [comment]
Have you updated hyprland? I have this problem because I use hyprland nvidia and it's kind of outdated.

**Comment by nx-smul** [comment]
> Have you updated hyprland? I have this problem because I use hyprland nvidia and it's kind of outdated.

I am using hyprland from extra repo I guess I have to wait for update

**Comment by nx-smul** [comment]
is the wlogout issue is related to hyprland?

**Comment by kRHYME7** [comment]
> is the wlogout issue is related to hyprland?
> 

It's not.

**Comment by kRHYME7** [comment]
What is the output for 

cat $HOME/.config/hypr/scripts/logoutlaunch.sh



Sorry man, I can only help you using my phone, I broke my  Arch installation , right now.

**Comment by nx-smul** [comment]
ok old config fixed it thanks for the help

**Comment by nx-smul** [comment]
I guess there is some problem with the newer one

**Comment by kRHYME7** [comment]
> ok old config fixed it thanks for the help 


Can you please share your output for
``` hyprctl monitor ```

Tnx
