### ISSUE TITLE
It used to work, but now it can't run after the update

### ISSUE THREAD

**Issue by hui3215** [prasanthrangan/hyprdots#318]
![image](https://github.com/prasanthrangan/hyprdots/assets/53279456/52dded15-ece3-47c8-9279-a7335f892d29)

**Comment by prasanthrangan** [comment]
Hi, did you update hyprland or just configs?

**Comment by hui3215** [comment]
> Hi, did you update hyprland or just configs?

Hi, I executed the installation script again, this problem is solved, but my waybar disappeared, his error is as follows, please help me solve it, greatly appreciated

```shell
(waybar:62860): Gtk-WARNING **: 15:43:44.511: cannot open display: :1
```

**Comment by T-Crypt** [comment]
Can I see the whole output when you run `waybar` in terminal?

**Comment by DiegoSof2** [comment]
> Hi, did you update hyprland or just configs?

I tried to update hyperland-nvidia but this error happened



extra/rhash  1.4.3-1      1.4.3-1        0.00 MiB

Total Installed Size:  0.32 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                                                                              [------------------------------------------------------------------------------------------------] 100%
(1/1) checking package integrity                                                                                                                            [------------------------------------------------------------------------------------------------] 100%
(1/1) loading package files                                                                                                                                 [------------------------------------------------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                                                                                           [------------------------------------------------------------------------------------------------] 100%
(1/1) checking available disk space                                                                                                                         [------------------------------------------------------------------------------------------------] 100%
warning: hook /etc/pacman.d/hooks/99-snapper-pre-post.hook line 14: overwriting previous definition of Description
warning: hook /etc/pacman.d/hooks/99-snapper-pre-post.hook line 15: overwriting previous definition of When
warning: hook /etc/pacman.d/hooks/99-snapper-pre-post.hook line 16: overwriting previous definition of Exec
:: Processing package changes...
(1/1) reinstalling rhash                                                                                                                                    [------------------------------------------------------------------------------------------------] 100%
warning: hook /etc/pacman.d/hooks/99-snapper-pre-post.hook line 14: overwriting previous definition of Description
warning: hook /etc/pacman.d/hooks/99-snapper-pre-post.hook line 15: overwriting previous definition of When
warning: hook /etc/pacman.d/hooks/99-snapper-pre-post.hook line 16: overwriting previous definition of Exec
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Creating post-transaction snapshot...
Unknown command 'post'.
Try 'snapper --help' for more information.
error: command failed to execute correctly
❯ yay -S hyprland-nvidia-git
AUR Explicit (1): hyprland-nvidia-git-0.27.2.r62.g08651736-1
:: PKGBUILD up to date, skipping download: hyprland-nvidia-git
  1 hyprland-nvidia-git              (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 1
:: Deleting (1/1): /home/diego/.cache/yay/hyprland-nvidia-git
HEAD is now at 65db221 Fix hyprland headers install path
Removing hyprland-nvidia-git/
Skipping repository src/hyprland-nvidia-git
  1 hyprland-nvidia-git              (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 1
 -> hyprland-nvidia-git: No changes -- skipping

:: Proceed with install? [Y/n] y
==> Making package: hyprland-nvidia-git 0.27.2.r62.g08651736-1 (Sun 15 Oct 2023 01:13:28 AM -03)
==> Retrieving sources...
  -> Cloning hyprland-nvidia-git git repo...
Cloning into bare repository '/home/diego/.cache/yay/hyprland-nvidia-git/hyprland-nvidia-git'...
remote: Enumerating objects: 29238, done.
remote: Counting objects: 100% (5984/5984), done.
remote: Compressing objects: 100% (690/690), done.
remote: Total 29238 (delta 5606), reused 5416 (delta 5291), pack-reused 23254
Receiving objects: 100% (29238/29238), 128.10 MiB | 33.46 MiB/s, done.
Resolving deltas: 100% (22531/22531), done.
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    hyprland-nvidia-git ... Skipped
:: (1/1) Parsing SRCINFO: hyprland-nvidia-git
==> Making package: hyprland-nvidia-git 0.27.2.r62.g08651736-1 (Sun 15 Oct 2023 01:13:34 AM -03)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating hyprland-nvidia-git git repo...
==> Validating source files with sha256sums...
    hyprland-nvidia-git ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of hyprland-nvidia-git git repo...
Cloning into 'hyprland-nvidia-git'...
done.
==> Starting prepare()...
Submodule 'subprojects/hyprland-protocols' (https://github.com/hyprwm/hyprland-protocols) registered for path 'subprojects/hyprland-protocols'
Submodule 'subprojects/tracy' (https://github.com/wolfpld/tracy) registered for path 'subprojects/tracy'
Submodule 'subprojects/udis86' (https://github.com/canihavesomecoffee/udis86) registered for path 'subprojects/udis86'
Submodule 'wlroots' (https://gitlab.freedesktop.org/wlroots/wlroots.git) registered for path 'subprojects/wlroots'
Cloning into '/home/diego/.cache/yay/hyprland-nvidia-git/src/hyprland-nvidia-git/subprojects/hyprland-protocols'...
Cloning into '/home/diego/.cache/yay/hyprland-nvidia-git/src/hyprland-nvidia-git/subprojects/tracy'...
Cloning into '/home/diego/.cache/yay/hyprland-nvidia-git/src/hyprland-nvidia-git/subprojects/udis86'...
Cloning into '/home/diego/.cache/yay/hyprland-nvidia-git/src/hyprland-nvidia-git/subprojects/wlroots'...
Submodule path 'subprojects/hyprland-protocols': checked out '0c2ce70625cb30aef199cb388f99e19a61a6ce03'
Submodule path 'subprojects/tracy': checked out '897aec5b062664d2485f4f9a213715d2e527e0ca'
Submodule path 'subprojects/udis86': checked out '5336633af70f3917760a6d441ff02d93477b0c86'
Submodule path 'subprojects/wlroots': checked out '3406c1b17a4a7e6d4e2a7d9c1176affa72bce1bc'
make: *** No rule to make target 'fixwlr'.  Stop.
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: hyprland-nvidia-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
hyprland-nvidia-git - exit status 4
