### ISSUE TITLE
Wallbash

### ISSUE THREAD

**Issue by tinytempmouse** [prasanthrangan/hyprdots#321]
Hi apologies for the thread, when win shift + D is pressed a notification that wallbash has been enabled/disabled is shown but nothing changes. Thanks for your great work, absolutely adore this.

**Comment by T-Crypt** [comment]
when wallbash enabled it is for extracting the dominant color from the wallpaper, try changing your wallpaper on the current theme and you should see the waybar and rofi, relevant colors change to the dominant color.
