### ISSUE TITLE
theme.conf group configuration error

### ISSUE THREAD

**Issue by psilvaricardo** [prasanthrangan/hyprdots#327]
After updating all the files with `git pull` and re-running the install script with -r flag minutes ago,  I had to comment this out to have a working setup:

```
group {
    #col.border_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    #col.border_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
    #col.border_locked_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    #col.border_locked_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
}

```

**Comment by Balssh** [comment]
Are you by any chance using the hyprland-nvidia-git package? I have the same problem because that package is not up to date with hyprland

**Comment by prasanthrangan** [comment]
Hi, these variables only works on the latest version of hyprland... so please update the package!

**Comment by psilvaricardo** [comment]
@prasanthrangan @Balssh 
I can confirm, I have _hyprland-nvidia-git_ package. Is possible to switch to _hyprland_ package without messing my system ? 

![image](https://github.com/prasanthrangan/hyprdots/assets/125488497/2ffc5382-8a0a-440e-ba80-5a36bd61792d)

I currently have: 

 NVIDIA GeForce RTX 3060 Lite Hash Rate 
 ​  GPU Driver : NVIDIA 535.113.01

**Comment by GeorgeAndreiBals** [comment]
@psilvaricardo  yup, although I'm curious about how you installed the package. I have version 0.28 and if I try to update it it tells me to install 0.27 lol

**Comment by T-Crypt** [comment]
`yay -S hyprland-nvidia-git` 

this should install manually and then youll need to reboot

**Comment by prasanthrangan** [comment]
the `hyprland-nvidia-git` package seems to be fixed now... so closing this!

**Comment by dvsociety** [comment]
In my case, the error has not been resolved, no matter how much I update with yay -S hyprland-nvidia-git and restart, the error persists.

![imagen](https://github.com/prasanthrangan/hyprdots/assets/102924958/81881209-c20f-4963-b0cf-5a71b1ee94f6)
![imagen](https://github.com/prasanthrangan/hyprdots/assets/102924958/9fc85e75-97a2-44c4-bbbc-ffd2eaa81252)

**Comment by T-Crypt** [comment]
@dvsociety --

Can you share the output of the command below in here:

`hyprctl version`

also make sure you have updated your .config files via the install script

`Hyprdots/Scripts/install.sh -r`

**Comment by dvsociety** [comment]
> `Hyprdots/Scripts/install.sh -r`

![imagen](https://github.com/prasanthrangan/hyprdots/assets/102924958/03ed0b20-3900-458c-abd4-680cd0dab58c)

**Comment by T-Crypt** [comment]
Delete the whole Hyprdots repository from your home folder -- reclone the repo and then run the install.sh -r script.

Looks like your getting that error because you are on the correct hyprland version but the configs are not updated so the group bordering is incorrect.
