### ISSUE TITLE
Scaling issue 

### ISSUE THREAD

**Issue by imap3** [prasanthrangan/hyprdots#33]
When I attempt to change the hyprland monitor settings it breaks the themes and the scaling when its set to auto is way too zoomed in for me. I am using a laptop with the Intel UHD Graphics drivers.

**Comment by imap3** [comment]
I have just restored the configs and its back to the normal scaling but now the wallpaper is broken

**Comment by prasanthrangan** [comment]
> When I attempt to change the hyprland monitor settings it breaks the themes and the scaling when its set to auto is way too zoomed in for me. I am using a laptop with the Intel UHD Graphics drivers.

Hmm... whats the screen resolution? it should scale correctly when scaling is set to 1 in `hyprland.conf`.

> I have just restored the configs and its back to the normal scaling but now the wallpaper is broken

Ohh, can you try running the wallapaper script from terminal to check the error
`~/.config/swww/swwwallpaper.sh`

maybe its related to this, so you can try clearing the cache `~/.cache/swww` -
https://bbs.archlinux.org/viewtopic.php?id=285223

**Comment by imap3** [comment]
When its at scaling 1 its 1920x1080 and I ran the swwwallpaper.sh and this was the output
Error: "Failed to connect to socket: Connection refused (os error 111)"
WARNING: socket file /run/user/1000/swww.socket was not deleted when the previous daemon exited
Error: "Failed to receive answer: io error: Connection reset by peer (os error 104)"
Error: "Failed to connect to socket: Connection refused (os error 111)"

**Comment by imap3** [comment]
I tried to delete everything in the .cache/swww folder and it worked
