### ISSUE TITLE
Notification error when switching layout

### ISSUE THREAD

**Issue by nickdritan** [prasanthrangan/hyprdots#331]
Whenever I switch layout using the new script, instead of showing the new layout, the notification panel shows all layouts. The layout switch itself works, but I can not understand what am I switching to.
![231014_21h41m44s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/113607157/8e7f3215-aa3f-4785-bca4-88538d8060e2)

**Comment by prasanthrangan** [comment]
Hi, this is already fixed in 888718b -

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/828759d0-7798-49ab-80ae-6bce55446157)

**Comment by nickdritan** [comment]
It works now 😀
