### ISSUE TITLE
Low Battery Notification

### ISSUE THREAD

**Issue by thanvirdiouf** [prasanthrangan/hyprdots#341]
I'm using a laptop and I run this this hyprland fork as my main DE. I have a problem where the laptop just switches off when it reaches 1% charge. I would love it if you'd add a notification to show low battery at 5%. Thanks

P.S. Other ideas:
1. If its a laptop, installing [auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq) (aur version isn't good) along with the install script might prolong the battery life.
2. Add an update command ("`sudo hyprdots --update`" or something) to get your latest version.

**Comment by nx-smul** [comment]
follow this

https://wiki.archlinux.org/title/laptop

**Comment by kRHYME7** [comment]
Good Day @thanvirdiouf!  There is already a battery notification script to notify us if the battery is at 20 percent.  Do you want to add another layer of notifications for Low Battery and another for critical/almost drained? 

As for the auto-cpu freq, this will be decided by the maintainer, I guess auto-cpufreq will conflict such as tlp or other packages which may be used by other users here.

**Comment by kRHYME7** [comment]
Gonna bump this repo because The battery Notification script cannot detect on my Acer laptop.

Let's see what we can do to add  support on various devices

**Comment by mur1chan** [comment]
> Gonna bump this repo because The battery Notification script cannot detect on my Acer laptop.
> 
> Let's see what we can do to add support on various devices

i can confirm that too. i'm using a lenovo thinkpad and the battery notify is also not working for me

**Comment by kRHYME7** [comment]
Maybe I can pull a request. In my case, my other device has BAT1, not BAT0 
and in the script it uses BAT0
```  battery_status=$(cat /sys/class/power_supply/BAT0/status)
    battery_percentage=$(cat /sys/class/power_supply/BAT0/capacity)
```

It should be an easy fix but before that can you guys help me with this survey? Can you  provide the outputs for 
@mur1chan  @thanvirdiouf 

```
ls /sys/class/power_supply/
```
I want to make sure that majority of us uses "BAT*"
Thanks! Have a great day!

**Comment by thanvirdiouf** [comment]
This is the output:
` ACAD -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:20/ACPI0003:00/power_supply/ACAD
 BAT1 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:20/PNP0C0A:00/power_supply/BAT1`

For context, I use an Acer Nitro 5 and it never shows battery notifications

**Comment by kRHYME7** [comment]
Can you please try the PR?
