### ISSUE TITLE
Can not disable Suspend through Keybinds

### ISSUE THREAD

**Issue by Nelo390** [prasanthrangan/hyprdots#342]
I have a laptop, that unpredictably, after the lid has been closed and opened again, Bugs out swaylock so that it doesn't accept input. (May be important to note that the desktop shows up for a few seconds upon Lid Opening, before swaylock stuff shows) After messing around for a while in the .config/hypr/keybindings.config file, I realized that even if I removed the '&& systemctl suspend' from the Lid switch trigger, my system still suspended. I looked through my BIOS to make sure that sleep isn't enabled there, and I'm really at my wits end to figure out how I can stop this behavior, so that Swaylock can be initialized properly before suspension, and stop locking me out of my computer. Sorry if this is poorly phrased, it's 1AM, help or even clarifying questions are appreciated.

**Comment by GeorgeAndreiBals** [comment]
What system are you on?

**Comment by prasanthrangan** [comment]
Hi, try commenting out this line in `~/.config/hypr/keybindings.conf`

https://github.com/prasanthrangan/hyprdots/blob/f6b17c3de2adcd024604d12d57389e212584a2b2/Configs/.config/hypr/keybindings.conf#L142

**Comment by Nelo390** [comment]
@prasanthrangan I did, and the laptop still suspends when the lid is closed (also tested with a simple magnet by the sleep sensor), I believe into a light sleep, because opening the lid (removing the magnet) makes the computer quickly and automatically resume (but with no lock screen). Thank you for the suggestion!

**Comment by Nelo390** [comment]
> What system are you on?

I'm using a dell Inspiron 15 5577, if that's what you're asking.

**Comment by prasanthrangan** [comment]
is there any udev rule or any power management settings configured for your laptop?
please refer [arch power management](https://wiki.archlinux.org/title/Power_management)

**Comment by Nelo390** [comment]
Systemd logind was the culprit! I forgot I had to reload the service for changes to take effect when I was looking into it earlier. Thanks, and thanks for the awesome template to get into ricing Arch!
