### ISSUE TITLE
[Request] SwayNC support

### ISSUE THREAD

**Issue by IgLocoXD** [prasanthrangan/hyprdots#344]
I know there is a notification system, but it would be nice to have [SwayNotificationCenter](https://github.com/ErikReider/SwayNotificationCenter) (SwayNC) support in Waybar, basically works like the notifications bar in Plasma (similar) But for Sway/Hyprland.

**Comment by kRHYME7** [comment]
Hello, Have you tried running it? In my system dunst  conflicts with swaync

**Comment by prasanthrangan** [comment]
yup, dunst will be installed by default.. so you'll have to uninstall it first.

**Comment by prasanthrangan** [comment]
I'll close this as it will create conflicts with dunst notification...
you can always uninstall dunst and install swaync manually, if that's your preference!
