### ISSUE TITLE
[Bug] Waybar GPU Info doesn't show at start (unless I start Waybar on terminal) and GPUInfo doesn't show up.

### ISSUE THREAD

**Issue by IgLocoXD** [prasanthrangan/hyprdots#345]
As the bug says, when Waybar starts from rofi/startup, the GPU info doesn't show up, but even if I start Waybar from the terminal, it shows like this, also it shows up iGPU/APU, not dGPU
![this.](https://github.com/prasanthrangan/hyprdots/assets/82992516/1a74c3a5-1062-454e-bc96-7c41eb48a006)

(Btw, I have found out that the reason it doesn't show up, its because of a Sudo bug I have on hyprland, fixable with "xhost + local:" command, because GPU Info needs to open with sudo, although even if i open with rofi after the fix, gpu info doesn't work)

**Comment by prasanthrangan** [comment]
can you please try running the `~/.config/hypr/scripts/gpuinfo.sh` script from terminal and check for errors!

**Comment by T-Crypt** [comment]
gpuinfo.sh does not require sudo privileges so this seems like a bug with the localhost

**Comment by T-Crypt** [comment]
@IgLocoXD -- Care to troubleshoot this with me today if you have time? I'm the developer of the gpuinfo.sh script so I can work this out with you.

**Comment by prasanthrangan** [comment]
Hi @T-Crypt , let me know if you need anything from me...
for now I'll assign this bug to you, so that you can investigate this further when you have some spare time... hope that's ok!

**Comment by T-Crypt** [comment]
@prasanthrangan yep of course! You can assign me to any issues / bugs you want me to work anytime, doesn't just have to be my scripts / contributions! 

I'll try to start on this tomorrow but Monday at the latest

**Comment by prasanthrangan** [comment]
Hey, thank you so much for your continuous help and support!

**Comment by T-Crypt** [comment]
@IgLocoXD - Can you provide output of the waybar via terminal? 

I haven't been able to replicate this issue on my end as of yet.

**Comment by IgLocoXD** [comment]
Sorry- I wasn't using Github this days, sorry for the waiting
@T-Crypt 
`/home/vivinosmol/.config/hypr/scripts/gpuinfo.sh: línea 4: nvidia-smi: orden no encontrada
python3: can't open file '/home/vivinosmol/.config/hypr/scripts/amdgpu.py': [Errno 2] No such file or directory
/home/vivinosmol/.config/hypr/scripts/gpuinfo.sh: línea 23: [: : se esperaba una expresión entera
{"text":"N/A", "tooltip":"Primary GPU: Not found"}`

(sorry if its on spanish)

**Comment by T-Crypt** [comment]
@IgLocoXD 

Looksl ike the amdgpu.py script isn't in the directory `.config/hypr/scripts/` 

can you confirm that the script is located in that directory? What kind of GPU do you have?

**Comment by kRHYME7** [comment]
Hello, I'm not assiged to this issue, however we have too many changes since. Please reopen another issue if the latest commit did not provide any fixes. Thank you.
