### ISSUE TITLE
Screenshot Tool Doesn't work

### ISSUE THREAD

**Issue by Newer1107** [prasanthrangan/hyprdots#347]
I've updated today and found out that the screenshot tool wasn't working, manually running the script gives the output:
```
❯ ~/.config/hypr/scripts/screenshot.sh
    ./screenshot.sh <action>
    ...valid actions are...
        p : print all screens
        s : snip current screen
        m : print focused monitor
rm: cannot remove '/tmp/screenshot.png': No such file or directory
```
```
❯ ~/.config/hypr/scripts/screenshot.sh p
/home/newer/.config/hypr/scripts/screenshot.sh: line 31: grimblast: command not found
rm: cannot remove '/tmp/screenshot.png': No such file or directory
```
Thanks in Advance!

**Comment by T-Crypt** [comment]
You updated the dotfiles via `install.sh -r` only updating the configs.

You need to install grimblast

`yay -S grimblast`

**Comment by T-Crypt** [comment]
If you are worried about missing package updates to the repo -- I would suggest just running 

`./install.sh` as it does the same as the install.sh -r but checks for packages added to custom_hypr.lst

**Comment by T-Crypt** [comment]
@Newer1107 -- Did this resolve your issue? If so we can close this out

**Comment by prasanthrangan** [comment]
this #350 should fix it, please pull the latest updates and exec -- `./install.sh`
