### ISSUE TITLE
How to change scaling of an app?? 

### ISSUE THREAD

**Issue by jaypatel208** [prasanthrangan/hyprdots#349]
Hey i just installed this by script , everythinh works fine , but the thing is the apps are seems little bit zoomed can say scaled , where i can change that?? should i make changes to hyprland config file or hyprdots specific files??

**Comment by kRHYME7** [comment]
Maybe you can try to set your scaling on your hyprland.conf and also on your userprefs.conf you can also set the GDK 
scaling and setting your xwayland applications to disable scaling.

**Comment by FardanRashidi** [comment]
I changed my scaling in 
~/.config/hypr/hyprland.conf 

added 
monitor=,highres,auto,1

and comment # the other monitor

**Comment by jaypatel208** [comment]
yes , i figured it out
