### ISSUE TITLE
How do you manage to change kitty colourscheme without reopening the window?

### ISSUE THREAD

**Issue by Ashe** [prasanthrangan/hyprdots#352]
I'm not using hyprdots directly since I'm not on arch or debian but I'm adapting my dotfiles to use some of the neat features you have going.

My biggest question is how you got kitty to reload automatically; changing the configuration doesn't actually change the appearance of the window for me, I have to specifically go out of my way to restart it and I have no idea why.

Can anyone fully explain how this works? Or *should* it be changing automatically by default and I need to examine my own processes?

**Comment by T-Crypt** [comment]
If you don't mind, can you close the issue and open a discussion for this? Like to manage the open-issues as much as possible. 

But to start the conversation:

Take a look at 

`config/hypr/scripts/themeswitch.sh`

and then specifically for kitty (line 92-93)

```bash
ln -fs $ConfDir/kitty/themes/${ThemeSet}.conf $ConfDir/kitty/themes/theme.conf
killall -SIGUSR1 kitty
```

**Comment by Ashe** [comment]
Don't know why I failed to see that, I'm so sorry! 

Yes I'm doing this but unfortunately this doesn't seem to have an effect. If this is all you're doing then that means I'll examine if there's something in my config specifically doing this 😊

**Comment by T-Crypt** [comment]
Can you open the discussion and paste the contents of your themeswitching script in there? I can help modify or take a look.
