### ISSUE TITLE
Inconsistent Cursor

### ISSUE THREAD

**Issue by kRHYME7** [prasanthrangan/hyprdots#353]
Is this an expected output?  I am pertaining to the cursor  changing back to bibata ice from setting it to gruvbox when I open rofi  or a brave-browser maybe any chromium?

**Comment by T-Crypt** [comment]
@kRHYME7  

Khing, this is expected behavior for right now as the ENV variables and cursor settings are actually set  in `.config/hypr/themes/common.conf` so the GTK settings are already defined.

**Comment by kRHYME7** [comment]
@T-Crypt  thanks! I really thought I was missing something! I just did not give a damn about cursors until this day haha. I will try to find scripts relating to cursors. Is having a universal/global cursor beneficial to this repo that we can switch back and forth?
