### ISSUE TITLE
I was wondering if there any way to see video thumbnails in file manager??

### ISSUE THREAD

**Issue by jaypatel208** [prasanthrangan/hyprdots#354]
So as i am using it  for few days i noticed in pictures i can view the thumbnail but when it comes to video i can't view what this video is and it's thumbnail , i added vlc media player but still thumbnail is not showed from that side , can i expect thumbnail updates in next version??

**Comment by kRHYME7** [comment]
Hi! The setting for thumbnails are controlled by the dolphin package which is used by this repo. Maybe we can find a way to integrate it depending on our maintainer. 

Would you mind  if you  try to find a way to enable it on dolphin file manager and get back to this comment.

**Comment by jaypatel208** [comment]
Sure i will check it out later , let's see what we can do

**Comment by kRHYME7** [comment]
Thanks !
