### ISSUE TITLE
Changing wallpaper

### ISSUE THREAD

**Issue by jaypatel208** [prasanthrangan/hyprdots#355]
i can change wallpaper from theme from toolbar , but how i can i change it to my custome wallpaper?? like i want my downloaded pictures as a wallpaper

**Comment by kRHYME7** [comment]
hello you can use this 
``` ~/.config/hypr/scripts/swwwallpaper.sh -s ~/path/to/your/wallpaper

**Comment by jaypatel208** [comment]
can we do something like in 1 folder there is bunch of wallpapers?? and from just taskbar i can change one by one , like this dots gave by default.

**Comment by kRHYME7** [comment]
Regarding this it is quite possible but it would be slow because we should cache  each Image on that folder. Once cached  it will be faster but would you mind sharing your envisioned workflow by this...

**Comment by jaypatel208** [comment]
i think it will be more simple , like currently we are changing wallpaper from waybar right so from where this is changing wallpaper in same folder what if user put wanted wallpaper?? and form perfomance they will put needed wallpaper only

**Comment by T-Crypt** [comment]
If you want to download wallpapers and have them rotated in the folder you can just pick one of the themes or place them in multiple themes in `.config/swww/(theme)` directory and then you can rotate wallpapers with `Super + Right Arrow or Left Arrow` 

Additionally if you want the theme to correspond with your downloaded wallpaper, just enable wallbash by using bind `Super + Shift + D` and this will set the theme color based on the dominant color of the wallpaper.
