### ISSUE TITLE
Bluetooth not working properly

### ISSUE THREAD

**Issue by jaypatel208** [prasanthrangan/hyprdots#356]
So from the theme bluetooth is working pretty good then expected , but it's having issues when i want to connect it to bluetooth keyboard , have to search and pair again and again , we can improve that??

And also most of user will connect multiple bluetooth devices like headphone+keyboard so connectivity issue is also there , not like it's not working , it just now working properly , i think that can be improved.

**Comment by kRHYME7** [comment]
Hi! I don't have this issue on my end. Can you elaborate more with the issue?  Does your Bluetooth resets and  forget your devices?

**Comment by jaypatel208** [comment]
no it doesn't connect sometimes,like it randomly gives error like br-connection-profile-unavailable, le-connection-abort-by-local and all that , but after trying again and again connection get success.

so if it can be fixed it's great for ux

**Comment by kRHYME7** [comment]
Can you send some screenshots of this output or something.? 

And what is the output for blueman-manager.. Ill try to run  and see if I have this problems on my devices

**Comment by kRHYME7** [comment]
Also, have you tried some fixes here? :

https://wiki.archlinux.org/title/Blueman

https://wiki.archlinux.org/title/bluetooth

**Comment by T-Crypt** [comment]
@jaypatel208 

Have you tried trusting the device with `bluetoothctl`?
