### ISSUE TITLE
No such field error 

### ISSUE THREAD

**Issue by piush-terminalwitchcraft** [prasanthrangan/hyprdots#359]
All the fields named as 
![image](https://github.com/prasanthrangan/hyprdots/assets/76522725/e7c46a08-e253-46d9-abc5-6b188c479cb3)
throws error stating that 
![image](https://github.com/prasanthrangan/hyprdots/assets/76522725/28568170-b78f-42a7-8ff7-e4e56d23aaf0)
Someone helpppppp!!!!!!!!

**Comment by kRHYME7** [comment]
hello please update your repository  and ~/install.sh -h from there.

**Comment by T-Crypt** [comment]
@piush-terminalwitchcraft 

Have you updated to the most recent dotfiles version by going to the repository on your system and running

```
git pull 
./install.sh
```

then you need to update hpyrland to v0.30.0

depending on what hyprland version you are using 

`hyprland-git` for non-nvidia users

`hyprland-nvidia-git` for nvidia users

So install manually 

`yay -S hyprland-nvidia-git` or `yay -S hyprland-git` based on the above 

and then reboot.

**Comment by piush-terminalwitchcraft** [comment]
It worked thanks !

**Comment by Tthenix** [comment]
where you make the git pull and ./install.sh -h?

**Comment by kRHYME7** [comment]
Hi!   if you clone this repo directly after opening the terminal it should be on your  ``` ~/Hyprdots ```
so  locate the directory Hyprdots

``` 
cd ~/.Hyprdots
git pull
./install.sh
```

Warning this will overwrite your configs. 
The backup for your config prior to updating  will be at ``` ~/.config/cfg* ``` * sufix for the latest date and time  for the back up. Cheers !

**Comment by Tthenix** [comment]
Hii! for some reason .hyperdots dosent exist on /home/user(tthenix)
![imagen](https://github.com/prasanthrangan/hyprdots/assets/80957556/2dcb963f-f996-4c28-9d8b-4e8ef6100021)

**Comment by Tthenix** [comment]
Nothing, sorry i am a little new on Arch
![imagen](https://github.com/prasanthrangan/hyprdots/assets/80957556/74483dc3-4da0-4207-b555-4b45362094f4)

**Comment by kRHYME7** [comment]
If you can find the Hyprdots Directory It would be better.

But You can Still follow the installation guide 
like this but will restore your config by adding -r

```
cd
git clone https://github.com/prasanthrangan/hyprdots ~/Hyprdots
cd ~/Hyprdots/Scripts
./install.sh -r

```

With this you will clone AGAIN the Repository to  you Home Directory.

For updating the config Soon you can Follow the instructions given here.

**Comment by T-Crypt** [comment]
No cloning just places the repository locally on your system, you aren't going to lose your files, apps, anything like that. 

You could just open Dolphin (Super + E)

and look in your Home directory for the hyprdots folder and then click inside, right click "Open Terminal here"

**Comment by Tthenix** [comment]
It worked thanks T-Crypt and kRHYME7!
