### ISSUE TITLE
command not fond fzf

### ISSUE THREAD

**Issue by Gedankenn** [prasanthrangan/hyprdots#364]
My fish is not being abble to autocomplete, giving this error:
__zic_fzf_bindings:4: command not found: fzf   

Anyone know how to solve it?

**Comment by katsuja** [comment]
Try installing fzf:
pacman -S fzf

**Comment by Balssh** [comment]
This, I suppose, is due to commit 0876a7aa7c231983496204c3de73688ebb7c4c1d which changes several zsh plugins. I'd first run `python zsh_plugin_installer.py -f plugin_list.lst` from the /Scripts/ directory and then install fzf (on Arch you can do that with `sudo pacman -S fzf`)

**Comment by prasanthrangan** [comment]
> This, I suppose, is due to commit [0876a7a](https://github.com/prasanthrangan/hyprdots/commit/0876a7aa7c231983496204c3de73688ebb7c4c1d) which changes several zsh plugins. I'd first run `python zsh_plugin_installer.py -f plugin_list.lst` from the /Scripts/ directory and then install fzf (on Arch you can do that with `sudo pacman -S fzf`)

yup, you just have to manually install fzf... I'll fix the plugin installer

**Comment by prasanthrangan** [comment]
Hi, this should be fixed in 6a8edd2, I'll close this but please reopen if required!
