### ISSUE TITLE
Waylock Style 2

### ISSUE THREAD

**Issue by Nelo390** [prasanthrangan/hyprdots#366]
A few very minor issues exist with the current CSS of the Second waylock screen, Mostly the widths of the other Boxes moving as you hover over them. This is because the text is not 'pushing' against the borders of other boxes after it does its expanding animation, so the rest of the buttons resize until they reach the text again, from either the expanded button or the button above/below it.
A fix for this would be to set an equal Width between the Top and Bottom boxes, for both Left and right, in the CSS, but that seems to make the css file crash, at least when I tried it.
 Setting "width" in the layout2 file didn't do anything as far as I could tell. (tried 0.3 and 1)
Very, Very low priority, and I'd fix it myself if I had found a productive path to go down. 
I am on a 1920x1080 display at 1.5 scale.

**Comment by prasanthrangan** [comment]
Hi, can you please share a screenshot for this? the scaling should be working for 1920x1080 display at 1.5.

**Comment by Nelo390** [comment]
https://github.com/prasanthrangan/hyprdots/assets/60764808/faed42d3-f64c-4492-9dad-4e0d4da47adf

**Comment by Balssh** [comment]
Hmm weird that it happens to you with those settings. I have the exact same ones and it looks better:
![image](https://github.com/prasanthrangan/hyprdots/assets/82440615/5fe4c380-076f-4805-b304-979bd555d4dd)
![image](https://github.com/prasanthrangan/hyprdots/assets/82440615/12b4a4ae-3cf3-4bfc-ac32-7aa8218b819b)

Maybe try a clean reinstall of the dotfiles?

**Comment by Nelo390** [comment]
Interesting... Line 24 was replaced by some repetitive junk, I don't know how it got there. 
`hypr_scale=$(hyprctl -j monitors | jq '.[] | select (.focused == true)' | jq '.scale' | cut -d '.' -f 1)
hypr_scale=$(( hypr_scale * 100 ))`
All the rest of the file seems to be the same, and replacing it with the original config file lines works. ¯\_(ツ)_/¯, thanks.

**Comment by prasanthrangan** [comment]
cool, thanks... so I'll close this issue!
