### ISSUE TITLE
Screenshot script is not working.

### ISSUE THREAD

**Issue by Exoutia** [prasanthrangan/hyprdots#367]
I tried finding the issue related to my problem  didn't see any so if it is already solved issue please forgive me.

So I just updated the hyprdots and loving it except when i am trying to take screenshot it is not working. I tried to see the keybinding and even changed the binding but it is not working. Then i tried to run the script manually and it is giving this error,

```sh
❯ ~/.config/hypr/scripts/screenshot.sh s
/home/bibek/.config/hypr/scripts/screenshot.sh: line 33: grimblast: command not found
rm: cannot remove '/tmp/screenshot.png': No such file or directory
```
(As I am not able to take screenshot I have copy pasted the error.)
So I opened the file in nvim and also opened the  screenshot script which was stored in my cfg folder before the lastest update and it is working fine and dandy without any problem.
![screen shot taken using old script ](https://github.com/prasanthrangan/hyprdots/assets/94464106/4908d0df-781f-4b2e-88f1-60bd68624896)

I am new to all of this and don't know what should i do right now, should i just change the path or do i need to install something.

**Comment by TheyCallMeSecond** [comment]
you should install "grimblast" package

**Comment by T3l3sc0p3** [comment]
Run `yay -S grimblast-git`

**Comment by kRHYME7** [comment]
#347 There you go. You can follow the instructions above or you can also fetch and pull the latest commits on this repo and rerun/restore the installation.
