### ISSUE TITLE
dunst theme break after changing wallpaper and theme

### ISSUE THREAD

**Issue by mahaveergurjar** [prasanthrangan/hyprdots#369]
https://github.com/prasanthrangan/hyprdots/assets/57872034/5d2ea20c-975e-4c96-b6e7-e53989cf4189

**Comment by kRHYME7** [comment]
Hello, I have a recent PR #371  but I do not know if this is relevant to this Issue. 

Can you please try to run ```pgrep -x dunst ``` after you change themes or wallpaper,  if it returns something? 

If it returns something this PR #371  may not be related to this issue. Thanks!

**Comment by mahaveergurjar** [comment]
![231022_10h31m07s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/2e1cf2fc-d154-4041-9a7b-54129fd0a5ff)

![231022_10h32m50s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/b9c8e6a5-a9c7-4d5b-84a9-63081a6ca3d1)

**Comment by mahaveergurjar** [comment]
ok i try your pr

**Comment by mahaveergurjar** [comment]
now working dunst theme properly thanks

**Comment by prasanthrangan** [comment]
Hi, looks like this is fixed now, please do confirm and close!

**Comment by mahaveergurjar** [comment]
fixed
