### ISSUE TITLE
Waybar won't start

### ISSUE THREAD

**Issue by jpx40** [prasanthrangan/hyprdots#373]
I have an issue with the newest waybar Version, i think it's waybar-git. It won't start (show up), does anyone have similar issues?

**Comment by kRHYME7** [comment]
Hi! No errors for waybar here using non-git
 I think this repo uses the non-git version of waybar. Have you tried installing the non-git version? Or is there any particular reason that you need to use waybar-git?  If so let's see what we can do.

**Comment by kRHYME7** [comment]
@jpx40  Hello is this a problem until now? I will close this as this issues looks stale. Please reopen if you still have this issue.
