### ISSUE TITLE
Cannot open google chrome or microsoft edge

### ISSUE THREAD

**Issue by DMNghia** [prasanthrangan/hyprdots#377]
Hi, I really like your configuration, but it seems have some error was happened, I cannot open google chrome or microsoft edge, I don't know why. When i open it, it load and after that it auto close. Please help

**Comment by kRHYME7** [comment]
Hi!! Have you tried appending ``` --ozone-platform=x11 ```  example ``` brave  --ozone-platform=x11 ```  in terminal ? 

I think this issue is not really related directly to this repo, but let's see what we can do

**Comment by DMNghia** [comment]
Ok, it worked, thanks for your help!
