### ISSUE TITLE
User preferences to survive updates (possible enhancement)

### ISSUE THREAD

**Issue by opticblu** [prasanthrangan/hyprdots#38]
Perhaps there's a better way to do this but I submitted a proposed change to hyprland.conf so that people can easily-ish keep their user preferences-- probably should go in another folder like ~/hypruserpref.conf and just be sourced from a directory that remains static during updates

Just a thought

Thanks so much for the amazing config and the hard work, I am really really enjoying this setup!

**Comment by prasanthrangan** [comment]
Hey, thank you for your suggestion!
Sounds like a good idea, but not sure what kind of user preferences that could be used as static, so that it does not change if you want to update.

**Comment by opticblu** [comment]
Additional keybindings, etc.

Perhaps it's better to break out keybinds, window rules, monitors.conf, etc. into different source = files so that when an update does change, for instance, hyprland.conf, the monitors/workspaces are left intact. Obviously environment variables and exec= is pretty static.

At least locally, for me (and I have a triple-head 4k display setup) I source:
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf
source = ~/userprefs.conf

Everything is brilliant and this is not a complaint; I just see that other people are taking notice of this config (434 stars, congrats!) and as it continues to gain popularity, additional modularity could make updates easier

**Comment by prasanthrangan** [comment]
Thank you so much!

Hmm, If we split the files (for example monitors, keybindings) and keep the original hyprland.conf with the defaults, will hyprland override the defaults if user creates and source his version of monitors.conf, keybindings.conf etc... I'll have to test this out.

The restore script is currently set to backup (move) the entire `~/.config/hypr` directory and copy the version from the git clone directory, based on the control file entry -
`${HOME}/.config|hypr|hyprland`

So to make this more granular, I will update this to -
`${HOME}/.config/hypr|hyprland.conf scripts themes|hyprland`

This make the restore script only move the objects `hyprland.conf`, `scripts` and `themes` and ignore the rest of the files in your `~/.config/hypr` directory that you have configured (such as `~/.config/hypr/workspaces.conf`).

**Comment by opticblu** [comment]
I'm not sure, I don't know if hyprland will prioritize source file preferences, I haven't explicitly tested it. At least for displays (monitors), I've forgotten to comment out the default preferred, auto/auto and it sill sources my monitors.conf with scaling etc being correct

As far as the restore script, at least for me, that would make things easier, thank you

Maybe for new users you could just add a comment #source=~/youradditionalpref.conf, or they can just figure it out lol

One example I've seen of a hyprland config broken out into (a lot) of different source files is this: https://github.com/end-4/dots-hyprland/tree/main/.config/hypr
^^ absolutely wild config

Thank you, this is awesome :-)

**Comment by prasanthrangan** [comment]
> I'm not sure, I don't know if hyprland will prioritize source file preferences, I haven't explicitly tested it. At least for displays (monitors), I've forgotten to comment out the default preferred, auto/auto and it sill sources my monitors.conf with scaling etc being correct

Yup, seems like it does override the defaults when you source your config at the end.

> As far as the restore script, at least for me, that would make things easier, thank you
> Maybe for new users you could just add a comment #source=~/youradditionalpref.conf, or they can just figure it out lol

I've updated the restore script control to ignore `userprefs.conf` and `monitors.conf` so that users can set it once and source it in `hyprland.conf` !


> One example I've seen of a hyprland config broken out into (a lot) of different source files is this: https://github.com/end-4/dots-hyprland/tree/main/.config/hypr
> ^^ absolutely wild config

woww, this looks wild indeed... makes me wanna try configuring eww and include it in my setup :)

**Comment by opticblu** [comment]
Thanks!
