### ISSUE TITLE
Black Screen After Login

### ISSUE THREAD

**Issue by Zelamus** [prasanthrangan/hyprdots#386]
Hi,im using the normal arch (i installed from archinstall) and there is a bug or issue with my hyprland,i login with normal username and password but hyprland just gives me black screen,is there are any other people that facing the same issue?Which logs i should send to you guys?

**Comment by T-Crypt** [comment]
@Zelamus -- 

Did you use sudo to run the install script? as in `sudo ./install.sh`

**Comment by Zelamus** [comment]
you cant run sudo with install.sh ,yay fails and other things fails as they shouldnt run with root.But i had other fails installing it,when i install it normally rofi's theme_parser test fails and installer doesnt continue,i tried everythin like minimal or with desktop installation always i get is theme_parser test error,So i installed it with ./install.sh -drs

**Comment by T-Crypt** [comment]
@Zelamus -- Im aware you can't run with sudo -- I've been one of the main contributors to these dotfiles. I was making sure you didn't run as sudo as it would install the dotfiles in the root user .config directory. 

Can you upload the error on install? Also, is this on bare metal or a VM?

Arch Linux install settings:

![image](https://github.com/prasanthrangan/hyprdots/assets/132922589/c8a1c0b8-f1b2-46e4-9aaf-aef001a5b37b)

You should just be running ./install.sh for first install.

**Comment by Zelamus** [comment]
I know,Its not vm and i tried with minimal too,it fails with minimal too,but i didnt install multilib.i think here is a problem with my gpu tho(4050 laptop),which logs i should send?

**Comment by T-Crypt** [comment]
If its failing on install -- you should send the error message from the install.sh or provide a line out of the error! (Depending on the size as you'll have to type it out on here with a working system)

**Comment by Zelamus** [comment]
Aint no way im using that shit im coming back to windows or kali👎

**Comment by Zelamus** [comment]
Aint no way im using that shit im coming back to windows or kali👎
