### ISSUE TITLE
[Nvidia] GPU Power limit query needs to be updated

### ISSUE THREAD

**Issue by Muhammad-Abubakr** [prasanthrangan/hyprdots#388]
Hi folks, first of all thank you for providing us with a wonderful and easy to configure hyprland setup. I have been enjoying the dots and trying to contribute to the project as much as I can and here is one more improvement that can be made in the dots.
![231027_16h17m04s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/74457014/30d8aafd-acdd-4659-9502-c7860c76d16a)

The query for `Power Limit` is a bit off in gpuinfo.sh, instead of `nvidia-smi --query-gpu=temperature.gpu,utilization.gpu,clocks.current.graphics,clocks.max.graphics,power.draw,power.limit --format=csv,noheader,nounits)` it should be `nvidia-smi --query-gpu=temperature.gpu,utilization.gpu,clocks.current.graphics,clocks.max.graphics,power.draw,power.max_limit --format=csv,noheader,nounits)` as `power.limit` is not a query parameter and should be `power.max_limit` according to the context. ![Here](https://codeyarns.com/tech/2019-04-26-nvidia-smi-cheatsheet.html#gsc.tab=0) is a cheatsheat for the gpu info query.

Keep up the awesome work! Thanks

**Comment by T-Crypt** [comment]
#390 

You can close this -- I've resolved this issue.
