### ISSUE TITLE
set defaults number workspace to multiple monitors

### ISSUE THREAD

**Issue by Miguerfi** [prasanthrangan/hyprdots#391]
I have 2 monitors and the workspace only works with win + 8 for the second monitor, the rest is set to the first. Is there any way to share this? from 1 to 4 in the first, from 5 to 0 in the second.

**Comment by kRHYME7** [comment]
Hi! @Miguerfi  Have you tried  Checking the hyprland wiki, I would love to send you the link but I do have  internet problems at the moment . On the Wiki there is an option to set a specific monitor to a default  workspace number. Just look in the Monitors section. I will give an in-depth explanation after  my net will be stable. Cheers!

Also, I wrote a messy script to change  the monitor config base on the monitor plug in, but I don't have the time to Pull a request yet.

**Comment by prasanthrangan** [comment]
Hi, here is the link - https://wiki.hyprland.org/Configuring/Workspace-Rules/
