### ISSUE TITLE
Failed to build hyprland-git 

### ISSUE THREAD

**Issue by bouyagas** [prasanthrangan/hyprdots#394]
![Image 10-27-23 at 10 06 PM](https://github.com/prasanthrangan/hyprdots/assets/6065727/2b25c2da-bbf3-4bd6-a96d-2003d9830d86)

**Comment by bouyagas** [comment]
During the installation, everything seemed to go well, but it failed to build hyprland-git. I believe it has to do with my laptop, I'm Macbook Pro M1 arm64.

**Comment by kRHYME7** [comment]
👋 Hi! Can you please try to Separately install Hyprland-git  on the terminal?

**Comment by prasanthrangan** [comment]
Hi @bouyagas , I'm not sure if hyprland supports apple M1.
You could try checking with the hyprland dev team...

**Comment by katsuja** [comment]
Have you already installed the opengl drivers for asahi? 
sudo pacman -S linux-asahi-edge mesa-asahi-edge
Otherwise you have to install hyprland-legacyrenderer without opengl support.
The first alternative seems the best to me 😂
Check it out: here: https://www.reddit.com/r/AsahiLinux/comments/142k63b/opengl_31_on_asahi_linux/

**Comment by bouyagas** [comment]
<img width="334" alt="9856DC22-B8FB-4EB9-90CA-5C4F8DD7C27E" src="https://github.com/prasanthrangan/hyprdots/assets/6065727/9c87a644-66ca-42b2-9237-8fed161c242f">

I believe the M1 machine uses a different mirror list for its package installs [Arch Linux ARM](https://archlinuxarm.org/packages). 

I found this

![46879650-95BB-4BF8-B165-B0B660438E91](https://github.com/prasanthrangan/hyprdots/assets/6065727/b9754fa1-6444-4050-9485-5091297a2018)

![C70B23DE-E6EB-4510-B145-A72C0E942AC3](https://github.com/prasanthrangan/hyprdots/assets/6065727/94fa5555-9fbc-421e-8585-f182b965d5a7)

I Had to change the local file Hyprdots/Scripts/custom_hypr.lst from hyprland-git to hyprland and sddm-git to sddm. 
  
![9C8E0996-65C2-4C9E-AD7C-89CA75FF0645_1_201_a](https://github.com/prasanthrangan/hyprdots/assets/6065727/aaea331d-f34a-40ad-b825-20833601edfb)
 
its works!!!

**Comment by katsuja** [comment]
> <img alt="9856DC22-B8FB-4EB9-90CA-5C4F8DD7C27E" width="334" src="https://user-images.githubusercontent.com/6065727/278906138-9c87a644-66ca-42b2-9237-8fed161c242f.png">
> 
> I believe the M1 machine uses a different mirror list for its package installs [Arch Linux ARM](https://archlinuxarm.org/packages).
> 
> I found this
> 
> ![46879650-95BB-4BF8-B165-B0B660438E91](https://user-images.githubusercontent.com/6065727/278906846-b9754fa1-6444-4050-9485-5091297a2018.png)
> 
> ![C70B23DE-E6EB-4510-B145-A72C0E942AC3](https://user-images.githubusercontent.com/6065727/278906856-94fa5555-9fbc-421e-8585-f182b965d5a7.png)
> 
> I Had to change the local file Hyprdots/Scripts/custom_hypr.lst from hyprland-git to hyprland and sddm-git to sddm.
> 
> ![9C8E0996-65C2-4C9E-AD7C-89CA75FF0645_1_201_a](https://user-images.githubusercontent.com/6065727/278907507-aaea331d-f34a-40ad-b825-20833601edfb.jpeg)
> 
> its works!!!

But with pacman you will never find an aur package.
You need to install and use, for example, paru or yay:
paru -S hyprland-git
yay -S hyprland-git
The "non-git" version is a few versions back. This rice was giving me problems because the features implemented in the git version were missing.
But if everything works better for you 😄

**Comment by prasanthrangan** [comment]
Hi, thank you guys... looks like this is resolved, so I'll close this!
reopen if required...
