### ISSUE TITLE
Issue with kdewallet on boot

### ISSUE THREAD

**Issue by cosmic-helios** [prasanthrangan/hyprdots#395]
### **kdewallet** popping up after launching  brave on the first boot.
- I recently clean installed everything from scratch, this issue started ever since.
- Its goes on line 'Application brave has requested to access kdewallet'
**Any Solutions?**

**Comment by kRHYME7** [comment]
Hello Can You check if you have Gnome-keyring?
Please install Gnome-keyring to manage these passwords.

https://archlinux.org/packages/?name=gnome-keyring

**Comment by prasanthrangan** [comment]
Hi, this is expected as brave detects kwallet (installed as dependency)
if you'd like to skipthis  kdewallet popup then use `--password-store=basic` as a launch option -

```
brave-browser --password-store=basic
```
I've brave installed as flatpak, so ive updated exec command in the shortcut as
```
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=brave --file-forwarding com.brave.Browser --password-store=basic
```

for reference -
![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/43347572-c2fa-47fe-b8e3-96cff76c7c56)

**Comment by kRHYME7** [comment]
Oy! Thanks @prasanthrangan  This is the solution I needed for months now. Just don't have time to search for removing password input prompt on brave.

**Comment by cosmic-helios** [comment]
> Hello Can You check if you have Gnome-keyring? Please install Gnome-keyring to manage these passwords.
> 
> https://archlinux.org/packages/?name=gnome-keyring
> 
> ```
> paru -S gnome-keyring
> ```

I Just Installed it

**Comment by cosmic-helios** [comment]
> brave-browser --password-store=basic

So, I've installed brave using **yay**. Do i have launch brave using this command everytime?

**Comment by cosmic-helios** [comment]
Everything works fine now, Thanks for the help
