### ISSUE TITLE
Network reset/disappear

### ISSUE THREAD

**Issue by tinkerbaj** [prasanthrangan/hyprdots#396]
I have strange issue where every few random minutes network (probably) reset I get sometimes error in browser your IP is changed. Its only with this dot files. But I really dont know how to find what is issue. Error in chromium is "ERR_NETWORK_CHANGED"

**Comment by TuxTweaker** [comment]
This seems like you have network services colliding with each other. What services are you using for managing your network? Have you checked?

**Comment by tinkerbaj** [comment]
I dont do anything just install arch minimal and run this script whatever it come with it this is what I'm using :) I dont know how to check

**Comment by TuxTweaker** [comment]
right. can you please paste here the output of `ls -R /etc/systemd/system | grep ".service"`

**Comment by tinkerbaj** [comment]
```
dbus-org.bluez.service -> /usr/lib/systemd/system/bluetooth.service
dbus-org.freedesktop.network1.service -> /usr/lib/systemd/system/systemd-networkd.service
dbus-org.freedesktop.resolve1.service -> /usr/lib/systemd/system/systemd-resolved.service
dbus-org.freedesktop.timesync1.service -> /usr/lib/systemd/system/systemd-timesyncd.service
display-manager.service -> /usr/lib/systemd/system/sddm.service
ollama.service
bluetooth.service -> /usr/lib/systemd/system/bluetooth.service
ollama.service -> /etc/systemd/system/ollama.service
getty@tty1.service -> /usr/lib/systemd/system/getty@.service
systemd-networkd.service -> /usr/lib/systemd/system/systemd-networkd.service
systemd-networkd-wait-online.service -> /usr/lib/systemd/system/systemd-networkd-wait-online.service
systemd-network-generator.service -> /usr/lib/systemd/system/systemd-network-generator.service
systemd-resolved.service -> /usr/lib/systemd/system/systemd-resolved.service
systemd-timesyncd.service -> /usr/lib/systemd/system/systemd-timesyncd.service
```

**Comment by TuxTweaker** [comment]
right. So next can you run `systemctl enable NetworkManager.service` and `systemctl start NetworkManager.service` and paste the output of `systemctl status NetworkManager.service`

**Comment by tinkerbaj** [comment]
```
NetworkManager.service - Network Manager
     Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; enabled; preset: disabled)
     Active: active (running) since Sat 2023-10-28 18:33:09 CEST; 20h ago
       Docs: man:NetworkManager(8)
   Main PID: 547 (NetworkManager)
      Tasks: 4 (limit: 18973)
     Memory: 13.1M
        CPU: 4.353s
     CGroup: /system.slice/NetworkManager.service
             └─547 /usr/bin/NetworkManager --no-daemon

Oct 28 18:33:09 archlinux NetworkManager[547]: <info>  [1698510789.3949] device (eno1): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'assume')
Oct 28 18:33:09 archlinux NetworkManager[547]: <info>  [1698510789.3951] device (eno1): state change: secondaries -> activated (reason 'none', sys-iface-state: 'assume')
Oct 28 18:33:09 archlinux NetworkManager[547]: <info>  [1698510789.3953] manager: NetworkManager state is now CONNECTED_SITE
Oct 28 18:33:09 archlinux NetworkManager[547]: <info>  [1698510789.3954] device (eno1): Activation: successful, device activated.
Oct 28 18:33:09 archlinux NetworkManager[547]: <info>  [1698510789.3957] manager: startup complete
Oct 28 18:33:10 archlinux NetworkManager[547]: <info>  [1698510790.6735] manager: NetworkManager state is now CONNECTED_GLOBAL
Oct 28 18:33:34 archlinux NetworkManager[547]: <info>  [1698510814.4814] agent-manager: agent[f805c91f1d159820,:1.31/org.freedesktop.nm-applet/1000]: agent registered
Oct 29 00:33:08 archlinux NetworkManager[547]: <info>  [1698532388.6855] dhcp4 (eno1): state changed new lease, address=192.168.31.19
Oct 29 05:04:26 archlinux NetworkManager[547]: <info>  [1698552266.6812] dhcp4 (eno1): state changed new lease, address=192.168.31.19
Oct 29 10:19:40 archlinux NetworkManager[547]: <info>  [1698571180.6814] dhcp4 (eno1): state changed new lease, address=192.168.31.19
```

**Comment by TuxTweaker** [comment]
okay, now can you connect to any wifi network using `nmtui` in terminal or `nm-applet` in waybar and see if the issue is resolved or not

**Comment by tinkerbaj** [comment]
I dont use wifi I'm using cable but its still happening

**Comment by TuxTweaker** [comment]
> I dont use wifi I'm using cable but its still happening

oh I didn't know you were doing it for the wired. Can you follow [this](https://bbs.archlinux.org/viewtopic.php?id=260219)

**Comment by tinkerbaj** [comment]
I disabled the Network Manager service and left systemd-networkd.service    I hope it will be solved

**Comment by TuxTweaker** [comment]
> I disabled the Network Manager service and left systemd-networkd.service I hope it will be solved

your system seems to be running all the required services for a wired network of systemd. It should have been fine but just in case can you refer to [this](https://wiki.archlinux.org/title/systemd-networkd) arch-wiki article, here it will tell you to setup dhcp configuration for your wired interface. That should solve your problem.

**Comment by tinkerbaj** [comment]
I disable this dbus-org.freedesktop.network1.service and NetworkManager now I dont have issues

**Comment by TuxTweaker** [comment]
> I disable this dbus-org.freedesktop.network1.service and NetworkManager now I dont have issues 
> 

That's good to hear, also please don't forget to close this issue.

**Comment by tinkerbaj** [comment]
Thank you for help I appreciate it

**Comment by l0f3n** [comment]
Im having a similar issue but using WiFi and disabling NetworkManager (and using systemd-networkd instead) seems to have helped. May I ask why it is enabled in the first place?
