### ISSUE TITLE
Discord crash when sharing screen pressed

### ISSUE THREAD

**Issue by jaypatel208** [prasanthrangan/hyprdots#397]
idk anyoune noticed it or not but when i try to share screen in discord the discord app crash and exit happens , while sharing screen in google meet completely works fine.

**Comment by TuxTweaker** [comment]
I tested it on my setup and strangely I got a different issue than yours. I was able to share the screen and discord didn't exit but it didn't capture my whole screen rather it only captured applications. It just showed a black screen with cursor if I wanted to project the entire screen. However, it works fine with obs while capturing the entire display.

![231029_00h17m19s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/149172798/cf5d4d7c-fc4e-4dd5-a7f9-d7fa73161be0)
![231029_00h17m39s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/149172798/f8c737c6-905f-440f-99c1-bc58585fdc00)

**Comment by jaypatel208** [comment]
Bro when i do screen share it directly crash my app , like exit happens can't even see discord in way bar , i will upload video if possible

**Comment by akashgagda** [comment]
Use discord on browser

**Comment by jaypatel208** [comment]
Yes i know that way , idk how @TuxTweaker managed to do it in discord app.

**Comment by TuxTweaker** [comment]
> Yes i know that way , idk how @TuxTweaker managed to do it in discord app.

Idk man, I just didn't face the problem that you are having. Can you start discord from terminal and check the logs when it crashes. That may help

**Comment by jaypatel208** [comment]
blackbox: 2023-10-30T15:27:56.178Z 7 ✅ webContents.did-finish-load web2
blackbox: 2023-10-30T15:27:56.289Z 8 window.close win1
blackbox: 2023-10-30T15:27:56.378Z 9 webContents.destroyed web1
blackbox: 2023-10-30T15:27:56.499Z 10 window.closed win1
mainScreen.UpdaterEvents: UPDATER_HISTORY_QUERY_AND_TRUNCATE
Setting Krisp model: full_NC
[1030/205904.291557:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
[4698:1030/205905.523818:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
[4698:1030/205905.524585:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
[1]    4494 segmentation fault (core dumped)  discord

**Comment by prasanthrangan** [comment]
Hi, could you please check if xdg-desktop-portal-hyprland service is running?
Please follow [this ](https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580) to troubleshoot.

**Comment by jaypatel208** [comment]
yes , i sholved it by just doing reinstall : `sudo pacman -S xdg-desktop-portal-hyprland`
