### ISSUE TITLE
Question about script !

### ISSUE THREAD

**Issue by MostafaMohamed2002** [prasanthrangan/hyprdots#4]
if i had archcraft installed , will the script makes any conflict ?

**Comment by prasanthrangan** [comment]
I'm not sure what packages archcraft use, so I cant say for sure... which DE does it use?

**Comment by MostafaMohamed2002** [comment]
if DE means Desktop Environment so it's using BSPWM and OpenBox , i can choose anyone of them at login screen .

**Comment by MostafaMohamed2002** [comment]
after trying to use script and download packages i face this error

`error: pahole: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
:: File /var/cache/pacman/pkg/pahole-1:1.24+r29+g02d67c5-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
`

**Comment by MostafaMohamed2002** [comment]
@prasanthrangan

**Comment by prasanthrangan** [comment]
oh looks like its trying to install an out of date package -
https://archlinux.org/packages/extra/x86_64/pahole/

let me have a look

**Comment by MostafaMohamed2002** [comment]
**thanks for help , i already installed the system and it looks very good**
