### ISSUE TITLE
[FEATURE REQUEST] Wallpapers ; Custom Directory

### ISSUE THREAD

**Issue by itstoxicqt** [prasanthrangan/hyprdots#400]
requesting a feature to possibly add a personal wallpaper folder to the wallpaper selection screen would be a nice touch.

**Comment by prasanthrangan** [comment]
Hi, you can already do that...
```
~/.config/hypr/scripts/swwwallpaper.sh -s path/to/wallpaper
```

**Comment by itstoxicqt** [comment]
I don't want to loop through I have a few hundred images in my wallpaper folder. Would be nice to have them also appear in the rofi wallpaper selection

**Comment by jasonKoogler** [comment]
This is a pain point for me right now too.  I like my own wallpapers , but if you add them to each of the theme folders and then run create_cache.sh your looking at gigs of extra space not including all the backups from running install.sh when there's an update.  I don't know bash well enough at this point to solve this, but I'm sure there's a solution.

**Comment by prasanthrangan** [comment]
oh okies... I'll update it now!

**Comment by prasanthrangan** [comment]
this is done, here you go -
```
./create_cache.sh -c "/path/to/wallpaper"
```

https://github.com/prasanthrangan/hyprdots/assets/106020512/a59ea5be-92b5-4d96-90f7-fd3c766d5073

**Comment by kRHYME7** [comment]
@prasanthrangan This is very nice. I have a question by the way does this overwrite the wallpapers for the theme?

**Comment by itstoxicqt** [comment]
> this is done in [f445d5d](https://github.com/prasanthrangan/hyprdots/commit/f445d5ddbaa1d418b4e6eb86b2ad7a4d6fe6a040) , here you go -
> 
> ```
> ./create_cache.sh -c "/path/to/wallpaper"
> ```
> 
>  wall_720p.mp4

thank you <3 i love the dot files

**Comment by Akie3301** [comment]
> this is done in [f445d5d](https://github.com/prasanthrangan/hyprdots/commit/f445d5ddbaa1d418b4e6eb86b2ad7a4d6fe6a040) , here you go -
> 
> ```
> ./create_cache.sh -c "/path/to/wallpaper"
> ```
> 
> wall_720p.mp4

What's the app that you use in this video?

**Comment by kRHYME7** [comment]
@itstoxicqt  @jasonKoogler  Closing this now as it is pretty doable.  Please feel free to reopen an issue.  Added this to ``` good first issue  ``` for future reference 

Conclusion to the thread: 

+ To set/change a custom folder for your wallpaper. 
https://github.com/prasanthrangan/hyprdots/issues/400#issuecomment-1784216656
``` ./create_cache.sh -c "/path/to/wallpaper" ```

or 
``` Hyrpdots wallpaper path  /path/to/wallpaper* ``` 


For now, as per writing this, each directory is bound to the theme it is set.  Therefore changing wallpaper  directory to another theme needs a re-cached. Can be solved by this #873

**Comment by glaceeee** [comment]
Hey, the way in which you change your wallpaper seems to have changed. I dont have a scripts folder containing swwwallpaper.sh anymore. Though i can find swwwallpaper.sh in ~/HyDE/Configs/.local/share/bin it doesnt seem to work anymore. I also didnt find any info on this on the wiki's as they all seem to be outdated as of now. How can I change my wallpaper to a custom one now?

**Comment by kRHYME7** [comment]
Add theme specific wallpapers in ~/.config/hyde/themes/Theme-Name/wallpapers 

If you want to make the directory global declare it in ~/.config/hyde/hyde.conf. Check the file in this repo

**Comment by glaceeee** [comment]
thank you :)
