### ISSUE TITLE
Some Scripts aren't executable after restore.

### ISSUE THREAD

**Issue by kRHYME7** [prasanthrangan/hyprdots#401]
Hi! I will just put this as an issue. 
Some of the scripts are not executable after I restore or from a fresh installation of this dots. Can I have some guidance regarding this? 

I ``` chmod ```  every after the restoration of the config.  I do not know if I'm the only one had this problem. Also, could someone help me where on the ./Scripts  handles the permission. Thank You !!!!

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/39321d85-3dfa-4cba-ad5e-0b188e4bdd42)

**Comment by prasanthrangan** [comment]
Hey, sorry i don't understand...
the screenshot shows 2 completely different directory -
`~/.config/hypr/scripts` and `~/Scripts`
In the first one, it already has `x` permissions, and the latter wont be affected when you run install script.

**Comment by kRHYME7** [comment]
Sorry for the confusion,  I forgot to highlight the problem. 
 On the ``` ~/.config/hypr/scripts ```    the batterynotify.sh don't have x permission after ./install.sh -r . And Regarding  that ~/Scripts/ I modified the ```./restore_cfg.lst ```  to fetch this folder on my device. I would Like to ask in which part of the scripts handles this permissions? Thank you.
 
 
 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/19e82245-99c8-455c-9b42-28b2f19fefb9)
My usual issue is this particular ``` ./batterynotify.sh ```. 


In addition, I don't  get this permission issue on my main laptop, I usually get this on my second laptop.

**Comment by prasanthrangan** [comment]
> which part of the scripts handles this permissions? Thank you.

file permissions are maintained by git itself, so you'll have to change the permission for `batterynotify.sh` and commit the script.

**Comment by kRHYME7** [comment]
Thanks
