### ISSUE TITLE
BUG: low battery notification not showing up

### ISSUE THREAD

**Issue by devCKVargas** [prasanthrangan/hyprdots#403]
We were watching a movie yesterday & I didn't see any low battery notification, so I was paranoid and kept going out of Fullscreen to check the battery. This was prior to finding out that we have a `batterynotify.sh` script 😄 but still, I've tested it again today, and still no notification.

**Comment by kRHYME7** [comment]
hello Is your ``` batterynotify.sh ```
 Executable? can Your run it on Hyprland?

**Comment by kRHYME7** [comment]
hello Is your ``` batterynotify.sh ```
 Executable? can Your run it on Hyprland?

**Comment by devCKVargas** [comment]
> hello Is your `batterynotify.sh` Executable? can Your run it on Terminal?

It isn't! So that's why! I assumed it was already set for other users as well.
it's `644` when I do `stat -c %a`
I should set it to be `755` like the others?

**Comment by devCKVargas** [comment]
I saw the PR.
Closing this once it gets merged. Thanks!

**Comment by kRHYME7** [comment]
Hi! Can you lend me some help  I issued a PR #408. Is it possible for you to try it and see if it works for you? Hihi Thank You!
