### ISSUE TITLE
Input method constantly flashing

### ISSUE THREAD

**Issue by zhkag** [prasanthrangan/hyprdots#405]
What should I do when the input method is constantly flashing, indicating that I am constantly competing for the focus?

**Comment by prasanthrangan** [comment]
Hi, sorry I don't understand the issue... could you please share screenshot showcasing the issue or provide more details?

**Comment by zhkag** [comment]
I use Sogou input method, which automatically enables input when there is a need for input. Originally, it is tiled and will always switch between input method and no input method. For example, my window only has one browser. When the browser has Chinese character input, it will pop up Sogou input method, and the default layout will pop up at the mouse position. At this time, the focus of the mouse cursor is on the input method, Then he may determine that the input method interface does not require an input method, and then turn off the input method

**Comment by zhkag** [comment]
When I change to floating, this situation also occurs, and I cannot avoid sometimes moving to the input method cursor, which is in English. When it is in Chinese, the abnormality is even more severe because there is an additional selection box and there is also squeezing of the text

**Comment by zhkag** [comment]
I am very sorry that I cannot provide you with a screenshot because I have uninstalled Sogou input method and used a Pinyin input method that comes with fcitx5. It is normal. Although I have found a way to avoid it, I still hope you can solve this problem

**Comment by prasanthrangan** [comment]
Hi, could you try setting your keybord layout preference in hyprland.conf and switch the input/layout with `Super` + `k`
please refer [this](https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/) to configure

**Comment by theslycat** [comment]
It's the issue with sogou input method itself, not hyprland. So I recommend that you switch your input method to Sunpinyin or IME from Google(works for me)

**Comment by kRHYME7** [comment]
@zhkag  Hello, I will close this as answered based on @theslycat  https://github.com/prasanthrangan/hyprdots/issues/405#issuecomment-1890446617. Feel free to reopen this/another issue. 🍥
