### ISSUE TITLE
How to suspend in your dotfiles? 

### ISSUE THREAD

**Issue by Akie3301** [prasanthrangan/hyprdots#407]
i dunno

**Comment by kRHYME7** [comment]
I hope this is what you meant. 
There were 2 options for that I guess, all of this  executes ``` systemctl suspend ``` 
1.
**using key binds**
the keybind executes  ``` ~/.config/hypr/scripts/logoutlaunch.sh 1 ```  ([Keybinds](https://github.com/prasanthrangan/hyprdots#Keybindings) )

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/9e859944-f35d-499d-a1e9-13ea8b68071f)


2.
Using ``` swayidle ``` this is located in your  ```  ~/.config/hypr/userprefs.conf  ```  You can Enable that there and set it as you please.   

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/23edf852-c26e-4586-9e80-e0aa38568537)

**Comment by Akie3301** [comment]
> I hope this is what you meant. There were 2 options for that I guess, all of this executes `systemctl suspend` 1. **using key binds** the keybind executes `~/.config/hypr/scripts/logoutlaunch.sh 1` ([Keybinds](https://github.com/prasanthrangan/hyprdots#Keybindings) )
> 
> ![image](https://user-images.githubusercontent.com/53417443/279341667-9e859944-f35d-499d-a1e9-13ea8b68071f.png)
> 
> 
> Using `swayidle` this is located in your ` ~/.config/hypr/userprefs.conf ` You can Enable that there and set it as you please.
> 
> ![image](https://user-images.githubusercontent.com/53417443/279342025-23edf852-c26e-4586-9e80-e0aa38568537.png)
thanks, how to turn off screen when lock screen like gnome?

**Comment by T-Crypt** [comment]
@Akie3301 -- Are you able to close out this issue now that @kRHYME7 resolved this?
