### ISSUE TITLE
invisible text

### ISSUE THREAD

**Issue by jenil1122** [prasanthrangan/hyprdots#409]
text is not visible in notification for some apps like spotify 
![231031_17h55m15s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/78353041/7bbc09f7-599a-4368-bdfe-13197b6e64eb)

**Comment by prasanthrangan** [comment]
Hi, yes I'm aware of this... this happens as the colors adapt to the current wallpaper... so wallpapers with low contrast will cause this.
I'll improve the colors extracted and use between text and background...
