### ISSUE TITLE
Do we have  spicetify and spotify?

### ISSUE THREAD

**Issue by kRHYME7** [prasanthrangan/hyprdots#410]
This looks awesome! 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/386914c7-d032-428b-be20-13daf9e07ea6)

Is this already on the repo?

**Comment by prasanthrangan** [comment]
hey, thank you..
Its there in `custom_apps.lst`... but you can also always install `spicetify` and `spotify` manually...

**Comment by kRHYME7** [comment]
Okies, thanks so this customization is not on the repo right?  I thought I was missing something haha.
