### ISSUE TITLE
Faulty font on vscode.

### ISSUE THREAD

**Issue by ghost** [prasanthrangan/hyprdots#415]
Some applications also have this error such as mailspring, jdownloader, some applications on flathub.
![image](https://github.com/prasanthrangan/hyprdots/assets/137863476/81d2352f-bd58-41b2-944f-f461e1bf1237)
![image](https://github.com/prasanthrangan/hyprdots/assets/137863476/e6d258fa-b025-440d-8eba-f4289c8297f9)

**Comment by prasanthrangan** [comment]
Hi, please try setting this in `userpref.conf` -

```
env = GDK_SCALE,1

xwayland {
force_zero_scaling = true
}
```

**Comment by Akie3301** [comment]
> Hi, please try setting this in `userpref.conf` -
> 
> ```
> env = GDK_SCALE,1
> 
> xwayland {
> force_zero_scaling = true
> }
> ```

Is this fine if my userpref.conf have nothing?

**Comment by prasanthrangan** [comment]
> Is this fine if my userpref.conf have nothing?

userpref.conf wont be set by default, so it will be initially empty so that you can add your own preferred settings in this file!

**Comment by kRHYME7** [comment]
Closing this as we're ghosted.
