### ISSUE TITLE
Cant change font of VS Code

### ISSUE THREAD

**Issue by jasonKoogler** [prasanthrangan/hyprdots#418]
title pretty much says it all.  I have ttf-maple installed and fira-code as well.  Font ligatures wont work, nor will changing the font.  also changing the kitty font doesn't appear to work either.  ran "fc-cache -fv" to no avail as well

**Comment by T-Crypt** [comment]
Font for Vscode is set in the settings.json

~/.config/Code/User/settings.json

you need to change the config below to change the font 

`~/.config/hypr/themes/common.conf`

and line 1 in the kitty.conf 

`~/.config/kitty/kitty.conf`

**Comment by T-Crypt** [comment]
@jasonKoogler -- If this resolved your issue are you able close out this issue?
