### ISSUE TITLE
split screen

### ISSUE THREAD

**Issue by cupenk** [prasanthrangan/hyprdots#419]
hello, I'm using Thorium browser and I do split screen when I swipe it's lag, but when I do it in Firefox it's fine.

**Comment by cupenk** [comment]
> hello, I'm using Thorium browser and I do split screen when I swipe it's lag, but when I do it in Firefox it's fine.

**Comment by prasanthrangan** [comment]
Hi, is Thorium browser native to wayland?

**Comment by T-Crypt** [comment]
@cupenk 

Again I believe this is an issue with Thorium, so it needs to be raised on the package maintainers page. This repository is just responsible for the look and feel of Arch. It does not maintain or handle package errors. 

[Thorium](https://github.com/Alex313031/thorium)

**Comment by Sitolam** [comment]
@cupenk 

I think switching Thorium to wayland can fix your issue:

- Go to chrome://flags
- Search "Prefered Ozone platform"
- Set it to "Wayland"
- Restart

I'm also using Thorium and by setting it to wayland it fixed a lot of issues for me. Hope this helps.

**Comment by cupenk** [comment]
> @cupenk
> 
> I think switching Thorium to wayland can fix your issue:
> 
> * Go to chrome://flags
> * Search "Prefered Ozone platform"
> * Set it to "Wayland"
> * Restart
> 
> I'm also using Thorium and by setting it to wayland it fixed a lot of issues for me. Hope this helps.

 it works thank

**Comment by cupenk** [comment]
> @cupenk
> 
> I think switching Thorium to wayland can fix your issue:
> 
> * Go to chrome://flags
> * Search "Prefered Ozone platform"
> * Set it to "Wayland"
> * Restart
> 
> I'm also using Thorium and by setting it to wayland it fixed a lot of issues for me. Hope this helps.
 do you know how to remove the close bar in thorium?
