### ISSUE TITLE
Battery Notify Spam

### ISSUE THREAD

**Issue by oxzh** [prasanthrangan/hyprdots#424]
Every 20-30s the battery_notify.sh ping's once time saying "battery is full, please disconnect the charger!" the laptop is always docked. was supposed to be 300s idk why this is happen, i installed this rice today, and i see who has an PR merged by @kRHYME7 i guess you can help with this!

i disabled the script in hyprland.conf for dont ping anymore
Using a laptop

**Comment by T-Crypt** [comment]
@oxzh -- I disabled mine cause I keep my laptop docked.

**Comment by oxzh** [comment]
me too

**Comment by kRHYME7** [comment]
Yups my latest commit fixes this

**Comment by kRHYME7** [comment]
But I needed inputs for the user huhu. #420  

What do you think about making all defaults null like if no flags means null thus not notifying it?  Or adding docking mode which enables all notifications. It would be very helpful if we could discuss in PR #420. Thank You. I owe you guys a lot

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/804ca7a2-f7ca-402b-9788-802531430c7d)

**Comment by oxzh** [comment]
sorry but i cant help, i new into linux and shell scripts so

**Comment by kRHYME7** [comment]
It's Fine! We all are learning things here. How about sharing your preferred use cases for this battery notification utility. OS that I can make defaults for the General?

**Comment by oxzh** [comment]
would be good, if 20% battery, warns for connect power supply, 50% too for, like, warning, and 5% suspends the notebook, for not losing any works or smth

**Comment by kRHYME7** [comment]
Thanks how about disabling the Battery full notification by default?

**Comment by kRHYME7** [comment]
or Adding docking mode to disable just the battery full notif but still has this 
> 
would be good, if 20% battery, warns for connect power supply, 50% too for, like, warning, and 5% suspends the notebook, for not losing any works or smth

**Comment by oxzh** [comment]
have a way to notify ONCE time, when it reaches 100%? i think is better than being notified every x seconds

**Comment by oxzh** [comment]
and a possible solution

**Comment by kRHYME7** [comment]
Oh nice that would be easier

**Comment by kRHYME7** [comment]
Hi Are you willing to test this?

**Comment by kRHYME7** [comment]
Defaults:

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/7cfe1bc9-c0d3-4f43-812b-b030cc521487)

**Comment by oxzh** [comment]
> Hi Are you willing to test this?

yes, if still need

**Comment by kRHYME7** [comment]
Can you try to pull the latest commit on my PR #420 ?

**Comment by oxzh** [comment]
@kRHYME7 its working normaly for me, im going to close after you response, i see you last pr, has been merge so, i guess is normal now

**Comment by kRHYME7** [comment]
Thanks for your help
