### ISSUE TITLE
Could you add a better Duntsk Notification or Deead Desktop Notification centre 

### ISSUE THREAD

**Issue by MISTERNEGATIVE21** [prasanthrangan/hyprdots#425]
Well improvements could be made in notifications and custom desktop notification and settings panel

**Comment by T-Crypt** [comment]
@MISTERNEGATIVE21 

Notifications are good, custom desktop notifications can be set on a user basis, and what settings panel are you referring to?

If you want customization just download the ArchLinux tweak tool

**Comment by prasanthrangan** [comment]
Hi, sorry i don't understand... are you missing any system notification?
