### ISSUE TITLE
I cant keep my .config

### ISSUE THREAD

**Issue by BlokCSS** [prasanthrangan/hyprdots#426]
first of all, this is an excuse to congratulate you for the great work you do for the community!

As the title says. i want to keep the changes im doing to the dotfiles  to fit my preferences and still have the chance to get the new commits that you are providing to the repo. **I read the closed issues about this and already tried few ways** but i keep losing all  the changes i do on my local .config and it becomes like fresh installation from your script. Maybe im doing something wrong or im skippin a few steps in between. The other way, maybe im dumb lmao.

hope i have made myself clear : D

**Comment by BlokCSS** [comment]
It seems like some of the files are backed. For example userpref.conf
BUT the keybindings nor hyprland.conf arent backed :c

i tried git pull and ./install.sh -r
and also tried ./restore_cfg.sh

SO maybe im doing something wrong or something that im not doing. Can you do kindly some script that updates but not overwrite what i did?

**Comment by kRHYME7** [comment]
Check this out on your ~/.config/

  ```    ls ~/.config/cfg*   ```

**Comment by olsen-jo** [comment]
i still kind of have the same problem, but i've found gtk fonts, input rules, keybindings and window rules can be set in the static userprefs config file. if you can get most of your changes into that file... i believe it is parsed last and will remain through updates. that's my workaround though likely not the correct way to do it, but maybe it can help you.

**Comment by kRHYME7** [comment]
The proper way is to utilize your userprefs.conf that is why userprefs.conf is static (also monitor.conf). So it is advisable to out all your user-specific configs including keybinding etc.  If the user still wants to modify the conf other than userpref and monitor during ./restore.sh it will be overwritten.  So I think you are doing it good. 

If you still needed to modify those configs that aren't static the backups of your config are located at ~/.config/cfg* with date and time as sufix then change the non static config to  the back up.

**Comment by kRHYME7** [comment]
userpref.conf and monitor.conf isn't backed up up at all though so maybe you should back it up manually.

**Comment by olsen-jo** [comment]
@kRHYME7 lol me calling it my workaround when it's what your supposed to do is a little embarrassing... anyway. i don't really understand how it works for configs where it is not explicitly sourcing userprefs at the end, but i still have a lot to learn.

**Comment by kRHYME7** [comment]
We are all learning here and the owner of the dotfiles is very organized in his scripts so you can learn this in no time.  
Also can we move this issue to discussions? 

BTW, the userprefs is sourced at the bottom of ~/.config/hypr/hyprland.conf

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/0cdfe6db-6088-4965-87ae-fcfc702ef84b)

**Comment by Exoutia** [comment]
what about the changes made in kitty.conf and my different wallpapers that i have stored how should i do with them so that they don't get override.

**Comment by kRHYME7** [comment]
for Kitty, you can remove the line that indicates kitty in ``` ~/Hyprdots/Scripts/restore_cfg.lst ```
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/3c6f28ce-878d-40f2-81fd-4292a6e6e4c8)


Then As for the wallpapers, I do have workarounds but this is not explicitly explained. 
But your saved wallpaper should be backed up at $HOME/.config/cfg*(Latest date and time ). 

If you want to save time as creating a cache takes time I suggest
* pulling the latest changes inside the ~/Hyprdots first ``` git pull ```
* then copy ```  ~/.config/swww/.cache  ``` to the ```  ~/Hyprdots/Configs/.config/swww/ ```  
* then run your ./install.sh of choice 
the cached images will be imported into your directory and the caching time will be quicker.
* then remove ```   ~/Hyprdots/Configs/.config/swww/.cache ``` to avoid future issues

A better workaround is Making your own fork for the dots repo and adding your own configuration then just merging if updates are available

**Comment by kRHYME7** [comment]
Also I added a PR I added a line that copies the cache back to the ~/.config/swww/  Can You give it a try?  this is about the faster caching of images

**Comment by prasanthrangan** [comment]
Hi, you'll have to configure everything in `userpref.conf` so that they are preserved...
for overriding default keybindings, use [unbind](https://wiki.hyprland.org/Configuring/Binds/#unbind) and then bind it to your preference!
