### ISSUE TITLE
Dolphin Crypto

### ISSUE THREAD

**Issue by aloisiomarques** [prasanthrangan/hyprdots#427]
Hello, I'm having a problem logging into an encrypted partition. the authentication window does not load when I click on the unit. Would any specific configuration be necessary to mount the unit?

my configs:

fstab:
LABEL=meuarray	     /media/backup     ext4          defaults,noauto,noatime,x-system.automount,x-systemd.requires=systemd-cryptsetup@raid1.service,x-systemd.idle-timeout=3min		0 2

crypttab:
raid1  /dev/md127p1       /etc/chave.key      luks,noauto 

In nautilus it works normally, but in dolphin I have this problem of not allowing it to authenticate.

**Comment by T-Crypt** [comment]
You should try using zulucrypt

`yay -S zulucrypt'

You use ZuluMount (GUI) to mount the image, then you have an option to open in Dolphin from ZuluMount - no CLI needed

I don't think there is any support for the encrypted drive authentication in Dolphin.
