### ISSUE TITLE
1920x1080 resolution issues (scale issues for single screens / laptops)

### ISSUE THREAD

**Issue by ejsadiarin** [prasanthrangan/hyprdots#43]
First of all, thank you @prasanthrangan  for your hard work, generosity, and for this **_exquisite_** rice, **its truly the best I found.** Upon installing, i found some resolution/scale issues, which are just mostly UI issues (all functionality works!), so I decided to share the UI problems I found here in this issue. 

**I still have not yet resolved the issues, so I'm looking for some help here**

**NOTE: that this is for single screens / laptops that are 1920x1080 res, I don't know much about other resolutions (check other issue for 4K monitors, it seems like they have at least resolved most of the issues for 4K display**

# Monitor (single screens / for laptops)
Summary:
- I want the preferred 1920x1080@60 setting in my own hyprland config (~/.config/hypr/userprefs.conf):
`monitor = eDP-1, 1920x1080@60, 0x0, 1` 
- but some launchers especially noticeable ones (wlogout, waybar, rofi, theme-switch) have problems

- mostly about scaling issues
- all about UI problems (all the functionality works as intended)
- specific problems on `monitor = eDP-1, 1920x1080@60, 0x0, 1`: 
  - some apps are very "far away" (tolerable, but for waybar it makes it unreadable)
  - waybar small size making it unreadable,
  - theme-switch UI (super shift t),
  - wlogout is not on center, overlapping text

## Details:
- most bearable config for 1920x1080 resolution (single screen):
`monitor = eDP-1, 1920x1080@60, 0x0, 1.2` (not preferred, since it causes blur issues on apps that can only be solved by setting the scale to 1)
- preferred setting should be: `monitor = eDP-1, 1920x1080@60, 0x0, 1`

### scale of `1.2` results to:
- theme-switch (super shift t) pictures is not showing (its just a blank slate, but the functionality works)
- waybar is small (but more readable than when scale is `1`)
- wlogout is not on the center like when scale is `1`
  - overlapping text and icons (same as when scale is `1`)
- flatpak apps like discord is "blurry"

### scale of `1` (classic 1920x1080 display, preferred) results to:
- rofi text is not fully showing (not a big deal but a minor problem)
![230716_15h01m56s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/106421149/00733d87-c2c5-41dc-843d-703fa41749a5)

- waybar is very small (little unreadable)
![230716_14h57m48s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/106421149/536170b8-bd3b-4392-b175-713d8d2a9b99)

- wlogout is not on the center
  - overlapping text and icons
  - doesn't look great for smaller resolution displays
![230716_14h47m18s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/106421149/76b68cf6-c356-4cbc-8b68-90acabf77bf9)

- theme-swtich is showing but the text is cut out (shows "...")
![230716_15h00m39s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/106421149/7228158d-7c44-4eb0-96f0-ae95d7c4e0f3)

- flatpak apps like discord works as intended (not blurry, highres)

**Comment by prasanthrangan** [comment]
Hi, thank you so much for your support and detailed inputs!

> * most bearable config for 1920x1080 resolution (single screen):
>   `monitor = eDP-1, 1920x1080@60, 0x0, 1.2` (not preferred, since it causes blur issues on apps that can only be solved by setting the scale to 1)
> 
> * preferred setting should be: `monitor = eDP-1, 1920x1080@60, 0x0, 1`

I agree, its not recommended to use fractional scaling, so I will focus on adjusting the configs for native scaling (1)  or (2) for HiDPI.

I'm using a 2560x1080 (21:9 ultrawide) monitor hence the UI breaks for 1920x1080 (16:9) res. That's my bad so I'm trying to make this as dynamic as possible.


> * rofi text is not fully showing (not a big deal but a minor problem)

Here the rofi launcher config breaks due to the 16:9 aspect ratio, the height and width is set as 55% and 45% of your screen res. As I'm trying to make this config dynamic, this will be fixed.


> * waybar is very small (little unreadable)

The waybar is already configured to be dynamic, so it should retain it shape based on your screen res. It detects the font size you have set in your hypr theme file, its 10 by default, so please try increasing the font size here till its readable -

```shell
❯ cd ~/.config/hypr/themes
❯ grep " font-name " *
Catppuccin-Latte.conf:exec = gsettings set org.gnome.desktop.interface font-name 'Cantarell 10'
Material-Sakura.conf:exec = gsettings set org.gnome.desktop.interface font-name 'Cantarell 10'
Decay-Green.conf:exec = gsettings set org.gnome.desktop.interface font-name 'Cantarell 10'
Material-Sakura.conf:exec = gsettings set org.gnome.desktop.interface font-name 'Cantarell 10'
Rose-Pine.conf:exec = gsettings set org.gnome.desktop.interface font-name 'Cantarell 10'
Tokyo-Night.conf:exec = gsettings set org.gnome.desktop.interface font-name 'Cantarell 10'
```

> wlogout is not on the center
>     * overlapping text and icons
>     * doesn't look great for smaller resolution displays

Yup, the wlogout config is still work in progress, I'll be reworking these as I'm trying to generate it based on current theme. In the meantime you can manually adjust the wlogout config to fit your screen res.


> * theme-swtich is showing but the text is cut out (shows "...")

Its same as the issue with rofi launcher, the UI is not scaling correctly for (16:9) aspect ratio. So this will also be fixed once i make these rofi configs dynamic.

**Comment by ejsadiarin** [comment]
Got it, take your time! Thank you for the detailed reply also, we really do appreciate your work!

**Comment by michalkoterba** [comment]
> The waybar is already configured to be dynamic, so it should retain it shape based on your screen res. It detects the font size you have set in your hypr theme file, its 10 by default, so please try increasing the font size here till its readable -

It does the job. The downside is it changes font size in Firefox:

`exec = gsettings set org.gnome.desktop.interface font-name 'Cantarell 18'`
![image](https://github.com/prasanthrangan/hyprdots/assets/59779070/eb4c7e82-5445-4fda-a533-03954f8ffd5d)

Apart from that, with font size set to: 12 my bar is compact but readable. Firefox tab font is too big, need to work on that.

BTW, grate job on that script. Thanks a lot!!!

**Comment by prasanthrangan** [comment]
Hey @michalkoterba , thank you... I didn't realize that the gtk font size and waybar font size looks different even when its same.
I'll try setting waybar font size to scale based on its height instead of using system font size.

**Comment by rohit-burman** [comment]
@ejsadiarin I have also got some resolution issues in laptop
 fixed it by changing:
```
monitor=,preferred,auto,auto
``` 
to 

```
monitor=,highres,auto,1
``` 
in hyprland.config file 
it actually uses the higher possible resolution for the available display

**Comment by jonfive** [comment]
I'm also having an issue where it's tiny. 

I was messing around with the waybar configs and may have found a way around it, but i'm not familiar enough with how all the scripts interact.

If you go to .config/waybar/style.css - line 6 you can set a font size. it works and everything looks fine. Doesn't mess with gtk/firefox etc.

Once you set it, logout, log back in to see the changes. **BUT** if you change the background, go light/dark mode it reverts back to 12px

Does anyone know *what* exactly controls/reverts this?

**Comment by kRHYME7** [comment]
> Does anyone know what exactly controls/reverts this?
Checkput
```  ~/.config/hypr/scripts/wbarconfgen.sh ``` 

for waybar scaling size at 

``` ~/.config/waybar/config.ctl ```

**Comment by AdrianFerrer1** [comment]
Any updates on this???? I'm having the issue where if I put 1.2 its decently scaled but the vscode text is pixelated, if I don't want it to be pixelated then I have to type 1 and it just makes everything insanely tiny so idk what to do tbh

**Comment by kRHYME7** [comment]
If vscode is the issue I think you can zoom it.

Also have you tried tinkering this 

``` 
xwayland {
    force_zero_scaling = false
    }
   ```
```

also this 
```
env = GDK_SCALE,1
```


Try to change values and see What might work for you

**Comment by AdrianFerrer1** [comment]
> If vscode is the issue I think you can zoom it.
> 
> Also have you tried tinkering this
> 
> ```
> xwayland {
>     force_zero_scaling = false
>     }
> ```
> 
> also this
> 
> ```
> env = GDK_SCALE,1
> ```
> 
> Try to change values and see What might work for you

Thx, this solved the issue!

**Comment by kRHYME7** [comment]
Nice! Also Just figured out that I needed to reboot to when we need to change ``` env = GDK_SCALE,1 ```

**Comment by kRHYME7** [comment]
@ejsadiarin  I think all the issues are fixed now, I will close this for now, please reopen in case you still find this issues on your system. Thanks !

**Comment by ejsadiarin** [comment]
> @ejsadiarin  I think all the issues are fixed now, I will close this for now, please reopen in case you still find this issues on your system. Thanks !

Yes!! Thank you!
