### ISSUE TITLE
How can i make Waybar transparent?

### ISSUE THREAD

**Issue by DouglasMartinEX** [prasanthrangan/hyprdots#431]
Your theme was the most complete, organized and tasteful of all the ones I tested! I can make the changes I want intuitively and without wasting time - which is funny, given that I don't even have 1 week of Arch Linux and not even 2 weeks of Linux in general. Congratulations!

I would like to know if there is an option where I can make the waybar background transparent (other than the icons).
One more thing: Is it possible for now changing the waybar to left side?

Congratulations again and good work!

**Comment by T-Crypt** [comment]
@DouglasMartinEX 

1. Left side waybar will take some work to make it compatible with the wbarconfgen.sh script that creates the waybar config.jsonc -- It is a task in the Project Tabs [Vertical Config](https://github.com/users/prasanthrangan/projects/1?pane=issue&itemId=37812200)

2. waybar background is set to the image created during the themeswitch and wallswitch script. So I'm sure its possible to make it more transparent, modify the opacity of the bar. Ill look into this.

**Comment by wutfor** [comment]
To make waybar background transparent, all you have to do is:
1. Go to ~/.config/hypr/themes/
2. Open the current theme .conf file in a text editor
3. Comment out / Delete the line `blurs = waybar` 
Here's my example:
![image](https://github.com/prasanthrangan/hyprdots/assets/145139846/bb00e2bc-a9f2-415b-b1b3-b712a2be388f)

**Comment by T-Crypt** [comment]
@wutfor 

I figured he was talking about the style here:

https://github.com/prasanthrangan/hyprdots/blob/17fe3f775983218b0d22d0a6783eff56438cdcc5/Configs/.config/waybar/style.css#L119-L124

**Comment by wutfor** [comment]
Ah, well probably still worth a shot.

**Comment by DouglasMartinEX** [comment]
> @wutfor
> 
> Achei que ele estava falando sobre o estilo aqui:
> 
> https://github.com/prasanthrangan/hyprdots/blob/17fe3f775983218b0d22d0a6783eff56438cdcc5/Configs/.config/waybar/style.css#L119-L124

Yep! Messing around i could make it transparent! Tnx for the help!!
