### ISSUE TITLE
update

### ISSUE THREAD

**Issue by cupenk** [prasanthrangan/hyprdots#433]
why my laptop is hot after updated.

**Comment by T-Crypt** [comment]
@cupenk -- Can you close the waybar issue previous to this one?

Your laptop is hot due to the waybar update.

**Comment by cupenk** [comment]
> @cupenk -- Can you close the waybar issue previous to this one?
> 
> Your laptop is hot due to the waybar update.
> 
> It adds reaping of child command process to the main reap queue
> 
> ```
> reap_mtx.lock();
>   reap.push_back(child_pid);
>   reap_mtx.unlock();
> ```
> 
> When its already reaped before close:
> 
> ```
>  exit_code = WEXITSTATUS(util::command::close(fp_, pid_)); 
> ```
> 
> https://github.com/Alexays/Waybar/blob/c6a9b63189c1617606ba726f3fd7af5a80df97d6/include/util/command.hpp#L44-L67
> 
> This is an issue with [Waybar](https://github.com/Alexays/Waybar)
sorry,i dont understand.

**Comment by T-Crypt** [comment]
Just update your waybar.

Yay -Syu waybar

**Comment by cupenk** [comment]
> Just update your waybar.
> 
> Yay -Syu waybar

alright.

**Comment by cupenk** [comment]
> Just update your waybar.
> 
> Yay -Syu waybar

still didn't work

**Comment by T-Crypt** [comment]
Can you run:

`Yay -Qs waybar`

and post the output here?

**Comment by cupenk** [comment]
> Can you run:
> 
> `Yay -Qs waybar`
> 
> and post the output here?

![image](https://github.com/prasanthrangan/hyprdots/assets/29496587/5374937a-b6ce-4dcf-87c4-8af634809f75)

**Comment by T-Crypt** [comment]
@cupenk -- Sounds good! We can close this issue cause technically this was a waybar issue and not the repository!

**Comment by cupenk** [comment]
> @cupenk -- Sounds good! We can close this issue cause technically this was a waybar issue and not the repository!

alright thanks
