### ISSUE TITLE
Clock running behind

### ISSUE THREAD

**Issue by Sitolam** [prasanthrangan/hyprdots#434]
My clock is running behind 1 hour. When I use `tzselect` to select my timezone it also shows the wrong time. I'm dual booting though so I entered this command to fix the time issue `timedatectl set-local-rtc 1` but that also didn't fix the issue.

**Comment by T-Crypt** [comment]
Try:

```
timedatectl set-local-rtc 1 --adjust-system-clock

timedatectl 
```

**Comment by Sitolam** [comment]
That worked. Thank you.

**Comment by Sitolam** [comment]
This works if I run it but after a while it just resets to the wrong time again.

**Comment by T-Crypt** [comment]
@Sitolam if you are dual booting and switching between windows and Arch, you most likely need to edit your windows time settings as well. 

## Windows 

`REG ADD "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation" /v RealTimeIsUniversal /t REG_DWORD /d 1 /f`

## Linux

`timedatectl set-local-rtc 1 --adjust-system-clock`

**Comment by Sitolam** [comment]
> @Sitolam if you are dual booting and switching between windows and Arch, you most likely need to edit your windows time settings as well.
> 
> ## Windows
> `REG ADD "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation" /v RealTimeIsUniversal /t REG_DWORD /d 1 /f`
> 
> ## Linux
> `timedatectl set-local-rtc 1 --adjust-system-clock`

That could maybe help, but every time the screen gets locked the clock runs behind again.
