### ISSUE TITLE
wallbash

### ISSUE THREAD

**Issue by TheyCallMeSecond** [prasanthrangan/hyprdots#435]
Does wallbash work for you guys recently?

**Comment by kRHYME7** [comment]
Hi Yes, it works on my end. 

Try to run ``` ~/.config/hypr/scripts/togglewallbash.switch.sh ``` on the terminal maybe we can get something.

**Comment by TheyCallMeSecond** [comment]
Do you mean wallbashtoggle.sh? It works but it doesn't extract the color... colors don't change when changing wallpaper or theme...

**Comment by TheyCallMeSecond** [comment]
i think it broke after this commit : 
https://github.com/prasanthrangan/hyprdots/commit/b64e2819f59987562388473a7e7962cf2cf40589

**Comment by kRHYME7** [comment]
Pulled this and it works on my end.

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/b372e104-08e1-48e7-88e5-0af3ce600ea9)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/509e8b6f-938a-41ca-b225-9cf7a59942c0)
![Uploading image.png…]()

**Comment by TheyCallMeSecond** [comment]
its strange...looks like it extracts the wallpapert's color in ~/.config/swww/.cache/themefolder but doesnt work on waybar dunst borders spotify for me

**Comment by kRHYME7** [comment]
Have you tried  pulling the latest repo ( like no custom changes from your end?)
Can you try to run the scripts on the terminal maybe we could get something.

**Comment by TheyCallMeSecond** [comment]
any specific scripts do you mean? my "~/.config/hypr/scripts" are the latest from repo without any changes

**Comment by kRHYME7** [comment]
❯ ```  ~/.config/hypr/scripts/wallbashtoggle.sh  ```
❯ ```  ~/.config/hypr/scripts/swwwallselect.sh ```
eDP-1: 1500x1000, scale: 2, currently displaying: image: /home/khing/.config/swww/Catppuccin-Mocha/evening-sky.png
❯ ```  ~/.config/hypr/scripts/themeselect.sh  ```
Selected theme: Catppuccin-Mocha
eDP-1: 1500x1000, scale: 2, currently displaying: image: /home/khing/.config/swww/Catppuccin-Mocha/evening-sky.png
kitty: no process found
ok
❯  ``` ~/.config/hypr/scripts/themeswitch.sh -n ```
Selected theme: Catppuccin-Latte
eDP-1: 1500x1000, scale: 2, currently displaying: image: /home/khing/.config/swww/Catppuccin-Mocha/evening-sky.png
kitty: no process found
ok




Here it also has my terminal ouputs

**Comment by kRHYME7** [comment]
just randomly try to see which script gives errors

**Comment by prasanthrangan** [comment]
my wild guess is that `parallel` is missing... as i did use parallel to enhance performance!
you could try running `./swwwallpaper.sh -n`
also check if `EnableWallDcol=1` gets updated in `globalcontrol.sh` with `wallbashtoggle.sh`...

**Comment by TheyCallMeSecond** [comment]
> my wild guess is that `parallel` is missing... as i did use parallel to enhance performance! you could try running `./swwwallpaper.sh -n` also check if `EnableWallDcol=1` gets updated in `globalcontrol.sh` with `wallbashtoggle.sh`...

:) yes "parallel" was the issue...tnx
