### ISSUE TITLE
Menus in vscode blank.

### ISSUE THREAD

**Issue by xryanv** [prasanthrangan/hyprdots#438]
The menus in vscode have some kind of transparency applied to them and are blank. This is likely because of the setup I had already going on before I install these dotfiles. Just curious if anyone could point me in the right direction as to how to fix this, or which config to look at. 

I have already tried the settings.json for vscode, there's nothing there. I tried commenting different parts of windowrules.conf but that didn't seem to do anything.

**Comment by prasanthrangan** [comment]
Hi, is this similar to issue #439 ?
if vscode was working fine before, then you could try copying the `settings.json` file back from backup directory `~/.config/cfg_*` ...

**Comment by xryanv** [comment]
Yes it is a similar issue to the one you mentioned but it only changes the menus to that blank glass color not the whole window itself. Changing the configs doesn't seem to help and it seems the same issue of transparent blank menus is happening in firefox as well (also firedragon was affected). I didn't notice this at first sense I was using librewolf. I tried changing windowrules.conf to windowfules.conf.bak but it didn't change the issue. 

I also tried switching to code-oss and vscodium but the issue continued in each. Then I tried completely deleting vscodium and vscode and code-oss and every config and anything I could find connected to them and reinstalling, the problem still persisted. There must be some process that is skinning the menu in these particular applications  in a way that doesn't quite work properly, but I don't know what's doing it.

It's strange to me that librewolf is not affected since it's basically the same as firefox and firedragon. However I have the most modifications into librewolf, changed the theme and changed some of the css to make sidebar tabs. Changing the themes in vscode didn't fix the issue though.

**Comment by xryanv** [comment]
I managed to change the theme in firefox and this fixed the menus. I didn't launch it from the terminal before the theme change but now when I launch it from terminal it gives the error "(firefox:13990): Gtk-WARNING **: 11:33:59.994: Theme parsing error: gtk.css:3213:16: Unit is missing." unsure if this is related.

Launching vscode from terminal gives no errors.

**Comment by kRHYME7** [comment]
Just for some context.
Tried older hyprland, and it fixes these issues but the hyprland package is out of date.
Also saw some mention about the xwayland app tooltips being blurred/invisible on their discord.
Tried using the old and the default hyprland conf issue persisted on the latest hyprland-git.

**Comment by T-Crypt** [comment]
This is a hyprland issue. 

https://github.com/hyprwm/Hyprland/issues/3743

**Comment by kRHYME7** [comment]
Hey @xryanv ,  we can now close this issue 
Just update your hyprland package. Be mindful that hyprland-nvidia-git may be delayed.


```
 yay -Syu hyprland-git

  ```

**Comment by jasonKoogler** [comment]
NVIDIA GPU?  Thats whats happening on my desktop

I was able to rectify it by changing my settings.json (user) 

`"window.toolbarStyle": "custom"`

pretty sure that was it, on my laptop now so I can't check

**Comment by zer0cha0s** [comment]
> NVIDIA GPU? Thats whats happening on my desktop
> 
> I was able to rectify it by changing my settings.json (user)
> 
> `"window.toolbarStyle": "custom"`
> 
> pretty sure that was it, on my laptop now so I can't check

@jasonKoogler Just checked and this solves it for me, thanks for that.
