### ISSUE TITLE
Applications Startup Exception

### ISSUE THREAD

**Issue by yan-xiongjiang** [prasanthrangan/hyprdots#439]
When I try to open an application such as vscode, clash, etc., I encounter such a situation(nothing is displayed after opening). How should I solve it?
![02d99b90-3403-4072-992f-a9f6a80b4827](https://github.com/prasanthrangan/hyprdots/assets/125042452/a0407764-0502-4424-8dea-53b10ac4280f)

**Comment by prasanthrangan** [comment]
Hi, could you please try opening vscode from terminal and share the output/log?

**Comment by cupenk** [comment]
> When I try to open an application such as vscode, clash, etc., I encounter such a situation(nothing is displayed after opening). How should I solve it? ![02d99b90-3403-4072-992f-a9f6a80b4827](https://user-images.githubusercontent.com/125042452/280446215-a0407764-0502-4424-8dea-53b10ac4280f.png)

same here

**Comment by T-Crypt** [comment]
Hyprland issue. 

https://github.com/hyprwm/Hyprland/issues/3743
