### ISSUE TITLE
[FEATURE REQUEST] Live Wallpaper.

### ISSUE THREAD

**Issue by ghost** [prasanthrangan/hyprdots#440]
Can you add live wallpaper feature to your dotfiles?

**Comment by kRHYME7** [comment]
For some info, I can add .gif to the swww directories and they worked as expected on swww.

**Comment by Akie3301** [comment]
> For some info, I can add .gif to the swww directories and they worked as expected on swww.
where's the path of swww? Can i add .mp4?

**Comment by kRHYME7** [comment]
sadly no .mp4 for now on swww
Look  from https://github.com/Horus645/swww
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/3310208c-93ec-4cce-9347-50c752e09c4a)

But i guess the maintainer can pull off something just like this great repo.

**Comment by Akie3301** [comment]
> For some info, I can add .gif to the swww directories

what's path of swww in your dotfiles? i saw it installed but i dunno where's the path.

**Comment by kRHYME7** [comment]
~/.config/swww/

if you like to add wallpaper you can put it inside the folders.

**Comment by T-Crypt** [comment]
~/.config/swww/(themename)

**Comment by Akie3301** [comment]
https://github.com/prasanthrangan/hyprdots/assets/137863476/7bfecfe2-f6df-4fb1-92b3-81c2711a0361

I didn't saw my gif appear on mod + shift + T or mod + shift + W

**Comment by T-Crypt** [comment]
It's because it's not cached. And make sure you're in the correct theme directory. 

You can run the create_cache.sh script in the Hyprdots repo that you cloned to your $HOME folder

**Comment by Akie3301** [comment]
https://github.com/prasanthrangan/hyprdots/assets/137863476/058c7281-84bc-40f2-bcb9-1fb0b0da1552

I tried but i didn't see anything.

**Comment by kRHYME7** [comment]
@T-Crypt   can this be the culprit.? 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/8f8ed86c-02f6-4e71-8d04-90949f1beee4)

**Comment by kRHYME7** [comment]
Ow sorry @Akie3301  I think the script has been optimized to use  to get jpg jpeg and png

**Comment by Akie3301** [comment]
> Ow sorry @Akie3301 I think the script has been optimized to use to get jpg jpeg and png If you're comfortable to add "gif " yourself
> 
> here is the line
> 
> ```
> mapfile -d '' wpArray < <(find "${wallPath}" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -iname "*.gif" \) -print0 | sort -z)
> ```

Where's this line for me can change it?

**Comment by T-Crypt** [comment]
He's right. 

You need to change line 88 in 

Hyprdots/Scripts/create_cache.sh

**Comment by kRHYME7** [comment]
I guess I wont recommend to try it because our notification and wall bash relied on the image we can disable the wallbash but our notification is built to use wallbash   script  you may get inviisible notifications

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/fbc63454-8827-4c9e-bf26-470179642d17)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/062d276e-564c-40c7-bc2c-e13e99323862)

**Comment by T-Crypt** [comment]
You could try this 


   ~/.config/hypr/scripts/swwwallpaper.sh -s path/to/wallpaper

**Comment by Akie3301** [comment]
> I guess I wont recommend to try it because our notification and wall bash relied on the image we can disable the wallbash but our notification is built to use wallbash script you may get inviisible notifications
> 
> ![image](https://user-images.githubusercontent.com/53417443/280477139-fbc63454-8827-4c9e-bf26-470179642d17.png) ![image](https://user-images.githubusercontent.com/53417443/280477151-062d276e-564c-40c7-bc2c-e13e99323862.png)
> 
> But gif can absolutely be supported soon.

yes, i hope you also add webm.

**Comment by kRHYME7** [comment]
BTW can I know where you got those sick .gifs?

**Comment by Akie3301** [comment]
> BTW can I know where you got those sick .gifs?

https://safebooru.donmai.us/

**Comment by Akie3301** [comment]
> You could try this
> 
> ~/.config/hypr/scripts/swwwallpaper.sh -s path/to/wallpaper
> 
> #400

it works, but:
❯ ~/.config/hypr/scripts/swwwallpaper.sh -s /home/akie3301/Downloads/Gif/__original_drawn_by_wujing_f__45b1f7c94badf252a99007477e0d4ed2.gif

/home/akie3301/.config/hypr/scripts/swwwallbash.sh: line 34: /home/akie3301/.config/spicetify/Themes/Sleek/Wall-Dcol.ini: No such file or directory
sed: can't read /home/akie3301/.config/spicetify/Themes/Sleek/Wall-Dcol.ini: No such file or directory
sed: can't read /home/akie3301/.config/spicetify/Themes/Sleek/Wall-Dcol.ini: No such file or directory
sed: can't read /home/akie3301/.config/spicetify/Themes/Sleek/Wall-Dcol.ini: No such file or directory
sed: can't read /home/akie3301/.config/spicetify/Themes/Sleek/Wall-Dcol.ini: No such file or directory
eDP-1: 1280x720, scale: 2, currently displaying: image: /home/akie3301/Pictures/wallpapers/wallhaven-y8982k_1920x1080.png
❯ 
![image](https://github.com/prasanthrangan/hyprdots/assets/137863476/aa12d8fa-53a7-42c7-9ffb-d236771a91f3)

**Comment by T-Crypt** [comment]
@Akie3301 

Just place those gifs in your pictures and run the command below 

Swww img /home/(user)/Pictures/*.gif 

Replace (user) with your user name and * with the name of the gif 

On Monday, I'll work on adding gif support to the repo. I'm just on my mobile during the weekends

**Comment by kRHYME7** [comment]
Yey, Looking forward for this.

**Comment by Akie3301** [comment]
> Yey, Looking forward for this.

Do you know how to use gifgen? I use it for convert mp4 to gif (i don't use ffmpeg because my gif can have low quality.)
I tried it but it has some error:

**Comment by prasanthrangan** [comment]
ya currently the scripts does not scan for gif files, this will require a rewrite to process gif files!
I tied to use gifs initially, but swww does not play well with gif files as it slows down significantly...

**Comment by Oskar-Idland** [comment]
I tried to just add in `-o  -iname "*.gif"` in both `swwwallpaper.sh` and `swwwallselect.sh`. It showed up in the menu, but without any preview, and when selected all my cpu cores went 100% until the screen shut off. I barely managed to revert the changes before rebooting! Did not show up as a new wallpaper, just froze on the old one.

**Comment by RookiexCookie** [comment]
yea i did that too
same thing happened to me Even my swap got eatten, well dude said he have to rewrite the code to make it properly scan gifs.

**Comment by kRHYME7** [comment]
I'll attempt first to rewrite... If someone already started a WIP maybe I can help with testing.

**Comment by ArikRahman** [comment]
Would it be possible to fix mp4 the same way as gifs?

**Comment by kRHYME7** [comment]
> I'll attempt first to rewrite... If someone already started a WIP maybe I can help with testing.

UPDATES GIF : Made it work.
Added [0] to each wallpaper calls to make the converter extract the very first frame 

Should I issue a MR ?

**Comment by kRHYME7** [comment]
@ArikRahman   > Would it be possible to fix mp4 the same way as gifs?

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/73274c3d-9a23-4060-9ec9-6ef722f7f624)

So in swww it would not be possible.
Might be possible to turn mp4 into gif or other types supported by swww but IMO user might more suitable converting it instead.


Read more : https://github.com/LGFae/swww?tab=readme-ov-file#features

**Comment by kRHYME7** [comment]
BTW CPU usage peaks at 30%.  averages between 10 % -20% CPU usage

**Comment by kRHYME7** [comment]
@Oskar-Idland  @RookiexCookie @ArikRahman 

The .gif support is out now! Try it out. 

to fetch updates you guys can follow this too https://github.com/prasanthrangan/hyprdots/discussions/863#discussioncomment-8438180

Closing this for now as the title is fulfilled.
