### ISSUE TITLE
blank

### ISSUE THREAD

**Issue by cupenk** [prasanthrangan/hyprdots#442]
vscode menu,thorium menu,please fix it.

**Comment by cupenk** [comment]
https://github.com/prasanthrangan/hyprdots/assets/29496587/dd9dcf56-2876-4542-8c5a-9293751ccab0

**Comment by kRHYME7** [comment]
Me too. I'll try to ask the hyprland community on reddit.

**Comment by kRHYME7** [comment]
Commit 4 days ago
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/53736b0f-e75e-47a7-aaf8-03de84472ad3)
got this issue maybe today .

**Comment by T-Crypt** [comment]
#439 and #438 already reference this issue. 

@cupenk can you please try to view open issues before submitting a bunch of issues to the repository? 

If you keep having issues that need to be discussed, I would suggest opening 1 issue and addressing everything in 1 issue please. (You can edit and issue or add comments to an open issue 

You can close this out.

**Comment by T-Crypt** [comment]
Hyprland issue, not the dotfiles. 

https://github.com/hyprwm/Hyprland/issues/3743

**Comment by kRHYME7** [comment]
Yow @cupenk ,  we can now close this issue 
Just update your hyprland package. Be mindful that hyprland-nvidia-git may be delayed.


```
 yay -Syu hyprland-git

  ```

**Comment by T-Crypt** [comment]
@cupenk 

Yay -Syu Hyprland-Nivida-Git or Yay -Syu hyprland-git 

Just replace yay with Paru if yay is not your preferred package manager

**Comment by T-Crypt** [comment]
> Yow @cupenk ,  we can now close this issue 
> 
> Just update your hyprland package. Be mindful that hyprland-nvidia-git may be delayed.
> 
> 
> 
> 
> 
> ```
> 
>  yay -Syu hyprland-git
> 
> 
> 
>   ```

Beat me to it!! 🚀
