### ISSUE TITLE
Can't reboot after install HyprDots

### ISSUE THREAD

**Issue by ms-kneknew** [prasanthrangan/hyprdots#443]
My pc: i3 7100 + Nvidia Gt740
I installed the script according to the instructions. After installing the script, it automatically accesses Hypr and I can use it normally. However, after restarting, I'm stuck at the "Loading init ramdisk" screen, everything is unresponsive, but I can reboot with Ctrl + Alt + Del. I have reinstalled arch and script many times but nothing has changed
I installed Arch using the "archinstall" command, using the default partition layout, Grub boot loader, Minimal Configuration, "Linux" kernel.

Information about my archinstall, issues:
https://drive.google.com/drive/folders/1IjRRAFya-bOktkzr5HN3w1FWnd5OU-SD?usp=sharing

Thanks everyone!!!

**Comment by T-Crypt** [comment]
Your problem is GRUB boatloader.

Install on UEFI partition and select systemd for boot loader.

**Comment by ms-kneknew** [comment]
> Your problem is GRUB boatloader.
> 
> Install on UEFI partition and select systemd for boot loader.

I reinstall arch with systemd bootloader. At reboot, I was able to get to the login screen.  However, after entering username, password and logging in, the screen turns black with an underline, then after 2 3 seconds it switches back to the login screen :<

**Comment by T-Crypt** [comment]
You may need to use hyprland legacy render.

**Comment by T-Crypt** [comment]
Try uninstalling hyprland and installing 

 hyprland-legacyrenderer

**Comment by T-Crypt** [comment]
There is a similar issue in discussion. #448

Let me do some research and see what's causing this.

**Comment by ms-kneknew** [comment]
I'll wait, hope you can help me fix it. Thank you
> There is a similar issue in discussion. #448
> 
> Let me do some research and see what's causing this. 
> 
> EDIT: seems to be a hyprland issue with the latest version 
> 
> https://github.com/hyprwm/Hyprland/issues/3769

**Comment by T-Crypt** [comment]
Are you able to login to TTY? 

You can try starting hyprland manually running the command 

Hyprland (it may fail the first time but should get you in after the 2nd time)

**Comment by ms-kneknew** [comment]
> Are you able to login to TTY? 
> 
> You can try starting hyprland manually running the command 
> 
> Hyprland (it may fail the first time but should get you in after the 2nd time)

I installed the nvidia driver according to the instructions at “https://github.com/korvahannu/arch-nvidia-drivers-installation-guide”, I tried running Hypr with the command “Hyprland” but the result is still the same.

The video describes the error
https://drive.google.com/file/d/1Ac-b4rdD1ZsjM5MGZAP6eqDRl3dv8Qpw/view?usp=drivesdk

**Comment by klpod221** [comment]
I've encountered this error before but sorry I don't remember much about it. Then I tried running the scripts again but something went wrong and I ran each script (restore_fnt.sh, restore_cfg.sh, restore_etc.sh). Then I restarted my computer and everything worked perfectly.

Oh, there is a difference. My system uses linux-lts kernel. Maybe you should try it.

**Comment by ms-kneknew** [comment]
> I've encountered this error before but sorry I don't remember much about it. Then I tried running the scripts again but something went wrong and I ran each script (restore_fnt.sh, restore_cfg.sh, restore_etc.sh). Then I restarted my computer and everything worked perfectly.
> 
> Oh, there is a difference. My system uses linux-lts kernel. Maybe you should try it.
> 
> (Tôi thấy bạn cũng là người Việt thì phải, nếu có gì tôi có thể giúp bạn kỹ hơn bằng tiếng Việt tại tôi không giỏi tiếng Anh cho lắm)

Tôi liên hệ với bạn qua đâu được nhỉ? Tôi cũng là người Việt

**Comment by ms-kneknew** [comment]
My problem is still the same.  Hope someone can help me fix it 😭

**Comment by prasanthrangan** [comment]
Hi, can you please try login to hyprland with default auto generated hyprland.conf file?
so try login to TTY and rename current `~/.config/hypr/hyprland.conf` to something else...

**Comment by ms-kneknew** [comment]
> Hi, can you please try login to hyprland with default auto generated hyprland.conf file?
> 
> so try login to TTY and rename current `~/.config/hypr/hyprland.conf` to something else...

I followed and logged in but it's still the same. I tried running the “Hyprland” command in TTY but it crashes and I can't do anything

**Comment by ms-kneknew** [comment]
Omg, maybe

**Comment by prasanthrangan** [comment]
is this fixed now? is it nvidia drm causing it?
