### ISSUE TITLE
[Request] Add a donation button to this repo

### ISSUE THREAD

**Issue by Balssh** [prasanthrangan/hyprdots#444]
I once again commend the achievements of this project. It's absolutely lovely, and I think you @prasanthrangan should add a donation button somewhere on the main page. I probably wouldn't have delved so deep into Arch if not for this project and I want so show some gratitude.

**Comment by prasanthrangan** [comment]
Hey, thank you (all other contributors as well) sooo much for the continuous help and support!
I just wanted to backup my personal configuration, so I never expected others to find this useful!
Anyways, I'm really happy that I'm able to help/contribute something to others...

> I probably wouldn't have delved so deep into Arch if not for this project and I want so show some gratitude.

hahahaa... my Arch journey just started this year with Microsoft auto upgrading my system from win10 to win11 and breaking the taskbar... which lead me to nuke my windows partition and dive into Linux, so i think we are all in the same boat here, learning Linux (the arch way) as we go :)

regarding donations I'm not sure, as i only do this as my hobby during free time (I work as a database developer in my day job)... so I'll think about it!

**Comment by zer0cha0s** [comment]
> regarding donations I'm not sure, as i only do this as my hobby during free time (I work as a database developer in my day job)... so I'll think about it!

Although it may have started as a hobby try to remember the time your spending fixing issues and reviewing pull requests for other people. 
I'm very much behind T-Crypt's 'Buy Me a Coffee' suggestion but if you don't feel comfortable with that then please know i for one am very grateful for the work you (and all the contributors for that matter) have put in so far.

**Comment by prasanthrangan** [comment]
> @prasanthrangan as a database developer, you have to crave a little coffee sometimes!!

hehee true, i defenitely cannot stay awake at work without coffee :)


> Although it may have started as a hobby try to remember the time your spending fixing issues and reviewing pull requests for other people.
> I'm very much behind T-Crypt's 'Buy Me a Coffee' suggestion but if you don't feel comfortable with that then please know i for one am very grateful for the work you (and all the contributors for that matter) have put in so far.

thank you brother, I've no idea how to enable it, but I'll loo into it!

**Comment by T-Crypt** [comment]
@prasanthrangan Just create an account and paste your link here. 

Ill add it to your repo!

**Comment by rubiin** [comment]
Even if this started as a hobby project, it has helped me and countless others from pain of setting things up with a sensible defaults. I was gonna try hyprland and was looking for resources and stumbled upon the repo and the configs just clicked not to mention the helpful community. So , you should add a donation so people who would like to donate can. I would definitely . Consider it as a token on appreciation for the work you have done @prasanthrangan
