### ISSUE TITLE
Invisible Context Menus in apps like VSCode, Chrome, etc.

### ISSUE THREAD

**Issue by somil0701** [prasanthrangan/hyprdots#445]
![image](https://github.com/prasanthrangan/hyprdots/assets/90393324/76d02625-154b-4a67-b46e-7ed38a08baee)
![image](https://github.com/prasanthrangan/hyprdots/assets/90393324/b1ae19fa-e081-428f-8e34-d74028fde87c)

**Comment by kRHYME7** [comment]
Hi This is already discussed on #438 and #439 Can we close this issue?

**Comment by T-Crypt** [comment]
This is a hyprland issue. 

It's fixed in the latest commit. 

Try yay -Syu hyprland-(version) 

https://github.com/hyprwm/Hyprland/issues/3743

**Comment by somil0701** [comment]
> This is a hyprland issue.
> 
> It's fixed in the latest commit.
> 
> Try yay -Syu hyprland-(version)
> 
> [hyprwm/Hyprland#3743](https://github.com/hyprwm/Hyprland/issues/3743)

I've tried updating hyprland but still this issue persists.

**Comment by kRHYME7** [comment]
Please reboot or exit hyprland to be sure.

**Comment by T-Crypt** [comment]
Your version of hyprland may be behind the main git branch. 

You can downgrade your version or wait until the update is resolved in your respective version branch.

**Comment by somil0701** [comment]
> Please reboot or exit hyprland to be sure. Here is the latest version ![image](https://user-images.githubusercontent.com/53417443/280475437-302981d4-ec86-4535-b951-c046b7b0b1a5.png)

![image](https://github.com/prasanthrangan/hyprdots/assets/90393324/32322cc4-a1c6-4ab4-a956-6cd7996a24ac)
I've noticed that my version is not noticed but I've already run the command sudo pacman -Syu hyprland-git. Am i missing something? (Sorry for asking dumb ques i'm a beginner)

**Comment by kRHYME7** [comment]
have you rebooted or exit Hyprland?

**Comment by somil0701** [comment]
> have you rebooted or exit Hyprland?

yes i've already tried that

**Comment by kRHYME7** [comment]
```  Tag: v0.31.0-81-g73e78f05    ```
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/897c9d03-2574-4c6c-9f14-b23fc19676e5)

Hmm can't answer why your AUR did not update  try to share your ``` paru -Syu hyprland-git ``` output.

**Comment by somil0701** [comment]
> ` Tag: v0.31.0-81-g73e78f05 ` ![image](https://user-images.githubusercontent.com/53417443/280476134-897c9d03-2574-4c6c-9f14-b23fc19676e5.png)
> 
> Hmm can't answer why your AUR did not update try to share your `paru -Syu hyprland-git` output.

Thank, i got it what was causing the problem.
pacman -Syu didn't seem to update the hyprland-git in my case.
But when i updated hyprland-git via yay hyprland-git, it is now working :)
