### ISSUE TITLE
Change locksreen wallpaper

### ISSUE THREAD

**Issue by remunata** [prasanthrangan/hyprdots#446]
Hi @prasanthrangan, thank you for this rice project! its really well made and I absolutely enjoy it!, but I wonder how can I change the lockscreen wallpaper?

Thanks a lot!

**Comment by T-Crypt** [comment]
Set your favorite wallpaper by adding it to a theme or selecting a wallpaper that's your favorite from the ~/.config/swww directory by going to the theme and setting with Super + Shift + W 

And then manually run the script sddmwall.sh cause you'll need to enter password as the directory is in /usr/share 

~/.config/hypr/scripts/sddmwall.sh

**Comment by remunata** [comment]
Alright, it worked. Thanks for your help!
