### ISSUE TITLE
Unable to launch to the image operation interface

### ISSUE THREAD

**Issue by hui3215** [prasanthrangan/hyprdots#447]
Hello, I am very eager for your help because I have a problem that is difficult to solve.

At the beginning, I updated the system and found that `xwaylandvideobridge-cursor-mode-2-git` was out of date, then I uninstalled it and installed `xwaylandvideobridge-git`, but now I can't get in, the desktop can only stay on the login page, the following picture is Hyprland's boot log

This is log text
```log

[LOG] Instance Signature: 2b07d54bc74f34a3561612bedaa44adBab550b8b_1699151147
[LOG] Hyprland PID: 1546
[LOG] ==== SYSTEN INFO ====
[LOG] System name : Linux
[LOG] Node name: archlinux
[LOG] release: 6.5.9-arch2-1
[LOG] Version: #1 SMP PREEMPT DYNANIC Thu, 26 Oct 2023 00:52:20 +0000

[LOG] GPU information:
01:00.0 VGA compatible controller [0300]: NUIDIA Corporation TU117N EGcForce GTX 1650 Nobile / Nax-Q] C10de:1f91] (rev a1)(prog-if 00 [VGA controller]) 
 
[WARN] Warning: you are using an NVIDIA GPU. Make sure you follow the instructions on the wiki if anything is amiss.

[LOG] os-release:
NANE="Arch Linux"
PRETTY_NANE="Arch Linux"
ID=arch
BUILD ID=rolling
ANSI COLOR=''38:2:23:147:209
HOME_URL="https:2/archlinux.org/"
DOCUNENTATION URL="https://wiki.archlimux.org/"
SUPPORT_URL="https://bbs.archlinux.orgey
BUG_REPORT_URL="'https://bugs.archlãnux.org/"
PRIUACY_POLICY_URL="'https://terws.archlinux.org/docs/privacy-policy/"
LOG0=archlinux-logo
[LOG] ==================================

[INFO] If you are crashing. or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/

[LOG] Creating the HookSystem!
[LOG] Creating the keybindManager
[LOG] [hookSystem] New hook event registered: configReloaded
[LOG] Createing the AnimationManager
[LOG] Created a bezior curue, baked 255 points,mem usage: 4.00KB ,time to bake: 22.82us

..........
 
```

![f96844c444db440355249e35fd6c0bca_750](https://github.com/prasanthrangan/hyprdots/assets/53279456/bd65eea2-3e2e-4335-b0e6-e1844e84d248)

**Comment by kRHYME7** [comment]
Sorry But the logs is quite blurry

**Comment by hui3215** [comment]
> 对不起，但是日志很模糊
> 
> 但是您是否尝试过重新安装 Hyprland 和 xdg-desktop-portal-hyprland-git。另外，如果您再次安装 xwaylandvideobridge-cursor-mode-2-git 会发生什么？不过，我对这个问题无能为力

Thank you, I will provide the log text later, if you can tell me if you find a problem, I will be very grateful for your help

**Comment by kRHYME7** [comment]
Is xwaylandvideobridge-git use for screensharing?  Why not use xdg-desktop-portal-hyprland-git ?  or they both serve different purposes?

**Comment by hui3215** [comment]
> xdg-desktop-portal-hyprland-git
Ok, I tried uninstalling xwaylandvideobridge-git，
And then please also take a look at the log above, I added a document

**Comment by hui3215** [comment]
> > Is xwaylandvideobridge-git use for screensharing?  Why not use xdg-desktop-portal-hyprland-git ?  or they both serve different purposes?
> > Edit: Ow I get it.
> > How about uninstalling xwaylandvideobridge-git to narrow down the Issue with hyprland
> 
> UPDATE: 没关系 xwaylandvideobridge-git 在我这边工作。您能否也提供您的系统硬件，以便存储库中的某个人更容易提供帮助。谢谢，我希望有人可能已经知道这个问题的解决方案。也许你可以检查一下
> 
> > [信息]如果你崩溃了。或遇到任何 bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/
> > maybe this is a common issue.

Intel(R) Core(TM) i7-9750HF CPU @ 2.60GHz   2.59 GHz
Getforce GTX 1650

**Comment by kRHYME7** [comment]
Hi How about Launching your Hyprland  without config so it could generate its  own config.

**Comment by prasanthrangan** [comment]
Hi, please try launching hyprland with the default auto generated config... just rename or remove the current `hyprland.conf` file

**Comment by hui3215** [comment]
> Hi, please try launching hyprland with the default auto generated config... just rename or remove the current `hyprland.conf` file

ok thank you
