### ISSUE TITLE
Weird Cursor Behaviour

### ISSUE THREAD

**Issue by somil0701** [prasanthrangan/hyprdots#451]
https://github.com/prasanthrangan/hyprdots/assets/90393324/4278dc4e-085b-4192-b22c-385c357636b9

Here, at first the cursor seems a little blurred and big (may not be noticeable in this screen recording) and while selecting text it does the same. But, after I hover the cursor at my waybar then the cursor becomes to it's normal size that it should be and with no blur at all and while selecting text the cursor does not change for text selection.

Note: I've tried restarting hyprland/rebooting but nothing seems to work for this issue.
(Sorry for bad explanation I don't know much about this)

**Comment by kRHYME7** [comment]
Sadly I think this is a normal/expected behavior as of now.  Hyprland states this on there wiki.

**Comment by kRHYME7** [comment]
Also answered on #353 Inconsistent Cursor.

**Comment by somil0701** [comment]
> Sadly I think this is a normal/expected behavior as of now. Hyprland states this on there wiki.
> 
> Unfortunately, as of now, there doesn't seem to be a general solution to these issues. The Hyprland team is aware of these problems and is working on fixes, but they may not be available yet.
> 
> Maybe We can Close this issue as of now? @somil0701

Thanks for the clarification @kRHYME7 (＾▽＾)
