### ISSUE TITLE
[question] How to remove or minimize the space between window and waybar?

### ISSUE THREAD

**Issue by harshil1973** [prasanthrangan/hyprdots#453]
I have tried setting padding-bottom: 0px in waybar style.css present in modules but it is not working.
![231106_14h46m03s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/58188146/cecce6ab-523e-4a90-831d-55b65a6b1029)

**Comment by kRHYME7** [comment]
``` ~/.config/hypr/themes/theme.conf  ``` (and the other  themes)
remember  that this is  only a link so you may need to modify other themes also

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c51b26f3-45f2-44a4-9713-818ed9ea3a12)

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/229aae1d-32d9-40c1-a621-0222eb53abaa)
