### ISSUE TITLE
Support for superultrawides (mainly 1440p, 4k)

### ISSUE THREAD

**Issue by Danielduel** [prasanthrangan/hyprdots#454]
Hi, I more or less understand how this project works, and I would like to add a few fixes for fonts being too small on hidpi displays and to add more fitting wallpaper sizes. 
I miss the info where the current bgs are coming from, so I can check if there are higher res/vector versions. The alternative would be to use an upscaling ai.

**Comment by T-Crypt** [comment]
@Danielduel 

What fonts are too small? A lot of these changes can be made on your dotfiles in userprefs.conf in the ~/.config/hypr/ directory

**Comment by prasanthrangan** [comment]
Hi, regarding fonts please try adjusting it in `.config/hypr/themes/common.conf`

https://github.com/prasanthrangan/hyprdots/blob/1c796214fea72abc26e78b7ae9f3dc443adaec84/Configs/.config/hypr/themes/common.conf#L16-L20

**Comment by Danielduel** [comment]
@T-Crypt @prasanthrangan 
Sorry for being very vague :sweat: 

## Fonts

My current overrides are:

`@/userprefs.conf`
```conf
exec = gsettings set org.gnome.desktop.interface font-name 'Cantarell 14'
exec = gsettings set org.gnome.desktop.interface document-font-name 'Cantarell 14'
exec = gsettings set org.gnome.desktop.interface monospace-font-name 'CaskaydiaCove Nerd Font Mono 11'
```

Can I somehow feature-request (or could you point me into a better direction) how to make fonts bigger for waybar without doing inline modifications to scripts?

`@/scripts/wbarconfgen.sh`
```sh
export i_size=$(( w_height*6/10 ))
if [ $i_size -lt 16 ] ; then                                # those 16s are inline modification
    export i_size="16"
fi

export i_theme=`gsettings get org.gnome.desktop.interface icon-theme | sed "s/'//g"`
export i_task=$(( w_height*6/10 ))
if [ $i_task -lt 30 ] ; then                                # those 30s are inline modification
    export i_task="30"
fi
```

`@/scripts/wbarstylegen.sh`
```sh
if [ $s_fontpx -lt 24 ] ; then                           # those 24s are inline modification
    export s_fontpx=24
fi
```

I think I could add global vars that are reused in those scripts and make PR, but I am not sure if this is the correct way when managing dotfiles.

## Wallpapers

The topic about wallpapers is not "where I can find them on my disc", but "where I could have a chance to find them in higher quality" so I could get for example 8k version and crop 5120x1440 (32:9) out of them (which is horizontally higher than 4k's 3840)

**Comment by kRHYME7** [comment]
>Can I somehow feature-request (or could you point me into a better direction) how to make fonts bigger for waybar without doing inline modifications to scripts?

Hi how about making waybar bigger at  ``` ~/.config/waybar/config.ctl   ``` ?

**Comment by Danielduel** [comment]
Hello @kRHYME7 
I don't see how you could modify size of the waybar in `~/.config/waybar/config.ctl`, I think you rather meant it's `style.css` and `config.jsonc`, but both of those files are autogenerated on theme/waybar change which makes this method unfeasible as long term solution. (note that I don't fully understand how those `.ctl` files are used so I might be very wrong here.

**Comment by Danielduel** [comment]
// I've understood how this ctl file works, thanks @kRHYME7

**Comment by kRHYME7** [comment]
My bad for not explaining it further. But great!

**Comment by Danielduel** [comment]
I am new to this "shared dotfiles" idea and I am often very confused by standards used here, but I am keen to learn! ^^

**Comment by wutfor** [comment]
@Danielduel I personally use a stable diffusion webui to upscale wallpapers, but [this](https://waifu2x.booru.pics/) should also get the job done.

**Comment by prasanthrangan** [comment]
guess this is answered, regarding wallpaper up scaling [upscaler]( https://flathub.org/apps/io.gitlab.theevilskeleton.Upscaler) has worked well for me!
