### ISSUE TITLE
Pacman autofill doesn't work

### ISSUE THREAD

**Issue by Artavazdpet** [prasanthrangan/hyprdots#455]
A week or so ago after update (pacman -Syu) pacman autofill doesn't work, but it works without sudo.
(F.e. "pacman -S wi" + tab works (looking for wine), but "sudo pacman wi" + tab doesn't work.)

**Comment by kRHYME7** [comment]
Reporting that it works on my end. And also for clarifications
>sudo pacman wi" + tab doesn't work.)
This is expected to not work right? no flags for pacman. but if this is a typo on the post 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/d59a6046-6345-4798-95e8-bb2f88d3f0b1)


![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/cc4406e5-0622-4d22-a8a2-219dde64bbf8)

**Comment by T-Crypt** [comment]
Terminal Auto Suggestion / Auto Filling is a zsh plugin.

Can you run:

`echo $SHELL`

`chsh -s $(which zsh)`

**Comment by labanya007** [comment]
It's not just pacman. Autosuggestion does not work at all with sudo prefix.

**Comment by labanya007** [comment]
Sorry, I wanted to mean tab-completion (I forgot auto-suggestion mean something else). If I try to tab-complete anything with the sudo prefix, it simply does not work.

**Comment by labanya007** [comment]
A quick fix that seems to work is to add the following in the ~/.zshrc

complete -cf sudo

**Comment by T-Crypt** [comment]
@labanya007 

Hitting the right arrow key is what auto completes the suggestion. 

Hitting tab will give you suggestions but its more broad when running sudo commands.

**Comment by ps-leonardo** [comment]
This issue is related to https://github.com/kovidgoyal/kitty/issues/6754
Adding `shell_integration no-sudo` to ~/.config/kitty/kitty.conf will fix it

**Comment by devCKVargas** [comment]
It happened about 2 weeks ago.
`sudo pacman -Rns` or `un` suddenly stopped giving suggestions for installed apps.
I've been using `expac --timefmt='\''%Y-%m-%d %T'\'' '\''%l\t%n %v'\'' | sort | tail -3000 | nl` with `grep` to check if pkg is in my system 😮‍💨

**Comment by prasanthrangan** [comment]
great thanks @ps-leonardo , but autofill works for me for sudo commands as well

**Comment by ps-leonardo** [comment]
mine suddenly stopped working after i had to reinstall Arch and reimport my personal .zsh files. it was working fine on the same day a few hours earlier, so idk how they implemented that change in kitty

**Comment by prasanthrangan** [comment]
cool thanks! I'll close this... please reopen if this workaround does not work.
