### ISSUE TITLE
Disable mouse when screenshot and change theme of Wifi and Bluetooth 

### ISSUE THREAD

**Issue by T3l3sc0p3** [prasanthrangan/hyprdots#460]
Hi, the first problem is that the Wifi and the Bluetooth doesn't change their theme after I turn on wallbash, you can see it in the screenshot below:
![image](https://github.com/prasanthrangan/hyprdots/assets/96990857/a83d96db-aa72-4f9b-9da8-3c3704d02551)

You also see that in the bottom right of the screenshot still have mouse, which is the second problem

Hope you can fix this soon

**Comment by zer0cha0s** [comment]
For the first issue these are application icons not glyphs so i don't think they can been themed. I have icons for steam,discord etc which are there default colors no matter what theme i use (With wallbash on or off).
![image](https://github.com/prasanthrangan/hyprdots/assets/21130965/b60f588d-2c20-4746-a15d-d39d4b66fb55)

With regards to the second issue does it only do that when you screenshot something at the bottom of the screen as I'm getting a slight bit of the cursor when i do that(see screenshot above) but as you can see in the below screenshot when i take a snip from the middle its fine.

![image](https://github.com/prasanthrangan/hyprdots/assets/21130965/36627a08-e6ba-48d1-b7a1-f507f443f8c2)

**Comment by T3l3sc0p3** [comment]
Thanks for the response, I agree with you on the first problem. However, in the second problem, I still get the cursor even if I take screenshots from any spot

**Comment by zer0cha0s** [comment]
No worries i'm sure we can get to the bottom of it. 
What version of Grimblast do you have installed ?

**Comment by T3l3sc0p3** [comment]
It's r68.e2cb355-1

**Comment by zer0cha0s** [comment]
Ok just updated mine to compare and i am unable to replicate the issue so far. 
Are you running Nvidia drivers, if so could you check the output of this command please `echo $WLR_NO_HARDWARE_CURSORS`. Id expect it to be 1 as that's what its set to in the hyprdots config.

**Comment by T3l3sc0p3** [comment]
Yea, it's 1

**Comment by zer0cha0s** [comment]
Guess what i was able to replicate it kinda I'm now getting double cursor! 

![image](https://github.com/prasanthrangan/hyprdots/assets/21130965/ac04fb1e-71c7-429e-bcca-cda2fb9eb563)

Do you happen to have hyprpicker installed, I've just installed it after seeing pull request #456 to fix the --freeze function of grimblast and now im getting the same.

**Comment by T3l3sc0p3** [comment]
Yes, so install hyprpicker will cause this bug right?

**Comment by zer0cha0s** [comment]
Yea looks that way, just taking a peek at the Grimblast code and it shows the following:

![image](https://github.com/prasanthrangan/hyprdots/assets/21130965/2953b475-283f-46c7-aa61-82667311ebce)

If i remove the --freeze option from .config/hypr/scripts/screenshot.sh it does not show the cursor as its not calling hyprpicker, so if your not worried about freezing the screen before taking your screenshot you can just change 
`grimblast --freeze copysave area $temp_screenshot && swappy -f $temp_screenshot ;;`
to 
`grimblast copysave area $temp_screenshot && swappy -f $temp_screenshot ;;`

Note: I did find this issue raised #https://github.com/hyprwm/contrib/issues/60 but it hasn't been fixed yet.

Sorry its only workarounds for this one at the mo, maybe one of the bigger brains will come along with a better solution.

**Comment by kRHYME7** [comment]
check this out  https://github.com/hyprwm/contrib/issues/47

**Comment by kRHYME7** [comment]
how about adding delays ?

**Comment by zer0cha0s** [comment]
> how about adding delays ?

I dont think that will help when using area from looking at the code im pretty sure its hyprpicker's freeze function that's capturing the crosshair from slurp.

**Comment by kRHYME7** [comment]
Hmmm So this issue should be addressed to  the contrib right? Do you have some work around here.

**Comment by T3l3sc0p3** [comment]
> If i remove the --freeze option from .config/hypr/scripts/screenshot.sh it does not show the cursor as its not calling hyprpicker, so if your not worried about freezing the screen before taking your screenshot you can just change `grimblast --freeze copysave area $temp_screenshot && swappy -f $temp_screenshot ;;` to `grimblast copysave area $temp_screenshot && swappy -f $temp_screenshot ;;`

I think I'll use this as a temporary solution until get a new update from Grimblast. Thanks @zer0cha0s 👍🏼

**Comment by zer0cha0s** [comment]
> > Hmmm So this issue should be addressed to  the contrib right? Do you have some work around here.
> > the cursor is a bit annoying BTW when I tried adding a screenshot to a document
> > nvm
> 
> Have you guys tried using just grimblast?

Grimblast is what we are all using right ?

**Comment by zer0cha0s** [comment]
> I found something slightly strange, I commented out hyprpicker on ~/.local/bin/grimblast and this removes the cursor and still effectively freezes the screen. What really is the use of hyprpicker? haha ![image](https://user-images.githubusercontent.com/53417443/281471094-f761ddc1-b4a6-4f01-b7f9-4ff5a89c8950.png)

Well thats basically the same as removing the hyprpicker package which does indeed remove the cursor as i mentioned earlier today. but when i tested earlier having a timer on my browser the screen was still updating.

**Comment by zer0cha0s** [comment]
Ive just doubled checked by commenting out that line and it 100% isnt freezing my screen.

**Comment by T3l3sc0p3** [comment]
> Ive just doubled checked by commenting out that line and it 100% isnt freezing my screen.

Me too, without hyprpicker it won't freeze screen anymore ._.

**Comment by kRHYME7** [comment]
Mine delays a few seconds and then freezes it thu. 
Well I will be actively monitoring the progress  of grimblast case some improvements can be applied to our screenshot script

**Comment by zer0cha0s** [comment]
If you could change your crosshair icons into half a crosshair (east and south prongs only) then you'd probably have a workaround that allows you to keep hyprpicker enabled/installed and doesn't have the crosshair showing in the bottom right of your screenshots.

**Comment by T3l3sc0p3** [comment]
Another way that I think is possible is to somehow make the cursor above Grimblast

**Comment by kRHYME7** [comment]
> none of these are the culprit, it's hyprland's fault. FWIW, same will happen on any wlroots compositor. We could get around it, but it would be inefficient.

#60  here is our answer for now.

**Comment by kRHYME7** [comment]
> the first problem is that the Wifi and the Bluetooth

Oh, to fulfill this Issue these are the tray Icons therefore they are using the GTK icons Ig. Therefore, we can't really do much, unless we configure GTK SVG icons to follow wallbash.(So this is a No for now) 

HOWEVER,  It's possible but would take a lot of effort.( Tittu is cooking this feature so will wait 😁)
