### ISSUE TITLE
Nvidia Driver for Arch; version 470xx

### ISSUE THREAD

**Issue by kneknew** [prasanthrangan/hyprdots#462]
Sorry if this question is not according to the rules.
I'm the one who created issue #441 and I found the problem, it was in the Nvidia driver for my GT740. I tried removing my VGA from the Mainboard and logging into Hypr and it worked fine.
Can anyone guide me to install drivers for it? I followed the instructions on ArchWiki and some youtube clips but it didn't seem to work. Thanks everyone

**Comment by prasanthrangan** [comment]
so you'll have to ensure nvidia drm is enabled at boot... could you please try the [early loading](https://wiki.archlinux.org/title/NVIDIA#Early_loading)

**Comment by ms-kneknew** [comment]
> so you'll have to ensure nvidia drm is enabled at boot... could you please try the [early loading](https://wiki.archlinux.org/title/NVIDIA#Early_loading)
> 
> I had this [script](https://github.com/prasanthrangan/hyprdots/blob/main/Scripts/.old/install_mod.sh) , you can try running it as well...

So with that script, I just need to install the nvidia-470xx-dkms package then run the script and it's done, right?

**Comment by prasanthrangan** [comment]
> So with that script, I just need to install the nvidia-470xx-dkms package then run the script and it's done, right?

yes correct, the script will just enable early loading for nvidia dkms modules as mentioned in arch wiki!

**Comment by ms-kneknew** [comment]
> > So with that script, I just need to install the nvidia-470xx-dkms package then run the script and it's done, right?
> 
> yes correct, the script will just enable early loading for nvidia dkms modules as mentioned in arch wiki!

I ran that Script but I'm still stuck at the login screen :<

**Comment by prasanthrangan** [comment]
oh no... does your card support nvidia-470xx-dkms driver? unfortunately Hyprland is hit or miss with old nvidia drivers

**Comment by ms-kneknew** [comment]
> nvidia-470xx-dkms

I have double checked my GT740 VGA is still supported in the 470xx package. After installing the driver, I checked with the command nvidia-smi and it seems it cannot recognize the name of my graphics card.

**Comment by GeorgeAndreiBals** [comment]
> > nvidia-470xx-dkms
> 
> I have double checked my GT740 VGA is still supported in the 470xx package. After installing the driver, I checked with the command nvidia-smi and it seems it cannot recognize the name of my graphics card.

Read carefully the Arch Wiki on the NVIDIA drivers, I also had troubles with them and I have a fairly new GPU. Also what bootloader do you use?

**Comment by prasanthrangan** [comment]
> I have double checked my GT740 VGA is still supported in the 470xx package. After installing the driver, I checked with the command nvidia-smi and it seems it cannot recognize the name of my graphics card.

this definitely looks like driver issue... the 470xx drivers are old, and it may have issues as mentioned in arch wiki

**Comment by ms-kneknew** [comment]
> > > nvidia-470xx-dkms
> 
> > 
> 
> > I have double checked my GT740 VGA is still supported in the 470xx package. After installing the driver, I checked with the command nvidia-smi and it seems it cannot recognize the name of my graphics card.
> 
> 
> 
> Read carefully the Arch Wiki on the NVIDIA drivers, I also had troubles with them and I have a fairly new GPU. Also what bootloader do you use?

I'm using Systemd boot

**Comment by Balssh** [comment]
> > > > nvidia-470xx-dkms
> > 
> > 
> > > 
> > 
> > 
> > > I have double checked my GT740 VGA is still supported in the 470xx package. After installing the driver, I checked with the command nvidia-smi and it seems it cannot recognize the name of my graphics card.
> > 
> > 
> > Read carefully the Arch Wiki on the NVIDIA drivers, I also had troubles with them and I have a fairly new GPU. Also what bootloader do you use?
> 
> I'm using Systemd boot

Did you made sure to rebuild the initramfs after the driver installation? I had a problem where I forgot to add the pacman hook for nvidia and they got out of sync so nvidia-smi was trowing errors.

**Comment by ms-kneknew** [comment]
I followed the instructions on ArchWiki and also HyprlandWiki but none of them worked.

**Comment by ms-kneknew** [comment]
I have now removed nvidia-dkms and nvidia-utils. And my arch is working fine 🥲

**Comment by prasanthrangan** [comment]
> I have now removed nvidia-dkms and nvidia-utils. And my arch is working fine 🥲

Ohh, is it working now?? You might be using igpu

**Comment by ms-kneknew** [comment]
> > I have now removed nvidia-dkms and nvidia-utils. And my arch is working fine 🥲
> 
> Ohh, is it working now?? You might be using igpu

Sure, I think using ipgu is a temporary solution until the exact error is discovered and fixed

**Comment by Balssh** [comment]
> > > I have now removed nvidia-dkms and nvidia-utils. And my arch is working fine 🥲
> > 
> > 
> > Ohh, is it working now?? You might be using igpu
> 
> Sure, I think using ipgu is a temporary solution until the exact error is discovered and fixed

Did you also try: https://www.reddit.com/r/archlinux/comments/z3owhm/comment/ixpncru/?utm_source=share&utm_medium=web2x&context=3
It refers to this part of https://wiki.archlinux.org/title/NVIDIA#Installation
![image](https://github.com/prasanthrangan/hyprdots/assets/82440615/911e6f6d-0bfe-41a1-8697-0580ed1934de)

**Comment by Balssh** [comment]
@ms-kneknew is this issue still relevant or can be closed?

**Comment by kRHYME7** [comment]
Hello @kneknew Or anyone might be reading this, older drivers like NVIDIA 470xx almost won't run Hyprland. But no worries, you can still use the nouveau driver instead and hyprland can run it. https://wiki.archlinux.org/title/nouveau
