### ISSUE TITLE
Right Click results in empty menu

### ISSUE THREAD

**Issue by gurv1r** [prasanthrangan/hyprdots#463]
Shown in image, using all themes but issue still persists. Issue not isolated to just Visual Studio Code, but other apps such as chromium browser.

![image](https://github.com/prasanthrangan/hyprdots/assets/104674196/aeaf01de-04ea-4ccc-a437-b085d4dc4ad6)

**Comment by zer0cha0s** [comment]
Changing the toolbar style to custom in the vscode settings fixed this for me 
"window.toolbarStyle": "custom"

**Comment by gurv1r** [comment]
How did you go about doing that? When clicking the gear I again only see blanks.

**Comment by zer0cha0s** [comment]
They were blank when i clicked the menus but appeared when i hovered over them.
You can also press F1 and type >Preferences: Open Settings (UI)
![image](https://github.com/prasanthrangan/hyprdots/assets/21130965/79439764-7ee2-40dc-8f7c-c76f6f2f40bd)


Also i typed the wrong thing in last night its this option you need to set to custom.
![image](https://github.com/prasanthrangan/hyprdots/assets/21130965/64d80f56-1ba5-4716-aaaf-39676b74af1e)

**Comment by prasanthrangan** [comment]
Hi @gurv1r , are you using nvidia?
This happens to me as well, so can please try launching with these options? 

```
code --disable-gpu-sandbox
```
or
```
code --disable-gpu
```

**Comment by gurv1r** [comment]
I'm on an Intel powered laptop, specifically the i7-1165G7 chip with integrated graphics. The issue is not isolated to only vscode, but also chromium based browsers.

**Comment by prasanthrangan** [comment]
Hi, please try launching chrome with these options
`--enable-features=UseOzonePlatform --ozone-platform=wayland`

**Comment by gurv1r** [comment]
Have fixed it on chromium, but the issue is not isolated to single instances. It is even on the vlc media player, and other apps such as multiviewer for f1.

**Comment by gurv1r** [comment]
Issue fixed by updating hyprland-git to newest, issue seems to be linked to https://github.com/hyprwm/Hyprland/issues/3743 but not confirmed. Anyone facing the same issue should also update their hyprland install.
