### ISSUE TITLE
Not find zsh

### ISSUE THREAD

**Issue by yousseffjel** [prasanthrangan/hyprdots#469]
Some help
i start script intsall.sh and everything go good but just have this error idk why, i try to remove zsh and install it again but have  the same error

![231109_18h06m23s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/37506107/861ff6b1-e519-49c4-ab9d-5fdfd2ae2248)

and when i run "chsh -l" i have this 
![231109_18h11m05s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/37506107/1c1b2635-0351-4370-9d46-81e1ca21ecfc)

**Comment by T-Crypt** [comment]
Command is

chsh-s $(which zsh)

**Comment by T-Crypt** [comment]
also sbin is wrong

It's in /bin/zsh

**Comment by yousseffjel** [comment]
when i do that manual its work

**Comment by prasanthrangan** [comment]
Hi, please run this to change shell, youjust have to do it once manually 

```
chsh -s /usr/bin/zsh
```
