### ISSUE TITLE
Failed to install package

### ISSUE THREAD

**Issue by PSCalderRued** [prasanthrangan/hyprdots#47]
Failed to install hyprland-nvidia-git. Tried adding it manually, didn't work. I'm using a 3060ti, I did a it in a minimal style as the instructions said, if I force to start it it displays the login screen with no hyprland install.Exit status 4

**Comment by PSCalderRued** [comment]
Nvm, fixed it

**Comment by prasanthrangan** [comment]
Oh great, what was the problem??

**Comment by PSCalderRued** [comment]
No idea 😅, ultimately I couldn't tell, when installing, after choosing between rust or rust up another screen appeared asking for imput, if I chose any other option other ran (I) Install it wouldn't fetch the files, anyways, amazing job with the rice, already using it on my main and laptop!

**Comment by prasanthrangan** [comment]
Thank you so much for the support! I'm glad its working for you :)
