### ISSUE TITLE
 Unable to start vmware ;  Gtk-WARNING **: 10:40:58.143: Cannot open display: :1

### ISSUE THREAD

**Issue by kurisaW** [prasanthrangan/hyprdots#470]
Unable to start vmware, and the error message is: (vmware:6584): Gtk-WARNING **: 10:40:58.143: Cannot open display: :1

**Comment by TwelveNight** [comment]
```bash
GDK_BACKEND=x11
```
add this to your env,for rofi you may change the .desktop file,but I think kvm is better

**Comment by devCKVargas** [comment]
Try adding this `env = GDK_BACKEND,wayland,x11` in your `~/.config/hypr/userprefs.conf`
And reboot

**Comment by kurisaW** [comment]
@devCKVargas @TwelveNight Thank you very much for your reply, but this method does not seem to be feasible, I was able to enter the graphical desktop normally, because I installed vmware workstation again after installing hyprdots on archlinux, when I tried to open the vm, the above error was displayed

**Comment by xryanv** [comment]
#!/bin/bash
xhost si:localuser:root
sudo DISPLAY=:1 vmware

**Comment by kRHYME7** [comment]
Any progress or potential solution here?

**Comment by kRHYME7** [comment]
Reopen if necessary
