### ISSUE TITLE
double battery 

### ISSUE THREAD

**Issue by yousseffjel** [prasanthrangan/hyprdots#472]
Hey guys want to ask if can make my 2 battery show in waybar  because its just show one 
![image](https://github.com/prasanthrangan/hyprdots/assets/37506107/0c5115ab-cbd5-4f84-b50a-c111f6715d11)

**Comment by OctavianOG** [comment]
Greetings, if I understand correctly you want to add a secondary battery module to the Waybar, you can probably do this by just following the [Waybar wiki](https://github.com/Alexays/Waybar/wiki/Configuration#multiple-instances-of-a-module)

**Comment by yousseffjel** [comment]
> Hi, sorry i don't get it... your laptop has 2 batteries?

Yes

**Comment by yousseffjel** [comment]
> Greetings, if I understand correctly you want to add a secondary battery module to the Waybar, you can probably do this by just following the [Waybar wiki](https://github.com/Alexays/Waybar/wiki/Configuration#multiple-instances-of-a-module)

Really i see that but i don't know how to do it

**Comment by OctavianOG** [comment]
@yousseffjel Unfortunately, my laptop doesn't have a secondary battery, so I haven't been able to test whether using the wiki's tips will actually help, but I'll try to give you some guidance on what you should do to suit your needs.

1. Open ur terminal <kbd>Command + T</kbd>

2. Open waybar config with any text editor(i'll use nano for example) - `sudo nano ~/.config/waybar/config.jsonc`

3. Find module named "battery", it should be on line 116, change it to this:
```ruby
    "battery": {
        "bat": "BAT1",
        "states": {
            "good": 95,
            "warning": 30,
            "critical": 20
        },
        "format": "{icon} {capacity}%",
        "format-charging": " {capacity}%",
        "format-plugged": " {capacity}%",
        "format-alt": "{time} {icon}",
        "format-icons": ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
    },
    
    "battery#bat2": {
        "bat": "BAT2",
        "states": {
            "good": 95,
            "warning": 30,
            "critical": 20
        },
        "format": "{icon} {capacity}%",
        "format-charging": " {capacity}%",
        "format-plugged": " {capacity}%",
        "format-alt": "{time} {icon}",
        "format-icons": ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
    },
```

If this works for you, then you also should change waybar config in your local hyprdots repo, it is located in `hyprdots/Config/.config/waybar/config.jsonc`, just do all of the above actions with this file.

As stated in wiki itself, it is incomplete, so if it doesn't work then try to find some info in [Waybar repo](https://github.com/Alexays/Waybar) issues or discussions.

**Comment by prasanthrangan** [comment]
please note `~/.config/waybar/config.jsonc` is generated on the fly, so please make this change in `.config/waybar/modules/battery.jsonc` instead

**Comment by kRHYME7** [comment]
Hi @yousseffjel  I will be willing to help you but we need you to test it because we don't have a dual batt setup.

**Comment by yousseffjel** [comment]
> @yousseffjel Unfortunately, my laptop doesn't have a secondary battery, so I haven't been able to test whether using the wiki's tips will actually help, but I'll try to give you some guidance on what you should do to suit your needs.
> 
> 1. Open ur terminal Command + T
> 2. Open waybar config with any text editor(i'll use nano for example) - `sudo nano ~/.config/waybar/config.jsonc`
> 3. Find module named "battery", it should be on line 116, change it to this:
> 
> ```ruby
>     "battery": {
>         "bat": "BAT1",
>         "states": {
>             "good": 95,
>             "warning": 30,
>             "critical": 20
>         },
>         "format": "{icon} {capacity}%",
>         "format-charging": " {capacity}%",
>         "format-plugged": " {capacity}%",
>         "format-alt": "{time} {icon}",
>         "format-icons": ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
>     },
>     
>     "battery#bat2": {
>         "bat": "BAT2",
>         "states": {
>             "good": 95,
>             "warning": 30,
>             "critical": 20
>         },
>         "format": "{icon} {capacity}%",
>         "format-charging": " {capacity}%",
>         "format-plugged": " {capacity}%",
>         "format-alt": "{time} {icon}",
>         "format-icons": ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
>     },
> ```
> 
> If this works for you, then you also should change waybar config in your local hyprdots repo, it is located in `hyprdots/Config/.config/waybar/config.jsonc`, just do all of the above actions with this file.
> 
> As stated in wiki itself, it is incomplete, so if it doesn't work then try to find some info in [Waybar repo](https://github.com/Alexays/Waybar) issues or discussions.

 i do it in battery.jsonc and not work

**Comment by yousseffjel** [comment]
> Hi @yousseffjel I will be willing to help you but we need you to test it because we don't have a dual batt setup.

okay

**Comment by OctavianOG** [comment]
@yousseffjel , after changing waybar configs you need to restart waybar, you can do it by following command:
```ruby
killall -SIGUSR2 waybar
```

**Comment by yousseffjel** [comment]
> @yousseffjel , after changing waybar configs you need to restart waybar, you can do it by following command:
> 
> ```ruby
> killall -SIGUSR2 waybar
> ```

the some not work

**Comment by yousseffjel** [comment]
i try something i put 

    "battery": {
        "bat": "BAT1",
        "states": {
            "good": 95,
            "warning": 30,
            "critical": 20
        },
        "format": "{icon} {capacity}%",
        "format-charging": " {capacity}%",
        "format-plugged": " {capacity}%",
        "format-alt": "{time} {icon}",
        "format-icons": ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
    }, 

in battery.jsonc
and 

    "battery#bat2": {
        "bat": "BAT2",
        "states": {
            "good": 95,
            "warning": 30,
            "critical": 20
        },
        "format": "{icon} {capacity}%",
        "format-charging": " {capacity}%",
        "format-plugged": " {capacity}%",
        "format-alt": "{time} {icon}",
        "format-icons": ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
    },

in battery2.jsonc
its show to in waybar but not exact the capacity i try change BAT1 and BAT2 and try put BAT0 and not work 
![image](https://github.com/prasanthrangan/hyprdots/assets/37506107/a3d6ed62-fbf4-4cc3-bb22-8470cc40a479)

**Comment by kRHYME7** [comment]
```  killall waybar && waybar > /dev/null & disown ``` use this to restart waybar on terminal.

**Comment by yousseffjel** [comment]
> killall waybar && waybar > /dev/null & disown

i restart waybar and the same not work

**Comment by kRHYME7** [comment]
Let's just Idetify first what battery name you have on your system to do that please send  the output for 

``` ls /sys/class/power_supply/ ``` we should see two BAT values 

Now I suggest modifying the ```  ~/.config/waybar/modules/battery.jsonc  ``` Adding the other battery object but "bat" should have a name base on  the output ``` ls /sys/class/power_supply/ ``` 
here is the new battery.jsonc remember to modify the bat part. 
https://gist.github.com/kRHYME7/d7523656976c06a85eaf341396396dc0


now add the new battery on your waybar control by editing 
 ``` ~/.config/waybar/config.ctl ```
 like this depends on what your configs have just focus on the battery part here ```  1|30|bottom|( custom/power battery battery#bat2 )( hyprland/workspaces hyprland/window )|( wlr/taskbar mpris )|( tray )( network bluetooth pulseaudio pulseaudio#micrphone )( clock custom/updates custom/audio_idle_inhibitor )  ```




To restart waybar 
```  killall waybar && waybar > /dev/null & disown ```

**Comment by yousseffjel** [comment]
> cat /sys/class/power_supply/BAT*/capacity

thank you so much its work now


![image](https://github.com/prasanthrangan/hyprdots/assets/37506107/f1c99d84-49c0-40d2-b615-785c3acf926c)

![image](https://github.com/prasanthrangan/hyprdots/assets/37506107/0ef8b067-2e4f-49ec-8922-e233f781b49c)

**Comment by kRHYME7** [comment]
We cannot add this to the repo yet though. 
Can you try to remove both the lines specifying "bat"? the whole line. Maybe waybar has a way to automatically identify. If this works then we can PR these modifications.

**Comment by yousseffjel** [comment]
> We cannot add this to the repo yet though. Can you try to remove both the lines specifying "bat"? the whole line. Maybe waybar has a way to automatically identify. If this works then we can PR these modifications.

no  its not working

**Comment by kRHYME7** [comment]
how about removing the first "bat" ?

**Comment by yousseffjel** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/37506107/32d2b47a-45f0-44e9-a9af-1942f160abd4)

![image](https://github.com/prasanthrangan/hyprdots/assets/37506107/fbb99380-e46a-46c9-9f60-9d9fab7e9beb)

i remove BAT0

**Comment by kRHYME7** [comment]
So it's not working, I guess let's just leave this as a preference for now. Will add this to the FAQs/ Tips and Tricks page soon. Thanks for your cooperation!

**Comment by kRHYME7** [comment]
Maybe we could close this  issue for now and maybe if issues occur regarding this you could open a discussion as this is not yet an issue on the repo. Cheers

**Comment by yousseffjel** [comment]
Yes sure you can close this issue, it's work now good for me, and lest think it's try to make it good with laptop I talk about battery life and some stuff like that and thanks again

**Comment by kRHYME7** [comment]
Maybe we could do some modular way to do these laptop tweaks. You could also use archlinux tweaking tool  to modify yours but be aware of the changes you made.  I don't personally use it either but it really is good.

**Comment by yousseffjel** [comment]
Thanks for help

**Comment by kRHYME7** [comment]
At your convenience can you test this?  #699
