### ISSUE TITLE
Please warn people that this installer will change your whole system and it is not campatible with non-systemd distros

### ISSUE THREAD

**Issue by Faez-Ansari** [prasanthrangan/hyprdots#473]
I am using Artix linux with openrc and didn't know the script uses systemctl or it would change my grub settings. I ran the installer and after installing all the packages and changing fonts and configs and everything, it crashed because of service manager incompatibility and I couldn't boot into my laptop anymore and had to learn how to chroot and reconfigure grub to get it back. It took so many hours from me. I see in the Readme that this might not work for all arch repos but it shouldn't deal this much damage at least add an option to opt out of grub setting or any similiar type of setting. Please add more explanation regarding this so others don't experience what I experienced. Thanks.

**Comment by Balssh** [comment]
To be honest it does say about the grub config thing (you can kind of opt out of it by tweaking the files before running the installer). Also you are now able to update the readme with your findings so you can help out others that could fall into the same problems.

**Comment by Faez-Ansari** [comment]
> To be honest it does say about the grub config thing (you can kind of opt out of it by tweaking the files before running the installer). Also you are now able to update the readme with your findings so you can help out others that could fall into the same problems.

Good point. I have never contributed in open-source so that sounds like a good oppurtunity.

**Comment by prasanthrangan** [comment]
Oh, there should be backup grub config created, which you can chroot and revert back...

Can you please let me know which grub option broke it... Is it nvidia drm loading?

**Comment by Balssh** [comment]
> > To be honest it does say about the grub config thing (you can kind of opt out of it by tweaking the files before running the installer). Also you are now able to update the readme with your findings so you can help out others that could fall into the same problems.
> 
> Good point. I have never contributed in open-source so that sounds like a good oppurtunity.

Yup, please try and do a PR and someone will review it. It's fun to contribute!

**Comment by prasanthrangan** [comment]
readme has been updated... hope that helps!
