### ISSUE TITLE
Rofi Launcher scaling issues @ 4K

### ISSUE THREAD

**Issue by HWG90** [prasanthrangan/hyprdots#474]
Launching rofi with the keyboard shortcuts creates an unusable (but oddly aesthetic) rofi launcher. 
![231110_17h59m46s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/40903496/42b6d8d5-3521-470f-8c53-6c546e5c5fbe)

Fresh install of hyprdots on a new Arch install.

Other styles seem fine though, besides the default one.

**Comment by HWG90** [comment]
I see that this is in known issues already. Closing this.

**Comment by prasanthrangan** [comment]
Hi, please adjust the width in this file to fix it

https://github.com/prasanthrangan/hyprdots/blob/9a61feed0caa40fa0b58b8534729c9317bdac066/Configs/.config/rofi/styles/style_1.rasi#L46
