### ISSUE TITLE
New Theme

### ISSUE THREAD

**Issue by 4Gettt25** [prasanthrangan/hyprdots#48]
Hey firstly, great work love seeing the progress everytime I lock at your page!

I'm currently trying to make a gruvbox theme config and wanted to ask for some tips, espacially with qt5ct as I can't get behind the other configs for qt5ct.

**Comment by prasanthrangan** [comment]
Hi, Thank you so much!

Ya the qt5ct colors are pain to work with... It works a bit different, as the colors from this config `~/.config/qt5ct/colors/<theme>.conf` is not directly visible in QT apps, it rather looks like composite to the kvantum colors `~/.config/Kvantum/<theme>/<theme>.svg` and `~/.config/Kvantum/<theme>/<theme>.kvconfig`.

So i just go by trial and error by replacing these colors `<col1>` ... `<col15>` in this template -

```
[ColorScheme]
active_colors=#<col1>69, #<col3>ef, #<col2>85, #<col4>93, #<col5>cc, #<col6>b0, #<col1>69, #<col1>69, #<col1>69, #<col7>f5, #<col3>ef, #<col8>a1, #<col9>f5, #<col7>f5, #<col12>fd, #<col13>53, #<col7>f5, #<col1>69, #<col14>e8, #<col1>69, #<col15>a1
disabled_colors=#<col2>85, #<col3>ef, #<col2>85, #<col4>93, #<col5>cc, #<col6>b0, #<col2>85, #<col2>85, #<col2>85, #<col7>f5, #<col3>ef, #<col8>a1, #<col6>b0, #<col11>77, #<col12>fd, #<col13>53, #<col7>f5, #<col1>69, #<col14>e8, #<col1>69, #<col15>a1
inactive_colors=#<col1>69, #<col3>ef, #<col2>85, #<col4>93, #<col5>cc, #<col6>b0, #<col1>69, #<col1>69, #<col1>69, #<col7>f5, #<col3>ef, #<col8>a1, #<col10>da, #<col2>85, #<col12>fd, #<col13>53, #<col7>f5, #<col1>69, #<col14>e8, #<col1>69, #<col15>a1
```

**Comment by 4Gettt25** [comment]
okay I'll try that thank you

**Comment by 4Gettt25** [comment]
okay I got everything working and it looks pretty good except dolphin but I can't figure out which files needs to be edited for dolphin.
![swappy-20230720_221844](https://github.com/prasanthrangan/hyprdots/assets/126004052/3a77d96e-8bc1-4b16-8474-31f80accbddb)

As you can see the text's in dolphin are black and also I would like to change the color from this black/dark blue to more of a brownish color.

Thanks in advance and keep up the good work!!

**Comment by 4Gettt25** [comment]
Okay I've found my error, I overread the kvantummanager --Set "theme" line in the .conf file

**Comment by prasanthrangan** [comment]
> okay I got everything working and it looks pretty good except dolphin but I can't figure out which files needs to be edited for dolphin.

Wow, your gruvbox theme looks great with warm/cozy vibe.

> As you can see the text's in dolphin are black and also I would like to change the color from this black/dark blue to more of a brownish color.
>
> Edit: Okay so after investigating a bit I see that it is kvantum aka that in the kvantum.kvconfig it says: [General] theme=Catppuccin-Mocha

Once you have the kvantum theme files `~/.config/Kvantum/gruvbox/gruvbox.svg` and `~/.config/Kvantum/gruvbox/gruvbox.kvconfig` created, please update the hypr theme file `~/.config/hypr/themes/gruvbox.conf` as well.

**Comment by 4Gettt25** [comment]
Ah yes, I've updated my ~/home/user/.config/hypr/themes/gruvbox-dark.conf file and now kvantum works the Text on the right is still black but I'll look into that after work

**Comment by 4Gettt25** [comment]
I couldn't get anything to work after 5 hours so I changed file manager to nemo and now everything works LMAO

**Comment by 4Gettt25** [comment]
I've actually created a folder in ~/.config/gtk-3.0 called colors with all 
`[Settings]
gtk-theme-name=Catppuccin-Latte 
gtk-icon-theme-name=Tela-circle-grey
gtk-font-name=Cantarell 10
gtk-cursor-theme-name=Bibata-Modern-Ice
gtk-cursor-theme-size=20
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=0
gtk-menu-images=0
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull
gtk-xft-rgba=rgb
gtk-application-prefer-dark-theme=0`

and changed the gtk-theme-name to the corresponding theme and put 
the following in the themeswitch.sh: 
`ln -fs $ConfDir/gtk-3.0/colors/${ThemeSet}.ini $ConfDir/gtk-3.0/settings.ini`

which works but I would have to close vscode for it to show the change, also I've noticed that when chaning themes vscode doesnt automatically change the color-scheme. For some themes it works e.g. from the gruvbox-dark theme to catppuccin-mocha but when chaning back to gruvbox-dark it stays at catppuccin-mocha, any Idea why it behaves like that?

**Comment by prasanthrangan** [comment]
Oh, for vs code please check the `~/.config/Code/User/settings.json` file when you change theme, does `workbench.colorTheme` value change to current theme?

If you have installed the gruvbox vs code theme as extension, then please set the theme name `gruvbox-dark`  in 
`~/.vscode/extensions/<theme>/package.json` and `~/.vscode/extensions/<theme>/themes/<theme>.json`
