### ISSUE TITLE
Stuck in login page 

### ISSUE THREAD

**Issue by Xito137** [prasanthrangan/hyprdots#481]
I just installed everything, it all went fine, at the end it booted in hyprland, i put my user and password, it opens, so i decide to reboot to make sure everything is ok. I reboot, i try to login again but when i do so, it flashes a black screen for 2/3 seconds and then goes back to login screen. What did i do wrong?
I'm using a desktop pc with an RTX 3060

**Comment by kRHYME7** [comment]
Can You try to run hyprland on your TTY? 
``` ctrl + alt + 3 ``` login and try to see if you could launch Hyprland there.

**Comment by prasanthrangan** [comment]
Hi, few things you can try -
1. from TTY please check `cat /proc/cmdline` it should show `nvidia-drm.modset=1` as boot image parameter
2. try running `nvidia-smi` from TTY and check if it gives you the gpu info
3. If you have igpu then try uninstalling the nvidia dkms drivers

**Comment by Xito137** [comment]
> Can You try to run hyprland on your TTY? `ctrl + alt + 3` login and try to see if you could launch Hyprland there.

just tried and nope, it doesn't, it says Couldn't connect to socket /run/seatd.sock: No such file or directory

![PXL_20231112_114735310](https://github.com/prasanthrangan/hyprdots/assets/94203067/a38586a3-529f-4e6f-b315-b1935bb78e18)

**Comment by Xito137** [comment]
> Hi, few things you can try -
> 
> 1. from TTY please check `cat /proc/cmdline` it should show `nvidia-drm.modset=1` as boot image parameter
> 2. try running `nvidia-smi` from TTY and check if it gives you the gpu info
> 3. If you have igpu then try uninstalling the nvidia dkms drivers

I just tried and no, it doesn't show nvidia-drm.modeset=1, but if i run nvidia-smi it's all fine

**Comment by prasanthrangan** [comment]
> I just tried and no, it doesn't show nvidia-drm.modeset=1, but if i run nvidia-smi it's all fine

oh, thats the problem then... are you using grub as boot loader?

So you could try the early loading method as mentioned in arch wiki [here](https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting)
there is also a script `~/Hyprdots/Scripts/.old/install_mod.sh` that does it, so you can try running it

**Comment by Xito137** [comment]
> > I just tried and no, it doesn't show nvidia-drm.modeset=1, but if i run nvidia-smi it's all fine
> 
> oh, thats the problem then... are you using grub as boot loader?
> 
> So you could try the early loading method as mentioned in arch wiki [here](https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting) there is also a script `~/Hyprdots/Scripts/.old/install_mod.sh` that does it, so you can try running it

nope, im using systemd-boot... is there a way to fix?

**Comment by Xito137** [comment]
Nvm, i found how to do that in systemd-boot, now it works perfectly, you can close the issue.

for everyone that finds himself in this situation, just do
nano /boot/loader/entries/<name_of_your_entry>.conf
and in the line that says "options" at the end.
it should look like this:

title   Arch Linux
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options root=PARTUUID=your_root_partition_uuid rw quiet nvidia-drm.modeset=1

**Comment by prasanthrangan** [comment]
yes, please add `nvidia_drm.modeset=1` to boot options in `/boot/loader/entries/arch.conf` to enable it from systemd-boot
refer [this](https://wiki.archlinux.org/title/Kernel_parameters#systemd-boot) for more details.

**Comment by prasanthrangan** [comment]
great thanks, I'll close this!
