### ISSUE TITLE
Anime girl on splash screen

### ISSUE THREAD

**Issue by YasirRWebDesigner** [prasanthrangan/hyprdots#488]
Hi, I would know how can I remove the anime girl that sometimes shows up on the splash screen of Hyprland. I looked around and found this thread on Reddit. I am okay with recompiling is needed. [Hyprland Motto](https://www.reddit.com/r/hyprland/comments/12lzrn4/where_does_the_motto_on_the_splash_screen_comes/) Also, Can I use my own wallpapers as well, so the motto is visible on them?

**Comment by zer0cha0s** [comment]
Hello there, a fix was provided in #275.
