### ISSUE TITLE
phpstorm/webstorm fullscreen

### ISSUE THREAD

**Issue by imhatep** [prasanthrangan/hyprdots#492]
The window does not go to full screen, it immediately returns, is there a solution to the problem?

**Comment by Balssh** [comment]
Without more context we can't really help. It suggest the good old "google it" first.

**Comment by imhatep** [comment]
Sry my fault 
https://youtu.be/MpThNdU93Ww
i mean alt+enter

**Comment by prasanthrangan** [comment]
Hi @imhatep , is there any `windowrule` set for this application in any of the `~/.conf/hypr/*.conf` files?
can you please try with the default autogenerated hyprland config, just rename `~/.conf/hypr/hyprland.conf` file..

**Comment by imhatep** [comment]
> Hi @imhatep , is there any `windowrule` set for this application in any of the `~/.conf/hypr/*.conf` files? can you please try with the default autogenerated hyprland config, just rename `~/.conf/hypr/hyprland.conf` file..

for default conf i added a full screen hotkey, but same issue

**Comment by prasanthrangan** [comment]
Oh, so its not an issue with the config file... 
could you check hyprland log file for errors - `~/.hyprland/*`
you could also try launching the app from terminal and try to fullscreen and check for errors in terminal.

**Comment by imhatep** [comment]
`--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Vaxry is going to be upset.

Hyprland received signal 6 (Aborted)

Version: 49597688e975c23b4f3bb53e77617ed3cd1e4937
Tag: v0.32.3-16-g49597688

System info:
	System name: Linux
	Node name: archlinux
	Release: 6.6.1-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:38 +0000

GPU:
	27:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7) (prog-if 00 [VGA controller])


os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://bugs.archlinux.org/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	


Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x62) [0x56479b950052]
		??
		??:0
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x581) [0x56479b91fa21]
		??
		??:0
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x43) [0x56479b8b5c33]
		??
		??:0
	#3 | /usr/lib/libc.so.6(+0x3e710) [0x7f2e1b45c710]
		??
		??:0
	#4 | /usr/lib/libc.so.6(+0x8e83c) [0x7f2e1b4ac83c]
		??
		??:0
	#5 | /usr/lib/libc.so.6(raise+0x18) [0x7f2e1b45c668]
		??
		??:0
	#6 | /usr/lib/libc.so.6(abort+0xd7) [0x7f2e1b4444b8]
		??
		??:0
	#7 | /usr/lib/libc.so.6(+0x27390) [0x7f2e1b445390]
		??
		??:0
	#8 | /usr/lib/libc.so.6(+0x987b7) [0x7f2e1b4b67b7]
		??
		??:0
	#9 | /usr/lib/libc.so.6(+0x9aa84) [0x7f2e1b4b8a84]
		??
		??:0
	#10 | /usr/lib/libc.so.6(free+0x73) [0x7f2e1b4bb353]
		??
		??:0
	#11 | Hyprland(+0xbdfef) [0x56479b8cefef]
		??
		??:0
	#12 | Hyprland(+0xbf250) [0x56479b8d0250]
		??
		??:0
	#13 | Hyprland(_ZN11CCompositorD1Ev+0x8fe) [0x56479b8bc00e]
		??
		??:0
	#14 | Hyprland(main+0x889) [0x56479b89ee39]
		??
		??:0
	#15 | /usr/lib/libc.so.6(+0x27cd0) [0x7f2e1b445cd0]
		??
		??:0
	#16 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f2e1b445d8a]
		??
		??:0
	#17 | Hyprland(_start+0x25) [0x56479b8b3225]
		??
		??:0


Log tail:
[LOG] Callback 56479db1c6b8 -> 56479db1c6b0, Keyboard removed.
[LOG] Callback 56479db1c650 -> 56479db1c648, Keyboard removed.
[LOG] Callback 56479db1f0c8 -> 56479db1f0c0, Mouse removed.
[LOG] Callback 56479de86718 -> 56479de86710, Mouse removed.
[LOG] Callback 56479de90618 -> 56479de90610, Mouse removed.
[LOG] Callback 56479db954f8 -> 56479db954f0, Mouse removed.
[LOG] Callback 56479e1077b8 -> 56479e1077b0, textInput removed.
[LOG] Callback 56479e107750 -> 56479e107748, textInput removed.
[LOG] Callback 56479e1076e8 -> 56479e1076e0, textInput removed.
[LOG] Callback 56479e107680 -> 56479e107678, textInput removed.
[LOG] Callback 56479e0f66e8 -> 56479e0f66e0, textInput removed.
[LOG] Callback 56479e0f6680 -> 56479e0f6678, textInput removed.
[LOG] Callback 56479e0f6618 -> 56479e0f6610, textInput removed.
[LOG] Callback 56479e0f65b0 -> 56479e0f65a8, textInput removed.
[LOG] Callback 56479e29e508 -> 56479e29e500, textInput removed.
[LOG] Callback 56479e29e4a0 -> 56479e29e498, textInput removed.
[LOG] Callback 56479e29e438 -> 56479e29e430, textInput removed.
[LOG] Callback 56479e29e3d0 -> 56479e29e3c8, textInput removed.
[LOG] Callback 56479dc20c68 -> 56479dc20c60, textInput removed.
[LOG] Callback 56479dc20c00 -> 56479dc20bf8, textInput removed.
[LOG] Callback 56479dc20b98 -> 56479dc20b90, textInput removed.
[LOG] Callback 56479dc20b30 -> 56479dc20b28, textInput removed.
[LOG] Callback 56479e302328 -> 56479e302320, textInput removed.
[LOG] Callback 56479e3022c0 -> 56479e3022b8, textInput removed.
[LOG] Callback 56479e302258 -> 56479e302250, textInput removed.
[LOG] Callback 56479e3021f0 -> 56479e3021e8, textInput removed.
[LOG] Callback 56479dd56258 -> 56479dd56250, textInput removed.
[LOG] Callback 56479dd561f0 -> 56479dd561e8, textInput removed.
[LOG] Callback 56479dd56188 -> 56479dd56180, textInput removed.
[LOG] Callback 56479dd56120 -> 56479dd56118, textInput removed.
[LOG] Callback 56479ddfc638 -> 56479ddfc630, textInput removed.
[LOG] Callback 56479ddfc5d0 -> 56479ddfc5c8, textInput removed.
[LOG] Callback 56479ddfc568 -> 56479ddfc560, textInput removed.
[LOG] Callback 56479ddfc500 -> 56479ddfc4f8, textInput removed.
[LOG] Callback 56479dc0d3a8 -> 56479dc0d3a0, textInput removed.
[LOG] Callback 56479dc0d340 -> 56479dc0d338, textInput removed.
[LOG] Callback 56479dc0d2d8 -> 56479dc0d2d0, textInput removed.
[LOG] Callback 56479dc0d270 -> 56479dc0d268, textInput removed.
[LOG] Callback 56479dd59008 -> 56479dd59000, textInput removed.
[LOG] Callback 56479dd58fa0 -> 56479dd58f98, textInput removed.
[LOG] Callback 56479dd58f38 -> 56479dd58f30, textInput removed.
[LOG] Callback 56479dd58ed0 -> 56479dd58ec8, textInput removed.
[LOG] Callback 56479ddf7668 -> 56479ddf7660, textInput removed.
[LOG] Callback 56479ddf7600 -> 56479ddf75f8, textInput removed.
[LOG] Callback 56479ddf7598 -> 56479ddf7590, textInput removed.
[LOG] Callback 56479ddf7530 -> 56479ddf7528, textInput removed.
[LOG] Callback 56479daa3858 -> 56479daa3850, textInput removed.
[LOG] Callback 56479daa37f0 -> 56479daa37e8, textInput removed.
[LOG] Callback 56479daa3788 -> 56479daa3780, textInput removed.
[LOG] Callback 56479daa3720 -> 56479daa3718, textInput removed.
`
and phpstorm starting via terminal 

> phpstorm .
> [0.003s][warning][cds] Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "com.intellij.util.lang.PathClassLoader"). To use archived non-system classes, this property must not be set
> CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
> WARNING: A Java agent has been loaded dynamically (/tmp/byteBuddyAgent13904138631151899254.jar)
> WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
> WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
> WARNING: Dynamic loading of agents will be disallowed by default in a future release
> 2023-11-18 15:52:39,448 [    447]   WARN - #c.i.o.e.i.FontFamilyServiceImpl - no such method: sun.font.Font2D.getTypographicFamilyName()String/invokeVirtual
> java.lang.NoSuchMethodException: no such method: sun.font.Font2D.getTypographicFamilyName()String/invokeVirtual
> 	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:915)
> 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:994)
> 	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3750)
> 	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2767)
> 	at com.intellij.util.MethodHandleUtil.getPublicMethod(MethodHandleUtil.kt:21)
> 	at com.intellij.openapi.editor.impl.FontFamilyServiceImpl.getFont2dMethod(FontFamilyServiceImpl.java:247)
> 	at com.intellij.openapi.editor.impl.FontFamilyServiceImpl.<clinit>(FontFamilyServiceImpl.java:45)
> 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
> 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
> 	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
> 	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
> 	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
> 	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
> 	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:63)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
> 	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
> 	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:21)
> 	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:185)
> 	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
> 	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
> 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
> 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
> 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:180)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService$suspendImpl(ComponentManagerImpl.kt:1162)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService(ComponentManagerImpl.kt)
> 	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invokeSuspend(ComponentManagerImpl.kt:1146)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
> Caused by: java.lang.NoSuchMethodError: 'java.lang.String sun.font.Font2D.getTypographicFamilyName()'
> 	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
> 	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
> 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:991)
> 	... 36 more
> 2023-11-18 15:52:39,455 [    454]   WARN - #c.i.o.e.i.FontFamilyServiceImpl - no such method: sun.font.Font2D.getTypographicSubfamilyName()String/invokeVirtual
> java.lang.NoSuchMethodException: no such method: sun.font.Font2D.getTypographicSubfamilyName()String/invokeVirtual
> 	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:915)
> 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:994)
> 	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3750)
> 	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2767)
> 	at com.intellij.util.MethodHandleUtil.getPublicMethod(MethodHandleUtil.kt:21)
> 	at com.intellij.openapi.editor.impl.FontFamilyServiceImpl.getFont2dMethod(FontFamilyServiceImpl.java:247)
> 	at com.intellij.openapi.editor.impl.FontFamilyServiceImpl.<clinit>(FontFamilyServiceImpl.java:46)
> 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
> 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
> 	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
> 	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
> 	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
> 	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
> 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
> 	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:63)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
> 	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
> 	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:21)
> 	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:185)
> 	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
> 	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
> 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
> 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
> 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
> 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:180)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService$suspendImpl(ComponentManagerImpl.kt:1162)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.preloadService(ComponentManagerImpl.kt)
> 	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invokeSuspend(ComponentManagerImpl.kt:1146)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
> Caused by: java.lang.NoSuchMethodError: 'java.lang.String sun.font.Font2D.getTypographicSubfamilyName()'
> 	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
> 	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
> 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:991)
> 	... 36 more
> 2023-11-18 15:52:39,463 [    462]   WARN - #c.i.o.e.i.FontFamilyServiceImpl - Couldn't access required runtime API, will fall back to basic logic of font selection
> 2023-11-18 15:52:39,905 [    904]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme Light - old: Light, new Light
> Info  | RdCoroutineScope          | 69:DefaultDispatcher-worker-41 | RdCoroutineHost overridden 
> 2023-11-18 15:52:42,185 [   3184]   WARN - #c.i.u.j.JBCefApp - JCefAppConfig.class is not from a JBR module, url: jar:file:/opt/phpstorm/lib/lib-client.jar!/com/jetbrains/cef/JCefAppConfig.class (Use JBR bundled with the IDE)
> Project service: vadym
> 2023-11-18 15:52:44,658 [   5657]   WARN - #c.i.o.a.i.ActionUpdater - 525 ms to grab EDT for ToolWindowHeader$2#getChildren@ToolwindowTitle (com.intellij.toolWindow.ToolWindowHeader$2)
> 2023-11-18 15:52:44,702 [   5701]   WARN - #c.i.o.a.i.ActionUpdater - 403 ms to grab EDT for EditorMarkupModelImpl$TrafficLightAction#update@EditorInspectionsToolbar (com.intellij.openapi.editor.impl.EditorMarkupModelImpl$TrafficLightAction)
> 2023-11-18 15:52:44,814 [   5813]   WARN - #c.i.i.s.p.i.BundledSharedIndexPostStartupActivity - Skipped 1 pre-built shared indexes: bundled-js-predefined-1d06a55b98c1-a7bc8b56ba54-JavaScript-PS-232.10072.32
> 2023-11-18 15:54:23,888 [ 104887]   WARN - #c.i.o.v.i.l.NativeFileWatcherImpl - unexpected node type: /tmp/.com.microsoft.Edge.7XDD2v/SingletonSocket, 49645
>

**Comment by imhatep** [comment]
no fullscreen errors

**Comment by imhatep** [comment]
@NeverALegend You are right, tried Rider EAP works fine

**Comment by prasanthrangan** [comment]
cool, looks like this is resolved!
