### ISSUE TITLE
Change Pokemon to Neofetch

### ISSUE THREAD

**Issue by ms-kneknew** [prasanthrangan/hyprdots#494]
Every time I start Kitty terminal, a pokemon appears there, I want to switch it to neofetch. I understand the internet but I don't know where Pokemon commands are written.

**Comment by T-Crypt** [comment]
You need to edit the .zshrc in your home directory 

1. Open a terminal 
2. nano .zshrc / or your favorite editor 
3. delete  `pokemon-colorscripts --no-title -r 1,3,6` on line 158 
4. add `neofetch` to that same line 
5. CRTL + X in nano and save changes

**Comment by prasanthrangan** [comment]
Hi, I'll close this as its already answered!
