### ISSUE TITLE
stuck

### ISSUE THREAD

**Issue by progb4atys** [prasanthrangan/hyprdots#499]
https://github.com/prasanthrangan/hyprdots/assets/131874894/c956a35d-5799-4d93-9389-e49799f4592f

Stucked here while installing the script, how to resolve this?

**Comment by OctavianOG** [comment]
Greetings @progb4atys  , when you were installing packages from AUR, the installer asked you "Proceed to review?", when you agree it'll show you PKGBUILD file, to exit it you just have to press <kbd>Q</kbd> or if you want to review a help screen you can press <kbd>H</kbd>.

The file viewer tool is named `less` if you want to search for a guide on how to use it.

**Comment by opticblu** [comment]
> Stucked here while installing the script, how to resolve this?

1. It's really important to read questions when asked; you're making changes to a running system (generally as root). If you're not sure, take a breath and Google it on your phone or something, it could-- no, it will-- save you from a lot of trouble now and will end up saving you time in the future
2. PROTIP: the Y is capitalized when it asks you the question because it's the default if you mindlessly push enter
3. Hit n when it asks you if you want to review
4. Profit

**Comment by progb4atys** [comment]
> Greetings @progb4atys , when you were installing packages from AUR, the installer asked you "Proceed to review?", when you agree it'll show you PKGBUILD file, to exit it you just have to press Q or if you want to view a help screen you can press H.
> 
> The file viewer tool is named [less](https://man.archlinux.org/man/less.1) if you want to search for a guide on how to use it.

Thanks it fixed my issue 
Sorry to bother you again but after proceeding with the installation i got 
error: failed retrieving file 'cmake-3.27.7-w...' from mirror.nxtgen.com : The requested url returned error: 404
error: failed .... 'cmake....' from mirror.sahil.world: the requested url returned error : 404


I tried VPNs but it dosen't fix that

**Comment by progb4atys** [comment]
> Greetings @progb4atys , when you were installing packages from AUR, the installer asked you "Proceed to review?", when you agree it'll show you PKGBUILD file, to exit it you just have to press Q or if you want to view a help screen you can press H.
> 
> The file viewer tool is named [less](https://man.archlinux.org/man/less.1) if you want to search for a guide on how to use it.

thanks
