### ISSUE TITLE
Which license are you sharing these files under?

### ISSUE THREAD

**Issue by Cu3PO42** [prasanthrangan/hyprdots#502]
Hi there,

thank you so much for sharing your dotfiles with the world. Your configurations look quite stunning! I'd love to use some bits and pieces in my own NixOS/Home-Manager configuration. Since these systems work quite differently from more standard distros such as Arch, I also expect to change lots of things.

Since you have shared your dotfiles and are accepting contributions, I hope this is fine with you. However, not specifying a license is roughly the same as saying 'all rights reserved'. In particular, I could not re-use parts of your configuration. I'd love if you could clarify and hopefully add a license! There's a variety of license options you could go with. I find [Choose A License](https://choosealicense.com) to be a good guideline for what's possible.

Thank you so much for your consideration!

**Comment by prasanthrangan** [comment]
Hi, Thank you so much for your support!
Please feel free to copy and modify as you like, I'll look into these License and add it to this repo..

There are requests for NixOS implementation as well, please refer #166.

**Comment by Cu3PO42** [comment]
I appreciate it! And thank you for referring me to that discussion, last I saw it, there hadn't been any activity yet. I'll definitely participate there!

**Comment by prasanthrangan** [comment]
this is done!

**Comment by Cu3PO42** [comment]
Thank you so much! GPLv3 is also the license I have chosen for my dotfiles.
