### ISSUE TITLE
Better style for clock and calendar

### ISSUE THREAD

**Issue by RAprogramm** [prasanthrangan/hyprdots#503]
![231116_17h50m31s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/70325462/3a1c9f46-1a64-4588-bcac-5c089cc476c4)
![231116_17h51m11s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/70325462/07e3ce32-42bd-4edb-ba05-74552106ed21)
do you like it?
i also have idea for network section.

**Comment by RAprogramm** [comment]
do you like it?

**Comment by Balssh** [comment]
One suggestion would be to restrict to +- one month from current one. This looks nice, albeit a bit cluttery.

**Comment by RAprogramm** [comment]
> One suggestion would be to restrict to +- one month from current one. This looks nice, albeit a bit cluttery.

do you mean too bright?  or a lot of color?  I can, for example, remove week numbers or use a color palette from the theme

**Comment by RAprogramm** [comment]
by the way, i already wrote the code

**Comment by RAprogramm** [comment]
![231118_14h14m41s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/70325462/4081b948-bb48-4c92-b378-432c408d1365)
![231118_14h14m59s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/70325462/a59e3ea3-b4f5-42b2-bc48-0c587b38707c)

how about this?

**Comment by prasanthrangan** [comment]
Hi, thank you so much bro... looks great!
for layout 2, I think its better to use short date format (`14:14 Sat, Nov 23`) as it will save some space for other modules

**Comment by RAprogramm** [comment]
> Hi, thank you so much bro... looks great!
> for layout 2, I think its better to use short date format (`14:14 Sat, Nov 23`) as it will save some space for other modules

I got you! I'll do it tomorrow

**Comment by prasanthrangan** [comment]
this is merged, thanks bro!
