### ISSUE TITLE
Refresh Rate

### ISSUE THREAD

**Issue by Zenbin-bash** [prasanthrangan/hyprdots#504]
how can i set my refresh rate?

**Comment by zer0cha0s** [comment]
Welcome @Zenbin-bash 

You can add your monitor(s) to  
`$HOME/.config/hypr/monitors.conf`

Here is my example:

`monitor = DP-1, 2560x1440@144, 0x0, 1`
`monitor = HDMI-A-1,2560x1080@60,0x1440, 1`

Refresh rate can be found after the @ symbol.

You can also read up about monitor set up here: 
https://wiki.hyprland.org/Configuring/Monitors/

Hope this helps 
Zer0

**Comment by Zenbin-bash** [comment]
> Welcome @Zenbin-bash 
> 
> You can add your monitor(s) to  
> `$HOME/.config/hypr/monitors.conf`
> 
> Here is my example:
> 
> `monitor = DP-1, 2560x1440@144, 0x0, 1`
> `monitor = HDMI-A-1,2560x1080@60,0x1440, 1`
> 
> Refresh rate can be found after the @ symbol.
> 
> You can also read up about monitor set up here: 
> https://wiki.hyprland.org/Configuring/Monitors/
> 
> Hope this helps 
> Zer0

Thank you broo

**Comment by prasanthrangan** [comment]
Hey, looks like this is resolved, so closing this!
