### ISSUE TITLE
padding issues on laptop

### ISSUE THREAD

**Issue by YasirRWebDesigner** [prasanthrangan/hyprdots#51]
Hi, First of all this is an amazing rice I have seen so far but I am facing some padding issues and I am not sure what to do as I am new to hyprland. First the lock screen looks like this 
![image](https://github.com/prasanthrangan/hyprdots/assets/32537564/8678ebb6-8ee9-406f-9000-97e071c93a52)
I tried to make some changes but nothing changed `monitor = DP-1, 1366x768@60, 0, 1`
 also wofi menu has also padding issues.
 
![image](https://github.com/prasanthrangan/hyprdots/assets/32537564/f763c03c-2581-44cf-98d2-1afc61d749b4)

the icons on waybar were also close but I increased the padding from 3 to 5px as for the lock menu and wofi menu not sure what to do
![image](https://github.com/prasanthrangan/hyprdots/assets/32537564/ffab5af6-07ff-43e3-99d1-5528594ab01b)

**Comment by prasanthrangan** [comment]
Hi, Thank you so much!

ya the rofi and lock menu scaling is broken for 1366x768 res, this is same as #43 
I'll be updating the configs to be dynamic, but in the meantime you can adjust these file manually for your res.

For Rofi, adjust these in `~/.config/rofi/themes/*.rasi`
```
	height:                      55%;
	width:                       45%;
```
For logout, adjust font size in `~/.config/wlogout/style.css` and padding in `~/.config/hypr/keybindings.conf` 
```
bind = $mainMod, backspace, exec, wlogout -b 2 -c 0 -r 0 -L 930 -R 930 -T 300 -B 300 --protocol layer-shell # logout menu
```

**Comment by prasanthrangan** [comment]
same as #43, closing this for now!
