### ISSUE TITLE
[Help]open app in a floating state by default

### ISSUE THREAD

**Issue by Asparkcn** [prasanthrangan/hyprdots#511]
am a Chinese user, so the Chinese input method is a must for me, and I installed Sogou Pinyin, but I encountered an embarrassing problem, as you can see in the picture below, the input method also takes up a huge  window, but it would be much better if the input method opens in a floating state by default, so I would like to ask how to set up the software to open in a floating state by default?  Could you help me? I will be very grateful.
![231117_23h02m51s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/125042452/15663fce-448b-42be-bb7c-d82fdb7a7a65)
![image](https://github.com/prasanthrangan/hyprdots/assets/125042452/c2cdc023-a833-4c66-8cfa-b0d5d18bc93b)

**Comment by T-Crypt** [comment]
@xiongjiangyan 

What is the software called? You can add it to the windowrules.conf 

`/.config/hypr/windowrules.conf`

at the bottom add a line for the chinese input software with its name like below!

`windowrulev2 = float,class:^(qt5ct)$`

**Comment by xiongjiangyan** [comment]
Thank you very much for your help, but maybe I'm just too stupid and I still haven't solved this problem.  I am using fcitx and got the Chinese input method by installing fcitx-sogoupinyin, but when I tried to write these two into the configuration as application names, I found that they were invalid. The following is the process of fcitx and sogoupinyin that I found.
![image](https://github.com/prasanthrangan/hyprdots/assets/125042452/a25581df-da2c-4514-80ac-3b8744b1a4b1)
![image](https://github.com/prasanthrangan/hyprdots/assets/125042452/39924e4a-99df-4b38-8894-8ed0c6137bc7)

**Comment by T-Crypt** [comment]
what is the command you put into terminal to run the program? that is the command you want to use in the ( ) for the float.

**Comment by xiongjiangyan** [comment]
Thank you very much for your help. I have resolved the issue of the input method opening in a floating state by default. However, I have encountered several new problems. Firstly, the window opens in the center by default, and I don't know how to set it to follow the mouse or ideally display it next to the input box. Secondly, when the input method window pops up, the focus switches to the input method, causing interruptions in typing. Thirdly, I need to disable the animation for the input method window.

**Comment by T-Crypt** [comment]
1. 
move [x] [y] | moves a floating window (x,y -> int or %, e.g. 20% or 100. You are also allowed to do 100%- for the right/bottom anchor, e.g. 100%-20). Additionally, you can also do cursor [x] [y] where x and y are either pixels or percent. Percent is calculated from the window’s size. Specify onscreen before other parameters to force the window into the screen (e.g. move onscreen cursor 50% 50%)
-- | --



</body>
</html>

2. 
nofocus | disables focus to the window  
-- | -- 
noinitialfocus | disables the initial focus to the window


</body>
</html>

3. 
noanim | disables the animations for the window
-- | --



</body>
</html>


So with that, here's examples below (Id play with the `move onscreen cursor` option to get it how you want)

1.  `windowrule = move onscreen cursor 50% 50% ,^(kitty)$ # moves kitty to 100 100`
2.  `windowrule =noinitialfocus,^(kitty)$  # no focus on kitty`
3. `windowrule = noanim,^(kitty)$ # disable animations`

**Comment by xiongjiangyan** [comment]
I really appreciate your help; it has almost perfectly solved my issues. However, I have a small question. Is it possible to set the reference point for moving the floating window to the position of the blinking cursor in the input box instead of the mouse? After all, the mouse position is not always accurate.

**Comment by xiongjiangyan** [comment]
ok，i will，thankyou
