### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by ArchBin** [prasanthrangan/hyprdots#516]
Hello Developer, how can I restore or reconfigure visual studion code due to its transparency, I updated it to visual-studio-code-bin

**Comment by imhatep** [comment]
visual-studio-code-bin is preinstalled on this config. If u talk about insiders-bin, there is class "Code - Insiders"
~/.config/hypr/windowrules.conf

windowrulev2 = opacity 0.90 0.80,class:^(Code - Insiders)$

**Comment by prasanthrangan** [comment]
Hi, please open vscode and then run `hyprctl clients` from terminal to get the window class -

```
Window 5586940cb6e0 -> Welcome - Hyprdots - Visual Studio Code:
	mapped: 1
	hidden: 0
	at: 10,10
	size: 1265,1028
	workspace: 2 (2)
	floating: 0
	monitor: 0
	class: Code
	title: Welcome - Hyprdots - Visual Studio Code
	initialClass: Code
	initialTitle: Visual Studio Code
	pid: 2372
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 1
```

**Comment by ArchBin** [comment]
Yoo thankk youu maannn

**Comment by Zenbin-bash** [comment]
> visual-studio-code-bin is preinstalled on this config. If u talk about insiders-bin, there is class "Code - Insiders"
> ~/.config/hypr/windowrules.conf
> 
> windowrulev2 = opacity 0.90 0.80,class:^(Code - Insiders)$
> 


can i do it in google chrome too?

**Comment by Zenbin-bash** [comment]
> Hi, please open vscode and then run `hyprctl clients` from terminal to get the window class -
> 
> ```
> Window 5586940cb6e0 -> Welcome - Hyprdots - Visual Studio Code:
> 	mapped: 1
> 	hidden: 0
> 	at: 10,10
> 	size: 1265,1028
> 	workspace: 2 (2)
> 	floating: 0
> 	monitor: 0
> 	class: Code
> 	title: Welcome - Hyprdots - Visual Studio Code
> 	initialClass: Code
> 	initialTitle: Visual Studio Code
> 	pid: 2372
> 	xwayland: 1
> 	pinned: 0
> 	fullscreen: 0
> 	fullscreenmode: 0
> 	fakefullscreen: 0
> 	grouped: 0
> 	swallowing: 0
> 	focusHistoryID: 1
> ```

can i do it in google chrome too?

**Comment by imhatep** [comment]
@Zenbin-bash yes u can

**Comment by prasanthrangan** [comment]
cool, i guess this can be closed!

**Comment by Zenbin-bash** [comment]
> cool, i guess this can be closed!

Yoo bro i can't find the class name of google chrome, you know what is class name of google chrome bro?

**Comment by imhatep** [comment]
@Zenbin-bash 
class: Google-chrome
