### ISSUE TITLE
Nvidia required for install?

### ISSUE THREAD

**Issue by skrekkugle** [prasanthrangan/hyprdots#517]
What happens if I install without an nvidia gpu? Should I edit something out from some configs beforehand?

**Comment by prasanthrangan** [comment]
Hi, no change is required... it will just skip the nvidia driver packages...

**Comment by h4or** [comment]
How to skip them if you have nvidia and want to keep using nouveau for example

**Comment by kRHYME7** [comment]
edit the ` ./global_ctl.sh `  (something that name) 
find the nvidia_detect part and make all ` return 1`  so instead of 0  all returns inside that function should return 1. This will make the script think you don't have nvidia

**Comment by kRHYME7** [comment]
or use the CLI to install it will ask to configure nvidia or not  run ` Hyde-install `
