### ISSUE TITLE
I guess we have breaking changes as of the moment. 

### ISSUE THREAD

**Issue by kRHYME7** [prasanthrangan/hyprdots#520]
Waybar, and dunst not updating...

**Comment by prasanthrangan** [comment]
Hey, whats the issue? any screenshot?
Its working fine in my system!

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/b40f5d90-658c-4fb3-a180-5dfe7add52a2)

**Comment by prasanthrangan** [comment]
ah oki, so wallbash change it is!

you'll have to regenerate the cache -
```
cd Hyprdots/Scripts
./create_cache.sh -f
```

**Comment by kRHYME7** [comment]
❯ ~/.config/hypr/scripts/testrunner.sh
ok
ok
cat: /home/khing/.config/dunst/Wall-Dcol.conf: No such file or directory
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
ok
ok
cat: /home/khing/.config/dunst/Wall-Dcol.conf: No such file or directory
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
ok
ok
cat: /home/khing/.config/dunst/Wall-Dcol.conf: No such file or directory
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
ok
ok
cat: /home/khing/.config/dunst/Wall-Dcol.conf: No such file or directory
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
WARNING: format_string %" is unknown.
ok
ok
^C

**Comment by kRHYME7** [comment]
> ah oki, so wallbash change it is!

you'll have to regenerate the cache -

cd Hyprdots/Scripts
./create_cache.sh -f


Thanks gonna try this now but it would take a while haha

**Comment by kRHYME7** [comment]
How About the waybar not updating after change theme?  
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/747b8c01-a000-42c6-be1d-e243d6fd2fff)

**Comment by prasanthrangan** [comment]
> How About the waybar not updating after change theme?

could you change theme from term -
```
~/.config/hypr/scripts/themeswitch.sh -n
```

**Comment by kRHYME7** [comment]
@prasanthrangan  Thank You !!! All is well now.

**Comment by kRHYME7** [comment]
How about we implement something like caching on first install, then  retaining swww wallpapers on following restore 
I will propose a PR  soon if this is not yet your priority.  Thanks for all this hardwork !
