### ISSUE TITLE
cp: cannot create regular file 'install_pkg.lst' : Permission denied 

### ISSUE THREAD

**Issue by FrostLynn** [prasanthrangan/hyprdots#521]
When I execute the `install.sh` using `./install.sh`, I encounter the following error: 

```
'cp: cannot create regular file 'install_pkg.lst': Permission denied'

```

Can you provide assistance in understanding why this is happening?

**Comment by OctavianOG** [comment]
Greetings @FrostLynn , the error you are encountering is basically telling you that the directory you are in does not have enough permissions to create/write files. To resolve this type of error, you should grant elevated permissions to the folder where your local hyprdots repository is located.

Steps to do so:
1. Open terminal <kbd>Super+T</kbd>
2. Run command that will grant elevated permission to folder
```ruby
sudo chmod a+rwx ~/PathToHyprdots
```
(Where `~/PathToHyprdots` is the path of the hyprdots directory that you should replace with your local hyprdots path, `a` means "all" (users) `+` means "add the following rights" and `rwx` means read, write and execute respectively)

If you want to get more info about folder/file permissions and attributes in Arch Linux here's the [wiki](https://wiki.archlinux.org/title/File_permissions_and_attributes)

**Comment by cassiofb-dev** [comment]
I'm also having the same issue. When I ran in my first machine this error did not appear, tried the said above but could not solve.

**Comment by OctavianOG** [comment]
@FrostLynn @cassiofb-dev , sorry for the confusion, there's also alternative command:
```ruby
sudo chmod 755 -R /PathToHyprdots
```
> [!IMPORTANT]
> You should replace `/PathToHyprdots` with your local path to hyprdots

If this doesn't work, I'm willing to provide my assistance in further troubleshooting:

Could you please provide output of the following command, from root directory where hyprdots located in (e.g. my hyprdots folder is located in `/home/hyprdots` directory, so if I were you, I would provide output of following command from `/home` directory):

```ruby
ls -l
```

**Comment by cassiofb-dev** [comment]
@OctavianOG thanks, yesterday I used this but with 777 instead of 755 but I think this will work too.

**Comment by OctavianOG** [comment]
@cassiofb-dev ,
I'm sorry, I was wrong when suggesting using `chmod a+rwx`, although it's not that dangerous as `chmod 777`

> [!CAUTION]
> please, be careful when using `chmod 777`, it can create vulnerabilities and pose a significant security risk to your system, because by doing so you're giving all three permission groups the ability to read,write and execute that file/directory. I suggest never use `chmod 777`
>
>`chmod a+rwx` : set the last 3 octals to 777, so it ensure that Owner, Group and Users have the "rwx" set. If there are additional bits in the first octal (setuid, setgid, and/or Sticky bit) it leaves them untouched. Think about it as a binary "or 00777".
>
>`chmod 777` : set the rights to 00777, so it ensure Owner, Group and Users have "rwx" set, AND NOTHING MORE. It also make sure the additional bits (setuid, setgid, and/or Sticky bit) are set to 0.
>
>So if you want to grant access to everyone to do everything(rwx), only if you don't have any other option, it'll be better to use `chmod a+rwx` instead of `chmod 777`, use it with caution and full understading of what you're doin. 
>
>But in general it's better to use `chmod 755`, because in that case only **owner** can read/write/execute, **group/others** can only read/execute

> [!IMPORTANT]
> Make sure you understand what you're doing with your system, check the [wiki](https://en.wikipedia.org/wiki/Chmod), [Arch Linux wiki](https://wiki.archlinux.org/title/File_permissions_and_attributes), [great explanation on askubuntu](https://askubuntu.com/questions/932713/what-is-the-difference-between-chmod-x-and-chmod-755) and any other useful source, before making such critically dangerous changes to your system

**Comment by T-Crypt** [comment]
Yeah I suggest never using 777 or a+rwx. 

Considering were using Arch linux that includes a laundry list of vulnerabilities that are found and updated constantly, if you want to make sure your PC is safe then I would suggest not changing permissions unless you deeply understand the risk.

**Comment by T-Crypt** [comment]
Can you please try running 

`Hyprdots/Scripts/install_pkg.sh` and post the output here?

This is the script responsible for handing the install_package.lst

You can view the code here:

https://github.com/prasanthrangan/hyprdots/blob/19fe3994034b1b5e44546d60e1d14642124893d6/Scripts/install.sh#L80-L104

**Comment by CazzJann** [comment]
Running the pkg.sh separately worked should I now run the original ./install.sh

**Comment by Juhayer-Al-Wasif** [comment]
I am on Endeavour OS Galileo. I had the same issue and `sudo chmod -R 777 ~/Downloads/hyprdots-main/` works
