### ISSUE TITLE
Installing Plasma 6 breaks QT and GTK themes.

### ISSUE THREAD

**Issue by IgLocoXD** [prasanthrangan/hyprdots#522]
Like the title says, installing Plasma 6 breaks both QT5/6 and GTK3/4 themes, here is both image about it.

To add; Changing themes also doesn't work, I tried every theme, and never fixes it

![image](https://github.com/prasanthrangan/hyprdots/assets/82992516/b31f7663-a29c-427c-8d9e-f1bbf5627664)
![image](https://github.com/prasanthrangan/hyprdots/assets/82992516/18a2b283-3097-4131-b06d-cf20b8e0bb13)

**Comment by kRHYME7** [comment]
Hi, I guess this is an expected issue. But, I want to clarify Do you want to keep/use Plasma 6 DE and Hyprland Compositor at the same time?

**Comment by prasanthrangan** [comment]
Hi, could you try installing and using qt5ct to set q6 theme?

**Comment by IgLocoXD** [comment]
> Hi, I guess this is an expected issue. But, I want to clarify Do you want to keep/use Plasma 6 DE and Hyprland Compositor at the same time?

Yea, specially because I want to use the HDR Alpha testing they have, it works really good.

**Comment by IgLocoXD** [comment]
> Hi, could you try installing and using `qt6ct` to set qt6 theme?

Yes! It worked... although now everything qt6 related looks bigger now.. but at least the theme worked!

**Comment by T-Crypt** [comment]
@IgLocoXD 

You probably need edit your QT6 conf, you can look at the QT5 conf in the .config directory for an example.

`~/.config/qt5ct/qt5ct.conf`

**Comment by prasanthrangan** [comment]
there are QT variables you can mess around with checkout the [wiki](https://wiki.hyprland.org/Configuring/Environment-variables/) as well as qt [docs](https://doc.qt.io/qt-6/highdpi.html)

**Comment by Enigma1309** [comment]
this is no longer an issues, as i also have plasma alongside of hyprland and it works now, maybe we can close this

**Comment by Enigma1309** [comment]
polkit has an separate issue and this issue was related to qt and gtk themes as a whole, which works on most apps (apart from polkit ) 
i think it's safe to close it now

**Comment by kRHYME7** [comment]
Okkk planning on closing some of the present issues,(Hyprdots features will be deprecated next week in favor of the new structure)
