### ISSUE TITLE
Right-click menu

### ISSUE THREAD

**Issue by abdul-kaium5** [prasanthrangan/hyprdots#528]
Right-click menu for Hyprland (or any other wayland compositor) like jgmenu i want to use because i use this menu in bspwm!

**Comment by T-Crypt** [comment]
@ab-kaium 

Hyprland doesn't natively support this -- but we can look into something like a rofi right click bind to have shortcuts to "keybinds", "themeswitch", "rofi style", and a few other options but I'm not sure it would give the same applicability that openbox and bspwm support!

I might look into xmenu or labwc 

[Labwc](https://github.com/labwc/labwc)

[Xmenu](https://github.com/phillbush/xmenu)

**Comment by Enigma1309** [comment]
shouldn't this be closed?
