### ISSUE TITLE
Volume buttons not working properly 

### ISSUE THREAD

**Issue by JayaDeep11** [prasanthrangan/hyprdots#532]
when i put it on mute i turn up the volume and it does't  unmute

**Comment by prasanthrangan** [comment]
Hi, this is not an issue.. when its in mute adjusting the volume should not unmute it

**Comment by kRHYME7** [comment]
Hi! @JayaDeep11  You  can  use this version of volume control instead 

https://raw.githubusercontent.com/kRHYME7/KhingDom/Khingdom/Configs/.config/hypr/scripts/volumecontrol.sh

This one  unmutes  if you press the volume up key also  if you reach  0 volume then it will notify muted 

You can replace your  ``` ~/.config/hypr/scripts/volumecontrol.sh ``` with this 

I  hope this helps

**Comment by JayaDeep11** [comment]
@prasanthrangan  okay bro
