### ISSUE TITLE
Problem with Notifications (dunst)

### ISSUE THREAD

**Issue by lnagler1** [prasanthrangan/hyprdots#542]
Dunst does not show icons, and is openning more than one notification as example for volume controle
![image](https://github.com/prasanthrangan/hyprdots/assets/92120753/677b1ed5-61f2-4d1b-88fa-8684cbef9894)

**Comment by kRHYME7** [comment]
Hi  @Inagler Assuming that you are up to date with th latest commit, would you mind sharing the output for 
``` ps aux | grep -E 'dunst|notification-daemon' ```  .  I can replicate this error but using swaync daemon.

**Comment by lnagler1** [comment]
> Hi @inagler Assuming that you are up to date with th latest commit, would you mind sharing the output for
> 
> ```
>  ps aux | grep -E 'swaync|notification-daemon'
> ps aux | grep -E 'dunst|notification-daemon'
>  ```  .  I can replicate this error but using swaync daemon. 
> ```

lukas     292523  0.0  0.0   6900  2460 pts/1    S+   11:18   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox -E swaync|notification-daemon
lukas     292531  0.0  0.0   6900  2516 pts/1    S+   11:18   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox -E dunst|notification-daemon

**Comment by kRHYME7** [comment]
Thanks , Can you run ``` dunst ``` on the terminal  also what is the output. 

Have you tried pulling the latest commits  ?

**Comment by lnagler1** [comment]
CRITICAL: [dbus_cb_name_lost:1152] Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'mako' with PID '1777'.

And yes i already pulled the latest commits

**Comment by kRHYME7** [comment]
ow I guess you are running mako on startup not dunst. I do not know how to run mako but can you try to run 

```  killall mako && dunst ``` then try to control your volume.   


I can replicate you issue now, Please disable mako or you can ``` paru -Rns mako ``` to delete it if you have no use for it 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/1f4e961f-07a5-4f20-bfa1-43d5ff02f128)

**Comment by lnagler1** [comment]
> ow I guess you are running mako on startup not dunst. I do not know how to run mako but can you try to run
> 
> ` killall mako && dunst` then try to control your volume. If the volume looks right we should remove mako.
> 
> I can replicate you issue now, Please disable mako or you can `paru -Rns mako` to delete it if you have no use for it ![image](https://user-images.githubusercontent.com/53417443/285464180-1f4e961f-07a5-4f20-bfa1-43d5ff02f128.png)

That worked for me.
Thank you!

**Comment by inagler** [comment]
Hey people, you got me confused but I'm glad you solved your issues!

**Comment by kRHYME7** [comment]
You got me confused with both of your usernames also. Haha
