### ISSUE TITLE
After fresh install (nvidia gpu) and reboot second monitors disconnects

### ISSUE THREAD

**Issue by h4or** [prasanthrangan/hyprdots#544]
I installed script on minimal arch install  and everything worked fine. After reboot pc starts and second monitors loads in very low resolution (also with black bars bcs native is 1920 1080).
I tried rebooting again and then it didnt work anymore. I tried xrandr list monitors and it showes me only my primary monitor. But when i use hyprctl monitors it shows both but second one doesnt have all valuea provided, like monitor brand, resolution, and everything else that main does have while second doesnt.

**Comment by OctavianOG** [comment]
Greetings @ka1ry , could you provide your system's specifications?

**Comment by ka1ry** [comment]
> Greetings @ka1ry , could you provide your system's specifications?

CPU: I7 3770
GPU: GTX 1060 3GB
nuidia/545.29.02

As I said; I installed minimal arch, booted installed rice with install.sh script, everything started, both monitors worked, after reboot monitor that wasn't primary disconnected (it works on windows so problem is on arch). Now when I do xrandr list monitors it displays only one, but hyprctl monitors display both but the one that is diaconnected doesnt include all information.

**Comment by ka1ry** [comment]
Also, I am using hyprland (this rice) for 5 months now and problem happend yesterday when I updated nvidia graph. Version to latest. Before that I used 535.**.**

**Comment by ka1ry** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/80115301/6a702239-355d-4f89-86bb-f07a5ea181df)

DVI-D-1 is the one that makes problems.
![20231124_074919](https://github.com/prasanthrangan/hyprdots/assets/80115301/b3f87170-7ea7-415b-b9f9-b720237d75ab)
This monitor is main (HDMI)
![20231124_074922](https://github.com/prasanthrangan/hyprdots/assets/80115301/44245812-1d99-49a2-8838-5ceb90ef3c49)
This one in login starts like this
But after login:

![20231124_074936](https://github.com/prasanthrangan/hyprdots/assets/80115301/f9f62d77-cb23-43f0-95ce-fbad11147dbf)

**Comment by OctavianOG** [comment]
@ka1ry , could you try setting your monitors manually ?

You can do so by:
1. Open monitors.conf
```ruby
Sudo nano ~/.config/hypr/monitors.conf
```
2. Add your monitors as you prefer by following this official documentation [example](https://wiki.hyprland.org/Configuring/Monitors/)

**Comment by kRHYME7** [comment]
@ka1ry  Hello any progress on this ?

**Comment by ka1ry** [comment]
> @ka1ry  Hello any progress on this ? 

Hello after long time. I switched to another rice that day and totally forgot about this issue.

I installed arch again and installed hyprdots, waited for script to finish and everything worked fine.
But after reboot I still have same problems like before.
Tried setting up monitors.conf but nothing changes.

**Comment by kRHYME7** [comment]
Have you tried using ``` nwg-displays ``` or any GUI to help you set up the monitor? 

Did it only happen if your using this rices?

**Comment by ka1ry** [comment]
Its only with this rice

**Comment by kRHYME7** [comment]
This is the nvidia related envs.

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/06e4af66-7d4a-4bd9-af25-3d5d661413dc)




also ``` lsmod | grep nvidia ``` to check if nvidia drivers are correctly set

**Comment by ka1ry** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/80115301/2b3db19d-1cf4-4b32-9ee6-943f2ff16dc3)

![image](https://github.com/prasanthrangan/hyprdots/assets/80115301/c7425588-536a-4dd3-95ee-2df98eaf5a65)

![image](https://github.com/prasanthrangan/hyprdots/assets/80115301/32e63fa8-796c-4198-9191-daadc67b9165)

**Comment by ka1ry** [comment]
Just updated to 550 but still same problem

**Comment by kRHYME7** [comment]
Let's assume first that the ENVS are the issue.
Try to run ``` Hyprland -c  /usr/share/hyprland/hyprland.conf   ``` on the tty please.  
If ``` wlr-randr ``` gives same results, we can assume this is the configs issue.  But if not maybe this is due the nvidia installation and mode setting script.

**Comment by ka1ry** [comment]
![20240315_140410.jpg](https://github.com/prasanthrangan/hyprdots/assets/80115301/855d044d-5653-458a-8bde-07a3cfac01aa)

![20240315_140502.jpg](https://github.com/prasanthrangan/hyprdots/assets/80115301/b11378b7-40a7-4d91-b0ac-556108c46d16)

First img is hyprland in tty stuck on that screen

Second is another tty session

**Comment by kRHYME7** [comment]
>  First img is hyprland in tty stuck on that screen 

Oh ``` ctrl + Q ``` to launch kitty. ``` wlr-randr ``` Needs a Wayland compositor to be use IG.  

Or do you mean hyprland is not responding using the default configuration ?

**Comment by ka1ry** [comment]
I just didnt know def keybinds

![20240315_143534.jpg](https://github.com/prasanthrangan/hyprdots/assets/80115301/77b5b93b-127f-4b12-91f6-58c3d4f183d5)

![20240315_143548.jpg](https://github.com/prasanthrangan/hyprdots/assets/80115301/d9877952-25bd-4e20-8a32-f11de828fd9d)

Second works here but with loe res, and in xlrrandr is not detected properly as u can see

**Comment by ka1ry** [comment]
I don't remember. Some of them I just made and installed drivers normally. Used dwm mostly so nothing special. What about switching from dkms to normal nvidia?

**Comment by kRHYME7** [comment]
> Some of them I just made and installed drivers normally.

Owki, I am starting to think this is either Nvidia or wlroots/Hyprland issues. As you mentioned, this happened after you updated from 535xx driver. 

If you have DWM (X11 ), and it works well then might be wayland is not playing along with  your GPU. 

1 more hint I can think of is telling Hyprland to use your NVIDIA GPU. Here are the instructions. 
https://wiki.hyprland.org/configuring/multi-gpu/

**Comment by h4or** [comment]
> > Some of them I just made and installed drivers normally.
> 
> Owki, I am starting to think this is either Nvidia or wlroots/Hyprland issues. As you mentioned, this happened after you updated from 535xx driver.
> 
> If you have DWM (X11 ), and it works well then might be wayland is not playing along with your GPU.
> 
> 1 more hint I can think of is telling Hyprland to use your NVIDIA GPU. Here are the instructions. https://wiki.hyprland.org/configuring/multi-gpu/

Something is actually wrong with that LG monitor. as you can see on pictures it is connected to HDMI, after switching it’s the same. Basically on any linux distro I can’t use nvidia drivers.

[I have using custom edid for that monitor](https://forums.developer.nvidia.com/t/external-monitor-can-t-set-desired-resolution/300743) but stil didn’t work. i need to mentions everything was perfect on windows for example

**Comment by abenezerw** [comment]
Could you close as solved if you no longer have this issue. Thank you @h4or
