### ISSUE TITLE
Vscode theme not changing  

### ISSUE THREAD

**Issue by YuryenUcahh** [prasanthrangan/hyprdots#545]
i updated my config and now like this
![image](https://github.com/prasanthrangan/hyprdots/assets/51506997/f9d04e23-f531-4906-89ec-749aec4ab685)

**Comment by OctavianOG** [comment]
Greetings @YuryenUcahh , have you tried changing theme manually?

You can do this by so:
1. In Vscode firstly press <kbd>CTRL + K</kbd> after that press  <kbd>CTRL + T</kbd>
2. Select and apply the theme you want

**Comment by YuryenUcahh** [comment]
> Greetings @YuryenUcahh , have you tried changing theme manually?
> 
> You can do this by so:
> 
>     1. In Vscode firstly press CTRL + K after that press  CTRL + T
> 
>     2. Select and apply the theme you want

Yeah i can change manually like that but when i change desktop theme vdcode doesn't change with desktop

**Comment by kRHYME7** [comment]
Hi let's try to diagnose this 

run ``` code ~/.config/Code/User/settings.json ```

it should open it on vscode 
 watch out for line ```     "workbench.colorTheme": "Gruvbox Dark Medium", ``` the theme name depends on your themes , so if you change your  desktop theme this part should change. And can you provide screenshot while doing this ? 
 
 Thanks. 


example 


![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/d0204436-d6eb-4710-8ef6-9c17165a67f0)

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c7a458c7-997f-4a55-8630-1040d6aaeeac)

**Comment by YuryenUcahh** [comment]
https://github.com/prasanthrangan/hyprdots/assets/51506997/cc10d772-85a3-45d5-a004-f11b53e2f1b2





> Hi let's try to diagnose this
> 
> run `code ~/.config/Code/User/settings.json`
> 
> it should open it on vscode watch out for line ` "workbench.colorTheme": "Gruvbox Dark Medium",` the theme name depends on your themes , so if you change your desktop theme this part should change. And can you provide screenshot while doing this ?
> 
> Thanks.
> 
> example
> 
> ![image](https://user-images.githubusercontent.com/53417443/285327317-d0204436-d6eb-4710-8ef6-9c17165a67f0.png)
> 
> ![image](https://user-images.githubusercontent.com/53417443/285327513-c7a458c7-997f-4a55-8630-1040d6aaeeac.png)

**Comment by kRHYME7** [comment]
I remembered now to fix this there we're two approaches you can delete the extensions on your ``` ~/.vscode/extensions/ ``` that are related to the theme. 

another solution is you should edit your ``` ~/Hyprdots/Scripts/create_cache.sh  ```
on line 138 append force to reinstall those theme extensions
```            code --install-extension "${codex}" --force ```


You can do both to be more effective

After that run ./install.sh -r

**Comment by YuryenUcahh** [comment]
> I see this is due to the latest update a new implementation of vscode theme extensions.
> 
> Uninstall all extensions in your vscode related to the themes then After that run ./install.sh -r or ./create_cached.sh

It's working thanks.

**Comment by Kushagra0514** [comment]
> I see this is due to the latest update a new implementation of vscode theme extensions.
> 
> Uninstall all extensions in your vscode related to the themes then After that run ./install.sh -r or ./create_cached.sh

Where do I enter that command?
