### ISSUE TITLE
script gamelauncher.sh does not work.

### ISSUE THREAD

**Issue by guoyatingg** [prasanthrangan/hyprdots#549]
script gamelauncher.sh does not work. error "steam libary not found". script paths coincide with real ones, also there are no problems with permissions.
![231124_19h29m38s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/135554418/4f99778c-9e5b-49d2-b2c8-f648e64c97ac)

**Comment by OctavianOG** [comment]
Greetings @guoyatingg , you need to have installed games on your machine in order to display gamelauncher

**Comment by guoyatingg** [comment]
> Привет @guoyatingg, на вашем компьютере должны быть установлены игры, чтобы отобразить программу запуска игр.

Hey, I have this game (dark souls 2).

**Comment by prasanthrangan** [comment]
Hi, you should also pass 1-4 (for style) as a parameter to launch it -
`~/.config/hypr/scripts/gamelauncher.sh 1`
