### ISSUE TITLE
pirewire-jack and jack2 are in conflict 

### ISSUE THREAD

**Issue by CWE-119** [prasanthrangan/hyprdots#55]
everytime i run the script it ask me to remove one of pipewire-jack and jack2 and if i agree on removing the script ends and the installation is never complete 
i tried sudo pacman -R jack2 or pipewire-jack still same thing happens and i tried editing the pkg list removing all the pipewire after i run the script it automatically restores the items i removed from the list

**Comment by prasanthrangan** [comment]
Please try removing it from Scripts/custom_hypr.lst file.

**Comment by prasanthrangan** [comment]
old issue, will reopen if required
