### ISSUE TITLE
Themes Got Overlapped and doesnt work anymore!

### ISSUE THREAD

**Issue by Hackprince99** [prasanthrangan/hyprdots#550]
[So]() what happened was i was switching from cyberpunk theme to Mocha one
but it glitched itself out and now i have 2 cyberpunk theme sections and both of them aint working also 
Mocha theme disappeared
![231125_01h16m59s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/117996828/4f5e1bf1-f3ef-48b2-8544-9617ce2f759e)
![231125_01h17m14s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/117996828/f79b0369-abc3-4e77-91a2-36d7c1286c5e)

**Comment by kRHYME7** [comment]
Hello can you do some recaching?

~~~ ./create_cache.sh -f~~~ This is due to some config changes I guess.

**Comment by Hackprince99** [comment]
> ./create_cache.sh -f

Hello im kind of a newbie 
i dont really know what you mean by that

**Comment by kRHYME7** [comment]
Ow sorry, can I know when you  updated this configs?

**Comment by Hackprince99** [comment]
No i didnt but after you mentioned it 
i ran that command and it restored all the files and its now fixed 
Thank you

**Comment by Hackprince99** [comment]
Ok im getting this error 
with all the themes now
should i remove those codes to suppress the warning or are they important 
![Uploading 231125_13h54m14s_screenshot.png…]()

**Comment by kRHYME7** [comment]
Can you provide your github version ? ``` hyprctl version ```

**Comment by Hackprince99** [comment]
> Can you provide your hyprland version ? `hyprctl version`

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty ().
Tag: v0.30.0

flags: (if any)

**Comment by kRHYME7** [comment]
Okay you are using an older version of hyprland. I guess you can try to run ``` paru -Sy hyprland-git ``` to follow the latest version of hyprland.  But there  were  reports that hyprland-git wont compile as of now. let me know if this is the case. 

Instructions on how to update configs to latest commit. 

```
cd ~/Hyprdots/Scripts
git pull
./install -r
```

Warning this will reinstall your configs again 

Tips:  if you allready cached you wallpapers (part where it took time to load) you can edit your 

``` ~/Hyprdots/Scripts/restore_cfg.lst ```
Then Changed Y to N in the line ``` N|${HOME}/.config|swww|swww ```

**Comment by kRHYME7** [comment]
If hyprland git won't compile then follow this https://wiki.hyprland.org/Getting-Started/Installation/#manual-manual-build
