### ISSUE TITLE
Replace Hyprland-git with Hyprland.

### ISSUE THREAD

**Issue by MinimumADHD** [prasanthrangan/hyprdots#551]
Not much to describe, PKGBUILD from Hyprland-git was broken so new users who just want to quickly install can't fix it themselves, installing hyprland-git from AUR fails always, but installing hyprland doesn't.
Per reference.. read comments here: https://aur.archlinux.org/packages/hyprland-git

**Comment by kRHYME7** [comment]
So the Hyprland  official release is up to date now on arch. Last time it was not updated.

**Comment by kRHYME7** [comment]
Hi  i think the Hyprland-git is now fixed.

**Comment by prasanthrangan** [comment]
Hi, I just tried updating my system... the package seems to be fixed now!
