### ISSUE TITLE
'xterm-kitty': unknown terminal type.

### ISSUE THREAD

**Issue by Pranav-Saraswat** [prasanthrangan/hyprdots#552]
I'm facing this issue when I try to use clear commands in ssh I'm using virtual machine with ubuntu 22.04 in kitty terminal with ssh

**Comment by Pranav-Saraswat** [comment]
![231125_12h08m16s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/85411336/646b0a82-1928-41d9-a4f4-7a565ecb9ee2)

**Comment by zer0cha0s** [comment]
Hey there @Pranav-Saraswat 

I have faced the same issue and was able to resolve this by adding the following to my ~/.bashrc file.

`export TERM=xterm`

Once that is added run to reload the settings(or you can disconnect and reconnect to your SSH session) :

`source ~/.bashrc`

Clear command should be working fine after this.

Hope this helps. 
Zer0

**Comment by Pranav-Saraswat** [comment]
Yeah @T-Crypt this works but still if you try to fix this in script it would be great help

Thanks @zer0cha0s for solution
