### ISSUE TITLE
Hyprland-git error status 4

### ISSUE THREAD

**Issue by askareija** [prasanthrangan/hyprdots#553]
i have error when installing hyprdots, its said failed to install package:

-hyprland-git - exit status 4
-grimblast-git - exit status 8

Im using endeavourOS galilleo,

**Comment by kRHYME7** [comment]
Hi, This is not an issue with the configs but an issue with those packages. 
As of the moment maybe Hyprland-git gives errors and may be broken #551.   As of now maybe you can install an older version/ official version of hyprland  ``` paru -Sy hyprland ``` or ``` yay -Sy hyprland ```

as for grimblast as this is not really essential to the installation edit your ```  ~/Hyprdots/Scripts/custom_hypr.lst ``` 

and remove the line or comment out the line which tells ``` grimblast-git ```

**Comment by SergoGansta777** [comment]
In addition to that, I also have hyprland-nvidia-git - exit status 4

**Comment by kRHYME7** [comment]
hi for the hyprland errors  It was the PKGBUILD for Arch that caused this. I can advice that as of the moment  you can pull and compile hyprland on you system.
Follow this please 
https://wiki.hyprland.org/Getting-Started/Installation/#manual-manual-build

**Comment by prasanthrangan** [comment]
Hi, this is an issue with package itself please try manual build or the non git version

**Comment by SergoGansta777** [comment]
Regarding hyprland-nvidia-git, everything is fine now, the package has been updated

**Comment by prasanthrangan** [comment]
cool, thanks for confirming.. I'll close this!

**Comment by Gribovoy29** [comment]
I still got the hyprland-nvidia-git exit status 4. I solved it by changing hyprland-nvidia-git to the non git version in the install script.
Also I want to thank prasanthrangan for making this great way to get into ricing. While i was having trouble with these dots,  and looking for alternatives, I realized how great Hyprdots is.
