### ISSUE TITLE
Waybar background changed to black for some themes after the latest system update

### ISSUE THREAD

**Issue by Ramy-Ashraf** [prasanthrangan/hyprdots#556]
![231125_15h55m29s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/85342902/9fa5d566-973b-4997-b137-253d0e00d2e5)
The waybar background changed to black for some themes after the latest system update, I think for hyprland update. Also, please return the old time and date style (displaying the day and day number with the time beside it), it was much better.

**Comment by OctavianOG** [comment]
Greetings @Ramy-Ashraf , faced same issue as you, I tried everything: inspecting changes in last commits, code of modules, even tried to debug waybar.

Turns out solution was pretty simple - just rerun `./install.sh` script, the error should be resolved and waybar would work as it should

**Comment by Ramy-Ashraf** [comment]
Thanks a lot @OctavianOG

**Comment by Ramy-Ashraf** [comment]
Unfortunately, this doesn't solve my problem @OctavianOG

**Comment by OctavianOG** [comment]
@Ramy-Ashraf , sorry if that would sound stupid, but did you rebooted after running installation script?

**Comment by askareija** [comment]
I've also have same issues after updating Hyprland to v0.32.3-64-g512a5973. I Build hyprland manually. But black bar is gone if i entered special workspace (Super + S). Check video below:

https://github.com/prasanthrangan/hyprdots/assets/21377617/29f5e07c-4ef3-4c9a-a163-e037171b180f

**Comment by HWG90** [comment]
There is a stopgap solution to fix this.

layerrule = xray 0, ^(waybar)$

**Comment by Ramy-Ashraf** [comment]
Yeah, I rebooted after running the script @OctavianOG

**Comment by Ramy-Ashraf** [comment]
Okay, I will try your solutions.@askareija @HWG90 
Thanks

**Comment by askareija** [comment]
> There is a stopgap solution to fix this.
> 
> layerrule = xray 0, ^(waybar)$

im kinda newbie, can you tell me where i place this?
