### ISSUE TITLE
dunst not have the same theme

### ISSUE THREAD

**Issue by yousseffjel** [prasanthrangan/hyprdots#557]
![image](https://github.com/prasanthrangan/hyprdots/assets/37506107/5328cda0-df8a-4882-ac1e-cfeee7dea86f)

I don't ave any problem on the theme, just dunst not have the same theme

**Comment by kRHYME7** [comment]
Assuming you are on the latest commit can you try to recaching your wallpaper? 

run 
```
cd ~/Hyprdots/Scripts
./create_cache.sh -f 
```
Warning: This will take time and CPU usage.

**Comment by yousseffjel** [comment]
let me try this

**Comment by yousseffjel** [comment]
the same problme

**Comment by kRHYME7** [comment]
If nothing works have you tried to  

``` cd ~/Hyprdots/Scripts
git pull
./install.sh
``` 

this will recursively re-install the configs. Maybe you missed something.

**Comment by kRHYME7** [comment]
@yousseffjel  Feel free to reopen this/another issue if you still have these problems after pulling the latest commits.
