### ISSUE TITLE
Issues on Manjaro KDE

### ISSUE THREAD

**Issue by lleonardonascimento** [prasanthrangan/hyprdots#558]
I installed on manjaro kde, but i have some issues.

1 - Sddm didn't change.

![IMG_20231125_151331788](https://github.com/prasanthrangan/hyprdots/assets/67169343/b8aba4b6-505d-4106-a18b-8aaf0c2cd723)

2 - Fonts are too small. I added these lines to ~/.config/hypr/userprefs.conf:

`exec = gsettings set org.gnome.desktop.interface font-name 'Cantarell 15'
exec = gsettings set org.gnome.desktop.interface document-font-name 'Cantarell 15'
exec = gsettings set org.gnome.desktop.interface monospace-font-name 'CaskaydiaCove Nerd Font Mono 13'`

but nothing happens. Only fonts for firefox changed.

![231125_15h31m30s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/67169343/686b70b0-fb9a-44dd-9731-0e289c855aed)
![231125_15h33m38s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/67169343/2ef7c324-9a93-4d19-9ca6-71e3c2523e62)

3 - Waybar GPU Info doesn't show my dedicated gpu. I have AMD RX 480 and intel integrated graphics. It only show information from intel gpu. I tried to run amdgpuinfo.py and gpuinfo.sh and get this result:

`❯ python3 amdgpu.py
Error: Unknown query failure (an AMDGPU call failed). This query may not be supported for this GPU.
❯ ./gpuinfo.sh
./gpuinfo.sh: line 4: nvidia-smi: Command Not Found
jq: parse error: Invalid numeric literal at line 1, column 6
jq: parse error: Invalid numeric literal at line 1, column 6
jq: parse error: Invalid numeric literal at line 1, column 6
jq: parse error: Invalid numeric literal at line 1, column 6
./gpuinfo.sh: line 23: [: : expected integer expression
{"text":"37°C", "tooltip":"Primary GPU: Intel GPU\n❄️ Temperature: 37°C"}`

**Comment by kRHYME7** [comment]
> 2 - Fonts are too small. I added these lines to ~/.config/hypr/userprefs.conf:

Hi, have you modified your monitor scaling?  How about setting it to 2.
``` monitor = ,preferred,auto,2  ```

 Then maybe ``` env = GDK_SCALE,1 ```.  for GTK

**Comment by lleonardonascimento** [comment]
> Do you mean sddm did not follow the repositories? Configuration?

Yes. it's remain the standard configuration from Manjaro and on `/usr/share/sddm/themes/` 
there's no new directories ( only the ones from Manjaro. )
Is there a way to fix it? ( Follow repositories configuration )

> Hi, have you modified your monitor scaling? How about setting it to 2 inside your ./userprefs `monitor = ,preferred,auto,2 `
>
I made a quick test and set it to `monitor = ,preferred,auto,1.3` and became a little better but not solve the problem completely.
Some applications not scale evenly.

> Then maybe `env = GDK_SCALE,1`. for GTK
>
I'll try this and post feedback.

> I guess for now the script does not support your GPU or lacked something, We are really welcome for contributions.

**Comment by T-Crypt** [comment]
@lleonardonascimento 

Can you check that the `kde-settings.conf` got added to `/etc/sddm.conf.d`?

The GPU error is related to the fact that is not a supported GPU for the queries. I can look into updating the script to see if I can add support for ATI AMD cards but right now it has limited functions on the older ATI integrated cards.

**Comment by lleonardonascimento** [comment]
> @lleonardonascimento
> 
> Can you check that the `kde-settings.conf` got added to `/etc/sddm.conf.d`?
> 
> The GPU error is related to the fact that is not a supported GPU for the queries. I can look into updating the script to see if I can add support for ATI AMD cards but right now it has limited functions on the older ATI integrated cards.

It was added.
![231127_17h01m02s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/67169343/702597ce-d47b-435d-96d2-54b24f2f1dc4)

I made i mistake when i said there's no directory in `/usr/share/sddm/themes/`. The directory is there and i was able to fix sddm by
editing the file `/etc/sddm.conf` but there's a problem. When i'm typing my password i can see for a brief moment the characters.
This doesn't happen when i use breeze sddm theme.
![IMG_20231127_164540518](https://github.com/prasanthrangan/hyprdots/assets/67169343/6522c452-4a9f-4b6c-88b5-05c935ee176d)

And i have other issues:
Scaling the resolution to `monitor = ,preferred,auto,1.3` increased font size but some apps got pixelated fonts( VScode for example) . To solve this i added `xwayland {
  force_zero_scaling = true
}` to hyprland.conf but Stremio ( Flatpak app ) doesn't open ( It opens and closes immediately ). If set resolution to `monitor = ,preferred,auto,1` it opens normally.
And network icon ( System Tray ) doesn't scale. You could see in the first image i attached.

**Comment by katsuja** [comment]
> @katsuja @lleonardonascimento
> 
> Can you guys try adding this script to maybe the downloads folder or anywhere on the local system and running this and showing me what error you get? I have added more error handling so I can figure out what the issue is. The AMDGPU python package may have had an update and I didn't catch the changes.
> 
> [amdtest.zip](https://github.com/prasanthrangan/hyprdots/files/13479482/amdtest.zip)

![231127_23h38m58s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/20012885/a4574cae-1856-4290-a6f3-7a20a433a869)

**Comment by lleonardonascimento** [comment]
@T-Crypt

The problem seems to be with `query_power()` method. I did some testing and when i ran this method i got an error.
The other methods seems to work.
![231127_21h10m17s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/67169343/bb334796-7bb4-43b4-bad9-e133237ec3a7)

I got an error on `query_northbridge_voltage()` too.

**Comment by kRHYME7** [comment]
Hello, The gpuinfo script has been updated recently. Feel free to reopen this/another issue. Added this to ``` good first issue ``` For reference on Manjaro KDE. Thanks!
