### ISSUE TITLE
Remove hyprland-nvidia-git for nvidia graphics cards

### ISSUE THREAD

**Issue by Ew4n1011** [prasanthrangan/hyprdots#559]
Hi, I tried to update the `hyprland-nvidia-git` package today, and saw that it gave an error. Looking on the official AUR page for the package, it seems that due to changes on the git repository of Hyprland, it now has built in support for Nvidia, and so these patches are apparently no longer necessary.

`hyprland-git` should be the only package necessary now if that's true.

**Comment by Ew4n1011** [comment]
On another note, whenever I update or reinstall Hyprland, it seems to always make my cursor invisible until I add `env WLR_NO_HARDWARE_CURSORS=1` to the desktop file in `/usr/share/wayland-sessions/hyprland.desktop`

**Comment by T-Crypt** [comment]
This is resolved in #567. 

Please use `hyprland-git`. You can install and change the branch by `Yay -S hyprland-git` and reboot.

**Comment by Ew4n1011** [comment]
> @Ew4n1011 you can add that to your userpref.conf file too

@NeverALegend I already have this variable in `nvidia.conf`, but it seems to not being executed.

**Comment by T-Crypt** [comment]
Have you rebooted?
