### ISSUE TITLE
waybar doesnt start

### ISSUE THREAD

**Issue by Newer1107** [prasanthrangan/hyprdots#56]
I did super+up-arrow and now waybar doesnt even start, it was working before I used the shortcut
when I do waybar in terminal it gives the output
❯ waybar
waybar: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory
other stuff is working fine, this is the only problem that is this waybar.
thanks for making these easy yet beautiful setups creator!

**Comment by Newer1107** [comment]
I just installed it and was testing the shortcuts until this happened.

**Comment by Newer1107** [comment]
Hello,
I fixed this issue by installing waybar-git from the AUR.
Thank you!

**Comment by prasanthrangan** [comment]
Hi, Thank you or sharing!

By default it should install `waybar-hyprland-git` package, and never seen this error before. So glad that `waybar-git` version works!
