### ISSUE TITLE
Waybar background not dynamically updating until application is opened

### ISSUE THREAD

**Issue by Ew4n1011** [prasanthrangan/hyprdots#560]
Whenever I change the wallpaper, it doesn't update the background until I open an application, like firefox for example. On startup, it's just a black background

**Comment by HWG90** [comment]
Iusee #556 details this, and a stopgap solution exists to resolve the issue. Create a layerrule for waybar, 

`layerrule = xray 0, ^(waybar)$`

Can be placed anywhere but for sake of this being related to hyprdots apparently, I have placed the fix within /hypr/themes/common.conf

**Comment by Ew4n1011** [comment]
Yep, that fixes it. Thanks!
