### ISSUE TITLE
cannot install hyprland-nvidia-git and grimblast-git

### ISSUE THREAD

**Issue by wemmmm** [prasanthrangan/hyprdots#564]
![image](https://github.com/prasanthrangan/hyprdots/assets/145137550/47261f8c-c8f6-4abd-9913-dcec042b3279)

**Comment by Unwrapped3** [comment]
Same issue here. It's my first try on arch install so I'm not sure if I've done something wrong or the issue is with the package itself

**Comment by Unwrapped3** [comment]
> @Unwrapped3 @wemmmm Move to hyprland-git, the Hyprland Team removed the Nvidia patches it seems because the nvidia hyprland maintainer apparently does not want to continue working on it. It might also break the special workspaces, it did for me at least, in your user preferences add under the dwindle layout a special_scale_factor value (it's a float value)

Thanks for the tip! I've deleted the line with hyprland-nvidia-git from install.sh completely and it also worked

**Comment by wemmmm** [comment]
> > @Unwrapped3 @wemmmm Move to hyprland-git, the Hyprland Team removed the Nvidia patches it seems because the nvidia hyprland maintainer apparently does not want to continue working on it. It might also break the special workspaces, it did for me at least, in your user preferences add under the dwindle layout a special_scale_factor value (it's a float value)
> 
> Thanks for the tip! I've deleted the line with hyprland-nvidia-git from install.sh completely and it also worked

send me line that you changed please, i don't understand what i need to do

**Comment by wemmmm** [comment]
> > > > @Unwrapped3 @wemmmm Move to hyprland-git, the Hyprland Team removed the Nvidia patches it seems because the nvidia hyprland maintainer apparently does not want to continue working on it. It might also break the special workspaces, it did for me at least, in your user preferences add under the dwindle layout a special_scale_factor value (it's a float value)
> 
> > > 
> 
> > > 
> 
> > > Thanks for the tip! I've deleted the line with hyprland-nvidia-git from install.sh completely and it also worked
> 
> > 
> 
> > send me line that you changed please, i don't understand what i need to do
> 
> 
> 
> You don't have to do what he did, just do `yay -S hyprland-git` or `paru hyprland-git` ( I think that's the right paru syntax), prasanthrangan or any of the other maintainers can push out a new commit with the changes

okay, thanks

**Comment by wemmmm** [comment]
> > > > @Unwrapped3 @wemmmm Move to hyprland-git, the Hyprland Team removed the Nvidia patches it seems because the nvidia hyprland maintainer apparently does not want to continue working on it. It might also break the special workspaces, it did for me at least, in your user preferences add under the dwindle layout a special_scale_factor value (it's a float value)
> 
> > > 
> 
> > > 
> 
> > > Thanks for the tip! I've deleted the line with hyprland-nvidia-git from install.sh completely and it also worked
> 
> > 
> 
> > send me line that you changed please, i don't understand what i need to do
> 
> 
> 
> You don't have to do what he did, just do `yay -S hyprland-git` or `paru hyprland-git` ( I think that's the right paru syntax), prasanthrangan or any of the other maintainers can push out a new commit with the changes

It is working, thanks!
