### ISSUE TITLE
High CPU usage and disconnections from the internet at random times

### ISSUE THREAD

**Issue by Dziobak727** [prasanthrangan/hyprdots#565]
When i don't have anything turned on and I'm on the desktop, it shows me 20% CPU usage, when i run a browser or Spotify, the CPU usage increases to 25-40%, is it because i installed something wrong? Or is it because my CPU is weak for hyprland? And as for disconnecting the internet at random times, it's like when I'm just using the internet or i'm on the desktop, at random times it disconnects me from the internet and i'm using ethernet. My CPU is I5 6600k

**Comment by jaypatel208** [comment]
Monitor your pc with tools like bpytop and you will able to see processes where your power is getting used

**Comment by kRHYME7** [comment]
Hi for comparison have you tried using another DE/WM  aside from hyprland? You can use btop to monitor your system also you could monitor your maximum cpu usage and more.

**Comment by Dziobak727** [comment]
> Hi for comparison have you tried using another DE/WM  aside from hyprland? You can use btop to monitor your system also you could monitor your maximum cpu usage and more.

I tried KDE and there was no such problem there

**Comment by kRHYME7** [comment]
Press ``` e ``` on btop to see the tree also check  waybar  and bash. To search press ``` f ``` to  and input. 
There was  a time that waybar  consumes power same as hyprland.


![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/6c027f38-8477-4fa3-a041-c492a04e89d3)

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c7cfb7a3-1bcd-4c72-86c2-26f233d398c8)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/9d5f9e1b-83d4-4744-99e9-28c740962fa2)


![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/6e8049b0-24bf-4f7d-83b7-3268fa42fc99)

**Comment by Dziobak727** [comment]
> Press `e` on btop to see the tree also check waybar and bash. To search press `f` to and input. There was a time when the waybar consumed power same as hyprland.
> 
> Also hyprland peaks on my system at 20 percent but this is very instant and should not cause issues
> 
> Check your Cpu also maybe it was heating and reaches its bottle neck
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/285813015-f462402c-0a4a-418f-8f2c-8ed1e670ff07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODU1OTQsIm5iZiI6MTcwMTA4NTI5NCwicGF0aCI6Ii81MzQxNzQ0My8yODU4MTMwMTUtZjQ2MjQwMmMtMGE0YS00MThmLThmMmMtOGVkMWU2NzBmZjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDExNDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1M2YzNzdmYjY1NGE1YTc1NjE4NTA4NjAxOTAxNWNkNzRjNDE0ZDVkYTQyYzM3MGVmNzRjMzA3OGU4YWI1OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_kVdNkYrE4RPQDOF5hHi0xmXHKwm0XYDyrMPNz58j0)
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/285811574-6c027f38-8477-4fa3-a041-c492a04e89d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODU1OTQsIm5iZiI6MTcwMTA4NTI5NCwicGF0aCI6Ii81MzQxNzQ0My8yODU4MTE1NzQtNmMwMjdmMzgtODQ3Ny00ZmEzLWEwNDEtYzQ5MmEwNGU4OWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDExNDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MWY5YzQ0N2JmNDJhNzAwNmNhNTEwNjMzMzRjY2Y1NzZjZGMyNDllZWNhNTRmYjliMTg2MGUzZjM0YzQxYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GanSQF33CBBQ0xmohxTw_1noSqOqU72z5ic1KJTN9Ik)
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/285811594-c7cfb7a3-1bcd-4c72-86c2-26f233d398c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODU1OTQsIm5iZiI6MTcwMTA4NTI5NCwicGF0aCI6Ii81MzQxNzQ0My8yODU4MTE1OTQtYzdjZmI3YTMtMWJjZC00YzcyLTg2YzItMjZmMjMzZDM5OGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDExNDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMDBkM2MyMGU2NGEzOWY2MzQyOTcxYWM0NWZiOTZmOTQ4MGQ5YTM4ZWUxN2QxNTQwYzdhZTZmNjY2MDYzOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EEAZj8zUz5UtvQBcjK2wUR881NNVLgYSEWE99Kc45MI) ![image](https://private-user-images.githubusercontent.com/53417443/285812330-9d5f9e1b-83d4-4744-99e9-28c740962fa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODU1OTQsIm5iZiI6MTcwMTA4NTI5NCwicGF0aCI6Ii81MzQxNzQ0My8yODU4MTIzMzAtOWQ1ZjllMWItODNkNC00NzQ0LTk5ZTktMjhjNzQwOTYyZmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDExNDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZjgyOTM0NGFiNDAzOTJmOTZjYjI2NmU0MDE4ODI1YWQ4M2RiMGMzYzQ5ZmM2MDljMzQ2YWNiZDIyOTViNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SDefkMxioqrutb5O99VaYzI9ruPW34Q_jqE08sW83d8)
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/285812425-6e8049b0-24bf-4f7d-83b7-3268fa42fc99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODU1OTQsIm5iZiI6MTcwMTA4NTI5NCwicGF0aCI6Ii81MzQxNzQ0My8yODU4MTI0MjUtNmU4MDQ5YjAtMjRiZi00ZjdkLTgzYjctMzI2OGZhNDJmYzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDExNDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxODMwMGM1YWNiNzRiZmY2NzYwN2ZiMzM2NTA0YjY1Y2RmYmM5NmE1OWFmMTc0Y2E5NjQyOWQ4ZjY5ZjA5ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9LxfeaRP-sH2KJ6et1-L_KGZDL1bzzp0V46ZiVJ9qK8)
I looked in btop and the waybar uses only 0.1% of the CPU, when it comes to hyprland it still consumes 20% of the CPU but sometimes it decreases but still in some moments it consumes that 20%, from what you wrote, even if it uses that 20% it shouldn't be a problem at all so i shouldn't worry about it? As for overheating the CPU and causing a bottleneck, my CPU is at 31C so i don't think it causes any bottleneck

**Comment by T-Crypt** [comment]
@Dziobak727 

What version of Hyprland are you currently using?

**Comment by Dziobak727** [comment]
> @Dziobak727 
> 
> What version of Hyprland are you currently using?

How to check? I installed Hyprland using the installation script from Prasanthrangan

**Comment by Dziobak727** [comment]
> `Yay -Qs hyprland`

local/grimblast-git r78.11bbb96-1
local/hyprland-nvidia-git 0.32.3.r74.gad3f6886-1
local/xdg-desktop-portal-hyprland 1.2.5-1

**Comment by T-Crypt** [comment]
Trying installed `hyprland-git`, hyprland-nvidia-git is no longer needed for Nvidia supported, Hyprland supports nvidia by default now.

**Comment by Dziobak727** [comment]
> Trying installing `hyprland-git`, hyprland-nvidia-git is no longer needed for Nvidia supported, Hyprland supports nvidia by default now.

Installed. Do you know anything about why i get internet disconnected at random times? I tried to restart NetworkManager but it didn't help, I had DNS from Cloudflare before then I deleted it because I thought it was their fault but also not that, I had the link negotiation to automatic then I changed it to manual and vice versa didn't help either, do you know what could be the cause of this? I'm using the internet over ethernet.

**Comment by jaypatel208** [comment]
Firstly check if there are any upgrades available to your package in system , if you are getting up-to-date even the aur got updated try to change mirror list by using: [](https://archlinux.org/mirrorlist/) and upgrade system to latest packages.

And after that you still get random network disconnecting errors , checking the network logs will may be help you.

**Comment by katsuja** [comment]
> > Trying installing `hyprland-git`, hyprland-nvidia-git is no longer needed for Nvidia supported, Hyprland supports nvidia by default now.
> 
> Installed. Do you know anything about why i get internet disconnected at random times? I tried to restart NetworkManager but it didn't help, I had DNS from Cloudflare before then I deleted it because I thought it was their fault but also not that, I had the link negotiation to automatic then I changed it to manual and vice versa didn't help either, do you know what could be the cause of this? I'm using the internet over ethernet.

This usually happens when you have multiple active services that conflict. Example if you use networkmanager make sure the dhcpcd service is disabled. Or rather, check all the active services that manage the connection and disable them except networkmanager with service rester.
​

**Comment by MxDx** [comment]
Hello I'm also having issue with the CPU usage, hyprland is almost always using 20% of my cpu. I'm having no network issue on the other hand. I'm new to hyprland and I really like it but I is difficult to use my computer when 20% is already used. 

local/grimblast-git r79.65e567a-1
local/hyprland-git 0.33.0.r3.37d7a8c6-1
local/xdg-desktop-portal-hyprland 1.2.5-1

**Comment by rlapray** [comment]
hyprland-git 0.33.1.r19.0c10b8ab-1
nvidia-dkms 545.29.06-1

Same high CPU usage. Between 25% et 40% for 1 core on a i9-9900k, just for hyprland.

**Comment by fmash16** [comment]
Facing the same issue here on i7-9750H, any solutions?

**Comment by kRHYME7** [comment]
About the High usage see if disabling borderangle animation fixes it, More info in this link: https://github.com/prasanthrangan/hyprdots/issues/641

**Comment by fmash16** [comment]
@kRHYME7 thanks a lot! That fixed it. Didn't notice it was running on a loop.

**Comment by kRHYME7** [comment]
Closing this for now, as high cpu usage is resolved by disabling the borderangle animation. (Hyprland upstream issue)   Here's the discussion https://github.com/prasanthrangan/hyprdots/issues/641 
to disable use ``` Hyprdots power save [--opts] ```

About the network disconnections, we can't confirm that this is related to the dotfiles, but feel free to reopen this issue if necessary. For questions, maybe post something in the Discussion panel.
