### ISSUE TITLE
Moving from hyprland-nvidia-git to hyprland-git

### ISSUE THREAD

**Issue by Exoutia** [prasanthrangan/hyprdots#569]
So I was updating my packages using yay and got into problem that its not updating properly and from the comments on the aur site that they are telling that hyprland-git is handling nvidia card all fine and dandy and they are saying that everyone can move to hyprland-git.
![image](https://github.com/prasanthrangan/hyprdots/assets/94464106/0f86b3fd-c1a0-4468-a099-d733b9a141ca)
How will it effect your configuration.

**Comment by Exoutia** [comment]
Now that I have updated your config also and noticed it is also using hyprland-git so I guess it is not giving much impact for now.

**Comment by T-Crypt** [comment]
@Exoutia -- You can install `hyprland-git` with yay and reboot and this should remove the dependency for hyprland-nvidia-git as it will ask if you want to remove it as its a conflict. 

There is a pull request for this currently to update the installer. #568

**Comment by Exoutia** [comment]
Ok thanks everything is working properly

**Comment by unkindypie** [comment]
Tried to install `hyprland-git` using yay to migrate from` hyprland-nvidia 0.31.0-2` but get this error when installing hyprland-git:
```
Submodule 'subprojects/hyprland-protocols' (https://github.com/hyprwm/hyprland-protocols) registered for path 'subprojects/hyprland-protocols'
Submodule 'subprojects/tracy' (https://github.com/wolfpld/tracy) registered for path 'subprojects/tracy'
Submodule 'subprojects/udis86' (https://github.com/canihavesomecoffee/udis86) registered for path 'subprojects/udis86'
Submodule 'subprojects/wlroots-hyprland' (https://github.com/hyprwm/wlroots-hyprland) registered for path 'subprojects/wlroots-hyprland'
Cloning into '/home/maxb/.cache/yay/hyprland-git/src/Hyprland/subprojects/hyprland-protocols'...
done.
Cloning into '/home/maxb/.cache/yay/hyprland-git/src/Hyprland/subprojects/tracy'...
done.
Cloning into '/home/maxb/.cache/yay/hyprland-git/src/Hyprland/subprojects/udis86'...
done.
Cloning into '/home/maxb/.cache/yay/hyprland-git/src/Hyprland/subprojects/wlroots-hyprland'...
Submodule path 'subprojects/hyprland-protocols': checked out '0c2ce70625cb30aef199cb388f99e19a61a6ce03'
Submodule path 'subprojects/tracy': checked out '37aff70dfa50cf6307b3fee6074d627dc2929143'
Submodule path 'subprojects/udis86': checked out '5336633af70f3917760a6d441ff02d93477b0c86'
Submodule path 'subprojects/wlroots-hyprland': checked out '62eeffbe233d199f520a5755c344e85f8eab7940'
fatal: cannot change to 'subprojects/wlroots': No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: hyprland-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
hyprland-git - exit status 4

```
Can anyone help fixing it? I've tried cleanBuild option but it doesn't help

**Comment by kRHYME7** [comment]
try to use hyprland package first. There is a drama happening at the Upstream Hyprland repo. ☺️

**Comment by unkindypie** [comment]
@kRHYME7 
It worked, thank you
