### ISSUE TITLE
About custom lock screen

### ISSUE THREAD

**Issue by 2420228300** [prasanthrangan/hyprdots#58]
How can I customize the wallpaper and user avatar of the lock screen interface?

**Comment by prasanthrangan** [comment]
Hi,

you can change the background of login screen in `/usr/share/sddm/themes/corners/theme.conf` -
```
Background="backgrounds/bg.png"
```

For user avatar, place your png file in `/usr/share/sddm/faces` as `username.face.icon`

**Comment by 2420228300** [comment]
thank you
