### ISSUE TITLE
Script is broken

### ISSUE THREAD

**Issue by charisvt** [prasanthrangan/hyprdots#586]
Hyprland removed the nvidia patch thus making hyprland-nvidia-gir obsolete.
(See this PR https://github.com/hyprwm/Hyprland/pull/3957)
This has no use anymore
https://aur.archlinux.org/packages/hyprland-nvidia-git
and produces an error during installation which in turn errors the installation script.

**Comment by kRHYME7** [comment]
Thanks ! 

 This was a known issue and the maintainer is not yet available to merge  PR. 

#569 #568

**Comment by prasanthrangan** [comment]
Hi, this should be fixed in #595
