### ISSUE TITLE
Menu for switching mode is completely broken

### ISSUE THREAD

**Issue by Newer1107** [prasanthrangan/hyprdots#59]
https://github.com/prasanthrangan/hyprdots/assets/116626403/db670043-3b3e-4f05-aed0-bd91b225839d

As you can see in the video, the menu to change modes is completely broken.
it didnt work at all since I installed hyprland with the script.

**Comment by Newer1107** [comment]
Also, when I use arrow keys and press enter it does change modes.

**Comment by prasanthrangan** [comment]
Hi, please try reducing element icon size in the `~/.config/rofi/themeselect.rasi`  to fit your screen size -

```
element-icon {
    size:                        450px;
```

for example, try using 350px
