### ISSUE TITLE
Scaling issue on 1920x1080 display

### ISSUE THREAD

**Issue by manangulati9** [prasanthrangan/hyprdots#590]
Hi, first of all thanks to Prasanth for creating this wonderful package that made transitioning to hyprland so seamless for me. Everything works, except the scaling. I did my homework and have went through other open issues with the same bug. I tried changing the `.config/hypr/hyprland.conf` file's monitor to `eDP-1,1920x1080@60,0x0,1` and also `,preferred,auto,1` but none of them seem to do anything. I also tried to edit the `.config/hypr/monitors.conf` with the same settings but it doesn't work. The scale is set to 1.5 as shown in the images which causes apps to look too large. I need help on how to fix this. I've attached images for your reference
![231201_15h48m18s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/91965258/c7a123dd-b5e8-462c-81fc-204740c7e339)
![231201_15h49m27s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/91965258/7d8e88be-329c-42a0-a9b4-5f874430a04d)

**Comment by kRHYME7** [comment]
have you tried adding this to your ./userprefs.conf?
env = GDK_SCALE,1


xwayland {
    force_zero_scaling = false
    }
    
    Try to test which works best also on my system I needed to reboot sometimes or exit hyprland to take effect.

**Comment by manangulati9** [comment]
> have you try to change those values ? 
> 

I just did. Tried to set it to 1.25 but nothing happened.

**Comment by kRHYME7** [comment]
Ok I see sorry I miss read your post . So the problem here is the monitor scale is not changing despite those changes in the configs? 

How about disabling  all those monitor specific  configs. 



also maybe some lines are messing around 

can we have the output for this ? 

 {cat ~/.config/hypr/userprefs.conf | grep 'monitor'
cat ~/.config/hypr/hyprland.conf | grep 'monitor'
cat ~/.config/hypr/hyprland.conf | grep 'source' } | grep '='

**Comment by kRHYME7** [comment]
yup that would be safe but you won't have some features like creating cached for new wallpapers I guess.  Also if you want  a Cleaner /home/user/

If you just want to have a cleaner $HOME directory you can just install the dots  on your directory of choice. The script will handle it for you.

**Comment by manangulati9** [comment]
> yup that would be safe but you won't have some features like creating cached for new wallpapers I guess. Also if you want a Cleaner /home/user/
> 
> If you just want to have a cleaner $HOME directory you can just install the dots on your directory of choice. The script will handle it for you.

Got it. Thank you so much for your help!!
