### ISSUE TITLE
Theme error on fresh install

### ISSUE THREAD

**Issue by rcparent17** [prasanthrangan/hyprdots#592]
Hello,

I just did a fresh install of hyprdots and have this error showing up. I've gone in and commented out the `group` section in `theme.conf` to get rid of the error for now, but what is the actual fix for this? Thanks in advance!

![image](https://github.com/prasanthrangan/hyprdots/assets/16656605/3ea93c51-7037-4571-a3f1-113cf74acd20)

**Comment by rcparent17** [comment]
@T-Crypt there isn't a `theme.conf` in the base `hypr` directory, but assuming you're talking about `hypr/themes/theme.conf`:
```
exec = gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-green'
exec = gsettings set org.gnome.desktop.interface gtk-theme 'Decay-Green'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(90ceaaff) rgba(ecd3a0ff) 45deg
    col.inactive_border = rgba(86aaeccc) rgba(93cee9cc) 45deg
    layout = dwindle
    resize_on_border = true
}

#group {
#    col.border_active = rgba(90ceaaff) rgba(ecd3a0ff) 45deg
#    col.border_inactive = rgba(86aaeccc) rgba(93cee9cc) 45deg
#    col.border_locked_active = rgba(90ceaaff) rgba(ecd3a0ff) 45deg
#    col.border_locked_inactive = rgba(86aaeccc) rgba(93cee9cc) 45deg
#}

decoration {
    rounding = 10
    drop_shadow = false

    blur {
        enabled = yes
        size = 5
        passes = 4
        new_optimizations = on
        ignore_opacity = on
        xray = true
    }
}

#blurls = waybar
```

**Comment by rcparent17** [comment]
UPDATE: Switching from `hyprland` to `hyprland-git` resolved the issue. @T-Crypt called it. Thank you for your help!

**Comment by Skerse** [comment]
Okay looking into it i feel we have two options: 
 - Revert this commit: https://github.com/prasanthrangan/hyprdots/commit/8c51adf67caf4142f3e3115353626f261b4a6e31
- Or change the configs to match v0.30.0, which is possible, but still hyprland in the official repos is 5 releases out of date..
