### ISSUE TITLE
Error setting value for group border colors

### ISSUE THREAD

**Issue by ElectroPerf** [prasanthrangan/hyprdots#598]
![image](https://github.com/prasanthrangan/hyprdots/assets/76483474/e50c314d-a79f-4c13-a0b2-a899892145b0)

getting this red error line after fresh installation

**Comment by kRHYME7** [comment]
Hello please Install Hyprland-git  ``` yay -Sy hyprland-git ```

**Comment by prasanthrangan** [comment]
Hi, this should be fixed in #595
