### ISSUE TITLE
Permission problem 

### ISSUE THREAD

**Issue by MLeandr0** [prasanthrangan/hyprdots#599]
So, I never used Arch before, but I liked this project so much that I wanted to change that. But when I try to run the script it says that I don't have permission to run it on root. So I don't know what to do and about the Arch installation, should I run the script before reboot the system or after it ?

**Comment by kRHYME7** [comment]
did you add your user to sudoers file?

**Comment by MLeandr0** [comment]
> did you add your user to sudoers file?

Yes I did.

**Comment by kRHYME7** [comment]
Okay, can I see how did you run the script? any screenshots? Also, reminders in case, do not run the script with sudo.

**Comment by MLeandr0** [comment]
I also tried run it with sudo... I didn't know I shouldn't but it didn't work either. Also, I don't have any screenshots, but I did like the installation guide here, but I just got to the option where I had to choose between yar or paru and after that I got permission denied.

**Comment by kRHYME7** [comment]
Thanks That gives me a hint which part may give those errors. Have you tried installing packages  like try to install hyprland-git.

**Comment by MLeandr0** [comment]
Okay, I will try this again and let you know.
