### ISSUE TITLE
Scale waybar script

### ISSUE THREAD

**Issue by rafaeljacov** [prasanthrangan/hyprdots#604]
can someone please add a scripts to scale waybar's fontsize, margins, padding, etc to some specific sizes? I use 100% scaling in my monitor and I think the waybar is very small for me. At first I changed the sizes manually but later realized it gets overridden when changing waybar styles

**Comment by kRHYME7** [comment]
Sure! https://github.com/prasanthrangan/hyprdots/wiki/Theming#waybar-config

**Comment by rafaeljacov** [comment]
> Sure! https://github.com/prasanthrangan/hyprdots/wiki/Theming#waybar-config

sorry I'm still confused. can you give an example of config?

**Comment by kRHYME7** [comment]
Sorry, to scale your waybar edit the ``` ~/.config/waybar/config.ctl ``` you'll need to edit the column 2  with your preferred size.  Every time you change it you should toggle  your waybar like next mode then previous mode and see what size fits for you.

**Comment by rafaeljacov** [comment]
how to fix this? 
![image](https://github.com/prasanthrangan/hyprdots/assets/110229646/1a83e7a8-c761-434f-b757-db08706804f3)

**Comment by rafaeljacov** [comment]
how can I edit the config.jsonrc without getting overridden?

**Comment by T-Crypt** [comment]
@rafaeljacov, you would need to edit the modules in `~/.config/waybar/modules` then the modules create the config.jsonc from the `wbarconfgen.sh` in the hypr scripts directory.
