### ISSUE TITLE
Glitchy fonts in terminal 

### ISSUE THREAD

**Issue by Atom-256** [prasanthrangan/hyprdots#609]
Kitty wasn't working for me after I installed an theme with the archlinux -tweak-tool ,so I replaced it with foot but now the font is glitching out when I try resize the window size of terminal (I hade the same issue with kitty too ,but not this often)..
![Uploading 17016292842051783260449487995794.jpg…]()

**Comment by prasanthrangan** [comment]
Hi, can you try removing the kitty conf file and try using the default conf?
Also i'm unable to view the screenshot.

**Comment by kRHYME7** [comment]
Please reopen if necessary.
