### ISSUE TITLE
Dolphin theme Issue

### ISSUE THREAD

**Issue by Newer1107** [prasanthrangan/hyprdots#61]
https://github.com/prasanthrangan/hyprdots/assets/116626403/62c6f63d-f933-403e-b0ba-8a7d820d88c6

the theme gets weird when I open dolphin with other apps like obs as shown in the video

**Comment by prasanthrangan** [comment]
Hi, can you please recheck the config files for dolphin, it seems to be messed up.
so you can try copying these files from my git to your home dir -
```
${HOME}/.config/dolphinrc
${HOME}/.config/kdeglobals
${HOME}/.local/share/dolphin
${HOME}/.local/share/kxmlgui5/dolphin
```
