### ISSUE TITLE
Bluetooth not working and sound not working

### ISSUE THREAD

**Issue by Parsa307** [prasanthrangan/hyprdots#612]
Bluetooth is not showing any devices and sound stop working

**Comment by T-Crypt** [comment]
@Parsa307 

If this is specific to the hyprdots, please provide some input. I will be working on an issue template with @prasanthrangan shortly so we can make sure issues for arch linux are not being submitted in the repository as we have a lot of new comers and users now to maintain and make sure we are providing support for. 

Generic system issues should be handled by the user to troubleshoot and/or provide evidence that it is an issue/bug with the hyprdots that is causing this.

**Comment by Parsa307** [comment]
> hehee... I'm not surprised, its Arch after all, new users will get used to it soon :) Ya my bad, didn't get a chance to look into issue template and maintain known errors... But I'll look into it soon! If you are aware of the issue feel free to link to the related arch/hypr wiki page or move it to discussions...

Oh okay i will close the issue

**Comment by prasanthrangan** [comment]
hey @Parsa307 , no worries bro...
as general steps to troubleshoot please always try to run it from command line, for bluetooth please try running `bluetoothctl` from terminal, for details please refer this [wiki](https://wiki.archlinux.org/title/bluetooth#Pairing).
