### ISSUE TITLE
libfmt.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by YasirRWebDesigner** [prasanthrangan/hyprdots#62]
OS: Arch Linux

After the latest Arch update, I got a few hours ago, waybar breaks and stops working, running `waybar` in the terminal gives the following output.

`libfmt.so.6: cannot open shared object file: No such file or directory`

reinstalling `fmt` or building `fmt-git` doesn't fix the issue. The workaround is to remove `waybar-hyprland-git` and install `waybar` instead.

**Comment by Gedankenn** [comment]
Mine did also break the libfmt, also runing Arch Linux. My solution was to just reinstall waybar-hyprland-git.

**Comment by YasirRWebDesigner** [comment]
> Mine did also break the libfmt, also runing Arch Linux. My solution was to just reinstall waybar-hyprland-git.

strange I did reinstall it but it didn't work for me

**Comment by YasirRWebDesigner** [comment]
for me, it was the other way around after installing the `waybar` I started to see this Arch Icon which wasn't visible before
![swappy-20230822_094425](https://github.com/prasanthrangan/hyprdots/assets/32537564/7a254737-0e8e-4394-87b1-a5c783b07658)
