### ISSUE TITLE
Can't boot system

### ISSUE THREAD

**Issue by MLeandr0** [prasanthrangan/hyprdots#622]
So I did a clean linux and script install and the system worked normaly. But then, after turning it on some hours later at the same day I got stuck at the boot screen showing this:

[ OK ] Reached target Graphical Interface 

I don't know if this has reason but my graphic card is 920M and I even tried installing the proper drivers 430.40 but the same keep happening.

**Comment by prasanthrangan** [comment]
Hi, can you please login to TTY and check the grup config to if the nvidia_drm.modeset=1 is set -
```
grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub
```
also please check if `nvidia-470xx-dkms` package is installed and verify `lsmod` as below - 

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/8cc02e40-eddf-42b7-884f-900cc864b40e)

**Comment by MLeandr0** [comment]
Because I was having so much problem, I decided to try an Arch install from the start without scripts, just to get used with the distro. So I can't try this fix for now. But, thank you so much for the help !!!
