### ISSUE TITLE
[Failed] to start systemd-hibernate-resume.service

### ISSUE THREAD

**Issue by Gl00ria** [prasanthrangan/hyprdots#623]
Hey, Thanks for this AWESOME config.

I used to have my own hyprland configuration with nvidia, and it was working perfectly. Recently, I wanted to move to this fantastic configuration, but I am having 2 issues.

### **Issue 1: Related to to the title.**

Whenever I resume from the Hibernate state I get this error 

`[Failed] Failed to start systemd-hibernate-resume.service`

then my laptop boots normally into the SDDM, but every opend window is gone due to the failur.

### **Issue 2: I guess it is related to the 1st issue.**

After the grub menu I get the following.

```
error: spares file not allowed.
Loading Linux linux ...
Loading initial ramdisk ...

Press any key to continue...
```

Now, right after pressing enter I get the first error message which related to the Hibernate state.

I still can access my machine & the config is working perfectly as expected.

Looking forward to find a fix.
Thanks again.

Edit: The installation was on a newly installed system using the script mentioned in the repo.

**Comment by katsuja** [comment]
I think you need a swap partition. Check it out here: [https://forum.manjaro.org/t/howto-enable-and-configure-hibernation-with-btrfs/51253](url)
It's a simple guide and is good for arch linux and all derivatives.

**Comment by Gl00ria** [comment]
> I think you need a swap partition. Check it out here: [https://forum.manjaro.org/t/howto-enable-and-configure-hibernation-with-btrfs/51253](url)
> It's a simple guide and is good for arch linux and all derivatives.

Thanks for your response,

I did the installation twice, in the 1st one I had this issue so I thought that I missed up something. For the 2nd one, I made sure everything is working perfectly including the Hibernation process, so I proceeded with the configuration installation process, but still facing the same issues.

Regarding the swap partition, I have a 17Gb swap partition.

**Comment by Gl00ria** [comment]
Hello, @katsuja 
Problem solved,

I did a new installation on a newly installed system, but this time I commented [this if statement](https://github.com/prasanthrangan/hyprdots/blob/7667812aa5cc6ff0ecb737cfdef9d3a24a32ff21/Scripts/restore_etc.sh#L40) which turned out to be the cause of the issue, then I manually added the `nvidia_drm.modeset=1` to GRUB.

So far everything works as perfectly as expected.

**Comment by katsuja** [comment]
So it was all already in the script. As always, the authors have thought of everything. Good job! 😄
Enjoy this beautiful rice.👍️

**Comment by prasanthrangan** [comment]
> I did a new installation on a newly installed system, but this time I commented [this if statement](https://github.com/prasanthrangan/hyprdots/blob/7667812aa5cc6ff0ecb737cfdef9d3a24a32ff21/Scripts/restore_etc.sh#L40) which turned out to be the cause of the issue, then I manually added the `nvidia_drm.modeset=1` to GRUB.

I had this happen once before, where the grub changes did not apply at `grub-mkconfig`, it didnt throw any errors as well, I'd to rerun the restore_etc.sh to fix it... I think I'll have to include a check after generating the grub config...

**Comment by Gl00ria** [comment]
@prasanthrangan 
I doubt that, in my case the 'grub-mkconfig' ran successfully because the white GRUB theme was applied which hurts my eyes lol. 

So my best guess is the way of adding the models [here](https://github.com/prasanthrangan/hyprdots/blob/main/Scripts/restore_etc.sh#L52).

I will make a VM soon and compare the GRUB file before & after the installation.

**Comment by Gl00ria** [comment]
@prasanthrangan Ok, Solved

### GRUB file before & after the `restore_etc.sh`:
![231208_15h01m30s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/74514103/1f59bdb4-8935-4621-9cfc-56539131d5b7)

### How I solved it:
1. Changed `GRUB_DEFAULT=saved` to `GRUB_DEFAULT='0'`
2. Commented `GRUB_SAVEDEFAULT=true`
3. Run `sudo grub-mkconfig -o /boot/grub/grub.cfg`

### NOTES:
1. The `restore_etc.sh` will never add the `nvidia_drm.modeset=1` to GRUB, I had to do it manually on my personal machine but I didn't add it on the VM since the VM won't detect nvidia.
2. Seems the `restore_etc.sh` to run successfully only the first time which produces the described issue above.

**Comment by prasanthrangan** [comment]
thank you so much @Gl00ria , for digging into this!
I do see line 4 where `GRUB_CMDLINE_LINUX_DEFAULT` is defined, did you add this line? if not it should have added `nvidia_drm.modeset=1` to it!

**Comment by Gl00ria** [comment]
@prasanthrangan No, THANK YOU for this amazing config, I even dropped [my own config](https://github.com/Gl00ria/dotfiles/tree/main/dot_hyprland) and started using yours with some modifications to fit my needs and to be able to contribute to it.

Also, Apologies for this late replay as I was working on [this pull request](https://github.com/prasanthrangan/hyprdots/pull/477#issuecomment-1848638955) hopefully its what needed.

Regarding this issue, yes I did edit the`GRUB_CMDLINE_LINUX_DEFAULT` whether on ArchLinux or EndeavourOS because its an encrypted install. I will deep dive into this case soon.

**Comment by kRHYME7** [comment]
@prasanthrangan  Hi Bro, do the latest commit fixes this issue?

**Comment by Gl00ria** [comment]
@kRHYME7 @prasanthrangan Long time no see, but came with informative description this time :) 
## Addressing: ISSUE 1
> [Failed] Failed to start systemd-hibernate-resume.service

I couldn't reproduce this error but my best guess is that the following services must be enabled in case of (nvidia drivers):
1. nvidia-suspend.service
2. nvidia-hibernate.service
3. nvidia-resume.service

And as a "Kernel Module Parameter"  add: 
1. NVreg_PreserveVideoMemoryAllocations=1
2. NVreg_TemporaryFilePath=/var/tmp 

As mentioned in the ArchWiki [here](https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend).
## Addressing: ISSUE 2

> Issue 2: I guess it is related to the 1st issue.

So I went deep deep down the rabbit hole "because it bugged me" so I found out that `GRUB_SAVEDEFAULT=true` [in this line](https://github.com/prasanthrangan/hyprdots/blob/a31bc6e5e6992594ae6a18a68ae72bb4d5f2234c/Scripts/install_pre.sh#L47C16-L47C37) is the cause of the issue.

### Environment where the issue occur:
-  [BTRFS](https://wiki.archlinux.org/title/Btrfs) file system.
- `GRUB_SAVEDEFAULT=true`

### Suggestion to fix:
- Remove the mentioned line from the script.
- Or set `GRUB_SAVEDEFAULT=false`

On normal Arch installation  `GRUB_SAVEDEFAULT` is commented by default.

### Why this suggestion to fix:
The `GRUB_SAVEDEFAULT` is set to detect the last booted kernel while this config has no extra kernel listed in [custom_apps.lst](https://github.com/prasanthrangan/hyprdots/blob/main/Scripts/custom_apps.lst) nor in [custom_hypr.lst](https://github.com/prasanthrangan/hyprdots/blob/main/Scripts/custom_hypr.lst) like (linux-lts, linux-zen). Also "GRUB" cannot write on "BTRFS".

**Comment by kRHYME7** [comment]
Hi! @Gl00ria! If this is for certain, can you please do a PR so that the matter will have a wider surface for discussion

**Comment by abenezerw** [comment]
Could you close as solved if you no longer have this issue. Thank you @Gl00ria
