### ISSUE TITLE
Repo missing License

### ISSUE THREAD

**Issue by DarkXero-dev** [prasanthrangan/hyprdots#626]
Hey ..

I have written a post on my forums about your dots, hats off to you for doing a great job. However, a lot of users voiced their concern about the lack of a license on the Repo it takes less than a minute. I know you mention it in Readme that anyone is free to fork n modify, but it would be safer for you to add the License file so people stop complaining.. 

Just a recommendation.. From one maintainer to another ;)

**Comment by prasanthrangan** [comment]
Thank you so much for your support!
Ya that's my bad, I didn't get a chance to read and understand how these licenses works, I'll do it shortly!

**Comment by prasanthrangan** [comment]
this is done!
