### ISSUE TITLE
Hyprland-git Build issues due to missing tomlplusplus dependency

### ISSUE THREAD

**Issue by DarkXero-dev** [prasanthrangan/hyprdots#629]
You need to include the `tomlplusplus` package to your install script otherwise there's an issue with Hyprland-git
```
hyprpm/src/meson.build:7:4: ERROR: Dependency "tomlplusplus" not found, tried pkgconfig and cmake
```
I am kinda new to **Hyprland**, trying to install alongside **KDE**.. Also would be great if you made sure of the following

- script detect if some of the offered packages are installed. For example I already have `ohmyzsh/zsh/powerlevel10k` installed as I compile n host them on my own repos. I do not want to override them with -git versions from AUR, at least as a prompt if we want to install or not.. 
- Do not force all apps on user, for example I do not need nor use VisualStudio-bin...
- Script should backup user's current config before applying yours...

Otherwise great job ;)

**Comment by prasanthrangan** [comment]
> Also how to set vivaldi as default browser ? Finally am having issue sharing screen on Discord. I do have xwaylandvideobridge installed for it to work on KDE Wayland.. Maybe causing a problem. And how to enable numlock on boot ?

by default the keybings are set to firefox, but you can change this line in here to vivaldi -
https://github.com/prasanthrangan/hyprdots/blob/7667812aa5cc6ff0ecb737cfdef9d3a24a32ff21/Configs/.config/hypr/keybindings.conf#L16

For discord, it can only share xwayland apps by default, but you can try the workaround with `xwaylandvideobridge-bin` as mentioned in the [wiki](https://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/).

and to enable numlock by default please use `numlock_by_default` in the input section on hyprland.conf, please refer the [input](https://wiki.hyprland.org/Configuring/Variables/) section from the wiki!

Yup, just saw the one about license, I'm on it :)

**Comment by Skerse** [comment]
After you clone it, you'll only ever need to run `git pull` in the Hyprdots directory to get the latest changes from the github without having to download the entire repo every time. This way you can stay up to date by restoring the configs after your pull the latest changes.

Hopefully when this pull request get's merged it'll be a lot easier too: https://github.com/prasanthrangan/hyprdots/pull/601

**Comment by DarkXero-dev** [comment]
Yeah but initial clone not going through dunno why I keep getting ssl error xD

**Comment by DarkXero-dev** [comment]
@prasanthrangan 

Hey bud, sorry for ping, but I was thinking, do you have a place where we can talk privately ? Discord or something ? I need your help with optimizing your script to make it work better for my needs.. I am no bash expert.. Like work together.. If you have some time.

**Comment by DarkXero-dev** [comment]
> hello @DarkXero-dev Have you still not installed the dots?
> 
> Are you using meson or make?

Installed just fine just need time to understand how this thing works I have never used WMs before I been using KDE for past 5 years..

**Comment by DarkXero-dev** [comment]
> Hey I uploaded the `hyprdots-ctl` script on AUR. `paru -Sy hyprdots-ctl`. You can run `hyprdots-ctl man` to see available functions. I think I can add a backup script on that and maybe push a PR for a backup script. @Skerse @DarkXero-dev

What does this do ? If I may ask ?

**Comment by kRHYME7** [comment]
> What does this do ? If I may ask ?

This was just a script to manage Hyprdots 

```
❯ hyprdots-ctl man
Hyprdots: v0.5-179-gfb9366e
CloneDirectory: /home/khing/Storage/My_Documents/GitHub/KhingDom
Usage: hyprdots-ctl [Function] [Arguments] [Parameters]

  [man]                * Show Manual
  [update]             * Pull Updates From Hyprdots Repository
  [install]            * Installs Hyprdots
                          [fresh]          Fresh installation of Hyprdots
                          [custom]         Custom installation of Apps
  [restore]            * Restore Hyprdots Configurations
                          [defaults]       Restore to Default Configurations of Hyprdots
  [theme]              * Theme Related Actions
                          [set]            Set Theme
                          [next]           Next Theme
                          [prev]           Previous Theme
                          [select]         Theme Selector
                          [patch]          Patch A Theme from different repository.
  [wallpaper]          * Wallpaper related Actions
                          [set]            Set /Path/to/Wallpaper as Wallpaper
                          [next]           Next Wallppaer
                          [prev]           Previous Wallpaper
                          [select]         Wallpaper Selector
  [sddm]               * Sddm Things
                          [set]            Set active Wallpaper to Sddm Lockscreen
  [wallbash]           * Wallbash
                          [toggle]         Toggle Wall bash On/Off
  [waybar]             * Waybar related Things
                          [control]        Edit waybar Control File.
  [code]               * Modify Vscode Extensions
                          [select]         Selector for default Theme presets
  [cache]              * Cache
                          [reload]         Reload Caches if you have new wallpapers.
                          [rebuild]        Force rebuild cache
                          [add]            Cache custom /path/to/wallpaper/*
                          
          
```

**Comment by DarkXero-dev** [comment]
@kRHYME7 Nice ! Added to my Hypr_repo ;)

**Comment by kRHYME7** [comment]
I guess, libtomlplusplus is required for the hypr plugin manager.

**Comment by Skerse** [comment]
Oh wow i didn't realize i was talking to the xerolinux dev, nice to see you here! I believe everyone here would be happy if you wanted to help make this project better.

A separate repo for pre-compiled aur packages during installation would definitely be nice, especially since it takes me around 40-50 minutes from running ./install.sh to it finishing.

Creating an entire distro for hyprdots is a lot harder because of the way it's been built, but i wouldn't be apposed to discussing it's possibility! I think however for right now, doing archinstall with minimal desktop, then with the introduction of hyprdots-ctl, it's really not that difficult to install and maintain hyprdots updates anymore.

I'd love to hear @prasanthrangan opinions on this, and this discussion should definitely continue on a discussion post instead of this issue thread so if you'd like to create one @DarkXero-dev please do!

**Comment by DarkXero-dev** [comment]
Oh no never a Distro. I tried to add more "flavors" and failed twice. No time as am alone doing this. People come n help which is greatly appreciated, but they also always leave me hanging by a thread. Anyway yeah will open a discussion thread as soon as I am back at work. 

Hopefully @prasanthrangan will see it n we can make this script better.

**Comment by prasanthrangan** [comment]
whoaa @DarkXero-dev , you are the developer for XeroLinux... nice to see you in here! I love your KDE customization in your distro, it looks clean and consistent :) keep up the good work!

> We can work together on making this project better.. If you are willing. HyprDots maintainer + Distro Maintainer. Am not saying we should turn this into a full on Distro, just make sure to make it build less from AUR by having our own repo, for a quicker install, and seamless error free experience. @prasanthrangan ;)

ya this repo just has the config files/scripts, so it is easier for me to maintain this, but it takes a lot of time and effort to make this a distro, so i dont think i'll have enough time to do so :(
regarding maintaining our own package repo, no idea if it is simple to maintain it, mainly because hyprland is VERY VERY active in development and its not expected to be stable.


> Creating an entire distro for hyprdots is a lot harder because of the way it's been built. I think however for right now, doing archinstall with minimal desktop, then with the introduction of hyprdots-ctl, it's really not that difficult to install and maintain hyprdots updates anymore.
> 
> I'd love to hear @prasanthrangan opinions on this, and this discussion should definitely continue on a discussion post instead of this issue thread so if you'd like to create one @DarkXero-dev please do!

yup, i agree @Skerse making this a distro requires a lot of time and effort to maintain... But ya @DarkXero-dev feel free to fork this and maintain the packages based your repo, i'll can definitely help you with improving/updating the script and configure pacman.conf

**Comment by DarkXero-dev** [comment]
@prasanthrangan 

Hehe thanks bud.. Just a bit of info, I do not and will not use WMs they do not fit my workflow. However that doesn't mean I cannot help other projects thrive when I can.

That being said all I meant to say is, not fork the project coz I wouldn't know where to start since it's not my thing. I was thinking of sharing ideas, as I did 
==> **[Here](https://github.com/prasanthrangan/hyprdots/discussions/634)**. 

Also let me worry about Repo, we can work on it together, you tell me what needs to be added packages wise leaving rest as it is, just so script doesn't have to build everything from AUR making it takes ages, with potential failures. I maintain 5 repos as it is it's fun for me. We merge heads.. 

Let me know what you think of my ideas on Discussion thread.. I am aware of how **Vaxry** works he was my guest on my show. Video never made the cut but we talked for hours..

**Comment by prasanthrangan** [comment]
> Hey bud, sorry for ping, but I was thinking, do you have a place where we can talk privately ? Discord or something ? I need your help with optimizing your script to make it work better for my needs/setup.. I am no bash expert.. Like work together.. If you have some time.

sure, my discord username is `nagnar.` but i rarely use discord so please expect a delay :)

**Comment by DarkXero-dev** [comment]
@prasanthrangan Will add you no rush .. Check previous message+Discussion.. You also keep forgetting license lol

**Comment by prasanthrangan** [comment]
yup, just added! and saw the discussions page. I'll close this so we can continue in https://github.com/prasanthrangan/hyprdots/discussions/634.
