### ISSUE TITLE
Keyboard Layout Resets to EN System-wide After Changing Theme

### ISSUE THREAD

**Issue by DiegoSof2** [prasanthrangan/hyprdots#63]
Every time I click the button to change the theme, my keyboard layout is reset from PT-BR to EN. What might be causing this, and how can I resolve it?

**Comment by Gedankenn** [comment]
with the latest update there is a file .config/hypr/userprefs.conf
just copy and paste the keyboard config from hyprland.conf to this folder, you will be good to go.

**Comment by DiegoSof2** [comment]
it worked perfectly, thank you very much

**Comment by prasanthrangan** [comment]
Hmm, that's strange, the layout set in `~/.config/hypr/hyprland.conf` should not change while changing theme.
Glad it works by setting it in `.config/hypr/userprefs.conf`, so closing this issue.
