### ISSUE TITLE
Make a single shell script to revert every single change?

### ISSUE THREAD

**Issue by SuppliedOrange** [prasanthrangan/hyprdots#631]
Someone installed this and seemed so utterly lost and confused because it changed everything on their system. Can we not have a single .sh file to revert every possible change? Kind of like an uninstaller. I think that'll make this easier for people who can't understand the code.

**Comment by Skerse** [comment]
I'd be willing to make a config revert shell script, but that's it. I think it should be very clear that you're basically installing an entire heavily themed desktop and using it with other desktops is at your own risk, since the described method of installation is a **minimal** arch installation (likely using archinstall).

**Comment by kRHYME7** [comment]
I tried to write a Backup script to revert my  config to a certain backup directory .

Fortunately  the overwritten configs where inside ~/.config/cfg_backup/cfg*  (latest commit) 

For now, if a user wants to revert, they can easily do that manually by copying those configs on the backup to ./.configs and the zshrc and other overwritten files.  We could push a script for this implementation though.  we could just utilize the ./restore_cfg.sh and append it with the directory and a file control. See ``` ~/Hyprdots/Scripts/restore_cfg.sh ```

**Comment by prasanthrangan** [comment]
Hi, if you are already customized your desktop environment/WM it will backup and overwrite your config files.
The config directory `~/Hyprdots/Configs` and backup dir `~/.config/cfg_backups/*` follows the exact file structure as your $HOME directory, so it should be possible to implement this by overriding the $CfgDir in `restore_cfg.sh` with the backup dir to restore from.

**Comment by kRHYME7** [comment]
> so this is already possible by overriding the $CfgDir in restore_cfg.sh with the backup dir to restore from... so i think all we need is a cli to list the backups and exec restore_cfg.sh with the backup override..

Baking...

**Comment by kRHYME7** [comment]
So, the approach with this is simply to reread the restore list and find if the file exists in the directory, It will just write its restore list and feed to the ./restore_cfg.sh.  The recursive list can also be marked not to be included in the restore funtion. 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a75ad6a4-3644-4892-a164-a9e1b6bf871a)

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/2daadb03-bad4-4c86-ba08-3f568bc0c3ff)


https://github.com/kRHYME7/Hyprdots-ctl

**Comment by prasanthrangan** [comment]
feature implemented in `hyprdots-ctl` thanks to @kRHYME7 !
