### ISSUE TITLE
Rofi element orientation is not consistent

### ISSUE THREAD

**Issue by topazrn** [prasanthrangan/hyprdots#638]
Running `~/.config/hypr/scripts/rofilaunch.sh` with any parameter ( d|w|f ) opens rofi but the elements orientation is not consistent as shown in the video.

[Recording 2023-12-10 at 10.20.44 AM.webm](https://github.com/prasanthrangan/hyprdots/assets/40129033/56028696-31a3-4803-8459-244815cd9b01)

Commenting out the `@media` block seems to fix it.
https://github.com/prasanthrangan/hyprdots/blame/f1c0f9d004c0a76f0ba11d01283c1395e197fcf9/Configs/.config/rofi/styles/style_1.rasi#L112

I've tried changing the `max-aspect-ratio` to lower and higher than my monitor's aspect ratio which is 1.778, but I don't notice any change.

Is there a reason why the `@media` block exists?

```
monitor: 2560x1440@144
hyprland: 0.32.3
rofi: 1.7.5+wayland2
```

**Comment by kRHYME7** [comment]
Hi Does the problem only exist on Style 1?

**Comment by topazrn** [comment]
The problem applies to all of the styles for me. Does the same problem not occur to you?

**Comment by kRHYME7** [comment]
Not, really. Are you on the latest update ?

**Comment by topazrn** [comment]
I wasn't, but even after updating and rebooting, the problem still occurs. Now that I think about it, it broke after I moved to fedora. I'll be back after testing.

**Comment by topazrn** [comment]
Yeah... Tested on both VMs and the problem only happens on fedora. Thanks for confirming @kRHYME7
