### ISSUE TITLE
A problem with screen resolution and mouse cursor while running on a VMware

### ISSUE THREAD

**Issue by Keffori** [prasanthrangan/hyprdots#639]
I wanted to change resolution because it shows only 50% of screen but when running any terminal app system freezes.
And kitty is gone on [video](https://www.youtube.com/watch?v=0xg1XxtqpZI) but theres was a kitty before recording a [video](https://www.youtube.com/watch?v=0xg1XxtqpZI)

**Comment by Skerse** [comment]
That is really weird.. i don't know if it's a hyprdots issue however. It could just be wayland or hyprland not playing well with vmware.

If you want to change resolution you could, once you enter in sddm, go into a separate tty (ctrl + alt + f1-f6) then run `vim ~/.config/hypr/monitors.conf` and enter your preferred configuration on there. `~/.config/hypr/monitors.t2` gives an example configuration.

**Comment by Gl00ria** [comment]
@Keffori 
This a Hyprland/VM issue.

Did you enable 3D Acceleration an mentioned in the [Hyprland wiki](https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#vm)?

Besides, I noticed your Hyprland went into maximized mode **(fullscreen)**, but the actual VM didn't, as you can see big black borders on the sides, thats why waybar went hidden.

Also, install [virtualbox-ext-oracle](https://aur.archlinux.org/packages/virtualbox-ext-oracle) via *yay* then reboot.

NOTE: from a personal experience, hyprland never plays well on a VM.

**Comment by prasanthrangan** [comment]
Hey, you'll have to set the monitor resolution manually in `~/.config/hypr/monitors.conf` as the auto setting does not seem to work in VM.

> NOTE: from a personal experience, hyprland never plays well on a VM.

I agree, I've tried it once and its honestly unusable without gpu passthrough, so please save your sanity :)
