### ISSUE TITLE
Apps and background become black after suspend

### ISSUE THREAD

**Issue by murleo** [prasanthrangan/hyprdots#640]
Steps:
* Installed fresh arch linux
* Installed hyprdots
* Configured monitors.conf
```
monitor = DP-1,2560x1440@165,0x0,1.2
```
* Configured userprefs.conf
```
# scaling
# unscale XWayland
env = GDK_SCALE,1
xwayland {
  force_zero_scaling = true
}

# input
input {
    kb_layout = us,ua
    kb_options = grp:alt_shift_toggle
}

# windowrules
windowrulev2 = opacity 1.00 1.00,class:^(firefox)$
windowrulev2 = opacity 1.00 1.00,class:^(Code)$
windowrulev2 = opacity 1.00 1.00,class:^(code-url-handler)$
windowrulev2 = opacity 0.90 0.90,class:^(kitty)$

windowrulev2 = float,class:^(org.telegram.desktop)$
```
* Installed a few apps (spotify, steam, telegram, chromium, nvchad) 
* Configured spotify and chromium to run using Wayland
* Suspended via wlogout or manually using `systemctl suspend`
* Resumed
* All apps and wallpaper became black. For example,
![231210_15h06m20s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/12598936/a017a7b4-72d8-4c5f-b93c-c686ac580300). However, Chromium-based apps and Firefox seem to go back to normal after navigating between workspaces back and forth. Other apps like kitty, steam have to be restarted. Wallpaper has to be manually changed via `switch wallpaper` button or shortcut. This happens consistently.
* Restarted apps work fine.

Packages:
* linux 6.6.4-arch1-1
* hyprland-git 0.33.1.r3.62a8d0be-1
* nvidia-dkms 545.29.06-1

Specs:
* ASUS ROG Crosshair VIII Dark Hero
* Ryzen 7 5800X3D
* ASUS RTX 2080

**Comment by Gl00ria** [comment]
Nvidia? If yes, then this is an nvidia driver issue of how to preserve video memory after suspend.

See [this from arch wiki](https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend),and [this issue](https://github.com/hyprwm/Hyprland/issues/1728#issuecomment-1571852169) from the Hyprland github page.

**Comment by murleo** [comment]
Thanks! I will try it out.
