### ISSUE TITLE
[FYI] borderangle animation doubling energy consumption

### ISSUE THREAD

**Issue by levnikmyskin** [prasanthrangan/hyprdots#641]
Hey!
This is not really a bug report, but rather a "FYI" report. I noticed that using the configs in this repo, my laptop's battery was dying almost twice as fast.  
I monitored this via `powertop`, and found out that the `borderangle` animation in `~/.config/hypr/animations.conf` is the root cause. If I disable this option, `powertop` (ran as `powertop --html=report.html`), reports ~4 to 5 W consumption (measurements taken while idle, no GUI apps except terminal).  
With the option enabled, instead, we go more around ~8 to 9 W consumption. I believe laptop users should be aware of this. A "powersaving" script might also be added, where all these kind of expensive operations are disabled.

**Comment by kRHYME7** [comment]
Hi @levnikmyskin Can you provide me a markdown list of those suspected expensive operations? I'll try to write some script for this as I am a laptop user too. Thank you.

**Comment by levnikmyskin** [comment]
Hey, that sounds cool!
As I mentioned, the biggest offender is the borderangle animation. Clearly, other animations will impact your battery but not as much. 
I believe there's also an issue with hyprland here, since the borderangle loop is probably ran even when no borders are visible (i.e., no_gaps_when_only).

That said, if you want to write a script, then definitely:  
 - disable the borderangle animation;
- other animations can be disabled too, if you _really_ need to squeeze every possible minute out of your battery;
- Removing blur might also be considered, haven't really measured its impact.

It could also be possible to enable/disable these features depending on whether AC is connected.
For instance, look [here](https://wiki.archlinux.org/title/Power_management#Using_a_script_and_an_udev_rule)

**Comment by levnikmyskin** [comment]
> https://github.com/prasanthrangan/hyprdots/blob/main/Configs%2F.config%2Fhypr%2Fscripts%2Fgamemode.sh
> 
> I guess we can build on top of this Script. 

Yes I guess that would work. However, do monitor the energy consumption with powertop when you disable animation.

Maybe I'm not remembering straight, but I think the borderangle thing was still drawing a lot of power, even though animations were disabled (something must be wrong with hyprland). The only thing that worked was commenting out the animations in the conf

**Comment by SalvaGuirado** [comment]
> https://github.com/prasanthrangan/hyprdots/blob/main/Configs%2F.config%2Fhypr%2Fscripts%2Fgamemode.sh
> 
> I guess we can build on top of this Script.

Hi, any advance on the script? I'm interested on it :)

**Comment by prasanthrangan** [comment]
oh cool, thank you @levnikmyskin for digging into this!
Looks like a enhancement for laptop users, so not sure if I'll be able to help with the script :(
but @kRHYME7 , if you have worked on it please feel free to add  it to this repo, and i'll look into creating a script to set udev rules and integrate it to the main install script.

**Comment by kRHYME7** [comment]
Sure, I'll work on it this week.

**Comment by kRHYME7** [comment]
Hello everyone, I will try to write this but seems like I can't replicate this issue on my end. are we all using hyprland-git ? Also, I'm tracking my Hyprland in btop and it was stable at around 5 - 8 percent CPU ( peaks at below 15 %  if I read at 100 ms) I guess this is not an issue right? Also if you have screenshots on your system output it would be better. 

For now, I'll be working on disabling those mentioned above (Commenting out). Thanks in advance!

**Comment by SalvaGuirado** [comment]
> Hello everyone, I will try to write this but seems like I can't replicate this issue on my end. are we all using hyprland-git ? Also, I'm tracking my Hyprland in btop and it was stable at around 5 - 8 percent CPU ( peaks at below 15 % if I read at 100 ms) I guess this is not an issue right? Also if you have screenshots on your system output it would be better.
> 
> For now, I'll be working on disabling those mentioned above (Commenting out). Thanks in advance!

Hello kRHYME7, thanks for working on this issue. Yes I'm using hyprland-git. If you use powertop you can see battery consumption. Here I attach two screenshots, one with borderangle animation enabled and the other without that animation.
Hope it helps. 
Thanks again.


![Powertop with border animation](https://github.com/prasanthrangan/hyprdots/assets/76570041/6372fe3c-ca53-4fd3-a4ee-cbfaea9f68be)
![Powertop without border animation](https://github.com/prasanthrangan/hyprdots/assets/76570041/4430d5ac-6d64-488a-8b5a-3a9ffac3eb44)

**Comment by kRHYME7** [comment]
Hello! I needed some opinions regarding what to and not to turn off. For now, My progress regarding this, I will host it on [Hyprdots-ctl](https://github.com/kRHYME7/Hyprdots-ctl). As it was user-specific also and @prasanthrangan  mentions about this :
 > a script to set udev rules and integrate it into the main install script.

Therefore while waiting for that is it okay for you that it is on Hyprdots-ctl

I have been thinking about the implementation of this. 
users will run ``` Hyprdots powersave --animation --blur --opacity ``` and so on to disable features.
(So that we can add a help message on ``` Hyprdots powersave ```  as I don't also like to bloat the repos code with help messages IMO)

Specific types will be toggleable. As I find it annoying to disable blur or have solid opacity and if I only want to disable animation. 
If any of this you like to persist you can just add exec-once on the userprefs.conf.

 I would love to have your input regarding this. Thank you

**Comment by SalvaGuirado** [comment]
Hi kRHYME7, everything you propose sounds good to me.
And the line regarding animation in userprefs.conf will be very useful while the script is eventually integrated in the main script :)

**Comment by kRHYME7** [comment]
> Important: For those who want to not use the animation borderangle feature and persist across updates
add this line to your userprefs.conf animation = borderangle, 0 , this wil override the borderangle and disables it


Hi, As for the Issue, as it is an issue regarding Hyprland's implementation of borderangle animation,  this should serve as workaround.  
We could either move this to discussion or add a new discussion focusing on laptop/battery optimization for Hyprdots. (As the issue number was overwhelming).

**Comment by kRHYME7** [comment]
Hello everyone! 

I managed to Add a power section on hyprdots-ctl.

This will persist across reboots therefore you need to run ``` Hyprdots power reset ``` to revert to the usual setting. 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/f4f88b81-a4e3-443e-8425-0e6a99ea0e71)



Please feel free to give some comments on what should be added. Thanks !
https://github.com/kRHYME7/Hyprdots-ctl

Basically, it will source the power_manager.conf file from hyprdots-ctl, Next will modify this file to override the hyprland.conf file.

**Comment by AdrianFerrer1** [comment]
I'm getting 186W firefox + pamac installing packages, that doesn't seem correct, right? its draining like 1% every 2 min

**Comment by kRHYME7** [comment]
>I'm getting 186W firefox + pamac installing packages, that doesn't seem correct, right? its draining like 1% every 2 min

@AdrianFerrer1  Can you please elaborate more ? what do you mean by installing packages? during installation ?  also is firefox draining at idle?

**Comment by AdrianFerrer1** [comment]
> > I'm getting 186W firefox + pamac installing packages, that doesn't seem correct, right? its draining like 1% every 2 min
> 
> @AdrianFerrer1 Can you please elaborate more ? what do you mean by installing packages? during installation ? also is firefox draining at idle?

I meant installing programs, post install of the OS procedures. And Firefox with a couple tabs open, normal use

**Comment by kRHYME7** [comment]
For Firefox it would be helpful to try to run it with no tabs on idle then test it, let's see what we got. 

As installing programs generally use more CPU as you are compiling it on your system.(Completely Normal) 

So would you like to install packages that are pre compiled and pre built?

**Comment by AdrianFerrer1** [comment]
![231224_00h30m19s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/112191768/0fd7d6a7-cac9-44f9-a4dc-017c70d7a305)
+240W on idle ? or am I missing something?

**Comment by kRHYME7** [comment]
Is that when you are running Firefox? That's problematically too much! What version of firefox do you have?

**Comment by levnikmyskin** [comment]
Dude, 250w...are you running a laptop or did you install Linux on a full fledged oven? 😅

Jokes aside, that is clearly impossible on a laptop. Your battery will likely have a capacity of ~60 watts (a little more if you have a gaming laptop). Even if you were running on AC, usually chargers cannot draw more than 120w, your laptop would explode.
So...measurements are clearly not correct, maybe try the powertop calibration https://wiki.archlinux.org/title/Powertop#Calibration_to_prevent_inaccurate_measurement

**Read the wiki**: your laptop will do all kinds of stuff, don't touch it until calibration is finished (your screen might stay off for a good minute or more)

**Comment by AdrianFerrer1** [comment]
I just did a calibration and it ended and it is still saying 220W

**Comment by levnikmyskin** [comment]
that's pretty bad, but it definitely is a bad measurement. As I explained before, it would be impossible to draw that much power from a laptop. I guess the html powerreport gives the same thing? Anyways, this is not related to hyprland or hyprdots in any way, unfortunately :/

**Comment by AdrianFerrer1** [comment]
> that's pretty bad, but it definitely is a bad measurement. As I explained before, it would be impossible to draw that much power from a laptop. I guess the html powerreport gives the same thing? Anyways, this is not related to hyprland or hyprdots in any way, unfortunately :/

I mean, https://superuser.com/questions/1487064/why-tick-sched-timer-uses-so-much-power-on-linux , it looks pretty related idk

**Comment by levnikmyskin** [comment]
How is that related to Hyprland or this repo? Once again, the measurements you are reading are wrong, you cannot draw 250w from a laptop.  
You said 1% every 2 mins, which means 200 mins of battery life. That's more than 3 hours, which depending on the laptop you own, could actually be pretty good. It's anyways _nowhere_ even close to the measurements reported by powertop (which would mean instant death of your laptop basically lol). The compositor, or this repo settings, can impact your battery life (as it might be clear from this whole issue, disable borderangle animation if that's your concern), but nothing can ever have such a huge impact. If I were you, I'd try to investigate why powertop is reporting such bullshit measurements

**Comment by kRHYME7** [comment]
@AdrianFerrer1   This is not related to Hyprdots though.
But that's an absurd Wattage displayed, I think you might need to use other top packages to monitor. Maybe btop or htop

**Comment by kRHYME7** [comment]
At your convenience can you test this?  #699

**Comment by AdrianFerrer1** [comment]
> At your convenience can you test this? #699

is it supposed to bring down the number of tick events? if so I think its working!
![231227_16h50m21s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/112191768/93bfd5e1-6b6e-49e6-8c03-7e8fdd66026e)

**Comment by kRHYME7** [comment]
I don't know how to read it but what is the number of events before?

**Comment by AdrianFerrer1** [comment]
> I don't know how to read it but what is the number of events before?
> 
> Aha! The current script uses wildcards '*' to parse a directory which causes globbing and becomes expensive. The PR just iterates it on the specific target which limits the events up to the number of Batteries not the number of subdirectories. Thanks! not expecting this LOL.
> 
> *Sorry for that explanation I might have forgotten about this so I wrote it here. Thanks!
> 
> By the way, the feature I want to share also is you can add `Hyprdots power save [--options]` in the config file of batterynotify. So you can run a script if you remove a charger or if the laptop is discharging or it reaches its threshold.

![231227_18h41m54s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/112191768/ff811811-eb83-41e3-b180-f6f8055c9114)
there? replacing (\"\")?

**Comment by kRHYME7** [comment]
No, 

Editing should be on the  generated config file at ~/.config/hypr/hyprdots-ctl/batterynotify.conf 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/98ff38d7-c0a4-4c30-9a57-2762f3322086)

**Comment by kRHYME7** [comment]
@levnikmyskin  Hello  #699 has already been merged and ``` Hyprdots power save [opts] ``` is possible now, I guess we can move this warning to the WIKI? so we can close this as an issue? 



options for ``` Hyprdots power save ```
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/8dffd254-e799-4aa8-aeb4-558f4c5a7748)


Options of the batterynotify script
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/7d54a3c0-3886-4f61-b136-934951e16b41)

**Comment by levnikmyskin** [comment]
Hey! I guess as long as users know about this script, then there's no need to keep this open or move it somewhere else
