### ISSUE TITLE
Wallpaper Resets after (mirrored) Monitor Change

### ISSUE THREAD

**Issue by Lightgaming** [prasanthrangan/hyprdots#642]
Hey, I just installed Hyprdots and I have a slight problem when mirroring my Laptop Screen. 

I set my monitor config to this
`monitor = ,highres,auto,1,mirror,HDMI-A-1`

And now **when I plug in another Monitor, it displays the default hyprland Wallpaper and not the swww wallpaper.** 
When I use the SUPER+CTRL+W Wallpaper and select it again, it fixes it, but I don't want to do that everytime.  

Any ideas what the problem could be?

**Comment by prasanthrangan** [comment]
Hey, have you configured both of your monitors in `monitors.conf`?
also please check if each of your port is shown in swww cache `~/.cache/swww/`

**Comment by kRHYME7** [comment]
Hi @Lightgaming 
dunno yet on how to trigger  swww for caching a monitor wallpaper but you can add this line 

``` exec-once = Hyprdots run events ``` this watches hyprland events, when events like plugging of monitor 
occurs it automatically loads again the wallpaper

this is the command used to reload the wallpaper 
``` swww img "$(awk -v home=$HOME -F'|' '$1 == 1 {gsub("~", home, $4); print $4}' "$HOME"/.config/hypr/theme.ctl)" ```

**Comment by Lightgaming** [comment]
Hey @prasanthrangan 

Yes I have configured them in my monitors.conf and they are also in `~/.cache/swww/`

![image](https://github.com/prasanthrangan/hyprdots/assets/18364007/55d9da39-cbcd-4973-bbdf-1a23568c8567)

@kRHYME7 `exec-once = Hyprdots run events` doesn't work for me. When I try to run the sww command you posted I get this error `Error: "Socket file not found. Are you sure swww-daemon is running?"`

So I guess **swww is crashing when I connect/disconnect a monitor**. Because when I do `swww init` the wallpaper is fixed again. 

[My Fix]

I added **`exec-once = swww init`** to my hyprland.conf and that seems to fix it :)

**Comment by kRHYME7** [comment]
@Lightgaming  Hello, can you confirm if changing monitors make swww crash? 🙏

**Comment by xk67** [comment]
Yes, the problem still exists, currently in version 0.9.1.
Visit https://github.com/LGFae/swww/issues/196

**Comment by abenezerw** [comment]
Could you close as solved if you no longer have this issue. Thank you @Lightgaming
