### ISSUE TITLE
QUESTION: how to remove visual studio code?

### ISSUE THREAD

**Issue by itsmenewbie03** [prasanthrangan/hyprdots#646]
### What?
- I want to remove `vscode` from my system. I'm new to arch based distro, i tried `yay -R code` and it doesn't work.
### Why?
- I switched IDE from `vscode` to `neovim` last month and I don't use `vscode` anymore. So I want to remove it for the extra storage space.

**Comment by itsmenewbie03** [comment]
I am posting the question here as `vscode` is installed by this dots.

**Comment by Gl00ria** [comment]
> ### What?
> - I want to remove `vscode` from my system. I'm new to arch based distro, i tried `yay -R code` and it doesn't work.
> ### Why?
> - I switched IDE from `vscode` to `neovim` last month and I don't use `vscode` anymore. So I want to remove it for the extra storage space.

[This is the PKG name](https://github.com/prasanthrangan/hyprdots/blob/main/Scripts%2Fcustom_hypr.lst#L51), use `yay -Rns PKGNAME`

**Comment by itsmenewbie03** [comment]
> > ### What?
> > 
> > * I want to remove `vscode` from my system. I'm new to arch based distro, i tried `yay -R code` and it doesn't work.
> > 
> > ### Why?
> > 
> > * I switched IDE from `vscode` to `neovim` last month and I don't use `vscode` anymore. So I want to remove it for the extra storage space.
> 
> [This is the PKG name](https://github.com/prasanthrangan/hyprdots/blob/main/Scripts%2Fcustom_hypr.lst#L51), use `yay -Rns PKGNAME`

Thank you.
