### ISSUE TITLE
install script fails

### ISSUE THREAD

**Issue by olsen-jo** [prasanthrangan/hyprdots#650]
installing on minimal eOS

`Installing extensions...
Error while installing extensions: read ECONNRESET
read ECONNRESET`

then kicks me out of install script
i've done this install a number of times on this computer and this is the first time i've had trouble. anyone know what this means or what i can do?

**Comment by olsen-jo** [comment]
okay so second try failed at same place, third try it went through, here is the output after the usual fail spot. So my problem is solved but maybe will happen to someone else.

Installing extensions...
(node:2381) [DEP0005] Deprecation₩arning: Buffer() is deprecated due to security and usability issues. Please use the Buffer .alloc(), Buffer.allocUnsafe(), or Buffer. front methods instead
Installing extension 'catppuccin.catppuccin-usc'..
(Use `code trace-deprecationto show where the warning was created)
Extension 'catppuccin.catppuccin-usc' 03.8.2

**Comment by Skerse** [comment]
I'll definitely look into this later, i remember the install script giving warnings when installing some vscode extensions about being deprecated but i just ignored it because it didn't seem to cause issues at the time. If there is something we need to fix in our script i'll try to fix it.

**Comment by olsen-jo** [comment]
yall r lovely :) hopefully it can help you in some way.
