### ISSUE TITLE
Which packages will this script install for Nvidia card?

### ISSUE THREAD

**Issue by valerii15298** [prasanthrangan/hyprdots#656]
Can you tell please which packages will this script install for `GeForce GTX 1660 Ti` card(code for this card is **NV168**)?
Which packages using pacman or AUR will this script install in such case? I cannot find it in the code unfortunately…

Can’t understand this part of code:
```bash
    if nvidia_detect; then
        cat /usr/lib/modules/*/pkgbase | while read krnl; do
            echo "${krnl}-headers" >>install_pkg.lst
        done
        IFS=$' ' read -r -d '' -a nvga < <(lspci -k | grep -E "(VGA|3D)" | grep -i nvidia | awk -F ':' '{print $NF}' | tr -d '[]()' && printf '\0')
        for nvcode in "${nvga[@]}"; do
            awk -F '|' -v nvc="${nvcode}" '{if ($3 == nvc) {split(FILENAME,driver,"/"); print driver[length(driver)],"\nnvidia-utils"}}' .nvidia/nvidia*dkms >>install_pkg.lst
        done
    else
        echo "nvidia card not detected, skipping nvidia drivers..."
    fi
```

I see `nnvidia-utils` there but it is not the only package that will be installed if nvidia card is detected I guess…

**Comment by Skerse** [comment]
I don't have an nvidia gpu, but i can say for sure that it's detecting for an nvidia gpu then adding the necessary packages to install in `install_pkg.lst`. So i guess if you want to know what packages it's installing, look in `install_pkg.lst` after you run that part of the script.

**Comment by valerii15298** [comment]
@Skerse, thanks! I figured that out, but I wanted to know which exactly packages without executing this script...
Just where is this hashMap of which packages should be installed for which card code...

**Comment by kRHYME7** [comment]
Please Try to run the script without
```
 >>install_pkg.lst
 ``` 



That part won't install anything.

**Comment by prasanthrangan** [comment]
hey @valerii15298 , it will install the linux headers for the kernels you have installed -
```
linux-lts-headers
linux-headers
linux-zen-headers
```
and just the bare minimum nvidia packages and dkms driver for your card `GeForce GTX 1660 Ti` which is `nvidia-dkms` -
```
nvidia-dkms
nvidia-utils
```

the code is very straight forward -
```
❯ awk -F '|' '{if ($3 == "TU116") {split(FILENAME,driver,"/"); print driver[length(driver)],"\nnvidia-utils"}}' .nvidia/nvidia*dkms
nvidia-dkms 
nvidia-utils
```

so the part of code you are referring -
It just reads the GPU code names from `lspci` command.
This gpu code works like a unique primary key to lookup column 3 from this list [here](https://github.com/prasanthrangan/hyprdots/blob/main/Scripts/.nvidia/nvidia-dkms), and finally use the filename (which is same as package name) from which the gpu code match was found.
