### ISSUE TITLE
How to Have Double Waybars 

### ISSUE THREAD

**Issue by RookiexCookie** [prasanthrangan/hyprdots#657]
Hey i wanna ask 
if there is a way to have 2 waybars simultaneously  1 at the bottom and 1 at the top like this?
![double_waybars](https://github.com/prasanthrangan/hyprdots/assets/136296017/26055ce9-f8de-41bb-b241-4cf9dbbca7a1)

Someone did it with adding top and bottom group in the main waybar conf file 
https://github.com/ldelossa/dotfiles/blob/e23c50698633ef0af767e37df1929d3caccbc7f1/config/waybar/config 

so how do that in the config.ctl 
writing directly in the conf file will be a waste of time since it will be overwritten by the script
 
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/a62ba456-f1fa-4af2-a1fe-8ece58789b02)

?

**Comment by opticblu** [comment]
fork the repo, add your changes, then the script will write your updated config, sync your repo with updates, git pull, boom

it's not like it's summoning config files from some proprietary magic, config files in this repo are structured like they are once installed

also pretty sure the script, to some degree, backs up and restores changes? not sure what all it covers,  can someone double check me on that

**Comment by kRHYME7** [comment]
It backs up configs and restores what is in the repository. So for now to have persistent changes is to fork this repo.

**Comment by RookiexCookie** [comment]
um are we talking about the same thing? im sorry if i wasnt clear
 I was talking about wbarconfgen.sh script which from what i understood when i press super+alt+up or down it executes that script which reads from the config.ctl and grab all the modules and rewrite the wbar config

**Comment by prasanthrangan** [comment]
Hey, currently `wbarconfgen.sh` will rewrite your waybar config based on `config.ctl` and only supports single line for a single bar.
you can remove this script and use hardcoded waybar config manually for 2 simultaneous bars.

generating 2 bars with `wbarconfgen.sh` would require a rewrite and extra ctl file (for bar 2) to implement this, so i'll look into it when i get a chance, but this will be low priority.
