### ISSUE TITLE
HINT in Waybar

### ISSUE THREAD

**Issue by FuckingToasters** [prasanthrangan/hyprdots#660]
Before I installed this hyperland script.inused another one and in this other script waybar was configured in a way to include a hint section which show the keybjnds. Such section don't seem to exist in this one or I'm too stupid to locate it.

I'd like to add such a hint section back but don't know how. Would be great if anyone here could help me.

**Comment by Skerse** [comment]
You should be looking at this pull request here: https://github.com/prasanthrangan/hyprdots/pull/477, which will hopefully be included soon.

**Comment by kRHYME7** [comment]
@FuckingToasters I see can you share what dots were? So we could see how was that implemented

**Comment by FuckingToasters** [comment]
> @FuckingToasters I see can you share what dots were? So we could see how was that implemented

https://github.com/JaKooLit/Arch-Hyprland/tree/main

**Comment by prasanthrangan** [comment]
Hi, I'll close this as pull request #477 is in the works.

**Comment by kRHYME7** [comment]
Hello @FuckingToasters  If you are usng this dots write now Maybe this is useful for you 
Running ``` Hyprdots show binds ```: 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/2a5cbab2-d2f9-4a2a-98d2-3f8e3826fcad)

You may add this to your ./userprefs.conf as keybinding. 

if you don't have the package yet here is the installation.
https://github.com/kRHYME7/Hyprdots-ctl
