### ISSUE TITLE
grep: /home/emhk/.config/hypr/theme.ctl: No such file or directory 

### ISSUE THREAD

**Issue by endermeme** [prasanthrangan/hyprdots#661]
help me

**Comment by Skerse** [comment]
I'm confused on what you want help with, please add a lot more information than just a single error message with no context.

**Comment by kRHYME7** [comment]
Hello, Based on your post please reinstall the dotfiles or run  ``` ./install.sh -r ```

Or 

You can use this tool to cater to some things for you 
https://github.com/kRHYME7/Hyprdots-ctl

after installingt this 

Run
 ```
 Hyprdots update
```
then run :
```
Hyprdots reinstall fresh
```

**Comment by prasanthrangan** [comment]
Hey, please provide more details.
we can only guess that the install script did not complete its run. so please try to reinstall.

**Comment by kRHYME7** [comment]
@endermeme Hello, feel free to reopen this issue if you need help relating to this.  We needed more details to solve this issues, don't hesitate to ask. For now, we will close this one.
