### ISSUE TITLE
Using custom Screenshot Tool

### ISSUE THREAD

**Issue by FuckingToasters** [prasanthrangan/hyprdots#668]
Hello, I'd like to change the current way of making an screenshot to use another program instead, mainly because the current way of making screenshots don't work as expected for me.

I used another hyperland installation script before (https://github.com/JaKooLit/Arch-Hyprland/tree/main) which used the tool called swappy (https://github.com/jtheoof/swappy)

I'd like to use swappy with hyperdots, would be nice if somebody can help me there.

Regards,
FuckingToasters

**Comment by kRHYME7** [comment]
Hi, I remembered  Hyprdots have swappy after a screenshot a while ago but something might have changed. I'll try to test it out.

**Comment by kRHYME7** [comment]
I see can you please install grimblast on your system ? 

yay -Sy grimblast
paru -Sy grimblast

**Comment by FuckingToasters** [comment]
> I see can you please install grimblast on your system ?
> 
> yay -Sy grimblast paru -Sy grimblast

yep, i can read the error msg xd, i just installed it and works now, thank you for your help ;)
