### ISSUE TITLE
Can't lock system

### ISSUE THREAD

**Issue by FuckingToasters** [prasanthrangan/hyprdots#670]
My Keybind is as follows:
```
bind = $mainMod, L, exec, swaylock # lock screen
```

When i press the keybind, nothing happens.

I tried to manually execute the `swaylock`command which casued following error:
`2023-12-18 15:25:31 - [main.c:1824] Compositor does not support the input inhibitor protocol, refusing to run insecurely`

Not that logging out via the logout menu works fine.

If more informations are needed, don't hestiate to hmu

Regads,
Infinimonster

**Comment by kRHYME7** [comment]
Hi can you run this ? 

 ``` pacman  -Q  swaylock ```

**Comment by FuckingToasters** [comment]
> swaylock

swaylock-effects 1.6.4-2

**Comment by kRHYME7** [comment]
Nice! have you tried upgrading the package or using the git version?

**Comment by FuckingToasters** [comment]
> Nice! have you tried upgrading the package or using the git version? 
> 
> Edit: 
> I see, it was the issue of wlroots protocol. 
> 
> In case you want some readings... As of now, my sway lock is running fine using the git version. 
> also swaylock 1.7... works try to upgrade yours.
> 
> https://github.com/hyprwm/Hyprland/issues/3932
> https://github.com/jirutka/swaylock-effects/issues/55

I now have the 1.7 version and I can open it but when pressing keys and then hitting enter, it tells me "Wrong" and I don't know how to change that.

**Comment by kRHYME7** [comment]
Is there any way I can replicate this issue? 

I guess it has many issues on the hyprland github page. 

Here is a list: https://github.com/hyprwm/Hyprland/issues/4150#issuecomment-1854422449, this should be a good read.

 I think try to install the ``` swaylock-effects-git ``` incase 1.7.0 is not working. ()
 
 This might be very confusing as all of this version are forks. 
 
I suggest you install swaylock-effects-git then if it becomes buggy revert back to swaylock-effects. (Revert them back and forth)

**Comment by FuckingToasters** [comment]
> Is there any way I can replicate this issue? 
> 
> I guess it has many issues on the hyprland github page. 
> 
> Here is a list: https://github.com/hyprwm/Hyprland/issues/4150#issuecomment-1854422449, this should be a good read.
> 
>  I think try to install the ``` swaylock-effects-git ``` incase 1.7.0 is not working. ()
>  
>  This might be very confusing as all of this version are forks. 
>  
> I suggest you install swaylock-effects-git then if it becomes buggy revert back to swaylock-effects. (Revert them back and forth)
> 

This version has the same issue, which is that after opening swaylock, it shows a circle with the time and date in if, if I then press any key, parts of the circle will be colored, when I then press enter, the text inside the circle becomes changed to "verifying" and after some time it becomes changed to "Wrong" so I can't get into the system anymore without a reboot if I have it locked.

**Comment by prasanthrangan** [comment]
Hi, you can also give `gtklock` a try!

**Comment by FuckingToasters** [comment]
> Hi, you can also give `gtklock` a try!

Well, i'm not sure how i can make it work with hyprdots but when i run gtklock manually i get following issue:

```
(gtklock:20971): Gtk-WARNING **: 18:48:52.459: Theme parsing error: gtk.css:6691:68: Invalid name of pseudo-class

** (gtklock:20971): WARNING **: 18:48:52.508: Custom style loading failed: style.css:3:20not a number

** (gtklock:20971): CRITICAL **: 18:48:52.515: Your compositor doesn't support wlr-input-inhibitor
```

**Comment by kRHYME7** [comment]
What version of Hyprland Are you on?

**Comment by kRHYME7** [comment]
I'll be closing this as unrelated to the Config files.

Be sure to test it on Hyprland official release and hyprland-git versions.  
Please reopen if necessary.
