### ISSUE TITLE
Can't apply updates from the repo

### ISSUE THREAD

**Issue by Ramy-Ashraf** [prasanthrangan/hyprdots#671]
This is what I get running ./install.sh -r:

![231218_17h10m39s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/85342902/71b640b2-e138-48c4-b7e5-58d07ffbe669)

**Comment by kRHYME7** [comment]
Hi @Ramy-Ashraf  What happens if you run this on your terminal ``` fc-cache -f  ```

**Comment by Ramy-Ashraf** [comment]
Sorry for replying late.
I get same error message.

![image](https://github.com/prasanthrangan/hyprdots/assets/85342902/431d94c4-9a4c-436f-b437-7bf2053f46c4)

**Comment by kRHYME7** [comment]
I see, can you provide the full output for this?  ``` fc-cache -fv ``` ? Also, what happens if you run it with sudo?

**Comment by prasanthrangan** [comment]
Hi, did the script extract the fonts properly?
try rerunning it.
