### ISSUE TITLE
Mouse movement is not smooth

### ISSUE THREAD

**Issue by endermeme** [prasanthrangan/hyprdots#673]
I have successfully installed your dotfiles on my computer, but I notice that when I move the mouse quickly with either the touchpad or an external mouse, it all appears sporadic, not very smooth, please help me.

https://github.com/prasanthrangan/hyprdots/assets/91008703/e2b306dd-613d-4263-a9f8-e389851ffc01

**Comment by endermeme** [comment]
I realized it only happens when I use it in the application

**Comment by prasanthrangan** [comment]
Hi, can you please try it with default autogenerated `hyprland.conf` file?

**Comment by kRHYME7** [comment]
Please reopen if necessary.
