### ISSUE TITLE
How can I install and setup Gujarati phonetic keyboard ?

### ISSUE THREAD

**Issue by gujlaw** [prasanthrangan/hyprdots#675]

**Comment by Skerse** [comment]
I don't think this issue really relates to Hyprdots that much, so you probably won't get much help here, i'd recommend looking elsewhere. A quick search online, it up it seems to be a keyboard layout i've never heard of, but it seems to be a really small thing, even more so with Linux and Hyprland so i don't even know where to start with it, sorry.
