### ISSUE TITLE
Primary GPU; Not Found

### ISSUE THREAD

**Issue by theCode-Breaker** [prasanthrangan/hyprdots#677]
Thank you @prasanthrangan for your hard work. I was able to fix the scaling issue but I not able to fix this

![image](https://github.com/prasanthrangan/hyprdots/assets/83777943/1272d3c2-0280-420e-8b02-ef68febaf49a)
 
![image](https://github.com/prasanthrangan/hyprdots/assets/83777943/2d7a8ebf-1d0c-4e25-b0a8-fe762c3acba7)

❯ lspci -v | grep -A 12 "VGA controller"
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] (rev c4) (prog-if 00 [VGA controller])
	DeviceName:  Onboard IGD
	Subsystem: Hewlett-Packard Company Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series]
	Flags: bus master, fast devsel, latency 0, IRQ 24, IOMMU group 10
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at f0000000 (64-bit, prefetchable) [size=2M]
	I/O ports at e000 [size=256]
	Memory at fcd00000 (32-bit, non-prefetchable) [size=512K]
	Capabilities: <access denied>
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu

**Comment by Skerse** [comment]
This is definitely an issue, i have it as well with this repo and have been working on a fix with explanations in: https://github.com/prasanthrangan/hyprdots/pull/643

I'd love to know if my gpuinfo.sh script works for you, so if you can and want to, install lact (An amdgpu controller) and nmap with by doing either: `paru -S lact nmap` or `yay -S lact nmap` then do sudo systemctl enable --now lactd.service. After, download my gpuinfo.sh script from [here](https://gist.github.com/Skerse/e23a6ee99da36a24f9b7b3bb3ec30c21) and replace the current file used in `~/.config/hypr/scripts`. If that works for you please let me know!

Remember, you can always revert this by uninstalling the packages and restoring the configs with `./install.sh -r`.

**Comment by theCode-Breaker** [comment]
@Skerse

**Comment by theCode-Breaker** [comment]
@Skerse
![image](https://github.com/prasanthrangan/hyprdots/assets/83777943/adfd5866-edad-43ae-a52c-e5ffedf67023)
![image](https://github.com/prasanthrangan/hyprdots/assets/83777943/83ef82d0-0d79-4ab4-b2bb-c614f784a083)

**Comment by Skerse** [comment]
Oh well, sorry it didn't work.. I do want to make it better however, so if you wouldn't mind running this script [here](https://gist.github.com/Skerse/bee3f28ebd3ecc190712ac9882a6dc41) and giving me it's output to see what is different about your gpu output, that would be really great!

**Comment by zaneschepke** [comment]
I am getting this same issue with a Nvidia 3070

**Comment by theCode-Breaker** [comment]
@Skerse 

![image](https://github.com/prasanthrangan/hyprdots/assets/83777943/22b60caa-0522-4711-9641-4edc2c066439)

**Comment by hamzawcchan** [comment]
i have the same problem. looks like i have the same gpu as theCode-Breaker
![231224_20h58m24s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/123036274/54f67ca3-b487-4f56-986f-46824bd30902)

**Comment by kRHYME7** [comment]
Hi, I'm trying to add a Feature #643. Can I have the output if you run ``` sensors ```. Happy holidays!

**Comment by Skerse** [comment]
For me at least it seems that sensors wouldn't work to get that much gpu information as we can currently, which is why i looked for hours to look for a solution that might work better for everyone.

In my opinion my solution looks promising just i might have a lot to look into all the outputs to figure out how to support almost every gpu (which thank you @theCode-Breaker and @hamzawcchan that really helps a lot). I want to continue to work on it but i hope i don't annoy people if i want to ask for people to see if it works..

Also @kRHYME7 i don't want to conflict with your work with the script. I'd be happy to work with you if you want, but i kind of don't know what to do.

On a kind of unfortunate note: I'm away from my home for a week with my family so i will be unable to do much development changes, and i'll be less active in general to respond until i get back.

**Comment by kRHYME7** [comment]
@Skerse Have a safe trip man! My goal to have sensors output at least the temp is to at least minimized those issues of having "N/A" displayed. As I can see some user didn't care as long as they have temps displayed( As Intel GPU uses sensors on this script). 

> Also @kRHYME7 i don't want to conflict with your work with the script. I'd be happy to work with you if you want, but i kind of don't know what to do.

I'll be happy to work with you, as I am trying my best to search methods for AMD too.
 On the gpuinfo script there is a function "amd_gpu" you can call your script with it like how amdgpu.py script works or call a separate function that gives AMD GPU information. Then the script will handle what to query and it will continue to query for it. 

If everything fails like every function can't give temperature we will call the sensors function just to have a consistent output not just N/A. What can you say about it? Happy Holidays!

**Comment by Skerse** [comment]
> My goal is to have sensors output at least the temp, to minimized those issues of having "N/A" displayed. As I can see some user didn't care as long as they have temps displayed.

That's fair, at least it'll be better than N/A. Sensors should at least give enough information to display temperature. Implementation is quite easy as well as a fallback.

> On the gpuinfo script there is a function "amd_gpu" you can call your script with it like how amdgpu.py script works or call a separate function that gives AMD GPU information. Then the script will handle what to query and it will continue to query for it.

That should work, i actually like that better since it shouldn't be doing anything to conflict with your work and future development shouldn't be difficult to understand hopefully!

**Comment by theCode-Breaker** [comment]
> Hi, I'm trying to add a Feature #643. Can I have the output if you run `sensors`. Happy holidays!

![image](https://github.com/prasanthrangan/hyprdots/assets/83777943/928da4aa-da79-47ec-845d-43b6e836f669)

**Comment by kRHYME7** [comment]
@theCode-Breaker  Hello Can I have the full text format for this? 

``` sensors | wl-copy ``` That should put the output in the clipboard.  I will try to use this for testing purposes Thanks!

**Comment by theCode-Breaker** [comment]
> @theCode-Breaker Hello Can I have the full text format for this?

amdgpu-pci-0400
Adapter: PCI adapter
vddgfx:           N/A  
vddnb:            N/A  
edge:         +33.0°C  

k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +33.2°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:          11.49 V  

nvme-pci-0100
Adapter: PCI adapter
Composite:    +34.9°C  (low  = -273.1°C, high = +81.8°C)
                       (crit = +84.8°C)
Sensor 1:     +34.9°C  (low  = -273.1°C, high = +65261.8°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +32.0°C

**Comment by kRHYME7** [comment]
Hello! @theCode-Breaker  Added a General Query, (Discussed at #643 )
this will give at least Temperature and hopefully other values
Here is the updated version, Please follow @Skerse  instructions on updating the script on your system.
>. After, download my gpuinfo.sh script from [here](https://raw.githubusercontent.com/kRHYME7/KhingDom/GPUinfo/Configs/.config/hypr/scripts/gpuinfo.sh
) and replace the current file used in ~/.config/hypr/scripts.

https://raw.githubusercontent.com/kRHYME7/KhingDom/GPUinfo/Configs/.config/hypr/scripts/gpuinfo.sh


Some expected output will be like this 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c15fa325-29b6-418a-927c-79bb788a51db)

if there where errors please try to run this: (To see if your system gives output for each)

```
temperature=$(sensors | grep -E "(Package id.*|edge|another keyword)" | awk -F ':' '{print int($2)}')
if [ -f /sys/class/power_supply/BAT*/power_now ]; then power_usage=$(awk '{print $1*10^-6 " "}' /sys/class/power_supply/BAT*/power_now)
else power_discharge=$(awk -v current="$(cat /sys/class/power_supply/BAT*/current_now)" -v voltage="$(cat /sys/class/power_supply/BAT*/voltage_now)" 'BEGIN {print (current * voltage) / 10^12 ""}')
fi
utilization=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1" "}')
current_clock_speed=$(awk '{sum += $1; n++} END {if (n > 0) print sum / n / 1000 ""}' /sys/devices/system/cpu/cpufreq/policy*/scaling_cur_freq)
 max_clock_speed=$(awk '{print $1/1000}' /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)

echo "Temp: $temperature"
echo "Power: $power_usage and $power_discharge"
echo "utilization: $utilization"
echo "Clock: $current_clock_speed and $max_clock_speed"
```

Thanks !

**Comment by theCode-Breaker** [comment]
> Hello! @theCode-Breaker Added a General Query, (Discussed at #643 ) this will give at least Temperature and hopefully other values Here is the updated version, Please follow @Skerse instructions on updating the script on your system.

![image](https://github.com/prasanthrangan/hyprdots/assets/83777943/83ab6102-9b28-4a4f-954a-59dc287b8a08)

**Comment by kRHYME7** [comment]
Oh, oh, I missed a single line, Sorry for that,  Please retry the same link as above. Thanks for your patience. 


Also Maybe can we have the output for this? 
```
temperature=$(sensors | grep -E "(Package id.*|edge|another keyword)" | awk -F ':' '{print int($2)}')
if [ -f /sys/class/power_supply/BAT*/power_now ]; then power_usage=$(awk '{print $1*10^-6 " "}' /sys/class/power_supply/BAT*/power_now)
else power_discharge=$(awk -v current="$(cat /sys/class/power_supply/BAT*/current_now)" -v voltage="$(cat /sys/class/power_supply/BAT*/voltage_now)" 'BEGIN {print (current * voltage) / 10^12 ""}')
fi
utilization=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1" "}')
current_clock_speed=$(awk '{sum += $1; n++} END {if (n > 0) print sum / n / 1000 ""}' /sys/devices/system/cpu/cpufreq/policy*/scaling_cur_freq)
 max_clock_speed=$(awk '{print $1/1000}' /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)

echo "Temp: $temperature"
echo "Power: $power_usage and $power_discharge"
echo "utilization: $utilization"
echo "Clock: $current_clock_speed and $max_clock_speed"
```

**Comment by theCode-Breaker** [comment]
Thanks @kRHYME7 

![image](https://github.com/prasanthrangan/hyprdots/assets/83777943/d3cd14b8-93e3-4a54-82b9-2426fb212ae4)

> Also Maybe can we have the output for this?

![image](https://github.com/prasanthrangan/hyprdots/assets/83777943/c4bcc06d-3e20-4773-8192-f1621e83842c)

**Comment by hamzawcchan** [comment]
@kRHYME7 
![231226_23h11m24s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/123036274/f567c66f-9d98-47ce-ba90-d78b63af516b)

**Comment by kRHYME7** [comment]
Thanks @hamzawcchan.

**Comment by hamzawcchan** [comment]
Hi @kRHYME7 
almost. butthe temperature is not showning on the waybar though.
![231227_11h51m36s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/123036274/469b83f5-704c-4522-ae1d-77d781ea675c)

**Comment by kRHYME7** [comment]
can You provide `` cat ~/.config/waybar/config.ctl ```

**Comment by hamzawcchan** [comment]
@kRHYME7 

❯ cat ~/.config/waybar/config.ctl
0|28|bottom|( cpu memory custom/gpuinfo ) ( custom/audio_idle_inhibitor idle_inhibitor clock )|( hyprland/workspaces hyprland/window )|( backlight network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
1||top|( hyprland/workspaces hyprland/window )|( custom/audio_idle_inhibitor idle_inhibitor clock )|( cpu memory custom/gpuinfo ) ( backlight network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
0|31|bottom|( custom/power custom/cliphist custom/wbar custom/mode custom/wallchange ) ( wlr/taskbar custom/spotify ) |( custom/audio_idle_inhibitor idle_inhibitor clock )|( tray battery ) ( backlight network bluetooth pulseaudio pulseaudio#microphone )
0|32|top||( custom/power ) ( tray battery ) ( wlr/taskbar custom/audio_idle_inhibitor idle_inhibitor clock ) ( custom/cliphist ) ( custom/wbar ) ( custom/wallchange ) ( custom/mode )|
0|31|bottom|( cpu memory custom/gpuinfo ) ( custom/audio_idle_inhibitor idle_inhibitor clock ) ( hyprland/workspaces )|( wlr/taskbar )|( backlight network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
0|29|top|( wlr/taskbar mpris )|( custom/audio_idle_inhibitor idle_inhibitor clock )|( backlight network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/wbar custom/cliphist custom/power )
0|28|bottom|( custom/power custom/cliphist custom/wbar custom/mode custom/wallchange ) ( custom/audio_idle_inhibitor idle_inhibitor clock custom/spotify )|( wlr/taskbar )|( tray ) ( backlight network bluetooth pulseaudio pulseaudio#microphone )

**Comment by kRHYME7** [comment]
Have you tried toggling the waybar? or running ``` waybar ``` in terminal.  Just be sure the active ~/.config/waybar/config.ctl  have 'custom/gpuinfo' in the line.

**Comment by hamzawcchan** [comment]
@kRHYME7 

hi, i found out its file permission problem. it is working now. thx for your help

**Comment by KitsuneKode** [comment]
> Thanks @kRHYME7
> 
> ![image](https://private-user-images.githubusercontent.com/83777943/292844466-d3cd14b8-93e3-4a54-82b9-2426fb212ae4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0Njk2NzQsIm5iZiI6MTcxNDQ2OTM3NCwicGF0aCI6Ii84Mzc3Nzk0My8yOTI4NDQ0NjYtZDNjZDE0YjgtOTNlMy00YTU0LTgyYjktMjQyNmZiMjEyYWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA5MjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYmQzOWZmMjE3MjZhYjA4ZDkwOWFhNDczMDVlMGY2ZTQzZDY1YWQ5YmFjMmQyOTZhY2QyZGI2ZmNiNzk5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CCvi2fuXbIARoOK9oH3RSdOSSFrb-ToaOU_l0YcIbqQ)
> 
> > Also Maybe can we have the output for this?
> 
> ![image](https://private-user-images.githubusercontent.com/83777943/292844411-c4bcc06d-3e20-4773-8192-f1621e83842c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0Njk2NzQsIm5iZiI6MTcxNDQ2OTM3NCwicGF0aCI6Ii84Mzc3Nzk0My8yOTI4NDQ0MTEtYzRiY2MwNmQtM2UyMC00NzczLTgxOTItZjE2MjFlODM4NDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA5MjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNTVhZjNlZmJlNzliNTFkYzA0MzM2NGM3ODUyMjdmNzRkNTUyYjRjMjFmNzIwNzNmMmVhMmVhYzUxNTNjZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NPaxMmFHVEJfaMGvarsRu5Qnmko1lk2wf9lETA1Xh3g)

hey @theCode-Breaker @kRHYME7   how to fix the gpu issue? i couldnt find a way out of this. the waybar shows 

![image] (https://github.com/prasanthrangan/hyprdots/assets/135751082/3104bac6-b2de-42ac-a896-5d7b4146df9f)
it used to work perfectly before but its been a while no gpu details are being shown, i have integrated amd and nvidia mx450

**Comment by kRHYME7** [comment]
please fix the image

**Comment by Skerse** [comment]
> I resolved this issue on my system by reinstalling python-pyamdgpuinfo.

Nice, i had this issue as well.. wonder why it broke. I'll let people know if anyone else reports the issue. Thanks!

**Comment by KitsuneKode** [comment]
> > I resolved this issue on my system by reinstalling python-pyamdgpuinfo.
> 
> Nice, i had this issue as well.. wonder why it broke. I'll let people know if anyone else reports the issue. Thanks!

the aur version of pyamdgpuinfo didn't worked tho although it was installed, couldn't figure out why! did a pip install pyamadgpuinfo --breakdown-system-packages, only after that the script was able to import the module! idk if thats selectively my system problem tho!
