### ISSUE TITLE
The screen flickers when using some app actions

### ISSUE THREAD

**Issue by hui3215** [prasanthrangan/hyprdots#678]
When I use Vscode or Typora I get a splash screen issue

This is my computer's graphics card and other information
![image](https://github.com/prasanthrangan/hyprdots/assets/53279456/5f9dc207-6bea-496e-8b23-e3a32b300411)

**Comment by prasanthrangan** [comment]
Hi, can you please share screenshot showing the issue?
you can also try launching vscode with `--disable-gpu` or `--disable-gpu-sandbox` option

**Comment by kRHYME7** [comment]
@hui3215  Any progress on this issue?

**Comment by kRHYME7** [comment]
Closing as no more helpful information provided.
