### ISSUE TITLE
Neofetch Image don't show correctly

### ISSUE THREAD

**Issue by FuckingToasters** [prasanthrangan/hyprdots#679]
Hello, smetimes when i open the terminal, everything works fine but most of the time the neofetch image is not renered correctly, i tried to use kitty and konsole but the issue is the same on both.

![image](https://github.com/prasanthrangan/hyprdots/assets/94435104/7586cb20-460f-407b-80ff-81ab4d360c75)

The screenshot above happens directly after opening the terminal with the keybinding.

Regards,
FuckingToasters

**Comment by akashgagda** [comment]
You are using xerolinux not minimal arch

**Comment by prasanthrangan** [comment]
Hi, are you referring to extra characters seen in the screenshot or the size of the ascii art?

**Comment by FuckingToasters** [comment]
> Hi, are you referring to extra characters seen in the screenshot or the size of the ascii art?

To both, cuz it should display an actual image, not ASCII art and it sometimes work, other times it don't.

**Comment by FuckingToasters** [comment]
> You are using xerolinux not minimal arch 
> And you can edit neofetch config file change image size it's by default "270"

That's correct however it is still set to the default value of 270 so this don't seem to be the issue

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/ea216d4b-2285-425d-ba52-8b8f1c33772a)
I also get this sometimes. Race conditions might be happening. I did not dive deeply. Got this every time my system lags or I call Kitty instantly/fast. 
Having this issue since I'm using Hyrdots.

**Comment by mahaveergurjar** [comment]
I don't face this type of glitch 

![231226_18h05m49s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/3eeaa569-3b4e-47de-ac54-ece424dd633e)
![231226_18h06m37s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/151db766-de87-4aa4-90d5-748ae8117827)


You can try this file config of neo-fetch
[Text File.txt](https://github.com/prasanthrangan/hyprdots/files/13771515/Text.File.txt)

**Comment by kRHYME7** [comment]
@FuckingToasters Adding a sleep before executing neofetch can help. 

If there is a way to add a delay on the neofetch it would be better. 

For now I aliased my 'neofetch' into "sleep 0.2 && neofetch"
