### ISSUE TITLE
Not entering the interface after the login screen "loop"

### ISSUE THREAD

**Issue by wz790** [prasanthrangan/hyprdots#68]
Ialready` downloaded it 4 times, and every time everything ends well, and when I restart, it takes me to the username and password interface, and when I enter it correctly, it re-exits the interface and re-enters it vedio for the problem [https://files.fm/f/xkg9wz2hp](url)

**Comment by zer0cha0s** [comment]
There is currently an issue with the hyprland-git package, remove this and install hyprland and you should be fine.

**Comment by wz790** [comment]
Well, I will reinstall it, and before running it, I will install hyprland. I hope this solves the problem. I will try it and say thank you.

> There is currently an issue with the hyprland-git package, remove this and install hyprland and you should be fine.

**Comment by Xito137** [comment]
this happened to me, i tried uninstalling hyprland-nvidia-git and installing hyprland but it didn't fix
