### ISSUE TITLE
GUI doesn't appear (or) What's next step?

### ISSUE THREAD

**Issue by Madhesh-V** [prasanthrangan/hyprdots#680]
The packages install without any issues, but the GUI does not appear. 
![photo_2023-12-20_19-38-17](https://github.com/prasanthrangan/hyprdots/assets/83573352/3e09dd55-63da-497a-85e5-0b621258ba6f)

I rebooted the system after a few minutes, and the boot menu was updated.
![IMG_20231220_200335](https://github.com/prasanthrangan/hyprdots/assets/83573352/75bd8fed-c0c3-46bb-9032-23f7263c2b36)

The GUI doesn't appear once you are in the system!
![IMG_20231220_200353](https://github.com/prasanthrangan/hyprdots/assets/83573352/428b9f9c-fa3b-42ac-b715-3a1b41ccb063)
![IMG_20231220_200422](https://github.com/prasanthrangan/hyprdots/assets/83573352/dc3fa5d3-a70c-4a3a-b3d4-db58995eac67)

```
System  configuration :

• OS: Arch Linux x86_64
• Kernel: 6.6.7-arch1-1
• Packages: 670 (pacman)
• Resolution: 1366x768
• Terminal: /dev/tty1
• CPU: AMD PRO A4-4350B R4 2C+3G (2) @ 2.500GHz 
• GPU: AMD ATI Radeon R2/R3/R4/R5 Graphics
• GPU Driver: amdgpu
• Memory: 212MB / 3761M1B
 ```

**Comment by gelordo** [comment]
how did you solve this?
I too get that login screen and after it takes me to tty, then I type manually `Hyprland` but its blank screen with nothing working

**Comment by Madhesh-V** [comment]
Yap! When I use ```Hyperland```, it works for me! I think some of the packages are not installed properly on your system or corrupted after installation. Try to stable your internet connection then try hyprdots>Scripts ```./install.sh -r``` one more time, then enter ``` Hyperland ```

**Comment by gelordo** [comment]
> try hyprdots>Scripts `./install.sh -r` one more time, then enter `Hyperland`

I did the exact thing at it still didnt help, the theme files are not lading properly
