### ISSUE TITLE
New Installation Script 

### ISSUE THREAD

**Issue by akashgagda** [prasanthrangan/hyprdots#683]
New Installation script is not working properly i just tested and its exit automatically in the last  create cache script![IMG20231222162435.jpg](https://github.com/prasanthrangan/hyprdots/assets/55386892/ff4a20d5-e936-456d-bfb2-a1089d3078d3)

![IMG20231222162649.jpg](https://github.com/prasanthrangan/hyprdots/assets/55386892/4ff2e551-748c-402a-84fd-71a4d3dae639)

@T-Crypt @prasanthrangan @kRHYME7

**Comment by akashgagda** [comment]
I try 2 times ![IMG-20231222-WA0000.jpeg](https://github.com/prasanthrangan/hyprdots/assets/55386892/ee268f24-ec21-4ec4-b408-8c4525f9986d)

**Comment by kRHYME7** [comment]
Hello, I guess we have some problems with installing Extensions, 

you can try to edit your ./create_cache.sh  around line 138   and 

change  ``` code --install-extension "${codex}" 2> /dev/null   ``` into ``` code --install-extension "${codex}" || true ```

This will continue the script even if installation is failing and also give us some error messages. 

Thanks! at least we can compile the culprits of vscode giving  exit status on our script. :pray:

**Comment by akashgagda** [comment]
Sorry guys i try again and it's working fine

**Comment by Him7n** [comment]
nope it is still broken
![Screenshot-22_12_2023-11-24-52](https://github.com/prasanthrangan/hyprdots/assets/123625528/bf2603f7-b37a-4dd7-a88d-29818556b16e)

**Comment by akashgagda** [comment]
> nope it is still broken
> ![Screenshot-22_12_2023-11-24-52](https://github.com/prasanthrangan/hyprdots/assets/123625528/bf2603f7-b37a-4dd7-a88d-29818556b16e)
> 

Bro type Yes remove rofi

**Comment by Him7n** [comment]
Even if I type Y, it still breaks with same message + i dont wanna remove Rofi i have bspwm configured with it

**Comment by kRHYME7** [comment]
I don't know if rofi is working fine on Wayland. Hyprdots uses this fork of rofi https://github.com/lbonn/rofi. 
also if you still want to not use this version of rofi you can edit your ./custom_hypr.lst and remove the ``` rofi-lbonn-wayland-git ``` 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/54c01b93-d896-40b2-9824-49cca3e77114)

**Comment by kRHYME7** [comment]
> Sorry guys i try again and it's working fine 

Good to hear, I guess that was a connectivity issues or some vscode extension issues.

**Comment by akashgagda** [comment]
> > Sorry guys i try again and it's working fine 
> 
> Good to hear, I guess that was a connectivity issues or some vscode extension issues.

Yea bro i think so thank you Brother
