### ISSUE TITLE
firefox theme broken

### ISSUE THREAD

**Issue by iEscapedVim** [prasanthrangan/hyprdots#684]
After today's update something happened to Firefox, it looks like this 
![image](https://github.com/prasanthrangan/hyprdots/assets/32537564/62690ced-40c7-44de-a809-eb14ac0d1a82)

![image](https://github.com/prasanthrangan/hyprdots/assets/32537564/248f0917-ea6d-4895-81ed-ce6bb790241b)

also to click on the buttons you have, click slightly to the bottom left.

**Comment by YasirRWebDesigner** [comment]
I think It might be related to firefox package and not the theme because I see the same thing on Tor Browser as well
![image](https://github.com/prasanthrangan/hyprdots/assets/32537564/91147086-9a23-45cb-b746-87a34357acd6)

**Comment by katsuja** [comment]
The culprit is the new gtk3 update. I had the same problem and by downgrading from version 3.24.39 to 3.24.38 everything works perfectly again.
I'm under arch linux.

**Comment by Kemipso** [comment]
Thanks a lot @katsuja for the tip. I did not know the downgrade package, it's brilliant!
_And I can confirm 3.24.38 works fine_

**Comment by prasanthrangan** [comment]
Hi, i'm unable to replicate this issue with 3.24.39.

```
local/gtk3 1:3.24.39-1
    GObject-based multi-platform GUI toolkit
```

**Comment by katsuja** [comment]
> Hi, i'm unable to replicate this issue with 3.24.39.
> 
> ```
> local/gtk3 1:3.24.39-1
>     GObject-based multi-platform GUI toolkit
> ```

It does it to me.
With version 3.24.38
![3 24 38](https://github.com/prasanthrangan/hyprdots/assets/20012885/b27c34da-a878-45cb-8c75-3a4c8385376b)
With version 3.24.39-1
![3 24 39-1](https://github.com/prasanthrangan/hyprdots/assets/20012885/bacab55a-043c-4894-8192-f141d3b60ca0)

And it's replayed every time I move on to the last release

**Comment by kRHYME7** [comment]
```
local/gtk3 1:3.24.39-1
    GObject-based multi-platform GUI toolkit


 local/firefox 121.0-1
    Standalone web browser from mozilla.org 
```

Can't replicate this but this problem is exhibited on Chromium browsers for the past few months. And toggling floating fixes it.  

Maybe > customized toolbar > then check the  [] Title Bar at the bottom left can fix it too?.

**Comment by katsuja** [comment]
> Chromium

I can always reply on firefox every time I switch to version 1:3.24.39-1. If I downgrade everything goes back to normal. With this I am not saying that it is Rice's fault, on the contrary, but rather a problem with Firefox or the new gtk3 update. Or firefox doesn't meet the requirements of the latest gtk3 release, and as you say, probably also on Chromium.
I say this as a layman, I am neither a developer nor a computer scientist, I am a simple user who has fun out of passion.
I tried the procedure you proposed with Firefox but it didn't work.
I downgraded again.
I take this opportunity again to thank you for this fun recipe and I take this opportunity to extend my happy holiday greetings to everyone.

**Comment by kRHYME7** [comment]
Happy Holiday Everyone

**Comment by katsuja** [comment]
Replicable on Lenovo T450 laptop with Intel I5 5300U CPU and integrated INTEL HD GRAPHICS 5500 GPU.
Not replicable on desktop with Intel i5 9600k CPU and dedicated AMD RX580 GPU. In fact I don't have any problems.

**Comment by YasirRWebDesigner** [comment]
> Replicable on Lenovo T450 laptop with Intel I5 5300U CPU and integrated INTEL HD GRAPHICS 5500 GPU. Not replicable on desktop with Intel i5 9600k CPU and dedicated AMD RX580 GPU. In fact I don't have any problems.

maybe it's happening on Intel only, My laptop is also i5 6300U, with integrated Intel HD Graphics 520 GPU.

**Comment by katsuja** [comment]
> > Replicable on Lenovo T450 laptop with Intel I5 5300U CPU and integrated INTEL HD GRAPHICS 5500 GPU. Not replicable on desktop with Intel i5 9600k CPU and dedicated AMD RX580 GPU. In fact I don't have any problems.
> 
> maybe it's happening on Intel only, My laptop is also i5 6300U, with integrated Intel HD Graphics 520 GPU.

The circle is narrowing. That's my suspicion too

**Comment by YasirRWebDesigner** [comment]
> Hi, i'm unable to replicate this issue with 3.24.39.
> 
> ```
> local/gtk3 1:3.24.39-1
>     GObject-based multi-platform GUI toolkit
> ```

Hi, do you have a system with Intel, if so see if you can reproduce it there.

**Comment by Kemipso** [comment]
For reference, this happened on my machine with an AMD CPU (5900X). I cannot reproduce it _right this minute_, I'm in the middle of setting up NixOS, trying to adapt Prasanthrangan's dots there :-)

**Comment by katsuja** [comment]
> ```
> local/gtk3 1:3.24.39-1
>     GObject-based multi-platform GUI toolkit
> 
> 
>  local/firefox 121.0-1
>     Standalone web browser from mozilla.org 
> ```
> 
> Can't replicate this but this problem is exhibited on Chromium browsers for the past few months. And toggling floating fixes it.
> 
> Maybe > customized toolbar > then check the [] Title Bar at the bottom left can fix it too?.
> 
> Not really a fix though

Your advice is to temporarily solve the problem on Firefox with gkt3 3.24.39-1/3.24.39-2.
Thank you.

**Comment by stove-jeebs** [comment]
Has anyone found an actual fix instead of downgrading yet?

**Comment by YasirRWebDesigner** [comment]
> Has anyone found an actual fix instead of downgrading yet?

not that I know of, I just added the gtk3 to ignore list for now.

**Comment by katsuja** [comment]
> Has anyone found an actual fix instead of downgrading yet?

I temporarily solved it with updated gt3k following the advice of kRHYME7: (https://github.com/kRHYME7) https://github.com/prasanthrangan/hyprdots/issues/684#issuecomment-1868399262

**Comment by kRHYME7** [comment]
Hello Anyone experiencing this issue?

**Comment by kRHYME7** [comment]
Hello Anyone still experiencing this issue?

**Comment by katsuja** [comment]
> Hello Anyone still experiencing this issue?
> 
> ```
> Name            : gtk3
> Version         : 1:3.24.41-1
> ```

For me it's OK
