### ISSUE TITLE
nvidia not suspending because it is getting queried regulary for temperature.

### ISSUE THREAD

**Issue by KAGEYAM4** [prasanthrangan/hyprdots#685]
I am on laptop with intel integrated graphics + dedicated nvidia and I was getting high temp because nvidia was running actively and not suspending. I have removed the hyprdots config and since then temps are reasonable. I am using https://wiki.archlinux.org/title/PRIME#PRIME_render_offload, to launch programs on nvidia card.

I am not sure how tems are getting queried but it might be that it is waking the gpu constantly. I can test hyprdots later sometime again if i get time. In meantime, if anyone interested and wanna look into this.

This command can be use to safely query the state of nvidia -> `cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_status` also if pevious dosen't work this can also be used `cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_suspended_time
`

To see what the expected output should be use this source - https://wiki.archlinux.org/title/PRIME#NVIDIA

**Comment by KAGEYAM4** [comment]
if this https://github.com/prasanthrangan/hyprdots/blob/507e8baeb27cc6a11d526ef8073a98ab67e4ce7b/Configs/.config/hypr/scripts/gpuinfo.sh#L4C11-L4C11 this line is run everytime temp is queried, `nvidia-smi` wakes up the gpu.

**Comment by kRHYME7** [comment]
Hello,  What happens if you remove only the ``` custom/gpuinfo ``` ? Also Do you also have multi GPU ?

**Comment by KAGEYAM4** [comment]
> Hello, What happens if you remove only the `custom/gpuinfo` ?

do i have to remove it from waybar config?

> Also Do you also have multi GPU ?
yes lapto(intel+nvidia)

**Comment by kRHYME7** [comment]
> do i have to remove it from waybar config?

For testing...

> yes lapto(intel+nvidia)

strange As my other Laptop (With intel plus nvidia gpu too ) is actively using the Nvidia But it still can Suspend

If removing ``` custom/gpuinfo ``` from waybar fixes this then it the gpuinfo.sh script is the culprit.

**Comment by KAGEYAM4** [comment]
> If removing `custom/gpuinfo` from waybar fixes this then it the gpuinfo.sh script is the culprit.

Yes, after removing `custom/gpuinfo`, nvidia went into suspend-mode.

For me the gpu module in waybar shows `primary gpu - nvidia` on latest git commit. is it different for you?

**Comment by KAGEYAM4** [comment]
And i don't know if i am going insane but is this also same for you?

```
[phoenix@ArchLinux hyprdots]$ ls -l Configs/.config/waybar/themes/theme.css 
lrwxrwxrwx - phoenix 13 Oct 14:51 Configs/.config/waybar/themes/theme.css -> /home/tittu/.config/waybar/themes/Catppuccin-Mocha.css
```

Why is link pointing to some user account which i don't even have. I stumbled upon this issue two months ago, and it is still here, or is it just on my device.

**Comment by KAGEYAM4** [comment]
@kRHYME7 are you really sure nvidia is suspended on your system? are you using optimus-manager or prim-run?

what is output of `cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_status`?

also run this command five times `cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_suspended_time` , does the number change ?

**Comment by kRHYME7** [comment]
I'll try to test this if I  get back to my system.

**Comment by kRHYME7** [comment]
> what is output of cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_status?
also run this command five times cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_suspended_time , does the number change ?


The runtime_status is active
It is always 0 the runtime_suspend_time ``` 0 ``` but  My device is on 04:00 not 01:00  (lspci | grep "NVIDIA")

**Comment by KAGEYAM4** [comment]
>  My device is on 04:00 not 01:00 (lspci | grep "NVIDIA")

Maybe we on different distro, i am on Arch.



> So the main issue here is some laptops with intel + nvidia gets pretty hot if nvidia is active right? 

Yuup totally, preveiously it wasn't like this because, the gpu temps wan't added to hyprdots. It runs like 10 or 15 degree extra hotter.


> I guesshttps://github.com/prasanthrangan/hyprdots/pull/665 is helpful for you! You can read about it also you can try to test and ask me some questions about it. Also I'll be happy to adjust this.

For the meantime, i am going to try to build my own config slowly. So i won't be able to help in this pr. Maybe we can higlight this bug in readme. or we can use above two commands to first querry if nvidia is in suspend-state as those two commands dont change the state of nvidia (the nvidia address would be retrieved from lspci as you mentioned you having different address).



For me, i am having rough time with this config repo ( i think it will be same everywhere because dot files were never meant to be general) . some of them are -

1. why is update command this `./install.s. -r`, in the wiki it says -r is for restore but it dosent mention what it restores.
2. I also asked this and you were the one who answered https://github.com/prasanthrangan/hyprdots/discussions/589. `How can we preserve our own changes like as i am new to whole linux thing. - kitty.conf, vscode ( these was manytimes when using ./install.sh removed wholed vscode configs, data, plugins). `

so  i will role with default config for now and slowly add changes.

**Comment by kRHYME7** [comment]
> Maybe we on different distro, i am on Arch.

Nope that is not Distro related, We just got different device I guess? different PCI ports



> why is update command this ./install.s. -r, in the wiki it says -r is for restore but it dosent mention what it restores.

Okay, been contributing here for a while I guess what this means to restore is the OWNERS config files as he said (dunno where to reference) that this Repo is for HIS Dot files to be saved. Now that the repo has users I think users misunderstood the term restore as they thought that it would restore user configs but no! That is why I wrote this https://github.com/kRHYME7/Hyprdots-ctl to have a helper and maybe soon to Sync user configs to the latest update of this repository.  

> also asked this and you were the one who answered https://github.com/prasanthrangan/hyprdots/discussions/589. How can we preserve our own changes like as i am new to whole linux thing. - kitty.conf, vscode ( these was manytimes when using ./install.sh removed wholed vscode configs, data, plugins).

For now, vscode will not be overwritten also keybindings.conf will be users too
Great! So you're one of the users who inspired me to write hyprdots-ctl, LOL. Well I'm Trying to add this one at a time. So I would be grateful to receive some FEATURE requests.

**Comment by kRHYME7** [comment]
> For the meantime, i am going to try to build my own config slowly. So i won't be able to help in this pr.

That would be great also you can try to read the scripts to understand some functions as Tittu wrote this in a very straight forward, stable and easy to understand.

**Comment by KAGEYAM4** [comment]
> > For the meantime, i am going to try to build my own config slowly. So i won't be able to help in this pr.
> 
> That would be great also you can try to read the scripts to understand some functions as Tittu wrote this in a very straight forward, stable and easy to understand.

Yes definitely, this repo has really good config which is a good learning material.

**Comment by kRHYME7** [comment]
Best of Luck!

**Comment by prasanthrangan** [comment]
Hi, i don't think nvidia sensor info can be directly read like AMD, so `nvidia-smi` is used for gpuinfo.
as @kRHYME7 already has PR #643 for improving this script, i'll leave this to you :)

**Comment by kRHYME7** [comment]
@KAGEYAM4  Can you elaborate more especially  number 1. ? 





> I don't think disabling is good idea because if it was me i would still like to know the status of nvidia. So there two approach i can think of -
>1. we can use above two commands to first querry if nvidia is in suspend-state as those two commands dont change the state of nvidia (the nvidia address would be retrieved from lspci as you mentioned you having different address).

I don't think it will become suspended as long as it is queried by nvidia-smi. Or I missed something? 

>2. the issue for above is that one extra command will run for those that have nvidia only system. so maybe we can mention this in readme for hybrid system so that they can make changes themselves to add querry for checking the state of nvidia.

I guess this is doable, What I meant by disabling nvidia-flag is just to prioritize intel instead of Nvidia we can just toggle the config file and it will query Nvidia. I'll try to write this approach if you also prefer this. This is an easier approach for me as I'm not good at writing a ReadMe.  

The beauty of this generated config file is we can modify what to query on the go. 
This is an example of my System's available GPU. (As I have 2 GPUs therefore I got 2 GPU flags but 1 fails so the script gives it a 0 so that it will query intel)

Travel Laptop:
```
❯ cat /tmp/hyprdots-gpuinfo-query
nvidia_gpu="NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."
nvidia_flag=0 # NVIDIA-SMI has failed
intel_flag=1
intel_gpu="00:02.0"
```

Laptop at HOME: 
```
 nvidia_gou="NVIDIA GeForce 940M"
nvidia_flag=1
intel_flag=1
intel_gpu="00:2.0"
```

As you can see both have Nvidia-flag and intel-flag and if are all set to 1 the script queries the the Nvidia as it is set as a priority, if we just make a function to make Nvidia-flag=0 then it will query intel. Then that would fulfill your request right? And I guess We can just use the toggle option of waybar to change GPU's.

**Comment by KAGEYAM4** [comment]
@kRHYME7 

> I don't think it will become suspended as long as it is queried by nvidia-smi. Or I missed something?

- `nvidia-smi` will wake up the gpu to get temps.
- These two commands `cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_suspended_time` & `cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_status` will won't wake up the gpu.



`cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_status` can return three values based on nvidia state - `suspend` `rusuming` `active`

`cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_suspended_time` will return a integer value, this command needs to be run multiple times, and if the integer value is different that means nvidia is suspended.



-----------------

> I guess this is doable, What I meant by disabling nvidia-flag is just to prioritize intel instead of Nvidia we can just toggle the config file and it will query Nvidia.

As a user, i would like to know state of all my gpu's.

So this is the approch i can think of ->

1. We use either of above two commands to safely query nvidia without waking it up. If it is `suspended` we show `suspended` in waybar. and if it is running we querry `nvidia-smi` for tempserature.
2.  OR, many people might have only one gpu and querying nvidia status dosen't make sense ( even though it is just one instruction), So - we can make `querying` option present to user at config install time and based on that config will be generated per user.
3. I still think `2` will be bad, as people might move the config and won't know the implications or might just have forgotten. So i thing 1. would be best if we want it to be portable.

**Comment by kRHYME7** [comment]
I'm really confused on what is the use of this  As it wont even give temperature

> cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_suspended_time & cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_status



Also, I managed to just use the waybar to toggle GPU if available. The work flow will be if you have 2 or more active/functioning GPUs you will just click on the waybar module then it will change what GPU you read(Will effectively disable nvidia-smi if your not using it). Is this not convenient? 


Or your requirements is  to not use nvidia-smi ?

**Comment by kRHYME7** [comment]
> We use either of above two commands to safely query nvidia without waking it up. If it is suspended we show suspended in waybar. and if it is running we querry nvidia-smi for temperature.


If you are talking about to only query nvidia if it is active. We can do that also.  I hope I understand now.

**Comment by KAGEYAM4** [comment]
> > We use either of above two commands to safely query nvidia without waking it up. If it is suspended we show suspended in waybar. and if it is running we querry nvidia-smi for temperature.
> 
> If you are talking about to only query nvidia if it is active. We can do that also. I hope I understand now.

Yes

**Comment by KAGEYAM4** [comment]
> ![IMG_20231224_120446.jpg](https://private-user-images.githubusercontent.com/53417443/292654352-40dcd3f2-65b7-49f8-b667-0565e107b9cc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzOTE1MjMsIm5iZiI6MTcwMzM5MTIyMywicGF0aCI6Ii81MzQxNzQ0My8yOTI2NTQzNTItNDBkY2QzZjItNjViNy00OWY4LWI2NjctMDU2NWUxMDdiOWNjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDA0MTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOTdjYmI3NGMzZjY1NzcwNDEyZWE3YTkxOThhYWZhOGI5MDNiNDgwZGIwNTRkNjI5ZGIxOTUxNzlkNzg3ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aiMX4gUj-rJV0-eEsIphdagzYW8CELbC8086IEGYxyg)
> 
> ![IMG_20231224_120439.jpg](https://private-user-images.githubusercontent.com/53417443/292654351-d84581bf-0b50-4213-b7b6-b0649af80c12.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzOTE1MjMsIm5iZiI6MTcwMzM5MTIyMywicGF0aCI6Ii81MzQxNzQ0My8yOTI2NTQzNTEtZDg0NTgxYmYtMGI1MC00MjEzLWI3YjYtYjA2NDlhZjgwYzEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDA0MTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxY2M1MmI0NjgxZjAxOGRhMjk1YTM0YmQ3MGE2ZmZhODhmMTNkNTY3YTkxYmJkNTkwYjZkNzRjYTQ3MTgwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JHOqnUhFeHmESo61aEATmaqNHYUTL3ZXdNtrYXtuWs8)

Yes, this looks good.

But personally, I would want to see both gpu temps directly showing in waybar and not having to hover or click to see temps. Like i dont wanna interact with waybar to see what my current temps at. Because temp is what you wanna just be able to look at and decide if temp are justified for current sytem load usage.

**Comment by kRHYME7** [comment]
@KAGEYAM4  I have tried to implement your feature request : multiple instance and no query on suspend

but to be sure Can I have the output for ``` cat /sys/bus/pci/devices/0000:"$(lspci | grep -i nvidia | cut -d' ' -f1)"/power/runtime_status ```



Please read the # Usage section of the PR, it would be very helpful if you give some review.

**Comment by KAGEYAM4** [comment]
> @KAGEYAM4 I have tried to implement your feature request : multiple instance and no query on suspend
> 
> but to be sure Can I have the output for `cat /sys/bus/pci/devices/0000:"$(lspci | grep -i nvidia | cut -d' ' -f1)"/power/runtime_status`
> 
> Please read the # Usage section of the PR, it would be very helpful if you give some review.

```
[phoenix@ArchLinux ~]$ cat /sys/bus/pci/devices/0000:"$(lspci | grep -i nvidia | cut -d' ' -f1)"/power/runtime_status
active
```

**Comment by kRHYME7** [comment]
>But personally, I would want to see both gpu temps directly showing in waybar and not having to hover or click to see temps. Like i dont wanna interact with waybar to see what my current temps at. Because temp is what you wanna just be able to look at and decide if temp are justified for current sytem load usage.

Can you try the latest version of gpuinfo in the PR and see the usage section.  @KAGEYAM4 

with this, you can call 2 separate GPUinfo script and embed them into 2 separate  GPU info modules of waybar

```
❯ ~/.config/hypr/scripts/gpuinfo.sh --help

Avalable GPU: nvidia intel 
[options]
--toggle         * Toggle available GPU
--use [GPU]      * Only call the specified GPU (Useful for adding specific GPU on waybar)
--reset          *  Remove & restart all query

[flags]
tired            * Adding this option will not query nvidia-smi if gpu is in suspend mode 
startup          * Useful if you want a certain GPU to be set at startup

* If $USER declared env = WLR_DRM_DEVICES on hyprland then use this as the primary GPU
```

Adding another gpuinfo2.json 
Looks like this(Maybe just modify the icon)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/2394035f-d499-4e87-8d24-2bcd0f98e976)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c4f647b3-187e-4f83-8186-7595a2ef11af)

**Comment by KAGEYAM4** [comment]
@kRHYME7  i checked the latest commit on the pr.

I am still confused as what problem does it solve, i think we are misunderstanding each other.

If it would be possible, i would like if we can do jitsi_meet and talk to each other. Problem would be how can we share the link.

**Comment by kRHYME7** [comment]
Maybe we can chat on Discord? Here's my username, ``` khing0v0 ``` . 

Or email me at bong.kook.khan@gmail.com

**Comment by KAGEYAM4** [comment]
> Maybe we can chat on Discord? Here's my username, `khing0v0` .
> 
> Or email me at [bong.kook.khan@gmail.com](mailto:bong.kook.khan@gmail.com)

sent you the friend request. you can delete this message now.

**Comment by kRHYME7** [comment]
Hahaha. You still quoted it in the reply. But it's alright it's a fresh dump account.

**Comment by KAGEYAM4** [comment]
lmao. Didn't knew.
