### ISSUE TITLE
Gruvbox waybar module widget borders

### ISSUE THREAD

**Issue by TuxTweaker** [prasanthrangan/hyprdots#686]
I don't know why is is there I have tried looking into config files but I couldn't find anything that removes these borders

![231222_23h51m30s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/149172798/10722315-0e81-4c14-be0e-7b9f1f50ac03)

**Comment by prasanthrangan** [comment]
Hi, this is duplicate of #190 - its an issue with gtk3 theme itself.
so i'll close this one.
