### ISSUE TITLE
globbing error 

### ISSUE THREAD

**Issue by AdrianFerrer1** [prasanthrangan/hyprdots#687]
![231223_12h09m16s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/112191768/e4873811-4059-445c-9ddb-5b935a3b2431)

**Comment by kRHYME7** [comment]
I see when did you get this Error?  Ss the ``` source = ~/.config/hypr/nvidia.conf  ...``` from the install script or you just restored this config without installing? This line should be written by the script to be in hyprland.conf. 


But try to

``` nano ~/.config/hypr/nvidia.conf ```


then Paste this 

```

# █▄░█ █░█ █ █▀▄ █ ▄▀█
# █░▀█ ▀▄▀ █ █▄▀ █ █▀█


# See https://wiki.hyprland.org/Nvidia/ for more

#env = GBM_BACKEND,nvidia-drm
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_VRR_ALLOWED,1
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_DRM_NO_ATOMIC,1


```

**Comment by AdrianFerrer1** [comment]
> I see when did you get this Error? Ss the ` source = ~/.config/hypr/nvidia.conf ...` from the install script or you just restored this config without installing? This line should be written by the script to be in hyprland.conf.
> 
> But try to
> 
> `nano ~/.config/hypr/nvidia.conf`
> 
> then Paste this
> 
> ```
> 
> # █▄░█ █░█ █ █▀▄ █ ▄▀█
> # █░▀█ ▀▄▀ █ █▄▀ █ █▀█
> 
> 
> # See https://wiki.hyprland.org/Nvidia/ for more
> 
> #env = GBM_BACKEND,nvidia-drm
> env = LIBVA_DRIVER_NAME,nvidia
> env = __GLX_VENDOR_LIBRARY_NAME,nvidia
> env = __GL_VRR_ALLOWED,1
> env = WLR_NO_HARDWARE_CURSORS,1
> env = WLR_DRM_NO_ATOMIC,1
> ```

Thanks, adding the nvidia.conf solved it.

Btw, I think I pressed [1] instead of enter on one of the steps that told me to delete something, but tbh idk if that ended up fixing itself somewhere else or what because all seems to be working fine

**Comment by AdrianFerrer1** [comment]
![231223_15h10m11s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/112191768/84e0c26a-f5e3-463f-9a0f-d686a3d3a6fb)

it was one of these steps like at the bottom, I pressed 1 instead of enter (Nothing), because I thought [1] was nothing

**Comment by kRHYME7** [comment]
Hmmm I think that is not the case, but let us know if this problem repeats. Thanks!

**Comment by prasanthrangan** [comment]
looks like its fixed now, so i'll close this!
