### ISSUE TITLE
[Theme]:  How to hide the application button

### ISSUE THREAD

**Issue by hdm9527** [prasanthrangan/hyprdots#692]
### Description

I want to hide or remove the button in the figure in the figure

### Steps to Reproduce (if applicable)
![image](https://github.com/prasanthrangan/hyprdots/assets/39702328/7a36e572-ebb7-406c-a03c-6efd3d3a40b9)

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots (if applicable)

[If applicable, add screenshots to help explain your problem.]

### Proposed Solution (if applicable)

[If you have a specific solution in mind, describe it here. If not, you can skip this section.]

### Additional Information

[Add any other information about the issue or request here. For example, you might include links to similar features in other projects, or screenshots or diagrams to help explain your idea.]

**Comment by kRHYME7** [comment]
What app is this?

**Comment by hdm9527** [comment]
> What app is this?

[intellij-idea-ultimate-edition](https://aur.archlinux.org/packages/intellij-idea-ultimate-edition)
Because jrebel cannot be used normally because it is installed through paru, I installed it through the following command. 
```shell
git clone https://aur.archlinux.org/pkgbase/intellij-idea-ultimate-edition
cd intellij-idea-ultimate-edition
makepkg -si
```

**Comment by hdm9527** [comment]
Solved, it is a Java runtime environment problem
