### ISSUE TITLE
[Bug]: Laptop battery drains within an hour

### ISSUE THREAD

**Issue by NerdzzyDev** [prasanthrangan/hyprdots#694]
Guys, thank you so much. Your project is simply incredible. I've tried all the popular tiling window managers, but none of them have provided such a great experience, it's really cool, thank you! This will continue to be my main system, I realized that I don't want to change it anymore.

Actually, there is just one thing that really bothers me. How can I add power management? Right now, my laptop's battery only lasts about an hour. I don't know how to fix this. Maybe I should disable some animation or blurring settings. But also, I would really like to have the option to choose performance/economy/balanced mode.

**Comment by theCode-Breaker** [comment]
> Actually, there is just one thing that really bothers me. How can I add power management? Right now, my laptop's battery only lasts about an hour. I don't know how to fix this. Maybe I should disable some animation or blurring settings. But also, I would really like to have the option to choose performance/economy/balanced mode.

Yes you can disable the animation and blurring with Super + Alt + G
If you are using arch then just refer https://wiki.archlinux.org/title/Power_management for power management

**Comment by NerdzzyDev** [comment]
Thank you, but I think it still doesn't work quite properly. The battery indicator is the same. It shows different times every time. Maybe a very large variation. That is, even now, several inquiries with an interval of one second gives such a result. But thank you very much, your advice is really helpful!![IMG_20231225_180515_227.jpg](https://github.com/prasanthrangan/hyprdots/assets/55660001/007d1f6c-4b3c-421e-930d-b1aa91351d69)

**Comment by Rafi1018** [comment]
Try this https://github.com/AdnanHodzic/auto-cpufreq

**Comment by kRHYME7** [comment]
#641 Might be useful 

You can run ``` Hyprdots power save ``` 

then you can see a list of options you can disable as per hyprdots scope.

**Comment by mahaveergurjar** [comment]
@kRHYME7 
 I am already used your hyprdots-ctl this is very good to tweak the hyperlink dost and also a good option for power save mode can you add one more option the power saver is automatically on in battery mode so that I don't need to enable by manually and make only on option all thing disables autosomally in power saver mode when  laptop is on battery mode I think add an option in waybar related to battery power mode for laptop user  like game, power saving mode and normal mode

**Comment by kRHYME7** [comment]
hi can You please Describe battery mode? like if it is not charging? or below a certain battery Percentage

**Comment by mahaveergurjar** [comment]
> hi can You please Describe battery mode? like if it is not charging? or below a certain battery Percentage

If it not charging

**Comment by kRHYME7** [comment]
Hey, Please submit some issues or post a discussion here https://github.com/kRHYME7/Hyprdots-ctl, so we can track our progress as this repo is more on USER specifics. Thank you.

**Comment by kRHYME7** [comment]
At your convenience can you test this?  #699

**Comment by mahaveergurjar** [comment]
> At your convenience can you test this? #699

OK I try
