### ISSUE TITLE
[Bug]: Double battery: full battery notification when only one battery is full 

### ISSUE THREAD

**Issue by Doomer-Cat** [prasanthrangan/hyprdots#695]
### Description

Just installed arch on an usb to test hyprdots on my
laptop with 2 batteries. (thinkpad t460)

After playing around a little with the themes 
i get a notification that my battery is full and that i can unplug my cable
Noticed tho that battery percentage in waybar was at 89% (also checked with upower)

### Steps to Reproduce

1. use laptop with 2 batteries
2. charge device till 1 battery is full
3. check via `upower -i /org/freedesktop/UPower/devices/battery_BAT*`

### Expected Behavior

Full Battery Notification after sum of all batteries is at 99%

### Actual Behavior

Battery Notification after only one Battery was full

### Screenshots

pls ask if needed 

### Environment

- Distro: ArchLinux (fresh install on usb medium, 25.12.23 about 2 hours ago)
- Hardware: Lenovo Thinkpad T460 (germany) , Sandisk usb

**Comment by kRHYME7** [comment]
Hello I'm the one who rewrites the battery notify script, can you show us  the output for ```  ls /sys/class/power_supply/ ``` 

also incase you needed this https://github.com/prasanthrangan/hyprdots/issues/472

**Comment by kRHYME7** [comment]
I assume you know how to do things so can you help me test this, 

1. Edit ``` ~/.config/hypr/scripts/batterynotify.sh ```
2. Find the function ``` fn_status_change ```
3.  Change that whole function ``` fn_status_change() { ... } ```
with function below: 

```
fn_status_change () { # Handle when status changes
  total_percentage=0 battery_count=0
  for battery in /sys/class/power_supply/BAT*; do battery_status=$(< "$battery/status") battery_percentage=$(< "$battery/capacity")
    total_percentage=$((total_percentage + battery_percentage))
    battery_count=$((battery_count + 1))
  done
  battery_percentage=$((total_percentage / battery_count))
  if [ "$battery_status" != "$last_battery_status" ] || [ "$battery_percentage" != "$last_battery_percentage" ]; then 
    last_battery_status=$battery_status 
    last_battery_percentage=$battery_percentage    # Check if battery status or percentage has changed
    fn_verbose
    fn_percentage
    if $undock; then fn_status echo yes ; fi
  fi
}
```

What this do: 
Sums all percentage divided by how many loops or counts of BAT*.

**Comment by Doomer-Cat** [comment]
> Hello I'm the one who rewrites the battery notify script, can you show us the output for
> 
> ```
>  ls /sys/class/power_supply/ 
>  cat /sys/class/power_supply/BAT*/capacity
> ```
> 
> also incase you needed this #472
> 
> Features for dual battery isn't added yet.


```
❯ ls /sys/class/power_supply/
 AC -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/PNP0C09:00/ACPI0003:00/power_supply/AC
 BAT0 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/PNP0C09:00/PNP0C0A:00/power_supply/BAT0
 BAT1 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/PNP0C09:00/PNP0C0A:01/power_supply/BAT1
```

Before charging:
```
❯ cat /sys/class/power_supply/BAT*/capacity
94
5
```

**Comment by kRHYME7** [comment]
Wow! Does your 2nd battery needed longer time to full charge? As I can see it lags a great amount, unless it charges 1 battery first.
Have you tried getting both at 100 percent?

**Comment by Doomer-Cat** [comment]
> Wow! Does your 2nd battery needed longer time to full charge? As I can see it lags a great amount, unless it charges 1 battery first. 

yes i had some issue with it taking a long time to full charge i guess its pretty bad since capacity only amounts to a little  over 55%. Had some issues with it being stuck at 97-98% sometimes too

> Have you tried getting both at 100 percent?
i did tho but didn't get any notification 
after reboot i did get one tho (battery% not getting higher than 98 before reboot i'd guess(?))

_currently still testing_

**Comment by Doomer-Cat** [comment]
the script seems to work

**Comment by kRHYME7** [comment]
Nice! I will try to add a PR.
 In some cases, systems can't reach 100 percent, you won't get a notification. 
Here are the options you can add upon running the script in the ``` hyprland.conf ```

example: ```   ~/.config/hypr/scripts/batterynotify.sh --full 98 ```  this will make the batteryfull threshold to 98%. 

```
Usage: /home/khing/.config/hypr/scripts/batterynotify.sh [options]
  --verbose, -v     Verbose Mode
  --undock, on     Shows Battery Plug In/Out/Full Notification
  --full, -f        Set battery full threshold (default: 100% percent)
  --critical, -c    Set battery critical threshold (default: 10% percent)
  --low, -l         Set battery low threshold (default: 20% percent)
  --unplug, -u      Set unplug charger threshold (default: 80% percent )
  --timer, -t       Set countdown timer (default: 120 seconds)
  --interval, -i    Set notify interval  on LOW UNPLUG Status  (default: 5% percent)
  --notify, -n      Set notify interval for Battery Full Status  (default: 1140 mins/ 1 day)
  --execute, -e     Set command/script to execute if battery on critical threshold (default: systemctl suspend)
  --help, -h        Show this help message
```

**Comment by kRHYME7** [comment]
At your convenience can you test this?  #699

**Comment by kRHYME7** [comment]
Hello @Doomer-Cat  @prasanthrangan  the #699  is alreadfy merged
