### ISSUE TITLE
[Feature Request]: HIDPI or fractional scaling problem. (Pycharm)

### ISSUE THREAD

**Issue by NerdzzyDev** [prasanthrangan/hyprdots#698]
Friends, I understand that this issue is more related to xwayland, but maybe you have already solved it :) (if not, I'll just close the issue)

Have you figured out the blurry display of applications not adapted for Wayland, but written for X? For example, pycharm displays with blurry text and pixels. It seems to be called a HIDPI or fractional scaling problem.

**Comment by kRHYME7** [comment]
Have you tried some combination of this: 
``` 
env = GDK_SCALE,1

xwayland {
    force_zero_scaling = true
    }
```
