### ISSUE TITLE
Stuck in Login screen loop 

### ISSUE THREAD

**Issue by pierre-rs** [prasanthrangan/hyprdots#70]
First, thank you for sharing your rice and your install script!

Please see if you can help me...

Currently, I enter the login and password and within moments the system returns to the login screen again.

I was able to access the system through text mode login prompt via `Ctrl+Alt+F4`.
I tried to start `Hyprland` and got errors:

![20230807_221605](https://github.com/prasanthrangan/hyprdots/assets/57575719/d3a76ac9-1cc3-43bd-a8ff-c651b863b049)

One error in particular caught my attention but I couldn't find much about it on the internet:
`Error: "Socket file not found. Are you sure sww-daemon is running?"`

> System Information
> 	Product Name: Acer Aspire ES1-572
>         Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
>        16GiB System memory
>         Skylake GT2 [HD Graphics 520] (1920x1080)
>         RTL8111/8168/8411 PCI Express Gigabit Ethernet (enp1s0)
>         QCA9565 / AR9565 Wireless Network Adapter (wlp2s0)

**Comment by prasanthrangan** [comment]
Hi, thank you! This looks similar to issue #68

so can you please try installing `hyprland` package instead of `hyprland-git`

**Comment by pierre-rs** [comment]
Thanks!

I installed the `hyprland` package, rebooted and Hyprland loaded.

At first, Hyprland presented some error messages (like the one in the image below).

![20230809_192332](https://github.com/prasanthrangan/hyprdots/assets/57575719/e93f2299-6264-4d51-8755-92be889037fc)


But after commenting out a few lines (34 to 39) of `~/.config/hypr/themes/theme.conf` the error messages disappeared.

![20230810_071053](https://github.com/prasanthrangan/hyprdots/assets/57575719/f233aaaf-cad1-41ed-861b-69f266afc45d)


**Off topic**: Just commenting on some first impressions

- Apparently the waybar doesn't seem to have a blur as cool as what appears on your rice/video printscreens. Also when I have applications open it appears as a line (fine and semi-transparent) just above the waybar.

- Apparently/unfortunately it seems that some applications I need to be ready to use (such as Rustdesk, Anydesk and Teamviewer) seem not to be fully prepared for wayland. I wonder if it would be the case to try to use/install Hypr (for Xorg) and, if so, if the settings you use in your rice would work in Hypr (for Xorg). I have to say, your rice is really nice! Especially the one you made with dolphin file manager is amazing!

**Comment by prasanthrangan** [comment]
Hi, thank you so much!

> At first, Hyprland presented some error messages (like the one in the image below).

> But after commenting out a few lines (34 to 39) of `~/.config/hypr/themes/theme.conf` the error messages disappeared.

Oh, this is a recent config (blur) change for hyprland v0.28.0, so you'll have to use the please versions of the  `~/.config/hypr/themes/*` theme files. So since you are using `hyprland` package instead of `hyprland-git`, you are getting this error.


> * Apparently the waybar doesn't seem to have a blur as cool as what appears on your rice/video printscreens. Also when I have applications open it appears as a line (fine and semi-transparent) just above the waybar.

Seems like you have removed the blur values set in `~/.config/hypr/themes/theme.conf` based on your screenshot, which disables the blur in waybar.

> * Apparently/unfortunately it seems that some applications I need to be ready to use (such as Rustdesk, Anydesk and Teamviewer) seem not to be fully prepared for wayland. I wonder if it would be the case to try to use/install Hypr (for Xorg) and, if so, if the settings you use in your rice would work in Hypr (for Xorg).

I've not used these applications, but it should work in xwayland so you try installing it. Hope it improves wayland support.

**Comment by Balssh** [comment]
@pierre-rs  is this still an issue or can it be closed?

**Comment by Elixir76** [comment]
Setting nvidia_drm.modeset=1 fixed it for me

**Comment by kRHYME7** [comment]
Please re-open a more recent issue. Will use this issue for reference. 🫰
