### ISSUE TITLE
[Bug]: Not working properly with external monitor

### ISSUE THREAD

**Issue by tushargoyalofficial** [prasanthrangan/hyprdots#700]
### Description

I really like the rice and installed it on my work laptop. Now I usually connect to external monitor when working on something. Issues are as follows:
1. Fonts for waybar/topbar is very small
2. Tried to make them big by changing scale but becomes jiggered.
3. Normally if we press WIn+p, a menu comes where you select modes like mirror, laptop only, external only ... , instead of that screen start getting fade on every press.
4. Not able to use one monitor at a time
5. While connected to external monitor, if I try to sleep it and resume, system hangs. 

### Steps to Reproduce

1. Install on laptop
2. Connect external monitor
3. It's detecting resolution, but fonts are way too small.
4. My monitor is 2k LG Ultragear 27GN800

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

1.  Fonts should get auto adjusted as per the monitor resolution.
2. Should be able to select the display output
3. System should resume properly from sleep if connected to external monitor

- Linux Distro: EndeavourOS
- Linux Version, 6.6.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 21 Dec 2023 19:01:01 +0000 x86_64 GNU/Linux
- Installation Environment: On The Main Hardware
- Other info: Display Resolution: 2K LG Ultragear 27GN800
- HP victus AMD 5600H/16GB/Nvidia 1650

**Comment by kRHYME7** [comment]
Simply this is not a bug as this is not yet implemented yet on hyprdots and what do we expect on a bare Window Manager. Nonetheless I am willing to write a PR specifically for this as I think the owner is not using a laptop( Also I badly needed the features above too).  


For now this might help. 


> Fonts for waybar/topbar is very small

Run : ``` Hyprdots waybar control ``` then the control file for waybar will open by default in vscode, also the daemon that waits for changes on the config file will start. On the editor, find the 1st column that has a value of 1, that's the active configuration,   on its 2nd column change it is the Scaling of the waybar config, so please modify it to your preferred scale, as you save the file the waybar will automatically refresh. 

> Tried to make them big by changing scale but becomes jiggered.

Where did you change the scaling? 

> Normally if we press WIn+p, a menu comes where you select modes like mirror, laptop only, external only ... , instead of that screen start getting fade on every press.

> Not able to use one monitor at a time

Try some packages like wdisplays, hdisplays and nwg-displays.  The latter is the one left being maintained. 
Also with a bare WM, these features are not yet implemented. 
You can check out   https://wiki.hyprland.org/Configuring/Monitors/  for some $user specific configuration.


>  While connected to external monitor, if I try to sleep it and resume, system hangs.

will try to test soon. 





>Fonts should get auto adjusted as per the monitor resolution.
Should be able to select the display output
System should resume properly from sleep if connected to external monitor

We can try to use kanshi or any package to save monitor configuration. I'll try to test nwg-displays first as it is actively maintained.

**Comment by tushargoyalofficial** [comment]
I tried to change scaling in this file
.config/hypr/hyprland.conf file's monitor to 
example : eDP-1,1920x1080@60,0x0,2 
@kRHYME7

**Comment by tushargoyalofficial** [comment]
I also tried on my workstation too, still top waybar fonts are very small. I have used openbox (archcraft) in past. It able to detect the correct resolution and set the font size accordingly. I was thinking might be some issue with the ricing. Thanks for detailed help @kRHYME7 . Will try to follow the steps you mentioned

**Comment by mahaveergurjar** [comment]
only font is small or icons and waybar all things are small
can you send a screenshot

**Comment by tushargoyalofficial** [comment]
Everything is small. Fonts and icons both.

**Comment by mahaveergurjar** [comment]
Can you attach a screenshot of the waybar

**Comment by mahaveergurjar** [comment]
You can try to change the waybar size in the file ~/.config/waybar/config.ctl
![231231_18h51m34s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/b7b98103-4a8e-416e-8a83-7e0d34f66d50)

The orange color arrow direction that is shows the position of waybar and the green color arrow direction shows the waybar size so you can try to change the size of waybar

**Comment by mahaveergurjar** [comment]
![231231_18h57m09s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/f38dcfe7-78e0-40d6-9bb3-6688ad0815f3)
![231231_18h56m38s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/d1df9df8-25e7-4638-9a11-a89fe16c65f8)

You can see the difference

**Comment by tushargoyalofficial** [comment]
whole system fonts are small, not only topbar. If this dot files only for specific user/machine, please mention that. If it is for everyone running Arch, then make it in that way.

**Comment by kRHYME7** [comment]
> please mention that.
 
 https://github.com/prasanthrangan/hyprdots/issues/700

> Fonts should get auto adjusted as per the monitor resolution.

It was strange why changing the monitors in  ``` $HOME/.config/hypr/hyprland.conf   ``` became jiggered. 
Normally hyprland will handle the default scaling. Normally ``` monitor = ,preferred,auto,auto ```  should determine the best resolution for you. For hidpi maybe change the last value to 2 or anything that is supported on your system. (see ```hyprctl monitors ```  to see some supported reso). 
If some apps are jiggered either check some of your GPU support (related to Nvidia)


> System should resume properly from sleep if connected to external monitor

Also, the dotfiles do not support yet some more changes on the system like setting up systemwide configuration.(Almost all of the scripts here are for $USER only. IMO, in this way, it will not cause confusion and unexpected results to individual systems)

https://wiki.archlinux.org/


sidenote* 
+ Try to run Hyprland first without these configurations to see if scaling is expected, maybe you can try to experiment with the monitor's configuration that suits yours. Let us know if it is the ricing issue. 
+ Also some electron apps are jiggered so please run it with Wayland, not X11 please add this flag on app execution
``` --ozone-platform=wayland ``` (warning some app might crash) 
+ For some x11 apps
```
xwayland {
    force_zero_scaling = true
    }
```
add this it will prevent the window from scaling. 
Apps will appear small so  
``` env = GDK_SCALE,2 ```  helps to scale it up. 


Please let us know if it works and what solutions you've done. A screenshot will also help.

**Comment by tushargoyalofficial** [comment]
My monitor is of 2K resolution, but fonts set for 4K resolution, appearing very small. Tried to make them bigger, fonts and icons are not looking smooth, as in they were stretched (jiggered).

**Comment by kRHYME7** [comment]
Does this issue occur even if not using this dot files?

**Comment by mahaveergurjar** [comment]
> My monitor is of 2K resolution, but fonts set for 4K resolution, appearing very small. Tried to make them bigger, fonts and icons are not looking smooth, as in they were stretched (jiggered).

Hyprland auto set the monitor scale display  but I don't know what the problem is in your case 
you can set the manual  you can read the hypland wiki see this link
[https://wiki.hyprland.org/Configuring/Monitors/](url)

**Comment by mahaveergurjar** [comment]
Can you send you monitor config screen shot of hyprland file & monitor file

like this type, i am also manually
![240124_11h24m46s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/57872034/c17aa4f3-8a5f-4efa-8ace-0e75201c3e29)
 config screen resolution

**Comment by kRHYME7** [comment]
Answers according to the wiki will close this as a stale issue
