### ISSUE TITLE
[Bug]: Low FPS When Gamemode Off

### ISSUE THREAD

**Issue by TZProgrammer** [prasanthrangan/hyprdots#702]
### Description

I get low FPS on my system even with no intensive application running (Discord at 6% CPU, Hyprland at 1%, everything else negligible). As soon as gamemode is turned on, the fps reaches my monitor refresh rate.

I find this strange since, if Hyprland was being so intense that the fps had to be halved, it would be consuming more of the GPU.

### Steps to Reproduce

1. Gamemode Off
2. Run glxgears to check framerate

### Expected Behavior

I expected either one of two things. Normal FPS, or low FPS with high CPU usage. On my monitor, the expected FPS would be 144.

### Actual Behavior

FPS hovers between 60fps and 90fps.

### Screenshots

Framerate before gamemode, and after gamemode (sudden jump in fps at the end):
![image](https://github.com/prasanthrangan/hyprdots/assets/22439185/b857a687-88fc-47ed-a8ea-3c75c4b1c8e1)

Consumption of resources at the time:
![image](https://github.com/prasanthrangan/hyprdots/assets/22439185/58ce495f-4164-4dba-b7fc-d951f609f39d)

(The Hyprland utilization is unusually high at this moment, it usually is at 1 or 2%, unsure what is happening here but it seems to be unrelated to the bug).

### Environment

e.g.,

- Linux Distro: ArchLinux
- Linux Version: Linux tzeger 6.6.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 21 Dec 2023 19:01:01 +0000 x86_64 GNU/Linux
- Hyprland Version: Hyprland, built from branch main at commit e5eb11ad0423bfdfd4056964ef868e26b2d3c846 dirty (Nix: wrap with gcc).
Date: Wed Dec 27 13:27:55 2023
Tag: v0.33.1-101-ge5eb11ad
- Installation Environment: Main Environment, Nvidia dedicated GPU, intel dedicated CPU
- Laptop: ASUS ROG G15.
- Other info: Laptop monitor at 144 Hz, 1920x1080. External monitor at 144 Hz, 1920x1080.

### Additional Information

This happens both with nvidia_anti_flicker = false or true.

**Comment by kRHYME7** [comment]
Steps you can try to see which in the game mode fixes the refresh rate:
(This is how gamemode.sh is written)
+ Start with gamemode.sh is off then
+ Please run each line one by one to see which gives the expected output
** PLEASE run ``` hyprctl reload ``` after each line to reset the hyprland settings 
```

hyprctl        keyword animations:enabled 0

 hyprctl keyword decoration:drop_shadow 0

 hyprctl       keyword decoration:blur:enabled 0

 hyprctl       keyword general:gaps_in 0

 hyprctl       keyword general:gaps_out 0

 hyprctl       keyword general:border_size 1

hyprctl        keyword decoration:rounding 0

```



This way we can find out which fixes the refresh rate and might help us understand the behaviour.

**Comment by kRHYME7** [comment]
Hello is the issue still relevant?

**Comment by WantDead** [comment]
For me helped this 
```
hyprctl keyword decoration:blur:enabled 0
```
