### ISSUE TITLE
The install.sh file no longer works[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by Aarush12862** [prasanthrangan/hyprdots#703]
### Description

[Provide a clear and concise description of the bug.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by Skerse** [comment]
Sorry, this is not helpful, you submitted the issue template with no information at all. Can you please give more information please?

**Comment by meduk0** [comment]
@Aarush12862  i tried on my machine for a try yesterday and it worked as charm maybe fork the repo and see the 4 insallation script they might be something that doesn't work with your hadware or system or just update your system (done it on cachy os with chaotic-aur )
