### ISSUE TITLE
cannot update through "git pull" command

### ISSUE THREAD

**Issue by Juhayer-Al-Wasif** [prasanthrangan/hyprdots#706]
![image](https://github.com/prasanthrangan/hyprdots/assets/124311164/d7733e8e-8400-4276-9661-1a6bc4d79463)

**Comment by kRHYME7** [comment]
git status?

**Comment by Juhayer-Al-Wasif** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/124311164/d526f92d-cd59-4efe-9862-b548344a725d)

**Comment by kRHYME7** [comment]
If those changes you made are intentional then you can run this. 

```
  git stash --include-untracked
  git pull
  git stash pop
```

**Comment by kRHYME7** [comment]
Stale?
