### ISSUE TITLE
Login screen issue

### ISSUE THREAD

**Issue by AdiKsOnDev** [prasanthrangan/hyprdots#71]
First of all, thanks for this rice! It is wonderful and beautifully set up. 
I have an issue, my login screen doesn't seem to know about my user.
Just to clarify some stuff:
- My user's name is NOT "User"
- I only have 1 user
- If I do alt + f4 and try to run "Hyprland" it DOES work
Here's what I see on the login screen:
![PXL_20230810_154815966.jpg](https://github.com/prasanthrangan/hyprdots/assets/80326762/ece965a6-dc60-41fd-86f3-3c3433ef6fc9)

![PXL_20230810_154808822.jpg](https://github.com/prasanthrangan/hyprdots/assets/80326762/4774303f-6894-4a32-b2f4-7a268394f890)

The "Login!!" button and "username" field are not clickable. Any suggestions are very appreciated!
Thanks in advance ~Average stupid arch user

**Comment by prasanthrangan** [comment]
Hi, Thank you so much!

For the first time login, please enter your actual username in that "user" box, as its only a placeholder value as seen in the screenshot.

**Comment by AdiKsOnDev** [comment]
Yeah I thought so too, but Username field is not clickable

**Comment by prasanthrangan** [comment]
Oh that's strange, it should be clickable, it is for me -

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/8623f40f-dfe7-4177-bab0-0675529fe0c2)

you can try login from TTY and try changing the sddm theme to default, to check if the default theme works.

**Comment by AdiKsOnDev** [comment]
Will try. Logging in from bash works, will try to fix that username field somehow. Gotta figure out where the folder with its config files is though :D
