### ISSUE TITLE
[Bug]: Config error at line 141

### ISSUE THREAD

**Issue by guerreroz01** [prasanthrangan/hyprdots#710]
## Bug Report
I have this issue with a fresh install 
### Description
Appears to be an error in the line 141 of the config file, also the resolution of the display is not correct, but the red notification does not dissapears 

### Screenshots

![240101_17h16m56s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/67748490/e9d4a580-f13b-4cc7-8d94-c5f52d03f302)

![240101_17h22m44s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/67748490/cf9965a2-2155-4bd5-a8fe-87b3e27c0884)

### Environment

-  ArchLinux
- Linux Version Linux archlinux 6.6.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 21 Dec 2023 19:01:01 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`:
- Hyprland, built from branch HEAD at commit d74607e414dcd16911089a6d4b6aeb661c880923  (props: bump ver to 0.33.1).
Tag: v0.33.1
- Installation Environment: On The Main Hardware

**Comment by guerreroz01** [comment]
[SOLVED]: use optimus-manager to disable integrated GPU and them re-install all over again, right now trying to solve resolution of the display 1920x1080 does not appears

**Comment by kRHYME7** [comment]
>resolution of the display 1920x1080 does not appears

Can you please specify what you mean about this?

**Comment by megatnuar** [comment]
still no fix. i cant use optimus-manager because since hyprland is using wayland.

**Comment by guerreroz01** [comment]
> still no fix. i cant use optimus-manager because since hyprland is using wayland.

Can you see the screen?

**Comment by megatnuar** [comment]
nvm i found the fix to making that red warning bar on top go away. 

cd .config/hypr/hyprland.conf

at line 141 the nvidia part is missing. go to original repo find that nvdia.conf file and download it.

go to your download depository and then 

mv nvidia.conf .config/hypr

this fixed the warning. you can close this bug label now or check if im wrong somewhere in my explanation first. 

i still cant get my apps (discord, microsoftedge, spotify, etc.) to be in proper resolution. they're all pixelated lol. maybe i'll post a bug post if i still cant find a fix.

**Comment by abenezerw** [comment]
I have the same issue, but changing monitor from 
monitor = ,preferred, auto, auto 
to 
monitor= ,preferred, auto, 1
Seems to have fixed the resolution issue but the whole screen is so far away yet crispy nice, and the big red header is still there too.

**Comment by kRHYME7** [comment]
2 scenarios to fix this.

1st if you actively use nvidia:

https://github.com/prasanthrangan/hyprdots/blob/main/Configs%2F.config%2Fhypr%2Fnvidia.conf

Here is the missing file that causes the error. paste this configuration to your ~/.config/hypr/nvidia.conf.


2nd scenario, If you won't use nvidia:

Comment out or remove the line 141 on your ~/.config/hypr/hyprland.conf 


I hope this helps.

**Comment by abenezerw** [comment]
You’re amazing!! Before I do this can you confirm this would solve it. Here is a detailed explanation.

ASSISTANCE REQUIRED. 
On launch there is a big red bar on top that says 
Config error at line 141 (/home/ben/.config/hypr/hyprland.conf): source= globbing error: found no match 
Hyprland may not work correctly 

There’s a similar problem in the GitHub repository of prasanthRagan with images. What do I do? There are forums that say install NVIDIA DKMS and I’m not sure because you said it was included. But the gpu driver is different from the one in the video because in neofetch it’s saying I’m using nouveau while yours(the YouTuber Ksk royal) is showing it’s using the dedicated gpu driver for NVIDIA but on mine I don’t know if nouveau is for my integrated Amd gpu or my dedicated NVIDIA gpu.

I did a dual boot from different partition and I switch using the f12 because my windows from different drive doesn’t show up in the drive with arch in it which is a really pretty grub btw. 

My neofetch

Lenovo Legion 5 pro
CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 4.463GHz
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
GPU Driver: nouveau 
Memory: 1364MiB / 13830 MiB

**Comment by kRHYME7** [comment]
In your case I guess you  can just remove that line. As you have dual GPU and Hyprland would prefer the integrated Amd

**Comment by abenezerw** [comment]
[SOLVED] yup I did it like you said. Downloaded and added the nvidia.conf and now it’s gone. Still not sure what Hyprland is using without any apps open though, I hope it’s the Amd for better battery and then the nvidia kicks in when gaming, preferably. Also in another issue between you and kraske the temperature bar shows as gpu not found.

**Comment by kRHYME7** [comment]
The nvidia config was not necessarily for what gpu will be used though specially for multi gpu, it only has the fixes for some issues for nvidia users.

#643 Here is the pull request.

About the AMD GPU,  there is a Pending Pull request about gpu info script. Please try to copy that and change your ''' ~/.config/hypr/script/gpuinfo.sh ``` with that and see if it gives temperature. Unfortunately for Nouveau drivers you  won't be having Nvidia GPU information through nvidia-smi on your system as it won't be very active given that you're using that driver but no worries it should still give information.

**Comment by abenezerw** [comment]
![IMG_0969](https://github.com/prasanthrangan/hyprdots/assets/46224293/c7504faa-993e-4855-b5be-a9062e61dc71)
I did that and I got this error. And it omitted the gpu temperature icon too, so it’s not visible. Just the cpu and ram. Btw I restarted waybar and then it showed that image and wouldn’t stay on, just kept fading away. I think I’ll revert the changes for now

**Comment by kRHYME7** [comment]
Aha, I see some permission errors. 
 Can you test it again but first run
``` chmod +x ~/.config/hypr/scripts/gpuinfo.sh ```
then run ```  ~/.config/hypr/scripts/gpuinfo.sh ``` on the terminal? 

Here is the raw file BTW https://raw.githubusercontent.com/kRHYME7/KhingDom/GPUinfo/Configs/.config/hypr/scripts/gpuinfo.sh

Thanks for your help this will make the PR better.

**Comment by abenezerw** [comment]
@
![IMG_0971](https://github.com/prasanthrangan/hyprdots/assets/46224293/58adb1f4-09ac-43b4-b616-2410f01cdbf8)
You’re amazing! Works beautifully. Hope 44° is okay. 
Never going back to windows. Gonna main this.

**Comment by LeonardoMor** [comment]
> > Aha, I see some permission errors. Can you test it again but first run `chmod +x ~/.config/hypr/scripts/gpuinfo.sh` then run ` ~/.config/hypr/scripts/gpuinfo.sh` on the terminal?
> > Here is the raw file BTW https://raw.githubusercontent.com/kRHYME7/KhingDom/GPUinfo/Configs/.config/hypr/scripts/gpuinfo.sh
> > Thanks for your help this will make the PR better.
> 
> I did this but it says my primary GPU is not found:
> 
> ```
> ❯ ./gpuinfo.sh
> {"text":"58°C", "tooltip":"Primary GPU: Not found\n Temperature: 58°C\n󰾆 Utilization: 9.5 %\n Clock Speed: 1056.67/3800 MHz"}
> ❯ rm /tmp/hyprdots-gpuinfo-query
> ❯ ./gpuinfo.sh
> ./gpuinfo.sh: line 8: nvidia-smi: command not found
> Initialized Variable:
> 
> 
> Reboot or rm /tmp/hyprdots-gpuinfo-query to RESET Variables
> {"text":"58°C", "tooltip":"Primary GPU: Not found\n Temperature: 58°C\n󰾆 Utilization: 7.8 %\n Clock Speed: 1500.56/3800 MHz"}
> ❯ ./gpuinfo.sh
> {"text":"58°C", "tooltip":"Primary GPU: Not found\n Temperature: 58°C\n󰾆 Utilization: 9.5 %\n Clock Speed: 839.658/3800 MHz"}
> ```

While installing hyprdots, it told me it detected nvidia. I thought it installed drivers and everything else. It seems it didn't.

**Comment by kRHYME7** [comment]
> So the driver was my responsibility? I must have missed that the drivers were a pre-requisite.

In some cases yes, ( a fresh install of Arch were a pre-req for this dots) 
 IMO we should manually install drivers for our system. 
https://wiki.archlinux.org/title/NVIDIA 
This should help you out why the Nvidia driver installation failed and the system still uses Nouveau.  Try to disable Nouveau first then try to install the appropriate driver for your system manually if you do not prefer nouveau driver. 
There are many factors. Some systems do not support nvidia-dkms.  


> Here the requested outputs:

Thanks! I will try to add support for nouveau.

**Comment by LeonardoMor** [comment]
> > So the driver was my responsibility? I must have missed that the drivers were a pre-requisite.
> 
> In some cases yes, ( a fresh install of Arch were a pre-req for this dots) 
>  IMO we should manually install drivers for our system. 
> https://wiki.archlinux.org/title/NVIDIA 
> This should help you out why the Nvidia driver installation failed and the system still uses Nouveau.  Try to disable Nouveau first then try to install the appropriate driver for your system manually if you do not prefer nouveau driver. 
> There are many factors. Some systems do not support nvidia-dkms.  
> 
> 
> > Here the requested outputs:
> 
> Thanks! I will try to add support for nouveau. 
> 
> 

Yeah, I installed the drivers. Now I have my GPU but lost a monitor. I hope hyprland gets to play well with PRIME at some point.

**Comment by kRHYME7** [comment]
Hi @abenezerw I noticed you mentioned you're using nouveau driver 
can I request for the output for ``` sensors ``` ? This help the PR to be better. 
Thanks in advance!

**Comment by abenezerw** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/46224293/2939a854-3545-48a2-ac5e-6d9a3507703b)
Do you mean these?
Btw some apps, mostly text editors like vscode just look wonky sometimes . Tooo low res. I saw somewhere on YouTube we can fix this by, I believe what he said was because of “fractional scaling”. And he said to change a line in Hyprland,conf to “monitors= ,preferred, auto, 1 . 
didn’t try it as I thought it might crash something like the waybar.

**Comment by LeonardoMor** [comment]
> Hi @abenezerw I noticed you mentioned you're using nouveau driver can I request for the output for `sensors` ? This help the PR to be better. Thanks in advance!
> 
> @LeonardoMor Can we also have the output for `sensors` ? Thank you!
```
❯ sensors
ath10k_hwmon-pci-3e00
Adapter: PCI adapter
temp1:        +47.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +57.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +57.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +54.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +54.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +53.0°C  (high = +100.0°C, crit = +100.0°C)

nvme-pci-3b00
Adapter: PCI adapter
Composite:    +25.9°C  (low  = -273.1°C, high = +84.8°C)
                       (crit = +84.8°C)
Sensor 1:     +25.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +28.9°C  (low  = -273.1°C, high = +65261.8°C)

hidpp_battery_0-hid-3-4
Adapter: HID adapter
in0:           4.22 V  

pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +47.0°C  

BAT1-acpi-0
Adapter: ACPI interface
in0:          12.75 V  
curr1:       1000.00 uA 
```

**Comment by kRHYME7** [comment]
Thanks!

> Btw some apps, mostly text editors like vscode just look wonky sometimes . Tooo low res. I saw somewhere on YouTube we can fix this by, I believe what he said was because of “fractional scaling”. And he said to change a line in Hyprland,conf to “monitors= ,preferred, auto, 1 .


I do not think it is the scaling if vscode and some chromium browser looks blurry. I tried using nouveau driver(open source) and I guess it is the culprit for those low resolution.  
You should try  to read this https://wiki.archlinux.org/title/NVIDIA and try to install the nvidia driver. In my case I just disabled nvidia completely as it makes my batterylife shorter and have heating issues. 

But do not worry in changing your ``` monitors= ,preferred, auto, 1 ``` waybar here is designed to scale based on your screen resolution.

**Comment by abenezerw** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/46224293/7157e6b6-2b76-4895-ace3-636d37c495d2)
Yeah, but earlier to get the GPU in my waybar, i set it as my primary gpu by adding this into env in hyprland.conv
![image](https://github.com/prasanthrangan/hyprdots/assets/46224293/148e8cfa-7163-4d2c-a590-3ab17c8d3b67)
which i would assume would leave the NVIDIA alone and use AMD for everything till i launch a game or something then NVIDIA would kick in right?
and the monitor line change seems to solve it but everything is so far away. as you can see in the first image. correct me if im wrong but i can try and download the proprietary.

**Comment by kRHYME7** [comment]
env = GDK_SCALE,2

xwayland {
    force_zero_scaling = true
    }
    
  try to modify the GDK _SCALE (needs a restart to take effect) in your ``` ~/.config/hypr/userprefs.conf ```

**Comment by abenezerw** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/46224293/0813e810-39ce-47e2-b232-f86b79005f09)
Did that and reboot my system but i don't think it changes anything.

**Comment by abenezerw** [comment]
> env = GDK_SCALE,2
> 
> xwayland { force_zero_scaling = true }
> 
> try to modify the GDK _SCALE (needs a restart to take effect) in your `~/.config/hypr/userprefs.conf`

I had to revert and delete this because it was getting too laggy and stuttery.

**Comment by kRHYME7** [comment]
> Btw any idea how the brightness could always leave where i left off after restart instead of always 100% at restart.

On my laptop, the last brightness set is preserved. Is this not the case in your system?

**Comment by abenezerw** [comment]
> > Btw any idea how the brightness could always leave where i left off after restart instead of always 100% at restart.
> 
> On my laptop, the last brightness set is preserved. Is this not the case in your system?

Nope. Always starts at 100%

**Comment by kRHYME7** [comment]
try my suggestion above maybe you can use that. 

I can help you with this, Let's try to test this out 


run ```  brightnessctl -s ``` then remember what brightness is that do not do it on 100% brightness as this test will be useless

Reboot your system 

then run ``` brightnessctl -r ```



See if the brightness sets to the saved one instead of 100%

**Comment by kRHYME7** [comment]
BTW I think You should Post on the discussion  for your questions,  I think we are cluttering on this issue. 😅

**Comment by kRHYME7** [comment]
Closing this as resolved. Feel free to reopen if needed.
