### ISSUE TITLE
Only can share screen electron app , besides of that it not detected

### ISSUE THREAD

**Issue by t101804** [prasanthrangan/hyprdots#714]
### Description

[Provide a clear and concise description of the bug.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[What did you expect to happen?]
Showing screen 

### Actual Behavior

[What actually happened?]
Only electron app 

### Screenshots

[If applicable, add screenshots to help explain your problem.]
![image](https://github.com/prasanthrangan/hyprdots/assets/113588203/334fa2f9-53de-4650-a02d-6f44ac14d6ef)

and if entire screen
![image](https://github.com/prasanthrangan/hyprdots/assets/113588203/38d5f0ae-4b7a-49de-b310-664449ce0fc6)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro:Arch linux
- Linux Version, output of `uname -a`: Linux archy 6.6.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 02 Jan 2024 02:28:28 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0
- Installation Environment: Main
- Other info: 

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by t101804** [comment]
i also already follow instruction in here https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580#option--1--xdg-desktop-portal-hyprland--recommended-

when i use obs its fine but if discord its not detected

**Comment by zer0cha0s** [comment]
Hey @t101804, installing `xwaylandvideobridge` solved this for me and has been working perfectly since i installed the package last week.

**Comment by t101804** [comment]
> `xwaylandvideobridge`

i installed but still same?

**Comment by t101804** [comment]
its work when i do command in terminal 

`discord --disable-gpu | xwaylandvideobridge`

but there is anyway to open it? without any terminal or like

discord --disable-gpu | xwaylandvideobridge --close terminal or something

**Comment by t101804** [comment]
> Hey @t101804, installing `xwaylandvideobridge` solved this for me and has been working perfectly since i installed the package last week.

![image](https://github.com/prasanthrangan/hyprdots/assets/113588203/0c574037-5df6-4f1d-84bc-7d8f84834567)
but when i use discord in browser is working. i already download discord-electron version in arch but same cant share screen. xwaylandvidiobridge also got freeze

**Comment by Skerse** [comment]
This is an issue with discord because discord still has not implemented pipewire screenshare support. 

xwaylandvideobridge should just work, like it should automatically show up when you start screensharing from an xwayland app like discord, but i don't know how to help you fix it when i've never used it.

My preferred way that i know works is just not using the official discord client, and instead use vencord-desktop as it has screenshare support without weird workarounds.
