### ISSUE TITLE
Autologin does not work

### ISSUE THREAD

**Issue by Juhayer-Al-Wasif** [prasanthrangan/hyprdots#715]
![image](https://github.com/prasanthrangan/hyprdots/assets/124311164/a3f0d3b0-71a9-4cbd-ad4b-7c638bed5a29)

**Comment by kRHYME7** [comment]
@Juhayer-Al-Wasif 

```
❯ cat /etc/sddm.conf.d/kde_settings.conf
[Autologin]
Relogin=false
Session=hyprland
User=wasif

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

```

Please try to modify your /etc/sddm.conf.d/kde_settings.conf adding the session and your user
