### ISSUE TITLE
discord share screen problem

### ISSUE THREAD

**Issue by FatngatirBilek** [prasanthrangan/hyprdots#717]
i can't screen share other application and only blank screen when i tried to share entire screen

![image](https://github.com/prasanthrangan/hyprdots/assets/81058978/b921fc99-77e5-450d-9bbf-442b6cbe6b3b)

**Comment by FatngatirBilek** [comment]
discord also flickering when i scroll down

**Comment by 0xl30** [comment]
> i can't screen share other application and only blank screen when i tried to share entire screen
> 
> ![image](https://private-user-images.githubusercontent.com/81058978/294658536-b921fc99-77e5-450d-9bbf-442b6cbe6b3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDkxOTIsIm5iZiI6MTcwNDU0ODg5MiwicGF0aCI6Ii84MTA1ODk3OC8yOTQ2NTg1MzYtYjkyMWZjOTktNzdlNS00NTBkLTliYmYtNDQyYjZjYmU2YjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDEzNDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZjM2NGRiNTUyMDUxYzMwMjkyNDU3M2ZjYjk1NzJiM2IyOGU3ZGNhN2ZjYzBmMzZhYmViMGFiZGI3NWEwMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r7z0m9SIc3N7UjN6jJFYjnuTRu_KuPwAQMtHThb2LEk)

Hyprland Don't Support Direct Screen Shareing

**Comment by ShubhamritG** [comment]
https://wiki.hyprland.org/hyprland-wiki/pages/Useful-Utilities/Hyprland-desktop-portal/ and use Armcord as an altenative for Discord, these might help you. It'll also fix obs problems if you're facing any black screen there.
