### ISSUE TITLE
waybar isn't theming

### ISSUE THREAD

**Issue by user12xxxxxx** [prasanthrangan/hyprdots#718]
waybar isn't theming according to wallpaper or themes

![240108_12h38m54s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111512589/1ec47539-de9c-4b68-b498-67defc0b735c)
![240108_12h39m18s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111512589/1b9232d1-48f2-48c9-9aff-6e991f44a63e)
![240108_12h39m55s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111512589/7998a5b5-d37c-41cf-a571-3110e3e7a897)

### Environment

- Linux Distro: [EndeavourOS]

- Hyprland Version
  ❯ hyprctl version
Hyprland, built from branch main at commit d9b74ff96b3e3f0341a386451b9a3375b6f05503 dirty (renderer: staticize local functions).
Date: Tue Dec 19 17:25:56 2023
Tag: v0.33.1-60-gd9b74ff9

flags: (if any)
debug

- Installation Environment: [On The Main Hardware]

### Additional Information

it happened after i updated the scripts

**Comment by kRHYME7** [comment]
$mainMod + Shift + D

or

run : ``` Hyprdots wallbash toggle ```

This toggles your wallbash script

**Comment by user12xxxxxx** [comment]
Thanks it worked
