### ISSUE TITLE
Issue in resolution

### ISSUE THREAD

**Issue by Dokkuhai** [prasanthrangan/hyprdots#72]
Firstly, thanks you very much for the best rice !
I have an issue about monitor that can't edit to 1920x1080 mode, please help me!
And have issue when open pavucontrol )):
![swappy-20230811_155939](https://github.com/prasanthrangan/hyprdots/assets/88721298/ee65d6b1-b950-469f-b497-a10beef2f594)
![swappy-20230811_160011](https://github.com/prasanthrangan/hyprdots/assets/88721298/de14713a-bc7d-4e79-a925-5d65e64b54dd)

**Comment by prasanthrangan** [comment]
Hi, Thank you so much!

by default the resolution is set to autodetect in hyprland conf `~/.config/hypr/hyprland.conf` -
```
monitor = ,preferred,auto,auto
```

You could try setting it to 1920x1080 and see if it works.

**Comment by Balssh** [comment]
@Dokkuhai is thi still an issue or can it be closed?
