### ISSUE TITLE
Disable Transparent Effect 

### ISSUE THREAD

**Issue by bimadewantoro** [prasanthrangan/hyprdots#722]
How do I disable the transparent effect in Specific Application?
I feel a little disturbed when watching online videos using Firefox and Brave Browser because of the transparent effect.

**Comment by kRHYME7** [comment]
Hello, try to read the friendly wiki for [hyprland](https://wiki.hyprland.org/) also I wrote a utility to handle some of this 

https://wiki.hyprland.org/Configuring/Window-Rules/#window-rules-v2

Add a windowrul about opacity  in your ``` ~/.config/hypr/userprefs.conf ``` 

examples: 

```
windowrule = fullscreen,^(Waydroid)$
windowrulev2 = fullscreen,initialtitle:^(FreeRDP: 192.168.122.180)$
windowrulev2 = fullscreen,initialtitle:^(Virt Viewer)$
windowrulev2= fakefullscreen,title:^(Canva)$
#windowrulev2= fullscreen,title:^(btop)$
#windowrulev2= fullscreen,title:^(Spotify)$
```

**Comment by velfern** [comment]
add this  in `~/.config/hypr/userprefs.conf`

```
windowrulev2 = opacity 1 1,class:^(firefox)$
```

**Comment by bimadewantoro** [comment]
Thankyou so much !
