### ISSUE TITLE
[Bug]: Cannot start hyprland (fresh archlinux install)

### ISSUE THREAD

**Issue by TahlonBrahic** [prasanthrangan/hyprdots#727]
### Cannot start hyprland (fresh arch Linux install)

After a fresh install of arch Linux per the guide I ran ./install.sh and afterwards the application didn't boot, even after a reboot. I ran Hyprland in the CLI and it created this bug report attached at the bottom.

### Steps to Reproduce

Install arch linux on a vm in Oracle Box on a Samsung Book3 Pro 360.

Install hyprdots.

### Expected Behavior

Clean install of hyprdots

### Actual Behavior

Install seems successful but cannot boot into desktop environment.

### Environment

I am running a VM through oracle box on a Samsung Book3 Pro 360. It uses a 13th gen i7 with iris gen graphics. The display is 3k.

### Additional Information

return _bootstrap._gcd_import(name[level:], package, level)

**Comment by kRHYME7** [comment]
> I am running a VM through oracle box on a Samsung Book3 Pro 360. It uses a 13th gen i7 with iris gen graphics. The display is 3k.

This issue may be the fact that you are in a VM. Try to install Hyprland again then run ``` Hyprland ``` on the tty terminal. Also, See some open issues about legacy renderer  #663 or solutions about running hyprland on a VM. (Have you tried it before)?

**Comment by TahlonBrahic** [comment]
I just ran a fresh install of arch linux and install Hyprland by itself and it still didn't work. It gave me this log: 

[EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message "DRI2: failed to create screen"
[CRITICAL] m_sWLRRenderer was NULL!
[CRITICAL] Critical error thrown: wlr_gles2_renderer_create_with_drm_fd() failed!

I will check out that open issue. I am also going to try to run a fresh install without a VM as a dual boot on this computer to make sure it is not a VM issue.

**Comment by TahlonBrahic** [comment]
**UPDATE:** After a fresh installation on hardware I determined the issue was probably archinstall. I installed arch linux manually and the issue resolved itself. The VM could of also had something to do with it but I received the same issue on both mediums.

**Comment by kRHYME7** [comment]
You still can't launch Hyprland?.

**Comment by TahlonBrahic** [comment]
> You still can't launch Hyprland?.
> 
> If so try to install Driver for your system? The error looked like wayland did not start well for Hyprland or maybe https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#vm
I finished a install on metal on my laptop that I was previously trying to install as a VM. Now I am trying to install it as a VM on my desktop. It could just be an issue with VM's. I have been trying to find a workaround.

**Comment by TahlonBrahic** [comment]
**FIX FOR BLANK SCREEN ON LOGIN**
**FIX FOR BLANK SCREEN ON VM**

Several hours on hunting and the answer is you need to enable 3D hardware acceleration. 
There should be a note for VM users in the installation guide / wiki.

**Comment by kRHYME7** [comment]
This is on the Hyprland wiki.

**Comment by TahlonBrahic** [comment]
Yeah, that is where I found it. I had never used Hyprland before and assumed this might be a Hyprdots-specific issue, but after reading through the post you linked, I found a link to the Hyprland page, and they have a note about that. I think a PR to the Hyprdots wiki or README would be great because, after reading through the issues of Hyprdots, it seems 4 or 5 of the open issues are actually this exact problem. If you would prefer to open one, let me know; if not, I can make a PR.

**Comment by kRHYME7** [comment]
It is more  appropriate if you add a PR. You can ad it on FAQ? maybe. 

https://github.com/prasanthrangan/hyprdots/wiki/FAQ

Thanks !

**Comment by rubiin** [comment]
I think this can be closed

**Comment by kRHYME7** [comment]
https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#vm

😀
