### ISSUE TITLE
Graphite Mono Theme weird borders  colors

### ISSUE THREAD

**Issue by RookiexCookie** [prasanthrangan/hyprdots#728]
I noticed a blue color border , notification in some of the wallpapers
like in this
![240112_11h53m49s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/136296017/d6c49e4d-4f18-46d8-aec8-a5151f79aedd)

when out of focus it turns blue but in this one no blue notification fonts 
but in the limbo wallpaper
![240112_11h55m24s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/136296017/de30f62d-8212-45c2-85df-05e31e6911b2)

no blue borders color but rather blue notifications and  other things 
whats up wth  that

**Comment by kRHYME7** [comment]
Hello this is determined by the wallbash script in this repo. it works like pywal.

you can run ``` ~/.config/hypr/scripts/wallbashtoggle.sh ```

ad:
you can run ```` Hyprdots show binds ``` then search for keyword " wallbash " to toggle it

**Comment by RookiexCookie** [comment]
ohh but where is the wallbash getting color blue all i see is grey black and white ,
 from what i know it takes the dominating color of the wallpaper to make sleek color palettes or something yea?
 anyways ill disabled it for a while but it doesnt look that cool without wallbash

**Comment by kRHYME7** [comment]
If you have used this repo from a while ago there is a problem where if colors on the wallpaper are almost monocolor we will have blank notifications.  So I guess the solution is to use a more inverted the primary color which we  have now. 
Maybe the Owner is formulating something for this issues though just to hit the sweet spot 

This is created during the caching of the images.

**Comment by kRHYME7** [comment]
> oh so wallbash essentially needs 3 colors to work properly

Not really (We have 18 colors parsed from each wallpaper)  
```
❯ cat ~/.cache/hyprdots/Graphite-Mono/chainsawman_sketch.png.dcol
dcol_pry0="0B0B0B"
dcol_txt0="F4F4F4"
dcol_0xa1="0B0B0B"
dcol_0xa2="0000FF"
dcol_0xa3="0E0E0E"
dcol_0xa4="101010"
dcol_pry1="A1A1A1"
dcol_txt1="0000FF"
dcol_1xa1="3A3A3A"
dcol_1xa2="444444"
dcol_1xa3="4E4E4E"
dcol_1xa4="585858"
dcol_pry2="FBFBFB"
dcol_txt2="040404"
dcol_2xa1="5A5A5A"
dcol_2xa2="6A6A6A"
dcol_2xa3="7A7A7A"
dcol_2xa4="898989"
```
then there is just a tiny funtion somewhere that assign those values to this templates 
```
ls ~/.config/hypr/wallbash
 dunst.dcol
 hypr.dcol
 icons
 kvantum_1.t2
 kvantum_2.t2
 palette.dcol
󰕙 palette.svg
 rofi.dcol
 spotify.dcol
 waybar.dcol
```
So if you're concerned about the blue color try to experiment with what color might fit to it ``` dunst.dcol  ``` is the template for the notif.  
```
cat ~/.config/hypr/wallbash/dunst.dcol
$HOME/.config/dunst/Wall-Dcol.conf|${ScrDir}/wallbashdunst.sh

[urgency_low]
    background = "#<wallbash_0xa1>"
    foreground = "#<wallbash_txt0>"
    frame_color = "#<wallbash_0xa4>"
    icon = "~/.config/dunst/icons/hyprdots.svg"
    timeout = 10

[urgency_normal]
    background = "#<wallbash_1xa4>"
    foreground = "#<wallbash_txt0>"
    frame_color = "#<wallbash_2xa4>"
    icon = "~/.config/dunst/icons/hyprdots.svg"
    timeout = 10
```
You can change the ``` txt ``` part maybe it might fit to all wallpapers
 

> supposedly it should make the current wallpaper the login screen background
but in my case when i logout after running the script
all i see is white bg ,


What is the output of the script? I'm not really familiar with sddm but try to search in the issue tracker for the same issues.

**Comment by RookiexCookie** [comment]
> What is the output of the script? I'm not really familiar with sddm but try to search in the issue tracker for the same issues.

well if i run it 
its just changing to dynamic wallpaper or static wallpaper

but the interesting thing is that it changes the location of the background to something else which is ~/.config/swww/wall.set
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/87edbb21-d362-490f-b7c3-e70756467d13)

but lol something happened in between
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/a2b04617-94cc-459c-b224-896d061418f4)

**Comment by kRHYME7** [comment]
``` ~/.config/swww/wall.set ``` is a binary image so it should look like that

also here is the command to set current wallpaper to sddm 

``` Hyprdots sddm set ```

**Comment by RookiexCookie** [comment]
Cool , will try that and 
Thanks for you time.

**Comment by kRHYME7** [comment]
@RookiexCookie  The .dcol script receives an update. I think the unusual blue color will be fixed now. 

Run this ``` find ~/.cache/hyprdots/ -type f -name '*.dcol'  ``` to confirm if it is the .dcol files in the cached dir. 

Run ``` find ~/.cache/hyprdots/ -type f -name '*.dcol' -delete ``` to purge them 

Then ``` Hyprdots cached reload ``` to reload new Dcol cached

**Comment by RookiexCookie** [comment]
Alrighty , thanks for the info
btw just to be clear Hyprdots cache reload will run the ~/Hyprdots/Scripts/create_cache.sh ? 
right?

**Comment by kRHYME7** [comment]
yups

**Comment by RookiexCookie** [comment]
@kRHYME7 although most of the bluish is pretty much eliminated 
but for like 1-2 wallpapers is like this
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/e3aac88c-4a9f-45be-8817-a0e8c357ba56)
idealy it wouldve be like this
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/5b437779-a7bd-496d-8266-38dc7730725a)


but its an amazing feat nonetheless , and these are just minor stuff
just lettin you know

**Comment by kRHYME7** [comment]
Thank you for this.

**Comment by RookiexCookie** [comment]
@kRHYME7 
Recent Update in kitty 
made it look like this 
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/ac190715-b7c8-41fe-a1bb-2be91d6a1041)

**Comment by kRHYME7** [comment]
yeah it's the gojo wallapper right? 

``` cp  ~/.cache/hyprdots/Graphite-Mono/limbo.jpg.dcol ~/.cache/hyprdots/Graphite-Mono/gojo.png.dcol ``` 

I just copied the .dcol of limbo as they are both slightly the same color scheme .

**Comment by RookiexCookie** [comment]
Lol that was one hacky to do stuff , thanks
but can i revert to old commit where the colors were more bright in kitty ?

**Comment by kRHYME7** [comment]
you can just disable the execute permission for  the ./wallbashkitty.sh

**Comment by RookiexCookie** [comment]
gotchu, i played around and got back the old colors , now it looks nice again
Thanks
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/06587904-0bac-4f97-bfd6-40e8d57df7d3)
