### ISSUE TITLE
[ui]: font and pictures look weird in other applications 

### ISSUE THREAD

**Issue by harshborana11** [prasanthrangan/hyprdots#729]
### Description

[icons and fornts are like glitched how can i fix it ]

### Steps to Reproduce

1. [Open any app other then firefox like discord , chrome ect]

[What actually happened?]

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/67332766/136457a2-d179-44a1-a44a-6005413581bb)

**Comment by harshborana11** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/67332766/bf5aa21c-0424-494c-a871-ecf97c44757b)
another example :)

**Comment by kRHYME7** [comment]
Maybe some recent issue? 
https://www.reddit.com/r/hyprland/comments/194rk1o/xwayland_apps_and_fractional_scaling/ You can read from the comment of vaxry himself.

try to play with this 
```
env = GDK_SCALE,1

xwayland {
    force_zero_scaling = true
    }
misc {
```

then use the GDK scaling to fine tune

**Comment by harshborana11** [comment]
`env = GDK_SCALE,1

xwayland {
    force_zero_scaling = true
    }`
thanks sir btw the waybar

**Comment by harshborana11** [comment]
sir the waybar

**Comment by Coderx11** [comment]
sir i im harshborana11 with diffrent acc as currently i cant login to that acc , im still getting gliched ui in gnome apps but other apps looks fine 
![image](https://github.com/prasanthrangan/hyprdots/assets/154494279/63c3b11d-1703-45a0-9126-80f5e615ff44)

**Comment by kRHYME7** [comment]
can you describe the glitch ?  try to toggle float

**Comment by Coderx11** [comment]
@kRHYME7 sorry sir for the late reply , no they just look weird in only gnome aplications , for now i have tried komikku , gradience , and  gnome-calculator and they looks weird in them 
![image](https://github.com/prasanthrangan/hyprdots/assets/154494279/50618403-9ccc-4476-a1fc-86618bcdcaec)
here is the image of firefox and gnome apps

**Comment by kRHYME7** [comment]
I do not know how gnome apps act on gnome as You're running their apps outside Gnome. Are the jiggered graphics only  on gnome apps?

**Comment by Coderx11** [comment]
@kRHYME7 only in gnome apps probably its only  my laptop screen i guess i dont know for sure :(

**Comment by kRHYME7** [comment]
Hmm, what is your hardware? I get blurry apps if I am using the Nouveau driver on Nvidia.  what are your system specs?

**Comment by Coderx11** [comment]
@kRHYME7 
![image](https://github.com/prasanthrangan/hyprdots/assets/154494279/6a7aa9d2-0d8d-4a37-ab16-9ccfe6a227e6)
herer are all the specs

**Comment by kRHYME7** [comment]
hmm, can you provide your hyprland version and also your monitor specs? 

Try to read this, found something similar
https://github.com/hyprwm/Hyprland/discussions/4379 Something similar happened.  I Advice that tries to install hyprland-git then reboot.

**Comment by Coderx11** [comment]
@kRHYME7 
i dont understand by which template you are metioning thanks for the reply i was busy so sorry for late responce ill try out git version

**Comment by Coderx11** [comment]
@kRHYME7 thanks sir all the app looks perfect now thank you so much for helping me it really means a lot , have a great day 
![image](https://github.com/prasanthrangan/hyprdots/assets/154494279/8a0c387c-7add-4f5f-8f6d-e795dcb1c193)
