### ISSUE TITLE
[Q]: Question

### ISSUE THREAD

**Issue by harshborana11** [prasanthrangan/hyprdots#732]
### Description

which spicefy theme is used in the video?

**Comment by kRHYME7** [comment]
The script uses Sleek theme and then uses the color scheme from the wallpaper.  If this is not yet reflected on your system download ``` spotify ``` and  ``` spicetify-cli ``` first.  


By the way, we have this on the repo https://github.com/prasanthrangan/hyprdots/discussions/categories/q-a . 
Thanks you!
