### ISSUE TITLE
[Query]: Instruction for minimizing the current window

### ISSUE THREAD

**Issue by sayskar500** [prasanthrangan/hyprdots#734]
In the keybindings section I saw the keybinding for full screen but didn't see any keybinding for minimizing the current window. Is it mentioned in a different manner in the keybindings section ?

**Comment by RookiexCookie** [comment]
um you cant minimise stuff in hyprland,
well minimising to tray is all you gonna get, you can switch to other workspace if you wanna have a full winow

**Comment by sayskar500** [comment]
@RookiexCookie thanks for the answer and understandable. Maybe the team could add the minimize stuff as an `future enhancement` thing. I wanted to ask one more thing (although I know I should have created a new issue for this).

Are there any instructions as to how to add our own Internet downloads pics as wallpapers ?

**Comment by RookiexCookie** [comment]
oh for the wallpaper you can read this #400  

but what i did , i just added downloaded images to ~/.config/sww/ respective themes
and ran the create_cache.sh which was in the Hyprdots files
and it created new ones along with old ones

**Comment by sayskar500** [comment]
Oh ok thanks man gonna read that up ! Closing this up
