### ISSUE TITLE
weird border in nvim 

### ISSUE THREAD

**Issue by harshborana11** [prasanthrangan/hyprdots#735]
weird border in nvim 

![image](https://github.com/prasanthrangan/hyprdots/assets/67332766/a30aa394-128b-42ed-ac10-5823d1918349)

**Comment by sudoCompetence** [comment]
It's most likely the terminal settings. Edit the kitty config file ~/.config/kitty and change border padding. Else it's your nvim config itself.

**Comment by Skerse** [comment]
> It's most likely the terminal settings. Edit the kitty config file ~/.config/kitty and change border padding.

This is correct, the padding itself usually looks fine, until you have a terminal application that isn't transparent and has a colored background. So i guess you can either change the padding like sudoCompetence said or i think you can change neovim to use terminal background color, it'll look a lot better probably.

**Comment by harshborana11** [comment]
thanks for the suggestion ill make the background transparent
