### ISSUE TITLE
waybar clock module

### ISSUE THREAD

**Issue by se7en-x230** [prasanthrangan/hyprdots#738]
24h time not displayed

![240114_15h03m58s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/69777713/4ff7bf0a-c4e8-430a-976e-098ea426d293)

shouldn't that change the time to 24h?

**Comment by RookiexCookie** [comment]
clicking on it will toggle it to 24hr format along with todays date

**Comment by se7en-x230** [comment]
Yes but I would want to have 24h as the default.

**Comment by kRHYME7** [comment]
It won't, we should regenerate the configuration. 
Please toggle next/prev to regen the waybar

run ``` Hyprdots show binds ```  then search for waybar to see what keybind is available
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/5938898f-9e2a-4d15-a871-9c73f81dd094)

**Comment by se7en-x230** [comment]
thanks

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/wiki/Theming

Might greatly help.
