### ISSUE TITLE
Remove pokemon in kitty terminal

### ISSUE THREAD

**Issue by sabindev** [prasanthrangan/hyprdots#74]
Hello, id like to being by saying i absolutely love this rice but im more of minimalist guy and the pokemon in kitty terminal just isnt right for me, but i cant figure out how to remove it.

**Comment by sabindev** [comment]
Removing by deleting the pokemon line in .zshrc

**Comment by prasanthrangan** [comment]
Hi, Thank you so much!

You can remove it from `~/.zshrc` file -

```
#Display Pokemon
pokemon-colorscripts --no-title -r 1,3,6
```

**Comment by DiegoSof2** [comment]
I'm making a custom theme is it possible to change the pokemons for other images?

**Comment by quiet69** [comment]
@DiegoSof2 this [project](https://gitlab.com/phoneybadger/pokemon-colorscripts) is being used. so if you replace the images with your own, it should work fine

**Comment by DiegoSof2** [comment]
> @DiegoSof2 this [project](https://gitlab.com/phoneybadger/pokemon-colorscripts) is being used. so if you replace the images with your own, it should work fine

Thanks

**Comment by serenes0ng** [comment]
for me it was 

~/.hyde.zshrc:5
`pokego --no-title -r 1,3,6`

was searching for it all day 😭
