### ISSUE TITLE
[QUESTION]: android studio too small

### ISSUE THREAD

**Issue by itsmenewbie03** [prasanthrangan/hyprdots#740]
### Description

I recently installed android studio and encountered the same issue with #729. I followed the discussion and was able to fix the issue by updating the userprefs.conf
```
#█░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
#█▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█


# Set your personal hyprland configuration here
# for sample file, please refer https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2

xwayland {
    force_zero_scaling = true
}
```
However this results to Android Studio being scaled down too much(idk if this is the right term xD).

### Expected Behavior

Android Studio should displayed(or scaled) like the other apps.

### Actual Behavior

It is scaled much lower as it appears to be more smaller than the rest of the apps.

### Screenshots (if applicable)
![image](https://github.com/prasanthrangan/hyprdots/assets/89230263/8029e7df-c554-4cae-850e-31625518c746)

**Comment by kRHYME7** [comment]
``` env = GDK_SCALE,2 ```
try. Needs a reboot

**Comment by itsmenewbie03** [comment]
> `env = GDK_SCALE,2` try. Needs a reboot

may i know what does that do?
`GDK_SCALE` and the value `2`

**Comment by kRHYME7** [comment]
xwayland {
    force_zero_scaling = true
}

This one disables scaling for some xwayland apps. Now to compensate for the scaling,  adjust it with ``` env = GDK_SCALE,2 ```


Here's some reference from the dev himself
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/76b4cfe9-8263-4138-b2f0-e76aea3e5ea9)

**Comment by itsmenewbie03** [comment]
> `env = GDK_SCALE,2` try. Needs a reboot

this works however it scales too much, i used `1.5` but does not have any difference with `1`.

**Comment by itsmenewbie03** [comment]
I just used the zoom feature of Android Studio in the Settings and I got it set to my liking.
![image](https://github.com/prasanthrangan/hyprdots/assets/89230263/341768ac-6aca-453a-b78a-fba4d7c5ab84)
I guess I can close this now.
