### ISSUE TITLE
[QUESTION]: custom_apps.lst

### ISSUE THREAD

**Issue by syphant** [prasanthrangan/hyprdots#741]
> You can also create your own list (for ex. custom_apps.lst) with all your favorite apps and pass the file as a parameter to install it -
> ./install.sh custom_apps.lst

Are we only able to add packages to this list that exist in the official repo, or can we add AUR packages to this list as well?

**Comment by kRHYME7** [comment]
You can add both official and AUR. 


* It would be great if we use this repos functionality
https://github.com/prasanthrangan/hyprdots/discussions/categories/q-a
