### ISSUE TITLE
[Bug]: gpg error for wlogout (?)

### ISSUE THREAD

**Issue by JonasD24** [prasanthrangan/hyprdots#742]
### Description

I get the error that a pgp key couldnt be imported.

### Screenshots
![Bildschirmfoto vom 2024-01-16 10-44-44](https://github.com/prasanthrangan/hyprdots/assets/116158239/6a6dca85-5dd1-4b77-9d11-b5cbe2dc41d8)

### Environment

- Linux Distro: EndeavourOS (on qemu)

**Comment by JonasD24** [comment]
Very odd, after using a VPN on my host machine it seems to work now and the key could be imported.

**Comment by leszkolukasz** [comment]
I had the same problem. Solution from this issue worked: https://github.com/ArtsyMacaw/wlogout/issues/3
