### ISSUE TITLE
[Custom] cant login after fresh installation in vmware

### ISSUE THREAD

**Issue by Muhiyaddeen** [prasanthrangan/hyprdots#745]
[MacAoi - VMware Workstation 17 Player (Non-commercial use only) 2024-01-16 18-26-56.zip](https://github.com/prasanthrangan/hyprdots/files/13950303/MacAoi.-.VMware.Workstation.17.Player.Non-commercial.use.only.2024-01-16.18-26-56.zip)

**Comment by kRHYME7** [comment]
https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#vm

``` 
VM?
If not using a VM, skip this step

In a VM, make sure you have 3D acceleration enabled in your virtio config (or virt-manager) otherwise Hyprland will not work.

You can also passthru a GPU to make it work.

Please bear in mind 3D accel in VMs may be pretty slow.


```

**Comment by Muhiyaddeen** [comment]
> https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#vm
> 
> ```
> VM?
> If not using a VM, skip this step
> 
> In a VM, make sure you have 3D acceleration enabled in your virtio config (or virt-manager) otherwise Hyprland will not work.
> 
> You can also passthru a GPU to make it work.
> 
> Please bear in mind 3D accel in VMs may be pretty slow.
> ```

Thank You
