### ISSUE TITLE
wallbash colors on kitty

### ISSUE THREAD

**Issue by talksickisil** [prasanthrangan/hyprdots#748]
I am trying to figure out how to use python-pywal along with hyprdots to have the colors in kitty to update automatically when I change wallpaper with super+alt+ L or R.  I am sorry to bring it here because I do not know where else to turn. I have tried using chat gpt to create a script which does this, but I have not been successful.  Could anybody help me figure this out, or can I request this as a feature? This is something that I used with Stephan Raabes config when it was pre-configured so I know it is possible to do.  I just don't know what I am doing to get it there. This is the best configuration I have seen. I just would like the colors to update in Kitty automatically when wallpaper is changed.

**Comment by kRHYME7** [comment]
we are not using pywal here. The owner made a bash script to get the wallpaper color. It is easier and very configurable. I will try to write for kitty today

**Comment by talksickisil** [comment]
Hello. Yes something like that would be great! I’m sorry if I am outta pocket opening this thread to begin with. This is this first time I have done it on any project.  If I am supposed to close this let me know.  I look forward to your work whenever you do it. Thank you,  I love this project.

**Comment by kRHYME7** [comment]
Would you like to test this? Are you comfortable modifying Files?

**Comment by Skerse** [comment]
I mean modifying files should be fine because if you mess something up you can restore default configs easily with `./install.sh -r` or `Hyprdots restore defaults`

**Comment by talksickisil** [comment]
I’d love to try it. I had previously tried making a script in GPT.

**Comment by kRHYME7** [comment]
Here you go,  I will put the filename on the top so you can create it 

~/.config/hypr/wallbash/kitty.dcol
```
$HOME/.config/kitty/themes/Wall-Dcol.conf|${ScrDir}/wallbashkitty.sh

# Wall Bash Color
# Created by khing

# The basic colors #Inverted when selected
foreground               #<wallbash_pry2> 
background               #<wallbash_pry0> 
selection_foreground     #<wallbash_pry0>  
selection_background     #<wallbash_pry2> 

# Cursor colors
cursor                  #<wallbash_pry1>
cursor_text_color       #<wallbash_pry2> 

# Kitty window border colors
active_border_color     #<wallbash_pry0>
inactive_border_color   #<wallbash_pry2>%            
```

~/.config/hypr/scripts/wallbashkitty.sh 
Aftter having and pasting the script below run :  ``` chmod +x ~/.config/hypr/scripts/wallbashkitty.sh ``` so that it will make the script executable

```
#!/usr/bin/env sh

# set variables
ScrDir=`dirname "$(realpath "$0")"`
source $ScrDir/globalcontrol.sh
kittyDir="${XDG_CONFIG_HOME:-${HOME}/.config}/kitty"

#Override kitty config
if [ "${EnableWallDcol}" -ne 1 ] ; then
 sed -i '/include themes\/Wall-Dcol\.conf/ s/^/#/' "${kittyDir}/kitty.conf"
else
 sed -i '/include themes\/Wall-Dcol\.conf/ s/^#//' "${kittyDir}/kitty.conf"
fi

killall -SIGUSR1 kitty

```

~/.config/kitty/kitty.conf
in this file you can add just this line at the bottom ``` include themes/Wall-Dcol.conf ``` . No need to copy paste the whole line 

```
font_family      CaskaydiaCove Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 9.0
window_padding_width 25
include themes/theme.conf
#background_opacity 0.60
#hide_window_decorations yes
#confirm_os_window_close 0
include themes/Wall-Dcol.conf
```

#### Then enable wallbash
how?
run ``` Hyprdots show binds ``` then it will show the list of your keybindings (neat right? )  search  for something like  
 " wallbash "
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/6fec7956-8bd7-4160-a419-41d7713f8549)
Now there is the keybind assigned to that also you can just press enter to execute that command.


now after doing so try to change your themes or wallpaper to see if it works. 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a3c18631-7c28-4359-a60e-b7d7e64bbeb9)

**Comment by talksickisil** [comment]
This works great except for one thing I must have done wrong somewhere.  I keep getting this error when I switch wallpapers: 

In file /home/user/.config/kitty/themes/Wall-Dcol.conf:
17:Invalid color name: #B43C60% in line: inactive_border_color   #B43C60% 

When I go into the Wall-Dcol.conf file and delete the % at the end of line 17 here, I don't get this warning. But whenever I change wallpapers the % will be added automatically to the end of that line.  Pressing enter will bypass the warning, but how do I stop this warning altogether?  Thank you so much for doing this. Such an awesome community. As always, on your own time you can answer. No hurry!

**Comment by kRHYME7** [comment]
Sorry I think it's a typo.

**Comment by talksickisil** [comment]
No need to apologize! You helped me so much.  You have no idea how much I was racking my brain to try to get pywal functioning before. This is definitely better. Pywal would keep printing a warning about  gtk reload needing python2. I won't bore you with the details. Thanks again.

**Comment by talksickisil** [comment]
How do I do that? Will I need to reopen this first?

**Comment by Skerse** [comment]
On the web client it's as simple as pressing edit near the title, you don't need to reopen it.

**Comment by kRHYME7** [comment]
@talksickisil  Hello maybe we can close this now #811  I started a thread here.

**Comment by talksickisil** [comment]
You got it! Thanks again. This is so good you should consider adding it to install script!
