### ISSUE TITLE
[Bug]: Password get removed after shutdown

### ISSUE THREAD

**Issue by shivamsinghcse** [prasanthrangan/hyprdots#750]
i have install this in my garuda which is pre configured by kde plasma.
but the issue is that whenever my pc got off may be it due it shut down or by power cut all my password credentials get reset it is asking wifi password again and again also all my social media pletform get logout

**Comment by Skerse** [comment]
Weird, i don't know why that would be happening. I don't know if this is a Hyprdots issue though. Since you're using this script on garuda which is an already **heavily** configured desktop, it is a lot harder to give support.

**Comment by kRHYME7** [comment]
If it is kde-plasma  maybe the kdewallet I think this is the one who manages your credentials. 
Here is a similar Issue
https://github.com/prasanthrangan/hyprdots/issues/395 

maybe install it again or just check.

**Comment by ShadeZerox** [comment]
Not sure if I should make a new issue, but the same is happening for me in garuda gnome (I dont think its that heavily customized as compared to its dragonised version).
What I found out is that my password works properly when I choose gnome, but doesn't work when i choose hyprland?!

**Comment by kRHYME7** [comment]
can you try to disable that gnome-keyring setting or something like that.

**Comment by ShadeZerox** [comment]
Okay I suppose I got some solution for the wifi atleast, not sure if it would work for you but what I did was-
right clicked on the wifi logo.
clicked edit connections.
On the new screen clicked on the wifi i need to click (supposing you already used it once) and clicked on the gear icon.
There, I clicked on the Wifi security tab and chose the option to store.
![image](https://github.com/prasanthrangan/hyprdots/assets/155251572/7025437f-8599-45a9-983b-5dd66be4fd67)

**Comment by shivamsinghcse** [comment]
After testing i found that when we install hyprland on top of kde kdewalletmanager get removed/or not installed that cause error in the password saving so we can install that from octopi 
![image](https://github.com/prasanthrangan/hyprdots/assets/121515299/d238b6ff-7e92-4fae-8926-a23c2e433f8e)
