### ISSUE TITLE
[Bug]: [error] theme.css:1:0Expected a valid selector

### ISSUE THREAD

**Issue by Chizuui** [prasanthrangan/hyprdots#756]
[error] theme.css:1:0Expected a valid selector
anyone know how to fix this?
![image](https://github.com/prasanthrangan/hyprdots/assets/127862333/be19115c-dd01-4415-8ea4-696573d55e4d)

**Comment by kRHYME7** [comment]
Hi this si a duplicate of the other issue #752

**Comment by Chizuui** [comment]
i tried reinstall linux and diff error

**Comment by kRHYME7** [comment]
can you run ``` Hyprdots ``` command?

**Comment by Chizuui** [comment]
Nope, I can't

**Comment by kRHYME7** [comment]
I see maybe you did not successfully install Hyprdots 
Here is the output if you run ``` Hyprdots ```

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/230cf8c9-53f6-43a7-9f59-cd08b6ceff29)



### Wait

So this is only a fresh install of Archlinux plus hyprland? you did not reinstall the Hyprdots configuration?
