### ISSUE TITLE
[Feature Request]: Waybar doesn't have a dropshadow even thoug i enabled it in hyprland

### ISSUE THREAD

**Issue by RandomLegend** [prasanthrangan/hyprdots#758]
Heyho,

i configured my drop_shadow as true in the themes folder for all of the themes. But waybar doesn't have a dropshadow. Since there is no layerrule for shadows i don't see how i could enable it.

Any tips for me?

Otherwise everything works perfect thank you for those dotfiles!

**Comment by kRHYME7** [comment]
Because it is not natively supported by maybe the protocol, it should be on the package like waybar( modifying its CSS)

on your ``` ~/.config/waybar/modules/style.css  ```  the other ./style.css is autogenerated, this is the one that should be edited.

add this at the bottom

```
window#waybar > box {
    border-radius: 8px; /* your preference for the curves */
    border: 0.5px solid @main-fg; /* Remove this to remove that borders */
    margin: 4px 8px 8px 8px; 
    background-color:  @main-bg; /* change it your preference but this @ follows the theme */
    box-shadow: 4px 4px 2px 1px @wb-hvr-bg; /* And here is the requested shadow */
}

```


### Examples (Enabled wallbash so that I have consistent color) :

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/ac14e97c-d97d-4aac-8524-022d729d0746)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/d4ed47cb-4ab8-4e31-ad04-139ac4661650)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/16c5e2ed-9172-449a-9fda-c8a0af5f9d41)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/eb203e83-741f-4bcf-8739-051751734ac7)

**Comment by kRHYME7** [comment]
BTW if we call this issue a bug might as well issue this in the Wlroots protocol as this is not related to the Hyprdots or Hyprland as of the moment. 

Can we change the title to a Feature request for waybar instead ?

**Comment by RandomLegend** [comment]
Hey, yeah i changed it to feature request now. Sorry i thought this was bug behaviour.

Thank you very much. However this makes the waybar now one solid bar that spans across the whole display. The current waybar mode i use is one of those that split the modules into little islands. Is it possible to have the shadows be applied only to the islands? The border also draws around the whole span now.

**Comment by kRHYME7** [comment]
I think that's possible you can modify it here ``` ~/.config/waybar/modules/style.css   ```

**Comment by RandomLegend** [comment]
yeah i tried but i can't get it to work the way i do...

I just play around with it until i find something. Thank you very much

**Comment by kRHYME7** [comment]
Yow please let me know too, I did realize I love having some shadows haha

I've managed to modify the left, right, and center elements, but the pill/island appears to be composed of several padding/spacer elements combined to form pills, boxes, etc. To achieve a separate wrapper for each pill, we might need to rewrite the Waybar style generator script.
the pill padding are a different bits of element: 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a943bfac-e0d2-4e4f-a94e-ccb1f13fd1c7)

  
Here is the left, center, right modules
Maybe you already know but I'll drop it here for someone to read. 
```
 .modules-left {
    border-radius: ${c_radius}px;
    border: 0.5px solid @main-fg;
    margin: 4px 8px 8px 8px;
    background-color:  @main-bg;
    box-shadow: 1px 1px 2px 1px @wb-hvr-bg;

}

.modules-center {
    border-radius: ${c_radius}px;
    border: 0.5px solid @main-fg;
    margin: 4px 8px 8px 8px;
    background-color:  @main-bg;
    box-shadow: 1px 1px 2px 1px @wb-hvr-bg;
}

.modules-right {
    border-radius: 8px;
    border: 0.5px solid @main-fg;
    margin: 4px 8px 8px 8px;
    background-color:  @main-bg;
    box-shadow: 1px 1px 2px 1px @wb-hvr-bg;
}
```

Here is the output. I am satisfied with this for now.

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/2195db59-d105-44ae-b4cb-0d8257424d0a)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/4bf33fba-16e8-4abb-81b1-432c98172f22)

**Comment by kRHYME7** [comment]
More info: 

``` 
// positions generated based on config.ctl //

	"modules-left": ["custom/padd","custom/l_end","cpu","memory","custom/gpuinfo","custom/r_end","custom/l_end","idle_inhibitor","clock","custom/r_end","custom/padd"],
	"modules-center": ["custom/padd","custom/l_end","hyprland/workspaces","hyprland/window","custom/r_end","custom/padd"],
	"modules-right": ["custom/padd","custom/l_end","backlight","network","bluetooth","pulseaudio","pulseaudio#microphone","custom/updates","custom/r_end","custom/l_end","tray","battery","custom/r_end","custom/l_end","custom/wallchange","custom/mode","custom/wbar","custom/cliphist","custom/power","custom/r_end","custom/padd"],

```


This part is generated by the wbarstylegen script so I can confirm that we needed to change the script if we would like to make each pill have its borders or shadows.

**Comment by RandomLegend** [comment]
You're a godsent my mate!

Thank you, i didn't find out before you so when i come home i can add your configs!

**Comment by RandomLegend** [comment]
Hey mate, so i finally had some time to play around and i don't know how you achieved that.

![image](https://github.com/prasanthrangan/hyprdots/assets/38812603/2e6e5c47-d798-4221-94eb-65019e15b989)

I have some seperations between the diferent elements. I don't know enough about the structure of the waybar config and the script you guys wrote to manually fix all of this.

The "modules-left" "modules-center" "modules-right" you posted, i can't find it in my config anywhere.

**Comment by kRHYME7** [comment]
> // positions generated based on config.ctl //

	"modules-left": ["custom/padd","custom/l_end","cpu","memory","custom/gpuinfo","custom/r_end","custom/l_end","idle_inhibitor","clock","custom/r_end","custom/padd"],
	"modules-center": ["custom/padd","custom/l_end","hyprland/workspaces","hyprland/window","custom/r_end","custom/padd"],
	"modules-right": ["custom/padd","custom/l_end","backlight","network","bluetooth","pulseaudio","pulseaudio#microphone","custom/updates","custom/r_end","custom/l_end","tray","battery","custom/r_end","custom/l_end","custom/wallchange","custom/mode","custom/wbar","custom/cliphist","custom/power","custom/r_end","custom/padd"],


This is autogenerated by the wbarconfgen.sh

**Comment by RandomLegend** [comment]
i executed wbarconfgen.sh and looked into the config.ctl aswell, still can't find anything there

**Comment by RandomLegend** [comment]
`0|45|bottom|( cpu memory custom/gpuinfo ) ( idle_inhibitor clock )|( hyprland/workspaces hyprland/window )|( backlight network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/cliphist custom/power )
0|45|top|( hyprland/workspaces hyprland/window )|( idle_inhibitor clock )|( cpu memory custom/gpuinfo ) ( backlight network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/cliphist custom/power )
0|45|bottom|( custom/power custom/cliphist custom/mode custom/wallchange ) ( wlr/taskbar custom/spotify ) |( idle_inhibitor clock )|( tray battery ) ( backlight network bluetooth pulseaudio pulseaudio#microphone )
0|45|top||( custom/power ) ( tray battery ) ( wlr/taskbar idle_inhibitor clock ) ( custom/cliphist ) ( ) ( custom/wallchange ) ( custom/mode )|
0|45|bottom|( cpu memory custom/gpuinfo ) ( idle_inhibitor clock ) ( hyprland/workspaces )|( wlr/taskbar )|( backlight network bluetooth pulseaudio pulseaudio#microphone custom/updates ) ( tray battery ) ( custom/wallchange custom/mode custom/cliphist custom/power )
1|45|top|( wlr/taskbar mpris )|( idle_inhibitor clock )|( backlight cpu memory custom/gpuinfo bluetooth pulseaudio puselaudio#microphone ) ( tray battery ) ( custom/wallchange custom/mode custom/cliphist custom/power )
0|45|bottom|( custom/power custom/cliphist custom/mode custom/wallchange ) ( idle_inhibitor clock custom/spotify )|( wlr/taskbar )|( tray ) ( backlight network bluetooth pulseaudio pulseaudio#microphone )
`

This is my config.ctl i got from the repo

**Comment by RandomLegend** [comment]
i found the stuff you posted. it's in the confic.jsonc

But in the confic.jsonc there are no .modules-left parts where i could define shadows. 

Do i just have to copy&paste your edits in there aswell?

**Comment by kRHYME7** [comment]
> i found the stuff you posted. it's in the confic.jsonc
But in the confic.jsonc there are no .modules-left parts where i could define shadows.
Do i just have to copy&paste your edits in there aswell?


If you just want to replicate the comment I posted with 3 elements 
modify  ```  ~/.config/waybar/modules/style.css ``` do not use the other style.css as it is auto-generated 

add your decors for each at the bottom 


```
 .modules-left {
    border-radius: ${c_radius}px;
    border: 0.5px solid @main-fg;
    margin: 4px 8px 8px 8px;
    background-color:  @main-bg;
    box-shadow: 1px 1px 2px 1px @wb-hvr-bg;

}

.modules-center {
    border-radius: ${c_radius}px;
    border: 0.5px solid @main-fg;
    margin: 4px 8px 8px 8px;
    background-color:  @main-bg;
    box-shadow: 1px 1px 2px 1px @wb-hvr-bg;
}

.modules-right {
    border-radius: 8px;
    border: 0.5px solid @main-fg;
    margin: 4px 8px 8px 8px;
    background-color:  @main-bg;
    box-shadow: 1px 1px 2px 1px @wb-hvr-bg;
}

```


You can reread my message about the script above if you're comfortable modifying the script

**Comment by RandomLegend** [comment]
Thank you!

i don't even understand the script so i won't even try to modify it :smile: 

I already pasted it in the ~/.config/waybar/modules/style.css and it works just as you screenshotted it. But the box it draws around the original waybar is 1) much bigger and 2) it groups the right modules into one box instead of splitting them up.

![image](https://github.com/prasanthrangan/hyprdots/assets/38812603/563c621c-89c2-44ac-828a-b1859f2db65c)

I changed the colors to show. The darker one is the original unmodified waybar and the other color is the box from your additional css. Do i need to read and understand your post about the script to be able to change that?

**Comment by kRHYME7** [comment]
Absolutely, I explained how the script works. Maybe I'll try to modify the script to Accept more than 3 separate elements

**Comment by kRHYME7** [comment]
Sadly, it turns out we are limited to 3 positions left right, and center.  So the part I explained above is not useful in waybar. I'll try to find another way soon.

**Comment by RandomLegend** [comment]
Bummer, but thank you so much for caring!

**Comment by kRHYME7** [comment]
BTW, have you seen some dots decorating more than 3 elements? Just like how you envisioned it?

 Example, inside 1 element they divided it into 3 more  so they can decorate more than just 3. I would like to learn how they do that. And hope that it will be easier to implement in the script.
