### ISSUE TITLE
[Bug]: Revert windows style after using gamemode

### ISSUE THREAD

**Issue by Dewinz** [prasanthrangan/hyprdots#759]
Hello,

As I was researching how to put games on my Linux machine with Hyprdots I found the gamemode shell script.
I ran it and it worked as I expected, but when I wanted to revert the changes by running the script again I found that the borders weren't returning to how they were before.
What I mean specifically is the rounding of the borders, the space between went to back to how they were before running the script.

I looked at the code the shell script ran and found the line
`keyword decoration:rounding 0;"`
so I decided to try and flip that to
`keyword decoration:rounding 1;"`
to no avail.

If there is anything I'm missing like another shell script to reverse this please do tell, or if there are some other configs I can run to fix this.
Please and thank you.

![240119_17h54m25s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/123136676/6a1ebd30-c9ba-44fe-8350-9ff895680186)

**Comment by kRHYME7** [comment]
hyprctl reload should work, but if no try changing themes.

**Comment by RookiexCookie** [comment]
Yea Graphite-mono doesnt got rounded border , but you can change that in ~/.config/hypr/themes/Graphite-Mono.conf

**Comment by Dewinz** [comment]
Thanks for the solution, seemed to completely slip my mind that the theme doesn't have a border to begin with!
Apologies for my inexperience and thank you again.
