### ISSUE TITLE
[Feature Request]: Custom theme/wallpaper change config

### ISSUE THREAD

**Issue by gravelord-nito** [prasanthrangan/hyprdots#764]
### Description

Having a custom config file to be applied when changing themes?

Sorry if it's already achievable, haven't looked deep enough into the configs yet.

### Use Case

Many other apps, keyboard backlighting/aura, etc... can be customized to be synced with themes.

Also there might be people who may wanna use other terminals, maybe something lightweight like foot can be added to the initial setup just like having multiple shells, but there always can be more customization people may need and this way they can do it themselves.

### Proposed Solution

As mentioned above, making a custom bash/conf file that is applied whenever the themes switch(maybe inputting a palette too?).

### Alternatives

Maybe you could just look for the keybinds/rofi actions and apply changes on theme/wallpaper change yourself.

### Additional Information

None

**Comment by kRHYME7** [comment]
would you like to manually input a palette.?

**Comment by abenezerw** [comment]
Could you close as solved if you no longer have this issue. Thank you @gravelord-nito
