### ISSUE TITLE
[Question]: Have some questions

### ISSUE THREAD

**Issue by MRParag95** [prasanthrangan/hyprdots#768]
1. if i want my custom config Powerlevel10k how i can setup? (when i try to do it using "p10k configure" it gives me an warning...
2. When i use jetbrains IDE the autosuggestion bar gets narrower and narrower every time i type. how to fix it?

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/discussions/categories/q-a

Hi! We have our discussion panel here.
