### ISSUE TITLE
How to not break theme selector when increading dpi?

### ISSUE THREAD

**Issue by KierPrev** [prasanthrangan/hyprdots#77]
![image](https://github.com/prasanthrangan/hyprdots/assets/44746791/739ace5e-390b-4310-82e6-4f81d8c71ef1)
Elements were too small for me, I increased the option in hypr conf monitor to 1.3, but then the theme selector doesn't show up :(

What would be the way to fix this?  Or maybe not using the monitor conf, but something else to increase the size of everything.

**Comment by KierPrev** [comment]
Btw, this project is amazing and I love it!  
See how I added a bluetooth battery level :D  using {device_battery_percentage}

**Comment by prasanthrangan** [comment]
Hi, Thank you so much!

Please try adjusting the icon size in `~/.config/rofi/themeselect.rasi` -
```.
element-icon {
    size:                        450px;
```
try decreasing this size to fit your screen res.

**Comment by KierPrev** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/44746791/fca16017-4868-4cdb-b4bf-7013484d171e)
We're soo baaaaack   😁
Thanks, glad that I asked  

Cheers, have a nice day :D  ✨

> Thanks again :) Ah cool I didn't know that, how does the bluetooth battery level work when multiple devices are connected ??

It shows the current battery level for the last connected device.
