### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by se7en-x230** [prasanthrangan/hyprdots#772]
andybody get 

](error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8))](error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8))

**Comment by kRHYME7** [comment]
is your internet connection okay?

**Comment by se7en-x230** [comment]
speedtest with a nearby server looks normal but cloning another bigger git repo fails as well after about 10 mb

**Comment by kRHYME7** [comment]
Hello, There is a way to fetch updates on your clone directory too. 

You can run ``` Hyprdots update ```
