### ISSUE TITLE
[Bug]: Can't run install.sh either way..

### ISSUE THREAD

**Issue by scribeby** [prasanthrangan/hyprdots#773]
### Description

So basically I'm on a fresh arch minimal installation and when i run "./install.sh" it says "cp: cannot create regular file "install_pkg.lst': Permission denied. So naturally I ran it as sudo to fix the issue. Nope, gives me this error: "Running makepkg as root is not allowed as it can cause permenant, catastrophic damage to your system."

### Steps to Reproduce

1. Use Arch Linux minimal
2. Run as sudo or normal, same issue??

### Expected Behavior

To continue the installation as normal

### Actual Behavior

No matter how I run it it gives me an error about the other.

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: Arch lunux
- Linux Version: 6.7.0
- Hyprland Version: Latest as of writing this
- Installation Environment: Main hardware

**Comment by Loudge** [comment]
I had the same problem with an EndeavourOs installation, with no desktop environment.
Actually I found a solution.

Find the location of the install.sh file : 
`cd ~/hyprdots/Scripts`

`sudo chmod +x install.sh`


Then you should edit the install.sh file. 
`nano install.sh`

In the file, at line 98, you will find the following code that is causing trouble : 
`cp custom_hypr.lst install_pkg.lst`

Just add sudo in the beggining so the line, so this specific command will be ran as superuser : 
`sudo cp custom_hypr.lst install_pkg.lst`

Normally, the rest of the installation will work.
I had another trouble, in the end it will ask you if you want to delate a protected file. You should say no, as saying yes will stop the installation.

**Comment by Loudge** [comment]
I had the same problem with an EndeavourOs installation, with no desktop environment.
Actually I found a solution.

Find the location of the install.sh file :
`cd ~/hyprdots/Scripts`

Then give the file the right to execute code : 
`sudo chmod +x install.sh`

Then you should edit the install.sh file : 
`nano install.sh`

In the file, at line 98, you will find the following code that is causing trouble :
`cp custom_hypr.lst install_pkg.lst`

Just add sudo in the beggining so the line, so this specific command will be ran as superuser :
`sudo cp custom_hypr.lst install_pkg.lst`


I had another trouble, in the end it will ask you if you want to delate a protected file. You should say no, as saying yes will stop the installation.
Aside from that, everything should work.

**Comment by Loudge** [comment]
I had the same problem with an EndeavourOs installation, with no desktop environment.
Actually I found a solution.

Find the location of the install.sh file :
`cd ~/hyprdots/Scripts`

Then give the file the right to execute code :
`sudo chmod +x install.sh`

Then you should edit the install.sh file :
`nano install.sh`

In the file, at line 98, you will find the following code that is causing trouble :
`cp custom_hypr.lst install_pkg.lst`

Just add sudo in the beggining so the line, so this specific command will be ran as superuser :
`sudo cp custom_hypr.lst install_pkg.lst`

I had another trouble, in the end it will ask you if you want to delete a protected file. You should say no, as saying yes will stop the installation.
Aside from that, everything should work.

**Comment by marcus-universe** [comment]
> I had the same problem with an EndeavourOs installation, with no desktop environment. Actually I found a solution.
> 
> Find the location of the install.sh file : `cd ~/hyprdots/Scripts`
> 
> Then give the file the right to execute code : `sudo chmod +x install.sh`
> 
> Then you should edit the install.sh file : `nano install.sh`
> 
> In the file, at line 98, you will find the following code that is causing trouble : `cp custom_hypr.lst install_pkg.lst`
> 
> Just add sudo in the beggining so the line, so this specific command will be ran as superuser : `sudo cp custom_hypr.lst install_pkg.lst`
> 
> I had another trouble, in the end it will ask you if you want to delete a protected file. You should say no, as saying yes will stop the installation. Aside from that, everything should work.

I still have this same issue even after following these steps :/

**Comment by opticblu** [comment]
sudo chown -R username:username /home/username

replace "username" above with your username

PS running scripts that you don't know/didn't write as root "naturally" will cause problems if it hasn't already

**Comment by nonme** [comment]
While the solutions above might fix the issue, the reason for it to occur is sudoing git clone (in my case). 
Simply 

`rm -rf ~/Hyprdots`

 and clone it without sudo resolved the issue for me.
