### ISSUE TITLE
Waybar Network Style

### ISSUE THREAD

**Issue by RAprogramm** [prasanthrangan/hyprdots#774]
Hello, i wanted to suggest new waybar network style.

simple (just network icon)
![240123_08h45m30s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/70325462/5308a98d-751f-4d51-a749-ce5087ec960a)

alt (up and down speed)
![240123_08h46m22s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/70325462/87417414-eb75-4b31-be0e-2c4311f0b888)

tooltip (more info)
![240123_08h47m00s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/70325462/6cd34e6d-82c8-45db-9317-34fa86de70e0)

**Comment by kRHYME7** [comment]
Hello I would love to try this

**Comment by RAprogramm** [comment]
> Hello I would love to try this

I'll make PR soon
