### ISSUE TITLE
[QUESTION]: Setting external monitor display mode.

### ISSUE THREAD

**Issue by itsmenewbie03** [prasanthrangan/hyprdots#775]
### Description

As someone who spent most my time using windows until last year and tried Ubuntu at first I was able to easily set the monitor display to mirror mode. Now I can't find ways that I understand on how to achieve that.

### Screenshots (if applicable)
This is what I use in Windows. I don't own this screenshot it belongs to this [site](http://www.edtittel.com/blog/winkeyp-powers-display-projection.html).
![image](https://github.com/prasanthrangan/hyprdots/assets/89230263/f85996f9-635c-461a-a608-b0535e55f8e2)

### Additional Information

I tried to read [this](https://wiki.hyprland.org/Configuring/Monitors/) but I'm having trouble trying to understand it. If there is any GUI tool that is similar to the screenshot I posted it will be much awesome. But a CLI tool will also be fine.

**Comment by kRHYME7** [comment]
https://github.com/nwg-piotr/nwg-displays

For now I can recommend you using this.

**Comment by itsmenewbie03** [comment]
> https://github.com/nwg-piotr/nwg-displays
> 
> For now I can recommend you using this.

I'll look into this.

**Comment by itsmenewbie03** [comment]
I'll keep this issue open for possible suggestions.

**Comment by itsmenewbie03** [comment]
> Or we can have this on discussions?

how to do that?

**Comment by abenezerw** [comment]
Could you close as solved if you no longer have this issue. Thank you @itsmenewbie03
