### ISSUE TITLE
I guess code should be a dependency

### ISSUE THREAD

**Issue by se7en-x230** [prasanthrangan/hyprdots#776]
./create_cache.sh: line 137: code: command not found

**Comment by kRHYME7** [comment]
```
❯ cat ./custom_hypr.lst | grep code
visual-studio-code-bin
```

Can you try to install it? It is already should be installed.

**Comment by se7en-x230** [comment]
Ahhh I understand.

I removed visual-studio as I don't use it.

My fault

**Comment by kRHYME7** [comment]
I see, remove the code block with ``` code ``` in it and you're good to go.
