### ISSUE TITLE
Need Help, second Monitor and my primary gpu is intel and not nvidia, i have a acer nitro 5, rtx 3050 laptop

### ISSUE THREAD

**Issue by RayDCabrera** [prasanthrangan/hyprdots#777]
First.
I can't move the place of my second monitor, is always on the right and i need on the left, i installed arandr but i cant..

Second.
   ​​ ​​​  : raymondcabrera@archlinux 
                                              ┌──────────────────────────────────────────┐ 
                                               ​​ ​  CPU : Intel i5-10300H (8) @ 4.500GHz 
                                               ​​ ​  GPU : NVIDIA GeForce RTX 3050 Mobile 
                                               ​​ ​  GPU : Intel CometLake-H GT2 [UHD Graphics] 
                                               ​​ ​ ** GPU Driver : i915** 
                                               ​​ ​ ﬙ Memory : 2807MiB / 23866MiB 
                                              └──────────────────────────────────────────┘ 
                                              ❯ ./gpuinfo.sh
./gpuinfo.sh: line 4: nvidia-smi: command not found
jq: parse error: Invalid numeric literal at line 1, column 3
jq: parse error: Invalid numeric literal at line 1, column 3
jq: parse error: Invalid numeric literal at line 1, column 3
jq: parse error: Invalid numeric literal at line 1, column 3
./gpuinfo.sh: line 23: [: : integer expression expected
{"text":"55°C", "tooltip":"Primary GPU: Intel GPU\n❄️ Temperature: 55°C"}
this says that is not using my nvidia and i install nvidia-dkms and now says this.....
❯ ./gpuinfo.sh
{"text":"N/A", "tooltip":"Primary GPU: Not found"}
gpu not found.. please help
and my neofetch still say gpu driver i915 its suppose to say nouveau right?
![Uploading 240123_01h02m34s_screenshot.png…]()

**Comment by kRHYME7** [comment]
> First.
I can't move the place of my second monitor, is always on the right and i need on the left, i installed arandr but i cant..


try to use nwg-display or wlr-randr 
https://github.com/nwg-piotr/nwg-displays
https://aur.archlinux.org/packages/nwg-displays

>Second.

The fix is on #643 Download it and replace the files ```  ~/.config/hypr/scripts/gpuinfo.sh  ```
 and ``` ~/.config/waybar/modules/gpuinfo.jsonc ```

Please try to see if it works for you.

**Comment by RayDCabrera** [comment]
> > First.
> > I can't move the place of my second monitor, is always on the right and i need on the left, i installed arandr but i cant..
> 
> try to use nwg-display or wlr-randr https://github.com/nwg-piotr/nwg-displays https://aur.archlinux.org/packages/nwg-displays
> 
> > Second.
> 
> The fix is on #643 Download it and replace the files ` ~/.config/hypr/scripts/gpuinfo.sh ` and `~/.config/waybar/modules/gpuinfo.jsonc`
> 
> Please try to see if it works for you.

THAAAANKS its works for me, Now I have a question, what happens if I make it only use my Intel integrated graphics? Is my hyprland going to be slower?

pd: the second problem its very weird, i install nvidia-dkms and now works fine, i just reboot my system and works,
just look, lol
❯ nvidia-smi
Wed Jan 24 00:56:48 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off | 00000000:01:00.0  On |                  N/A |
| N/A   41C    P8               8W /  60W |     31MiB /  4096MiB |     19%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     48333      G   /usr/lib/Xorg                                 4MiB |
|    0   N/A  N/A     48377      G   Hyprland                                      1MiB |
+---------------------------------------------------------------------------------------+
❯ cd .config/hypr/scripts
❯ ./gpuinfo.sh
{"text":"41°C", "tooltip":"Primary GPU: NVIDIA GPU\n❄️ Temperature: 41°C\n󰾆 Utilization: 21%\n Clock Speed: 210/2100 MHz\n Power Usage: 8.94/75.00 W"}

    ~/.config/hypr/scripts                                                                                                                                                                                                                ✔  12:57:06 AM  


but in neofetch says gpu driver i915 hahaha but the bar says nvidia the primary gpu hahaha

**Comment by kRHYME7** [comment]
About the first query that's normal  if you used the modified ./gpuinfo.jsonc You can click on the icon to change GPU queries. More information on the Pull Request.

About the battery usage:
please check some issues on this repo I think the border angle consumes a hell lot of Cpu.

Try to run ``` Hyprdots power save ``` plus flags I suggest if you're using a laptop to disable the borderangle animation

**Comment by RayDCabrera** [comment]
Thaaanks
