### ISSUE TITLE
Issue with dual screen layout.

### ISSUE THREAD

**Issue by kathadris** [prasanthrangan/hyprdots#78]
I have a nvidia optimus laptop with external monitor. Laptop eDP-1. External HDMI-A-1.  In config I have eDP-1 set to 1920x0 position and HDMI-A-1 set to 0x0 position.  eDP-1 sets right but the HDMI-A-1 sets to 3840x0 and it should be 0x0.   Anyway to fix override this?

![2023-08-14-133018_hyprshot](https://github.com/prasanthrangan/hyprdots/assets/115186196/e55c0db0-2437-4813-ad99-61febf8ae019)

![2023-08-14-133031_hyprshot](https://github.com/prasanthrangan/hyprdots/assets/115186196/11b1d6a7-c639-4d15-9cec-ee6705db1c47)

**Comment by prasanthrangan** [comment]
Hi, can you please check if there is anything set in `~/.config/hypr/monitors.conf`.
Not sure where this `3840x0` value is set, does it work the other way around?

**Comment by kathadris** [comment]
Tried to reinstall to look at this but waybar-hyprland-git is failing to build right now. Tried three times and tried manually same issue. Also tried waybar-hyprland with same result. So something on them is failing. Will try back tomorrow to see if it will build.
