### ISSUE TITLE
[Bug]: Cant switch language

### ISSUE THREAD

**Issue by Raze4284** [prasanthrangan/hyprdots#781]
**Description:**
I use manjaro linux and I have 2 language layouts in the system: russian and english. When i press WIN+K (standart switch combination) language does not switch

https://github.com/prasanthrangan/hyprdots/assets/38469989/e9540cfa-911c-44c2-ba57-98bb45d80ff5

**Comment by kRHYME7** [comment]
I do not know how multi-language works cause I only use us as my keyboard layout. 

What is the output of this? ``` cat ~/.config/hypr/hyprland.conf ~/.config/hypr/userprefs.conf | grep "kb_layout" ``` 

Should changing keyboard layout change system language too?

**Comment by Raze4284** [comment]
`cat ~/.config/hypr/hyprland.conf ~/.config/hypr/userprefs.conf | grep "kb_layout"
kb_layout = us`

No, keyboard layout cant change system language, only keyboard layout.
System now on Russian, but keyboard also cant switch

**Comment by Raze4284** [comment]
I fixed, added in hyprland.conf russian
Btw thank you.
