### ISSUE TITLE
Can't change keyboard layout when system locked

### ISSUE THREAD

**Issue by Engardian** [prasanthrangan/hyprdots#784]
The thing is that I use several keyboard layouts and the combination to switch them is Super + Space. When the system is not locked, it works, but when it is locked, swaylock perceives this key combination as a password. Perhaps this can be configured in some of the configurations that I couldn't find, or is this a bug/problem? I would also like to add that this is a problem for me, because if I press Super + L with the keyboard layout enabled, which does not contain the characters required for the password, I have to reboot the system.

**Comment by kRHYME7** [comment]
make bind to bindl.
