### ISSUE TITLE
[Feature Request]: Also change neovim colorscheme with themeswitch.sh

### ISSUE THREAD

**Issue by ps-leonardo** [prasanthrangan/hyprdots#785]
### Description

When changing themes, e.g SUPER+SHIFT+T, besides changing the themes for kitty, code, dolphin etc, also change them for neovim.

### Use Case

I like when my tools match, and everytime I wanna swap themes, I have to manually change my neovim colorscheme

### Proposed Solution

I have [poorly] edited themeswitch.sh to also change my neovim config files and add the new colorscheme (at least the ones that I could find). Howerver,  I am using LazyVim and am doing it in a not so efficient way.

Anyways, if there's interest I can share the code, or even make a PR, and if someone have suggestions to make it less LazyVim dependant, even if just for me, let me know.

**Comment by kRHYME7** [comment]
hello you do not need to change the themeswitch

**Comment by NerdzzyDev** [comment]
You just need to use the standard neovim theme. 
Then it will automatically change when the hyprdots theme
![240127_23h38m51s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/55660001/03461ad4-4fa2-4b4c-9f72-4fb4a7736c30)
![240127_23h38m37s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/55660001/09f64678-022a-4d9f-a9ef-a42f6f9bb9b3)
![240127_23h38m14s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/55660001/df57721f-9ea1-4f6e-8ab2-d731a2822a2f)
![240127_23h37m49s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/55660001/35219326-026f-46b4-b761-bf37558a3440)
 changes. You will only need to change the color of some elements. I don't think it's a good idea to add this element to the main code. Many people prefer to set this up themselves. I have attached an example of how this might look. So try just installing the default theme.

**Comment by kRHYME7** [comment]
Hello this is hardcoded to each theme right? Can I try it?

**Comment by NerdzzyDev** [comment]
> Hello this is hardcoded to each theme right? Can I try it?

yep, because  the standard nvim theme adapts to the terminal theme.  you can try this using `:colorsheme default` in nvim (as shown in the screenshots).  And if you like it, then add the theme you are using to the nvim config file

**Comment by kRHYME7** [comment]
Wow I see. What happens if the wallbash is enabled? what color does it follow?

**Comment by ps-leonardo** [comment]
I didn't know it worked like that. Thanks. I'll mark this as closed then
