### ISSUE TITLE
Spicetify theme not working

### ISSUE THREAD

**Issue by HornanKattila** [prasanthrangan/hyprdots#786]
i have installed spotify and spicetify, i ran the restore_app.sh script, which from my understanding should apply a theme to spotify.
but when i open spotify it's just normal spotify. 
when opened from terminal it says `/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)`
`(spotify:8608): Gtk-WARNING **: 22:02:19.426: Theme parsing error: gtk.css:3213:16: Unit is missing.`
`/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)`

spotify from AUR
OS: EndeavourOS

**Comment by shivambegin** [comment]
same thing happening with me as well so i m now manually switching spotify theme to the system theme.

**Comment by aryan-212** [comment]
> i have installed spotify and spicetify, i ran the restore_app.sh script, which from my understanding should apply a theme to spotify. but when i open spotify it's just normal spotify. when opened from terminal it says `/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)` `(spotify:8608): Gtk-WARNING **: 22:02:19.426: Theme parsing error: gtk.css:3213:16: Unit is missing.` `/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)`
> 
> spotify from AUR OS: EndeavourOS

It's pretty simple, just

`yay -S spicetify-cli
sudo chmod a+wr /opt/spotify
sudo chmod a+wr /opt/spotify/Apps -R`

This worked for me.

**Comment by kRHYME7** [comment]
@aryan-212  Thanks!

**Comment by aryan-212** [comment]
> @aryan-212 Thanks!
> 
> For everyone who might want to add this to the script https://gist.github.com/kRHYME7/3b9931f35e0419bba5e802913e615cdd
> 
> Should we submit a PR ?

yessss

**Comment by H1manshu-Soni** [comment]
is the spotify theme taken down? because on a fresh install even after running the script it says the theme "sleek" is not found so it spicetify not an option anymore?

**Comment by AzanAdnan23** [comment]
Hey, how to set spotify to change according to the theme. i have to set them manually by spicetify apply.

**Comment by kRHYME7** [comment]
Try to search on the Issues and discussions. So far some problems have already been solved there.

**Comment by AzanAdnan23** [comment]
i tried the following command but it doesn't work.
sudo chmod a+wr /opt/spotify && sudo chmod a+wr /opt/spotify/Apps -R

**Comment by kRHYME7** [comment]
@AzanAdnan23  what is the output if you run ``` ~/.config/hypr/scripts/wallbashspotify.sh  ``` in the terminal ?

**Comment by kRHYME7** [comment]
check if  ``` spicetify config   ``` gives
```
prefs_path                    /home/username/.config/spotify/prefs
```

Try this commands

```
spicetify backup apply || spicetify restore backup
spicetify apply
```

or simply

```
spicetify restore apply  
```

**Comment by KitsuneKode** [comment]
I wanna try this and i have the latest commit ! On doing `~/.config/hypr/scripts/wallbashspotify.sh `  this is the output`config/hypr/scripts/wallbashspotify.sh': No such file or directory`. I mean there was no scripts directory inside of hypr!

I created wallbashspotify.sh but it is dependent on  `hypr/scripts/globalcontrol.sh` but that shows this `r/scripts/globalcontrol.sh: No such file or directory` 

Am I the only one who has this issue?
