### ISSUE TITLE
How to get that spotify rice in demo video?

### ISSUE THREAD

**Issue by KisenaMiyuki** [prasanthrangan/hyprdots#788]
Seen in wallbash_720p.mp4
I suppose that's a theme from spicetify but couldn't find anything like that in the marketplace

**Comment by kRHYME7** [comment]
Hello please Comment on some other open issues. as we have many duplicate issues here. Thanks.

**Comment by kRHYME7** [comment]
First install Spotify and spicetify-cli  

then run these commands according from this [comment](https://github.com/prasanthrangan/hyprdots/issues/786#issuecomment-1912178846)

 ``` sudo chmod a+wr /opt/spotify && sudo chmod a+wr /opt/spotify/Apps -R ```

**Comment by kRHYME7** [comment]
Closing this for now as permissions are handled upon install and a polkit popup. Please reopen if neccessary.
