### ISSUE TITLE
[Bug]: can't boot to arch

### ISSUE THREAD

**Issue by Darshil-154** [prasanthrangan/hyprdots#789]
### Description

When i reboot after installation it doesn't boot any solution 

### Steps to Reproduce

1. Install arch minimal
2. Install hyprland
3. Reboot

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots

![Screenshot_20240126-163056_Photos](https://github.com/prasanthrangan/hyprdots/assets/118457005/d3348801-34b3-4251-9751-6f30a23c6db8)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by kRHYME7** [comment]
>Environment
[Please add any other relevant information about the bug and remove the unnecessary lines.]

>e.g.,

>Linux Distro: [e.g., ArchLinux, EndeavourOS]
Linux Version, output of uname -a:
Hyprland Version, output of hyprctl version:
Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
Other info: [e.g., Display Resolution, Resolution, etc]
Additional Information
[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]


What CARd you used nvidia, and intel ?

**Comment by Darshil-154** [comment]
nvidia gforce gt 730

sir you know any fix for that

**Comment by kRHYME7** [comment]
Is this a fresh install?

**Comment by Darshil-154** [comment]
> ~Is this a fresh install?~
> 
> Have you tried to check the wiki about this GPU?
> 
> I can help you with the problem on #790. But to solve this "can't boot to arch" is so vague. Can you try to reinstall minimal arch? Then maybe we can guide you on Installing the Hyprdots?

ok i am ready

**Comment by Darshil-154** [comment]
> ~Is this a fresh install?~
> 
> Have you tried to check the wiki about this GPU?
> 
> I can help you with the problem on #790. But to solve this "can't boot to arch" is so vague. Can you try to reinstall minimal arch? Then maybe we can guide you on Installing the Hyprdots?

Yes it said this has no support
https://bbs.archlinux.org/viewtopic.php?id=276080

**Comment by kRHYME7** [comment]
I see, before we start. 
As I understand you want to install Hyprdots without making it install the nvidia-dkms? Is this correct?

**Comment by Darshil-154** [comment]
> I see, before we start. As I understand you want to install Hyprdots without making it install the nvidia-dkms? Is this correct?

Yes cause dkms is not supported

**Comment by Darshil-154** [comment]
So i close issue #790 ?

**Comment by kRHYME7** [comment]
Alright. 
Follow this 
``` cd ~/Hyprdots/Scripts/```

then 

edit this file, with what editor you have 
```  ./install.sh   ```

find the part that looks like this 

```
    #--------------------------------#
    # add nvidia drivers to the list #
    #--------------------------------#
    if nvidia_detect; then
        cat /usr/lib/modules/*/pkgbase | while read krnl; do
            echo "${krnl}-headers" >>install_pkg.lst
        done
        IFS=$' ' read -r -d '' -a nvga < <(lspci -k | grep -E "(VGA|3D)" | grep -i nvidia | awk -F ':' '{print $NF}' | tr -d '[]()' && printf '\0')
        for nvcode in "${nvga[@]}"; do
            awk -F '|' -v nvc="${nvcode}" '{if ($3 == nvc) {split(FILENAME,driver,"/"); print driver[length(driver)],"\nnvidia-utils"}}' .nvidia/nvidia*dkms >>install_pkg.lst
        done
        echo -e "\033[0;32m[GPU]\033[0m: detected // ${nvga[@]}"
    else
        echo "nvidia card not detected, skipping nvidia drivers..."
    fi

```

now remove that  part

**Comment by kRHYME7** [comment]
> So i close issue https://github.com/prasanthrangan/hyprdots/issues/790 ?

It's fine to leave that open for now.

**Comment by Darshil-154** [comment]
> Alright. Follow this ` cd ~/Hyprdots/Scripts/`
> 
> then
> 
> edit this file, with what editor you have ` ./install.sh `
> 
> find the part that looks like this
> 
> ```
>     #--------------------------------#
>     # add nvidia drivers to the list #
>     #--------------------------------#
>     if nvidia_detect; then
>         cat /usr/lib/modules/*/pkgbase | while read krnl; do
>             echo "${krnl}-headers" >>install_pkg.lst
>         done
>         IFS=$' ' read -r -d '' -a nvga < <(lspci -k | grep -E "(VGA|3D)" | grep -i nvidia | awk -F ':' '{print $NF}' | tr -d '[]()' && printf '\0')
>         for nvcode in "${nvga[@]}"; do
>             awk -F '|' -v nvc="${nvcode}" '{if ($3 == nvc) {split(FILENAME,driver,"/"); print driver[length(driver)],"\nnvidia-utils"}}' .nvidia/nvidia*dkms >>install_pkg.lst
>         done
>         echo -e "\033[0;32m[GPU]\033[0m: detected // ${nvga[@]}"
>     else
>         echo "nvidia card not detected, skipping nvidia drivers..."
>     fi
> ```
> 
> now remove that part

Ok wait

**Comment by kRHYME7** [comment]
Another way to make it more effective 

``` cd ~/Hyprdots/Scripts/ ```
in that directory  same directory 

edit this ``` ./global_fn.sh  ```

at the bottom you will see this 

```
nvidia_detect()
{
    if [ `lspci -k | grep -A 2 -E "(VGA|3D)" | grep -i nvidia | wc -l` -gt 0 ]
    then
        #echo "nvidia card detected..."
        return 0
    else
        #echo "nvidia card not detected..."
        return 1
    fi
}
```

you see those return 0 and return 1. Make all the return values into 1 . This way it will assume no nvidia is present. 



after you can run 

``` install.sh ```

**Comment by Darshil-154** [comment]
> Another way to make it more effective
> 
> `cd ~/Hyprdots/Scripts/` in that directory same directory
> 
> edit this `./global_fn.sh `
> 
> at the bottom you will see this
> 
> ```
> nvidia_detect()
> {
>     if [ `lspci -k | grep -A 2 -E "(VGA|3D)" | grep -i nvidia | wc -l` -gt 0 ]
>     then
>         #echo "nvidia card detected..."
>         return 0
>     else
>         #echo "nvidia card not detected..."
>         return 1
>     fi
> }
> ```
> 
> you see those return 0 and return 1. Make all the return values into 1 . This way it will assume no nvidia is present.
> 
> after you can run
> 
> `install.sh`

I will do this one

**Comment by kRHYME7** [comment]
In case this discussion might become too long you can DM me in my dump discord. Here is my ID ``` khing0v0 ``` . Goodluck.

**Comment by Darshil-154** [comment]
> In case this discussion might become too long you can DM me in my dump discord. Here is my ID `khing0v0` . Goodluck.

Ok sir

**Comment by kRHYME7** [comment]
We can close this now. This is somewhat related to #790

**Comment by Darshil-154** [comment]
> We can close this now. This is somewhat related to #790

Ok

**Comment by Darshil-154** [comment]
This has been fix thanks to @kRHYME7
