### ISSUE TITLE
icons in rofi are not centered

### ISSUE THREAD

**Issue by katanayka** [prasanthrangan/hyprdots#796]
Hello, just yesterday I installed hyprdots, I encountered a problem, the icons in rofi are not centered. 
This applies to all themes
![image](https://github.com/prasanthrangan/hyprdots/assets/102469200/5689e07c-87bf-4964-a98c-6c1bad2555b5)

**Comment by katanayka** [comment]
I just noticed, most likely this is due to the fact that the buttons themselves are not round, but oval

**Comment by kRHYME7** [comment]
@TurtleMeds Hello @katanayka  ,👋
This is a normal behavior and I can't find a configuration regarding centering the text. Rofi is text-based and those Icons are just glyphs. and most of them aren't centered at all.

I will try to dig deeper into configuring rofi.

**Comment by TurtleMeds** [comment]
This also applies to some waybar configs

**Comment by sujer-ux** [comment]
Specifically for rofi, I was able to correct the centering using the special symbol U+2009 - ( ).
Yes, this is not entirely correct, but it works.

`// Config //
configuration {
    modi:                        "drun,filebrowser,window,run";
    show-icons:                  true;
    display-drun:                " ";
    display-run:                 " ";
    display-filebrowser:         " ";
    display-window:              " ";
    drun-display-format:         "{name}";
    window-format:               "{w}{t}";
    font:                        "JetBrainsMono Nerd Font 10";
    icon-theme:                  "Tela-circle-dracula";
}`

![240224_13h56m44s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/67526489/7ecb3b7a-a5fb-4af3-b181-3c8b20973e1b)

**Comment by kRHYME7** [comment]
Can we use that for waybar  that used glyphs?

**Comment by sujer-ux** [comment]
> Can we use that for waybar that used glyphs?

You can add this special character to any module, in the "format" line, for example:
```
"custom/rofi": {
	"format": " ",
	"on-click": "~/.config/hypr/scripts/rofilaunch.sh d",
	"tooltip": false,
},

``` 
![изображение](https://github.com/prasanthrangan/hyprdots/assets/67526489/3ef30d03-0bfa-4d54-98ab-2111cefcfe6e)
