### ISSUE TITLE
[Bug]: Hyprland becomes laggy

### ISSUE THREAD

**Issue by AzerSD** [prasanthrangan/hyprdots#800]
### Description

Hyprland is very smooth with its animations and everything when freshly logged in, but as time goes on (30min), the animations become janky, and everything seems slow and jittery.

It's not a CPU or RAM issue. There are plenty of free resources. Even if I close everything and open a single terminal, it is still jittery. And even if I open 10 apps on startup, it stays smooth and fast.

But my GPU may be struggling, it's running on around 75% the whole time, also about 90% of the VRAM is being used the whole time, While my cpu is chilling at an average usage of 3%.

I was playing with it and I noticed smth really weird. So I have an external monitor plugged to my laptop. when I move all the apps to the external monitor, the gpu's usage drops from ~75% to ~30%, and everything is smooth again, but the moment I just move my mouse to the laptop's screen, the gpu's usage rockets to 70-90%

I just had a fresh install on a bare-bones arch linux.

### Steps to Reproduce

1. Move the mouse or any app to the laptops monitor -> gpu usage rockets (picture 1)
2. Move all app to the external monitor -> gpu usage drops (picture 2)

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/56733438/b3c70b55-766d-4cd4-9200-1e5001664b3f)

![image](https://github.com/prasanthrangan/hyprdots/assets/56733438/69875bb4-e864-4c12-ac5d-39eb5bc276c6)

### Environment

e.g.,

- Linux Distro: `ArchLinux`
- Linux Version, `Linux 6.7.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 21 Jan 2024 22:14:10 +0000 x86_64 GNU/Linux`
- Hyprland Version: `Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0). Date: Mon Jan 1 12:03:15 2024 Tag: v0.34.0
`
- Installation Environment: On The Main Hardware
- Main Display (laptop) `eDP-1 connected 1440x960+0+0 (normal left inverted right x axis y axis) 300mm x 200mm `
- External Display: `HDMI-A-1 connected 2560x1440+1440+0 (normal left inverted right x axis y axis) 600mm x 340mm`

- GPU (lspci | grep 'VGA'): 03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne (rev c2)

### Additional Information

Also I noticed when moving some apps to the laptop's monitor everything is kinda blury and slow to render (laggy)

**Comment by kRHYME7** [comment]
Hello, I saw this post on Reddit.  Have you tried detaching the external monitor? 
also, what are the refresh rates on these monitors? 
``` hyprctl monitors ```
It's pretty strange...

**Comment by AzerSD** [comment]
> Hello, I saw this post on Reddit. Have you tried detaching the external monitor? also, what are the refresh rates on these monitors? `hyprctl monitors` It's pretty strange...

```bash
Monitor eDP-1 (ID 0):
	2160x1440@60.00100 at 0x0
	description: BOE 0x0893 (eDP-1)
	make: BOE
	model: 0x0893
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 29 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false

Monitor HDMI-A-1 (ID 1):
	2560x1440@59.95100 at 2160x0
	description: ViewSonic Corporation VA2715-QHD WPX222320012 (HDMI-A-1)
	make: ViewSonic Corporation
	model: VA2715-QHD
	serial: WPX222320012
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 29 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```
I'm currently playing with monitors.conf, I'm guessing it's a scaling problem, because of the blury font when I uses the laptops monitor. also because I installed everything while the extarnal monitor is plugged in so it took it's scale as the default one, idk what I'm doing just playing around tbh xd,

yea CPU and RAM are stable, the major changes happens with the GPU and VRAM.

**Comment by kRHYME7** [comment]
Try to detach first the external monitor while having the the issue. 

``` monitor = eDP-1,preferred,auto,1 ``` This should be enough to detect your laptops monitor.

**Comment by AzerSD** [comment]
`monitor=,highres,auto,1`

That fixed the problem, apps are not blury anymore, also gpu is stable, around 30%, vram still 90% but I think that's normal I'm not sure.

The only visual change I noticed is that the laptop's screen resolution changed to a higher resolution, now it looks like a 2160x1440 resolution.

**Comment by kRHYME7** [comment]
So this might be considered hyprland bug ?

**Comment by AzerSD** [comment]
idk if it's a bug, I think all of this happened just because I had an extra monitor installed when installing hyprdots. also the monitors.conf was empty when I checked it.

`wlr-randr` with issue fixed (`monitor=,highres,auto,1` in monitors.conf)
```
HDMI-A-1 "ViewSonic Corporation VA2715-QHD WPX222320012 (HDMI-A-1)"
  Make: ViewSonic Corporation
  Model: VA2715-QHD
  Serial: WPX222320012
  Physical size: 600x340 mm
  Enabled: yes
  Modes:
    2560x1440 px, 59.951000 Hz (preferred, current)
    ...
    720x400 px, 70.082001 Hz
  Position: 2160,0
  Transform: normal
  Scale: 1.000000
  Adaptive Sync: disabled
eDP-1 "BOE 0x0893 (eDP-1)"
  Make: BOE
  Model: 0x0893
  Serial: (null)
  Physical size: 300x200 mm
  Enabled: yes
  Modes:
    2160x1440 px, 60.000999 Hz (preferred, current)
    1920x1200 px, 60.000999 Hz
    ...
    640x480 px, 60.000999 Hz
  Position: 0,0
  Transform: normal
  Scale: 1.000000
  Adaptive Sync: disabled
```

`wlr-randr` with default monitors.conf, (also problem occurs only after reboot, even tho the scaling changed without reboot)
```
HDMI-A-1 "ViewSonic Corporation VA2715-QHD WPX222320012 (HDMI-A-1)"
  Make: ViewSonic Corporation
  Model: VA2715-QHD
  Serial: WPX222320012
  Physical size: 600x340 mm
  Enabled: yes
  Modes:
    2560x1440 px, 59.951000 Hz (preferred, current)
    ...
    720x400 px, 70.082001 Hz
  Position: 1440,0
  Transform: normal
  Scale: 1.000000
  Adaptive Sync: disabled
eDP-1 "BOE 0x0893 (eDP-1)"
  Make: BOE
  Model: 0x0893
  Serial: (null)
  Physical size: 300x200 mm
  Enabled: yes
  Modes:
    2160x1440 px, 60.000999 Hz (preferred, current)
    ...
    640x480 px, 60.000999 Hz
  Position: 0,0
  Transform: normal
  Scale: 1.500000
  Adaptive Sync: disabled
```
:w
The only difference is the scale.

**Comment by kRHYME7** [comment]
> monitor=,highres,auto,1

> That fixed the problem, apps are not blury anymore, also gpu is stable, around 30%, vram still 90% but I think that's normal I'm not sure.

But this fixes it right? 


> idk if it's a bug, I think all of this happened just because I had an extra monitor installed when installing hyprdots. also the monitors.conf was empty when I checked it.

Well, Hyprland does not have any metadata to store this information.  If ```  monitor=,highres,auto,1 ```  solves the problem then your system is not supporting this config ``` monitor = ,preferred,auto,auto ``` that is set inside 
``` ~/.config/hypr/hyprland.conf  ```

**Comment by AzerSD** [comment]
Thanks for your help and feedback, I will close the issue.
Best regards.

**Comment by danfilg** [comment]
> > monitor=,highres,auto,1
> 
> > That fixed the problem, apps are not blury anymore, also gpu is stable, around 30%, vram still 90% but I think that's normal I'm not sure.
> 
> But this fixes it right?
> 
> > idk if it's a bug, I think all of this happened just because I had an extra monitor installed when installing hyprdots. also the monitors.conf was empty when I checked it.
> 
> Yeah not really a bug as it is in the wiki to set some monitors to highres .
> 
> > because I had an extra monitor installed when installing hyprdots
> 
> Well, Hyprland and hyprdots do not have any metadata to store this information. If ` monitor=,highres,auto,1` solves the problem then your system is not supporting this config `monitor = ,preferred,auto,auto` that is set inside `~/.config/hypr/hyprland.conf ` So maybe just setting the monitor declaratively fixes the issues on your system. Nice!

In my case, with a laptop with hybrid graphics, when the external monitor is connected on the hdmi port, of the integrated gpu, there are delays. When connecting to the USB-c DPI connection, the laggy goes away. it seems that one enters the GPU and another in the integrated. has to pay attention to it and use the optimus-manager
