### ISSUE TITLE
[Bug]: Rofi filesystem menu not working

### ISSUE THREAD

**Issue by Antoine-TH0MAS** [prasanthrangan/hyprdots#801]
### Description

The rofi filesystem menu isn't showing anything anymore after changing hyprland.conf

### Steps to Reproduce

1. Install hyprdots
2. Modify the config (monitor)
3. Launch rofi with Super + R

### Expected Behavior

Showing me the home folder

### Actual Behavior
The menu is blank

### Screenshots
![image](https://github.com/prasanthrangan/hyprdots/assets/124618103/05fe42a7-a85f-4a8f-b086-a6e712c53767)
![240128_19h13m26s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/124618103/49f6d42d-e862-402d-8353-ec8a280c0256)

### Environment
Minimal archinstall + hyprdots
Kernel : 6.7.2-arch1-1 
Resolution : 2560x1600 
Lenovo legion slim 5i 16"
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

### Additional Information

No error mesages

**Comment by kRHYME7** [comment]
Other menu Worked?.

The only changes you've done are the monitor right?

What happens if you search something?

Also can you run this on the terminal to see what it throws out.

**Comment by Antoine-TH0MAS** [comment]
It does not display anything when I search.
I also navigated a little in the menu before changing my config but it was only the monitor.
Running in the terminal gives no errors.

**Comment by Its-Haze** [comment]
Use this layout of rofi, it shows the input field atleast..

I have the same issue with the rest of the layouts.
![image](https://github.com/prasanthrangan/hyprdots/assets/90850836/b5e78fe7-1d24-426f-9a2a-0b80fb016c5b)

**Comment by Its-Haze** [comment]
Works for me
![image](https://github.com/prasanthrangan/hyprdots/assets/90850836/fbab3db1-c3bb-4788-b051-09ed07e5378c)

**Comment by kRHYME7** [comment]
>  Running in the terminal gives no errors.

Would you mind sharing those errors, maybe somebody can fix it?

**Comment by abenezerw** [comment]
Could you close as solved if you no longer have this issue. Thank you @Antoine-TH0MAS

**Comment by kRHYME7** [comment]
stale
