### ISSUE TITLE
Nothing happened after installation

### ISSUE THREAD

**Issue by reverbman** [prasanthrangan/hyprdots#804]
After installing Arch with minimal settings, I added GRUB and installed the repository following the recommended instructions. At the end, when I clicked on “Proceed to review,” nothing happened. Later, I tried to reboot, but it returned me to the minimal Arch Linux environment.
Any help would be appreciated, thx.

**Comment by kRHYME7** [comment]
Hello I think you need to re-run install.sh.  After you press enter to review a package installation press q to exit the review and continue the installation

**Comment by trishan9** [comment]
> Hello, I think you need to re-run install.sh.  Your installation is not complete.
> After you press enter to review a package installation press q to exit the review and continue the installation 

Thanks this resolved the issue which made me stuck for an hour
