### ISSUE TITLE
[Bug]: if i direct use waybar config only in my current hyprland i get [error] theme.css:1:0Expected a valid selector 

### ISSUE THREAD

**Issue by HakaishinShwet** [prasanthrangan/hyprdots#805]
i just wanted to implement waybar of this project so i cloned and copy the files of waybar to my waybar folder and when i tried to kill waybar and run with new files i got that error even tho i have cloned exact styles and other files then i got this error any idea devs? i am attaching one image for that too
![20240129_15h11m40s_grim](https://github.com/prasanthrangan/hyprdots/assets/55040435/ed4b06e2-324e-41f6-bb4d-c45a9c5d7a42)

**Comment by HakaishinShwet** [comment]
plus if i am doing something wrong please guide me because i wanted waybar at top with all styles and options as shown in video

**Comment by kRHYME7** [comment]
You did not install Hyprdots right? you just copy the waybar files? Maybe you can open up in the discussion panel as this isn't a bug. 
https://github.com/prasanthrangan/hyprdots/discussions

And this script automates the waybar configuration and style. 
https://raw.githubusercontent.com/prasanthrangan/hyprdots/main/Configs/.config/hypr/scripts/wbarconfgen.sh
https://raw.githubusercontent.com/prasanthrangan/hyprdots/main/Configs/.config/hypr/scripts/wbarconfgen.sh
https://raw.githubusercontent.com/prasanthrangan/hyprdots/main/Configs/.config/hypr/scripts/globalcontrol.sh

**Comment by HakaishinShwet** [comment]
@kRHYME7 yea i told you i didnt installed full because i dont need many things which are implemented by i wanted waybar one so wanted guidance for that. will try to paste those scripts and see if it works or not because hyprland is different and waybar is different and i needed that so thought to copy dots and use but when i got error i got surprised like why same files not working here so thought to ask here
i know it is not bug but there was no other option so maybe dev can add question category to issue template so that we can use that for asking general question because max time i especially either forget to ask in discussion or wanted quick reply as issues are max time resolved quicker so posted here , if anything apart from these files i might be missing then do let me know i will try

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/discussions/categories/q-a

**Comment by HakaishinShwet** [comment]
@kRHYME7 thanks for reply, but unfortunately i got same error :-(( i thought maybe you didnt mentioned about wbarstylegen.sh so i created that too in script and make all those three files executable and then i exact copy paste all the waybar files or his dots to mine main waybar folder as it is still after that i got error :-(( everything is related to style.css is is possible for anyone to direct give style.css for top waybar(in which waybar is at top of screen instead of bottom) directly which i can paste and run my waybar?

**Comment by kRHYME7** [comment]
Oh I pasted same same link, my bad. 

```
 cat ~/.config/waybar/style.css
* {
    border: none;
    border-radius: 0px;
    font-family: "JetBrainsMono Nerd Font";
    font-weight: bold;
    font-size: 11px;
    min-height: 10px;
}

@import "themes/theme.css";


```

do you have  ``` @import "themes/theme.css"; ``` this file? 


```
❯ cat ~/.config/waybar/config.jsonc
//   --// waybar config generated by wbarconfgen.sh //--   //

{
// sourced from header module //

    "layer": "top",
    "position": "bottom",
    "mod": "dock",
    "height": 30,
    "exclusive": true,
    "passthrough": false,
    "gtk-layer-shell": true,


// positions generated based on config.ctl //


```

```    "position": "bottom", ``` 



In case you have a hard time, you can add a separate user. Install this then archive whatever you need from that. That would be easier.

**Comment by kRHYME7** [comment]
Also did you read how the script works?

**Comment by HakaishinShwet** [comment]
@kRHYME7 yes i have that lines when i cat i can see that part too,I told you that i have direct copy paste from this repo so i will have it but i dont how but it is causing issue plus  i have found different easy solution for not what i actually wanted but still i got something i needed in easy way so yea i am using that, and i didnt read in too depth how scripts are working i just copy pasted and tested to see if things work or not and unfortunately it didnt work but thanks for your responses tho :-))
