### ISSUE TITLE
[Bug]: "Signal Lost" screen after login

### ISSUE THREAD

**Issue by franciscoDevv** [prasanthrangan/hyprdots#806]
I was installing hyprland in a vm with arch linux, i did minimal install with archinstall command and then runned the install script, all was going good, but after log in, i see this screen and nothing else.
https://ibb.co/z64pGD8

**Comment by abenezerw** [comment]
It’s laggy and not recommended to install Hyprland in vm, maybe that’s why but 
Could you close as solved if you no longer have this issue. Thank you  @franciscoDevv
