### ISSUE TITLE
How to remap the capslock key to anything useful and swap the alt key with the super (windows key).

### ISSUE THREAD

**Issue by Lol-Lap** [prasanthrangan/hyprdots#81]
How to remap the capslock key to anything useful, like when you press it, it's esc, and when you hold it, it's ctrl or even remap it to, like swap it only. I found in my research in Wayland that it's so hard to do this. I tried everything, basically, but it did not work. even tried the hyprland wiki to put in the hyprland.conf in the input section to remap it also didn't work, so any idea how to do it?

**Comment by prasanthrangan** [comment]
I found this to remap capslock to control key, here in this [wiki](https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/) -
```
input {
    kb_options = ctrl:nocaps
}
```

**Comment by Lol-Lap** [comment]
> I found this to remap capslock to control key, here in this [wiki](https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/) -
> 
> ```
> input {
>     kb_options = ctrl:nocaps
> }
> ```

Yeah, I tried that, but it didn't work. Idk, why any idea!?

**Comment by Lol-Lap** [comment]
> 

I have tried this, but I pasted the kb_options = ctrl:nocaps in the input section that was already there in the hyprland.conf, and it didn't work. Am I doing it right?

**Comment by prasanthrangan** [comment]
this is working for me, i have it set in `hyprland.conf` as below -
![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/dbe2e868-6c8e-41ce-97d3-9169088e4558)

**Comment by Lol-Lap** [comment]
> this is working for me, i have it set in `hyprland.conf` as below - ![image](https://user-images.githubusercontent.com/106020512/261529773-dbe2e868-6c8e-41ce-97d3-9169088e4558.png)

I don't know what I am doing wrong, but it's not working for me.
![image](https://github.com/prasanthrangan/hyprdots/assets/120711779/fa31f26d-22f4-4764-b7a4-223935736354)

**Comment by prasanthrangan** [comment]
> Yeah, this works. Thank you so much. Last thing, any idea how to make it when held down be ctrl and when pressed like one tap, it's esc. and to swap the super with alt key make it like that

No idea on how to make it work as "tap to esc", not sure if this is even possible.
