### ISSUE TITLE
swappy default get overwritten?

### ISSUE THREAD

**Issue by se7en-x230** [prasanthrangan/hyprdots#810]
![image](https://github.com/prasanthrangan/hyprdots/assets/69777713/6dbccd88-ce7f-4d32-a166-64c1c738c88c)

the minute I start the tool the config gets overwritten

**Comment by kRHYME7** [comment]
yes

**Comment by se7en-x230** [comment]
Where could I set the defaults for swappy?

**Comment by kRHYME7** [comment]
Do you want to use swappy as a separate utility for screenshot ?

**Comment by se7en-x230** [comment]
no just would want the arrow as the default paint_tool.

**Comment by se7en-x230** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/69777713/a89b41da-3a2a-48dd-a065-cac8fdcffeb0)

**Comment by se7en-x230** [comment]
thanks
