### ISSUE TITLE
Issue: Black screen when i restart hyprland (mainmod + del)

### ISSUE THREAD

**Issue by RayDCabrera** [prasanthrangan/hyprdots#813]
I dont know why, My specifications are this
![240130_12h13m36s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/113148861/af025d71-ef9f-4947-8cea-36e2e44fd0be)
pls help, and When I turn on my laptop again and log in, I get the image of the girl on my wallpaper, that shouldn't happen right?
and this morning I was working with openoffice calc and my computer stuck and I had to hold down the power button to make it turn off. I need help because with the specifications I have, I don't think I should have this type of problem. I understand that my Nvidia graphics card is being used, or not?

**Comment by kRHYME7** [comment]
> pls help, and When I turn on my laptop again and log in, I get the image of the girl on my wallpaper, that shouldn't happen right?

add this to your config on misc { ..  }

```
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
```

**Comment by RayDCabrera** [comment]
Yes, i have another gpu, but the hyprl just use's nvidia right?, It's strange, because the thing about it freezing was the first time it happened to me, but the thing about pressing main + del, and it going black and forcing me to turn off the laptop, was not the first time  

Does some other package exhibit this? Is this frequent?
Now no, luckily now it's not happening to me anymore

**Comment by kRHYME7** [comment]
I think Hyprland Uses your intel gpu for rendering.

**Comment by RayDCabrera** [comment]
some program or line to watch who gpu was used?
vulkan-tools to watch?

**Comment by RayDCabrera** [comment]
Need help i change the gpu that hyprland use's 
![240202_12h51m11s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/113148861/dcb3436a-1ef4-4b38-9f12-0b6b2bc2d8e6)
Thats my config, i insert that two lines in the env config, and now my second monitor, is the only recognized and my original monitor is freezed

**Comment by kRHYME7** [comment]
why? is this an external GPU?

**Comment by RayDCabrera** [comment]
i have a laptop, and i read this https://wiki.hyprland.org/Configuring/Multi-GPU/ and i put that two lines to just use my nvidia gpu but when i use thats env configs, xrandr just recognize my external monitor, i dont know why

**Comment by kRHYME7** [comment]
Because you set Nvidia as the primary GPU for hyprland. And your laptop monitor is attached to your intel GPU?

 iGPU dGPU eGPU

sorry I ll fire up some gpt
ref:
```
iGPU (Integrated Graphics Processing Unit): This is a graphics processor that is built into the same chip as the CPU. It shares resources with the CPU and doesn't have its own dedicated memory. It's typically found in budget or mid-range laptops and desktops. iGPUs are less powerful compared to dGPUs and eGPUs, but they're also less expensive and consume less power [2](https://en.wikipedia.org/wiki/Graphics_processing_unit).
dGPU (Discrete Graphics Processing Unit): This is a standalone graphics processor that operates independently of the CPU. It has its own dedicated memory, which means it can perform graphics-intensive tasks more efficiently than an iGPU. dGPUs are commonly used in gaming PCs, high-end laptops, and workstations. They offer superior performance for graphics-intensive applications, but they also consume more power and generate more heat [2](https://en.wikipedia.org/wiki/Graphics_processing_unit).
eGPU (External Graphics Processing Unit): This is a graphics processor that's connected to a computer via an external interface, like Thunderbolt or USB-C. An eGPU acts as an extension of the computer's graphics capabilities, providing more power than the computer's built-in GPU. This setup is useful for tasks that require high graphical performance, such as 3D modeling, video editing, and gaming
```

**Comment by RayDCabrera** [comment]
![240202_13h32m53s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/113148861/7905f381-e11e-4a33-ac8e-d8bdad201805)
this

**Comment by kRHYME7** [comment]
why would you choose nvidia as the GPU for hyprland session ?

**Comment by RayDCabrera** [comment]
and more speed? or its the same? because sometime i have bugs, for example, i turn on and my wallpaper doesnt change or y restart the hyprland session and my laptop just freezed, you dont have these problems? can you pls share me your hyprland config?

**Comment by kRHYME7** [comment]
> hyprland config? 

https://github.com/kRHYME7/Hyprdesk Just a fork 
of Hyprdots nothing much. 


I think intel is enough for rendering this. Also have you check your laptop hardware how the main monitor is attached like does it use the  integrated GPU or it can switch to dedicated GPu or it only uses the dGPU for speed. 

>i turn on and my wallpaper doesnt change or y restart the hyprland session and my laptop just freezer

turn on from reboot or turn on from suspend? 
Maybe check your journalctl? in case the problem is on system level..

**Comment by RayDCabrera** [comment]
turn on from reboot or turn on from suspend?
the laptop is on and i press mainmod + DEL.

i can copy your .config files to my .config?

**Comment by kRHYME7** [comment]
Hmm, I think having my .config  is not a solution. 

Let's prioritized first this part I think this is config related . 

>the laptop is on and i press mainmod + DEL.
run 
``` Hyprdots show binds ``` then maybe search for "del" then find that part maybe that's a keybind

**Comment by kRHYME7** [comment]
I see 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/ffcd7941-057e-4e8b-bdb5-55cc6faba0b8)

**Comment by RayDCabrera** [comment]
yes is super+del and my session es off but my laptop stay freezed lol

**Comment by kRHYME7** [comment]
can You describe this freeze?

For example in my case I am not using Display manager so naturally it logs me back to TTY
Like this
![IMG_20240203_013305.jpg](https://github.com/prasanthrangan/hyprdots/assets/53417443/2a6f7bad-fcc7-47ad-a845-b39a63cb9496)

But If I use SDDM the normal behavior will log me out and display Sddm login screen. Can you describe this Freeze? like which part it freezes? Also did it happen only on multiple monitor setup?

**Comment by RayDCabrera** [comment]
yes, only happends me when i have teo monitors, but i dont i never use my hyprland with only one, the freeze is, i press the command button and my screen stay on but black, and i can't do nothing, just holdpress the powerbutton to poweroff my laptop.. that is the problem i have sometimes.

**Comment by RayDCabrera** [comment]
you delete the display manager? 
 how? I tried to do it but I was afraid of breaking something. lol

**Comment by kRHYME7** [comment]
How about testing it first without an external monitor.

Also I think you don't necessarily needed the env for multi GPU. 


About the display  manager, You can turn it off by disabling sddm.service.

In my case I just enabled autologin on my getty.service, more info on arch wiki.
then on my .profile or .zprofile I just run a script that runs hyprlands.

**Comment by RayDCabrera** [comment]
ok thanks man, and im gonna copy your settings looks very good, I just hope something doesn't crash on me hahahahaha

**Comment by kRHYME7** [comment]
Archwiki should be your best friend in that case.
