### ISSUE TITLE
[Bug]: Wallpaper selection is full with unrecognized .png images that shouldn't be there.

### ISSUE THREAD

**Issue by Its-Haze** [prasanthrangan/hyprdots#815]
### Description

Wallpapers are not only retrieved by ``.config/swww/<theme>``, but also ``$HOME/.cache/`` and other places...
I noticed when i ran "SUPER + SHIFT + W" it showed me images that was not wallpapers..

I am using the Catppuccin-Mocha theme, and there are only wallpapers in that directory.

I am not sure exactly how to reproduce this.. since it just happened randomly

### Steps to Reproduce

1. Open the wallpaper selector ``SUPER + SHIFT + W``
2. Observe the wallpapers presented.

### Expected Behavior

Expecting to only see my wallpapers that are located in my ``.config/swww/<theme>/``

### Actual Behavior
Images, that are not wallpapers are showing up as transparent images in the wallpaper selector.

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/90850836/154e3c52-10c6-4973-95ae-f7d5cbd217f6)

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux arch 6.7.2-arch1-1
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
- Installation Environment: Hardware
- Other info: 3 monitors. happened 1-2 days after fresh install of unknown reasons..

### Additional Information
It's good that the image/filename is written in the wallpaper selection. It made it easier to understand what those blank images were. So i tried finding the path to one of them and i found this:

![image](https://github.com/prasanthrangan/hyprdots/assets/90850836/fb60fe39-f81a-4bf3-a900-a51cee3d6523)

```bash
❯ find /home/haze -type f -name "023a59b0f8c245b467f18*"
/home/haze/.cache/thumbnails/large/023a59b0f8c245b467f188fdc3cb7755.png
```
I have no idea why images from my .cache, are showing up as wallpapers. super strange..

I then tried another one.
![image](https://github.com/prasanthrangan/hyprdots/assets/90850836/09b8e36f-4f99-4f2a-8a0f-8182b07f204a)

```bash
❯ find /home/haze -type f -name "aurora_borealis.png"
/home/haze/.config/swww/Decay-Green/aurora_borealis.png
/home/haze/.cache/hyprdots/Decay-Green/aurora_borealis.png
/home/haze/Hyprdots/Configs/.config/swww/Decay-Green/aurora_borealis.png
```
once again, I have no idea why these paths are used to pick wallpapers. I have not modified the behavior of the wallpaper picker. The only thing i did was to run ``SUPER + ALT + LEFT/RIGHT`` arrow a couple of times during the first moments of the installation.. but after a few days after i had used my system, i could no longer switch wallpapers because of these random images being included in the list of wallpapers to pick..

**Comment by kRHYME7** [comment]
It's normal that the path is pointed on the cache because what you see there was just for thumbnails. When did you last update this or installed?

**Comment by Its-Haze** [comment]
> It's normal. That path is pointed on the cached directory of each theme. What you see there was just for thumbnails. ~When did you last update this or installed?~
> 
> So this happens sometimes right?
> 
> can you provide output for `cat ~/.config/hypr/theme.ctl`
> 
> also Try to run `Hyprdots reload`

```bash
❯ cat ~/.config/hypr/theme.ctl

```
Looks like i dont have anything in there.
![image](https://github.com/prasanthrangan/hyprdots/assets/90850836/591b5a0e-ac33-41f8-93a1-178b0ef8bcbb)


```bash
Hyprdots-ctl created a directory: /home/haze/.config/hyprdots-ctl
Unknown theme selected: 
Available themes are:
```
![image](https://github.com/prasanthrangan/hyprdots/assets/90850836/2aa3ab01-8f93-44f8-a472-c8ef25048dd1)

Unknown theme selected... thats strange

**Comment by kRHYME7** [comment]
That's why your configuration is Lost. Something might have been deleted the file. Can you like just navigate that file in the repo and copy paste it see if that's the only one lacking

**Comment by Its-Haze** [comment]
sure, i will try that

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/blob/main/Configs%2F.config%2Fhypr%2Ftheme.ctl


Here's the file . If it doesn't work You can reinstall Hyprdots..


``` Hyprdots restore config ```

Let's you modify what files or directories to be Restored or overwrite.

**Comment by Its-Haze** [comment]
```bash
❯ nvim  ~/.config/hypr/theme.ctl
❯ Hyprdots reload
Selected theme: Catppuccin-Mocha
DP-1: 1920x1080, scale: 1, currently displaying: image: /home/haze/.config/swww/Tokyo-Night/tokyo_pink.png
DP-2: 1920x1080, scale: 1, currently displaying: image: /home/haze/.config/swww/Tokyo-Night/tokyo_pink.png
DP-3: 1920x1080, scale: 1, currently displaying: image: /home/haze/.config/swww/Tokyo-Night/tokyo_pink.png
rm: cannot remove '/home/haze/.config/gtk-4.0': No such file or directory
/home/haze/.config/hypr/scripts/themeswitch.sh: line 124: flatpak: command not found
/home/haze/.config/hypr/scripts/themeswitch.sh: line 125: flatpak: command not found
ok
environment: line 5: /home/haze/.config/spicetify/Themes/Sleek/Wall-Dcol.ini: No such file or directory
sed: can't read /home/haze/.config/spicetify/Themes/Sleek/Wall-Dcol.ini: No such file or directory
```

After reloading Hyperdots, i indeed see the expected result

![image](https://github.com/prasanthrangan/hyprdots/assets/90850836/2af403a5-339a-4a9a-8699-3f25745ffe10)

So thanks for that
