### ISSUE TITLE
[Rofi]: Rofi not working after fresh install.

### ISSUE THREAD

**Issue by AzanAdnan23** [prasanthrangan/hyprdots#816]
Rofi not working after fresh install.

menu bar is not opening for apps.

when i type rofi in terminal it says:
❯ rofi

(process:26831): Rofi-WARNING **: 00:06:25.014: Failed to set locale.

**Comment by AzanAdnan23** [comment]
it opens a window and shows some commands.

**Comment by kRHYME7** [comment]
rofi now pops up?

**Comment by AzanAdnan23** [comment]
I don't know about locale. So, the above command opens Rofi, but when I close it and use the shortcut, it doesn't work.
![image](https://github.com/prasanthrangan/hyprdots/assets/108145762/d4333893-c623-4537-aae3-2b68a6c3764c)

**Comment by AzanAdnan23** [comment]
also one more thing vs code text is blurred.


![image](https://github.com/prasanthrangan/hyprdots/assets/108145762/43f28392-3a50-4bb5-b43f-670de1252825)

**Comment by waqaswasil96** [comment]
> also one more thing vs code text is blurred.
> 
> ![image](https://private-user-images.githubusercontent.com/108145762/301625993-43f28392-3a50-4bb5-b43f-670de1252825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTI3NTMsIm5iZiI6MTcwNzI5MjQ1MywicGF0aCI6Ii8xMDgxNDU3NjIvMzAxNjI1OTkzLTQzZjI4MzkyLTNhNTAtNGJiNS1iNDNmLTY3MGRlMTI1MjgyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNzU0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTM1MWFiN2VmYzM4ZTI4ZDg5NWM4NmRmNDk5OWMyN2ZiNGRiYWJmZjU2ZTFhZjU1OWNlMDM2NmI1ZTcxZDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yOU8l_bybMcBt6aLgZDrDaVyaoI6bRX0wQO7R9Gw0rs)

That's definitely a locale problem. The clock module is also not working on waybar. 
To solve, edit `/etc/locale.gen` and uncomment `en_US.UTF-8 UTF-8`. Generate the locales by running:

`sudo locale-gen`

**Comment by waqaswasil96** [comment]
> I don't know about locale. So, the above command opens Rofi, but when I close it and use the shortcut, it doesn't work. ![image](https://private-user-images.githubusercontent.com/108145762/301615672-d4333893-c623-4537-aae3-2b68a6c3764c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTI3NTMsIm5iZiI6MTcwNzI5MjQ1MywicGF0aCI6Ii8xMDgxNDU3NjIvMzAxNjE1NjcyLWQ0MzMzODkzLWM2MjMtNDUzNy1hYWUzLTJiNjhhNmMzNzY0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNzU0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjU4Y2M0MTYzYzI5MmEyZTMzZmE2OGZhYjQxMzI3YWRjZDYyMGUxMzEyZThiMDliNjdmYzcyOTNkNzAxODBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.boNSm1O25SXPoOnb_8XI-dp53jyphJQko4TtdEDOQ4E)

That's definitely a locale problem. The clock module is also not working on waybar. 
To solve, edit `/etc/locale.gen` and uncomment `en_US.UTF-8 UTF-8`. Generate the locales by running:

`sudo locale-gen`

**Comment by AzanAdnan23** [comment]
Rofi Working. 
But the font is very bad in vs Code & Chrome.
i cant code because of this.

**Comment by RookiexCookie** [comment]
check this out
@AzanAdnan23 https://www.reddit.com/r/hyprland/comments/15jb7l7/blurry_vscode_on_hyprland/

**Comment by AzanAdnan23** [comment]
Thanks it works

**Comment by AzanAdnan23** [comment]
> > I don't know about locale. So, the above command opens Rofi, but when I close it and use the shortcut, it doesn't work. ![image](https://private-user-images.githubusercontent.com/108145762/301615672-d4333893-c623-4537-aae3-2b68a6c3764c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTI3NTMsIm5iZiI6MTcwNzI5MjQ1MywicGF0aCI6Ii8xMDgxNDU3NjIvMzAxNjE1NjcyLWQ0MzMzODkzLWM2MjMtNDUzNy1hYWUzLTJiNjhhNmMzNzY0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNzU0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjU4Y2M0MTYzYzI5MmEyZTMzZmE2OGZhYjQxMzI3YWRjZDYyMGUxMzEyZThiMDliNjdmYzcyOTNkNzAxODBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.boNSm1O25SXPoOnb_8XI-dp53jyphJQko4TtdEDOQ4E)
> 
> That's definitely a locale problem. The clock module is also not working on waybar. To solve, edit `/etc/locale.gen` and uncomment `en_US.UTF-8 UTF-8`. Generate the locales by running:
> 
> `sudo locale-gen`

It is already uncommented and the sudo locale-gen command has been run, but it did nothing.
What I did was add this command in the Hyprland keybinds file: `bind =$mainMod , R ,exec, export LC_ALL=C && ~/.config/hypr/scripts/rofilaunch.sh`. Other Rofi things are not working. Also, the clock module is not working. Can you help?

**Comment by waqaswasil96** [comment]
> > > I don't know about locale. So, the above command opens Rofi, but when I close it and use the shortcut, it doesn't work. ![image](https://private-user-images.githubusercontent.com/108145762/301615672-d4333893-c623-4537-aae3-2b68a6c3764c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTI3NTMsIm5iZiI6MTcwNzI5MjQ1MywicGF0aCI6Ii8xMDgxNDU3NjIvMzAxNjE1NjcyLWQ0MzMzODkzLWM2MjMtNDUzNy1hYWUzLTJiNjhhNmMzNzY0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNzU0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjU4Y2M0MTYzYzI5MmEyZTMzZmE2OGZhYjQxMzI3YWRjZDYyMGUxMzEyZThiMDliNjdmYzcyOTNkNzAxODBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.boNSm1O25SXPoOnb_8XI-dp53jyphJQko4TtdEDOQ4E)
> > 
> > 
> > That's definitely a locale problem. The clock module is also not working on waybar. To solve, edit `/etc/locale.gen` and uncomment `en_US.UTF-8 UTF-8`. Generate the locales by running:
> > `sudo locale-gen`
> 
> It is already uncommented and the sudo locale-gen command has been run, but it did nothing. What I did was add this command in the Hyprland keybinds file: `bind =$mainMod , R ,exec, export LC_ALL=C && ~/.config/hypr/scripts/rofilaunch.sh`. Other Rofi things are not working. Also, the clock module is not working. Can you help?

Can you run `waybar` and `rofi` from terminal and post the output here?

**Comment by AzanAdnan23** [comment]
waybar:

(process:65716): Gtk-WARNING **: 21:02:47.789: Locale not supported by C library.
	Using the fallback 'C' locale.
[2024-02-09 21:02:47.879] [info] Using configuration file /home/Azan/.config/waybar/config.jsonc
[2024-02-09 21:02:47.880] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[2024-02-09 21:02:47.880] [info] Using CSS file /home/Azan/.config/waybar/style.css
[2024-02-09 21:02:47.897] [warning] module clock: Disabling module "clock", locale::facet::_S_create_c_locale name not valid
[2024-02-09 21:02:47.898] [warning] Mapping is not an object
[2024-02-09 21:02:47.898] [info] Hyprland IPC starting
/home/Azan/.config/hypr/scripts/gpuinfo.sh: line 4: nvidia-smi: command not found

** (waybar:65716): WARNING **: 21:02:48.075: Status Notifier Item with bus name ':1.553' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered
[2024-02-09 21:02:48.079] [warning] Requested height: 31 is less than the minimum height: 32 required by the modules
[2024-02-09 21:02:48.079] [info] Bar configured (width: 1280, height: 32) for output: eDP-1

** (waybar:65716): WARNING **: 21:02:48.132: Status Notifier Item with bus name ':1.553' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered
/home/Azan/.config/hypr/scripts/gpuinfo.sh: line 4: nvidia-smi: command not found
/home/Azan/.config/hypr/scripts/gpuinfo.sh: line 4: nvidia-smi: command not found



rofi:

─────────────────────────────────────────────────░▒▓ ✔  09:03:39 PM  ▓▒░
╰─ rofi                

(process:66755): Rofi-WARNING **: 21:03:44.579: Failed to set locale.

**Comment by waqaswasil96** [comment]
That confirms that its a locale problem. Have you added a locale like `LANG=en_US.UTF-8` to `/etc/locale.conf` ?

**Comment by waqaswasil96** [comment]
> waybar:
> 
> (process:65716): Gtk-WARNING **: 21:02:47.789: Locale not supported by C library. Using the fallback 'C' locale. [2024-02-09 21:02:47.879] [info] Using configuration file /home/Azan/.config/waybar/config.jsonc [2024-02-09 21:02:47.880] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop [2024-02-09 21:02:47.880] [info] Using CSS file /home/Azan/.config/waybar/style.css [2024-02-09 21:02:47.897] [warning] module clock: Disabling module "clock", locale::facet::_S_create_c_locale name not valid [2024-02-09 21:02:47.898] [warning] Mapping is not an object [2024-02-09 21:02:47.898] [info] Hyprland IPC starting /home/Azan/.config/hypr/scripts/gpuinfo.sh: line 4: nvidia-smi: command not found
> 
> ** (waybar:65716): WARNING **: 21:02:48.075: Status Notifier Item with bus name ':1.553' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered [2024-02-09 21:02:48.079] [warning] Requested height: 31 is less than the minimum height: 32 required by the modules [2024-02-09 21:02:48.079] [info] Bar configured (width: 1280, height: 32) for output: eDP-1
> 
> ** (waybar:65716): WARNING **: 21:02:48.132: Status Notifier Item with bus name ':1.553' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered /home/Azan/.config/hypr/scripts/gpuinfo.sh: line 4: nvidia-smi: command not found /home/Azan/.config/hypr/scripts/gpuinfo.sh: line 4: nvidia-smi: command not found
> 
> rofi:
> 
> ─────────────────────────────────────────────────░▒▓ ✔  09:03:39 PM  ▓▒░ ╰─ rofi
> 
> (process:66755): Rofi-WARNING **: 21:03:44.579: Failed to set locale.

That confirms that its a locale problem. Have you added a locale like `LANG=en_US.UTF-8` to `/etc/locale.conf` ?

**Comment by AzanAdnan23** [comment]
it is written as en_US.UTF-8. should u add LANG= ?

> > waybar:
> > (process:65716): Gtk-WARNING **: 21:02:47.789: Locale not supported by C library. Using the fallback 'C' locale. [2024-02-09 21:02:47.879] [info] Using configuration file /home/Azan/.config/waybar/config.jsonc [2024-02-09 21:02:47.880] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop [2024-02-09 21:02:47.880] [info] Using CSS file /home/Azan/.config/waybar/style.css [2024-02-09 21:02:47.897] [warning] module clock: Disabling module "clock", locale::facet::_S_create_c_locale name not valid [2024-02-09 21:02:47.898] [warning] Mapping is not an object [2024-02-09 21:02:47.898] [info] Hyprland IPC starting /home/Azan/.config/hypr/scripts/gpuinfo.sh: line 4: nvidia-smi: command not found
> > ** (waybar:65716): WARNING **: 21:02:48.075: Status Notifier Item with bus name ':1.553' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered [2024-02-09 21:02:48.079] [warning] Requested height: 31 is less than the minimum height: 32 required by the modules [2024-02-09 21:02:48.079] [info] Bar configured (width: 1280, height: 32) for output: eDP-1
> > ** (waybar:65716): WARNING **: 21:02:48.132: Status Notifier Item with bus name ':1.553' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered /home/Azan/.config/hypr/scripts/gpuinfo.sh: line 4: nvidia-smi: command not found /home/Azan/.config/hypr/scripts/gpuinfo.sh: line 4: nvidia-smi: command not found
> > rofi:
> > ─────────────────────────────────────────────────░▒▓ ✔  09:03:39 PM  ▓▒░ ╰─ rofi
> > (process:66755): Rofi-WARNING **: 21:03:44.579: Failed to set locale.
> 
> That confirms that its a locale problem. Have you added a locale like `LANG=en_US.UTF-8` to `/etc/locale.conf` ?

**Comment by waqaswasil96** [comment]
> > > waybar:
> > > (process:65716): Gtk-WARNING **: 21:02:47.789: Locale not supported by C library. Using the fallback 'C' locale. [2024-02-09 21:02:47.879] [info] Using configuration file /home/Azan/.config/waybar/config.jsonc [2024-02-09 21:02:47.880] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop [2024-02-09 21:02:47.880] [info] Using CSS file /home/Azan/.config/waybar/style.css [2024-02-09 21:02:47.897] [warning] module clock: Disabling module "clock", locale::facet::_S_create_c_locale name not valid [2024-02-09 21:02:47.898] [warning] Mapping is not an object [2024-02-09 21:02:47.898] [info] Hyprland IPC starting /home/Azan/.config/hypr/scripts/gpuinfo.sh: line 4: nvidia-smi: command not found
> > > ** (waybar:65716): WARNING **: 21:02:48.075: Status Notifier Item with bus name ':1.553' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered [2024-02-09 21:02:48.079] [warning] Requested height: 31 is less than the minimum height: 32 required by the modules [2024-02-09 21:02:48.079] [info] Bar configured (width: 1280, height: 32) for output: eDP-1
> > > ** (waybar:65716): WARNING **: 21:02:48.132: Status Notifier Item with bus name ':1.553' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered /home/Azan/.config/hypr/scripts/gpuinfo.sh: line 4: nvidia-smi: command not found /home/Azan/.config/hypr/scripts/gpuinfo.sh: line 4: nvidia-smi: command not found
> > > rofi:
> > > ─────────────────────────────────────────────────░▒▓ ✔  09:03:39 PM  ▓▒░ ╰─ rofi
> > > (process:66755): Rofi-WARNING **: 21:03:44.579: Failed to set locale.
> > 
> > 
> > That confirms that its a locale problem. Have you added a locale like `LANG=en_US.UTF-8` to `/etc/locale.conf` ?
> 
> it is written as en_US.UTF-8. should I add LANG= ?

Yes, as stated in the Arch install guide on the wiki.

**Comment by AzanAdnan23** [comment]
![Uploading 240209_21h18m16s_screenshot.png…]()

**Comment by waqaswasil96** [comment]
> ![240209_21h18m16s_screenshot](https://private-user-images.githubusercontent.com/108145762/303635043-31e5e0c1-e35d-48d7-a466-35f89f753092.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NzgwMTQsIm5iZiI6MTcwNzQ3NzcxNCwicGF0aCI6Ii8xMDgxNDU3NjIvMzAzNjM1MDQzLTMxZTVlMGMxLWUzNWQtNDhkNy1hNDY2LTM1Zjg5Zjc1MzA5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxMTIxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjk3ZGM5ZTcyMTBiNzQ1YzRlMzQ4YTA3YjAyNjhlMDExNjVkNzVlMTJiZWEwN2NiZGQ5M2IxZjI0NjliZTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aMD1z3ayGtZgAtqSPMNm73tdiwRdIrgF16bf8btMWK4)

I see a typo right there, change the UTTF to UTF. Also check your Instagram.
