### ISSUE TITLE
waybar hyprland error while installing

### ISSUE THREAD

**Issue by mur1chan** [prasanthrangan/hyprdots#82]
hey i'm getting this issue while installing the rice with your install script. i did already three times a clean install but it didn't worked
![image](https://github.com/prasanthrangan/hyprdots/assets/126001665/be552a6b-4c37-43be-9585-bca88665c323)

**Comment by TK-ed** [comment]
> hey i'm getting this issue while installing the rice with your install script. i did already three times a clean install but it didn't worked ![image](https://user-images.githubusercontent.com/126001665/261315412-be552a6b-4c37-43be-9585-bca88665c323.jpeg)

Just remove the waybar-hyprland-git from custom-hypr and install. Everything will install perfectly and wait until the package gets updated as its an upstream issue!! :)

**Comment by mur1chan** [comment]
> Hello, [this fix](https://github.com/Alexays/Waybar/issues/2415#issuecomment-1682442203) allowed me to install waybar without issues

That worked thank you! but how does it work with configuration? waybar is using currently the configfiles from local/etc/xdg/waybar/config

**Comment by prasanthrangan** [comment]
> That worked thank you! but how does it work with configuration? waybar is using currently the configfiles from local/etc/xdg/waybar/config

It might have skipped the waybar config files as waybar was not installed when you ran the install script, please try copying the waybar config files to your `~/.config`

**Comment by Lol-Lap** [comment]
Is This upstream issue got fixed because when I tried running the installer on another computer, it gave me the same error. If not, how to know? It got fixed.

**Comment by mur1chan** [comment]
> Is This upstream issue got fixed because when I tried running the installer on another computer, it gave me the same error. If not, how to know? It got fixed.

Sorry for the late response
you can fix it like that:
1. uninstall waybar if installed and buggy
2. `yay -S spdlog`
3. `yay -S waybar-hyprland-git`

if it's still doesn't work try a clean reinstall. sad but this is what i needed to do at the end.

if you consider to do a clean install then add into the custom_apps spdlog-git at the top. this is the whay which worked for me at the end.

**Comment by mark-sercombe** [comment]
I have the same issue, none of the fixes mentioned here helped, is there anything i can do?

**Comment by prasanthrangan** [comment]
Closing this, as this is a temporary issue with waybar-hyprland-git aur package.
