### ISSUE TITLE
[Bug]: Script exits at "Installing Extensions"

### ISSUE THREAD

**Issue by Manokii** [prasanthrangan/hyprdots#821]
### Description

fresh install get stuck to "Installing extensions" and then then the program exits. I had to rerun the `./install.sh` multiple times

### Steps to Reproduce

1. Fresh install arch (using archinstall with minimal profile)
2. clone this repo and follow installation steps
3. wait for it to until it says "Installing extensions..."

### Expected Behavior

It shouldn't get stuck nor exit the script

### Actual Behavior

It exits the script and it does not finish it

### Screenshots

<img width="1131" alt="image" src="https://github.com/prasanthrangan/hyprdots/assets/49423729/b0dfc160-6eee-4fd1-8fdf-3934dc821651">

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: **ArchLinux**
- Linux Version: **Linux archlinux 6.7.3-arch1-1 #1 SMP PREEMPT_DUNAMIC Thu, 01 Feb 2024 10:30:35 +0000 x86_64 GNU/Linux**
- Hyprland Version: 0.35.0
- Installation Environment: Hardware with ryzen 5 3600 + 7800xt
- Other info: Displays, 1x 1080p and 1x 4k

### Additional Information

might have something to do with extensions

**Comment by kRHYME7** [comment]
> It shouldn't get stuck nor exit the script

Maybe there is a problem with the extension or your internet connection. Can you test your net speed?

**Comment by Manokii** [comment]
Yep it might've been my connection at the time! it is solved now, closing this issue~!
