### ISSUE TITLE
[Bug]:   Can't  remove anime pictures from 

### ISSUE THREAD

**Issue by Radrahil** [prasanthrangan/hyprdots#825]
Adding 
```
force_default_wallpaper =  0   
disable_hyprland_logo = true
disable_splash_rendering = true 

``` 
doesn't seem to be doing anything. I want to remove the anime pictures from neofetch.

**Expected Behavior**

No anime pictures in neofetch

**Actual Behavior**

No change

**Steps to Reproduce**

add 
```
force_default_wallpaper =  0   
disable_hyprland_logo = true
disable_splash_rendering = true 

``` 
to misc in hyprland.conf

**Comment by Radrahil** [comment]
How do I get it it to use the gifs?

**Comment by kRHYME7** [comment]
I guess add .gif to the ./gifs folder and I think neofetch will fetch random files inside ./gifs and ./pngs
