### ISSUE TITLE
[Bug]:  hyprland config problem

### ISSUE THREAD

**Issue by legendboyAni** [prasanthrangan/hyprdots#829]
Hey so where is the other hyprland configs i mean
In default config there is no lines for gaps, roundness and other even i tried to type those in hear but they doesn't work so i guess they are somewhare else where they are can you guys pls tell me.

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/discussions/new/choose

 sourced at the bottom of the hyprland.conf

**Comment by legendboyAni** [comment]
> https://github.com/prasanthrangan/hyprdots/discussions/new/choose
> 
> sourced at the bottom of the hyprland.conf

Hey so if i put

general {
   gaps_in = 1
   gaps_out = 2
}

In userprefs.conf it will change it or do i have to do somthing else?

**Comment by kRHYME7** [comment]
It will change it overriding the configuration before the ./userprefs. 

BTW we have a discussion panel for questions about Hyprdots. https://github.com/prasanthrangan/hyprdots/discussions/categories/q-a
 also at least scanning the wiki might help. https://wiki.hyprland.org/Configuring/Configuring-Hyprland/
