### ISSUE TITLE
About the operation of the program

### ISSUE THREAD

**Issue by 2420228300** [prasanthrangan/hyprdots#83]
您好，我使用了最新的脚本搭建的系统但是我无法运行一些软件，例如Gparted...他们的报错如下`Authorization required, but no authorization protocol specified (gpartedbin:84261): Gtk-WARNING **: 23:44:34.329: cannot open display: :1`，但是在上一个脚本中是可以运行的，，然后就是obs-studio依旧无法录屏

**Comment by prasanthrangan** [comment]
Hi, sorry I don't understand this, can you please post this in English?

**Comment by 2420228300** [comment]
Hello, I use the latest script to build the system but I can't run some software, such as Gparted... Their error is as follows`Authorization required, but no authorization protocol specified (gpartedbin:84261): Gtk-WARNING **: 23:44:34.329: cannot open display: :1`
But in the previous script it can be run, and then obs-studio still can't record the screen

**Comment by prasanthrangan** [comment]
Looks like an issue with the user, your user should have sudo privileges, and also make sure `polkit-kde-agent` is running.

> obs-studio still can't record the screen

are you using nvidia system? please refer [this](https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580) to troubleshoot.

**Comment by 2420228300** [comment]
I have successfully run polkit-kde-agent, when I open this kind of program that requires authentication, I enter the password, and then nothing responds and the program does not open

**Comment by prasanthrangan** [comment]
can you try this -
```
sudo -E gparted
```

**Comment by 2420228300** [comment]
My God, thank you very much, super thankful
