### ISSUE TITLE
[Bug]: Qt6 based apps are not themed.

### ISSUE THREAD

**Issue by TitanHZZ** [prasanthrangan/hyprdots#830]
### Description

Install a Qt6 app like wireshark-qt (i haven't tested other apps), and you will see the app has no theme applied.

### Environment

- Linux Distro: [e.g., ArchLinux]
- Linux Version, output of `uname -a`: Linux laptop-arch 6.7.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 01 Feb 2024 10:30:35 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0
flags: (if any)
- Installation Environment: Dual boot with windows 11 on the main hardware

### Additional Information

I installed qt6ct but no custom color scheme was available like it is in qt5ct.
I am assuming that only qt5 apps are themed as qt6ct is not listed in the packages installed with Hyprdots.

**Comment by prasanthrangan** [comment]
Hey, please install `qt6ct` and apply the kvantum style manually for now.
In the meantime I'll integrate it with the theme script.
