### ISSUE TITLE
[Bug]: 'abbr' command not found by zsh on fresh install

### ISSUE THREAD

**Issue by danielaird27** [prasanthrangan/hyprdots#831]
### Description

zsh-abbr is not installed when performing a fresh install of arch and fresh install of hyprdots. Therefore, the abbreviations added to the .zshrc cause the following error upon opening new terminal windows:
"zsh: command not found: abbr"

### Steps to Reproduce

1. Fresh install arch linux
2. Fresh install hyprdots with zsh as your terminal
3. Open a new terminal and observe the abbr error

**Comment by Zardexd** [comment]
Just installed, have this issue as well.

**Comment by danielaird27** [comment]
For a quick workaround, you could simply comment out the abbr abbreviations declared in ~/.zshrc

**Comment by danielaird27** [comment]
I successfully downloaded zsh-abbr by running `yay -Sy` then `yay -S zsh-abbr`. If that doesn't work, you'll just need to import the keys by running `curl https://github.com/olets.gpg | gpg --import` then running the first two commands.

**Comment by Lol-Lap** [comment]
> I successfully downloaded zsh-abbr by running `yay -Sy` then `yay -S zsh-abbr`. If that doesn't work, you'll just need to import the keys by running `curl https://github.com/olets.gpg | gpg --import` then running the first two commands.

That didn't work for me. Is there any update on this issue?

**Comment by ntdsrd** [comment]
> > I successfully downloaded zsh-abbr by running `yay -Sy` then `yay -S zsh-abbr`. If that doesn't work, you'll just need to import the keys by running `curl https://github.com/olets.gpg | gpg --import` then running the first two commands.
> 
> That didn't work for me. Is there any update on this issue?

Run `vim .zshrc` and comment all lines have abbr (maybe have 6 lines) and run `source .zshrc` and restart terminal. This works for me

**Comment by Skerse** [comment]
Looks like this commit: https://github.com/prasanthrangan/hyprdots/commit/41ebe845637ab1af0c925c80675f5b8be4608747 caused that, likely because the person making the commit had the package installed and forgot to add the package to the package installation list. Will look into it then submit a pull request to fix it.

**Comment by prasanthrangan** [comment]
hey, sorry my bad, i'll update it. It was for fish.
