### ISSUE TITLE
[Bug]: Cursor does not change when hovered on buttons/textfield

### ISSUE THREAD

**Issue by ChirayuGupta2003** [prasanthrangan/hyprdots#834]
### Description

When I click on the waybar or any other window, sometimes the cursor stays in the same arrow shape and does not change to pointer/I-beam. The temporary fix is to hover the cursor on a different window and its back to normal behaviour, but I would like a more permanent solution.

### Steps to Reproduce

1. Click on the waybar a few times
2. Hover back on a window and it stays the arrow shape

### Expected Behavior

Cursor changing shapes when hovered on different components on a window

### Actual Behavior

Cursor stays in the same arrow shape

**Comment by TitanHZZ** [comment]
I have actually experienced this too. You don't even need to click multiple times in waybar, it happens "naturally".

**Comment by forlornlamp** [comment]
First thing I noticed after a fresh install on real hardware, minimal arch. Hovering over waybar seems to reset the cursor to the default pointer, but it gets stuck as a I-beam as soon as I hover over a text input field. I haven't seen the hand cursor yet.
What consistently works are the resize markers, if I hover over a window edge they all work as expected for all directions.

**Comment by ChirayuGupta2003** [comment]
No solution still. I reinstalled minimal arch but the issue still persists. Maybe its a hyprland problem and not a Hyprdots problem

**Comment by kRHYME7** [comment]
@ChirayuGupta2003  You got it! it's hyprland problem.  

Tip when this happens, faster way is to  launch rofi so that the cursor will follow rofi menu and it will be back

**Comment by kRHYME7** [comment]
@forlornlamp  This is pretty common on hyprland especially if a window is running on Xwayland. In case your using a different scaling like 2 you can modify the 


For invisble cursor problems with nvidia
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/7972435f-b663-46d8-b7e4-3e6399843ca0)


How to modify in case cursor is out of scale:
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/072c0858-2c28-4e2e-acf6-4c16ef1e52aa)

**Comment by kRHYME7** [comment]
Yow, Maybe you're interested to try https://github.com/hyprwm/hyprcursor.

**Comment by shyce** [comment]
This happens if wezterm or kitty are visible in any current workspace and hover of them. The cursor is now stuck as an I-Beam

**Comment by kRHYME7** [comment]
We can't expect much about having a consistent cursor. I'm looking forward to the implementation and adaption of hyprcursor
 ( 
Imagine a world where we got a unified cursor size/shape/type 😇
)
For now, IIRC applications can just render their cursor, hashtag#framentation (useful only for games IMO). 

👀 High hopes to this  https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/

**Comment by abenezerw** [comment]
Could you close as solved if you no longer have this issue. Thank you @ChirayuGupta2003
