### ISSUE TITLE
[Bug]: fullscreen mode does not work in special workspace

### ISSUE THREAD

**Issue by katanayka** [prasanthrangan/hyprdots#835]
I don’t know if it should be like this, but I like to put a browser in this workspace and sometimes watch videos, but because of this bug I can’t put them in fullscreen

**Comment by prasanthrangan** [comment]
Hi, This does not seem like a bug related to this config. Please try with the default autogenerated hyprland.conf file to check if it helps.
Also not sure if special workspace supports fullscreen, please check in hyprland wiki or in hyprland repo.
