### ISSUE TITLE
[Bug]: Glitchy Screen When Launching Game Through Steam (Proton)

### ISSUE THREAD

**Issue by ShinsuSenju** [prasanthrangan/hyprdots#838]
### Description
I have a Ryzen 5 5600h cpu paired with radeon 5500m gpu.
Everytime i open any game from steam i'm getting this glitchy screen.
There was no issue on plasma kde

### Screenshots
![240207_21h14m47s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/63202411/70318b79-91ab-41a4-9ed0-c1e29572b910)

- Linux Distro: Manjaro Kde

**Comment by prasanthrangan** [comment]
Hi, is there any gpu related env variables sourced in hyprland.conf?
can you please try with the default autogenrated hyprland.conf file to make sure its not the config that's causing it.
It might be your gpu driver or hyprland that's causing it.
