### ISSUE TITLE
No fullscreen resolution for Hypervisors

### ISSUE THREAD

**Issue by HIXETA** [prasanthrangan/hyprdots#842]
Bit scared to dual-boot.. so, VMs are a go to for me. Fell in love with your Hyprdots scripts. Installed it, doesn't work on Endeavour OS at all if I select Candy, meanwhile, selecting Corners does allow me to login but max screen resolution is only 640×400 ![20240208_164734.jpg](https://github.com/prasanthrangan/hyprdots/assets/101002827/a0317304-a273-46fc-9382-edc36710f13b)

![20240208_165948.jpg](https://github.com/prasanthrangan/hyprdots/assets/101002827/7e71da21-dcb1-47dd-b7da-4db8b8d10590)

Won't try it on bare metal until I get another machine to play around with.. don't want to lose the one I have. I hope in future there will be a fix for this, will look forward to it. And there is this guy who goes by Ja.KooLit.. his hyprdot scripts does work on virtual machines with full resolution, upto 1440p tbh. 

Love your work, will wait for new version.. Hopefully will get another machine to try it out on bare metal.

**Comment by kRHYME7** [comment]
Hello what are Candy  and Corners?

**Comment by RookiexCookie** [comment]
@kRHYME7 i think they meant the sddm theme
i saw the owner added the choice to download either candy or corners theme

**Comment by RookiexCookie** [comment]
@HIXETA I dont know a whole lot but im using this dots on dual boot with endeavour os , 
 you can change the resolution of hyprland here `~/.config/hypr/hyprland.conf`, here is mine 
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/18fdfce5-acfc-42f5-a732-528d7dcbe5d0)
you can read the wiki on how to configure using the hyprland wiki https://wiki.hyprland.org/Configuring/Monitors/

**Comment by HIXETA** [comment]
Tried, it didn't work. Maybe because i am using it within VMware instead of baremetal.. using it on baremetal compromises on the secure boot option on BIOS with Endeavour OS, leaves a backdoor open for anyone who could access my device physically.. so, at this point I am not using it since I just have one machine.

**Comment by HIXETA** [comment]
Tried. xrandr allows a max of 640×400 only in VM.. I tried editing the monitor.conf file to set it to 1980x1080 but it didn't work.

**Comment by HIXETA** [comment]
Did, didn't work, then I dual Booted in my laptop today ![20240216_222707.jpg](https://github.com/prasanthrangan/hyprdots/assets/101002827/1f8b5013-5c5c-44e0-90ab-a042229ee25e)

**Comment by hchasens** [comment]
You might want to check your virt drivers.
https://wiki.archlinux.org/title/VMware/Install_Arch_Linux_as_a_guest
https://wiki.archlinux.org/title/VirtualBox/Install_Arch_Linux_as_a_guest#Load_the_VirtualBox_kernel_modules

**Comment by HIXETA** [comment]
I installed it on the bare metal using dual boot.. yet, the same results, I tried changing the monitors.config hyprland.config too taking help of the Hyprland wiki.. yet, whenever I ran xrandr -q this was the result. Everything works fine but due to resolution issue i cant get games working at all .. other apps have the same issue too. ![20240216_222707.jpg](https://github.com/prasanthrangan/hyprdots/assets/101002827/8b3a5904-4942-427b-ac74-a266ac081792)

**Comment by kRHYME7** [comment]
can you run ```wlr-randr  ``` I don't really understand why using xrandr? 

Example how inaccurate it is on wayland. 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/f63b1a15-e961-4b4c-aef1-6cefe4903165)
