### ISSUE TITLE
[Bug]: Steam library doesn't open

### ISSUE THREAD

**Issue by enzzodani** [prasanthrangan/hyprdots#843]
### Description

![240208_15h28m33s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/135847182/4ce9972f-f25c-4c3a-aef2-353ab3759327)
 (Sorry for the bad english)

I've trying open the game laucher with the command '''gamelaucher.sh 1''', but it's still not working, What should I do now?

### Expected Behavior

Open the game laucher with my games in the steam folder

### Actual Behavior
Steam library doesn't found

### Environment

![240208_15h33m03s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/135847182/03f567de-f701-4bff-a133-960c998995f5)
e.g.,

### Additional Information

I was searching in the past issues, but none of them could help me.
Sorry for the trouble

**Comment by kRHYME7** [comment]
Based on that script it looks like checking first if these directories are present. Have you check if these are on that directory ?
```
SteamLib="${XDG_DATA_HOME:-$HOME/.local/share}/Steam/config/libraryfolders.vdf"
SteamThumb="${XDG_DATA_HOME:-$HOME/.local/share}/Steam/appcache/librarycache"
```

**Comment by enzzodani** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/135847182/50097eb9-56d4-41a6-9ac2-b4648bfbaef2)

Looks like this directorys are indeed presents in my machine.

**Comment by prasanthrangan** [comment]
Hi @enzzodani , seems like you have installed `flatpak` version as the library path seen here is `.var/app/`.
But the script only supports `.local/share/` path for now, so this is expected.
As a workaround for now, please try updating the `SteamLib` and `SteamThumb` vars with the correct path.

**Comment by enzzodani** [comment]
> Hi @enzzodani , seems like you have installed `flatpak` version as the library path seen here is `.var/app/`.
> But the script only supports `.local/share/` path for now, so this is expected.
> As a workaround for now, please try updating the `SteamLib` and `SteamThumb` vars with the correct path.

Alright, thanks for the help
