### ISSUE TITLE
[Bug]: Switch Between Desktop applications no longer working

### ISSUE THREAD

**Issue by Radrahil** [prasanthrangan/hyprdots#848]
### Description

Pressing win tab to launch the rofi menu for that works, but the menu itself doesn't do anything.

**Comment by kRHYME7** [comment]
can you test if rofi will be able to switch  
On terminal : ``` rofi -show window    ```
see if you see some error or something. Maybe Rofi's upstream bug.

BTW got this issue also

**Comment by Radrahil** [comment]
nope doesn't work

**Comment by prasanthrangan** [comment]
Hey, it does not seem like an issue related to this config.
I just tried it with default rofi config and it still does not work, so please check upstream.

**Comment by Radrahil** [comment]
```
❯ paru -S rofi
resolving dependencies...
looking for conflicting packages...
:: rofi and rofi-lbonn-wayland-git are in conflict. Remove rofi-lbonn-wayland-git? [y/N] n
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: rofi and rofi-lbonn-wayland-git are in conflict
```
Is this a problem?

**Comment by pragit-raj-sharma** [comment]
It is still not working can confirm that.

**Comment by kRHYME7** [comment]
I personally used the hycov plugin... We should check the Upstream rofi wayland to see if this is being fixed or reported.

**Comment by kRHYME7** [comment]
@Radrahil  https://github.com/hyprwm/Hyprland/issues/4829 

It now works on my end. I'll close this as unrelated and this is now resolved.

**Comment by MostlyKIGuess** [comment]
- Even after following those issues, it doesn't seem to be fixed, can we reopen this?

**Comment by kRHYME7** [comment]
It is suitable to reopen on the upstream rofi, we can't actually do something on this Repo.

**Comment by kRHYME7** [comment]
@MostlyKIGuess  Can you try to downgrade first rofi ?

**Comment by MostlyKIGuess** [comment]
> @MostlyKIGuess Can you try to downgrade rofi first ?
> 
> Output for ` rofi -v` ?
> 
> Latest git version still works on my end...
```
❯ rofi -v
Version: 1.7.5+wayland2-167-gb88dddd1 (makepkg)
```

**Comment by kRHYME7** [comment]
Latest version is ``` Version: 1.7.5+wayland3-3-g47ae31eb (makepkg) ``` 

```
❯ paru -Qs rofi-lbonn-wayland-git
local/rofi-lbonn-wayland-git 1.7.5.wayland3.r3.g47ae31eb-1
    A window switcher, application launcher and dmenu replacement (fork with Wayland support)
```

Output for ``` yay -Qs rofi ``` ?

**Comment by MostlyKIGuess** [comment]
yeah up streaming it fixed the issue, thanks a lot!

- Apparently it was because of the debug file file was of "rofi" and not rofi wayland in my usr lib directory.
- So the correct way to fix the issue would be to remove that file, uninstall rofi, and then installing rofi+wayland from:
https://aur.archlinux.org/packages/rofi-lbonn-wayland
