### ISSUE TITLE
[QUESTION]: Global Theme from a Wallpaper

### ISSUE THREAD

**Issue by itsmenewbie03** [prasanthrangan/hyprdots#850]
### Description

Currently you can cycle from different wallpapers and they apply globally(is this the right term? xD). Is there a way to reproduce this behavior by specifying file to set as wallpaper and also make it persist?
Something like this would be good
```bash
./whatever wallpaper.png
```
And voila wallpaper set, way bar colors updated, and etc.

**Comment by kRHYME7** [comment]
``` Hyprdots wallpaper set ``` this command just redirects you to use ``` ~/.config/hypr/scripts/swwwallpaper.sh s ```

**Comment by itsmenewbie03** [comment]
> `Hyprdots wallpaper set` this command just redirects you to use `~/.config/hypr/scripts/swwwallpaper.sh s`

how to invoke that command? the doesn't seem to be globally accessible

**Comment by kRHYME7** [comment]
sorry I don't understand what do you mean by globally?

**Comment by itsmenewbie03** [comment]
> sorry I don't understand what do you mean by globally? also persist upon?
> 
> do you mean like getting the color palette of the wallpaper?

By globally I mean I could invoke the command regardless of the current directory I am.
for example I am currently in `~/Downloads/` it would be nice if I could just use `setwallpaper my_wallpaper.png` setwallpaper could be of course on any name the is suitable. 
With pesist, I mean it would still be the theme even after reboot.

**Comment by itsmenewbie03** [comment]
# Note
I was able to make this work by moving the wallpaper file along with the wallpapers of the theme and rebooting my laptop.

**Comment by kRHYME7** [comment]
Thanks for clarifying, you mean a global command right? 

``` Hyprdot wallpaper set ``` commands should work systemwide and set a wallpaper at the current directory, added this feature recently so maybe updating hyprdots-ctl is needed. 

https://github.com/kRHYME7/Hyprdots-ctl

**Comment by kRHYME7** [comment]
> ~/Downloads/ it would be nice if I could just use setwallpaper my_wallpaper.png setwallpaper could be of course on any name the is suitable.
With pesist, I mean it would still be the theme even after reboot.

@itsmenewbie03  if you will do this, the ``` ~/Downloads ``` becomes the current directory for that current theme.  now if you cycle wallpapers using key binds it will find images inside  ``` ~/Downloads ```

**Comment by kRHYME7** [comment]
Please try the latest changes it should work this way 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/b6c1256c-8a37-4bb2-b8ea-98dfb753d742)

` wallAddCustomPath=( "" "")` inside ` ~/.config/hyde/hyde.conf `

**Comment by itsmenewbie03** [comment]
Yep it works now, tried this right after I asked at discord.
also I forgot about this issue I opened xD
![image](https://github.com/prasanthrangan/hyprdots/assets/89230263/c36ac06a-2fb8-410e-826f-68faba144636)
