### ISSUE TITLE
[Bug]: Display & Sound Issue 

### ISSUE THREAD

**Issue by t101804** [prasanthrangan/hyprdots#851]
### Description

[Provide a clear and concise description of the bug.]

### Steps to Reproduce

https://github.com/prasanthrangan/hyprdots/assets/113588203/e210e600-254e-436b-a098-eb8c06324085

### Expected Behavior

[What did you expect to happen?]
Normal vidio and audioo
### Actual Behavior

[What actually happened?]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: Arch
- Linux Version, output of `uname -a`: 
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by t101804** [comment]
Maybe its nvidia bug but idk

**Comment by kRHYME7** [comment]
tried  modifying ENVs as stated in the hyprland wiki ?

**Comment by t101804** [comment]
> tried  modifying ENVs as stated in the hyprland wiki ? 

modify to what?

**Comment by kRHYME7** [comment]
Oh, my bad. I think no env related to this.

http://wiki.hyprland.org/Nvidia/#fixing-random-flickering-nuclear-method
 What is your driver version? 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/2bd107ab-b3a1-4889-ba29-21c203f46ec8)

**Comment by t101804** [comment]
> Oh, my bad. I think no env related to this.
> 
> http://wiki.hyprland.org/Nvidia/#fixing-random-flickering-nuclear-method
>  What is your driver version? 
> 
> ![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/2bd107ab-b3a1-4889-ba29-21c203f46ec8)
> 

nvidia 3060 , i already instaalled correct nvidia driver yay -S nvidia

**Comment by kRHYME7** [comment]
![Screenshot_2024-02-11-02-32-53-406_com.brave.browser-edit.jpg](https://github.com/prasanthrangan/hyprdots/assets/53417443/1be74bad-9944-46b4-82f5-89daa8b75585)

Is your correct nvidia driver version 535? or 545,?

**Comment by prasanthrangan** [comment]
Hey @t101804 , I had heavy stuttering (but not flashing as seen in your recording) with the 545 driver, and downgrading the drivers to 535.113.01 fixed it for me, so please try it -

```
yay -S downgrade
downgrade nvidia-dkms nvidia-utils lib32-nvidia-utils 
```

**Comment by t101804** [comment]
> Hey @t101804 , I had heavy stuttering (but not flashing as seen in your recording) with the 545 driver, and downgrading the drivers to 535.113.01 fixed it for me, so please try it -
> 
> ```
> yay -S downgrade
> downgrade nvidia-dkms nvidia-utils lib32-nvidia-utils 
> ```

should i change to nvidia-dkms? my graphic cards are nvidia rtx 3060

**Comment by t101804** [comment]
https://github.com/prasanthrangan/hyprdots/assets/113588203/b1736008-b37a-484f-b5fd-5cf887593ea2
It seems working but the audio still broken

**Comment by kRHYME7** [comment]
> nvidia rtx 3060

I think the recommended driver version for this is 535.  See archwiki or this https://www.nvidia.com/download/index.aspx#

I've read somewhere that the stuttering will be fixed on around version 550. But this is not yet release.(Beta version of 550 did not fix too) So maybe version 535 is okay

**Comment by kRHYME7** [comment]
> It seems working but the audio still broken

 I think it is echoing, or somthing Can you check using pavucontrol to see the outputs? 

clicking the volume icon in thewaybar will launch it or using the application launcher

**Comment by t101804** [comment]
> > It seems working but the audio still broken
> 
> I think it is echoing, or somthing Can you check using pavucontrol to see the outputs?
> 
> clicking the volume icon in thewaybar will launch it or using the application launcher

yes i can launch pavucontrol i already adjust volume and etc but still same

**Comment by t101804** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/113588203/58231dee-af2b-42ed-96fc-14f5365f263f)
the app didnt show in the playback

**Comment by kRHYME7** [comment]
do all music from spotify or browsers exibits this ?

**Comment by t101804** [comment]
> do all music from spotify or browsers exibits this ?

nope even if i close all browser its still echoing

**Comment by kRHYME7** [comment]
When you play spotify the sound also have problems? or the sound issue is specific to minecraft. 
Also can you change your outputs?  or test some configuration profiles maybe play around some configs profile. 

Here's my pavucontrol  with minecraft running 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/85499e63-1426-4503-b2ea-7c82d5012d4a)

I might not be able to help further with this as I am mainly using a laptop and I don't have a way to replicate this.

**Comment by t101804** [comment]
> When you play spotify the sound also have problems? or the sound issue is specific to minecraft. Also can you change your outputs? or test some configuration profiles maybe play around some configs profile.
> 
> Here's my pavucontrol with minecraft running ![image](https://private-user-images.githubusercontent.com/53417443/303930299-85499e63-1426-4503-b2ea-7c82d5012d4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2Njc1NzcsIm5iZiI6MTcwNzY2NzI3NywicGF0aCI6Ii81MzQxNzQ0My8zMDM5MzAyOTktODU0OTllNjMtMTQyNi00NTAzLWIyZWEtN2M4MmQ1MDEyZDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE2MDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYmQ0OTFmYmEwY2Q5YmE1YTkxZjNlYThiMWRkYjc4ZGRhNWMwYzY1N2Y3ZWYzY2VjY2NiNjA3YjkwZWIxYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RCC4nyDSnGLA_Nd4dIPYrceQWxMZWfZGTUctz6GdGJ8)
> 
> I might not be able to help further with this as I am mainly using a laptop and I don't have a way to replicate this.

in mine didnt have java in playback :(

**Comment by t101804** [comment]
Fix it after restart. Dont forget to downgrade ur nvida driver

**Comment by HoangLe734** [comment]
hey guys, do you know why when I use hyprdots, my audio as default for laptop cannot be used, like they are being turned off, I can only hear sounds when I use headphones or via bluetooth
