### ISSUE TITLE
[Bug]: Firefox 60hz in non-fullscreen & 120hz in fullsceen

### ISSUE THREAD

**Issue by Reon-1** [prasanthrangan/hyprdots#854]
### Description
Firefox runs at 60Hz in non-fullscreen/normal mode but operates at 120Hz in fullscreen mode.

### Steps to Reproduce

1. Launch Firefox
2. Open any webpage
3. Observe refresh rate behavior in both non-fullscreen and fullscreen modes.

### Expected Behavior

Firefox should consistently utilize the display's maximum refresh rate, regardless of fullscreen status.

### Actual Behavior

In non-fullscreen mode, Firefox operates at 60Hz, while in fullscreen mode, it operates at 120Hz.

### Screenshots

![240210_19h48m45s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/85833207/4b826787-9f39-407f-80e4-58d3aad60339)
![240210_19h49m59s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/85833207/d5ee72ce-cf1b-49d2-8d86-bb8344724267)

### Environment
- Linux Distro: [ ArchLinux]
- Linux Version, output of `uname -a`:  6.7.4-arch1-1
- Hyprland Version, output of `hyprctl version`:Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0
- Installation Environment: On The Main Hardware
- Other info: 1920x1080@120hz

### Additional Information

[Everything is a fresh install, just goggled and changed the layout.frame_rate and set it to 120]

**Comment by kRHYME7** [comment]
Hi, what is the output for ``` hyprctl getoption misc:vrr    ```

**Comment by Reon-1** [comment]
Hey, yes i used that setting as well as tried manually setting also like  ,1920x1080@120,0x0,1 (all work great except for firefox)

maybe it;s the nvidia drivers (545.29.06)
 
I mean it's not an issues 60hz is good to go for the most part, but just the feeling is diff, coming from a 120hz i can see it so slow and all.

hyprctl getoption misc:vrr -j | jq '.int' 
-> 0

tried both 0 and 1 in VRR didn't work

Brave works fine after enabling Wayland support. It just take a lot longer to load due to the kwallet5 or like that, so i tried to use Firefox.

Thank you for the response.

**Comment by kRHYME7** [comment]
Oh I see. Should the reason be being an Xwayland window?

**Comment by Reon-1** [comment]
idk about that one, maybe but all other works fine, I would've used brave but idk why it takes more than a min to launch but it launches instantly when i run it from terminal brave --disable-gpu.
Guess i'll just stick with firefox as it it, i will be getting a new monitor so, hope it works on the external one.

**Comment by kRHYME7** [comment]
about the password thing. 

``` brave --password-store=basic ``` so this is a CLI dunno how to set it in the GUI. For now, what I've done is edit the .desktop of brave and add --password-store=basic flag. But this won't persist as updating will change it. Dunno yet if making a ./.local/share/application for brave will be fine and  a good practice

**Comment by prasanthrangan** [comment]
Hey @Reon-1, I'm unable to replicate this issue, firefox just works fine for me -

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/7ce61a02-fd8e-4e02-993f-507ba13daba3)

So please check `hyprctl monitors` and confirm that hyprland detects the correct refresh rate and vrr.
Also check if MOZ_ENABLE_WAYLAND,1 if enabled in hyprland.conf and make sure it runs in native wayland mode `hyprctl clients`  should show `xwayland: 0` for firefox window.
```
Window 584456c86d10 -> [Bug]: Firefox 60hz in non-fullscreen & 120hz in fullsceen · Issue #854 · prasanthrangan/hyprdots — Mozilla Firefox:
	mapped: 1
	hidden: 0
	at: 10,10
	size: 1477,1032
	workspace: 1 (1)
	floating: 0
	monitor: 0
	class: firefox
	title: [Bug]: Firefox 60hz in non-fullscreen & 120hz in fullsceen · Issue #854 · prasanthrangan/hyprdots — Mozilla Firefox
	initialClass: firefox
	initialTitle: Mozilla Firefox
	pid: 1056
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 1
```

**Comment by Reon-1** [comment]
Thank you for the reply.
it's all correct, guess it's my nvidia 1070, it was working fine few months back so maybe i did something to mess it up. guess i'll re install after few updates.

**Comment by Reon-1** [comment]
> about the password thing.
> 
> `brave --password-store=basic` so this is a CLI dunno how to set it in the GUI. For now, what I've done is edit the .desktop of brave and add --password-store=basic flag. But this won't persist as updating will change it.
> 
> ~Dunno yet if making a ./.local/share/application for brave will be fine and a good practice~
> 
> so what I did was add another .desktop entry `~/.local/share/applications/brave-basic-password.desktop` with this you can launch this with cli flags
> 
> ```
> [Desktop Entry]
> Name=Brave-Browser
> GenericName=Web Browser
> Exec=/usr/bin/brave --password-store=basic %U
> StartupWMClass=Brave-browser
> Icon=brave-browser
> Terminal=false
> Type=Application
> Categories=Network;WebBrowser;
> ```
> 
> Now with this, I will have 2 desktop applications available
> 
> ![image](https://private-user-images.githubusercontent.com/53417443/303900255-d24becd2-8714-4fd2-91b5-037c6fe6777d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NDAxNzUsIm5iZiI6MTcwNzYzOTg3NSwicGF0aCI6Ii81MzQxNzQ0My8zMDM5MDAyNTUtZDI0YmVjZDItODcxNC00ZmQyLTkxYjUtMDM3YzZmZTY3NzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDA4MjQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNzEyMTVkYzE4MzYwN2JiNWQ5ZGUzOTRlY2YzNTllMzBjZmMyNjYyMTljZGY5NjBlNDQ0ZGQ4NTcxYTJhMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qM9SraiHp5sTjsI-HFUYBhE0iD9LKx6NG38BznoUZb8)
I'll try to do that, thank you!!

**Comment by Reon-1** [comment]
Hello, I noticed that even though i set the vrr to 1 on the .conf, hyprctl monitors show it as 0, is it working correctly or should it show 1? 
![image](https://github.com/prasanthrangan/hyprdots/assets/85833207/3d884599-43a6-4d54-aebd-dd4647e29246)

**Comment by kRHYME7** [comment]
> Hello, I noticed that even though i set the vrr to 1 on the .conf, hyprctl monitors show it as 0, is it working correctly or should it show 1?


``` hyprctl getoption misc:vrr -j | jq '.int'   ``` or ```  hyprctl getoption misc:vrr     ```  this command should be  enough to see if hyprland configuration has vrr set to true/false

I think vrr can be activated if available?
 Is vrr supported for your monitor?

**Comment by Reon-1** [comment]
Hey, I just fresh installed, and added my new monitor aswell, so for now it works on both monitors, it doesnt get to 120hz but it is atleast not locked at 60, so it's working well on both since my other monitor is 75.  Thank you for the support!!
