### ISSUE TITLE
[Bug]: the "switch mode" button isn't working ; Wallpaper won't display upon selection

### ISSUE THREAD

**Issue by rubairakib** [prasanthrangan/hyprdots#855]
## Bug Report

cant change theme and im stuck on a single wallpaper

### Steps to Reproduce
it probably happened after i tried some keybindings like "wallpaper select menue" or "theme select menue", wallpapers dont load on floating screen after executing the keybinding.

### Expected Behavior

want to change the theme like it was yesterday

### Actual Behavior

new to it, probably screwed it up while testing some keybinds.

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux archlinux 6.6.16-1-lts #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 21:20:21 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`:  v0.35.0
- Installation Environment: On The Main Hardware
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by kRHYME7** [comment]
what will happen if you run ``` Hyprdots theme select ``` on terminal?

**Comment by rubairakib** [comment]
![240211_20h53m09s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/149327362/eaf7ed19-2600-4bf3-a492-1ea6557bf90e)
it shows this

**Comment by rubairakib** [comment]
![240211_20h59m09s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/149327362/a791d59c-bafd-41ba-abae-8ec7bf1b33e2)
and this is what i get after pressing super+alt+w. I get something similiar for the theme too

**Comment by kRHYME7** [comment]
I think you have a Similar case with someone. what is the output for ``` cat ~/.config/hypr/theme.ctl ```

**Comment by rubairakib** [comment]
thanks man, you're a lifesaver!

**Comment by kRHYME7** [comment]
Should we close this now? I can say that this is really a bug as having this issue reported 2 times already. Can you describe more why might this happened to you? like maybe doing something unexpected?

**Comment by kRHYME7** [comment]
BTW you can  test active keybinds with this ``` Hyprdots show binds ```

**Comment by rubairakib** [comment]
idk just wanted to try some key binding, tried to switch theme and wallpaper exactly, then the screen seemed lagging so i reboot it. After rebooting im stuck with one wallpaper, couldn't even change themes. 

> Should we close this now? I can say that this is really a bug as having this issue reported 2 times already. Can you describe more why might this happened to you? like you did something unexpected?
> 
> > it probably happened after i tried some keybindings like "wallpaper select menue" or "theme select menue", wallpapers dont load on floating screen after executing the keybinding.
> 
> Can you elaborate more?

**Comment by kRHYME7** [comment]
Thanks for the info. This is a very rare incident. Your theme.ctl file does not exist or just empty?

**Comment by rubairakib** [comment]
it was empty.

**Comment by kRHYME7** [comment]
I replicated it by changing theme/wallpaper rapidly. Now all some of the configs like theme.ctl are empty.  I can conclude that this is due to some race conditions. Some text manipulation commands aren't done loading yet. I'm afraid this is something that can be fixed thru time. So I will close this issue as resolved for now. 
 
 
By the way you can manage your configs using ``` Hyprdots ``` commands backup, revert to a certain backup  use different clone etc


![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/91740acd-568e-4364-be14-e75242ca3883)
