### ISSUE TITLE
[Bug]: Missing system tray icons

### ISSUE THREAD

**Issue by TitanHZZ** [prasanthrangan/hyprdots#856]
### Description

Some apps like Spotify should have system tray icons but they do not. Others like OpenRGB, only have an icon in the system tray when opened as a regular user, as root there is no icon but, please note that i manually compiled OpenRGB as i am developing support for a new device, i didn't test any package.  
Also, i am using Brave and i think it should have a tray icon but it does not. Not sure tho.  
But, some apps do work as expected such as Discord and Stremio, so not really sure what is going on.

### Steps to Reproduce

1. Install, as an example, [Spotify](https://aur.archlinux.org/packages/spotify)
2. Open Spotify

### Expected Behavior

Waybar would have a tray icon for Spotify.

### Actual Behavior

No system tray icon.

### Environment

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: Linux laptop-arch 6.7.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)
- Installation Environment: Dual boot with Windows 11 on the main hardware

**Comment by kRHYME7** [comment]
Spotify and Brave do not have a tray icon. Are pertaining to Active window Icons?

**Comment by TitanHZZ** [comment]
Spotify did have a tray icon in X11, OpenBox.

I am not sure what you asking here `Are pertaining to Active window Icons?`, sorry.

This is my waybar:
![image](https://github.com/prasanthrangan/hyprdots/assets/79657495/941c71af-7998-4504-a88d-8742d680e43a)

**Comment by RookiexCookie** [comment]
@TitanHZZ Brave doesnt have a tray icon but spotify does yes
can you check in the spotify setting under equalizer have you checked this option?
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/53ab3dde-9177-46e2-a7f0-3fed42b4377c)

if you did it will look like this
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/eb48bcd1-90e0-43d3-b3ef-ff582a45c02b)

**Comment by kRHYME7** [comment]
My bad, spotify does indeed have an Icon. 

What I mean by active window icons are this at the center. 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/0faa46e5-11e7-4618-bbbc-a2bd673cdb79)

this is the module for windows     ```hyprland/window ```

**Comment by TitanHZZ** [comment]
@RookiexCookie That did it for Spotify, thanks. My bad ( tho i don't remember ever enabling that :/ ).
I also installed [OpenRGB](https://archlinux.org/packages/extra/x86_64/openrgb/) and, just like the manually compiled version, it works well as a normal user but no tray icon (or even qt theme!) when running as root. I am assuming Waybar only "accepts" tray icons for normal users, is that right?

**Comment by kRHYME7** [comment]
@TitanHZZ  I think tray icons are coded by the  application itself. Not all apps have a system tray. 

window:center            systemtray: rightmost
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/61b7eac2-dd38-40fa-9780-30bce034c4ba)

>, it works well as a normal user but no tray icon (or even qt theme!) when running as root.
did you run waybar and hyprland as root also?

**Comment by TitanHZZ** [comment]
> Did you run waybar and hyprland as root also?

No, just OpenRGB.

**Comment by TitanHZZ** [comment]
> Why run it as root?

I was testing support for a new device. That is why i opened it as root and noticed that there is no tray icon or qt theme applied. But sometimes apps do need root to work like [Grub Customizer](https://archlinux.org/packages/extra/x86_64/grub-customizer/) and as a result they have no theme. In the case of Grub Customizer there is no tray icon anyway so no problems there.

> Based on my basic knowledge of the Linux file system I think if you run an application with root the session of that application is in root `/` not in `/home/$user/` Now if your configs are inside your home directory and also the session is primarily launch by user like Hyprland or waybar, how would your application even know where to find those configs/data?

Yeah, that makes total sense.

> Where are we now for the issue again?

Not really sure to be honest. I do think apps should be able to have tray icons (and themes) regardless of the user that started them but i totally understand if that is not something relevant to the project because GUI apps with root privileges are not that common as far as i know.

> Do brave have a system icon?

Yes it does. System icons work well but it does not have a tray icon as it is not supposed to have one (sorry about that).

**Comment by kRHYME7** [comment]
Yes I understand now, let's just say that this project is basically dot files or .config files.  This means that configurations are only on USER wide scale. Some apps need to run with sudo because they are systemwide apps.

>  GUI apps with root privileges are not that common as far as i know.

Unless the GUI needs to access systemwide files /.  then a polkit will popup asking for sudo. 


BTW I've seen on your waybar, that you're not enabling the module that displays the window icons, is that your preference? 

Thanks to this open issue I reenabled Spotify's systray.

**Comment by kRHYME7** [comment]
>So, we would need to apply those same dot files and config files to the root user to get the themes and tray icons to work? Symlinks, env variables pointing to the user configs? We could just apply all the configs to the root user as well but that just sounds overkill and honestly, i am not really sure if applying custom configs to the root user is something normal in Linux pricing.

That's not even a good practice

> Uhm, weird. I just selected the waybar style i liked the most, i didn't disable anything.

I see here's how you can add window icons to your bar also how to modify 
https://github.com/prasanthrangan/hyprdots/wiki/Theming#waybar
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c6aa16aa-f9ba-4869-8533-50939fbc124a)

**Comment by TitanHZZ** [comment]
> That's not even a good practice

Yeah, kinda saw that coming.

> I see here's how you can add window icons to your bar also how to modify https://github.com/prasanthrangan/hyprdots/wiki/Theming#waybar ![image](https://private-user-images.githubusercontent.com/53417443/304175657-c6aa16aa-f9ba-4869-8533-50939fbc124a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjE5MjQsIm5iZiI6MTcwNzc2MTYyNCwicGF0aCI6Ii81MzQxNzQ0My8zMDQxNzU2NTctYzZhYTE2YWEtZjliYS00ODY5LTg1MzMtNTA5MzlmYmMxMjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDE4MTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjOTkyNzlkN2E1MzI0NGJjY2Y3Y2Q5M2JiMjY4NTE0M2U0NDExZjExYTQ1MDFmOWI5ZTEwOTZmY2U5NmU5ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yT28yvAuLQVDv9asJodXvZSM_mCsUGAUT6eEUB6kdhw)

Gonna take a look a that. Thank you.

**Comment by RookiexCookie** [comment]
@TitanHZZ i think brave only have a tray icon for one thing
i asked phind ai and it searched and got results from github , reddit and stuff to find that only for vpn connection brave has a tray icon, heck i've  never seen that icon cuz i never used vpn feature of brave but so ya
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/48ea1305-9ad1-47f9-a3c0-17f8d8a80c6e)

**Comment by kRHYME7** [comment]
@TitanHZZ  is this issue resolved for now? Can we close this?

**Comment by TitanHZZ** [comment]
Yeah, i think we can.
