### ISSUE TITLE
Can't login ; multiGPU

### ISSUE THREAD

**Issue by naiyanrahman** [prasanthrangan/hyprdots#858]
* After installing this hyprland rice, can't log in using my user and password when I type my user credentials a black screen comes for a second and returns me to the login page again 

https://github.com/prasanthrangan/hyprdots/assets/77504180/bc1ef707-512b-4330-b451-ee55e96f446d

**Comment by kRHYME7** [comment]
@naiyanrahman  can you provide more info about your system ? 

```
[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- system information (GPU information ,CPU etc)
- Other info: [e.g., Display Resolution, Resolution, etc]
```

**Comment by kRHYME7** [comment]
Can you please login to TTY  ( ctrl + alt + 3 ) and check the grub config to if the nvidia_drm.modeset=1 is set -

``` grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub ```
also please check if nvidia-470xx-dkms package is installed and verify lsmod. 
``` lsmod | grep nvidia ```

**Comment by kRHYME7** [comment]
How about running ``` Hyprland ```` in that tty? 

I am afraid your GPU is not set correctly, have you tried some solutions in the issue tracker ?

also how about rerunning the installation? ``` ./install.sh ```

**Comment by kRHYME7** [comment]
>  also how about rerunning the installation? ./install.sh


Are you comfortable with the command line and editing files?

**Comment by kRHYME7** [comment]
Lets start by Starting Hyprland in the TTY.

**Comment by kRHYME7** [comment]
ctrl + alt + 3 
then log in 
then
run ``` Hyprland ```

**Comment by t101804** [comment]
> > also how about rerunning the installation? ./install.sh
> 
> Are you comfortable with the command line and editing files?
> 
> Also some issues might be similar to yours. Please read the some issues, here some example: #663 [#696 (comment)](https://github.com/prasanthrangan/hyprdots/issues/696#issuecomment-1869595507)

how to open tty in login menu ?

**Comment by t101804** [comment]
> ctrl + alt + 3 then log in then run `Hyprland`

i do ctrl alt 3 then enter my pass then login it still black screen

**Comment by kRHYME7** [comment]
Damn, I missed that you're using a VM. did you enable 3D acceleration? 
http://wiki.hyprland.org/Getting-Started/Master-Tutorial/#vm
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/02694cff-6d42-4024-a3a8-cd361b2a7d8d)

**Comment by Darshil-154** [comment]
> Damn, I missed that you're using a VM. did you enable 3D acceleration? http://wiki.hyprland.org/Getting-Started/Master-Tutorial/#vm ![image](https://private-user-images.githubusercontent.com/53417443/304272650-02694cff-6d42-4024-a3a8-cd361b2a7d8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTQ3MDEsIm5iZiI6MTcwNzgxNDQwMSwicGF0aCI6Ii81MzQxNzQ0My8zMDQyNzI2NTAtMDI2OTRjZmYtNmQ0Mi00MDI0LWEzYTgtY2QzNjFiMmE3ZDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA4NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MGY0NGEwMmM4OGY5NjJmYTE5MjQzMDQ5NDU3N2YwYTEzZWFjZjc1NTUwOTdjOTZjOGZlMzU0YzkzZWI2N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4rWftFXfypt9gm2W8EBByAMrWrYgLNc0v_BDXq6Cm5o)

btw there is no way to run hyprland on vm cause it has very slow 3D acceleration so use in actual hardware is neccessary

**Comment by kRHYME7** [comment]
@naiyanrahman  Did you enable 3D acceleration on your VM? As I can see no GPU detected.  https://github.com/prasanthrangan/hyprdots/issues/858#issuecomment-1940184817

**Comment by kRHYME7** [comment]
what is the ooutput for this 

``` paru -Qs nvidia ```

**Comment by kRHYME7** [comment]
yay -Qs nvidia

**Comment by kRHYME7** [comment]
@naiyanrahman  How did you solved it? So that we can share this as reference for other isues

**Comment by kRHYME7** [comment]
Thanks, closing this then
