### ISSUE TITLE
[Bug]: Increasing brightness locks and suspends my computer

### ISSUE THREAD

**Issue by JosiasPires** [prasanthrangan/hyprdots#859]
### Description

When I increase the brightness with XF86MonBrightnessUp, my computer executes swaylock and systemctl suspend, as if I have opened my laptop lid. I commented the suspension command (systemctl suspend) for demonstration purposes.

### Steps to Reproduce

1. Press laptop key to increase brightness (In my case: Fn + F4)

### Expected Behavior

Increase brightness

### Actual Behavior

It did increase the brightness, but it also suspended and locked my laptop.

### Screenshots

https://github.com/prasanthrangan/hyprdots/assets/104743492/855d508b-366e-4883-b166-c5cc43246bb2

### Environment

- Linux Distro: EndeavourOS
- Linux Version, output of `uname -a`: 
`Linux alucard-notebook 6.7.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000 x86_64 GNU/Linux`
- Hyprland Version, output of `hyprctl version`: v0.35.0
- Installation Environment: Main Hardware
- Other info: Acer Aspire A515-45

### Additional Information

If i change the 'increase brightness' to another key, e.g., F10, it works normally.

**Comment by kRHYME7** [comment]
Hello  @JosiasPires how about disabling the lid switch keybind? 
You do not have duplicate keybinds? 

* If so we can assume that ``` fn + f4 ``` on your system is also bind to the system lid switch? you can try to install ``` wev ``` package to see what is the input name of the fn + f4 keys. 

* also in case you have some duplicate keybindings you can run ``` Hyprdots show binds ``` and see if some duplicates are available. 



#### Another solution:

If this is the case maybe I can help you on setting this. 
disable the lid close keybinds and configure systemd to suspend on lid close. Then use swayidle to lock the screen before suspend .

**Comment by JosiasPires** [comment]
This is what happens when I press `fn + f4`:
```
[14:     wl_keyboard] keymap: format: 1 (xkb v1), size: 66551
[14:     wl_keyboard] repeat_info: rate: 25 keys/sec; delay: 600 ms
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 592; time: 1082207; key: 248; state: 1 (pressed)
                      sym: NoSymbol     (0), utf8: ''
[14:     wl_keyboard] key: serial: 593; time: 1082207; key: 248; state: 0 (released)
                      sym: NoSymbol     (0), utf8: ''

```

I don't have any duplicate keybinds, I didn't modify hyprdots too much.

**Comment by kRHYME7** [comment]
I think this is a Hyprland issue. I have the same issue too on one of my laptop. 
To solve this I commented out  the bind for the lid switch. 
``` #bindl= , switch:on:Lid Switch, exec, swaylock && systemctl suspend ```
and use systemd to handle my lid close 
here is the file you need to modify ``` /etc/systemd/logind.conf ``` 
here's the wiki https://wiki.archlinux.org/title/Power_management#ACPI_events


Maybe there is a conflict somewhere and Hyrpdots might not be able to solve this. 

If you want to dig deeper into this problem please raise an issue in the  https://github.com/hyprwm/Hyprland

**Comment by JosiasPires** [comment]
Hey! Thanks for the help, I solved this by uncommenting the HandleLidSwitch in `logind.conf` and creating this service in `/etc/systemd/system/swaylock.service`:
```
[Unit]
Description=Lock when suspending
Before=sleep.target

[Service]
User=alucard
Environment=WAYLAND_DISPLAY=wayland-1
Environment=XDG_RUNTIME_DIR=/run/user/1000
Type=forking
ExecStart=/usr/bin/swaylock
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=sleep.target
```
