### ISSUE TITLE
Rofi style/Theme selection bugs out

### ISSUE THREAD

**Issue by Balssh** [prasanthrangan/hyprdots#86]
Hi, first of all I want to send @prasanthrangan many thanks and good wishes as this setup made me able to run Arch for the first time (I spend a lot of getting the installation right and didn't have the sanity to rice everything on my own).

Now, when I try to select a Rofi/theme style using SUPER SHIFT A or SUPER SHIFT T the following happens:
![image](https://github.com/prasanthrangan/hyprdots/assets/82440615/522a34c6-1da8-4e10-90b7-1e9ed7c0cf1c)

Only the dark rectangle is up and I can't select anything. Haven't had time to debug on my own yet.

**Comment by prasanthrangan** [comment]
Hi, Thank you so much for your support!


> Only the dark rectangle is up and I can't select anything. Haven't had time to debug on my own yet.

No worries, this is a known issue (please refer #77) as the rofi config does not scale correctly to your screen size.


To fix this, please try adjusting the icon size in ~/.config/rofi/themeselect.rasi -
```
element-icon {
    size:                        450px;
```
try decreasing this size to fit your screen res.

**Comment by Balssh** [comment]
Well, I have quite the problem now, I accidentally hit MAIN L and put my laptop to sleep. I haven’t been able to wake it up from sleep for the past 2 hours and I am afraid I’ll have to send it to warranty.

Is this a known issue with arch/wayland/hyprland?

**Comment by prasanthrangan** [comment]
Oh, this should not be causing any hardware issue with your laptop. did your laptop reboot after?

**Comment by Balssh** [comment]
I researched a bit and it may be linked to https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate#Suspend/hibernate_does_not_work,_or_does_not_work_consistently so not anything by your script, but rather the setup already used (in my case I used: Arch in dual boot with Windows 11, secure boot enabled with NVIDIA GPU). Anyway, I got it to work after making sure the AC adapter is plugged on + hard rebooting my laptop (hold power button for ~30s).

I'll continue messing around with your config and maybe open new issues (hopefully even propose PRs if needed). Thanks again for your work!

**Comment by prasanthrangan** [comment]
> Anyway, I got it to work after making sure the AC adapter is plugged on + hard rebooting my laptop (hold power button for ~30s).

Thank you, glad that you got your laptop running! yeah, my script does not mess with power management, you'll have to configure it manually for hibernation to work.
