### ISSUE TITLE
Dunst not updates theme changes

### ISSUE THREAD

**Issue by se7en-x230** [prasanthrangan/hyprdots#861]
~/.config/dunst/ hast 2 files 
dunstrc und dunst.config

Which one gets called? 

also If I change the them dunst defaults back to what I guess it's default config. 
so does a logout/login without reboot.

OR the systemd notification system kicks in
~ ❯ dunst
CRITICAL: [dbus_cb_name_lost:1152] Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'mako' with PID '4455'.

**Comment by kRHYME7** [comment]
as you can see you have mako installed. you can disable that or delete that package

**Comment by se7en-x230** [comment]
ups ... how where did that come from?

Solved thanks

**Comment by kRHYME7** [comment]
Maybe you installed someone's dots?
