### ISSUE TITLE
[Bug]: Black Screen after modfying Screen in hyprland.conf

### ISSUE THREAD

**Issue by t101804** [prasanthrangan/hyprdots#867]
### Description
I'm accidently editing the monitor to 2k ( my monitor is 1080 ) and then i got blackscreen , i want to move back to 1080 but i cant. because my screen is full black after login. how i edit it ? even i cant get into tty mode ( ctrl alt 3 login ) 

### Expected Behavior
 
Edit monitor back

### Actual Behavior

[What actually happened?]

### Screenshots
Just black screen after login

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by kRHYME7** [comment]
Can you reboot? In sddm menu, change tty.

**Comment by t101804** [comment]
> Can you reboot? In sddm menu, change tty. 

sddm menu mean login page right? to input password and user or bios memu

**Comment by kRHYME7** [comment]
> sddm menu mean login page  

this

**Comment by t101804** [comment]
> Can you reboot? In sddm menu, change tty. 

how to change to tty?

**Comment by t101804** [comment]
> ctrl +alt + 3

i already pressed ctrl alt 3 in sddm then?

**Comment by kRHYME7** [comment]
log in

**Comment by t101804** [comment]
> log in 
> 
> then run ``` Hyprland ```

after i login it black screen even if already pressed ctrl alt 3

**Comment by kRHYME7** [comment]
can you send a picture? of this ?

**Comment by t101804** [comment]
> Here: 
> 
> + once you are in the sddm DO NOT LOG IN. 
> + press ctrl + alt + 3, now you will see a black screen with the login screen asking for username and password
> you will see this 
> ![IMG_20240213_121323](https://github.com/prasanthrangan/hyprdots/assets/53417443/1c95280f-3a79-4992-a817-63438fd19d71)
> 
>  
> + tell me if you successfully logged in using that
> then let's continue to the next step

https://github.com/prasanthrangan/hyprdots/assets/113588203/8cb94ed8-7b73-4191-97e9-26c8afb839ba


I ALREADY PRESS CTRL ALT 3 BUT Not got into Tty

**Comment by kRHYME7** [comment]
I do really Apologize 😔 I meant Ctrl Alt F3. I always miss typed Fn  numbers.Here's my Discord I might be able to help.khing0v0

**Comment by t101804** [comment]
> I do really Apologize 😔 I meant Ctrl Alt F3. I always miss typed Fn  numbers.Here's my Discord I might be able to help.khing0v0

acc my friend req so i can chat u. r3plican

**Comment by kRHYME7** [comment]
@t101804  can we close it now?

**Comment by t101804** [comment]
yep
