### ISSUE TITLE
Logout menu all cluttered

### ISSUE THREAD

**Issue by Balssh** [prasanthrangan/hyprdots#87]
If I click the logout icon on the waybar the following happens:
![image](https://github.com/prasanthrangan/hyprdots/assets/82440615/7ed51640-ce37-47b7-8155-9fcc50102af5)
As with https://github.com/prasanthrangan/hyprdots/issues/86 I haven't had yet time to debug on my own.

**Comment by prasanthrangan** [comment]
Same here, this is also a known issue (please refer #51).

to fix this, please adjust font size in `~/.config/wlogout/style.css` and padding in `~/.config/hypr/keybindings.conf`

```
bind = $mainMod, backspace, exec, wlogout -b 2 -c 0 -r 0 -L 930 -R 930 -T 300 -B 300 --protocol layer-shell # logout menu
```

**Comment by Balssh** [comment]
Thanks! I edited the font to 12 and it looks better but I think there still needs to be some edits to where the menu window is placed (it's still skewed towards the right side of the screen) even with the setting you commented (that was default in the config I had).

**Comment by prasanthrangan** [comment]
cool, I'm planning to make this dynamic later, so that it scales correctly for different screen res. Closing this for now!
