### ISSUE TITLE
[Custom]: battery charge limitation

### ISSUE THREAD

**Issue by Komoro4eK** [prasanthrangan/hyprdots#878]
How do I limit the battery charge? I found the file "/home/glazyrik/.config/hypr/hyprdots-ctl/batterynotify.conf" but it does not limit the battery charge to 60%. There is a function that should, in theory, limit the charge: unplug_charger_threshold. it works just as a notification.
As far as I understand, the full battery charge is in this file (/sys/class/power_supply/BAT0/charge_control_end_threshold), but the value does not change, even through sudo.

I think something needs to be done here to limit it, but I can't find it on the Internet, maybe you have documentation on this file so I can figure it out, I'll be only glad.
    #? Command/script to execute at minimum unplug_charger_threshold
`execute_unplug=""`
    #? Command/script to execute at maximum battery_low_threshold
`execute_low=""`

[batterynotify.conf.txt](https://github.com/prasanthrangan/hyprdots/files/14294285/batterynotify.conf.txt)
[batterynotify.sh.txt](https://github.com/prasanthrangan/hyprdots/files/14294286/batterynotify.sh.txt)

**Comment by kRHYME7** [comment]
Hello this Script nor Hypdots do not have the ability to limit this. And This is intended only for notification.  That threshold is just for notification it won't touch anything in your system. I wrote it this way.

BTW if you need something to limit the battery threshold, packages like tlpui for the GUI or TLP will be useful.
