### ISSUE TITLE
neovim colorscheme inconsistency

### ISSUE THREAD

**Issue by Mahathirrr** [prasanthrangan/hyprdots#881]
When using the Solarized Osaka colorscheme in Neovim, there is a mismatch in the background color between the folder/file project area and the code editing area. The folder/file project section adheres to Solarized Osaka, while the code writing area follows the Kitty theme. can anyone explain or solve it?
![240215_23h43m09s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/111866202/582e59af-461a-4dc9-94aa-fe861a03baa2)

by the way, Solarized-osaka's repo: https://github.com/craftzdog/solarized-osaka.nvim

**Comment by kRHYME7** [comment]
Hello this is a dupe of https://github.com/prasanthrangan/hyprdots/issues/735 . You can Try the suggestions there.

**Comment by Mahathirrr** [comment]
> Hello this is a dupe of #735 . You can Try the suggestions there.

that case is different. in my case, occur the different colorscheme inside the neovim, on the left use solarized-osaka (which it's my neovim colorscheme) and on the right side, it inherit kitty theme color. i just want use 1 colorscheme on my neovim(colorscheme that i had setup before on neovim).

**Comment by Mahathirrr** [comment]
oops my bad, i made the neovim colorscheme transparent so that it inherits the background from the kitty theme. i set colorscheme transparency to false, now it's already solved, thanks!
