### ISSUE TITLE
[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by shell-worm** [prasanthrangan/hyprdots#883]
hi i don't know what is keybind to lunch game luncher like this im new to linux please help me guys 
https://raw.githubusercontent.com/prasanthrangan/hyprdots/main/Source/assets/game_launch_2.png

**Comment by kRHYME7** [comment]
To know the keybind try to search it in ``` Hyprdots show binds ``` command

**Comment by RookiexCookie** [comment]
i dont think its set as a keybind 
also it got 5 different styles which you can set by typing the number after the script 
for example `~/.config/hypr/scripts/gamelauncher.sh 1` this will open the launcher with style 1

btw @kRHYME7 idk but somethind kinda weird
the thumbnails appear like this 
![image](https://github.com/prasanthrangan/hyprdots/assets/136296017/b5466ebe-3a7b-4ca7-ab74-006731f99056)

**Comment by kRHYME7** [comment]
@RookiexCookie  Let's open another issue for that.  What style number is this? I don't have games but @prasanthrangan  can test and fix this. Thanks for the headup.

**Comment by shell-worm** [comment]
@RookiexCookie awwah man i understand. now thank u so much man u really make my day
