### ISSUE TITLE
[Custom]: Short description of the issue

### ISSUE THREAD

**Issue by mohammedaouamri5** [prasanthrangan/hyprdots#884]
### Description

[Provide a clear and concise description of the issue or request.]

### Steps to Reproduce (if applicable)

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots (if applicable)

[If applicable, add screenshots to help explain your problem.]

### Proposed Solution (if applicable)

[If you have a specific solution in mind, describe it here. If not, you can skip this section.]

### Additional Information

[Add any other information about the issue or request here. For example, you might include links to similar features in other projects, or screenshots or diagrams to help explain your idea.]

**Comment by kRHYME7** [comment]
@mohammedaouamri5  I'll be closing this for now, Please reopen this issue if you have issues with the configuration.
