### ISSUE TITLE
swaylock using 100% of CPU

### ISSUE THREAD

**Issue by stove-jeebs** [prasanthrangan/hyprdots#89]
My screen doesn't lock when i click on "lock" and the CPU usage shoots up to 90-100% usage. Anyone experience something similar?

**Comment by prasanthrangan** [comment]
I've not faced this with my system. can you check if its the `swaylock` process that's causing this?

**Comment by stove-jeebs** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/1326803a-8cf8-4963-a96a-93a37e0a495d)

**Comment by prasanthrangan** [comment]
oh, that looks bad... for me its just 0.7 - 0.8% cpu usage.
you can try replacing `swaylock` with `gtklock` and check if it works better.

**Comment by stove-jeebs** [comment]
Swaylock works if i remove "screenshot" from the /home/<username>/.config/swaylock/config file
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/a41f7981-5800-46be-98a7-6c8afe11fa22)

**Comment by prasanthrangan** [comment]
> Swaylock works if i remove "screenshot" from the /home//.config/swaylock/config file

glad it worked! screenshot option is used for that blurred background.
I have faced issue with this option before, in my nvidia system.

**Comment by stove-jeebs** [comment]
huh turns out screenshots will work with only one screen...

**Comment by prasanthrangan** [comment]
> huh turns out screenshots will work with only one screen...

oh, good to know.. It does crash my system as well, so I'm looking for lockscreen alternatives, so i might replace swaylock in future.

**Comment by stove-jeebs** [comment]
thank you for the responses i will close the issue now

**Comment by Lol-Lap** [comment]
> Swaylock works if i remove "screenshot" from the /home//.config/swaylock/config file ![image](https://user-images.githubusercontent.com/67490238/261838085-a41f7981-5800-46be-98a7-6c8afe11fa22.png)


Sry How did you fix this? I have the same issue.

**Comment by prasanthrangan** [comment]
> Sry How did you fix this? I have the same issue.

just remove or comment out the line in `~/.config/swaylock/config` file.
