### ISSUE TITLE
[Bug]: Keybind to resize window not working

### ISSUE THREAD

**Issue by TurtleMeds** [prasanthrangan/hyprdots#893]
### Description

If I have multiple windows open and I try to resize to the right, it will not work. To be clear, this is just the keybind that is broken. I've successfully resized the window with the mouse and even running `Hyprdots show binds` and hitting enter on resize.

### Steps to Reproduce

1. Open two windows
2. Use <kbd>:penguin:</kbd> + <kbd>Shift</kbd> + <kbd>→</kbd>

### Expected Behavior

current window resizes to the right

### Actual Behavior

nothing

### Screenshots

N/A

### Environment

- Linux Distro: Arch
- Linux Version, output of `uname -a`: `Linux E16 6.7.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000 x86_64 GNU/Linux`
- Hyprland Version, output of `hyprctl version`:
```
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)
```
- Installation Environment: Real Hardware (thinkpad E16)

**Comment by RookiexCookie** [comment]
Works for me tho

https://github.com/prasanthrangan/hyprdots/assets/136296017/ea2ad3df-c3ae-47f4-afdb-4715f7b9f42a

**Comment by TurtleMeds** [comment]
Like I said, even using `Hyprdots show binds` and hitting enter works.
![240217_14h45m04s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/76972146/7ed4dc4e-cf0c-4510-be7c-808f58e0047f)
I know that it works for most people, that is why this is not a duplicate issue. I think this is just an issue with my specific setup.

**Comment by kRHYME7** [comment]
Strange, can you try to search for duplicate binds? Like searching for Ctrl Shift right

**Comment by TurtleMeds** [comment]
It also will not work when moving windows

**Comment by TurtleMeds** [comment]
> Strange, can you try to search for duplicate binds? Like searching for Ctrl Shift right

I searched in the entire `~/.config/hypr/` folder for all instances of "right" and couldn't find anything.

**Comment by kRHYME7** [comment]
okay if the dispatcher works then try to remap this functionality to another key and see if this works. 


+ Also here's how to search it, this is way better as Hyprdots show binds will juts fetch all the active keybindings so no need to check the .conf. (This only uses the .conf to fetch comments for the description)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/7e1ba4ae-63be-476d-9581-2fb11414a041)


+ Another way to troubleshoot this is using the package ``` wev ``` this will help you know the keys you pressed 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/765fe7e1-6490-4e81-a41f-a3b7ea748044)


+ Any chance you're using another keyboard layout?

**Comment by TurtleMeds** [comment]
Okay this is weird. `wev` shows an output for super and shift but not right. it works with all other directions too, so I have no idea what could be causing this (probably not the fault of these dotfiles). as for the keyboard layout, I do have two in my config, (us and us international) but neither of them work. I am using a normal us qwerty keyboard on a thinkpad (e16) so very standard.
thanks for your help!

**Comment by kRHYME7** [comment]
Is your right arrow keyboard still working?. can you navigate cursors?

**Comment by TurtleMeds** [comment]
yes, the right arrow key does work without modifiers.

**Comment by TurtleMeds** [comment]
> okay if the dispatcher works then try to remap this functionality to another key and see if this works.

oops I didn't see this until now. I remapped it and yes, it does work. the problem seems to just be the right arrow key.

**Comment by kRHYME7** [comment]
@TurtleMeds I'll close this for now as this isn't really config related. Feel free to open or continue to discuss any improvements and findings. 🫰
