### ISSUE TITLE
[Bug]: Screen Flickering During gaming 

### ISSUE THREAD

**Issue by KMcNeace** [prasanthrangan/hyprdots#895]
Hey I’m running a laptop with an Intel i7 7700k and a Nvidia GTX 1070 mobile. I’m using the default config and fresh out of an install I only installed Steam and tried to run a couple games. Every game runs with great framrate but I have issues with my screen just flickering on and off. I’m not for sure if this is a Wayland issue or an Nvidia issue but does anyone have any tips to fix this?

**Comment by kRHYME7** [comment]
Hello This is a common report, so please see some issues that might help you. 

But try to downgrade your nvidia driver to v535.

**Comment by szymon-f** [comment]
I am running Nvidia GTX 1060 and Intel i5 12600k. This seems to be an Nvidia issue. For me it started around November of 2023, when Nvidia drivers were updated to version 545. I wasn't able to find a general solution (one that didn't involve downgrading drivers to version 535), but I was able to make Minecraft run without issues. To fix Minecraft you have to install the WayGL mod ( https://modrinth.com/mod/waygl ). If you want to fix anything other than Minecraft, I have no idea.

**Comment by KMcNeace** [comment]
> I am running Nvidia GTX 1060 and Intel i5 12600k. This seems to be an Nvidia issue. For me it started around November of 2023, when Nvidia drivers were updated to version 545. I wasn't able to find a general solution (one that didn't involve downgrading drivers to version 535), but I was able to make Minecraft run without issues. To fix Minecraft you have to install the WayGL mod ( https://modrinth.com/mod/waygl ). If you want to fix anything other than Minecraft, I have no idea.

I appreciate all the help. I’m installing the 535 drivers now and I’ll update this post with the results of this!

**Comment by kRHYME7** [comment]
@KMcNeace Halu any improvements/updates?

**Comment by KMcNeace** [comment]
> @KMcNeace Halu any improvements/updates? 

Not really. When I downgraded the drivers I couldn't get any games to launch from Steam anymore. So I did a fresh install of hyprdots and just left it as is. Gaming seems to be the only problem so I kept a dual boot of Garuda's KDE for that reason. I'll use hyprland for everything but gaming.

**Comment by kRHYME7** [comment]
v550 is out so might as well try it.

**Comment by KMcNeace** [comment]
> v550 is out so might as well try it. 

I'm gonna test those out today, I'll see if it fixes that issue. Using froggy-family to install the 530 driver did fix the issue for certain games but then broke others lol. I'm sure if I had a rtx card with the open source drivers I may have had a better experience. But for now I'm not gonna stress gaming on hyprland atm.
