### ISSUE TITLE
[Bug]: Cant install ; chsh: "/sbin/zsh" is not listed in /etc/shells.

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [prasanthrangan/hyprdots#896]
## Bug Report
```
[DISPLAYMANAGER] detected // sddm
[SKIP] sddm is already configured...
[FILEMANAGER] detected // dolphin
[FILEMANAGER] setting org.kde.dolphin.desktop as default file explorer...
[SHELL] detected // zsh
intalling zsh plugins (git sudo zsh-256color zsh-autosuggestions zsh-syntax-highlighting)
[SHELL] changing shell to zsh...
Changing shell for boobs.
Password: 
chsh: "/sbin/zsh" is not listed in /etc/shells.
Use chsh -l to see list.
```

$ chsh -l
/bin/sh
/bin/bash
/bin/rbash
/usr/bin/sh
/usr/bin/bash
/usr/bin/rbash
/usr/bin/git-shell
/bin/zsh
/usr/bin/zsh
/usr/bin/fish
/bin/fish

### Description

I think the wrong directory is selected somewhere?
/sbin/zsh insteam of /bin/zsh

### Steps to Reproduce

1. Start the installer

### Expected Behavior

install

### Actual Behavior

stops installing because directory doesn't exist

- ArchLinux
- 6.7.5-zen1-1-zen
- Hyprland Version, output of `hyprctl version`:
- Hardware
- 2560 1440

**Comment by H1manshu-Soni** [comment]
happens to me as well just change restore_shl.sh and line 59 change that to "chsh -s "/bin/fish" if you use fish or "chsh -s /bin/zsh" if you use zsh
this is just a workaround and not a proper solution

**Comment by kRHYME7** [comment]
Strange, If I understand correctly ``` chsh ``` command says the ``` $(which zsh) ``` returns  ``` /sbin/zsh ```  which  is not listed inside the /etc/shells.  

to fix this soon we will add this line ```     grep -q "$(which zsh)" /etc/shells || sudo tee -a /etc/shells < <(which zsh)
 ``` which checks if the shell is inside  /etc/shells

**Comment by prasanthrangan** [comment]
Hey, please try reinstalling `zsh`, and then check in `/etc/shells`. did you run the installed script with sudo or as root?

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Probably without because i wasnt told to run it with sudo
```

# Pathnames of valid login shells.
# See shells(5) for details.

/bin/sh
/bin/bash
/bin/rbash
/usr/bin/sh
/usr/bin/bash
/usr/bin/rbash
/usr/bin/git-shell
/bin/zsh
/usr/bin/zsh
/usr/bin/fish
/bin/fish

```
get a different error after reinstalling i think i corrupted my install ill reinstall if i still have issues ill make a new comment if not ill close it

**Comment by kRHYME7** [comment]
how about ``` which zsh ```?

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Same problem on a new install on a different pc

**Comment by kRHYME7** [comment]
what is the output for ``` which zsh ```  on that system?

**Comment by Schweeeeeeeeeeeeeeee** [comment]
/sbin/zsh

**Comment by kRHYME7** [comment]
That's the problem, why you zsh was installed in system bin.  

+ If you run ``` whoami ```, is your username is displayed? 

+ I usually use this to recompile and reinstall something ``` paru -Sy zsh --rebuild ``` as we can see that you have a faulty zsh install. 

+ For now you can manually run this command to set your shell ```  chsh -s /usr/bin/zsh ```   then rerun the installation again. 


Please try to follow these solutions.

**Comment by Schweeeeeeeeeeeeeeee** [comment]
The pc im at is really slow im propably not going to be able to do that here (limited time here and builds for ages) ill try it on mine

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Same thing on a completely fresh arch install 

(really didnt have the time to use my pc the last 2 days)

**Comment by Schweeeeeeeeeeeeeeee** [comment]
after running chsh -s /usr/bin/zsh i get this error

NetworkManager service is not running, enabling...
Created symlink /etc/systemd/system/multi-user.target.wants/NetworkManager.service → /usr/lib/systemd/system/NetworkManager.service.
Created symlink /etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service → /usr/lib/systemd/system/NetworkManager-dispatcher.service.
Created symlink /etc/systemd/system/network-online.target.wants/NetworkManager-wait-online.service → /usr/lib/systemd/system/NetworkManager-wait-online.service.
NetworkManager service enabled, and running...
bluetooth service is not running, enabling...
Created symlink /etc/systemd/system/dbus-org.bluez.service → /usr/lib/systemd/system/bluetooth.service.
Created symlink /etc/systemd/system/bluetooth.target.wants/bluetooth.service → /usr/lib/systemd/system/bluetooth.service.
bluetooth service enabled, and running...
sddm service is not running, enabling...
Failed to enable unit: File /etc/systemd/system/display-manager.service already exists and is a symlink to /usr/lib/systemd/system/ly.service.

**Comment by kRHYME7** [comment]
Hmmm how did you install arch?


Does that Error message always come out? I think that's not an error though.

**Comment by Schweeeeeeeeeeeeeeee** [comment]
I used the archinstall script
And the error is bright red
Failed to enable unit: File /etc/systemd/system/display-manager.service already exists and is a symlink to /usr/lib/systemd/system/ly.service.

**Comment by kRHYME7** [comment]
Anything unusual you've done on your archinstall?

like why, 😆 what is the output for 

``` echo $SHELL

whoami
```

**Comment by Schweeeeeeeeeeeeeeee** [comment]
I chose grub and and for the login screen (forgot what thats called) i chose ly

whoami
/usr/bin/bash
boobs
[boobs@archlinux S

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Seems like everything works now thx :)

**Comment by kRHYME7** [comment]
Closing this for now as resolved.
