### ISSUE TITLE
[Bug]: Spotify doesnt work! (i have read other related issues)

### ISSUE THREAD

**Issue by H1manshu-Soni** [prasanthrangan/hyprdots#897]
## Bug Report

Spotify theme never works I have tried other solutions with related issues and still couldnt get it to work.

### Description

I have tried this
"sudo chmod a+wr /opt/spotify && sudo chmod a+wr /opt/spotify/Apps -R"
Also on a new install of hyprdots spotify and spicetify-cli doesnt install automatically.
I manually have to install them.

### Steps to Reproduce

1. Install Hyprdots
2. Install spotify and spicetify-cli
3. Open spotify un-riced.

### Expected Behavior

Spotify riced?

### Actual Behavior

Nada kasha boom!! Nothing

### Environment

- Linux Distro: Arch Linux

- Linux Version, output of `uname -a`: Linux Saturday 6.7.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:33 +0000 x86_64 GNU/Linux

- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

- Installation Environment: Bare Metal

**Comment by kRHYME7** [comment]
> Also on a new install of hyprdots spotify and spicetify-cli doesnt install automatically.
I manually have to install them.

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/4b53c65f-5de6-443e-bd41-b80c32ffd7d6)


+ Try to run and see what its output. 

``` ~/.config/hypr/scripts/wallbashspotify.sh ```

**Comment by H1manshu-Soni** [comment]
Oh I see, sorry for the ignorance but the scripts posts no output 



![240218_18h44m43s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/84933847/622e978f-1d8d-4288-bbc5-6bf76e4eda9c)

**Comment by H1manshu-Soni** [comment]
Oh I see, sorry for the ignorance

The script works now (idk why it wasnt working before)
One more thing it wont auto update after changing theme so I added a line in ~/.config/hypr/scripts/swwwallpaper.sh
in line 70 "spicetify apply" in order for it to change theme with wallpaper change :)
(might be helpful for anyone else in the future)

Again thanks for the help!

**Comment by kRHYME7** [comment]
What did you mean with line 70 ? 

BTW I think  ```         spicetify -q watch -s & ```  should change it but incase it wont yah ```  spicetify  apply  -q  ```  would work.

**Comment by H1manshu-Soni** [comment]
> ~What did you mean with line 70 ?~ ah yes
> 
> BTW I think ` spicetify -q watch -s &` should change it but incase it wont yah ` spicetify apply -q ` would work. `~/.config/hypr/scripts/wallbashspotify.sh` this script should always be called while changing wallpapers.



actually this command works much better 
Nice!
