### ISSUE TITLE
Keyboard layout issues

### ISSUE THREAD

**Issue by yamborghinifly** [prasanthrangan/hyprdots#9]
Hello, 
firstly thanks for the impressive design and script. 
There's one issue that I seem to have, it's that the keyboardlayout seems to be stuck to the US layout. Tried changing it in the hyprland.conf but it doesn't seem to work. 

Please keep in mind that I'm still pretty much a newbie in these topics.

Thanks!

**Comment by Freakstyleer** [comment]
![grafik](https://github.com/prasanthrangan/hyprdots/assets/118598928/356a8d72-3630-4cde-89d1-2674a8a40a9e)
Works for me

**Comment by yamborghinifly** [comment]
@Freakstyleer 
That worked after reinstalling Arch somehow, thanks!
