### ISSUE TITLE
How to minimize a software

### ISSUE THREAD

**Issue by naiyanrahman** [prasanthrangan/hyprdots#903]
I install google chrome and now cant find the minimize option and in git documentation there are no keyboarding for that

**Comment by kRHYME7** [comment]
Hi are you mistaking this Hyprland Window Manager as Full Desktop environment?

**Comment by kRHYME7** [comment]
No problem! It's a bit hacky giving Window managers a minimized option as it did not exist. Some apps might be minimized if they have tray icon. Goodluck!
