### ISSUE TITLE
[Feature Request]: Setting on Hyprland.conf to change mouse speed

### ISSUE THREAD

**Issue by jorgemota** [prasanthrangan/hyprdots#907]
## Feature Request
Setting on hyprland.conf to allow change mouse/cursor speed
### Description

I was looking on docs and examples to change the cursor/mouse speed, I have 3 monitors (27",32",27" widescreen)
I need a lot of movements on my logitech trackball to get from left to right

### Alternatives

 I used from arch forums the steps described on https://wiki.archlinux.org/title/Mouse_acceleration but I got the speed I need on awesome, but not in Hyprland

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/blob/main/Configs%2F.config%2Fhypr%2Fhyprland.conf#L67-L85


Hello you can override your preferred Sensitivity on the ./userprefs.conf as this is device specific change. Please refer to the wiki on how you can change this.

**Comment by jorgemota** [comment]
Thanks, I have reviewed it, but Cannot figure out what I need to put in the configuration file. I am going to review again.

**Comment by kRHYME7** [comment]
simply you can add this in your userprefs.
According to the wiki 

```

input {
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

```

if you want to add your device , hyprland needs to know what is your device therefore use this command to get your ``` mice ``` model, ``` hyprctl devices ``` 


Here's an example 
```

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more

device:epic mouse V1 {
    sensitivity = -0.5
}

```

**Comment by jorgemota** [comment]
Thanks, I already have it like this:
devices list:
`hyprctl devices
mice:
	Mouse at 64389708da20:
		asustek-tuf-gaming-k1-keyboard-1
			default speed: 0.00000
	Mouse at 643896d194f0:
		asustek-tuf-gaming-k1-mouse
			default speed: 0.00000
	Mouse at 643896c651c0:
		logitech-usb-trackball
			default speed: 0.`
Configuration added:

`device:logitech-usb-trackball { 
  accel_profile =  custom 800 0.0 1.5
  sensitivity = 1 
  }`

But after save I dont' get any change, increased 200 to 400,600,800 without changes, and 0.0 and 1.5 to 2.0 with 0.1 intervals but no luck, I am not sure if the problem is caused by the mouse  type  (trackball)

I don´t have gaming k1 mouse, (only keyboard)
![image](https://github.com/prasanthrangan/hyprdots/assets/1952329/ffc6b7c4-f512-4198-95d4-d7479c83db88)

I am going to buy tomorrow a simple mouse to check the configuration with a normal mouse.

**Comment by kRHYME7** [comment]
I have no luck or dunno yet how to set the per device input

```
input {
    sensitivity = 1 # -1.0 - 1.0, 0 means no modification.
    force_no_accel = 1 
}

```

to query the values you set you can use 

``` hyprctl getoption input:[options] ```
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/5adf1c96-b8d8-4151-bc15-591a48b0f445)

**Comment by kRHYME7** [comment]
https://github.com/hyprwm/Hyprland/issues/2056 

@jorgemota  I think this is unresolved issue in the upstream Hyprland.

**Comment by jorgemota** [comment]
thanks @kRHYME7 I changed it, and now the speed is a bit better, with some random jumps, but i don't need a lot of movements to navigate between screens.

**Comment by kRHYME7** [comment]
Closing this then.  

> furthermore it hsould be handled by libinput
https://github.com/hyprwm/Hyprland/issues/2056#issuecomment-1544908992

**Comment by vampirepapi** [comment]
> Confirmed, with a cheap mouse, modifyn input global or input:devicename I can see how changes affects mouse speed, but never to trackball

what changes you exactly made to increase the mouse acceleration?
im using ext mouse and its acceleration is very low, i tried changing in conf file but didnt worked for me. TIA

**Comment by jorgemota** [comment]
> > Confirmed, with a cheap mouse, modifyn input global or input:devicename I can see how changes affects mouse speed, but never to trackball
> 
> what changes you exactly made to increase the mouse acceleration? im using ext mouse and its acceleration is very low, i tried changing in conf file but didnt worked for me. TIA

in hyprlando.conf leave only this to input:

input {
    follow_mouse = 1
    touchpad {
        natural_scroll = no
    }
    #sensitivity = 0
    #force_no_accel = 1
    numlock_by_default =true
    accel_profile =  adaptive
    sensitivity = 0.8 # -1.0 - 1.0, 0 means no modification.
    force_no_accel = 0
}

comment the "epic mouse"

#/*device {
#    name = epic mouse V1
#    sensitivity = -0.5
#}*/


I need to add this on userprefs.conf:


input {
    float_switch_override_focus=0 #you can ignore this
    follow_mouse = 1 #you can ignore this
    mouse_refocus=0
    touchpad {
        natural_scroll = no
    }
    numlock_by_default =true #you can ignore this
    accel_profile =  adaptive
    sensitivity = 0.8 # -1.0 - 1.0, 0 means no modification.
    force_no_accel = 0
}

**Comment by vampirepapi** [comment]
> > > Confirmed, with a cheap mouse, modifyn input global or input:devicename I can see how changes affects mouse speed, but never to trackball
> > 
> > 
> > what changes you exactly made to increase the mouse acceleration? im using ext mouse and its acceleration is very low, i tried changing in conf file but didnt worked for me. TIA
> 
> in hyprland.conf I leave only this to input:
> 
> ```
> input {
>     follow_mouse = 1
>     touchpad {
>         natural_scroll = no
>     }
>     #sensitivity = 0
>     #force_no_accel = 1
>     numlock_by_default =true
>     accel_profile =  adaptive
>     sensitivity = 0.8 # -1.0 - 1.0, 0 means no modification.
>     force_no_accel = 0
> }
> ```
> 
> commented the "epic mouse"
> 
> ```
> #/*device {
> #    name = epic mouse V1
> #    sensitivity = -0.5
> #}*/
> ```
> 
> And I need to add this on userprefs.conf:
> 
> ```
> input {
>     float_switch_override_focus=0 #you can ignore this
>     follow_mouse = 1 #you can ignore this
>     mouse_refocus=0 #you can ignore this
>     touchpad {
>         natural_scroll = no
>     }
>     numlock_by_default =true #you can ignore this
>     accel_profile =  adaptive
>     sensitivity = 0.8 # -1.0 - 1.0, 0 means no modification.
>     force_no_accel = 0
> }
> ```

great, will try on evening and check if this works for me.

**Comment by vampirepapi** [comment]
> > > Confirmed, with a cheap mouse, modifyn input global or input:devicename I can see how changes affects mouse speed, but never to trackball
> > 
> > 
> > what changes you exactly made to increase the mouse acceleration? im using ext mouse and its acceleration is very low, i tried changing in conf file but didnt worked for me. TIA
> 
> in hyprland.conf I leave only this to input:
> 
> ```
> input {
>     follow_mouse = 1
>     touchpad {
>         natural_scroll = no
>     }
>     #sensitivity = 0
>     #force_no_accel = 1
>     numlock_by_default =true
>     accel_profile =  adaptive
>     sensitivity = 0.8 # -1.0 - 1.0, 0 means no modification.
>     force_no_accel = 0
> }
> ```
> 
> commented the "epic mouse"
> 
> ```
> #/*device {
> #    name = epic mouse V1
> #    sensitivity = -0.5
> #}*/
> ```
> 
> And I need to add this on userprefs.conf:
> 
> ```
> input {
>     float_switch_override_focus=0 #you can ignore this
>     follow_mouse = 1 #you can ignore this
>     mouse_refocus=0 #you can ignore this
>     touchpad {
>         natural_scroll = no
>     }
>     numlock_by_default =true #you can ignore this
>     accel_profile =  adaptive
>     sensitivity = 0.8 # -1.0 - 1.0, 0 means no modification.
>     force_no_accel = 0
> }
> ```

Thanks, bro, it worked. But could you please explain what that code does?

**Comment by dieBakterie** [comment]
It Sets the sensotivity to 0.8 and the acceleration Profile to adaptive.
