### ISSUE TITLE
cant install spotify 

### ISSUE THREAD

**Issue by naiyanrahman** [prasanthrangan/hyprdots#914]
I tried to install spotify but can't install it, I also tried to make from makepkg from this git https://github.com/kpcyrd/spotify-launcher still the same  
![image](https://github.com/prasanthrangan/hyprdots/assets/77504180/5a2c18fe-a50e-4f90-b380-a633fcaab2c6)

**Comment by kRHYME7** [comment]
Please reopen an issue relating to dotfiles, Cheers 🥂
