### ISSUE TITLE
Automatically set ENV for a Virtual Machine

### ISSUE THREAD

**Issue by alexcarman** [prasanthrangan/hyprdots#92]
Based on this issue two environment variables need to be configured for running in a Virtual Machine:
https://github.com/hyprwm/Hyprland/issues/797

They are:

WLR_NO_HARDWARE_CURSORS=1
WLR_RENDERER_ALLOW_SOFTWARE=1

I'm asking for a feature enhancement that will detect that we are installing on a VM and set these much like the nvidia auto detection.

In a virtual machine once hyprland starts it locks up.

**Comment by alexcarman** [comment]
The more I played with it the more I think this enhancement will no be necessary.  The virtual 3d accelerator doesn't seem to be able to even run kitty and I continued having issues getting things working and or even responsive.

**Comment by prasanthrangan** [comment]
Hi, I don't think hw acceleration works in VM unless you pass through your GPU, and kitty does use gpu.
