### ISSUE TITLE
[Bug]: Brave, Thorium (GTK theme error) wierd behaviour.

### ISSUE THREAD

**Issue by H1manshu-Soni** [prasanthrangan/hyprdots#922]
### Description

I installed brave-bin and thorium-bin and ran them but they dont open properly with no GUI running through the terminal I got errors (screenshot below).

### Steps to Reproduce

I am not sure if its reproducable on other devices.

### Screenshots

![240220_23h09m55s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/84933847/7cff67ef-49c9-4b59-84e7-67242ecad83d)

![240220_23h11m32s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/84933847/75f76b04-2984-420c-ad20-f080821deec3)

### Environment

- Linux Distro:  ArchLinux

- Linux Version, output of `uname -a`: Linux Saturday 6.7.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:33 +0000 x86_64 GNU/Linux

- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

- Installation Environment: Bare Metal
- Other info: 1920x1080@60

### Additional Information

I added custom wallpapers which I thought might be the reason for error but the default theme gives the same error.

**Comment by pragit-raj-sharma** [comment]
try runnig with `brave --ozone-platform-hint=wayland --disable-gpu`
there is an issue with chromium based browsers on wayland.

**Comment by H1manshu-Soni** [comment]
That works but I can't be opening it like that every time
