### ISSUE TITLE
guys please help me i just swith that theme and every thing just broke i can't change theme i can't do anything i can just open terminnal please help me

### ISSUE THREAD

**Issue by shell-worm** [prasanthrangan/hyprdots#923]
![1708451917970](https://github.com/prasanthrangan/hyprdots/assets/141477909/5c0eb3e8-ccb5-43db-bbe1-207c305edd7a)
![1708451917908](https://github.com/prasanthrangan/hyprdots/assets/141477909/f08bd14d-58fa-4ffa-ab43-69207b790578)
![1708451917941](https://github.com/prasanthrangan/hyprdots/assets/141477909/1a83c93e-fe81-4425-aa88-ff9b22548d9b)

**Comment by kRHYME7** [comment]
retry to  change the theme/wallpaper again

**Comment by shell-worm** [comment]
@kRHYME7 thank u bro it work brother u are live save
