### ISSUE TITLE
VSCode is super delayed when opened

### ISSUE THREAD

**Issue by QuackSecX** [prasanthrangan/hyprdots#925]
### Description

When using SUPER + C to open VSCode, there is an extremely long delay and it sometimes doesn't open until a few minutes later. The same goes for accessing it via cli and it will throw an error saying that an instance of VSCode is already in use (because I used the keybind option). Sometimes it doesn't open at all, not sure why.

**Comment by Enigma1309** [comment]
Seems system related issue, more info needed

**Comment by Radrahil** [comment]
Try pkill vscode and then opening vscode in the terminal. See if there are any warnings or error messages

**Comment by Enigma1309** [comment]
that won't work launching vs-code from terminal wont give any output, i tried it before the above comment
