### ISSUE TITLE
[Feature Request]: Optional cheatsheet for keybinds on Waybar

### ISSUE THREAD

**Issue by Haraven** [prasanthrangan/hyprdots#926]
### Description

Having a cheatsheet readily available while you're still learning the ropes is very useful. I've only been using Hyprland + Hyprdots since yesterday and I find myself having to go back to the keybinds section of Hyprdots every now and then, to figure out how to navigate. 

### Use Case

Especially useful for newcomers to Hyprland and Hyprdots, who are still learning how to use their new system.

### Proposed Solution

This cheatsheet should be:
- available on the Waybar as an icon
- optional: add it to the Waybar or remove it as needed
- preferably configurable: if you add extra keybinds in your `~/.config/hypr/userprefs.conf` or if you comment out some of the default keybinds, the cheatsheet should reflect these changes

### Alternatives

A quick and dirty alternative would be to add a link to the Hyprdots README on the Waybar, so people can reference it when needed.

### Additional Information

I found this feature in [Garuda Linux's](https://garudalinux.org/downloads) Hyprland edition and it was very useful when trying out their distro.

**Comment by kRHYME7** [comment]
Try ``` Hyprdots show binds ```

**Comment by Haraven** [comment]
So cool! 

I didn't know there was such a tool available. Thank you!

As for the icon, I'm not too sure myself. Maybe [sheet-plastic](https://fontawesome.com/icons/sheet-plastic?f=classic&s=solid), [keyboard](https://fontawesome.com/icons/keyboard?f=classic&s=solid), or [clipboard-list](https://fontawesome.com/icons/clipboard-list?f=classic&s=solid)? The keyboard icon is the most intuitive, in my opinion.

**Comment by kRHYME7** [comment]
Yeah, no time to make documentation.

**Comment by Haraven** [comment]
I'll keep that in mind, thank you!

PS. I've been playing around with Hyprdots-ctl and it's been such a good experience! It's made editing waybar and theme settings much easier. I also just noticed the SDDM configs (I'd manually edited it before finding out about the tool).

Thanks for all your work!

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/pull/942/files

@Haraven 

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/eaebe848-bcb8-4bf3-882b-9593ea9d36e4)


```
"custom/keybindhint": {
    "format": " ",
    "on-click": "Hyprdots show binds",
},

```

**Comment by Haraven** [comment]
Thank you!

Not sure where to go from here, as this is my first time posting a feature request on GitHub. Do I close the issue now or wait for the PR to go through?

**Comment by kRHYME7** [comment]
Let's wait for the PR.

**Comment by kRHYME7** [comment]
@Haraven  Merged
