### ISSUE TITLE
Waybar text size too small.

### ISSUE THREAD

**Issue by pragit-raj-sharma** [prasanthrangan/hyprdots#928]
I want to change the text size of waybar, which can be changed by `.config/waybar/modules/style.css (font-size: ${s_fontpx}px;)` and `$_fontpx` is generated by `.config/hypr/scripts/wbarstylegen.sh (export s_fontpx=$(( b_height*38/100 )))`

Now if I change font size in `style.css` it gets overwritten by `wbarstylegen.sh.` To make it persistent over all themes, I have to change the ratio in `wbarstylegen.sh`.

I have to change the script or there's some specific configuration file like `.config/hypr/userprefs.conf` to do it.

**Comment by pragit-raj-sharma** [comment]
so I tried it and it worked but it gets overwritten as soon as I update the theme and also I made some changes to the modules of waybar they are also overwritten after update.

**Comment by kRHYME7** [comment]
update what? repo? if theme what is the output for ``` ~/.config/waybar/config.ctl ```

**Comment by pragit-raj-sharma** [comment]
> Update what? Theme? Repo?
> 
> If theme, what is the output for `~/.config/waybar/config.ctl`, I'm pretty sure it won't be overwritten.
> 
> > I made some changes to the modules of waybar they are also overwritten after update.
> 
> If updating the repo then there's no mechanism for that. The only way to manage your version of Hyprdots is to fork it and merge the latest commits. That's the way to manage dot files on git. There's a workaround, though.
> 
> Instead, you can create a separate module file then use `Hyprdots restore config` , follow the instructions on what will happen to your file. This way, you can control what to overwrite/preserve on your dots.
> 
> Here's the link on how you can do that: #863 #913
> 
> BTW there are many queries here on how to do these things, as this is asked many times, (no documentation yet) but it's a good practice that before someone opens an issue they sure have read other issues, or the discussion. Search filter is there to help.
> 
> I'll be adding a guide on how to manage configs soon.

Yeah, I was talking about the repo. Thanks.

**Comment by inevity** [comment]
> @pragit-raj-sharma no, don't do that, you can run `Hyprdots waybar control` then the control file will pop out in vscode. the 2nd column/field is the size. Read more about theming in the hyprdots repo wiki.
> 
> Do not forget to browse documentation (if it exists 😁) https://github.com/prasanthrangan/hyprdots/wiki/Theming#waybar

Where is the Hyprdots binary?
I use the ~/HyDE/Scripts/ install.sh to install the De, not second install method.
waybar bar and text size both too small. 
How?
