### ISSUE TITLE
[Bug]: When i updated the systme i get this 

### ISSUE THREAD

**Issue by ZAAFHachemrachid** [prasanthrangan/hyprdots#929]
## Bug Report
![image](https://github.com/prasanthrangan/hyprdots/assets/117745305/17d5268a-8035-4ad1-bac5-bb56fea6fefa)

### Description
when i updated my system i get this error try to resolve it but no result  
```conf

80 device:epic mouse V1 {
81    sensitivity = -0.5
83 }
```
### Steps to Reproduce

1.  update system  :  `
2. reboot and you have it

### Screenshots
![image](https://github.com/prasanthrangan/hyprdots/assets/117745305/d25aac5a-718e-4283-8b56-3e07450ace2e)
(https://github.com/prasanthrangan/hyprdots/assets/117745305/17d5268a-8035-4ad1-bac5-bb56fea6fefa)

### Environment
Arch 

                            ​ ​​  OS : Arch Linux x86_64 
                            ​​ ​  Kernel : 6.7.5-arch1-1 
                            ​​ ​  Packages : 1525 (pacman) 
                            ​​ ​  Resolution : 1920x1080 
                            ​​ ​  DE : Hyprland 
                            ​​ ​  Terminal : kitty 
                            
                            ​​ ​  CPU : 11th Gen Intel i5-1135G7 (8) @4.200GHz 
                            ​​ ​  GPU : Intel TigerLake-LP GT2 [Iris Xe Graphics] 
                            ​​ ​  GPU Driver : Hewlett-Packard Company TigerLake-LP GT2 [Iris Xe Graphics] [103c:8846] 
                            ​​ ​ ﬙ Memory : 3253MiB / 15680MiB 
```shell
❯ hyprctl version
Hyprland, built from branch main at commit 13d985489788fa5349b3457d6eb1c19bad8f37e9 dirty (xdgpopup: fix UAF because of an invalid listener connection).
Date: Tue Feb 20 19:14:36 2024
Tag: v0.35.0-63-g13d98548
```
```shell
 uname -a
Linux archlinux 6.7.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:33 +0000 x86_64 GNU/Linux
```
### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by kRHYME7** [comment]
Thanks for the heads-up. You're using the hyprland-git therefore you got the latest change from hyprland.

You can either check the hyprland wiki to fix those changes or install the tagged release of hyprland ``` yay -Sy hyprland ```
The repo is following the tagged release to have a slight stability. 

Remove that line or change the syntax into this 

https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs
```

device {
   name = epic mouse V1
    sensitivity = -0.5
}
```


I'll be

**Comment by kRHYME7** [comment]
@ZAAFHachemrachid  By the way, I'm curious if I'm the only one having this rendering issue on latest release? 

![240220_18h57m14s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/53417443/2b240361-5745-4590-a18b-d0bdcfc98c93)
![240220_18h58m04s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/53417443/27fc3b53-c2d1-4e19-a344-391145843d8e)
![240220_18h58m16s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/53417443/97704f9b-dd5c-4c27-84bb-956ed9aa5868)

**Comment by ZAAFHachemrachid** [comment]
@kRHYME7  THX for solution , and for rendering issue just in vms that i run

**Comment by kRHYME7** [comment]
@ZAAFHachemrachid Closing this for now as the owner acknowledge the merge.
