### ISSUE TITLE
Power menu buttons with a strange scale

### ISSUE THREAD

**Issue by jhenrique04** [prasanthrangan/hyprdots#93]
First of all, thanks for the hard work, this really is the best rice for me.

As you can see in the image below, power menu its a little awkward here in my machine:
![image](https://github.com/prasanthrangan/hyprdots/assets/115225048/9fcbf997-8dbe-4122-af00-67d204c22efd)

I'm using only my laptop screen and these are my current settings on .config/hypr/hyprland.conf for the monitor section:
![image](https://github.com/prasanthrangan/hyprdots/assets/115225048/588aa231-5373-4cbd-8d02-bda24cf36177)

I tried other scale values but still the same issue, if you have any idea on how to fix this i would be glad, peace out m8.

**Comment by prasanthrangan** [comment]
Hi, Thank you so much!

this is a known issue, same as #87

to fix this, please adjust font size in ~/.config/wlogout/style.css and padding in ~/.config/hypr/keybindings.conf

```
bind = $mainMod, backspace, exec, wlogout -b 2 -c 0 -r 0 -L 930 -R 930 -T 300 -B 300 --protocol layer-shell # logout menu
```

**Comment by jhenrique04** [comment]
Works like a charm!

I forgot to check resolved issues tab, my bad.

Again, thanks for the work, appreciate it.
