### ISSUE TITLE
Random Black or Noisy screen 

### ISSUE THREAD

**Issue by jenil1122** [prasanthrangan/hyprdots#935]
Random screen noise while normally using hyprland or black screen while locking with WIN + L

**Comment by kRHYME7** [comment]
Output for ``` hyprctl systeminfo ```

**Comment by jenil1122** [comment]
output :
❯ hyprctl systeminfo
Hyprland, built from branch main at commit 86be75dd97b5633b8c0aa6bdcb3346fa871a8480 dirty (events: bring back accidentally nuked preConfigReload).
Date: Tue Feb 20 04:24:15 2024
Tag: v0.35.0-59-g86be75dd

flags: (if any)


System Information:
System name: Linux
Node name: Hyprland
Release: 6.7.5-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:21 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 620 [8086:5916] (rev 02) (prog-if 00 [VGA controller])
00:13.0 Non-VGA unclassified device [0000]: Intel Corporation Sunrise Point-LP Integrated Sensor Hub [8086:9d35] (rev 21)


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

**Comment by jenil1122** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/78353041/e6368742-828b-4029-adcd-8eaf851acb85)

**Comment by kRHYME7** [comment]
Okay I got this problem too! It can be fixed if I use the tagged version of hyprland. ``` yay -Sy hyprland ```. You're using the hyprland-git therefore not all might experience this. This Repo now follows the Tagged release.

**Comment by jenil1122** [comment]
installing Hyprland stable version from yay worked..
