### ISSUE TITLE
Buggy and unwanted keybind?

### ISSUE THREAD

**Issue by gravelord-nito** [prasanthrangan/hyprdots#946]
### Description

This last line in keybinds.conf namely 
```
# Trigger when the switch is turning off
bindl= , switch:on:Lid Switch, exec, swaylock && systemctl suspend
```
causes annoying unwanted actions, specifically when using fn keybinds the system just suspends. Also happens on my wireless keyboard by just pressing the fn key.

### Steps to Reproduce

I'm not sure, it may be a laptop specific or second keyboard problem.

### Expected Behavior
---
### Actual Behavior
---
### Screenshots
---
### Environment

Using fully updated arch linux on a asus tuf laptop.

### Additional Information

I wish you could remove/change this bind for now from default if this happens for others too.

**Comment by kRHYME7** [comment]
Thanks this keybindings has been reported multiple times. I'll try to remove this

**Comment by kRHYME7** [comment]
@gravelord-nito  Resolved
