### ISSUE TITLE
Is overwriting /.config/fish and .zshrc on each update necessary?

### ISSUE THREAD

**Issue by opticblu** [prasanthrangan/hyprdots#947]
It could be just something weird that happened when I forked this repo for my personal setup, but I think I recall that even when I pull this direct from this repo and run the script (to update with latest changes) **_it overwrites the entire .config/fish folder, the functions, completions, variables, everything but the history_** (which is not in that directory thank goodness) as well as .zshrc.

I understand for a first install that's possibly fine and that the script does do backups in the .config/cfg_backups (thank you) and it's no big deal for me to move the backed up configs in case I forget, or push the changes to my fork as necessary.

My concern is, for less experienced users especially, overwriting, or really, deleting environment variables and forcing chsh might cause problems for people who don't know where to look or how to undo these changes.

This isn't necessarily a bug, just a polite suggestion.

Thanks again for your hard work, hyprdots is awesome!

**Comment by kRHYME7** [comment]
Hello I think we do not have Any update mechanism  here. It is  restore  which restores the owners configuration to your system. I wrote something on ``` hyprdots-ctl ```. Try to invoke ``` Hyprdots update ``` then ``` Hyprdots upgrade ```. The command will guide you on how to manage it. You should modify the configuration list first.

**Comment by opticblu** [comment]
Yikes, I actually forgot that hyprdots-ctl could update-- got used to using my fork and hyprdots-ctl slipped my mind


Thank you for your reply and the reminder :)
