### ISSUE TITLE
Not allowing to login and the cursor is displayed as a cross

### ISSUE THREAD

**Issue by b0tish** [prasanthrangan/hyprdots#949]
I did a fresh minimal arch install and installed the hyprdots as shown in the README.md.

But after completing the hyprdots installation and rebooting the system , I am stuck at the login menu. At the login menu, I cannot type anything and the mouse turns into a cross which doesn't let me click anything either.

![helpthis](https://github.com/prasanthrangan/hyprdots/assets/118423577/6d2a0e62-d990-41ad-9d08-8c14a8b4ed0c)

Although the password box is highlighted, I cannot type in it either. 

Hope you could fix this problem.

**Comment by kRHYME7** [comment]
Navigate to  the tty by pressing ``` ctrl + alt + F3 ```

provide the output for ``` hyprctl systeminfo ```. an image is fine.

Also try to run Hyprland in the terminal.

Browse the issues and discussions as this is very common issue. Read archwiki also read hyprland wiki.

**Comment by b0tish** [comment]
For the hyprctl systeminfo I got the following output:

![Screenshot_2024-02-24-10-19-05-666_com.instagram.android~2.jpg](https://github.com/prasanthrangan/hyprdots/assets/118423577/4d8e4b1e-1c1e-44ba-921e-f6f3caaca1b5)

**Comment by kRHYME7** [comment]
### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: [e.g., ArchLinux, EndeavourOS]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

**Comment by b0tish** [comment]
I am using Arch Linux Minimal Install.
And I am installing it on the main hardware but dual booting with Windows 10.

No I dont have Nvidia and i can also confirm that i was able to use this same config before. I had to remove it and now i am trying to use it again.

![Screenshot_2024-02-24-10-51-19-621_com.instagram.android~2.jpg](https://github.com/prasanthrangan/hyprdots/assets/118423577/1ba558cf-54a8-45e2-83d2-7376895d6937)

For the uname and hyprctl version.

**Comment by hasharmujahid** [comment]
Same thing is happening to me. When i enter password SDDM gets stuck. Only way out is to forcefully shut down. 

System Info.

i5 12450H
Nvidia - 1650 

I have installed nvidia proprietory drivers using  nvidia-dkms  , nvidia-utills.

**Comment by kRHYME7** [comment]
> I have installed nvidia proprietory drivers using nvidia-dkms , nvidia-utills.

Try the v535 driver of nvidia

``` yay -S nvidia-535xx-dkms nvidia-535xx-utils    ```

**Comment by hasharmujahid** [comment]
I logged in through the command line and launched Hyprland. After that run the command Hyprdots update , Hypardots install, I dont know what it did now its working fine again.

**Comment by kRHYME7** [comment]
@b0tish can you try to run Hyprland using the default config file? 

Here's the command
```  Hyprland -c  /usr/share/hyprland/hyprland.conf ```

**Comment by b0tish** [comment]
With the default config i am stuck at the default image and nothing works either.


I cant use any keybindings nor open a terminal. I get stuck at the intro picture.

**Comment by kRHYME7** [comment]
Can you provide logs?
