### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by CokoJl1** [prasanthrangan/hyprdots#95]
The error occurred when executing the -S command in the file install_pkg.sh , line 67: command not found. This message appeared after the file was executed install.sh . Please help me. I have already tried to perform all the necessary actions manually, but everything works except the themes. I'm new to Hyprland and really want to get this configuration, it's so beautiful, but for some reason I can't install it the usual way. The only thing I use is Manjaro, but that probably has nothing to do with it.

**Comment by prasanthrangan** [comment]
Hi, this should be fixed, please pull the latest change and try again.

**Comment by prasanthrangan** [comment]
fixed in commit 5fe39c0
