### ISSUE TITLE
time not displaying on waybar

### ISSUE THREAD

**Issue by sugeodj** [prasanthrangan/hyprdots#96]
install went smoothly however there is a blank section on the waybar that looks like wheere time is supposed to be displayed but is blank. I have poked around the config files but are unable to fix the issue.

**Comment by prasanthrangan** [comment]
Hi, can you please share screenshot?

**Comment by sugeodj** [comment]
![20230822_17h26m33s_grim](https://github.com/prasanthrangan/hyprdots/assets/135717890/64411323-efb6-47ef-a375-4b70ba4c9a8f)

mayb im mistaken but i just thought it looks like where the time would be placed but has only ever been blank

**Comment by prasanthrangan** [comment]
> mayb im mistaken but in the bottom left corner, i just thought it looks like where the time would be placed but has only ever been blank

which version are you using? I think you have `waybar` package installed,  not the `waybar-hyprland-git` version.. this aur package is currently flagged out of date, so you try updating it when its working.

**Comment by Newer1107** [comment]
Hello, this happened with me too when I started using hyprland, for this to work, you need to set your timezone properly using 
`timedatectl set-timezone Zone/SubZone`
To list available zones:
`timedatectl list-timezones`

**Comment by sugeodj** [comment]
thanks this fixed the issue for me
