### ISSUE TITLE
[Feature Request]: A way to restore it all

### ISSUE THREAD

**Issue by Schwarzeisc00l** [prasanthrangan/hyprdots#961]
### Description

I can't get used to all of this new things. I want to restore my old config and undo everything the script did. Is that possible?

**Comment by kRHYME7** [comment]
No. But some configs are backed up inside ```  ~/.config/cfg_backup* ```

**Comment by opticblu** [comment]
> ## Feature Request
> ### Description
> I can't get used to all of this new things. I want to restore my old config and undo everything the script did. Is that possible?

Use something like chezmoi in the future

You're using someone else's dotfiles that they're sharing with you

That would be like deleting all your old music files because someone shared their music collection with you; that would be on you, not the person who so graciously shared with you.
