### ISSUE TITLE
[Quesiton] How to disable transparency in apps?

### ISSUE THREAD

**Issue by lucasquin** [prasanthrangan/hyprdots#963]
My terminal, Firefox, Discord and lot apps have transparency, how to disable? 

Sorry for my bad english, is not my language

**Comment by RookiexCookie** [comment]
you mean less opacity? like you can kinda see through apps
you can change them in `~/.config/hypr/windowrules.conf`
just comment out the lines where you see the name of the app that you dont want to have that

**Comment by lucasquin** [comment]
Thank you, this solve my question
