### ISSUE TITLE
[Docs]: How do I upgrade without losing my configs?

### ISSUE THREAD

**Issue by Haraven** [prasanthrangan/hyprdots#966]
### Description

I would like to keep Hyprdots up to date with the latest Git changes, but I don't understand how to properly keep my configuration settings after an upgrade. I have read the wiki, but it seems outdated? And even if up to date, personally I don't understand how to upgrade and keep my configs, or at least what configs get overwritten when upgrading. 

Maybe I'm misunderstanding the purpose of Hyprdots - is it meant to be installed as a starting point and then left alone while we configure our systems to our liking?

### Current Documentation

[This section](https://github.com/prasanthrangan/hyprdots/wiki/Installation#restoring-configs) on restoring configs after an upgrade describes the structure of `restore_cfg.lst`, but the actual file contents look like this:

```
N|Y|${HOME}|.zshrc .p10k.zsh|zsh oh-my-zsh-git zsh-theme-powerlevel10k pokemon-colorscripts-git
Y|Y|${HOME}/.config/Code/User|settings.json|visual-studio-code-bin
Y|Y|${HOME}/.config|dunst|dunst
Y|Y|${HOME}/.config|fish|fish
Y|Y|${HOME}/.config/hypr|animations.conf hyprland.conf theme.ctl windowrules.conf scripts themes wallbash|hyprland
N|Y|${HOME}/.config/hypr|keybindings.conf monitors.conf userprefs.conf|hyprland
N|Y|${HOME}/.config/hypr|nvidia.conf|hyprland nvidia-utils
Y|Y|${HOME}/.config|kitty|kitty
# ...
```

I don't understand what the 2 Y/N's on each line are supposed to mean. I also don't understand whether this file is used to restore _my_ configs or the default Hyprdots ones. Also, maybe I'm more dense, but I don't understand how to actually use or modify this file.

In the README file, in [the section on updating](https://github.com/prasanthrangan/hyprdots?tab=readme-ov-file#updating), it's mentioned that overwritten configurations `can be recovered in ~/.config/cfg_backups`. Last week, after pulling the latest changes and running the update procedure via the [Hyprdots Ctl](https://github.com/kRHYME7/Hyprdots-ctl) (command: `Hyprdots update`), I lost most of my configuration settings. On top of that, even though `~/.config/cfg_backups` had a folder with the timestamp of the update, the folder itself was empty.

What I want is to update e.g., the scripts and maybe pull additional themes and config options (e.g., Waybar modes) _without_ losing my current settings. I don't know how to do this from the docs. Maybe I'm too much of a beginner at this -  I just don't understand the docs on updating.

### Proposed Documentation

Please document either one of:
- exactly which configs are lost when updating Hyprdots
- how to properly update and keep personal configs

### Additional Information

N/A

**Comment by kRHYME7** [comment]
>[This section](https://github.com/prasanthrangan/hyprdots/wiki/Installation#restoring-configs) on restoring configs after an upgrade describes the structure of restore_cfg.lst, but the actual file contents look like this: 

It will restore configs from the repository. That's why it is called "restore". The current implementation will always populate all configurations from the Github Repo thinking that the repo is the fork of hyprdots where the user manages the configs using git. (I think I answered a similar question somewhere, I'll link it here later. )


> I don't understand what the 2 Y/N's on each line are supposed to mean. I also don't understand whether this file is used to restore my configs or the default Hyprdots ones. Also, maybe I'm more dense, but I don't understand how to actually use or modify this file.

Here
### https://github.com/kRHYME7/Hyprdots-ctl/issues/11#issuecomment-1913179843

To be clear, it will restore the configurations from the repository. So if user had personal configs,user should fork the repository and learn git. 

 
=======================================================



About the ``` Hyprdots-ctl ``` it is a different implementation. This implementation manages the files or directories one by one. 
The control file is in here
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/3710ca5f-b387-46dd-8c58-af604ae9a6c3)


``` Hyprdots update  ``` fetch the repository and stash all uncommitted changes

> Last week, after pulling the latest changes and running the update procedure via the [Hyprdots Ctl](https://github.com/kRHYME7/Hyprdots-ctl) (command: Hyprdots update), I lost most of my configuration settings. On top of that, even though ~/.config/cfg_backups had a folder with the timestamp of the update, the folder itself was empty.

I will admit. This is totally my fault as I made a mistake of not adding the backup in all flags. 
I updated it recently and should be fixed.

Also, I advise that use ``` Hyprdots backup all ``` first just to be sure to back up all configs. 
then run ``` Hyprdots upgrade ``` to populate the configurations.
See this. 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a2074f57-7e3e-42b6-8cc7-b709b8b31e8e)



I'll try to make a mega thread, so I can share how to manage configs, but I am afraid my English is poor.

**Comment by kRHYME7** [comment]
To truly update configs from repo without altering personal configs is to use git.

**Comment by Haraven** [comment]
Ah, so the answer is that I should fork the Hyprdots repo and use it to set up my own dotfiles configurations. I've been wondering how to back up my configs in a Git repo, so I guess now's a good time to learn how to do it.

**Comment by kRHYME7** [comment]
> Ah, so the answer is that I should fork the Hyprdots repo and use it to set up my own dotfiles configurations. I've been wondering how to back up my configs in a Git repo, so I guess now's a good time to learn how to do it.


Perfect!  I'll add more note here. 

This repo stores dotfiles of the owner, not a full suite DESKTOP ENVIRONMENT.  (same as other repos hosting there personal configurations we call dotfiles ) 

On DEs, user can save their "personal configurations" in example ```  /.config/*```  .  When DE like gnone/KDE updates something, files from your $HOME/ should/will not be touch by the DE. therefore leaving your configs intact. (unless major changes on configuration syntax)

Now we are talking about sharing "personal configuration" alone, therefore any updates from these configs will change the whole repo and hence if a user just blindly copied the repos "personal configuration" then it should mess up their $HOME/  dir. It is also not good to  make a configuration file for configuration file right? doesn't make any sense. More likely dotfiles should be copied with intervention and knowledge on what the configuration does as this is "personal configurations" we are copying.

**Comment by Enigma1309** [comment]
Also remember if you are configuring something, say waybarconfgen.sh you modified some of it's lines and the upstream repo come with a change to that specific script/file, then your some of the other scripts might break due to dependendence on the new waybarconfgen.sh config.

**Comment by Enigma1309** [comment]
The best practice would be to keep active on the repo and check the commits few times a day, also you have an option to not to update if you think the change isn't gonna affect how you use your system

**Comment by Enigma1309** [comment]
>  I've been wondering how to back up my configs in a Git repo.

There a a few good practice if you are considering backing up your repo 

- Git Bare Repo (Recommended), search yt for tutorial
- Using Stow (quite advanced)
- Symlinking your all files to a git repo (Tedious, it Works but the better alternative would be git Bare)
- Manually uploading you files github (Not Recoomended)

**Comment by Skerse** [comment]
My way of handling this is pretty easy, all i really do is stash my changes, pull the latest changes from this repository, then load back my stashed changes, all this can be done in vscode very easily than if there are any merge conflicts vscode has a conflict resolver editing tool for that. After you run `Hyprdots restore defaults` and you'll be up to date without loosing your changes.

**Comment by Haraven** [comment]
After a few failed repo forks, I ended up getting my personal dotfiles repo up and running! I've tested it in a VM and configs get copied over very well. I also decided to run the Hyprdots `install.sh -r` script with my personal config, on my working PC, to see if everything still stays configured like I want it.

I'm pretty happy with how things are. I do have a few issues I'm not sure how to address right now:
- dunst doesn't seem to change colors unless i edit `/etc/dunst/dunstrc`, even if I update all the settings from `~/.config/dunst/`
- Dolphin for some reason defaults to using black text instead of white and I have to forcefully reapply my settings in `qt5ct` and `qt6ct` so the text gets displayed correctly
- not entirely sure how to make sure my preferred nerd font, Noto Nerd Font, gets installed on a fresh setup. I wanted to create an archive under `Source/arcs` and pass it to `Scripts/restore_fnt.lst`, but the tarball is too big and I can't push it to GitHub.
- using a custom GRUB theme is a bit more tedious to set up than I'd like - the `Scripts/install_pre.sh` script has 2 hardcoded GRUB themes and you need to manually edit the script to add your own GRUB theme (fetched from a tarball in `Source/arcs`)

I'll keep hammering away at these issues, but for now I'm verry happy that:
1) I have a rough backup up of my dotfiles!
2) I can finally update Hyprdots and keep (most of) my settings

If you guys have any pointers for solving the above issues, I'd appreciate it.

Either way, thanks very much for your help so far!

**Comment by kRHYME7** [comment]
@Haraven 

> dunst doesn't seem to change colors unless I edit /etc/dunst/dunstrc, even if I update all the settings from ~/.config/dunst/. Something strange happens, whereby the configs for the different kinds of notifications (urgent, low, normal) get duplicated /etc/dunst/dunstrc. Probably I'm configuring it wrong

+ edit this ``` dunst.conf ```. dunstrc will be overwritten on the fly upon wallpaper/theme change.

> not entirely sure how to make sure my preferred nerd font, Noto Nerd Font, gets installed on a fresh setup. I wanted to create an archive under Source/arcs and pass it to Scripts/restore_fnt.lst, but the tarball is too big and I can't push it to GitHub.

+ install it using the AUR https://archlinux.org/packages/extra/any/ttf-noto-nerd/ . add ``` ttf-noto-nerd  ``` inside ``` custom_app.lst

> using a custom GRUB theme is a bit more tedious to set up than I'd like - the Scripts/install_pre.sh script has 2 hardcoded GRUB themes and you need to manually edit the script to add your own GRUB theme (fetched from a tarball in Source/arcs)


+ Yeah, How abut doing it as post install? Grub customizer.


> for some reason, after installing the latest Hyprdots updates, my cursor disappears when I hover over the desktop - it shows up fine when it's hovering over Waybar, the terminal, or other apps, but it disappears when it's just the desktop. This sounds like a Hyprland config, but I'm not sure where to change this


+ if nvidia set the XCURSOR see hyprland wiki for that. 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/beef6f8f-721e-46b0-978e-a9e8bf266207)
if not effective, it's hyprland

> Dolphin for some reason defaults to using black text instead of white, even when configured otherwise. I have to forcefully reapply my settings using qt5ct and qt6ct so the text gets displayed correctly


Dunno... but dolphin theme is bind to each theme also wallbash 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/397d7f30-eb1b-4d45-a2d4-2f64dee911ab)
kvantum
