### ISSUE TITLE
themes.conf error

### ISSUE THREAD

**Issue by Gedankenn** [prasanthrangan/hyprdots#97]
Applying the latest commit i had an issue with waybar and nvidia, im using hyprland-nvidia and the themes.conf has a new layout that isnt updated for hyprland-nvidia. i solved by manually going back to the old themes.conf file, i think the problem actually is with hyprland-nivida repo that isnt updated in aur. anyone had the same problem

**Comment by prasanthrangan** [comment]
I'm using hyprland nvidia version as well, but the new theme.conf is working fine for me

**Comment by Gedankenn** [comment]
wich one are you using? hyprland-nvidia or hyprland-nivida-git ? perhaps the git version is more updated.
By the way, loving your dots, really thanks for the repo. 

As a curiosity, im using your dots inside a VM with passtrhough from gpu and nvme. all running perfectly.

![image](https://github.com/prasanthrangan/hyprdots/assets/13906812/683dbf91-5635-4e4c-9c58-43a455f5534e)

**Comment by prasanthrangan** [comment]
Thank you so much, means a lot!

> wich one are you using? hyprland-nvidia or hyprland-nivida-git ? perhaps the git version is more updated.

yup, i'm using the git version `hyprland-nivida-git`.

> As a curiosity, im using your dots inside a VM with passtrhough from gpu and nvme. all running perfectly.

Oh cool, I never tried this in VM, glad it works... I don't know how to passthrough my GPU to VM, so i'll have to figure that out first :)

**Comment by Gedankenn** [comment]
Just to give an end to the thread.

Instaling `hyprland-nvidia-git`solved the issue.

**Comment by prasanthrangan** [comment]
> Instaling `hyprland-nvidia-git`solved the issue.

cool, i'll close this!
