### ISSUE TITLE
Login screen changed to sddm default.

### ISSUE THREAD

**Issue by Radrahil** [prasanthrangan/hyprdots#973]
The login screen has changed to the sddm default. How do I fix this?

**Comment by SpaceLarry14** [comment]
I can confirm the latest updates did the same thing to me

**Comment by kRHYME7** [comment]
Dupe #972

**Comment by kRHYME7** [comment]
You can monitor the fist raised issue #972,  as this is duplicate of #972. Re-open this if necessary.
