### ISSUE TITLE
[Feature Request]: Use Hyprlock as an alternative screen locking utility. 

### ISSUE THREAD

**Issue by LunasShade** [prasanthrangan/hyprdots#977]
## Feature Request

GitHub repositorie: https://github.com/hyprwm/hyprlock

### Description

Use Hyprlock as an alternative screen locking utility. 

### Use Case

To have an equally simple login option in addition to the existing one that you can easily change in config.

### Additional Information

Hyprlock is Hyprland's simple, yet multi-threaded and GPU-accelerated screen locking utility.

**Comment by kRHYME7** [comment]
Dupe  #967
