### ISSUE TITLE
cannot connect to bluetooth device: "confirm value for authentication"

### ISSUE THREAD

**Issue by stove-jeebs** [prasanthrangan/hyprdots#98]
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/288a4469-cb0d-42e3-89c9-eda6efb5b51e)

How do I connect? I don't see the "confirm" and "deny" buttons like in the photo below

![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/532a7de5-46f7-4b6c-9f65-4c0cffb852cf)

how can I fix this? If not, Can I disable this authentication somehow?

**Comment by prasanthrangan** [comment]
Hi, have you tried middle click on the notification to accept it?
Also, you can try marking that device as trusted from blueman applet.

**Comment by stove-jeebs** [comment]
I've tried both but it would still ask to "Confirm value for authentication".

**Comment by stove-jeebs** [comment]
I've tried both but it would still ask to "Confirm value for authentication".

**Comment by stove-jeebs** [comment]
I switched back to Windows, and I would also need to go through a similar step of auauthentication, except I have the option to choose whether I want to accept or reject the authentication

**Comment by stove-jeebs** [comment]
this is what I get when I try to connect with `bluetoothctl`

```
Agent registered
[CHG] Controller 8C:C6:81:94:23:E2 Discovering: yes
[NEW] Device 58:FC:C6:A8:47:50 TOZO-T6
[CHG] Device 58:FC:C6:A8:47:50 RSSI is nil
[CHG] Controller 8C:C6:81:94:23:E2 Discovering: no
[bluetooth]# connect 58:FC:C6:A8:47:50
Attempting to connect to 58:FC:C6:A8:47:50
[CHG] Device 58:FC:C6:A8:47:50 Connected: yes
[CHG] Device 58:FC:C6:A8:47:50 Modalias: bluetooth:v0094p0123d1000
[CHG] Device 58:FC:C6:A8:47:50 UUIDs: 00000000-0000-0000-0099-aabbccddeeff
[CHG] Device 58:FC:C6:A8:47:50 UUIDs: 00001108-0000-1000-8000-00805f9b34fb
[CHG] Device 58:FC:C6:A8:47:50 UUIDs: 0000110b-0000-1000-8000-00805f9b34fb
[CHG] Device 58:FC:C6:A8:47:50 UUIDs: 0000110c-0000-1000-8000-00805f9b34fb
[CHG] Device 58:FC:C6:A8:47:50 UUIDs: 0000110e-0000-1000-8000-00805f9b34fb
[CHG] Device 58:FC:C6:A8:47:50 UUIDs: 0000111e-0000-1000-8000-00805f9b34fb
[CHG] Device 58:FC:C6:A8:47:50 UUIDs: 00001200-0000-1000-8000-00805f9b34fb
[CHG] Device 58:FC:C6:A8:47:50 ServicesResolved: yes
[CHG] Device 58:FC:C6:A8:47:50 ServicesResolved: no
Failed to connect: org.bluez.Error.Failed br-connection-canceled
[CHG] Device 58:FC:C6:A8:47:50 Connected: no
[CHG] Device 58:FC:C6:A8:47:50 Connected: yes
[CHG] Device 58:FC:C6:A8:47:50 Connected: no
[DEL] Device 58:FC:C6:A8:47:50 TOZO-T6
```

**Comment by prasanthrangan** [comment]
hmm.. I never had authentication request once I add it as trusted device... does it pair with other devices? or does this TOZO-T6 device pair correctly with you phone?

**Comment by stove-jeebs** [comment]
Yes, it does connect with my phone. It shows me a paring request every time which I can choose to pair or cancel

**Comment by stove-jeebs** [comment]
I tried to set middle click to open context menu instead but still nothing pops up

**Comment by Gedankenn** [comment]
i had this issue, its a problem with the bluetoothclt. running it and running some commands solved the issue for me.

run bluetoothclt, remove the device, add it to thrusted devices and try again, for me it solved the issue.

**Comment by prasanthrangan** [comment]
I did always add it as trusted device, and i never got the authentication prompt... I'll try pairing some other devices.

**Comment by stove-jeebs** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/d8a534f9-f777-4156-9d51-d40b93f01008)

**Comment by prasanthrangan** [comment]
I get the same error, unable to pair when it asks for authentication:

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/aabe83a3-df90-4bca-be83-552a3deaaf75)

**Comment by stove-jeebs** [comment]
in case anyone encounters the same problem you will have to pair and connect using bluetoothctl. In my case, I didn't understand the difference between pairing and connecting haha... Turns out I just have to pair and quickly use the connect command before it times out

**Comment by stove-jeebs** [comment]
so I managed to open the context menu by adding this line in ~/.config/dunst/dunstrc:

![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/41197fa1-8322-41f9-9f95-72811be7dcb9)

this is because I realized that dunst uses dmenu by default instead of rofi
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/69eb22da-903a-4a39-883d-c8f1d98911d3)

the problem is that even though the context menu successfully opens I would still fail to pair and connect to my bluetooth device
![image](https://github.com/prasanthrangan/hyprdots/assets/67490238/0c332bd4-98ee-4ad3-945f-fb7aa5cdd3ae)

**Comment by stove-jeebs** [comment]
UPDATE: nvm I have successfully connected to my device by adding it as "trusted" first and then accepting the authentication in the rofi context menu
