### ISSUE TITLE
[Bug]: create_cache.sh broken

### ISSUE THREAD

**Issue by itsmenewbie03** [prasanthrangan/hyprdots#983]
### Description
`./install.sh -r` stops and gives the following error
```shell
./create_cache.sh: line 156: code: command not found
```

### Steps to Reproduce

I followed the updating guide in the README.md
```shell
cd ~/Hyprdots/Scripts
git pull
./install.sh -r
```

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro:  `EndeavourOS`
- Linux Version: `Linux dadsgift 6.7.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:31:48 +0000 x86_64 GNU/Linux`
- Hyprland Version:
```shell
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0
```
- Installation Environment: On The Main Hardware

**Comment by kRHYME7** [comment]
did you ``` git pull ```  the changes ?

**Comment by itsmenewbie03** [comment]
> did you git pull the changes ?

yes, i pulled the changes.

> And this error seemed you uninstalled your vscode.

yes i don't have vscode #646 

I commented the following lines and it worked
![image](https://github.com/prasanthrangan/hyprdots/assets/89230263/47a48c3b-b652-4f3f-bdb1-fc25ca3903f3)

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/2c4d8f31-f6ee-4af4-b0ca-94b40905b003)

Or patch this https://github.com/prasanthrangan/hyprdots/pull/984

**Comment by itsmenewbie03** [comment]
Thanks.
