### ISSUE TITLE
[Bug]: Installation stuck on Restoring part

### ISSUE THREAD

**Issue by 4L33T** [prasanthrangan/hyprdots#986]
### Description

I ran the install script and everything seems to work fine until it reaches /.local/share/kxmlgui5. I've waited for 20 minutes with no response and tried again and with same result of being stuck at the exact same instance.

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/70110149/92b3bb04-15a0-40e4-93ae-1da990f6cd49)

### Environment

- Linux Distro: ArchLinux
- Installation Environment: On The Main Hardware
- Laptop Model: Legion Pro 7i Gen 8 Intel (16″) with RTX 4090

### Additional Information

I used archinstall for my ArchLinux installation and noticed that it just gets stuck during the pre install stage where it's "configurating grub" so I switched to Systemd and now I'm stuck during the restore stage. This is probably a seperate issue not related to this though.

**Comment by kRHYME7** [comment]
click [ENTER] and wait?

**Comment by 4L33T** [comment]
Pressing [ENTER] only moves the blinking cursor to a new line.
I'm getting this when runninng `bash -x ./install.sh`
![image](https://github.com/prasanthrangan/hyprdots/assets/70110149/b62cbfb1-fe21-48b0-82be-4508ba539dd8)


> Press [ENTER] and wait?
> 
> Or run the whole install script with debugging. `bash -x ./install.sh` to see what is the last process being executed.

**Comment by kRHYME7** [comment]
When it's stuck can you cancel the script? Or the system needs to reboot?

**Comment by 4L33T** [comment]
The script is stuck and I can't cancel it so I have to reboot each time. I've tried a fresh install with the same results.

**Comment by kRHYME7** [comment]
Is your Hard drive still healthy? I can only experience this when testing arch + hyprland on a USB flash drive or older hard drive.  I'ts the hard drive that is loose or something.

**Comment by 4L33T** [comment]
Wow, thanks! I tested with a seperate hard drive and it suddenly works. I'll close this issue now.
