### ISSUE TITLE
[Bug]: Random shutdowns (not sure where the problem lies though)

### ISSUE THREAD

**Issue by H1manshu-Soni** [prasanthrangan/hyprdots#991]
### Description

I am not exactly sure if its related to these dots but I have been facing random shutdowns whenever.
Hard to reproduce at will, it just happens when it feels like, sometimes upon boot sometime out of no where.

### Environment

- Linux Distro: ArchLinux
 
- Linux Version, output of `uname -a`: Linux Saturday 6.7.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:31:48 +0000 x86_64 GNU/Linux

- Hyprland Version, output of `hyprctl version`:Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

- Installation Environment: On The Main Hardware

### Additional Information

If more people face this issue then please comment on this issue I will try to grab some logs (if I can).

**Comment by kRHYME7** [comment]
Yow, hi! It also happens when you press something on keyboard? 
Can you comment out this line? 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/1272312a-c3ff-4138-82f1-75e76458ba39)
