### ISSUE TITLE
SDDM not displaying layout anymore after recent SDDM github update.

### ISSUE THREAD

**Issue by TNitroo** [prasanthrangan/hyprdots#995]
SDDM not displaying layout anymore after recent SDDM update on github from 2 days ago.

Well, sadly, I have no idea how I could make it work again, so that's why I'm reporting it, I'm pretty sure there are plenty of other people that are still learning linux and how things go here.

1. just either do a clean install or do git pull and the config will not work anymore. (tried it on 3 other VMs just to make sure I wasn't just stupid.

[What did you expect to happen?]:
to work just like it did before 5 days ago.

[What actually happened?]:
Default hyprland login gets shown

**Comment by cprzytocki** [comment]
seems like an issue with the latest updates. Check the comments on https://aur.archlinux.org/packages/sddm-git

I checked out an older commit from the repo and ran `makepkg -si` and it's working again

**Comment by brmoretti** [comment]
My lockscreen changed to the default SDDM's after the update. I used Timeshift to roll back and it's ok now.

**Comment by Skerse** [comment]
I was wondering if we want to switch from not using the git version of sddm to using the release versions in the official package repos. That's what i do and it works perfectly fine. Same with a lot of other git packages this repo installs by default.

**Comment by se7en-x230** [comment]
That was my question if there is a reason behind the use of the git version(s). If the "official" package works as well why not use that as a default

**Comment by kRHYME7** [comment]
Yeah, maybe it's better to use the stable release. But can someone confirm if this update/changes is official and will be available on the next release of ssdm? (If so, we should still adjust our config soon.)

**Comment by TNitroo** [comment]
> seems like an issue with the latest updates. Check the comments on https://aur.archlinux.org/packages/sddm-git
> 
> I checked out an older commit from the repo and ran `makepkg -si` and it's working again

well, now looking at the github page, no wonder it's not working now. They must have made huge changes, because the 0.20.0 update was in june, so more than half a year ago.

**Comment by pragit-raj-sharma** [comment]
install `sddm` and remove `sddm-git`.

**Comment by prasanthrangan** [comment]
So i did update and broke the sddm theme...

the sddm theme based on qt5 version are run by `sddm-greeter` which is now replaced with `sddm-greeter-qt6`. A metadata entry is required to use the qt6 greeter -
```
❯ cat /usr/share/sddm/themes/Candy/metadata.desktop
[SddmGreeterTheme]
QtVersion=6
```

But unfortunately the themes use `QtGraphicalEffects` for blur and shader effects that seems to be only available in `qt5-graphicaleffects` and I'm unable to find this module for qt6 :(

**Comment by Liangyiu** [comment]
This is how I fixed it for now:
_(taken from the [sddm github installation wiki](https://github.com/sddm/sddm/wiki/Installation))_

1. removed the sddm-git
`sudo pacman -R sddm-git`
2. cloned, build & installed from a releases branch
`git clone --depth=1 --branch=v0.20.0 https://github.com/sddm/sddm.git`
`cd sddm`
`mkdir build`
`cd build`
`cmake .. -DCMAKE_INSTALL_PREFIX=/usr`
`make`
`sudo make install`

**Comment by TNitroo** [comment]
> So i did update and broke the sddm theme...
> 
> the sddm theme based on qt5 version are run by `sddm-greeter` which is now replaced with `sddm-greeter-qt6`. A metadata entry is required to use the qt6 greeter -
> 
> ```
> ❯ cat /usr/share/sddm/themes/Candy/metadata.desktop
> [SddmGreeterTheme]
> QtVersion=6
> ```
> 
> But unfortunately the themes use `QtGraphicalEffects` module for blur and shader effects that seems to be only available in `qt5-graphicaleffects` and I'm unable to find this module for qt6 :(

It's fine, I fixed it for myself. All I did was delete sddm-git and install sddm through yay from AUR. Took me about 2 hours to figure out how I should be doing this, because first I wanted to try roll back to the older version, but AUR didn't let me roll back to version 0.20.0-4 for sddm-git. But thanks for looking for a solution!
I don't see any reason now to update my sddm :kek:

**Comment by eyyyyyyy3** [comment]
This is just a temporary solution tho

**Comment by Kai-Johnstone** [comment]
I'm using sddm 0.20.0-4 and the issue still persists?

**Comment by Megalomaniak** [comment]
> If the "official" package works as well why not use that as a default

Used to be bugged. Like, badly bugged. Black screen after boot up bad. But if that has been resolved then yeah.

**Comment by kRHYME7** [comment]
The latest sddm update requires us to change our theme configuration or maybe how we approach it.

It would be appreciated if someone can make a PR or point us to the way we could configure sddm 0.21. I am reading some sddm-themes but all are using the older implementation. 

For now reverting to the nearest sddm v0.20 is enough to fix breaking changes.

Thanks!

**Comment by Skerse** [comment]
Just downloaded the latest SSDM package from the testing repo then installed it and can confirm SDDM 0.21.0 will work perfectly fine when it comes to main non-testing repos! We don't need to change anything in our repo to make it work, [qt5-wayland](https://archlinux.org/packages/extra/x86_64/qt5-wayland/) depends on [qt5-declarative](https://archlinux.org/packages/extra/x86_64/qt5-declarative/) so it should be installed on everyone's systems.
