### ISSUE TITLE
[Bug]: Using scrollwheel on rofi skipping items

### ISSUE THREAD

**Issue by lapaii** [prasanthrangan/hyprdots#996]
### Description

Using scroll wheel on mouse skips every other item in application select

### Steps to Reproduce

1. Open rofi with ```Super```  + ```A``` 
2. Scroll using mouse scroll wheel
3. See that every other option is getting skipped

### Expected Behavior

To scroll the list one item at a time

### Actual Behavior

Scrolls list but skips every other item

### Video

https://github.com/prasanthrangan/hyprdots/assets/96551682/850616dd-e640-4732-b0a2-6921bb4c46e1

### Environment

- Linux Distro: Arch Linux
- Linux Version: ```Linux lapaiipc 6.7.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:31:48 +0000 x86_64 GNU/Linux```
- Hyprland Version: v0.35.0 (no flags)
- Installation Environment: main hardware

### Additional Information

using Logitech G PRO Wireless mouse

**Comment by kRHYME7** [comment]
Halu @lapaii when did this happen? after a recent update?

**Comment by lapaii** [comment]
@kRHYME7 i just installed for the first time < 1 hr ago so don't know when the issue first started but its been happening since install

**Comment by kRHYME7** [comment]
Okiii thanks! I'll try to check this.

**Comment by Enigma1309** [comment]
@kRHYME7 this was there for a long time, i thought this was intentional to scroll more items at once, didn't checked much after that

**Comment by Skerse** [comment]
Yeah it's always been like that, i wonder if there is a way to reduce it to 1.

**Comment by kRHYME7** [comment]
Raised an issue recently. https://github.com/lbonn/rofi/issues/120

**Comment by kRHYME7** [comment]
Fixed on this commit https://github.com/lbonn/rofi/commit/37b8e9fb990db1a6b3b144e3cba4be7741a305b8

 please update your rofi ``` yay -Sy rofi-lbonn-wayland-git ``` 


* for chaotic AUR users, please compile it using the AUR first, as chaotic AUR are hours late. 😁
